### PR TITLE
nb selection highlighting -- #200406

### LINKED ISSUE #200406: Notebook cell editor -- selection highlighting doesn't work
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When `"editor.selectionHighlight"` is set, in non-notebook windows, selecting a block of text will highlight matching blocks elsewhere in the document.

I seem to recall this used to be true in jupyter notebook cells as well, but it is no longer the case (for me at least). Here's an SO post from a couple years back demonstrating that selection highlighting was indeed once working in notebook cells:
https://stackoverflow.com/questions/68527700/ipynb-highlight-other-occurrences-of-selected-variable-in-vscode-ipython-notebo).

This is independent of whether the kernel is local or remote, or any other settings that I have tried. I observe it on two different machines (one a Mac connected via the remote extension to a linux box; another a Mac editing locally -- and there is no settings sync between them or anything so these are ~independent configs...)

Unsure of whether this is a core vscode issue, or a vscode-jupyter one.

### VS Code Version

Version: 1.84.2 (Universal) Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e Date: 2023-11-09T10:52:33.687Z Electron: 25.9.2 ElectronBuildId: 24603566 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Darwin arm64 23.1.0

### Jupyter Extension Version

v2023.10.1100000000

### Jupyter logs

_No response_

### Coding Language and Runtime Version

_No response_

### Language Extension Version (if applicable)

_No response_

### Anaconda Version (if applicable)

_No response_

### Running Jupyter locally or remotely?

None

### PR DESCRIPTION
**Pull request by Yoyokrazy**
Fixes: #200406

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/browser/contrib/multicursor/notebookSelectionHighlight.ts [hunk 1]
```diff
@@ -71,19 +70,20 @@ class NotebookSelectionHighlighter extends Disposable implements INotebookEditor
 					return;
 				}
 
-				this.clearNotebookSelectionDecorations();
-				this.runDelayer.trigger(() => { this._update(); });
-
+				if (this.notebookEditor.hasModel()) {
+					this.clearNotebookSelectionDecorations();
```
Comment (rebornix) [inline src/vs/workbench/contrib/notebook/browser/contrib/multicursor/notebookSelectionHighlight.ts:74]: any reason we don't want to use delayer here anymore?

**Review by rebornix — APPROVED** [review]
