### PR TITLE
bring back terminal voice input 

### LINKED ISSUE #253442: Missing speech dictation in terminal
Type: <b>Bug</b>

1. Try to use the Alt+` or Ctrl+Alt+V keybindings in a Terminal, nothing happens.

There are keybindings for "Start Dictation in Editor" but nothing for the Terminal.  It seems like this might have been removed in #210580 but I'm not sure why?

How do you perform voice dictation using the Speech capabilities in a terminal?

Extension version: 0.16.0
VS Code version: Code 1.101.2 (2901c5ac6db8a986a5666c3af51ff804d05af0d4, 2025-06-24T20:27:15.391Z)
OS version: Windows_NT x64 10.0.26100
Modes:
Remote OS version: Linux x64 6.6.87.2-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (20 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (8.32GB free)|
|Process Argv|--crash-reporter-id e6a432db-87fc-4819-bb9a-63dbac992c16|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 6.6.87.2-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (20 x 0)|
|Memory (System)|11.68GB (4.76GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt551cf:31249601
vscod805:30301674
binariesv615:30325510
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dwnewjupyter:31046869
pythonrstrctxt:31112756
nativeloc2:31192216
5fd0e150:31155592
dwcopilot:31170013
6074i472:31201624
dwoutputs:31242946
customenabled:31248079
9064b325:31222308
copilot_t_ci:31333650
e5gg6876:31282496
pythoneinst12:31285622
bgtreat:31268568
4gafe986:31271826
c7cif404:31314491
pythonpulldiagcf:31335740
996jf627:31283433
pythonrdcb7:31303018
usemplatestapi:31297334
0aa6g176:31307128
7bj51361:31289155
747dc170:31275177
aj953862:31281341
generatesymbolt:31295002
convertfstringf:31295003
j6a0c355:31339598
91889449:31338102
i851h500:31338111
usemarketplace:31336439
nesew2to5:31336538
agentclaude:31335814
nes-diff-11:31337487
nes-set-on:31339175
testaa123cf:31335227
6abeh943:31336334
yijiwantestdri0626-c:31336931

```

</details>

### PR DESCRIPTION
**Pull request by meganrogge**
We had removed this before, thinking natural language wouldn't be useful in the terminal. I learned that this is useful for Gemini/Claude terminals, so we should bring it back.

https://github.com/user-attachments/assets/ebcf23c5-9457-4c3a-bff3-288bd8f9f34c

fix #253442

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalActions.ts [hunk 1]
```diff
@@ -1393,6 +1395,28 @@ export function registerTerminalActions() {
 			}
 		}
 	});
+
+	registerActiveInstanceAction({
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalActions.ts]: This is the perfect type of thing to add to a terminalContrib as I think it's completely self contained.

File: src/vs/workbench/contrib/terminal/browser/terminalVoice.ts [hunk 2]
```diff
@@ -0,0 +1,208 @@
...
+			this._sendText();
+		}
+		this._marker?.dispose();
+		this._ghostTextMarker?.dispose();
+		this._ghostText?.dispose();
+		this._ghostText = undefined;
+		this._decoration?.dispose();
+		this._decoration = undefined;
+		this._cancellationTokenSource?.cancel();
+		this._disposables.clear();
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalVoice.ts]: We have `_disposables`, so this._ghostText and the like could be registered on that when it's created?

**Review by Tyriar — DISMISSED** [review]
I didn't review terminalVoice.ts thoroughly, assuming we did that before

File: src/vs/workbench/contrib/terminal/browser/terminalActions.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalActions.ts]: not following - we're using `sharedWhenClause` here too, so I think these are in the right place already?

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalActions.ts]: You can export that if you need, just rename it to terminalSharedWhenClause`. The less stuff we put in the core the easier it is to maintain the core, otherwise this is just another debt issue that would go ignored.

**Review by Tyriar — DISMISSED** [review]

**Review by dbaeumer — DISMISSED** [review]

**Review by Tyriar — APPROVED** [review]

**Comment by lsegal** [comment]
Thanks for the quick work on this @meganrogge!
