### PR TITLE
Fix welcome view links missing hover color

### LINKED ISSUE #121521: Tree View welcome content doesn't use hover link color
1. `settings.json`

```js
"workbench.colorCustomizations": {
	"textLink.activeForeground": "#ff0000",
}
```

2. Hover over link in welcome content
3. It's not highlighted

Screenshot (475)

### PR DESCRIPTION
**Pull request by sangxxh**
This PR fixes #121521 

microsoft_vscode_121521_After

### CODE REVIEW

File: src/vs/platform/opener/browser/link.ts [hunk 1]
```diff
@@ -28,6 +29,7 @@ export class Link extends Disposable {
 	readonly el: HTMLAnchorElement;
 	private disabled: boolean;
 	private styles: ILinkStyles = {
+		textLinkActiveForeground: Color.fromHex('#3794FF'),
```
Comment (hantatsang) [inline src/vs/platform/opener/browser/link.ts:32]: Please suggest a default color for the hover state.

**Comment by JacksonKearl** [comment]
What theme are you using? In the default theme I do not see color-based hover feedback in any links in the workbench. If there's an existing color token themes can set to support link color we should be using that. 

Could you open an to better track what the problem is here before jumping into a PR?

File: src/vs/platform/opener/browser/link.ts [hunk 2]
```diff
@@ -57,6 +59,11 @@ export class Link extends Disposable {
 			}
 		}));
 
+		const onMouseOver = domEvent(this.el, 'mouseover');
```
Comment (JacksonKearl) [inline src/vs/platform/opener/browser/link.ts:62]: I'd recommend to instead follow the existing pattern for styling links on hover using CSS, for example here's how the search view does it:
https://github.com/microsoft/vscode/blob/f547ada6eeb701a5e88cff1243d347f862d9d3c9/src/vs/workbench/contrib/search/browser/searchView.ts#L1977-L1981

**Review by JacksonKearl — CHANGES_REQUESTED** [review]

File: src/vs/platform/opener/browser/link.ts (hunk 2 above)
Comment (hantatsang) [reply src/vs/platform/opener/browser/link.ts:62]: I implemented it but realized it doesn't really work because `Link` is used in a few different places:

- `src/vs/workbench/browser/parts/views`
- `src/vs/workbench/contrib/welcome/gettingStarted/browser`
- `src/vs/workbench/contrib/workspace/browser`

So it doesn't look like there's a safe CSS selector that can cover all those cases and potential future consumers of `Link`.

What's your thought?

Comment (JacksonKearl) [reply src/vs/platform/opener/browser/link.ts:62]: You might add a class to the link's `a` element and style based on that, but I'll leave further review to @joaomoreno as he owns this code.

Comment (hantatsang) [reply src/vs/platform/opener/browser/link.ts:62]: Oh yes, that sounds like the way to do it. I'll have a go while waiting for @joaomoreno's review

Comment (hantatsang) [reply src/vs/platform/opener/browser/link.ts:62]: No luck with `registerThemingParticipant` yet, I'll wait for @joaomoreno 's review for now

**Review by glaukiol1 — APPROVED** [review]
solid fix, thanks for contributing, also, please make a default color! thanks

File: src/vs/platform/opener/browser/link.ts (hunk 2 above)
Comment (hantatsang) [reply src/vs/platform/opener/browser/link.ts:62]: Any thoughts @joaomoreno ?

**Comment by joaomoreno** [comment]
Thanks! 🍻 Ended up cleaning up quite a bit how we style links.
