### PR TITLE
Bugfix on enter/arrow/mouse interaction for code action widget

### LINKED ISSUE #156587: Enter Keybinding doesn't work when not mouse hovered on code action widget.
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Open the code action widget using one of the keybindings or from the context menu, but when the mouse is not in the widget or hovering over any of the selected items.
2. Hit enter.
3. Users will be unable to run the item that is highlighted. 

Alternatively:
1. Open the code action widget.
2. Hover over a disabled item after hovering over an enabled item
3. Hit enter.
4. The menu will activate and run the last highlighted enabled item, when it should not fire the action at all.

### PR DESCRIPTION
**Pull request by justschen**
Fixes https://github.com/microsoft/vscode/issues/156587

### CODE REVIEW

File: src/vs/editor/contrib/codeAction/browser/codeActionMenu.ts [hunk 1]
```diff
@@ -164,6 +164,7 @@ export class CodeActionMenu extends Disposable implements IEditorContribution {
 	private currSelectedItem: number = 0;
 	private hasSeperator: boolean = false;
 	private block?: HTMLElement;
+	private allowEnterClick: boolean = true;
```
Comment (rebornix) [inline src/vs/editor/contrib/codeAction/browser/codeActionMenu.ts:167]: Nit: `Enter` is contributed via keybinding/command, it would be better if we set context (e.g., `code-action-enabled`) on list items and enforce the context on keybindings directly.

File: src/vs/editor/contrib/codeAction/browser/codeActionMenu.ts [hunk 2]
```diff
@@ -391,7 +400,9 @@ export class CodeActionMenu extends Disposable implements IEditorContribution {
 	}
 
 	public onEnterSet() {
-		this.codeActionList.value?.setSelection([this.currSelectedItem]);
+		if (this.allowEnterClick) {
```
Comment (mjbvz) [inline src/vs/editor/contrib/codeAction/browser/codeActionMenu.ts:403]: Having `allowEnterClick` and `currSelectedItem` seems  redundant. Could `currSelectedItem` be nullable instead to indicate nothing is selected and that nothing should be accepted on enter?

File: src/vs/editor/contrib/codeAction/browser/codeActionMenu.ts [hunk 3]
```diff
@@ -161,10 +161,9 @@ export class CodeActionMenu extends Disposable implements IEditorContribution {
 	private _ctxMenuWidgetVisible: IContextKey<boolean>;
 	private viewItems: ICodeActionMenuItem[] = [];
 	private focusedEnabledItem: number | undefined;
-	private currSelectedItem: number = 0;
+	private currSelectedItem: number | null = 0;
```
Comment (mjbvz) [inline src/vs/editor/contrib/codeAction/browser/codeActionMenu.ts:164]: Should this default to undefined instead of `0`?

Also prefer `undefined` over `null`

File: src/vs/editor/contrib/codeAction/browser/codeActionMenu.ts [hunk 4]
```diff
@@ -391,7 +394,10 @@ export class CodeActionMenu extends Disposable implements IEditorContribution {
 	}
 
 	public onEnterSet() {
-		this.codeActionList.value?.setSelection([this.currSelectedItem]);
+		// 0 case when first enabled item is the 0th element in list.
+		if (this.currSelectedItem === 0 || this.currSelectedItem) {
```
Comment (mjbvz) [inline src/vs/editor/contrib/codeAction/browser/codeActionMenu.ts:398]: Here it would be clearer to check if it is a number: `typeof this.currSelectedItem === 'number'`

**Review by mjbvz — CHANGES_REQUESTED** [review]

**Review by mjbvz — APPROVED** [review]
