### PR TITLE
dnd terminals bw windows in panel and fix moving from editor to panel

### LINKED ISSUE #126387: Support terminal drag and drop across windows
Once https://github.com/microsoft/vscode/issues/118276 is done it shouldn't be too hard to be able to detach on one window and reattach in another window to enable moving terminals across windows.

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #126387

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 1]
```diff
@@ -753,25 +758,43 @@ export class TerminalService implements ITerminalService {
...
-			const instanceId = this._getInstanceIdFromUri(e.uri);
-			if (instanceId === undefined) {
-				return;
-			}
+		instance.addDisposable(instance.onRequestAddInstanceToGroup(async e => await this._addInstanceToGroup(instance, e)));
+	}
+
+
+	private async _addInstanceToGroup(instance: ITerminalInstance, e: IRequestAddInstanceToGroupEvent): Promise<void> {
+		const [, workspaceId, instanceId] = e.uri.path.split('/');
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:766]: Let's make a helper similar to this:

```
parseTerminalUri(): ITerminalIdentifier;

interface ITerminalIdentifier {
  workspaceId: string;
  instanceId: number | undefined;
}
```

**Review by Tyriar — COMMENTED** [review]
Didn't test but seems fine. Not sure about the `onRequestAddInstanceToGroup ` thing, try trace?

File: src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts [hunk 2]
```diff
@@ -167,7 +171,23 @@ export class TerminalEditorService extends Disposable implements ITerminalEditor
...
 		}
 
-		const input = this._instantiationService.createInstance(TerminalEditorInput, instance);
+		if (URI.isUri(instance)) {
+			console.log('here');
+			const [, workspaceId, instanceId] = instance.path.split('/');
+
+			// Terminal from a different window
+			this._onDidRequestDetachInstance.fire({ workspaceId, instanceId: Number.parseInt(instanceId) });
+			timeout(300);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts:180]: it's working, but have any better way to do this? @tyriar

**Comment by meganrogge** [comment]
still no clue what the issue is @Tyriar otherwise, works great in all cases 🤷🏼

File: src/vs/workbench/contrib/terminal/browser/terminal.ts [hunk 3]
```diff
@@ -197,11 +202,14 @@ export interface ITerminalEditorService extends ITerminalInstanceHost, ITerminal
...
 
+	onDidRequestDetachInstance: Event<{ workspaceId: string, instanceId: number }>;
+
 	openEditor(instance: ITerminalInstance): Promise<void>;
-	getOrCreateEditorInput(instance: ITerminalInstance | SerializedTerminalEditorInput): TerminalEditorInput;
+	getOrCreateEditorInput(instance: ITerminalInstance | SerializedTerminalEditorInput | URI): TerminalEditorInput;
 	detachActiveEditorInstance(): ITerminalInstance;
 	detachInstance(instance: ITerminalInstance): void;
 	splitInstance(instanceToSplit: ITerminalInstance, shellLaunchConfig?: IShellLaunchConfig): ITerminalInstance;
+	parseTerminalUri(resource: URI): ITerminalIdentifier;
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminal.ts:212]: todo: move this elsewhere since it's also used in cases that might be panel terminals?

File: src/vs/workbench/browser/dnd.ts [hunk 4]
```diff
@@ -113,8 +113,22 @@ export function extractEditorsDropData(e: DragEvent, externalOnly?: boolean): Ar
...
 
+		// Check for terminals transfer
+		const terminals = e.dataTransfer.getData(DataTransfers.TERMINALS);
+		if (terminals) {
+			try {
+				const terminalEditors: string[] = JSON.parse(terminals);
+				editors.push(...terminalEditors.map(e => {
+					return {
+						resource: URI.parse(e), isExternal: true
+					};
```
Comment (Tyriar) [inline src/vs/workbench/browser/dnd.ts:125]: Copy existing style on one line and for loop

File: src/vs/workbench/contrib/terminal/browser/remoteTerminalService.ts [hunk 5]
```diff
@@ -44,6 +44,8 @@ export class RemoteTerminalService extends Disposable implements IRemoteTerminal
 	readonly onPtyHostRequestResolveVariables = this._onPtyHostRequestResolveVariables.event;
 	private readonly _onDidRequestDetach = this._register(new Emitter<{ requestId: number, workspaceId: string, instanceId: number }>());
 	readonly onDidRequestDetach = this._onDidRequestDetach.event;
+	private readonly _onDidAcceptAttachInstanceReply = this._register(new Emitter<IProcessDetails>());
+	readonly onDidAcceptAttachInstanceReply = this._onDidAcceptAttachInstanceReply.event;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/remoteTerminalService.ts:48]: Not being used

File: src/vs/workbench/contrib/terminal/browser/terminal.ts [hunk 6]
```diff
@@ -187,6 +192,11 @@ export interface ITerminalService extends ITerminalInstanceHost {
 	getFindHost(instance?: ITerminalInstance): ITerminalFindHost;
 }
 
+export interface ITerminalIdentifier {
+	workspaceId: string;
+	instanceId: number | undefined;
+}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminal.ts:198]: We can move this to `terminalUriParser`

File: src/vs/workbench/contrib/terminal/browser/terminal.ts [hunk 7]
```diff
@@ -197,8 +207,10 @@ export interface ITerminalEditorService extends ITerminalInstanceHost, ITerminal
 	/** Gets all _terminal editor_ instances. */
 	readonly instances: readonly ITerminalInstance[];
 
+	onDidRequestDetachInstance: Event<{ workspaceId: string, instanceId: number }>;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminal.ts:210]: Remove

File: src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts [hunk 8]
```diff
@@ -36,15 +42,21 @@ export class TerminalEditorService extends Disposable implements ITerminalEditor
 	readonly onDidChangeActiveInstance = this._onDidChangeActiveInstance.event;
 	private readonly _onDidChangeInstances = new Emitter<void>();
 	readonly onDidChangeInstances = this._onDidChangeInstances.event;
+	private readonly _onDidRequestDetachInstance = new Emitter<{ workspaceId: string, instanceId: number }>();
+	readonly onDidRequestDetachInstance = this._onDidRequestDetachInstance.event;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts:46]: Remove

File: src/vs/workbench/contrib/terminal/browser/terminalEditorInput.ts [hunk 9]
```diff
@@ -47,11 +51,27 @@ export class TerminalEditorInput extends EditorInput {
 		return TerminalEditor.ID;
 	}
 
+	setTerminalInstance(instance: ITerminalInstance): void {
+		if (this._terminalInstance) {
+			throw new Error('cannot set instance that has already been set');
+		}
+		this._terminalInstance = instance;
+		this._setupInstanceListeners();
+		this._terminalEditorFocusContextKey = TerminalContextKeys.editorFocus.bindTo(this._contextKeyService);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalEditorInput.ts:60]: Can be removed, let's make the property readonly too

File: src/vs/workbench/contrib/terminal/browser/terminalEditorInput.ts [hunk 10]
```diff
@@ -69,34 +89,47 @@ export class TerminalEditorInput extends EditorInput {
...
+		public readonly resource: URI,
+		private _terminalInstance: ITerminalInstance | undefined,
 		@IThemeService private readonly _themeService: IThemeService,
 		@ITerminalInstanceService private readonly _terminalInstanceService: ITerminalInstanceService,
 		@IInstantiationService private readonly _instantiationService: IInstantiationService,
 		@IConfigurationService private readonly _configurationService: IConfigurationService,
-		@ILifecycleService lifecycleService: ILifecycleService,
-		@IContextKeyService contextKeyService: IContextKeyService
+		@ILifecycleService private readonly _lifecycleService: ILifecycleService,
+		@IContextKeyService private readonly _contextKeyService: IContextKeyService
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalEditorInput.ts:108]: Remove `private readonly`

File: src/vs/workbench/contrib/terminal/browser/terminalEditorInput.ts [hunk 11]
```diff
@@ -69,34 +89,47 @@ export class TerminalEditorInput extends EditorInput {
...
+				this._onDidChangeDirty.fire();
+			}
+		});
+		if (_terminalInstance) {
+			this._setupInstanceListeners();
+		}
+	}
+
+	private _setupInstanceListeners(): void {
+		if (!this._terminalInstance) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalEditorInput.ts:126]: `const instance = this._terminalInstance`, can then remove the ?

File: src/vs/workbench/contrib/terminal/browser/terminalEditorInput.ts [hunk 12]
```diff
@@ -111,26 +144,22 @@ export class TerminalEditorInput extends EditorInput {
...
-		lifecycleService.onWillShutdown(() => {
+		this._lifecycleService.onWillShutdown(() => {
 			this._isShuttingDown = true;
 			dispose(disposeListeners);
 		});
 	}
 
 	override getName() {
-		return this._terminalInstance.title;
+		return this._terminalInstance?.title || this.resource?.fragment || '';
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalEditorInput.ts:156]:
```suggestion
		return this._terminalInstance?.title || this.resource.fragment;
```

File: src/vs/workbench/contrib/terminal/browser/terminalEditorSerializer.ts [hunk 13]
```diff
@@ -41,7 +41,8 @@ export class TerminalInputSerializer implements IEditorSerializer {
 			titleSource: instance.titleSource,
 			cwd: '',
 			icon: instance.icon,
-			color: instance.color
+			color: instance.color,
+			resource: instance.resource.toString()
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalEditorSerializer.ts:45]: Let's convert this back inside `deserialize` so that the uri <-> string conversion is contained in this file. And then remove it where we were using `string` before

File: src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts [hunk 14]
```diff
@@ -153,31 +165,71 @@ export class TerminalEditorService extends Disposable implements ITerminalEditor
...
-			cachedEditor = this._editorInputs.get(instance.instanceId);
+	getOrCreateEditorInput(instanceOrUri: ITerminalInstance | SerializedTerminalEditorInput | URI, isFutureSplit: boolean = false): TerminalEditorInput {
+		let resource: URI;
+		if (URI.isUri(instanceOrUri)) {
+			resource = instanceOrUri;
+		} else if ('instanceId' in instanceOrUri) {
+			resource = instanceOrUri.resource;
+		} else {
+			resource = URI.parse(instanceOrUri.resource);
 		}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts:176]: Should be able to do 

```ts
} else {
  resource = instanceOrUri.resource;
}
```

File: src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts [hunk 15]
```diff
@@ -153,31 +165,71 @@ export class TerminalEditorService extends Disposable implements ITerminalEditor
...
+
+		// Terminal from a different window
+		if (URI.isUri(instanceOrUri)) {
+			const terminalIdentifier = parseTerminalUri(instanceOrUri);
+			if (terminalIdentifier.instanceId) {
+				this._primaryOffProcessTerminalService.requestDetachInstance(terminalIdentifier.workspaceId, terminalIdentifier.instanceId).then(attachPersistentProcess => {
+					const instance = this._terminalInstanceService.createInstance({ attachPersistentProcess }, TerminalLocation.Editor, resource);
+					input.setTerminalInstance(instance);
+					// TODO: fix and use an event instead, for now is used to trigger TerminalEditor's setInput,
+					// which attaches to the element
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts:195]: Let's replace this with an explanatory comment and remove the on did attach event if we don't need it anymore

File: src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts [hunk 16]
```diff
@@ -153,31 +165,71 @@ export class TerminalEditorService extends Disposable implements ITerminalEditor
...
+			this._registerInstance(inputKey, input);
+		}
+		return input;
+	}
+
+	private _registerInstance(inputKey: string, input: TerminalEditorInput, instance?: ITerminalInstance): void {
+		this._editorInputs.set(inputKey, input);
+		if (!instance) {
+			return;
+		}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts:223]: Let's pull this out and make `instance` mandatory

File: src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts [hunk 17]
```diff
@@ -153,31 +165,71 @@ export class TerminalEditorService extends Disposable implements ITerminalEditor
...
+		this._instanceDisposables.set(inputKey, [
+			instance.onDidFocus(this._onDidFocusInstance.fire, this._onDidFocusInstance),
+			// TODO: why don't these do anything
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts:226]: resolved?

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 18]
```diff
@@ -753,25 +742,41 @@ export class TerminalService implements ITerminalService {
...
-		}));
+		// View terminals
+		sourceInstance = this._terminalGroupService.instances.find(e => e.instanceId === terminalIdentifier.instanceId);
+		if (sourceInstance) {
+			this._terminalGroupService.moveInstance(sourceInstance, instance, e.side);
+			return;
+		}
+
+		// Terminal editors
+		sourceInstance = this._terminalEditorService.instances.find(e => e.instanceId === terminalIdentifier.instanceId);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:774]: I think these will also need a `getInstanceByResource` method

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 19]
```diff
@@ -1087,14 +1091,14 @@ export class TerminalService implements ITerminalService {
 		let instance: ITerminalInstance;
 		const target = options?.target || this.configHelper.config.defaultLocation;
 		if (target === TerminalLocation.Editor) {
-			instance = this._terminalInstanceService.createInstance(shellLaunchConfig);
+			instance = this._terminalInstanceService.createInstance(shellLaunchConfig, undefined, options?.resource);
 			instance.target = TerminalLocation.Editor;
 			this._terminalEditorService.openEditor(instance);
 		} else {
+			// TODO: pass resource?
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:1098]: Need to verify this

File: src/vs/workbench/contrib/terminal/browser/terminalTabsList.ts [hunk 20]
```diff
@@ -618,21 +619,22 @@ class TerminalTabsDragAndDrop implements IListDragAndDrop<ITerminalInstance> {
 		this._autoFocusInstance = undefined;
 
 		let sourceInstances: ITerminalInstance[] | undefined;
-		const terminalResources = originalEvent.dataTransfer?.getData(DataTransfers.RESOURCES);
-		const terminals = originalEvent.dataTransfer?.getData(DataTransfers.TERMINALS);
 		let promises: Promise<IProcessDetails | undefined>[] = [];
-		if (terminals && terminalResources) {
-			const json = JSON.parse(terminalResources);
+		const resources = originalEvent.dataTransfer?.getData(DataTransfers.TERMINALS) || originalEvent.dataTransfer?.getData(DataTransfers.RESOURCES);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalTabsList.ts:623]: Can we just do the TERMINALS one now that we have the resource change done? Ideally we wouldn't hit the `if (terminalIdentifier.instanceId) {` if it's a file for example.

File: src/vs/workbench/contrib/terminal/browser/terminalUriParser.ts [hunk 21]
```diff
@@ -0,0 +1,21 @@
+/*---------------------------------------------------------------------------------------------
+ *  Copyright (c) Microsoft Corporation. All rights reserved.
+ *  Licensed under the MIT License. See License.txt in the project root for license information.
+ *--------------------------------------------------------------------------------------------*/
+
+import { Schemas } from 'vs/base/common/network';
+import { URI } from 'vs/base/common/uri';
+import { ITerminalIdentifier } from 'vs/workbench/contrib/terminal/browser/terminal';
+
+export function parseTerminalUri(resource: URI): ITerminalIdentifier {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalUriParser.ts:10]: Call this file `terminalUri.ts` and be a gathering spot for any other URI-related helpers?

File: src/vs/workbench/contrib/terminal/browser/terminalUriParser.ts [hunk 22]
```diff
@@ -0,0 +1,21 @@
...
+	const [, workspaceId, instanceId] = resource.path.split('/');
+	return { workspaceId, instanceId: Number.parseInt(instanceId) };
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalUriParser.ts:12]: Let's throw with a nice message when the format is inexpected?

File: src/vs/workbench/contrib/terminal/common/terminal.ts [hunk 23]
```diff
@@ -82,6 +82,7 @@ export interface IOffProcessTerminalService {
 	onPtyHostRestart: Event<void>;
 
 	onDidRequestDetach: Event<{ requestId: number, workspaceId: string, instanceId: number }>;
+	onDidAcceptAttachInstanceReply: Event<IProcessDetails>;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/terminal.ts:85]: Remove?

File: src/vs/workbench/contrib/terminal/electron-sandbox/localTerminalService.ts [hunk 24]
```diff
@@ -38,6 +38,8 @@ export class LocalTerminalService extends Disposable implements ILocalTerminalSe
 	readonly onPtyHostRestart = this._onPtyHostRestart.event;
 	private readonly _onDidRequestDetach = this._register(new Emitter<{ requestId: number, workspaceId: string, instanceId: number }>());
 	readonly onDidRequestDetach = this._onDidRequestDetach.event;
+	private readonly _onDidAcceptAttachInstanceReply = this._register(new Emitter<IProcessDetails>());
+	readonly onDidAcceptAttachInstanceReply = this._onDidAcceptAttachInstanceReply.event;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/electron-sandbox/localTerminalService.ts:42]: Remove?

File: src/vs/workbench/test/browser/workbenchTestServices.ts [hunk 25]
```diff
@@ -1666,10 +1666,9 @@ export class TestLocalTerminalService implements ILocalTerminalService {
 	onPtyHostRestart = Event.None;
 	onDidMoveWindowInstance = Event.None;
 	onDidRequestDetach = Event.None;
+	onDidAcceptAttachInstanceReply = Event.None;
```
Comment (Tyriar) [inline src/vs/workbench/test/browser/workbenchTestServices.ts:1669]: Remove?

File: src/vs/workbench/test/browser/workbenchTestServices.ts [hunk 26]
```diff
@@ -1685,6 +1684,7 @@ export class TestLocalTerminalService implements ILocalTerminalService {
 	updateIcon(id: number, icon: URI | { light: URI; dark: URI } | { id: string, color?: { id: string } }, color?: string): Promise<void> { throw new Error('Method not implemented.'); }
 	requestDetachInstance(workspaceId: string, instanceId: number): Promise<IProcessDetails | undefined> { throw new Error('Method not implemented.'); }
 	acceptDetachInstanceReply(requestId: number, persistentProcessId: number): Promise<void> { throw new Error('Method not implemented.'); }
+	fireAcceptDetachInstanceReply(options: ICreateTerminalOptions): void { throw new Error('Method not implemented.'); }
```
Comment (Tyriar) [inline src/vs/workbench/test/browser/workbenchTestServices.ts:1687]: Remove?

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts (hunk 17 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts:226]: not resolved - we now call this._terminalEditorService.detachInstance(instanceToDetach); within terminal service on line 265

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts:226]: Ok in that case let's remove this
