### PR TITLE
Pass session down so we can avoid a network call

### LINKED ISSUE #173645: Github Education - VSCode API rate limiting issue
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: NA
- OS Version: NA

Steps to Reproduce:

The github education team sees about [85k+](https://data.githubapp.com/sql/share/d647ed34) calls from Visual-studio-code in an hour for api/user. This is quite unusual and since we are rate limiting anyway, it is not an immediate issue.  

From initial discussions with @TylerLeonhardt I understand that the call is made only for telemetry and has no impact on the user. So, raising this bug, if we can find a better way to do telemetry without having to rate limit.  This [issue](https://github.com/github/education-web/issues/7783) here shows some more details.

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
We don't need to fetch the user details when the Auth Session already has the info we need. This PR removes that extraneous web request.

I've also changed the `User-Agent` that we pass to be more specific so we can narrow down any future issues with spamming web requests.

Fixes #173645

### CODE REVIEW

File: extensions/github-authentication/src/githubServer.ts [hunk 1]
```diff
@@ -606,8 +595,9 @@ export class GitHubServer implements IGitHubServer {
 			}
 		*/
 		this._telemetryReporter.sendTelemetryEvent('session', {
-			isEdu: edu ?? 'unknown',
-			isManaged: managed ?? 'unknown'
+			isEdu: edu,
+			// Apparently, this is how you tell if a user is an EMU...
+			isManaged: session.account.label.includes('_') ? 'true' : 'false'
```
Comment (bhavyaus) [inline extensions/github-authentication/src/githubServer.ts:600]: nit: What is an EMU? Perhaps including an example in the comment will help?

**Review by bhavyaus — APPROVED** [review]
