### PR TITLE
bind `configure` function so `this` is not undefined

### LINKED ISSUE #161455: Configure build task does not work in VS Code insiders
Does this issue occur when all extensions are disabled?: [Yes]/No

- VS Code Version: 1.72.0-insider (user setup)
- OS Version:

Steps to Reproduce:

When I do CTRL+SHIFT+B I get the "No build task to run found. Configure build task..." UI, but when I hit enter, nothing happens. Normally this should show some UI (which I choose to create a shell task) and then create/open the build settings JSON file so that I can edit it appropriately, but I get nothing in the current version.

### PR DESCRIPTION
**Pull request by meganrogge**
fix #161455

### CODE REVIEW

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 1]
```diff
@@ -2953,7 +2953,6 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
 					// eat the error, it has already been surfaced to the user and we don't care about it here
 				});
 			}
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:2955]:
```suggestion
			}
			
```

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 2]
```diff
@@ -2953,7 +2953,7 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
...
-
+
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:2956]:
```suggestion

```

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 3]
```diff
@@ -2968,7 +2967,7 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
 								return;
 							}
 							if (task === null) {
-								configure();
+								configure.bind(this).apply(this);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:2970]: I think this would work as just `.apply(this)` (or longer `.bind(this)()`)

**Review by Tyriar — DISMISSED** [review]

**Review by Tyriar — APPROVED** [review]
