### PR TITLE
Integrated Browser: Fix buggy Right Click -> Copy into New Window

### LINKED ISSUE #284525: Integrated Browser: unexpected behavior with "Copy into New Window"
- VS Code Version: 1.109.0-insider
- OS Version: macOS Tahoe 26.2

Steps to Reproduce:

1. In command palette: "Browser: Open Integrated Browser" (Note that this is different from the Simple Browser)
2. Open a website with animations, such as https://doodles.google/
3. Notice the smooth animations on the page
4. Right click on the editor tab and "Copy into New Window"
    Image

5. Two issues happen:
    1. 🐛 The new window is synced to the old window, so every scroll or click or type is mirrored between these windows. I'm not sure if this is expected or not
    2. 🐛 At least one of the windows will now show some lag in the animation, or the popped out window might even glitch, very briefly disappearing every so often

**Expected behavior:**
either the two windows become independent of each other, not synced, or if they're synced there no perf hit, or as another option we just don't show the option to "Copy into New Window" if that's not meant to be supported.

The approach that Simple Browser takes is to keep the "Copy into New Window" button, but they force it to work like "Move into New Window": Once the copy is created, they force the closure of the original one. (This is not a perfect solution, because the original window ends up with focus, so the popped out window kind of disappears until you put it in focus again)

---

Related to feature: https://github.com/microsoft/vscode/issues/286579

### PR DESCRIPTION
**Pull request by jruales**
Fixes https://github.com/microsoft/vscode/issues/284525
(Copy into New Window was very buggy. Not to be confused with Move into New Window, which has been working fine.)

This PR does the following:
* Creates an independent browser editor to avoid linked state
* Adds a resize observer to fix some issues where sometimes the copied window ended up with a zero-size webview or where a moved window ended up with a squashed webview until the user resized the window

---

Related feature: https://github.com/microsoft/vscode/issues/286579

### CODE REVIEW

File: src/vs/workbench/contrib/browserView/electron-browser/browserEditor.ts [hunk 1]
```diff
@@ -368,8 +368,22 @@ export class BrowserEditor extends EditorPane {
...
+		// Watch for container size changes to handle window moves/resizes.
+		// This is especially important when copying or moving to a new window on a different
+		// monitor where the initial bounds may be incorrect until the window finishes layout.
+		// For some reason, the workbench's normal layout() calls do not cover this case.
+		const resizeObserver = new ResizeObserver(async () => {
+			if (this._model) {
+				const containerRect = this._browserContainer.getBoundingClientRect();
+				// Only proceed if we have valid bounds
+				if (containerRect.width > 0 && containerRect.height > 0) {
+					this.layout();
```
Comment (kycutler) [inline src/vs/workbench/contrib/browserView/electron-browser/browserEditor.ts]: Does this cause duplicate layout calls when e.g. resizing? I believe VS Code generally already handles this. If we just need to wait for the first insertion I'd prefer to clean up the listener after that's done

Comment (jruales) [reply src/vs/workbench/contrib/browserView/electron-browser/browserEditor.ts]: Now using ResizeObserver exclusively, instead of both that and the original layout() call

**Review by kycutler — APPROVED** [review]
