### PR TITLE
Pass full function breakpoint options from plugin

### LINKED ISSUE #209386: Adding function breakpoint through plugin API does not result in DAP call to add breakpoint
Does this issue occur when all extensions are disabled?: No - relates to behavior of plugin API.

- VS Code Version: 1.87.2
- OS Version: RHEL8

Steps to Reproduce:

1. I have a plugin with code like this:

```typescript
    commands.registerCommand("add-a-function-breakpoint", () => {
		debug.addBreakpoints([
			new FunctionBreakpoint("get_char", true)
		]);
	});
```

that I am running together with the [CDT-GDB VSCode plugin](https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode). When this code is run, a breakpoint does appear in the breakpoints widget, but the breakpoint is not sent to the debug adapter, and so it is not set with GDB and cannot be hit.

When the builtin ['Add Function Breakpoint' command](https://github.com/microsoft/vscode/blob/e02d14210805688fc558069c5b8ffeb2d9fbb9f1/src/vs/workbench/contrib/debug/browser/breakpointsView.ts#L1401-L1429) is invoked, it isn't until the user enters the name of the function that [a chain of calls](https://github.com/microsoft/vscode/blob/e02d14210805688fc558069c5b8ffeb2d9fbb9f1/src/vs/workbench/contrib/debug/browser/breakpointsView.ts#L946) is set off that leads to [a transmission to the adapter](https://github.com/microsoft/vscode/blob/e02d14210805688fc558069c5b8ffeb2d9fbb9f1/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L427). When a breakpoint is added via the extension API, no further input is required, so after [the event for a new breakpoint](https://github.com/microsoft/vscode/blob/e02d14210805688fc558069c5b8ffeb2d9fbb9f1/src/vs/workbench/contrib/debug/common/debugModel.ts#L1902) is fired, there is no path leading to actually setting the breakpoint with a debug adapter.

### LINKED ISSUE #211894: Support full range of function breakpoint fields in plugin `addBreakpoints`
At the moment, it is possible to pass a `FunctionBreakpoint` instance with the full range of fields configured, but when the breakpoint [is eventually inserted](https://github.com/microsoft/vscode/blob/1451e4fbbbf074a4355cc537c35b547b80ce1c52/src/vs/workbench/api/browser/mainThreadDebugService.ts#L226-L228), only the name and mode are included.

It would increase the power of the API to pass the full set of fields.

### PR DESCRIPTION
**Pull request by OccasionalDebugger**
Fixes #211894 by modifying the chain of calls to create a new function breakpoint to accept the full range of configurable fields. This ensures that the inserted function breakpoint matches the specification provided by a plugin rather than ignoring a variety of fields.

While working on this, I noticed #209386, and I have added code to send well-formed function breakpoints at the time of their creation, so this also fixes #209386.

### CODE REVIEW

**Comment by OccasionalDebugger** [comment]
> @OccasionalDebugger please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
>  > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

File: src/vs/workbench/api/browser/mainThreadDebugService.ts [hunk 1]
```diff
@@ -223,7 +223,14 @@ export class MainThreadDebugService implements MainThreadDebugServiceShape, IDeb
 				}));
 				this.debugService.addBreakpoints(uri.revive(dto.uri), rawbps);
 			} else if (dto.type === 'function') {
-				this.debugService.addFunctionBreakpoint(dto.functionName, dto.id, dto.mode);
+				this.debugService.addFunctionBreakpoint({
```
Comment (roblourens) [inline src/vs/workbench/api/browser/mainThreadDebugService.ts:226]: This seems fine, right @connor4312? I don't know why it would have been limited

Comment (connor4312) [reply src/vs/workbench/api/browser/mainThreadDebugService.ts:226]: yea, I don't either. This limitation dates from https://github.com/microsoft/vscode/commit/eba681fed8b36e9abfeb0b80c7b0c5078c7d843d and I think it's just a bug.

**Review by connor4312 — APPROVED** [review]

**Review by TylerLeonhardt — APPROVED** [review]
