### PR TITLE
Fix #142028

### LINKED ISSUE #142028: When setting the state of a TestRun more than once, the last one wins, not the "most failed" one
- VS Code Version: 1.64.0-insider (4ccfe1100c3c)

In the Catch2 C++ test framework it is possible to have multiple test results for the same test in one run. This happens for example for the following code:
```
TEST_CASE("T")
{
  SECTION("S")
  {
    auto value = GENERATE(3, 7);
    CHECK(value == 7);
  }
}
```
In this scenario, the section "S" is run twice, and the first time it fails, the second time it succeeds.

The C++ TestMate extension will see the two test runs, and call `TestRun.failed` for the first one, and `TestRun.passed` for the second, _with the same `TestItem`_ for both calls. This results in the confusing display that the section is green, even though it shows a failure inside:

image

@connor4312, does it make sense to change `failed()` and `passed()` (et al) so that when called multiple times, it sets the item's state to the max of the old and the new state? This seems to be analogous to what happens with the test messages (they are appended, and `passed()` doesn't clear them).

Or would you say it's the extension's responsibility to not set the state more than once for a given TestItem? (Cc @matepek)

Or maybe it is even Catch2's responsibility to accumulate the results for any section that is run more than once?

### PR DESCRIPTION
**Pull request by stefanhaller**
If a test is run multiple times during a single test run, don't allow to set
the state back to a lower one, e.g. if the first test run failed but the second
passed. See #142028 for a reproduction recipe.

Fixes #142028

### CODE REVIEW

File: src/vs/workbench/contrib/testing/common/testResult.ts [hunk 1]
```diff
@@ -379,7 +379,11 @@ export class LiveTestResult implements ITestResult {
 		}
 
 		const index = this.mustGetTaskIndex(taskId);
-		this.fireUpdateAndRefresh(entry, index, state, duration);
+		// Ignore requests to set the state back to a "lower" one, e.g. from
+		// failed back to passed:
+		if (state >= entry.tasks[index].state) {
```
Comment (stefanhaller) [inline src/vs/workbench/contrib/testing/common/testResult.ts:384]: Note that this also prevents the state from going back to running if it is passed or failed. This is not ideal, but it's necessary to solve the issue. In the concrete scenario in the linked issue, the sequence of states is actually running - failed - running - passed.

File: src/vs/workbench/contrib/testing/test/common/testResultService.test.ts [hunk 2]
```diff
@@ -144,21 +144,31 @@ suite('Workbench - Test Results Service', () => {
...
 			]);
+
+			r.updateState(testId, 't', TestResultState.Passed);
+			assert.deepStrictEqual(r.getStateById(testId)?.ownComputedState, TestResultState.Passed);
+
+			r.updateState(testId, 't', TestResultState.Errored);
+			assert.deepStrictEqual(r.getStateById(testId)?.ownComputedState, TestResultState.Errored);
+
+			r.updateState(testId, 't', TestResultState.Passed);
+			assert.deepStrictEqual(r.getStateById(testId)?.ownComputedState, TestResultState.Errored);
```
Comment (stefanhaller) [inline src/vs/workbench/contrib/testing/test/common/testResultService.test.ts:171]: I wasn't sure about the amount of test coverage that's appropriate for this change. Let me know if this is too much or too little.

File: src/vs/workbench/contrib/testing/common/testResult.ts (hunk 1 above)
Comment (connor4312) [reply src/vs/workbench/contrib/testing/common/testResult.ts:384]: Hm, previously we didn't prescribe meaning to the order of states in the enum. Maybe instead we just say errored, failed, and passed are terminal states and then don't update anything after a terminal state is reached?

File: src/vs/workbench/contrib/testing/test/common/testResultService.test.ts (hunk 2 above)
Comment (connor4312) [reply src/vs/workbench/contrib/testing/test/common/testResultService.test.ts:171]: That's fine

File: src/vs/workbench/contrib/testing/common/testResult.ts (hunk 1 above)
Comment (stefanhaller) [reply src/vs/workbench/contrib/testing/common/testResult.ts:384]: That alone wouldn't fix the problem; we need a "stronger" final state to override a "weaker" one. For example, setting passed and then failed needs to result in failed. Setting failed and then passed also needs to result in failed.

So what we'd have to do is something like this:

```
  if (old state is terminal and
    (new state is not terminal or new state is "weaker" than old state)) {
       // ignore the update
    }
  }
```

Does that make sense?

I'm a bit unclear how "skipped" plays into this; but I think skipped should be a terminal state too, and come between passed and failed. (Setting passed/skipped or skipped/passed should result in skipped, but setting failed/skipped or skipped/failed should result in failed.) It's a little academic and I think it can't happen in practice, at least not with the C++ extension, so I don't have a strong opinion on this.

Is it possible to change the order of the enum entries? That would make the implementation a bit easier, if we could put the terminal states at the end in the right order.

Comment (stefanhaller) [reply src/vs/workbench/contrib/testing/common/testResult.ts]: I pushed a new version that does this without reordering the enum entries. I'm not proud of the code, but I'm not an experienced Typescript coder. Let me know what you think.

File: src/vs/workbench/contrib/testing/common/testResult.ts [hunk 3]
```diff
@@ -379,6 +379,24 @@ export class LiveTestResult implements ITestResult {
 		}
 
 		const index = this.mustGetTaskIndex(taskId);
+
+		const terminalStates: { [key in TestResultState]?: number } = {
+			[TestResultState.Passed]: 0,
+			[TestResultState.Skipped]: 1,
+			[TestResultState.Failed]: 2,
+			[TestResultState.Errored]: 3,
+		};
```
Comment (connor4312) [inline src/vs/workbench/contrib/testing/common/testResult.ts:388]: I think this overall looks good, can you move this object into `testingStates.ts`?

Comment (stefanhaller) [reply src/vs/workbench/contrib/testing/common/testResult.ts]: Done, I force-pushed a new version. I decided to rename it to `terminalStatePriorities`, that's a little more precise.

**Review by connor4312 — APPROVED** [review]
Thanks for the PR!
