### PR TITLE
align auxiliary window zooming to main titlebar behavior

### LINKED ISSUE #200435: Aux Window: Respect zoom level in the lightweight windows
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.0
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Set _Window: Zoom Level_ to values other than 0. (2 in the following screenshot)
2. Turn _Window: Command Center_ off
3. Move an opened tab to a new window (Right-click on the tab and select _Move into New Window_)
4. Find the title bar of the new window does not respect the zoom level

image

### PR DESCRIPTION
**Pull request by sbatten**
fixes #200435

@bpasero, feel free to edit to your liking but this is the basic implementation to match behaviors across windows

### CODE REVIEW

File: src/vs/workbench/browser/parts/titlebar/titlebarPart.ts [hunk 1]
```diff
@@ -713,19 +710,19 @@ export class BrowserTitlebarPart extends Part implements ITitlebarPart {
 		return !this.isAuxiliary && this.configurationService.getValue(LayoutSettings.ACTIVITY_BAR_LOCATION) === ActivityBarPosition.TOP;
 	}
 
-	protected get useCounterZoom(): boolean {
+	get hasNoElementsToZoom(): boolean {
```
Comment (bpasero) [inline src/vs/workbench/browser/parts/titlebar/titlebarPart.ts:713]: I think this would be easier to read if we were not using negation. Why not call this `hasZoomableElements`

File: src/vs/workbench/browser/parts/titlebar/titlebarPart.ts [hunk 2]
```diff
@@ -713,19 +710,19 @@ export class BrowserTitlebarPart extends Part implements ITitlebarPart {
...
+		const noMenubar = this.currentMenubarVisibility === 'hidden' || this.currentMenubarVisibility === 'compact' || (!isWeb && isMacintosh);
+		const noCommandCenter = !this.isCommandCenterVisible;
+		const noToolBarActions = !this.layoutControlEnabled && !this.editorActionsEnabled && !this.activityActionsEnabled;
+		return (noMenubar && noCommandCenter && noToolBarActions);
+	}
 
+	get useCounterZoom(): boolean {
```
Comment (bpasero) [inline src/vs/workbench/browser/parts/titlebar/titlebarPart.ts:720]: Nit: I never fully got what "counter zoom" actually means. Can we find a better name?

File: src/vs/workbench/browser/parts/titlebar/titlebarPart.ts [hunk 3]
```diff
@@ -817,4 +815,8 @@ export class AuxiliaryBrowserTitlebarPart extends BrowserTitlebarPart implements
 		const id = AuxiliaryBrowserTitlebarPart.COUNTER++;
 		super(`workbench.parts.auxiliaryTitle.${id}`, getWindow(container), editorGroupsContainer, contextMenuService, configurationService, environmentService, instantiationService, themeService, storageService, layoutService, contextKeyService, hostService, hoverService, editorGroupService, editorService, menuService, keybindingService);
 	}
+
+	override get hasNoElementsToZoom(): boolean {
```
Comment (bpasero) [inline src/vs/workbench/browser/parts/titlebar/titlebarPart.ts:819]: I would add a comment here as to why we actually defer to the main part here.

File: src/vs/workbench/electron-sandbox/parts/titlebar/titlebarPart.ts [hunk 4]
```diff
@@ -324,6 +325,10 @@ export class AuxiliaryNativeTitlebarPart extends NativeTitlebarPart implements I
 		const id = AuxiliaryNativeTitlebarPart.COUNTER++;
 		super(`workbench.parts.auxiliaryTitle.${id}`, getWindow(container), editorGroupsContainer, contextMenuService, configurationService, environmentService, instantiationService, themeService, storageService, layoutService, contextKeyService, hostService, nativeHostService, hoverService, editorGroupService, editorService, menuService, keybindingService);
 	}
+
+	override get hasNoElementsToZoom(): boolean {
```
Comment (bpasero) [inline src/vs/workbench/electron-sandbox/parts/titlebar/titlebarPart.ts:329]: I would add a comment here as to why we actually defer to the main part here.

**Review by bpasero — CHANGES_REQUESTED** [review]

**Comment by sbatten** [comment]
Thanks @bpasero, updated based on feedback. Also, I didn't like that `hasZoomableElements` was lying on the auxiliary title bar parts, so I override `preventZoom` instead which has some minor duplication, but looks better IMO.

**Review by bpasero — APPROVED** [review]

**Comment by bpasero** [comment]
Thank you 🙏
