### PR TITLE
adjust `commandStartX` after polling succeeds

### LINKED ISSUE #195374: [Accessibility] Shell integration character-tracking is buggy
Type: <b>Bug</b>

CC @meganrogge 

1. Launch `Terminal: Create New Terminal in Editor Area`

1. Type `echo hello` and hit Enter

1. Type `echo world` and hit Enter

1. Press UpArrow key

1. Press LeftArrow key

* Note: NVDA and JAWS announce it as "blank."

VS Code version: Code - Insiders 1.84.0-insider (6a7a661757dec1983ff05ef908a2bbb75ce841e0, 2023-10-11T05:34:23.077Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (6.08GB free)|
|Process Argv|--crash-reporter-id b05b88e5-8894-4031-ae34-fa034ebddea9|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (92)</summary>

Extension|Author (truncated)|Version
---|---|---
android-dev-ext|ade|1.3.2
aiprm-lang|AIP|0.0.2
Bookmarks|ale|13.4.2
openscad|Ant|1.2.2
spellright|ban|3.0.118
zoterolatex|bna|0.4.1
mermaid-markdown-syntax-highlighting|bpr|1.5.2
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.52.0
vscode-eslint|dba|2.4.2
vscode-quick-select|dba|0.2.9
vscode-deno|den|3.26.0
gitlens|eam|14.3.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
vscode-google-translate|fun|1.4.13
codespaces|Git|1.15.4
copilot|Git|1.125.0
copilot-chat|Git|0.9.2023101002
remotehub|Git|0.62.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.74.0
overleaf-workshop|iam|0.3.0
cslpreview|igo|0.2.2
easy-snippet|inu|0.6.3
path-autocomplete|ion|1.25.0
latex-workshop|Jam|9.14.1
lilypond-syntax|jea|0.1.1
scheme|jea|0.2.0
better-cpp-syntax|jef|1.17.2
vscode-bard|jim|0.0.10
google-search|kam|0.0.1
vscode-lua-format|Koi|1.3.8
lilypond-formatter|lhl|0.2.3
lilypond-pdf-preview|lhl|0.2.8
lilypond-snippets|lhl|0.1.1
vslilypond|lhl|1.7.3
zotero|mbl|0.1.10
git-graph|mhu|1.30.0
vscode-docker|ms-|1.26.1
black-formatter|ms-|2023.4.1
flake8|ms-|2023.8.0
isort|ms-|2023.11.12711013
python|ms-|2023.18.0
vscode-pylance|ms-|2023.10.10
jupyter|ms-|2023.9.1102792234
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.318.0
remote-ssh|ms-|0.106.5
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.8
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.38.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
js-debug-nightly|ms-|2023.10.917
powershell|ms-|2023.9.5
remote-repositories|ms-|0.40.0
vscode-github-issue-notebooks|ms-|0.0.130
vscode-selfhost-test-provider|ms-|0.3.18
vscode-serial-monitor|ms-|0.10.0
vsliveshare|ms-|1.0.5883
autodocstring|njp|0.6.1
pandocciter|not|0.10.3
shiny-python|Pos|0.1.4
shinyuieditor|pos|0.5.0
quarto|qua|1.103.0
r-debugger|RDe|0.5.4
java|red|1.23.0
vscode-xml|red|0.26.1
r|REd|2.8.2
multi-command|ryu|1.6.0
vscode-deepl|soe|1.0.6
abc-music|sof|0.4.0
lua|sum|3.7.0
latex-utilities|tec|0.4.10
cmake|twx|0.0.17
errorlens|use|3.14.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-arduino|vsc|0.6.0
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.14
vscode-java-test|vsc|0.40.0
vscode-maven|vsc|0.42.0
markdown-all-in-one|yzh|3.5.1
grammarly|znc|0.22.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
ecj1e332:30687743
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
asynctok:30821568
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonmpsinfo:30842935
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809
pythonregdiag:30842812
pythonmypyd1cf:30850306
pythoncet0:30848247

```

</details>

### PR DESCRIPTION
**Pull request by meganrogge**
fix #195374

### CODE REVIEW

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 1]
```diff
@@ -413,6 +415,8 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
 			const line = this._terminal.buffer.active.getLine(this._currentCommand.commandStartMarker.line);
 			if (line) {
 				this._currentCommand.commandStartLineContent = line.translateToString(true);
+				this._logService.debug('command start line content', this._currentCommand.commandStartLineContent);
+				this._logService.debug('command start x', this._currentCommand.commandStartX);
```
Comment (meganrogge) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:419]:
```suggestion
```

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 2]
```diff
@@ -390,6 +390,8 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
 			this._windowsPromptPollingInProcess = false;
 			if (i === 20) {
 				this._logService.debug('CommandDetectionCapability#_handleCommandStartWindows reached max attempts, ', this._cursorOnNextLine(), this._cursorLineLooksLikeWindowsPrompt());
+			} else {
+				this._currentCommand.commandStartX = this._terminal.buffer.active.cursorX;
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:394]: We should use the regex to set the position as it's possible input has occurred

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 3]
```diff
@@ -434,13 +437,13 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
...
-	private _cursorLineLooksLikeWindowsPrompt(): boolean {
+	private _cursorLineLooksLikeWindowsPrompt(): RegExpMatchArray | undefined {
 		const line = this._terminal.buffer.active.getLine(this._terminal.buffer.active.baseY + this._terminal.buffer.active.cursorY);
 		if (!line) {
-			return false;
+			return;
 		}
 		// TODO: fine tune prompt regex to accomodate for unique configurtions.
-		return line.translateToString(true)?.match(/^(PS.+>)|([A-Z]:\\.*>)/) !== null;
+		return line.translateToString(true)?.match(/^(PS.+>)|([A-Z]:\\.*>)/) ?? undefined;
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:446]: Could we use a named capture group for this: `/^(?<prompt>(?:PS.+>)|(?:[A-Z]:\\.*>))/`, then return object describing the prompt (`{ prompt: string } | undefined`)? Then dealing with the regex is all encapsulated within this function.

Comment (meganrogge) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:446]: Yeah, I like the idea of that, but I think it's simpler to just return that capture group, if any?

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 4]
```diff
@@ -432,13 +437,13 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
...
-	private _cursorLineLooksLikeWindowsPrompt(): boolean {
+	private _getWindowsPrompt(): string | undefined {
 		const line = this._terminal.buffer.active.getLine(this._terminal.buffer.active.baseY + this._terminal.buffer.active.cursorY);
 		if (!line) {
-			return false;
+			return;
 		}
 		// TODO: fine tune prompt regex to accomodate for unique configurtions.
-		return line.translateToString(true)?.match(/^(PS.+>)|([A-Z]:\\.*>)/) !== null;
+		return line.translateToString(true)?.match(/^(?<prompt>(?:PS.+>)|(?:[A-Z]:\\.*>))/)?.groups?.prompt;
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:446]: Instead of adding 1 to length, we should change the pwsh part of this to have a space at the end (cmd doesn't have a space at end)

**Review by Tyriar — DISMISSED** [review]

File: src/vs/workbench/services/extensions/common/extensionsApiProposals.ts [hunk 5]
```diff
@@ -12,7 +12,6 @@ export const allApiProposals = Object.freeze({
 	canonicalUriProvider: 'https://raw.githubusercontent.com/microsoft/vscode/main/src/vscode-dts/vscode.proposed.canonicalUriProvider.d.ts',
 	chat: 'https://raw.githubusercontent.com/microsoft/vscode/main/src/vscode-dts/vscode.proposed.chat.d.ts',
 	chatAgents: 'https://raw.githubusercontent.com/microsoft/vscode/main/src/vscode-dts/vscode.proposed.chatAgents.d.ts',
-	chatAgents2: 'https://raw.githubusercontent.com/microsoft/vscode/main/src/vscode-dts/vscode.proposed.chatAgents2.d.ts',
```
Comment (meganrogge) [inline src/vs/workbench/services/extensions/common/extensionsApiProposals.ts:15]: fixing

**Review by Tyriar — DISMISSED** [review]

**Review by rzhao271 — APPROVED** [review]

**Review by rzhao271 — APPROVED** [review]

**Review by rzhao271 — APPROVED** [review]
Another approve
