### PR TITLE
Fix Settings editor layout order

### LINKED ISSUE #145572: Settings box can overlap setting
See here:

image

I have zoomed in a bit to reproduce.

//cc @joaomoreno

### PR DESCRIPTION
**Pull request by rzhao271**
Fixes #145572

Because one specifies a `layout` field when adding views to the splitview, the container layout calls should happen there, instead, otherwise the layouts are happening in the wrong order.

Thanks to @joaomoreno for pointing out what was going on at https://github.com/microsoft/vscode/issues/145572#issuecomment-1079158937!

Screencap demo showing the settings items properly increasing in height

### CODE REVIEW

File: src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts [hunk 1]
```diff
@@ -1517,15 +1519,8 @@ export class SettingsEditor2 extends EditorPane {
 
 	private layoutTrees(dimension: DOM.Dimension): void {
```
Comment (roblourens) [inline src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts:1520]: Could be renamed to avoid confusion

**Review by roblourens — APPROVED** [review]

File: src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts (hunk 1 above)
Comment (rzhao271) [reply src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts]: Renamed to `layoutSplitView`
