### PR TITLE
TerminalTaskSystem: Fix addtion arguments for string command

### LINKED ISSUE #169821: VS Code is still adding `/d /c` to task commands
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2
- OS Version: Windows 11

Steps to Reproduce (on Windows):

1. Have an `npm` task that starts a script.
2. In the User Preferences, set `"terminal.integrated.automationProfile.windows"` as such:
    ```json
    "terminal.integrated.automationProfile.windows": {
        "path": "nu.exe",
        "args": ["-c"],
    },
    ```
    This is an example; this also works with, e.g. `pwsh.exe` / `["-Command"]`.
3. Run the task.
4. VS Code will run `nu.exe -c /d /c yarn run name` rather than `nu.exe -c "yarn run name"`.

This was marked as fixed in #93437, but it isn't. A [workaround](https://github.com/microsoft/vscode/issues/93437#issuecomment-814330206) is given, but is IMO unacceptable. If I modify my shell in _user_ settings, I shouldn't have to modify a `tasks.json` that many users will use, and whose preferred shells are different. More importantly, a single shell can be specified, so `/bin/sh` won't work for users on Windows, and `cmd.exe` / `pwsh.exe` / whatever won't work for users on Linux. This makes `terminal.integrated.automationProfile.*` essentially useless.

Since `terminal.integrated.automationProfile.*` takes an `args` argument, why add unwanted arguments to it? I understand why defaults may be nice (e.g. set `args` to `["-Command"]` when `path` is `pwsh.exe`), but if preferences are explicitly specified, why append new arguments to them if they only work with a single shell?

### PR DESCRIPTION
**Pull request by dylanchu**
Changes:
- Default addtional args is set to empty as "/d /c" is only for `cmd.exe`
- For `cmd.exe`: the "/d" argument should always be the first argument if there are other arguments specified in profiles
- For `cmd.exe`: argument "/k" from profiles will be ignored as it conflicts with "/c"
- For `msys2.cmd` & `msys2_shell.cmd`: "-c" will be added automatically if not specified in profiles

This should fix https://github.com/microsoft/vscode/issues/169821.

### CODE REVIEW

**Comment by dylanchu** [comment]
@microsoft-github-policy-service agree

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 1]
```diff
@@ -1227,59 +1226,24 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
...
-					}
-				} else {
-					if (!shellSpecified) {
-						toAdd.push('/d', '/c');
-					}
 				}
+			}
+			const combinedShellArgs = this._addExecStringFlags(shellSpecified, basename, shellArgs, platform);
+			if (windowsShellArgs) {
+				combinedShellArgs.push('"' + commandLine + '"');
```
Comment (anthonykim1) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1211]: I thought we wanted commandLine to come be BEFORE all of the shell arguments? @dylanchu @meganrogge

Comment (dylanchu) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1211]: Well, no, we didn't. The previous code is like this:
```ts
const combinedShellArgs = this._addAllArgument(toAdd, shellArgs);
combinedShellArgs.push(commandLine);  // also after other arguments
shellLaunchConfig.args = windowsShellArgs ? combinedShellArgs.join(' ') : combinedShellArgs;
```

`commandLine` is the payload command string specified in tasks by `command` field. To pass it to the executable, we need to put it exactly **behind** the _"execute command from string"_ flag (i.e. -c, -Command).

Take `cmd.exe` and `nu.exe` as examples, we would like the combined result to be
```sh
cmd.exe /d /q /c "echo hello"
nu.exe -I . -c "echo hello"
```
instead of
```sh
cmd.exe "echo hello" /d /c 
nu.exe "echo hello" -I . -c
# or
cmd.exe /d /c /q "echo hello" 
nu.exe -c -I . "echo hello"
```
;)

**Comment by dylanchu** [comment]
Looking forward to the approval @anthonykim1 @meganrogge

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 2]
```diff
@@ -1354,9 +1318,44 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
...
+					'nu.exe': ['-c'],
+					'bash.exe': ['-c'],
+					'zsh.exe': ['-c'],
+					'wsl.exe': ['-e'],
+					'msys2.cmd': ['-c'],
+					'msys2_shell.cmd': ['-c'],
+				};
+				return defaults[basename] || [];
+			} else {
+				return ['-c'];
```
Comment (anthonykim1) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1331]: Did we want to check whether shellSpecified is false like before when we add `-c`

```
				if (!shellSpecified) {
 					// Under Mac remove -l to not start it as a login shell.
 					if (platform === Platform.Platform.Mac) {
 						// Background on -l on osx https://github.com/microsoft/vscode/issues/107563
 						// TODO: Handle by pulling the default terminal profile?
 						// const osxShellArgs = this._configurationService.inspect(TerminalSettingId.ShellArgsMacOs);
 						// if ((osxShellArgs.user === undefined) && (osxShellArgs.userLocal === undefined) && (osxShellArgs.userLocalValue === undefined)
 						// 	&& (osxShellArgs.userRemote === undefined) && (osxShellArgs.userRemoteValue === undefined)
 						// 	&& (osxShellArgs.userValue === undefined) && (osxShellArgs.workspace === undefined)
 						// 	&& (osxShellArgs.workspaceFolder === undefined) && (osxShellArgs.workspaceFolderValue === undefined)
 						// 	&& (osxShellArgs.workspaceValue === undefined)) {
 						// 	const index = shellArgs.indexOf('-l');
 						// 	if (index !== -1) {
 						// 		shellArgs.splice(index, 1);
 						// 	}
 						// }
 					}
 					toAdd.push('-c');
 				}
 			}
```

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts (hunk 1 above)
Comment (anthonykim1) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1211]: Thanks for explaining this :)

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts (hunk 2 above)
Comment (dylanchu) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1331]: Yes, and it is the common logic for the three platforms. Several `"if (!shellSpecified)"` checks have been refactored into a single `"if (shellSpecified)"` check at the beginning of the `_addExecStringFlags` method to make the code more concise. When shell is specified, we do not add any additional arguments. This is consistent with the previous logic.

```ts
	private _addExecStringFlags(shellSpecified: boolean, basename: string, configuredShellArgs: string[], platform: Platform.Platform): string[] {
		if (shellSpecified) {
			return Objects.deepClone(configuredShellArgs);
		}
		....
	}
```

Comment (anthonykim1) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1331]: sounds good, we should probably merge this next week since this week is reserved for testing and basically only significant/breaking bug fixes are allowed in

**Comment by anthonykim1** [comment]
Not sure why the CI is failing @dylanchu otherwise LGTM
Looks like something to do with `npm error path /mnt/vss/_work/1/s/node_modules/@vscode/ripgrep` 

Maybe we'd get a better chance if PR comes from upstream branch rather than a fork? It might just be flaky tbh

**Review by anthonykim1 — APPROVED** [review]

**Review by meganrogge — APPROVED** [review]
