### PR TITLE
Add boundary for right arrow typeahead and fix bug with resetting Terminal

### LINKED ISSUE #113857: When using typeahead right arrow should stop at the end of the prompt
Version: 1.53.0-insider
Commit: 4a875e23d20b64504a818834f3fa4c40adb8d480
Date: 2020-12-21T12:32:43.927Z (2 wks ago)
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Darwin x64 20.2.0

holding down right arrow makes the cursor continue past where we expect it to end... screenshot isn't great but imagine holding right arrow and cursor keeps going right
image

It should stop at the "end of the prompt" just like how typeahead stops at the being of the prompt on left arrow.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
This PR fixes #113857

This adds a similar boundary as the left boundary.... but for the right. The boundary will be equal to the furthest we've ever seen the cursor on the active line.

Additionally, I noticed a bug where when you reset/relaunch a terminal like when asked here:
image

~xtermjs appears to get into a bad state. I need to check with @Tyriar about this but it seems like the `buffer` property on `Terminal` gets into a bad state where it always thinks the `baseY` and `cursorY` are 0 (even after spamming ENTER in the terminal). I've workedaround this in this PR.~ I was wrong about this because the problem was that the TypeAheadAddOn still had a reference to the old disposed of `processManager`.

This PR fixes that bug by refactoring the reference of `processManager` out of the `TypeAheadAddOn` because the lifecycle of the `ProcessManager` is not the same as the lifecycle as the AddOn ([processManager is disposed of and recreated](https://github.com/microsoft/vscode/blob/bd8b9d65b2c0d3c2cd3c4ad701faac34a1221ee8/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1202-L1208)). The refactor sets the `OnBeforeDataProcessing` handler right before we create the new process that the processManager will manage

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts [hunk 1]
```diff
@@ -1291,6 +1291,12 @@ export class TypeAheadAddon extends Disposable implements ITerminalAddon {
 		}));
 	}
 
+	// We need a new reference to the Terminal object because the buffer appears to be
+	// corrupted.
+	public reset(terminal: Terminal) {
+		this.timeline = new PredictionTimeline(terminal, this.typeaheadStyle!);
```
Comment (TylerLeonhardt) [inline src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts:1297]: This is the workaround. If not for this, the terminal.buffer used in `onUserData(..)` (which comes from `this.timeline.terminal.buffer`) has values of 0 for all Y props.

File: src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts [hunk 2]
```diff
@@ -1381,16 +1391,22 @@ export class TypeAheadAddon extends Disposable implements ITerminalAddon {
 		// the user gave input, and mark all additions before that as tentative.
 		const actualY = buffer.baseY + buffer.cursorY;
 		if (actualY !== this.lastRow?.y) {
-			this.lastRow = { y: actualY, startingX: buffer.cursorX, charState: CharPredictState.Unknown };
+			this.lastRow = { y: actualY, startingX: buffer.cursorX, endingX: buffer.cursorX, charState: CharPredictState.Unknown };
 		} else {
 			this.lastRow.startingX = Math.min(this.lastRow.startingX, buffer.cursorX);
+			this.lastRow.endingX = Math.max(this.lastRow.endingX, buffer.cursorX);
```
Comment (connor4312) [inline src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts:1397]: This can actually be the cursor x, which will allow left/right navigation in predicted characters

```suggestion
			this.lastRow.endingX = Math.max(this.lastRow.endingX, this.timeline.getCursor(buffer).x);
```

We don't need to do this for startingX, we will never apply a prediction (backspace or left arrow) that goes beyond the startingX, but for endingX the character predictions should increase the navigable area.

**Review by connor4312 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts (hunk 2 above)
Comment (connor4312) [reply src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts:1397]: In better words -- breaking the startingX boundary will always require a round trip to the pty, which will be relatively slow. But the endingX boundary will happen on key type, so we should use the internal cursor position to avoid incorrectly adding tentative boundaries if there are writes which are not yet flushed.

Technically the startingX can use the internal cursor position as well, but that will be about equivalent.

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts (hunk 2 above)
Comment (TylerLeonhardt) [reply src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts:1397]: That change still gives me the behavior of the cursor going beyond where it is allowed.

Comment (TylerLeonhardt) [reply src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts:1397]: Clarification: 

> That change still gives me the behavior of the cursor going beyond where it is allowed

This only happens when I _hold down right arrow_. If I just hit it once in a fresh terminal, everything works as expected.

**Review by Tyriar — COMMENTED** [review]
What was the work around for the buffer/reset problem? It would be great if we could squash the xterm.js bug if it exists

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 3]
```diff
@@ -985,6 +986,9 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 	}
 
 	private _createProcess(): void {
+		if (this._xtermTypeAhead) {
+			this._processManager.onBeforeProcessData(e => this._xtermTypeAhead?.onBeforeProcessData(e));
+		}
```
Comment (TylerLeonhardt) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:991]: Adding this is the fix for relaunch 1/2

File: src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts [hunk 4]
```diff
@@ -1272,7 +1271,6 @@ export class TypeAheadAddon extends Disposable implements ITerminalAddon {
 				}
 			}
 		}));
-		this._register(this.processManager.onBeforeProcessData(e => this.onBeforeProcessData(e)));
```
Comment (TylerLeonhardt) [inline src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts:1275]: Removing this is the fix for relaunch 2/2

**Comment by TylerLeonhardt** [comment]
@Tyriar I _thought_ I posted a nice elegant message about why it wasn't actually xterm.js...........but it's gone. In any case, I've updated the description and left a couple PR comments to call out the specific lines of code that fix it.

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 5]
```diff
@@ -985,6 +986,9 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 	}
 
 	private _createProcess(): void {
+		if (this._xtermTypeAhead) {
+			this._processManager.onBeforeProcessData(e => this._xtermTypeAhead?.onBeforeProcessData(e));
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:990]: Right now it's nice that the only thing inside TerminalInstance relating to type ahead is that it loads the addon, everything else is encapsulated within the addon. A slight improvement to this I think is to create a `this._xtermTypeAhead.setProcessManager` which gets called inside `reuseTerminal`, a little more explicit about why it's there and lets the addon handling the events.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts (hunk 5 above)
Comment (connor4312) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:990]: I actually suggested going this way to Tyler initially. Before my mistaken assumption was that the process manager's lifetime was equivalent to the lifetime of the terminal instance, so I had it injected into the constructor of the addon on which we'd set up listeners. Since it's not actually the case, I thought a better approach would be to make the type ahead addon unaware of the process manager (or generally the way in which pty input is received) and be called into. Lessens the amount of knowledge it carries slightly.

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:990]: My incentives are generally pushing knowledge down into sub components to make `TerminalInstance` smaller/simpler😉, self contained addons that manage everything are great. Feel free to leave this as is, the ideal fix would probably be some event on process manager and making it aware of multiple processes or something. `TerminalInstance.reuseTerminal` and what it does is pretty ugly currently.

**Review by Tyriar — APPROVED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts (hunk 2 above)
Comment (connor4312) [reply src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts:1397]: Oh, I think there's an off-by-one in `addRightNavigating`, it should be `>= this.lastRow!.endingX - 1`, since we're seeing it we can move _ahead_ to that position at which we've never been before.

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts (hunk 5 above)
Comment (TylerLeonhardt) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts]: So I realized I needed some sort of `reset()` method on the AddOn because the `lastRow` needed to be wiped out otherwise the bad behavior would show up after a `reuseTerminal()` if you had something typed on the line.

Since I needed a `reset` anyway, I have it passing in the new reference of `processManager` doing more what @Tyriar suggested here.

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 6]
```diff
@@ -1160,9 +1161,6 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 		this._pressAnyKeyToCloseListener?.dispose();
 		this._pressAnyKeyToCloseListener = undefined;
 
-		// Kill and clear up the process, making the process manager ready for a new process
-		this._processManager.dispose();
-
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1165]: Did this need to be moved?

Comment (TylerLeonhardt) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1165]: It was just so that that one is next to the line that creates the new one. More readable.

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1165]: It's probably fine, but this may reorder when some events happen. Need to be careful of regressions.

**Review by Tyriar — APPROVED** [review]

**Review by connor4312 — APPROVED** [review]
