### PR TITLE
git: Open File command fix on clean tree

### LINKED ISSUE #60174: Open File shortcut does not work if tree is clean
Issue Type: <b>Bug</b>

"Open File" shortcut/command does not work on an opened diff-view file if the working tree becomes clean (e.g. after a commit). Oddly, pressing the button near the top right corner for this action does work.

"Open Changes" in a file doesn't work on a clean tree which is expected, but going from a diff-view back to the file after changes have been committed should be a valid flow IMO.

It'd be nice to have a shortcut by default to toggle between the two.

Repro steps: 
1. Have a dirty working tree
2. Go to the modified file via "Open Changes" button or shortcut
3. Keep that diff-view file open
4. Git commit the changes
5. Attempt to "Open File" via the command pallette (shift+cmd P) -> "Git: Open File", nothing happens
6. Click on the "Open File" button near top right corner. This takes me to the corresponding file.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:40:40.180Z)
OS version: Darwin x64 18.0.0

### PR DESCRIPTION
**Pull request by ParkourKarthik**
Fixes #60174

### CODE REVIEW

File: extensions/git/src/commands.ts [hunk 1]
```diff
@@ -608,6 +608,9 @@ export class CommandCenter {
 
 				uris = resources.map(r => r.resourceUri);
 			}
+			else {
+				uris = [(window.activeTextEditor && window.activeTextEditor.document.uri)] as Uri[];
```
Comment (kumarharsh) [inline extensions/git/src/commands.ts]: If window.activeEditor is undefined, this will cause `uris` to be an array with one element (undefined). Better use the ternary operator.

```
uris = (activeTextEditor ? [activeTextEditor.document.uri] : []) as Uri[];
```

Also you can move the `activeTextEditor` declaration above the uris declaration (close to the start of the `openFile` function), and reuse that.

Comment (ParkourKarthik) [reply extensions/git/src/commands.ts]: Sorry, for the late response. You're right about the check. But I doubt that this command will be invoked without an active editor. Because this command would not be accessible when there is no active editor. Let me know if I'm wrong.

Comment (kumarharsh) [reply extensions/git/src/commands.ts]: Actually the `window.activeTextEditor` is a nullable field (of type `TextEditor | undefined`) hence using the existence check is required, otherwise there can be bugs in the future.

**Comment by joaomoreno** [comment]
Thanks! :beers:
