### PR TITLE
fixes VS Code asks about trust even when the remote is trusted #126542

### LINKED ISSUE #126542: VS Code asks about trust even when the remote is trusted
Steps to Reproduce:

1. Connect to a codespace from desktop
2. In the terminal, create a second folder to add to the workspace
3. `code --add <folderName>`

:bug: => workspace trust kicks in forgetting that the uri being added belongs to the currently resolved workspace which is trusted

### PR DESCRIPTION
**Pull request by sbatten**
This PR fixes #126542

### CODE REVIEW

File: src/vs/workbench/services/workspaces/common/workspaceTrust.ts [hunk 1]
```diff
@@ -389,6 +397,18 @@ export class WorkspaceTrustManagementService extends Disposable implements IWork
 		return isVirtualResource(uri) && uri.scheme !== 'vscode-vfs';
 	}
 
+	private isTrustedByRemote(uri: URI): boolean {
+		if (this.environmentService.remoteAuthority) {
```
Comment (lszomoru) [inline src/vs/workbench/services/workspaces/common/workspaceTrust.ts]: Should be `!this.environmentService.remoteAuthority`

**Review by lszomoru — APPROVED** [review]
Other than the one comment. LGTM!

File: src/vs/workbench/services/workspaces/common/workspaceTrust.ts [hunk 2]
```diff
@@ -528,6 +548,11 @@ export class WorkspaceTrustManagementService extends Disposable implements IWork
 			return { trusted: true, uri };
 		}
 
+		// Uri is trusted automatically by the remote
```
Comment (lszomoru) [inline src/vs/workbench/services/workspaces/common/workspaceTrust.ts:551]: Are we missing the `this.isTrustedVirtualResource()` here?

Comment (sbatten) [reply src/vs/workbench/services/workspaces/common/workspaceTrust.ts:551]: this will be required if file system provider's can provide canonical uris, but they cannot at the current time
