### PR TITLE
activityBar.activeBorder at workbench.colorCustomizations has no effect. #179229

### LINKED ISSUE #179229: `activityBar.activeBorder` at `workbench.colorCustomizations` has no effect
Version: 1.78.0-insider
Commit: cbf35328c8357175b9cd747823f39ade987c3d3c
Date: 2023-04-04T18:48:48.802Z
Electron: 22.4.3
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 20.6.0
Sandboxed: Yes

ProductName:	macOS
ProductVersion:	11.7.5
BuildVersion:	20G1225

Steps to Reproduce:

1.  Write the following setting to `settings.json`

```json
    "workbench.colorCustomizations": {
        "activityBar.activeBorder": "#ff0000"
    }
```
2. The setting has no effect. On VS Code v1.77, the color of the active border at the activity bar changes.

### PR DESCRIPTION
**Pull request by aeschli**
Fixes https://github.com/microsoft/vscode/issues/179229

### CODE REVIEW

**Review by alexr00 — APPROVED** [review]

File: src/vs/workbench/browser/parts/activitybar/activitybarActions.ts [hunk 1]
```diff
@@ -628,6 +628,15 @@ registerAction2(
 
 registerThemingParticipant((theme, collector) => {
 
+	const activityBarActiveBorderColor = theme.getColor(ACTIVITY_BAR_ACTIVE_BORDER);
```
Comment (bpasero) [inline src/vs/workbench/browser/parts/activitybar/activitybarActions.ts:631]: @aeschli why exactly can this not be expressed via CSS?

Comment (aeschli) [reply src/vs/workbench/browser/parts/activitybar/activitybarActions.ts:631]: I do not fully understand it but the dom node containing the icon (a :`before`) does not see the css color variable definitions.
