### PR TITLE
Adds tests for injected text events & fixes caching bug.

### LINKED ISSUE #127412: testing for injected text eventing

### PR DESCRIPTION
**Pull request by hediet**
This PR fixes #127412

### CODE REVIEW

File: src/vs/editor/common/model/textModel.ts [hunk 1]
```diff
@@ -1468,7 +1470,7 @@ export class TextModel extends Disposable implements model.ITextModel {
 					this.getOffsetAt(new Position(firstEditLineNumber, 1)),
 					this.getOffsetAt(new Position(lastInsertedLineNumber, this.getLineMaxColumn(lastInsertedLineNumber))),
 					0,
-					0
+					this._versionId
```
Comment (alexdima) [inline src/vs/editor/common/model/textModel.ts:1471]: Very nice!!!

**Review by alexdima — APPROVED** [review]
Very nice find to increase the version id before, such that decorations ranges benefit from caching!
