### PR TITLE
Fixes source control remember tree collapsed state

### LINKED ISSUE #89145: Source Control select default setting show/hide untracked changes tab
I'd like to request the ability to set a default value for whether the "untracked changes"-tab is expanded or minimized. 

As it is now, the tab is always open to show the files. I'd like to be able to change my default to minimized to reduce clutter and noise when looking at the changes I actually care about.

### PR DESCRIPTION
**Pull request by jeanp413**
This PR fixes #89145

### CODE REVIEW

File: src/vs/base/browser/ui/tree/compressedObjectTreeModel.ts [hunk 1]
```diff
@@ -49,11 +49,11 @@ export function compress<T>(element: ICompressedTreeElement<T>): ITreeElement<IC
...
 		}
 
-		element = children[0];
-
-		if (element.incompressible) {
+		let childElement: ICompressedTreeElement<T> = children[0];
+		if (childElement.incompressible) {
 			break;
 		}
+		element = childElement;
```
Comment (jeanp413) [inline src/vs/base/browser/ui/tree/compressedObjectTreeModel.ts]: I was getting an incorrect behavior when an ISCMResourceGroup contained just one element. This changes fix that.
scmrememberstatebug

**Comment by Trass3r** [comment]
This has been rotting for more than 8 months.
Some review and reaction on this would be nice @microsoft @joaomoreno.

File: src/vs/workbench/contrib/scm/browser/scmViewPane.ts [hunk 2]
```diff
@@ -783,6 +798,8 @@ class ViewModel {
 
 		configurationService.onDidChangeConfiguration(this.onDidChangeConfiguration, this, this.disposables);
 		this.onDidChangeConfiguration();
+
+		this.disposables.add(this.tree.onDidChangeCollapseState(() => this.updateViewState()));
```
Comment (joaomoreno) [inline src/vs/workbench/contrib/scm/browser/scmViewPane.ts:802]: This might be too expensive. We really only need to snapshot the view state whenever the view goes invisible or when the workbench shuts down.

**Review by joaomoreno — APPROVED** [review]
@jeanp413 Once again, fantastic work. Thanks a lot of keeping the changes up to date and for your patience! 🙏 

Apart from the inline comments I found other issues:

- When using the tree view mode, new folders appeared as collapsed by default. For that reason I've changed the state to store collapsed folders, instead of expanded ones.

I've addressed my own feedback.
