### PR TITLE
Fix #180162. Turn off design mode after searching.

### LINKED ISSUE #180162: Cell outputs sometimes become editable
## Environment data

-   VS Code version: 1.77.1
-   Jupyter Extension version: v2023.3.1201040234
-   Python Extension version: v2023.6.0
-   OS: macOS 13.3.1
-   Python and/or Anaconda version: 3.9.13
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Actual behaviour

Cell outputs sometimes become editable. This doesn't seem to be on purpose

bug

## Steps to reproduce:

I'm not sure, but here are hints:
* It's been happening with several different Python notebooks on several occasions in the last week or so.
* It doesn't seem related to a specific notebook. However, just creating a new notebook or opening an existing notebook doesn't immediately exhibit the bug.
* When the bug occurs, closing and re-opening the notebook makes it go away.
* Some things I may have done with the notebook before the bug was triggered: running cells, debugging cells, committing to git, changing between multiple notebooks.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

This log contains private info, please ask if you need anything specific.

</p>
</details>

### PR DESCRIPTION
**Pull request by rebornix**

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts [hunk 1]
```diff
@@ -1225,6 +1225,8 @@ async function webviewPreloads(ctx: PreloadContext) {
 
 		viewModel.toggleDragDropEnabled(currentOptions.dragAndDropEnabled);
 
+		document.designMode = 'Off';
```
Comment (mjbvz) [inline src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts:1228]: Just in case, should this in a `finally` block of the `try/catch` above. That way we disable design mode even if an error is thrown

**Review by mjbvz — APPROVED** [review]
