### PR TITLE
console error when issue reporter fails

### LINKED ISSUE #205729: Show a debugger warning if extensionID is not found
Testing #205587

image

For this, I put an invalid `extensionId`, and as expected, the `Extension` field in the issue reporter is not set to a specific extension. However, I'd appreciate a warning log in the debug console that warns devs that they have an invalid `extensionId`

### LINKED ISSUE #205731: Issue reporter doesn't do anything on invalid URI
Testing #205587

I had the arg
```
uri: vscode.Uri.parse('https://github.com/microsoft/sdfgsdfgsdfgsdfg')
```

For `workbench.action.openIssueReporter` and clicking "Create on GitHub" did nothing. I would expect an error to log in the console for this so that devs know what has happened.

### PR DESCRIPTION
**Pull request by justschen**
partially fixes https://github.com/microsoft/vscode/issues/205731 and fixes https://github.com/microsoft/vscode/issues/205729

todo in debt: if reporter fails for any reason, ie ban, or github limit exceeded, etc, show warning in UI

### CODE REVIEW

File: src/vs/workbench/services/issue/electron-sandbox/issueService.ts [hunk 1]
```diff
@@ -185,6 +185,13 @@ export class NativeIssueService implements IWorkbenchIssueService {
 			githubAccessToken
 		}, dataOverrides);
 
+		if (issueReporterData.extensionId) {
+			const extensionExists = extensionData.some(extension => extension.id === issueReporterData.extensionId);
+			if (!extensionExists) {
```
Comment (rzhao271) [inline src/vs/workbench/services/issue/electron-sandbox/issueService.ts:190]: Should the function return early in this case?

Comment (justschen) [reply src/vs/workbench/services/issue/electron-sandbox/issueService.ts:190]: I think i didn't want to `throw` here because we have a `selected extension` option, where no extension is selected. If we throw, nothing happens, if we allow it to go thru, it goes into this state with the console error

Screenshot 2024-02-21 at 4 09 32 PM

**Review by rzhao271 — APPROVED** [review]
