### PR TITLE
fix overlapping decoration

### LINKED ISSUE #144597: Placeholder decoration overlaid with success/error decoration
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Enable shell integration
2. Run a successful command
3. :bug: see that success/error decorations are rendered on top of placeholder decorations
image

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #144597

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 1]
```diff
@@ -168,7 +168,7 @@ export class DecorationAddon extends Disposable implements ITerminalAddon {
 		}
 		decoration.onRender(element => {
 			decoration.onDispose(() => this._decorations.delete(decoration.marker.id));
-			if (beforeCommandExecution && !this._placeholderDecoration) {
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:171]: `this._placeholderDecoration` was still defined (though disposed of), so the else was happening and a decoration was getting added

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:171]: Should we have this here too?

```ts
if (!this._placeholderDecoration.isDisposed) {
  this._placeholderDecoration.dispose();
}
```

Should probably have a helper to do that for us in order to prevent future issues like this?

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 2]
```diff
@@ -162,13 +161,14 @@ export class DecorationAddon extends Disposable implements ITerminalAddon {
 		if (!command.marker) {
 			throw new Error(`cannot add a decoration for a command ${JSON.stringify(command)} with no marker`);
 		}
+		this._placeholderDecoration?.dispose();
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:164]: anytime a new decoration is registered, we want to dispose of the placeholder.

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:164]: Let's also set to undefined to free the now invalid decoration

**Review by Tyriar — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]
