### PR TITLE
Alias `Thenable` to `PromiseLike`

### LINKED ISSUE #192385: Thenable incorrectly infers argument types of chained `.then()` calls with an error handler
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.81.0
- OS Version: Pop!_OS 22.04

Steps to Reproduce:

1. Install `@types/vscode`
2. Create the following TypeScript file
   ```ts
   import 'vscode'

   declare let promise: Promise<string>
   promise
     .then(
       (result) => result,
       (error) => 42
     )
     .then((stringOrNumber) => {
       // `stringOrNumber` is correctly inferred as `string | number`
     })

   declare let promiseLike: PromiseLike<string>
   promiseLike
     .then(
       (result) => result,
       (error) => 42
     )
     .then((stringOrNumber) => {
       // `stringOrNumber` is correctly inferred as `string | number`
     })

   declare let thenable: Thenable<string>
   thenable
     .then(
       (result) => result,
       (error) => 42
     )
     .then((stringOrNumber) => {
       // `stringOrNumber` should be or type `string | number`, but it’s incorrectly inferred as `string`
     })
   ```
3. Observe how the type of `stringOrNumber` is inferred incorrectly.

Alternatively, open [this TypeScript playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAcgG4GcDGEAmBTBAoPHNAGwEMps5jt4woIRgVsAuOABXseYB4UYowAHYBzAHx46DJtjxw4AOhgALbEIAUc+XHUUUAV2IwAlHAC8YuHsMwANFvnrsUelFMW4AFgBMW41qVVDXV+QVEAeSgAOX0QACNnd0sAbwc4AHp0uAADUOERSJj452y4JjgMF2w0GGIATzKhADNnCkw4UhQcvNE4AB84IViEqGytAF9-QmqyCioaOClubAAZYABrVg4uGTXNvgF8iSXdjdl5QLVNbR1rIySrbAMjexunF2gHnz8AlSuQw4RaLDRLmFJpTLdQEFYHFUZlLqVCg1eqNFpVdqdKFhET9QYg0YTKZEWaUajwP5CUhxahsAAqQWp1AOOIklKZ50UlOu2l0TxsDzudjS71cX188n8F25AJxhQJD1SN0huWh8rhpRQygghnaCTg0DgMDqYEoqpxeKGGtscDi+ngwBggEwCLrCJHVWoNYTotodLrm-JjeSTPBAA).

The issue originates from https://github.com/microsoft/vscode/pull/192047#issuecomment-1704752680

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #192385

While fixing some typing issues with `Thenable`, I noticed I was duplicating the typings for `PromiseLike`. This PR updates `Thenable` to be an alias for `PromiseLike`

### CODE REVIEW

File: extensions/microsoft-authentication/src/betterSecretStorage.ts [hunk 1]
```diff
@@ -240,11 +240,8 @@ export class BetterTokenStorage<T> {
 				},
 				err => {
 					Logger.error(err);
-					resolve(tokens);
-				}).then(resolve, err => {
-					Logger.error(err);
-					resolve(tokens);
-				});
+					return tokens;
+				}).then(resolve);
```
Comment (mjbvz) [inline extensions/microsoft-authentication/src/betterSecretStorage.ts:244]: @TylerLeonhardt The previous code could call resolve twice:

1. First promise (`this._secretStorage.get(this.keylistKey)` throws, going into the error handler which calls `resolve`
2. Because the error handler returns a value, we not continue on to the next `.then`
3. This then calls `resolve` again

Please look closely at this change to make sure I have not accidentally changed the behavior

File: src/typings/thenable.d.ts [hunk 2]
```diff
@@ -9,13 +9,4 @@
...
-	/**
-	* Attaches callbacks for the resolution and/or rejection of the Promise.
-	* @param onfulfilled The callback to execute when the Promise is resolved.
-	* @param onrejected The callback to execute when the Promise is rejected.
-	* @returns A Promise for the completion of which ever callback is executed.
-	*/
-	then<TResult>(onfulfilled?: (value: T) => TResult | Thenable<TResult>, onrejected?: (reason: any) => TResult | Thenable<TResult>): Thenable<TResult>;
-	then<TResult>(onfulfilled?: (value: T) => TResult | Thenable<TResult>, onrejected?: (reason: any) => void): Thenable<TResult>;
-}
+interface Thenable<T> extends PromiseLike<T> { }
```
Comment (mjbvz) [inline src/typings/thenable.d.ts:12]: Using this instead of `type Thenable<T> = PromiseLike<T>` to avoid duplicate type declarations errors between `vscode.d.ts` and `thenable.d.ts`

**Comment by mjbvz** [comment]
Missed that this was already attempted with #192047. This PR is more conservative in that it keeps `Thenable` but just updates its definition by using the typings from `PromiseLike`

**Review by TylerLeonhardt — APPROVED** [review]

**Review by jrieken — APPROVED** [review]
