### PR TITLE
Async data tree node: improve node preservation

### LINKED ISSUE #69950: Data tree node not found
Any os

1. Take the insiders which is not to become stable
2. Open explorer, have autoReveal: true, open some file which is a bit nested
3. Collapse all in explorer, Refresh in explorer -> notice error in console

So does not repro in our candidate to be shipped. Only happens after your tree refactoring thus I believe that is the cause of this issue. First giving to you @joaomoreno 

```
ERR Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at WorkbenchAsyncDataTree.getDataNode (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:416:23)
    at WorkbenchAsyncDataTree.<anonymous> (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:325:35)
    at Generator.next (<anonymous>)
    at file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:10:71
    at new Promise (<anonymous>)
    at __awaiter (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:6:12)
    at WorkbenchAsyncDataTree.expand (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:317:20)
    at Array.<anonymous> (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/files/browser/views/explorerView.js:405:81)
    at next (file:///Users/isidor/Development/vscode/out/vs/base/common/async.js:281:59)
    at thenHandler (file:///Users/isidor/Development/vscode/out/vs/base/common/async.js:287:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### PR DESCRIPTION
**Pull request by isidorn**
Fixes https://github.com/Microsoft/vscode/issues/69950

### CODE REVIEW

File: src/vs/workbench/contrib/files/browser/views/explorerView.ts [hunk 1]
```diff
@@ -507,27 +507,35 @@ export class ExplorerView extends ViewletPanel {
...
-			this.tree.setFocus([fileStat]);
-			this.tree.setSelection([fileStat]);
-		});
+					this.tree.setFocus([item]);
+					this.tree.setSelection([item]);
+				} else {
+					await this.tree.expand(item);
+					let found = false;
+					item.children.forEach(async child => {
+						if (!found && isEqualOrParent(resource, child.resource)) {
```
Comment (Kedstar99) [inline src/vs/workbench/contrib/files/browser/views/explorerView.ts]: Sorry for the random comment, I was just kind of curious about this pattern here.

https://stackoverflow.com/questions/37576685/using-async-await-with-a-foreach-loop
https://dev.to/burkeholland/asyncawait-and-the-foreach-pit-of-despair-2267
https://codeburst.io/javascript-async-await-with-foreach-b6ba62bbf404

Researching online seems to indicate this may be a slight antipattern with recommendations to use Promises.all or just a simple for loop with await. Is that necessarily the case here?

Comment (isidorn) [reply src/vs/workbench/contrib/files/browser/views/explorerView.ts]: Here it does not matter, since there is only one promise which will be waited on I believe. So we don't even have to await it in practice.

Comment (joaomoreno) [reply src/vs/workbench/contrib/files/browser/views/explorerView.ts]: I thought the same once I saw it, ended up simplifying that code a lot.

Comment (isidorn) [reply src/vs/workbench/contrib/files/browser/views/explorerView.ts]: Thanks for simplifying!
