### PR TITLE
try to ignore history on editor open for quicksearch

### LINKED ISSUE #205135: Quick Search should omit history
Steps to Reproduce:

1. Use quick search and look at results from different files.  (`%<text-here>` in quick open)
2. `esc`
3. Go back in history (either using command center or 'Go Back' command).
4. Notice that all of the files navigated to during quick search are in the history :bug:

Especially if the user looks at a lot of files, they probably don't want that info in their history.

### PR DESCRIPTION
**Pull request by andreamah**
Related to https://github.com/microsoft/vscode/issues/204853
Fixes https://github.com/microsoft/vscode/issues/205135

cc @bpasero

### CODE REVIEW

**Review by justschen — APPROVED** [review]

**Comment by bpasero** [comment]
@andreamah sorry for the late response, I should have been the reviewer here, can you add me for future PRs in this area? I will post a follow up PR with some cleanup and thoughts.

File: src/vs/workbench/test/browser/workbenchTestServices.ts [hunk 1]
```diff
@@ -545,6 +545,7 @@ export class TestMenuService implements IMenuService {
 export class TestHistoryService implements IHistoryService {
 
 	declare readonly _serviceBrand: undefined;
+	declare shouldIgnoreActiveEditorChange: boolean;
```
Comment (bpasero) [inline src/vs/workbench/test/browser/workbenchTestServices.ts:548]: I think this is not very safe, this would not actually put the property on the class as far as I know but just declare it as type to be there.

File: src/vs/workbench/test/common/workbenchTestServices.ts [hunk 2]
```diff
@@ -149,6 +149,7 @@ export class TestStorageService extends InMemoryStorageService {
 export class TestHistoryService implements IHistoryService {
 
 	declare readonly _serviceBrand: undefined;
+	declare shouldIgnoreActiveEditorChange: boolean;
```
Comment (bpasero) [inline src/vs/workbench/test/common/workbenchTestServices.ts:152]: ...same here

File: src/vs/workbench/contrib/search/browser/quickTextSearch/textSearchQuickAccess.ts [hunk 3]
```diff
@@ -116,10 +122,15 @@ export class TextSearchQuickAccess extends PickerQuickAccessProvider<ITextSearch
...
 				this.editorViewState.set();
-				// open it
-				this._editorService.openEditor({
-					resource: item.match.parent().resource,
-					options: { preserveFocus: true, revealIfOpened: true, ignoreError: true, selection: item.match.range() }
+				const itemMatch = item.match;
+				this.editorSequencer.queue(async () => {
+					// disable and re-enable history service so that we can ignore this history entry
+					this._historyService.shouldIgnoreActiveEditorChange = true;
+					await this._editorService.openEditor({
```
Comment (bpasero) [inline src/vs/workbench/contrib/search/browser/quickTextSearch/textSearchQuickAccess.ts:129]: Opening an editor can fail with an error thrown and so this would leave the history in ignore-mode, without ever setting it back. At least a `try/finally` is needed.
