### PR TITLE
add quick fix telemetry

### LINKED ISSUE #162969: Telemetry for terminal quick fixes
If we sent the following telemetry around quick fixes we could validate our high confidence guesses and tweak accordingly:

When a particular quick fix occurred, which of the following happened
- (Best) The quick fix was executed
- (Good) The proposed quick fix was run manually instead of via quick fix
- (Bad) A different command than what was proposed was run
- (Worse) The quick fix dropdown was shown and a different command was run

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #162969

@Tyriar tested using the logs and LGTM, but could use your testing as well

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 1]
```diff
@@ -99,7 +129,27 @@ export class TerminalQuickFixAddon extends Disposable implements ITerminalAddon,
 		if (!terminal || !commandDetection) {
 			return;
 		}
-		this._register(commandDetection.onCommandFinished(command => this._resolveQuickFixes(command)));
+		this._register(commandDetection.onCommandFinished(command => {
+			if (this._fixesAvailable) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:133]: I think we should attach an ID for the quick fix in question, that way we know which ones are successful and which aren't. Just make sure it's a static ID for each quick fix, not the actual command that was run.

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 2]
```diff
@@ -120,9 +170,20 @@ export class TerminalQuickFixAddon extends Disposable implements ITerminalAddon,
...
 		this._quickFixes = fixes;
-		onDidRunQuickFix(() => this._disposeQuickFix());
+		this._register(this.onDidRequestRerunCommand(() => {
+			this._logService.debug(QuickFixCommandResultTelemetryEvent.QuickFixExecuted);
+			this._telemetryService?.publicLog2<{ classification: 'SystemMetaData'; purpose: 'FeatureInsight' }>(QuickFixCommandResultTelemetryEvent.QuickFixExecuted);
+			this._fixesAvailable = false;
+		}));
+		this._register(onDidRunQuickFix(() => {
+			this._logService.debug(QuickFixCommandResultTelemetryEvent.QuickFixExecuted);
+			this._telemetryService?.publicLog2<{ classification: 'SystemMetaData'; purpose: 'FeatureInsight' }>(QuickFixCommandResultTelemetryEvent.QuickFixExecuted);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:183]: Won't this double report? I forgot what `onDidRequestRerunCommand` is for

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 3]
```diff
@@ -99,7 +129,27 @@ export class TerminalQuickFixAddon extends Disposable implements ITerminalAddon,
...
 			return;
 		}
-		this._register(commandDetection.onCommandFinished(command => this._resolveQuickFixes(command)));
+		this._register(commandDetection.onCommandFinished(command => {
+			if (this._fixesAvailable) {
+				if (this._fixesShown) {
+					if (this._expectedCommands?.includes(command.command)) {
+						this._logService.debug(QuickFixCommandResultTelemetryEvent.QuickFixExecutedManually);
+						this._telemetryService?.publicLog2<{ classification: 'SystemMetaData'; purpose: 'FeatureInsight' }>(QuickFixCommandResultTelemetryEvent.QuickFixExecutedManually);
+					} else {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:138]: Won't this also fire when a quick fix is executed via the dropdown? A quick fix should fire `onCommandFinished` as well

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts (hunk 3 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:138]: not sure what you mean - would suggest testing it w debug level logging on bc does what i'm expecting

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts (hunk 2 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:183]: doesn't double report based on my testing. `onDidRunQuickFix` only gets fired for quick fixes without a type or of type `open`

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 4]
```diff
@@ -99,7 +129,27 @@ export class TerminalQuickFixAddon extends Disposable implements ITerminalAddon,
...
+					this._fixesShown = false;
+				} else {
+					this._logService.debug(QuickFixCommandResultTelemetryEvent.QuickFixIgnored);
+					this._telemetryService?.publicLog2<{ classification: 'SystemMetaData'; purpose: 'FeatureInsight' }>(QuickFixCommandResultTelemetryEvent.QuickFixIgnored);
+				}
+			} else {
+				this._expectedCommands = undefined;
+			}
+			this._resolveQuickFixes(command);
+			this._fixesAvailable = false;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:151]: I think `_fixesAvailable` and `_expectedCommands` serve the same purpose and we could just use `_expectedCommands` instead (_fixesAvailable = true = !!_expectedCommands)

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts (hunk 2 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:183]: It does, it was being sent 3 times when I ran a quick fix:

image

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 5]
```diff
@@ -99,7 +129,27 @@ export class TerminalQuickFixAddon extends Disposable implements ITerminalAddon,
...
-		this._register(commandDetection.onCommandFinished(command => this._resolveQuickFixes(command)));
+		this._register(commandDetection.onCommandFinished(command => {
+			if (this._fixesAvailable) {
+				if (this._fixesShown) {
+					if (this._expectedCommands?.includes(command.command)) {
+						this._logService.debug(QuickFixCommandResultTelemetryEvent.QuickFixExecutedManually);
+						this._telemetryService?.publicLog2<{ classification: 'SystemMetaData'; purpose: 'FeatureInsight' }>(QuickFixCommandResultTelemetryEvent.QuickFixExecutedManually);
+					} else {
+						this._logService.debug(QuickFixCommandResultTelemetryEvent.QuickFixWrong);
+						this._telemetryService?.publicLog2<{ classification: 'SystemMetaData'; purpose: 'FeatureInsight' }>(QuickFixCommandResultTelemetryEvent.QuickFixWrong);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:140]: There's a little nuance here, opening the link is reported as wrong even if you open it manually. Should we just not send this for the PR link? This might just work itself out if we merge `_fixesAvailable` and `_expectedCommands`

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 6]
```diff
@@ -99,7 +129,27 @@ export class TerminalQuickFixAddon extends Disposable implements ITerminalAddon,
 		if (!terminal || !commandDetection) {
 			return;
 		}
-		this._register(commandDetection.onCommandFinished(command => this._resolveQuickFixes(command)));
+		this._register(commandDetection.onCommandFinished(command => {
+			if (this._fixesAvailable) {
+				if (this._fixesShown) {
+					if (this._expectedCommands?.includes(command.command)) {
+						this._logService.debug(QuickFixCommandResultTelemetryEvent.QuickFixExecutedManually);
+						this._telemetryService?.publicLog2<{ classification: 'SystemMetaData'; purpose: 'FeatureInsight' }>(QuickFixCommandResultTelemetryEvent.QuickFixExecutedManually);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:137]: This didn't seem to work for me, running `--set-upstream` manually showed it as ignored, not executed manually:

image

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts (hunk 2 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:183]: It might be a listener not being disposed, after a bunch of testing it's reporting it a lot more:

image

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts (hunk 6 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:137]: if you didn't click on the lightbulb, that's what we consider `ignored`. `executedManually` only differs in that the lightbulb was consulted

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:137]: maybe instead of these 4 states it would be better if we had one for if the quick fix was interacted with / shown and another for if the next command run matched one of our suggestions

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts (hunk 4 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:151]: This was necessary because there won't be expected commands in the `open` case

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts (hunk 6 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:137]: Oh that confused me a little, how about instead it's a single command but we add whether the quick fix was opened as a common property to all the events? That way there's one executedManually but we can filter whether or not we care about whether it was opened.

**Comment by meganrogge** [comment]
to do: info -> debug

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 7]
```diff
@@ -130,26 +108,16 @@ export class TerminalQuickFixAddon extends Disposable implements ITerminalAddon,
...
-					this._fixesShown = false;
-				} else {
-					this._logService.debug(QuickFixCommandResultTelemetryEvent.QuickFixIgnored);
-					this._telemetryService?.publicLog2<{ classification: 'SystemMetaData'; purpose: 'FeatureInsight' }>(QuickFixCommandResultTelemetryEvent.QuickFixIgnored);
-				}
-			} else {
+			if (this._expectedCommands) {
+				const info = `terminal/quick-fix/command/fixes-shown:${this._fixesShown}/expected-command:${this._expectedCommands.includes(command.command)}`;
+				this._logService.info(info);
+				this._telemetryService?.publicLog2<{ classification: 'SystemMetaData'; purpose: 'FeatureInsight' }>(info);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:114]: We still want the events to be called something like `terminal/quick-fix/command/fixes-shown`, but you can add additional metadata to the event which is filterable. Here's an example:

https://github.com/microsoft/vscode/blob/c5aa167e9b1c260f2b26b5fb3d93683ca5484b7e/src/vs/code/electron-main/app.ts#L1211-L1217

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 8]
```diff
@@ -29,7 +29,16 @@ import type { ITerminalAddon } from 'xterm-headless';
...
 
-
+type QuickFixResultTelemetryEvent = {
+	fixesShown: boolean;
+	expectedCommand: boolean;
+};
+type QuickFixClassification = {
+	owner: 'meganrogge';
+	fixesShown: { classification: 'SystemMetaData'; purpose: 'FeatureInsight'; comment: 'Whether the fixes were shown by the user' };
+	expectedCommand: { classification: 'SystemMetaData'; purpose: 'FeatureInsight'; comment: 'If the command that was executed matched a quick fix suggested one' };
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts]: `wasQuickFixCommand`? `expectedCommand` makes me think it's the command string, not a bool

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 9]
```diff
@@ -143,8 +159,14 @@ export class TerminalQuickFixAddon extends Disposable implements ITerminalAddon,
 		this._quickFixes = fixes;
 		this._register(onDidRunQuickFix((id) => {
 			const info = `terminal/quick-fix/${id}`;
-			this._logService.debug(info);
-			this._telemetryService?.publicLog2<{ classification: 'SystemMetaData'; purpose: 'FeatureInsight' }>(info);
+			this._logService.debug(info, {
+				fixesShown: this._fixesShown,
+				expectedCommand: this._expectedCommands?.includes(command.command) || false,
+			});
+			this._telemetryService?.publicLog2<QuickFixResultTelemetryEvent, QuickFixClassification>(info, {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts]: This will introduce many new events that would all need to be documented, instead the `quickFixId` should be done similar to `providerId` here:

https://github.com/microsoft/vscode/blob/db4c864178ea96ae85480c9a8996b033db372aa5/src/vs/editor/contrib/suggest/browser/suggestController.ts#L463-L464

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts (hunk 8 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts]: `ranQuickFixCommand`?

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 10]
```diff
@@ -108,6 +145,8 @@ export class TerminalQuickFixAddon extends Disposable implements ITerminalAddon,
 		}));
 	}
 
+
+
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:149]:
```suggestion
```

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 11]
```diff
@@ -177,11 +229,12 @@ export function getQuickFixesForCommand(
 	quickFixOptions: Map<string, ITerminalQuickFixOptions[]>,
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:229]: add an id to terminalquickfixoptions and use that

**Review by Tyriar — APPROVED** [review]
