### PR TITLE
Fix candidate port finding (more async, better timing)

### LINKED ISSUE #112843: Port scanning executes even if auto forward ports is off
We have been seeing a bunch of remote issues where the remote extension host burns a lot of CPU. I think it is caused by our port scanning code, which executes even if the setting `"remote.autoForwardPorts"` is false. See https://github.com/microsoft/vscode/blob/768cd308c620936ccb79a94ae80cb6edf7d214ed/src/vs/workbench/api/node/extHostTunnelService.ts#L160-L171

Possible issues:
* https://github.com/microsoft/vscode/issues/112581 / https://github.com/redhat-developer/vscode-java/issues/1743
* https://github.com/microsoft/vscode-remote-release/issues/4205
* https://github.com/microsoft/vscode/issues/112466#issuecomment-744869515

Other:
* https://github.com/microsoft/vscode-remote-release/issues/4204
* https://github.com/microsoft/vscode-remote-release/issues/4201
* https://github.com/microsoft/vscode-remote-release/issues/4211
* https://github.com/microsoft/vscode-remote-release/issues/4186
* ? https://github.com/microsoft/vscode/issues/112457
* ? https://github.com/microsoft/vscode/issues/112367
* ? https://github.com/microsoft/vscode-remote-release/issues/4210
* ~~https://github.com/microsoft/vscode/issues/112797~~

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #112843

### CODE REVIEW

File: src/vs/workbench/api/node/extHostTunnelService.ts [hunk 1]
```diff
@@ -237,16 +250,18 @@ export class ExtHostTunnelService extends Disposable implements IExtHostTunnelSe
...
 		for (let childName of procChildren) {
 			try {
 				const pid: number = Number(childName);
 				const childUri = resources.joinPath(URI.file('/proc'), childName);
-				const childStat = fs.statSync(childUri.fsPath);
+				const childStat = await pfs.stat(childUri.fsPath);
 				if (childStat.isDirectory() && !isNaN(pid)) {
-					const cwd = fs.readlinkSync(resources.joinPath(childUri, 'cwd').fsPath);
-					const cmd = fs.readFileSync(resources.joinPath(childUri, 'cmdline').fsPath, 'utf8');
+					const cwd = await promisify(fs.readlink)(resources.joinPath(childUri, 'cwd').fsPath);
```
Comment (connor4312) [inline src/vs/workbench/api/node/extHostTunnelService.ts:263]: By the way, since Node 12 there's a `promises` export from `fs`, I usually do `import { promises as fs } from 'fs'` 🙂
