### PR TITLE
fix: fallback to editor hover if can't evaluate debug expression - (#169151)

### LINKED ISSUE #169151: "Debug: Show Hover" does nothing when triggered from shortcut (but works with mouse)
Sometimes I leave the debugger running when editing code and making changes. The one thing which fails to work during this period is triggering hover from a keybinding (ctrl/cmd+k, ctrl/cmd + i). Whenever I trigger this over a red squiggly line nothing happens. I understand this is because the debugger overrides that keybinding when running but 90% of the time it's replaced with nothing.

Is it possible to fall back through to the normal hover action if im not on a line currently being inspected? This must be possible because mouse hover does exactly this.

This seems to be the UX with mouse hover:
1. When a breakpoint has triggered I get the debug info on hover.
2. When a breakpoint hasn't triggered the hover falls back to normal hover information

Triggering hover with keybindings:
1. When a breakpoint has triggered I get the debug info on hover.
2. When a breakpoint hasn't triggered nothing happens.

This issue is asking for the keyboard shortcut (ctrl/cmd+k, ctrl/cmd + i) to match up with the mouse hover.

### PR DESCRIPTION
**Pull request by Viijay-Kr**
Closes #169151

As proposed in this comment https://github.com/microsoft/vscode/issues/169151#issuecomment-1351805554, If a expression cannot be evaluated within the active debug context , the normal editor hover is shown.

The above action applies to both keyboard and muse initiated hover action.

### CODE REVIEW

File: src/vs/workbench/contrib/debug/browser/debugHover.ts [hunk 1]
```diff
@@ -201,6 +201,7 @@ export class DebugHoverWidget implements IContentWidget {
 		const expression = await this.debugHoverComputer.evaluate(session);
```
Comment (roblourens) [inline src/vs/workbench/contrib/debug/browser/debugHover.ts:201]: Can this be done by returning a result value rather than passing in a callback? Also, should the editor hover be shown in the cases above too? It also seems weird to show it when the hover is canceled which this change will do.

**Review by roblourens — COMMENTED** [review]
Sorry for the slow review

File: src/vs/workbench/contrib/debug/browser/debugHover.ts (hunk 1 above)
Comment (Viijay-Kr) [reply src/vs/workbench/contrib/debug/browser/debugHover.ts:201]: If I got it right , by returning `result` you mean change the return type of this function to `Promise<void | 'some_other_value'>` ? 
?

Comment (Viijay-Kr) [reply src/vs/workbench/contrib/debug/browser/debugHover.ts:206]: Actually I got the context of your comment , I created a enum with some statuses that indicates the state of the debug expression.

1. When not available , (when the expression is not available / no session available)
2. When the existing expression did not change (when evaluated in the same range)
3. When it gets cancelled ? (Although I'm not sure from where does it get cancelled)

Only when a debug hover expression is not available should it fallback to editor hover.

wdyt ?

File: src/vs/workbench/contrib/debug/browser/debugEditorContribution.ts [hunk 2]
```diff
@@ -376,10 +374,21 @@ export class DebugEditorContribution implements IDebugEditorContribution {
 		const sf = this.debugService.getViewModel().focusedStackFrame;
 		const model = this.editor.getModel();
 		if (sf && model && this.uriIdentityService.extUri.isEqual(sf.source.uri, model.uri) && !this.altPressed) {
-			return this.hoverWidget.showAt(position, focus);
+			return this.hoverWidget.showAt(position, focus).then(state => {
```
Comment (roblourens) [inline src/vs/workbench/contrib/debug/browser/debugEditorContribution.ts:377]: Use async/await?

File: src/vs/workbench/contrib/debug/browser/debugHover.ts [hunk 3]
```diff
@@ -178,30 +178,35 @@ export class DebugHoverWidget implements IContentWidget {
...
+		}
+
+		if (cancellationSource.token.isCancellationRequested) {
+			this.hide();
+			return DEBUG_HOVER_EXPRESSION.CANCELLED;
 		}
 
 		const expression = await this.debugHoverComputer.evaluate(session);
-		if (cancellationSource.token.isCancellationRequested || !expression || (expression instanceof Expression && !expression.available)) {
+		if (!expression || (expression instanceof Expression && !expression.available)) {
```
Comment (roblourens) [inline src/vs/workbench/contrib/debug/browser/debugHover.ts:207]: You still need to check for cancellation after the await above, it could have been cancelled while that expression was being awaited

File: src/vs/workbench/contrib/debug/common/debug.ts [hunk 4]
```diff
@@ -1183,6 +1183,13 @@ export const enum BreakpointWidgetContext {
 	LOG_MESSAGE = 2
 }
 
+// Debug Hover States
+export const enum DEBUG_HOVER_EXPRESSION {
```
[the remark this answers is not in the document]
Comment (roblourens) [reply src/vs/workbench/contrib/debug/common/debug.ts:1187]: And it should just be in debugHover.ts

[the remark this answers is not in the document]
Comment (roblourens) [reply src/vs/workbench/contrib/debug/common/debug.ts:1187]: Or if this just represents error cases, the name should represent that too

**Review by roblourens — DISMISSED** [review]

File: src/vs/workbench/contrib/debug/common/debug.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (Viijay-Kr) [reply src/vs/workbench/contrib/debug/common/debug.ts]: > Or if this just represents error cases, the name should represent that too
The enum represents the state of the hover at the position and I don't see any erroring possibilities.

File: src/vs/workbench/contrib/debug/browser/debugHover.ts [hunk 5]
```diff
@@ -178,30 +184,37 @@ export class DebugHoverWidget implements IContentWidget {
...
 		}
 
 		const result = await this.debugHoverComputer.compute(position, cancellationSource.token);
 		if (this.isVisible() && !result.rangeChanged) {
-			return;
+			return ShowDebugHoverResult.NOT_CHANGED;
 		}
 
-		if (!result.range || cancellationSource.token.isCancellationRequested) {
+		if (!result.range) {
```
Comment (roblourens) [inline src/vs/workbench/contrib/debug/browser/debugHover.ts:202]: Now you've removed this check of the cancel token. We should _always_ check the cancellation token after doing an async operation. Otherwise we might do unnecessary work or make side-effects after the operation has already been cancelled.

Comment (Viijay-Kr) [reply src/vs/workbench/contrib/debug/browser/debugHover.ts:202]: Ah apologies for that. I did not realise that. I now get it why the token is being passed around async functions.

So here is what I think could be the flow of statements

1. After computing the result , firstly if there was a cancellation requested then we return `ShowDebugHoverResult.CANCELLED`
2. Else, if there is no range associated with the result , then we return `ShowDebugHoverResult.NOT_AVAILABLE` 
3. Else, if the result is visible and the range hasn't changed since the previous show then we return `ShowDebugHoverResult.NOT_CHANGED`
4. After evaluating the expression, if there is a cancellation requested then we return `ShowDebugHoverResult.CANCELLED`
5. Finally when there is no expression available , we return `ShowDebugHoverResult.NOT_AVAILABLE`.

Screenshot 2023-03-28 at 20 28 01

Comment (roblourens) [reply src/vs/workbench/contrib/debug/browser/debugHover.ts:202]: Yeah, I think that is correct

File: src/vs/workbench/contrib/debug/browser/debugHover.ts [hunk 6]
```diff
@@ -178,30 +184,38 @@ export class DebugHoverWidget implements IContentWidget {
...
 		}
-
-		if (!result.range || cancellationSource.token.isCancellationRequested) {
+		if (!result.range) {
 			this.hide();
-			return;
+			return ShowDebugHoverResult.NOT_AVAILABLE;
+		}
+		if (this.isVisible() && !result.rangeChanged) {
+			this.hide();
```
Comment (roblourens) [inline src/vs/workbench/contrib/debug/browser/debugHover.ts:207]: Previously, this case did not hide the hover, now you are hiding it.

Comment (Viijay-Kr) [reply src/vs/workbench/contrib/debug/browser/debugHover.ts:207]: According to the current logic , `this.hide()` is relevant here isn't it ?

Comment (Viijay-Kr) [reply src/vs/workbench/contrib/debug/browser/debugHover.ts:207]:
```suggestion
```

**Review by roblourens — APPROVED** [review]
Just pushed a commit to restore some deleted newlines, and overall it looks great, thanks for the contribution!

**Review by joyceerhl — APPROVED** [review]

**Comment by Viijay-Kr** [comment]
> Just pushed a commit to restore some deleted newlines, and overall it looks great, thanks for the contribution!

Thanks for the great review
