### PR TITLE
Avoid doing a hit test if the line is empty or if the mouse is after the line width

### LINKED ISSUE #208262: Safari: clicking to the right of some text puts cursor at the front
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.88.0-insider in Safari
- OS Version: macOS

Steps to Reproduce:

1. In _Safari_ open https://insiders.vscode.dev
2. create a file with:
```
asdf
asdf
asdf
asdf
```
3. click to the right of any `asdf`
4. 🐛 the cursor goes to the beginning of the line not the end

https://github.com/microsoft/vscode/assets/2644648/da460347-23f7-4cc4-bdcf-ae1058a9df92

This does not repro in stable vscode.dev

### PR DESCRIPTION
**Pull request by alexdima**
Fixes #208262

### CODE REVIEW

File: src/vs/editor/browser/controller/mouseTarget.ts [hunk 1]
```diff
@@ -404,26 +408,53 @@ abstract class BareHitTestRequest {
...
+	public readonly hitTestResult = new Lazy(() => MouseTargetFactory.doHitTest(this._ctx, this));
+	private _useHitTestTarget: boolean;
+	private _targetPathCacheElement: HTMLElement | null = null;
+	private _targetPathCacheValue: Uint8Array = new Uint8Array(0);
+
+	public get target(): HTMLElement | null {
+		if (this._useHitTestTarget) {
+			return this.hitTestResult.value.hitTarget;
+		}
+		return this._eventTarget;
```
Comment (hediet) [inline src/vs/editor/browser/controller/mouseTarget.ts:421]: I think `_useHitTestTarget` is not needed:
```suggestion
		return this._eventTarget ?? this.hitTestResult.value.hitTarget;
```

Comment (hediet) [reply src/vs/editor/browser/controller/mouseTarget.ts:421]: Oh, nevermind, `_useHitTestTarget` is changed later.

**Review by hediet — APPROVED** [review]
