### PR TITLE
use theme service for issue reporter

### LINKED ISSUE #224600: Opening issue reporter breaks product icons
Type: <b>Bug</b>

Repro:
1. Have aux window issue reporter enabled
2. Open issue reporter

:bug: => product icons disappear in activity bar and status bar

VS Code version: Code - Insiders 1.93.0-insider (3b27f1f74bc09fe2e2068997fcd42768be44a4e3, 2024-08-02T05:03:53.254Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (14.75GB free)|
|Process Argv|--folder-uri file:///d%3A/Source/github/microsoft/vscode --enable-proposed-api monekoluv.issue-paste-formatter --log info --crash-reporter-id 6da3720d-fb86-47a1-91f3-ebd9f5fa64fd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
tsl-problem-matcher|amo|0.6.2
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
ruff|cha|2024.36.0
simple-icons|com|0.1.6
esbuild-problem-matchers|con|0.0.3
vscode-eslint|dba|3.0.11
gitlens|eam|2024.8.205
prettier-vscode|esb|10.4.0
codespaces|Git|1.17.2
copilot|Git|1.219.1019
copilot-chat|Git|0.19.2024080201
remotehub|Git|0.63.2024061801
vscode-pull-request-github|Git|0.95.2024080212
vscode-drawio|hed|1.6.6
vscode-tree-sitter-query|jri|0.0.5
rainbow-csv|mec|3.12.0
fluent-icons|mig|0.0.18
issue-paste-formatter|mon|0.0.1
vscode-language-pack-es|MS-|1.92.2024073109
vscode-language-pack-fr|MS-|1.92.2024073109
vscode-language-pack-pt-BR|MS-|1.92.2024073109
csdevkit|ms-|1.9.53
csharp|ms-|2.41.26
vscode-dotnet-runtime|ms-|2.1.1
black-formatter|ms-|2024.3.12071014
debugpy|ms-|2024.11.2024080201
python|ms-|2024.13.2024080201
vscode-pylance|ms-|2024.7.104
sarif-viewer|MS-|3.4.4
jupyter|ms-|2024.8.2024080201
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.381.0
remote-ssh|ms-|0.113.2024072315
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
azure-repos|ms-|0.39.2024061901
debug-value-editor|ms-|0.1.0
extension-test-runner|ms-|0.0.11
hexeditor|ms-|1.10.0
mock-debug|ms-|0.52.0
remote-explorer|ms-|0.5.2024070409
remote-repositories|ms-|0.41.2024022202
remote-server|ms-|1.6.2024070809
ts-file-path-support|ms-|0.9.0
vscode-github-issue-notebooks|ms-|0.0.130
vscode-js-profile-flame|ms-|1.0.9
web-editors|ms-|0.1.0
color-highlight|nau|2.8.0
material-icon-theme|PKi|5.8.0
excalidraw-editor|pom|3.7.4
vscode-thunder-client|ran|2.24.13
vscode-yaml|red|1.15.0
vscode-sort-json|ric|1.20.0
even-better-toml|tam|0.19.2
fugio|Tyl|0.0.6
luna-paint|Tyr|0.16.0
explorer|vit|1.0.6
vscode-scope|yiw|0.0.34

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vsc_aacf:30263846
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
01bff139:31013167
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
nb_pkg_only:31057982
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
1iic9185:31091668
flighttreat:31105043
wkspc-onlycs-t:31106322
nativeloc2:31106923
cf971741:31108168

```

</details>

### PR DESCRIPTION
**Pull request by justschen**
fixes https://github.com/microsoft/vscode/issues/224600

### CODE REVIEW

File: src/vs/workbench/contrib/issue/electron-sandbox/issueReporterService.ts [hunk 1]
```diff
@@ -18,11 +18,11 @@ import { ThemeIcon } from 'vs/base/common/themables';
 import { URI } from 'vs/base/common/uri';
 import { localize } from 'vs/nls';
 import { isRemoteDiagnosticError } from 'vs/platform/diagnostics/common/diagnostics';
+import { IIssueMainService, IProcessMainService, OldIssueReporterData, OldIssueReporterExtensionData, OldIssueReporterStyles, OldIssueReporterWindowConfiguration, OldIssueType } from 'vs/platform/issue/common/issue';
```
Comment (justschen) [inline src/vs/workbench/contrib/issue/electron-sandbox/issueReporterService.ts:21]: this change is just a result of `organizeImports`

**Review by andreamah — DISMISSED** [review]

**Review by lramos15 — APPROVED** [review]
