### PR TITLE
alexr00/issue115337

### LINKED ISSUE #115337: If tooltip is falsy after `resolveTreeItem` is called, then the tooltip gets stuck as 'Loading...'
Issue Type: <b>Bug</b>

In the past, if the tree item `tooltip` was falsy, the `label` would be used instead on hover.

[This code](https://github.com/microsoft/vscode/blob/5b75a42575fd85c3a9f69bec76bd1afe7c2dcb33/src/vs/base/browser/ui/iconLabel/iconLabel.ts#L262-L269) makes it so that if the tree item's `tooltip` is falsy after calling `resolveTreeItem`, then instead of following the old behavior and using `label`, it will stick as 'Loading...' forever.

Instead, if `resolvedTooltip` is falsy, it should fall back to `label` to most closely resemble prior behavior.

VS Code version: Code - Insiders 1.53.0-insider (7b0cfdd04ad530a9c8d782c618afd79290be3d64, 2021-01-27T08:59:32.031Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (16.38GB free)|
|Process Argv|--crash-reporter-id edba2bce-ac1c-499b-b3ff-28d400cc9143|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
vscode-docker|ms-|1.9.1
csharp|ms-|1.23.8
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.156.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.53.2
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.5

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt600:30247031

```

</details>

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #115337

### CODE REVIEW

File: src/vs/base/browser/ui/iconLabel/iconLabel.ts [hunk 1]
```diff
@@ -259,7 +259,7 @@ export class IconLabel extends Disposable {
 						};
 						IconLabel.adjustXAndShowCustomHover(hoverOptions, mouseX, hoverDelegate, isHovering);
 
-						const resolvedTooltip = await tooltip(tokenSource.token);
+						const resolvedTooltip = (await tooltip(tokenSource.token)) ?? (!isString(markdownTooltip) ? markdownTooltip.markdownNotSupportedFallback : undefined);
 						if (resolvedTooltip) {
```
Comment (bpasero) [inline src/vs/base/browser/ui/iconLabel/iconLabel.ts:263]: Is it intentional that it will not work when the empty string is returned? Wouldn't it then still show "Loading..."?

Comment (alexr00) [reply src/vs/base/browser/ui/iconLabel/iconLabel.ts:263]: Good catch, yes it will still show "Loading...". I think in this case would should simply hide the hover since none was provided.

**Review by bpasero — APPROVED** [review]
I think this is better now. A follow up item is maybe to not just have a generic `hideHover` method but correlate the operation to an identifier. Now it seems we are resolving a hover (which can take a long time) and then eventually might call `hideHover` even though I maybe opened another hover. I wonder if this could accidentally close a different hover.
