### PR TITLE
`relativeFileDirname` gives empty string when the Dirname equals to current working directory

### LINKED ISSUE #108437: `relativeFileDirname` gives empty string when the Dirname equals to current working directory
- VSCode Version:
- OS Version:
Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:10:52.432Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. I use C++ extension and configured `tasks.json` to use task to get my source code compiled.
The part of the `tasks.json` relatives to this issue is basically like this:
```json
      "command": "clang++",
      "args": [
        "-g",
        "${relativeFile}",
        "-o",
        "${relativeFileDirname}/${fileBasenameNoExtension}.exe"
      ]
```
2. VSCode now synthesizes this command as `clang++ -g tmp.cpp -o /tmp.exe`,
rather than previously in VSCode version 1.49.3, `clang++ -g tmp.cpp -o ./tmp.exe`.
3. The compiler will get `permission denied` for trying to write to root folder, of course.

Should  `relativeFileDirname` still be `.` under such cases or not?

Currently I reverted to 1.49.3.

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #108437

### CODE REVIEW

File: src/vs/workbench/services/configurationResolver/common/variableResolver.ts [hunk 1]
```diff
@@ -278,7 +278,8 @@ export class AbstractVariableResolverService implements IConfigurationResolverSe
 						}
 						const dirname = paths.dirname(getFilePath());
 						if (folderUri || argument) {
-							return paths.relative(this.fsPath(getFolderUri()), dirname);
+							const relative = paths.relative(this.fsPath(getFolderUri()), dirname);
+							return relative.length === 0 ? '.' : relative;
```
Comment (alexr00) [inline src/vs/workbench/services/configurationResolver/common/variableResolver.ts:282]: We used to call `paths.normalize(relative)`, which does the conversion from empty string to '.'. Since it isn't safe to call `normalize` on a path that could come from a remote, I removed it. In this case though, we still need the '.' instead of empty string.

Comment (aeschli) [reply src/vs/workbench/services/configurationResolver/common/variableResolver.ts:282]: There's potential for refactoring here as `fsPath` and `path.relative` should not be used on remote URIs.

But for the fix release the change is minimal and good.

**Review by aeschli — APPROVED** [review]
