### PR TITLE
"input" variables prevent compound configuration from launching more than one session

### LINKED ISSUE #141514: "input" variables prevent compound configuration from launching more than one session
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: macOS 12.1 (ARM64)

I can't get more than two launch configurations to run at the same time. I can run the rest of the configurations afterwards and everything works (debugging, etc.). StopAll will also only close the two configs that were successfully launched.

I haven't found any mention in the documentation that this is limited to two launch configurations. I've only seen that two are used in every explanation or tutorial about this feature.

Steps to Reproduce:

1. Add multiple launch configurations in multi-root workspace inside of project roots.
2. Add launch configurations to compounds in .code-workspace file
3. Start debugging
4. Only two of the many compound configurations will run

Examples:

tasks.json

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "dotnet: build bc1",
            "detail": "Build the Bounded Context 1 WebAPI Project",
            "type": "shell",
            "command": "dotnet build -p:Config=Debug ./src/Presentation/WebAPI",
            "problemMatcher": ["$msCompile"],
            "presentation": {
                "echo": true,
                "reveal": "silent",
                "focus": false,
                "panel": "dedicated",
                "showReuseMessage": true,
                "clear": true
            }
        }
    ]
}
```

launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch API (Debug)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "dotnet: build bc1",
            "program": "${workspaceFolder}/src/Presentation/WebAPI/bin/Debug/net6.0/BoundedContext1.dll",
            "args": [],
            "cwd": "${workspaceFolder}/src/Presentation/WebAPI",
            "stopAtEntry": false,
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "\\bNow listening on:\\s+https?://\\S+:(\\S+)",
                "uriFormat": "http://localhost:%s/swagger"
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Debug"
            }
        }
    ]
}
```

Root.code-workspace
```json
{
    "launch": {
        "version": "0.2.0",
        "compounds": [
            {
                "name": "Launch Full (with Docker)",
                "configurations": [
                    "Launch WebUI",
                    {
                        "folder": "Bounded Context 1",
                        "name": "Launch API (Debug)"
                    },
                    {
                        "folder": "Bounded Context 2",
                        "name": "Launch API (Debug)"
                    },
                    {
                        "folder": "Bounded Context 3",
                        "name": "Launch API (Debug)"
                    }
                ],
                "preLaunchTask": "docker: up db/mail",
                "stopAll": true
            }
        ]
    }
}
```

### PR DESCRIPTION
**Pull request by roblourens**
Fixes #141514

### CODE REVIEW

File: src/vs/workbench/services/configurationResolver/browser/baseConfigurationResolverService.ts [hunk 1]
```diff
@@ -346,9 +349,9 @@ export abstract class BaseConfigurationResolverService extends AbstractVariableR
 						}
 					}
 					const pickOptions: IPickOptions<PickStringItem> = { placeHolder: info.description, matchOnDetail: true, ignoreFocusLost: true };
-					return this.quickInputService.pick(picks, pickOptions, undefined).then(resolvedInput => {
+					return this.userInputAccessQueue.queue(() => this.quickInputService.pick(picks, pickOptions, undefined)).then(resolvedInput => {
```
Comment (alexr00) [inline src/vs/workbench/services/configurationResolver/browser/baseConfigurationResolverService.ts:352]: The `this.commandService.executeCommand` on line 364 should also be queued since a command can trigger quick input.

**Review by alexr00 — CHANGES_REQUESTED** [review]
Thanks for the PR!

**Review by alexr00 — APPROVED** [review]
