### PR TITLE
for diff editors, resolve the modified editor to allow run tests in c…

### LINKED ISSUE #205998: Run Tests in Current file/Run Test at Cursor / Do nothing when File is in Diff view
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.86.2
- OS Version:  macOS Sonoma 14.3.1

Steps to Reproduce:

1.  Open a test file with detected tests.
2.  Make an edit.
3.  In Source Control View, select the file to open the file in Diff view
4. From the command palette, select `Test: Run tests in Current File`/`Test: Run test at Cursor`

Expected:
The tests in the current file are run

Actual:
Nothing happens.

image

### PR DESCRIPTION
**Pull request by mahmoudsalah1993**
…urrent file or run test at cursor to work

Resolves #205998 

When having a test file with detected tests in a diff view, the File shows test icons, but running `Run tests in current file` or `Run tests at cursor` from the command palette or shortcut, both commands fail silently. Instead resolve the underlying modified editor to run the appropriate test.

### CODE REVIEW

File: src/vs/workbench/contrib/testing/browser/testExplorerActions.ts [hunk 1]
```diff
@@ -983,11 +983,15 @@ abstract class ExecuteTestAtCursor extends Action2 {
 	public async run(accessor: ServicesAccessor) {
 		const editorService = accessor.get(IEditorService);
 		const activeEditorPane = editorService.activeEditorPane;
-		const activeControl = editorService.activeTextEditorControl;
+		let activeControl = editorService.activeTextEditorControl;
```
Comment (connor4312) [inline src/vs/workbench/contrib/testing/browser/testExplorerActions.ts:986]: This PR assumes that the modified editor in the diff editor is always the one where tests are present, but this may not be the case. I think we should probably use `editorService.activeEditor`, since that will be the editor that focus is currently in, and then there's no need to check `isDiffEditor`

File: src/vs/workbench/contrib/testing/browser/testExplorerActions.ts [hunk 2]
```diff
@@ -983,11 +983,15 @@ abstract class ExecuteTestAtCursor extends Action2 {
...
 		if (!activeEditorPane || !activeControl) {
 			return;
 		}
 
+		if (isDiffEditor(activeControl)) {
```
Comment (connor4312) [inline src/vs/workbench/contrib/testing/browser/testExplorerActions.ts:991]: This PR assumes that the modified editor in the diff editor is always the one where tests are present, but this may not be the case.

I think we may want to use`ICodeEditorService.getActiveCodeEditor()` instead. The thing to check for there is whether the editor is embedded, via `if (editor instanceof EmbeddedCodeEditorWidget) { editor = editor.getParentEditor() }`

Comment (mahmoudsalah1993) [reply src/vs/workbench/contrib/testing/browser/testExplorerActions.ts]: Done. Removed checks for isCodeEditor given the change now uses activeCodeEditor.

**Comment by connor4312** [comment]
Lgtm however there is a compilation error

**Review by connor4312 — APPROVED** [review]

**Review by aeschli — APPROVED** [review]
