### PR TITLE
Remove angle brackets when checking the scheme

### LINKED ISSUE #132974: Syntax Highlighting and Opening Link error in Markdown file
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: MacOS 10.14.3

Steps to Reproduce:

1. Copy & paste `[foo-bar](<https://foo-bar.com/foo-bar(foo-bar).ext>)` into markdown file
2. Press <kbd>⌘</kbd> and click the link

[Click here, It works with GitHub's markdown syntax](<https://foo-bar.com/foo-bar(foo-bar).ext>)

### PR DESCRIPTION
**Pull request by codingLogan**
# Summary
When the link is being checked for a known scheme in a markdown file, the scheme wasn't being recognized when encased inside of angle brackets < and >.  This change strips the link of beginning and ending < and > so the scheme can be properly checked.

This only removes the brackets during the scheme check if the initial link provided actually has angle brackets.  Otherwise it will just use the given link as usual.

## Issue
This PR fixes #132974

## Testing (Currently Released Build)
Begin editing a markdown file, and enter the following text into the file.  If you attempt to `command + click` or `control + click` the link in the markdown file you are editing, it won't open in a browser.  (note it will open from the markdown preview, just not the editable markdown file)
```
[Bad - Opens file](<http://google.com>)
```

## Testing (Fixes)
With the code changes applied, you can enter the same text in a markdown file, and the link will open up as expected in the browser.  (and it will still open from the markdown preview).

### CODE REVIEW

File: extensions/markdown-language-features/src/util/links.ts [hunk 1]
```diff
@@ -22,13 +22,29 @@ const knownSchemes = [
 ];
 
 export function getUriForLinkWithKnownExternalScheme(link: string): vscode.Uri | undefined {
-	if (knownSchemes.some(knownScheme => isOfScheme(knownScheme, link))) {
+	const cleanLink = stripAngleBrackets(link);
```
Comment (mjbvz) [inline extensions/markdown-language-features/src/util/links.ts:25]: Let's move the angle bracket stripping logic to the caller instead ( `parseLink`)  since angle brackets are a detail of the document link syntax

File: extensions/markdown-language-features/src/util/links.ts [hunk 2]
```diff
@@ -22,13 +22,29 @@ const knownSchemes = [
...
 
 	return undefined;
 }
 
+/* Used to strip brackets from the markdown link
+	<http://example.com> will be transformed to
+	http://example.com
+*/
+export function stripAngleBrackets(link: string) {
+	const bracketMatcher = /^<(.*)>$/;
```
Comment (mjbvz) [inline extensions/markdown-language-features/src/util/links.ts:38]: [nit] Use `.replace` instead to simplify this

**Review by mjbvz — CHANGES_REQUESTED** [review]
Thanks for taking a look. Just a few minor points of feedback

File: extensions/markdown-language-features/src/util/links.ts (hunk 1 above)
Comment (codingLogan) [reply extensions/markdown-language-features/src/util/links.ts:25]: I'm looking to move that over to `parseLink` instead 👍

File: extensions/markdown-language-features/src/util/links.ts (hunk 2 above)
Comment (codingLogan) [reply extensions/markdown-language-features/src/util/links.ts:38]: Absolutely, I agree the match made it complex.

File: extensions/markdown-language-features/src/util/links.ts (hunk 1 above)
Comment (codingLogan) [reply extensions/markdown-language-features/src/util/links.ts]: I moved the function and the call of it to `extensions\markdown-language-features\src\features\documentLinkProvider.ts`.  If that is not what you intended, please let me know

File: extensions/markdown-language-features/src/util/links.ts (hunk 2 above)
Comment (codingLogan) [reply extensions/markdown-language-features/src/util/links.ts]: This has now been simplified, please see the most recent changes 👍

**Comment by codingLogan** [comment]
@mjbvz I made those changes you suggested, and thank you for reviewing the PR.  Let me know of any further changes you may think of.
