### PR TITLE
fix: increase titlebar height for macOS 26

### LINKED ISSUE #279769: macOS Tahoe traffic light alignment is off
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version:

> 1.106.3 (Universal)
> Commit: bf9252a2fb45be6893dd8870c0bf37e2e1766d61
> Date: 2025-11-25T22:28:18.024Z
> Electron: 37.7.0
> ElectronBuildId: 12781156
> Chromium: 138.0.7204.251
> Node.js: 22.20.0
> V8: 13.8.258.32-electron.0
> OS: Darwin arm64 25.1.0

- OS Version: macOS 26.1 (25B78)

Steps to Reproduce:

1. Launch Visual Studio Code on macOS Tahoe

On macOS Tahoe, the window controls (traffic light) of the Visual Studio Code window are no longer centered vertically in the window's title bar.

**On Sonoma:**
Image

Here, the window controls are perfectly vertically centered.

**On Tahoe:**
Image

As illustrated by the crosshairs I've added to the image here, the window controls are two points, or four pixels, too far to the top:

Image

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes https://github.com/microsoft/vscode/issues/279769

### CODE REVIEW

File: src/vs/base/common/platform.ts [hunk 1]
```diff
@@ -275,10 +275,6 @@ export const isSafari = !!(!isChrome && (userAgent && userAgent.indexOf('Safari'
 export const isEdge = !!(userAgent && userAgent.indexOf('Edg/') >= 0);
 export const isAndroid = !!(userAgent && userAgent.indexOf('Android') >= 0);
 
-export function isBigSurOrNewer(osVersion: string): boolean {
```
Comment (deepak1556) [inline src/vs/base/common/platform.ts:278]: We have dropped support for Big Sur, refs https://github.com/microsoft/vscode/issues/268375

File: src/vs/workbench/electron-browser/parts/titlebar/titlebarPart.ts [hunk 2]
```diff
@@ -272,13 +272,7 @@ export class NativeTitlebarPart extends BrowserTitlebarPart {
 		super.layout(width, height);
 
 		if (useWindowControlsOverlay(this.configurationService)) {
-
-			// When the user goes into full screen mode, the height of the title bar becomes 0.
-			// Instead, set it back to the default titlebar height for Catalina users
-			// so that they can have the traffic lights rendered at the proper offset.
-			// Ref https://github.com/microsoft/vscode/issues/159862
-
-			const newHeight = (height > 0 || this.bigSurOrNewer) ? Math.round(height * getZoomFactor(getWindow(this.element))) : this.macTitlebarSize;
```
Comment (deepak1556) [inline src/vs/workbench/electron-browser/parts/titlebar/titlebarPart.ts:281]: The workaround for catalina from https://github.com/microsoft/vscode/pull/160919/files is no longer needed

**Review by bpasero — APPROVED** [review]

**Review by bpasero — CHANGES_REQUESTED** [review]
Red CI

**Review by bpasero — DISMISSED** [review]

**Review by bpasero — APPROVED** [review]

**Comment by StefanXhunga** [comment]
Thank you for your support
