### PR TITLE
Fix issue with clicking between active tabs

### LINKED ISSUE #213160: Tabs: clicking between active tabs results in 4 `redrawTabSelectedActiveAndDirty`
When I log a stack trace in `redrawTabSelectedActiveAndDirty`, I see 3 calls when I click on the active tab, even when the tab is already active:

```
multiEditorTabsControl.js:1263 redrawTabSelectedActiveAndDirty Error
    at MultiEditorTabsControl.redrawTabSelectedActiveAndDirty (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/multiEditorTabsControl.js:1263:60)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/multiEditorTabsControl.js:480:22
    at MultiEditorTabsControl.doWithTab (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/multiEditorTabsControl.js:563:17)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/multiEditorTabsControl.js:550:22
    at Array.forEach (<anonymous>)
    at MultiEditorTabsControl.forEachTab (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/multiEditorTabsControl.js:543:72)
    at MultiEditorTabsControl.updateEditorSelections (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/multiEditorTabsControl.js:479:18)
    at MultiRowEditorControl.updateEditorSelections (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/multiRowEditorTabsControl.js:132:44)
    at EditorTitleControl.updateEditorSelections (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/editorTitleControl.js:118:36)
    at EditorGroupView.onDidChangeEditorSelection (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:648:31)
    at EditorGroupView.onDidGroupModelChange (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:432:26)
    at UniqueContainer.value (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:415:66)
    at Emitter._deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:926:26)
    at Emitter._deliverQueue (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:937:22)
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:960:22)
    at EditorGroupModel.doSetSelection (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/common/editor/editorGroupModel.js:488:36)
    at EditorGroupModel.setSelection (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/common/editor/editorGroupModel.js:474:18)
    at EditorGroupModel.openEditor (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/common/editor/editorGroupModel.js:227:22)
    at EditorGroupView.doOpenEditor (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:941:64)
    at EditorGroupView.openEditor (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:866:25)
    at handleClickOrTouch (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/multiEditorTabsControl.js:660:46)
    at HTMLDivElement.<anonymous> (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/browser/parts/editor/multiEditorTabsControl.js:672:100)
```

For some reason a `onDidChangeEditorSelection` selection event is fired always?

### PR DESCRIPTION
**Pull request by benibenj**
Previously, when clicking between active tabs, the `redrawTabSelectedActiveAndDirty` function was being called multiple times, resulting in unnecessary redraws. This pull request fixes the issue by adding a check to only update the tabs if the active editor is the same as before. If the active editor is different, the update will happen from an open editor call.

Fixes #213160

### CODE REVIEW

**Review by jrieken — DISMISSED** [review]

**Review by lszomoru — APPROVED** [review]

File: src/vs/workbench/browser/parts/editor/multiEditorTabsControl.ts [hunk 1]
```diff
@@ -684,7 +684,20 @@ export class MultiEditorTabsControl extends EditorTabsControl {
 		this.layout(this.dimensions, { forceRevealActiveTab: true });
 	}
 
+	private previousSelectedCount = 0;
```
Comment (bpasero) [inline src/vs/workbench/browser/parts/editor/multiEditorTabsControl.ts:687]: It would be nice if the old selection count was part of the event that leads to this update. I guess one challenge is that here you want the filtered selection count for the multi-tab-row case?

File: src/vs/workbench/browser/parts/editor/multiEditorTabsControl.ts [hunk 2]
```diff
@@ -684,7 +684,20 @@ export class MultiEditorTabsControl extends EditorTabsControl {
...
 	updateEditorSelections(): void {
+		// We only need to redraw from here when a selection got removed
+		// otherwise it will be handled by the open editor change event.
+		// Checking count is currently enough but might require checking
+		// each editor in the future if selection is changed programatically.
+		const newSelectedCount = this.tabsModel.selectedEditors.length;
```
Comment (bpasero) [inline src/vs/workbench/browser/parts/editor/multiEditorTabsControl.ts:693]: I wonder if this assumption should be made by the component that calls this method because that is the one knowing more about open editors behaviour.
