### PR TITLE
increase search area of quick fixes

### LINKED ISSUE #172068: sometimes quick fixes don't show up when they should
going to keep track of examples here to see if there's a pattern

Screenshot 2023-01-23 at 2 12 18 PM

### PR DESCRIPTION
**Pull request by meganrogge**
fix #172068

below you see oss then insider's - always reproes if you have 3 splits that are pretty narrow in insider's, but not oss

this is because we check only `length` lines where `length` is the number `\n` in a possibly wrapped string. it often exceeds the length of 5, so we don't find a match. 15 is arbitrary, but seems to work in my testing without being too many

https://user-images.githubusercontent.com/29464607/214704753-8e07c84c-a804-4023-b70e-776f4d3a30cf.mov

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts [hunk 1]
```diff
@@ -129,7 +129,7 @@ export function gitPushSetUpstream(): IInternalOptions {
 			lineMatcher: GitPushOutputRegex,
 			anchor: 'bottom',
 			offset: 0,
-			length: 5
+			length: 15
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts:132]: This was meant to be _wrapped lines_ in my eyes, so we might want to clear that up later? I made a change in this area recently as it was causing a freeze

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Review by Tyriar — APPROVED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts:132]: yeah I think that's why this was confusing to both of us. we should make this clearer
