### PR TITLE
Show exception widget in inactive editors

### LINKED ISSUE #272516: The debug exception widget should be rendered in inactive editors
https://github.com/microsoft/vscode/pull/270615 fixed the issue that all editors with the same file are scrolling to the same location with widgets, the fix changes it to only scrolling the active one, keep from scrolling the inactive ones but also removed the exception widget. 
We should still keep the exception widget there in inactive editors.

### PR DESCRIPTION
**Pull request by bryanchen-d**
Follow-up PR to fix https://github.com/microsoft/vscode/issues/272516, which is an issue from PR https://github.com/microsoft/vscode/pull/270615. 

Show exception widget in the inactive editors, controlling the editor to not move the current focus range in the inactive editors.

### CODE REVIEW

File: src/vs/workbench/contrib/debug/browser/debugEditorContribution.ts [hunk 1]
```diff
@@ -620,6 +623,43 @@ export class DebugEditorContribution implements IDebugEditorContribution {
...
+		if (this.exceptionWidget) {
+			this.exceptionWidget.dispose();
+		}
+
+		// Disable scrolling to exception widget
+		this.allowScrollToExceptionWidget = false;
+
+		const currentScrollTop = this.editor.getScrollTop();
+		const visibleRanges = this.editor.getVisibleRanges();
+		const firstVisibleLine = visibleRanges.length > 0 ? visibleRanges[0].startLineNumber : 1;
```
[the remark this answers is not in the document]
Comment (bryanchen-d) [reply src/vs/workbench/contrib/debug/browser/debugEditorContribution.ts]: updated.

File: src/vs/workbench/contrib/debug/browser/debugEditorContribution.ts [hunk 2]
```diff
@@ -620,6 +623,43 @@ export class DebugEditorContribution implements IDebugEditorContribution {
...
+			let scrollAdjustment = 0;
+			if (whitespaces.length > 0) {
+				// The most recently added whitespace is our widget
+				const lastWhitespace = whitespaces[whitespaces.length - 1];
+				scrollAdjustment = lastWhitespace.height;
+			}
+
+			// Scroll down by the actual widget height to keep the first visible line the same
+			this.editor.setScrollTop(currentScrollTop + scrollAdjustment, ScrollType.Immediate);
+		}
```
[the remark this answers is not in the document]
Comment (bryanchen-d) [reply src/vs/workbench/contrib/debug/browser/debugEditorContribution.ts:660]: updated.

**Comment by bryanchen-d** [comment]
@microsoft-github-policy-service rerun

File: src/vs/workbench/contrib/debug/browser/exceptionWidget.ts [hunk 3]
```diff
@@ -129,4 +139,16 @@ export class ExceptionWidget extends ZoneWidget {
...
 	}
+
+	getWhitespaceHeight(): number {
+		// Returns the height of the whitespace zone from the editor's whitespaces
+		// This is more accurate than the container height as it includes the actual zone dimensions
+		if (!this._viewZone || !this._viewZone.id) {
+			return 0;
+		}
+
+		const whitespaces = this.editor.getWhitespaces();
```
Comment (roblourens) [inline src/vs/workbench/contrib/debug/browser/exceptionWidget.ts:150]: How is this different from what we do in '_doLayout'? It includes some other zone size outside of our container?

File: src/vs/workbench/contrib/debug/browser/debugEditorContribution.ts [hunk 4]
```diff
@@ -620,6 +623,46 @@ export class DebugEditorContribution implements IDebugEditorContribution {
...
+		this.exceptionWidgetVisible.set(true);
+
+		// only adjust scroll if the exception widget is above the first visible line
+		if (lineNumber < firstVisibleLine) {
+			// Get the actual height of the widget that was just added from the whitespace
+			// The whitespace height is more accurate than the container height
+			const scrollAdjustment = this.exceptionWidget.getWhitespaceHeight();
+
+			// Scroll down by the actual widget height to keep the first visible line the same
+			this.editor.setScrollTop(currentScrollTop + scrollAdjustment, ScrollType.Immediate);
```
Comment (roblourens) [inline src/vs/workbench/contrib/debug/browser/debugEditorContribution.ts:659]: Interesting, didn't realize it wouldn't preserve the view range for you.

**Review by roblourens — APPROVED** [review]

File: src/vs/workbench/contrib/debug/browser/exceptionWidget.ts (hunk 3 above)
Comment (bryanchen-d) [reply src/vs/workbench/contrib/debug/browser/exceptionWidget.ts:150]: yes, there are some pixels difference if we just get the height from the widget itself so I have to get the whitespaces to account for that.
