### PR TITLE
Fix updates failing during output of a notebook

### LINKED ISSUE #9327: Problem with NotebookCell.outputs not updating
These tests are failing:

image

They all come down to a NotebookCell.outputs not updating past a certain point.

### PR DESCRIPTION
**Pull request by rchiodo**
This PR fixes https://github.com/microsoft/vscode-jupyter/issues/9327

Outputs that contain any data would crash during an update preventing the cell output update from coming through to an extension.

I believe the issue was originally caused by this commit (our tests started failing this morning):
https://github.com/microsoft/vscode/pull/144679

### CODE REVIEW

File: src/vs/workbench/api/common/extHostNotebookDocuments.ts [hunk 1]
```diff
@@ -32,7 +60,7 @@ export class ExtHostNotebookDocuments implements extHostProtocol.ExtHostNotebook
 	$acceptModelChanged(uri: UriComponents, event: SerializableObjectWithBuffers<extHostProtocol.NotebookCellsChangedEventDto>, isDirty: boolean, newMetadata?: NotebookDocumentMetadata): void {
 		const document = this._notebooksAndEditors.getNotebookDocument(URI.revive(uri));
 		const e = document.acceptModelChanged(event.value, isDirty, newMetadata);
-		this._onDidChangeNotebookDocument.fire(deepFreeze(e));
+		this._onDidChangeNotebookDocument.fire(partialFreeze(e));
```
Comment (rchiodo) [inline src/vs/workbench/api/common/extHostNotebookDocuments.ts:63]: I was getting this with a full freeze:

```
ERR Cannot freeze array buffer views with elements: TypeError: Cannot freeze array buffer views with elements
	at Function.freeze (<anonymous>)
	at deepFreeze (d:\Source\vscode\out\vs\base\common\objects.js:36:20)
	at ExtHostNotebookDocuments.$acceptModelChanged (d:\Source\vscode\out\vs\workbench\api\common\extHostNotebookDocuments.js:32:77)
	at RPCProtocol._doInvokeHandler (d:\Source\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:399:27)
	at RPCProtocol._invokeHandler (d:\Source\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:384:45)
	at RPCProtocol._receiveRequest (d:\Source\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:311:32)
	at RPCProtocol._receiveOneMessage (d:\Source\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:243:26)
	at d:\Source\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:115:52
	at Listener.invoke (d:\Source\vscode\out\vs\base\common\event.js:420:27)
	at Emitter.fire (d:\Source\vscode\out\vs\base\common\event.js:559:34)**
**
```
because the output.items.data were not freezable.

File: src/vs/workbench/api/common/extHostNotebookDocument.ts [hunk 2]
```diff
@@ -114,12 +114,16 @@ export class ExtHostCell {
...
-		const output = this._outputs.find(op => op.id === outputId);
-		if (output) {
+
+		// Use an index so we can overwrite internal properties (otherwise readonly)
+		const index = this._outputs.findIndex(op => op.id === outputId);
+		if (index >= 0) {
+			const output = deepClone(this._outputs[index]);
 			if (!append) {
-				output.items.length = 0;
+				output.items.length = 0; // This crashes without a copy
```
Comment (rchiodo) [inline src/vs/workbench/api/common/extHostNotebookDocument.ts:123]: I also noticed this throwing an exception while running the same code.

**Comment by rchiodo** [comment]
To repro this issue:
- Open a jupyter notebook
- Put this code into it:
```python
print("Start")
import time
for i in range(100):
  time.sleep(0.1)
  print(i)

print("End")
```
- Exception should be thrown inside of VS code

File: src/vs/workbench/api/common/extHostNotebookDocuments.ts [hunk 3]
```diff
@@ -13,6 +12,35 @@ import { NotebookDocumentMetadata } from 'vs/workbench/contrib/notebook/common/n
 import { SerializableObjectWithBuffers } from 'vs/workbench/services/extensions/common/proxyIdentifier';
 import type * as vscode from 'vscode';
 
+declare const Buffer: any;
+
+const hasBuffer = (typeof Buffer !== 'undefined');
+
+export function partialFreeze<T>(obj: T): T {
```
Comment (rchiodo) [inline src/vs/workbench/api/common/extHostNotebookDocuments.ts:19]: This is a bit messy, hoping you guys have a cleaner way to do this. Maybe modifying the original deepFreeze to do the same?

File: src/vs/workbench/api/common/extHostNotebookDocument.ts [hunk 4]
```diff
@@ -114,12 +114,16 @@ export class ExtHostCell {
...
 	setOutputItems(outputId: string, append: boolean, newOutputItems: extHostProtocol.NotebookOutputItemDto[]) {
 		const newItems = newOutputItems.map(extHostTypeConverters.NotebookCellOutputItem.to);
-		const output = this._outputs.find(op => op.id === outputId);
-		if (output) {
+
+		// Use an index so we can overwrite internal properties (otherwise readonly)
+		const index = this._outputs.findIndex(op => op.id === outputId);
+		if (index >= 0) {
+			const output = deepClone(this._outputs[index]);
 			if (!append) {
```
Comment (mjbvz) [inline src/vs/workbench/api/common/extHostNotebookDocument.ts:122]: Not very familiar with this code so trying to understand why the deep clone is correct

Can you share more details about what is happening on the python side that causes the error?  My guess is that the existing code mutates the `NotebookCellOutput.items`, and some code is perhaps taking a reference to `NotebookCellOutput.items` and expecting it not to change behind the scenes? Is that correct?

By cloning the entire object, doesn't that also mean that after every call to `setOutputItems`, the `NotebookCellOutput` we expose in  the api is now a different object (even if it has the same id)? What happens if an extension is holding onto an old `NotebookCellOutput` at that point?

File: src/vs/workbench/api/common/extHostNotebookDocuments.ts (hunk 3 above)
Comment (jrieken) [reply src/vs/workbench/api/common/extHostNotebookDocuments.ts:19]: > Maybe modifying the original deepFreeze to do the same?

💯% All users of `deepFreeze` should benefit from this goodness. There is already a [check](https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/base/common/objects.ts#L38) to decide to decent on an object or not. This check should be extended. 

Also, this shouldn't be checking for `Buffer` - that's a nodejs only type and where are here in  `common`-land. I also believe the error is coming from the underlying typed array, this fails the same way

```
> var a = new Uint8Array(12)
undefined
> Object.freeze(a)
Uncaught TypeError: Cannot freeze array buffer views with elements
    at Function.freeze (<anonymous>)
```

There should be a check iff an object is a typed array - quite a few candidates according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays#typed_array_views. Good news is they are instanceof-able, e.g `candidate instanceof Float32Array` works etc.

File: src/vs/workbench/api/common/extHostNotebookDocument.ts (hunk 2 above)
Comment (jrieken) [reply src/vs/workbench/api/common/extHostNotebookDocument.ts:123]: You have a stack trace? Is it throwing because the event processing froze it? That wouldn't be good...

**Review by jrieken — CHANGES_REQUESTED** [review]
Thanks for far. I have added a few comments and suggestions for improvements. I will also push a change that removes the deepFreeze to unblock you.

File: src/vs/workbench/api/common/extHostNotebookDocument.ts (hunk 4 above)
Comment (rchiodo) [reply src/vs/workbench/api/common/extHostNotebookDocument.ts:122]: I believe it's failing because of the freeze that happens when sending the event. An alternative would be to not freeze at all in when sending the event.

This call here crashes:
```
output.items.length = 0
```
With an error stating a readonly object cannot be modified (likely because it was frozen).

File: src/vs/workbench/api/common/extHostNotebookDocument.ts (hunk 2 above)
Comment (rchiodo) [reply src/vs/workbench/api/common/extHostNotebookDocument.ts:123]: Yes I believe it's crashing because of the freeze.

File: src/vs/base/common/types.ts [hunk 5]
```diff
@@ -42,6 +42,15 @@ export function isObject(obj: unknown): obj is Object {
 		&& !(obj instanceof Date);
 }
 
+/**
+ *
+ * @returns whether the provided parameter is of type `Buffer` or Uint8Array dervived type
+ */
+export function isBuffer(obj: unknown): obj is Object {
+	return typeof obj === 'object'
+		&& obj instanceof Uint8Array;
```
Comment (roblourens) [inline src/vs/base/common/types.ts:51]: I assume that all the types in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays#typed_array_views will have the same problem, I think this should check for those too. Should be called `isTypedArray` or something like that

Comment (rchiodo) [reply src/vs/base/common/types.ts:51]: Yes seems obvious in retrospect. I'll change it.

File: src/vs/workbench/api/common/extHostNotebookDocument.ts (hunk 4 above)
Comment (mjbvz) [reply src/vs/workbench/api/common/extHostNotebookDocument.ts:122]: What about the second point? By switching from mutating the original array to replacing one output with another, is there a risk of having multiple versions of the same output item that extensions are hanging on to?

**Review by jrieken — CHANGES_REQUESTED** [review]
I suggest to take in the changes for `deepFreeze` (checking for typed array) but no cloning of outputs or such. Instead, the event itself shouldn't likely be using `deepFreeze` but some level of shallow freeze.

**Comment by rchiodo** [comment]
> I suggest to take in the changes for `deepFreeze` (checking for typed array) but no cloning of outputs or such. Instead, the event itself shouldn't likely be using `deepFreeze` but some level of shallow freeze.

I modified deepFreeze to support an exclusion list. I then used this at the event location to exclude freezing the outputs.

File: src/vs/workbench/api/common/extHostNotebookDocument.ts [hunk 6]
```diff
@@ -456,4 +456,5 @@ export class ExtHostNotebookDocument {
 	getCellIndex(cell: ExtHostCell): number {
 		return this._cells.indexOf(cell);
 	}
+
```
Comment (rchiodo) [inline src/vs/workbench/api/common/extHostNotebookDocument.ts:459]: Darn it, I'll remove this.

**Comment by jrieken** [comment]
> I modified deepFreeze to support an exclusion list. I then used this at the event location to exclude freezing the outputs.

Not a fan of that tbh - `deepFreeze` is "deep" and a flat list of key is always ambiguous in that context. Maybe my earlier suggestion was misleading. I like two things from this PR

1. improve `deepFreeze` to always ignore typed arrays because it is apparently illegal to freeze them. 
1. don't use `deepFreeze` when emitting the notebook change event. 

It is my bad that I started with `deepFreeze` here but I came to believe it is wrong to freeze objects that you "don't own", e.g the [function](https://github.com/microsoft/vscode/blob/1799e12d7ba8d94a5fa661d2ea2f2d6968e0b7a9/src/vs/workbench/api/common/extHostNotebookDocuments.ts#L31) that applies the change and emits the event should only shallow freeze the parts of the event it owns, like the event itself, `cellChanges`, `contentChanges` etc but not the notebook document or its cells. It's the responsibility of themselves to protect them from outside modifications

**Comment by rchiodo** [comment]
> it is my bad that I started with deepFreeze here but I came to believe it is wrong to freeze objects that you "don't own", e.g the [function](https://github.com/microsoft/vscode/blob/1799e12d7ba8d94a5fa661d2ea2f2d6968e0b7a9/src/vs/workbench/api/common/extHostNotebookDocuments.ts#L31) that applies the change and emits the event should only shallow freeze the parts of the event it owns, like the event itself, cellChanges, contentChanges etc but not the notebook document or its cells. It's the responsibility of themselves to protect them from outside modifications (which may or may not be the case but that would be a different issue)

Yeah that makes more sense. Only freeze event properties, not the notebook itself.

File: src/vs/workbench/api/common/extHostNotebookDocument.ts [hunk 7]
```diff
@@ -294,6 +294,10 @@ export class ExtHostNotebookDocument {
 			}
 		}
 
+		// Freeze event properties so handlers cannot accidentally modify them
+		deepFreeze(result.cellChanges);
+		deepFreeze(result.contentChanges);
```
Comment (jrieken) [inline src/vs/workbench/api/common/extHostNotebookDocument.ts:299]: shallow freeze only, otherwise `NotebookCell` instances are frozen

**Review by jrieken — CHANGES_REQUESTED** [review]

File: src/vs/workbench/api/common/extHostNotebookDocument.ts (hunk 7 above)
Comment (rchiodo) [reply src/vs/workbench/api/common/extHostNotebookDocument.ts:299]: Yes this should just be object.freeze instead of deepFreeze

Comment (rchiodo) [reply src/vs/workbench/api/common/extHostNotebookDocument.ts:299]: Although it's weird that the output wasn't frozen? I think I need to debug the actual outputs here to see what's in them. Object. freeze would certainly work but there might be more that can be frozen.

**Review by jrieken — APPROVED** [review]
lgtm

**Comment by jrieken** [comment]
Ops, post merge (while writing the TPI) I realised this was still freezing the notebook itself and its metadata. Pushed another change on top of thing
