### PR TITLE
Fix #164630

### LINKED ISSUE #164630: No command localizations load if any command title points to an invalid `package.nls.json` entry
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.72.2 (user setup)
OS: Windows_NT x64 10.0.22518

Steps to Reproduce:

1. Use [Python extension](https://github.com/microsoft/vscode-python) for example. Have an entry in `package.json` for a command but misspell the `title` part:
```
{
    "category": "Python",
    "command": "python.setInterpreter",
    "title": "%python.command.python.doesNotExist.title%"
},
```
2. None of the other localizations load:

image

Issue observed in Python extension: https://github.com/microsoft/vscode-python/pull/20063 and Jupyter: https://github.com/microsoft/vscode-jupyter/issues/11600

cc/ @TylerLeonhardt

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
Feel free to review one commit at a time which may be easier.

Fixes #164630

### CODE REVIEW

File: src/vs/platform/extensionManagement/common/extensionNls.ts [hunk 1]
```diff
@@ -16,6 +16,7 @@ export function localizeManifest(extensionManifest: IExtensionManifest, translat
 	try {
 		replaceNLStrings(extensionManifest, translations, fallbackTranslations);
 	} catch (error) {
+		console.error(error?.message ?? error);
```
Comment (roblourens) [inline src/vs/platform/extensionManagement/common/extensionNls.ts:19]: Just checking that this is supposed to be left?

Comment (TylerLeonhardt) [reply src/vs/platform/extensionManagement/common/extensionNls.ts:19]: Yes. Because I didn't have that, I didn't catch this issue, so I'm surfacing it

**Review by roblourens — APPROVED** [review]
