### PR TITLE
Fix race bug

### LINKED ISSUE #52838: Workspace Recommendation badges sometimes dont appear
In most recent insiders.

Steps to Reproduce:

1. Refresh "@recommended" a few times, sometimes extensions will show up, but not have their badge.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by JacksonKearl**
Fixes #52838.

### CODE REVIEW

File: src/vs/workbench/parts/extensions/electron-browser/extensionsList.ts [hunk 1]
```diff
@@ -168,7 +169,7 @@ export class Renderer implements IPagedRenderer<IExtension, ITemplateData> {
 			data.icon.style.visibility = 'inherit';
 		}
 
-		this.updateRecommendationStatus(extension, data);
+		(this.extensionTipsService as ExtensionTipsService).loadRecommendationsPromise.then(() => this.updateRecommendationStatus(extension, data));
```
Comment (JacksonKearl) [inline src/vs/workbench/parts/extensions/electron-browser/extensionsList.ts]: I think it could even make sense to just expose this promise at the interface level.

**Review by ramya-rao-a — APPROVED** [review]
