### PR TITLE
Fix #165415. Reveal range fails to work with out of date cell view height.

### LINKED ISSUE #165415: pasting code makes cell invisible on screen
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

to reproduce:
- (using a normal 1080p and font size 13, unknown zoom level but looks like original)
- create a notebook with 45 empty cells
- paste 150 lines of code in the 2nd cell on top

what happened: 
- the 2nd cell is invisible, the notebook is scrolled to the middle
- consequences: https://github.com/microsoft/vscode/issues/163943

expected: after pasting many lines of code in one cell, the cursor (inside current cell) should be visible in an appropriate position on screen, e.g. near button; instead of being invisible and causing problems.

temp

(if this issue belongs to vscode instead of vscode -jupyter, please help transfer, thx!)

### VS Code Version

1.72.2

### Jupyter Extension Version

2022.9.1202862440

### Jupyter logs

_No response_

### Coding Language and Runtime Version

_No response_

### Language Extension Version (if applicable)

_No response_

### Anaconda Version (if applicable)

_No response_

### Running Jupyter locally or remotely?

Local

### PR DESCRIPTION
**Pull request by rebornix**

### CODE REVIEW

**Review by lramos15 — APPROVED** [review]

File: src/vs/workbench/contrib/notebook/browser/view/cellParts/markupCell.ts [hunk 1]
```diff
@@ -490,6 +482,12 @@ export class MarkupCell extends Disposable {
 			const selections = editor.getSelections();
 
 			if (selections?.length) {
+				const contentHeight = editor.getContentHeight();
+				const layoutContentHeight = this.viewCell.layoutInfo.editorHeight;
+
+				if (contentHeight !== layoutContentHeight) {
+					this.onCellEditorHeightChange(editor, contentHeight);
```
Comment (roblourens) [inline src/vs/workbench/contrib/notebook/browser/view/cellParts/markupCell.ts:489]: Why does this have to be done here?
