### PR TITLE
Fix terminal link disposable leak 

### LINKED ISSUE #252302: LEAKED DISPOSABLE
```
[LEAKED DISPOSABLE] Error: CREATED via:
    at GCBasedDisposableTracker.trackDisposable (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-22.x/out/vs/base/common/lifecycle.js:27:23)
    at trackDisposable (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-22.x/out/vs/base/common/lifecycle.js:198:24)
    at new Disposable (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-22.x/out/vs/base/common/lifecycle.js:393:9)
    at new TerminalLink (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-22.x/out/vs/workbench/contrib/terminalContrib/links/browser/terminalLink.js:25:9)
    at InstantiationService._createInstance (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-22.x/out/vs/platform/instantiation/common/instantiationService.js:130:24)
    at InstantiationService.createInstance (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-22.x/out/vs/platform/instantiation/common/instantiationService.js:101:27)
    at TerminalLinkDetectorAdapter._createTerminalLink (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-22.x/out/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.js:86:43)
    at TerminalLinkDetectorAdapter._provideLinks (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-22.x/out/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.js:76:29)
    at async TerminalLinkDetectorAdapter.provideLinks (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode-electron-
```

### PR DESCRIPTION
**Pull request by anthonykim1**
Resolves: https://github.com/microsoft/vscode/issues/252302

### CODE REVIEW

File: src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts [hunk 1]
```diff
@@ -93,9 +95,10 @@ export class TerminalLinkDetectorAdapter extends Disposable implements ILinkProv
 
 		const detectedLinks = await this._detector.detect(lines, startLine, endLine);
 		for (const link of detectedLinks) {
-			links.push(this._createTerminalLink(link, async (event) => this._onDidActivateLink.fire({ link, event })));
+			const terminalLink = this._createTerminalLink(link, async (event) => this._onDidActivateLink.fire({ link, event }));
+			links.push(terminalLink);
+			this._activeLinksStore.add(terminalLink);
```
Comment (anthonykim1) [inline src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts:94]: I couldn't repro the leak, but looking at the trace https://github.com/microsoft/vscode/issues/252302, here is my hypothesis:
 
--> The "active links" that gets added into `_activeLinks` may NOT get disposed when the `TerminalLinkDetectorAdapter` itself gets disposed. 

What I did:
* Created `DisposableStore` to add in all these links the moment they are added to `_activeLinks`, so when adapter gets disposed, all of these links would get disposed too.

Concern:
* I wanted to avoid having both `_activeLinks` and `_activeLinksStore`, but wasn't so easy just converting `_activeLinks` into DisposableStore itself since https://github.com/microsoft/vscode/blob/bb5e45ae593ba041df740974f24041b2ca6895f9/src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts#L60-L64 already exists and felt wrong to change the type of `_activeLinks` into DisposableStore.

Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts:94]: This is basically happening already here:

https://github.com/microsoft/vscode/blob/ee1ec076b8baa7c8f20163d00fca1959fecbbc42/src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts#L53-L57

I think the issue is actually around the active request promise here, where new requests for different lines will abandon the old links:

https://github.com/microsoft/vscode/blob/ee1ec076b8baa7c8f20163d00fca1959fecbbc42/src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts#L47-L57

Following that I actually got a really easy repro case, just add `await timeout(1000);` before the return in `_provideLinks`. That will simulate really slow link fetching and cause a lot of dispose warnings 🎉

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Review by Tyriar — DISMISSED** [review]
lgtm once you verify

**Comment by anthonykim1** [comment]
Managed to get the leak again, pretty easily actually by typing pretty fast :/

https://github.com/user-attachments/assets/e4e1f2fd-516f-4e8a-8d2c-331563a75e82


Will re-investigate..!

File: src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts [hunk 2]
```diff
@@ -28,7 +28,7 @@ export interface IShowHoverEvent {
  * Wrap a link detector object so it can be used in xterm.js
  */
 export class TerminalLinkDetectorAdapter extends Disposable implements ILinkProvider {
-	private _activeLinks: TerminalLink[] | undefined;
+	private readonly _activeLinksStore = this._register(new DisposableStore());
```
Comment (anthonykim1) [inline src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts:31]: Got rid of `_activeLinks` and added `_activeLinksStore` which is a disposable store. 
This is where I add all the links after creating them via `_createTerminalLink` below.

File: src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts [hunk 3]
```diff
@@ -46,20 +46,16 @@ export class TerminalLinkDetectorAdapter extends Disposable implements ILinkProv
 	async provideLinks(bufferLineNumber: number, callback: (links: ILink[] | undefined) => void) {
 		let activeRequest = this._activeProvideLinkRequests.get(bufferLineNumber);
 		if (activeRequest) {
-			await activeRequest;
-			callback(this._activeLinks);
+			const links = await activeRequest;
```
Comment (anthonykim1) [inline src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts:49]: I'm bit lost how before, we used `this._activeLinks` instead of result of `await activeRequest` (which is type `Promise<TerminalLinks[]>`, for callback. I might be missing some context though, 

By using `callback(links)`, where `await activeRequests` we won't need `_activeLinks` anymore and can just rely on `activeLinksStore`

**Comment by anthonykim1** [comment]
@Tyriar  The current version is the only one that seem to "work" --> I couldn't repro disposable leak. 

What completely doesn't make sense is before, why we called `await activeRequest`, but then `callback(this._activeLinks)` instead of just `callback(await activeRequest)` 

Screenshot 2025-08-26 at 4 12 41 PM

File: src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts [hunk 4]
```diff
@@ -46,20 +46,16 @@ export class TerminalLinkDetectorAdapter extends Disposable implements ILinkProv
...
-			for (const link of this._activeLinks) {
-				link.dispose();
-			}
-		}
+		this._activeLinksStore.clear();
 		activeRequest = this._provideLinks(bufferLineNumber);
 		this._activeProvideLinkRequests.set(bufferLineNumber, activeRequest);
-		this._activeLinks = await activeRequest;
+		const links = await activeRequest;
 		this._activeProvideLinkRequests.delete(bufferLineNumber);
```
Comment (anthonykim1) [inline src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts:57]: I'm also wondering purpose of `_activeProvideLinkRequests`, maybeee it is somehow related to concurrency?

It seems like `_activeProvideLinkRequests` only gets referenced inside of this `provideLinks` function, and kind of confusing to `_activeProvideLinkRequests.set` and then `_activeProvideLinkRequests.delete` right afterwards 🧐🥲

Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts:57]: It's possible this isn't needed and could have been related to caching that never ended up happening. I'd be careful about changing this stuff to clean up though without a full understanding of how links interact with xterm.js. For example, tracking different rows probably prevents duplicate requests when hovering multiple rows especially when there's a remote connection and it's slower to verify the links.

File: src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts (hunk 3 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts:49]: Your proposal to use the return value does seem more correct, just make sure it's tested well

File: src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts (hunk 2 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts:31]: Good change 👍

**Review by Tyriar — APPROVED** [review]

File: src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts (hunk 3 above)
Comment (anthonykim1) [reply src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts:49]: Just did more manual testing more via web link, `ls` and clicking on some different file links, spamming like above.

In terms of test files, it seems like `terminalManager` instantiates `terminalLinkDetectorAdapter` and [getLinks](https://github.com/microsoft/vscode/blob/db87c97754cef3a2ba89989caf281f8268dedc64/src/vs/workbench/contrib/terminalContrib/links/test/browser/terminalLinkManager.test.ts#L177) calls `provideLinks`, where provideLinks is what we want to test.

I don't see dedicated test file for https://github.com/microsoft/vscode/blob/db87c97754cef3a2ba89989caf281f8268dedc64/src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts itself though, should I add one?

Or maybe that is intended since its an adapter.

Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkDetectorAdapter.ts:49]: You could try asking Copilot to try write some unit tests and see if they're useful? I never tried since it's the adapter that integrates with xterm.js.
