### PR TITLE
fix leak -- dispose model ref

### LINKED ISSUE #230453: Undo still works for reopened files even if the "Restore Undo Stack" is disabled
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.0 (Universal)
- OS Version: Sonoma 14.7 (23H124)

Steps to Reproduce:

1. Open any file, make changes then close the file.
2. Reopen file and undo. the undo still works even if the "Restore Undo Stack" is disabled

https://github.com/user-attachments/assets/ddba4d85-9f12-4dd3-921e-e217154b15e2

### LINKED ISSUE #230635: Word highlighting leaks text models
Does this issue occur when all extensions are disabled?: Yes/No

- [x] Yes

- VS Code Version: 1.94.0
- OS Version: MacOS Sonoma (14.4.1)

Steps to Reproduce:

1. Open VSCode
2. create new file (CMD+N)
3. input random text
4. close file (CMD+A -> delete -> CMD+W)
5. create new file again (CMD+N)

Attach Video:

https://github.com/user-attachments/assets/d05a1225-2e59-43ae-af41-c46623cfb8d2

### PR DESCRIPTION
**Pull request by Yoyokrazy**
Fixes: #230635, #230453

model ref is resolved for to address notebook use-case. ref isn't disposed, leaking models.

dispose of the ref after the occurrence request is resolved. Verification steps listed on both issues.

### CODE REVIEW

File: src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts [hunk 1]
```diff
@@ -710,6 +709,7 @@ class WordHighlighter {
 					this._beginRenderDecorations();
 				}
 			}, onUnexpectedError);
+			queryModelRef.dispose()
```
Comment (bpasero) [inline src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts:712]: I would put this into a `finally` of a `try`.

File: src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts [hunk 2]
```diff
@@ -733,6 +732,7 @@ class WordHighlighter {
 					this._beginRenderDecorations(noDelay);
 				}
 			}, onUnexpectedError);
+			queryModelRef.dispose();
```
Comment (bpasero) [inline src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts:735]: I would put this into a `finally` of a `try`.

**Review by bpasero — CHANGES_REQUESTED** [review]

**Review by bpasero — APPROVED** [review]
