### PR TITLE
Fix hover display for nested targets

### LINKED ISSUE #273888: [a11y] Tooltip of context button is overlapped by tree item
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.105.1 (user setup)
Commit: 7d842fb85a0275a4a8e4d7e040d2625abbf7f084
Date: 2025-10-14T22:33:36.618Z
Electron: 37.6.0
ElectronBuildId: 12502201
Chromium: 138.0.7204.251
Node.js: 22.19.0
V8: 13.8.258.32-electron.0
OS: Windows_NT x64 10.0.26200
- OS Version: 

Steps to Reproduce:

1. Tab navigate through the context buttons on tree item
2. When context button is focused, first the tooltip of the context button is displayed, then it disappear and the tooltip of the tree item is displayed
3. This can be reproduced with Agents Toolkit extension or the Source control panel in VSC

https://github.com/user-attachments/assets/bc3147c6-d3d7-455d-bd47-c682dd8e6eb5

### PR DESCRIPTION
**Pull request by benibenj**
```Copilot Generated Description:``` Update hover service logic to correctly handle mouse and focus events for nested hover targets, ensuring that hover does not display when interacting with other hover targets.

fixes https://github.com/microsoft/vscode/issues/273888

### CODE REVIEW

File: src/vs/platform/hover/browser/hoverService.ts [hunk 1]
```diff
@@ -597,6 +601,10 @@ class HoverContextViewDelegate implements IDelegate {
 	}
 }
 
+function eventIsRelatedToTarget(event: UIEvent, target: HTMLElement): boolean {
+	return isHTMLElement(event.target) && getHoverTargetElement(event.target as HTMLElement, target) !== target;
```
Comment (benibenj) [inline src/vs/platform/hover/browser/hoverService.ts]: this should be `===`

**Review by Tyriar — APPROVED** [review]
Do you know if this a regression or was it always like this?
