### PR TITLE
Fixes #116335: Send a file path text to the dropped terminal area

### LINKED ISSUE #116335: Dropped files on split terminals always write to the active terminal, not the one the drop event one
Issue Type: <b>Bug</b>

Steps to reproduce:

1. split the terminal in half

2. type something in the left

3. drop a file into the right half, and you'll see the filename goes into the left half

Isn't this weird? I think the file should go to the dropped point instead of the active one.

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.19042

### PR DESCRIPTION
**Pull request by shskwmt**
This PR fixes https://github.com/microsoft/vscode/issues/116335

https://user-images.githubusercontent.com/17052177/107854311-6aa34c00-6e5e-11eb-9b2a-3d0412cefe4d.mp4

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 1]
```diff
@@ -534,6 +535,35 @@ export class TerminalService implements ITerminalService {
...
+			if (!dragEvent.dataTransfer) {
+				return;
+			}
+
+			// Check if files were dragged from the tree explorer
+			let path: string | undefined;
+			const resources = dragEvent.dataTransfer.getData(DataTransfers.RESOURCES);
+			if (resources) {
+				path = URI.parse(JSON.parse(resources)[0]).fsPath;
+			} else if (dragEvent.dataTransfer.files.length > 0 && dragEvent.dataTransfer.files[0].path /* Electron only */) {
```
Comment (rheh) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:549]: I think you can simplify this to one condition with optional chaining:

```
} else if (dragEvent.dataTransfer?.files?.[0].path /* Electron only */) {
```

**Review by Tyriar — APPROVED** [review]
Sorry about the delay but this works great, I adding a bunch of commits to update against main, fix merge and do some general clean up. Thanks!
