### PR TITLE
wait for profiles to be ready before creating 1st terminal

### LINKED ISSUE #138999: Powershell opening on Terminal in first instance despite default
- VSCode Version: 1.63.0
- Local OS Version: Windows 10 20H2
- Remote OS Version: N/A
- Remote Extension/Connection Type: SSH/Docker/WSL
- Logs: Unable to find source log that indicates terminal launch

Steps to Reproduce:

1. Open VSCode
2. press CTRL+~ to open terminal

Killing the terminal and executing step 2 will open the default terminal (Git Bash for me)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

image

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #138999

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 1]
```diff
@@ -929,12 +929,10 @@ export class TerminalService implements ITerminalService {
 		// Await the initialization of available profiles as long as this is not a pty terminal or a
 		// local terminal in a remote workspace as profile won't be used in those cases and these
 		// terminals need to be launched before remote connections are established.
-		if (!this._terminalProfileService.availableProfiles) {
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:932]: this was never entered bc `availableProfiles` are always defined IE `[]`

**Comment by meganrogge** [comment]
fyi @Tyriar

**Review by rzhao271 — APPROVED** [review]
