### PR TITLE
Fix for not auto-starting same-named tasks in different folders

### LINKED ISSUE #168741: Tasks with the same label from different folders can't run at the same time
Type: <b>Bug</b>

Repro steps:

git clone https://github.com/markw65/multi-workspace.git
cd multi-workspace
code abc.code-workspace
trust the workspace
The workspace has three folders (a, b and c), and each folder has its own watch script, which is configured via tasks.json to run on folder open.

Expected behavior: each folder's watch script should auto run.
Actual behavior: Only a's watch script auto runs.

This works prior to 1.74.0

In addition, attempting to manually start either b's watch, or c's watch (via the triangle in the "npm scripts" side panel) fails, with no error message.

If you rename b's watch script to watchb (in b/package.json), and c's script to watchc, then you can manually start them, but they still don't auto start when opening the workspace.

If you go into b/.vscode/tasks.json and change the label to "npm: watchb", and do the same for c, then all three auto start.

1.74.0 has added some checks to avoid starting the same task multiple times, but it doesn't take account of the fact that tasks in different folders could have the same name

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (1.38GB free)|
|Process Argv|--crash-reporter-id e8eaf96d-f4d4-4874-a9d9-08e2c6d99409|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
gltf-vscode|ces|2.3.16
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
gitlens|eam|13.1.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.3
php-intellisense|fel|2.3.14
monkey-c|Gar|1.0.7
jq-syntax-highlighting|jq-|0.0.2
prettier-extension-monkeyc|mar|2.0.36
vscode-selfhost-test-provider|ms-|0.3.11
peggy-language|Peg|2.3.0
shader|sle|1.1.5
php-debug|xde|1.29.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

```

</details>

### PR DESCRIPTION
**Pull request by markw65**
Fixes #168741

The recently added `AbstractTaskService._inProgressTasks` used the task label to prevent multiple copies of the same task running at the same time. But tasks in different folders can have the same label, and there's no reason not to run them at the same time.

There's an example in #168741 that demonstrates the problem without this commit. The example works in 1.73 and earlier, and also works with this pull request.

### CODE REVIEW

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 1]
```diff
@@ -1198,18 +1198,27 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
...
 
+	private taskLabel(task: Task): string {
+		let label = task._label;
+		const workspaceFolder = task.getWorkspaceFolder();
+		if (workspaceFolder) {
+			label += ' (' + workspaceFolder.name + ')';
+		}
+		return label;
+	}
+
```
Comment (markw65) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:1209]: This is the same string that appears in the tasks panel while a task is running, so I assume there's already a function that produces it somewhere - but after a cursory search I didn't find it.

If there *is* a suitable function that could be used instead of taskLabel, please let me know...

Comment (meganrogge) [reply src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:1209]: thanks so much for looking into this. There's a `task.getQualifiedLabel()` function that does pretty much this. We should use that instead

**Review by meganrogge — CHANGES_REQUESTED** [review]
thanks for looking into this - commented a suggestion

**Review by meganrogge — DISMISSED** [review]

**Comment by markw65** [comment]
Just wanted to check what happens next? Will this get merged automatically now, or do I still need to do something?

**Review by meganrogge — APPROVED** [review]

**Comment by meganrogge** [comment]
@markw65 it will get reviewed by another person before getting merged. nothing left for you to do

**Review by hediet — APPROVED** [review]
