### PR TITLE
Resolve all time-based snippet variables using the same time

### LINKED ISSUE #128570: All time-based snippets variables should resolve using the same time
Issue Type: <b>Bug</b>
Does this issue occur when all extensions are disabled?: Yes

---

Snippets with multiple references to time-based snippet variables (eg. `$CURRENT_YEAR`, `$CURRENT_MINUTE`, `$CURRENT_SECOND`) are not guaranteed to resolve to the same values due to the passage of time during the resolving process.

---

1. Create a snippet with with multiple references to `$CURRENT_SECOND`

```jsonc
  "Print to console": {
    "scope": "javascript,typescript",
    "prefix": "second",
    "body": [
      "$CURRENT_SECOND",
      "$UUID",
      // Repeated "$UUID" lines 15,000 times. Not necessary, but helps increas odds of reproducing
      // ...
      "$UUID",
      "$CURRENT_SECOND",
    ],
    "description": "Show that time-based snippet variables can change during resolution."
  }
```

2. Use the snippet.

There is a chance that the first `$CURRENT_SECOND` will resolve to a different value than the second `$CURRENT_SECOND`.

I would expect that VSCode would save the time at the start of the resolution process and use it for the resolution of all time-based snippet variables.

This is a time-based issue, so it helps to slow your CPU with heavy load.
For example, I ran across this issue while running Folding@Home on my machine.

---

I'll submit a PR momentarily to fix this.

---

VS Code version: Code - Insiders 1.59.0-insider (Universal) (807dfb817fef0d0c5729c1924bd4889b04fa405b, 2021-07-13T09:15:26.467Z)
OS version: Darwin x64 20.5.0
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 6, 8|
|Memory (System)|16.00GB (0.60GB free)|
|Process Argv|--crash-reporter-id 8e80114c-46de-44c7-87ff-0e5b2885669a|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwtct:30312693
bridge0708:30335490

```

</details>

### PR DESCRIPTION
**Pull request by movermeyer**
### What are you trying to accomplish?

This PR fixes #128570

### What approach did you choose and why?

Since `TimeBasedVariableResolver` is only used as part of `CompositeSnippetVariableResolver` and immediately used to resolve all the variables in a snippet, I added the time as a field on `TimeBasedVariableResolver` without worrying about it getting stale.

### The impact of these changes

All the time-based snippet variables in a snippet will resolve using the same time, fixing #128570

### Checklist
- [x] I have manually tested this change. 
- [x] This PR is safe to roll back.

### CODE REVIEW

File: src/vs/editor/contrib/snippet/snippetVariables.ts [hunk 1]
```diff
@@ -255,33 +255,38 @@ export class TimeBasedVariableResolver implements VariableResolver {
 	private static readonly monthNames = [nls.localize('January', "January"), nls.localize('February', "February"), nls.localize('March', "March"), nls.localize('April', "April"), nls.localize('May', "May"), nls.localize('June', "June"), nls.localize('July', "July"), nls.localize('August', "August"), nls.localize('September', "September"), nls.localize('October', "October"), nls.localize('November', "November"), nls.localize('December', "December")];
 	private static readonly monthNamesShort = [nls.localize('JanuaryShort', "Jan"), nls.localize('FebruaryShort', "Feb"), nls.localize('MarchShort', "Mar"), nls.localize('AprilShort', "Apr"), nls.localize('MayShort', "May"), nls.localize('JuneShort', "Jun"), nls.localize('JulyShort', "Jul"), nls.localize('AugustShort', "Aug"), nls.localize('SeptemberShort', "Sep"), nls.localize('OctoberShort', "Oct"), nls.localize('NovemberShort', "Nov"), nls.localize('DecemberShort', "Dec")];
 
+	#date: Date;
```
Comment (jrieken) [inline src/vs/editor/contrib/snippet/snippetVariables.ts:258]: Please use `private readonly _data: Date;` instead. While we do support "native" private fields, the emitted JS code isn't ideal yet - it uses a weak map trick which is much slower than a true property access. Once ES2021 has been finalized we can go ahead and use native privates

**Review by jrieken — CHANGES_REQUESTED** [review]

File: src/vs/editor/contrib/snippet/snippetVariables.ts (hunk 1 above)
Comment (movermeyer) [reply src/vs/editor/contrib/snippet/snippetVariables.ts]: 👍 Done

File: src/vs/editor/contrib/snippet/test/snippetVariables.test.ts [hunk 2]
```diff
@@ -291,6 +292,36 @@ suite('Snippet Variables Resolver', function () {
...
+			$CURRENT_MONTH_NAME_SHORT
+			$CURRENT_SECONDS_UNIX
+		`;
+
+		const clock = sinon.useFakeTimers();
+		try {
+			const resolver = new TimeBasedVariableResolver;
+
+			const firstResolve = new SnippetParser().parse(snippetText).resolveVariables(resolver);
+			clock.tick((365 * 24 * 3600 * 1000) + (24 * 3600 * 1000) + (3661 * 1000));  // 1 year + 1 day + 1 hour + 1 minute + 1 second
```
Comment (jrieken) [inline src/vs/editor/contrib/snippet/test/snippetVariables.test.ts:316]: Since `_date` is a new constructor argument you could simplify this further, e.g. skip clock-magic and just a fixed date when constructing the resolver

**Review by jrieken — APPROVED** [review]
Some nit about the test, I leave it up to you. Will merge later today. Thanks so far

File: src/vs/editor/contrib/snippet/test/snippetVariables.test.ts (hunk 2 above)
Comment (movermeyer) [reply src/vs/editor/contrib/snippet/test/snippetVariables.test.ts:316]: I guess it depends on what behaviour you want to test.

The test as it is shows that "the same resolver will return the same values even though time has passed".
Changing the test to just use the constructor would change the test to "the resolver uses the date given".

I agree that the different tests would fail in the same ways, but IMO, the intention is captured better in the current code. 🤷 

Happy to make the change if you want it.

Comment (jrieken) [reply src/vs/editor/contrib/snippet/test/snippetVariables.test.ts:316]: > The resolver only has a constructor argument since we don't have "native" private fields.

Not sure what that means? You can define a non-native private field anywhere, not just as ctor-argument-field

Comment (jrieken) [reply src/vs/editor/contrib/snippet/test/snippetVariables.test.ts:316]: > I agree that the different tests would fail in the same ways, but IMO, the intention is captured better in the current code. 🤷

Yeah, either way is fine for me. I would have done it different or most likely I wouldn't have written a test ;-)

Comment (movermeyer) [reply src/vs/editor/contrib/snippet/test/snippetVariables.test.ts:316]: > You can define a non-native private field anywhere, not just as ctor-argument-field

Whoops. Fixed in https://github.com/microsoft/vscode/pull/128857
