### PR TITLE
don't throw error about activation when we are waiting to activate intentionally

### LINKED ISSUE #225002: Task errors in vscode repo
I think this just started today, I see this notification every time I open the vscode repo.

Image

The output is 

```
Error: The gulp task detection didn't contribute a task for the following configuration:
{
    "type": "gulp",
    "task": "hygiene",
    "problemMatcher": []
}
The task will be ignored.
```

But it seems like that task is detected fine here

Image

So I don't understand what the issue is

### PR DESCRIPTION
**Pull request by meganrogge**
pass `waitToActivate` to `_getCustomTaskPromises` and don't throw when the providers aren't yet activated as that's expected and by design.

see https://github.com/microsoft/vscode/issues/225002#issuecomment-2273830287

fixes #225002

cc @connor4312

### CODE REVIEW

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 1]
```diff
@@ -2110,141 +2110,139 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
...
 								}
 							}
+						}
+						if (requiredTaskProviderUnavailable) {
+							this._log(nls.localize(
+								'TaskService.providerUnavailable',
+								'Warning: {0} tasks are unavailable in the current environment.',
+								configuringTask.configures.type
+							));
+						} else if (!waitToActivate) {
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:2228]: this is the main change

**Review by roblourens — APPROVED** [review]
