### PR TITLE
fix: use view range for glyph margin widgets

### LINKED ISSUE #198674: Glyph Widgets Operate On View Positions, Not Model Positions
[Monaco Editor Repro](https://microsoft.github.io/monaco-editor/playground.html?source=v0.45.0-dev-20231117#XQAAAAIDBgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw9vveOAmRHEYw2pVmocjg2JTLAYRSDUpZuOkFaezs6BukOHFHluuzVCMzkZPlBGNrDEdrZWFK_vwi_52sicvusS-Tv1CK5wcEYboEZoVdvCdN9JFSgiUGHax3DQyEvYDtrqAb8-T30VeamGUqnA18wuyfa0Auy28KfjtZDNAuGJLGH-M7AyY_mTF9mi6Iib91HnxlBBYui5aULiXN8DN8ubVR7SXpxhhatnff9KHaOGrQN8spWbnkm3NYtnbC9ScoGBjXikdvliKdVzHec8gzFe6BougNaPjtJvYEdCXPz6nHGw5zTugxGCh-Ssq5u71mTs2OJ3gbDdWZE6FUzX8rt4MuqBNh2h9OH8i0eWZXChGWXnPdBk_P-DnX70a-ovRVTjRAiZmh1jDk2aRF0Apc2kNJmhwpTnKUGQPKpwN-iSAguYxlYjhF81qvaeCBPsuyTcXzEde_AghAjeEHtLhX4bfIPr-rzSQh_4xzG5a4bw3v9EY-yNybuAup-nCznpzezxjt7kuEzgq9hjCLvgI8OmMZr0J2TOODTNPMAvAVB9EbBo2NfkbMalpLUrlzAMOWIyNYoPPoYT1YNZ2_vnet2ea7Sis-kseBAXCqzYFpGqgD7D7Ssf2jUuNomy0uAK2KkgUJNNxNwwoeYEiKILkHZbv2d4aZjE0V-iSIlZtPC5e9yNuysZ3oDFkFQyEIe_geeYXHS-GECV6gl8mKMuLmCQ0dQgTiY9VWVaWubYCrX5wF59Pw3Nxe_9Hl-4w)

As you can see, the positioning does not folding into account:

Image

This breaks the revert arrows in the diff editor, as I adopted glyph widgets for them.

### PR DESCRIPTION
**Pull request by joyceerhl**
Fixes https://github.com/microsoft/vscode/issues/198674

### CODE REVIEW

**Review by bpasero — APPROVED** [review]

File: src/vs/editor/common/viewModel/viewModelLines.ts [hunk 1]
```diff
@@ -1308,6 +1308,19 @@ class IdentityCoordinatesConverter implements ICoordinatesConverter {
...
+			// invalid arguments
+			return false;
+		}
+		if (modelRange.endLineNumber < 1 || modelRange.endLineNumber > lineCount) {
+			// invalid arguments
+			return false;
+		}
+		return true;
+	}
+
```
Comment (hediet) [inline src/vs/editor/common/viewModel/viewModelLines.ts:1323]: This method seems unusued?
