### PR TITLE
fix fish SI issue, wrap path in quotes

### LINKED ISSUE #234069: fish shell integration source error
Does this issue occur when all extensions are disabled?: Yes/

```
> code-insiders --version
1.96.0-insider
0c9dd26823dc38dd59d6240e1b6698add43d942c
arm64
```

- OS Version:  macOS 15.2 Beta (24C5079e)

Steps to Reproduce:

1.  Install fish shell
2. Open VSCode Terminal and see always an error

```
> . /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration.fish
.: Error encountered while sourcing file '/Applications/Visual':
.: No such file or directory
```

That file exists the path just needs escaping because of whitespace

### PR DESCRIPTION
**Pull request by meganrogge**
creating a custom build to test 

fixes #234069

### CODE REVIEW

File: src/vs/platform/terminal/node/terminalEnvironment.ts [hunk 1]
```diff
@@ -344,8 +344,8 @@ shellIntegrationArgs.set(ShellIntegrationExecutable.PwshLogin, ['-l', '-noexit',
 shellIntegrationArgs.set(ShellIntegrationExecutable.Zsh, ['-i']);
 shellIntegrationArgs.set(ShellIntegrationExecutable.ZshLogin, ['-il']);
 shellIntegrationArgs.set(ShellIntegrationExecutable.Bash, ['--init-file', '{0}/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-bash.sh']);
-shellIntegrationArgs.set(ShellIntegrationExecutable.Fish, ['--init-command', '. {0}/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration.fish']);
-shellIntegrationArgs.set(ShellIntegrationExecutable.FishLogin, ['-l', '--init-command', '. {0}/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration.fish']);
+shellIntegrationArgs.set(ShellIntegrationExecutable.Fish, ['--init-command', 'source "{0}/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration.fish"']);
+shellIntegrationArgs.set(ShellIntegrationExecutable.FishLogin, ['-l', '--init-command', 'source "{0}/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration.fish"']);
```
Comment (Tyriar) [inline src/vs/platform/terminal/node/terminalEnvironment.ts:348]: Do we know what caused this? We would have seen it on macOS since the default folder has a space in it.

**Review by Tyriar — APPROVED** [review]
Seems safe, I didn't know there was a difference between `.` and `source` but the intent behind it was to source the file.

File: src/vs/platform/terminal/node/terminalEnvironment.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/platform/terminal/node/terminalEnvironment.ts:348]: this caused it https://github.com/microsoft/vscode/pull/226589

I don't think we use fish enough to have caught this - in oss, it does not reproduce. that's why I've created an experimental build to verify it's fixed

Comment (Tyriar) [reply src/vs/platform/terminal/node/terminalEnvironment.ts:348]: Makes sense after seeing the diff, thanks :+1:
