### PR TITLE
option to disable encryption of keys

### LINKED ISSUE #8110: [Remote-SSH Bug]: token invalidated when switching machines
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

I'm using the `code tunnel` on a multi-node HPC cluster. This means that I can run it from any number of machines (depending on where my job is scheduled), but all share the same NFS-mounted home directory. However I've noticed that the generated token is tied to a specific machine: if I run a new `code tunnel` from a different machine, it will give the prompt:
```
To grant access to the server, please log into https://github.com/login/device and use code XXXX-XXXX
```

This appears to modify the `~/.vscode-cli/token.json` file. If I run `code tunnel` again from the same machine, I don't see the prompt, but I do if I change machines (including ones previously authenticated).

Is there a way I can tell it to use the existing token? (I believe this was the behavior in an earlier release I was using)

### Expected Behavior

I keep seeing the token generation prompt when switching machines. 

### Steps To Reproduce

_No response_

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by simonbyrne**
Avoids issue of token invalidation when switching machines with a shared home directory, as suggested by @connor4312 in https://github.com/microsoft/vscode-remote-release/issues/8110#issuecomment-1452270922

Fixes https://github.com/microsoft/vscode-remote-release/issues/8110

### CODE REVIEW

File: cli/src/auth.rs [hunk 1]
```diff
@@ -183,15 +183,18 @@ where
 	T: Serialize + ?Sized,
 {
 	let dec = serde_json::to_string(value).expect("expected to serialize");
-	encrypt(&dec)
+	if std::env::var("VSCODE_CLI_DISABLE_ENCRYPT").is_ok() {
```
Comment (connor4312) [inline cli/src/auth.rs:186]:
```suggestion
	if std::env::var("VSCODE_CLI_DISABLE_KEYCHAIN_ENCRYPT").is_ok() {
```

File: cli/src/auth.rs [hunk 2]
```diff
@@ -183,15 +183,18 @@ where
...
+	encrypt(&dec);
 }
 
 // unseal decrypts and deserializes the value
 fn unseal<T>(value: &str) -> Option<T>
 where
 	T: DeserializeOwned,
 {
-	// small back-compat for old unencrypted values
+	// small back-compat for old unencrypted values, or if VSCODE_CLI_DISABLE_ENCRYPT set
```
Comment (connor4312) [inline cli/src/auth.rs:197]:
```suggestion
	// small back-compat for old unencrypted values, or if VSCODE_CLI_DISABLE_KEYCHAIN_ENCRYPT set
```

File: cli/src/auth.rs [hunk 3]
```diff
@@ -183,15 +183,18 @@ where
 	T: Serialize + ?Sized,
 {
 	let dec = serde_json::to_string(value).expect("expected to serialize");
-	encrypt(&dec)
+	if std::env::var("VSCODE_CLI_DISABLE_ENCRYPT").is_ok() {
+		return dec;
+	}
+	encrypt(&dec);
```
Comment (connor4312) [inline cli/src/auth.rs:189]:
```suggestion
	encrypt(&dec)
```

fixes the build error

File: cli/src/auth.rs (hunk 1 above)
Comment (simonbyrne) [reply cli/src/auth.rs:186]: doesn't this also disable encryption if a file is used instead of the keychain?

Comment (connor4312) [reply cli/src/auth.rs:186]: In this I use "keychain" as a general purpose term for the place where secrets are stored; each platform has their own name for it anyway (keychain on macOS, secret store on Linux, credential manager on Windows). We already have a similar variable VSCODE_CLI_USE_FILE_KEYCHAIN.

**Review by connor4312 — APPROVED** [review]

**Review by lramos15 — APPROVED** [review]
