### PR TITLE
Fix object widget tooltips, fixes #129059

### LINKED ISSUE #129059: Object widget in settings editor doesn't render description
Testing #128429

I noticed when hovering over the object widget that I don't get the text "IT IS YOUR TAG.", but instead get something like "The property \`asdf\` is set to \`test\`."

### PR DESCRIPTION
**Pull request by rzhao271**
This PR fixes #129059 

For object widgets, hovering over the key now displays the key enumDescription or description, and hovering over the value displays the value enumDescription. In both cases, if none of those descriptions are provided, there is still the fallback to the default description saying "property X is set to Y".

The default description is still used for the aria-label to help with accessibility.

Demo

I tested the issue with the following settings:

```json
"emmet.hmm": {
  "type": "object",
  "properties": {
	"property": {
	  "type": "string",
	  "enum": ["a", "b", "c"],
	  "enumDescriptions": ["Item a", "Item b", "Item c"],
	  "description": "propertiesDescription"
	}
  },
  "patternProperties": {
	"^pattern-": {
	  "type": "string",
	  "enum": ["d", "e", "f"],
	  "enumDescriptions": ["Item d", "Item e", "Item f"],
	  "description": "patternDescription"
	}
  },
  "additionalProperties": {
	"type": "string",
	"enum": ["g", "h", "i"],
	"enumDescriptions": ["Item g", "Item h", "Item i"],
	"description": "additionalPropertiesDescription"
  },
  "default": {
	"property": "a",
	"pattern-here": "e",
	"additional": "h"
  }
},
"emmet.boolhmm": {
  "type": "object",
  "properties": {
	"property": {
	  "type": "boolean",
	  "description": "propertiesDescription"
	}
  },
  "default": {
	"property": true
  }
}
```

### CODE REVIEW

File: src/vs/workbench/contrib/preferences/browser/settingsWidgets.ts [hunk 1]
```diff
@@ -1150,20 +1155,25 @@ export class ObjectSettingDropdownWidget extends AbstractListSettingWidget<IObje
 		return true;
 	}
 
-	protected getLocalizedRowTitle(item: IObjectDataItem): string {
-		let enumDescription = item.key.type === 'enum'
-			? item.key.options.find(({ value }) => item.key.data === value)?.description
-			: undefined;
+	protected addTooltipsToRow(rowElement: HTMLElement, item: IObjectDataItem): void {
+		const keyElement = rowElement.getElementsByClassName('setting-list-object-key')[0] as HTMLElement;
```
Comment (roblourens) [inline src/vs/workbench/contrib/preferences/browser/settingsWidgets.ts:1159]: Avoid querying for elements like this. Set these attributes when creating these elements. Or if you can't do that, you could make each row a class, or use a template-like object that has property references to elements that are needed externally

**Review by roblourens — APPROVED** [review]
