### PR TITLE
Fixes #6938: Integrated terminal non-falsey shell exit codes should be reported to the UI, not just the console

### LINKED ISSUE #6938: Integrated terminal non-falsey shell exit codes should be reported to the UI, not just the console
Steps to Reproduce:

1. Set terminal as "faketerm"
2. ctrl+`

### PR DESCRIPTION
**Pull request by chrmarti**
Replacing console.error with the regular error message.

### CODE REVIEW

File: src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts [hunk 1]
```diff
@@ -52,7 +55,7 @@ export class TerminalInstance {
 				this.isExiting = true;
 				this.dispose();
 				if (exitCode) {
-					console.error('Integrated terminal exited with code ' + exitCode);
+					this.messageService.show(Severity.Error, nls.localize('terminal.integrated.exitedWithCode', 'Terminal: The terminal process terminated with exit code: {0}', exitCode));
```
Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: I don't think `Terminal: ` is necessary here, doesn't seem to be used elsewhere (from a cursory search of `Severity.Error`).

**Comment by Tyriar** [comment]
Generally good practice to keep first line of git commit messages under 50 characters, more detail underneath (for future ref :smiley:).
