### PR TITLE
Setting `NODE_UNC_HOST_ALLOWLIST` does not work (fix #182019)

### LINKED ISSUE #182019: Setting `NODE_UNC_HOST_ALLOWLIST` does not work
**Steps:**
* make sure no `security.allowedUNCHosts` is configured
* configure an environment variable `NODE_UNC_HOST_ALLOWLIST` to be `localhost`
* restart Windows
* run `code --user-data-dir \\localhost\c$\Users\<name>\Desktop\some-empty-folder`
* VS Code should open fine
* open a folder such as `vscode`
* make sure extensions work (e.g. typescript) and you can change user settings

### PR DESCRIPTION
**Pull request by bpasero**
We offer `NODE_UNC_HOST_ALLOWLIST` as a way to configure the allow list from the system and this works fine up until we have anyone calling `setUNCHostAllowlist()`: we used to `clear` any previously configured hosts and this will actually clear any host configured by `NODE_UNC_HOST_ALLOWLIST`. 

The fix is to not `clear` but `add` to the `Set`. Since we only do this once on startup and never react to settings changes, this will be fine.

A variant of this fix is already live in todays insider 👍

### CODE REVIEW

File: src/vs/base/node/unc.ts [hunk 1]
```diff
@@ -22,10 +22,10 @@ export function setUNCHostAllowlist(allowedHosts: string[]): void {
 
 	const allowlist = processUNCHostAllowlist();
 	if (allowlist) {
-		allowlist.clear();
-
 		for (const allowedHost of allowedHosts) {
-			allowlist.add(allowedHost);
+			if (!allowlist.has(allowedHost)) {
+				allowlist.add(allowedHost);
+			}
```
Comment (joaomoreno) [inline src/vs/base/node/unc.ts:28]: Since it's a set?

```suggestion
			allowlist.add(allowedHost);
```

**Review by joaomoreno — APPROVED** [review]
