### PR TITLE
fix [object Object] in invalid decorator warning

### LINKED ISSUE #183839: Invalid decoration warning says `[object Object]`
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 60bfd19

Steps to Reproduce:

1. provide an invalid decoration in `provideFileDecoration`
2. see warning in ext host logs that says `[object Object]` instead of the extension name:

```
[warning] INVALID decoration from extension '[object Object]': Error: The decoration is empty
```

### PR DESCRIPTION
**Pull request by mroch**
when there's an invalid decorator, you get a warning like this:

```
[warning] INVALID decoration from extension '[object Object]': Error: The decoration is empty
```

as is done elsewhere in this file, should use `extensionId.identifier.value` to get a string

Fixes #183839

### CODE REVIEW

File: src/vs/workbench/api/common/extHostDecorations.ts [hunk 1]
```diff
@@ -106,7 +106,7 @@ export class ExtHostDecorations implements ExtHostDecorationsShape {
 					}
 					result[id] = <DecorationData>[data.propagate, data.tooltip, data.badge, data.color];
 				} catch (e) {
-					this._logService.warn(`INVALID decoration from extension '${extensionId}': ${e}`);
```
Comment (BobKerns) [inline src/vs/workbench/api/common/extHostDecorations.ts:109]: You're just deleting the warning, not fixing it as you suggest in the comment?

I'd like to know what extension is giving me these warnings, not just suppress it.

Comment (mroch) [reply src/vs/workbench/api/common/extHostDecorations.ts:109]: see the green line below

**Review by jrieken — APPROVED** [review]
Thanks

**Review by alexdima — APPROVED** [review]
