### PR TITLE
Simplify and fix bugs in no results/result count message logic

### LINKED ISSUE #57090: Screen cheese in the settings editor
Issue Type: <b>Bug</b>

1. Open the new settings editor
2. Select `modified settings` from the drop down
3. In the search box, delete all text but `@` - wait 2s
4. Activate intellisense after the `@` and select the `@tag` proposal

-> screen cheese on the left; `No Settings Found` still on the right.

image

VS Code version: Code - Insiders 1.27.0-insider (07618102efdd63f09949ce54c161e7fd2a954ee8, 2018-08-23T05:12:28.997Z)
OS version: Darwin x64 16.7.0

### PR DESCRIPTION
**Pull request by JacksonKearl**
This fixes #57090 by adding full support for filter tags in the count logic.

### CODE REVIEW

**Comment by roblourens** [comment]
You might want to do the count inside triggerSearch, so it only happens once when the debounced search actually runs. As-is I think it will happen on every keypress even when search doesn't run.

File: src/vs/workbench/parts/preferences/browser/settingsEditor2.ts [hunk 1]
```diff
@@ -958,7 +957,7 @@ export class SettingsEditor2 extends BaseEditor {
 
 	private renderResultCountMessages() {
 		let count = countSettingGroupChildrenWithPredicate(this.settingsTree.getInput() as SettingsTreeGroupElement, element => element.matchesAllTags(this.viewState.tagFilters));
-
+		console.log('triggered');
```
Comment (mikaelsouza) [inline src/vs/workbench/parts/preferences/browser/settingsEditor2.ts]: Is this intended to be here?

Comment (JacksonKearl) [reply src/vs/workbench/parts/preferences/browser/settingsEditor2.ts]: Oops. Good catch.

**Review by roblourens — APPROVED** [review]
