### PR TITLE
Add support to edit all potential Quick Fixes in the line

### LINKED ISSUE #194222: Only the nearest problem is considered with quick fixes
Testing #194072

I was expecting quick fixes for the whole line to be included, ranked by distance to the cursor, up to a certain maximum

Image

### PR DESCRIPTION
**Pull request by justschen**
fixes https://github.com/microsoft/vscode/issues/194222 and small update to https://github.com/microsoft/vscode/pull/194636

### CODE REVIEW

**Review by connor4312 — APPROVED** [review]

File: src/vs/editor/contrib/codeAction/browser/codeActionContributions.ts [hunk 1]
```diff
@@ -37,10 +37,10 @@ Registry.as<IConfigurationRegistry>(Extensions.Configuration).registerConfigurat
 Registry.as<IConfigurationRegistry>(Extensions.Configuration).registerConfiguration({
 	...editorConfigurationBaseNode,
 	properties: {
-		'editor.codeActionWidget.includeNearbyQuickfixes': {
+		'editor.codeActionWidget.includeNearbyQuickFixes': {
```
Comment (gjsjohnmurray) [inline src/vs/editor/contrib/codeAction/browser/codeActionContributions.ts:40]: When a setting"s name changes, even only a case-change, shouldn't I also see changes in code that references the setting value, plus migration code to update a user's settings?

Comment (justschen) [reply src/vs/editor/contrib/codeAction/browser/codeActionContributions.ts:40]: Completely went over my head - great catch! The fixes/feature changes worked as intended so I didn't think to update that.
