### PR TITLE
replace double vs single space in terminal accessible buffer

### LINKED ISSUE #181834: In the accessible buffer the whitespace is apparently being replaced by something other than whitespace.
Type: <b>Bug</b>
CC: @meganrogge  @isidorn

I noticed that I can't navigate the accessible buffer using ctrl left arrow or ctrl+right arrow. When using this combination orca treats the whole line as if it were a single word.
Except for misunderstandings, this happens because the blank spaces present in the accessible buffer are being replaced by the character 0xa0. 
I ran the command echo "this is test" in the VSCode terminal and ran the same command in the gnome terminal. Browsing character by character with orca I noticed that in the gnome terminal space appears as 0x20 and in the accessible buffer it appears as 0xa0.

VS Code version: Code - Insiders 1.79.0-insider (2c73d2651cc525b27fc697b820743098a204ec01, 2023-05-04T22:12:16.054Z)
OS version: Linux x64 6.2.14-300.fc38.x86_64
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 4.14.146-93.123.amzn1.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2899)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|15.26GB (6.34GB free)|
|Process Argv|--crash-reporter-id bc02adbd-6c3a-44b8-af92-55103a608af7|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: informal|
|OS|Linux x64 4.14.146-93.123.amzn1.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz (2 x 2500)|
|Memory (System)|3.80GB (1.63GB free)|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.50.0
vscode-eslint|dba|2.4.0
EditorConfig|Edi|0.16.4
copilot|Git|1.86.82
rest-client|hum|0.25.1
better-cpp-syntax|jef|1.17.2
docomment|k--|1.0.0
azure-pipelines|ms-|1.208.0
vscode-docker|ms-|1.25.0
csharp|ms-|1.25.7
vscode-dotnet-runtime|ms-|1.6.0
vscode-kubernetes-tools|ms-|1.3.11
remote-containers|ms-|0.293.0
remote-ssh|ms-|0.101.2023050515
remote-ssh-edit|ms-|0.84.0
azure-account|ms-|0.11.4
azurecli|ms-|0.5.0
cmake-tools|ms-|1.14.31
cpptools|ms-|1.15.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.7.0
powershell|ms-|2023.5.0
remote-explorer|ms-|0.5.2023040509
vsliveshare|ms-|1.0.5864
oracledevtools|Ora|21.5.0
fabric8-analytics|red|0.3.6
java|red|1.19.2023050804
vscode-xml|red|0.25.2023050404
vscode-yaml|red|1.12.2
sonarlint-vscode|Son|3.17.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.46.0
vscode-java-debug|vsc|0.50.2023042406
vscode-java-dependency|vsc|0.22.2023042900
vscode-java-pack|vsc|0.25.2023042006
vscode-java-test|vsc|0.38.2023042703
vscode-maven|vsc|0.41.2023042103
vscode-spring-boot-dashboard|vsc|0.13.0
vscode-spring-initializr|vsc|0.11.2
gitblame|wad|10.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstes627cf:30244335
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
6233i204:30725950
azdwalk:30721579
pythonms35:30671666
cai9j608:30680470
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
hidesbindicator:30724476
pythongtdpath:30726887

```

</details>

### PR DESCRIPTION
**Pull request by meganrogge**
fix #181834

### CODE REVIEW

File: src/vs/workbench/contrib/terminalContrib/accessibility/browser/bufferContentTracker.ts [hunk 1]
```diff
@@ -82,7 +82,7 @@ export class BufferContentTracker {
 			const isWrapped = buffer.getLine(i + 1)?.isWrapped;
 			currentLine += line.translateToString(!isWrapped);
 			if (currentLine && !isWrapped || i === (buffer.baseY + this._xterm.raw.rows - 1)) {
-				const line = currentLine.replace(new RegExp(' ', 'g'), '\xA0');
+				const line = currentLine.replace(new RegExp('  ', 'g'), '\xA0');
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/accessibility/browser/bufferContentTracker.ts:85]: You want to replace 2 spaces with a space and a non-breaking space, if they're interleaved like `<space><nbsp><space><nbsp>` then it will give us the same spacing as the normal terminal while fixing the orca problem.

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Review by Tyriar — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]

**Review by Tyriar — DISMISSED** [review]

**Review by mjbvz — DISMISSED** [review]

**Review by roblourens — APPROVED** [review]
