### PR TITLE
fix terminal suggest light+ contrast issue for partial item

### LINKED ISSUE #251932: Terminal suggest partial `selectionMode` contrast issue
From @kieferrm 

On the `Light+` theme, there's a contrast issue where the font of the completion item has very low contrast with the foreground. This might be related to the `this._suggestWidget.list.style(` calls in `TerminalSuggestAddon`.

Image

### PR DESCRIPTION
**Pull request by meganrogge**
fix #251932

Before:

Screenshot 2025-06-19 at 2 50 02 PM

After:

Screenshot 2025-06-19 at 2 50 12 PM

### CODE REVIEW

File: src/vs/workbench/services/suggest/browser/simpleSuggestWidget.ts [hunk 1]
```diff
@@ -928,9 +931,16 @@ export class SimpleSuggestWidget<TModel extends SimpleCompletionModel<TItem>, TI
 	}
 }
 
-function getListStylesWithMode(partial?: boolean): IListStyles {
+function getListStylesWithMode(themeService: IThemeService, partial?: boolean): IListStyles {
 	if (partial) {
-		return getListStyles({ listInactiveFocusOutline: focusBorder });
+		const themeIsLight = themeService.getColorTheme().type === ColorScheme.LIGHT;
+		if (themeIsLight) {
```
Comment (Tyriar) [inline src/vs/workbench/services/suggest/browser/simpleSuggestWidget.ts]: This isn't inherent to light themes. Since dark themes can do it too the fix should work for both.

You can simulate a dark theme doing it like this:

image

```
  "workbench.colorCustomizations": {
    "list.inactiveFocusBackground": "#fff",
```

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Review by Tyriar — APPROVED** [review]
