### PR TITLE
fix: text overlay in replace input

### LINKED ISSUE #151624: text in Find in Files Replace textbox does not wrap correctly around Preserve Case button
Issue Type: <b>Bug</b>

Shrinking the left panel causes the Preserve Case button to overlap with text in the Replace textbox.  Expected result is for the text to wrap before overlapping with the button.

https://user-images.githubusercontent.com/7648957/172888889-c0a5256c-683d-4830-b35f-2d3b65e584a9.mov

VS Code version: Code - Insiders 1.68.0-insider (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:38:41.739Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.88GB free)|
|Process Argv|--crash-reporter-id aee3bdc0-7363-4093-8073-91b768ab1df9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.81.2022060215
remote-ssh-edit|ms-|0.80.0
cpptools|ms-|1.10.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912cf:30496797
vsclangdf:30492506

```

</details>

### PR DESCRIPTION
**Pull request by g1eny0ung**
Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>

This PR tries to fix the below text overlay problem in the replace input:

image

After:

image

I will add the explanation in the comments.

Fixes #151624

### CODE REVIEW

**Comment by g1eny0ung** [comment]
@microsoft-github-policy-service agree

File: src/vs/base/browser/ui/findinput/replaceInput.ts [hunk 1]
```diff
@@ -370,7 +370,6 @@ export class ReplaceInput extends Widget {
 
 	public set width(newWidth: number) {
 		this.inputBox.paddingRight = this.cachedOptionsWidth;
-		this.inputBox.width = newWidth;
```
Comment (g1eny0ung) [inline src/vs/base/browser/ui/findinput/replaceInput.ts:373]: Here I remove this line because `set paddingRight(paddingRight: number)` already calculates the input width with the right padding. Setting the width again is redundant.

File: src/vs/workbench/contrib/search/browser/media/searchview.css [hunk 2]
```diff
@@ -68,11 +68,10 @@
 	display: none;
 }
 
-.search-view .search-widget .monaco-findInput,
 .search-view .monaco-findInput {
 	display: inline-block;
 	vertical-align: middle;
-	width: 100% !important;
+	width: 100%;
```
Comment (g1eny0ung) [inline src/vs/workbench/contrib/search/browser/media/searchview.css:74]: This change and the below changes aim to reduce unnecessary width settings. The inline width will be overridden by `width: 100% !important;`, so these operations are also redundant.

**Comment by roblourens** [comment]
Is there an open issue for this? I think I remember one but can't find it. If not, please open one.

**Comment by andreamah** [comment]
> Is there an open issue for this? I think I remember one but can't find it. If not, please open one.
Linked the relevant issue

**Comment by g1eny0ung** [comment]
@roblourens @andreamah Will this PR be included in the October release?

**Comment by andreamah** [comment]
> @roblourens @andreamah Will this PR be included in the October release?

Unfortunately, we weren't able to get to reviewing this one in time for October, apologies for that! :(

**Comment by g1eny0ung** [comment]
> > @roblourens @andreamah Will this PR be included in the October release?
> 
> Unfortunately, we weren't able to get to reviewing this one in time for October, apologies for that! :(

Never mind. Hopefully this fix will be reviewed and merged in November. :)

File: src/vs/workbench/contrib/searchEditor/browser/media/searchEditor.css [hunk 3]
```diff
@@ -79,7 +79,6 @@
 	max-width: 50px;
 }
 
-
```
Comment (andreamah) [inline src/vs/workbench/contrib/searchEditor/browser/media/searchEditor.css:82]: nit: remove deleted line

File: src/vs/workbench/contrib/search/browser/patternInputWidget.ts [hunk 4]
```diff
@@ -75,7 +75,6 @@ export class PatternInputWidget extends Widget implements IThemable {
 
 	setWidth(newWidth: number): void {
 		this.width = newWidth;
-		this.domNode.style.width = this.width + 'px';
```
Comment (andreamah) [inline src/vs/workbench/contrib/search/browser/patternInputWidget.ts:78]: I'm a bit unsure on why this is redundant? Wouldn't we want to keep re-setting the findInput's width for include/exclude?

File: src/vs/workbench/contrib/searchEditor/browser/media/searchEditor.css (hunk 3 above)
Comment (g1eny0ung) [reply src/vs/workbench/contrib/searchEditor/browser/media/searchEditor.css]: Done.

File: src/vs/workbench/contrib/search/browser/patternInputWidget.ts (hunk 4 above)
Comment (g1eny0ung) [reply src/vs/workbench/contrib/search/browser/patternInputWidget.ts:76]: image

image

@andreamah Perhaps these screenshots can help to understand why this line and below are redundant. If the `.monaco-findInput` has the `width: 100%` property (changes above 👆), setting the dom width manually will override it.

These two parts contradict each other, the past code used the `!important` rule, then manually setting the widths is a redundant operation, as they will be overridden. The opposite is also true, so here we just need to remove the `!important` and remove the manual setting of the dom width to allow the input width to scale automatically.

**Review by andreamah — APPROVED** [review]
LGTM! Thanks for the contribution!

**Review by aeschli — APPROVED** [review]
