### PR TITLE
Handle disposing better

### LINKED ISSUE #172134: Disposed logger still reacts
Testing #172057

Given this code:

```ts
// The command has been defined in the package.json file
// Now provide the implementation of the command with registerCommand
// The commandId parameter must match the command field in package.json
let disposable = vscode.commands.registerCommand('test-telemetry-api-ts.helloWorld', () => {
	// The code you place here will be executed every time your command is executed
	// Display a message box to the user
	vscode.window.showInformationMessage('Hello World from test-telemetry-api-ts!');

	const logger = vscode.env.createTelemetryLogger({
		sendEventData: function (eventName: string, data?: Record<string, any> | undefined): void {
			console.log("sendEventData: ", eventName, data);
		},
		sendErrorData: function (error: Error, data?: Record<string, any> | undefined): void {
			console.log("sendErrorData: ", error, data);
		}
	}, {});
	logger.dispose();

	console.log("logger.isErrorsEnabled", logger.isErrorsEnabled);
	console.log("logger.isUsageEnabled", logger.isUsageEnabled);

	logger.onDidChangeEnableStates(e => console.log("onDidChangeEnableStates", e));

	logger.logUsage("myEventName token=1234 /Users/bpasero/Development/Microsoft/vscode/src/vs/platform/extensionManagement/common/extensionsProfileScannerService.ts", { "key": "/Users/bpasero/Development/Microsoft/vscode/src/vs/platform/extensionManagement/common/extensionsProfileScannerService.ts", "common.extversion": "roflcopter" });
	logger.logError(new Error("foo token=1234 /Users/bpasero/Development/Microsoft/vscode/src/vs/platform/extensionManagement/common/extensionsProfileScannerService.ts"));
	logger.logError("hello error token=1234 /Users/bpasero/Development/Microsoft/vscode/src/vs/platform/extensionManagement/common/extensionsProfileScannerService.ts", { "key": "token=1234" });
});
```

I was expecting my event handlers not to fire since the logger is disposed, but they still fire.

### PR DESCRIPTION
**Pull request by lramos15**
Fixes https://github.com/microsoft/vscode/issues/172134

### CODE REVIEW

File: src/vs/workbench/api/common/extHostTelemetry.ts [hunk 1]
```diff
@@ -275,7 +278,9 @@ export class ExtHostTelemetryLogger {
 
 	dispose(): void {
 		if (this._sender?.flush) {
-			this._sender.flush();
+			// Disposed of so now we set it to undefined
+			Promise.resolve(this._sender.flush()).then(this._sender = undefined);
```
Comment (connor4312) [inline src/vs/workbench/api/common/extHostTelemetry.ts:282]: Should `this._sender` be unset synchronously so any callers immediately see the "disposed" behavior?

**Review by connor4312 — APPROVED** [review]

File: src/vs/workbench/api/common/extHostTelemetry.ts (hunk 1 above)
Comment (jrieken) [reply src/vs/workbench/api/common/extHostTelemetry.ts:282]: 👍 

also `this._sender` will stick around when flushing fails (for whatever reason)
