### PR TITLE
Make default text editor replace existing editors for resource

### LINKED ISSUE #111474: "Toggle Editor Type" creates corrupted new view that cannot be opened
- VSCode Version: 1.51.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file in a custom editor (I tested with third party extensions and with the "PawDraw" and "CatScratch" extension samples)
2. Run "View: Toggle editor type" from the command palette
3. Try and switch between the new and old tab

The command will create a new tab, even though it should replace the original tab, and the new tab cannot be selected properly.

Does this issue occur when all extensions are disabled?: No, the issue applies to functionality that is only exposed by custom editors.

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #111474

This ports the logic that we previously had for custom editors to the generic open with flow: https://github.com/microsoft/vscode/blob/f0bb23ca02f320816219017234e412caa425851e/src%2Fvs%2Fworkbench%2Fcontrib%2FcustomEditor%2Fbrowser%2FcustomEditors.ts#L281

### CODE REVIEW

File: src/vs/workbench/services/editor/common/editorOpenWith.ts [hunk 1]
```diff
@@ -155,7 +155,21 @@ export function getAllAvailableEditors(
...
+							const existingEditor = group.editors.find(editor => editor.resource && isEqual(editor.resource, resource));
+							if (existingEditor && !fileEditorInput.matches(existingEditor)) {
+								await editorService.replaceEditors([{
+									editor: existingEditor,
+									replacement: fileEditorInput,
+									options: options ? EditorOptions.create(options) : undefined,
+								}], group);
+							}
+
+							return editorService.openEditor(fileEditorInput, textOptions, group);
```
Comment (bpasero) [inline src/vs/workbench/services/editor/common/editorOpenWith.ts:170]: I believe this extra `openEditor` call would not be needed since the `replaceEditors` call should take care of that already, please test.

File: src/vs/workbench/services/editor/common/editorOpenWith.ts [hunk 2]
```diff
@@ -155,7 +155,21 @@ export function getAllAvailableEditors(
 
 					const fileEditorInput = editorService.createEditorInput({ resource, forceFile: true });
 					const textOptions: IEditorOptions | ITextEditorOptions = options ? { ...options, override: false } : { override: false };
-					return { override: editorService.openEditor(fileEditorInput, textOptions, group) };
+					return {
+						override: (async () => {
+							// Try to replace existing editors for resource
+							const existingEditor = group.editors.find(editor => editor.resource && isEqual(editor.resource, resource));
```
Comment (bpasero) [inline src/vs/workbench/services/editor/common/editorOpenWith.ts:161]: This helper method to find an editor by `resource` should ideally live in the `EditorGroup` imho. That is the best place to do the comparison of resources I think. I found more places where we would benefit from such a method ([1], [2]).

There is already a bug here where you compare the "original URI" with the "canonical URI" of the input. If any, you need to compare with `fileEditorInput.resource` because that is the canonical one.


**[1]** https://github.com/microsoft/vscode/blob/07bd0e3c351dab4f30c6b6b43ff6f0a5db0ae6ff/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L321-L321

**[2]** https://github.com/microsoft/vscode/blob/f0bb23ca02f320816219017234e412caa425851e/src/vs/workbench/contrib/customEditor/browser/customEditors.ts#L549-L549

**Review by bpasero — CHANGES_REQUESTED** [review]
I am not entirely sure the purpose: is it to have a first entry in the "Open With..." picker to open as text? And then if the editor is already opened we replace the editor instead of opening a new one? What happens if you do not replace, do we open another editor and the original one is also there?

File: src/vs/workbench/services/editor/common/editorOpenWith.ts (hunk 2 above)
Comment (bpasero) [reply src/vs/workbench/services/editor/common/editorOpenWith.ts:161]: Hm, maybe a better place is inside `IEditorService` itself because the other one does not really talk about `URI`, rather typed editor inputs. We have a similar method `isOpen` that allows to pass in a resource editor input which I think is very similar:

https://github.com/microsoft/vscode/blob/66f5e9294e3af365bc62260839fe51806eb83ac5/src/vs/workbench/services/editor/browser/editorService.ts#L743-L755

We could have a new method `find` that allows to pass in editor input or resource editor input and does something similar?

Comment (mjbvz) [reply src/vs/workbench/services/editor/common/editorOpenWith.ts:161]: I just a change that adds a `IEditorService.getEditorsForResource` method. Let me know if this matches what you were thinking or if we should try something different

File: src/vs/workbench/services/editor/common/editorOpenWith.ts (hunk 1 above)
Comment (mjbvz) [reply src/vs/workbench/services/editor/common/editorOpenWith.ts:230]: This function currently needs to return an `IEditorPane`, so I was calling `openEditor` to get that. I also seem to remember that replaceEditor does not show the replacing editor, although I could be wrong

File: src/vs/workbench/services/editor/browser/editorService.ts [hunk 3]
```diff
@@ -756,6 +756,17 @@ export class EditorService extends Disposable implements EditorServiceImpl {
 
 	//#endregion
 
+	//#region findEditor()
+
+	getEditorsForResource(resource: URI, group: IEditorGroup): IEditorInput[] {
+		const cononicalResource = this.asCanonicalEditorResource(resource);
+		return group.getEditors(EditorsOrder.SEQUENTIAL).filter(editor => {
```
Comment (bpasero) [inline src/vs/workbench/services/editor/browser/editorService.ts:763]: Instead of looping over all editors in the group, I would do a quick first `this.isOpen({ resource })` to see if the editor is open after all. This is a very fast `Set` lookup without loops and can be used to return quickly.

File: src/vs/workbench/services/editor/browser/editorService.ts [hunk 4]
```diff
@@ -756,6 +756,17 @@ export class EditorService extends Disposable implements EditorServiceImpl {
 
 	//#endregion
 
+	//#region findEditor()
+
+	getEditorsForResource(resource: URI, group: IEditorGroup): IEditorInput[] {
+		const cononicalResource = this.asCanonicalEditorResource(resource);
```
Comment (bpasero) [inline src/vs/workbench/services/editor/browser/editorService.ts:762]:
```suggestion
		const canonicalResource = this.asCanonicalEditorResource(resource);
```

**Review by bpasero — CHANGES_REQUESTED** [review]

**Comment by mjbvz** [comment]
Thanks @bpasero! Just pushed the suggested changes

**Review by bpasero — APPROVED** [review]
@mjbvz one thing I forgot to ask for: is it possible to add a unit test for this new method?
