### PR TITLE
Handle mnemonic escaping 

### LINKED ISSUE #61139: Missing ampersands in new "custom" title bar
- VSCode Version: 1.28.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a folder containing an ampersand. i.e. "Notes & Todos"
2. Open this folder in VS Code
3. Go to File > Open Recent, and you will see that the folder is listed, but missing the ampersand.

Does this issue occur when all extensions are disabled?: Yes

This only occurs when the new title bar setting is set to "custom." When set to "native" the ampersand appears as expected.

### PR DESCRIPTION
**Pull request by sbatten**
fixes https://github.com/Microsoft/vscode/issues/61139

replaces https://github.com/Microsoft/vscode/pull/66761

### CODE REVIEW

**Comment by sbatten** [comment]
@bpasero ping

**Review by bpasero — CHANGES_REQUESTED** [review]
@sbatten I am confused by the new (?) notion of `&&&` to present a literal `&` in the menu labels. I would prefer a solution that is consistent with our current approach where `&&` is a mnemonic and `&` is the literal `&`. Otherwise we have competing notations for buttons vs menus.

See for example https://github.com/Microsoft/vscode/issues/64999 for a discussion around this for extensions.

**Comment by sbatten** [comment]
@bpasero Electron's methodology is && => & and & => mnemonic. Our current menus do not have a method of presenting & literally. The &&& was a way to get us to a working state where we could escape mnemonics, but ideally we would eventually move all our commands to use & and &&. Using && for a mnemonic instead of & because now && is not possible to present literally.

**Comment by bpasero** [comment]
@sbatten I just checked how the old menu used to be and found e.g. this: https://github.com/Microsoft/vscode/blob/1.20.1/src/vs/code/electron-main/menus.ts#L382 which seems to indicate to me that for translations we always said that `&&` is a mnemonic and `&` is the literal `&`.

Can we get to a solution where `&` is the literal `&` in both custom and native menu and `&&` is the ampersand which gets removed on platforms that do not support it or if this is disabled?

File: src/vs/workbench/electron-browser/main.contribution.ts [hunk 1]
```diff
@@ -383,7 +383,7 @@ MenuRegistry.appendMenuItem(MenuId.MenubarHelpMenu, {
 	group: '2_reference',
 	command: {
 		id: 'workbench.action.openTipsAndTricksUrl',
-		title: nls.localize({ key: 'miTipsAndTricks', comment: ['&& denotes a mnemonic'] }, "Tips and Tri&&cks")
+		title: nls.localize({ key: 'miTipsAndTricks', comment: ['&& denotes a mnemonic'] }, "Tips &&& Tri&&cks")
```
Comment (bpasero) [inline src/vs/workbench/electron-browser/main.contribution.ts]: @sbatten should this be `&` instead of `&&&`

File: src/vs/base/browser/ui/menu/menu.ts [hunk 2]
```diff
@@ -767,6 +770,10 @@ class MenuSeparatorActionItem extends ActionItem {
 	}
 }
 
+/**
```
Comment (bpasero) [inline src/vs/base/browser/ui/menu/menu.ts]: @sbatten is this something you still work on?

**Review by bpasero — APPROVED** [review]
Much better, some comments.
