### PR TITLE
Set TERM_PROGRAM in terminal

### LINKED ISSUE #29426: Set TERM_PROGRAM environment variable on integrated shell
- VSCode Version: 1.13.1
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. Launch VSCode from launcher and integrated shell.
2. `TERM_PROGRAM` is not set.
3. Launch VSCode within `iTerm2.app` by `code` command and open integrated shell. 
4. `TERM_PROGRAM` is set as `iTerm.app`

I change shell behavior by terminal applications. I set tmux to be launched only if `TERM_PROGRAM` equals `iTerm.app`. 

 VSCode does not set that environment variable however. `TERM_PROGRAM` is affected by applications launching VSCode.

Please set `TERMINAL_PROGRAM` variable like `vscode`, or add preference for environment variables on integrated shell :)

Related issue: https://github.com/Microsoft/vscode/issues/23295

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #29426

Sets the TERM_PROGRAM and TERM_PROGRAM_VERSION environment variables for the integrated terminal

### CODE REVIEW

File: src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts [hunk 1]
```diff
@@ -665,6 +667,8 @@ export class TerminalInstance implements ITerminalInstance {
 		const env = shell.env ? shell.env : TerminalInstance._cloneEnv(parentEnv);
 		env['PTYPID'] = process.pid.toString();
 		env['PTYSHELL'] = shell.executable;
+		env['TERM_PROGRAM'] = product.nameShort;
```
Comment (mjbvz) [inline src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: Not sure if it would be better to use a constant name across all VSCode builds (insiders, stable, oss)?

Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: I think just a consistent 'vscode' across all would be best as this is meant for scripts to be able to see what the terminal is (maybe certain ones have more capabilities). `TERM_PROGRAM` is good for differentiating versions if needed.

**Review by Tyriar — APPROVED** [review]
