### PR TITLE
Always trim trailing colon from word link provider links

### LINKED ISSUE #101155: ctrl-click in terminal doesn't handle trailing ':' in file:line:col: links
Issue Type: <b>Bug</b>

gcc generates errors in the terminal window that look like this:
```
File.cpp:52:32: error: blah blah blah
```

if you ctrl-click on the `File.cpp` bit in the terminal window, it populates the vscode file search popup with the text `File.cpp:52:32:`, but this yields **no** search results.

however, if you delete the trailing `:` from that text (resulting in `File.cpp:52:32` then the file search popup shows the correct file and hitting &lt;enter&gt; takes you to the correct file/line/column.

Either:
- the terminal window location parsing code should omit the trailing `:`, or
- the file search popup parser should handle the trailing `:`

left-hand meet right-hand.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (2.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.56.1:2222|
|OS|Linux x64 3.10.0-1127.el7.x86_64|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2903)|
|Memory (System)|3.70GB (1.62GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.56.1:2222|
|OS|Linux x64 3.10.0-1127.el7.x86_64|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2903)|
|Memory (System)|3.70GB (1.62GB free)|
|VM|100%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.4.1
vscode-markdownlint|Dav|0.36.0
gitlens|eam|10.2.2
php-debug|fel|1.13.0
cmake|twx|0.0.17
change-case|wma|1.0.0
plsql-language|xyz|1.8.2
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4

</details>

### PR DESCRIPTION
**Pull request by Abhijith-S-D**
This PR fixes #101155

This fix removes trailing colon before providing the word links in the terminalWordLinkProvider.
Have added the test for the corresponding change

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/links/terminalWordLinkProvider.ts [hunk 1]
```diff
@@ -68,14 +68,23 @@ export class TerminalWordLinkProvider extends TerminalBaseLinkProvider {
...
 		if (startX !== -1) {
-			result.push(new TerminalLink({ start: { x: startX + 1, y }, end: { x: line.length, y } }, text, this._xterm.buffer.active.viewportY, activateCallback, this._tooltipCallback, false, localize('searchWorkspace', 'Search workspace'), this._configurationService));
+			result.push(new TerminalLink({ start: { x: startX + 1, y }, end: { x: line.length, y } }, this._remove_trailing_colon(text), this._xterm.buffer.active.viewportY, activateCallback, this._tooltipCallback, false, localize('searchWorkspace', 'Search workspace'), this._configurationService));
 		}
 
 		return result;
 	}
 
+	// Remove trailing colon in the provided text
+	private _remove_trailing_colon(text: string): string {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/links/terminalWordLinkProvider.ts:80]: We use this naming convention: `_removeTrailingColon`

**Review by Tyriar — CHANGES_REQUESTED** [review]
Right now this changes the text but not the actual range of the link which means the `:` gets underlined:

image

I think it would be better if we instead removed any trailing `:` from the range in addition to the text so that it doesn't get underlined.

File: src/vs/workbench/contrib/terminal/browser/links/terminalWordLinkProvider.ts [hunk 2]
```diff
@@ -68,14 +68,23 @@ export class TerminalWordLinkProvider extends TerminalBaseLinkProvider {
...
+		if (text.length > 0 && text[text.length - 1] === ':') {
+			return text.slice(0, text.length - 1);
+		}
+		return text;
```
Comment (walidbarakat) [inline src/vs/workbench/contrib/terminal/browser/links/terminalWordLinkProvider.ts:84]: since you're sure that : 
1) text won't be NULL.
2) case of trailing spaces isn't exist or no need to remove it.
so you don't need to check if length of the text is bigger than 0, i think TS has no problem to call slice on ZERO length string, you just need to check if trailing colon needed to be removed - i'd like to suggest TRIM instead of REMOVE in the function name but it's not necessary - 
```suggestion
		return (text.slice(-1) === ':')? text.slice(0,-1) : text;
```

**Review by walidbarakat — CHANGES_REQUESTED** [review]

**Comment by Abhijith-S-D** [comment]
Thanks for the comments. As suggested by @Tyriar, now fixed the bug and : is now trimmed from underlined range as well. Have incorporated changes suggested by @walidbarakat :)

File: src/vs/workbench/contrib/terminal/browser/links/terminalWordLinkProvider.ts (hunk 1 above)
Comment (Abhijith-S-D) [reply src/vs/workbench/contrib/terminal/browser/links/terminalWordLinkProvider.ts]: Thanks for the comments. Have now followed the same naming convention in the latest commit :)

File: src/vs/workbench/contrib/terminal/browser/links/terminalWordLinkProvider.ts (hunk 2 above)
Comment (Abhijith-S-D) [reply src/vs/workbench/contrib/terminal/browser/links/terminalWordLinkProvider.ts]: Thanks for the suggestion. Have incorporated these in my latest commit :)

**Review by Tyriar — APPROVED** [review]
