### PR TITLE
if profile name is null return undefined 

### LINKED ISSUE #136362: "No default profile" exception when creating a new terminal if default setting is null
On split of ctrl+shift+`, clicking the + silently fails:

image

This should be `<string | null>` or `<unknown>`:

https://github.com/microsoft/vscode/blob/2c390625bcac38c698df84bb806956049ad81ce7/src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts#L145

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #136362

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts [hunk 1]
```diff
@@ -34,7 +34,7 @@ export class TerminalProfileService implements ITerminalProfileService {
 	private _profilesReadyBarrier: AutoOpenBarrier;
 	private _availableProfiles: ITerminalProfile[] | undefined;
 	private _contributedProfiles: IExtensionTerminalProfile[] = [];
-	private _defaultProfileName?: string;
+	private _defaultProfileName: string | null = null;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts:37]: Could keep this and do `getValue<string | null>(...) ?? undefined` instead, to handle the conversion at a single point.
