### PR TITLE
Dangling text file models of deleted files hanging around in memory

### LINKED ISSUE #98057: Dangling text file models of deleted files hanging around in memory
- VSCode Version: 1.45.1
- OS Version: Windows 10

Steps to Reproduce:
Screencast:
dnd1

1. Open sample node project below in VS Code.
[dnd.zip](https://github.com/microsoft/vscode/files/4642123/dnd.zip)
2. Set the setting **"typescript.updateImportsOnFileMove.enabled": "always"** or **"never"**.
3. Click to open multiple files (e.g. **src/utils/ma.ts, src/utils/mb.ts, src/utils/mc.ts, src/utils/md.ts**) in VS Code.
4. In File Explorer, drag and drop these files back and forth several times, e.g. 
```
1st dnd:  utils/m*.ts -> funcs/m*.ts
2st dnd:  funcs/m*.ts -> utils/m*.ts
3rd dnd:  utils/m*.ts -> funcs/m*.ts
```
5. You would see the states for these opened editors are in chaos. Some showed as "**deleted**", see the screenshot below. But actually these files exist. My initial finding was that vscode didn't clear the opened text models for the old locations after the move operation, so that the next time you move back, vscode will try to reuse the previously cached text models.
image

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by bpasero**
This PR fixes #98057

### CODE REVIEW

File: src/vs/workbench/api/browser/mainThreadDocuments.ts [hunk 1]
```diff
@@ -30,14 +31,30 @@ export class BoundModelReferenceCollection {
 		//
 	}
 
-	dispose(): void {
+	dispose(uri?: URI): void {
+		if (uri) {
```
Comment (jrieken) [inline src/vs/workbench/api/browser/mainThreadDocuments.ts:35]: This isn't really needed, right? I am more in favour of keeping `dispose` as-is and only have the special dispose-that-one-resource function.

File: src/vs/workbench/api/browser/mainThreadDocuments.ts [hunk 2]
```diff
@@ -30,14 +31,30 @@ export class BoundModelReferenceCollection {
...
+		}
+	}
+
+	private _disposeAll(): void {
 		this._data = dispose(this._data);
 	}
 
-	add(ref: IReference<ITextEditorModel>): void {
+	private _disposeResource(uri: URI): void {
+		for (const entry of [...this._data] /* copy array because dispose will modify it */) {
```
Comment (jrieken) [inline src/vs/workbench/api/browser/mainThreadDocuments.ts:47]: Learnt something

**Review by jrieken — APPROVED** [review]
👏

File: src/vs/workbench/api/browser/mainThreadDocuments.ts (hunk 1 above)
Comment (bpasero) [reply src/vs/workbench/api/browser/mainThreadDocuments.ts]: @jrieken yeah I pushed https://github.com/microsoft/vscode/pull/98154/commits/cd68bcb0272c0a681fb75a660d7e7798ec247ce9 to have an explicit `remove` method.

I wonder if the use of `isEqualOrParent` is a little bit fishy in this context because it should only be used for URIs that have file system semantics, not for any other. Let me know how you feel about it, we could make that conditional only if the scheme is known to the file service.

Comment (jrieken) [reply src/vs/workbench/api/browser/mainThreadDocuments.ts]: Yeah, it took me a while to understand what this is about at all. I'd say it unlikely to cause false positives
