### PR TITLE
Fix #49777 - Emmet balance In after balance out should go back to initial selection and not first child

### LINKED ISSUE #49777: Emmet balance In after balance out should go back to initial selection and not first child
Using emmet's balance in after using balance out shrinks to incorrect selection.

**Current Behavior:**

**Expected Behavior:**
Currently balance in selects just the first child element for the selected tag. It should select in the order reverse of balance out.

Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

### PR DESCRIPTION
**Pull request by Heldenkrieger01**
This should fix #49777 according to the instructions of @ramya-rao-a.

This is my first contribution, I hope everything is alright 😃.

### CODE REVIEW

File: extensions/emmet/src/balance.ts [hunk 1]
```diff
@@ -56,30 +73,3 @@ function getRangeToBalanceOut(document: vscode.TextDocument, selection: vscode.S
 	}
 	return selection;
 }
-
-function getRangeToBalanceIn(document: vscode.TextDocument, selection: vscode.Selection, rootNode: HtmlNode): vscode.Selection {
```
Comment (ramya-rao-a) [inline extensions/emmet/src/balance.ts]: This function `getRangeToBalanceIn` is needed.
Take the case when the user selects an html node and starts balancing inwards. Then the `beforeEmmetSelection` array will be empty and the command would fail. In this case, we should use `getRangeToBalanceIn`

File: extensions/emmet/src/balance.ts [hunk 2]
```diff
@@ -7,6 +7,10 @@ import * as vscode from 'vscode';
 import { HtmlNode } from 'EmmetNode';
 import { getNode, parseDocument, validate } from './util';
 
+let balanceStack: Array<vscode.Selection[]> = [];
```
Comment (ramya-rao-a) [inline extensions/emmet/src/balance.ts]: In the current code, the `balanceStack` is never reset. Take the case, where the user runs a series of balance out operations. Then they continue with some other work. After some time, they select some text and try to balance in. The current code will pop the stack and give wrong selections

Or take the case of a series of balance out, escape, then another series of balance out in a separate part of the file. Now when you balance in, the stack has selections from the first set which would be wrong

**Review by ramya-rao-a — CHANGES_REQUESTED** [review]
Hi @Heldenkrieger01,

Thanks for the PR and your first contribution! Its a good start. I have left 2 comments for cases when the fix will not work as the stack being maintained gets stale.

My proposal:
- Have a variable that will contain the selections that are applied at the end of every balance out command
- When a new balance in/out command is run, compare current selections with the above. If they are the same, then they all belong to the same stack, else clear the stack.
- When a balance in command is run and the stack is empty, then clear the above variable and use the `getRangeToBalanceIn` method to determine the selections

Thoughts?

**Review by ramya-rao-a — APPROVED** [review]

**Comment by ramya-rao-a** [comment]
@Heldenkrieger01 I have made the necessary changes
