### PR TITLE
Step over surrogate pairs on zero-lenth matches (fixes #100134)

### LINKED ISSUE #100134: Regexp freezes VS Code when code has emoji
- VSCode Version: 1.46.0 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open editor.
2. Create new file.
3. Press win+; select any emoji.
4. Open search panel and select regexp mode.
5. Type /* in search line.
6. RIP.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by IllusionMH**
This PR fixes #100134

Problem lies in fact that regexp with `u` flag will change `lastIndex` to the start of surrogate pair if started after high pair:
```js
const unicodeRe = /()/gu;
const regularRe = /()/g;
unicodeRe.lastIndex = 1;
regularRe.lastIndex = 1;
console.log('unicode', unicodeRe.lastIndex, unicodeRe.exec('💻').index, unicodeRe.lastIndex); // unicode 1 0 0
console.log('regular', regularRe.lastIndex, regularRe.exec('💻').index, regularRe.lastIndex); // regular 1 1 1
```

Which ended attempts to step forward for zero-length matches in endless loop.

This PR takes into account surrogate pairs and propagates `lastIndex` accordingly.
Endless loop during find matches is fixed in this PR.

Not in this PR:
1. In some cases (for files with a lot of matches) it's impossible to use Find next button to get to the next match after surrogate pair. Can give a try in this PR if needed, but would prefer to leave it out of scope of this PR
_(new fallback logic not triggered in that case, but should use similar strategy - remember last position and advance for zero-length matches, but this should survive `reset`)_
What do you think?

1. Inconsistency of handling matches of for surrogate pairs between JS RegExp's with `u` flag and ripgrep
I can create issue with more details but simple example will be for file with 1💻 replace using RegExp `1.` - Find in files breaks surrogate, while replace in editor replaces whole emoji

### CODE REVIEW

File: src/vs/editor/common/model/textModelSearch.ts [hunk 1]
```diff
@@ -548,8 +548,12 @@ export class Searcher {
 			if (matchStartIndex === this._prevMatchStartIndex && matchLength === this._prevMatchLength) {
 				if (matchLength === 0) {
 					// the search result is an empty string and won't advance `regex.lastIndex`, so `regex.exec` will stuck here
-					// we attempt to recover from that by advancing by one
-					this._searchRegex.lastIndex += 1;
+					// we attempt to recover from that by advancing by two if surrogate pair found and by one otherwise
+					if (strings.getNextCodePoint(text, textLength, this._searchRegex.lastIndex) > 0xFFFF) {
```
Comment (IllusionMH) [inline src/vs/editor/common/model/textModelSearch.ts:552]: This one looks closes alternative to "missing" `isSurrogatePair` helper (without recreating logic that involves `isHighSurrogate` and `isLowSurrogate`)

**Comment by alexdima** [comment]
Looks great! Thank you!

**Comment by IllusionMH** [comment]
@alexdima thank you for review!

Could you please provide more insights why when there is large number of matches in file (no in string with current match) it will re-evaluate matches (`reset`/`next`) starting from current match position? 

Had no problem with small files with few matches - Find next can step over emoji and doesn't trigger `reset`/`next`
