### PR TITLE
save to EH synchronously

### LINKED ISSUE #212087: Occasional error notification for notebook save
When working a python jupyter notebook within vscode, I started occasionally seeing this notification:

Image

With this in the dev console: 

```
ERR [stored file working copy] handleSaveError(437) - exit - resulted in a save error: Error: Document version mismatch file:///Users/ulugbekna/code/nlp_course/week01_embeddings/homework.ipynb notebook/jupyter-notebook
```

cc @rebornix 

Version: 1.90.0-insider
Commit: 816c6f7d7bc4da9796cd19ac6b122b6e26f50d7f
Date: 2024-05-03T18:08:45.720Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

### PR DESCRIPTION
**Pull request by amunger**
fix https://github.com/microsoft/vscode/issues/212087

when saving on EH, make sure to collect the data to be saved synchronously so that the version cannot be incremented in the middle of the action.

### CODE REVIEW

File: src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts [hunk 1]
```diff
@@ -77,7 +77,7 @@ export interface IStoredFileWorkingCopyModel extends IFileWorkingCopyModel {
 	 * which is to ask the model for a `snapshot` and then
 	 * writing that to the model's resource.
 	 */
-	save?(options: IWriteFileOptions, token: CancellationToken): Promise<IFileStatWithMetadata>;
+	getSaveDelegate(): ((options: IWriteFileOptions, token: CancellationToken) => Promise<IFileStatWithMetadata>) | undefined;
```
Comment (bpasero) [inline src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts:80]: This method should be optional and if defined, should not return `undefined`.

Comment (bpasero) [reply src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts:80]: Maybe this could be a property rather than a method? And then please also introduce a `IStoredFileWorkingCopySaveDelegate` interface with documentation.

**Review by bpasero — DISMISSED** [review]
I only checked the changes in stored working copy land.

File: src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts (hunk 1 above)
Comment (amunger) [reply src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts:80]: There needs to be a way for a defined method to indicate that the delegate should not be used for the fix that I'm trying to implement here. If something requires going async before we collect the notebook data to be saved, we don't want this method to be used.
Or we could rely on the model being resolved (it probably always is) and throw if not.

Comment (bpasero) [reply src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts:80]: But that can still be a property, which if defined, can indicate this?

Comment (amunger) [reply src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts]: no more changes to working copy land

Comment (bpasero) [reply src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts]: Nice!

**Comment by bpasero** [comment]
Will defer to @rebornix review.

**Review by rebornix — APPROVED** [review]
