### PR TITLE
Handle error in getting wsl distros

### LINKED ISSUE #120119: Cannot select profile if WSL is not installed
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Don't have WSL installed
2. Select Default Profile:

image

3. Nothing happens... in Dev tools I see this:

> ERR Problem occurred when getting wsl distros

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #120119

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/node/terminalProfiles.ts [hunk 1]
```diff
@@ -64,7 +64,15 @@ async function detectAvailableWindowsProfiles(configuredProfilesOnly: boolean, s
...
-		resultProfiles.push(... await getWslProfiles(`${system32Path}\\${useWSLexe ? 'wsl.exe' : 'bash.exe'}`, useWslProfiles));
+		let result;
+		try {
+			result = await getWslProfiles(`${system32Path}\\${useWSLexe ? 'wsl.exe' : 'bash.exe'}`, useWslProfiles);
+		} catch (e) {
+			logService?.info('WSL is not installed so could not detect WSL profiles');
+		}
+		if (result) {
+			resultProfiles.push(...result);
+		}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/node/terminalProfiles.ts:75]: We could just move this in the `try` to prevent creating `result`:

```
resultProfiles.push(... await getWslProfiles(`${system32Path}\\${useWSLexe ? 'wsl.exe' : 'bash.exe'}`, useWslProfiles));
```

**Review by Tyriar — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]
