### PR TITLE
fix leaking event listeners

### LINKED ISSUE #207453: Leaking event listener
https://github.com/microsoft/vscode/blob/be776fbfff16d18b19457cc271e4e049b766490d/src/vs/workbench/services/search/common/searchService.ts#L212

fyi that you use `raceCancellation` instead

### LINKED ISSUE #207455: Leaking event listener
https://github.com/microsoft/vscode/blob/be776fbfff16d18b19457cc271e4e049b766490d/src/vs/workbench/contrib/search/browser/searchView.ts#L235

### LINKED ISSUE #207456: Leaking event listener
https://github.com/microsoft/vscode/blob/be776fbfff16d18b19457cc271e4e049b766490d/src/vs/workbench/contrib/search/browser/searchWidget.ts#L382

### PR DESCRIPTION
**Pull request by andreamah**
Fixes https://github.com/microsoft/vscode/issues/207453

Fixes https://github.com/microsoft/vscode/issues/207455

Fixes https://github.com/microsoft/vscode/issues/207456

### CODE REVIEW

File: src/vs/workbench/contrib/search/browser/searchWidget.ts [hunk 1]
```diff
@@ -170,6 +171,7 @@ export class SearchWidget extends Widget {
 	public contextLinesInput!: InputBox;
 
 	private _notebookFilters: NotebookFindFilters;
+	private _toggleReplaceButtonListener: IDisposable | undefined;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/search/browser/searchWidget.ts:174]: Perfect place to use `MutableDisposable`

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/search/browser/searchWidget.ts (hunk 1 above)
Comment (andreamah) [reply src/vs/workbench/contrib/search/browser/searchWidget.ts]: Fixed!

**Review by rzhao271 — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]
