### PR TITLE
Fix multiple editors being marked as active

### LINKED ISSUE #122739: Multiple editors marked as "currently active"
- Open a notebook
- Run "Reopen editor with"
- Can't switch to text editor because it's marked as active already

image

### PR DESCRIPTION
**Pull request by lramos15**
This PR fixes #122739

Wasn't checking if it was a text editor. This meant `.matches` was always active.

### CODE REVIEW

File: src/vs/workbench/services/editor/browser/editorService.ts [hunk 1]
```diff
@@ -524,7 +524,7 @@ export class EditorService extends Disposable implements EditorServiceImpl {
 				id: DEFAULT_EDITOR_ASSOCIATION.id,
 				label: DEFAULT_EDITOR_ASSOCIATION.displayName,
 				detail: DEFAULT_EDITOR_ASSOCIATION.providerDisplayName,
-				describes: (currentEditor) => currentEditor.matches(this.activeEditor),
+				describes: (currentEditor) => this.fileEditorInputFactory.isFileEditorInput(currentEditor) && currentEditor.matches(this.activeEditor),
 				priority: ContributedEditorPriority.builtin
 			},
```
Comment (connor4312) [inline src/vs/workbench/services/editor/browser/editorService.ts:529]: Test comment for issue verification, please ignore

File: src/vs/workbench/services/editor/browser/editorService.ts [hunk 2]
```diff
@@ -524,7 +524,7 @@ export class EditorService extends Disposable implements EditorServiceImpl {
 				id: DEFAULT_EDITOR_ASSOCIATION.id,
 				label: DEFAULT_EDITOR_ASSOCIATION.displayName,
 				detail: DEFAULT_EDITOR_ASSOCIATION.providerDisplayName,
-				describes: (currentEditor) => currentEditor.matches(this.activeEditor),
+				describes: (currentEditor) => this.fileEditorInputFactory.isFileEditorInput(currentEditor) && currentEditor.matches(this.activeEditor),
```
Comment (roblourens) [inline src/vs/workbench/services/editor/browser/editorService.ts:527]: What is `describes` supposed to check? I thought it was checking the _type_ of the given editor input, but this is checking that the input is a particular instance which is the active editor?

Comment (lramos15) [reply src/vs/workbench/services/editor/browser/editorService.ts:527]: `describes` is used to figure out if your contribution is the editor passed into the function. It's normally the active editor so in this case we see if it's a fileEditor and if so make sure it's not the active one. I used to have the function be called `active`, but Ben felt it was better as describes.

Comment (lramos15) [reply src/vs/workbench/services/editor/browser/editorService.ts:527]: You could probably get away without the matches, but I don't want to break it this close to release. So I just added the important thing which is to make sure it's a file editor input.

Comment (roblourens) [reply src/vs/workbench/services/editor/browser/editorService.ts:527]: I see, yeah it seems like you would just want the file editor check

**Review by roblourens — APPROVED** [review]
