### PR TITLE
[typescript-language-features] Fix autoImportFileExcludePatterns format to work on Windows

### LINKED ISSUE #55781: Auto import does not import Disposable or Emitter from VS Code's codebase
Related to https://github.com/microsoft/vscode/issues/116375

This issue has been around for years, I think I've mentioned it in DMs but not sure if there's an issue. Regardless, here's a detailed description of it. I'm assuming this is an upstream issue but please keep this issue open to track as it's a papercut.

This does impact my productivity; instead of auto import just working like it's supposed to, I instead have to:

1. Import one of the other symbols
2. Scroll to the top of the file
3. Find the import
4. Change the import
5. Go back
6. Change the symbol I entered in step 1

---

Image

`AsyncEmitter` and `EmitterOptions` shows up:

https://github.com/microsoft/vscode/blob/85de2f21c63608e8bbc5c2347fe927b00c8300bf/src/vs/base/common/event.ts#L1184

https://github.com/microsoft/vscode/blob/85de2f21c63608e8bbc5c2347fe927b00c8300bf/src/vs/base/common/event.ts#L695

But not `Emitter`:

https://github.com/microsoft/vscode/blob/85de2f21c63608e8bbc5c2347fe927b00c8300bf/src/vs/base/common/event.ts#L897

---

Image

Image

`DisposableStore` and `DisposableMap` shows up:

https://github.com/microsoft/vscode/blob/85de2f21c63608e8bbc5c2347fe927b00c8300bf/src/vs/base/common/lifecycle.ts#L210

https://github.com/microsoft/vscode/blob/85de2f21c63608e8bbc5c2347fe927b00c8300bf/src/vs/base/common/lifecycle.ts#L503

But not `Disposable`:

Image

### LINKED ISSUE #56415: typescript.preferences.autoImportFileExcludePatterns unable to exclude a specific file with TS aliases
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: Windows 11 Pro, 22621.2428
- I have tried VS Code insiders (latest) and also to run with `--disable-extensions` too, neither worked.

I have tried to look for this issue online but can't find anything about it. I have a `lib.ts` file in my `src` folder in a typescript project which contains exports for building my package as a library. The problem is VS Code keeps very frequently auto importing from this file (via path aliases, so it imports `@/lib`, which is equivalent to `src/lib.ts`, instead of the real file path, causing circular import problems.

This is in a multi-root workspace, although if I try to open the specific package folder by itself (so without a workspace and without multi-root), I still get the same problem.

Steps to Reproduce:

1. Have a multi-root workspace project (might not be relevant, I get the issue even without it)
2. Have script aliases in tsconfig setting up `@/*` to alias to `src/*`
3. Have a `src/lib.ts` file exporting lots of things
4. Have `typescript.preferences.autoImportFileExcludePatterns` in workspace settings with various patterns to exclude that file (I've tried to put those both at the root of the multi-root workspace, or directly in the package folder)
5. Try writing code in other places, notice VS Code keeps importing from `src/lib.ts` no matter what exclude pattern is attempted.

Here are the patterns I've tried adding to settings:

```json
{
  "typescript.preferences.autoImportFileExcludePatterns": [
    "@/lib/**",
    "@/lib**",
    "@/lib",
    "@/lib.ts",
    "**/lib.ts",
    "**/lib",
    "src/lib",
    "**/node_modules/**",
    "**/dist/**",
    "**/lib/**",
    "src/lib.ts",
    "lib.ts",
    "packages/narrat/src/lib.ts",
    "src/lib/*",
    "lib",
    "**/lib.ts"
  ]
}
```

So I tried various patterns with the alias, without the alias, and also hard paths to the package just in case. None of those values are working, whether I'm running the multi-root workspace or directly opening the package folder itself, and I've tried putting them both in the root `.code-workspace` file, and the folder's `settings.json`. They are definitely being picked up, because they appear in the settings editor:

image

<details>
<summary>Full workspace json config:</summary>

```json
{
  "folders": [
    {
      "name": "narrat",
      "path": "packages/narrat"
    },
    {
      "name": "root",
      "path": "."
    },
    {
      "name": "docs",
      "path": "docs"
    }
  ],
  "settings": {
    "vitest.enable": true,
    "editor.tabSize": 2,
    "files.exclude": {
      "src/lib.ts": true,
      "**/dist/*": true,
      "**/lib/*": true,
      "node_modules/": true,
      "packages/": true,
      "docs/": true,
      "demo-template": true,
      "**/*.rpyc": true,
      "**/*.rpa": true,
      "**/*.rpymc": true,
      "**/cache/": true,
      "**/lib.ts": true
    },
    "search.exclude": {
      "src/lib.ts": true,
      "dist/": true,
      "lib/": true,
      "**/lib": true,
      "node_modules/": true,
      "**/lib.ts": true
    },
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "[javascript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[typescript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "typescript.preferences.autoImportFileExcludePatterns": [
      "@/lib/**",
      "@/lib**",
      "@/lib",
      "@/lib.ts",
      "**/lib.ts",
      "**/lib",
      "src/lib",
      "**/node_modules/**",
      "**/dist/**",
      "**/lib/**",
      "src/lib.ts",
      "lib.ts",
      "packages/narrat/src/lib.ts",
      "src/lib/*",
      "lib",
      "**/lib.ts"
    ],
    "javascript.preferences.autoImportFileExcludePatterns": ["@lib"],
    "javascript.preferences.importModuleSpecifier": "shortest",
    "typescript.preferences.importModuleSpecifier": "shortest"
  }
}
```
</details>

Just in case, here's the `tsconfig.json` for that folder:

<details>
<summary>tsconfig.json</summary>

```json
{
  "compilerOptions": {
    "target": "esnext",
    "baseUrl": "./",
    "useDefineForClassFields": true,
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "outDir": "dist",
    "sourceMap": true,
    "isolatedModules": true,
    "resolveJsonModule": true,
    "declaration": true,
    "esModuleInterop": true,
    "allowJs": true,
    "lib": ["esnext", "dom"],
    "skipLibCheck": true,
    "paths": {
      "@/*": ["src/*"]
    },
    "types": ["@testing-library/jest-dom"],
    "typeRoots": ["src/types/", "node_modules/@types/"]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "src/tests.setup.ts"
  ],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

</details>

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes https://github.com/microsoft/TypeScript/issues/56415
Fixes https://github.com/microsoft/TypeScript/issues/55781

Counterpart to https://github.com/microsoft/TypeScript/pull/57090. The TypeScript change mostly fixes things on its own, but this change provides a 99% fix even when using an older TS Server version.

### CODE REVIEW

File: extensions/typescript-language-features/src/languageFeatures/fileConfigurationManager.ts [hunk 1]
```diff
@@ -215,12 +215,16 @@ export default class FileConfigurationManager extends Disposable {
...
 		return workspaceFolder && config.get<string[]>('autoImportFileExcludePatterns')?.map(p => {
 			// Normalization rules: https://github.com/microsoft/TypeScript/pull/49578
-			const slashNormalized = p.replace(/\\/g, '/');
-			const isRelative = /^\.\.?($|\/)/.test(slashNormalized);
+			const isRelative = /^\.\.?($|[\/\\])/.test(p);
+			// In TypeScript < 5.3, the first path component cannot be a wildcard, so we need to prefix
+			// it with a path root (e.g. `/` or `c:\`)
+			const wildcardPrefix = this.client.apiVersion.gte(API.v540)
+				? ''
+				: path.parse(this.client.toTsFilePath(workspaceFolder)!).root;
```
Comment (andrewbranch) [inline extensions/typescript-language-features/src/languageFeatures/fileConfigurationManager.ts:223]: @mjbvz can you help confirm that this non-null assertion is safe here? I looked at the implementation and the only way it can return `undefined` is

```ts
if (fileSchemes.disabledSchemes.has(resource.scheme)) {
  return undefined;
}
```

I feel like we wouldn’t make it this far if that were the case for the workspace folder, but I’m not confident.

**Comment by andrewbranch** [comment]
@mjbvz I just noticed this is still open. Could you take a look? Thanks!

**Review by mjbvz — APPROVED** [review]

**Review by jrieken — APPROVED** [review]
