### PR TITLE
A11y: Disable forced color adjustment for Monaco editor

### LINKED ISSUE #4942: In High contrast Aquatic and desert mode disabled control controls visually appearing as enabled controls: A11y_MonacoEditor_ No Disruption of Accessibility Features
### Reproducible in vscode.dev or in VS Code Desktop?

- [x] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

_No response_

### Monaco Editor Playground Code

```typescript

```

### Reproduction Steps

GitHubTags:
#A11yTCS; #A11ySev2; #A11yMAS; #WCAG4.3.1; #Desktopweb; #Win11; #Visual Studio Code Client; #VisualStudioCode-Web-Apr2021; #Chrome; #a11y-monacoeditor; #DevTools; #PartnerBug; # No Disruption of Accessibility Features:

Environment Details:
#URL: https://microsoft.github.io/monaco-editor/playground.html?source=v0.52.2#XQAAAAJjAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscwzZypW_1uhs0-3YGTBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKimARHSWlrTPOQHROITHxmAetfeRrm3VHdSe7_Etv6WpgzlH4o4eQ6dMnzwfwYcUqOiZ_ge3TaAC-S-3X8NnmdsBgoPipQD3aPDiLZZPK6l7xCFp8ZECZbOE6TnVWRQ5d9hpoWU6fPQxCmvXOHG0yQjnpBbUFcTVnmLIgKYp_MMpyC98ktGgml-3rke-U2SAGxZ_LvB8DSxLE1KkD9hE5voTWZUnA5LHB1fNAbw8DB8v_jVO8Ng
Application name: Monaco Editor
Chrome: Version 131.0.6778.205 (Official Build) (64-bit)
Windows 11 Enterprise (Version 23H2)  
OS Build 22631.3737

Repro Steps:
Hit the URL: https://microsoft.github.io/monaco-editor/playground.html?source=v0.52.2#example-creating-the-editor-hello-world.
Monaco editor page will appear. TAB to code editor and press ctrl+ F key .
Apply high contrast.
Observe that In High contrast Aquatic and desert mode disabled control controls visually appearing as enabled controls.

Actual Results:
 In High contrast Aquatic and desert mode disabled control controls visually appearing as enabled controls.

Expected Results:
The disable 'previous match and next match' button border should be visible as disable in High contrast 'aquatic and desert' modes.

User Impact:
Low vision users who depend on contrast modes will face difficulty in identifying the functionality of the control and will get confused.

Attachment:;

### Actual (Problematic) Behavior

_No response_

### Expected Behavior

_No response_

### Additional Context

_No response_

### LINKED ISSUE #4945: {Linked:Bug10274492}After enabling High Contrast, unable to see the selection when highlighting text: A11y_MonacoEditor_ No Disruption of Accessibility Features
### GitHubTags:
#A11yTCS; #A11ySev2; #A11yMAS; #WCAG4.3.1; #Desktopweb; #Win11; #Visual Studio Code Client; #VisualStudioCode-Web-Apr2021; #ChromiumEdge; #a11y-monacoeditor; #DevTools; #PartnerBug; # No Disruption of Accessibility Features:#ED:Bug10274492;

### Environment Details:
#URL: https://microsoft.github.io/monaco-editor/playground.html?source=v0.52.2#XQAAAAJjAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscwzZypW_1uhs0-3YGTBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKimARHSWlrTPOQHROITHxmAetfeRrm3VHdSe7_Etv6WpgzlH4o4eQ6dMnzwfwYcUqOiZ_ge3TaAC-S-3X8NnmdsBgoPipQD3aPDiLZZPK6l7xCFp8ZECZbOE6TnVWRQ5d9hpoWU6fPQxCmvXOHG0yQjnpBbUFcTVnmLIgKYp_MMpyC98ktGgml-3rke-U2SAGxZ_LvB8DSxLE1KkD9hE5voTWZUnA5LHB1fNAbw8DB8v_jVO8Ng
Application name: Monaco Editor
Chromium Edge: Version 138.0.3351.95 (Official build) (64-bit)
Windows 11 Enterprise (Version 23H2)  
OS Build 22631.3737

### Repro Steps:

1. Hit the URL: https://microsoft.github.io/monaco-editor/playground.html?source=v0.52.2#example-creating-the-editor-hello-world.
2. Monaco editor page will appear.
3. Apply high contrast.
4. Observe that In After enabling High Contrast, unable to see the selection when highlighting text.

### Actual Results:
After enabling High Contrast, unable to see the selection when highlighting text.

### Expected Results:
After applying High Contrast, User should be able to see the selection while selecting text..

### User Impact:
Low vision users may have trouble identifying selected text if they cannot see the selection when using High Contrast mode.

### Attachment:

https://github.com/user-attachments/assets/72a5db4d-b958-4691-9bda-62a3747c0117

### LINKED ISSUE #4985: In high contrast aquatic or desert modes, cursor is not visible at 'plain text': A11y_MonacoEditor_High Contrast
### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0-dev.20230707#XQAAAAKlAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw2Kir5Juetpg8d5BCIdogK6CBmgyKHIOVjH6uO-oA-RA-rcpQdGBlgwMT7NDeGjyzFr76MYz0c_YZhkfVact66KR8EKI9H0wOi-Q6tpDt-O42AX4Vj2BBGCeVYFhuwwQHQ084HXevxFU6s-aiyWw_iVEKmIVfS1mf-DaP5DuuJ9ninHo2zYoxRUK6gbOmW-kkEFhe84sCJio9lqPwjgEUbfAMk52muZB43edii8a6ay0CNuV1k16w8W6kt0kIlpz_rHCLlPrBGxJ3G5aWhuvMqA05A2XT_oDw060WX7VLyNNhagA1yGSkMrHmbmj7PTZb-kmmUw

### GitHubTags:
#A11yTCS; #A11ySev2; #A11yMAS; #WCAG4.3.1; #Desktopweb; #Win11; #Visual Studio Code Client; #VisualStudioCode-Web-Apr2021; #ChromiumEdge; #a11y-monacoeditor; #DevTools; #PartnerBug; # No Disruption of Accessibility Features:#External:BUG6023023;CAI:BUG6023023

### Environment Details:
#URL: https://microsoft.github.io/monaco-editor/playground.html?source=v0.52.2#XQAAAAJjAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscwzZypW_1uhs0-3YGTBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKimARHSWlrTPOQHROITHxmAetfeRrm3VHdSe7_Etv6WpgzlH4o4eQ6dMnzwfwYcUqOiZ_ge3TaAC-S-3X8NnmdsBgoPipQD3aPDiLZZPK6l7xCFp8ZECZbOE6TnVWRQ5d9hpoWU6fPQxCmvXOHG0yQjnpBbUFcTVnmLIgKYp_MMpyC98ktGgml-3rke-U2SAGxZ_LvB8DSxLE1KkD9hE5voTWZUnA5LHB1fNAbw8DB8v_jVO8Ng
Application name: Monaco Editor
Windows 11 Enterprise (Version 24H2)  
OS build :26100.4770  

### Repro Steps:

1. Hit the URL: https://microsoft.github.io/monaco-editor/playground.html?source=v0.52.2#example-creating-the-editor-hello-world.
2. Monaco editor page will appear.
3. Apply high contrast.
4. Observe that In high contrast aquatic or desert modes, cursor is not visible at 'plain text'.

### Actual Results:
In high contrast aquatic or desert modes, cursor is not visible at 'plain text'.

### Expected Results:
In  'Aquatic & desert' mode, the contrast ratio for cursor present in 'plain text' should be clearly visible to the users,

### User Impact:
Low vision users cannot see where the cursor is, making it difficult to interact with or edit plain text fields.

### Attachment:

https://github.com/user-attachments/assets/c75768f3-dda6-4666-96b4-9d5960846939

Image

### PR DESCRIPTION
**Pull request by hawkticehurst**
Resolves https://github.com/microsoft/monaco-editor/issues/4942 
Resolves https://github.com/microsoft/monaco-editor/issues/4945
Resolves https://github.com/microsoft/monaco-editor/issues/4985

This PR disables forced color adjustment for the Monaco editor. This change matches what we do in VS Code desktop and now the editor will rely on the custom built-in high contrast themes that we ship instead.

### CODE REVIEW

**Review by meganrogge — DISMISSED** [review]
👏🏼

**Review by bpasero — COMMENTED** [review]
🤔 this seems like a very isolated change in one area, does this impact all actions that show disabled?

**Review by Tyriar — DISMISSED** [review]

**Comment by hawkticehurst** [comment]
I can get behind that and am happy to draft up a new PR for the monaco editor repo. @bpasero does that sound good to you?

*Would also do the same for https://github.com/microsoft/vscode/pull/265430 which tackles a similar issue but for `::selection` colors.

**Review by mjbvz — DISMISSED** [review]

**Comment by hawkticehurst** [comment]
@aeschli @bpasero reverted the old CSS change and made some updates. Not quite sure if this was the direction you were thinking, but was my attempt at still having declarative color tokens inside the theme file and making sure that the color changes only get applied when forced colors is active.

Bonus: Since system colors are finite, I also added typing so that autocomplete / intellisense kicks in nicely when adding new tokens in the future.

Let me know what you think and if you'd like me to go a different direction instead.

**Comment by hawkticehurst** [comment]
Oh two more things:

1. I included the changes to fix https://github.com/microsoft/vscode/pull/265430 as well –– if you're happy with this PR, I'll close the other one, rename this one, and let it resolve both issues.
2. I'm not actually sure how to test / validate these changes beyond your reviews. As @aeschli mentioned VS Code does support forced colors mode, but I also learned recently from @hediet that the Monaco Editor Playground debug task has been broken for awhile and will probably get removed. Any thoughts or do we just release this to Insiders and test in the browser-based playground via the latest release dropdown?

**Review by bhavyaus — DISMISSED** [review]

**Comment by aeschli** [comment]
adding `.monaco-editor { forced-color-adjust: none; }` is the simplest fix.  It brings Monaco en par with we do in VS Code. Properly supporting (and maintaining) a forced color theme is not trivial. Needs more work and testing (and maintenance)

**Review by meganrogge — APPROVED** [review]

File: src/vs/editor/standalone/browser/standaloneThemeService.ts [hunk 1]
```diff
@@ -263,7 +263,11 @@ export class StandaloneThemeService extends Disposable implements IStandaloneThe
 		}));
 
 		addMatchMediaChangeListener(mainWindow, '(forced-colors: active)', () => {
+			// Update theme selection for auto-detecting high contrast
 			this._onOSSchemeChanged();
+			// Always rebuild the generated CSS so that the `forced-color-adjust: none`
+			// rule is added/removed reactively when the OS forced colors state changes.
+			this._updateThemeOrColorMap();
```
Comment (aeschli) [inline src/vs/editor/standalone/browser/standaloneThemeService.ts:270]: Is that necessary? I think that's already triggered from_onOSSchemeChanged when needed

File: src/vs/editor/standalone/browser/standaloneThemeService.ts [hunk 2]
```diff
@@ -399,6 +403,13 @@ export class StandaloneThemeService extends Disposable implements IStandaloneThe
 		const colorMap = this._colorMapOverride || this._theme.tokenTheme.getColorMap();
 		ruleCollector.addRule(generateTokensCSSForColorMap(colorMap));
 
+		// If the OS has forced-colors active, disable forced color adjustment for
+		// Monaco editor elements so that VS Code's built-in high contrast themes
+		// (hc-black / hc-light) are used instead of the OS forcing system colors.
+		if (mainWindow.matchMedia(`(forced-colors: active)`).matches) {
```
Comment (aeschli) [inline src/vs/editor/standalone/browser/standaloneThemeService.ts:409]: No need to check that, 'forced-color-adjust: none;' can be added also when forced colors are off, it has no effect then.
See how it is done for VS Code:
https://github.com/microsoft/vscode/blob/1852c9eb8b487879c14cae041b38d2d051b92361/src/vs/workbench/services/themes/browser/workbenchThemeService.ts#L470
