### PR TITLE
fix focus on `closeWidget`

### LINKED ISSUE #214285: calling `closeWidget` on the references view with `focusEditor=false` will still focus editor
Found while testing https://github.com/microsoft/vscode/pull/205914

1. Open up a search editor 
2. Peek a go to definition view.
3. Search for something in the search editor with the definition still open.
5. Notice that the editor focuses. :bug:

If you do the same think without keeping the definition open, then the input stays focused.

When digging into this, it is because this is called twice- once with the correct `focusEditor=false` and another with the default arg.
https://github.com/microsoft/vscode/blob/1b25a13761d5e0db1308309a30ea8cf98a383796/src/vs/editor/contrib/gotoSymbol/browser/peek/referencesController.ts#L229-L240
Disposing the widget causes `_onDidClose` to fire again with default args. 
https://github.com/microsoft/vscode/blob/0bd70d48ad8b3e2fb1922aa54f87c786ff2b4bd8/src/vs/editor/contrib/peekView/browser/peekView.ts#L135

### PR DESCRIPTION
**Pull request by andreamah**
Fixes https://github.com/microsoft/vscode/issues/214285

cc @jrieken since this is in your feature area. Just a fix to prevent `closeWidget` to be called twice. You can see the linked issue for more info.

### CODE REVIEW

File: src/vs/editor/contrib/gotoSymbol/browser/peek/referencesController.ts [hunk 1]
```diff
@@ -227,7 +232,7 @@ export abstract class ReferencesController implements IEditorContribution {
 	}
 
 	closeWidget(focusEditor = true): void {
-		this._widget?.dispose();
+		this._widget?.disposeFromClose();
```
Comment (jrieken) [inline src/vs/editor/contrib/gotoSymbol/browser/peek/referencesController.ts:235]: Not a fan of having `disposeFromClose` and `dispose`. Could we instead change this method to only run once, like have a boolean `_isClosing` and exit early if this is set because closing once is enough.

**Review by jrieken — COMMENTED** [review]
Thanks for the investigation and good findings. I believe a more local fix inside the controller would be simpler and also fix this.

File: src/vs/editor/contrib/gotoSymbol/browser/peek/referencesController.ts (hunk 1 above)
Comment (andreamah) [reply src/vs/editor/contrib/gotoSymbol/browser/peek/referencesController.ts]: Fixed!

**Review by jrieken — APPROVED** [review]
Thanks!
