### PR TITLE
Fixes error after reload window when terminal panel is hidden

### LINKED ISSUE #126642: Error after reload window when terminal panel is hidden
- VS Code Version: stable and from sources

Steps to Reproduce:

1. Create a terminal
2. Hide terminal panel
3. Reload window
4. :bug: Error shows in dev tools console

```
  ERR Cannot read property '_renderer' of undefined: TypeError: Cannot read property '_renderer' of undefined
    at hi._measureRenderTime (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2851:113547)
```
terminal_reload_error

### PR DESCRIPTION
**Pull request by jeanp413**
This PR fixes #126642

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 1]
```diff
@@ -684,12 +684,6 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 
 		xterm.open(this._xtermElement);
 
-		const suggestedRendererType = this._storageService.get(SUGGESTED_RENDERER_TYPE, StorageScope.GLOBAL);
-		if (this._configHelper.config.gpuAcceleration === 'auto' && (suggestedRendererType === 'auto' || suggestedRendererType === undefined)
-			|| this._configHelper.config.gpuAcceleration === 'on') {
-			this._enableWebglRenderer();
-		}
-
```
Comment (jeanp413) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:692]: I deleted this as `this._enableWebglRenderer()` is called again inside `this.updateConfig();` line 819

**Comment by meganrogge** [comment]
Looks good, thanks!
