### PR TITLE
Validate URLs in open browser tool

### LINKED ISSUE #299437: "Open in integrated browser" opens empty
Type: <b>Bug</b>

It had the correct file path but that didn't make it through:

Image

Extension version: 0.39.2026030501
VS Code version: Code - Insiders 1.111.0-insider (b929e4a80a4efef27d78998dad24e015ed7313cd, 2026-03-04T20:49:49-08:00)
OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2
Modes:

<details><summary>Prompt Details</summary>
<pre>
Info: [messagesAPI] message 0 returned. finish reason: [stop]
Trace: [messagesAPI]SSE: [DONE]
Info: ccreq:96ab3d45.copilotmd | success | claude-opus-4.6-1m -> claude-opus-4-6 | 4014ms | [panel/editAgent]
Trace: Resolving chat model
Debug: AgentIntent: rendering with budget=788096 (baseBudget: 935997, toolTokens: 8825), summarizationEnabled=true
Trace: [CopilotCLI] [DIFF] getActiveDiffByTab: tab is not a diff tab
Trace: [CopilotCLI] [DIFF] getActiveDiffByTab: tab is not a diff tab
Trace: [CopilotCLI] [DIFF] getActiveDiffByTab: tab is not a diff tab
Trace: Resolving chat model
Trace: Resolving chat model
Trace: [CopilotCLI] [DIFF] getActiveDiffByTab: tab is not a diff tab
Trace: [CopilotCLI] [DIFF] getActiveDiffByTab: tab is not a diff tab
Trace: Resolving chat model
Trace: Built prompt
Trace: Sending prompt to model
Debug: [PowerService] Acquired power save blocker, active count: 1
Debug: modelMaxPromptTokens 935997
Debug: modelMaxResponseTokens 64000
Debug: chat model claude-opus-4.6-1m
Debug: GH request id: 7055:95F7A:FD7A2:115F2A:69A956C4
Debug: request.response: [{"type":"ChatMessages"}], took 2282 ms
Debug: [PowerService] Released power save blocker acquisition, active count: 0
Debug: [PowerService] Scheduling power save blocker release in 120000ms
Trace: [messagesAPI]SSE: {"message":{"content":[],"id":"msg_vrtx_019imipxZF9arKBWu9FrmBHN","model":"claude-opus-4-6","role":"assistant","stop_reason":null,"stop_sequence":null,"type":"message","usage":{"cache_creation":{"ephemeral_1h_input_tokens":0,"ephemeral_5m_input_tokens":123},"cache_creation_input_tokens":123,"cache_read_input_tokens":19112,"input_tokens":1,"output_tokens":2}},"type":"message_start"}
Trace: [messagesAPI]SSE: {"content_block":{"text":"","type":"text"},"index":0,"type":"content_block_start"}
Trace: [messagesAPI]SSE: {"delta":{"text":"Opened","type":"text_delta"},"index":0,"type":"content_block_delta"}
Trace: [messagesAPI]SSE: {"delta":{"text":" [","type":"text_delta"},"index":0,"type":"content_block_delta"}
Trace: [messagesAPI]SSE: {"delta":{"text":"index.html](index.html)","type":"text_delta"},"index":0,"type":"content_block_delta"}
Trace: [messagesAPI]SSE: {"delta":{"text":" in the browser.","type":"text_delta"},"index":0,"type":"content_block_delta"}
Trace: [messagesAPI]SSE: {"delta":{"text":" You","type":"text_delta"},"index":0,"type":"content_block_delta"}
Trace: [messagesAPI]SSE: {"delta":{"text":" should","type":"text_delta"},"index":0,"type":"content_block_delta"}
Trace: [messagesAPI]SSE: {"delta":{"text":" see the Game of Life grid","type":"text_delta"},"index":0,"type":"content_block_delta"}
Trace: [messagesAPI]SSE: {"delta":{"text":" with","type":"text_delta"},"index":0,"type":"content_block_delta"}
Trace: [messagesAPI]SSE: {"delta":{"text":" the pattern","type":"text_delta"},"index":0,"type":"content_block_delta"}
Trace: [messagesAPI]SSE: {"delta":{"text":" sidebar","type":"text_delta"},"index":0,"type":"content_block_delta"}
Trace: [messagesAPI]SSE: {"delta":{"text":" on the left and controls","type":"text_delta"},"index":0,"type":"content_block_delta"}
Trace: [messagesAPI]SSE: {"delta":{"text":" at","type":"text_delta"},"index":0,"type":"content_block_delta"}
Trace: [messagesAPI]SSE: {"delta":{"text":" the top","type":"text_delta"},"index":0,"type":"content_block_delta"}
Trace: [messagesAPI]SSE: {"delta":{"text":".","type":"text_delta"},"index":0,"type":"content_block_delta"}
Trace: [messagesAPI]SSE: {"index":0,"type":"content_block_stop"}
Trace: [messagesAPI]SSE: {"delta":{"stop_reason":"end_turn","stop_sequence":null},"type":"message_delta","usage":{"cache_creation_input_tokens":123,"cache_read_input_tokens":19112,"input_tokens":1,"output_tokens":39}}
Trace: [messagesAPI]SSE: {"type":"message_stop"}
Info: [messagesAPI] message 0 returned. finish reason: [stop]
Trace: [messagesAPI]SSE: [DONE]
Info: ccreq:df1e0a98.copilotmd | success | claude-opus-4.6-1m -> claude-opus-4-6 | 2300ms | [panel/editAgent]
Info: [ToolCallingLoop] Stop hook result: shouldContinue=false, reasons=undefined
Trace: Resolving chat model
Debug: [context keys] Window state change. Needs offline check: false, active: true, focused: false.
Debug: [context keys] Window state change. Needs offline check: false, active: true, focused: true.
Trace: [CLISessionItemProvider] provideChatSessionItems: 0 session(s) to convert
</pre>
</details>
<details><summary>Request IDs</summary>
<pre>
353c3f9c-6c5e-4ccd-800d-3a43c31424f2
d6770b0c-aab6-4d33-b535-132f5683cabc
4997e0d7-479e-4460-92be-1cc66487a35c
8b331140-c43c-45d1-8b63-3682ebf788df
c23a48a3-022c-4fc1-8e1d-15c217d2aef1
78fd48d1-2373-4a75-8b26-dfff7133de93
26c90421-50e7-4cef-a14d-e8364add9d06
</pre>
</details><details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (16 x 0)|
|GPU Status|2d_canvas: unavailable_software<br>GPU0: VENDOR= 0xffff [Google Inc. (Google)], DEVICE=0xffff [ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver-5.0.0)], DRIVER_VENDOR=SwANGLE, DRIVER_VERSION=5.0.0 *ACTIVE*<br>Machine model name: <br>Machine model version: <br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>trees_in_viz: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|31.32GB (29.33GB free)|
|Process Argv|--transient --user-data-dir /tmp/vscode-skOUaemp/data --extensions-dir /tmp/vscode-skOUaemp/extensions --crash-reporter-id 90859db6-ab22-4a03-b74a-eeece9c436a3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
pythonvspyt551:31249597
nativeloc1:31118317
dwcopilot:31158714
dwoutputs:31242946
copilot_t_ci:31333650
g012b348:31231168
pythonrdcb7:31268811
pythonpcpt1:31399616
6518g693:31302842
82j33506:31327384
6abeh943:31336334
envsactivate1:31349248
editstats-enabled:31346256
cloudbuttont:31366566
3efgi100_wstrepl:31403338
use-responses-api:31390341
je187915:31401257
cp_cls_c_966_ss:31454199
inlinechat_v2_hd992725:31445440
4je02754:31455664
ge8j1254_inline_auto_hint_haiku:31426887
a5gib710:31434435
8g5ec713_opus_4_6:31464538
7ig2g208:31429686
cp_cls_c_1081:31454833
copilot-nes-oct-trt:31432609
ia-use-proxy-models-svc:31446143
a43f0576c:31442820
e9c30283:31453065
test_treatment2:31471001
h_5b0j5247:31457745
9c05b404_max_request_50:31468594
idci7584:31454084
edit_mode_hidden:31453871
nes-ftch-ctrl:31458523
nes_chat_context_enabled:31451401
showstats:31452402
e3e4d672:31454087
864ei723_large_tool_results_to_disk:31455802
showingstats:31457201
ei9d7968:31462942
b1f5h706:31455228
7ef87755:31455235
nes-extended-on:31455475
regwelcome:31461167
nes-vscode-team-custom:31467776
vscode-team-custom-2:31467843
nes-sp-on:31470943
f860i809:31458078
jc933416:31462667
jdddd261:31461283
89g7j272:31469979
7e884298:31462391
nes-rcnt-edit:31468468
bg_compact_t:31466296
t-some:31466503
dfc2j404:31470440
thinking_effort_h:31471653
i2gc6536:31470023

```

</details>

### PR DESCRIPTION
**Pull request by kycutler**
Fixes #299437

### CODE REVIEW

File: src/vs/workbench/contrib/browserView/electron-browser/tools/openBrowserTool.ts [hunk 1]
```diff
@@ -25,7 +25,7 @@ export const OpenBrowserToolData: IToolData = {
 		properties: {
 			url: {
 				type: 'string',
-				description: 'The URL to open in the browser.'
+				description: 'The full URL to open in the browser.'
```
Comment (jruales) [inline src/vs/workbench/contrib/browserView/electron-browser/tools/openBrowserTool.ts:28]: should we include an example? Or maybe mention "absolute URL" as opposed to relative?

**Review by amunger — APPROVED** [review]

File: src/vs/workbench/contrib/browserView/electron-browser/tools/openBrowserTool.ts [hunk 2]
```diff
@@ -60,6 +60,9 @@ export class OpenBrowserTool implements IToolImpl {
 		if (!params.url) {
 			return errorResult('The "url" parameter is required.');
 		}
+		if (!URL.parse(params.url)) {
```
Comment (jruales) [inline src/vs/workbench/contrib/browserView/electron-browser/tools/openBrowserTool.ts:63]: should we maybe identify common incorrect URLs and be more specific in the error message? Like "you provided a relative URL". Or just trust that the model will figure it out?

**Review by jruales — APPROVED** [review]
