### PR TITLE
Git - do not add a separate after the last command group

### LINKED ISSUE #153501: SCM commit dropdown has a separator at the bottom
Testing #153366

The line at the bottom is unexpected:

image

### PR DESCRIPTION
**Pull request by lszomoru**
Fix #153501

### CODE REVIEW

File: src/vs/workbench/contrib/scm/browser/scmViewPane.ts [hunk 1]
```diff
@@ -2629,11 +2629,13 @@ export class SCMActionButton implements IDisposable {
...
-			for (const commandGroup of button.secondaryCommands) {
-				for (const command of commandGroup) {
+			for (let index = 0; index < button.secondaryCommands.length; index++) {
+				for (const command of button.secondaryCommands[index]) {
 					actions.push(new Action(command.id, command.title, undefined, true, async () => await executeButtonAction(command.id, ...(command.arguments || []))));
 				}
-				actions.push(new Separator());
+				if (index !== button.secondaryCommands.length - 1) {
+					actions.push(new Separator());
+				}
```
Comment (jrieken) [inline src/vs/workbench/contrib/scm/browser/scmViewPane.ts:2638]: Having encountered similar bugs myself many times and I am on the fence between a fix like here (using the index) and calling `actions.pop()` after the loop is done. Too much choice 🤷

**Review by jrieken — APPROVED** [review]

File: src/vs/workbench/contrib/scm/browser/scmViewPane.ts (hunk 1 above)
Comment (lszomoru) [reply src/vs/workbench/contrib/scm/browser/scmViewPane.ts:2638]: Thanks for the suggestion. Did not think of that. Will consider it.
