### PR TITLE
Fix tasks status incorrect #163393

### LINKED ISSUE #163393: Shell Task Status is not correct
Does this issue occur when all extensions are disabled?: Yes/No
YES

- VS Code Version:  
- Version: 1.72.1
Commit: 129500ee4c8ab7263461ffe327268ba56b9f210d
Date: 2022-10-10T17:23:16.506Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
- OS Version: 
- 
图片

Steps to Reproduce:

1.  make a shell task  to run a shell script file ,  set  pretention as follow:
     "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "new",
                "showReuseMessage": true,
                "clear": false
            }, 
3.  use cmd+shift +B  run this task once, then ,the terminal pannel will display  run result status as  ok 
4. use cmd+shift+b run this task twice , then  ,the terminal pannel will display two termianl window, and the bug is:  the first one and the second one all display the running icon !! when the second task  display run stauts , the first termianl display running icon all the time.

### PR DESCRIPTION
**Pull request by mustard-mh**
Fixes #163393

## How to Test

Open vscode with source with `tasks.json` defined like below, tasks status should be correct after task is done

(Use `cmd+shift+b` to start task)

```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo11",
            "type": "shell",
            "command": "${workspaceFolder}/a.sh",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "new",
                "showReuseMessage": true,
                "clear": false
            },
            "problemMatcher": [],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo11",
            "type": "shell",
            "command": "${workspaceFolder}/a.sh",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "showReuseMessage": true,
                "clear": false
            },
            "problemMatcher": [],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "runOptions": {
                "instanceLimit": 3
            }
        }
    ]
}
```

File `a.sh` can be like
```shell
echo hello
sleep 3
```

### CODE REVIEW

**Comment by mustard-mh** [comment]
@microsoft-github-policy-service agree

**Comment by mustard-mh** [comment]
@microsoft-github-policy-service agree

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 1]
```diff
@@ -982,7 +982,7 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
 			let processStartedSignaled = false;
 			terminal.processReady.then(() => {
 				if (!processStartedSignaled) {
-					this._fireTaskEvent(TaskEvent.create(TaskEventKind.ProcessStarted, task, terminal!.processId!));
+					this._fireTaskEvent(TaskEvent.create(TaskEventKind.ProcessStarted, task, terminal!.instanceId!));
```
Comment (jeanp413) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:985]:
```suggestion
					this._fireTaskEvent(TaskEvent.create(TaskEventKind.ProcessStarted, task, terminal!.instanceId, terminal!.processId!));
```

**Comment by mustard-mh** [comment]
Updated, see diff [here](https://github.com/microsoft/vscode/pull/163952/commits/2d7536376e491c1478adeacf045dc8b1b6ac3ac6), and local integration test passed

**Comment by jeanp413** [comment]
cc @meganrogge

File: src/vs/workbench/contrib/tasks/common/tasks.ts [hunk 2]
```diff
@@ -1153,16 +1153,15 @@ export namespace TaskEvent {
 				group: task.configurationProperties.group,
 				processId: undefined as number | undefined,
 				exitCode: undefined as number | undefined,
-				terminalId: undefined as number | undefined,
+				terminalId: terminalId,
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/common/tasks.ts:1156]:
```suggestion
				terminalId
```

File: src/vs/workbench/contrib/tasks/browser/taskTerminalStatus.ts [hunk 3]
```diff
@@ -130,7 +130,7 @@ export class TaskTerminalStatus extends Disposable {
 		}
 		if (!terminalData.disposeListener) {
 			terminalData.disposeListener = terminalData.terminal.onDisposed(() => {
-				this.terminalMap.delete(event.__task?._id!);
+				this.terminalMap.delete(event.terminalId!);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/taskTerminalStatus.ts:133]: we should check if `event.terminalId` is defined here instead of using `!`

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 4]
```diff
@@ -880,13 +880,13 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
 			let processStartedSignaled = false;
 			terminal.processReady.then(() => {
 				if (!processStartedSignaled) {
-					this._fireTaskEvent(TaskEvent.create(TaskEventKind.ProcessStarted, task, terminal!.processId!));
+					this._fireTaskEvent(TaskEvent.create(TaskEventKind.ProcessStarted, task, terminal!.instanceId!, terminal!.processId!));
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:883]: can remove the `!` after `instanceId`

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 5]
```diff
@@ -933,13 +933,13 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
 					watchingProblemMatcher.done();
 					watchingProblemMatcher.dispose();
 					if (!processStartedSignaled) {
-						this._fireTaskEvent(TaskEvent.create(TaskEventKind.ProcessStarted, task, terminal!.processId!));
+						this._fireTaskEvent(TaskEvent.create(TaskEventKind.ProcessStarted, task, terminal!.instanceId!, terminal!.processId!));
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:936]: same I think `!` after `instanceId` can be removed

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 6]
```diff
@@ -933,13 +933,13 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
...
 						processStartedSignaled = true;
 					}
-					this._fireTaskEvent(TaskEvent.create(TaskEventKind.ProcessEnded, task, exitCode ?? undefined));
+					this._fireTaskEvent(TaskEvent.create(TaskEventKind.ProcessEnded, task, terminal!.instanceId!, exitCode ?? undefined));
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:939]: here too

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 7]
```diff
@@ -933,13 +933,13 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
...
 
 					for (let i = 0; i < eventCounter; i++) {
-						this._fireTaskEvent(TaskEvent.create(TaskEventKind.Inactive, task));
+						this._fireTaskEvent(TaskEvent.create(TaskEventKind.Inactive, task, terminal!.instanceId!));
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:942]: and here

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 8]
```diff
@@ -975,7 +975,7 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
 			let processStartedSignaled = false;
 			terminal.processReady.then(() => {
 				if (!processStartedSignaled) {
-					this._fireTaskEvent(TaskEvent.create(TaskEventKind.ProcessStarted, task, terminal!.processId!));
+					this._fireTaskEvent(TaskEvent.create(TaskEventKind.ProcessStarted, task, terminal!.instanceId!, terminal!.processId!));
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:978]: here

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 9]
```diff
@@ -1031,16 +1031,16 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
 						startStopProblemMatcher.dispose();
 					}, 100);
 					if (!processStartedSignaled && terminal) {
-						this._fireTaskEvent(TaskEvent.create(TaskEventKind.ProcessStarted, task, terminal.processId!));
+						this._fireTaskEvent(TaskEvent.create(TaskEventKind.ProcessStarted, task, terminal.instanceId!, terminal.processId!));
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1034]: here

**Review by meganrogge — APPROVED** [review]
Thanks for working on this 👍🏼

**Review by alexr00 — APPROVED** [review]
