### PR TITLE
Fix OOM crash on arm related to tree sitter powershell grammar

### LINKED ISSUE #273177: VS Code crashes when chat suggests a powershell command
Image

### PR DESCRIPTION
**Pull request by hediet**
Fixes https://github.com/microsoft/vscode/issues/273177 by making sure the powershell tree-sitter wasm is not loaded anymore.

### CODE REVIEW

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/treeSitterCommandParser.ts [hunk 1]
```diff
@@ -24,26 +24,32 @@ export class TreeSitterCommandParser {
...
-		parser.setLanguage(language);
+		const disableSubCommandExtraction = true; // see https://github.com/microsoft/vscode/issues/273177
 
-		const tree = parser.parse(commandLine);
-		if (!tree) {
-			throw new BugIndicatingError('Failed to parse tree');
-		}
+		if (disableSubCommandExtraction) {
+			throw new Error('not supported');
+		} else {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/treeSitterCommandParser.ts]: Removing the else will save changing all the following lines

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/test/electron-browser/commandSimplifier.test.ts [hunk 2]
```diff
@@ -23,7 +23,7 @@ import { FileService } from '../../../../../../platform/files/common/fileService
 import { Schemas } from '../../../../../../base/common/network.js';
 import { TreeSitterLibraryService } from '../../../../../services/treeSitter/browser/treeSitterLibraryService.js';
 
-suite('command re-writing', () => {
+suite.skip('command re-writing', () => {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/test/electron-browser/commandSimplifier.test.ts]: If this is arm only, can you check that and keep the suite? Tests are important and I can't verify doing that myself as I don't have the hardware.

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/treeSitterCommandParser.ts [hunk 3]
```diff
@@ -24,26 +24,32 @@ export class TreeSitterCommandParser {
 	}
 
 	async extractSubCommands(languageId: TreeSitterCommandParserLanguage, commandLine: string): Promise<string[]> {
-		const parser = await this._parser;
-		const language = await waitForState(derived(reader => {
-			return this._treeSitterLibraryService.getLanguage(languageId, true, reader);
-		}));
-		parser.setLanguage(language);
+		const disableSubCommandExtraction = true; // see https://github.com/microsoft/vscode/issues/273177
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/treeSitterCommandParser.ts]: Don't you need this?

```
if (os.arch() === 'arm')
```

Disabling this for everything will literally break terminal auto approve completely.

**Review by Tyriar — DISMISSED** [review]

**Review by benvillalobos — APPROVED** [review]
