### PR TITLE
Skip collapsed state check for nested children when dropping files in explorer

### LINKED ISSUE #156746: explorer drag&drop file throws error with fileNesting feature
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.2
- OS Version: macOS 12.0.1 (21A559)
```
Version: 1.69.2 (Universal)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:57.074Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.1.0
```

Steps to Reproduce:

1. enable file nesting config, for example this nests all `xxx.*.ts` inside `xxx.ts`
```json
{
  "explorer.fileNesting.enabled": true,
  "explorer.fileNesting.expand": false,
  "explorer.fileNesting.patterns": {
    "*.ts": "$(capture).*.ts",
  },
}
```
2. drag and drop a collapsed file with nested children to another folder, an error will be thrown
image

Error stack
```
Error
at WorkbenchCompressibleAsyncDataTree.getDataNode (vs/base/browser/ui/tree/asyncDataTree.js:507:27)
at WorkbenchCompressibleAsyncDataTree.isCollapsed (vs/base/browser/ui/tree/asyncDataTree.js:431:47)
at ExplorerView.isItemCollapsed (vs/workbench/contrib/files/browser/views/explorerView.js:206:30)
at FileDragAndDrop.isCollapsed (vs/workbench/contrib/files/browser/views/explorerView.js:279:112)
at FileDragAndDrop.handleExplorerDrop (vs/workbench/contrib/files/browser/views/explorerViewer.js:949:26)
at FileDragAndDrop.drop (vs/workbench/contrib/files/browser/views/explorerViewer.js:938:32)
at AsyncDataTreeNodeListDragAndDrop.drop (vs/base/browser/ui/tree/asyncDataTree.js:140:22)
at TreeNodeListDragAndDrop.drop (vs/base/browser/ui/tree/abstractTree.js:90:22)
at ListViewDragAndDrop.drop (vs/base/browser/ui/list/listWidget.js:916:22)
at ListView.onDrop (vs/base/browser/ui/list/listView.js:848:22)
```

I have searched and found a related issue collected from telemetry https://github.com/microsoft/vscode/issues/154744, but that has a different call stack and is caused by different action, this one should be a new issue

### PR DESCRIPTION
**Pull request by Semesse**
fixes #156746

The error is caused by calling `this.isCollapsed(item)` where `item` is a nested child which does not have a corresponding data node but pushed to `distinctItems` during the loop

### CODE REVIEW

**Review by lramos15 — DISMISSED** [review]
Thanks for the quick fix!

File: src/vs/workbench/contrib/files/browser/views/explorerViewer.ts [hunk 1]
```diff
@@ -1176,20 +1176,22 @@ export class FileDragAndDrop implements ITreeDragAndDrop<ExplorerItem> {
...
-			if (this.isCollapsed(item)) {
+		for (const [item, collapsed] of distinctItems) {
+			if (collapsed) {
 				const nestedChildren = item.nestedChildren;
 				if (nestedChildren) {
 					for (const child of nestedChildren) {
-						distinctItems.add(child);
+						// if parent is collapsed, then the nested children is considered collapsed to operate as a group
+						// and skip collapsed state check since they're not in the tree
+						distinctItems.set(child, collapsed || this.isCollapsed(child));
```
Comment (rzhao271) [inline src/vs/workbench/contrib/files/browser/views/explorerViewer.ts:1188]: Since this is inside of the `if (collapsed)`, can `collapsed || this.isCollapsed(child)` be simplified to `true`?

**Review by Tyriar — DISMISSED** [review]

File: src/vs/workbench/contrib/files/browser/views/explorerViewer.ts (hunk 1 above)
Comment (Semesse) [reply src/vs/workbench/contrib/files/browser/views/explorerViewer.ts]: You are right :)
I have amended the commit

**Review by lramos15 — APPROVED** [review]

**Review by rzhao271 — APPROVED** [review]
