### PR TITLE
debug: fix error on malformed paths

### LINKED ISSUE #174054: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
```javascript
Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
at I in src/vs/base/common/uri.ts:40:11
at _validateUri in src/vs/base/common/uri.ts:175:4
at new g in src/vs/base/common/uri.ts:419:1
at u.from in src/vs/base/common/uri.ts:331:18
at S in src/vs/workbench/contrib/debug/common/debugSource.ts:133:14
at getUriFromSource in src/vs/workbench/contrib/debug/common/debugSource.ts:52:14
at N.getSource in src/vs/workbench/contrib/debug/browser/debugSession.ts:1271:16
at Object.factory in src/vs/workbench/contrib/debug/browser/debugSession.ts:1123:19
at A.h in src/vs/base/common/async.ts:635:33
at A.j in src/vs/base/common/async.ts:646:9
at <anonymous> in src/vs/base/common/async.ts:637:51
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=e2816fe719a4026ffa1ee0189dc89bdfdbafb164&bH=0cbdc69b-8eef-e2b1-42a2-5a263833a0e2)

### PR DESCRIPTION
**Pull request by connor4312**
Fixes #174054

### CODE REVIEW

**Review by TylerLeonhardt — APPROVED** [review]

File: src/vs/workbench/contrib/debug/common/debugSource.ts [hunk 1]
```diff
@@ -134,7 +134,7 @@ export function getUriFromSource(raw: DebugProtocol.Source, path: string | undef
 		if (typeof raw.sourceReference === 'number' && raw.sourceReference > 0) {
 			return URI.from({
 				scheme: DEBUG_SCHEME,
-				path,
+				path: path?.replace(/^\/+/g, '/'), // #174054
```
Comment (roblourens) [inline src/vs/workbench/contrib/debug/common/debugSource.ts:137]: Do you think there's a legit reason the DA would send a path formed like this? To me this feels like trying to hide a problem

Comment (connor4312) [reply src/vs/workbench/contrib/debug/common/debugSource.ts:137]: UNC paths, I would wager

in DAP however we don't specify anything about the path, so as a client VS Code should accept any string. (There's probably more cases we don't handle come to think of it)
