### PR TITLE
Switch Remote button not working after hiding

### LINKED ISSUE #194569: Remote explorer - Switch Remote button not working
Type: <b>Bug</b>

For some reason I decided that hiding the Swich Remote button was a good idea.
To repeat this:
1.- Go to Remote Explorer section
2.- Hide the "Swich Remote" button
3.- Now, ¿how to show again?
4.- Go to more options and select "Swich Remote", vscode display an interesting error

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22623
Modes:

image
image

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #194569
Part of #194603

### CODE REVIEW

File: src/vs/workbench/contrib/remote/browser/explorerViewItems.ts [hunk 1]
```diff
@@ -4,45 +4,56 @@
...
-		super(null, action, optionsItems, 0, contextViewService, defaultSelectBoxStyles, { ariaLabel: nls.localize('remotes', 'Switch Remote') });
+		super();
+		this.selectedRemoteContext = SELECTED_REMOTE_IN_EXPLORER.bindTo(contextKeyService);
+
+		this.switchRemoteMenu = new MenuId('workbench.remote.menu.switchRemoteMenu');
+		this._register(MenuRegistry.appendMenuItem(MenuId.ViewContainerTitle, {
+			submenu: this.switchRemoteMenu,
+			title: nls.localize('switchRemote.label', "Switch Remote"),
+			group: 'navigation',
+			when: ContextKeyExpr.equals('activeViewlet', VIEWLET_ID),
```
Comment (sandy081) [inline src/vs/workbench/contrib/remote/browser/explorerViewItems.ts:48]:
```suggestion
			when: ContextKeyExpr.equals('viewContainer', VIEWLET_ID),
```

This should be `viewContainer` otherwise this action will be added to the view containers in panel and auxilary bar when the remote explorer is active.

**Review by sandy081 — CHANGES_REQUESTED** [review]

**Comment by sandy081** [comment]
@alexr00 Looks like the new changes are not considering the remote views contributed by an extension when it is installed. In the below screenshot, I just installed dev containers extensions and the dropdown is not updated

image

**Review by alexr00 — COMMENTED** [review]
@sandy081, thank you for the help! This is now ready to review again.

**Comment by sandy081** [comment]
LGTM. Thanks for the changes 👏

**Review by sandy081 — APPROVED** [review]
