### PR TITLE
Opt debug console filter box into nice overflow behavior

### LINKED ISSUE #140540: Narrow Debug Console search bar hides other tabs
Issue Type: <b>Bug</b>

1. Move the integrated console viewlets to a vertical layout
2. Make the viewlet narrow

When wide enough:
image

Once narrowed:
image

Expected result: Debug Console search bar shrinks/hides itself in order to show other tabs first (like in the first screenshot). The 3 dots "works", but is, at least in my opinion, more annoying than not being able to search in the Debug Console when the viewlet is narrow.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.75GB free)|
|Process Argv|--crash-reporter-id a67afd80-6294-4ad2-b3ee-2184c6ffa8b8|
|Screen Reader|no|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by roblourens**
Also fix an issue with the body height calculation when the filter box is in the body
Fix #140540

### CODE REVIEW

**Review by Tyriar — APPROVED** [review]

File: src/vs/workbench/browser/parts/views/viewPane.ts [hunk 1]
```diff
@@ -689,9 +689,11 @@ export abstract class FilterViewPane extends ViewPane {
 			this.updateActions();
 			if (!shouldShowFilterInHeader) {
 				append(this.filterContainer!, this.filterWidget.element);
-				height = height - 44;
 			}
 		}
+		if (!shouldShowFilterInHeader) {
+			height = height - 44;
```
Comment (roblourens) [inline src/vs/workbench/browser/parts/views/viewPane.ts:695]: cc @sandy081
