### PR TITLE
Fix disable privileged ports for OSX

### LINKED ISSUE #160266: Disable Privileged ports for OSX
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.71.0 (Universal)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:38.437Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

Steps to Reproduce:

1. Start vscode as a non-root user
2. Use a remote extension like codespaces
3. Have a setup that forwards a port below 1024 ie port 80
4. After the connection the port is forward to a random number

This is annoying if you are working on a server and want to use a local domain ie `myProject.localhost` which requires the mapping to port 80. OSX does not enforce root for binding to ports below 1024 so I think vscode should also not treat them as privileged. 

I wanted to submit a pr for this, but it is hard to test codespaces/remote container dev with vscode OSS. 
My first impression is that I would only need to change the definition of a privileged port here:

https://github.com/microsoft/vscode/blob/main/src/vs/platform/tunnel/common/tunnel.ts#L158-L164

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes https://github.com/microsoft/vscode/issues/160266

Requires to update setting`"remote.localPortHost": "allInterfaces"` in macos to [properly work](https://news.ycombinator.com/item?id=18302380)

### CODE REVIEW

**Review by mcbridenMoey — DISMISSED** [review]

File: src/vs/workbench/services/tunnel/electron-sandbox/tunnelService.ts [hunk 1]
```diff
@@ -73,8 +75,13 @@ export class TunnelService extends AbstractTunnelService {
 		});
 	}
 
+	private get defaultTunnelHost(): string {
```
Comment (alexr00) [inline src/vs/workbench/services/tunnel/electron-sandbox/tunnelService.ts:78]: This is now duplicated from `BaseTunnelService`. We should move it into a shared location like `AbstractTunnelService`.

File: src/vs/platform/tunnel/node/tunnelService.ts [hunk 2]
```diff
@@ -84,7 +84,9 @@ class NodeRemoteTunnel extends Disposable implements RemoteTunnel {
 
 	public async waitForReady(): Promise<this> {
 		// try to get the same port number as the remote port number...
-		let localPort = await findFreePortFaster(this.suggestedLocalPort ?? this.tunnelRemotePort, 2, 1000);
+		const startPort = this.suggestedLocalPort ?? this.tunnelRemotePort;
+		const hostname = isMacintosh && startPort < 1024 && !isPortPrivileged(startPort, this.defaultTunnelHost, OS, os.release()) ? '0.0.0.0' : '127.0.0.1';
```
Comment (alexr00) [inline src/vs/platform/tunnel/node/tunnelService.ts:88]: We shouldn't default to all interfaces unless the user has explicitly asked us to by using the setting.

**Review by alexr00 — CHANGES_REQUESTED** [review]
Thanks for the PR! Just a few comments.

File: src/vs/workbench/services/tunnel/electron-sandbox/tunnelService.ts (hunk 1 above)
Comment (jeanp413) [reply src/vs/workbench/services/tunnel/electron-sandbox/tunnelService.ts]: done

File: src/vs/platform/tunnel/node/tunnelService.ts (hunk 2 above)
Comment (jeanp413) [reply src/vs/platform/tunnel/node/tunnelService.ts]: done :+1:

File: src/vs/platform/tunnel/node/tunnelService.ts [hunk 3]
```diff
@@ -83,8 +83,10 @@ class NodeRemoteTunnel extends Disposable implements RemoteTunnel {
 	}
 
 	public async waitForReady(): Promise<this> {
+		const startPort = this.suggestedLocalPort ?? this.tunnelRemotePort;
+		const hostname = isMacintosh && startPort < 1024 && isAllInterfaces(this.defaultTunnelHost) && !isPortPrivileged(startPort, this.defaultTunnelHost, OS, os.release()) ? '0.0.0.0' : '127.0.0.1';
```
Comment (alexr00) [inline src/vs/platform/tunnel/node/tunnelService.ts:87]: I might be missing something here, but why wouldn't we just do this?

```ts
const hostname = isAllInterfaces(this.defaultTunnelHost) ? '0.0.0.0' : '127.0.0.1';
```

**Review by alexr00 — COMMENTED** [review]
I'm going to do some testing then I'll approve. Thanks for the changes!

File: src/vs/platform/tunnel/node/tunnelService.ts (hunk 3 above)
Comment (jeanp413) [reply src/vs/platform/tunnel/node/tunnelService.ts:87]: ah yeah that will work too, don't really have a preference I just thought it would be still preferred to just use `127.0.0.1` as before for all other cases as it's only a needed due to macos bug

**Review by alexr00 — APPROVED** [review]
Looks good, thank you!

**Review by rebornix — APPROVED** [review]
