### PR TITLE
fix task leak

### LINKED ISSUE #252515: Leaked disposable
```
"[LEAKED DISPOSABLE] Error: CREATED via:
    at GCBasedDisposableTracker.trackDisposable (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/lifecycle.js:27:23)
    at trackDisposable (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/lifecycle.js:198:24)
    at toDisposable (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/lifecycle.js:276:18)
    at TerminalInstance._event [as onDisposed] (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:885:28)
    at TerminalTaskSystem._createTerminal (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/tasks/browser/terminalTaskSystem.js:1402:18)
    at async TerminalTaskSystem._executeInTerminal (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/tasks/browser/terminalTaskSystem.js:762:33)
    at async Promise.all (index 3)", source: vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/lifecycle.js (23)
[26221:0626/165118.644270:INFO:CONSOLE(23)] "[LEAKED DISPOSABLE] Error: CREATED via:
    at GCBasedDisposableTracker.trackDisposable (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/lifecycle.js:27:23)
    at trackDisposable (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/lifecycle.js:198:24)
    at toDisposable (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/lifecycle.js:276:18)
    at TerminalInstance._event [as onDisposed] (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:885:28)
    at TerminalTaskSystem._createTerminal (vscode-file://vscode-app/Users/bpasero/Development/Micro
```

### PR DESCRIPTION
**Pull request by meganrogge**
fix #252515

### CODE REVIEW

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 1]
```diff
@@ -1538,7 +1538,7 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
 		}
 		const terminalKey = terminal.instanceId.toString();
 		const terminalData = { terminal: terminal, lastTask: taskKey, group };
-		terminal.onDisposed(() => this._deleteTaskAndTerminal(terminal, terminalData));
+		this._register(terminal.onDisposed(() => this._deleteTaskAndTerminal(terminal, terminalData)));
```
Comment (Tyriar) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts]: This listener should be tracked and disposed of after it's been disposed of. I think this would work?

```ts
const onDisposedListener = this.register(terminal.onDisposed(() => {
  this._deleteTaskAndTerminal(terminal, terminalData));
  this.delete(onDisposedListener);
});
```

**Review by Tyriar — DISMISSED** [review]

**Review by Tyriar — APPROVED** [review]
