### PR TITLE
Pass renderer locale to exthost, fixes #85675

### LINKED ISSUE #85675: "Intl.DateTimeFormat().resolvedOptions().locale" returns different values in extension host to VS Code process
I'm using MacBook with its system language set to en-GB. I launched VS Code (from the dock, not the terminal) and if I run:

```ts
Intl.DateTimeFormat().resolvedOptions().locale
```

in the Chrome dev tools console, I see this:

Screenshot 2019-11-27 at 9 23 00 am

However, in an extension's activate function if I do this:

```ts
console.log(Intl.DateTimeFormat().resolvedOptions().locale);
```

Then I see this:

Screenshot 2019-11-27 at 9 23 44 am

I need to get the system language in order to set the `LANG` env variable for spawned processes because CocoaPods crashes if `LANG` is not set to something-UTF-8, and there's no way to set it without a language part so I need to get at the system language.

### PR DESCRIPTION
**Pull request by rzhao271**
This PR fixes #85675.

The PR passes in the main process' locale as a `LANG` environment variable to the extension host so that extensions use the same locale as the renderer. 

Some notes:
- Any processes that an extension spawns will also use that same locale, unless the user specifies a different locale in the spawn options.
- The PR should be merged in February so give more time for testing on Insiders.

### CODE REVIEW

File: src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts [hunk 1]
```diff
@@ -212,6 +212,11 @@ export class LocalProcessExtensionHost implements IExtensionHost {
 
 				this._extensionHostProcess = new ExtensionHostProcess(extensionHostCreationResult.id, this._extensionHostStarter);
 
+				let lang = processEnv['LANG'];
+				if (platform.isMacintosh && lang === undefined) {
+					lang = Intl.DateTimeFormat().resolvedOptions().locale;
```
Comment (bpasero) [inline src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts:217]: I am usually nervous about performance whenever it comes to using `Intl`. Can we test how slow this call is across platforms?

//cc @jrieken

Comment (jrieken) [reply src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts:217]: Yeah, something we should measure. Tho, I am more curious why this is for mac only?

Comment (rzhao271) [reply src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts:217]: On macOS, there's a function that Electron calls that overrides the locale to use the system locale: https://source.chromium.org/chromium/chromium/src/+/main:ui/base/l10n/l10n_util_mac.h;l=109?q=OverrideLocale&sq=&ss=chromium. However, when we spawn the extension host, because it's running as a node process, it doesn't call that function. Therefore, users see a discrepancy between the main process + renderer locales compared to the extension host locale.

I already put up an Electron PR at https://github.com/electron/electron/pull/32527, but decided to close it because it might break other Electron projects, and because the Electron team would prefer running Electron with `RUN_ELECTRON_AS_NODE=1` to behave consistently with node.

Another alternative is to call `app.getLocale()` instead of calling `Intl`. But, in that case, the renderer would have `es-MX` as the locale, whereas the extension host would have `es-419` as the locale, a slight discrepancy: https://source.chromium.org/chromium/chromium/src/+/master:ui/base/l10n/l10n_util.cc;l=417.

Comment (jrieken) [reply src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts:217]: Thanks for the detailed explanation! I believe `Intl` is fine to use but you could measure it in real, like run a few times with the snippet below and see what it reads

```
const t = Date.now();
lang = Intl.DateTimeFormat().resolvedOptions().locale;
console.log(Date.now() - t);
```

Comment (rzhao271) [reply src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts:217]: I consistently get `4` or under.
Screenshot evidence

Comment (bpasero) [reply src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts:217]: From my past experience, `Intl` was only slow the very first time called in a process and then fast. There is probably some caching going on after it was called once.

**Review by jrieken — APPROVED** [review]

**Review by raghavthind2005 — APPROVED** [review]

File: src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts (hunk 1 above)
Comment (rzhao271) [reply src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts:217]: Discussed offline. The perf impact should be fine in this case.
Merging the PR next iteration.

**Review by alexdima — APPROVED** [review]
