### PR TITLE
Avoid using privates via cast

### LINKED ISSUE #169639: debug.RemoveBreakpoint doesn't work in version 1.74.1 VScode
Type: <b>Bug</b>

When I try to delete breakpoint by using vscode module, unfortunately i am not able to delete it, on the other hand it was possible on prevous version of vscode. 
Sample code : 
import * as vscode from "vscode";
...
...

```
private async deleteBreakPoint(id: string) {
         const removebpts: vscode.Breakpoint[] = [];
            for (const b of vscode.debug.breakpoints) {
                if (b.id == id) {
                    removebpts.push(b);
                    vscode.debug.removeBreakpoints(removebpts);
                }
         }
 }
```

As I mentioned above, same code was working as expected in previous version of vscode

VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.54GB free)|
|Process Argv|--crash-reporter-id 526d94d7-378a-4ca7-9c7e-9ae729a59785|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
abend-analyzer|Bro|1.0.1
ccf|Bro|1.0.4
cobol-language-support|Bro|1.1.1
data-editor-for-mainframe|Bro|1.0.0
debugger-for-mainframe|Bro|1.6.1
explorer-for-endevor|Bro|1.3.2
hlasm-language-support|Bro|1.5.0
jcl-language-support|bro|1.0.1
vscode-eslint|dba|2.2.6
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.3
vscode-docker|ms-|1.23.3
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
vscode-extension-for-zowe|Zow|2.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

### PR DESCRIPTION
**Pull request by roblourens**
Fixes #169639

### CODE REVIEW

File: src/vs/workbench/api/common/extHostTypes.ts [hunk 1]
```diff
@@ -2745,7 +2745,7 @@ export class Breakpoint {
 	readonly hitCondition?: string;
 	readonly logMessage?: string;
 
-	protected constructor(enabled?: boolean, condition?: string, hitCondition?: string, logMessage?: string) {
+	protected constructor(enabled?: boolean, condition?: string, hitCondition?: string, logMessage?: string, id?: string) {
```
Comment (roblourens) [inline src/vs/workbench/api/common/extHostTypes.ts:2748]: @jrieken this is an extension API object that is constructed by extensions and also by us. I just want to enable us to construct it with an id internally, but not allow extensions to. Is it ok to add this constructor parameter here and just leave it out of the signature in vscode.d.ts? Even though they could technically still pass an id, it would be misusing the API.

Comment (jrieken) [reply src/vs/workbench/api/common/extHostTypes.ts:2748]: > Even though they could technically still pass an id, it would be misusing the API.

Yeah, there is the API has described by `vscode.d.ts` and there is the API discoverable by debugging and introspection... Ideally, the API contract is true down to the implementation. In this particular case you have a breakpoint class with the full constructor and a sub-type for the API that doesn't have the ctor-arg

Comment (roblourens) [reply src/vs/workbench/api/common/extHostTypes.ts:2748]: I didn't want to use subclasses because I think extensions use `instanceof` to disambiguate breakpoint kinds.

**Review by connor4312 — APPROVED** [review]
