### PR TITLE
fix: debugger is unresponsive to repl evaluation after switching

### LINKED ISSUE #152407: Using debug console picker when not paused leaves console unresponsive
- Start two node launch configs
- Both sessions are running and not paused
- Use the debug console switcher to switch consoles
- Evaluate `1+1`, there is no response

In the console picker, we show parent sessions. The child needs to be focused to get the evaluate requests. When a child is paused, we will focus that one with this code

https://github.com/microsoft/vscode/blob/16c2a3ab3be4cf89c71fcce1ff1c11a06fcb923a/src/vs/workbench/contrib/debug/browser/repl.ts#L890-L896

I think this is the same as https://github.com/microsoft/vscode/issues/112595 except we still need to pick a child when not paused, and it also doesn't work when a deeper child is stopped instead.

https://github.com/microsoft/vscode/issues/138963 is relevant too

Basically when something tries to focus a new wrapper parent session, we should always focus one of its children instead. cc @isidorn

### PR DESCRIPTION
**Pull request by bryanchen-d**
Fixes https://github.com/microsoft/vscode/issues/152407:

## Problem Analysis
The issue occurred when using the debug console picker to switch between consoles. If the selected session was a parent session (wrapper) with child sessions, the console would become unresponsive because it focused the parent session instead of a child that can actually handle evaluation requests.

## Root Cause
The existing logic in both repl.ts and debugCommands.ts only looked for stopped child sessions, but ignored running child sessions. When both parent and children were running (not paused), the system would focus the parent session, which couldn't handle REPL evaluations properly.

## Solution

* Always check if the target session has child sessions
* Prefer stopped child sessions when available (preserves fix for #112595)
* Fallback to the first available child session if no stopped children exist
* Only focus parent if there are no child sessions at all

### CODE REVIEW

File: src/vs/workbench/contrib/debug/browser/debugCommands.ts [hunk 1]
```diff
@@ -711,10 +711,7 @@ CommandsRegistry.registerCommand({
 	handler: async (accessor: ServicesAccessor, session: IDebugSession) => {
 		const debugService = accessor.get(IDebugService);
 		const editorService = accessor.get(IEditorService);
-		const stoppedChildSession = debugService.getModel().getSessions().find(s => s.parentSession === session && s.state === State.Stopped);
-		if (stoppedChildSession && session.state !== State.Stopped) {
-			session = stoppedChildSession;
-		}
+		session = resolveChildSession(session, debugService.getModel().getSessions());
```
Comment (roblourens) [inline src/vs/workbench/contrib/debug/browser/debugCommands.ts:714]: What's the difference between this command and the one in repl.ts?

**Review by roblourens — COMMENTED** [review]
This looks good but I will test it a bit later

File: src/vs/workbench/contrib/debug/browser/debugCommands.ts (hunk 1 above)
Comment (bryanchen-d) [reply src/vs/workbench/contrib/debug/browser/debugCommands.ts:714]: From what I understand, the repl.ts one is responsible for when user executes an expression in the repl pannel, and the command one is for general debugging context - like switching debugging session using the debug toolbar, etc. 
However I couldn't find similar issue for the debugCommand one, it seems better to have it consistent though.

**Review by roblourens — APPROVED** [review]
