### PR TITLE
Turn sortByLabel back on by default

### LINKED ISSUE #256561: Julia Markdown is showing above Markdown, causing annoyance when quickly changing the language to Markdown
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest
- OS Version: Mac

Steps to Reproduce:

1. Hit CMD + Shift + P
2. Type "mark", and "Markdown" should be the first...now it's Julia Markdown and it's _extremely_ annoying.

The raw majority of people use Markdown, not Julia Markdown - this used to be a single set of actions - now it's very frustrating.  Remove Julia Markdown, lower it, or let us select a list of languages to exclude.

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
Fixes https://github.com/microsoft/vscode/issues/256561

### CODE REVIEW

**Review by rzhao271 — APPROVED** [review]

File: src/vs/platform/quickinput/browser/quickInputController.ts [hunk 1]
```diff
@@ -546,7 +546,9 @@ export class QuickInputController extends Disposable {
 			input.ignoreFocusOut = !!options.ignoreFocusLost;
 			input.matchOnDescription = !!options.matchOnDescription;
 			input.matchOnDetail = !!options.matchOnDetail;
-			input.sortByLabel = !!options.sortByLabel;
+			if (options.sortByLabel) {
```
Comment (bpasero) [inline src/vs/platform/quickinput/browser/quickInputController.ts:549]: Shouldn't this be `typeof options.sortByLabel === 'boolean'` so that I can disable sorting by label? Isn't otherwise sorting by label the default?
