### PR TITLE
Use new completion label for imported modules

### LINKED ISSUE #98228: Improve TS auto import label
- VSCode Version: 1.45.1
- OS Version: macOS Mojave 10.14.6 

Steps to Reproduce:

Recently, the autocomplete auto import text has become cropped so short as to be completely useless.  In many cases over the past couple of days, I've had the option to import 2-4 same-named classes/components.  Normally, I can select the correct one based on the additional text 
> Auto import from 'react-native'

Now the package name is cropped to the same text for all options:

> Auto import from 'react...

This makes the auto-import feature completely useless (one of the most important features in an IDE).

See example:
autoimport-broken

1. Create project with React Native + React Navigation
2. Type in 'Header' and cmd+space to open autocomplete
(It may be that additional conditions apply, for example what the other options presented in the list would be.)

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by jrieken**
This PR fixes #98228

### CODE REVIEW

File: extensions/typescript-language-features/src/languageFeatures/completions.ts [hunk 1]
```diff
@@ -62,6 +62,13 @@ class MyCompletionItem extends vscode.CompletionItem {
 			// De-prioritze auto-imports
 			// https://github.com/microsoft/vscode/issues/40311
 			this.sortText = '\uffff' + tsEntry.sortText;
+
+			// Render "fancy" when source is a workspace path
+			const qualifierCandidate = vscode.workspace.asRelativePath(tsEntry.source);
+			if (qualifierCandidate !== tsEntry.source) {
```
Comment (jrieken) [inline extensions/typescript-language-features/src/languageFeatures/completions.ts:68]: This is the safe way and prevents `ThisProperty/`-path

**Review by mjbvz — APPROVED** [review]
Let's try this out in insiders
