### PR TITLE
only adjust top when resizing if widget is rendered above

### LINKED ISSUE #239030: Terminal Suggest Widget is cutoff when invoked from a maximized terminal
Testing #238901

Repro Steps:
1. Close all other panels in vscode
2. Expand the terminal to be the only visible panel inside vscode and invoke the suggest widget
🐛
 Image

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #239030

This was caused by https://github.com/microsoft/vscode/pull/238723

https://github.com/user-attachments/assets/c6804000-3fd7-499b-8b08-5daed3962b7a

### CODE REVIEW

File: src/vs/workbench/services/suggest/browser/simpleSuggestWidget.ts [hunk 1]
```diff
@@ -749,7 +749,7 @@ export class SimpleSuggestWidget<TModel extends SimpleCompletionModel<TItem>, TI
 
 		this._listElement.style.width = `${width}px`;
 		this.element.layout(height, width);
-		if (this._cursorPosition) {
+		if (this._cursorPosition && this._preference === WidgetPositionPreference.Above) {
 			this.element.domNode.style.top = `${this._cursorPosition.top - height}px`;
 		}
```
Comment (Tyriar) [inline src/vs/workbench/services/suggest/browser/simpleSuggestWidget.ts:754]: Do we need to clean top otherwise?

**Review by Tyriar — APPROVED** [review]

File: src/vs/workbench/services/suggest/browser/simpleSuggestWidget.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/services/suggest/browser/simpleSuggestWidget.ts:754]: It doesn't seem like it.
