### PR TITLE
Fix onDidChangeTextEditorSelection firing when the editor is resized

### LINKED ISSUE #32092: Resizing can reset markdown preview scroll location
**Repo**
1. Open markdown preview for long doc
1. Scroll partway down page
1. Resize the preview window

**Bug**
Scroll location reset

### PR DESCRIPTION
**Pull request by mjbvz**
**Bug**
`onDidChangeTextEditorSelection` is being fired when the editor window is resized. This does not seem correct since the selection has not actually changed

**Fix**
Make sure we do not refire this event if the selection as not changed

Fixes #32092

### CODE REVIEW

File: src/vs/workbench/api/electron-browser/mainThreadEditor.ts [hunk 1]
```diff
@@ -121,7 +121,11 @@ export class MainThreadTextEditor {
 			}));
 
 			let forwardSelection = (event?: ICursorSelectionChangedEvent) => {
-				this._lastSelection = this._codeEditor.getSelections();
+				const newSelections = this._codeEditor.getSelections();
+				if (Selection.selectionsArrEqual(this._lastSelection, newSelections)) {
+					return;
+				}
+				this._lastSelection = newSelections;
```
Comment (jrieken) [inline src/vs/workbench/api/electron-browser/mainThreadEditor.ts]: Look valid but also like the wrong place. Shouldn't we make sure that the editor widget isn't firing the event on resize and help all consumer of this event?

Comment (rebornix) [inline src/vs/workbench/api/electron-browser/mainThreadEditor.ts]: @mjbvz FYI https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/controller/cursor.ts#L372 .

**Comment by mjbvz** [comment]
I've update the PR to handle this at a lower level. I believe we only want to fire `CursorStateChangedEvent` when the model state has changed, not the view state
