### PR TITLE
if a command was replayed, don't evaluate quick fixes

### LINKED ISSUE #167573: Terminal quick fix provider is called many times when the window reloads
Testing #166762

- Use the example git provider
- Have a terminal with a bunch of misspelled git commands
- Reload the window
- The provider is called for all the stuff in the reconnected terminal

I think there isn't any way to access the quick fixes for old commands anyway, right? So it seems like we shouldn't do this, especially during window startup if it may be expensive

### PR DESCRIPTION
**Pull request by meganrogge**
fix #167573

### CODE REVIEW

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 1]
```diff
@@ -618,7 +618,8 @@ export class CommandDetectionCapability implements ICommandDetectionCapability {
 				hasOutput: () => !executedMarker?.isDisposed && !endMarker?.isDisposed && !!(executedMarker && endMarker && executedMarker.line < endMarker.line),
 				getOutput: () => getOutputForCommand(executedMarker, endMarker, buffer),
 				getOutputMatch: (outputMatcher: ITerminalOutputMatcher) => getOutputMatchForCommand(executedMarker, endMarker, buffer, this._terminal.cols, outputMatcher),
-				markProperties: e.markProperties
+				markProperties: e.markProperties,
+				replayed: true
```
Comment (meganrogge) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:622]:
```suggestion
				wasReplayed: true
```

**Review by Tyriar — APPROVED** [review]
