### PR TITLE
Fixes #198566: ellipsize left-cut search preview

### LINKED ISSUE #198566: Front-trimmed search result preview should be ellipsized
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.2
- OS Version: macOS 12.6.5

Steps to Reproduce:

1. make a file with a long line of code, e.g.
   ```
   // Test using the latest Insiders build to see if your issue has already been fixed: https://code.visualstudio.com/insiders/
   ```
2. search for something near the end of that line of code, e.g. _"fixed"_
3. observe that search results preview cuts the beginning of the line, e.g. showing only _"your issue has already been fixed: https://code.visualstudio.com/insiders/"_ 
4. make the search pane narrower so it starts ellipsizing the end of the preview, e.g. showing only _"your issue has already been fixed: https://code…"_
6. observe that if you hover over the search result preview, the hover title shows the search result shortened at the start but not at the end where it's ellipsized

This screenshot shows the current behaviour, implying the last search result is on a line starting with `12`.

Screen Shot 2023-11-17 at 21 25 52

The cutting at the start can make the preview confusing in circumstances where the first parts of the code line affect the meaning of the matched part (e.g. where it's in a string or in a comment rather than in code). It's confusing because there is no indication that the line is cut at the start.

This can be solved by adding an ellipsis … at the start of the cut preview, and by showing the whole line in the hover title.

This screenshot shows what it should look like:

Screen Shot 2023-11-17 at 21 23 36

PR coming in a few moments.

### PR DESCRIPTION
**Pull request by jacekkopecky**
This fixes #198566 

The second screenshot in the issue is done with this PR in place.

Comments:

* In `strings.ts`, perhaps `lcut()` should have the prefix default to '…' – it seems that the search preview generation is the only user of this function, and it would be consistent with `truncate()`.
* In `searchModel.ts`, we don't need to do `trimStart()` on `before` because `lcut()` already does that (and already did it before this PR, too).

### CODE REVIEW

**Review by andreamah — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/search/browser/searchModel.ts [hunk 1]
```diff
@@ -90,13 +90,12 @@ export class Match {
...
-	preview(): { before: string; inside: string; after: string } {
-		let before = this._oneLinePreviewText.substring(0, this._rangeInPreviewText.startColumn - 1),
-			inside = this.getMatchString(),
-			after = this._oneLinePreviewText.substring(this._rangeInPreviewText.endColumn - 1);
+	preview(): { before: string; fullBefore: string; inside: string; after: string } {
+		const fullBefore = this._oneLinePreviewText.substring(0, this._rangeInPreviewText.startColumn - 1),
+			before = lcut(fullBefore, 26, '…');
 
-		before = lcut(before, 26);
-		before = before.trimStart();
```
Comment (andreamah) [inline src/vs/workbench/contrib/search/browser/searchModel.ts:99]: We still need `trimStart()` for cases where the string's length is less than 26.

Comment (jacekkopecky) [reply src/vs/workbench/contrib/search/browser/searchModel.ts:99]: @andreamah yes, quite right, I missed that. 

However, looking at this, I've improved my understanding of `lcut()` - it seems that `n` is not a maximum but a target, given a string that's longer than `n`:

  - with whitespace characters before, it can return less than `n` characters,
  - but given non-whitespace characters, it can return more. The original tests show that with `assert.strictEqual(strings.lcut('foo bar', 5), 'foo bar');`
 
I'm adding new tests that show when `lcut()` can return more than `n` characters, which is behaviour not affected by my PR. 

Therefore, it feels that `lcut()` could also trim the start of a string that's already shorter. I've implemented your comment that way.

File: src/vs/workbench/contrib/search/browser/searchModel.ts [hunk 2]
```diff
@@ -105,6 +104,7 @@ export class Match {
 
 		return {
 			before,
+			fullBefore,
 			inside,
 			after,
 		};
```
[the remark this answers is not in the document]
Comment (jacekkopecky) [reply src/vs/workbench/contrib/search/browser/searchModel.ts:110]: @andreamah `before` is truncated at the beginning for the search results view so the match has a chance of being visible. The search results view also truncates the end automatically with CSS ellipsis. The hover title is expected to provide stuff that has been cut. That's why we need `fullBefore`. I'm sure it could be named better, though, your guidance will be appreciated.

The size of `fullBefore` may want to be constrained, but here it becomes interesting, or in the words of a relevant comment in existing code, fishy:

* The `before`, `inside` and `after` elements are constrained in `searchModel.ts` to 250 chars (`MAX_PREVIEW_CHARS`). Perhaps it would make sense to constrain `fullBefore` to the same 250, cutting from the start, of course.
* The code in `searchResultsView.ts` constrains the hover title to 999 characters. 
* Search results seem to be constrained in length already in the constructor of `TextSearchMatch` (`src/vs/workbench/services/search/common/search.ts`, around line 311 where it performs "elision"). That code sees itself as "fishy", but seems to remove the need for us to shorten `fullBefore` ourselves.

There seems to be an inordinate amount of shortening going on; bug #198566 complains that it's being overdone. I'm trying to make the search results more useful when the match is beyond 26 characters into a normal-length line.

What do you think, do we need to shorten `fullBefore`?

File: src/vs/workbench/contrib/search/browser/searchModel.ts (hunk 1 above)
Comment (andreamah) [reply src/vs/workbench/contrib/search/browser/searchModel.ts:99]: I still see a case where an ellipsis is present where it shouldn't be. See below:
image


I'm assuming that the `...` represents the leading whitespace, which is inconsistent with other cases where we trim whitespace and don't have a `...`.

File: src/vs/workbench/contrib/search/browser/searchModel.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (andreamah) [reply src/vs/workbench/contrib/search/browser/searchModel.ts:110]: That sounds fine. I think that we can rely on the elision to trim the before enough. Thanks for looking into this!

File: src/vs/workbench/contrib/search/browser/searchModel.ts (hunk 1 above)
Comment (jacekkopecky) [reply src/vs/workbench/contrib/search/browser/searchModel.ts:99]: Thank you again, yes, this wasn't handled well. I've committed a fix. The code feels cleaner now, too.

**Review by andreamah — APPROVED** [review]
LGTM! Thanks so much for contributing this! 

Thinking about this change, I do wonder if people will disagree with it since it takes up space in the search preview that would otherwise not be present. However, we can discuss this more if it actually comes up. For now, we can try out this change and see what the reception is from it. 🙂

File: src/vs/workbench/contrib/search/browser/searchModel.ts [hunk 3]
```diff
@@ -90,13 +90,12 @@ export class Match {
 	}
 
 	@memoize
-	preview(): { before: string; inside: string; after: string } {
-		let before = this._oneLinePreviewText.substring(0, this._rangeInPreviewText.startColumn - 1),
-			inside = this.getMatchString(),
-			after = this._oneLinePreviewText.substring(this._rangeInPreviewText.endColumn - 1);
+	preview(): { before: string; fullBefore: string; inside: string; after: string } {
+		const fullBefore = this._oneLinePreviewText.substring(0, this._rangeInPreviewText.startColumn - 1),
+			before = lcut(fullBefore, 26, '…');
```
Comment (TylerLeonhardt) [inline src/vs/workbench/contrib/search/browser/searchModel.ts:95]: I won't block on this... but I wonder why this is done here and not in CSS using `text-overflow`.

**Review by TylerLeonhardt — APPROVED** [review]

File: src/vs/workbench/contrib/search/browser/searchModel.ts (hunk 3 above)
Comment (andreamah) [reply src/vs/workbench/contrib/search/browser/searchModel.ts:95]: As a short answer, the reason it's not like that is because it was easier to modify the existing code to add an ellipsis.
Taking a quick skim of the spec for `text-overflow`, it seems that it would be based on an offset based on `px` whereas we  seem to want to measure the offset by character. I might consider changing it to use `text-overflow` in the future, but it's probably not in the scope of this particular PR.

Comment (jacekkopecky) [reply src/vs/workbench/contrib/search/browser/searchModel.ts:95]: `text-overflow` is also for the end of the string; we could abuse RTL text direction to cut from the start but then the ellipsis wouldn't reliably start at the start of the line.
