### PR TITLE
#27498 restore extension editor webview scroll positions

### LINKED ISSUE #27498: Extension editor: scroll position is not restored.
Testing: #27350 

- VSCode Version: 1.13 insider
- OS Version: Linux Fedora

Steps to Reproduce:

1. open extension editor
1. scroll the content
1. switch to another editor in the same group
1. switch back to extension editor

Observe: scroll position is not restored

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This <strike>draft</strike> PR tries to fix #27498.

Until now if an extension's README is being viewed and you scroll part way through it, then switch to another editor (e.g. to change settings), upon return to the extension editor the README gets scrolled back to the beginning.

This happens because the content of the extension editor is reloaded each time you switch back to it.

This <strike>draft</strike> PR tracks the vertical scroll position of the two webviews corresponding to the Details and Changelog action bar items and instructs those webviews to scroll to the last-noted position when reloading.

<strike>However it is **not yet working reliably**. For instance it seems to handle the README (aka Details) of my georgejames.vscode-serenji extension correctly, retaining the scroll position as I switch away to the Contributions subtab and back to the Details one. But in similar testing on that extension's Changelog subtab the scroll position is incorrectly restored. And when testing on the msjsdiag.debugger-for-chrome extension neither Details nor Changelog reposition correctly.

I am submitting this PR in the hope someone else can help work out the flaw in my approach.</strike>

UPDATE - it now uses a [1-second timer](https://github.com/microsoft/vscode/pull/85982#issuecomment-562985969) to defer its scroll position adjustment, giving the webview contents time to load completely.

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
@mjbvz in https://github.com/microsoft/vscode/pull/85982/commits/98b02966f4b37843132c58c9895c9e2d35c65613 I have deferred the setInitialScrollPosition call by using a 1000ms setTimeout. That figure was the result of trial and error testing with the Details tab of the Debugger for Chrome extension (scroll to a position, switch to the Contributions tab, then back to Details and check it scrolls to the old position). But this is clearly a hack, and I wish I could work out a 100% reliable way to call this code after the entire iframe contents have loaded and laid out.

**Comment by gjsjohnmurray** [comment]
> 
> 
> @mjbvz in [98b0296](https://github.com/microsoft/vscode/commit/98b02966f4b37843132c58c9895c9e2d35c65613) I have deferred the setInitialScrollPosition call by using a 1000ms setTimeout ...

https://github.com/microsoft/vscode/blob/238617a847b378eeefbd95fc2e9cd585737837c3/src/vs/workbench/contrib/webview/browser/pre/main.js#L485 seems to explain why I need to delay the setInitialScrollPosition. If I'm understanding that code correctly, it will wait a maximum of 200ms before calling onLoad. This would explain why the previously-noted scroll position is sometimes re-established before the entire document has been rendered. The consequence is, the user sees the document scrolled somewhere, but not to the correct place.

**Comment by gjsjohnmurray** [comment]
@mjbvz I have just updated this branch so it's ready to be merged. Any chance of you looking at doing that for this iteration?

File: src/vs/workbench/contrib/webview/browser/pre/main.js [hunk 1]
```diff
@@ -491,8 +491,13 @@
 				const onLoad = (contentDocument, contentWindow) => {
 					if (contentDocument && contentDocument.body) {
 						// Workaround for https://github.com/Microsoft/vscode/issues/12865
-						// check new scrollY and reset if necessary
-						setInitialScrollPosition(contentDocument.body, contentWindow);
+						// check new scrollY and reset if neccessary
+
+						// Delay this in the hope that all of the iframe content will have loaded by the time we set
+						// the desired initial scroll position. But how can we be sure how long is long enough?
+						setTimeout(() => {
```
Comment (mjbvz) [inline src/vs/workbench/contrib/webview/browser/pre/main.js:498]: I don't think we should change this to fix this issue. This code is run for all webviews changing it may break other webviews

Can you tell me more about why was this part of the change is needed?

File: src/vs/workbench/contrib/extensions/browser/extensionEditor.ts [hunk 2]
```diff
@@ -174,6 +174,12 @@ export class ExtensionEditor extends BaseEditor {
 	private extensionChangelog: Cache<string> | null;
 	private extensionManifest: Cache<IExtensionManifest | null> | null;
 
+	// Some action bar items use a webview whose vertical scroll position we track in this array (Readme=0, Changelog=1)
+	private initialScrollProgress: number[] = [];
```
Comment (mjbvz) [inline src/vs/workbench/contrib/extensions/browser/extensionEditor.ts:178]: Use a map here since it providers better type checking

File: src/vs/workbench/contrib/extensions/browser/extensionEditor.ts [hunk 3]
```diff
@@ -582,19 +593,25 @@ export class ExtensionEditor extends BaseEditor {
 		return Promise.resolve(null);
 	}
 
-	private async openMarkdown(cacheResult: CacheResult<string>, noContentCopy: string, template: IExtensionEditorTemplate): Promise<IActiveElement> {
+	private async openMarkdown(cacheResult: CacheResult<string>, noContentCopy: string, template: IExtensionEditorTemplate, webviewIndex: number): Promise<IActiveElement> {
```
Comment (mjbvz) [inline src/vs/workbench/contrib/extensions/browser/extensionEditor.ts:596]: `webviewIndex` should probably be an enum instead so that the code is more legible

**Review by mjbvz — CHANGES_REQUESTED** [review]
Thanks for taking a look! Just have a few comments and questions that I'd like addressed before we merge this in

File: src/vs/workbench/contrib/extensions/browser/extensionEditor.ts (hunk 2 above)
Comment (gjsjohnmurray) [reply src/vs/workbench/contrib/extensions/browser/extensionEditor.ts]: Good suggestion. I have pushed an update containing this.

File: src/vs/workbench/contrib/extensions/browser/extensionEditor.ts (hunk 3 above)
Comment (gjsjohnmurray) [reply src/vs/workbench/contrib/extensions/browser/extensionEditor.ts]: Good point. Done.

File: src/vs/workbench/contrib/webview/browser/pre/main.js (hunk 1 above)
Comment (gjsjohnmurray) [reply src/vs/workbench/contrib/webview/browser/pre/main.js:499]: I take your point about this change having effects beyond this issue, but I found that the onLoad in which I made this change is getting called even before the whole of the iframe content has loaded. I commented on this earlier in this PR, e.g. https://github.com/microsoft/vscode/pull/85982#issuecomment-562985969 and https://github.com/microsoft/vscode/pull/85982#issuecomment-573640635

**Comment by mjbvz** [comment]
Sorry @gjsjohnmurray. This PR kept falling off my radar.

Is this change in a good state now to check in?

**Comment by gjsjohnmurray** [comment]
> Is this change in a good state now to check in?

@mjbvz if you are satisfied with my explanation of the main.js change you queried [here](https://github.com/microsoft/vscode/pull/85982#discussion_r425488177) then yes, please merge it. But as indicated in the comment I added in the code there, it feels a bit of a hack:

```
// Delay this in the hope that all of the iframe content will have loaded by the time we set
// the desired initial scroll position. But how can we be sure how long is long enough?
```

**Comment by gjsjohnmurray** [comment]
@mjbvz do you need any more from me to get this progressed?

File: src/vs/workbench/contrib/webview/browser/pre/main.js (hunk 1 above)
Comment (mjbvz) [reply src/vs/workbench/contrib/webview/browser/pre/main.js:500]: This is by-design. We don't want to block the entire webview from loading if it happens to load a slow resource loaded inside of it

What happens if you remove this part of the change?

Comment (gjsjohnmurray) [reply src/vs/workbench/contrib/webview/browser/pre/main.js:500]: As I recall, without this part of the change the restore of scroll position is unreliable. You get scrolled somewhere, but not necessarily back to exactly the position you were at. If an extension's README.md includes some large screenshots for example. For resetting the former scroll position accurately it seems to me to be necessary for the webview to wait until the resources have loaded. Or at least all of the resources that occupy space above the desired scroll position.

Comment (mjbvz) [reply src/vs/workbench/contrib/webview/browser/pre/main.js:500]: Again, doing this for all webviews seems like it will cause other problems. It's also a poor experience to have the scroll position suddenly jump when all the images are loaded, so maybe there's a better compromise here

Comment (gjsjohnmurray) [reply src/vs/workbench/contrib/webview/browser/pre/main.js:500]: I'm running out of ideas. My understanding of the webviews code is that the mechanism to (optionally) restore the previous scroll position when reviving(?) a webview tries to set it to the same percentage (`initData.initialScrollProgress`) of the entire document contents as the former scroll position was at. Assuming that at the time the old scroll position was noted all the image resources had been fully loaded, then unless the same is true at the time we reinstate the scroll position for the revived document there's a chance we won't put the user back to where they remember being when they switched away.

So I'm going to remove my main.js change, leaving an imperfect fix for the original issue. But the imperfection will probably only show up in extension READMEs that pull in big images.

**Comment by mjbvz** [comment]
Thanks @gjsjohnmurray! (and apologies for the long review process)
