### PR TITLE
Fix traffic light centering on macOS

### LINKED ISSUE #208226: Traffic lights on macOS are not centered
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.0-insider (f7c827a5e0ddbba66425ea54e33430bce8f53c84)
- OS Version: macOS Sonoma 14.4

The traffic light icons in the custom title bar should be [centered vertically](https://github.com/microsoft/vscode/blob/342d7a0c0ceec77ace1a4b50c1da809c64d224a9/src/vs/platform/windows/electron-main/windowImpl.ts#L333-L341), but the padding at the top is larger than at the bottom, especially when the command center is disabled:

Traffic lights

### PR DESCRIPTION
**Pull request by klaussner**
Fixes #208226.

This PR makes two changes to the traffic light centering logic for macOS (see the linked issue for a screenshot of the problem):
- The traffic light icons have a height of `12px`. A margin of `2px` is added at the top and bottom, so the total height for centering is `16px`.
- If the title bar height is odd (i.e., if the command center is enabled), the result of `(options.height - 16) / 2` is also odd. In this case, Electron rounds up the value. To make the offset look better, the value is rounded down instead.

### CODE REVIEW

**Comment by klaussner** [comment]
Here are two screenshots showing the result (with and without command center enabled):

Fix with command center

Fix without command center

File: src/vs/platform/windows/electron-main/windowImpl.ts [hunk 1]
```diff
@@ -377,7 +377,7 @@ export abstract class BaseWindow extends Disposable implements IBaseWindow {
 
 		// macOS: traffic lights
 		else if (isMacintosh && options.height !== undefined) {
-			const verticalOffset = (options.height - 15) / 2; // 15px is the height of the traffic lights
+			const verticalOffset = Math.floor((options.height - 16) / 2); // 16px is the height of the traffic lights
```
Comment (Sapientia-PT) [inline src/vs/platform/windows/electron-main/windowImpl.ts:380]: Set traffic light height as const. Useless comment that could be explained in code

**Comment by klaussner** [comment]
I made another small change to the traffic light position. In most Mac apps, the distance between the traffic lights and the window frame is the same horizontally and vertically. The positioning in this PR is based on an invisible margin around the traffic lights, shown in this image:

Traffic lights

Here are two updated screenshots of the final result (command center enabled on the right, disabled on the left):

Traffic lights

**Comment by klaussner** [comment]
@benibenj Would it be possible to include this in one of the next releases?

**Comment by benibenj** [comment]
I'll try and have a look at it this month.

**Review by benibenj — APPROVED** [review]

**Review by aeschli — APPROVED** [review]

**Review by benibenj — APPROVED** [review]
