### PR TITLE
fix #177488

### LINKED ISSUE #177488: Extension pack for Java recommended to a JS project
Does this issue occur when all extensions are disabled?: Yes/No

# Description 

I keep seeing "Extension pack for Java is recommended for this repository" in JS/TS projects. There must be something wrong. 

(I'm reporting here and not with the extension because of the recent work there was with extension recommendations -- maybe it's an extension issue)

image

# How to reproduce: 

I cloned https://github.com/microsoft/vscode-json-languageservice, opened it in insiders and got this recommendation. 

To try another project, I cloned the react repo (https://github.com/facebook/react) and opened with insiders, again the same problem. 

# Version info

Version: 1.77.0-insider (Universal)
Commit: c97d5812f10c28efbcdb1fd404bc25afae873312
Date: 2023-03-16T05:22:31.950Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

### PR DESCRIPTION
**Pull request by sandy081**
fix #177488

### CODE REVIEW

File: src/vs/platform/extensionManagement/common/extensionTipsService.ts [hunk 1]
```diff
@@ -61,15 +61,9 @@ export class ExtensionTipsService extends Disposable implements IExtensionTipsSe
...
 			}
 			try {
-				let content: string | undefined;
-				const getContent = async () => {
-					if (content === undefined) {
-						content = (await this.fileService.readFile(joinPath(folder, configPath))).value.toString();
-					}
-					return content;
-				};
+				const content = (await this.fileService.readFile(joinPath(folder, configPath))).value.toString();
```
Comment (amunger) [inline src/vs/platform/extensionManagement/common/extensionTipsService.ts:64]: this file read will no longer be short circuited if `value.contentPattern` is falsy

Comment (sandy081) [reply src/vs/platform/extensionManagement/common/extensionTipsService.ts:64]: Yes, this is expected. When `value.contentPattern` is falsy, it is enough for file to exist. When file does not exist, `readFile` throws error.

**Review by amunger — APPROVED** [review]
