### PR TITLE
Fix run active file in terminal on paths with spaces under Windows

### LINKED ISSUE #62350: Run active file does nothing on windows if file path has space in it
Issue Type: <b>Bug</b>

While testing https://github.com/Microsoft/vscode/issues/60768

**steps**
1. On windows
1. Create an html file called `sp ace.html`
1. Open the file
1. From the terminal menu, select `Run Active file`

**bug**
This command executes `"c:\Users\matb\folder\sp ace.html"` in the terminal. For powershell at least, this does nothing.

If the file does not have a space, then we run  `c:\Users\matb\projects\san\nospace.html` which opens a web browser 

VS Code version: Code - Insiders 1.29.0-insider (97ad72a02c351d6cde0fd32b41d9700a43e5964a, 2018-10-31T06:19:46.141Z)
OS version: Windows_NT x64 10.0.18262

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.98GB (1.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details>

### PR DESCRIPTION
**Pull request by nunottlopes**
Fixes [#62350](https://github.com/Microsoft/vscode/issues/62350).

When we run a file on powershell with a path that has a space in it instead of running "c:\Users\matb\folder\sp ace.html" it will now execute & 'c:\Users\matb\folder\sp ace.html'. This way powershell will be able to execute the file as it is pretended.
capture4

### CODE REVIEW

**Review by Tyriar — APPROVED** [review]
Thanks!

File: src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts [hunk 1]
```diff
@@ -688,6 +688,8 @@ export class TerminalInstance implements ITerminalInstance {
 						c(this._escapeNonWindowsPath(stdout.trim()));
 					});
 					return;
+				} else if (hasSpace && (exe.indexOf('powershell') !== -1)) {
```
Comment (TylerLeonhardt) [inline src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: In the latest version of PowerShell, PowerShell Core (xplat, ships outside of Windows), the executable has been renamed to `pwsh` to prevent any conflicts with the PowerShell version that ships in Windows, called Windows PowerShell aka `powershell.exe`.

This fix should also include a check for the latest version of PowerShell as well.

```Javascript
exe.indexOf('powershell') !== -1 || exe.indexOf('pwsh') !== -1
```

Also, I think this fix only works on Windows, but PowerShell Core works on macOS and Linux.

cc @Tyriar I probably should have called out the executable name in the issue you tagged me in. My bad.

Comment (Tyriar) [reply src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: @TylerLeonhardt 👍, you can do a PR for that to get credit for it if you want?
