### PR TITLE
Forces match parent node rendering in order to update match counter badge in searchView

### LINKED ISSUE #69977: When dismissing a search result, the total result count should decrement by 1, or indicate dismissed results count
I do not see a duplicate of my issue:

image

So I'm in the clear.

- VSCode Version: 1.32.0
- OS Version: Windows 10 1809 Stable

Steps to Reproduce:

1. In Visual Studio Code, click on the "Search" sidebar menu item to bring up the huge Search menu. 

image

2. Search for a common word used quite a lot. Like "a", "let", "var", "i", and so forth.
3. When the Search displays the total results count, dismiss a few of them.
4. The total results count should **decrement by 1** per dismissal, or indicate both the **original total results count and the remaining non-dismissed total results count** side by side when dismissing the search results. For example:

image

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes #69977

### CODE REVIEW

File: src/vs/workbench/contrib/search/browser/searchView.ts [hunk 1]
```diff
@@ -452,8 +452,12 @@ export class SearchView extends ViewletPanel {
 					return;
 				}
 
-				const root = element instanceof SearchResult ? null : element;
-				this.tree.setChildren(root, this.createIterator(element, collapseResults));
+				if (element instanceof SearchResult) {
+					this.tree.setChildren(null, this.createIterator(element, collapseResults));
+				} else {
+					this.tree.setChildren(element, this.createIterator(element, collapseResults));
+					this.tree.rerender(element);
```
Comment (roblourens) [inline src/vs/workbench/contrib/search/browser/searchView.ts]: Why does this fix it, shouldn't it rerender already when setChildren is called?

Comment (jeanp413) [reply src/vs/workbench/contrib/search/browser/searchView.ts]: @roblourens from what I understand from [here](https://github.com/Microsoft/vscode/blob/6d444df6669feb905909e636741bd7a770ed570a/src/vs/base/browser/ui/tree/indexTreeModel.ts#L89-L188) to refresh the parent node you have to spliced it from the list as in rerender `this.list.splice(listIndex, 1, [node]);` but the splice function from indexTreeModel just does it for the [children](https://github.com/Microsoft/vscode/blob/6d444df6669feb905909e636741bd7a770ed570a/src/vs/base/browser/ui/tree/indexTreeModel.ts#L161).

Comment (roblourens) [reply src/vs/workbench/contrib/search/browser/searchView.ts]: Oh I see , thanks

**Review by roblourens — APPROVED** [review]
