### PR TITLE
activity: fix activity API is active although there is no any user interactions

### LINKED ISSUE #237386: window activity API is active although there is no any user interactions
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.96.0
Commit: 138f619c86f1199955d53b4166bef66ef252935c
Date: 2024-12-11T02:29:09.626Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0

I'm not sure what's triggering it. It appears that long-running progress operations (around 15 seconds) from some extensions can trigger it. For Gitpod, we don't really care about these since our minimum timeout is 30 minutes—we're only care about actual user interactions, i.e. keyboard/mouse events from DOM.

@connor4312 Would it be possible to add a machine setting to disable any other activity tracking but from DOM? Currently, VS Code can't distinguish between user-triggered and automatic progress events, which causes false positives.

### PR DESCRIPTION
**Pull request by connor4312**
Fixes #237386

### CODE REVIEW

**Comment by joshspicer** [comment]
test comment for tpi please ignore

File: src/vs/workbench/services/progress/browser/progressService.ts [hunk 1]
```diff
@@ -47,7 +47,7 @@ export class ProgressService extends Disposable implements IProgressService {
 		const { location } = options;
 
 		const task = async (progress: IProgress<IProgressStep>) => {
-			const activeLock = this.userActivityService.markActive({ whenHeldFor: 15_000 });
+			const activeLock = this.userActivityService.markActive({ extendOnly: true, whenHeldFor: 15_000 });
```
Comment (joshspicer) [inline src/vs/workbench/services/progress/browser/progressService.ts:50]: test comment please ignore

**Review by rzhao271 — APPROVED** [review]
