### PR TITLE
PromptInputModel: Detect interrupts and show executing in dev mode

### LINKED ISSUE #210752: Terminal suggest does not work properly when completion starts before the original input
Testing #210394

Tested on branch https://github.com/microsoft/vscode/pull/210750

Repro:

1. Enable terminal suggest
2. Start pwsh
3. Type `d`
4. Press ctrl+space
5. Scroll down to bottom and select one of the entries that doesn't start with `d`

image
image

### LINKED ISSUE #210757: PromptInputModel: Prompt can be incorrect after interrupting
Setup: `"terminal.integrated.developer.devMode": true`

1. Open Windows 11/pwsh terminal
2. Type Ge
3. Press ctrl+c, 🐛 the status bar item should show `|` only

image

### LINKED ISSUE #210758: PromptInputModel: Prompt can be incorrect after interrupting (after a window reload)
Related: https://github.com/microsoft/vscode/issues/210757

Setup: `"terminal.integrated.developer.devMode": true`

Repro:

1. Open Windows 11/pwsh terminal
2. Type Ge
3. Press ctrl+c
4. Reload window

image

Type Ge

image

Press ctrl+c

image

🐛 the status bar item should show `|` only

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #210757
Fixes #210758
Fixes #210752

Recording 2024-04-19 at 09 38 19

### CODE REVIEW

File: src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts [hunk 1]
```diff
@@ -72,11 +85,12 @@ export class PromptInputModel extends Disposable implements IPromptInputModel {
 	) {
 		super();
 
-		this._register(this._xterm.onData(e => this._handleInput(e)));
 		this._register(Event.any(
-			this._xterm.onWriteParsed,
 			this._xterm.onCursorMove,
+			this._xterm.onData,
```
Comment (rzhao271) [inline src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts:90]: Since onData has multiple handlers, is there a consistent order in which the events are handled, or does it not matter in this case?

Comment (Tyriar) [reply src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts:90]: It doesn't matter since `_sync` is `throttle(0)`

**Comment by Tyriar** [comment]
Ok should be passing now, ready for another review

**Review by chrmarti — APPROVED** [review]
