### PR TITLE
Send breakpoint init requests in parallel

### LINKED ISSUE #163248: Send all breakpoint requests in parallel
Currently we send all the different types of breakpoint requests one at a time

https://github.com/microsoft/vscode/blob/ae34e8d2df286f8c8882d22db417e6dc4cdb01f5/src/vs/workbench/contrib/debug/browser/debugService.ts#L1041-L1046

This is a lot of back and forth between the client and debug adapter, and can take some time. I want to send all of these requests in parallel. In principle, nothing in the spec prevents this. But the comment above the last line is apparently from a time before the `configurationDone` event, when some DAs were using the setExceptionBreakpoints request to know when this initialization stage was done. That comment is from years ago https://github.com/microsoft/vscode/commit/3f0381cd6c9f8e85e5634317d7ba757a8c80fafd#diff-8fcf91137d71e8866175ec9c092132c5a23e4260523c72d57c0c85c5d9c2eaaeR785 and I think it should be fine today. But still I'd like to ping a handful of folks who work on DAs just to check that nobody has an issue with this.

cc @connor4312 @weinand @gregg-miskelly @DanTup @polinasok @zobo @karthiknadig

### PR DESCRIPTION
**Pull request by roblourens**
Fix #163248

### CODE REVIEW

File: src/vs/workbench/contrib/debug/browser/debugService.ts [hunk 1]
```diff
@@ -1038,12 +1038,24 @@ export class DebugService implements IDebugService {
...
-		await Promise.all(distinct(this.model.getBreakpoints(), bp => bp.uri.toString()).map(bp => this.sendBreakpoints(bp.uri, false, session)));
-		await this.sendFunctionBreakpoints(session);
-		await this.sendDataBreakpoints(session);
-		await this.sendInstructionBreakpoints(session);
-		// send exception breakpoints at the end since some debug adapters rely on the order
-		await this.sendExceptionBreakpoints(session);
+		// If sending breakpoints to one session which we know supports the configurationDone request, can make all requests in parallel
+		if (session?.capabilities.supportsConfigurationDoneRequest) {
+			await Promise.all([
+				...distinct(this.model.getBreakpoints(), bp => bp.uri.toString()).map(bp => this.sendBreakpoints(bp.uri, false, session)),
```
Comment (connor4312) [inline src/vs/workbench/contrib/debug/browser/debugService.ts:1044]: Could store the `Promise<void>[]` for this in a variable to use in both places and avoid duplicating, since it's somewhat complex

**Review by connor4312 — DISMISSED** [review]

**Review by TylerLeonhardt — APPROVED** [review]
