### PR TITLE
fix chat terminal leaks

### LINKED ISSUE #304828: [042/d9f] potential listener LEAK in chatTerminalToolProgressPart.ts
## Error Message
````
[042] potential listener LEAK detected, having 1102 listeners already. MOST frequent listener (372):
```

## Stack Trace

**Primary bucket (`f9a4e690`):**
```
at (anonymous) (src/vs/base/common/event.ts:1061:14)
at (anonymous) (src/vs/base/common/event.ts:1246:33)
at (anonymous) (src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatTerminalToolProgressPart.ts:1082:0)
at (anonymous) (src/vs/platform/instantiation/common/instantiationService.ts:162:17)
at (anonymous) (src/vs/platform/instantiation/common/instantiationService.ts:128:17)
at (anonymous) (src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatTerminalToolProgressPart.ts:356:0)
at (anonymous) (src/vs/platform/instantiation/common/instantiationService.ts:162:17)
at (anonymous) (src/vs/platform/instantiation/common/instantiationService.ts:128:17)
at (anonymous) (src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatToolInvocationPart.ts:190:36)
at (anonymous) (src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatToolInvocationPart.ts:117:37)
```

**Related bucket (`ea8af029`) — same file, different leak path:**
```
[d9f] potential listener LEAK detected, having 2748 listeners already. MOST frequent listener (2574):

at (anonymous) (src/vs/base/common/event.ts:1061:14)
at (anonymous) [as onDidContinueInBackground] (src/vs/base/common/event.ts:1246:33)
at _initializeTerminalActions (src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatTerminalToolProgressPart.ts:596:0)
````

## Details
| Property | Value |
| --- | --- |
| Primary Bucket ID | [`f9a4e690-4f46-5720-8ddc-ad6e4362233e`](https://errors.code.visualstudio.com/bucket/f9a4e690-4f46-5720-8ddc-ad6e4362233e?product=VSCode) |
| Related Bucket ID | [`ea8af029-2149-4b37-513c-8d86d2220d1b`](https://errors.code.visualstudio.com/bucket/ea8af029-2149-4b37-513c-8d86d2220d1b?product=VSCode) |
| Version | 1.112.0 |
| Commit | [`07ff9d61`]((insiders.vscode.dev/redacted) |
| Last Seen | 2026-03-23 |
| Combined Hits | 2.2M |
| Combined Affected Users | 142.5K |
| Platforms | Linux, Mac, Windows |
| Product | VSCode |

## Analysis

Multiple listener LEAK errors originate from `chatTerminalToolProgressPart.ts` in the chat terminal tool progress component. Two distinct leak paths are observed:

1. **Bucket `f9a4e690`** (1.2M hits / 64.9K users): Leak occurs during construction at line 1082 and line 356, triggered via `createToolInvocationSubPart` in `chatToolInvocationPart.ts`.
2. **Bucket `ea8af029`** (1M hits / 77.6K users): Leak occurs in `_initializeTerminalActions` at line 596, triggered via the `onDidContinueInBackground` event listener.

Both are new in 1.112.0 and appear across insiders and stable builds. The trend is **increasing** — this is a significant leak introduced with recent chat terminal tool progress changes.

---
*This issue was automatically created from error telemetry triage*

> Generated by [errors-triage](https://github.com/microsoft/vscode-errors/actions/runs/23552236369) · [◷](https://github.com/search?q=repo%3Amicrosoft%2Fvscode+is%3Aissue+%22gh-aw-workflow-call-id%3A+microsoft%2Fvscode-errors%2Ferrors-triage%22&type=issues)

### PR DESCRIPTION
**Pull request by meganrogge**
fix #304828
fix https://github.com/microsoft/vscode/issues/307401

### CODE REVIEW

**Review by roblourens — DISMISSED** [review]

File: src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatTerminalToolProgressPart.ts [hunk 1]
```diff
@@ -379,6 +379,18 @@ export class ChatTerminalToolProgressPart extends BaseChatToolInvocationSubPart
...
 		this._terminalService.whenConnected.then(() => this._initializeTerminalActions());
+
+		// Listen for continue in background to remove the button (registered once in constructor,
+		// not inside _initializeTerminalActions which may be called multiple times)
+		const terminalToolSessionId = this._terminalData.terminalToolSessionId;
+		if (terminalToolSessionId) {
+			this._register(this._terminalChatService.onDidContinueInBackground(sessionId => {
+				if (sessionId === terminalToolSessionId) {
+					this._terminalData.didContinueInBackground = true;
+					this._removeContinueInBackgroundAction();
```
Comment (roblourens) [inline src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatTerminalToolProgressPart.ts]: I'm wondering why it works by managing actions manually instead of a context key?

Comment (meganrogge) [reply src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatTerminalToolProgressPart.ts]: I did not implement this 😓

Comment (meganrogge) [reply src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatTerminalToolProgressPart.ts]: But good point

Comment (meganrogge) [reply src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatTerminalToolProgressPart.ts]: Fixed

**Review by justschen — APPROVED** [review]
