### PR TITLE
Handle normalized absolute file paths on markdown preview link click 

### LINKED ISSUE #115812: links in Markdown preview no longer work
Issue Type: <b>Bug</b>

with agit repo open, preview a MD doc with a link to another MD doc in the same repo... hovering over the link shows a tooltip with the correct full path of the linked file (file:///c:/workspace/folder/file.md), yet clicking the link does nothing

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (20.14GB free)|
|Process Argv|--crash-reporter-id 06338080-eec2-498d-98e0-cf3111dc1cde|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (94)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-icalendar|af4|1.0.1
vscode-m3u|af4|1.0.0
vscode-caniuse|aga|0.5.0
rtf|ale|2.2.0
vscode-sqlite|ale|0.11.1
swagger-viewer|Arj|3.0.1
vscode-browser-preview|auc|0.6.7
armview|ben|0.4.5
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
disableligatures|Coe|0.0.10
vscode-markdownlint|Dav|0.38.0
jshint|dba|0.11.0
vscode-eslint|dba|2.1.14
rushnav|Dev|0.0.6
githistory|don|0.6.14
xml|Dot|2.5.1
escaping-characters|drp|1.0.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
git-project-manager|fel|1.7.1
scriptcsRunner|fil|0.1.0
vscode-firefox-debug|fir|2.9.1
vscode-npm|fkn|3.3.0
shell-format|fox|7.0.1
matlab|Gim|2.0.0
vscode-pull-request-github|Git|0.23.0
gc-excelviewer|Gra|3.0.41
beautify|Hoo|1.5.0
rest-client|hum|0.24.4
mediawiki|jak|2.1.0
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
gpg|jva|0.1.2
docomment|k--|0.1.20
vscode-liquid-snippets|kil|2.0.1
gnuplot|mam|1.0.5
markdown-shortcuts|mdi|0.12.0
openapi-lint|mer|1.2.0
HTMLHint|mka|0.10.0
azure-pipelines|ms-|1.183.0
vscode-azureappservice|ms-|0.20.0
vscode-azurefunctions|ms-|1.2.0
vscode-azureresourcegroups|ms-|0.2.0
vscode-azurestorage|ms-|0.11.0
vscode-azurevirtualmachines|ms-|0.2.0
vscode-cosmosdb|ms-|0.15.1
csharp|ms-|1.23.9
vscode-dotnet-runtime|ms-|1.0.0
mssql|ms-|1.10.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.0
jupyter|ms-|2020.12.414227025
vscode-ai|ms-|0.6.19
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.5
azurecli|ms-|0.5.0
mono-debug|ms-|0.16.2
powershell|ms-|2020.6.0
vscode-node-azure-pack|ms-|0.1.0
vscode-typescript-tslint-plugin|ms-|1.3.3
azurerm-vscode-tools|msa|0.14.0
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
language-liquid|nei|0.1.1
azdo-wiki-md|ni|0.0.3
vscode-yaml|red|0.14.0
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8
toggle-case|rya|1.0.2
vscode-hexdump|sle|1.8.1
vscode-zipexplorer|sle|0.3.1
addDocComments|ste|0.0.8
code-spell-checker|str|1.10.2
code-spell-checker-greek|str|0.1.6
code-spell-checker-hebrew|str|0.1.5
code-spell-checker-medical-terms|str|1.0.9
code-spell-checker-spanish|str|1.0.7
msbuild-project-tools|tin|0.3.11
shell-launcher|Tyr|0.4.1
vscodeintellicode|Vis|1.2.11
vscode-icons|vsc|11.1.0
highlight-bad-chars|wen|0.0.3
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
t4-support|zbe|0.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

### PR DESCRIPTION
**Pull request by habibkarim**
This PR fixes #115812

### CODE REVIEW

File: extensions/markdown-language-features/src/features/preview.ts [hunk 1]
```diff
@@ -439,6 +439,9 @@ class MarkdownPreview extends Disposable implements WebviewResourceProvider {
 		if (hrefPath[0] !== '/') {
 			// Fix #93691, use this.resource.fsPath instead of this.resource.path
 			hrefPath = path.join(path.dirname(this.resource.fsPath), hrefPath);
+		} else {
+			// Handle any normalized file paths
+			hrefPath = hrefPath.replace('file///', '');
```
Comment (habibkarim) [inline extensions/markdown-language-features/src/features/preview.ts:444]: After investigation, I noticed that this issue was caused inadvertently by https://github.com/microsoft/vscode/pull/114553/files where the links were normalised to display images. This fix handles both absolute links and file:// links

**Review by mjbvz — CHANGES_REQUESTED** [review]

File: extensions/markdown-language-features/src/features/preview.ts (hunk 1 above)
Comment (habibkarim) [reply extensions/markdown-language-features/src/features/preview.ts]: Thanks for the suggestion. I've made the change The latest update now handles `file:/` links as well. I've tested this change both on Windows and Mac for multiple paths.

Windows:
Windows

Mac:
Mac

From what I can see, `file://` paths aren't supported right now. I can't seem to build a version of vscode prior to https://github.com/microsoft/vscode/pull/114553/files so not sure if they were supported before then

**Comment by mjbvz** [comment]
Thanks! Will be in the next insiders build and is scheduled for VS Code 1.54
