### PR TITLE
Set DragData when directory is dragged

### LINKED ISSUE #241007: Markdown support: issue with dragging folder into editor to create a link on Linux edition of VSCode
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.97.2 (latest)
- OS Version: Ubuntu/Windows 10

Steps to Reproduce:

1. Open an `.md` file
2. Drag a folder from the left hand File Explorer and drop it into the editor while holding the SHIFT key down
3. Using the Microsoft Windows version of VSCode this action will result in the creation of a markdown style relative link in the editor **as expected**, e.g.:

```
[text](../../../folder_name)
```

4. Using the `.deb` file installed release of VSCode on Ubuntu Desktop or Linux Mint desktop, the same action results in the absolute path to the folder being pasted into the editor, e.g.:

```
/home/my_user/Documents/gitlab/doc/content/en/some/path/folder_name
```

I feel that the behaviour in the Linux distros is **incorrect and is a bug** and a markdown style link should be created instead.

I do not have any extensions installed in VSCode and all settings are in their default state (I have not changed any).

Note that I can drag an `.md` file or an image type file (`.png`, `.jpg` etc.) from a folder in the left hand explorer and drop it into the editor and on both Linux and Windows a markdown link will be created **as expected** with the relative path to the file - so I know the drag and drop facility is working as designed.

### PR DESCRIPTION
**Pull request by mkhuzaima**
Fixes #241007 

### Bug
[drag-directory-issue.webm](https://github.com/user-attachments/assets/751a97f9-18b7-49a2-835c-c0ef305714e9)

### After Fix
[drag-directory-fix.webm](https://github.com/user-attachments/assets/bd1d5729-54d5-4c5c-bccd-93bb7e68d934)

### CODE REVIEW

**Comment by TedVu** [comment]
Couldn't reproduce on the latest version.

**Comment by mkhuzaima** [comment]
> Couldn't reproduce on the latest version.

Are you using ubuntu ?

**Comment by TedVu** [comment]
I'm using Windows 11, what's the directory structure ? I created a folder and dragged it to an md file, it appeared fine.

**Comment by mkhuzaima** [comment]
@TedVu The issue occurs on Ubuntu but works fine on Windows. When dragging a directory into a Markdown file, it inserts the absolute path instead of the relative path and does not generate a link.

File: src/vs/workbench/browser/dnd.ts [hunk 1]
```diff
@@ -268,7 +268,7 @@ export function fillEditorsDragData(accessor: ServicesAccessor, resourcesOrEdito
 		} else if (URI.isUri(resourceOrEditor)) {
 			const { selection, uri } = extractSelection(resourceOrEditor);
 			editor = { resource: uri, options: selection ? { selection } : undefined };
-		} else if (!resourceOrEditor.isDirectory) {
+		} else {
```
Comment (mjbvz) [inline src/vs/workbench/browser/dnd.ts:271]: A lot of the code below assumes that `resource` will be a file, not a directory

Instead I think this check should happen down where we set the `Mimes.uriList` data. That logic should be updated to also include directories in the url-list

Comment (mkhuzaima) [reply src/vs/workbench/browser/dnd.ts:271]: Sure, will update accordingly. 

Can you describe some scenarios, through which I can test the change?

Comment (mjbvz) [reply src/vs/workbench/browser/dnd.ts:271]: It should work the same as with the PR but using a more correct data-transfer type instead of the `editors` type. That could potentially result in VS Code trying to open a folder as an editor, while `url-list` should work for any type of file or folder

Comment (mkhuzaima) [reply src/vs/workbench/browser/dnd.ts:271]: Got it. 👍
Thank you for your prompt reply.

Comment (mkhuzaima) [reply src/vs/workbench/browser/dnd.ts:271]: I reviewed the code in detail and found that the flow is identical for both files and directories. To ensure that the `if (draggedEditors.length)` condition is met (which is required for setting the MIME type), we need to add the editor to the `draggedEditors` list.  

Additionally, `textFileModel` is `undefined` for both files and directories:  
https://github.com/microsoft/vscode/blob/8785777b1f4e70ea36210c9202b118378915b20f/src/vs/workbench/browser/dnd.ts#L291-L292

The most reasonable approach seems to be adding a separate condition for directories, like this:  
```ts
} else if (!resourceOrEditor.isDirectory) {
	editor = {
		resource: resourceOrEditor.resource,
		options: { selection: resourceOrEditor.selection }
	};
} else if (resourceOrEditor.isDirectory) {
	editor = {
		resource: resourceOrEditor.resource,
		options: { selection: undefined } // or resourceOrEditor.selection
	};
}
```
Since this is my first contribution to this repo, I’d appreciate any guidance on whether this approach aligns with the expected changes or if there are additional considerations I should address.

Comment (mjbvz) [reply src/vs/workbench/browser/dnd.ts:271]: It may be easier to add a new `draggedDirectories` variable to go with with `draggedEditors`. A directory should never end up in `draggedEditors`

Then update the code where we build the `uriListEntries` to loop through both the draggedEditors and draggedDirectories

**Comment by mkhuzaima** [comment]
@microsoft-github-policy-service agree

File: src/vs/workbench/browser/dnd.ts [hunk 2]
```diff
@@ -220,18 +220,23 @@ export function fillEditorsDragData(accessor: ServicesAccessor, resourcesOrEdito
...
+
+	// Separate directories from files
+	const draggedDirectories: IResourceStat[] = fileSystemResources.filter(({ isDirectory }) => isDirectory);
+	const draggedFiles: IResourceStat[] = fileSystemResources.filter(({ isDirectory }) => !isDirectory);
+
 	if (!options?.disableStandardTransfer) {
 
 		// Text: allows to paste into text-capable areas
 		const lineDelimiter = isWindows ? '\r\n' : '\n';
-		event.dataTransfer.setData(DataTransfers.TEXT, fileSystemResources.map(({ resource }) => labelService.getUriLabel(resource, { noPrefix: true })).join(lineDelimiter));
```
Comment (mjbvz) [inline src/vs/workbench/browser/dnd.ts:227]: We want to write both files and dirs in this case

It looks like maybe a few too many lines got touch in this change. Maybe instead of adding `draggedDirectories` and `draggedFiles`, you can make the fix clearer by focusing on the part below where we built the `url-list`. You can use use `fileSystemResources` to get the directories and combine those with the dragged editors. Something like:

```ts
if (draggedEditors.length) {
   event.dataTransfer.setData(CodeDataTransfers.EDITORS, stringify(draggedEditors));
}

const allDraggedResources = [
    ...draggedEditors.map(editor => resource),
    ...fileSystemResources.filter(({ isDirectory }) => isDirectory).map(dir => dir.resource)
]
if (allDraggedResources.length) {
    // set url-list
}
```

**Review by mjbvz — CHANGES_REQUESTED** [review]

File: src/vs/workbench/browser/dnd.ts [hunk 3]
```diff
@@ -334,9 +334,16 @@ export function fillEditorsDragData(accessor: ServicesAccessor, resourcesOrEdito
 
 	if (draggedEditors.length) {
 		event.dataTransfer.setData(CodeDataTransfers.EDITORS, stringify(draggedEditors));
+	}
+
+	const draggedDirectories: URI[] = [
+		...fileSystemResources.filter(({ isDirectory }) => isDirectory).map(({ resource }) => resource),
+	];
```
Comment (mjbvz) [inline src/vs/workbench/browser/dnd.ts:341]: Since `filter` creates a copy of the array, you can simplify this to: `const draggedDirectories = fileSystemResources .filter(...)` without using spread

**Review by mjbvz — CHANGES_REQUESTED** [review]
Just a minor note but otherwise looks good. Thanks for following up!

File: src/vs/workbench/browser/dnd.ts (hunk 3 above)
Comment (mkhuzaima) [reply src/vs/workbench/browser/dnd.ts:341]: Sure.

File: src/vs/workbench/browser/dnd.ts [hunk 4]
```diff
@@ -332,11 +332,13 @@ export function fillEditorsDragData(accessor: ServicesAccessor, resourcesOrEdito
 		draggedEditors.push(editor);
 	}
 
-	if (draggedEditors.length) {
-		event.dataTransfer.setData(CodeDataTransfers.EDITORS, stringify(draggedEditors));
+	const draggedDirectories: URI[] = fileSystemResources.filter(({ isDirectory }) => isDirectory).map(({ resource }) => resource);
+
+	if (draggedEditors.length || draggedDirectories.length) {
+		event.dataTransfer.setData(CodeDataTransfers.EDITORS, stringify([...draggedEditors, ...draggedDirectories]));
```
Comment (mkhuzaima) [inline src/vs/workbench/browser/dnd.ts:338]: If we don't set directories here, it does not solve the bug.

**Comment by mkhuzaima** [comment]
@mjbvz I have updated the PR based on the requested changes. Please review it when you have time.
I appreciate your prompt feedback and guidance.

**Comment by mjbvz** [comment]
@mkhuzaima I think there was a bug with how `resources` was set. Please test out the change I fixed and let me know if it works for you too

**Comment by mkhuzaima** [comment]
> @mkhuzaima I think there was a bug with how `resources` was set. Please test out the change I fixed and let me know if it works for you too

Will let you know soon.

**Review by mjbvz — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]
