### PR TITLE
Fix debug console after restarting session

### LINKED ISSUE #192653: Debug console is not working
Type: <b>Bug</b>

After updating yesterday, I encountered an issue with my VS code where I set a breakpoint and attempted to enter a variable in the debug console, but the console remained empty.

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (3.02GB free)|
|Process Argv|--file-uri file:///d%3A/Work/InstachatAI/InstachatAIApi.code-workspace --crash-reporter-id 6da24a21-c0cd-41c8-b3e7-ed9a77b716df|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
TabOut|alb|0.2.2
Bookmarks|ale|13.4.1
ng-template|Ang|16.1.8
vscode-django|bat|1.10.0
vscode-opennewinstance|chr|0.0.12
fastapi-snippets|dam|0.0.2
dart-code|Dar|3.72.2
flutter|Dar|3.72.0
gitlens|eam|14.3.0
prettier-vscode|esb|10.1.0
remotehub|Git|0.60.0
vscode-pull-request-github|Git|0.72.0
gc-excelviewer|Gra|4.2.58
todo-tree|Gru|0.0.226
vscode-drawio|hed|1.6.6
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.26.0
csharp|ms-|2.1.2
vscode-dotnet-runtime|ms-|1.7.2
vscode-edge-devtools|ms-|2.1.3
autopep8|ms-|2023.6.0
isort|ms-|2023.10.1
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.10
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.309.0
remote-ssh|ms-|0.106.2
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.2
vscode-remote-extensionpack|ms-|0.24.0
remote-explorer|ms-|0.4.1
remote-repositories|ms-|0.38.1
remote-server|ms-|1.4.3
vsliveshare|ms-|1.0.5883
autodocstring|njp|0.6.1
material-icon-theme|PKi|4.30.1
material-product-icons|PKi|1.6.0
sqlite-viewer|qwt|0.3.13
vscode-thunder-client|ran|2.11.4
vscode-yaml|red|1.14.0
errorlens|use|3.13.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscodeintellicode-completions|Vis|1.0.22
change-case|wma|1.0.0
material-theme|zhu|3.16.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
a2ce3375:30757347
7ij38806:30736111
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

### PR DESCRIPTION
**Pull request by roblourens**
Don't add global DebugSession listeners to rawListeners, which are disposed when a DebugSession is restarted
Fix #192653

### CODE REVIEW

File: src/vs/workbench/contrib/debug/browser/debugSession.ts [hunk 1]
```diff
@@ -103,11 +103,14 @@ export class DebugSession implements IDebugSession, IDisposable {
 			this.repl = (this.parentSession as DebugSession).repl;
 		}
 
-		const toDispose = this.rawListeners.add(new DisposableStore());
+		const toDispose = new DisposableStore();
 		const replListener = toDispose.add(new MutableDisposable());
 		replListener.value = this.repl.onDidChangeElements(() => this._onDidChangeREPLElements.fire());
 		if (lifecycleService) {
-			toDispose.add(lifecycleService.onWillShutdown(() => this.shutdown()));
+			toDispose.add(lifecycleService.onWillShutdown(() => {
```
Comment (connor4312) [inline src/vs/workbench/contrib/debug/browser/debugSession.ts:110]: It looks like disposables made in this DebugSession hang around until the window is closed -- that's probably not right?

This change looks fine if it restores the status quo of 1.81 but we should probably have a better fix for this

Comment (roblourens) [reply src/vs/workbench/contrib/debug/browser/debugSession.ts:110]: The DebugSession isn't disposed anyway- https://github.com/microsoft/vscode/issues/191904

Comment (roblourens) [reply src/vs/workbench/contrib/debug/browser/debugSession.ts:110]: I've still got to fix that and make it work with the repl

Comment (connor4312) [reply src/vs/workbench/contrib/debug/browser/debugSession.ts:110]: Sounds good. Looks like this (correctly) triggered the leak detector in some unit tests

**Review by rebornix — APPROVED** [review]
