### PR TITLE
show missingFromGallery warning only when `isEnabled && isRunning`

### LINKED ISSUE #250433: Copilot chat extension shows a warning that this is no longer available in the Marketplace
Steps to Reproduce:

1.  Create a codespace for a github repo 
2. Switch to use Insiders version from the gear menu
3. Reload window and open extensions view
🐛 Copilot chat extension has a warning that this is no longer available in Marketplace

Image

### PR DESCRIPTION
**Pull request by joshspicer**
closes https://github.com/microsoft/vscode/issues/250433

### CODE REVIEW

**Review by anthonykim1 — APPROVED** [review]

File: src/vs/workbench/contrib/extensions/browser/extensionsActions.ts [hunk 1]
```diff
@@ -2812,6 +2807,11 @@ export class ExtensionStatusAction extends ExtensionAction {
 		const isEnabled = this.workbenchExtensionEnablementService.isEnabled(this.extension.local);
 		const isRunning = this.extensionService.extensions.some(e => areSameExtensions({ id: e.identifier.value, uuid: e.uuid }, this.extension!.identifier));
 
+		if (this.extension.missingFromGallery && isEnabled && isRunning) {
```
Comment (sandy081) [inline src/vs/workbench/contrib/extensions/browser/extensionsActions.ts:2810]: @joshspicer I am not sure if this is the right fix. 

1. We should should this warning irrespective of enablement
2. We should not set missingFromGallery flag on an extension that exists in Marketplace. This is the root cause of this issue. We should check why this flag is set on Copilot chat extension
