### PR TITLE
Fixes #4803: Adding support for swipe gestures on macOS.

### LINKED ISSUE #4803: Add support for swipe gestures on Mac
- VSCode Version:
  Latest
- OS Version:
  OS X 10.11

Steps to Reproduce:
1. Use VS Code's forward and back navigation hot keys
2. Try to do the same by swiping left and right

On a Mac the Safari web browser can use the forward and back buttons to go back and forth with web pages. I do this with VS Code using hot keys when working with various files. I navigate forward by clicking through function and class names and and often want to go back. Swiping is the most natural gesture.

There was a request to add these gestures in Electron but the issue was closed. I feel it should be reopened.

https://github.com/nylas/N1/issues/541

### PR DESCRIPTION
**Pull request by seivan**
For https://github.com/Microsoft/vscode/issues/4803

Disabled by default, enabled with: 
```json
"workbench.editor.swipeToNavigate": true
```

vscode

### CODE REVIEW

**Comment by bpasero** [comment]
@seivan should this work out of the box or do I need to configure my trackpad specifically?

**Comment by seivan** [comment]
@bpasero It *should* work out of the box (with default macOS settings) but I'm not sure since I've changed my settings. 

screen shot 2017-03-31 at 01 00 46

**Comment by bpasero** [comment]
It seems to me this does not work when trackpad is configured like this:

image

**Comment by seivan** [comment]
@bpasero My take is it's an Electron issue if anything, since we're just listening to events here.

**Comment by seivan** [comment]
#### Event: 'swipe' _macOS_

Returns:

* `event` Event
* `direction` String

Emitted on ***3-finger swipe***. Possible directions are `up`, `right`, `down`, `left`.


Emphasis mine.

**Comment by bpasero** [comment]
Ok the only way I get this to work is with the following config:

image

File: src/vs/code/electron-main/window.ts [hunk 1]
```diff
@@ -373,6 +373,19 @@ export class VSCodeWindow {
 			}
 		});
 
+		// Swipe command support (macOS)
+		this._win.on('swipe', (e, cmd) => {
```
Comment (bpasero) [inline src/vs/code/electron-main/window.ts]: @seivan can we reuse this code with the `on('app-command')` handler? Seems duplicate.

**Review by bpasero — CHANGES_REQUESTED** [review]

**Comment by seivan** [comment]
@bpasero This seems like intended behaviour as Electron does not switch between `full-screen apps` but between `pages` and it *needs* three fingers as two fingers is scrolling.

File: src/vs/code/electron-main/window.ts (hunk 1 above)
Comment (seivan) [inline src/vs/code/electron-main/window.ts]: @bpasero Read my mind. I thought about it but I wasn't sure you guys would want it. We could take an object of events and left/right options to compare to. 

Is that OK with you?

**Comment by bpasero** [comment]
@seivan makes sense, I asked on the related issue for more feedback from users. Otherwise your PR seems like the way to go (I added little bit of feedback).

File: src/vs/code/electron-main/window.ts (hunk 1 above)
Comment (bpasero) [inline src/vs/code/electron-main/window.ts]: @seivan extracting the code to a function and calling it works for me best

**Comment by bpasero** [comment]
@seivan ping

**Comment by seivan** [comment]
@bpasero I thought we were still waiting for feedback. My bad. I'll get it on later tonight.

**Comment by bpasero** [comment]
Thanks!

**Comment by bpasero** [comment]
@seivan the more I think about it the more I feel this should be controlled via a new setting so that users can opt-in to this feature and report back how it works. I suggest something like `workbench.swipeToNavgiate` (boolean) and wire it up. You can see for other settings like `window.titleBarStyle` how this is wired up.

**Comment by seivan** [comment]
@bpasero Yeah that makes sense. I'll give it a go tomorrow.

**Comment by seivan** [comment]
@bpasero  I didn't have time to check, but do you 're-run'  `registerListeners()` on settings change? 
Or do you need to trigger a function on setting changes? 

If you do not re-run `registerListeners()`  then I need to listen to setting changes to remove the swipe-listener, not sure where to find those.

**Comment by bpasero** [comment]
@seivan yes you should listen to the settings change and adjust accordingly, see https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/window.ts#L246 for example how we do it there.

**Comment by seivan** [comment]
@bpasero Sorry, I don't quite follow, could you show which specific callback to listen to? Your link seems outdated now.

**Comment by bpasero** [comment]
@seivan yes that is the right listener to use, it should be available on the main side to listen for config changes (maybe I did not understand your question properly?)

**Comment by seivan** [comment]
@bpasero Just to clear the ambiguity, I am just not sure where I'm supposed to to use `this.onConfigurationUpdated { .... } ` and check for enable/disable and set the listener or remove it?

**Comment by bpasero** [comment]
@seivan I would say you can maybe remove the swipe listener (or add it) based on the configuration change event, iff the value of this setting changes. So I would say that listening on this event around where you register the swipe listener is the right place.

**Comment by seivan** [comment]
@bpasero Yeah, that's what I am asking; what's the method that triggers on configuration change? Will it also trigger on boot? So I can just keep it in one place?

**Comment by seivan** [comment]
@bpasero Alright, so I think I figured it out. Take a look, thanks!

File: src/vs/code/electron-main/window.ts [hunk 2]
```diff
@@ -334,6 +335,22 @@ export class VSCodeWindow {
...
+			if (this.readyState !== ReadyState.READY) {
+				return; // window must be ready
+			}
+
+			if (cmd === back) {
+				this.send('vscode:runAction', 'workbench.action.navigateBack');
+			} else if (cmd === forward) {
+				this.send('vscode:runAction', 'workbench.action.navigateForward');
+			} else {
+				console.warn('[electron command]: did not handle: ', command);
```
Comment (bpasero) [inline src/vs/code/electron-main/window.ts]: Should not happen, please remove.

File: src/vs/code/electron-main/window.ts [hunk 3]
```diff
@@ -425,11 +431,20 @@ export class VSCodeWindow {
...
-		const newMenuBarVisibility = this.getMenuBarVisibility(config);
+		const newMenuBarVisibility = this.getMenuBarVisibility();
 		if (newMenuBarVisibility !== this.currentMenuBarVisibility) {
 			this.currentMenuBarVisibility = newMenuBarVisibility;
 			this.setMenuBarVisibility(newMenuBarVisibility);
 		}
+
+		// Swipe command support (macOS)
+		const workbenchConfig = this.configurationService.getConfiguration<IWorkbenchEditorConfiguration>();
+		if (workbenchConfig && workbenchConfig.workbench && workbenchConfig.workbench.editor.swipeBetweenOpenFiles) {
```
Comment (bpasero) [inline src/vs/code/electron-main/window.ts]: Careful here, `workbenchConfig.workbench.editor` can be `null` so we need another `null` check.

File: src/vs/workbench/electron-browser/main.contribution.ts [hunk 4]
```diff
@@ -76,83 +76,96 @@ workbenchActionsRegistry.registerWorkbenchAction(new SyncActionDescriptor(Decrea
...
+	},
+	'workbench.editor.closeOnFileDelete': {
+		'type': 'boolean',
+		'description': nls.localize('closeOnFileDelete', "Controls if editors showing a file should close automatically when the file is deleted or renamed by some other process. Disabling this will keep the editor open as dirty on such an event. Note that deleting from within the application will always close the editor and that dirty files will never close to preserve your data."),
+		'default': true
+	}
+};
+
+if (isMacintosh) {
+	workbenchProperties['workbench.editor.swipeBetweenOpenFiles'] = {
```
Comment (bpasero) [inline src/vs/workbench/electron-browser/main.contribution.ts]: I am not a big fan of the naming `swipeBetweenOpenFiles`, because in reality you can swipe left and right between any editor that is opened, not just files. How about naming this `workbench.editor.swipeToNavigate`?

**Review by bpasero — CHANGES_REQUESTED** [review]
Getting closer, some minor feedback included.

File: src/vs/code/electron-main/window.ts (hunk 2 above)
Comment (seivan) [inline src/vs/code/electron-main/window.ts]: The cmd is a string. It could technically happen? You want the warning removed?

Comment (bpasero) [inline src/vs/code/electron-main/window.ts]: You could guard against this by using a string variable, e.g. `'foo' | 'bar'` so that noone can pass anything else in.

Comment (seivan) [inline src/vs/code/electron-main/window.ts]: @bpasero We can't predict all the available commands for every event related to navigation that exists. You would have to maintain a list somewhere to keep them up to date. 
E.g for `swipe` it's `left` and `right` but on `app-command` it's:  `browser-backward` and `browser-forward`

File: src/vs/code/electron-main/window.ts (hunk 3 above)
Comment (seivan) [inline src/vs/code/electron-main/window.ts]: Ah good point. I was thinking maybe they should be defined as optionals.I actually thought of doing that refactoring. But maybe that should be a different PR? 

I feel having to do those checks without the compiler enforcing it is *wrong* per se.

File: src/vs/workbench/electron-browser/main.contribution.ts (hunk 4 above)
Comment (seivan) [inline src/vs/workbench/electron-browser/main.contribution.ts]: @bpasero You're right, I'm not happy with the name either, changed it twice, lol. 
Sure, that's a good call.

File: src/vs/code/electron-main/window.ts (hunk 2 above)
Comment (bpasero) [inline src/vs/code/electron-main/window.ts]: But we are calling this method, no? Why do we expect to print a warning? This is not API anyone else is using?

File: src/vs/code/electron-main/window.ts (hunk 3 above)
Comment (bpasero) [inline src/vs/code/electron-main/window.ts]: All of it can be null as soon as a user configures something like this in settings:

```json
{
   editor: null
}
```

Comment (seivan) [inline src/vs/code/electron-main/window.ts]: Ah I understand! 
How do you feel about making this more inline with TS and using optionals? Should prevent future issues like this.

Comment (bpasero) [inline src/vs/code/electron-main/window.ts]: Like how?

Comment (seivan) [inline src/vs/code/electron-main/window.ts]: @bpasero I can take that in a different PR if it would be of interest, basically the structure now could technically be changed to a class with optional attributes. It's just a regular object for now(?). I'll leave it and do the checks for now.

Comment (bpasero) [inline src/vs/code/electron-main/window.ts]: We cannot change this, it is just a plain old object after all.

File: src/vs/code/electron-main/window.ts (hunk 2 above)
Comment (seivan) [inline src/vs/code/electron-main/window.ts]: @bpasero Imagining future navigation gestures that have unhandled cmds. It's up to you. If you want it gone, I'll remove it.

Comment (bpasero) [inline src/vs/code/electron-main/window.ts]: Yeah, lets remove it for now, thanks 👍

**Comment by seivan** [comment]
@bpasero Take another look.

**Comment by bpasero** [comment]
Thanks, looks good now!
