### PR TITLE
include `hideFromUser` terminals in `terminalService.instances`

### LINKED ISSUE #199611: `onDidExecuteTerminalCommand` does not fire events for hidden terminal
Does this issue occur when all extensions are disabled?: Yes/No

For proposed API: https://github.com/microsoft/vscode/issues/145234

Version: 1.85.0-insider (user setup)
OS: Windows_NT x64 10.0.22518

Steps to Reproduce:

1. Create a hidden terminal using `hideFromUser` to `true`
2. Send text to terminal, for eg. "echo hello"
3. Watch no events are fired

Same is not the case if `hideFromUser` is set to `false`.

cc/ @Tyriar

### PR DESCRIPTION
**Pull request by meganrogge**
See https://github.com/microsoft/vscode/issues/199611#issuecomment-2065292283
fix #199611

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalView.ts [hunk 1]
```diff
@@ -343,7 +343,7 @@ export class TerminalViewPane extends ViewPane {
 	}
 
 	override shouldShowWelcome(): boolean {
-		return this._hasWelcomeScreen() && this._terminalService.instances.length === 0;
+		return this._hasWelcomeScreen() && this._terminalGroupService.instances.length === 0;
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalView.ts:346]:
```suggestion
		return this._hasWelcomeScreen() && this._terminalService.instances.length === 0;
```

**Review by Tyriar — APPROVED** [review]
