### PR TITLE
Fix #163005 (#163339)

### LINKED ISSUE #163005: Extension sync not working in vscode server web
- VS Code Version:  stable from sources

Regression in current september release

Steps to Reproduce:

1. Run server, open workbench in browser
2. Enable settings sync
3. Install some extension
4. Check remote server logs

```
[2022-10-07 21:19:32.337] [remoteagent] [error] ENOPRO: No file system provider found for resource 'vscode-userdata:/User/extensions.json'
    at f.withProvider (/ide/out/vs/server/node/server.main.js:87:18410)
    at async f.withReadProvider (/ide/out/vs/server/node/server.main.js:87:18533)
    at async f.readFile (/ide/out/vs/server/node/server.main.js:87:23097)
    at async Object.factory (/ide/out/vs/server/node/server.main.js:89:1822)
```

cc @sandy081

### PR DESCRIPTION
**Pull request by sandy081**
#163005

### CODE REVIEW

File: src/vs/workbench/services/extensionManagement/common/remoteExtensionManagementService.ts [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+
+	override async installFromGallery(extension: IGalleryExtension, options?: InstallOptions): Promise<ILocalExtension> {
+		options = this.validateProfileLocation(options);
+		return super.installFromGallery(extension, options);
+	}
+
+	private validateProfileLocation<T extends { profileLocation?: URI }>(options?: T): T | undefined {
+		if (options?.profileLocation) {
+			if (!this.uriIdentityService.extUri.isEqual(options?.profileLocation, this.userDataProfileService.defaultProfile.extensionsResource)) {
+				throw new Error('This opertaion is not supported in remote scenario');
```
Comment (aeschli) [inline src/vs/workbench/services/extensionManagement/common/remoteExtensionManagementService.ts:55]: typo on `opertaion`

**Review by aeschli — DISMISSED** [review]

**Review by aeschli — APPROVED** [review]

**Comment by MEDVEDEFFIZZAMUZZIC1996** [comment]
> #163005
