### PR TITLE
Fix-75259 - Interact with files in search results

### LINKED ISSUE #75259: Interact with files in search results
Being able to interact with the files that appear in `Search` would be useful. A few examples that come to mind:

1. Rename file matched by search. Clicking the file in the search result and then pressing `F2` does not work. Right-clicking the file does not show the `Rename` command. Right-clicking the file does not show `Reveal in Side Bar` (where the file could be renamed). The only option I've found is to click one of the matches to open the file, right click the tab, select `Reveal in Side Bar` and rename the file using the `Explorer` side bar (`F2` or right-click).
2. Delete file matched by search.
3. Delete multiple files matched by search.
4. Dismiss multiple files from the search result.
5. Compare two files matched by search.

When right-clicking a file in `Search`, I think all the options that are shown when right-clicking a file in `Explorer` should be shown. Then any options added by extensions would also be available. The keyboard shortcuts `Delete` and `Ctrl+C` should probably keep their current behavior.

Also, it should be possible to select multiple files, similar to in `Explorer`.

### PR DESCRIPTION
**Pull request by skprabhanjan**
@roblourens , I added "Reveal in Side Bar" menu to search to fix #75259 but there seems to be one issue .
When I use "Reveal in Side Bar" from the title then it switches to explorer and highlights the correct file in explorer .
I have added the same way but when I click on the new menu option I added in search , it takes me to the explorer but highlights the file that is shown in the editor and not the one I asked to Reveal in side bar.

Added a small [video](https://drive.google.com/open?id=1-y9bh2HDYBUQ07TkhwkPnx6xY8T4O72O) of the same for better understanding , Can you please help me out on this ? ( If some other event is causing the highlighting on click or something ?? )

### CODE REVIEW

**Comment by roblourens** [comment]
That command will try to get the currently selected row and it will probably be trying to get it from the explorer view, not the search view. You will probably need a new command that can get the current file from the search view.

**Comment by skprabhanjan** [comment]
@roblourens , Yes i figured it out and changed it accordingly .
Works perfectly now , Please review it and let me know if anything needs to be changed :)

File: src/vs/workbench/contrib/search/browser/search.contribution.ts [hunk 1]
```diff
@@ -212,6 +214,37 @@ KeybindingsRegistry.registerCommandAndKeybindingRule({
...
+					explorerService.select(uri, true).then(() => explorerView.focus(), onUnexpectedError);
+				}
+			}
+		});
+	}
+});
+
+const RevealInSideBarForSearchResultsCommand: ICommandAction = {
+	id: Constants.RevealInSideBarForSearchResults,
+	title: nls.localize('revealInSideBar', "Reveal in Side Bar")
```
Comment (roblourens) [inline src/vs/workbench/contrib/search/browser/search.contribution.ts]: I think I would rather see "Reveal in Explorer" since the search view may already be in the side bar

File: src/vs/workbench/contrib/search/browser/search.contribution.ts [hunk 2]
```diff
@@ -212,6 +214,37 @@ KeybindingsRegistry.registerCommandAndKeybindingRule({
...
+};
+
+MenuRegistry.appendMenuItem(MenuId.SearchContext, {
+	command: RevealInSideBarForSearchResultsCommand,
+	when: ResourceContextKey.IsFileSystemResource && Constants.HasSearchResults,
```
Comment (roblourens) [inline src/vs/workbench/contrib/search/browser/search.contribution.ts]: `ResourceContextKey` is not actually hooked up for the search view, please see how ExplorerView does it. An issue from this is that this command is enabled when you right click on a Match, not just a file/folder

Comment (roblourens) [reply src/vs/workbench/contrib/search/browser/search.contribution.ts]: It should probably only be available for a file, not a folder (you can try that by adding a second folder to the workspace, searching something that matches in both folders, and clicking the folder row)

**Review by roblourens — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/search/browser/search.contribution.ts (hunk 1 above)
Comment (skprabhanjan) [reply src/vs/workbench/contrib/search/browser/search.contribution.ts]: Done

**Comment by skprabhanjan** [comment]
@roblourens  ,  All the changes are done :)
For the `ResourceContextKey` not hooked up in search view issue , I reused `Constants.FileMatchOrFolderMatchFocusKey`, This works fine .

**Comment by roblourens** [comment]
But does it do the right thing for a folder?

**Comment by skprabhanjan** [comment]
@roblourens , sorry forgot to add that change.
Now the "Reveal in Explorer" comes up only for a file (Not enabled when clicked on a folder or a match)

**Review by roblourens — APPROVED** [review]
Looks good, thanks!
