### PR TITLE
Fix ipv6 support for simple browser

### LINKED ISSUE #158599: Simple browser opener doesn't work with IPv6 hosts
Pretty sure the problem is here:

https://github.com/microsoft/vscode/blob/82fce9f053fda71dd7d0f89ef32f2b5748eabe19/extensions/simple-browser/src/extension.ts#L70-L71

When passed the string `"http://0:0:0:0:0:0:0:0:3000/"`, `new URL` throws. You can reproduce the issue by trying to "open in preview" the auto detected port that you get when running the server in https://github.com/joshaber/simple-server/tree/devcontainer-preview from a codespace.

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #158599

This correctly handles ipv6 uris, such as `http://[::]:3000`. In these cases, the brackets are required

### CODE REVIEW

File: extensions/simple-browser/src/extension.ts [hunk 1]
```diff
@@ -65,14 +62,15 @@ export function activate(context: vscode.ExtensionContext) {
...
 	}));
 
 	context.subscriptions.push(vscode.window.registerExternalUriOpener(openerId, {
 		canOpenExternalUri(uri: vscode.Uri) {
 			// We have to replace the IPv6 hosts with IPv4 because URL can't handle IPv6.
-			const originalUri = new URL(uri.toString().replace(IPv6Localhost, '127.0.0.1').replace(IPv6AllInterfaces, '0.0.0.0'));
+			const originalUri = new URL(uri.toString(true));
 			if (enabledHosts.has(originalUri.hostname)) {
+				return vscode.ExternalUriOpenerPriority.Default;
 				return isWeb()
```
Comment (alexr00) [inline extensions/simple-browser/src/extension.ts:74]: Unreachable code?

**Review by alexr00 — CHANGES_REQUESTED** [review]

**Review by alexr00 — APPROVED** [review]
