### PR TITLE
poll until windows cursor position is correct for `onCommandStarted`

### LINKED ISSUE #193456: [Accessibility] Terminal input edit is still buggy
Type: <b>Bug</b>

CC @meganrogge 

# Reproducible Steps

1. Create a new terminal

1. Type `echo hello` and hit enter

1. Type `echo world` in a new line and hit enter (you must create at least two lines of code to test b/c the single line does not have this issue)

1. Press UpArrow

1. Press LeftArrow multiple times to test if you can hear "echo world" character by character.

* Notes: For NVDA and JAWS on Windows, it keeps saying "d" which is the last character.

VS Code version: Code - Insiders 1.83.0-insider (7c7f7eee860e299499a3bd2915ad716f09f2d6a6, 2023-09-19T08:56:35.775Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (6.31GB free)|
|Process Argv|C:\\Users\\jseo1005\\OneDrive - University of Illinois - Urbana\\Desktop\\source.R --crash-reporter-id b05b88e5-8894-4031-ae34-fa034ebddea9|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (91)</summary>

Extension|Author (truncated)|Version
---|---|---
android-dev-ext|ade|1.3.2
aiprm-lang|AIP|0.0.2
Bookmarks|ale|13.4.1
openscad|Ant|1.2.1
spellright|ban|3.0.118
zoterolatex|bna|0.4.1
mermaid-markdown-syntax-highlighting|bpr|1.5.2
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.51.0
vscode-eslint|dba|2.4.2
vscode-quick-select|dba|0.2.9
vscode-deno|den|3.22.0
gitlens|eam|14.3.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|10.1.0
vscode-google-translate|fun|1.4.13
codespaces|Git|1.15.3
copilot|Git|1.112.422
copilot-chat|Git|0.8.2023091902
remotehub|Git|0.60.0
vscode-github-actions|git|0.26.2
vscode-pull-request-github|Git|0.72.0
overleaf-workshop|iam|0.1.5
cslpreview|igo|0.2.2
easy-snippet|inu|0.6.3
path-autocomplete|ion|1.25.0
latex-workshop|Jam|9.14.0
lilypond-syntax|jea|0.1.1
scheme|jea|0.2.0
better-cpp-syntax|jef|1.17.2
google-search|kam|0.0.1
vscode-lua-format|Koi|1.3.8
lilypond-formatter|lhl|0.2.3
lilypond-pdf-preview|lhl|0.2.8
lilypond-snippets|lhl|0.1.1
vslilypond|lhl|1.7.3
zotero|mbl|0.1.10
git-graph|mhu|1.30.0
vscode-docker|ms-|1.26.0
black-formatter|ms-|2023.4.1
flake8|ms-|2023.6.0
isort|ms-|2023.11.12061012
python|ms-|2023.16.0
vscode-pylance|ms-|2023.9.10
jupyter|ms-|2023.8.1002501831
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.311.0
remote-ssh|ms-|0.106.4
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.81.3
vscode-remote-extensionpack|ms-|0.24.0
azure-repos|ms-|0.36.0
cmake-tools|ms-|1.15.31
cpptools|ms-|1.17.5
cpptools-extension-pack|ms-|1.3.0
js-debug-nightly|ms-|2023.9.1317
powershell|ms-|2023.6.0
remote-repositories|ms-|0.38.1
vscode-github-issue-notebooks|ms-|0.0.129
vscode-selfhost-test-provider|ms-|0.3.18
vscode-serial-monitor|ms-|0.10.0
vsliveshare|ms-|1.0.5883
autodocstring|njp|0.6.1
pandocciter|not|0.10.3
shiny-python|Pos|0.1.4
shinyuieditor|pos|0.4.3
quarto|qua|1.98.0
r-debugger|RDe|0.5.4
java|red|1.22.1
vscode-xml|red|0.26.1
r|REd|2.8.1
multi-command|ryu|1.6.0
vscode-deepl|soe|1.0.6
abc-music|sof|0.4.0
lua|sum|3.7.0
latex-utilities|tec|0.4.10
cmake|twx|0.0.17
errorlens|use|3.13.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-arduino|vsc|0.6.0
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.14
vscode-java-test|vsc|0.39.1
vscode-maven|vsc|0.42.0
markdown-all-in-one|yzh|3.5.1
grammarly|znc|0.22.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
ecj1e332:30687743
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
asynctok:30821568
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonlinttype:30823781
pythonmpsinfo:30815194
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809

```

</details>

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #193456

### CODE REVIEW

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 1]
```diff
@@ -451,7 +487,7 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
 
 	handleCommandFinished(exitCode: number | undefined, options?: IHandleCommandOptions): void {
 		if (this._isWindowsPty) {
```
Comment (meganrogge) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:489]: do we need to be worried about `handleCommandExecuted` happening at the same time as `handleCommandFinished` given they both could be awaiting the same promise?

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 2]
```diff
@@ -404,7 +440,7 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
 
 	handleCommandExecuted(options?: IHandleCommandOptions): void {
 		if (this._isWindowsPty) {
-			this._handleCommandExecutedWindows();
+			this._commandStartWindowsPromise?.then(() => this._handleCommandExecutedWindows());
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:443]: We want to "flush" this task and execute it immediately instead of wait for it as it could back up and never get canceled. You can do this in a few ways, for example using a Barrier and calling `open()` before handling execution/finished

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts (hunk 1 above)
Comment (Tyriar) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:489]: Yes let's make sure the task has run before handling finished as it looks like `handleCommandFinished` does some validation later on (`if (this._currentCommand.commandStartMarker === undefined || !this._terminal.buffer.active) {`). It would also be nicer to the awaiting inside `_preHandleCommandFinishedWindows` and make that `async`

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 3]
```diff
@@ -361,35 +362,70 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
...
+		}
+
+		function lineIsPrompt(): boolean {
+			const line = terminal.buffer.active.getLine(terminal.buffer.active.baseY + terminal.buffer.active.cursorY);
+			if (!line) {
+				return false;
+			}
+			// TODO: fine tune prompt regex to accomodate for unique configurtions.
+			return line.translateToString(true)?.match(/^(PS.+>)|([A-Z]:\\.*>)/) !== null;
+		}
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:391]: I'm a bit hazy on the details of performance/JIT wrt inline functions like this. To be on the safe side, let's make these class methods instead.

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 4]
```diff
@@ -361,35 +362,70 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
...
-						if (marker) {
-							this._commandMarkers.push(marker);
-						}
-					}
-				});
+
+		const lastCommand = this.commands.at(-1);
+		const terminal = this._terminal;
+
+		function cursorOnCorrectLine(): boolean {
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:374]: Name could be improved "correct" is ambiguous

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 5]
```diff
@@ -361,35 +362,70 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
...
-				const line = this._terminal.buffer.active.getLine(this._currentCommand.commandStartMarker.line);
-				if (line) {
-					this._currentCommand.commandStartLineContent = line.translateToString(true);
+			const cursorYAbsolute = terminal.buffer.active.baseY + terminal.buffer.active.cursorY;
+			// If the cursor position is within the last command, we should poll.
+			const lastCommandYAbsolute = (lastCommand.endMarker ? lastCommand.endMarker.line : lastCommand.marker?.line) ?? -1;
+			return cursorYAbsolute > lastCommandYAbsolute;
+		}
+
+		function lineIsPrompt(): boolean {
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:384]: Name is a bit ambiguous again, how about `cursorLineLooksLikeWindowsPrompt`? It's long but it removed all ambiguity

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 6]
```diff
@@ -361,35 +362,70 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
...
+
+		// Conpty could have the wrong cursor position at this point.
+		if (!cursorOnCorrectLine() || !lineIsPrompt()) {
+			// Poll for 200ms until the cursor position is correct.
+			for (let i = 0; i < 20; i++) {
+				await timeout(10);
+				if (cursorOnCorrectLine() && lineIsPrompt()) {
+					this._logService.debug('CommandDetectionCapability#_handleCommandStartWindows polling attempts required: ', i + 1);
+					break;
 				}
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:401]: I think the main interesting thing to log here is when it does not end up breaking after the loop has finished. Move the log after the for loop and check `i >= 20`?

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts (hunk 4 above)
Comment (meganrogge) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:374]: Yeah I wondered about that too. `Next` is relative, so isn't great either.

Comment (Tyriar) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts]: `isCursorLineWithLastCommand`?

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 7]
```diff
@@ -407,6 +409,7 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
 		}
 		this._onCommandStarted.fire({ marker: this._currentCommand.commandStartMarker } as ITerminalCommand);
 		this._logService.debug('CommandDetectionCapability#_handleCommandStartWindows', this._currentCommand.commandStartX, this._currentCommand.commandStartMarker?.line);
+		this._commandStartedWindowsBarrier.open();
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:412]: This isn't quite right, we want the task that runs when the polling has finished to be after `this._commandStartedWindowsBarrier.wait()`. Right now it will automatically open after 200ms which isn't what we're after as then executed code will run before started code

Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:412]: This isn't quite right, we want the task that runs when the polling has finished to be after `this._commandStartedWindowsBarrier.wait()`. Right now it will automatically open after 200ms which isn't what we're after as then executed code will run before started code

Comment (meganrogge) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:412]: But I thought that we don't want to block / back things up? Maybe setting it to 500 ms is sufficient?

Comment (meganrogge) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:412]: I misunderstood it seems - I thought we wanted to set a limit for how long we'd wait

**Comment by meganrogge** [comment]
something's wrong now. it's reaching max attempts 🤔 pretty frequently

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 8]
```diff
@@ -361,35 +362,81 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
...
+			await Promise.race(
+				[
+					new Promise((resolve) => {
+						let i = 0;
+						for (; i < 20; i++) {
+							timeout(10).then(() => {
+								if (this._cursorOnNextLine() && this._cursorLineLooksLikeWindowsPrompt()) {
+									resolve(undefined);
+								}
+							});
```
Comment (meganrogge) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:384]: this is still not working correctly, working on it

Comment (meganrogge) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:384]: also tried `resolve(true)` here and that didn't work. not sure what's going on

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 9]
```diff
@@ -361,35 +363,74 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
...
 			}
-			this._currentCommand.commandStartMarker = this._terminal.registerMarker(0);
-			if (this._currentCommand.commandStartMarker) {
-				const line = this._terminal.buffer.active.getLine(this._currentCommand.commandStartMarker.line);
-				if (line) {
-					this._currentCommand.commandStartLineContent = line.translateToString(true);
+			if (i === 20) {
+				this._logService.debug('CommandDetectionCapability#_handleCommandStartWindows reached max attempts, ', this._cursorOnNextLine(), this._cursorLineLooksLikeWindowsPrompt());
+			}
+		} else {
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:386]: We need to cancel this process if another command happens while it's happening. It's an edge case that can maybe only reproduce in a misbehaving shell, but it could lead to really weird bugs.

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 10]
```diff
@@ -438,7 +479,9 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
 		this._onCommandExecuted.fire();
 	}
 
-	private _handleCommandExecutedWindows(): void {
+	private async _handleCommandExecutedWindows(): Promise<void> {
+		await this._commandStartedWindowsBarrier?.wait();
+		this._commandExecutedWindowsBarrier = new Barrier();
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:484]: I don't think this one does anything as everything between it and the `open` is synchronous.

**Review by Tyriar — DISMISSED** [review]

**Comment by meganrogge** [comment]
I'm still seeing occasional issues - when the polling is not sufficient 😢

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 11]
```diff
@@ -361,35 +363,82 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
...
-							this._commandMarkers.push(marker);
-						}
+
+		// Conpty could have the wrong cursor position at this point.
+		if (!this._cursorOnNextLine() || !this._cursorLineLooksLikeWindowsPrompt()) {
+			this._windowsPromptPollingInProcess = true;
+			// Poll for 200ms until the cursor position is correct.
+			let i = 0;
+			for (; i < 20; i++) {
+				await timeout(10);
```
Comment (mjbvz) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:382]: Does this need to handle cases where the `this` object is disposed of while the timeouts are still firing?

**Review by mjbvz — APPROVED** [review]
