### PR TITLE
resolvers: fallback to one authority when resolving nesting remote authorities fail

### LINKED ISSUE #187202: Failed to connect to the remote extension host server (Error: Not an authority that can be resolved!) on 1.80.0 but not on earlier versions
Does this issue occur when all extensions are disabled?: Yes

Version: 1.80.0 (Universal)
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:39:33.766Z (2 days ago)
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

Steps to Reproduce:

1. When I try to connect to a machine over ssh using a vs code remote url 

eg: `vscode://vscode-remote/ssh-remote+devzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects?windowId=_blank`

I get the following error message 

```
Failed to connect to the remote extension host server (Error: Not an authority that can be resolved!)
 ```

I can work around by either:

- downgrading vscode to May 2023 (version 1.79)

- manually adding entry to my ~/.ssh/config

working ssh config 

```
Host ybsvmibl.devinfra.dev0.run
	HostName ybsvmibl.devinfra.dev0.run
	User devzero
```
vscode dev console logs 

```
vscode-remote-resource?path=%2Fhome%2Fdevzero%2F.vscode-server%2Fextensions%2Feamodio.gitlens-14.0.1%2Fimages%2Fgitlens-icon.png:1          Failed to load resource: net::ERR_INVALID_URL
log.ts:421  INFO Invoking resolveAuthority(ssh-remote)...
log.ts:421  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] obtaining proxy...
log.ts:421  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] invoking...
log.ts:441   ERR [LocalProcess0][resolveAuthority(ssh-remote,1)][6ms] returned an error Error: Not an authority that can be resolved!
	at i.ob (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:16793)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:17528
	at Array.map (<anonymous>)
	at i.$resolveAuthority (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:17435)
	at t.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:11199)
	at t.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:10965)
	at t.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:10046)
	at t.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:9122)
	at i.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:7952)
	at p.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:76:13931)
	at i.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:30341)
	at p.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:76:13931)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:28621)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
log.ts:441   ERR resolveAuthority(ssh-remote) returned an error after 6 ms CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR Error received from starting extension host (kind: Remote)
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR [remote-connection][attempt 2] An error occurred in initial connection! Will retry... Error:
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR [remote-connection][attempt 3] An error occurred in initial connection! Will retry... Error:
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR [remote-connection][attempt 4] An error occurred in initial connection! Will retry... Error:
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR [remote-connection][attempt 5]  An error occurred in initial connection! It will be treated as a permanent error. Error:
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR Cannot register remote filesystem provider. Error while fetching remote environment. Not an authority that can be resolved!
notificationsAlerts.ts:42 Failed to connect to the remote extension host server (Error: Not an authority that can be resolved!)
c @ notificationsAlerts.ts:42
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:431  WARN Ignoring the error while validating workspace folder vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects - ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects'
log.ts:441   ERR Not an authority that can be resolved!: CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19839)
    at async e.$W9b.nb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19105)
    at async e.$W9b.Lb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2610:11242)
    at async e.$W9b.gb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:16869)
log.ts:441   ERR Not an authority that can be resolved!: CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19839)
    at async e.$W9b.nb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19105)
    at async e.$W9b.Lb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2610:11242)
    at async e.$W9b.gb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:16869)
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects/.vscode': CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects/.vscode'
    at e.$op.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:11401)
    at async e.$op.exists (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:13607)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1993:6258
    at async Promise.all (index 0)
    at async e.$ijb.v (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1993:6365)
log.ts:441   ERR Not an authority that can be resolved!: CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19839)
    at async e.$W9b.nb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19105)
    at async e.$W9b.Lb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2610:11242)
    at async e.$W9b.gb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:16869)
log.ts:441   ERR CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects'
    at e.$op.j (fileService.ts:140:18)
    at async e.$op.W (fileService.ts:1110:20)
    at async fileService.ts:1095:24
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects/.git/config': CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects/.git/config'
    at e.$op.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:11401)
    at async e.$op.exists (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:13607)
    at async Promise.all (index 0)
log.ts:441   ERR ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects/pom.xml': CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects/pom.xml'
    at e.$op.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:11401)
    at async e.$op.exists (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:13607)
    at async Promise.all (index 0)
log.ts:441   ERR ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects': CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdevzero@ybsvmibl.devinfra.dev0.run/home/devzero/projects'
    at e.$op.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:11401)
    at async e.$op.n (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:12190)
    at async e.$op.resolve (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:627:12018)
    at async e.$IXb.i (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1931:5269)
log.ts:441   ERR Not an authority that can be resolved!: CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19839)
    at async e.$W9b.nb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19105)
    at async e.$W9b.Lb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2610:11242)
    at async e.$W9b.gb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:16869)
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (abstractExtensionService.ts:620:9)
    at async e.$W9b.nb (abstractExtensionService.ts:581:19)
    at async e.$W9b.Lb (nativeExtensionService.ts:368:22)
    at async e.$W9b.gb (abstractExtensionService.ts:417:31)
log.ts:441   ERR Not an authority that can be resolved!: CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19839)
    at async e.$W9b.nb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19105)
    at async e.$W9b.Lb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2610:11242)
    at async e.$W9b.gb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:16869)
log.ts:441   ERR Not an authority that can be resolved!: CodeExpectedError: Not an authority that can be resolved!
    at e.$W9b.ob (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19839)
    at async e.$W9b.nb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19105)
    at async e.$W9b.Lb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2610:11242)
    at async e.$W9b.gb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2609:16869)
 
```

### PR DESCRIPTION
**Pull request by Viknet**
Fixes #187202 
If resolving nested authorities failed, fallback to the old logic with one authority.

### CODE REVIEW

**Comment by Viknet** [comment]
@microsoft-github-policy-service agree

File: src/vs/workbench/api/common/extHostExtensionService.ts [hunk 1]
```diff
@@ -824,20 +825,26 @@ export abstract class AbstractExtHostExtensionService extends Disposable impleme
...
-				logInfo(`activating resolver...`);
-				const { resolver, authorityPrefix } = await this._activateAndGetResolver(remoteAuthority);
-				if (!resolver) {
-					logError(`no resolver`);
-					throw new RemoteAuthorityResolverError(`No remote extension installed to resolve ${authorityPrefix}.`, RemoteAuthorityResolverErrorCode.NoResolverFound);
-				}
-				return { resolver, authorityPrefix, remoteAuthority };
-			}));
+			resolvers = await Promise.all(chain.map(getResolver)).catch(async (e: Error) => {
+				if (e instanceof RemoteAuthorityResolverError) { throw e; }
```
Comment (connor4312) [inline src/vs/workbench/api/common/extHostExtensionService.ts:844]: Did you mean to make this instead

```suggestion
				if (!RemoteAuthorityResolverError.isNoResolverFound(e)) { throw e; }
```

Comment (Viknet) [reply src/vs/workbench/api/common/extHostExtensionService.ts:844]: I think here we should do fallback only when error is ```Error(`Not an authority that can be resolved!`)``` - and it is not subclass of `RemoteAuthorityResolverError`

Comment (connor4312) [reply src/vs/workbench/api/common/extHostExtensionService.ts:844]: Yes, I agree. The way the logic is implemented, it will only fall back to `getResolver(remoteAuthorityChain)` if `e` is _not_ a subclass of RemoteAuthorityResolverError

**Comment by Viknet** [comment]
@connor4312 Is this PR ready to merge?

File: src/vs/workbench/api/common/extHostExtensionService.ts (hunk 1 above)
Comment (connor4312) [reply src/vs/workbench/api/common/extHostExtensionService.ts:844]: Oh, sorry, I misunderstood.

I think we should introduce a new RemoteAuthoriyResolverErrorCode for an "invalid authority" to avoid having to catch generic errors here, which could lead to incorrectly falling back (e.g. if an error is thrown from a remote extension' activate method)

Comment (Viknet) [reply src/vs/workbench/api/common/extHostExtensionService.ts:844]: I don't really understand why there are two different classes for RemoteAuthorityResolverError:
https://github.com/microsoft/vscode/blob/main/src/vs/platform/remote/common/remoteAuthorityResolver.ts#L97
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostTypes.ts#L536

But import in this file points to the second one, which does not have `.isNoResolverFound` methods.

File: src/vs/workbench/api/common/extHostExtensionService.ts [hunk 2]
```diff
@@ -795,7 +795,7 @@ export abstract class AbstractExtHostExtensionService extends Disposable impleme
 	private async _activateAndGetResolver(remoteAuthority: string): Promise<{ authorityPrefix: string; resolver: vscode.RemoteAuthorityResolver | undefined }> {
 		const authorityPlusIndex = remoteAuthority.indexOf('+');
 		if (authorityPlusIndex === -1) {
-			throw new Error(`Not an authority that can be resolved!`);
+			throw RemoteAuthorityResolverError.InvalidAuthority(`Not an authority that can be resolved!`);
```
Comment (connor4312) [inline src/vs/workbench/api/common/extHostExtensionService.ts:798]: We should actually construct this manually; the class in extHostTypes is exposed to extensions and they won't throw this type of error.

```suggestion
			throw new RemoteAuthorityResolverError(`Not an authority that can be resolved!`, RemoteAuthorityResolverErrorCode.InvalidAuthority);
```

that's the reason it was done down below

File: src/vs/workbench/api/common/extHostExtensionService.ts [hunk 3]
```diff
@@ -862,7 +869,7 @@ export abstract class AbstractExtHostExtensionService extends Disposable impleme
 					performance.mark(`code/extHost/willResolveExecServer/${authorityPrefix}`);
 					execServer = await resolver.resolveExecServer?.(remoteAuthority, { resolveAttempt, execServer });
 					if (!execServer) {
-						throw new RemoteAuthorityResolverError(`Exec server was not available for ${remoteAuthority}`, RemoteAuthorityResolverErrorCode.NoResolverFound); // we did, in fact, break the chain :(
+						throw RemoteAuthorityResolverError.NoResolverFound(`Exec server was not available for ${remoteAuthority}`); // we did, in fact, break the chain :(
```
Comment (connor4312) [inline src/vs/workbench/api/common/extHostExtensionService.ts:872]: should be kept-as-is for ^

**Review by connor4312 — COMMENTED** [review]
one more change, looks good after that though

File: src/vs/workbench/api/common/extHostExtensionService.ts [hunk 4]
```diff
@@ -824,20 +825,26 @@ export abstract class AbstractExtHostExtensionService extends Disposable impleme
...
-				logInfo(`activating resolver...`);
-				const { resolver, authorityPrefix } = await this._activateAndGetResolver(remoteAuthority);
-				if (!resolver) {
-					logError(`no resolver`);
-					throw new RemoteAuthorityResolverError(`No remote extension installed to resolve ${authorityPrefix}.`, RemoteAuthorityResolverErrorCode.NoResolverFound);
-				}
-				return { resolver, authorityPrefix, remoteAuthority };
-			}));
+			resolvers = await Promise.all(chain.map(getResolver)).catch(async (e: Error) => {
+				if (e instanceof RemoteAuthorityResolverError && e._code !== RemoteAuthorityResolverErrorCode.InvalidAuthority) { throw e; }
```
Comment (connor4312) [inline src/vs/workbench/api/common/extHostExtensionService.ts:844]: This should be

```suggestion
				if (!(e instanceof RemoteAuthorityResolverError) || e._code !== RemoteAuthorityResolverErrorCode.InvalidAuthority) { throw e; }
```

**Review by connor4312 — APPROVED** [review]

**Comment by connor4312** [comment]
Thanks for the contribution!

**Review by Tyriar — APPROVED** [review]

**Comment by Perfecto1noly** [comment]
👌
