### PR TITLE
Fix editor tabs drag and drop

### LINKED ISSUE #243540: Drag placeholder from editor tabs has serif font
https://github.com/user-attachments/assets/73bfa409-3109-44ac-9327-5142669922a4

### PR DESCRIPTION
**Pull request by benibenj**
fixes https://github.com/microsoft/vscode/issues/243540

The drag image was being added to the dcument body and not the `monaco-workbench` dom element which is why it had none of the workbench styling. This also meant we have to add a z-index to make sure it renders on top. I checked with `list.css` and it picks `z-index: 1000` so I picked the same.

### CODE REVIEW

File: src/vs/base/browser/ui/list/listView.ts [hunk 1]
```diff
@@ -1198,7 +1198,7 @@ export class ListView<T> implements IListView<T> {
 				while (e && !e.classList.contains('monaco-workbench')) {
 					e = e.parentElement;
 				}
-				return e || this.domNode.ownerDocument;
+				return e || this.domNode.ownerDocument.body;
```
Comment (benibenj) [inline src/vs/base/browser/ui/list/listView.ts:1201]: @bpasero this seems to have been lost when adopting aux windows. Its not possible to add a DOM element to the document so this would probably throw if it were ever to happen.

Comment (bpasero) [reply src/vs/base/browser/ui/list/listView.ts:1201]: Yes indeed! Also found another instance:

https://github.com/microsoft/vscode/blob/069fb11cd79c04b956b2c41df9264a0658d37556/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L197-L202

**Review by bpasero — CHANGES_REQUESTED** [review]
Should we add a utility for this code that finds the root to attach to? Its repeated 3 times:

image

**Comment by benibenj** [comment]
I don't think we need utility for the finding of the root. I rather think list and breadcrumbs should be using `applyDragImage` from `dnd.ts`. I think this would help reduce duplicate code and make sure the styling also aligns which isn't the case currently. 
Do you agree?

**Comment by bpasero** [comment]
Yes 💯

File: src/vs/base/browser/ui/list/list.css [hunk 2]
```diff
@@ -68,6 +68,20 @@
...
+	outline-offset: -1px;
+
+	/*
+	 * Browsers apply an effect to the drag image when the div becomes too
+	 * large which makes them unreadable. Use max width so it does not happen
+	 */
+	max-width: 120px;
+	overflow: hidden;
+	text-overflow: ellipsis;
+	white-space: nowrap;
```
Comment (benibenj) [inline src/vs/base/browser/ui/list/list.css:84]: I'm not sure yet where `.monaco-drag-image` should live

File: src/vs/base/browser/ui/list/listWidget.ts [hunk 3]
```diff
@@ -899,14 +899,14 @@ export class DefaultStyleController implements IStyleController {
 
 		if (styles.listFocusAndSelectionBackground) {
 			content.push(`
-				.monaco-drag-image,
+				.monaco-drag-image${suffix},
```
Comment (bpasero) [inline src/vs/base/browser/ui/list/listWidget.ts:902]: Does `.monaco-drag-image` with a `suffix` make any difference? Whats the intent?

**Review by bpasero — CHANGES_REQUESTED** [review]

File: src/vs/base/browser/ui/list/listWidget.ts (hunk 3 above)
Comment (benibenj) [reply src/vs/base/browser/ui/list/listWidget.ts:902]: Each list has its own styles. explorer might have `listFocusAndSelectionBackground` set to red but outline could have `listFocusAndSelectionBackground` set to red. Suffix is needed to make sure the style applies only to that specific tree/list and not all (this was a bug before)

Comment (bpasero) [reply src/vs/base/browser/ui/list/listWidget.ts:902]: But does this work? I see it makes sense for `monaco-list`, but the drag image is root leveled and not within the suffix?

Comment (benibenj) [reply src/vs/base/browser/ui/list/listWidget.ts:902]: Yes, it works, I tested it. `applyDragImage` supports adding a extraClass to the dragImage. The listWidget uses this and adds its suffix so the styles will be applied correctly

**Review by bpasero — APPROVED** [review]
