### PR TITLE
fix frequent refresh of available profiles

### LINKED ISSUE #136509: Elements keep deselecting, shifting focus
Issue Type: <b>Bug</b>

Reproduction unsure, but sometimes, the active UI element keeps losing focus, making it sometimes impossible to do anything, like adding a config item via text input.
See video attached:
https://user-images.githubusercontent.com/13470026/140500990-0ad7bed9-230e-4b35-971e-0688c2335db9.mp4

Disabling extensions did not help.

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor              (6 x 3490)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>

webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (20.12GB free)|
|Process Argv|--crash-reporter-id 143bf0e7-84bd-4340-b6a3-b569938d752e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-export|asl|1.2.0
code-gnu-global|aus|0.2.2
vscode-icontheme-nomo-dark|be5|1.3.6
working-sets|ber|1.4.0
jshint|dba|0.11.0
vscode-eslint|dba|2.2.2
open-files|Div|0.0.4
file-icons|fil|1.0.29
csharp|ms-|1.23.16
brackets-keybindings|ms-|0.1.1
cpptools|ms-|1.7.1
vscode-opened-editors|Nic|0.1.2
prettier-now|rem|1.4.9
tabster|rib|0.0.6
reopenclosedtab|uyi|1.1.0
vscode-backup|Wes|0.0.6

</details>

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #136509

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts [hunk 1]
```diff
@@ -60,21 +59,25 @@ export class TerminalProfileService implements ITerminalProfileService {
 		// that contributes a profile
 		this._extensionService.onDidChangeExtensions(() => this.refreshAvailableProfiles());
 
-		this._configurationService.onDidChangeConfiguration(async e => {
-			const platformKey = await this.getPlatformKey();
-			if (e.affectsConfiguration(TerminalSettingPrefix.DefaultProfile + platformKey) ||
-				e.affectsConfiguration(TerminalSettingPrefix.Profiles + platformKey) ||
-				e.affectsConfiguration(TerminalSettingId.UseWslProfiles)) {
-				this.refreshAvailableProfiles();
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts:68]: `affectsConfiguration` wasn't working as expected. even when `e.affectedKeys` were totally unrelated to the terminal/profiles, it was entering this statement and refreshing the available profiles

File: src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts [hunk 2]
```diff
@@ -41,7 +41,6 @@ export class TerminalProfileService implements ITerminalProfileService {
 
 	get profilesReady(): Promise<void> { return this._profilesReadyBarrier.wait().then(() => { }); }
 	get availableProfiles(): ITerminalProfile[] {
-		this.refreshAvailableProfiles();
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts:44]: this was another issue

File: src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts [hunk 3]
```diff
@@ -60,21 +59,25 @@ export class TerminalProfileService implements ITerminalProfileService {
...
 		// Wait up to 5 seconds for profiles to be ready so it's assured that we know the actual
 		// default terminal before launching the first terminal. This isn't expected to ever take
 		// this long.
 		this._profilesReadyBarrier = new AutoOpenBarrier(5000);
 		this.refreshAvailableProfiles();
+		this._setupConfigListener();
+	}
+
+	private async _setupConfigListener(): Promise<void> {
+		const platformKey = await this.getPlatformKey();
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts:73]: we don't want to await the platform key every time config changes

**Comment by meganrogge** [comment]
to test, have this as your settings:
```
{
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell",
            "args": [
                "powershell -NoLogo -NoExit -ExecutionPolicy ByPass -Command ${env:USERPROFILE}\\Miniconda3\\shell\\condabin\\conda-hook.ps1"
            ]
        },
    },
    "terminal.integrated.defaultProfile.windows": "PowerShell"
}
```
go to the settings UI and try to add an item to files/exclude - every 2 seconds it will shut that input box.

File: src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts:68]: investigating why that is

File: src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts (hunk 2 above)
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts:44]: this was causing issues as well. @Tyriar know why this was added?
