### PR TITLE
Workaround for #16909

### LINKED ISSUE #16909: [regression] TypeScript word highlighter (provideDocumentHighlights) now highlights entire strings
* open vscode repo on `cursor.test.ts`
* click inside a test name

### Stable behaviour (expected): No highlights for strings
image

### Insiders behaviour (unexpected): Highlights entire string
image

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #16909

Workaround TS2.1+ returning strings in the `occurrences` response we use for highlighting symbol occurrences in a document

The workaround is to look at the text surrounding the first occurrence to see if it is a string literal.

### CODE REVIEW

File: extensions/typescript/src/features/documentHighlightProvider.ts [hunk 1]
```diff
@@ -34,7 +34,18 @@ export default class TypeScriptDocumentHighlightProvider implements DocumentHigh
 		}
 		return this.client.execute('occurrences', args, token).then((response): DocumentHighlight[] => {
 			let data = response.body;
-			if (data) {
+			if (data && data.length) {
```
Comment (mjbvz) [inline extensions/typescript/src/features/documentHighlightProvider.ts]: We may also want to scope to using the TypeScript version just to be safe. That way if something does go terribly wrong, users could point to their own ts install as a workaround.
