### PR TITLE
fix #191374

### LINKED ISSUE #191374: Windows: unsafe usages of `.fsPath` with `URI` that are not `file:` scheme
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.81.1
- OS Version:  server 2022

Steps to Reproduce:

1. This is a system install.  Users login using redirected appdata folders
2.  launch code with appdata redirected to a unc path or can launch 'code --user-data-dir \\server\share$\code'
3. Get error Unable to write program user data , code trying to write to c:\share$
4.  Users do not have access to write to c:\
5. If grant full control to root of C:\  and launch code a new folder is created c:\share$
6. New file created c:\share$\code\User\globalStorage\state.vscdb is created and code launches
7.  state.vscdb does not use the unc path while all other files are written to \\server\share$\code
8. Works fine with version 1.79.2

### PR DESCRIPTION
**Pull request by sandy081**
fix #191374

### CODE REVIEW

File: src/vs/platform/environment/electron-main/environmentMainService.ts [hunk 1]
```diff
@@ -68,6 +69,9 @@ export class EnvironmentMainService extends NativeEnvironmentService implements
 	@memoize
 	get useCodeCache(): boolean { return !!this.codeCachePath; }
 
+	@memoize
+	override get userRoamingDataHome(): URI { return this.appSettingsHome; }
```
Comment (bpasero) [inline src/vs/platform/environment/electron-main/environmentMainService.ts:73]: @sandy081 its a bit hard for me to understand the consequences. Is it that this would essentially put profiles under the `file` scheme here:

https://github.com/microsoft/vscode/blob/0e638c988a64a9d68d78027621ccfbe5ca680977/src/vs/platform/userDataProfile/common/userDataProfile.ts#L218

And thus help for the global storage path here:

https://github.com/microsoft/vscode/blob/0e638c988a64a9d68d78027621ccfbe5ca680977/src/vs/platform/userDataProfile/common/userDataProfile.ts#L45

But would it have side effects other than that? Is there a file system provider in `electron-main` for `vscode-userdata` that behaves different than `file` scheme? Or do we have code that probes on file scheme to make certain assumptions now?

**Review by bpasero — CHANGES_REQUESTED** [review]

**Review by bpasero — APPROVED** [review]
