### PR TITLE
mcp: add lenses to control server state from mcp config, inputs

### LINKED ISSUE #243526: Server fails completey silently when mcp.json entry uses ${workspaceFolder}
@digitarald: STR: Add mcp for memory tool

```
    "Memory": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-memory"],
      "env": {
        "MEMORY_FILE_PATH": "${workspaceFolder}/.vscode/memory.json"
      }
    },
```

🐛 Server Start/Output is a noop without any UI feedback.

DevTools:

```
Variable ${workspaceFolder} can not be resolved. Please open a folder.: CodeExpectedError: Variable ${workspaceFolder} can not be resolved. Please open a folder.
    at u (
```

### LINKED ISSUE #243613: MCP server inputs keep getting re-prompted
I have several tools with API keys, and keep getting prompts for the same key between sessions.

For API keys this means I have to go back into some far away API settings pages, where some can be re-copied, while others can't be read again after they got created. 

Can we clarify/simplify the heuristics for how long those inputs are stored and when they are removed, optimizing for prompting less

### LINKED ISSUE #243875: `inputs` does not work in user-level MCP setting
1. Define a user-level mcp setup with inputs
2. Launching gets an error `Variable 'githubpat' must be defined in an 'inputs' section of the debug or task configuration.: Error: Variable 'githubpat' must be defined in an 'inputs' section of the debug or task configuration`

### PR DESCRIPTION
**Pull request by connor4312**
image

Closes https://github.com/microsoft/vscode/issues/243875
Closes https://github.com/microsoft/vscode/issues/243613
Closes https://github.com/microsoft/vscode/issues/243526

### CODE REVIEW

File: src/vs/base/common/htmlContent.ts [hunk 1]
```diff
@@ -201,3 +202,13 @@ export function parseHrefAndDimensions(href: string): { href: string; dimensions
...
 }
+
+export function markdownCommandLink(command: { title: string; id: string; arguments?: unknown[] }): string {
+	const uri = URI.from({
+		scheme: Schemas.command,
+		path: command.id,
+		query: command.arguments?.length ? encodeURIComponent(JSON.stringify(command.arguments)) : undefined,
+	}).toString();
+
+	return `[${command.title}](${uri})`;
```
Comment (mjbvz) [inline src/vs/base/common/htmlContent.ts:213]: Just to be safe, you may want to escape the `title` using `escapeMarkdownSyntaxTokens`

File: src/vs/workbench/contrib/mcp/browser/mcpCommands.ts [hunk 2]
```diff
@@ -412,3 +414,93 @@ export class AddConfigurationAction extends Action2 {
...
+
+	async run(accessor: ServicesAccessor, serverId: string) {
+		const s = accessor.get(IMcpService).servers.get().find(s => s.definition.id === serverId);
+		await s?.stop();
+		await s?.start();
+	}
+}
+
+export class StopServer extends Action2 {
+	static readonly ID = 'workbench.mcp.StopServer';
```
Comment (mjbvz) [inline src/vs/workbench/contrib/mcp/browser/mcpCommands.ts:491]:
```suggestion
	static readonly ID = 'workbench.mcp.stopServer';
```

File: src/vs/workbench/contrib/mcp/browser/mcpLanguageFeatures.ts [hunk 3]
```diff
@@ -0,0 +1,266 @@
...
+import { localize } from '../../../../nls.js';
+import { IWorkbenchContribution } from '../../../common/contributions.js';
+import { ConfigurationResolverExpression, IResolvedValue } from '../../../services/configurationResolver/common/configurationResolverExpression.js';
+import { IMcpConfigPathsService } from '../common/mcpConfigPathsService.js';
+import { IMcpRegistry } from '../common/mcpRegistryTypes.js';
+import { IMcpService, McpConnectionState } from '../common/mcpTypes.js';
+import { EditStoredInput, RemoveStoredInput, ShowOutput, StartServer, StopServer } from './mcpCommands.js';
+
+export class McpLanguageFeatures extends Disposable implements IWorkbenchContribution {
+	private readonly _cachedMcpSection = new MutableDisposable<{ model: ITextModel; node: Node } & IDisposable>();
```
Comment (mjbvz) [inline src/vs/workbench/contrib/mcp/browser/mcpLanguageFeatures.ts:25]:
```suggestion
	private readonly _cachedMcpSection = this._register(new MutableDisposable<{ model: ITextModel; node: Node } & IDisposable>());
```

**Review by mjbvz — DISMISSED** [review]

**Review by rebornix — APPROVED** [review]

**Comment by alexjalonso7777** [comment]
#244058
