### PR TITLE
Fixes #218254

### LINKED ISSUE #218254: Copying a PNG image from VSCode results in a different image.
Type: <b>Bug</b>

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.1
- OS Version: Windows NT x64 10.0.22631

Steps to Reproduce:

1. Place the two different images in the left and right panels.
image

2. Right-click to copy the left image.
image

3. However, the copied image is actually the one on the right. You can notice that after right-clicking, the window focuses on the right image.
image

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:01:24.262Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 6.5.0-41-generic
Remote OS version: Linux x64 6.5.0-26-generic
Remote OS version: Linux x64 5.4.0-177-generic
Remote OS version: Linux x64 6.5.0-26-generic
Remote OS version: Linux x64 5.4.0-177-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.70GB free)|
|Process Argv|--crash-reporter-id 0b846954-7f35-4b4c-9e5e-5cdc8b9df8e1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 100.74.107.43|
|OS|Linux x64 6.5.0-41-generic|
|CPUs|Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz (32 x 1000)|
|Memory (System)|62.44GB (46.62GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 100.89.17.128|
|OS|Linux x64 6.5.0-26-generic|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (32 x 4071)|
|Memory (System)|61.94GB (48.59GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 100.117.15.93|
|OS|Linux x64 5.4.0-177-generic|
|CPUs|AMD EPYC 7H12 64-Core Processor (16 x 0)|
|Memory (System)|15.62GB (7.00GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 100.89.17.128|
|OS|Linux x64 6.5.0-26-generic|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (32 x 3473)|
|Memory (System)|61.94GB (48.59GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 100.117.15.93|
|OS|Linux x64 5.4.0-177-generic|
|CPUs|AMD EPYC 7H12 64-Core Processor (16 x 0)|
|Memory (System)|15.62GB (7.00GB free)|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.9.0
doxdocgen|csc|1.4.0
dart-code|Dar|3.90.0
vscode-markdownlint|Dav|0.55.0
xml|Dot|2.5.1
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
json-tools|eri|1.0.2
code-runner|for|0.12.2
matlab|Gim|3.0.2
codespaces|Git|1.16.23
copilot|Git|1.207.0
copilot-chat|Git|0.16.1
path-autocomplete|ion|1.25.0
latex-workshop|Jam|10.0.0
cmake-language-support-vscode|jos|0.0.9
vsc-python-indent|Kev|1.18.0
vscode-fix-checksums|leh|1.1.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.29.1
vscode-dotnet-runtime|ms-|2.0.7
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.7.11591013
python|ms-|2024.9.2024062507
vscode-pylance|ms-|2024.6.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.369.0
remote-ssh|ms-|0.110.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
cmake-tools|ms-|1.18.42
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2024.2.2
remote-explorer|ms-|0.5.2024061309
remote-server|ms-|1.6.2024061709
resourcemonitor|mut|1.0.7
sqlite-viewer|qwt|0.5.8
java|red|1.31.0
vscode-sort-json|ric|1.20.0
partial-diff|ryu|1.4.3
markdown-preview-enhanced|shd|0.8.13
vscode-tailscale|Tai|1.0.0
pdf|tom|1.2.2
cmake|twx|0.0.17
jinja|who|0.0.8
material-theme|zhu|3.17.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
legacy_priority:31082724

```

</details>

### PR DESCRIPTION
**Pull request by Parasaran-Python**
Fixes #218254 

onDidShowContextMenu fires for every webview even though only one webview has the context menu visible, hence removed the onDidShow listener, sending the set-context-menu-visible event to the html on did-context-menu event so that the context-menu-visible class gets applied only to the webview that actually has the context menu visible

### CODE REVIEW

**Comment by Parasaran-Python** [comment]
@mjbvz could you please check and review this change 🙂

**Comment by Parasaran-Python** [comment]
(Fixes #218254)

**Comment by Parasaran-Python** [comment]
@mjbvz could you please take a look at this when you have a moment 🙂? Thank you! 🙂

File: src/vs/workbench/contrib/webview/browser/webviewElement.ts [hunk 1]
```diff
@@ -506,6 +505,10 @@ export class WebviewElement extends Disposable implements IWebview, WebviewFindD
 
 				this._messagePort = e.ports[0];
 				this._messagePort.onmessage = (e) => {
+					if (e.data.channel === 'did-context-menu') {
```
Comment (mjbvz) [inline src/vs/workbench/contrib/webview/browser/webviewElement.ts:508]: You can use the existing `did-context-menu` listener on line 246 for this

Comment (Parasaran-Python) [reply src/vs/workbench/contrib/webview/browser/webviewElement.ts:508]: Sure will check and update

Comment (Parasaran-Python) [reply src/vs/workbench/contrib/webview/browser/webviewElement.ts]: Done @mjbvz 🙂

**Review by mjbvz — APPROVED** [review]
Thanks!

**Review by Tyriar — APPROVED** [review]

**Review by rzhao271 — APPROVED** [review]
