### PR TITLE
Fixing incorrect color range calculation

### LINKED ISSUE #199900: Color picker is bugged, adding additional ) when choosing color
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 
1.84.2
- OS Version: 
Windows_NT x64 10.0.19045
Steps to Reproduce:

1.  Create any css file (or any file where you could open built in color picker)
2.  Write simple css similar to this:
```css
* {
   color: red;
}
```
3. When red box appear (color picker), choose any color desired color

Actual bug:
In some cases it does append additional `)` which is unnecessary.

### PR DESCRIPTION
**Pull request by aiday-mar**
Fixes https://github.com/microsoft/vscode/issues/199900

### CODE REVIEW

File: src/vs/editor/contrib/colorPicker/browser/colorHoverParticipant.ts [hunk 1]
```diff
@@ -225,28 +224,35 @@ function renderHoverParts(participant: ColorHoverParticipant | StandaloneColorPi
 }
 
 function _updateEditorModel(editor: ICodeEditor, range: Range, model: ColorPickerModel, context?: IEditorHoverRenderContext) {
+
+	const edit = model.presentation.textEdit;
+	const textEdits = [edit ?? { range, text: model.presentation.label, forceMoveMarkers: false }];
```
Comment (hediet) [inline src/vs/editor/contrib/colorPicker/browser/colorHoverParticipant.ts:229]: Warning, this could initialize `textEdits` to `[undefined]`!

**Review by hediet — CHANGES_REQUESTED** [review]

File: src/vs/editor/contrib/colorPicker/browser/colorHoverParticipant.ts [hunk 2]
```diff
@@ -225,28 +224,35 @@ function renderHoverParts(participant: ColorHoverParticipant | StandaloneColorPi
...
-			model.presentation.textEdit.range.startLineNumber,
-			model.presentation.textEdit.range.startColumn,
-			model.presentation.textEdit.range.endLineNumber,
-			model.presentation.textEdit.range.endColumn
+			startLineNumber,
+			startColumnNumber,
+			endLineNumber,
+			endColumnNumber
 		);
 		const trackedRange = editor.getModel()!._setTrackedRange(null, newRange, TrackedRangeStickiness.GrowsOnlyWhenTypingAfter);
```
Comment (hediet) [inline src/vs/editor/contrib/colorPicker/browser/colorHoverParticipant.ts:251]: I don't know what _setTrackedRange does, but it could be an issue that the edits are now applied before this call and not afterwards.

**Review by hediet — APPROVED** [review]
