### PR TITLE
Fix terminal quick fix bugs

### LINKED ISSUE #211857: Sometimes quick fixes don't work in the terminal on macOS
I see this happen quite often where I push but don't get the quick fix:

Screenshot 2024-05-02 at 10 46 29 AM

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #211857

Previously, both the **Create PR** and **Push Upstream** terminal quick fixes required the command line to match a specific regex:

https://github.com/microsoft/vscode/blob/7de10c33ba1ff24e9787e3f80bf3fc3e211ef766/src/vs/workbench/contrib/terminalContrib/quickFix/browser/terminalQuickFixBuiltinActions.ts#L12

However, in certain cases, the captured `commandLine` was incorrectly set to `gitpush` instead of `git push`. This occurred when the user entered `git` and `push` on separate lines — such as when a command wrapped due to line length.

Wrapped command

During the `execute` phase, the command was correctly recognized. But by the `finished` phase, the space had been lost, breaking the match:

Incorrect by finished

The issue was caused by trimming whitespace **before** combining wrapped lines — which removed the space between command parts. 

Daniel suggested instead of changing that logic, we replace it and use the `promptInputModel.value` instead which does not have this issue. 

Working case

### CODE REVIEW

**Review by Tyriar — COMMENTED** [review]
The trim there was intentional I believe to combating potential whitespace cells that are left around from previous renders on that line. For example if when you backspace on a shell, it prints the space character instead of actually clearing it.

What this is doing is very similar to prompt input model, I wonder if we could leverage that logic here instead of doing it manually? PromptInputModel is owned by CommandDetectionCapability, so it might just be a matter of using `PromptInputModel.value` instead (removing ghost text is ghostTextIndex is !== -1).

**Comment by meganrogge** [comment]
test

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 1]
```diff
@@ -540,24 +540,7 @@ class UnixPtyHeuristics extends Disposable {
...
-					currentCommand.command += '\n';
-				}
-				const startColumn = continuation?.end ?? 0;
-				currentCommand.command += line.translateToString(true, startColumn);
-			}
-		}
-		if (y === commandExecutedLine) {
-			currentCommand.command += this._terminal.buffer.active.getLine(commandExecutedLine)?.translateToString(true, undefined, currentCommand.commandExecutedX) || '';
-		}
+		currentCommand.command = this._capability.promptInputModel.ghostTextIndex > -1 ? this._capability.promptInputModel.value.substring(0, this._capability.promptInputModel.ghostTextIndex) : this._capability.promptInputModel.value;
```
Comment (rzhao271) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:543]: Confirming that if ghostTextIndex is 0, currentCommand.command is an empty string?

Comment (meganrogge) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:543]: Yes 👍

**Review by rzhao271 — APPROVED** [review]

**Comment by meganrogge** [comment]
This was supposed to be merged in May... my bad for leaving auto-merge enabled on it. It's probably fine.
