### PR TITLE
fix problems with html style comments in embedded code

### LINKED ISSUE #47448: [html] problems with html style comments in embedded code
Issue Type: <b>Bug</b>

I have some computer generated HTML with some inline javascript and within the javascript, the code has generated HTML style comments, if I then format the file using Format Document (Shift+Alt+F) the formatter adds a space between the < and ! causing the file to error when attempting to load in a browser. I understand if you don't fix this as really you shouldn't use HTML style comments in your javascript. I have attached 2 files, one before and one after formatting, of a trivial example case. (rename these to .html)
[Issue Broken.txt](https://github.com/Microsoft/vscode/files/1888001/Issue.Broken.txt)
[Issue Working.txt](https://github.com/Microsoft/vscode/files/1888002/Issue.Working.txt)

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3100)|
|Memory (System)|15.94GB (6.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\Jack\Desktop\PUBGAPI|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gotemplate|cas|0.2.0
Go|luk|0.6.78
python|ms-|2018.3.1

</details>

### PR DESCRIPTION
**Pull request by w1redch4d**
Fixes #47448

### CODE REVIEW

File: extensions/html-language-features/server/src/modes/javascriptMode.ts [hunk 1]
```diff
@@ -41,7 +41,12 @@ function getLanguageServiceHost(scriptKind: ts.ScriptKind) {
 			getScriptSnapshot: (fileName: string) => {
 				let text = '';
 				if (fileName === currentTextDocument.uri) {
-					text = currentTextDocument.getText();
+					if (fileName.endsWith('html')) {
+						text = currentTextDocument.getText().replace(`<!--`, `/*`).replace(`-->`, `*/`);
```
Comment (aeschli) [inline extensions/html-language-features/server/src/modes/javascriptMode.ts:45]: The replacement should have the same amount of chatacters, so that all offsets stay the same.
-> `/* ` instead of `/* `

**Review by aeschli — CHANGES_REQUESTED** [review]
Can you add a test case to https://github.com/microsoft/vscode/blob/4b54ea927a64c9bd3e6d164edc7e021ca93dafcc/extensions/html-language-features/server/src/test/embedded.test.ts#L120 ?

File: extensions/html-language-features/server/src/modes/javascriptMode.ts (hunk 1 above)
Comment (UwUeeb) [reply extensions/html-language-features/server/src/modes/javascriptMode.ts]: > Can you add a test case to
> 
> https://github.com/microsoft/vscode/blob/4b54ea927a64c9bd3e6d164edc7e021ca93dafcc/extensions/html-language-features/server/src/test/embedded.test.ts#L120
> ?

sure working on it

**Comment by UwUeeb** [comment]
PTAL!

File: extensions/html-language-features/server/src/modes/javascriptMode.ts (hunk 1 above)
Comment (aeschli) [reply extensions/html-language-features/server/src/modes/javascriptMode.ts]: Thanks, pleaese add also one with some JavaScript code before and after it.

Comment (UwUeeb) [reply extensions/html-language-features/server/src/modes/javascriptMode.ts]: check the new commits, will that work?

**Comment by w1redch4d** [comment]
any progress on this?

**Review by dbaeumer — APPROVED** [review]

**Review by aeschli — APPROVED** [review]

**Comment by aeschli** [comment]
@w1redch4d Looks like the CLA bot is still not happy, can you add a comment with
```
@microsoft-github-policy-service agree [company="{your company}"]
```
to get the PR merged?

**Comment by w1redch4d** [comment]
@aeschli  what if i dont work for any company?, im currently a student

**Comment by aeschli** [comment]
@w1redch4d If you work just on your behalf, then you can skip the company part and accept the Contributor License Agreement by replying
```
@microsoft-github-policy-service agree
```

**Comment by w1redch4d** [comment]
> @w1redch4d please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree
