### PR TITLE
fix #62112 - merge overlapping delete operations

### LINKED ISSUE #62112: Delete line does not work properly when multiple cursors are on line
Issue Type: <b>Bug</b>

1. For a text file:

```
a
foo boo
too
c
```

2. Create a cursor after each `foo`, `boo`, and `too`:

```
a
foo| boo|
too|
c
```

3. Now run the `delete line` command

**Expected**

```
a
c
```

**actual**

```
a
too
c
```

VS Code version: code-oss-dev 1.29.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.54GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|22%|

</details>

### PR DESCRIPTION
**Pull request by YisraelV**
There are more details at the issue #62112 page

### CODE REVIEW

File: src/vs/editor/contrib/linesOperations/linesOperations.ts [hunk 1]
```diff
@@ -316,13 +316,13 @@ class DeleteLinesAction extends EditorAction {
...
-		// Merge delete operations on consecutive lines
+		// Merge delete operations which are adjacent or overlapping
 		let mergedOperations: IDeleteLinesOperation[] = [];
 		let previousOperation = operations[0];
 		for (let i = 1; i < operations.length; i++) {
-			if (previousOperation.endLineNumber + 1 === operations[i].startLineNumber) {
+			if (previousOperation.endLineNumber + 1 >= operations[i].startLineNumber) {
 				// Merge current operations into the previous one
-				previousOperation.endLineNumber = operations[i].endLineNumber;
+				previousOperation.endLineNumber = Math.max(previousOperation.endLineNumber, operations[i].endLineNumber);
```
Comment (YisraelV) [inline src/vs/editor/contrib/linesOperations/linesOperations.ts]: Math.max is needed in case the first operation is a subset of the second operation. This can actually happen I checked.

**Comment by YisraelV** [comment]
I could write unit tests for the function _getLinesToRemove if that's advisable. If I do I think it would be better for the signature to be _getLinesToRemove(selections: Selection[]) so that we don't have to mock the editor. 

Please tell me if I should do that and if yes if I should add it to this pull request.
