### PR TITLE
prevent exception during notebook toolbar layout call

### LINKED ISSUE #186394: `NotebookEditor.layout()` throws:  TypeError: Cannot read properties of undefined (reading 'size')
Testing #186191

1. Open a foo.py file
2. Shift+enter to run cell in interactive window
3. Reload window
4. Have GitHub Copilot classic installed and signed in
5. Type something into the input box and ctrl+enter, this opens a third editor group with multiple synthesized Copilot solutions (feature from GitHub Copilot)
6. Immediately close that editor
7. :bug: now there is an empty third editor group which really shouldn't happen AFAIK, also there is screen cheese, it shouldn't really be possible for Copilot to cause this kind of layout issue

image

image

### PR DESCRIPTION
**Pull request by amunger**
fixes https://github.com/microsoft/vscode/issues/186394

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/browser/viewParts/notebookEditorToolbar.ts [hunk 1]
```diff
@@ -645,15 +645,17 @@ function actionOverflowHelper(initialPrimaryActions: IActionModel[], initialSeco
...
 
-	for (let i = (renderActions.length - 1); i !== 0; i--) {
-		const temp = renderActions[i];
-		if (temp.size === 0) {
-			continue;
-		}
-		if (temp.action instanceof Separator) {
-			renderActions.splice(i, 1);
+	if (renderActions.length) {
+		for (let i = (renderActions.length - 1); i !== 0; i--) {
```
Comment (rebornix) [inline src/vs/workbench/contrib/notebook/browser/viewParts/notebookEditorToolbar.ts:649]: I think the reason we ran into this bug in the first place is we are checking `!== 0`, instead we should check `> 0`

Comment (amunger) [reply src/vs/workbench/contrib/notebook/browser/viewParts/notebookEditorToolbar.ts]: yeah good point

**Review by rebornix — APPROVED** [review]
