### PR TITLE
Adjust heuristic for preferring 2 over 4 for indentation size

### LINKED ISSUE #249040: Unexpected 2-spaces indent detection despite of predominant 4-spaces usage
- VS Code Version: 1.95
- OS Version: Linux x64 5.15.0-139-generic

When _Editor: Detect Indentation_ is enabled and there are some areas indented using 2 spaces, VSCode detects a 2-space indentation even when the file is mostly indented with 4 spaces.

Image

This doesn't happen for other pairs of values such as {3, 6} or {4,8}.
Is there any reason for choosing 2 spaces over 4? Why does this happen only for the {2, 4} pair?

### PR DESCRIPTION
**Pull request by dmitrivMS**
Fixes #249040

The heuristic was added by @alexdima to fix issue #65668 where we were detecting indent in YAML incorrectly (because YAML indent skips `- ` portion). However, that change also broke detection in non-list based languages.

This change adjusts the heuristic to be less aggressive.
Added tests for both issues to ensure there is no regression.

### CODE REVIEW

File: src/vs/editor/common/model/indentationGuesser.ts [hunk 1]
```diff
@@ -192,10 +192,7 @@ export function guessIndentation(source: ITextBuffer, defaultTabSize: number, de
 
 	// Guess tabSize only if inserting spaces...
 	if (insertSpaces) {
-		let tabSizeScore = (insertSpaces ? 0 : 0.1 * linesCount);
-
-		// console.log("score threshold: " + tabSizeScore);
-
+		let tabSizeScore = 0;
```
Comment (aiday-mar) [inline src/vs/editor/common/model/indentationGuesser.ts:195]: Hi could you please describe why you changed this line?

Comment (dmitrivMS) [reply src/vs/editor/common/model/indentationGuesser.ts:195]: At this point `insertSpaces` is `true` due to the `if` statement above, so the conditional always evaluates to `0`.

Comment (aiday-mar) [reply src/vs/editor/common/model/indentationGuesser.ts:195]: I see yes

**Review by aiday-mar — APPROVED** [review]
