### PR TITLE
Fixes #95040

### LINKED ISSUE #95040: git merge conflict support detects wrong ======= break
Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:
Markdown files which use ==== to indicate titles cause vscode to detect the markdown markup, rather than the git merge conflict separator as the break for the merge. 

image
In this example, vscode detected the blue group of equals signs as the separator between the merge conflicts. However, it should have used the later entry at the red arrow. 
Selecting the vscode option "Accept Current Change" would thus, only include a subset of the the current change, while selecting "Accept Incoming Change" would bring along some of the current change set. 

The detection of git merge should thus only look for exactly 7 equal signs followed by the end of line `^=======$`

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by Klagopsalmer**
This PR fixes #95040

Check that the merge conflict splitter line contains exactly 7 '=' characters to avoid detecting Markdown titles as splitter line.

### CODE REVIEW

File: extensions/merge-conflict/src/mergeConflictParser.ts [hunk 1]
```diff
@@ -58,7 +58,7 @@ export class MergeConflictParser {
 				currentConflict.commonAncestors.push(line);
 			}
 			// Are we within a conflict block and is this a splitter? =======
-			else if (currentConflict && !currentConflict.splitter && line.text.startsWith(splitterMarker)) {
+			else if (currentConflict && !currentConflict.splitter && line.text.match(splitterMarkerRegex)) {
```
Comment (gjsjohnmurray) [inline extensions/merge-conflict/src/mergeConflictParser.ts:61]: Why are you using a regex rather than a simple equality test?

Comment (Klagopsalmer) [reply extensions/merge-conflict/src/mergeConflictParser.ts]: You are right. Comment in #95040 led me to think that a regex was required to ensure correct line ending detection.

**Comment by chrmarti** [comment]
Thanks!
