### PR TITLE
terminal profile fixes

### LINKED ISSUE #119141: Remember workspace profile permissions choice

### LINKED ISSUE #119200: $getAvailableProfiles exception
Seeing this in Insiders when I create a terminal:

```
ERR NotSupported: Error: NotSupported
	at u.$getAvailableProfiles (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:79:42536)
	at u._doInvokeHandler (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:79:77970)
	at u._invokeHandler (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:79:77654)
	at u._receiveRequest (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:79:76321)
	at u._receiveOneMessage (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:79:75107)
	at file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:79:73208
	at v.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:57:1836)
	at MessagePort.m.port1.onmessage (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:87:3503)
```

It's probably because we're allowing requests go through to non-primary extension hosts (like the web worker ext host).

### LINKED ISSUE #119275: Tweak detectWslProfiles setting
We always want to detect, but not always show them in the quick launch. Let's tweak behavior and update the setting name

### LINKED ISSUE #119277: Dedupe auto detected profiles
If there are multiple paths registered for a shell in `/etc/shells` they come up as separate profiles, we should pick only one (whichever is the default? maybe the last? should see if we can find what is meant to be the primary one)

image

### LINKED ISSUE #119283: JS debug terminal broke when we merged in quick profiles
recording (1)

fyi @connor4312

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #119200
fixes #119275 
fixes #119277
fixes #119283
fixes #119141

### CODE REVIEW

**Comment by meganrogge** [comment]
Perhaps just path (and args?) should be considered as the key for workspace permissions - I don't think changing the name of a profile is risky.

File: src/vs/workbench/api/browser/mainThreadTerminalService.ts [hunk 1]
```diff
@@ -350,7 +354,7 @@ export class MainThreadTerminalService implements MainThreadTerminalServiceShape
 	}
 
 	private async _onRequestAvailableProfiles(req: IAvailableProfilesRequest): Promise<void> {
-		if (this._isPrimaryExtHost()) {
+		if (this._isPrimaryExtHost() && this._extHostKind !== ExtensionHostKind.LocalWebWorker) {
```
Comment (meganrogge) [inline src/vs/workbench/api/browser/mainThreadTerminalService.ts:357]: do we want to return `this._extHostKind !== ExtensionHostKind.LocalWebWorker` instead of true from `this._isPrimaryExtHost()`?

Comment (Tyriar) [reply src/vs/workbench/api/browser/mainThreadTerminalService.ts:357]: Yes this should go inside `_isPrimaryExtHost` as it probably represents another bug. This is also why we returned `''` in these 2 spots instead of throwing which makes more sense:

https://github.com/microsoft/vscode/blob/3fd2415c9f74eaa82079c2fd1292d7d18341ac3d/src/vs/workbench/api/common/extHostTerminalService.ts#L773-L776

https://github.com/microsoft/vscode/blob/3fd2415c9f74eaa82079c2fd1292d7d18341ac3d/src/vs/workbench/api/common/extHostTerminalService.ts#L790-L792

Comment (Tyriar) [reply src/vs/workbench/api/browser/mainThreadTerminalService.ts:357]: Let's do in debt week https://github.com/microsoft/vscode/issues/119322

File: src/vs/workbench/contrib/terminal/common/terminal.ts [hunk 2]
```diff
@@ -102,7 +102,7 @@ export interface ITerminalConfiguration {
 		windows: string[];
 	};
 	profiles: ITerminalProfiles;
-	detectWslProfiles: boolean;
+	quickLaunchWslProfiles: boolean;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/terminal.ts:105]: It's getting long, but maybe `showQuickLaunchWslProfiles` is better as the name kind of looks like you would define profiles (instead of true/false).

File: src/vs/workbench/contrib/terminal/browser/terminalActions.ts [hunk 3]
```diff
@@ -1464,37 +1466,42 @@ export function registerTerminalActions() {
...
-								terminalService.setActiveInstance(instance);
-							}
-						},
-						{
-							label: 'Disallow',
-							run: () => {
-								const activeInstance = terminalService.getActiveInstance();
-								if (activeInstance) {
-									terminalService.setActiveInstance(activeInstance);
+					if (!storageService.getBoolean(`${QUICK_LAUNCH_PROFILE_CHOICE}-${item}-${launchConfig.path}`, StorageScope.WORKSPACE, false)) {
```
[the remark this answers is not in the document]
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalActions.ts:1479]: You might recall that I tried that originally and then we decided I should move it here.
