### PR TITLE
set findWidgetVisible for find using regex 

### LINKED ISSUE #127922: [Bug] Terminal find widget can't be hidden under a certain circumstance
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.57.1
- OS Version: Windows 10

Steps to Reproduce:

1. Focus integrated terminal.
2. Trigger `workbench.action.terminal.toggleFindRegex`, now this will show up:

   image

3. Trigger `workbench.action.terminal.hideFind`.
4. Terminal find widget can't be hidden.
5. Change `workbench.action.terminal.hideFind` `when` from `terminalFindVisible && terminalFocus && terminalProcessSupported` to `terminalFocus && terminalProcessSupported`.
6. Repeat step 1 to step 4.
7. Terminal find widget will be hidden.

### LINKED ISSUE #128152: toggle find commands do not work in terminal editors

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #127922
fixes #128152

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalGroupService.ts [hunk 1]
```diff
@@ -191,6 +191,7 @@ export class TerminalGroupService extends Disposable implements ITerminalGroupSe
 	}
 
 	getFindState(): FindReplaceState {
+		KEYBINDING_CONTEXT_TERMINAL_FIND_VISIBLE.bindTo(this._contextKeyService).set(true);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalGroupService.ts:194]: Can this be controlled by whatever handles showing/hiding of the find widget instead?

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalGroupService.ts:194]: that would be `focusFindWidget`, which I thought we were trying to avoid

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalGroupService.ts:194]: That's only when it gets focus isn't it? We need to differentiate these 2 contexts:

```
	FindVisible = 'terminalFindVisible',
	FindFocused = 'terminalFindFocused',
```
