### PR TITLE
dirty diff: use IEditorGroupsService instead of IEditorService

### LINKED ISSUE #163499: Switching tabs resolves `git:/...` URLs everytime even when nothing changed
Does this issue occur when all extensions are disabled?: Yes (?) I test it in the docker container 

- VS Code Version: 
- OS Version: OSS (?)

Steps to Reproduce:

1. Load a project from a Github repository
2. Open two files from the file explorer (generating two tabs)
3. Put a breakpoint at the function resolveFromFile 
4. Focus on another tab
5. Check with the debugger what this function does. The file focused will be reloaded every time. In case it is a large file it won't be due to a final check in the code but this does not seem the right behavior. I think it should not attempt to reload  every time and even if it is a large file maybe it should reload if it has been modified (maybe disabling controls and showing a popup while it does)

It seems that the problem is in the lastResolvedFileStat: it is reset or not updated at some point. 
This is where the check fails:

```
// Decide on etag
let etag: string | undefined;
if (forceReadFromFile) {
	etag = ETAG_DISABLED; // disable ETag if we enforce to read from disk
} else if (this.lastResolvedFileStat) {
	etag = this.lastResolvedFileStat.etag; // otherwise respect etag to support caching
}

```
_File /workspaces/vscode/src/vs/workbench/services/textfile/common/textFileEditorModel.ts , line 419_

**EDIT: The problem seems to happen only when using a git repository. Looks like TextFileEditorModelManage.doResolve receives "git:file_uri" while it has only registered "file:file_uri" and therefore every time onEditorsChanged is fired it generates a new instance of TextFileEditorModel which consequently has no lastResolvedFileStat**

I'd like to try to fix it myself and make a pull request if I am confirmed that this is an issue and you don't have any objection.

### PR DESCRIPTION
**Pull request by joaomoreno**
also, do not dispose DirtyDiffItem of non-active tabs
fixes #163499

### CODE REVIEW

File: src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts [hunk 1]
```diff
@@ -1345,7 +1350,7 @@ export class DirtyDiffWorkbenchController extends Disposable implements ext.IWor
 
 	private enabled = false;
 	private viewState: IViewState = { width: 3, visibility: 'always' };
-	private items = new Map<IResolvedTextFileEditorModel, DirtyDiffItem>();
+	private items = new ResourceMap<DirtyDiffItem>();
```
Comment (bpasero) [inline src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts:1353]:
```suggestion
	private readonly items = new ResourceMap<DirtyDiffItem>();
```

**Review by bpasero — APPROVED** [review]
