### PR TITLE
Error in search input for spawn ripgrep ENOENT

### LINKED ISSUE #204011: Error in search input for spawn ripgrep ENOENT
Type: <b>Bug</b>

As I typed into the search input, nothing fancy:

`spawn /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg ENOENT`

See screenshot

image

VS Code version: Code - Insiders 1.87.0-insider (442c133fe92b5e2606c8242caae4e68938faccc7, 2024-02-01T09:55:21.613Z)
OS version: Darwin x64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (0.32GB free)|
|Process Argv|--log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
tsl-problem-matcher|amo|0.6.2
docs-view|bie|0.1.0
emojisense|bie|0.10.0
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.21.0
markdown-preview-github-styles|bie|2.0.3
markdown-yaml-preamble|bie|0.1.0
mermaid-markdown-syntax-highlighting|bpr|1.6.0
esbuild-problem-matchers|con|0.0.3
kusto|don|0.4.4
prettier-vscode|esb|10.1.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
codespaces|Git|1.16.9
copilot|Git|1.156.686
copilot-chat|Git|0.13.2024020102
remotehub|Git|0.63.2024010901
vscode-pull-request-github|Git|0.81.2024020111
cortex-debug|mar|1.12.1
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.25
peripheral-viewer|mcu|1.4.6
rtos-views|mcu|0.0.7
vscode-azureresourcegroups|ms-|0.8.3
vscode-dotnet-runtime|ms-|2.0.1
debugpy|ms-|2024.0.0
python|ms-|2023.25.10292213
vscode-pylance|ms-|2024.1.103
jupyter|ms-|2024.1.2024012502
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
remote-containers|ms-|0.339.0
remote-ssh|ms-|0.108.2024012417
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
anycode|ms-|0.0.72
azure-account|ms-|0.11.6
azure-repos|ms-|0.38.0
remote-repositories|ms-|0.40.0
remote-server|ms-|1.6.2024012309
vscode-github-issue-notebooks|ms-|0.0.130
vscode-markdown-notebook|ms-|0.0.26
vscode-selfhost-test-provider|ms-|0.3.25
vscode-speech|ms-|0.5.2024020116
vscode-typescript-next|ms-|5.4.20240124
prisma|Pri|5.9.1
vscode-xml|red|0.26.1
vscode-yaml|red|1.14.0
kuskus-kusto-syntax-highlighting|ros|1.2.0
svg-preview|Sim|2.8.3
rest-book|tan|6.2.1
pdf|tom|1.2.2
vscode-mdx|uni|1.7.0
volar|Vue|1.8.27
vscode-typescript-vue-plugin|Vue|1.8.27
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:30784851
vscaac:30438845
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialogc:30812479
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
8082a590:30953407
b1063948:30943794
fegfb526:30952798
7j2b6412:30951517
bg6jg535:30946824
ccp1r3:30950904

```

</details>

### PR DESCRIPTION
**Pull request by andreamah**
Fixes #204011

Temporary fix, will try to have a more complete fix connected to https://github.com/microsoft/vscode/issues/205044

### CODE REVIEW

File: src/vs/workbench/api/common/extHostNotebook.ts [hunk 1]
```diff
@@ -434,6 +434,12 @@ export class ExtHostNotebookController implements ExtHostNotebookShape {
 							}
 							finalMatchedTargets.add(uri);
 						});
+					}).catch(_err => {
+						// temporary fix for https://github.com/microsoft/vscode/issues/205044: don't show notebook results for remotehub repos.
```
Comment (amunger) [inline src/vs/workbench/api/common/extHostNotebook.ts:438]: it would be good to log a warning at least since this is swallowing and ignoring _all_ exceptions. Or just ignore the specific exception?

Comment (andreamah) [reply src/vs/workbench/api/common/extHostNotebook.ts:438]: Good point, I added a check and a warning log.

**Review by justschen — APPROVED** [review]
