### PR TITLE
fix: areLanguageDiagnosticSettingsEqual always return true

### LINKED ISSUE #125364: Changing any Settings will trigger the problems view  refresh
Issue Type: Performance Issue 

Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.56.2
- OS Version: Darwin x64 20.3.0

Steps to Reproduce:

1. Run `Run Dev` task in vscode repo.
2. Write some TypeScript/JavaScript wrong code. 
image
(https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/markers/browser/markersView.ts#L258)
3. Change any settings, `refreshPanel` always called.

markervView

only typescript/javascript file can reproduce this issue.

### PR DESCRIPTION
**Pull request by Aaaaash**
This PR fixes #125364

### CODE REVIEW

File: extensions/typescript-language-features/src/languageFeatures/diagnostics.ts [hunk 1]
```diff
@@ -95,8 +95,7 @@ interface LanguageDiagnosticSettings {
 }
 
 function areLanguageDiagnosticSettingsEqual(currentSettings: LanguageDiagnosticSettings, newSettings: LanguageDiagnosticSettings): boolean {
```
Comment (mjbvz) [inline extensions/typescript-language-features/src/languageFeatures/diagnostics.ts:97]: Instead of inverting the function, how about using `!areLanguageDiagnosticSettingsEqual` where it is called?

Comment (Aaaaash) [reply extensions/typescript-language-features/src/languageFeatures/diagnostics.ts]: Sounds like good

**Comment by mjbvz** [comment]
Thanks!
