### PR TITLE
Fix #selection in chat editor and new window

### LINKED ISSUE #248885: #selection attachment doesn't work in chat editor or new window
Oddly, editor service starts returning the right thing as soon as I stop at a breakpoint

Here I set a breakpoint in the `isCodeEditor` block.

https://github.com/user-attachments/assets/d2ecf7aa-b23a-42f8-b252-c551962b7955

Same behavior when debugging in devtools, but the runtime behavior when not hitting a breakpoint (activeTextEditorControl is undefined) seems wrong and is strange...

### PR DESCRIPTION
**Pull request by roblourens**
Fix #248885

### CODE REVIEW

File: src/vs/workbench/contrib/chat/browser/contrib/chatInputCompletions.ts [hunk 1]
```diff
@@ -591,6 +595,36 @@ class BuiltinDynamicCompletions extends Disposable {
...
+				return undefined;
+			}
+
+			if (model) {
+				return codeEditor;
+			}
+		}
+		for (const codeOrDiffEditor of this.editorService.getVisibleTextEditorControls(EditorsOrder.MOST_RECENTLY_ACTIVE)) {
+			let codeEditor: ICodeEditor;
+			if (isDiffEditor(codeOrDiffEditor)) {
```
Comment (bpasero) [inline src/vs/workbench/contrib/chat/browser/contrib/chatInputCompletions.ts:612]: fyi there is a utility method called `getCodeEditor` in `src/vs/editor/browser/editorBrowser.ts`

File: src/vs/workbench/contrib/chat/browser/contrib/chatInputCompletions.ts [hunk 2]
```diff
@@ -537,7 +541,7 @@ class BuiltinDynamicCompletions extends Disposable {
 				return;
 			}
 
-			const active = this.editorService.activeTextEditorControl;
+			const active = this.findActiveCodeEditor();
```
Comment (bpasero) [inline src/vs/workbench/contrib/chat/browser/contrib/chatInputCompletions.ts:544]: Curious: in what case did `activeTextEditorControl` not return a good result that makes you go via  `codeEditorService.getActiveCodeEditor`? Is it for floating windows?

**Review by bpasero — DISMISSED** [review]

File: src/vs/workbench/contrib/chat/browser/contrib/chatInputCompletions.ts (hunk 1 above)
Comment (roblourens) [reply src/vs/workbench/contrib/chat/browser/contrib/chatInputCompletions.ts:612]: Sure. This is your code from https://github.com/microsoft/vscode/blob/c2b5fd631b414873257c141f55bd3ffb56c38ebc/src/vs/workbench/contrib/chat/browser/contrib/chatImplicitContext.ts#L135 :)

**Review by meganrogge — APPROVED** [review]
