### PR TITLE
Delete vscode-typescript upon close of VS Code

### LINKED ISSUE #71577: vscode-tscancellation- files being created without limit.
- VSCode Version: 1.32.3
- OS Version: Windows 10

Steps to Reproduce:

1. Use VS Code with TypeScript for any amount of time
2. There is no step 2.

Does this issue occur when all extensions are disabled?: Yes/No
Seems to be caused by core TypeScript support.

OK so this has been reported before. #54671, #53423, #61935, #28970, probably more. I got bored of checking. Technically this report is a duplicate, but since the issue keeps getting ignored, here we all are.

Each time the report is closed, and we're told it's by design.

Well I'm telling you it's a terrible design. I mean, quite aside from the issue of using a file to signal that a request has been cancelled (surely there's some better IPC mechanism that could be used for that? A named pipe, an event, a signal, a socket, a domain socket, anything), there's the minor issue of VSCode never actually deleting the files.

@mjbvz seems to be of the [opinion](https://github.com/Microsoft/vscode/issues/53423#issuecomment-401842492) that the files will be cleaned up by the operating system. And that might be true on a Linux machine with files created under /tmp, because /tmp should get clobbered each time you reboot. It might even be true of macOS, I don't know.

What I do know is that it's not true of Windows. %temp% does not get clobbered automatically. A file that's created in %temp% is going to stay there until it's manually removed. It's true that the Disk Cleanup utility can remove some files from %temp% and can be scheduled, but typically nothing is ever removed from %temp% by the operating system. Applications are meant to tidy up after themselves. VSCode is failing to do so.

If VSCode were using raw win32 then the obvious answer would be to open the files with delete-on-close, so they'd get tidied up automatically. But I don't know if Electron apps have the ability to do that.

### PR DESCRIPTION
**Pull request by lramos15**
VS Code's typescript language services produces many temp files to handle cancellations which many users have complained about. This cleans up that temp folder upon exit of VS Code. Fixes #71577.

### CODE REVIEW

File: extensions/typescript-language-features/src/typescriptServiceClient.ts [hunk 1]
```diff
@@ -346,6 +348,7 @@ export default class TypeScriptServiceClient extends Disposable implements IType
 			}
 			this.serviceExited(!this.isRestarting);
 			this.isRestarting = false;
+			rimraf.sync(electron.getRootTempDir());
```
Comment (mjbvz) [inline extensions/typescript-language-features/src/typescriptServiceClient.ts]: This will be invoked when the server restarts, which I don't think is correct since there is only a single temp dir for the entire extension. You can test this using the `Restart TS Server` command with a js/ts file open. I believe it will error when it tries created a new cancellation file in the deleted temp dir

Two options:

* Create a temp dir for each server process
* Move the delete to the extension's deactivate method

Comment (lramos15) [reply extensions/typescript-language-features/src/typescriptServiceClient.ts]: I don't believe this will error since `getRootTempDir()` creates the directory if it does not exist. Therefore when it attempts to make a cancellation file it calls this function and then joins the path with the file name effectively preventing the directory from never not existing when being written to. I will test it out though just to be sure

Comment (mjbvz) [reply extensions/typescript-language-features/src/typescriptServiceClient.ts]: I would not rely on that behavior. That code was added to fix a bug: f264e8f33bfe5eebd3526844fa3519be88ea7a1a

The intent of this function is temp direction is created once and exists over the lifespan on the extension

Comment (lramos15) [reply extensions/typescript-language-features/src/typescriptServiceClient.ts]: Moved folder removal to deactivate method.

**Review by mjbvz — APPROVED** [review]
Looks good to me. If you've tested and the fix looks good, feel free to merge

As we discussed, this will not cleanup if there is a hard shutdown but those should be fairly uncommon. And, as the original issue mentions, having empty files in tmp does not really have much real world impact

File: extensions/typescript-language-features/package.json [hunk 2]
```diff
@@ -17,17 +17,20 @@
...
-    "@types/node": "8.0.33",
+    "@types/node": "^12.0.2",
     "@types/semver": "^5.5.0",
+    "@types/rimraf": "2.0.2",
     "vscode": "^1.1.10"
   },
   "scripts": {
-    "vscode:prepublish": "node ../../node_modules/gulp/bin/gulp.js --gulpfile ../../build/gulpfile.extensions.js compile-extension:typescript ./tsconfig.json"
+    "vscode:prepublish": "node ../../node_modules/gulp/bin/gulp.js --gulpfile ../../build/gulpfile.extensions.js compile-extension:typescript ./tsconfig.json",
+    "watch": "tsc --watch"
```
Comment (sbatten) [inline extensions/typescript-language-features/package.json]: we added this watch script but it should be removed

File: extensions/typescript-language-features/src/utils/electron.ts [hunk 3]
```diff
@@ -22,8 +22,21 @@ const getRootTempDir = (() => {
 	};
 })();
 
+export const getInstanceDir = (() => {
+	let dir: string | undefined;
+	return () => {
```
Comment (sbatten) [inline extensions/typescript-language-features/src/utils/electron.ts]: why does this return a function?

**Review by sbatten — CHANGES_REQUESTED** [review]

File: extensions/typescript-language-features/src/utils/electron.ts (hunk 3 above)
Comment (lramos15) [reply extensions/typescript-language-features/src/utils/electron.ts]: This is so that every time we call `getInstanceDir()` we do not reinitialize the dir variable after each run. The dir variable is initialized once upon self execution of the outside function and then isn't reinitialized on subsequent calls because the getInstanceDir only holds the returned function.

File: extensions/typescript-language-features/package.json (hunk 2 above)
Comment (lramos15) [reply extensions/typescript-language-features/package.json]: I forgot about this. I have removed it.

**Comment by sbatten** [comment]
looks good
