### PR TITLE
Pass along remote authority when opening window on folders with custom scheme

### LINKED ISSUE #110352: Opening a folder with custom scheme does not work (remote, desktop)
- VSCode Version: 1.51.0-insider
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36

Steps to Reproduce:

(Running an extension in Codespaces)

1. Execute this command to open a folder in the current window. The URI is from a [custom file system](https://github.com/microsoft/vscode-azurestorage/blob/4f15c16b60cdc9aff790343c4f69654a5e50d440/package.json#L34).
```typescript
await commands.executeCommand('vscode.openFolder', uri, false /* forceNewWindow */);
```
2. An error is thrown
Screen Shot 2020-11-10 at 1 18 26 PM

Hovering over the workspace folder shows this warning:
image

Clicking on the workspace folder throws this error:
image

Does this issue occur when all extensions are disabled?: N/A

### PR DESCRIPTION
**Pull request by aeschli**
Fixes #110352

When opening a folder or workspace with a schema that is not `file` or `vscode-remote` but from a file system provider, we must also pass along the `remoteAutority` of the current window. 
That way the new window will be opened on the same remote. The extension that provides the file system provider might only be installed on that remote.

The change also affects the recent history, as the `remoteAutority` also needs to be stored there.

There are also small changes to the Menu code as the open recent menu entries also need the `remoteAutority`.

### CODE REVIEW

File: src/vs/platform/windows/common/windows.ts [hunk 1]
```diff
@@ -19,6 +19,7 @@ export const WindowMinimumSize = {
 
 export interface IBaseOpenWindowsOptions {
 	readonly forceReuseWindow?: boolean;
+	readonly remoteAuthority?: string | null;  /* used when no inputs are provided or inputs are neither file nor vscode-remote. Null forces a local window */
```
Comment (bpasero) [inline src/vs/platform/windows/common/windows.ts:22]:
```suggestion
		/**
	 * Only used when a window is opened with either
	 * no workspace or with a workspace that is
	 * neither `file://` nor `vscode-remote://`
	 * protocol to indicate the remote authority
	 * that should be used.
	 *
	 * Use `null` to explicitly force a window without
	 * remote authority.
	 */
	readonly remoteAuthority?: string | null;
```

Comment (bpasero) [reply src/vs/platform/windows/common/windows.ts:22]: @aeschli comments like yours do not appear in our hovers, can you please makes sure to use JSDoc compliant comments for APIs, even if they are internal? I think otherwise people will not understand what the option is about since it has very specific behavour.

File: src/vs/platform/windows/electron-main/windows.ts [hunk 2]
```diff
@@ -197,6 +197,7 @@ export interface IOpenConfiguration extends IBaseOpenConfiguration {
 	readonly gotoLineMode?: boolean;
 	readonly initialStartup?: boolean;
 	readonly noRecentEntry?: boolean;
+	readonly remoteAuthority?: string; /* used when no inputs are provided or inputs are neither file nor vscode-remote */
```
Comment (bpasero) [inline src/vs/platform/windows/electron-main/windows.ts:200]:
```suggestion
		/**
	 * Only used when a window is opened with either
	 * no workspace or with a workspace that is
	 * neither `file://` nor `vscode-remote://`
	 * protocol to indicate the remote authority
	 * that should be used.
	 */
	readonly remoteAuthority?: string;
```

File: src/vs/platform/launch/electron-main/launchMainService.ts [hunk 3]
```diff
@@ -119,14 +119,16 @@ export class LaunchMainService implements ILaunchMainService {
...
 
 		// Special case extension development
 		if (!!args.extensionDevelopmentPath) {
-			this.windowsMainService.openExtensionDevelopmentHostWindow(args.extensionDevelopmentPath, { context, cli: args, userEnv, waitMarkerFileURI });
+			this.windowsMainService.openExtensionDevelopmentHostWindow(args.extensionDevelopmentPath, { context, cli: args, userEnv, waitMarkerFileURI, remoteAuthority });
 		}
 
 		// Start without file/folder arguments
 		else if (!args._.length && !args['folder-uri'] && !args['file-uri']) {
+
```
Comment (bpasero) [inline src/vs/platform/launch/electron-main/launchMainService.ts:131]: Extra newline

Comment (bpasero) [inline src/vs/platform/launch/electron-main/launchMainService.ts:131]: Extra newline

File: src/vs/workbench/api/common/apiCommands.ts [hunk 4]
```diff
@@ -32,7 +32,7 @@ function adjustHandler(handler: (executor: ICommandsExecutor, ...args: any[]) =>
 
 interface INewWindowAPICommandOptions {
 	reuseWindow?: boolean;
-	remoteAuthority?: string;
+	remoteAuthority?: string | null; /* allow null to force a local window */
```
Comment (bpasero) [inline src/vs/workbench/api/common/apiCommands.ts:35]: Again, JSDoc please and maybe copy the JSDoc from the internal API if it applies here.

File: src/vs/workbench/browser/actions/windowActions.ts [hunk 5]
```diff
@@ -343,7 +343,7 @@ export class NewWindowAction extends Action {
 	}
 
 	run(): Promise<void> {
-		return this.hostService.openWindow();
+		return this.hostService.openWindow({ remoteAuthority: null });
```
Comment (bpasero) [inline src/vs/workbench/browser/actions/windowActions.ts:346]: Why do we need to introduce `null` to enforce local remote authority? If I leave out `remoteAuthority`, shouldn't that be sufficient?

Comment (bpasero) [reply src/vs/workbench/browser/actions/windowActions.ts:346]: Oh I think I see it now, in `nativeHostService.doOpenWindow` you automagically add the `remoteAuthority` of the current window unless it is explicitly set to `null`.

File: src/vs/platform/windows/electron-main/windowsMainService.ts [hunk 6]
```diff
@@ -160,16 +160,12 @@ export class WindowsMainService extends Disposable implements IWindowsMainServic
 
 	openEmptyWindow(openConfig: IOpenEmptyConfiguration, options?: IOpenEmptyWindowOptions): ICodeWindow[] {
 		let cli = this.environmentMainService.args;
-		const remote = options?.remoteAuthority;
-		if (cli && (cli.remote !== remote)) {
-			cli = { ...cli, remote };
-		}
-
+		const remoteAuthority = options?.remoteAuthority || undefined;
```
Comment (bpasero) [inline src/vs/platform/windows/electron-main/windowsMainService.ts:163]: Yes, I like 👍

File: src/vs/platform/windows/electron-main/windowsMainService.ts [hunk 7]
```diff
@@ -1060,11 +1056,12 @@ export class WindowsMainService extends Disposable implements IWindowsMainServic
 			}
 		}
 
-		let authority = '';
+		let authority = openConfig.remoteAuthority;
```
Comment (bpasero) [inline src/vs/platform/windows/electron-main/windowsMainService.ts:1059]: Can we rename this to `remoteAuthority` to be consistent?

**Review by bpasero — CHANGES_REQUESTED** [review]
Overall I like the direction, left some comments.

Can you go a bit more into detail why we need the `remoteAuthority` now in the recently opened? Is that so we can support preserving the remote authority when a recently opened entry is neither `file` nor `vscode-remote`.

Overally the new `remoteAuthority` option is a bit misleading for opening windows because it is more like an override when the input is not provided or not `file` or `vscode-remote`. But for the sake of simplicity, let's use it so that we have an easy way to figure out all traces of `remoteAuthority` in our code. However: do we have code somewhere that makes sure to use `remoteAuthority: undefined` whenever an input is `file://` and `remoteAuthority:vscode-remote` whenever the input is `vscode-remote://`? Because I understand that now an extension could in theory give bad instructions (aka opening a `file` input with a `remoteAuthority` that is `vscode-remote`)? Should such a bad instruction maybe lead into an assertion error?

Finally, I do not fully understand how an extension would adopt this new `remoteAuthority` option. Take for example the Azure Storage extension that allows to open a virtual folder as workspace: does the extension have to adopt this new option or can we do that automatically based on figuring out wether the extension runs remote or not?

File: src/vs/workbench/browser/actions/windowActions.ts (hunk 5 above)
Comment (aeschli) [reply src/vs/workbench/browser/actions/windowActions.ts:346]: Yes, if undefined we use the one from the current window.

File: src/vs/code/electron-main/app.ts [hunk 8]
```diff
@@ -265,7 +266,8 @@ export class CodeApplication extends Disposable {
 					cli: this.environmentMainService.args,
 					urisToOpen: macOpenFileURIs,
 					gotoLineMode: false,
-					preferNewWindow: true /* dropping on the dock or opening from finder prefers to open in a new window */
+					preferNewWindow: true, /* dropping on the dock or opening from finder prefers to open in a new window */
+					remoteAuthority: undefined /* always local */
```
Comment (bpasero) [inline src/vs/code/electron-main/app.ts:270]: Is that needed here though? Shouldn't the fact that we have `urisToOpen` be enough to decide on the `remoteAuthority`?

File: src/vs/code/electron-main/app.ts [hunk 9]
```diff
@@ -748,6 +750,7 @@ export class CodeApplication extends Disposable {
 						cli: { ...environmentService.args },
 						urisToOpen: [windowOpenableFromProtocolLink],
 						gotoLineMode: true
+						/* remoteAuthority will be determined based on windowOpenableFromProtocolLink */
```
Comment (bpasero) [inline src/vs/code/electron-main/app.ts:753]: I think it is OK to remove this line, I would have expected exactly that.

File: src/vs/code/electron-main/app.ts [hunk 10]
```diff
@@ -808,6 +813,7 @@ export class CodeApplication extends Disposable {
 				urisToOpen: pendingWindowOpenablesFromProtocolLinks,
 				gotoLineMode: true,
 				initialStartup: true
+				/* remoteAuthority will be determined based on pendingWindowOpenablesFromProtocolLinks */
```
Comment (bpasero) [inline src/vs/code/electron-main/app.ts:816]: I think it is OK to remove this line, I would have expected exactly that.

File: src/vs/code/electron-main/app.ts [hunk 11]
```diff
@@ -832,7 +839,8 @@ export class CodeApplication extends Disposable {
 				urisToOpen: macOpenFiles.map(file => this.getWindowOpenableFromPathSync(file)),
 				noRecentEntry,
 				waitMarkerFileURI,
-				initialStartup: true
+				initialStartup: true,
+				remoteAuthority: undefined /* always local */
```
Comment (bpasero) [inline src/vs/code/electron-main/app.ts:843]: Is that needed here though? Shouldn't the fact that we have `urisToOpen` be enough to decide on the `remoteAuthority`?

File: src/vs/platform/native/electron-main/nativeHostMainService.ts [hunk 12]
```diff
@@ -161,7 +161,8 @@ export class NativeHostMainService extends Disposable implements INativeHostMain
 				addMode: options.addMode,
 				gotoLineMode: options.gotoLineMode,
 				noRecentEntry: options.noRecentEntry,
-				waitMarkerFileURI: options.waitMarkerFileURI
+				waitMarkerFileURI: options.waitMarkerFileURI,
+				remoteAuthority: options.remoteAuthority || undefined
```
Comment (bpasero) [inline src/vs/platform/native/electron-main/nativeHostMainService.ts:165]: Maybe rather `withNullAsUndefined(options.remoteAuthority)`? Does the `null` not travel to the main side?

File: src/vs/platform/native/electron-main/nativeHostMainService.ts [hunk 13]
```diff
@@ -309,7 +310,8 @@ export class NativeHostMainService extends Disposable implements INativeHostMain
 			contextWindowId: windowId,
 			cli: this.environmentMainService.args,
 			urisToOpen: openable,
-			forceNewWindow: options.forceNewWindow
+			forceNewWindow: options.forceNewWindow,
+			remoteAuthority: undefined // always local
```
Comment (bpasero) [inline src/vs/platform/native/electron-main/nativeHostMainService.ts:314]: Why is that so, what if I picked a remote URI?

File: src/vs/platform/native/electron-main/nativeHostMainService.ts [hunk 14]
```diff
@@ -521,7 +523,7 @@ export class NativeHostMainService extends Disposable implements INativeHostMain
 	//#region macOS Touchbar
 
 	async newWindowTab(): Promise<void> {
-		this.windowsMainService.open({ context: OpenContext.API, cli: this.environmentMainService.args, forceNewTabbedWindow: true, forceEmpty: true });
+		this.windowsMainService.open({ context: OpenContext.API, cli: this.environmentMainService.args, forceNewTabbedWindow: true, forceEmpty: true, remoteAuthority: this.environmentMainService.args.remote || undefined });
```
Comment (bpasero) [inline src/vs/platform/native/electron-main/nativeHostMainService.ts:526]: Why is the `|| undefined` needed, isn't that a optional property anyway?

File: src/vs/platform/windows/electron-main/windowsMainService.ts [hunk 15]
```diff
@@ -160,16 +160,12 @@ export class WindowsMainService extends Disposable implements IWindowsMainServic
 
 	openEmptyWindow(openConfig: IOpenEmptyConfiguration, options?: IOpenEmptyWindowOptions): ICodeWindow[] {
 		let cli = this.environmentMainService.args;
```
Comment (bpasero) [inline src/vs/platform/windows/electron-main/windowsMainService.ts:162]: I think the `|| undefined` can be removed in the line below?

File: src/vs/platform/windows/electron-main/windowsMainService.ts [hunk 16]
```diff
@@ -1060,17 +1056,18 @@ export class WindowsMainService extends Disposable implements IWindowsMainServic
...
 
-		let authority = '';
+		let remoteAuthority = openConfig.remoteAuthority;
 		for (const extensionDevelopmentPath of extensionDevelopmentPaths) {
 			if (extensionDevelopmentPath.match(/^[a-zA-Z][a-zA-Z0-9\+\-\.]+:/)) {
 				const url = URI.parse(extensionDevelopmentPath);
-				if (url.scheme === Schemas.vscodeRemote) {
-					if (authority) {
-						if (url.authority !== authority) {
+				const devPathRemoteAuthority = getRemoteAuthority(url);
```
Comment (bpasero) [inline src/vs/platform/windows/electron-main/windowsMainService.ts:1063]: I would explicitly call this `extensionDevelopmentPathRemoteAuthority`, I couldn't understand this at first.

**Review by bpasero — CHANGES_REQUESTED** [review]
Found some more things after doing a more in-depth review after your changes.

File: src/vs/platform/windows/electron-main/windowsMainService.ts (hunk 15 above)
Comment (aeschli) [reply src/vs/platform/windows/electron-main/windowsMainService.ts:162]: I wanted to restrict the remoteAuthorty: null to only the IOpenEmptyWindowOptions & IOpenWindowOptions. 
These are the parameter types for IHostService.openWindow and signal remote/local/default. 
The IHostService will then evaluate the default. On the main side, in IOpenConfiguration, used on the main side there's just remote and local (undefined).
In all other places in our code remoteAuthorty: undefined means local. Maybe we need to rename the parameter name in IOpenEmptyWindowOptions & IOpenWindowOptions to avoid confusion.

File: src/vs/platform/native/electron-main/nativeHostMainService.ts (hunk 14 above)
Comment (aeschli) [reply src/vs/platform/native/electron-main/nativeHostMainService.ts:526]: That's to avoid potential issues with the empty string
