### PR TITLE
Fix #164704. comment thread memory leak.

### LINKED ISSUE #164704: [365] potential listener LEAK detected
* have an eager comments controller extension (see below)
* open a notebook
* create a new cell
* leak warnings are printed

```
event.js:467 [365] potential listener LEAK detected, having 3431 listeners already. MOST frequent listener (3257):
event.js:468 Error
    at Stacktrace.create (event.js:478:35)
    at MainThreadCommentThread._event [as onDidChangeLabel] (event.js:576:44)
    at CommentThreadWidget._bindCommentThreadListeners (commentThreadWidget.js:150:69)
    at CommentThreadWidget.updateCommentThread (commentThreadWidget.js:98:18)
    at cellComments.js:79:55
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

```ts
const cctrl = vscode.comments.createCommentController('foo', "HELLO")

	vscode.window.onDidChangeActiveTextEditor(e => {
		if (!e) {
			return;
		}
		const thread = cctrl.createCommentThread(e.document.uri, new vscode.Range(0, 0, 1, 1), [{
			author: { name: 'FOOO' },
			body: `Hello ${e.document.uri.path}`,
			mode: vscode.CommentMode.Editing
		}])

	})

```

### PR DESCRIPTION
**Pull request by rebornix**

### CODE REVIEW

File: src/vs/workbench/contrib/comments/browser/commentThreadWidget.ts [hunk 1]
```diff
@@ -149,12 +149,9 @@ export class CommentThreadWidget<T extends IRange | ICellRange = IRange> extends
 	}
 
 	updateCommentThread(commentThread: languages.CommentThread<T>) {
-		if (this._commentThread !== commentThread) {
-			dispose(this._commentThreadDisposables);
-		}
-
 		this._commentThread = commentThread;
 		this._commentThreadDisposables = [];
+		dispose(this._commentThreadDisposables);
```
Comment (rzhao271) [inline src/vs/workbench/contrib/comments/browser/commentThreadWidget.ts:154]: Shouldn't this line go before 153?

File: src/vs/workbench/contrib/notebook/browser/view/cellParts/cellComments.ts [hunk 2]
```diff
@@ -102,25 +101,41 @@ export class CellComments extends CellPart {
...
 					}
+
+					this._commentThreadWidget.updateCommentThread(info.thread);
+					this.currentElement.commentHeight = this._calcualteCommentThreadHeight(this._commentThreadWidget.getDimensions().height);
 				}
 			}
 		}));
 	}
 
+	private _calcualteCommentThreadHeight(bodyHeight: number) {
```
Comment (rzhao271) [inline src/vs/workbench/contrib/notebook/browser/view/cellParts/cellComments.ts:126]:
```suggestion
	private _calculateCommentThreadHeight(bodyHeight: number) {
```

Though other references will also need to be updated.

**Review by rzhao271 — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/comments/browser/commentThreadWidget.ts (hunk 1 above)
Comment (rebornix) [reply src/vs/workbench/contrib/comments/browser/commentThreadWidget.ts:154]: @rzhao271 good catch, moved to the wrong line 👍

**Review by rzhao271 — APPROVED** [review]
