### PR TITLE
fix: disable skia graphite backend

### LINKED ISSUE #263554: Rendering broken on macOS
Does this issue occur when all extensions are disabled?: Unknown - issue is intermittent and difficult to replicate consistently.

Version: 1.103.2 (Universal)
Commit: 6f17636121051a53c88d3e605c491d22af2ba755
Date: 2025-08-20T16:45:34.255Z
Electron: 37.2.3
ElectronBuildId: 12035395
Chromium: 138.0.7204.100
Node.js: 22.17.0
V8: 13.8.500258-electron.0
OS: Darwin arm64 24.5.0

Steps to Reproduce:

1. Use VSCode with multiple window open. 
2. Allow MacOS to sleep
3. Wake up MacOS and navigate to VSCode
4. VSCode intermittently will completely fail to render - Every window

Rendering completely broken:
Image

Sorry this bug report is pretty sparse but I'm not able to use the help tools built into vscode to make a report. This rendering issue happened once or twice in the previous version of VSCode, but since the most recent update it is failing more often and requires a restart everytime.

I do know that I haven't added any extensions in a while. Definitely in the last couple of updates.

If you have any suggestions on being able to get some diagnostic information via a terminal command or by setting a flag in VSCode I am happy to do so and to continue to update this issue. Unfortunately due to the nature of this bug I can't disable plugins as I am relying on them day to day.

### LINKED ISSUE #284162: Broken rendering on macOS after app resumed from idle state
Type: <b>Performance Issue</b>

When I am working in my mac and toggle back to vscode, its bugged screen where half of the things are not showing up, until i hover my mouse to the empty place of grey square area and then it blinks the content of my vscode, and Yes i have restarted my laptop many times.
It has been very frequent these days
Attaching a video with it 

https://github.com/user-attachments/assets/e7f96994-4d18-4d9b-85c4-95fef6d33cf0

VS Code version: Code 1.107.1 (994fd12f8d3a5aa16f17d42c041e5809167e845a, 2025-12-17T14:15:14.850Z)
OS version: Darwin arm64 25.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: enabled_on<br>trees_in_viz: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 0973dd4c-cb45-4907-8bc9-24603bbd4fc9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    3	42221246507	 14724	code
    2	16888498603	 14727	   gpu-process
    0	8444249301	 14728	   utility-network-service
    1	115404740451	 14730	window [1] (Untitled 1 — GTA7)
    0	16888498603	 14765	pty-host
    0	     0	 15497	     /bin/zsh -il
    1	39406496739	 14766	shared-process
    0	     0	 16128	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	14073748836	 14767	file-watcher [1]
    0	121034239986	 15450	extension-host [1]
    0	11258999068	 16026	     electron-nodejs (languageserver.js)
    0	22517998137	 16032	     /Users/shanks/.vscode/extensions/ms-vscode.cpptools-1.30.0-darwin-arm64/bin/cpptools
    0	11258999068	 16045	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=15450
    0	14073748836	 16087	     electron-nodejs (server-node.js)
  107	70368744178	 16097	   window
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Untitled 1 — GTA7)
|    Folder (GTA7): 337 files
|      File types: c(71) cmake(38) h(36) txt(22) make(21) md(20) xml(10) in(7)
|                  ts(5) m(5)
|      Conf files: cmake(38) makefile(4);
```

</details>
<details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
python-image-preview|076|0.1.2
preview-pdf|ana|1.0.0
vscode-django|bat|1.15.0
codeviz|Cod|1.6.9
dart-code|Dar|3.124.1
flutter|Dar|3.124.0
vscode-eslint|dba|3.0.20
competitive-programming-helper|Div|2025.10.1761074305
docker|doc|0.18.0
python-environment-manager|don|1.2.7
python-extension-pack|don|1.7.0
vscode-html-css|ecm|2.0.13
prettier-vscode|esb|11.0.2
code-runner|for|0.12.2
codespaces|Git|1.18.4
copilot-chat|Git|0.35.1
vscode-github-actions|git|0.28.2
go|gol|0.50.0
vsc-python-indent|Kev|1.21.0
vscord|Leo|5.3.9
MagicPython|mag|1.1.0
rainbow-csv|mec|3.23.0
vscode-containers|ms-|2.3.0
vscode-docker|ms-|2.0.0
csharp|ms-|2.110.4
vscode-dotnet-runtime|ms-|3.0.0
debugpy|ms-|2025.18.0
isort|ms-|2025.0.0
python|ms-|2025.20.1
vscode-pylance|ms-|2025.10.4
vscode-python-envs|ms-|1.14.0
jupyter|ms-|2025.9.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.3.0
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.434.0
remote-wsl|ms-|0.104.3
cmake-tools|ms-|1.21.36
cpptools|ms-|1.30.0
cpptools-extension-pack|ms-|1.3.1
makefile-tools|ms-|0.12.17
powershell|ms-|2025.4.0
sqltools|mtx|0.28.5
autodocstring|njp|0.6.1
syntx|Ora|2.5.0
java|red|1.50.0
r|REd|2.8.6
r-syntax|REd|0.1.3
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.2719
cmake|twx|0.0.17
errorlens|use|3.26.0
vscode-gradle|vsc|3.17.1
vscode-java-debug|vsc|0.58.4
vscode-java-dependency|vsc|0.26.5
vscode-java-pack|vsc|0.30.5
vscode-java-test|vsc|0.43.2
vscode-maven|vsc|0.45.1
vscode-mermaid-preview|vst|2.1.2
jinja|who|0.0.8
p4-lang|Zha|0.0.14

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
binariesv615:30325510
nativeloc1:31344060
dwcopilot:31170013
dwoutputs:31242946
copilot_t_ci:31333650
e5gg6876:31282496
pythonrdcb7:31342333
6518g693:31436602
aj953862:31281341
nes-set-on:31351930
63221493:31336333
envsactivate1:31353494
cloudbuttont:31379625
todos-1:31405332
3efgi100_wstrepl:31403338
trigger-command-fix:31379601
use-responses-api:31390855
je187915:31407605
3i15c187:31428712
ec5jj548:31422691
terminalsuggestenabled:31431119
cmp-ext-treat:31426748
cp_cls_c_966_ss:31435507
copilot6169-t2000-control:31431385
c0683394:31419495
478ah919:31426797
ge8j1254_inline_auto_hint_haiku:31427726
a5gib710:31434435
38bie571_auto:31426784
request_with_suggest:31435827
rename_enabled:31436409
7a04d226_do_not_restore_last_panel_session:31434268
anthropic_thinking_t:31432745
31c7i317_no_change:31434515
cp_cls_c_1081:31433293
copilot-nes-callisto-trt:31434412

```

</details>

### PR DESCRIPTION
**Pull request by deepak1556**
Disabled until a fix is landed in skia, refer to https://gist.github.com/deepak1556/434964e5e379339be1d02db2a9afb743 for the conclusion towards this fix.

Fixes https://github.com/microsoft/vscode/issues/284162
Fixes https://github.com/microsoft/vscode/issues/263554

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -359,6 +356,10 @@ function configureCommandlineSwitchesSync(cliArgs: NativeParsedArgs) {
 	// use up to 2
 	app.commandLine.appendSwitch('max-active-webgl-contexts', '32');
 
+	// Disable Skia Graphite backend.
+	// Refs https://github.com/microsoft/vscode/issues/284162
+	app.commandLine.appendSwitch('disable-skia-graphite');
```
Comment (nikwen) [inline src/main.ts:361]: Only on macOS?

Comment (deepak1556) [reply src/main.ts:361]: Its only macOS internally in the runtime https://source.chromium.org/chromium/chromium/src/+/main:gpu/config/gpu_finch_features.cc;l=301-312

However irrespective of the platform, the issue is in the recorder so disabling it all cases is more appropriate.

Comment (nikwen) [reply src/main.ts:361]: Cool, thanks!

**Review by dmitrivMS — APPROVED** [review]
