### PR TITLE
`workbench.action.findInFiles` var resolver bug

### LINKED ISSUE #175973: `workbench.action.findInFiles` var resolver bug
repro steps:
1. paste this into `keybindings.json`
```
    {
        "key": "ctrl+shift+g",
        "command": "workbench.action.findInFiles",
        "args": {
            "filesToInclude": "${relativeFileDirname}",
        }
    },
```
2. ctrl+shift+g in a random file in the workspace 
3. Doesn't add the the current directory to the search viewlet.

### PR DESCRIPTION
**Pull request by andreamah**
Fixes #175973

### CODE REVIEW

**Review by rebornix — APPROVED** [review]

File: src/vs/workbench/contrib/search/browser/searchActionsFind.ts [hunk 1]
```diff
@@ -381,11 +381,11 @@ export async function findInFilesCommand(accessor: ServicesAccessor, _args: IFin
 				const searchAndReplaceWidget = openedView.searchAndReplaceWidget;
 				searchAndReplaceWidget.toggleReplace(typeof args.replace === 'string');
 				let updatedText = false;
-				if (typeof args.query === 'string') {
-					openedView.setSearchParameters(args);
-				} else {
+				if (typeof args.query !== 'string') {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/search/browser/searchActionsFind.ts:384]: FYI we have a util for this, using it should end up being less bytes in the bundle

https://github.com/microsoft/vscode/blob/7b39d0e24ae473beb9d1d28d8372e960681ddda9/src/vs/base/common/types.ts#L9-L11

**Review by Tyriar — APPROVED** [review]
