### PR TITLE
Fixes #97602: LinkedMap got modified during iteration

### LINKED ISSUE #97602: LinkedMap got modified during iteration.: Error: LinkedMap got modified during iteration.
ERR LinkedMap got modified during iteration.: Error: LinkedMap got modified during iteration.
    at LinkedMap.forEach (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:310:462)
    at g.cleanUp (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4797:282)
    at g.saveState (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4797:185)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4795:566

Code is here: https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/baseEditor.ts#L321

### PR DESCRIPTION
**Pull request by dbaeumer**
This PR fixes #

### CODE REVIEW

File: src/vs/workbench/browser/parts/editor/baseEditor.ts [hunk 1]
```diff
@@ -321,18 +321,21 @@ export class EditorMemento<T> implements IEditorMemento<T> {
...
 		const cache = this.doLoad();
 
-		// Remove groups from states that no longer exist
-		cache.forEach((mapGroupToMemento, resource) => {
+		// Remove groups from states that no longer exist. Since we modify the
+		// cache and its is a LRU cache make a copy to ensure iteration succeeds
+		const entries = [...cache.entries()];
+		for (const entry of entries) {
+			const resource: string = entry[0];
+			const mapGroupToMemento = entry[1];
```
Comment (bpasero) [inline src/vs/workbench/browser/parts/editor/baseEditor.ts:329]:
```suggestion
		for (const [resource, mapGroupToMemento] of entries) {
```

**Review by bpasero — APPROVED** [review]
Thanks, have one minor code change suggestion.
