### PR TITLE
fix more terminal completion issues

### LINKED ISSUE #234261: `git.blame.editorDecoration.enabled` shows incorrect value for diff changes displayed in source control
Does this issue occur when all extensions are disabled?: Yes

Version: 1.96.0-insider (user setup)
Commit: 8d1d1373cd9b8408222b51958e9688827a9e27ce
Date: 2024-11-20T09:23:45.992Z
Electron: 32.2.5
ElectronBuildId: 10579404
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

Steps to Reproduce:

1. Enable Git › Blame › Editor Decoration option - `git.blame.editorDecoration.enabled`
2. Open Source Control panel
3. Click on any commit

Newly added changes are displayed as `Not Committed Yet`:
<details><summary>Screenshot</summary>

Image

</details>

In the left panel some of old lines also shows `Not Committed Yet`, but in right panel it's displayed correctly:
<details><summary>Screenshot</summary>

Image

</details>

https://github.com/user-attachments/assets/7b531954-aeca-4b4c-b78e-a6ffed7c8c7f

By the way, thank you for adding this feature.

### PR DESCRIPTION
**Pull request by meganrogge**

### CODE REVIEW

File: extensions/terminal-suggest/src/terminalSuggestMain.ts [hunk 1]
```diff
@@ -288,7 +288,7 @@ export function getCompletionItemsFromSpecs(specs: Fig.Spec[], terminalContext:
 		}
 	}
 
-	if (!specificSuggestionsProvided) {
+	if (!specificSuggestionsProvided && (filesRequested === foldersRequested)) {
```
Comment (Tyriar) [inline extensions/terminal-suggest/src/terminalSuggestMain.ts:291]: This is a little hard to read, does it actually mean if neither files or folders requested OR both files and folders requests?

Comment (meganrogge) [reply extensions/terminal-suggest/src/terminalSuggestMain.ts:291]: It means don't provide generic commands when just one of them is provided - because that means it was requested by an arg of cd for example

**Review by Tyriar — DISMISSED** [review]

**Review by Tyriar — APPROVED** [review]
