### PR TITLE
Fix native editor shortcuts in integrated browser

### LINKED ISSUE #286633: Integrated Browser: copy/paste keyboard shortcuts not working on Mac
- VS Code Version: 1.109.0-insider
- OS Version: macOS Tahoe 26.2

**Steps to Reproduce:**
1. In command palette, run: "Browser: Open Integrated Browser"
2. Open any website that has text and a textbox, such as wikipedia.org
3. 🐛 Try to copy the text using Cmd + C and paste it into the textbox using Cmd + V. Neither copy nor paste work.

**Expected behavior:**
Copy/Paste shortcuts should work as expected

**Note:**
Copy/Paste currently only works if you do it from VS Code's Edit menu via mouse clicks

### PR DESCRIPTION
**Pull request by kycutler**
Fixes #286633

### CODE REVIEW

File: src/vs/platform/browserView/electron-main/browserView.ts [hunk 1]
```diff
@@ -15,7 +15,21 @@ import { IBaseWindow, ICodeWindow } from '../../window/electron-main/window.js';
 import { IAuxiliaryWindowsMainService } from '../../auxiliaryWindow/electron-main/auxiliaryWindows.js';
 import { IAuxiliaryWindow } from '../../auxiliaryWindow/electron-main/auxiliaryWindow.js';
 import { ILogService } from '../../log/common/log.js';
+import { isMacintosh } from '../../../base/common/platform.js';
 
+const nativeShortcutKeys = new Set(['KeyA', 'KeyC', 'KeyV', 'KeyX', 'KeyZ']);
+function ignoreNativeShortcut(input: Electron.Input): boolean {
```
Comment (jruales) [inline src/vs/platform/browserView/electron-main/browserView.ts]: nit: rename this to `shouldIgnoreNativeShortcut` so it sounds like a boolean-returning function instead of an action function

**Review by jruales — DISMISSED** [review]

File: src/vs/platform/browserView/electron-main/browserView.ts (hunk 1 above)
Comment (kycutler) [reply src/vs/platform/browserView/electron-main/browserView.ts]: done

**Review by jruales — APPROVED** [review]
