### PR TITLE
Sandboxed issue reporter

### LINKED ISSUE #101833: Issue reporter: remove node.js/electron dependencies
The issue reporter depends on a lot of Electron/node.js and should move into `electron-sandbox` compatible layer. The dependencies can be broken up by e.g. depending on the `IElectronService` instead. More methods can be added to this service as needed.

### PR DESCRIPTION
**Pull request by bpasero**
This PR fixes #101833 with 2 🚧  areas remaining:
- does this dialog needs its own log file or could it log to console / main side?
- does this dialog need telemetry at all

https://github.com/microsoft/vscode/blob/209c612baa8131e48dfcbef95f3f3615ea897798/src/vs/code/electron-sandbox/issue/issueReporterMain.ts#L326-L330

You can test this by running `code --__sandbox` which will enable sandbox and context isolation for the issue reporter.

### CODE REVIEW

**Comment by RMacfarlane** [comment]
Thanks @bpasero for doing this work! I pushed a change to remove both the telemetry and log service - I haven't looked at this data and don't think it provides much use.

I'll go ahead and merge this.

File: src/vs/code/electron-sandbox/issue/issueReporterMain.ts [hunk 1]
```diff
@@ -617,11 +583,11 @@ export class IssueReporter extends Disposable {
 						}, timeToWait * 1000);
 					}
 				}
-			}).catch(e => {
-				this.logSearchError(e);
+			}).catch(_ => {
+				// Ignore
```
Comment (deepak1556) [inline src/vs/code/electron-sandbox/issue/issueReporterMain.ts:587]: Can we log the error to console/main process instead, might be easy to miss an error the fetch method reports. Is there any utility on the electronservice to forward error messages to main process console ?
