### PR TITLE
Fixes #27041

### LINKED ISSUE #27041: Terminate all tasks
- VSCode Version: 1.12.2
- OS Version: Ubuntu 17.04

Steps to Reproduce:

I have multiple tasks running, One Sass and one TypeScript, I would like to be able to end all tasks with one keyboard shortcut. I currently have to end each task separately, so it would be nice to have something that will end all tasks.

Here is what I have for tasks:

```json
{
    "version": "2.0.0",
    "isShellCommand": true,
    "showOutput": "always",
    "tasks": [
        {
            "isBuildCommand": true,
            "taskName": "Build",
            "dependsOn": [
                "Build Sass",
                "Build TypeScript"
            ]
        },
        {
            "taskName": "Build Sass",
            "command": "node-sass",
            "args": [
                "-w",
                "./src/sass/main.scss",
                "./public/assets/css/prefab.css",
                "--output-style",
                "compressed"
            ]
        },
        {
            "taskName": "Build TypeScript",
            "command": "tsc",
            "problemMatcher": "$tsc-watch",
            "args": [
                "-w",
                "-p",
                "./src/typescript"
            ]
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by alpalla**
Fixes #27041. Added quick pick entry to terminate all running tasks along with argument 'terminateAll' which can be used with custom key binding to terminate all tasks via keyboard shortcut.
Possible issues/hacks associated with this fix:
- using difference between `undefined` and `null` to distinguish between "No task is currently running" and terminate "All running tasks" quick pick entries (https://github.com/alpalla/vscode/blob/master/src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts#L2219).
- using `showQuickPick()` parameter `selectedEntry` to actually add the terminate "All running tasks" entry to the quick pick (https://github.com/alpalla/vscode/blob/master/src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts#L1976).

### CODE REVIEW

File: src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts [hunk 1]
```diff
@@ -1973,6 +1973,9 @@ class TaskService extends Disposable implements ITaskService {
 			if ((entries.length === 0) && defaultEntry) {
 				entries.push(defaultEntry);
 			}
+			else if (selectedEntry) {
```
Comment (alexr00) [inline src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts]: Rather than using the selectedEntry, let's add a new paramter to `showQuickPick` for additional `TaskQuickPickEntry` items.

File: src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts [hunk 2]
```diff
@@ -2195,16 +2198,27 @@ class TaskService extends Disposable implements ITaskService {
...
 				},
-				false, true
+				false, true,
+				{
+					label: nls.localize('TaskService.terminateAllRunningTasks', 'All running tasks'),
+					task: null
+				}
 			).then(task => {
 				if (task === undefined || task === null) {
+					if (task === null) {
```
Comment (alexr00) [inline src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts]: Instead of having this null or undefined check, I'd prefer that `showQuickPick` be refactored to return the quick pick entry instead of the task. That way you can set an ID on the quick pick entry and check for it here.

**Review by alexr00 — CHANGES_REQUESTED** [review]

**Comment by alpalla** [comment]
@alexr00 As per your suggestions I did the following:
- added a parameter `additionalEntries?: TaskQuickPickEntry[]` to `showQuickPick()` so as to be able to pass in the terminate "All running tasks" entry as an argument (and make it possible to pass in further additional quick pick entries in the future).
- refactored `showQuickPick()` to return type `TaskQuickPickEntry` (can still return `undefined` or `null`). Because of this refactoring I did have to add code in other functions where a `Task` return type was still expected, the added code looks like this:
```
if (entry === undefined || entry === null) {
    return;
}
let task: Task | undefined | null = entry.task;
```
It makes for the same duplicate code in about 8 different locations in the file, let me know if I should implement some kind of `getTaskFromEntry()` function to clean that up a little.
- lastly in `runTerminateCommand()` I used an `id` value of `66` to check whether the terminate "All running tasks" entry was chosen.

File: src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts [hunk 3]
```diff
@@ -2195,16 +2210,33 @@ class TaskService extends Disposable implements ITaskService {
...
-					task: null
+					task: undefined
 				},
-				false, true
-			).then(task => {
+				false, true,
+				undefined,
+				[{
+					label: nls.localize('TaskService.terminateAllRunningTasks', 'All running tasks'),
+					id: '66',
```
Comment (alexr00) [inline src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts]: To make it consistant, let's make the id `terminalAll`.

File: src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts [hunk 4]
```diff
@@ -2195,16 +2210,33 @@ class TaskService extends Disposable implements ITaskService {
...
 				{
 					label: nls.localize('TaskService.noTaskRunning', 'No task is currently running'),
-					task: null
+					task: undefined
 				},
-				false, true
-			).then(task => {
+				false, true,
+				undefined,
+				[{
```
Comment (alexr00) [inline src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts]: Having the All running tasks option show in the quick pick when there is only one task is a bit confusing. We should only show it when there is > 1 task.

**Review by alexr00 — CHANGES_REQUESTED** [review]
Just about ready to merge. For your comment about duplicate code: Can you just collapse the check on to one line:
`let task: Task | undefined | null =  entry ? entry.task : undefined;`

**Comment by alpalla** [comment]
@alexr00 Confirming I made the following changes:
- changed the id to `terminateAll`
- collapsed the previously mentioned checks onto one line as you suggested
- only show the terminate "All running tasks" entry if there are more than one task by checking if `entries.length > 1` in `showQuickPick()` (if that's okay) like so: https://github.com/alpalla/vscode/blob/master/src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts#L1976

**Review by alexr00 — APPROVED** [review]

**Comment by alexr00** [comment]
@alpalla Thank you for adding this feature!
