### PR TITLE
Fixes terminal drop overlay moves horizontally instead of vertically when pane is on the side

### LINKED ISSUE #124928: Terminal drop overlay moves horizontally instead of vertically when pane is on the side
- VS Code Version: From sources

Steps to Reproduce:

terminal_overlay_vertical

### PR DESCRIPTION
**Pull request by jeanp413**
This PR fixes #124928

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 1]
```diff
@@ -2012,13 +2020,24 @@ class TerminalInstanceDragAndDropController extends Disposable implements IDragA
...
+			? (e.clientX - rect.left < rect.width / 2 ? 'before' : 'after')
+			: (e.clientY - rect.top < rect.height / 2 ? 'before' : 'after');
+	}
+
+	private _getViewOrientation(): Orientation {
+		const panelPosition = this._layoutService.getPanelPosition();
+		const terminalLocation = this._viewDescriptorService.getViewLocationById(TERMINAL_VIEW_ID);
+		return terminalLocation === ViewContainerLocation.Panel && panelPosition === Position.BOTTOM
+			? Orientation.HORIZONTAL
+			: Orientation.VERTICAL;
```
Comment (jeanp413) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:2040]: Had to copy this logic from `TerminalGroup` as I cannot use `TerminalService.onPanelOrientationChanged` to avoid a cyclic dependency

**Review by Tyriar — APPROVED** [review]
Great job as always 👍
