### PR TITLE
Fix-72650 Shell paths should be validated before launched to prevent ambiguous errors

### LINKED ISSUE #72650: Shell paths should be validated before launched to prevent ambiguous errors
We should validate the shell path exists and cache the result per window. Need to make sure it also works with symlinks.

image

There is this code that is meant to do this sort of thing right now but I think it's Windows only and also still just says "exit code 2":

https://github.com/Microsoft/vscode/blob/50c9a782ad2cf3b1b662966455187f8a9ec41bac/src/vs/workbench/contrib/terminal/node/terminalProcess.ts#L71-L77

### PR DESCRIPTION
**Pull request by skprabhanjan**
@Tyriar , Added the changes to handle file path check to resolve #72650 .
For the async problem that you had raised , I have used `fs.existsSync` ( https://nodejs.org/api/fs.html#fs_fs_existssync_path)
Please review this and let me know if anything is not rite or needs to be changed , Thanks :)

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/node/terminalProcess.ts [hunk 1]
```diff
@@ -70,12 +70,22 @@ export class TerminalProcess implements ITerminalChildProcess, IDisposable {
 		};
 
 		try {
-			this._ptyProcess = pty.spawn(shellLaunchConfig.executable!, shellLaunchConfig.args || [], options);
-			this._processStartupComplete = new Promise<void>(c => {
-				this.onProcessIdReady((pid) => {
-					c();
+			const filePath = path.basename(shellLaunchConfig.executable!);
+			if (fs.existsSync(filePath)) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/node/terminalProcess.ts]: Unfortunately we can't use existsSync as that will block the whole thread and could cause issues particularly on slow HDDs. To do this properly I think we would need to change `_ptyProcess` to a `pty.IPty | undefined` and create it asynchronously and then fix any compile errors that come out of that. It's probably a good idea to do that anyway as `pty.spawn` is synchronous as well which we should fix eventually.

We already have `_processStartupComplete` which signals when the process is ready so hopefully there isn't too much to do here.

File: src/vs/workbench/contrib/terminal/node/terminalProcess.ts [hunk 2]
```diff
@@ -70,12 +70,22 @@ export class TerminalProcess implements ITerminalChildProcess, IDisposable {
...
+				this._processStartupComplete = new Promise<void>(c => {
+					this.onProcessIdReady((pid) => {
+						c();
+					});
 				});
-			});
+			}
+			else {
+				// file path does not exist , handle it with negative exit code
+				this._exitCode = -1;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/node/terminalProcess.ts]: Let's create a new constant like `SHELL_PATH_INVALID_EXIT_CODE` inside `common/terminal.ts` and compare against that on both sides.

File: src/vs/workbench/contrib/terminal/node/terminalProcess.ts [hunk 3]
```diff
@@ -70,12 +70,22 @@ export class TerminalProcess implements ITerminalChildProcess, IDisposable {
...
+				this._queueProcessExit();
+				this._processStartupComplete = Promise.resolve(undefined);
+				return;
+			}
 		} catch (error) {
 			// The only time this is expected to happen is when the file specified to launch with does not exist.
 			this._exitCode = 2;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/node/terminalProcess.ts]: Right now this will fire for window and we won't get the nice error message, we should move this inside the fs exists check so we do the check on Windows too and then change the try/catch to maybe another exit code and `console.error` the error?

**Review by Tyriar — CHANGES_REQUESTED** [review]
Thanks for looking into this, got some comments below

File: src/vs/workbench/contrib/terminal/node/terminalProcess.ts (hunk 3 above)
Comment (skprabhanjan) [reply src/vs/workbench/contrib/terminal/node/terminalProcess.ts]: Removed Try catch as the catch block was meant for => "The only time this is expected to happen is when the file specified to launch with does not exist."
As we have handled this in async fs.stat , I removed it

File: src/vs/workbench/contrib/terminal/node/terminalProcess.ts (hunk 2 above)
Comment (skprabhanjan) [reply src/vs/workbench/contrib/terminal/node/terminalProcess.ts]: Done

File: src/vs/workbench/contrib/terminal/node/terminalProcess.ts (hunk 1 above)
Comment (skprabhanjan) [reply src/vs/workbench/contrib/terminal/node/terminalProcess.ts]: Done and fixed the compile errors , The only thing i have not touched is changing pty.spawn to async functions , we might have to do that later as per your comments.

**Comment by skprabhanjan** [comment]
@Tyriar , I have changed as per your comments , Please check and review the same :)

PS : I felt the try catch was no more required as the catch block was meant to catch only file not found exceptions.

File: src/vs/workbench/contrib/terminal/node/terminalProcess.ts [hunk 4]
```diff
@@ -69,28 +69,32 @@ export class TerminalProcess implements ITerminalChildProcess, IDisposable {
...
+			}
+			else if (err.code === 'ENOENT') {
+				this._exitCode = SHELL_PATH_INVALID_EXIT_CODE;
+				this._queueProcessExit();
+				this._processStartupComplete = Promise.resolve(undefined);
+				return;
+			}
+		});
+
+		this._ptyProcess!.on('data', (data) => {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/node/terminalProcess.ts]: I don't think this will work atm as _ptyProcess is delayed until after the stat but this runs immediately. Let move this and everything below in the ctor to inside the stat

File: src/vs/workbench/contrib/terminal/node/terminalProcess.ts [hunk 5]
```diff
@@ -69,28 +69,32 @@ export class TerminalProcess implements ITerminalChildProcess, IDisposable {
...
-		} catch (error) {
-			// The only time this is expected to happen is when the file specified to launch with does not exist.
-			this._exitCode = 2;
-			this._queueProcessExit();
-			this._processStartupComplete = Promise.resolve(undefined);
-			return;
-		}
-		this._ptyProcess.on('data', (data) => {
+			}
+			else if (err.code === 'ENOENT') {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/node/terminalProcess.ts]: Let's handle the error cases first to reduce indentation:

```ts
if (err && err.code === 'ENOENT') {
  ...
  return;
}

// spawn...
```

File: src/vs/workbench/contrib/terminal/node/terminalProcess.ts [hunk 6]
```diff
@@ -121,7 +125,7 @@ export class TerminalProcess implements ITerminalChildProcess, IDisposable {
 		}, 0);
 		// Setup polling
 		this._titleInterval = setInterval(() => {
-			if (this._currentTitle !== this._ptyProcess.process) {
+			if (this._currentTitle !== this._ptyProcess!.process) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/node/terminalProcess.ts]: If `this._ptyProcess` is passed into _setupTitlePolling we can avoid the `!`

**Review by Tyriar — CHANGES_REQUESTED** [review]
I think just to be safe we should be checking `if (this._ptyProcess)` instead of using `!`, otherwise null pointer exceptions could slip in.

File: src/vs/workbench/contrib/terminal/node/terminalProcess.ts (hunk 4 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/node/terminalProcess.ts]: I think this is why the integration tests failed in CI

File: src/vs/workbench/contrib/terminal/node/terminalProcess.ts (hunk 6 above)
Comment (skprabhanjan) [reply src/vs/workbench/contrib/terminal/node/terminalProcess.ts]: Done

File: src/vs/workbench/contrib/terminal/node/terminalProcess.ts (hunk 5 above)
Comment (skprabhanjan) [reply src/vs/workbench/contrib/terminal/node/terminalProcess.ts]: Yes this makes sense

File: src/vs/workbench/contrib/terminal/node/terminalProcess.ts (hunk 4 above)
Comment (skprabhanjan) [reply src/vs/workbench/contrib/terminal/node/terminalProcess.ts]: Sorry that was my bad , should have checked the async behaviour , this is done now. Added a new function `setupPtyProcess` to make the code look cleaner :) ( Let me know if this is not needed )

**Comment by skprabhanjan** [comment]
@Tyriar , Changes are done as per your reviews .
Added a new function `setupPtyProcess` which will be called in ctor if the file is found , Handled the error part first :) 
Let me know if we do not need this new function and have to add the code there itself :)

**Comment by Tyriar** [comment]
Wow my exitCodeMessage code really became a mess over time 😅, I cleaned that up a bit, also the path.basename was preventing the stat from working properly before.

**Review by Tyriar — APPROVED** [review]
Thanks @skprabhanjan, provided tests pass this time I'll merge this in for May soon 👍

**Comment by skprabhanjan** [comment]
@Tyriar, Thanks for the cleanup and few code changes related to path.basename :)
Yes if the tests pass then good to go , Thanks for reviewing it and getting this done from me :)
