### PR TITLE
fix fish terminal suggestions when wrapping occurs

### LINKED ISSUE #243800: When `fish` terminal wraps, suggestions stop working
deferred from #243786

This is because the prompt input model has line continuations in it - that's happening because we have to guess where those are for fish since they don't have one set explicitly.

Image

### PR DESCRIPTION
**Pull request by meganrogge**
fix #243800

Fish does not set a line continuation, so we need to handle it in the prompt input model specially to ensure we detect the command line correctly.

For fish, either nothing is used as a line continuation or a `\` is used.
1. When nothing is used, we will add `\n` to the prompt input value.
2. When `\` is used, we will not add `\n` to the prompt input value. 

In both cases, we will trim the whitespace. 

This also fixes an issue where the last line of a wrapped set is not included in the value. 

It also adds tests for these various cases.

Screenshot 2025-03-17 at 2 42 34 PM

### CODE REVIEW

File: src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts [hunk 1]
```diff
@@ -300,8 +308,9 @@ export class PromptInputModel extends Disposable implements IPromptInputModel {
 			line = buffer.getLine(y);
 			const lineText = line?.translateToString(true);
 			if (lineText && line) {
-				// Check if the line wrapped without a new line (continuation)
-				if (line.isWrapped) {
+				// Check if the line wrapped without a new line (continuation) or if the first line was empty
+				// for fish, which doesn't use a continuation prompt.
+				if (line.isWrapped || (commandLine === '' && this._shellType === PosixShellType.Fish)) {
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts:313]: To handle the possible empty new line at the beginning, can we set `commandStartY` and `commandStartX` conditionally based on shell type and whether content after the prompt is empty?

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts:313]: I'm not sure I follow - if I set commandStartY differently, the lines won't get processed?

Comment (Tyriar) [reply src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts]: I haven't tested the PR, but these are the main cases we need to handle:

Wrapping line that does not result in `\n`: `hello world|` (the `\` must be removed)
image

Wrapping line that does result in `\n`: `"hello\nworld"|` (`world` must not start with many spaces)
image

Wrapping first line beyond available width: `hello world|` (this must not start with `\n`)
image

File: src/vs/platform/terminal/test/common/capabilities/commandDetection/promptInputModel.test.ts [hunk 2]
```diff
@@ -693,11 +693,11 @@ suite('PromptInputModel', () => {
 			await assertPromptInput(`ech|`);
 
 			await writePromise('o ');
-			await assertPromptInput(`echo |`);
+			await assertPromptInput(`ech\no|`);
```
Comment (Tyriar) [inline src/vs/platform/terminal/test/common/capabilities/commandDetection/promptInputModel.test.ts:696]: This test suite is ambiguous, I think we need 2 different suites: `multi-line wrapped` and `multi-line wrapped (no continuation prompt)`.

For `multi-line` and `multi-line wrapped` suites we can then call `setContinuationPrompt('∙ ');` inside the suite setup.

File: src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts [hunk 3]
```diff
@@ -302,7 +321,26 @@ export class PromptInputModel extends Disposable implements IPromptInputModel {
 			if (lineText && line) {
 				// Check if the line wrapped without a new line (continuation)
 				if (line.isWrapped) {
-					value += lineText;
+					value += `\n${lineText}`;
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts:324]: I'm not sure about this change? I think in general the `\n` should be there if it's wrapped, so you might need to move this special behavior into the `if (this._shellType === PosixShellType.Fish)` block?

File: src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts [hunk 4]
```diff
@@ -302,7 +321,26 @@ export class PromptInputModel extends Disposable implements IPromptInputModel {
...
+					const relativeCursorIndex = this._getRelativeCursorIndex(0, buffer, line);
+					if (absoluteCursorY === y) {
+						cursorIndex += relativeCursorIndex;
+					} else {
+						cursorIndex += lineText.length;
+					}
+				} else if (this._shellType === PosixShellType.Fish) {
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts:331]: Could you write some unit tests for all the special fish cases?

File: src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts [hunk 5]
```diff
@@ -79,6 +82,7 @@ export class PromptInputModel extends Disposable implements IPromptInputModel {
 	private _commandStartX: number = 0;
 	private _lastPromptLine: string | undefined;
 	private _continuationPrompt: string | undefined;
+	private _shellType: TerminalShellType | undefined;
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts:85]: Could we merge the fish_cancel calls in the SI script into a single one, maybe this?

```
function __vsc_cmd_clear --on-event fish_cancel
	__vsc_esc E "" $__vsc_nonce
	__vsc_esc C
	__vsc_esc D
	set --global _vsc_has_cmd
end
```

**Review by Tyriar — DISMISSED** [review]

File: src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts (hunk 3 above)
Comment (meganrogge) [reply src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts:324]: Yes I think this was an accidental change

File: src/vs/platform/terminal/test/common/capabilities/commandDetection/promptInputModel.test.ts [hunk 6]
```diff
@@ -698,6 +699,66 @@ suite('PromptInputModel', () => {
...
+			await assertPromptInput(`echo "a"\nb|`);
+			await writePromise('\n\r\∙ ');
+			await assertPromptInput(`echo "a"\nb\n|`);
+			await writePromise('c');
+			await assertPromptInput(`echo "a"\nb\nc|`);
+			await writePromise('\n\r\∙ ');
+			await assertPromptInput(`echo "a"\nb\nc\n|`);
+		});
+	});
+	suite('multi-line wrapped fish', () => {
```
Comment (Tyriar) [inline src/vs/platform/terminal/test/common/capabilities/commandDetection/promptInputModel.test.ts:737]: Don't think we cover this case?

```
[I] meganrogge@Megans-MacBook-Pro ~ (main|BISECTING)> echo "hello
                                                      world"|
```

Comment (meganrogge) [reply src/vs/platform/terminal/test/common/capabilities/commandDetection/promptInputModel.test.ts:737]: think that's what this does? https://github.com/microsoft/vscode/blob/4ba1f5fec254ebb5b1c32cbdd24ea0f42eca54f3/src/vs/platform/terminal/test/common/capabilities/commandDetection/promptInputModel.test.ts#L750-L762

**Review by connor4312 — APPROVED** [review]
