### PR TITLE
use ID for quick fix telemetry

### LINKED ISSUE #165190: improve terminal quick fix telemetry

### PR DESCRIPTION
**Pull request by meganrogge**
fix #165190

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 1]
```diff
@@ -131,18 +132,20 @@ export class TerminalQuickFixAddon extends Disposable implements ITerminalAddon,
 		}
 		this._register(commandDetection.onCommandFinished(command => {
 			if (this._expectedCommands) {
+				const id = this._fixId || '';
 				const ranQuickFixCommand = this._expectedCommands.includes(command.command);
-				this._logService.debug(quickFixTelemetryTitle, {
-					id: this._expectedCommands.join(' '),
+				this._logService.info(quickFixTelemetryTitle, {
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:137]:
```suggestion
				this._logService.debug(quickFixTelemetryTitle, {
```

**Review by mjbvz — DISMISSED** [review]

**Review by mjbvz — DISMISSED** [review]

**Review by jrieken — APPROVED** [review]

**Review by heatherleeann — APPROVED** [review]
