### PR TITLE
Fixes issue #28695 with tooltips in Activity Bar

### LINKED ISSUE #28695: When hovering over vertical menu tooltips, icons have shortcuts in them, but wrapper buttons don't
- VSCode Version: 1.13.0
- OS Version: Windows 10 Home 10.0.15063

Steps to Reproduce:

1. Hover over vertical menu icons and slowly slide up and down
2. See the tooltip containing shortcut where directly over icon, not when just over the button space

Should be consistent across both

vs-code-tooltips

### PR DESCRIPTION
**Pull request by brandedoutcast**
Fixes #28695 by making the tool tips consistent

### CODE REVIEW

File: src/vs/workbench/browser/parts/activitybar/activitybarActions.ts [hunk 1]
```diff
@@ -310,6 +310,10 @@ export class ViewletActionItem extends ActivityActionItem {
 	public render(container: HTMLElement): void {
 		super.render(container);
 
+		if (this._keybinding) {
```
Comment (bpasero) [inline src/vs/workbench/browser/parts/activitybar/activitybarActions.ts]: @RohithKumbharkar I have a different suggestion where to put this code that makes it much easier. If you look below in that class there is a `public set keybinding(keybinding: string)`. I suggest to set the title in there because it gets computed there:

```typescript
this.$label.title(title);
this.$badge.title(title);
this.$container.title(title); // <-- add it here
```

**Review by bpasero — CHANGES_REQUESTED** [review]

**Comment by RohithKumbharkar** [comment]
@bpasero Yup totally makes sense for some reason I thought I couldn't access $container in there. Made the changes
