### PR TITLE
fix `problemMatcher` bug

### LINKED ISSUE #225826: Custom Problem matcher does not get recognized when passed into new Task()
For part of https://github.com/microsoft/vscode-python/pull/23953/files, where we are trying to define a default problem matcher and a task, I have noticed an issue:

- The problem matcher, when defined in its separate user's tasks.json with same shell execution command (such as python my_file.py), gets attached properly and shows problem in the problems panel.
- However, when the exact same problem panel is defined in extension's package.json (as opposed to user's tasks.json) and passed as an argument to the API
``` 
new Task(...., $customProblemMatcher)
```
 the problem matcher fails to get attached and does not show the problem in problems panel.

I've read through task-sample repository, https://github.com/Microsoft/vscode/issues/67285, https://code.visualstudio.com/api/references/contribution-points#contributes.problemMatchers, but could not tell the reason why contributing problem matcher fails when trying to attach to a custom task.

### PR DESCRIPTION
**Pull request by meganrogge**
Fixes #225826

We define problem matchers as `string | string[]` here https://github.com/microsoft/vscode/blob/64c211389b557bb7a0cdd6130c03e737b35a09f9/src/vscode-dts/vscode.d.ts#L8731

But we define them here as `string []`
https://github.com/microsoft/vscode/blob/a0933df3cca6fbbf2936313fa01685df7fe40a99/src/vscode-dts/vscode.d.ts#L8803

Since consumers of the API might pass in a `string`, we need to handle that.

validated the fix here https://github.com/microsoft/vscode/issues/225826#issuecomment-2305998838

### CODE REVIEW

File: src/vscode-dts/vscode.d.ts [hunk 1]
```diff
@@ -8800,7 +8800,7 @@ declare module 'vscode' {
 		 * The problem matchers attached to the task. Defaults to an empty
 		 * array.
 		 */
-		problemMatchers: string[];
+		problemMatchers: string | string[];
```
Comment (jrieken) [inline src/vscode-dts/vscode.d.ts:8803]: I don't think we can make this change because task can be "read" via `task.fetchTasks()`. This means there can be consumers of `Task#problemMatchers` which expect this to be an array and not a single string

**Review by jrieken — DISMISSED** [review]
This should be discussed in the API sync but also know that we don't change the API so that it breaks existing extension. 

For the process: https://github.com/microsoft/vscode/wiki/Extension-API-process

File: src/vscode-dts/vscode.d.ts (hunk 1 above)
Comment (meganrogge) [reply src/vscode-dts/vscode.d.ts:8803]: Ok, makes sense. The change in the `extHostTask.ts` file should be sufficient.

File: src/vs/workbench/api/common/extHostTask.ts [hunk 2]
```diff
@@ -279,7 +279,7 @@ export namespace TaskDTO {
 			isBackground: value.isBackground,
 			group: TaskGroupDTO.from(value.group as vscode.TaskGroup),
 			presentationOptions: TaskPresentationOptionsDTO.from(value.presentationOptions),
-			problemMatchers: value.problemMatchers,
+			problemMatchers: value.problemMatchers && Array.isArray(value.problemMatchers) ? value.problemMatchers : value.problemMatchers ? [value.problemMatchers] : [],
```
Comment (Tyriar) [inline src/vs/workbench/api/common/extHostTask.ts:282]: Could use a helper here: `value.problemMatchers ? asArray(value.problemMatchers) : []`

**Review by Tyriar — DISMISSED** [review]

File: src/vs/workbench/api/common/extHostTask.ts (hunk 2 above)
Comment (meganrogge) [reply src/vs/workbench/api/common/extHostTask.ts:282]: even better, could be `problemMatchers: asArray(value.problemMatchers`

File: src/vs/workbench/api/common/extHostTask.ts [hunk 3]
```diff
@@ -793,3 +793,13 @@ export class WorkerExtHostTask extends ExtHostTaskBase {
 }
 
 export const IExtHostTask = createDecorator<IExtHostTask>('IExtHostTask');
+
+function asArray(value: string | string[] | undefined): string[] {
```
Comment (roblourens) [inline src/vs/workbench/api/common/extHostTask.ts:797]: There is an `asArray` in arrays.ts that does this

**Review by roblourens — APPROVED** [review]
