### PR TITLE
Swallow copy zsh script error to allow multi-user machines

### LINKED ISSUE #157611: The terminal cannot be opened when multiple users use remote-ssh
Type: <b>Bug</b>

The terminal cannot be opened when multiple users use remote-ssh

When I used Remote-SSH today, I found that the terminal could not be opened. After checking the log, I found the following error output:

```
[2022-08-09 15:52:42.302] [remoteagent] [error] ["Error: EACCES: permission denied, copyfile '/home/{myuser}/.vscode-server/bin/da76f93349a72022ca4670c1b84860304616aaa2/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh' -> '/tmp/vscode-zsh/.zshrc'"]
```

Since the terminal I use is `zsh`, vscode-server copies my  `.zshrc` to `/tmp/vscode-zsh/.zshrc`, and the permission of this file belongs to me. As a result, the other users who use `zsh` as the terminal cannot open the terminal when using Remote-SSH for no permission to overwrite this file.

And I find that when the user uses bash, vscode-server does not copy `.bashrc` to `/tmp/vscode-bash/.bashrc`. Therefore, this bug does not exist when `bash` is used by all users
 

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:55.829Z)
OS version: Darwin x64 20.6.0
Modes:
Remote OS version: Linux x64 5.4.0-122-generic
Remote OS version: Linux x64 5.4.0-122-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv|--crash-reporter-id 7fae5c7a-b061-4e88-926b-c65a9268e173|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.12.41.222|
|OS|Linux x64 5.4.0-122-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz (12 x 1385)|
|Memory (System)|23.43GB (9.91GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: zjut.222.jinzcdev|
|OS|Linux x64 5.4.0-122-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz (12 x 1478)|
|Memory (System)|23.43GB (9.91GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
pythonsnippets|frh|1.0.2
vscode-language-pack-zh-hans|MS-|1.70.8030922
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
material-icon-theme|PKi|4.19.0
svg-preview|Sim|2.8.3
jinja|who|0.0.8
material-theme|zhu|3.15.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253

```

</details>

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #157611

### CODE REVIEW

File: src/vs/platform/terminal/node/terminalProcess.ts [hunk 1]
```diff
@@ -226,7 +233,15 @@ export class TerminalProcess extends Disposable implements ITerminalChildProcess
 			const zdotdir = path.join(tmpdir(), 'vscode-zsh');
 			await fs.mkdir(zdotdir, { recursive: true });
 			const source = path.join(path.dirname(FileAccess.asFileUri('', require).fsPath), 'out/vs/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh');
-			await fs.copyFile(source, path.join(zdotdir, '.zshrc'));
+			// TODO: Does filesToCopy make this unnecessary now?
```
Comment (Tyriar) [inline src/vs/platform/terminal/node/terminalProcess.ts:236]: @meganrogge I'm not sure if we use `_ZDOTDIR` anymore, is this if no longer run after we made the generic `filesToCopy`?

**Review by meganrogge — APPROVED** [review]

File: src/vs/platform/terminal/node/terminalProcess.ts [hunk 2]
```diff
@@ -213,7 +213,14 @@ export class TerminalProcess extends Disposable implements ITerminalChildProcess
 				if (injection.filesToCopy) {
 					for (const f of injection.filesToCopy) {
 						await fs.mkdir(path.dirname(f.dest), { recursive: true });
-						await fs.copyFile(f.source, f.dest);
+						try {
+							await fs.copyFile(f.source, f.dest);
+						} catch {
+							// Swallow error, this should only happen when multiple users are on the same
+							// machine. Since the shell integration scripts rarely change, plus the other user
+							// should be using the same version of the server in this case, assume the script is
```
Comment (roblourens) [inline src/vs/platform/terminal/node/terminalProcess.ts:221]: I don't think you can assume that two users are on the same client version of vscode, especially around the time of a release. And if the name is as generic as `/tmp/vscode-zsh/.zshrc` couldn't you have an issue with a single user upgrading too? And insiders vs stable?

Comment (Tyriar) [reply src/vs/platform/terminal/node/terminalProcess.ts:221]: @roblourens I think you're right about multiple versions of the server running at once, though maybe we should notify if we don't when a newer version is installed on the same machine? I didn't want to get into the business of leaving a bunch of per version files around. The impact of not writing this file is quite small as the script doesn't change often and even if it did, it likely wouldn't cause problems and they're easily resolved (update to latest).

We should include the product name in the folder, this was an oversight.

Comment (roblourens) [reply src/vs/platform/terminal/node/terminalProcess.ts:221]: > they're easily resolved (update to latest).

When you update, how does it end up actually using a newer version of this file? Seems like the oldest will stick around forever?

Comment (Tyriar) [reply src/vs/platform/terminal/node/terminalProcess.ts:221]: @roblourens oh, I thought this was related to a lock on the file but it's because a user cannot modify another user's file? I'll reopen the issue then

Comment (roblourens) [reply src/vs/platform/terminal/node/terminalProcess.ts:221]: That's my assumption - I haven't tried to break it
