### PR TITLE
Fix #11284 - Resolve tokens found in settings referenced by launch.json

### LINKED ISSUE #11284: Tokens defined in settings.json not resolved when the setting is referenced via launch.json
- VSCode Version:1.4
- OS Version:OS X

Steps to Reproduce:

1. Download [Python Extension](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python)
2. Create a simple python file with the following code ```print(1)```
3. Install a virtual environment under "p27" subdirectory of the workspace root.
4. Define the path to python interpreter as follows ```"python.pythonPath":"${workspaceRoot}/p27/bin/python"```  
5. Ensure the path to the pythonPath in launch.json is configured as follows ```"pythonPath": "${config.python.pythonPath}"```  
6. Debug the file created in step 2.
  
Error displayed:
```Failed to launch the Python Process, please validate the path '${workspaceRoot}/p27/bin/python'```

Problem: The token ${workspaceRoot} has not been resolved to the workspace root path.
   
The bug is in [configVariables](https://github.com/Microsoft/vscode/blob/903a011485215a29b20c1b1a33ddfaeb46f9e85d/src/vs/workbench/parts/lib/node/configVariables.ts#L35). 
The value returned contains the tokens ${workspaceRoot} that needs to be resolved.

### PR DESCRIPTION
**Pull request by DonJayamanne**
This fixes the issue (https://github.com/Microsoft/vscode/issues/11284):
- Launch.json can reference settings defined in settings.json via the syntax ${config.python.pythonPath}
- if a setting in setting.json such as python.pythonPath="abc", then the value received in the debugger via launch.json is "abc"
- However if the value for python.pythonPath="${workspaceRoot}/bin/python", then the value received by the debugger is "${workspaceRoot}/bin/python", when the value ${workspaceRoot} should be resolved.

Solution is to treat all values referenced by the syntax ${config...} as values that need to be resolved.

### CODE REVIEW

**Comment by bpasero** [comment]
@dbaeumer @weinand not sure who owns this?

**Comment by weinand** [comment]
@bpasero we (debug) have already planned to consolidate the variable substitution across VS Code. So we can take care of this.

/cc @dbaeumer @isidorn

**Comment by isidorn** [comment]
I'll take ownership

**Comment by bpasero** [comment]
@weinand @isidorn I wonder if we should expand this feature to the general configuration service and so maybe we should talk next milestone when this becomes current.

**Comment by isidorn** [comment]
@bpasero expanding it to everything and moving it to one central place would be awesome. Yeah let's talk about it in September

File: src/vs/workbench/parts/lib/node/configVariables.ts [hunk 1]
```diff
@@ -25,14 +25,16 @@ export class ConfigVariables extends SystemVariables {
 	}
 
 	protected resolveString(value: string): string {
+		const originalValue = value;
 		value = super.resolveString(value);
 
 		let regexp = /\$\{config\.(.*?)\}/g;
 		return value.replace(regexp, (match: string, name: string) => {
 			let config = this.configurationService.getConfiguration();
 			let newValue = new Function('_', 'try {return _.' + name + ';} catch (ex) { return "";}')(config);
```
Comment (isidorn) [inline src/vs/workbench/parts/lib/node/configVariables.ts]: Can we simplify this line such that it is more readable? Also new Function syntax is not our style - it is not used anywhere else in our code base so I would suggest to change this

File: src/vs/workbench/parts/lib/node/configVariables.ts [hunk 2]
```diff
@@ -25,14 +25,16 @@ export class ConfigVariables extends SystemVariables {
...
 			if (Types.isString(newValue)) {
-				return newValue;
+				// Prevent infinite recursion and also support nested references (or tokens)
+				return newValue === originalValue ? '' : this.resolveString(newValue);
 			}
```
Comment (isidorn) [inline src/vs/workbench/parts/lib/node/configVariables.ts]: Else formating is not our style, please keep the else on the same line

**Comment by isidorn** [comment]
@DonJayamanne I have added some comments in your commit mostly regarding older changes to this file. The newest change makes sense though - especailly if you tested it.
Love that you have added tests!
Once you adress my comments we can merge this PR in and then @bpasero and me can look into centralizing this.

File: src/vs/workbench/parts/lib/node/configVariables.ts (hunk 1 above)
Comment (DonJayamanne) [inline src/vs/workbench/parts/lib/node/configVariables.ts]: @isidorn , not sure how I could simplify this. Open to suggestions.
The only thing that comes to mind is adding more comments.
The use of new Function syntax is to allow for evaluation of expressions such as ```terminal.integrated.fontFamily``` or even the possibility of array indexes, and the like.

**Comment by isidorn** [comment]
Merging this PR in as my concerns where unrelated to the code this PR contributes.
