### PR TITLE
fix terminal aria label issues

### LINKED ISSUE #172199: Terminal accessibility menu keybinding not read with screen reader attached
Testing #171862

With editor.accessibilitySupport enabled and Windows Narrator running, when I click into the terminal, Narrator reads the terminal number, type (pwsh), and keybindings to navigate within the terminal history, but does not read the keybinding for Show Terminal Accessibility Help. Shortcuts are unchanged from defaults:

image

### PR DESCRIPTION
**Pull request by meganrogge**
fix #172199

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 1]
```diff
@@ -1997,10 +1997,13 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 				label = nls.localize('terminalTextBoxAriaLabel', "Terminal {0}", terminalId);
 			}
 			const screenReaderOptimized = this._accessibilityService.isScreenReaderOptimized();
-			if (screenReaderOptimized && isMacintosh) {
-				label += nls.localize('terminalTextBoxAriaLabelMacKeybinding', 'Press alt+f1 for terminal accessibility help');
+			if (!screenReaderOptimized) {
+				label += nls.localize('terminalScreenReaderMode', " To enter screen reader optimized mode, run the command Toggle Screen Reader Accessibility Mode.");
+			}
+			if (isMacintosh) {
+				label += nls.localize('terminalTextBoxAriaLabelMacKeybinding', " Press alt+f1 for terminal accessibility help");
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:2004]:
```suggestion
				label += nls.localize('terminalTextBoxAriaLabelMacKeybinding', " Press alt+f1 for terminal accessibility help.");
```

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 2]
```diff
@@ -1997,10 +1997,13 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
...
 			} else if (screenReaderOptimized) {
-				label += nls.localize('terminalTextBoxAriaLabelLinuxWinKeybinding', 'Press shift+f1 for terminal accessibility help');
+				label += nls.localize('terminalTextBoxAriaLabelLinuxWinKeybinding', " Press shift+f1 for terminal accessibility help");
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:2006]:
```suggestion
				label += nls.localize('terminalTextBoxAriaLabelLinuxWinKeybinding', " Press shift+f1 for terminal accessibility help.");
```

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 3]
```diff
@@ -1997,10 +1997,13 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 				label = nls.localize('terminalTextBoxAriaLabel', "Terminal {0}", terminalId);
 			}
 			const screenReaderOptimized = this._accessibilityService.isScreenReaderOptimized();
-			if (screenReaderOptimized && isMacintosh) {
-				label += nls.localize('terminalTextBoxAriaLabelMacKeybinding', 'Press alt+f1 for terminal accessibility help');
+			if (!screenReaderOptimized) {
+				label += nls.localize('terminalScreenReaderMode', " To enter screen reader optimized mode, run the command Toggle Screen Reader Accessibility Mode.");
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:2001]: It might be better to separate all by a ` ` like this?

```ts
labelParts.push(...)
labelParts.join('\n')
```

We don't want a leading space to get translated incorrectly.

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 4]
```diff
@@ -1997,10 +1997,13 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
...
+			}
+			if (isMacintosh) {
+				label += nls.localize('terminalTextBoxAriaLabelMacKeybinding', " Press alt+f1 for terminal accessibility help.");
 			} else if (screenReaderOptimized) {
-				label += nls.localize('terminalTextBoxAriaLabelLinuxWinKeybinding', 'Press shift+f1 for terminal accessibility help');
+				label += nls.localize('terminalTextBoxAriaLabelLinuxWinKeybinding', " Press shift+f1 for terminal accessibility help.");
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:2006]: These keybindings are custom so we want to pull the labels from the keybindings service.

**Review by Tyriar — DISMISSED** [review]

**Review by mjbvz — APPROVED** [review]
