### PR TITLE
Fix possible TerminalInstance leak

### LINKED ISSUE #200400: TerminalInstance memory leak
Repro:

1. Open Code - OSS
2. Close all terminals
3. Reload
4. Open devtools
5. Go to memory and take a heap snapshot
6. Open a terminal
7. Close the terminal
8. Go to memory and take a heap snapshot
9. Compare the two heap snapshots, you should not see `TerminalInstance`

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #200400

Two fixes:

- Explicitly make sure an event is disposed of
- In EventMultiplexer, explicitly dispose of all listeners when the multiplexer is disposed

### CODE REVIEW

File: src/vs/workbench/api/browser/mainThreadTerminalService.ts [hunk 1]
```diff
@@ -245,7 +245,7 @@ export class MainThreadTerminalService implements MainThreadTerminalServiceShape
 				output: e.data.getOutput()
 			});
 		});
-		this._sendCommandEventListener.value = multiplexer;
+		this._sendCommandEventListener.value = combinedDisposable(multiplexer, sub);
```
Comment (connor4312) [inline src/vs/workbench/api/browser/mainThreadTerminalService.ts:248]: test

**Review by connor4312 — DISMISSED** [review]

**Review by benibenj — APPROVED** [review]
