### PR TITLE
Fix potential leak of chat editors

### LINKED ISSUE #213209: [286] REFUSES to accept new listeners because it exceeded its threshold by far (<REDACTED: user-file-path>). HINT: Stack shows most frequent listener (112-times)
```javascript
Error
at c.create in src/vs/base/common/event.ts:900:15
at r.q [as onDidChange] in src/vs/base/common/event.ts:1095:34
at new h in src/vs/editor/common/model/tokenizationTextModelPart.ts:59:53
at new x in src/vs/editor/common/model/textModel.ts:330:37
at $.J in src/vs/editor/common/services/modelService.ts:317:28
at $.createModel in src/vs/editor/common/services/modelService.ts:454:21
at re.provideTextContent in src/vs/workbench/contrib/chat/browser/codeBlockPart.ts:433:29
at h.u in src/vs/workbench/services/textmodelResolver/common/textModelResolverService.ts:187:33
at h.r in src/vs/workbench/services/textmodelResolver/common/textModelResolverService.ts:78:15
at h.b in src/vs/workbench/services/textmodelResolver/common/textModelResolverService.ts:38:15
at h.acquire in src/vs/base/common/lifecycle.ts:650:43
at k.acquire in src/vs/base/common/lifecycle.ts:680:40
at l.createModelReference in src/vs/workbench/services/textmodelResolver/common/textModelResolverService.ts:238:42
at $.getOrCreate in src/vs/workbench/contrib/chat/common/codeBlockModelCollection.ts:53:37
at $.update in src/vs/workbench/contrib/chat/common/codeBlockModelCollection.ts:64:22
at n.code in src/vs/workbench/contrib/chat/common/chatViewModel.ts:277:34
at J.parse in out-vscode/vs/workbench/vs/base/common/marked/marked.js:2404:1
at Q.parse in out-vscode/vs/workbench/vs/base/common/marked/marked.js:2325:1
at Function.q [as parse] in out-vscode/vs/workbench/vs/base/common/marked/marked.js:2757:1
at i.updateCodeBlockTextModels in src/vs/workbench/contrib/chat/common/chatViewModel.ts:281:10
at i.m in src/vs/workbench/contrib/chat/common/chatViewModel.ts:251:8
at <anonymous> in src/vs/workbench/contrib/chat/common/chatViewModel.ts:203:10
at Array.forEach (<anonymous>)
at new i in src/vs/workbench/contrib/chat/common/chatViewModel.ts:197:24
at m.o in src/vs/platform/instantiation/common/instantiationService.ts:161:18
at m.createInstance in src/vs/platform/instantiation/common/instantiationService.ts:127:18
at O.setModel in src/vs/workbench/contrib/chat/browser/chatWidget.ts:612:46
at p.s in src/vs/workbench/contrib/chat/browser/chatViewPane.ts:113:16
at p.W in src/vs/workbench/contrib/chat/browser/chatViewPane.ts:168:9
at p.render in src/vs/base/browser/ui/splitview/paneview.ts:285:9
at p.render in src/vs/workbench/browser/parts/views/viewPane.ts:435:9
at R.tb in src/vs/workbench/browser/parts/views/viewPaneContainer.ts:792:9
at R.create in src/vs/workbench/browser/parts/views/viewPaneContainer.ts:538:9
at O.create in src/vs/workbench/browser/panecomposite.ts:48:26
at f.Eb in src/vs/workbench/browser/parts/compositePart.ts:235:14
at f.Eb in src/vs/workbench/browser/parts/paneCompositePart.ts:230:9
at f.Cb in src/vs/workbench/browser/parts/compositePart.ts:158:8
at f.Bb in src/vs/workbench/browser/parts/compositePart.ts:122:15
at f.Bc in src/vs/workbench/browser/parts/paneCompositePart.ts:483:15
at f.openPaneComposite in src/vs/workbench/browser/parts/paneCompositePart.ts:457:16
at f.run in src/vs/workbench/browser/parts/paneCompositeBar.ts:772:32
at D.u in src/vs/base/common/actions.ts:194:16
at D.run in src/vs/base/common/actions.ts:185:15
at I.onClick in src/vs/base/browser/ui/actionbar/actionViewItems.ts:172:21
at HTMLLIElement.<anonymous> in src/vs/base/browser/ui/actionbar/actionViewItems.ts:152:10
```
[Go to Errors Site](https://errors.code.visualstudio.com/card?ch=a48f464a3e01aad384703ec964018299b14bb7cf&bH=39347958-9148-9f0f-28f5-6c73f59628b4)

### LINKED ISSUE #217835: Go to definition in Chat view does not work for typescript
Based on your message I got the impression that we are adding language smarts to the code blocks in the chat view. However it is not working for me.

macOS, insiders, latest copilot chat pre-release

1. binary search in typescript
2. I get this output
```typescript
function binarySearch(arr: number[], target: number): number {
    let left: number = 0;
    let right: number = arr.length - 1;

    while (left <= right) {
        let mid: number = Math.floor((left + right) / 2);

        // Check if target is present at mid
        if (arr[mid] === target) {
            return mid;
        }

        // If target greater, ignore left half
        if (arr[mid] < target) {
            left = mid + 1;
        }
        // If target is smaller, ignore right half
        else {
            right = mid - 1;
        }
    }

    // Target was not found
    return -1;
}

// Example usage
const arr: number[] = [2, 3, 4, 10, 40];
const target: number = 10;
const result: number = binarySearch(arr, target);
if (result !== -1) {
    console.log(`Element found at index ${result}`);
} else {
    console.log("Element not present");
}
```

I click on the `binarySearch` function call at the end, and go to definition. This is a no-op 🐛 
I would expect that the start of the code block is revealed and that cursor moves to the method declaration of `binarySearch`.

Similarly for other language features and languages none of the smart features work in code blocks in chat for me. Am I missing something?

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #213209

I believe that chat editors are potentially being leaked when progressive rendering ends due to `contentParts` being set without also being disposed of

Also fixes the wrong selection potentially being used

Fixes #217835

### CODE REVIEW

File: src/vs/workbench/contrib/chat/browser/chatListRenderer.ts [hunk 1]
```diff
@@ -488,6 +488,9 @@ export class ChatListItemRenderer extends Disposable implements ITreeRenderer<Ch
 				parts.push(newPart);
 			}
 		});
+		if (templateData.renderedParts) {
```
Comment (roblourens) [inline src/vs/workbench/contrib/chat/browser/chatListRenderer.ts:491]: Good catch. I was just wondering why I still do this totally differently in this case rather than do the same 'diff' flow as in the progressive rendering case. I should just make the two cases exactly the same.

**Review by roblourens — APPROVED** [review]
