### PR TITLE
Disable terminal sandboxing for confirmation prompts

### LINKED ISSUE #301928: Copilot CLI terminal tools are never invoked due to sandboxing feature missing dependencies
* Open VS Code insiders
* Select copilot CLI
* Select an existing session or start a new session
* Send the prompt `use terminal to tell me the current date`
* It will do nothing

Logs in console window

```
log.ts:460   ERR [LanguageModelToolsService#invokeTool] Error from tool vscode_get_terminal_confirmation with parameters {"message":"Get current date and time","command":"date","isBackground":false}:
Sandbox dependencies are not available on this system. Required: ripgrep (rg).: Error: Sandbox dependencies are not available on this system. Required: ripgrep (rg).
    at Object.initialize (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/node_modules/@anthropic-ai/sandbox-runtime/dist/sandbox/sandbox-manager.js:162:15)
    at Sc.wrapWithSandbox (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/main.js:539:14947)
    at Object.call (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/main.js:409:5336)
    at Sd.onPromise (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/main.js:407:14316)
    at Sd.onRawMessage (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/main.js:407:13739)
    at Pa.value (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/main.js:407:13030)
    at S._deliver (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/main.js:406:2869)
    at S._deliverQueue (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/main.js:406:2958)
    at S.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/main.js:406:3292)
    at Pa.value (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/main.js:404:5941)
    at S._deliver (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/main.js:406:2869)
    at S.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/main.js:406:3187)
    at Pa.value (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/main.js:404:6131)
    at S._deliver (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/main.js:406:2869)
    at S.fire (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/main.js:406:3187)
    at X (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/main.js:404:9491)
    at IpcMainImpl.t (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/main.js:412:13212)
    at IpcMainImpl.emit (node:events:531:35)
    at Session.<anonymous> (node:electron/js2c/browser_init:2:112437)
    at Session.emit (node:events:519:28)
```

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes https://github.com/microsoft/vscode/issues/301928

### CODE REVIEW

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts [hunk 1]
```diff
@@ -369,6 +369,7 @@ export class RunInTerminalTool extends Disposable implements IToolImpl {
 	}
 
 	constructor(
+		enableSandboxing: boolean,
```
Comment (dileepyavan) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts]: can enableSandboxing be defaulted to true?

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/terminal.chatAgentTools.contribution.ts [hunk 2]
```diff
@@ -102,7 +102,7 @@ class ChatAgentToolsContribution extends Disposable implements IWorkbenchContrib
 		this._register(toolsService.executeToolSet.addTool(KillTerminalToolData));
 
 		instantiationService.invokeFunction(createRunInTerminalToolData).then(runInTerminalToolData => {
-			const runInTerminalTool = instantiationService.createInstance(RunInTerminalTool);
+			const runInTerminalTool = instantiationService.createInstance(RunInTerminalTool, true);
```
Comment (dileepyavan) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/terminal.chatAgentTools.contribution.ts]: if its defaulted to true in run in terminal, this is no longer needed

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalConfirmationTool.ts [hunk 3]
```diff
@@ -58,6 +71,43 @@ export const ConfirmTerminalCommandToolData: IToolData = {
...
+			_remoteAgentService,
+			_storageService,
+			_terminalChatService,
+			_logService,
+			_terminalService,
+			_workspaceContextService,
+			_chatWidgetService,
+			_agentSessionsService,
+		);
+	}
```
[the remark this answers is not in the document]
Comment (dileepyavan) [reply src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalConfirmationTool.ts]: This is a better approach.

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/terminal.chatAgentTools.contribution.ts (hunk 2 above)
Comment (DonJayamanne) [reply src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/terminal.chatAgentTools.contribution.ts]: still required the way the DI injection works

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts (hunk 1 above)
Comment (DonJayamanne) [reply src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts]: We cannot have optional parameters with default values, not with our DI

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts [hunk 4]
```diff
@@ -399,7 +399,9 @@ export class RunInTerminalTool extends Disposable implements IToolImpl {
 		RunInTerminalTool._activeExecutions.delete(id);
 		return true;
 	}
-
+	protected get _sandboxingEnabled() {
```
Comment (dileepyavan) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts]: can you add a comment for this property as this is kind of confusing with sandboxenabled from terminal sandboxservice.

**Review by dileepyavan — DISMISSED** [review]

**Review by dileepyavan — APPROVED** [review]
