### PR TITLE
Ignore file-like domain suffixes in terminal sandbox

### LINKED ISSUE #307510: Agent sandbox incorrectly identifies a file name as a domain name
## Bug Description

The agent sandbox is incorrectly classifying a file name as a domain name.

## Expected Behavior

A plain file name should be treated as a local file reference and not as an external domain.

## Actual Behavior

The sandbox interprets the file name as a domain name, which leads to incorrect handling.

## Notes

Labeling this under `agent-sandbox` for sandbox classification/routing behavior.

### PR DESCRIPTION
**Pull request by dileepyavan**
## Summary
- ignore hostname matches whose final label looks like a common file extension when normalizing candidate domains in the terminal sandbox service
- reduce false positives from commands that reference local files such as `.js`, `.json`, `.php`, `.java`, `.css`, `.md`, and `.env`
- add targeted regressions covering direct filename-like matches and commands that include filenames so they remain sandboxed

## Testing
- `./scripts/test.sh --run src/vs/workbench/contrib/terminalContrib/chatAgentTools/test/browser/terminalSandboxService.test.ts`
- `node --experimental-strip-types build/hygiene.ts src/vs/workbench/contrib/terminalContrib/chatAgentTools/common/terminalSandboxService.ts src/vs/workbench/contrib/terminalContrib/chatAgentTools/test/browser/terminalSandboxService.test.ts`

fixes #307510

### CODE REVIEW

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/common/terminalSandboxService.ts [hunk 1]
```diff
@@ -135,6 +135,12 @@ export class TerminalSandboxService extends Disposable implements ITerminalSandb
 	private static readonly _urlRegex = /(?:https?|wss?):\/\/[^\s'"`|&;<>]+/gi;
 	private static readonly _sshRemoteRegex = /(?:^|[\s'"`])(?:[^\s@:'"`]+@)?([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})(?::[^\s'"`|&;<>]+)(?=$|[\s'"`|&;<>])/gi;
 	private static readonly _hostRegex = /(?:^|[\s'"`(=])([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})(?::\d+)?(?=(?:\/[^\s'"`|&;<>]*)?(?:$|[\s'"`)\]|,;|&<>]))/gi;
+	private static readonly _fileExtensionSuffixes = new Set([
+		'7z', 'bz2', 'cjs', 'class', 'cpp', 'cs', 'css', 'csv', 'dll', 'exe', 'gif', 'gz', 'ico', 'jar',
+		'env', 'java', 'jpeg', 'jpg', 'js', 'json', 'jsx', 'lock', 'log', 'md', 'mjs', 'pdf', 'php', 'png',
+		'py', 'rar', 'rs', 'so', 'sql', 'svg', 'tar', 'tgz', 'toml', 'ts', 'tsx', 'txt', 'wasm', 'webp',
+		'xml', 'yaml', 'yml', 'zip'
```
[the remark this answers is not in the document]
Comment (dileepyavan) [reply src/vs/workbench/contrib/terminalContrib/chatAgentTools/common/terminalSandboxService.ts:143]: these are file extensions.

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/common/terminalSandboxService.ts [hunk 2]
```diff
@@ -135,6 +135,12 @@ export class TerminalSandboxService extends Disposable implements ITerminalSandb
 	private static readonly _urlRegex = /(?:https?|wss?):\/\/[^\s'"`|&;<>]+/gi;
 	private static readonly _sshRemoteRegex = /(?:^|[\s'"`])(?:[^\s@:'"`]+@)?([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})(?::[^\s'"`|&;<>]+)(?=$|[\s'"`|&;<>])/gi;
 	private static readonly _hostRegex = /(?:^|[\s'"`(=])([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})(?::\d+)?(?=(?:\/[^\s'"`|&;<>]*)?(?:$|[\s'"`)\]|,;|&<>]))/gi;
+	private static readonly _fileExtensionSuffixes = new Set([
```
Comment (justschen) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/common/terminalSandboxService.ts:139]: nit: it's kinda annoying to maintain a hardcoded list like this (unless we know for sure these are all the cases we might have), maybe down the line we can use regex or something of the sort.

**Review by justschen — DISMISSED** [review]

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/common/terminalSandboxService.ts (hunk 2 above)
Comment (dileepyavan) [reply src/vs/workbench/contrib/terminalContrib/chatAgentTools/common/terminalSandboxService.ts:139]: yeah this is tricky as the valid regex for domain can pick up file names too. This list is to avoid false positives.

**Review by justschen — APPROVED** [review]
