### PR TITLE
Nb Sticky Scroll z-index & css fixes

### LINKED ISSUE #191632: z-index issues with notebooks sticky scroll
* have side by side editors
* open a notebook in the 2nd tab group
* scroll so that NB sticky scroll shows
* it overlays the editor sash

Screenshot 2023-08-29 at 16 44 41

### PR DESCRIPTION
**Pull request by Yoyokrazy**
Fixes: #191632, #188974, #193404, #191558, #199601

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/browser/viewParts/notebookEditorStickyScroll.ts [hunk 1]
```diff
@@ -153,36 +168,36 @@ export class NotebookStickyScroll extends Disposable {
...
+			this.updateContent(computeContent(this.notebookEditor, this.notebookCellList, this.filteredOutlineEntries, this.getCurrentStickyHeight(), this.renderedStickyLines));
 		}));
 
 		this._disposables.add(this.notebookEditor.onDidScroll(() => {
-			DOM.clearNode(this.domNode);
-			this.disposeCurrentStickyLines();
-			this.updateContent(computeContent(this.domNode, this.notebookEditor, this.notebookCellList, this.notebookOutline.entries));
+			const deboucer = new Delayer(200);
+
+			deboucer.trigger(() => {
```
Comment (rebornix) [inline src/vs/workbench/contrib/notebook/browser/viewParts/notebookEditorStickyScroll.ts:191]: we want to dispose `deboucer` properly.

File: src/vs/workbench/contrib/notebook/browser/viewParts/notebookEditorStickyScroll.ts [hunk 2]
```diff
@@ -210,91 +225,38 @@ export class NotebookStickyScroll extends Disposable {
...
+		const sizeDelta = this.getCurrentStickyHeight() - oldStickyHeight;
+		if (sizeDelta !== 0) {
+			this._onDidChangeNotebookStickyScroll.fire(sizeDelta);
+		}
 		this.updateDisplay();
 	}
 
 	private updateDisplay() {
-		const hasSticky = this.currentStickyLines.size > 0;
+		const hasSticky = this.getCurrentStickyHeight() > 0;
```
Comment (rebornix) [inline src/vs/workbench/contrib/notebook/browser/viewParts/notebookEditorStickyScroll.ts:249]: we can check the size of `currentStickyLines`

**Review by Henderv — COMMENTED** [review]
Ok

File: src/vs/workbench/contrib/notebook/browser/viewParts/notebookEditorStickyScroll.ts (hunk 2 above)
Comment (Yoyokrazy) [reply src/vs/workbench/contrib/notebook/browser/viewParts/notebookEditorStickyScroll.ts:249]: Don't think so, as that is all of the potential lines to be rendered for a section. As they collapse against the next section, some will not be rendered. Need to specifically check with the fxn since it checks the rendered value

**Comment by Yoyokrazy** [comment]
todo: 
- [ ] update testing to reflect new behavior changes 
- [ ] edge case for visible index 0 to avoid showing sticky line for a cell index 0 header (header to start a notebook, etc)

**Review by roblourens — APPROVED** [review]
