### PR TITLE
Fixes terminal group relative size not preserved

### LINKED ISSUE #192517: Regresion: Terminal group relative size not preserved
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: stable and from sources
- OS Version: 

Steps to Reproduce:

1. Open terminal panel
2. Split terminal and resize
3. Reload window
4. :bug: terminal relative sizes are not preserved

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes https://github.com/microsoft/vscode/issues/192517

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 1]
```diff
@@ -503,30 +503,23 @@ export class TerminalService extends Disposable implements ITerminalService {
...
-					config: { attachPersistentProcess },
-					location: { parentTerminal: lastInstance }
-				});
-			}
-			mark(`code/terminal/didRecreateTerminal/${attachPersistentProcess.id}-${attachPersistentProcess.pid}`);
+			lastInstance = this.createTerminal({
+				config: { attachPersistentProcess },
+				location: lastInstance ? { parentTerminal: lastInstance } : TerminalLocation.Panel
+			});
+			lastInstance.then(() => mark(`code/terminal/didRecreateTerminal/${attachPersistentProcess.id}-${attachPersistentProcess.pid}`));
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:516]: could we use `await` instead of these `then` statements?

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 2]
```diff
@@ -503,30 +503,23 @@ export class TerminalService extends Disposable implements ITerminalService {
...
 		}
-		group?.then(g => g?.resizePanes(tabLayout.terminals.map(terminal => terminal.relativeSize)));
+		const group = lastInstance?.then(instance => {
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:518]: also here?

**Review by meganrogge — APPROVED** [review]
It works, thank you!

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalService.ts:516]: oh I see the problem with that

**Review by connor4312 — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]
