### PR TITLE
fix #138104

### LINKED ISSUE #138104: Tasks with type `process` and a missing `command` fail too early to emit the right events
Issue Type: <b>Bug</b>

See the [reproduction repo](https://github.com/mkhl/issue-process-task-for-missing-executable-drops-events), which provides two tasks `shell` and `process` and a README with these steps.

### Actual behavior

1. Run the task `process`
1. Run the task `process` again.
1. Note that each failed in its own terminal, despite what the message in the terminal said.
1. Focus the terminal and press a key to close it.
1. Run the task `shell`.
1. Run the task `shell` again.
1. Note that both failed in the same terminal, again not shared with the `process` task.
1. Without closing the terminal, run the task `process` again.
1. Note that the task reuses the terminal now, but doesn't fail. Instead it just produces no output at all, and doesn't seem to signal that it's finished.

### Expected behavior

The `process` task doesn't hang, it just fails.
Its terminal gets reused like the one from `shell`.
Ideally both tasks would emit the exact same sequence events, including both `onDidEndTask` and `onDidEndTaskProcess` so the listener can determine that the task failed.

VS Code version: Code - Insiders 1.63.0-insider (c42793d0357ff9c6589cce79a847177fd42852ee, 2021-11-29T08:08:44.056Z)
OS version: Linux x64 5.15.4-201.fc35.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1567)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|23.24GB (2.03GB free)|
|Process Argv|--disable-extensions .|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593:30376534
vsc1dst:30396469
pythonvs932:30404738
vscexrecpromptt2:30397559
vscop804cf:30404767
vs360:30404995

```

</details>

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #138104

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 1]
```diff
@@ -1312,7 +1312,11 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 		// Set the new shell launch config
 		this._shellLaunchConfig = shell; // Must be done before calling _createProcess()
 
-		this._processManager.relaunch(this._shellLaunchConfig, this._cols || Constants.DefaultCols, this._rows || Constants.DefaultRows, this._accessibilityService.isScreenReaderOptimized(), reset);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1315]: modeled after 

https://github.com/microsoft/vscode/blob/bb8f435388ad119b536d056addd975f2d0a61e67/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1150-L1154

**Comment by meganrogge** [comment]
before:

after:
recording (9)
