### PR TITLE
await available profiles before creating a terminal

### LINKED ISSUE #132150: Powershell console opens every time I launch VS Code with a project
Issue Type: <b>Bug</b>

1. Update to the latest VS Code.
2. Right click VS Code icon on task bar and choose a project to load that doesn't use powershell.

Expected result: Your project loads. 
Actual result: Your project loads and the powershell console window opens, exhorting you to try the new cross-platform Powershell. 

Alternate repro steps: 
1. Navigate in the cmd.exe prompt to a project which contains no powershell code. 
2. Execute `code -n .`

Expected result: Your project loads. 
Actual result: Your project loads and the powershell console window opens, exhorting you to try the new cross-platform Powershell. 

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.21390
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (20.40GB free)|
|Process Argv|--file-uri file:///f%3A/wowbackups/elvui.code-workspace --crash-reporter-id 32772866-2d76-498c-8293-b5f51b9b73de|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.3
exuberant-ctags|chr|0.0.12
coddx-alpha|cod|0.3.1
bracket-pair-colorizer|Coe|1.0.61
supersharp|cra|0.1.4
vscode-markdownlint|Dav|0.43.2
githistory|don|0.6.18
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
gitlens|eam|11.6.0
vscode-drawio|eig|1.0.3
git-project-manager|fel|1.7.1
vscode-pull-request-github|Git|0.30.0
language-cython|guy|0.0.6
vscode-test-explorer|hbe|2.21.1
vscode-drawio|hed|1.6.2
beautify|Hoo|1.5.0
mysql-syntax|jak|1.3.1
sharppad|jma|1.1.0
vscodeilviewer|jos|0.0.1
restructuredtext|lex|162.0.0
vscode-python-test-adapter|lit|0.7.0
MagicPython|mag|1.1.0
vscode-docker|ms-|1.16.1
csharp|ms-|1.23.15
vscode-kubernetes-tools|ms-|1.3.3
mssql|ms-|1.10.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.6.0
powershell|ms-|2021.8.2
test-adapter-converter|ms-|0.1.2
neuron-IPE|neu|1.0.4
autodocstring|njp|0.5.4
errorlens|Phi|1.1.3
platformio-ide|pla|2.3.3
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
cython|tcw|0.1.0
vscodeintellicode|Vis|1.2.14
vscode-todo-highlight|way|1.0.4
material-theme|zhu|3.11.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
vsdyn321cf:30356811
vscus224cf:30358040

```

</details>

### PR DESCRIPTION
**Pull request by meganrogge**

### CODE REVIEW

**Comment by meganrogge** [comment]
@Tyriar see https://github.com/microsoft/vscode/commit/c765e70cf92bc4d2f08bdaa11ed1231063b7aa39#commitcomment-56021309

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 1]
```diff
@@ -507,6 +507,20 @@ export class TerminalService implements ITerminalService {
...
+		const profilesChanged = !equals(result, this._availableProfiles);
+		const contributedProfilesChanged = !equals(this._terminalContributionService.terminalProfiles, this._contributedProfiles);
+		if (profilesChanged || contributedProfilesChanged) {
+			this._availableProfiles = result;
+			this._contributedProfiles = Array.from(this._terminalContributionService.terminalProfiles);
+			this._onDidChangeAvailableProfiles.fire(this._availableProfiles);
+			this._profilesReadyBarrier.open();
+			await this._refreshPlatformConfig(result);
+		}
+	}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:521]: The pattern I usually use for this type of thing is:

```ts
@throttle(2000)
private async _refreshAvailableProfiles(): Promise<void> {
  return this._refreshAvailableProfilesNow();
}

async createTerminal(options?: ICreateTerminalOptions): Promise<ITerminalInstance> {
  if (!this._availableProfiles) {
    await this._refreshAvailableProfilesNow();
  }
  ...
}
```

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalService.ts:521]: that's what I tried first, but didn't work - see https://github.com/microsoft/vscode/pull/132172#issuecomment-913939637

Comment (IllusionMH) [reply src/vs/workbench/contrib/terminal/browser/terminalService.ts:521]: Should work - both `_refreshAvailableProfiles` and `createTerminal` call unthrottled `_refreshAvailableProfilesNow` (notice Now it the end, which is `_initAvailableProfiles` in your code)

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 2]
```diff
@@ -507,6 +507,20 @@ export class TerminalService implements ITerminalService {
 		}
 	}
 
+	private async _refreshAvailableProfilesNow(): Promise<void> {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:510]: We should use this in the throttled method

Comment (IllusionMH) [reply src/vs/workbench/contrib/terminal/browser/terminalService.ts:510]: Also about throttled method - probably it should be changed from `private async _refreshAvailableProfiles(): Promise<void>` to `private _refreshAvailableProfiles(): void` which would match decorated method signature/behavior.
TS at this moment doesn't override method signature with decorated one.

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalService.ts:510]: @IllusionMH maybe you're right as it would reinforce that you should never await `_refreshAvailableProfiles`, we'd just have to avoid using async/await then in favor of `then`

Comment (IllusionMH) [reply src/vs/workbench/contrib/terminal/browser/terminalService.ts:501]: @Tyriar I'm not sure "we'd just have to avoid using async/await then in favor of then"  do you mean don't use `await` and use `.then` instead in this file?

Looks like it not using `await` on non-promise values can be enforced with https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/await-thenable.md so no need for `.then`

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalService.ts:501]: right we weren't awaiting it before anyway, so no changes are required to change the signature

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalService.ts:501]: Nvm, I was thinking if that change was made in isolation, diff looks good

**Review by Tyriar — APPROVED** [review]
