### PR TITLE
Fix #105177 get terminal environment variable to show up in remote co…

### LINKED ISSUE #105177: Terminal environment variable ⚠️ doesn't show up in remote container
I'm not sure if it's isolated to this scenario, but this is where I observed it:

Steps to Reproduce:

1. Open a Node.js dev container, and install js-debug-nightly in there
2. Open a terminal
3. Make your remote settings look like:

  ```
  {
    "terminal.integrated.shell.linux": "/bin/bash",
    "debug.node.autoAttach": "on",
    "debug.javascript.usePreviewAutoAttach": true
  }
  ```

4. Observe that no ⚠️ is shown in the existing terminal 🐛  `echo $NODE_OPTIONS` -- it's empty
5. Open a new terminal. `echo $NODE_OPTIONS` and see that it was applied -- the open terminal just didn't notify on it

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #105177

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts [hunk 1]
```diff
@@ -230,6 +234,27 @@ export class TerminalProcessManager extends Disposable implements ITerminalProce
 		return undefined;
 	}
 
+	// Fetch any extension environment additions and apply them
+	private async _refreshEnvironmentVariables(activeWorkspaceRootUri: URI | undefined, shellLaunchConfig: IShellLaunchConfig): Promise<void> {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts:238]: Since this is only called when a terminal is created let's name it `_setupEnv...` instead of refresh.

File: src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts [hunk 2]
```diff
@@ -230,6 +234,27 @@ export class TerminalProcessManager extends Disposable implements ITerminalProce
...
+		const envFromConfigValue = this._workspaceConfigurationService.inspect<ITerminalEnvironment | undefined>(`terminal.integrated.env.${platformKey}`);
+		const isWorkspaceShellAllowed = this._configHelper.checkWorkspaceShellPermissions();
+		this._configHelper.showRecommendations(shellLaunchConfig);
+		const baseEnv = this._configHelper.config.inheritEnv ? processEnv : await this._terminalInstanceService.getMainProcessParentEnv();
+		const env = terminalEnvironment.createTerminalEnvironment(shellLaunchConfig, envFromConfigValue, terminalEnvironment.createVariableResolver(lastActiveWorkspace, this._configurationResolverService), isWorkspaceShellAllowed, this._productService.version, this._configHelper.config.detectLocale, baseEnv);
+
+		if (!shellLaunchConfig.strictEnv) {
+			this._extEnvironmentVariableCollection = this._environmentVariableService.mergedCollection;
+			this._register(this._environmentVariableService.onDidChangeCollections(newCollection => this._onEnvironmentVariableCollectionChange(newCollection)));
+			this._extEnvironmentVariableCollection.applyToProcessEnvironment(env);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts:250]: Looks like this is already happening for the remote here:

https://github.com/microsoft/vscode/blob/821afe5e92921ced2461d28c27acd19b02aae68a/src/vs/workbench/api/node/extHostTerminalService.ts#L214-L218

Is it just the event forwarding we're missing?

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts (hunk 2 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts:250]: If you look into it, it's more than just forwarding that happens. I didn't think we should copy all of that code into that `extHostTerminalService` and `remoteTerminalChannel`. 
the `_onEnvironmentVariableCollectionChange` method, for instance, with its dependencies.

File: src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts [hunk 3]
```diff
@@ -230,6 +235,28 @@ export class TerminalProcessManager extends Disposable implements ITerminalProce
...
+		const envFromConfigValue = this._workspaceConfigurationService.inspect<ITerminalEnvironment | undefined>(`terminal.integrated.env.${platformKey}`);
+		const isWorkspaceShellAllowed = this._configHelper.checkWorkspaceShellPermissions();
+		this._configHelper.showRecommendations(shellLaunchConfig);
+		const baseEnv = this._configHelper.config.inheritEnv ? processEnv : await this._terminalInstanceService.getMainProcessParentEnv();
+		const env = terminalEnvironment.createTerminalEnvironment(shellLaunchConfig, envFromConfigValue, terminalEnvironment.createVariableResolver(lastActiveWorkspace, this._configurationResolverService), isWorkspaceShellAllowed, this._productService.version, this._configHelper.config.detectLocale, baseEnv);
+
+		if (!shellLaunchConfig.strictEnv) {
+			this._extEnvironmentVariableCollection = this._environmentVariableService.mergedCollection;
+			this._register(this._environmentVariableService.onDidChangeCollections(newCollection => this._onEnvironmentVariableCollectionChange(newCollection)));
+			// for remote terminals, this is a copy of the mergedEnvironmentCollection created on the remote side
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts:251]:
```suggestion
			// For remote terminals, this is a copy of the mergedEnvironmentCollection created on
			// the remote side. Since the environment collection is synced between the remote and
			// local sides immediately this is a fairly safe way of enabling the env var diffing and
			// info widget. While technically these could differ due to the slight change of a race
			// condition, the chance is minimal plus the impact on the user is also not that great
			// if it happens - it's not worth adding plumbing to sync back the resolved collection.
```

**Review by Tyriar — APPROVED** [review]
lgtm after the more detailed comment
