### PR TITLE
adjust command decoration font size and margins based on terminal font size

### LINKED ISSUE #143932: Terminal decorations don't seem to scale with terminal font size
Issue Type: <b>Bug</b>

Found while testing #142894

1. Enable shell integration
1. Run a few commands in the terminal that produce decorations
1. Now scale the terminal font size up or down

**bug**

The decorations don't seem to adjust along with the font size. Here's with a  very small font size:

Screen Shot 2022-02-24 at 4 10 54 PM

And with a very large font size:

Screen Shot 2022-02-24 at 4 11 32 PM

VS Code version: Code - Insiders 1.65.0-insider (Universal) (3112460dc48ce7e557ea9feeaae04b912164b48b, 2022-02-24T05:14:50.798Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|32.00GB (1.11GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d --crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d --crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #143932

See https://github.com/microsoft/vscode/issues/143932#issuecomment-1050463278 which explains the decision to cap the decoration size

### CODE REVIEW

**Comment by meganrogge** [comment]
This is getting deferred because there are ramifications - when you move the terminal from the panel to the editor area and it was the first split for example

**Comment by meganrogge** [comment]
To do:

shouldn't this be factoring in the width/height coming from xterm since those will have been updated to account for zoom/font size changes?

File: src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts [hunk 1]
```diff
@@ -146,6 +147,7 @@ export class XtermTerminal extends DisposableStore implements IXtermTerminal {
 		this.add(this._viewDescriptorService.onDidChangeLocation(({ views }) => {
 			if (views.some(v => v.id === TERMINAL_VIEW_ID)) {
 				this._updateTheme();
+				this._decorationAddon?.refreshLayouts();
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts:150]: this is necessary so when it moves from or to the panel, the correct left margin is used

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 2]
```diff
@@ -28,7 +28,14 @@ const enum DecorationSelector {
 	ErrorColor = 'error',
 	DefaultColor = 'default',
 	Codicon = 'codicon',
-	XtermDecoration = 'xterm-decoration'
+	XtermDecoration = 'xterm-decoration',
+	FirstSplitContainer = '.pane-body.integrated-terminal .terminal-group .monaco-split-view2.horizontal .split-view-view:first-child .xterm'
+}
+
+const enum DecorationStyles {
+	DefaultDimension = 16,
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:36]: using 16 here because that's the default codicon size - there is some overlap when it's the second (third, etc) split terminal, in the editor area or side bar. i tried 12 as the default size and it looked too small IMO.
Screen Shot 2022-02-25 at 10 59 02 AM
t

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:36]: LMK what you think

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 3]
```diff
@@ -57,28 +64,36 @@ export class DecorationAddon extends Disposable implements ITerminalAddon {
...
-				}
-			} else if (e.affectsConfiguration(TerminalSettingId.ShellIntegrationDecorationsEnabled)) {
-				if (!this._configurationService.getValue(TerminalSettingId.ShellIntegrationDecorationsEnabled)) {
-					this._commandStartedListener?.dispose();
-					this._commandFinishedListener?.dispose();
-					this._clearDecorations();
-				}
+				this._refreshClasses();
+			} else if (e.affectsConfiguration(TerminalSettingId.FontSize)) {
+				this.refreshLayouts();
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:74]: We're only taking font size into account here but line height is also important. With lineHeight = 2:

image

This is the difference between char height vs cell height in xterm.

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 4]
```diff
@@ -57,28 +64,36 @@ export class DecorationAddon extends Disposable implements ITerminalAddon {
...
+		this._updateLayout(this._placeholderDecoration?.element);
+		for (const decoration of this._decorations) {
+			this._updateLayout(decoration[1].decoration.element);
+		}
+	}
+
+	private _refreshClasses(): void {
+		this._updateClasses(this._placeholderDecoration?.element);
+		for (const decoration of this._decorations) {
+			this._updateClasses(decoration[1].decoration.element, decoration[1].exitCode);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:93]:
```suggestion
		for (const decoration of this._decorations.values()) {
			this._updateClasses(decoration.decoration.element, decoration.exitCode);
```

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts (hunk 3 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:74]: Screen Shot 2022-02-25 at 1 22 06 PM
