### PR TITLE
Setting a different color for the output view

### LINKED ISSUE #193674: Sticky scroll in output is the wrong color
Repro:

- Use a theme that has the editor as a different color to the panel
- Print a json object to an output channel

Image

### PR DESCRIPTION
**Pull request by aiday-mar**
Fixes https://github.com/microsoft/vscode/issues/193674

### CODE REVIEW

File: src/vs/editor/contrib/stickyScroll/browser/stickyScrollWidget.ts [hunk 1]
```diff
@@ -73,7 +73,11 @@ export class StickyScrollWidget extends Disposable implements IOverlayWidget {
 		this._linesDomNodeScrollable.className = 'sticky-widget-lines-scrollable';
 		this._linesDomNodeScrollable.appendChild(this._linesDomNode);
 
+		const isOutput = this._editor.getModel()?.uri.scheme === 'output';
```
[the remark this answers is not in the document]
Comment (aeschli) [reply src/vs/editor/contrib/stickyScroll/browser/stickyScrollWidget.ts]: Or there's a css class that is part of the pane div that you can use.
Note that the css again should not be defined in the editor layer.

**Comment by aeschli** [comment]
Instead of `panelStickyScroll.background`, make it specific and call it `outputEditorStickyScroll.background".

That follows our guidline to make colors view specific and matches the existing colors `editorStickyScroll.background` and `terminalStickyScroll.background`. 
In general, the sticky scroll color needs to match the background color of the view. If you want, you can add a color `outputEditor.background".

File: src/vs/editor/contrib/stickyScroll/browser/stickyScrollWidget.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (aiday-mar) [reply src/vs/editor/contrib/stickyScroll/browser/stickyScrollWidget.ts]: Ah yes that's a good idea and certainly simplifies the code a lot.

**Comment by aiday-mar** [comment]
Yes that makes sense, I added CSS rules to the panelpart.css file which is inside of the workbench folder and registered two new colors, namely:

```
"--vscode-outputEditor-background"
"--vscode-outputEditorStickyScroll-background"
```

**Comment by aeschli** [comment]
I just found this:
https://github.com/microsoft/vscode/blob/177522431411f4fc6e3149135f56da186f0b5144/src/vs/workbench/contrib/output/browser/outputView.ts#L269

- the output view can also be in the side bar with its own background color 
- `outputEditor.background` color better defaults to `null` so the background can default to the color matching the location. Terminal [does that too](https://github.com/microsoft/vscode/blob/177522431411f4fc6e3149135f56da186f0b5144/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L2527)
- Is suggest also `outputEditorStickyScroll.background` defaults to null and is computed based on the backgrund.
Terminal [does this](https://github.com/microsoft/vscode/blob/177522431411f4fc6e3149135f56da186f0b5144/src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/media/stickyScroll.css#L12) (@Tyriar Looks like terminal sticky scroll should also handle the sidebar)

CSS for the output view not be in panelPart.css, but in it's own css file in the contribution (e.g. src/vs/workbench/contrib/output/browser/output.css)

File: src/vs/workbench/common/theme.ts [hunk 2]
```diff
@@ -401,6 +401,24 @@ export const PANEL_SECTION_BORDER = registerColor('panelSection.border', {
...
 }, localize('panelSectionBorder', "Panel section border color used when multiple views are stacked horizontally in the panel. Panels are shown below the editor area and contain views like output and integrated terminal. Panel sections are views nested within the panels."));
 
+// < --- Output Editor -->
+
+const OUTPUT_EDITOR_BACKGROUND = registerColor('outputEditor.background', {
+	dark: null,
+	light: null,
+	hcDark: null,
+	hcLight: null
+}, localize('outputEditorBackground', "Output editor background color."));
```
Comment (hediet) [inline src/vs/workbench/common/theme.ts:411]: I'm a bit confused, what is this color needed for? And why doesn't it have a default?

Comment (aiday-mar) [reply src/vs/workbench/common/theme.ts:411]: Yes this color is used as the background of the output editor. The reason it does not have a default is because of comment https://github.com/microsoft/vscode/pull/200251#issuecomment-1850282256. Since the color is null, it defaults to the base color of the panel view.

There is also another color, which is the color of the sticky scroll background. This color defaults to the output editor background.

**Review by hediet — APPROVED** [review]

File: src/vs/workbench/common/theme.ts (hunk 2 above)
Comment (hediet) [reply src/vs/workbench/common/theme.ts:411]: Ah, this is because of the `var` fallback value in the added css.

**Comment by aeschli** [comment]
What about the case when the output view is in the editor area or the side bar?
If the new colors are defined, they should be applied in all 3 cases.
If not, it should fall back to pane /editor or sideback background color.

I would have expected that https://github.com/microsoft/vscode/blob/177522431411f4fc6e3149135f56da186f0b5144/src/vs/workbench/contrib/output/browser/outputView.ts#L269
goes away.

**Comment by aeschli** [comment]
Oh, I realize only now, I wouldn't call the color `outputEditor....`. For the user it is not an editor, just a view.
