### PR TITLE
show file/folder path in detail for terminal suggestions, fix details height

### LINKED ISSUE #237818: terminal suggest widget is very wide and details are not visible sometimes
Image

### LINKED ISSUE #237976: Terminal suggest: Show full absolute path in folder/file suggestion detail
This should show the full path of the `bin` dir on the right:

Image

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #237976
fixes #237818

Screenshot 2025-01-21 at 12 27 20 PM

### CODE REVIEW

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts [hunk 1]
```diff
@@ -317,6 +317,7 @@ export class TerminalCompletionService extends Disposable implements ITerminalCo
 					label,
 					provider,
 					kind,
+					detail: getFriendlyFolderPath(stat.resource, resourceRequestConfig.pathSeparator),
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts:320]: Need the file variable of the function that doesn't do the trailing `/`

**Review by Tyriar — DISMISSED** [review]

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts [hunk 2]
```diff
@@ -352,10 +352,10 @@ export class TerminalCompletionService extends Disposable implements ITerminalCo
 	}
 }
 
-function getFriendlyFolderPath(uri: URI, pathSeparator: string): string {
+function getFriendlyFolderPath(uri: URI, pathSeparator: string, isFile?: boolean): string {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts:355]: Would be nice as `getFriendPath` and pass in `kind`?

**Review by Tyriar — DISMISSED** [review]

**Review by Tyriar — DISMISSED** [review]

**Review by Tyriar — APPROVED** [review]
