### PR TITLE
Fix 109906

### LINKED ISSUE #109906: Intellisense shows only one suggestion
Issue Type: <b>Bug</b>

I'm coding in js, css and html and intellisense shows only one suggestion

VS Code version: Code - Insiders 1.51.0-insider (fce8fc82cacf0b4e2a18c633b6c6f3058702a5c9, 2020-11-02T19:45:32.796Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.56GB free)|
|Process Argv|--crash-reporter-id cd7405a1-4997-42c2-abbd-a29c4b00bc6b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|4.4.0
vscode-counter|uct|2.2.0

(1 theme extensions excluded)

</details>

### PR DESCRIPTION
**Pull request by jrieken**
This PR fixes #109906

### CODE REVIEW

File: src/vs/editor/contrib/suggest/suggestController.ts [hunk 1]
```diff
@@ -875,3 +879,20 @@ registerEditorCommand(new SuggestCommand({
...
 	}
 }));
+
+
+registerEditorAction(class extends EditorAction {
+
+	constructor() {
+		super({
+			id: 'editor.action.resetSuggestSize',
+			label: nls.localize('suggest.reset.label', "Reset Suggest Widget Size"),
```
Comment (isidorn) [inline src/vs/editor/contrib/suggest/suggestController.ts:889]: We do not use the word "Widget" in all our commands.
We only have one command with suggest and it is called
"Trigger Suggest"

Due to that I suggest we call this
"Reset Suggest Size"

File: src/vs/editor/contrib/suggest/suggestWidget.ts [hunk 2]
```diff
@@ -162,14 +168,15 @@ export class SuggestWidget implements IDisposable {
 			persistHeight = persistHeight || !!e.north || !!e.south;
 			persistWidth = persistWidth || !!e.east || !!e.west;
 			if (e.done) {
-
-				// only store width or height value that have changed
+				// only store width or height value that have changed and also
+				// only store changes that are above a certain threshold
+				const threshold = Math.floor(this.getLayoutInfo().itemHeight / 3);
```
Comment (isidorn) [inline src/vs/editor/contrib/suggest/suggestWidget.ts:173]: This threshold might be too aggresive for high suggets widget.
E.G my widget is 600 px, I reduce the size to 400 px and the size is not stored.
I suggest to go with item size / 4 or /5

Also should the width threshold be a function of the width?

**Comment by isidorn** [comment]
I have commented in the PR. I will also verify if this indeed fixes the issue...

File: src/vs/editor/contrib/suggest/suggestController.ts (hunk 1 above)
Comment (jrieken) [reply src/vs/editor/contrib/suggest/suggestController.ts:889]: Settings is big in talking about "suggest widget" that why I am using it here

File: src/vs/editor/contrib/suggest/suggestWidget.ts (hunk 2 above)
Comment (jrieken) [reply src/vs/editor/contrib/suggest/suggestWidget.ts:173]: The threshold is based on the item height, that's the height of a single row, not the height of the widget. With defaults it should be 6px but it will scale when larger/smaller fonts are used.

Comment (isidorn) [reply src/vs/editor/contrib/suggest/suggestWidget.ts:173]: Ok, makes sense, but then why not take the height of the whole item? Currently you just take 1/3 of it?

Comment (jrieken) [reply src/vs/editor/contrib/suggest/suggestWidget.ts:173]: I think the full height is too much, I was hovering between 1/3 and 1/2 and ended with 1/3 since that's already something, e.g. half the icon size

**Comment by isidorn** [comment]
I have verified that the `Reset Widget Size` commands works as expected, however I can still easily get the widget to remember the wrong size.
Here are my steps:

1. Open a suggest widget when it can only show 1 item, just slightly resize it via corner sash
2. Open suggest widget where there are more items -> size of 1 is preserved

What seems like a potential regresion, after step 2 if I try to resize the widget to be considerable larger, the size is not preserved.

Here's a gif showing my steps

recording

**Comment by jrieken** [comment]
You are right. There is logic flaw...

**Comment by jrieken** [comment]
Pushed a fix for the flawed comparison. Also increased the threshold to 1/2 item height (9px).

**Comment by isidorn** [comment]
Thank you, let me re-try it...

**Comment by isidorn** [comment]
This now works great -> approved.
Just found one potential corner case (which you do not have to fix as part of this).

1. Reset suggest widget size
2. Open suggest widget when there is only one suggestion
3. Resize suggest widget just a bit (below the threshold)
4. Open the suggest widget where there are mutliple items -> it is small

So I can only reproduce this if I did not have the suggest widget size set explicitly (storage empty)

**Review by isidorn — APPROVED** [review]

**Comment by jrieken** [comment]
> Just found one potential corner case (which you do not have to fix as part of this).

Yeah, you found it... The problem is that after reset (or on very first resize) there is no persisted value to compare (sanitize) against and in that case we go with the current size

**Comment by jrieken** [comment]
@isidorn thanks for the good review

**Comment by isidorn** [comment]
Welcome.

Yeah I thought that is the reason behind the corner case..
