### PR TITLE
Regenerate Client Id when invalid_client is returned

### LINKED ISSUE #250960: MCP Authenthication - VsCode does not evict client when client not be authorized
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.101.0-insider
Commit: f832c6b59a2ed11890f4988a29e85658b092a69a
Date: 2025-06-06T20:43:03.362Z
Electron: 35.5.1
ElectronBuildId: 11708675
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Darwin arm64 24.4.0

Steps to Reproduce:

1. Run the OAuth in-memory demo to try out MCP Authorization in VSCode: [https://github.com/modelcontextprotocol/typescript-sdk/blob/main/src/examples/server/demoInMemoryOAuthProvider.ts](https://github.com/modelcontextprotocol/typescript-sdk/blob/main/src/examples/server/demoInMemoryOAuthProvider.ts)
2. Add your MCP server to the `mcp.servers` setting in the code.
3. Click on "Restart" and follow the instructions to authenticate with the server.
4. Make a test tool call to check if authentication works and if the client was properly registered.
5. Restart your MCP server to flush the client information.
6. The code will send the token on the next request, but the server returns a 400 error when the client cannot be found. However, VSCode retains the client indefinitely. There is not way to delete a client. I had to clean up the global storage to make it work again.

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
Fixes https://github.com/microsoft/vscode/issues/250960

### CODE REVIEW

**Review by anthonykim1 — APPROVED** [review]

File: src/vs/workbench/api/node/extHostAuthentication.ts [hunk 1]
```diff
@@ -292,9 +296,7 @@ export class NodeDynamicAuthProvider extends DynamicAuthProvider {
 				if (isCancellationError(error)) {
 					throw error;
 				}
-				this._logger.error(`Error polling for token: ${error}`);
-				// Continue polling on network errors
-				continue;
+				throw new Error(`Error polling for token: ${error}`);
```
Comment (anthonykim1) [inline src/vs/workbench/api/node/extHostAuthentication.ts:299]: did you wanted to keep the logger here as well?

Comment (TylerLeonhardt) [reply src/vs/workbench/api/node/extHostAuthentication.ts:299]: Nah the error will be logged higher up
