### PR TITLE
Fix textarea sync edge cases

### LINKED ISSUE #196758: Terminal textbox cursor is not in correct position when unfocusing and focusing again
Repro:

1. Windows (maybe not needed?)
2. Set `"terminal.integrated.developer.devMode": true`
3. Open terminal
4. Write some text, note the cursor location
5. Focus an editor
6. Focus the terminal, 🐛 the cursor is at the start of the textbox

image

### PR DESCRIPTION
**Pull request by Tyriar**
- PowerShell is now handled with a specific regex which has an optional space at the end, if matched a space will be added to the end. This is needed because conpty may not 'render' the final space in the prompt.
- Return true in _cursorOnNextLine check if there is a single command as this means it's the first command, so any match should be correct.
- Increase polling to 1000ms (50x20ms) as it was being hit on my machine.

Fixes #196758

Recording 2023-10-30 at 12 53 22

### CODE REVIEW

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 1]
```diff
@@ -442,8 +444,26 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
 		if (!line) {
 			return;
 		}
-		// TODO: fine tune prompt regex to accomodate for unique configurtions.
-		return line.translateToString(true)?.match(/^(?<prompt>(\(.+\)\s)?(?:PS.+>\s)|(?:[A-Z]:\\.*>))/)?.groups?.prompt;
+		// TODO: fine tune prompt regex to accomodate for unique configurations.
```
Comment (meganrogge) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:447]: nit: could move this down to where it's relevant

**Review by meganrogge — APPROVED** [review]
