### PR TITLE
Fix terminal sticky scroll flash when pager 

### LINKED ISSUE #222075: Terminal sticky scroll can show up for 1 frame when using page down in a pager
Repro:

1. On Windows
2. Enable sticky scroll
3. Open pwsh
4. Run `git diff` with more than a page of changes
5. Page up+down, 🐛 sticky scroll will show up for 1 frame every time page down is used

It rarely shows up in the gif due to low recording framerate

Recording 2024-07-18 at 04 46 30

### PR DESCRIPTION
**Pull request by anthonykim1**
Resolves: https://github.com/microsoft/vscode/issues/222075

### CODE REVIEW

File: src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts [hunk 1]
```diff
@@ -193,6 +194,19 @@ export class TerminalStickyScrollOverlay extends Disposable {
 	}
 
 	private _refresh(): void {
+		this._refreshTimeout.clear();
+
+		// Always debounce by 100ms to prevent flashing during rapid scroll/enter events
```
Comment (anthonykim1) [inline src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts]: I've tried wrapping this timeout conditionally for only pager related scenarios, using https://github.com/microsoft/vscode/blob/a3208e218c788bc19d9c915c4612d37ae2650096/src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts#L280-L284 , but found out the current code (Pre-PR) doesn't always detect we are in pager as I enter through the `git diff`.

Hence made this debounce generic(?) here. Curious what you think @Tyriar

File: src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts [hunk 2]
```diff
@@ -193,6 +194,19 @@ export class TerminalStickyScrollOverlay extends Disposable {
...
+		const timeoutId = window.setTimeout(() => {
+			this._executeRefresh();
+		}, 100);
+
+		this._refreshTimeout.value = toDisposable(() => {
```
Comment (anthonykim1) [inline src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts]: Is this how I properly use disposable for timeout?

File: src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts (hunk 1 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts]: `_refresh` actually already has some debouncing but it's at the microtask level:

https://github.com/microsoft/vscode/blob/fb3ad8dfeb2118c3dbf5154c89be35cdf8cb9e58/src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts#L195-L204

You want to debounce the hide -> show transition specifically. And for that you should use the `@debounce` helper

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts (hunk 1 above)
Comment (anthonykim1) [reply src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts]: Sounds good! @Tyriar 
I think `_setVisible` might be the one we want.
And it came out to be one liner.. hahah

File: src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts [hunk 3]
```diff
@@ -185,6 +185,7 @@ export class TerminalStickyScrollOverlay extends Disposable {
 		this._refreshListeners.clear();
 	}
 
+	@debounce(100)
 	private _setVisible(isVisible: boolean) {
 		if (isVisible) {
 			this._ensureElement();
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts]: Almost, I think we need to be more specific here. We want to make sure the debounce only applies going from hidden -> visible. Visible -> hidden should be immediate. So I think we need to split this into 2 functions. Not doing this means stale would stick around a little longer, that's not the end of the world but an unnecessary 100ms delay can make apps feel sluggish.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts (hunk 3 above)
Comment (anthonykim1) [reply src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts]: You're right. Hiding should be immediate, and we should only debounce when showing to prevent flash.
What do you think of https://github.com/microsoft/vscode/pull/262436/commits/718442ddc4896762856616ff78347488258b0e8e ?

**Review by Tyriar — APPROVED** [review]
