### PR TITLE
Fix bug with hanged pseudoterminal

### LINKED ISSUE #84174: PseudoTerminal.open isn't called in some circumstances
I have the following problem in one of the extensions:
- Extension uses Terminal.create with Pseudoterminal API
- In some circumstances pseudoterminal.open isn't called, though, when I resize and close it, events come

In extHostTerminalService I found the following code:
```
		let retries = 5;
		while (retries-- > 0) {
			if (this._terminalProcesses[id]) {
				(this._terminalProcesses[id] as ExtHostPseudoterminal).startSendingEvents(initialDimensions);
				return;
			}
			await timeout(50);
		}
```

It gives only 250ms for terminal to create and it seems that in my circumstances it's not enough. What's worse not even an error message is displayed. It's completely ignored. Could you do something around it, please?

### PR DESCRIPTION
**Pull request by solomatov**
This PR fixes #84174
More time to initialize terminal as well as exponential backoff for wait periods.

### CODE REVIEW

File: src/vs/workbench/api/common/extHostTerminalService.ts [hunk 1]
```diff
@@ -456,14 +456,18 @@ export abstract class BaseExtHostTerminalService implements IExtHostTerminalServ
 		// Processes should be initialized here for normal virtual process terminals, however for
 		// tasks they are responsible for attaching the virtual process to a terminal so this
 		// function may be called before tasks is able to attach to the terminal.
-		let retries = 5;
+		let retries = 8;
+		let currentTimeout = 50;
 		while (retries-- > 0) {
 			if (this._terminalProcesses[id]) {
```
Comment (Tyriar) [inline src/vs/workbench/api/common/extHostTerminalService.ts]: Unfortunately tweaking the timeout to just go longer could still cause the issue on slower machines.

Could we instead just move this to the bottom of `_setupExtHostProcessListeners`? We would want to make sure this is guaranteed to happen after `openPromise` is fired.

Alternatively we could add promises for `_terminalProcesses` like we do for `_getTerminalPromises` (`ExtHostTerminal`) and just rely on the promise instead of polling. This would probably be the better approach.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/api/common/extHostTerminalService.ts (hunk 1 above)
Comment (solomatov) [reply src/vs/workbench/api/common/extHostTerminalService.ts]: Ok. Understood. My thought was that intent was to say that it's an error if we aren't able to establish a terminal, and during refactoring throwing an exception was forgotten.

Comment (Tyriar) [reply src/vs/workbench/api/common/extHostTerminalService.ts]: It would be but it shouldn't ever happen. If we move to the promise-based approach we don't need to do any polling and if for some reason the connection doesn't get made then you will have a broken terminal. That's far better than valid cases where it just took a long time, it will also happen as soon as possible if we use promises rather than waiting for 50ms+ every check.

Comment (solomatov) [reply src/vs/workbench/api/common/extHostTerminalService.ts]: @Tyriar BTW, in _createGetTerminalPromise you have 1s to get terminal, otherwise it returns undefined. Is it normal? For me, it looks like the same error. What's worse undefined value is ignored in most of the cases. Using remoting will lead to arbitrarily long delays due to TCP/IP and all this code will break down in these cases.

Comment (solomatov) [reply src/vs/workbench/api/common/extHostTerminalService.ts]: I mean this code:

```
	private _createGetTerminalPromise(id: number, retries: number = 5): Promise<ExtHostTerminal> {
		return new Promise(c => {
			if (retries === 0) {
				c(undefined);
				return;
			}

			const terminal = this._getTerminalById(id);
			if (terminal) {
				c(terminal);
			} else {
				// This should only be needed immediately after createTerminalRenderer is called as
				// the ExtHostTerminal has not yet been iniitalized
				timeout(200).then(() => c(this._createGetTerminalPromise(id, retries - 1)));
			}
		});
	}
```

Comment (Tyriar) [reply src/vs/workbench/api/common/extHostTerminalService.ts]: Yeah that's a similar problem we should fix, not sure if there's an issue for that one. There's #77655 which is tracking one of the issues that I fixed but needed to get reverted because it broke some tests.

Comment (solomatov) [reply src/vs/workbench/api/common/extHostTerminalService.ts]: @Tyriar I followed a simple solution. I will try to fix the issues with a different PR. We will definitely experience the problems with longer delays. Will create a separate PR for this.

Comment (solomatov) [reply src/vs/workbench/api/common/extHostTerminalService.ts]: @Tyriar So, the tests failed. Do you have any tips on what to do?

Comment (solomatov) [reply src/vs/workbench/api/common/extHostTerminalService.ts]: @Tyriar Do you have any instructions on how to debug them? Or at least run only subset of them?

**Comment by Tyriar** [comment]
You can run these tests with `./scripts/test-integration.sh` (or `.bat`). To skip the other integration tests you can change this:

https://github.com/microsoft/vscode/blob/434662c6cb11b4cad41bd4bf80c23812aeb319d6/extensions/vscode-api-tests/src/singlefolder-tests/terminal.test.ts#L9

To use `suite.only` (but we don't want to commit that).

**Comment by solomatov** [comment]
@Tyriar It seems that finally I made the tests pass. Could you take a look? :-) Glad that you have them. When I made initial change, I didn't find them.

Also, what do you do if a build breaks. Is there a good way to clean everything? I have it all the time when I have yarn watch running, and change branches.

**Comment by solomatov** [comment]
@Tyriar I also have a question for getting rid of delays in other place. There's this code:

```
	// TODO: This could be improved by using a single promise and resolve it when the terminal is ready
	private _getTerminalByIdEventually(id: number, retries: number = 5): Promise<ExtHostTerminal | undefined> {
		if (!this._getTerminalPromises[id]) {
			this._getTerminalPromises[id] = this._createGetTerminalPromise(id, retries);
		} else {
			this._getTerminalPromises[id].then(c => {
				return this._createGetTerminalPromise(id, retries);
			});
		}
		return this._getTerminalPromises[id];
	}
```
Do I understand correctly that the else branch does nothing useful? The then block is activated only if the terminal is found, and the value returned by then has no side effects.

**Comment by Tyriar** [comment]
Will try review soon

> Is there a good way to clean everything? I have it all the time when I have yarn watch running, and change branches.

Typically we don't need to do anything here as TypeScript is pretty good at handling this. If I do get into this state I'll either delete `out` or nuke everything and start from scratch (`git stash` or commit then `git clean -xfd`).

> Do I understand correctly that the else branch does nothing useful? 

I think that was to restart retrying maybe? That TODO is actually talking about how I proposed we fix this; create a bunch of promises and store their resolves instead of using polling.

**Comment by solomatov** [comment]
@Tyriar Are there any updates on this? This fix is very important for us.

**Comment by solomatov** [comment]
@Tyriar Any updates on this?

**Review by Tyriar — APPROVED** [review]
@solomatov I made some changes to simplify the PR. Let me know if this still looks good and if so I'll merge in.

**Comment by solomatov** [comment]
@Tyriar You know this code definitely better than me, and your changes looks good to me, so feel free to merge.

**Comment by solomatov** [comment]
@Tyriar Do you need help resolving this merge?

**Comment by solomatov** [comment]
@Tyriar Remerged again, and hopefully, it will work well.

**Comment by solomatov** [comment]
@Tyriar Seems merged worked this time.
