### PR TITLE
Call revealLastElement within runAtThisOrScheduleAtNextAnimationFrame in repl

### LINKED ISSUE #70331: Debug console scrolls near top after each evaluated line after exception raised in debug console
Issue Type: <b>Bug</b>

See also https://github.com/Microsoft/vscode-python/issues/4725 - but note that `vscode-python` people say they 
> do not control the scrolling behavior of the debug console in VS Code

## Expected behaviour

Debug console behaves normally

## Actual behaviour

Debug console scrolls to top after each evaluated line

## Steps to reproduce:
1. Save this code as Bug.py:
```
import sys
sys.exit()
```
2. Enable breakpoints at "Uncaught exceptions"
3. Debug `Bug.py` in VS Code
4. When hitting SystemExit exception, run `print(1)` in Debug console.
5. Run `sys.exit()` a bunch of times (1-5 times) in the Debug console.
6. Notice that at one point, Debug console scrolls to top
7. Scroll to bottom of Debug console output
8. Run `print(2)` in Debug console.
9. Notice that you don't see `2` due to Debug console scrolling near top again.

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310M CPU @ 2.70GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.91GB (2.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|6.2.0
svn-scm|joh|1.47.1
python|ms-|2019.2.5558
multi-command|ryu|1.3.0
code-settings-sync|Sha|3.2.7

</details>

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes #70331

### CODE REVIEW

**Comment by isidorn** [comment]
Thanks for providing the PR. Added comments in the code

File: src/vs/workbench/contrib/debug/browser/repl.ts [hunk 1]
```diff
@@ -103,6 +103,7 @@ export class Repl extends Panel implements IPrivateReplService, IHistoryNavigati
 	private historyNavigationEnablement: IContextKey<boolean>;
 	private scopedInstantiationService: IInstantiationService;
 	private replElementsChangeListener: IDisposable;
+	private replDelayedRender: IDisposable | null = null;
```
Comment (isidorn) [inline src/vs/workbench/contrib/debug/browser/repl.ts]: Use `undefined` not `null`, we prefer that style in debug.

File: src/vs/workbench/contrib/debug/browser/repl.ts [hunk 2]
```diff
@@ -302,9 +303,13 @@ export class Repl extends Panel implements IPrivateReplService, IHistoryNavigati
 	layout(dimension: dom.Dimension): void {
 		this.dimension = dimension;
 		if (this.tree) {
+			const lastElementVisible = this.tree.scrollTop + this.tree.renderHeight >= this.tree.scrollHeight;
 			const treeHeight = dimension.height - this.replInputHeight;
 			this.tree.getHTMLElement().style.height = `${treeHeight}px`;
 			this.tree.layout(treeHeight, dimension.width);
+			if (lastElementVisible) {
```
Comment (isidorn) [inline src/vs/workbench/contrib/debug/browser/repl.ts]: I do not really like this call here.
When the repl gets layouted if the last element is visible we should reveal it?
Why should we reveal it if it is already visible?
Also on layout seems like a wrong place to call this. Layout happens every time the dimensions of the repl change and on the first render.

File: src/vs/workbench/contrib/debug/browser/repl.ts [hunk 3]
```diff
@@ -354,10 +359,13 @@ export class Repl extends Panel implements IPrivateReplService, IHistoryNavigati
 			}
 			const lastElementVisible = this.tree.scrollTop + this.tree.renderHeight >= this.tree.scrollHeight;
 			this.tree.updateChildren().then(() => {
-				if (lastElementVisible) {
-					// Only scroll if we were scrolled all the way down before tree refreshed #10486
-					revealLastElement(this.tree);
-				}
+				this.replDelayedRender = dom.runAtThisOrScheduleAtNextAnimationFrame(() => {
+					this.replDelayedRender = null;
```
Comment (isidorn) [inline src/vs/workbench/contrib/debug/browser/repl.ts]: This is basically introducing a timeout, which we always try to avoid.
Can we try to fix this issue in a cleaner way?

**Review by isidorn — CHANGES_REQUESTED** [review]

**Comment by isidorn** [comment]
I think this approach is not good, bottom line it just calls reveal more often and with a timeout.
I believe the actual issue is in the provisional measuring of the height of the repl element.
https://github.com/Microsoft/vscode/blob/5ef80a9acde66c587a1de57a0868ac5cd24e6f1b/src/vs/workbench/contrib/debug/browser/repl.ts#L749

Note the height strategy we use with the tree which the repl uses. Repl gives the provisional height of each element so the tree would get an idea of the scroll size, and once the elments are in the dom the tree measuers them actually and adjusts.
So I think the provisional height computation should be improved and that is the root cause of this issue.

Thanks again for jumping on this issue!

File: src/vs/workbench/contrib/debug/browser/repl.ts (hunk 2 above)
Comment (jeanp413) [reply src/vs/workbench/contrib/debug/browser/repl.ts]: I put that extra call to reveal the last element when the inputbox gets resized because otherwise it would be covered. Also when resizing the windows.
console

**Comment by jeanp413** [comment]
Updated the PR with a better approximation for provisional height

**Comment by isidorn** [comment]
Great work, merging in.
Thanks a lot!
