### PR TITLE
Fix async race condition in the tree

### LINKED ISSUE #82290: Reveal in Sidebar crashes
- VSCode Version: 1.39
- OS Version: Darwin x64 18.7.0

This doesn't happen consistently, but every once in a while, this feature would completely crash and I'd have to restart my editor. The steps are as follows:

* I open a folder, I start editing some code.
* I right click the tab name, and click `Reveal in Sidebar`.
* The whole File explorer is highlighted in blue, without my file actually getting highlighted.

I checked the dev tools, and here is the error that gets shown:

```
  ERR TreeError [FileExplorer] Data tree node not found: [object Object]: Error: TreeError [FileExplorer] Data tree node not found: [object Object]
    at WorkbenchAsyncDataTree.getDataNode (file:///Applications/VS Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:64272:23)
    at WorkbenchAsyncDataTree.reveal (file:///Applications/VS Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:64253:35)
    at ExplorerView.onSelectResource (file:///Applications/VS Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:292485:31)
```

I traced it down to this line:
https://github.com/microsoft/vscode/blob/b0dccbcf75fd03ac8cc0fa94da5c552a4f47309d/src/vs/base/browser/ui/tree/asyncDataTree.ts#L650

Which indiates that tree items are refreshed/updated somehow, but the key used to look up this map is still referring to the old object? Should this map be indexed by something else? item id (string)?

### PR DESCRIPTION
**Pull request by solomatov**
This PR fixes #82290

The following was done:
- Introduced _isDisposed field on the ExplorerItem class
- Set it to true when children are deleted from the active tree
- Check that nodes are not disposed in the code revealing resource, and if they are disposed start over

### CODE REVIEW

**Comment by isidorn** [comment]
Thank you for the PR and your investigation from #82290
At the end of the day you are checking if the item got disposed and if yes start over. In theory none of the items should be disposed which are in the model, so we can try to fix this one level sooner?
Maybe instead of introducing the whole `dispose` logic we should fire the `onDidSelectResource` with a timeout of 0 [here](https://github.com/Microsoft/vscode/blob/0bf0936b819aec3789ed9d95b6a1d34868f825db/src/vs/workbench/contrib/files/common/explorerService.ts#L183). Or react with a timeout [here](https://github.com/Microsoft/vscode/blob/0bf0936b819aec3789ed9d95b6a1d34868f825db/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L198)

@solomatov did you also check that your fix trully fixes the issue
@joaomoreno can you also take a look, would be interested in what you have to say. Thanks

File: src/vs/workbench/contrib/files/browser/views/explorerView.ts [hunk 1]
```diff
@@ -534,12 +534,18 @@ export class ExplorerView extends ViewletPanel {
 			.sort((first, second) => second.resource.path.length - first.resource.path.length)[0];
 
 		while (item && item.resource.toString() !== resource.toString()) {
+			if (item.isDisposed) {
+				return this.onSelectResource(resource, reveal);
```
Comment (joaomoreno) [inline src/vs/workbench/contrib/files/browser/views/explorerView.ts]: This is cool, but can get into an endless loop if the model gets inconsistent.

File: src/vs/workbench/contrib/files/browser/views/explorerView.ts [hunk 2]
```diff
@@ -534,12 +534,18 @@ export class ExplorerView extends ViewletPanel {
...
+			}
 			await this.tree.expand(item);
 			item = first(values(item.children), i => isEqualOrParent(resource, i.resource));
 		}
 
 		if (item && item.parent) {
 			if (reveal) {
+				if (item.isDisposed) {
+					return this.onSelectResource(resource, reveal);
```
Comment (joaomoreno) [inline src/vs/workbench/contrib/files/browser/views/explorerView.ts]: Same here. I would simply retry only once.

**Review by joaomoreno — COMMENTED** [review]
Overall this makes sense. Given that the model has a `forgetChildren`, it serves as a great starting point to remember that those children should not be give to the tree.

**Comment by solomatov** [comment]
@isidorn Concerning the applicability of this, my understanding of the problem is that children are loaded asynchronously, and we can't do anything with it. It's nodejs, and if we use sync calls, UI wouldn't be so responsive.

File: src/vs/workbench/contrib/files/browser/views/explorerView.ts (hunk 1 above)
Comment (solomatov) [reply src/vs/workbench/contrib/files/browser/views/explorerView.ts]: I fixed it.

**Comment by isidorn** [comment]
Let's go with this PR and push it to insiders to get user feedback.
The code is not so nice, but it is a decent workaround until we get something better.
Thank you for your PR @solomatov
