### PR TITLE
Button - add label getter

### LINKED ISSUE #177980: SCM view is broken
image

Not showing any changes

Error in console when running from sources

```
Cannot read properties of undefined (reading 'value'): TypeError: Cannot read properties of undefined (reading 'value')
    at renderMarkdownAsPlaintext (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/markdownRenderer.js:406:30)
    at renderStringAsPlaintext (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/markdownRenderer.js:398:54)
    at new ButtonWithDropdown (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/button/button.js:198:127)
    at SCMActionButton.setButton (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/workbench/contrib/scm/browser/scmViewPane.js:2035:31)
    at ActionButtonRenderer.renderElement (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/workbench/contrib/scm/browser/scmViewPane.js:39:39)
    at CompressibleRenderer.renderElement (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/tree/objectTree.js:65:31)
    at TreeRenderer.renderElement (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/tree/abstractTree.js:288:27)
    at PipelineRenderer.renderElement (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/list/listWidget.js:861:26)
    at ListView.insertItemInDOM (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/list/listView.js:605:23)
    at ListView._splice (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/list/listView.js:401:26)
    at ListView.splice (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/list/listView.js:319:29)
    at vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/list/splice.js:14:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/list/splice.js:14:30)
    at vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/list/listWidget.js:1113:67
    at EventBufferer.bufferEvents (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/common/event.js:957:23)
    at TreeNodeList.splice (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/list/listWidget.js:1113:32)
    at TreeNodeList.splice (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/tree/abstractTree.js:1069:19)
    at Object.splice (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:273:22)
    at IndexTreeModel.spliceSimple (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:163:27)
    at IndexTreeModel.splice (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/tree/indexTreeModel.js:63:22)
    at ObjectTreeModel._setChildren (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:66:24)
    at ObjectTreeModel.setChildren (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/tree/objectTreeModel.js:31:18)
    at CompressedObjectTreeModel._setChildren (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:158:24)
    at CompressedObjectTreeModel.setChildren (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:104:22)
    at CompressibleObjectTreeModel.setChildren (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:324:24)
    at WorkbenchCompressibleObjectTree.setChildren (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/tree/objectTree.js:122:24)
    at ViewModel.refresh (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/workbench/contrib/scm/browser/scmViewPane.js:994:27)
    at ViewModel._onDidChangeVisibleRepositories (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/workbench/contrib/scm/browser/scmViewPane.js:917:18)
    at ViewModel.setVisible (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/workbench/contrib/scm/browser/scmViewPane.js:962:22)
    at Listener.invoke (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/common/event.js:530:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/common/event.js:706:38)
    at Emitter.fire (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/common/event.js:670:37)
    at SCMViewPane.setVisible (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/workbench/browser/parts/views/viewPane.js:133:53)
    at vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/workbench/browser/parts/views/viewPaneContainer.js:507:37
    at Array.map (<anonymous>)
    at SCMViewPaneContainer.setVisible (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/workbench/browser/parts/views/viewPaneContainer.js:507:18)
    at PaneContainer.setVisible (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/workbench/browser/panecomposite.js:34:37)
    at SidebarPart.showComposite (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/workbench/browser/parts/compositePart.js:171:23)
    at SidebarPart.doOpenComposite (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/workbench/browser/parts/compositePart.js:73:18)
    at SidebarPart.openComposite (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/workbench/browser/parts/compositePart.js:46:25)
    at SidebarPart.doOpenViewlet (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:177:25)
    at SidebarPart.openPaneComposite (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:141:29)
    at ViewContainerActivityAction.run (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/workbench/browser/parts/activitybar/activitybarActions.js:60:42)
    at ActionRunner.runAction (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/common/actions.js:114:26)
    at ActionRunner.run (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/common/actions.js:106:28)
    at CompositeActionViewItem.onClick (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/actionbar/actionViewItems.js:113:31)
    at HTMLLIElement.<anonymous> (vscode-file://vscode-app/Users/sandy081/work/vscode/out/vs/base/browser/ui/actionbar/actionViewItems.js:97:26)
```

### PR DESCRIPTION
**Pull request by lszomoru**
Fixes https://github.com/microsoft/vscode/issues/177980

### CODE REVIEW

File: src/vs/base/browser/ui/button/button.ts [hunk 1]
```diff
@@ -193,6 +194,14 @@ export class Button extends Disposable implements IButton {
 	}
 
 	set label(value: string | IMarkdownString) {
+		if (typeof this._label === 'string' && typeof value === 'string' && this._label === value) {
```
Comment (joaomoreno) [inline src/vs/base/browser/ui/button/button.ts:197]: Simplify:

```suggestion
		if (this._label === value) {
```

**Review by joaomoreno — DISMISSED** [review]

**Review by hediet — APPROVED** [review]
