### PR TITLE
Suggest widget set aria active descendent

### LINKED ISSUE #3787: Autocomplete accessibility glitch
There's something odd going on when typing actual code into Vs Code. To reproduce:
1. Create a file called index.html.
2. Type <html> .
3. Press enter.
Expected behavior:
The cursor goes to the next line.
Perceived behavior:
Nothing actually happens. You have to press Enter again to go to the next line.

Expected cause: I think an autocomplete list pops up that the accessibility stack isn't aware of. Pressing the first enter likely selects the first option in this list.
Problem with this hypothesis: Arrowing up and down should make different things happen if my theory is correct, however it doesn't seem to do that. Therefore I am not a 100% sure I am correct, someone comment on it to check please.
I think fixing this so the prsumed opup is correctly handled should be the next step for accessibility of this product.

### PR DESCRIPTION
**Pull request by isidorn**
This PR:
* Adds the `setAria` api to the Editor, that gets passed to the `textAreaHandler`
* Adopts the `setAria` api in the Suggest widget. This way the suggest widget no longer uses the `aria.alert`
* Refactors how aria labels are set for `CompletionItems` and the `details`. Overall things should be simpler now in the `SuggestWidget`

Fixes https://github.com/microsoft/vscode/issues/3787
Please note that I have tested this on my macOS Catalina and it works just fine. I plan to test it on windows when I am get back to the office next week.

@alexdima let me know what you think
fyi @zersiax @jrieken 
We can still fine tune what is exactly being read and if there are still issues.

### CODE REVIEW

File: src/vs/editor/contrib/suggest/suggestWidget.ts [hunk 1]
```diff
@@ -162,6 +165,7 @@ class Renderer implements IListRenderer<CompletionItem, ISuggestionTemplateData>
 		const data = <ISuggestionTemplateData>templateData;
 		const suggestion = (<CompletionItem>element).completion;
 
+		data.root.id = getAriaId(_index);
```
Comment (jrieken) [inline src/vs/editor/contrib/suggest/suggestWidget.ts]: no more underscore for _index? (now that it is used...)

File: src/vs/editor/contrib/suggest/suggestWidget.ts [hunk 2]
```diff
@@ -521,7 +513,22 @@ export class SuggestWidget implements IContentWidget, IListVirtualDelegate<Compl
 		this.list = new List('SuggestWidget', this.listElement, this, [renderer], {
 			useShadows: false,
 			openController: { shouldOpen: () => false },
-			mouseSupport: false
+			mouseSupport: false,
+			accessibilityProvider: {
+				getAriaLabel: (item: CompletionItem) => {
+					if (this.expandDocsSettingFromStorage()) {
+						const { documentation, detail } = item.completion;
+						const docs = strings.format(
```
Comment (jrieken) [inline src/vs/editor/contrib/suggest/suggestWidget.ts]: This is tricky... Usually, detail and documentation aren't defined and the UI triggers that when an item gains focus. I don't think tho that this call is sync'd on that and what you get is likely indeterministic. You should be able to call `resolve` on the item but you need to know how long you can "wait" for its result...

**Review by jrieken — CHANGES_REQUESTED** [review]

File: src/vs/editor/contrib/suggest/suggestWidget.ts (hunk 1 above)
Comment (isidorn) [reply src/vs/editor/contrib/suggest/suggestWidget.ts]: Updated, thanks.

File: src/vs/editor/contrib/suggest/suggestWidget.ts (hunk 2 above)
Comment (isidorn) [reply src/vs/editor/contrib/suggest/suggestWidget.ts]: Yes, I missed this. 
However this is just working since once the suggestion details and docs get resolved the item will get re-rendered by the `splice` call [here](https://github.com/Microsoft/vscode/blob/21731345de457a1e3463b16283ba29ae799d9f62/src/vs/editor/contrib/suggest/suggestWidget.ts#L692).
When the item gets rerendered we will return deterministicly the correct aria label since the item already got resolved.

I can not wait in the `getAriaLabel` call since it is not async.

Idealy the method would also check if the item is resolved, if not just return the `label`. However not sure how to check that.
I am open for suggestions.

Comment (jrieken) [reply src/vs/editor/contrib/suggest/suggestWidget.ts]: Yeah, would just be nicer if we wouldn't read it twice. To know if its resolved, you can add a boolean to the `CompletionItem` which knows that resolving is done.

Comment (isidorn) [reply src/vs/editor/contrib/suggest/suggestWidget.ts]: As you suggested I have added a `isResolved` boolean to the `CompletionItem`. So when we compute the aria label if the item is not resolved we will only read the `label`.
Let me know what you think.

Comment (jrieken) [reply src/vs/editor/contrib/suggest/suggestWidget.ts]: Yeah, looking better now

**Comment by zersiax** [comment]
Once this hits Insiders', I can give you test results for NVDA on WIndows. You only tested with VoiceOver on OS X so far, correct?

**Comment by isidorn** [comment]
@zersiax correct. If everything goes well this should hit insiders some time next week, most probably Tuesday or Wednesday. Thanks a lot!

**Review by alexdima — APPROVED** [review]
LGTM, thank you!!

Just a few small things I left comments for.

**Comment by isidorn** [comment]
Thanks a lot for the review.
@zersiax you can try it out with vscode insiders from next Monday. Thanks!

**Comment by zersiax** [comment]
@isidorn confirmed, will let you know monday or tuesday ;)
