### PR TITLE
Fixes #152088 - Adds various editor gutter tooltips

### LINKED ISSUE #152088: Provide tooltip for gutter actions
Originally from testing out https://github.com/microsoft/vscode/issues/25887

When hovering items in the gutter, we don't provide any tooltip for additional information about what each item is and does (with the exception of an added breakpoint). We should provide this additional information as we already for other actions and for added breakpoints to give new users and indication of the action will do as well as a name for the given action:

- [x] Adding breakpoints
- [x] SCM decorators
- [x] Diff arrow decorators
- [x] Folding regions

https://user-images.githubusercontent.com/35271042/173626852-14bd4b48-bed5-49f7-b1fb-06ddc164c1d2.mp4

### PR DESCRIPTION
**Pull request by hediet**
Fixes #152088 - Adds various editor gutter tooltips

Image

Image

Image

### CODE REVIEW

**Review by benibenj — DISMISSED** [review]

File: src/vs/base/common/strings.ts [hunk 1]
```diff
@@ -48,6 +48,19 @@ export function format2(template: string, values: Record<string, unknown>): stri
...
+		switch (ch) {
+			case '<': return '&lt;';
+			case '>': return '&gt;';
+			case '"': return '&quot;';
+			case '\'': return '&apos;';
+			case '&': return '&amp;';
+		}
+		return ch;
+	});
+}
```
Comment (alexdima) [inline src/vs/base/common/strings.ts:62]: Since changing this function could lead to XSS injection, could we please add documentation explaining this and also unit tests?

**Review by alexdima — CHANGES_REQUESTED** [review]
Small request to document + unit test the function since it should never be touched.

**Review by alexdima — APPROVED** [review]
