### PR TITLE
Fixes cannot install web extension using remote cli

### LINKED ISSUE #144521: Cannot install web extension using remote cli
- VS Code Version: stable and from sources

Steps to Reproduce:

1. Run code-server
2. Open terminal and use remote cli to install vim extension
3. :bug: vim extension cannot be installed and the following error shows in terminal `Cannot install the 'vscodevim.vim' extension because it is declared to not run in this setup.`

It should be possible to install vim extension after #141322 , now that it's possible to run an extension installed in the remote inside the web worker

### PR DESCRIPTION
**Pull request by jeanp413**
This PR fixes #144521

### CODE REVIEW

File: src/vs/workbench/api/browser/mainThreadCLICommands.ts [hunk 1]
```diff
@@ -111,7 +111,9 @@ class RemoteExtensionCLIManagementService extends ExtensionManagementCLIService
 	}
 
 	protected override validateExtensionKind(manifest: IExtensionManifest, output: CLIOutput): boolean {
-		if (!this._extensionManifestPropertiesService.canExecuteOnWorkspace(manifest)) {
+		if (!this._extensionManifestPropertiesService.canExecuteOnWorkspace(manifest)
+			// Web extensions installed on remote can be run in web worker extension host
+			&& !this._extensionManifestPropertiesService.canExecuteOnWeb(manifest)) {
```
Comment (sandy081) [inline src/vs/workbench/api/browser/mainThreadCLICommands.ts:116]: Please add `isWeb` check because it is allowed only in web

**Review by sandy081 — CHANGES_REQUESTED** [review]

File: src/vs/workbench/api/browser/mainThreadCLICommands.ts (hunk 1 above)
Comment (jeanp413) [reply src/vs/workbench/api/browser/mainThreadCLICommands.ts]: done :+1:

**Review by sandy081 — APPROVED** [review]
