### PR TITLE
detect ghost text more broadly

### LINKED ISSUE #233799: Handle fish ghost text suggestions in the prompt input model
We need to adjust for ghost text, that's why it's not working ATM.

https://github.com/microsoft/vscode/blob/499475f2ff2d07e4bcdfb69eaba2a8c67d3d4f46/extensions/terminal-suggest/src/terminalSuggestMain.ts#L42-L52

### PR DESCRIPTION
**Pull request by meganrogge**
fixes https://github.com/microsoft/vscode/issues/233799

### CODE REVIEW

**Review by Tyriar — DISMISSED** [review]

File: src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts [hunk 1]
```diff
@@ -440,12 +442,50 @@ export class PromptInputModel extends Disposable implements IPromptInputModel {
...
+					// ghost text style
+					while (x < line.length) {
+						const cell = line.getCell(x++);
+						if (!cell || cell.getCode() === 0) {
+							break;
+						}
+
+						if (!this._cellStylesMatch(ghostTextCell, cell)) {
+							ghostTextIndex = -1;
+							break;
```
Comment (connor4312) [inline src/vs/platform/terminal/common/capabilities/commandDetection/promptInputModel.ts:457]: Should this return -1 instead? I think the `= -1` is a no-op because it gets overwritten down below

**Review by rzhao271 — APPROVED** [review]
