### PR TITLE
On escape place focus back into editor

### LINKED ISSUE #186223: Focusing hover still breaks keyboard navigation
Does this issue occur when all extensions are disabled?: Yes

- VS Code Insiders Version: `1.80.0-insider b4952d14a465572e33f0635ef58de089227b8876`
- VS Code Version: `1.79.2 695af097c7bd098fbf017ce3ac85e09bbc5dda06`
- OS Version: Ubuntu 22.04.2 LTS

Steps to Reproduce:

> 1. Press Cmd K, Cmd I twice on a symbol which has a hover.
> 2. Press Escape
> 3. Press UpArrow or DownArrow
> bug Nothing happens, since focus didn't return to the editor after pressing Escape.

This issue is identical to #177806 which was supposedly fixed by #177859. I do not have a windows machine atm, so I cannot test if this is exclusively an issue with the snap-installed version of vscode, but I highly doubt it is.

`shift-tab` does give focus back to editor, but that's just a workaround.

### PR DESCRIPTION
**Pull request by aiday-mar**
Fixes https://github.com/microsoft/vscode/issues/186223

### CODE REVIEW

File: src/vs/editor/contrib/hover/browser/contentHover.ts [hunk 1]
```diff
@@ -730,15 +726,12 @@ export class ContentHoverWidget extends ResizableContentWidget {
 		if (!this._visibleData) {
 			return;
 		}
```
Comment (jrieken) [inline src/vs/editor/contrib/hover/browser/contentHover.ts:728]: Unsure about removing this. Looks like this was the only reader of `stoleFocus` and we either remove it alltogether or validate when/why is used

**Review by jrieken — CHANGES_REQUESTED** [review]

File: src/vs/editor/contrib/hover/browser/contentHover.ts (hunk 1 above)
Comment (aiday-mar) [reply src/vs/editor/contrib/hover/browser/contentHover.ts:728]: Indeed, I placed it back. The variable stoleFocus now also checks the value of focusedHoverKey.

**Review by jrieken — APPROVED** [review]
