### PR TITLE
Emmet: Select next/previous item does not work with script tag.

### LINKED ISSUE #113515: Emmet Select Item does not select into script tags
Version: 1.53.0-insider (user setup)
Commit: 4a875e23d20b64504a818834f3fa4c40adb8d480
Date: 2020-12-21T12:33:38.481Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.19042

1. Create an HTML file with the following contents
```html
<script type="text/plain">
  <p></p>
</script>```

2. Place the cursor within the text/plain string
3. Run 'Emmet: Select Next Item' command

Expected: Emmet selects the opening `p` tag
Actual: Emmet does nothing

### PR DESCRIPTION
**Pull request by vinku**
This PR fixes #113515

**_Issue_**: Emmet select does not work with html script tags. 

**_Reason_**: The reason is that the html subtree corresponding to the script tag is not generated and as a result, emmet does not select into the script tag.

**_Fix_**: Whenever we are fetching the HTML node corresponding to a position, if we end up in fetching a script tag, then we would set up the the script node subtree and then again fetch the HTML node corresponding to the same position. This way we would be able to parse/select contents which are child of the <script> tags.

**_Validations_**: Verified that the scenario mentioned in the tag is working after these changes + other manual verification of select next/previous item.

### CODE REVIEW

File: extensions/emmet/src/selectItemHTML.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ export function nextItemHTML(document: vscode.TextDocument, selectionStart: vsco
 	if (currentNode.type !== 'comment') {
 		// If cursor is in the tag name, select tag
 		if (currentNode.open &&
-			selectionEndOffset < currentNode.open.start + currentNode.name.length) {
+			selectionEndOffset <= currentNode.open.start + currentNode.name.length) {
```
Comment (rzhao271) [inline extensions/emmet/src/selectItemHTML.ts:22]: Can you give an example where this change is needed?

File: extensions/emmet/src/util.ts [hunk 2]
```diff
@@ -380,30 +380,34 @@ export const allowedMimeTypesInScriptTag = ['text/html', 'text/plain', 'text/x-t
...
 export function getHtmlFlatNode(documentText: string, root: FlatNode | undefined, offset: number, includeNodeBoundary: boolean): HtmlFlatNode | undefined {
-	const currentNode: HtmlFlatNode | undefined = <HtmlFlatNode | undefined>getFlatNode(root, offset, includeNodeBoundary);
+	let currentNode: HtmlFlatNode | undefined = <HtmlFlatNode | undefined>getFlatNode(root, offset, includeNodeBoundary);
 	if (!currentNode) { return; }
 
-	const isTemplateScript = currentNode.name === 'script' &&
-		(currentNode.attributes &&
-			currentNode.attributes.some(x => x.name.toString() === 'type'
+	// If the currentNode is a script one, first set up its subtree and then find HTML node.
+	if (currentNode.name === 'script' && currentNode.children.length === 0) {
```
Comment (rzhao271) [inline extensions/emmet/src/util.ts:387]: Why do we check if `children.length` is 0?

File: extensions/emmet/src/util.ts [hunk 3]
```diff
@@ -380,30 +380,34 @@ export const allowedMimeTypesInScriptTag = ['text/html', 'text/plain', 'text/x-t
...
+		const endToUse = scriptNode.close ? scriptNode.close.start : scriptNode.end;
+		const scriptBodyText = beforePadding + documentText.substring(scriptNode.open.end, endToUse);
 		const innerRoot: HtmlFlatNode = parse(scriptBodyText);
-		const scriptBodyNode = getHtmlFlatNode(scriptBodyText, innerRoot, offset, includeNodeBoundary);
-		if (scriptBodyNode) {
-			scriptBodyNode.parent = currentNode;
-			currentNode.children.push(scriptBodyNode);
-			return scriptBodyNode;
-		}
+		innerRoot.children.forEach(child => {
```
Comment (rzhao271) [inline extensions/emmet/src/util.ts:406]: Does this change still work when one decides to nest multiple `<script type="text/plain">` tags?
Also, this change could affect some other command behaviours, such as Balance In/Out, so just a reminder that those Emmet commands also need to be tested as part of this change.

Comment (vinku) [reply extensions/emmet/src/util.ts:406]: I can make changes to accommodate nested script tags but that is not a valid HTML
https://rules.sonarsource.com/html/RSPEC-4645

File: extensions/emmet/src/selectItemHTML.ts (hunk 1 above)
Comment (vinku) [reply extensions/emmet/src/selectItemHTML.ts:22]: Consider this with your cursor between **i** and **v** in the very first line 
`<div>
      <span></span>
</div>
`

It should select the `<div>` tag but it selects the child `<span>`. This is because the condition changed in the code does not consider this cursor position as part of the current node.

File: extensions/emmet/src/util.ts (hunk 3 above)
Comment (vinku) [reply extensions/emmet/src/util.ts:406]: So I think this would be un-necessary to support it. WDYT?

File: extensions/emmet/src/util.ts (hunk 2 above)
Comment (vinku) [reply extensions/emmet/src/util.ts]: removed it.

File: extensions/emmet/src/util.ts [hunk 4]
```diff
@@ -380,30 +380,34 @@ export const allowedMimeTypesInScriptTag = ['text/html', 'text/plain', 'text/x-t
...
+	let currentNode: HtmlFlatNode | undefined = <HtmlFlatNode | undefined>getFlatNode(root, offset, includeNodeBoundary);
 	if (!currentNode) { return; }
 
-	const isTemplateScript = currentNode.name === 'script' &&
-		(currentNode.attributes &&
-			currentNode.attributes.some(x => x.name.toString() === 'type'
+	// If the currentNode is a script one, first set up its subtree and then find HTML node.
+	if (currentNode.name === 'script') {
+		setUpScriptNodeSubtree(documentText, currentNode);
+		currentNode = <HtmlFlatNode | undefined>getFlatNode(root, offset, includeNodeBoundary);
```
Comment (rzhao271) [inline extensions/emmet/src/util.ts:389]: Do we have to re-search from the root in this case?

File: extensions/emmet/src/util.ts (hunk 3 above)
Comment (rzhao271) [reply extensions/emmet/src/util.ts:406]: We don't need to support that case then. Thanks for checking!

File: extensions/emmet/src/util.ts (hunk 4 above)
Comment (rzhao271) [reply extensions/emmet/src/util.ts:389]: @vinku bump

Comment (vinku) [reply extensions/emmet/src/util.ts:389]: I will try if we can restrict it today.

File: extensions/emmet/src/util.ts (hunk 2 above)
Comment (vinku) [reply extensions/emmet/src/util.ts]: @rzhao271 , I am actually adding this check back.

It handles the following case:
Let's say we run this command multiple times without making any edits to the content of the file.

`<script type="text/plain">
  <p></p>
</script>`

First time, in the HTML tree corresponding to the document-root, there will have no children for the script tag and we would create one children.

Second time, in the HTML tree corresponding  to the document-root, there will be one child for the script tag (The one we added in previous step). If we dont have this check, we would add another child which would make script node having 2 children (which is incorrect)

Third time, in the HTML tree corresponding  to the document-root, there will be two children for the script tag (The one  previous step). if we dont have this check, we would add another child which would make script node having 2 children (which again is incorrect as it should have 1 children only)


So if the file is not edited, looks like there is some cached HTML tree that is returned and running this command more that 1 times would result in wrong HTML tree structure (a one that does not correspond to the text in the file).

So adding a 0 check to ensure that we don't add children to the script-node that has already been set up. Alternative approach is to clear the children array of script-node before setting up its subtree but that would again be not as performant as this check.

File: extensions/emmet/src/util.ts (hunk 4 above)
Comment (vinku) [reply extensions/emmet/src/util.ts]: ok, searching inside currentNode (i.e the script node, if that returns null, then the script-node is the node we need).

**Review by rzhao271 — APPROVED** [review]
LGTM, thanks!
