### PR TITLE
fix repl find being jumpy bug

### LINKED ISSUE #225295: debug console find causes tree to jump to bottom
1. have a debug console filled with output
2. search using `ctrlCmd+alt+f`
3. as you type input, the tree jumps and scrolls to the bottom

https://github.com/user-attachments/assets/58833f7a-470b-47c1-9294-1256b2a8e257

### PR DESCRIPTION
**Pull request by meganrogge**
fix #225295

before:

https://github.com/user-attachments/assets/30184ed4-72df-48c7-8856-f2bf5fa0bce7

after:

https://github.com/user-attachments/assets/a2c8f360-df79-4ef4-a398-65b326963f31

### CODE REVIEW

**Review by roblourens — APPROVED** [review]

File: src/vs/workbench/contrib/debug/browser/repl.ts [hunk 1]
```diff
@@ -237,7 +237,9 @@ export class Repl extends FilterViewPane implements IHistoryNavigationWidget {
 			this.filter.filterQuery = this.filterWidget.getFilterText();
```
Comment (roblourens) [inline src/vs/workbench/contrib/debug/browser/repl.ts:237]: I don't totally follow this, is it right that this event is for when the (old) filter widget text changes? But you're typing in the new one?

Comment (meganrogge) [reply src/vs/workbench/contrib/debug/browser/repl.ts:237]: this didn't actually fix the bug 🤦🏼‍♀️ . I just wasn't reproducing it. This should be reverted - it's not causing issues though, so will wait on the real fix https://github.com/microsoft/vscode/pull/225300
