### PR TITLE
fix #259057

### LINKED ISSUE #259057: Chat participant contributed from `chatSessions` contribution shows up in the panel chat
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Have PR extension installed
2. Have chat sessions enabled per https://github.com/microsoft/vscode/issues/258320
3. Type `@copilot` in a non-chat sessions editor.
4. 🐛 nothing happens

see: https://github.com/microsoft/vscode/issues/258691#issuecomment-3139419733

### PR DESCRIPTION
**Pull request by joshspicer**
closes https://github.com/microsoft/vscode/issues/259057
Temporary fix until we have API to initiate new sessions from the chat participant

### CODE REVIEW

File: src/vs/workbench/contrib/chat/browser/chatSessions.contribution.ts [hunk 1]
```diff
@@ -475,6 +478,21 @@ class CodingAgentChatImplementation extends Disposable implements IChatAgentImpl
...
 		if (chatSession?.requestHandler) {
 			await chatSession.requestHandler(request, progress, [], token);
+		} else {
+			// TODO(jospicer): Temporary while we work on API for dynamic agent to trigger a session
+			const content = new MarkdownString(
+				localize('chatSessionNotFound', "Use `#copilotCodingAgent` to begin a new [coding agent session]({0}).", CODING_AGENT_DOCS),
+				{
+					isTrusted: true,
+					supportHtml: true,
+				}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/chat/browser/chatSessions.contribution.ts]: Do you need these?

Comment (joshspicer) [reply src/vs/workbench/contrib/chat/browser/chatSessions.contribution.ts]: Thanks, looks like I don't. Updated.

**Review by mjbvz — APPROVED** [review]
