### PR TITLE
Ensure nb cell source uses LF instead of CRLF

### LINKED ISSUE #125132: Detect line break in notebook cell content
Issue Type: <b>Bug</b>

* Open a notebook which uses `\n` as line break on Windows
* Edit a cell, undo, save
* The document becomes dirty on SCM

What happens under the hood is now the cell is saved with `\r\n`.

VS Code version: Code - Insiders 1.57.0-insider (1e446dfadf588ec28b3fdba7ac083bfa1d45df3c, 2021-06-01T05:13:48.346Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.22GB free)|
|Process Argv|--enable-proposed-api joyceerhl.vscode-pyolite --crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by DonJayamanne**
Unfortunately I don't have windows, will need to test this out on windows, give me some time to get this tested.

This PR fixes #125132

### CODE REVIEW

File: extensions/ipynb/src/notebookSerializer.ts [hunk 1]
```diff
@@ -91,6 +91,7 @@ export class NotebookSerializer implements vscode.NotebookSerializer {
 		const indentAmount = data.metadata && 'indentAmount' in data.metadata && typeof data.metadata.indentAmount === 'string' ?
 			data.metadata.indentAmount :
 			' ';
-		return JSON.stringify(notebookContent, undefined, indentAmount);
+		// ipynb always ends with a trailing new line (we add this so that SCMs do not show unnecesary changes, resulting from a missing trailing new line).
+		return JSON.stringify(sortObjectPropertiesRecursively(notebookContent), undefined, indentAmount) + '\n';
```
Comment (DonJayamanne) [inline extensions/ipynb/src/notebookSerializer.ts:95]: ipynb have a trailing `\n`

File: extensions/ipynb/src/serializers.ts [hunk 2]
```diff
@@ -30,12 +30,35 @@ export function createJupyterCellFromNotebookCell(
 	return cell;
 }
 
+
+/**
+ * Sort the JSON to minimize unnecessary SCM changes.
+ * Jupyter notbeooks/labs sorts the JSON keys in alphabetical order.
+ * https://github.com/microsoft/vscode-python/issues/13155
+ */
+export function sortObjectPropertiesRecursively(obj: any): any {
```
Comment (DonJayamanne) [inline extensions/ipynb/src/serializers.ts:39]: This was missed when moving the serializer into vscode, adding this back.
I think at one point we relialized this was missing, can't remember. but added comments with the link to the original issue so we have some history.

File: extensions/ipynb/src/serializers.ts [hunk 3]
```diff
@@ -30,12 +30,35 @@ export function createJupyterCellFromNotebookCell(
...
+	return obj;
+}
+
 function createCodeCellFromNotebookCell(cell: NotebookCellData): nbformat.ICodeCell {
 	const cellMetadata = cell.metadata?.custom as CellMetadata | undefined;
 	const codeCell: any = {
 		cell_type: 'code',
 		execution_count: cell.executionSummary?.executionOrder ?? null,
-		source: splitMultilineString(cell.value),
+		source: splitMultilineString(cell.value.replace(/\r\n/g, '\n')),
```
Comment (DonJayamanne) [inline extensions/ipynb/src/serializers.ts:61]: Use `\n` instead of `\r\n`

File: extensions/ipynb/src/notebookSerializer.ts [hunk 4]
```diff
@@ -81,7 +81,7 @@ export class NotebookSerializer implements vscode.NotebookSerializer {
 		const notebookContent: Partial<nbformat.INotebookContent> = data.metadata?.custom || {};
 		notebookContent.cells = notebookContent.cells || [];
 		notebookContent.nbformat = notebookContent.nbformat || 4;
-		notebookContent.nbformat_minor = notebookContent.nbformat_minor || 2;
+		notebookContent.nbformat_minor = notebookContent.nbformat_minor ?? 2;
```
Comment (DonJayamanne) [inline extensions/ipynb/src/notebookSerializer.ts:84]: a Bug, if the value was `0` we were replacing with `2`

**Review by DavidKutu — APPROVED** [review]

File: extensions/ipynb/src/common.ts [hunk 5]
```diff
@@ -40,3 +40,23 @@ export interface CellOutputMetadata {
...
+
+/**
+ * Metadata we store in VS Code cells.
+ * This contains the original metadata from the Jupyuter cells.
+ */
+export interface CellMetadata {
+	/**
+	 * Cell id for notebooks created with the new 4.5 version of nbformat.
+	*/
+	id?: string;
```
Comment (DonJayamanne) [inline extensions/ipynb/src/common.ts:53]: Brought in a PR that was in jupyter extnesion to support forwards compatibility with the new notebook format 4.5
https://github.com/microsoft/vscode-jupyter/pull/5970

Comment (DonJayamanne) [reply extensions/ipynb/src/common.ts:53]: This new property isn't required in older versions, and only required in the latest 4.5 version (since we support older versions we're not going to upgrade to 4.5, but ensure users can create notebooks in format 4.2 and open notebooks created using format 4.5)

Note: Assume user creates a notebook in vscode (or older version of jupyter) & then opens this in latest version of Jupyter, the notebook format is upgrade to version 4.5 & jupyter notebook/lab will add the new id attribute.

File: extensions/ipynb/src/notebookSerializer.ts (hunk 4 above)
Comment (roblourens) [reply extensions/ipynb/src/notebookSerializer.ts:84]: Same for the above? Maybe that can't happen

File: extensions/ipynb/src/serializers.ts (hunk 2 above)
Comment (roblourens) [reply extensions/ipynb/src/serializers.ts:39]: I think there is an issue on the vscode side for it but I thought we figured out that it wasn't actually being done in the other serializer at the time we moved it
