### PR TITLE
Fix custom task shell doesn't work without manually passing in "run command" arg/flag

### LINKED ISSUE #169821: VS Code is still adding `/d /c` to task commands
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2
- OS Version: Windows 11

Steps to Reproduce (on Windows):

1. Have an `npm` task that starts a script.
2. In the User Preferences, set `"terminal.integrated.automationProfile.windows"` as such:
    ```json
    "terminal.integrated.automationProfile.windows": {
        "path": "nu.exe",
        "args": ["-c"],
    },
    ```
    This is an example; this also works with, e.g. `pwsh.exe` / `["-Command"]`.
3. Run the task.
4. VS Code will run `nu.exe -c /d /c yarn run name` rather than `nu.exe -c "yarn run name"`.

This was marked as fixed in #93437, but it isn't. A [workaround](https://github.com/microsoft/vscode/issues/93437#issuecomment-814330206) is given, but is IMO unacceptable. If I modify my shell in _user_ settings, I shouldn't have to modify a `tasks.json` that many users will use, and whose preferred shells are different. More importantly, a single shell can be specified, so `/bin/sh` won't work for users on Windows, and `cmd.exe` / `pwsh.exe` / whatever won't work for users on Linux. This makes `terminal.integrated.automationProfile.*` essentially useless.

Since `terminal.integrated.automationProfile.*` takes an `args` argument, why add unwanted arguments to it? I understand why defaults may be nice (e.g. set `args` to `["-Command"]` when `path` is `pwsh.exe`), but if preferences are explicitly specified, why append new arguments to them if they only work with a single shell?

### LINKED ISSUE #181302: Custom task shell executable doesn't work
Does this issue occur when all extensions are disabled?: Yes/No

Yes

Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

pwsh:

image

git bash:

image

without custom shell executable (default pwsh)

image

### PR DESCRIPTION
**Pull request by Legend-Master**
Fix #181302
Fix https://github.com/microsoft/vscode/issues/169821

### CODE REVIEW

**Comment by Legend-Master** [comment]
@microsoft-github-policy-service agree

**Review by meganrogge — DISMISSED** [review]

**Comment by dbaeumer** [comment]
@meganrogge  It is a long time ago that I coded that but I think the rational behind this was that the shell property is only used for `unknown` shells and there the command argument could be totally different. So now we would always `'/d', '/c'` which could be totally wrong. This is why as soon as you specify a shell you need to provide the command argument.

**Comment by Legend-Master** [comment]
> So now we would always '/d', '/c' which could be totally wrong. This is why as soon as you specify a shell you need to provide the command argument.

Yes, but we're doing this already...

image

I think we could add commands for known shells, and do nothing for others
And add some documentations on

**Comment by Legend-Master** [comment]
Also fixes #169821

**Comment by Legend-Master** [comment]
@meganrogge @dbaeumer It's been 3 weeks by now may I get some response? If you think the changes are not appropriate, could we just talk...

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 1]
```diff
@@ -1104,7 +1104,6 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
 				color: task.configurationProperties.icon?.color || undefined,
 				waitOnExit
 			};
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1106]: sdfsd

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 2]
```diff
@@ -1104,7 +1104,6 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
...
-			let shellSpecified: boolean = false;
 			const shellOptions: IShellConfiguration | undefined = task.command.options && task.command.options.shell;
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1107]: sdf

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts (hunk 1 above)
Comment (Legend-Master) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1106]: What does sdf and sdfsd mean?

Comment (meganrogge) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1106]: I was testing a GHPR feature. I'll look into your PR tomorrow. Sorry for the delay.

Comment (Legend-Master) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1106]: ok

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 3]
```diff
@@ -1108,7 +1107,6 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
 						shellLaunchConfig.args = undefined;
 					}
 					shellLaunchConfig.executable = await this._resolveVariable(variableResolver, shellOptions.executable);
-					shellSpecified = true;
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1111]: why do you believe we don't need to check this anymore?

Comment (Legend-Master) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1111]: We checked all known shells and added the corresponding command flag on Windows and leave it blank for unknown shells

For other OSs I do think we should check for known shells (instead of always adding `-c`) as well but we're already not checking it for custom terminal profiles anyway... https://github.com/microsoft/vscode/pull/181760#issuecomment-1541566202

Comment (meganrogge) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1111]: @alexr00 thoughts here?

Comment (meganrogge) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1111]: also @Tyriar ?

Comment (meganrogge) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1111]: i'm still concerned about passing in args for a user when they can do that themselves

Comment (Tyriar) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1111]: I don't think I'm knowledgable enough to know about this, it certainly looks like a risky change to me but it might be fine.

Comment (alexr00) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1111]: @meganrogge I don't remember the context for this, but it looks like the idea behind this was to only add the arguments if the user didn't include arguments in tasks.json.

Comment (meganrogge) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1111]: Yes @Legend-Master

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 4]
```diff
@@ -1127,29 +1126,29 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
...
+						toAdd.push('/d', '/c');
+					}
+				} else if ((basename === 'powershell.exe') || (basename === 'pwsh.exe')) {
+					if (!shellArgsSpecified) {
 						toAdd.push('-Command');
 					}
 				} else if ((basename === 'bash.exe') || (basename === 'zsh.exe')) {
 					windowsShellArgs = false;
-					if (!shellSpecified) {
+					if (!shellArgsSpecified) {
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1142]: I think that we still want to also check if `!shellSpecified`, @Legend-Master?

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 5]
```diff
@@ -1135,29 +1134,29 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
...
 					}
 				} else if (basename === 'wsl.exe') {
-					if (!shellSpecified) {
+					if (!shellArgsSpecified) {
 						toAdd.push('-e');
 					}
-				} else {
-					if (!shellSpecified) {
-						toAdd.push('/d', '/c');
-					}
```
Comment (Legend-Master) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1157]: I'm not sure if we should keep `/d /c` as the default for Windows like before (like what we did `-c` for other OSs)

My opinion is default to `-c` for all OSs, since most shells are using it

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts (hunk 4 above)
Comment (Legend-Master) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1150]: Do you mean we shouldn't add `-c` in this case? since you said yes in https://github.com/microsoft/vscode/pull/181760#discussion_r1301181334 ?

> ```jsonc
> "shell": {
>     "executable": "C:/Program Files/Git/bin/bash.exe",
> }
> ```

---

I think the right behavior is

- Add specific arguments for known shells
- Add `-c` for other shells
- Add nothing when the user sets `args` in the settings

**Add `/d /c` for this**

```jsonc
"shell": {
    "executable": "cmd.exe",
}
```

**Add `-c` for these**

```jsonc
"shell": {
    "executable": "C:/Program Files/Git/bin/bash.exe",
}
```
```jsonc
"shell": {
    "executable": "some_random_shell.exe",
}
```

**Do nothing for these**

```jsonc
"shell": {
    "executable": "some_random_shell.exe",
    "args": ["-whatever"],
}
```
```jsonc
"shell": {
    "executable": "some_random_shell.exe",
    "args": [],
}
```

---

In this way, we'll have the most out of box experience while still having full control over the arguments

What do you think?

**Comment by Legend-Master** [comment]
Sorry for the super late reply, I didn't notice that I didn't publish my comments, somehow the reply comment gets mixed up with pending review comments

**Review by meganrogge — APPROVED** [review]
This makes sense to me and works based on my testing. Thanks!

**Review by alexr00 — APPROVED** [review]

**Comment by alexr00** [comment]
We reverted this because it broke tasks on Mac. I don't see a way to re-open the PR though. @meganrogge FYI.

**Comment by Legend-Master** [comment]
@alexr00 Can you explain a bit more about how it broke tasks on Mac? I don't see any platform specific code that could be causing a breakage from just scanning the code

**Comment by Legend-Master** [comment]
Ah, I see now, `args` is not empty on Mac for the default profile, will open a reland
