### PR TITLE
Git - Fix bug when we checkout a remote branch detached

### LINKED ISSUE #153001: Cannot checkout detached
Issue Type: <b>Bug</b>

Using the built in Git, I select _check out to ..._ then _checkout detached_ and select a branch. Every time I get this git log output:

```
> git for-each-ref --format %(refname:short)%00%(upstream:short) refs/heads [147ms]
> git checkout -q --track --detach origin/ISR-12710 [136ms]
fatal: '--detach' cannot be used with '-b/-B/--orphan'
```

If I copy this and run it in Git Bash, same error. Removing --track and running it works correctly.

Side note, is there any way I can manually change the git commands used? Or does it need a bug fix?

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (2.37GB free)|
|Process Argv|--crash-reporter-id 3c3653d2-b95d-4a30-9cc7-10217ce35dbb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.10.12
coldfusionsymbols|dal|0.0.2
git-diff-and-merge-tool|dav|1.0.5
githistory|don|0.6.19
gitlens|eam|12.1.1
swap|fau|0.0.5
auto-close-tag|for|0.5.14
todo-tree|Gru|0.0.215
vscode-cfml|Kam|0.5.4
auto-build|mar|2.1.40
mssql|ms-|1.15.0
sql-bindings-vscode|ms-|0.2.0
cpptools|ms-|1.10.7
vscode-coldbox|ort|1.0.3
vscode-testbox|ort|1.0.1
platformio-ide|pla|2.4.3
vscode-yaml|red|1.8.0
code-settings-sync|Sha|3.4.3
cfml-comment-tags|trs|0.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549
841h4636:30513380

```

</details>

### PR DESCRIPTION
**Pull request by lszomoru**
Fixes #153001

### CODE REVIEW

File: extensions/git/src/repository.ts [hunk 1]
```diff
@@ -1581,7 +1581,16 @@ export class Repository implements Disposable {
 	}
 
 	async checkoutTracking(treeish: string, opts: { detached?: boolean } = {}): Promise<void> {
```
Comment (joaomoreno) [inline extensions/git/src/repository.ts:1583]: It feels like this should be an either/or scenario.

If the user wants to checkout detached, that means they don't want to create a new branch (tracking or otherwise). If the user wants to checkout a tracking branch, then it's not detached, by definition.

If I read it correctly, whenever the user wants to checkout detached, this PR will (1) create a tracking branch and (2) detach HEAD from it. Having that branch created would be unexpected, right?

Comment (lszomoru) [reply extensions/git/src/repository.ts:1583]: Your assessment is correct. I will explore implementing a different fix that does not end up creating a tracking branch.

**Review by joaomoreno — APPROVED** [review]
