### PR TITLE
Fixes #11451 - Add `konsole` as default terminal for KDE-plasma

### LINKED ISSUE #11451: Debugger doesn't recognize `konsole` as a terminal on Kubuntu
- VSCode Version: 1.4.0
- OS Version: Kubuntu 14.04

The debugger can't start due to the following error:

> Error: unable to start debugging. No terminal is available to launch the debugger. Please install Gnome Terminal or XTerm.

IMHO, it's not a good idea to mix KDE and gnome (especially low level things like terminals), so many KDE users wouldn't have one of those two installed. Instead, vscode should recognize `konsole` as a terminal application.

Interestingly, the integrated terminal works just fine.

Steps to Reproduce:

1. Make a c++ project 
2. Configure a launch
3. Press the green triangle

### PR DESCRIPTION
**Pull request by nholthaus**

### CODE REVIEW

File: src/vs/workbench/parts/execution/electron-browser/terminal.ts [hunk 1]
```diff
@@ -11,6 +11,8 @@ if (env.isLinux) {
 		defaultTerminalLinux = 'x-terminal-emulator';
 	} else if (process.env.DESKTOP_SESSION === 'gnome' || process.env.DESKTOP_SESSION === 'gnome-classic') {
 		defaultTerminalLinux = 'gnome-terminal';
+	} else if (process.env.DESKTOP_SESSION === 'kde-plasma') {
```
Comment (Tyriar) [inline src/vs/workbench/parts/execution/electron-browser/terminal.ts]: Is plasma a version or something? If so can this be made more generic?

File: src/vs/workbench/parts/execution/electron-browser/terminal.ts [hunk 2]
```diff
@@ -11,6 +11,8 @@ if (env.isLinux) {
...
+		defaultTerminalLinux = 'konsole';
```
Comment (Tyriar) [inline src/vs/workbench/parts/execution/electron-browser/terminal.ts]: Is there some environment variable that houses this? `konsole` is the default terminal for this distribution, correct?

File: src/vs/workbench/parts/execution/electron-browser/terminal.ts (hunk 1 above)
Comment (nholthaus) [inline src/vs/workbench/parts/execution/electron-browser/terminal.ts]: plasma is the name of KDE's desktop manager, not a specific version.

File: src/vs/workbench/parts/execution/electron-browser/terminal.ts (hunk 2 above)
Comment (nholthaus) [inline src/vs/workbench/parts/execution/electron-browser/terminal.ts]: @Tyriar I'm not a KDE expert, but none was present on my (fresh install) system. `konsole` is the default terminal for the distro.

File: src/vs/workbench/parts/execution/electron-browser/terminal.ts (hunk 1 above)
Comment (Tyriar) [inline src/vs/workbench/parts/execution/electron-browser/terminal.ts]: So this `if` should be entered regardless of the specific distribution, as long as it's using KDE and not on Debian (due to the first case)? [This comment](http://unix.stackexchange.com/questions/116539/how-to-detect-the-desktop-environment-in-a-bash-script#comment181412_116569) I found concerns me a little, is there a more reliable environment variable if this can be the `"default"` on KDE Fedora?

Comment (nholthaus) [inline src/vs/workbench/parts/execution/electron-browser/terminal.ts]: @Tyriar hmm, yeah I was only really thinking about improving Kubuntu. This whole section may need work if it's going to include desktop-manager specific code, even just to handle the major flavors. 

That said, if old versions of KDE Fedora (or others) fall through the `if`, they're no worse off then they are now.

Another approach might be to have the workspace/user setting for the external terminal affect the debugger. When I tried setting it to `konsole`, there was no change in the "install gnome terminal" error message. Not sure if that's an issue in and of itself (or a feature) or what the side effects would be.

**Comment by Tyriar** [comment]
v1.5 has been branched so I think I'll merge this, the comments are trying to solve an extra problem on top of this. Note that I'm not sure that the debugger will recognize this, but will definitely launch konsole when the "Open New Terminal" command is run.

The debugger issue was moved to https://github.com/Microsoft/vscode/issues/11451#issuecomment-244497778
