### PR TITLE
testing: hide ANSI color codes in test peeks

### LINKED ISSUE #148397: Testing api `TestRun.appendOutput` does not support ANSI color
Issue Type: <b>Bug</b>

Error information in peek error view does not support ANSI color.

**Expected behavior**
- Colors are rendered
- Or all ANSI color control characters are filtered

Related issue: https://github.com/vitest-dev/vscode/issues/19

image

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (22.37GB free)|
|Process Argv|--crash-reporter-id d11854f1-3a77-48cd-9674-a8efe260feee|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

### PR DESCRIPTION
**Pull request by connor4312**
Fixes #148397

@rzhao271 you have been chosen for review by randomly scrolling around the "reviewers" list 😛

### CODE REVIEW

File: src/vs/workbench/contrib/testing/browser/testingOutputPeek.ts [hunk 1]
```diff
@@ -1175,7 +1175,9 @@ class TestMessageElement implements ITreeElement {
 
 		this.id = this.uri.toString();
 
-		const asPlaintext = renderStringAsPlaintext(message);
+		const asPlaintext = type === TestMessageType.Info
```
Comment (rzhao271) [inline src/vs/workbench/contrib/testing/browser/testingOutputPeek.ts:1178]: Why do we want to remove the escape codes only for info messages, whereas for other types of messages, we render them as plaintext directly?

File: src/vs/workbench/contrib/testing/common/testingContentProvider.ts [hunk 2]
```diff
@@ -61,12 +62,14 @@ export class TestingContentProvider implements IWorkbenchContribution, ITextMode
...
-				const message = test.tasks[parsed.taskIndex].messages[parsed.messageIndex]?.message;
-				if (typeof message === 'string') {
-					text = message;
-				} else if (message) {
-					text = message.value;
-					language = this.languageService.createById('markdown');
+				const message = test.tasks[parsed.taskIndex].messages[parsed.messageIndex];
+				if (message) {
+					if (typeof message.message === 'string') {
+						text = message.type === TestMessageType.Info ? removeAnsiEscapeCodes(message.message) : message.message;
```
Comment (rzhao271) [inline src/vs/workbench/contrib/testing/common/testingContentProvider.ts:68]: Should the else condition in this also call `renderStringAsPlaintext`?

**Review by rzhao271 — APPROVED** [review]
Added some clarification questions, but approving for now.

File: src/vs/workbench/contrib/testing/common/testingContentProvider.ts (hunk 2 above)
Comment (connor4312) [reply src/vs/workbench/contrib/testing/common/testingContentProvider.ts:68]: no, since this is already a plaintext string in this branch (vs an `IMarkdownString`)
