### PR TITLE
Fix terminals in editor area not reloading

### LINKED ISSUE #140429: Terminal in editor area not restored after vs code restart.
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Windows 11

Steps to Reproduce:

1. Start VS code without extensions : 
code-insiders --disable-extensions
2. Create new terminal in editor : 
CTRL+SHIFT+P -> Terminal:Create New Terminal in Editor area to the side.
3. Close vs code by clicking on 'x' button on app top right of the WIndow.
4. Re-open vs code, see that the terminal in editor area is not restored.

Notes:
1. Persistent sessions value set
"terminal.integrated.persistentSessionReviveProcess": "onExitAndWindowClose"
2. No issues with the terminals in panel area. Terminal are restored correctly when vs code is restarted. Issue only with terminals opened in editor area,

### PR DESCRIPTION
**Pull request by ssigwart**
This PR fixes #140429

This isn't perfect because it just reopens then without setting the original location, but at least it reloads them.

If you have any thought on how to do that, I can try to implement it.  I think people would probably appreciate them at least reloading though.

## Testing
- Make sure `terminal.integrated.persistentSessionReviveProcess` setting is enabled.
- Other a few terminal in the terminal window.
- Quit VS Code.
- Reopen VS Code, which should reopen the terminals.

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 1]
```diff
@@ -645,7 +655,25 @@ export class TerminalService implements ITerminalService {
...
-		const state: ITerminalsLayoutInfoById = { tabs };
+
+		// Save terminals in editors too
+		const seenPersistentProcessIds: number[] = [];
+		for (const t of tabs) {
+			for (const term of t.terminals) {
+				seenPersistentProcessIds.push(term.terminal);
+			}
+		}
+		const otherInstances = this.instances.filter(instance => typeof instance.persistentProcessId === 'number' && instance.shouldPersist && seenPersistentProcessIds.indexOf(instance.persistentProcessId) === -1);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:666]: It would be simpler to get the terminals in the editor area from `terminalEditorService`

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalService.ts:666]: tried and that doesn't work, but should. 

I believe it doesn't work because of this, which happens when you close the window and then the state is saved with no terminals
https://github.com/ssigwart/vscode/blob/a084f63f4d3e5477efbcd8851008e8d996a45681/src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts#L92-L103

**Review by meganrogge — DISMISSED** [review]

**Comment by ssigwart** [comment]
Thank you for reviewing this and making the updates, @meganrogge.  Please let me know if you need me to do anything more on this.

**Comment by meganrogge** [comment]
@Tyriar when I revert ae7a4ba555b640be4d76ed482f043a51418df3bb, I don't see the duplicated prompt but I do see two terminal editors (with the same content) on reload
Screen Shot 2022-06-17 at 7 47 19 AM

**Review by Tyriar — CHANGES_REQUESTED** [review]
@ssigwart thanks for the PR, after looking a little closer at this I think it's the wrong approach. Instead of expanding the tabs like we do for terminal groups in the panel we want to rely on the editor's existing serialization as that will already get handled for us and it will then prevent focus/tabs appearing after start up problems.

It's been a while since I looked at this but I think there's a boolean somewhere near the [serializer](https://github.com/microsoft/vscode/blob/bfa57bdad5012d29e437e97747b4128d33e0bbf6/src/vs/workbench/contrib/terminal/browser/terminalEditorSerializer.ts) that says close the tab so it doesn't restore on _quit_ (when process _revive_ would be used) but allow is on _reload_ (when process _reconnect_ would be used).

**Comment by ssigwart** [comment]
Thanks for the tip, @Tyriar.  It took me quite a while to come up with this new fix, but I don't think I would have gotten there without your suggestion.

The issue is `_onWillShutdown` is called before `TerminalInputSerializer` serializes, so I added `shutdownPersistentProcessId` to record the ID for use in `TerminalInputSerializer`.

After that, when restoring the editor, it was using the ID from before the shutdown, which is no longer valid.  So I added `getRevivedPtyNewId` to get the new ID.

I wasn't able to test the remote terminal settings because I wasn't really sure what "remote terminals" meant.  I assumed it had something to do with https://code.visualstudio.com/docs/remote/ssh so I tried installing the extension and connect to SSH, but it failed after trying to install a VS Code Server on the server.

**Comment by Tyriar** [comment]
@ssigwart for remote you can create a test resolver window for the remote side of things:

image

**Review by Tyriar — CHANGES_REQUESTED** [review]
I tested it out again, revive seems to work great but reconnect appears to have broken.

Repro:

1. Create a terminal editor on left and right
2. Type something in each
3. Reload the window

Expected: What was typed in step 2 should show up (gif off `main`)

Recording 2022-06-20 at 15 15 51

Actual: New processes are created because reconnect fails:

image

**Comment by ssigwart** [comment]
Thanks, @Tyriar.  I think I got that working now.

**Review by Tyriar — APPROVED** [review]
Thanks, it works great 👍, it should land in v1.70

**Review by sandy081 — APPROVED** [review]
