### PR TITLE
Fix tabbing in trees

### LINKED ISSUE #31835: Terminal Switcher:  Rename should be reachable with first tab
While testing #31784.

- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:07:59.267Z)
- OS Version: Darwin x64 16.7.0

---

Steps to Reproduce:

1. Open 3 terminals
2. Select `Terminal: Switch Active Terminal` from the command palette
3. <kbd>ArrowDown</kbd> to the last terminal in the switcher
4. <kbd>Tab</kbd> to rename the terminal
-> keyboard focus disappears from the input box (and seems to be nowhere). I need a second <kbd>Tab</kbd> to move the keyboard focus to the rename action in the selected row. A single <kbd>Tab</kbd> should suffice.

### PR DESCRIPTION
**Pull request by Lixire**
PR 2: Electric Boogaloo

I changed the tab index to -1 instead of not setting it at all so it can still be focusable which fixes the quick navigate feature. 

- Changes the tabbing in quick-open-tree so that the actionbar items can be reached in one tab instead of two (where the first tab was to focus the whole tree).
- Keeps quickopen open when pressing up or down with an action bar item focused

Fixes https://github.com/Microsoft/vscode/issues/31835 and https://github.com/Microsoft/vscode/issues/31836

### CODE REVIEW

File: src/vs/base/parts/tree/browser/treeView.ts [hunk 1]
```diff
@@ -444,7 +444,7 @@ export class TreeView extends HeightMap {
 
 		this.domNode = document.createElement('div');
 		this.domNode.className = `monaco-tree no-focused-item monaco-tree-instance-${this.instance}`;
-		this.domNode.tabIndex = 0;
+		this.domNode.tabIndex = context.options.preventRootFocus ? -1 : 0;
```
Comment (roblourens) [inline src/vs/base/parts/tree/browser/treeView.ts]: Is preventRootFocus still a good name for the option? And were you able to figure out why we need the tabIndex for quick navigate?

File: src/vs/base/parts/quickopen/browser/quickOpenWidget.ts [hunk 2]
```diff
@@ -335,7 +336,15 @@ export class QuickOpenWidget implements IModelProvider {
 		}
 
 		this.applyStyles();
-
```
Comment (bpasero) [inline src/vs/base/parts/quickopen/browser/quickOpenWidget.ts]: I prefer to keep the newline here, looks logically too close otherwise imho:

image

**Review by bpasero — APPROVED** [review]
Thanks, seems to work nicely 👍

**Review by roblourens — APPROVED** [review]
