### PR TITLE
List still dirty files when backup fails

### LINKED ISSUE #113627: Failure to backup custom editors close veto message should list problem tabs
If backup fails for a custom editor, it may be hard to know which editor is the issue.

image

This message could be made more friendly by listing the problem files much like a regular dirty save dialog:

image

I'm aware this ideally shouldn't happen, but it may be inevitable if the source of truth must be kept within the webview and `retainContextWhenHidden` is false. It wouldn't be a problem if we had https://github.com/microsoft/vscode/issues/113507, but the dialog improvement would be welcome still for misbehaving extensions.

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #113627

### CODE REVIEW

File: src/vs/workbench/contrib/backup/electron-sandbox/backupTracker.ts [hunk 1]
```diff
@@ -140,8 +147,11 @@ export class NativeBackupTracker extends BackupTracker implements IWorkbenchCont
 		}
 	}
 
-	private showErrorDialog(msg: string, error?: Error): void {
-		this.dialogService.show(Severity.Error, msg, [localize('ok', 'OK')], { detail: localize('backupErrorDetails', "Try saving or reverting the dirty editors first and then try again.") });
+	private showErrorDialog(msg: string, error?: Error, fileList?: string): void {
+		const advice = localize('backupErrorDetails', "Try saving or reverting the dirty editors first and then try again.");
+		const detail = fileList ? fileList + '\n' + advice : advice;
```
Comment (bpasero) [inline src/vs/workbench/contrib/backup/electron-sandbox/backupTracker.ts:152]: I wonder if the `details` part of the dialog should be like this:

```
Try saving or reverting the dirty editors first and then try again:
<list of editors>
```

Instead of the other way around?

**Review by bpasero — CHANGES_REQUESTED** [review]
@mjbvz I suggest to implement this inside the `showErrorDialog` method because there are 2 cases where an error can show: either because backup failed or because save/revert failed and in both cases it would help the user see the name of the editor, right?

So simply check for dirty working copies inside `showErrorDialog` and if there are, list the names below the error message, is what I suggest.

File: src/vs/workbench/contrib/backup/electron-sandbox/backupTracker.ts (hunk 1 above)
Comment (rheh) [reply src/vs/workbench/contrib/backup/electron-sandbox/backupTracker.ts:152]: Also, is it worth including the actual error held in the 'error' variable in the dialog.  It is pushed through the log service, but, not part of the dialogue.

**Comment by mjbvz** [comment]
Thanks @bpasero! I've moved the file list logic into `showErrorDialog`

For your other suggestion, here's the detail UI with the current change:

Screen Shot 2021-01-11 at 11 25 52 AM

And here's with the detail order swapped:

Screen Shot 2021-01-11 at 11 23 22 AM

I like prefer the current ordering and also think this matches our current 'save all' dialog: https://github.com/microsoft/vscode/issues/113627#issue-777049300

**Review by bpasero — APPROVED** [review]
@mjbvz I also prefer the first variant where it aligns with the save dialog.
