### PR TITLE
show tooltip on icon label keyboard focus 

### LINKED ISSUE #132344: [Acc] Button tooltip doesn't show up on tab\
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0 (user setup) 
- OS Version: Windows 10 

Steps to Reproduce:

1. Navigate through VS Code Search tab  and tab through all the buttons . ( refresh , clear search results , etc. ) ( Search tab is just an example I can see the same behavior in all buttons) 

Expected : On the tab navigation to each of the button, the tooltip should be displayed. On escape the tooltip should be dismissed. Keyboard users will not know what is the use of the button through the icon for the button.

Actual :  User cannot see the tooltip when they tab into a button. They can only see the tooltip when they hover over. 
Animation2

### PR DESCRIPTION
**Pull request by meganrogge**
Will only work for icon labels with custom hovers

partially fix #132344

### CODE REVIEW

File: src/vs/base/browser/ui/iconLabel/iconLabelHover.ts [hunk 1]
```diff
@@ -219,6 +219,21 @@ export function setupCustomHover(hoverDelegate: IHoverDelegate, htmlElement: HTM
...
+
+	const onFocus = () => {
+		if (hoverPreparation) {
+			return;
+		}
+		const target: IHoverDelegateTarget = {
+			targetElements: [htmlElement],
+			dispose: () => { }
+		};
+		const toDispose: DisposableStore = new DisposableStore();
```
Comment (Tyriar) [inline src/vs/base/browser/ui/iconLabel/iconLabelHover.ts:231]: This doesn't get disposed

**Review by Tyriar — DISMISSED** [review]

**Review by Tyriar — APPROVED** [review]
Make sure this gets a TPI/verification as it looks like main issue won't be closed with this.

**Comment by meganrogge** [comment]
#199228
