### PR TITLE
Fix left navigation across wrapping points when selection is active

### LINKED ISSUE #105730: "Select all occurrences of find match" selects weirdly when word wrapping
Issue Type: <b>Bug</b>

With word wrap enabled, "select all occurrences of find match", if matching the end of a line, will select those weirdly, so that pressing Left will, instead of moving to the beginning of the line, move one beyond.

For instance, here, I'm searching for the string `,[space]`:

image

After I press Left, I expect the cursor to be at `,`, but instead:

image

Most cursors are correctly at `,`, but the cursors at the ends of lines are instead at `l`.

Here's a GIF showing the full process:

fullprocess

This makes it very hard to process a list like `foo,bar,baz` into `'foo','bar','baz'`, because the misalignment will instead turn it into `'foo','ba'r',baz'`

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.3.0
Remote OS version: Linux x64 4.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (11.55GB free)|
|Process Argv|-psn_0_81940|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ps-sim|
|OS|Linux x64 4.15.0-72-generic|
|CPUs|Intel(R) Xeon(R) E-2136 CPU @ 3.30GHz (12 x 4298)|
|Memory (System)|62.69GB (4.80GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
remote-containers|ms-|0.134.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
sublime-commands|Zar|0.1.0

</details>

### PR DESCRIPTION
**Pull request by hediet**
This PR fixes #105730.

### CODE REVIEW

**Review by alexdima — APPROVED** [review]
:+1: LGTM

**Comment by hediet** [comment]
I also fixed right cursor movement and generalized the normalization function. What do you think?

File: src/vs/editor/common/viewModel/splitLinesCollection.ts [hunk 1]
```diff
@@ -1327,9 +1323,16 @@ export class SplitLine implements ISplitLine {
...
-		if (outputLineIndex > 0 && outputPosition.column === this._getViewLineMinColumn(outputLineIndex)) {
-			return new Position(outputPosition.lineNumber - 1, this.getViewLineMaxColumn(model, modelLineNumber, outputLineIndex - 1));
+	public normalizePosition(model: ISimpleModel, modelLineNumber: number, outputLineIndex: number, outputPosition: Position, affinity: PositionNormalizationAffinity): Position {
+		if (affinity === PositionNormalizationAffinity.Left) {
+			if (outputLineIndex > 0 && outputPosition.column === this._getViewLineMinColumn(outputLineIndex)) {
+				return new Position(outputPosition.lineNumber - 1, this.getViewLineMaxColumn(model, modelLineNumber, outputLineIndex - 1));
+			}
+		}
+		else if (affinity === PositionNormalizationAffinity.Right) {
+			if (outputPosition.column === this.getViewLineMaxColumn(model, modelLineNumber, outputLineIndex)) {
```
Comment (alexdima) [inline src/vs/editor/common/viewModel/splitLinesCollection.ts:1333]: I think there might be a bug here because this if statement will go through even on the last consecutive wrapped line. In this case, the if statement should not go through:
Screen Shot 2021-05-10 at 12 01 08

**Review by alexdima — CHANGES_REQUESTED** [review]
There is a problem with the right affinity computation and I would love to see also a test for this. Everything else looks good :+1:.

**Review by alexdima — APPROVED** [review]
