### PR TITLE
fix-71570 Error when restoring a markdown preview for a file that has been deleted

### LINKED ISSUE #71570: Error when restoring a markdown preview for a file that has been deleted
Issue Type: <b>Bug</b>

**repo**
1. Create a file `x.md`.
1. Open markdown preview for the file
1. Now close  the `x.md` editor and rename the file to `y.md` (without opening it again in the editor)
1. Reload window and go to the restored markdown preview

**Bug**
Non-specific error shown in the editor

VS Code version: Code - Insiders 1.33.0-insider (0ac111466ec925fd5ca180ab9893f51531e419b2, 2019-04-01T15:47:22.304Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv|-psn_0_15584988|
|Screen Reader|no|
|VM|22%|

</details>

### PR DESCRIPTION
**Pull request by skprabhanjan**
@mjbvz  , Added logic to handle preview update when a file is renamed or deleted to fix #71570  , tested it on my local and works fine :)

PS : The Error html return value that is shown can be changed if its too simple :)

Please review it and let me know if there needs to be any other changes :)

### CODE REVIEW

File: extensions/markdown-language-features/src/features/previewContentProvider.ts [hunk 1]
```diff
@@ -90,6 +90,18 @@ export class MarkdownContentProvider {
...
 	}
 
+	public async provideFileNotFoundContent(
+		resource: vscode.Uri,
+	): Promise<string> {
+		const resourcePath = path.basename(resource.fsPath);
+		return `<!DOCTYPE html>
+			<html>
+			<body class="vscode-body">
+				${resourcePath} cannot be found.
```
Comment (mjbvz) [inline extensions/markdown-language-features/src/features/previewContentProvider.ts]: Any user facing strings must be localizable.  For the body use `localize('preview.notFound', '{0} cannot be found', resourcePath)` so it can be translated

**Review by mjbvz — CHANGES_REQUESTED** [review]
Good direction. Let me know if you have any questions about my suggested changes

File: extensions/markdown-language-features/src/features/previewContentProvider.ts (hunk 1 above)
Comment (skprabhanjan) [reply extensions/markdown-language-features/src/features/previewContentProvider.ts]: @mjbvz , Ahh sorry for that , I missed it :) 
Fixed it now , Please check :)

Thanks!

**Comment by skprabhanjan** [comment]
@mjbvz , Changes are pushed :)

**Comment by skprabhanjan** [comment]
@mjbvz sorry , did you get time to look at the changes ?

**Comment by mjbvz** [comment]
Thanks! Will be in the next VS Code insiders and is scheduled to ship with the April update
