### PR TITLE
Fix vscode becomes unresponsive after pasting filename with many dots in explorer

### LINKED ISSUE #116199: VSCode becomes unresponsive after pasting filename with many dots in file tree
- VSCode Version: 1.53.0 (commit id: 8490d3dde47c57)
- OS Version: Ubuntu 20.04.2 LTS (Kernel: Linux 5.4.0-65-generic)

I stumbled upon this bug by accident when I had the contents of some large file in my clipboard and (not realizing I had these file contents in the clipboard) when I pasted it in the filename of the file explorer of VSCode, it became unresponsive to the point I had to force kill it. In my opinion it is not very critical, not many people with encounter this issue, it was just surprising that my vscode became unresponsive due to this. I tried to locate the source of the issue in the code, but I couldn't find it myself.

Steps to Reproduce:

1. open a directory in VSCode such that you have some file existing in the Explorer
2. copy some filename with many dots to the clipboard. I use ```python -c "print('a.' * 50000)" | xclip -sel clip``` for this
2. select the file and click rename `F2`, followed by `CTRL-V` to paste the string
3. observe vscode is unresponsive for more than 30 seconds, after which I force kill it. 
 
I found out that when you would paste 100.000 characters without using dots (i.e. `python -c "print('ab' * 50000)" | xclip -sel clip`), then VSCode responds very quickly and lets me know the filename is invalid.

Since the maximum allowed length of a filename is 255 characters, I think it would suffice to limit the filename to 255 characters **before** any further parsing is done.  

Does this issue occur when all extensions are disabled?: **Yes** / ~~no~~

### PR DESCRIPTION
**Pull request by jeanp413**
Chose to ignore filenames whose length > 255 to avoid an explosive combination of extensions
Another option would be to just use the last `n` extensions
cc @bpasero let me know what you think

This PR fixes #116199

### CODE REVIEW

File: src/vs/editor/common/services/getIconClasses.ts [hunk 1]
```diff
@@ -37,9 +37,14 @@ export function getIconClasses(modelService: IModelService, modeService: IModeSe
...
 			if (name) {
 				classes.push(`${name}-name-file-icon`);
-				const dotSegments = name.split('.');
-				for (let i = 1; i < dotSegments.length; i++) {
-					classes.push(`${dotSegments.slice(i).join('.')}-ext-file-icon`); // add each combination of all found extensions if more than one
+				// Avoid doing an explosive combination of extensions for very long filenames
+				// (most file systems do not allow files > 255 length) with lots of `.` characters
+				// https://github.com/microsoft/vscode/issues/116199
+				if (name.length <= 255) {
+					const dotSegments = name.split('.');
```
Comment (rheh) [inline src/vs/editor/common/services/getIconClasses.ts:44]: Suggestion: Instead of the name length check, could we simply limit the number of items in dotSegment? e.g.
```
name.split('.').slice(-5));
```
That would at least show some of the class extensions?

**Comment by bpasero** [comment]
Thanks, I think we can go with this suggested change 👍
