### PR TITLE
Remove env var info widget and surface info in terminal tab

### LINKED ISSUE #151160: remove env var indicator from terminal
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Have some task for which shell integration fails to activate
2. :bug: warning icon is rendered on top of task output
image

### LINKED ISSUE #177078: Surface environment variable information in hover, even when not stale
Currently when a terminal environment is "stale" we show messages here:

image

And here:

image

We have wanted to remove the latter as part of https://github.com/microsoft/vscode/issues/151160.

Something I've always wanted since this was added was to surface existing environment variable contributions here as well and the upcoming description API (https://github.com/microsoft/vscode/issues/171108) will make this a lot nicer. For example, the git extension could explain that it's contributing an authentication provider instead of a bunch of mysterious environment variables.

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #151160
Fixes #177078

Typical terminal hover now:

image

Stale environment now (notice no warning icon in top right of terminal):

image

A description for the changes is coming in https://github.com/microsoft/vscode/issues/171108, and an action to view all the changes is coming in https://github.com/microsoft/vscode/issues/177128

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalStatusList.ts [hunk 1]
```diff
@@ -22,32 +22,10 @@ export const enum TerminalStatus {
 	Bell = 'bell',
```
Comment (karrtikr) [inline src/vs/workbench/contrib/terminal/browser/terminalStatusList.ts:22]: Curious, when is this shown and how does it look?

**Review by karrtikr — APPROVED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalStatusList.ts (hunk 1 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalStatusList.ts:22]: In bash for example when you hit left in an empty prompt you see this for a second:

image
