### PR TITLE
fix(search): fix expand all not working

### LINKED ISSUE #247812: "Expand All" doesnt work in the Search
Type: <b>Bug</b>

in vscode Search, the "Expand All" doesnt work. "Collapse All" does work. How to fix that?

VS Code version: Code 1.99.3 (Universal) (17baf841131aa23349f217ca7c570c76ee87b957, 2025-04-15T23:18:46.076Z)
OS version: Darwin arm64 24.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M4 Max (14 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|36.00GB (0.46GB free)|
|Process Argv|--crash-reporter-id d7b35c74-83ea-476a-b056-e622c163288a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
numbered-bookmarks|ale|8.5.0
vscode-raml|blz|3.0.1
vscode-intelephense-client|bme|1.14.4
laravel-goto-view|cod|1.3.11
docker|doc|0.6.0
githistory|don|0.6.20
gitlens|eam|17.0.3
vscode-search-open-all-results|fab|2.0.2
auto-close-tag|for|0.5.15
code-runner|for|0.12.2
copilot|Git|1.311.0
copilot-chat|Git|0.26.7
remotehub|Git|0.64.0
vscode-pull-request-github|Git|0.108.0
selected-lines-count|gur|1.4.0
vscode-favorites|how|1.11.0
twig-language-2|mbl|0.9.4
dotenv|mik|1.0.1
escape-quotes|mil|1.10.0
prettify-json|moh|0.0.3
compare-folders|mos|0.25.1
easy-less|mrc|2.0.2
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.29.6
debugpy|ms-|2025.6.0
python|ms-|2025.4.0
remote-containers|ms-|0.409.0
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.87.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.42.0
remote-server|ms-|1.5.2
copy-file-name|nem|1.2.0
laravel5-snippets|one|1.19.1
material-icon-theme|PKi|5.21.2
vscode-xml|red|0.28.1
gotomanual|rha|1.0.0
phpdoc-generator|ron|1.1.1
svg-preview|Sim|2.8.3
sonarlint-vscode|Son|4.21.0
laravel-goto-controller|ste|0.0.15
remove-empty-lines|use|1.0.1
vscode-gradle|vsc|3.16.4
twig|wha|1.0.2
php-debug|xde|1.36.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dwnewjupytercf:31046870
pythonrstrctxt:31112756
nativeloc2:31192216
5fd0e150:31155592
dwcopilot:31170013
6074i472:31201624
dwoutputs:31242946
customenabled:31248079
9064b325:31222308
copilot_t_ci:31222730
e5gg6876:31282496
cp15370_t:31280197
pythoneinst12:31285622
bgtreat:31268568
4gafe986:31271826
31787653:31262186
3e8i5726:31271747
996jf627:31283433
usemplatestapi:31297334
7bj51361:31289155
747dc170:31275177
aj496949:31278748
aj953862:31281341
generatesymbolt:31295002
convertfstringf:31295003
gendocf:31295004

```

</details>

### PR DESCRIPTION
**Pull request by mortalYoung**
`Expand All` action don't need to expand a specific root node as the aims of the action is to expand all node.

fixed #247812

### CODE REVIEW

File: src/vs/workbench/contrib/search/browser/searchActionsTopBar.ts [hunk 1]
```diff
@@ -252,7 +252,7 @@ async function expandAll(accessor: ServicesAccessor) {
 			if (searchView.model.hasAIResults) {
 				await forcedExpandRecursively(viewer, undefined);
 			} else {
-				await forcedExpandRecursively(viewer, searchView.model.searchResult.plainTextSearchResult);
+				await forcedExpandRecursively(viewer, undefined);
```
Comment (osortega) [inline src/vs/workbench/contrib/search/browser/searchActionsTopBar.ts:255]: All these statements now do the same thing, could we just remove all the nesting and execute `forcedExpandRecursively` for all cases?

**Review by osortega — COMMENTED** [review]
@mortalYoung Thank you for this contribution! Left one comment

**Review by osortega — APPROVED** [review]
LGTM! Thank you ❤️

**Review by lramos15 — APPROVED** [review]
