### PR TITLE
disable decorations

### LINKED ISSUE #154412: terminal.integrated.shellIntegration.decorationsEnabled does not disable decorations
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.0
- OS Version: Fedora 36 through Remote-SSH on Windows 10

Steps to Reproduce:

1. Set `terminal.integrated.shellIntegration.decorationsEnabled` to `false`
2. Notice the sidebar decorations don't go away

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #154412

https://user-images.githubusercontent.com/29464607/177899745-c9f94784-7bb9-41a7-b76a-3167b628aed7.mov

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 1]
```diff
@@ -365,7 +374,7 @@ export class DecorationAddon extends Disposable implements ITerminalAddon {
 				run: () => this._clipboardService.writeText(command.command)
 			});
 		}
-		if (command.hasOutput()) {
+		if (command.hasOutput) {
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:377]:
```suggestion
		if (command.hasOutput()) {
```

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 2]
```diff
@@ -79,6 +81,13 @@ export class DecorationAddon extends Disposable implements ITerminalAddon {
 				this.refreshLayouts();
 			} else if (e.affectsConfiguration('workbench.colorCustomizations')) {
 				this._refreshStyles(true);
+			} else if (e.affectsConfiguration(TerminalSettingId.ShellIntegrationDecorationsEnabled) || e.affectsConfiguration(TerminalSettingId.ShellIntegrationEnabled)) {
+				const enabledDecorations = this._configurationService.getValue(TerminalSettingId.ShellIntegrationDecorationsEnabled) && this._configurationService.getValue(TerminalSettingId.ShellIntegrationEnabled);
+				if (!enabledDecorations) {
+					document.querySelector(DecorationSelector.Container)?.classList.add('hide');
+				} else {
+					document.querySelector(DecorationSelector.Container)?.classList.remove('hide');
+				}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:90]: As mentioned by @LangLangBart in https://github.com/microsoft/vscode/issues/154412#issuecomment-1178702192, we'll want to change the actual decorations to either not exist or change to be invisible (including `overviewRulerOptions`).

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 3]
```diff
@@ -79,6 +81,13 @@ export class DecorationAddon extends Disposable implements ITerminalAddon {
 				this.refreshLayouts();
 			} else if (e.affectsConfiguration('workbench.colorCustomizations')) {
 				this._refreshStyles(true);
+			} else if (e.affectsConfiguration(TerminalSettingId.ShellIntegrationDecorationsEnabled) || e.affectsConfiguration(TerminalSettingId.ShellIntegrationEnabled)) {
+				const enabledDecorations = this._configurationService.getValue(TerminalSettingId.ShellIntegrationDecorationsEnabled) && this._configurationService.getValue(TerminalSettingId.ShellIntegrationEnabled);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:85]: This should be:

```suggestion
				const enabledDecorations = this._configurationService.getValue(TerminalSettingId.ShellIntegrationDecorationsEnabled)
```

`TerminalSettingId.ShellIntegrationEnabled` is a little misleading in the name but it's really "shell integration auto injection enabled", we recommend users disable `TerminalSettingId.ShellIntegrationEnabled` when they manually install shell integration.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/media/terminal.css [hunk 4]
```diff
@@ -302,10 +323,11 @@
 	overflow: hidden;
 }
 
-.monaco-workbench .pane-body.integrated-terminal .tabs-container > .monaco-toolbar {
+.monaco-workbench .pane-body.integrated-terminal .tabs-container>.monaco-toolbar {
 	padding: 4px 0 2px;
 	margin: auto;
 }
+
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/media/terminal.css:330]: ugh format on save

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts (hunk 2 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts]: We could recreate the decorations when re enabled since we will still have the markers. I'm thinking about the extra perf consumed maintaining them if someone has disabled them completely

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 5]
```diff
@@ -28,13 +28,15 @@ import { IGenericMarkProperties } from 'vs/platform/terminal/common/terminalProc
...
 	ErrorColor = 'error',
 	DefaultColor = 'default-color',
 	Default = 'default',
 	Codicon = 'codicon',
 	XtermDecoration = 'xterm-decoration',
-	OverviewRuler = 'xterm-decoration-overview-ruler',
-	GenericMarkerIcon = 'codicon-circle-small-filled'
+	GenericMarkerIcon = 'codicon-circle-small-filled',
+	Container = '.xterm-decoration-container',
+	OverviewRuler = '.xterm-decoration-overview-ruler'
```
[the remark this answers is not in the document]
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:39]: yeah good pt. ok seems like just changing visibility won't work so should dispose of the decorations and re-create them. I wonder if disposing of the decoration disposes of the marker though?

[the remark this answers is not in the document]
Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:39]: It shouldn't, it's a bug if it does.

We create all the decorations when the addon activates anyway so it should just be a matter of calling that function again:

https://github.com/microsoft/vscode/blob/1eb2480d91650f82b3b1da0b05d382a01b2d38e2/src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts#L138-L156

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 6]
```diff
@@ -170,6 +227,7 @@ export class DecorationAddon extends Disposable implements ITerminalAddon {
 		}
 		this._commandDetectionListeners.push(capability.onCommandStarted(command => this.registerCommandDecoration(command, true)));
 		// Command finished
+		console.log('commands', capability.commands.map(c => c.command));
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:230]:
```suggestion
```

**Comment by meganrogge** [comment]
need to update the smoke tests

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 7]
```diff
@@ -79,11 +83,65 @@ export class DecorationAddon extends Disposable implements ITerminalAddon {
...
 			}
 		});
 		this._themeService.onDidColorThemeChange(() => this._refreshStyles(true));
+		this._updateDecorationVisibility();
 	}
 
+	private _updateDecorationVisibility(): void {
+		const showDecorations = this._configurationService.getValue(TerminalSettingId.ShellIntegrationDecorationsEnabled);
+		switch (showDecorations) {
+			case 'never':
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:97]: You could tweak this to reduce duplication:

```ts
const gutterDecorations = (showDecorations === 'both' || showDecorations === 'gutter');
const overviewRulerDecorations = (showDecorations === 'both' || showDecorations === 'overviewRuler');
this._updateGutterDecorationVisibility(gutterDecorations);
...
```

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 8]
```diff
@@ -79,11 +83,65 @@ export class DecorationAddon extends Disposable implements ITerminalAddon {
...
+			case 'overviewRuler':
+				this._updateGutterDecorationVisibility(false);
+				this._overviewRulerDecorations = true;
+				this._decorationsDisabled = false;
+				this._attachToCommandCapability();
+				break;
+		}
+	}
+
+	private _disposeOfDecorations(): void {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:127]: nit: `_disposeAllDecorations`?

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 9]
```diff
@@ -79,11 +83,65 @@ export class DecorationAddon extends Disposable implements ITerminalAddon {
...
+	}
+
+	private _updateGutterDecorationVisibility(visible?: boolean): void {
+		const containers = document.querySelectorAll(DecorationSelector.Container);
+		for (const container of containers) {
+			if (visible) {
+				container.classList.remove('hide');
+			} else {
+				container.classList.add('hide');
+			}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:142]:
```suggestion
			container.classList.toggle('hide', visible);
```

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 10]
```diff
@@ -79,11 +83,65 @@ export class DecorationAddon extends Disposable implements ITerminalAddon {
...
+		this._placeholderDecoration?.dispose();
+		for (const value of this._decorations.values()) {
+			value.decoration.dispose();
+			dispose(value.disposables);
+		}
+	}
+
+	private _updateGutterDecorationVisibility(visible?: boolean): void {
+		const containers = document.querySelectorAll(DecorationSelector.Container);
+		for (const container of containers) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:137]: We can't hide the decoration container as we will use other decorations as well which should still work when command decorations are disables (eg. contextual commands, find matches). You could add a class to the decoration in `onRender` and hide that though.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts (hunk 9 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts]: actually tried that and it didn't work

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts (hunk 5 above)
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:39]: Can be removed

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 11]
```diff
@@ -28,13 +28,15 @@ import { IGenericMarkProperties } from 'vs/platform/terminal/common/terminalProc
 
 const enum DecorationSelector {
 	CommandDecoration = 'terminal-command-decoration',
+	Hide = 'hide',
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:31]: I don't think this is referenced yet but could be below

File: src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts [hunk 12]
```diff
@@ -546,15 +546,22 @@ const terminalConfiguration: IConfigurationNode = {
...
+			markdownDescription: localize('terminal.integrated.shellIntegration.enabled', "Determines whether or not shell integration is auto-injected to support features like enhanced command tracking and current working directory detection. \n\nShell integration works by injecting the shell with a startup script. The script gives VS Code insight into what is happening within the terminal.\n\nSupported shells:\n\n- Linux/macOS: bash, pwsh, zsh\n - Windows: pwsh\n\nThis setting applies only when terminals are created, so you will need to restart your terminals for it to take effect.\n\n Note that the script injection may not work if you have custom arguments defined in the terminal profile, a [complex bash `PROMPT_COMMAND`](https://code.visualstudio.com/docs/editor/integrated-terminal#_complex-bash-promptcommand), or other unsupported setup. To disable decorations, see ${0}", '`#terminal.integrated.shellIntegrations.decorationsEnabled#`'),
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts:549]:
```suggestion
			markdownDescription: localize('terminal.integrated.shellIntegration.enabled', "Determines whether or not shell integration is auto-injected to support features like enhanced command tracking and current working directory detection. \n\nShell integration works by injecting the shell with a startup script. The script gives VS Code insight into what is happening within the terminal.\n\nSupported shells:\n\n- Linux/macOS: bash, pwsh, zsh\n - Windows: pwsh\n\nThis setting applies only when terminals are created, so you will need to restart your terminals for it to take effect.\n\n Note that the script injection may not work if you have custom arguments defined in the terminal profile, a [complex bash `PROMPT_COMMAND`](https://code.visualstudio.com/docs/editor/integrated-terminal#_complex-bash-promptcommand), or other unsupported setup. To disable decorations, see {0}", '`#terminal.integrated.shellIntegrations.decorationsEnabled#`'),
```

File: src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts [hunk 13]
```diff
@@ -546,15 +546,22 @@ const terminalConfiguration: IConfigurationNode = {
...
 		},
 		[TerminalSettingId.ShellIntegrationDecorationsEnabled]: {
 			restricted: true,
 			markdownDescription: localize('terminal.integrated.shellIntegration.decorationsEnabled', "When shell integration is enabled, adds a decoration for each command."),
-			type: 'boolean',
-			default: true
+			type: 'string',
+			enum: ['both', 'gutter', 'overviewRuler', 'never'],
+			enumDescriptions: [
+				localize('terminal.integrated.shellIntegration.decorationsEnabled.both', "Show decorations in the gutter (left) and overviewRuler (right)"),
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts:559]:
```suggestion
				localize('terminal.integrated.shellIntegration.decorationsEnabled.both', "Show decorations in the gutter (left) and overview ruler (right)"),
```

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Review by chrmarti — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]
