### PR TITLE
fix #102718, add formatting indicator

### LINKED ISSUE #102718: No loading indicator when formatting a document
- VSCode Version: 1.47.1
- OS Version: Darwin x64 19.5.0

Steps to Reproduce:

1. Create a file with a large amount (2000+ lines) of unformatted JSON data (or any other format) 
2. Right click -> Format Document
3. No indicators are visisble.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by cyyyu**
This PR fixes #102718

My approach is exactly as @ConradSollitt 's suggestion(https://github.com/microsoft/vscode/issues/102718#issuecomment-660347534).
Any inputs/comments/reviews are welcome.

### CODE REVIEW

File: src/vs/editor/contrib/format/formatActions.ts [hunk 1]
```diff
@@ -25,7 +25,7 @@ import { KeybindingWeight } from 'vs/platform/keybinding/common/keybindingsRegis
 import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
 import { onUnexpectedError } from 'vs/base/common/errors';
 import { EditorOption } from 'vs/editor/common/config/editorOptions';
-import { Progress } from 'vs/platform/progress/common/progress';
+import { Progress, IProgressService, ProgressLocation } from 'vs/platform/progress/common/progress';
```
Comment (jrieken) [inline src/vs/editor/contrib/format/formatActions.ts:28]: Better use the `IEditorProgressService`. It renders progress in the context of an editor that's what we use for editor features, like rename, go-to, etc

**Review by jrieken — CHANGES_REQUESTED** [review]

File: src/vs/editor/contrib/format/formatActions.ts (hunk 1 above)
Comment (cyyyu) [reply src/vs/editor/contrib/format/formatActions.ts:28]: thanks, updated~

File: src/vs/editor/contrib/format/formatActions.ts [hunk 2]
```diff
@@ -231,7 +231,10 @@ class FormatDocumentAction extends EditorAction {
 	async run(accessor: ServicesAccessor, editor: ICodeEditor): Promise<void> {
 		if (editor.hasModel()) {
 			const instaService = accessor.get(IInstantiationService);
-			await instaService.invokeFunction(formatDocumentWithSelectedProvider, editor, FormattingMode.Explicit, Progress.None, CancellationToken.None);
+			const progressService = accessor.get(IEditorProgressService);
+			await progressService.showWhile(
```
Comment (jrieken) [inline src/vs/editor/contrib/format/formatActions.ts:235]: In the editor land we call this with 250ms delay so that it isn't too nervous, for reference see https://github.com/microsoft/vscode/blob/6a9f98bc864bd879cbc6d556983ab05781942c16/src/vs/editor/contrib/rename/rename.ts#L248

**Review by jrieken — CHANGES_REQUESTED** [review]

File: src/vs/editor/contrib/format/formatActions.ts (hunk 2 above)
Comment (cyyyu) [reply src/vs/editor/contrib/format/formatActions.ts:235]: make sense~

**Review by jrieken — APPROVED** [review]

**Comment by jrieken** [comment]
Thanks 👏

**Comment by ConradSollitt** [comment]
Great Job @cyyyu 

I just tested using the 3 test JSON files I created for this and it works well. I'll make sure to test this on the next release build as well.
