### PR TITLE
Fixes ArcTracker.handleEdits line number computation

### LINKED ISSUE #264048: `editTelemetry.reportEditArc` showing unexpected lineCounts
@hediet 
```
Version: 1.104.0-insider (user setup)
Commit: 4a31639f5f6e1ba6f2521ca73430f3d59eb97524
Date: 2025-08-27T07:48:03.836Z
Electron: 37.2.3
ElectronBuildId: 12035395
Chromium: 138.0.7204.100
Node.js: 22.17.0
V8: 13.8.500258-electron.0
OS: Windows_NT x64 10.0.22631

Copilot Chat 
0.31.2025082702
```

When looking at the telemetry sent in `editTelemetry.reportEditArc`, we wrote down some scenarios of user edits. See below for one of them:

> ### Description
> * AI removes the `TODO` line
> * AI adds `Charlie`
> * User adds `*` characters
> * User adds `ICAO spelling alphabet:`.
> 
> ### Document States
> #### Initial State
> ```
> TODO: Add Charlie
> Alpha
> Bravo
> Delta
> ```
> 
> #### State after AI edits
> ```
> Alpha
> Bravo
> Delta
> Charlie
> ```
> 
> #### Current State (after user edits)
> ```
> ICAO spelling alphabet:
> * Alpha
> * Bravo
> * Delta
> * Charlie
> ```
> 
> ### Expected Telemetry
> | Metric | Value |
> | - | - |
> originaldeletedlinecount | 1 |
> originallinecount | 1 |
> currentdeletedlinecount | 1 |
> currentlinecount | 1 |
> 
> ## VS Code Telemetry:
> ```
> "originalCharCount":9,
> "originalLineCount":1,
> "originalDeletedLineCount":1,
> "arc":9,
> "currentLineCount":2,
> "currentDeletedLineCount":1
> ```

Can we get some details on why vscode reports currentLineCount > originalLineCount?

### PR DESCRIPTION
**Pull request by hediet**
Fixes https://github.com/microsoft/vscode/issues/264048

### CODE REVIEW

File: src/vs/workbench/contrib/editTelemetry/common/arcTracker.ts [hunk 1]
```diff
@@ -24,8 +26,12 @@ export class ArcTracker {
...
 	handleEdits(edit: BaseStringEdit): void {
 		const e = edit.mapData(_d => new IsTrackedEditData(false));
-		const composedEdit = this._updatedTrackedEdit.compose(e);
-		const onlyTrackedEdit = composedEdit.decomposeSplit(e => !e.data.isTrackedEdit).e2;
+		const composedEdit = this._updatedTrackedEdit.compose(e); // (still) applies to valueBeforeTrackedEdit
+
+		// decomposeSplit computes e1 and e2 such that all replacements in e1 have the given property
+		// and no replacement in e2 has the property, and such that e1.compose(e2).equals(composedEdit).
+		// Thus, e1 applies to valueBeforeTrackedEdit.
+		const onlyTrackedEdit = composedEdit.decomposeSplit(e => e.data.isTrackedEdit).e1;
```
Comment (hediet) [inline src/vs/workbench/contrib/editTelemetry/common/arcTracker.ts:34]: This is the main fix.

**Review by lszomoru — APPROVED** [review]
