### PR TITLE
Fix MaxNumber incrementFileName bug

### LINKED ISSUE #50822: Hang when copy/pasting file with large number
- Have file named `file-9007199254740992.txt` in explorer
- Copy/paste it
- Window hangs

This is from https://github.com/Microsoft/vscode/pull/50003. We shouldn't attempt this when the number is >= Number.MAX_SAFE_INTEGER.

It loops forever here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileActions.ts#L1049

This bug will happen whenever incrementFileName fails to modify the file name.

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
Fix https://github.com/Microsoft/vscode/issues/50822

CC: @isidorn

### CODE REVIEW

File: src/vs/workbench/parts/files/electron-browser/fileActions.ts [hunk 1]
```diff
@@ -1060,20 +1060,27 @@ function findValidPasteFileTarget(targetFolder: ExplorerItem, fileToPaste: { res
 
 export function incrementFileName(name: string, isFolder: boolean): string {
 	const separators = '[\\.\\-_]';
+	const maxNumber = 9007199254740991;
```
[the remark this answers is not in the document]
Comment (isidorn) [reply src/vs/workbench/parts/files/electron-browser/fileActions.ts]: Please use this instead of introducing a new maxNumber https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/core/uint.ts#L40

File: src/vs/workbench/parts/files/electron-browser/fileActions.ts [hunk 2]
```diff
@@ -1060,20 +1060,27 @@ function findValidPasteFileTarget(targetFolder: ExplorerItem, fileToPaste: { res
...
 
 	// file.1.txt=>file.2.txt
 	let suffixFileRegex = RegExp('(.*' + separators + ')(\\d+)(\\..*)$');
 	if (!isFolder && name.match(suffixFileRegex)) {
 		return name.replace(suffixFileRegex, (match, g1?, g2?, g3?) => {
-			return g1 + strings.pad(parseInt(g2) + 1, g2.length) + g3;
```
Comment (isidorn) [inline src/vs/workbench/parts/files/electron-browser/fileActions.ts]: Can we have a helper method for this?
Since this code seems like it is duplicated 4 times?

File: src/vs/workbench/parts/files/test/electron-browser/fileActions.test.ts [hunk 3]
```diff
@@ -88,6 +88,18 @@ suite('Files - Increment file name', () => {
 		assert.strictEqual(result, 'test_2');
 	});
```
Comment (isidorn) [inline src/vs/workbench/parts/files/test/electron-browser/fileActions.test.ts]: Great job with tests

**Review by isidorn — CHANGES_REQUESTED** [review]

**Comment by isidorn** [comment]
Thanks for this PR. I have commented directly in the code. Once that is addressed we can merge this in. Thanks!

File: src/vs/workbench/parts/files/electron-browser/fileActions.ts (hunk 2 above)
Comment (Krzysztof-Cieslak) [reply src/vs/workbench/parts/files/electron-browser/fileActions.ts]: It's bit different for every case since it formats the string in different formats, not sure if there is a sense in trying to extract that to helper function.

File: src/vs/workbench/parts/files/electron-browser/fileActions.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (Krzysztof-Cieslak) [reply src/vs/workbench/parts/files/electron-browser/fileActions.ts]: Updated
