### PR TITLE
Fix PATH prepending when using Fish

### LINKED ISSUE #232495: Prepending PATH env var with environmentVariableCollection doesn't work on linux for fish
I was having issues with how the VSCode terminal was resolving the PATH variable on my system and I discovered this PR which fixes the execution order of the shell integration and the fish config, which I thought was the cause. In particular I was having this same old issue but on Linux with fish https://github.com/microsoft/vscode/issues/99878 , which was fixed for macOS back in the day.

But despite the fix in this PR, my issue specifically with the PATH wasn't fixed. In particular, I'm using the official fish variable `fish_user_paths` to handle the PATH in my system. It looks like fish always prepends these paths at the very end of the fish shell setup, even after the initial-command, so the `context.environmentVariableCollection.prepend("PATH", "/foo/my/path:");` functionality used by some extensions doesn't work.

I opened a PR on top of this one with the simple fix https://github.com/aravind-n/vscode/pull/1
My fix is dependent on the changes on this PR, so if the team thinks this is a valid solution, it could be included in the same PR.

The linked old issue is particularly annoying when working with extensions that let you change the version of a language SDK per project, because the PATH change won't work in the terminal.

_Originally posted by @davidmartos96 in https://github.com/microsoft/vscode/issues/226589#issuecomment-2405802480_

### PR DESCRIPTION
**Pull request by davidmartos96**
Support Linux on EnvMixin to handle `fish_user_paths` being prepended to the PATH, overriding any configuration in the VSCode environment via the `context.environmentVariableCollection` API.

Fixes https://github.com/microsoft/vscode/issues/232495

(The root problem was originally fixed for macOS on https://github.com/microsoft/vscode/issues/99878 but it can also trigger when using the fish shell in other platforms)

More context: https://github.com/microsoft/vscode/pull/226589#issuecomment-2405802480

cc @meganrogge

### CODE REVIEW

File: src/vs/platform/terminal/node/terminalEnvironment.ts [hunk 1]
```diff
@@ -284,16 +284,19 @@ export function getShellIntegrationInjection(
...
+ * This causes significant problems for the environment variable
  * collection API as the custom paths added to the end will now be somewhere in the middle of
  * the PATH. To combat this, VSCODE_PATH_PREFIX is used to re-apply any prefix after the profile
  * has run. This will cause duplication in the PATH but should fix the issue.
  *
  * See #99878 for more information.
  */
 function addEnvMixinPathPrefix(options: ITerminalProcessOptions, envMixin: IProcessEnvironment): void {
-	if (isMacintosh && options.environmentVariableCollections) {
+	if ((isMacintosh || isLinux) && options.environmentVariableCollections) {
```
Comment (Tyriar) [inline src/vs/platform/terminal/node/terminalEnvironment.ts:299]: Shouldn't we only be doing this for fish + linux? Applying the environment variable collection multiple times can lead to things like duplicating PATH entries when unnecessary.

**Review by Tyriar — DISMISSED** [review]

File: src/vs/platform/terminal/node/terminalEnvironment.ts (hunk 1 above)
Comment (davidmartos96) [reply src/vs/platform/terminal/node/terminalEnvironment.ts:299]: You are right, we can be more specific here to avoid that extra work

**Comment by davidmartos96** [comment]
@Tyriar I applied the fix conditionally based on the shell being used.

While further testing it, I noticed that the envMixin should be applied even on non-login shells with fish, because the variable `$fish_user_paths` is always set, regardless if the shell is login or not.
Otherwise, in order for the fix to work, the user needs to explicitly use the following config. And that kind of extra configuration is not necessary for the PATH prefixing to work on both bash and zsh.

```json
{
  "terminal.integrated.profiles.linux": {
    "fish login": {
      "path": "fish",
      "args": [
        "-l"
      ]
    }
  },
  "terminal.integrated.defaultProfile.linux": "fish login"
}
```

File: src/vs/platform/terminal/node/terminalEnvironment.ts [hunk 2]
```diff
@@ -284,16 +288,19 @@ export function getShellIntegrationInjection(
...
  * collection API as the custom paths added to the end will now be somewhere in the middle of
  * the PATH. To combat this, VSCODE_PATH_PREFIX is used to re-apply any prefix after the profile
  * has run. This will cause duplication in the PATH but should fix the issue.
  *
  * See #99878 for more information.
  */
-function addEnvMixinPathPrefix(options: ITerminalProcessOptions, envMixin: IProcessEnvironment): void {
-	if (isMacintosh && options.environmentVariableCollections) {
+function addEnvMixinPathPrefix(options: ITerminalProcessOptions, envMixin: IProcessEnvironment, shell: string): void {
+	if ((isMacintosh || (isLinux && shell === 'fish')) && options.environmentVariableCollections) {
```
Comment (Tyriar) [inline src/vs/platform/terminal/node/terminalEnvironment.ts:303]: > While further testing it, I noticed that the envMixin should be applied even on non-login shells with fish, because the variable $fish_user_paths is always set

If this is the case, should this instead be `isMacintosh || shell === 'fish'` and not mention Linux?

**Review by Tyriar — COMMENTED** [review]
@meganrogge could you review this please? I've only done a very high level review not digging into the details.

File: src/vs/platform/terminal/node/terminalEnvironment.ts [hunk 3]
```diff
@@ -284,16 +288,19 @@ export function getShellIntegrationInjection(
 }
 
 /**
- * On macOS the profile calls path_helper which adds a bunch of standard bin directories to the
- * beginning of the PATH. This causes significant problems for the environment variable
+ * There are a few situations where some directories are added to the beginning of the PATH.
+ * 1. On macOS when the profile calls path_helper.
+ * 2. On fish when it automatically prepends "$fish_user_paths" to the PATH.
```
Comment (meganrogge) [inline src/vs/platform/terminal/node/terminalEnvironment.ts:293]:
```suggestion
 * 2. For fish terminals, which always prepend "$fish_user_paths" to the PATH.
```

**Comment by meganrogge** [comment]
Should the PR title be updated to indicate Fish in general, not just on Linux?

**Comment by meganrogge** [comment]
Thanks for working on this. I created this issue - we'll want to link it to this PR. https://github.com/microsoft/vscode/issues/232495

**Review by meganrogge — APPROVED** [review]

**Review by sandy081 — APPROVED** [review]
