### PR TITLE
Selective task provider activation using a new `onTaskType:` activation event

### LINKED ISSUE #126238: Provide an onTask:foo activation event
When trying to run a task of type `foo` when the extension that contributes the relevant task provider _not activate_ the task fails with:

> There is no task provider registered for tasks of type "foo"

There's a suggestion at https://github.com/microsoft/vscode/issues/103942#issuecomment-669098534 that the extension should use an activation event of `onCommand:workbench.action.tasks.runTask`, but this seems too eager - it will result in the extension being activated for unrelated workspaces and using up resources (eg. spawning language servers, etc.).

I personally find it quite infuriating when I'm working in a workspace of one language type and some random action triggers the activation of a bunch of extensions that do expensive work (for example when the C# extension suddenly activates and starts downloading SDKs, which block some VS Code actions until it completes!). I'd prefer not to have my own extensions have that sort of behaviour.

### PR DESCRIPTION
**Pull request by alexdima**

### CODE REVIEW

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 1]
```diff
@@ -900,7 +982,12 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
 		this.openerService.open(URI.parse('https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher'));
 	}
 
-	private build(): Promise<ITaskSummary> {
+	private async build(): Promise<ITaskSummary> {
+		const buildTasks = await this._findWorkspaceTasksInGroup(TaskGroup.Build);
+		if (buildTasks.length > 0) {
+			// TODO: If a task was found, execute it and return early
```
Comment (alexdima) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:988]: I've left a TODO here

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 2]
```diff
@@ -917,7 +1004,12 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
 		});
 	}
 
-	private runTest(): Promise<ITaskSummary> {
+	private async runTest(): Promise<ITaskSummary> {
+		const cleanTasks = await this._findWorkspaceTasksInGroup(TaskGroup.Test);
+		if (cleanTasks.length > 0) {
+			// TODO: If a task was found, execute it and return early
```
Comment (alexdima) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:1010]: And another one here

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 3]
```diff
@@ -2647,30 +2739,8 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
...
-							buildTasks.push(task);
-						}
-					}
-				}
-				if (buildTasks.length > 0) {
-					break;
-				}
-			}
+		let promise = (async () => {
+			const buildTasks = await this._findWorkspaceTasksInGroup(TaskGroup.Build);
```
Comment (alexr00) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:2743]: This will only find default tasks. We still need to find the non-default build tasks for this command.

**Review by alexr00 — APPROVED** [review]
I've made the remaining changes and tested. It all looks good!

**Comment by alexdima** [comment]
Nice! 🚀

**Comment by DanTup** [comment]
Thanks, I appreciate this! (it would still be great to have some general guidance around extension activation though because it's still a little unclear how often we should expect to be activated in contexts where we might not really be needed :-) )
