### PR TITLE
Pass profiles, defaultProfile, isWorkspaceTrusted from renderer to shared process

### LINKED ISSUE #125440: Workspace trust doesn't work for terminal profiles
Steps to Reproduce:

1. In a trusted workspace, add a profile to your workspace settings
2. 🐛 it does not show up in the profile dropdown, Select Default Profile, etc bc `configurationService.getValue` isn't returning workspace settings

Workaround:
pass in whether or not the workspace is trusted to `detectProfiles`
use `inspect` instead of `getValue` in `terminalProfiles` to consolidate workspace/user profiles https://github.com/microsoft/vscode/blob/4ad3265cbed901777d32b169ea8bbd1ff2695ab9/src/vs/platform/terminal/node/terminalProfiles.ts#L40-L40

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #125440

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 1]
```diff
@@ -380,7 +382,8 @@ export class TerminalService implements ITerminalService {
 		if (!offProcService) {
 			return this._availableProfiles || [];
 		}
-		return offProcService?.getProfiles(includeDetectedProfiles);
+		const platform = await this._getPlatformKey();
+		return offProcService?.getProfiles(this._workspaceTrustManagementService.isWorkpaceTrusted(), this._configurationService.getValue(`${TerminalSettingPrefix.Profiles}${platform}`), this._configurationService.getValue(`${TerminalSettingPrefix.DefaultProfile}${platform}`), includeDetectedProfiles);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:386]: I don't think isWorkspaceTrusted is needed because getValue here will return the correct value?

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalService.ts:386]: correct
