### PR TITLE
fixes #80014

### LINKED ISSUE #80014: Updating breakpoint from debug adapter does not work if another session is focused
When implementing Debug Adapter Protocol, I sometimes issue `breakpoints` event where breakpoints change the `verified` status from `false` to `true`. If that happens while another debugging session is current (focused), the update is ignored.

I _think_ the problem is in [this line](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/debug/browser/debugSession.ts#L802). Here `idFromAdapter` depends on [currently focused](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/debug/common/debugModel.ts#L587) debugging session, which may or may not be the one receiving the event.

Steps to reproduce:
- Use this modified version of [vscode-mock-debug](https://github.com/dgozman/vscode-mock-debug/tree/breakpoints-bug).
- Run the mock debug extension on `testWorkspace` folder included in the branch above.
- Set breakpoint in the `session2.md` file on the line with "lazy".
- Launch "Bug" configuration.
- Two scenarios
  - If you select "Session2" during first 5 seconds, breakpoint on the "lazy" line will be verified after 5 seconds (Session2 will emit ["breakpoint changed"](https://github.com/dgozman/vscode-mock-debug/commit/8968db2384f75f5ba0639b0264bc788dd293dda4#diff-e70dc7454d13dfe5cd4251355a59111dR202) DAP event).
  - If you don't select "Session2" during first 5 seconds (e.g. do nothing, Session1 will be focused by default), the breakpoint will not be verified, and switching between sessions afterwards does not help.

### PR DESCRIPTION
**Pull request by dgozman**

### CODE REVIEW

**Comment by dgozman** [comment]
@isidorn Could you please take a look? This is my first PR to vscode, so any contributing suggestions are more than welcome!

**Comment by isidorn** [comment]
@dgozman thanks a lot for providing a PR. This looks great and captures the approach I had in mind. I left one minor comment inline in the code.
Did you build vscode with these changes and verifed that #80014 gets fixed?

File: src/vs/workbench/contrib/debug/common/debug.ts [hunk 1]
```diff
@@ -337,7 +337,7 @@ export interface IBaseBreakpoint extends IEnablement {
 	readonly hitCondition?: string;
 	readonly logMessage?: string;
 	readonly verified: boolean;
-	readonly idFromAdapter: number | undefined;
+	idFromAdapter(sessionId: string): number | undefined;
```
Comment (isidorn) [inline src/vs/workbench/contrib/debug/common/debug.ts]: I would prefer if this method is called `getIdFromAdapter` that way it would be more clear that it is a method, and not an attribute on the class.

**Review by isidorn — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/debug/common/debug.ts (hunk 1 above)
Comment (dgozman) [reply src/vs/workbench/contrib/debug/common/debug.ts]: Done.

**Review by dgozman — COMMENTED** [review]
> Did you build vscode with these changes and verifed that #80014 gets fixed?
Sure, my repro case works as expected with this change.

**Comment by isidorn** [comment]
Looks great, thanks a lot for this PR.
Merging in 🎉

**Comment by dgozman** [comment]
Thank you!
