### PR TITLE
get terminal accessible view/buffer to update dynamically

### LINKED ISSUE #191825: Terminal buffer is not updating information
Type: <b>Bug</b>

In the insiders version, I noticed that the buffer is no longer automatically reflecting terminal information.

For example, when executing the mvn clean install command in my project, the information of the build that starts to run is updated from time to time in the buffer, sometimes it is only necessary to give a tab to go to the terminal and give a shift tab that I have the information updated while the build is running and printing various information.

In the insiders version, this update no longer occurs.

I have to keep pressing alt + f2, but I couldn't be sure if I still have all the updated information.

VS Code version: Code - Insiders 1.82.0-insider (35be9bf683eace09796e59d54f1f225bbc3a7866, 2023-08-30T05:33:47.972Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (11.44GB free)|
|Process Argv|--crash-reporter-id dd13835f-488a-4675-bdf9-21fedc4249ef|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (4 x 1896)|
|Memory (System)|15.62GB (5.22GB free)|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.307.0
remote-wsl|ms-|0.81.0
cucumber-official|Cuc|1.7.0
gitlens|eam|2023.8.3005
copilot|Git|1.106.367
copilot-chat|Git|0.7.2023083001
vscode-docker|ms-|1.26.0
vscode-language-pack-pt-BR|MS-|1.82.2023083009
postman-for-vscode|Pos|0.6.2
vscode-thunder-client|ran|2.10.5
java|red|1.21.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.48.0
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.13
vscode-java-test|vsc|0.39.1
vscode-maven|vsc|0.42.0
vscode-spring-boot-dashboard|vsc|0.13.1
vscode-spring-initializr|vsc|0.11.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
2i9eh265:30646982
showlangstatbar:30737417
0bi6i642:30823812
ecj1e332:30687743
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonlinttypecf:30823782
pythonmpsinfo:30815194
dsvsc015:30821418

```

</details>

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #191825 and removes a hack 

Recording 2023-09-18 at 14 29 47

### CODE REVIEW

**Review by roblourens — APPROVED** [review]

File: src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminal.accessibility.contribution.ts [hunk 1]
```diff
@@ -90,23 +93,35 @@ export class TerminalAccessibleViewContribution extends Disposable implements IT
 		xterm.raw.loadAddon(addon);
 		addon.activate(xterm.raw);
 		this._xterm = xterm;
+		this._register(this._xterm.raw.onWriteParsed(async () => {
+			if (this._isTerminalAccessibleViewOpen() && this._xterm!.raw.buffer.active.baseY === 0) {
+				this.show();
+			}
+		}));
+
+		const onRequestUpdateEditor = Event.latch(this._xterm.raw.onScroll);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminal.accessibility.contribution.ts:102]: You need to register the new `Event` created via `Event.latch`. I think best practice would be:

```ts
		this._register(Event.latch(this._xterm.raw.onScroll, this._store)(() => {
			if (this._isTerminalAccessibleViewOpen()) {
				this.show();
			}
		}));
```

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminal.accessibility.contribution.ts:102]: Ok, is that different from registering the const that gets created as is currently done on the line below that one?

Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminal.accessibility.contribution.ts:102]: Actually it might be find actually. It's a little tough to understand but I think since `Emitter` is not a `DisposableStore`, disposing of it is optional. Its dispose just unsets everything:

https://github.com/microsoft/vscode/blob/613640d25feb7b9bdd8c6d056a7d5c7acfa870f8/src/vs/base/common/event.ts#L988-L1019

This is why this note exists:

https://github.com/microsoft/vscode/blob/613640d25feb7b9bdd8c6d056a7d5c7acfa870f8/src/vs/base/common/event.ts#L323-L329

If listeners exist outside of a class, ie. the event listeners created outside may not be disposed when Event.latch's Emitter is implicitly disposed, they can hold on to references.

All good as is 👌
