### PR TITLE
Make Search All Files search as you type

### LINKED ISSUE #46326: Auto search - option to search while typing
- VSCode Version: Version 1.21.1 (1.21.1)
- OS Version: macOS 10.13.3 (17D102)

Steps to Reproduce:

1. open workspace
2. type something in search - it will not execute search till click of Return/Enter or mouse click

Does this issue occur when all extensions are disabled?: Yes

While for some workspaces with tens of thousands of files it would be performance killer for smaller workspaces I would like to have the option to search "live". When I don't know the exact name of the file I could just start typing and search would make it's job.

### PR DESCRIPTION
**Pull request by JacksonKearl**
Closes #46326.

### CODE REVIEW

File: src/vs/workbench/contrib/search/browser/searchWidget.ts [hunk 1]
```diff
@@ -323,9 +324,6 @@ export class SearchWidget extends Widget {
 		this.searchInput.setRegex(!!options.isRegex);
 		this.searchInput.setCaseSensitive(!!options.isCaseSensitive);
 		this.searchInput.setWholeWords(!!options.isWholeWords);
-		this._register(this.onSearchSubmit(() => {
```
Comment (JacksonKearl) [inline src/vs/workbench/contrib/search/browser/searchWidget.ts]: extraneous, handled by searchView.

**Comment by jbwyme** [comment]
yes! so excited, thank you!
