### PR TITLE
Increase the configurability of auto-closing

### LINKED ISSUE #8536: autoClosingBrackets and bracket surround should be two features
I'd like to use the bracket surround functionality, where you select a word and enter a bracket-like character `' " ( {` and the word becomes surrounded by these characters.  VScode does this already, but only if you have autoClosingBrackets enabled.  I find the other behaviors of autoClosingBrackets really annoying (it swallows closing bracket characters if you type one which often leads to mistakes when using a multi-cursor edit).  It would be nice if we could have finer control over these behaviors.

### LINKED ISSUE #35197: Curly braces (brackets) not auto-completing in JSX tags.
- VSCode Version: 1.17.0-insider
- OS Version: Ubuntu 17.04

Steps to Reproduce:

1. Create a JS file.
2. Insure 'JavaScript' is set as the file type.
3. Write a function that returns a JSX (React) component.
```jsx
const Component = () =>
  <div>
  </div>
```
4. Add an attribute to the tag, like `className`.
```jsx
const Component = () =>
  <div className={>
                  ^ Should auto-complete the curly brace, here.
  </div>
```
5. Auto-complete of curly brace also not working in interpolated strings:
```jsx
const Component = () =>
  <div className={`${`}>
                     ^ Should auto-complete the curly brace, here.
  </div>
```

Reproduces without extensions: Yes

### LINKED ISSUE #36259: "editor.autoClosingBrackets" granularity
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-add-nativescript-files|ale|1.0.1
vscode-svgviewer|css|1.4.3
xml|Dot|1.9.2
auto-close-tag|for|0.5.1
mssql|ms-|1.2.0
csharp|ms-|1.12.1
vs-keybindings|ms-|0.1.7
vetur|oct|0.9.11
material-icon-theme|PKi|2.2.2
vscode-icons|rob|7.15.0
code-settings-sync|Sha|2.8.3
nativescript|Tel|0.7.2

---
"editor.autoClosingBrackets" disables all closing "things" (as parenthesis, quotes, brackets, etc.).
It would be nice if those settings were by type: editor.autoClosingQuotes, editor.autoClosingParenthesis and editor.autoClosingBrackets.
Also, it would be a LOT helpful if braces were inserted only after typing enter (and no immediatly after typing "{")

Steps to Reproduce:

1. Edit settings and set "editor.autoClosingBrackets": false
2. Only brackets should be disabled for autoClosing (as quotes are not brackets, nor are parenthesis)

Reproduces without extensions: Yes

### PR DESCRIPTION
**Pull request by JacksonKearl**
Closes #35197 and  closes #36259 and closes #8536.

### CODE REVIEW

**Comment by JacksonKearl** [comment]
This modifies the "editor.autoClosingBrackets" config option to accept a configuration object as an alternative to the current true/false. It also adds an "editor.autoClosingQuotes" which allows for configuring quote auto-closing behavior separately from the bracket behavior.  

The default config objects look as follows:
```
  // Controls if and when the editor should automatically close brackets after opening them
  "editor.autoClosingBrackets": {
    "autoClose": true,
    "autoWrap": true,
    "enabledBefore": ",.:; \n\t"
  },

  // Controls if and when the editor should automatically close quotes after opening them
  "editor.autoClosingQuotes": {
    "autoClose": true,
    "autoWrap": true,
    "enabledBefore": " \n\t"
  },
```

For backwards compatibility and simplicity, these options still accept a boolean value, which will enable or disable both auto-wrapping and auto-closing.

The `enabledBefore` parameter for `autoClosingBrackets` has been extended from just whitespace to include standard punctuation, as autoClosing not working before punctuation was a common source of issues. 

These configuration settings also allow for language specific settings, such as for HTML:
```
  "[html]": {
    "editor.autoClosingQuotes": {
      "autoClose": true,
      "autoWrap": true,
      "enabledBefore": "<> \n\t"
    },
    "editor.autoClosingBrackets": {
      "autoClose": true,
      "autoWrap": true,
      "enabledBefore": ",.:;<> \n\t"
    }
  }
```
Which allows easier tempting, like auto-closing the braces in: `<div>{{}}</div>`.

**Comment by JacksonKearl** [comment]
Feedback at sitdown was to move "enabledBefore" to language config. I feel like the user should have some ability to configure it, but maybe move the defaults to language config?

File: src/vs/editor/common/controller/cursorDeleteOperations.ts [hunk 1]
```diff
@@ -49,7 +49,8 @@ export class DeleteOperations {
 	}
 
 	private static _isAutoClosingPairDelete(config: CursorConfiguration, model: ICursorSimpleModel, selections: Selection[]): boolean {
-		if (!config.autoClosingBrackets) {
+		if (!(config.autoClosingBrackets.autoClose || config.autoClosingBrackets.autoWrap
+			|| config.autoClosingQuotes.autoClose || config.autoClosingQuotes.autoWrap)) {
```
Comment (evgenyKozlov1996) [inline src/vs/editor/common/controller/cursorDeleteOperations.ts]: May you create a small private function which will contain this check? It will be better for readability.

**Review by evgenyKozlov1996 — CHANGES_REQUESTED** [review]

**Comment by MrLoh** [comment]
I think most editors (e.g. sublime, atom), handle this very well by default. It'd be nice to give the user some control, but good defaults for common languages should prevent most users from ever having to think about this and the language settings certainly seem like a good place to handle such specific tweaking. 

Hope this will land soon ❤️

File: src/vs/editor/common/config/editorOptions.ts [hunk 2]
```diff
@@ -1586,7 +1637,8 @@ export class EditorOptionsValidator {
 			wordWrapBreakBeforeCharacters: _string(opts.wordWrapBreakBeforeCharacters, defaults.wordWrapBreakBeforeCharacters),
 			wordWrapBreakAfterCharacters: _string(opts.wordWrapBreakAfterCharacters, defaults.wordWrapBreakAfterCharacters),
 			wordWrapBreakObtrusiveCharacters: _string(opts.wordWrapBreakObtrusiveCharacters, defaults.wordWrapBreakObtrusiveCharacters),
-			autoClosingBrackets: _boolean(opts.autoClosingBrackets, defaults.autoClosingBrackets),
+			autoClosingBrackets: _autoClosingOptions(opts.autoClosingBrackets, defaults.autoClosingBrackets),
+			autoClosingQuotes: _autoClosingOptions(opts.autoClosingQuotes, defaults.autoClosingQuotes),
```
Comment (rebornix) [inline src/vs/editor/common/config/editorOptions.ts]: We may want to make sure the old boolean `autoClosingBrackets` contributes to `autoClosingQuotes` as well. If `autoClosingBrackets` is `true`, which is the old default value, `autoClosingQuotes` needs to be true otherwise users will miss auto quotes closing.

File: src/vs/editor/common/config/editorOptions.ts [hunk 3]
```diff
@@ -2279,7 +2333,8 @@ export const EDITOR_DEFAULTS: IValidatedEditorOptions = {
 	wordWrapBreakBeforeCharacters: '([{‘“〈《「『【〔（［｛｢£¥＄￡￥+＋',
 	wordWrapBreakAfterCharacters: ' \t})]?|&,;¢°′″‰℃、。｡､￠，．：；？！％・･ゝゞヽヾーァィゥェォッャュョヮヵヶぁぃぅぇぉっゃゅょゎゕゖㇰㇱㇲㇳㇴㇵㇶㇷㇸㇹㇺㇻㇼㇽㇾㇿ々〻ｧｨｩｪｫｬｭｮｯｰ”〉》」』】〕）］｝｣',
 	wordWrapBreakObtrusiveCharacters: '.',
-	autoClosingBrackets: true,
+	autoClosingBrackets: { autoClose: true, autoWrap: true, enabledBefore: ',.:; \n\t' },
+	autoClosingQuotes: { autoClose: true, autoWrap: true, enabledBefore: ' \n\t' },
```
Comment (rebornix) [inline src/vs/editor/common/config/editorOptions.ts]: Should `enabledBefore` be general whitespaces in this case?

**Comment by rebornix** [comment]
@JacksonKearl sorry for responding late, the code in overall looks good to me. My only concern is still the one we mentioned in sitdown about `enabledBefore`, putting it into editor configuration is powerful but it will confuse language contributors. For example, below is the language configuration for HTML

```
	"autoClosingPairs": [
		{ "open": "{", "close": "}"},
		{ "open": "[", "close": "]"},
		{ "open": "(", "close": ")" },
		{ "open": "'", "close": "'" },
		{ "open": "\"", "close": "\"" },
		{ "open": "<!--", "close": "-->", "notIn": [ "comment", "string" ]}
	],
	"surroundingPairs": [
		{ "open": "'", "close": "'" },
		{ "open": "\"", "close": "\"" },
		{ "open": "{", "close": "}"},
		{ "open": "[", "close": "]"},
		{ "open": "(", "close": ")" },
		{ "open": "<", "close": ">" }
	]
```

This two configurations control what characters to use for auto closing or auto surrounding, as you can see we didn't separate them into auto closing/surrounding *Quotes* and *Brackets*. Our existing `editor.autoClosingBrackets` is not a perfect name as it controls most of these pairs (except the multi character ones). Now whether we should auto close a character becomes a bit confusing

1. we check if it's in `autoClosingPairs`
2. we check if it should not be triggered by checking `notIn`
3. we check if it's brackets or quotes, and then validate against `editor.autoClosingBrackets.autoClose` or `editor.autoClosingQuotes.autoClose`
4. we check if it's before `editor.autoClosingBrackets.enabledBefore`

1 & 2 are from language configuration, 3 & 4 are controlled by the editor configuration. 1 & 3 are static while 2 & 4 are determined by token information. 2 or 4 doesn't know about each other and can't work together.

We can probably let the language configuration decide *what* (autoClosingPairs, surroundingPairs) and *how* (notIn, enabledBefore), and the core editor decides *if* (autoClose, autoWrap, etc), instead of mixing them. @JacksonKearl what do you think?

**Comment by JacksonKearl** [comment]
The separation of concerns between user level config and language extension config makes sense to me, but I do think users want more configuration over the `when` than is presently available. What would you think of having the settings options be something along the lines of:
```
autoPairBrackets.autoClose: 'always' | 'beforePunctuationAndWhitespace' | 'beforeWhitespace' | 'never'
autoPairBrackets.autoWrap: true | false
autoPairQuotes.autoClose: 'always' | 'beforePunctuationAndWhitespace' | 'beforeWhitespace' | 'never'
autoPairQuotes.autoWrap: true | false
```
Then letting the language config decide what punctuation is and what quotes are?

**Comment by JacksonKearl** [comment]
@rebornix updated with a new interface...
`editor.autoClosingQuotes` and `editor.autoClosingBrackets` can be `always`, `never`, `beforeWhitespace`, or `languageDefined`. 

`always` and `never` are as they sound, `beforeWhitespace` is the preexisting behaviour, and `languageDefined` uses a string in `language-config.json` to determine when to autoclose. 

`languageDefined` defaults to allowing `;:.,=}])> \n\t` to fall after the cursor as a prerequisite for autoclosing to occur, and extension authors are instructed to add characters that can not be at the start of an expression in their languages, as this seems to make the most sense semantically. The default (`;:.,=}])> \n\t`) is a greatest subset of those characters that makes sense for most common languages.

`editor.autoWrapping` can be `always`, `never`, `brackets`, or `quotes`.

For backwards compatibility, if `editor.autoClosingBrackets` is `false`, all settings will  be set to `never`, and a green squiggle will appear under the relevant line in the settings file, instructing the user to use the new interface.

the new default is `languageDefined` for autoclosing, and `always` for autowrapping.

**Comment by JacksonKearl** [comment]
The one specialization to the language defined mode I've added is support for the backtick as an autoCloseBefore for javascript and typescript. This goes against the usual paradigm of "only characters which cannot start an expression", but it makes sense in the JS/TS context because of how backticks are used as template strings, which require embedded curly braces. This use case is probably much more common than using backtics in an expression like:
```
`{`
```

**Comment by JacksonKearl** [comment]
Ping @alexandrudima for input

**Comment by MrLoh** [comment]
Another release without this fix. How is this not one of the top priorities? This effects tons of users every minute they tipe in VSCode their daily work. Breadcrumbs and stuff are all nice, but this is essential. It's very frustrating that this is not getting merged.

**Comment by alexandrudima** [comment]
@JacksonKearl Very high quality! Good job!
