### PR TITLE
Fix webview views not updating correctly on scroll

### LINKED ISSUE #110450: bug positioning of webview in explorer
- VSCode Version: 1.51
- OS Version:macOS 10.6.7

Steps to Reproduce:

My extension have 4 view. just the second view is webview.
1. expand the second view and the third view.
2. expand and shrink the first view, the second view will be broken

屏幕录制2020-11-12 下午2 20 25

Does this issue occur when all extensions are disabled?: Yes/No

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #110450

This fixes two issues with webview views that are inside view pane containers that are overflowing:

- When a container with webview views is scrolled, we need to update the positon of the webview

- If the webview is then scrolled outside of the container, we need to make sure it is clipped so it does not draw on top of other interface elements

Both of these are required since the webview is not part of the normal editor dom. Instead it is a top level element that is absolutely positioned in the slot it needs to me

### CODE REVIEW

**Comment by mjbvz** [comment]
@sbatten and @joaomoreno Please look at the changes to the split view and view panes to let me know if this  approach is ok or if there's a better way to accomplish this. If things look good, I'll go ahead and update the other files in the codebase to pass through the new parameters

File: src/vs/base/browser/ui/splitview/splitview.ts [hunk 1]
```diff
@@ -237,6 +237,9 @@ export class SplitView<TLayoutContext = undefined> extends Disposable {
 	private _onDidSashReset = this._register(new Emitter<number>());
 	readonly onDidSashReset = this._onDidSashReset.event;
 
+	private _onScroll = this._register(new Emitter<ScrollEvent>());
```
Comment (joaomoreno) [inline src/vs/base/browser/ui/splitview/splitview.ts:240]: This emitter doesn't need to exist. We can just `this.onScroll = this.scrollableElement.onScroll`, right?

File: src/vs/base/browser/ui/splitview/paneview.ts [hunk 2]
```diff
@@ -286,7 +287,7 @@ export abstract class Pane extends Disposable implements IView {
 	}
 
 	protected abstract renderHeader(container: HTMLElement): void;
-	protected abstract renderBody(container: HTMLElement): void;
+	protected abstract renderBody(container: HTMLElement, rootContainer: HTMLElement): void;
```
Comment (joaomoreno) [inline src/vs/base/browser/ui/splitview/paneview.ts:290]: This makes me itchy. 🙈

Comment (joaomoreno) [reply src/vs/base/browser/ui/splitview/paneview.ts:290]: I think this is a hack, but I also can't propose a good solution. Nevertheless, my rule for hacks is: keep them as contained as possible. In that mindset, couldn't we simply navigate up the parent DOM chain in `layoutWebview()`, find the element we assume to be the _root element_ and use that? The hack would not spread to other files and would also not change component API.

Comment (mjbvz) [reply src/vs/base/browser/ui/splitview/paneview.ts:290]: Ok, I think that should be possible. As you note, it will require touching less code but could break if the parent dom structure changes (such as if an element's class is renamed)

I originally tried using intersection observers for this but couldn't get them working as I needed

Comment (joaomoreno) [reply src/vs/base/browser/ui/splitview/paneview.ts:290]: >  intersection observers

TIL!

**Comment by mjbvz** [comment]
Merging this so we can get some testing. Let me know if you have any concerns about the implementation
