### PR TITLE
Fix onBell listener being registered after term dispose, allow for DisposableStore-managed disposableTimeouts

### LINKED ISSUE #190251: Trying to add a disposable to a DisposableStore that has already been disposed of
* run integration tests
* very many error like below are printed

```
Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at DisposableStore.add (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/common/lifecycle.js:210:34)
    at TerminalInstance._register (vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/common/lifecycle.js:248:32)
    at vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:568:22", source: vscode-file://vscode-app/Users/jrieken/Code/_collab/vscode2/out/vs/base/common/lifecycle.js (210)
```

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #190251

### CODE REVIEW

**Review by aeschli — APPROVED** [review]

File: src/vs/base/common/async.ts [hunk 1]
```diff
@@ -490,9 +490,36 @@ export function timeout(millis: number, token?: CancellationToken): CancelablePr
...
+ * // Call the timeout after 1000ms at which point it will be automatically
+ * // evicted from the store.
+ * const timeoutDisposable = disposableTimeout(() => {}, 1000, store);
+ *
+ * if (foo) {
+ *   // Cancel the timeout and evict it from store.
+ *   timeoutDisposable.dispose();
+ * }
+ */
+export function disposableTimeout(handler: () => void, timeout = 0, store?: DisposableStore): IDisposable {
```
Comment (hediet) [inline src/vs/base/common/async.ts:510]: I think it might be better to to put the timeout as first argument. I rarely skip that argument and shorter arguments (such as const numbers) should be before longer arguments (such as functions).

I would also rename this function to be in verb-form, e.g. `setDisposableTimeout` or `setTimeoutDisposable`.

File: src/vs/base/common/lifecycle.ts [hunk 2]
```diff
@@ -430,6 +430,34 @@ export class DisposableStore implements IDisposable {
...
+	/**
+	 * Deletes a disposable from store and disposes of it. This will not throw or warn and proceed to dispose the
+	 * disposable even when the disposable is not part in the store.
+	 */
+	public delete<T extends IDisposable>(o: T): void {
+		if (!o) {
+			return;
+		}
+		if ((o as unknown as DisposableStore) === this) {
+			throw new Error('Cannot dispose a disposable on itself!');
```
Comment (hediet) [inline src/vs/base/common/lifecycle.ts:443]: Does this happen in practice? If so, I think the error message should be adjusted and `BugIndicatingError` should be used.

File: src/vs/base/common/lifecycle.ts [hunk 3]
```diff
@@ -430,6 +430,34 @@ export class DisposableStore implements IDisposable {
 
 		return o;
 	}
+
+	/**
+	 * Deletes a disposable from store and disposes of it. This will not throw or warn and proceed to dispose the
+	 * disposable even when the disposable is not part in the store.
+	 */
+	public delete<T extends IDisposable>(o: T): void {
+		if (!o) {
```
Comment (hediet) [inline src/vs/base/common/lifecycle.ts:439]: Type checks should prevent this from ever happening:

Code_-_Insiders_2h0lrwsH89

I would either change it to `o: T | undefined` or remove that check (otherwise it might swallow fishy runtime behavior).

File: src/vs/base/common/lifecycle.ts [hunk 4]
```diff
@@ -430,6 +430,34 @@ export class DisposableStore implements IDisposable {
 
 		return o;
 	}
+
+	/**
+	 * Deletes a disposable from store and disposes of it. This will not throw or warn and proceed to dispose the
+	 * disposable even when the disposable is not part in the store.
+	 */
+	public delete<T extends IDisposable>(o: T): void {
```
Comment (hediet) [inline src/vs/base/common/lifecycle.ts:438]: I know it is called `Set.delete`, but I think this method should be called `remove`. Better even would be `removeAndDispose`

Comment (Tyriar) [reply src/vs/base/common/lifecycle.ts:438]: I was going to call it remove, but it's using add and delete internally on Set which aligns with the web api. Instead of delete and deleteAndDispose, I flipped them do delete (and dispose, common case) and deleteAndLeak (rare case).

File: src/vs/base/common/lifecycle.ts (hunk 3 above)
Comment (Tyriar) [reply src/vs/base/common/lifecycle.ts:439]: It aligns with `Set.delete`, the `if (!o)` check if to make it work the same as `DisposableStore.add`

File: src/vs/base/common/lifecycle.ts (hunk 2 above)
Comment (Tyriar) [reply src/vs/base/common/lifecycle.ts:443]: 🤷 just doing what `add` does

File: src/vs/base/common/lifecycle.ts (hunk 4 above)
Comment (hediet) [reply src/vs/base/common/lifecycle.ts:438]: I just think it might be surprising that `delete` also disposes the object.

File: src/vs/base/common/async.ts (hunk 1 above)
Comment (hediet) [reply src/vs/base/common/async.ts:510]: Ah, I misread the diff, I thought this method was added in this PR.

File: src/vs/base/common/lifecycle.ts (hunk 2 above)
Comment (hediet) [reply src/vs/base/common/lifecycle.ts:443]: At least the error message is weird.

File: src/vs/base/common/lifecycle.ts (hunk 4 above)
Comment (Tyriar) [reply src/vs/base/common/lifecycle.ts:438]: I would think the opposite, the main concern is leaks so disposing is the safe option imo.

Comment (Tyriar) [reply src/vs/base/common/lifecycle.ts:438]: We can be explicit on both though, as long as the leak one is called out
