### PR TITLE
Fix #97564

### LINKED ISSUE #97564: missing icons due to wrong svg content type
Issue Type: <b>Bug</b>

Try to set File Icon Theme to other than Seti (Visual Studio Code), and file icons will show no icons (or an empty tab space as icon). Also, somehow the root cause affected my 'Bookmarks' Extension which shows no icon. 

Anotación 2020-05-11 200509

I've downgraded VSCode to version 1.42, and the issue is not present there.
I'm pretty sure the issue is not related to VSCode version, as I have installed the latest version to another PC, and the issue is not present there.

I've also reinstalled VSCode as many as four or five times, deleting some tmp files from VSCode, but have not got rid of the issue.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.2.0
bracket-pair-colorizer|Coe|1.0.61
python|ms-|2020.4.76186
cpptools|ms-|0.28.0-insiders3
vscode-icons|vsc|10.1.1
srecord|xia|0.0.3

</details>

### PR DESCRIPTION
**Pull request by rzhao271**
This PR fixes #97564

### CODE REVIEW

**Comment by deepak1556** [comment]
@sandy081 this also fixes an issue where the webrequest listeners where not working because of the null argument.

**Comment by sandy081** [comment]
@deepak1556  Thanks for the info.

I am not very much familiar with this code so I would go with your review. 

Please let me know if I can help with sharing any info you need.

File: src/vs/code/electron-main/window.ts [hunk 1]
```diff
@@ -424,24 +424,36 @@ export class CodeWindow extends Disposable implements ICodeWindow {
...
 
 			return callback({});
 		});
 
-		this._win.webContents.session.webRequest.onHeadersReceived(null!, (details, callback) => {
+		this._win.webContents.session.webRequest.onHeadersReceived((details, callback) => {
 			const responseHeaders = details.responseHeaders as Record<string, (string) | (string[])>;
-
 			const contentType = (responseHeaders['content-type'] || responseHeaders['Content-Type']);
-			if (contentType && Array.isArray(contentType) && contentType.some(x => x.toLowerCase().indexOf('image/svg') >= 0)) {
```
Comment (deepak1556) [inline src/vs/code/electron-main/window.ts:443]: /cc @mjbvz based on commit https://github.com/microsoft/vscode/commit/577105a72c08400f3311b92efefbe2a0fe23982c

Can you clarify if this was only intended to prevent loading svg from remote url or all urls ? Is it okay to allow loading for `file`, `vscode-file` protocol which we are using to load the app resources ?

File: src/vs/code/electron-main/window.ts [hunk 2]
```diff
@@ -424,24 +424,36 @@ export class CodeWindow extends Disposable implements ICodeWindow {
...
 
-		// Prevent loading of svgs
-		this._win.webContents.session.webRequest.onBeforeRequest(null!, (details, callback) => {
-			if (details.url.indexOf('.svg') > 0) {
+		// Prevent loading of remote svgs
+		this._win.webContents.session.webRequest.onBeforeRequest((details, callback) => {
+			if (details.url.endsWith('.svg')) {
 				const uri = URI.parse(details.url);
-				if (uri && !uri.scheme.match(/file/i) && uri.path.endsWith('.svg')) {
+				if (uri && uri.scheme.toLowerCase() !== 'file') {
```
Comment (deepak1556) [inline src/vs/code/electron-main/window.ts:431]: Use scheme constants from https://github.com/microsoft/vscode/blob/master/src/vs/base/common/network.ts#L41 

`Schemas.file` and also should allow for `Schemas.vscodeFileResource`

File: src/vs/code/electron-main/window.ts (hunk 1 above)
Comment (mjbvz) [reply src/vs/code/electron-main/window.ts:443]: Remote resources were the main concern. We wanted to block svgs in hovers for example

Comment (deepak1556) [reply src/vs/code/electron-main/window.ts:443]: Thanks for confirming @mjbvz

**Review by deepak1556 — APPROVED** [review]
