### PR TITLE
Avoid List View default find widget steal keybindings.

### LINKED ISSUE #156604: Find in Notebook/Settings/Keybindings stops working
* Open a notebook
* Put focus into a cell editor
* Ctrl/Cmd+F, Find Widget doesn't show up
* Put focus on cell container (out of Monaco editor), Ctrl+Cmd +F, Find Widget shows up

It's a regression, and my guess is we introduced `list.find` recently for File Explorer. @joaomoreno what's the best way to allow us override it?

### PR DESCRIPTION
**Pull request by rebornix**
Fix #156604. Avoid the builtin find widget in List/Tree view steals the keybindings for customized Find support in Notebook, Settings Editor and Keybindings Editor.

### CODE REVIEW

File: src/vs/workbench/contrib/preferences/browser/settingsTree.ts [hunk 1]
```diff
@@ -2367,6 +2367,7 @@ export class SettingsTree extends WorkbenchObjectTree<SettingsTreeElement> {
 				filter: instantiationService.createInstance(SettingsTreeFilter, viewState),
 				smoothScrolling: configurationService.getValue<boolean>('workbench.list.smoothScrolling'),
 				multipleSelectionSupport: false,
+				findWidgetEnabled: false
 			},
```
Comment (rebornix) [inline src/vs/workbench/contrib/preferences/browser/settingsTree.ts:2371]: @rzhao271 this allows `Ctrl/Cmd+F` to put focus into the settings input box.

**Review by joaomoreno — APPROVED** [review]
Really nice fix!
