### PR TITLE
fix bugs & polish

### LINKED ISSUE #131190: Inconsistent terminal renaming when using the editor area
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: Arch Linux

Steps to Reproduce:

1. Open two or more terminals in the panel.
2. Move one or more terminals into the editor area.
image
3. Attempt to rename either an unfocused editor area terminal, or if only one terminal remains in the panel, the panel terminal by right clicking when the editor area has had last focus.
image
image
image
4. The name of the most recently focused editor terminal (even if none is presently selected) changes, rather than the right-clicked terminal (whether an unfocused editor area terminal or the unfocused panel terminal).
image

Expected behaviour:

The name of the terminal selected on right click will be changed.

### LINKED ISSUE #131276: Clean up and pull apart NewWithProfile command
https://github.com/microsoft/vscode/blob/c8612458cb50f259b400a445b2cefe393106429f/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L2020-L2064

### LINKED ISSUE #131595: vscode.TerminalLocation.Editor always goes to the first view column
Testing #131278
```
vscode.window.createTerminal({
        location: vscode.TerminalLocation.Editor
      });
```
always goes to column 1. I would have expected it to go to the active view column.

Is that expected?

### LINKED ISSUE #131813: Show terminal type (eg. Task) next to the title in the term quick access
image

It should say "Task" like in the tabs:

image

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #131190
fixes #131595
fixes #131276
fixes #131813

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalActions.ts [hunk 1]
```diff
@@ -748,8 +748,11 @@ export function registerTerminalActions() {
 				precondition: TerminalContextKeys.processSupported
 			});
 		}
-		async run(accessor: ServicesAccessor) {
-			return accessor.get(ITerminalService).activeInstance?.changeIcon();
+		async run(accessor: ServicesAccessor, resource: unknown) {
+			const terminalService = accessor.get(ITerminalService);
+			const castedResource = URI.isUri(resource) ? resource : undefined;
+			const instance = terminalService.getInstanceFromResource(castedResource) || terminalService.activeInstance;
+			instance?.changeIcon();
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalActions.ts:755]: Could reduce some repetition by making something similar to `doWithActiveInstance`:

```ts
doWithResourceOrActiveInstance<T>(resource: unknown | URI | undefined, callback: (terminal: ITerminalInstance) => T): T | void {
}

async run(accessor: ServicesAccessor, resource: unknown) {
  accessor.get(ITerminalService).doWithResourceOrActiveInstance(e => e.changeIcon());
}
```

File: src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts [hunk 2]
```diff
@@ -163,13 +163,14 @@ export class TerminalEditorService extends Disposable implements ITerminalEditor
...
 				resource,
+				description: instance.shellLaunchConfig.description,
 				options:
 				{
 					pinned: true,
 					forceReload: true,
 					preserveFocus: editorOptions?.preserveFocus
 				}
-			}, editorOptions?.viewColumn);
+			}, editorOptions?.viewColumn || ACTIVE_GROUP);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts:173]: Is this not implied when undefined?

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts:173]: I would've thought so, but apparently not

File: src/vs/workbench/contrib/terminal/browser/terminalActions.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalActions.ts:755]: thought about it, but wasn't sure if it was worth adding another method to terminal service since it's only used in 3 places.
