### PR TITLE
make the timeout for formatOnSave configurable

### LINKED ISSUE #41194: Format Document working, editor.formatOnSave=true broken
- VSCode Version: 1.19
- OS Version: Mac OS 10.12.6

I am having some trouble with `editor.formatOnSave=true` when using the Ruby extension. It isn't formatting on save. This is strange, because a manual `Format Document` works fine. How is that possible?

I assumed this was user error or an extension bug. So I modified the extension locally and added some debug output to this file:

https://github.com/rubyide/vscode-ruby/blob/master/src/format/rubyFormat.ts

I verified that the correct edits were being returned from `provideDocumentFormattingEdits`. This makes sense since a manual `Format Document` works fine. What am I missing? Could this be a vscode bug? Not sure how to debug further.

### PR DESCRIPTION
**Pull request by buyology**
Fixes #41194 

As reported by users of extensions for `TypeScript`, `Python`, `ruby` and `go` `formatOnSave`-commands can take longer than the hard coded `750 ms`, e.g. for large projects or complex commands.

This removes the hardcoded value and instead makes it user configurable.

### CODE REVIEW

File: src/vs/workbench/parts/files/electron-browser/files.contribution.ts [hunk 1]
```diff
@@ -298,6 +298,12 @@ configurationRegistry.registerConfiguration({
 			'description': nls.localize('formatOnSave', "Format a file on save. A formatter must be available, the file must not be auto-saved, and editor must not be shutting down."),
 			'overridable': true,
 			'scope': ConfigurationScope.RESOURCE
+		},
+		'editor.formatOnSaveTimeout': {
```
Comment (MikhailArkhipov) [inline src/vs/workbench/parts/files/electron-browser/files.contribution.ts]: Setting is editor-global, it will be hard for end user to figure out correct timeout as it depends on the language and the machine speed.

Comment (buyology) [reply src/vs/workbench/parts/files/electron-browser/files.contribution.ts]: True. Made it overridable, then at least every extension that identifies this as a potential issue can provide a sane default (as well as the user).

**Comment by buyology** [comment]
Any update on this @jrieken?

**Comment by prateek** [comment]
+1 I was about to put up a PR for the same thing.

**Comment by jrieken** [comment]
Back from vacations... Too late for Feb-endgame but will take a look in March.

**Review by jrieken — APPROVED** [review]
Looks good. I will merge as soon as master is open for business again.
