### PR TITLE
fix: snap env variables leaking into terminal env

### LINKED ISSUE #179086: GTK+ module libcanberra-gtk-module.so cannot be loaded
Hello guys,

I'm using _OpenCV_ in VSCode (Ubuntu Software installation) and everything worked fine, until I updated my libraries (`sudo apt-get update/upgrade/full-upgrade`) I guess. But now VSCode or rather _OpenCV_ can't find the _GTK_ library. 

I've tested this succesfully:
 `GTK_PATH=/usr/lib/x86_64-linux-gnu/gtk-2.0 ./test` --> works

But when I specify the version gtk-3.0:
`GTK_PATH=/usr/lib/x86_64-linux-gnu/gtk-3.0 ./test` --> fails

 Normally the loaded version without using GTK_PATH is gtk-3.0 and then it shows me this error:
image

I verified that the in `/usr/lib/x86_64-linux-gnu/gtk-3.0/modules` is:

image

Would appreciate to solve this warning and to understand why the .so cannot be loaded.

Thanks in advance

**UPDATE:** the example code can be executed without warnings in the normal gnome terminal, but VSCode seems to habe problems to find the specific libraries, so it's definitely _VSCode_.

### LINKED ISSUE #179917: Snap: no links open at all
Does this issue occur when all extensions are disabled?: Yes

version info:

```
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:52.732Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 6.2.10-1-MANJARO snap
Sandboxed: No
```

Steps to Reproduce:

1. Install VS Code from Snap, and run with no extensions enabled.
2. Click a link in a comment in some code or document.
3. Observe that nothing happens.

This also prevents me from completing GitHub authentication, and from submitting this bug report through the issue reporter.

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes https://github.com/microsoft/vscode/issues/179917
Fixes https://github.com/microsoft/vscode/issues/179086

### CODE REVIEW

**Review by joaomoreno — APPROVED** [review]

File: src/vs/platform/environment/electron-main/environmentMainService.ts [hunk 1]
```diff
@@ -64,4 +70,39 @@ export class EnvironmentMainService extends NativeEnvironmentService implements
...
 	get useCodeCache(): boolean { return !!this.codeCachePath; }
+
+	unsetSnapExportedVariables() {
+		if (!isLinux) {
+			return;
+		}
+		for (const key in process.env) {
+			if (key.endsWith('_VSCODE_SNAP_ORIG')) {
+				const originalKey = key.slice(0, -17); // Remove the _VSCODE_SNAP_ORIG suffix
+				if (this._snapEnv[originalKey]) {
```
Comment (AmeyaVS) [inline src/vs/platform/environment/electron-main/environmentMainService.ts:81]: This seems suspicious.
Is it checking the `_snapEnv[originalKey]` is empty or not?
If it is not empty then it will skip the the complete loop logic following it.

Comment (deepak1556) [reply src/vs/platform/environment/electron-main/environmentMainService.ts:81]: `_snapEnv[originalKey]` will not be defined when this function gets called, this is only present when multiple `unsetSnapExportedVariables()` calls are made without calling to `restoreSnapExportedVariables()`, which does not happen today.
