### PR TITLE
size to content width per instance and for proper viewport (#134393)

### LINKED ISSUE #133962: View port wrong
Testing #133550

~~Sorry, no good steps yet but after toggling content width a couple I time I ended up with frozen view port dimensions, esp vertically~~

* open a terminal
* type `ls -la`
* toggle wrapping a few times and repeat the `ls -la` command
* :bug: size goes off

https://user-images.githubusercontent.com/1794099/135058934-5ff6a37a-d843-4e66-923a-130c3ace85fc.mov

### LINKED ISSUE #133971: Toggling fixed width only works one way
Testing #133550

* have fixed with on
* in a narrow terminal type `ls -la`
* select `alt+z`, existing text is re-rendered correctly
* select `alt+z` again, :bug: no effect

https://user-images.githubusercontent.com/1794099/135059941-07d76af4-b5cf-4e9c-ad16-059bcd3025ae.mov

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #133971 fixes #133962

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 1]
```diff
@@ -1989,10 +1988,6 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 		let newIndex = index;
 		while (line?.isWrapped) {
 			width += line.length;
-			for (let i = 0; i < line.length; i++) {
-				const cell = line.getCell(i);
-				width += cell?.getWidth() || 0;
-			}
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1995]: was accounting for this twice
