### PR TITLE
Fix: Upgrading Extensions Blows Up

### LINKED ISSUE #1111: Extensions: Upgrading Extensions Blows Up
I pushed out a new version of the Vim extension, however, when upgrading it on top of the existing version, we are seeing this error: https://github.com/VSCodeVim/Vim/issues/93. Installing the new version by itself (with no previous versions of the Vim extension) works successfully. 

I've been unsuccessful at getting a repro. Is there a way in which I can install a specific version from the marketplace?

I've built the packages (`vsce package`) and made them available here: https://github.com/VSCodeVim/Vim/releases. I have tried:

1) `code vim-0.0.2.vsix` - This installs successfully
2) On top of the existing install `code vim-0.0.3.vsix`, VSCode blows up with a different error than reported in https://github.com/VSCodeVim/Vim/issues/93. The [console log is here](https://github.com/Microsoft/vscode/files/55978/vscode-blows-up.txt).
3) Installing `code vim-0.0.3.vsix` (not upgrading) works fine

tldr;
* Is there a way to install a specific version of an extension from the marketplace?
* Barring the above, is manually upgrading a plugin through the vsix expected to work?

### PR DESCRIPTION
**Pull request by joaomoreno**
Fixes #1111

@alexandrudima, would be great to get a second pair of eyes in this, mind reviewing? We can do a live code review in Lync, if you want.

Here are my intended changes:
- The **extension service** should install each extension to a path containing the extension's version. Example: `.vscode/extensions/joaomoreno.uuid-0.0.2`.
- The `scanPlugin` call should only return the latest extension version, in case there are multiple versions of the same extension installed, per extension folder (global vs user).
- The **extension service** should clean up old extension versions in the user's extension folder, on startup. Currently set to run once 5 seconds after startup.
- The **list extensions** action should only display the latest version of an extension.

This also needs extensive testing, which I will do through today.

### CODE REVIEW

File: src/vs/workbench/node/extensionPoints.ts [hunk 1]
```diff
@@ -81,22 +83,37 @@ export class PluginScanner {
...
+		absoluteFolderPath:string,
+		isBuiltin:boolean
+	) : TPromise<IPluginDescription[]>
+	{
+		return pfs.readDirsInDir(absoluteFolderPath)
+			.then(folders => TPromise.join(folders.map(f => this.scanPlugin(version, collector, paths.join(absoluteFolderPath, f), isBuiltin))))
+			.then(plugins => plugins.filter(item => item !== null))
+			.then(plugins => {
+				const pluginsById = values(groupBy(plugins, p => p.id));
+				return pluginsById.map(p => p.sort((a, b) => semver.rcompare(a.version, b.version))[0]);
```
Comment (alexandrudima) [inline src/vs/workbench/node/extensionPoints.ts]: `semver.rcompare(a.version, b.version)` throws if `a.version` or `b.version` are undefined.

Effectively, this change makes `version` a required field in `package.json`. If this is the intent, then the validation of `package.json` must reflect this. If the version field is required, then `pluginsRegistry.ts` > `isValidPluginDescription` must be updated to check the field exists and **is parsable by semver**.

The following `package.json` breaks all extension loading:
```
{
	"name": "test",
	"publisher": "alex",
	"engines": {
		"vscode": "0.10.x"
	}
}
```

Just place it twice in the extensions folder with two different folder names to repro.

**Comment by joaomoreno** [comment]
@alexandrudima check latest commit

**Comment by alexandrudima** [comment]
@joaomoreno 

:+1:  LGTM
