### PR TITLE
Task terminals with a failed `process` task aren't always reused properly

### LINKED ISSUE #141728: Task terminals with a failed `process` task aren't always reused properly
When the process task's process is never started (for example, when executable doesn't exist), that terminal won't be reused correctly. Full context at https://github.com/microsoft/vscode/issues/138104#issuecomment-1023405620

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #141728

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 1]
```diff
@@ -1412,7 +1412,7 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 		}
 
 		// First onExit to consumers, this can happen after the terminal has already been disposed.
-		this._onExit.fire(this._exitCode);
+		this._onExit.fire(parsedExitResult);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1415]: The introduction of `null` seems pretty confusing, could this instead fire `exitCodeOrError` which would let you check `message` directly? If `exitCodeOrError` is an `ITerminalLaunchError` then the terminal failed before the process launched which is the case you're after.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts (hunk 1 above)
Comment (alexr00) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1415]: The `message` is localized, so I'm not sure what I should check for there. 

Checking if `exitCodeOrError` is an `ITerminalLaunchError` will work though. I didn't realize it would only be an `ITerminalLaunchError` when the terminal failed before the process launched.

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1415]: `parsedExitResult` is localized for the notification, `exitCodeOrError.message` isn't though.

**Review by Tyriar — APPROVED** [review]
Looks good!

**Comment by alexr00** [comment]
Thanks for reviewing!
