### PR TITLE
fix: fallback to strings for non-executable libc.so.6

### LINKED ISSUE #202580: WSL Server unable to start if 'libc.so.6' is not executable
Type: <b>Bug</b>

Issue presumably introduced with PR https://github.com/microsoft/vscode/pull/202210

Reproduce by connecting to WSL in VS Code Insiders.

VS Code version: Code - Insiders 1.86.0-insider (2c8f29174a63b3ace3d00ad0028cdc7ed9853b8b, 2024-01-16T05:35:26.709Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Connection to 'WSL: Ubuntu-Preview' could not be established  VS Code Server for WSL closed unexpectedly.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.43GB free)|
|Process Argv|--disable-extensions --file-uri=vscode-remote://wsl+Ubuntu-Preview/home/khr/.vscode-server-insiders/bin/2c8f29174a63b3ace3d00ad0028cdc7ed9853b8b/bin/helpers/check-requirements.sh --remote=wsl+Ubuntu-Preview|
|Screen Reader|no|
|VM|0%|

Connection to 'WSL: Ubuntu-Preview' could not be established  VS Code Server for WSL closed unexpectedly.
</details>Extensions disabled

### PR DESCRIPTION
**Pull request by khreenberg**
This PR adds a fallback to `strings` on hosts where `libc.so.6` is not executable. I don't know if using `strings` is a robust solution, but it resolves the issue for me on WSL distro `Ubuntu-Preview`.

Fixes #202580

### CODE REVIEW

**Comment by xangma** [comment]
Just to confirm, this is also happening on Ubuntu 22 and 23. Strings does seem to get the right info though :-)

File: resources/server/bin/helpers/check-requirements-linux.sh [hunk 1]
```diff
@@ -81,7 +81,13 @@ if [ -n "$(ldd --version | grep -v musl)" ]; then
 		# Rather than trusting the output of ldd --version (which is not always accurate)
 		# we instead use the version of the cached libc.so.6 file itself.
         libc_real_path=$(readlink -f "$libc_path")
-        libc_version=$($libc_real_path --version | sed -n 's/.*stable release version \([0-9]\+\.[0-9]\+\).*/\1/p')
+        if [ -x "$libc_real_path" ]; then
+            # get version from executable
+            libc_version=$($libc_real_path --version | sed -n 's/.*stable release version \([0-9]\+\.[0-9]\+\).*/\1/p')
+        else
+            # .so is not executable on this host; try getting from strings
+            libc_version=$(strings "$libc_real_path" | sed -n 's/.*stable release version \([0-9]\+\.[0-9]\+\).*/\1/p')
```
Comment (deepak1556) [inline resources/server/bin/helpers/check-requirements-linux.sh:89]: strings might not be available by default in most scenarios

```suggestion
            libc_version=$(cat "$libc_real_path" | sed -n 's/.*stable release version \([0-9]\+\.[0-9]\+\).*/\1/p')
```

**Review by deepak1556 — COMMENTED** [review]
Thanks for catching this issue, left a minor change.

**Review by deepak1556 — APPROVED** [review]

**Review by chrmarti — APPROVED** [review]
