### PR TITLE
Semantic tokens help for 1.43.1

### LINKED ISSUE #92740: Semantic highlighting improvements for 1.43.1
As mentioned in https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#semantic-highlighting, the goal is to improve the first impression of semantic highlighting as well allow themes to opt-in to semantic highlighting.

- give themes a way to opt-in to semantic highlighting
- enable semantic coloring by default only the built-in themes. All other themes can be enabled by the theme author or in the user settings.
- show a notification when semantic coloring shows up the first time. The notification will point to the docs with background and information on how to configure the feature.
- fix the bugs found related to wrong token classification and color lookup.
- no longer show semantic color in imports

### PR DESCRIPTION
**Pull request by aeschli**
Show a notification when semantic tokens are shown the first tome with a link to more information.
For #92740

The forward link points to https://code.visualstudio.com/docs/getstarted/themes#_semantic-highlighting which still needs to be published

### CODE REVIEW

File: src/vs/editor/common/model/textModel.ts [hunk 1]
```diff
@@ -1790,6 +1793,7 @@ export class TextModel extends Disposable implements model.ITextModel {
 
 		this._emitModelTokensChangedEvent({
 			tokenizationSupportChanged: false,
+			semanticTokensApplied: true,
```
Comment (alexdima) [inline src/vs/editor/common/model/textModel.ts]: This is a bit too eager to set `semanticTokensApplied: true`. I would suggest to leave this to false to avoid a false positive, where some piece of code calls `clearSemanticTokens` even if real semantic tokens were never set.

File: src/vs/workbench/contrib/codeEditor/browser/semanticTokensHelp.ts [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+
+				const message = nls.localize(
+					{
+						key: 'semanticTokensHelp',
+						comment: [
+							'Variable 0 will be a file name.',
+							'Variable 1 will be a theme name.'
+						]
+					},
+					"Semantic highlighting has been applied on top of the syntax highlighting of {0} as current the theme ({1}) has semantic highlighting enabled.",
```
Comment (alexdima) [inline src/vs/workbench/contrib/codeEditor/browser/semanticTokensHelp.ts]: This message might need more tweaks, it seems a bit off: "as current the theme"

**Review by alexdima — APPROVED** [review]
LGTM overall.

I left a couple of comments with some specific feedback.

One thing is not immediately clear to me. How annoying is this popup? Does it show all the time?

File: src/vs/editor/common/model/textModel.ts (hunk 1 above)
Comment (aeschli) [reply src/vs/editor/common/model/textModel.ts]: oh, right, actually I wanted to set this false, and only set semanticTokensApplied to true when there are actual tokens to set

**Review by aeschli — COMMENTED** [review]
Will change the message to `Semantic highlighting has been applied to '{0}' as the theme '{1}' has semantic highlighting enabled`

**Comment by aeschli** [comment]
The notification only shows up once per window for the very first editor when semantic tokens are applied. 
Unless `Don't show again` is pressed, the notification shows again after a window reload, or a new windows opened.
The notification stays open a while and disappears (part of the notification service). IMO it's better to show it for every new window again, so users get a chance to see it.
