### PR TITLE
Make _activeTasks synchronous wrt _executeTask

### LINKED ISSUE #180578: There is a race starting dependent tasks
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.3
- OS Version: MacOS 13.3.1

Steps to Reproduce:

Run the following shell commands to create a project with a suitable set of dependent tasks

```shell
mkdir -p test/.vscode
cd test
cat <<"EOF" > .vscode/tasks.json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "shell",
      "command": "sleep 2",
      "label": "sleeper",
      "problemMatcher": [],
      "presentation": {
        "reveal": "always",
        "group": "sleepers",
        "close": false
      }
    },
    {
      "type": "shell",
      "command": "echo task1",
      "dependsOn": ["sleeper"],
      "label": "task1",
      "problemMatcher": [],
      "presentation": {
        "reveal": "always",
        "group": "sleepers",
        "close": false
      }
    },
    {
      "type": "shell",
      "command": "echo task2",
      "dependsOn": ["task1"],
      "label": "task2",
      "problemMatcher": [],
      "presentation": {
        "reveal": "always",
        "group": "sleepers",
        "close": false
      }
    },
    {
      "type": "shell",
      "command": "echo task3",
      "dependsOn": ["task1"],
      "label": "task3",
      "problemMatcher": [],
      "presentation": {
        "reveal": "always",
        "group": "sleepers",
        "close": false
      }
    },
    {
      "type": "shell",
      "command": "echo task4... && sleep 3 && echo ...done",
      "dependsOn": ["task2", "task3"],
      "label": "task4",
      "problemMatcher": [],
      "presentation": {
        "reveal": "always",
        "group": "sleepers",
        "close": false
      },
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
EOF
code .
```

The pattern here is that task4 depends on task3 and task2, task3 and task2 each depend on task1, and task1 depends on sleeper.

Running task4 should launch one copy of sleeper, then one instance of task1, then one instance each of task2 and task3 (in parallel) and finally task4.

Instead it runs sleeper, task1 then task2, then reports there's a dependency cycle involving task1 and stops (the message appears in the output pane, rather than the debug console).

The issue is similar to the one in #180541. task2 launches task1 via `_executeDependentTask` which calls `_executeTask`, which returns before adding task1 to _activeTasks because that can't happen until `sleeper` finishes. Then task3 thinks that task1 isn't running yet (because it's not in _activeTasks) and tries to launch it again; and now it sees the false dependency cycle. What we want is for task3 to attach to the already launched task1.

### PR DESCRIPTION
**Pull request by markw65**
Fixes #180578

The problem was that after a call to _executeTask there is a delay (at least until the next tick, but potentially considerably longer) before the task is added to _activeTasks. During this period a second instance of the task could be kicked off, causing problems.

This commit fixes the issue by adding an entry (without a terminal) to _activeTasks before returning from _executeTask. For the most part though, it preserves the existing behavior - so for example `getActiveTasks` only returns the tasks that have terminals attached, just as it did before; and there is no change to when `TaskEvent` events are fired for the task.

### CODE REVIEW

**Comment by markw65** [comment]
This still isn't right. This version once again reports false dependency cycles. I'm working on a fix.

**Comment by markw65** [comment]
Sorry for the churn. This version fixes both issues:
- it won't report false dependencies when multiple tasks depend on a single subtask (A depends on B and C, and B and C each depend on D)
-  it will report actual cycles (A depends on B depends on A).

**Comment by meganrogge** [comment]
Thanks so much for looking into this. We have endgame this week, so i'll test your PRs after that.

**Comment by markw65** [comment]
I just added a commit that fixes #180850 - but I can't see a way to link this pull request to that issue...

**Comment by meganrogge** [comment]
This works well, thank you!

**Review by meganrogge — DISMISSED** [review]

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 1]
```diff
@@ -526,76 +523,90 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
...
+		const promise = Promise.resolve().then(async () => {
+			alreadyResolved = alreadyResolved ?? new Map<string, string>();
+			const promises: Promise<ITaskSummary>[] = [];
+			if (task.configurationProperties.dependsOn) {
+				liveDependencies = new Set(liveDependencies).add(task.getCommonTaskId());
+				for (const dependency of task.configurationProperties.dependsOn) {
+					const dependencyTask = await resolver.resolve(dependency.uri, dependency.task!);
+					if (dependencyTask) {
+						this._adoptConfigurationForDependencyTask(dependencyTask, task);
+						let promise;
```
Comment (alexr00) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:543]: `promise` is redeclared here (also declared on line 534). It might be clearer to use another variable name.

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 2]
```diff
@@ -526,76 +523,90 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
...
-						dependency.uri.toString()
-					));
-					this._showOutput();
 				}
 			}
-		}
 
-		if ((ContributedTask.is(task) || CustomTask.is(task)) && (task.command)) {
-			return Promise.all(promises).then((summaries): Promise<ITaskSummary> | ITaskSummary => {
-				encounteredDependencies.delete(task.getCommonTaskId());
```
Comment (alexr00) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:575]: Where are task IDs removed from `liveDependencies` now?

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 3]
```diff
@@ -600,6 +600,9 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
 				});
 			}
 		}).finally(() => {
+			const commonKey = task.getCommonTaskId();
+			liveDependencies.delete(commonKey);
```
Comment (markw65) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:604]: This isn't needed. The stack of live dependencies is maintained by cloning the set. I don't think it breaks anything, but it unnecessarily extends the lifetime of the set, preventing it from being garbage collected earlier.

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 4]
```diff
@@ -600,6 +600,9 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
...
+			encounteredTasks.delete(commonKey);
```
Comment (markw65) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:605]: This is wrong. 

The whole point of encounteredTasks is that its all tasks that have been started to date, including those that have finished.

**Review by markw65 — COMMENTED** [review]
This change breaks 180850. I'm not allowed to request changes apparently...

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts (hunk 2 above)
Comment (markw65) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:575]: I already commented on the "fix", but to clarify, they don't need to be removed, because the passed in set is never modified. The passed in set is cloned, and the new entry is added to the clone, and the clone is passed down to the dependent tasks. Once the dependent tasks have all been launched, the clone is dead, and will be garbage collected.

Note that due to the asynchronous nature of this, there's no way to maintain a single set that detects cycles in the directed graph (which are errors), while not falsely identifying cycles in the undirected graph (which are fine - eg A depends on B, C which each depend on D).

**Comment by markw65** [comment]
@meganrogge you marked this as fixing #180243 - but it doesn't (it doesn't even address it). It does fix #180850 though.

**Comment by meganrogge** [comment]
@markw65 it does fix that with this change

https://github.com/microsoft/vscode/pull/180617/files#diff-f77e08d48fa5a43f6cd385c0bac2c04ee2123565ead5f0f4b60e23c8af821b76R329-R335

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 5]
```diff
@@ -600,9 +600,7 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
 				});
 			}
 		}).finally(() => {
-			const commonKey = task.getCommonTaskId();
-			liveDependencies.delete(commonKey);
-			encounteredTasks.delete(commonKey);
+			liveDependencies.delete(task.getCommonTaskId());
```
Comment (markw65) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:603]: This still seems wrong. liveDependencies is (long) dead here; and its lifetime is being artificially extended, *just* to delete an entry from it. It also confuses the code; anyone reading this in future will assume the delete is there for a reason.

Maybe a better fix would be to introduce a new variable holding the modified dependencies... I can put up a diff...

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 6]
```diff
@@ -326,6 +326,13 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
 		});
 		this._lifecycleService.onBeforeShutdown(e => {
 			this._willRestart = e.reason !== ShutdownReason.RELOAD;
+			this.getActiveTasks().then(async (tasks) => {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:329]: Can you use an async callback in onBeforeShutdown instead to avoid `then`?

```ts
this._lifecycleService.onBeforeShutdown(async e => {
```

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 7]
```diff
@@ -326,6 +326,13 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
...
+				for (const task of tasks) {
+					if (!task.configurationProperties.isBackground) {
+						await this.terminate(task);
+					}
+				}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:334]: Shutdown time is very tight, you'd be better off doing these all at once via `Promise.all` instead of in sequence

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 8]
```diff
@@ -496,28 +491,30 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
 
 	public terminateAll(): Promise<ITaskTerminateResponse[]> {
 		const promises: Promise<ITaskTerminateResponse>[] = [];
-		Object.keys(this._activeTasks).forEach((key) => {
-			const terminalData = this._activeTasks[key];
+		Object.entries(this._activeTasks).forEach(([key, terminalData]) => {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:494]: Preferred:

```ts
for (const [key, terminalData] of Object.entries(this._activeTasks)
```

**Review by Tyriar — COMMENTED** [review]
@meganrogge I'm not totally clear what's going on in this change, shall we talk through it tomorrow?

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 9]
```diff
@@ -324,15 +324,10 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
...
 			this._willRestart = e.reason !== ShutdownReason.RELOAD;
-			this.getActiveTasks().then(async (tasks) => {
-				for (const task of tasks) {
-					if (!task.configurationProperties.isBackground) {
-						await this.terminate(task);
-					}
-				}
-			});
+			const tasks = (await this.getActiveTasks()).filter(t => t.configurationProperties.isBackground);
+			await Promise.all(tasks.map(t => this.terminate(t)));
```
Comment (markw65) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:330]: Just for my education...

I get why you don't want to `await this.terminate(task)` each time through the loop. But what's the point of the `await Promise.all` in this case? Nothing (as far as I can see) is going to await the result of the callback, so why not just

```
  const tasks = (await this.getActiveTasks()).filter(t => t.configurationProperties.isBackground);
  for (const task of tasks) {
    this.terminate(task);
  }
``` 
If I'm wrong, and something *is* going to await it, why not `return Promise.all(...)` rather than `await Promise.all(...)`

**Review by meganrogge — APPROVED** [review]

**Review by alexr00 — APPROVED** [review]

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 10]
```diff
@@ -294,7 +294,7 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
 		}
 		const lastTaskInstance = this.getLastInstance(task);
 		const terminalData = lastTaskInstance ? this._activeTasks[lastTaskInstance.getMapKey()] : undefined;
-		if (terminalData && terminalData.promise && !validInstance) {
+		if (terminalData && terminalData.promise && !validInstance && !task.configurationProperties.dependsOn?.length) {
```
[the remark this answers is not in the document]
Comment (markw65) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:297]: Well, it does. Try this with a current build:
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "shell",
      "command": "echo dependent",
      "label": "dependent",
      "problemMatcher": []
    },
    {
      "type": "shell",
      "command": "echo Running top level task...;sleep 5;echo done",
      "label": "toplevel",
      "dependsOn": ["dependent"],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "problemMatcher": []
    }
  ]
}
```

Now hit Cmd-Shift-B a few times; each one will start a new task, rather than telling you the task is already running. It was already somewhat broken (#180546) before this commit; but without this specific change, this commit would have fixed #180546. Now its completely broken it...

[the remark this answers is not in the document]
Comment (markw65) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:297]: Also, sorry, I didn't get notified about your response until this morning for some reason...

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts (hunk 3 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts]: Run `start demo`. Kill the `watch` task. Run `start demo`. Without this change, and with the changes from this PR, it doesn't restart `watch`

```
{
  "version": "2.0.0",
  "presentation": {
    "echo": false,
    "reveal": "always",
    "focus": false,
    "panel": "dedicated",
    "showReuseMessage": true
  },
  "tasks": [
    {
      "type": "npm",
      "script": "test",
      "group":{
        "kind": "test",
        "isDefault": true
      },
      "problemMatcher": []
    },
    {
      "label": "watch",
      "type": "npm",
      "script": "watch",
      "group": "build",
      "isBackground": true,
      "problemMatcher": "$tsc-watch",
      "presentation": {
        "group": "vscode"
      }
    },
    {
      "label": "start",
      "type": "npm",
      "script": "start",
      "group": "build",
      "isBackground": true,
      "problemMatcher": [],
      "presentation": {
        "group": "vscode"
      }
    },
    {
      "label": "Start demo",
      "dependsOn": ["start", "watch"],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "isBackground": true,
      "problemMatcher": {
        "owner": "typescript",
        "fileLocation": [
          "relative",
          "${workspaceFolder}"
        ],
        "pattern": [
          {
            "regexp": "^([^\\\\s].*)\\\\((\\\\d+,\\\\d+)\\\\):\\\\s*(.*)$",
            "file": 1,
            "location": 2,
            "message": 3
          }
        ],
        "background": {
          "beginsPattern": "assets by",
          "endsPattern": "webpack \\d+\\.\\d+\\.\\d+ compiled successfully"
        }
      },
      "presentation": {
        "group": "vscode"
      }
    }
  ]
}

```

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts (hunk 10 above)
[the remark this answers is not in the document]
Comment (markw65) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:297]: @meganrogge Are you sure its *in* the insiders you're testing with? In order to get that popup, `run` has to return `{ kind: TaskExecuteKind.Active, ... }`, and after the change above, it can only do that if the task has no dependents. Tasks with dependents simply ignore their instanceLimit.

If I checkout d980921bf1 (main after this was merged), and build, the problem above repros. If I remove the ` && !task.configurationProperties.dependsOn?.length` the problem goes away; and if I checkout main as of now, the problem has been fixed by #180546.

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts (hunk 3 above)
Comment (markw65) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts]: I've tried that on main as of a few minutes ago, and it seems to work perfectly, without either the `configurationProperties.dependsOn?.length` check (removed by #180546), or the `liveDependencies.delete` which was removed in 3b80fb233 as part of this pull request.

But I've also tried checking out 3b80fb233^, and getting rid of the `configurationProperties.dependsOn?.length`, and then I *am* able to repro - and that makes no sense to me. The `liveDependencies.delete` doesn't affect the result; it's broken without the `configurationProperties.dependsOn?.length` change, and fixed with it, whether or not we do the `liveDependencies.delete` (which makes sense to me, because liveDependencies is 100% dead at the point you added the delete; nothing will ever read it again).

But I'm going to keep debugging it, because I don't understand either why there was a problem then, or why there isn't a problem now...

Comment (meganrogge) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts]: Yes I agree now I understand why `liveDependencies.delete` is not needed. 

When I tested your most recently merged PR in oss, I wasn't seeing the bug where deleting a dependency task and re running the overarching one was not restarting the terminated child. 

I think that was needed because before your change (which checks if a task is running regardless of whether or not `instancePolicy` is set), we were just disallowing that from getting run again 🤷🏼‍♀️

Comment (markw65) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts]: Ok - I see what happened. 

Tasks satisfying `_isEmptyTask` (such as `Start demo` in your example) never get added to `_instances`. But prior to #180546 a task without an entry in `_instances` would end up with `validInstance` false. That seems wrong, but prior to #180617 it was ok, because such tasks would never get an entry in `_activeTasks` either, and without an `_activeTasks` entry,  `validInstance` was completely ignored.

Then #180617 changed it so that such tasks *do* get an entry in _activeTasks (from the time that _executeTask is called, until all of their dependencies finish), so `terminalData` is non null, and `validInstance` is false, and we would prevent the task from running a second time. So that's why the bug appeared. At this point the `configurationProperties.dependsOn?.length` check did work around that issue, but also completely disabled the `instanceLimit` checks for any task with dependencies.

But then #180546 fixed it so that if there's no entry in `_instances`, `validInstance` is true (if you have no running instances, you can't possibly have hit the `instanceLimit`), and everything was fine again, without needing the `configurationProperties.dependsOn?.length` check.

So I think everything is ok now that both pull requests have been merged.

Comment (meganrogge) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts]: Thanks for investigating and yeah that all makes sense to me. agreed - based on my testing everything seems to be in a good state. Thank you for the fixes - this is not an easy code area to understand 😅 .
