### PR TITLE
Preserve files on exit (aka hot exit)

### LINKED ISSUE #101: Unsaved files should be preserved on quit (hot exit)
Mac OSX 10.10.5 Yosemite, VS Code 0.10.1

Modern apps have a convention of not losing changes when the application quits and files haven't been explicitly saved. Sublime Text is particularly nice in this regard, where newly created or unsaved files are silently preserved on quit and restored when it is launched again. This would be nice for VS Code to support as well.

**To Reproduce**
1. Make changes to a file, or create a brand new unsaved file
2. Quit VS Code

**Desired Behavior**

VS Code immediately quits with no prompt. After relaunching the changed file is restored with changes intact and an unsaved indicator.

**Actual Behavior**

VS Code prompts you to save the file or discard your changes.

### PR DESCRIPTION
**Pull request by Tyriar**
Opening this now to more easily track changes during development.

Fixes #101

**TODO**
- [x] Backup files that are modified
- [x] Add a delay to file backup to reduce amount of disk access
- [x] Discard backups when files are no longer dirty
- [x] Ensure no collisions occur with backup files
  - [x] Untitled files
  - [x] Text files
- [x] Discard backups when a window is being closed and there is another window open
- [x] Retain backups when the last window is being exited
  - [x] Ensure backups are up to date
- [x] Restore backups if available on first window launch
  - [x] Restore text files
  - [x] Restore untitled files
  - [x] Launch a second window if the backup folder is different to that requested

**Feedback Round 1**
- [x] [Clarify "workspace" name in IBackupService](https://github.com/Microsoft/vscode/pull/12400#pullrequestreview-4091575) (fixed in https://github.com/Microsoft/vscode/pull/12400/commits/1a29d14961c32633dd2bd3043c9614344279a469)
- [x] [Share `BackupService` between the main and renderer processes](https://github.com/Microsoft/vscode/pull/12400#pullrequestreview-4093389) (fixed in https://github.com/Microsoft/vscode/pull/12400/commits/c280e0cac0c81de10802af3df4a8cc50b1e1b9ca)
- [x] [Move `BackupService` to `vs/platform/backup/node/`](https://github.com/Microsoft/vscode/pull/12400#pullrequestreview-4093819) (fixed in https://github.com/Microsoft/vscode/pull/12400/commits/3387b6c1b1cf0378724497c807de4ba2bdc319df)
- [x] [Opening empty workspaces currently errors out, disable completely for empty workspaces](https://github.com/Microsoft/vscode/pull/12400#pullrequestreview-4094188) (fixed in https://github.com/Microsoft/vscode/pull/12400/commits/10aa7095f6fa6104155bf97adfd8e4ad6dc5eb28)
- [x] [Avoid sync calls where possible](https://github.com/Microsoft/vscode/pull/12400#pullrequestreview-4094309) (fixed in https://github.com/Microsoft/vscode/pull/12400/commits/2b0a65afb0a7b9856881f59bb419ac05e4cab2a5)

**Clean up**
- [x] Resolve remaining TODOs
- [x] Remove any `console.log` statements
- [x] Add some tests
- [x] Remove all empty lines at beginning of functions https://github.com/Microsoft/vscode/pull/12400#pullrequestreview-4095956
- [x] Have backup service tests use a temporary folder for backups (needed to have tests pass on Travis)

**Known issues/follow ups**
- https://github.com/Microsoft/vscode/issues/13305 Support multiple folder restore
  - Behavior on Mac is a little strange right now due to the fact that the application is kept open when all windows are closed. This will not feel natural on Mac until restoring multiple workspaces is resolved (made notes there)
- https://github.com/Microsoft/vscode/issues/13733 Support hot exit on empty workspaces
- https://github.com/Microsoft/vscode/issues/12327 Hot Exit: Restore files after an editor crashes
- https://github.com/Microsoft/vscode/issues/14038 The tab dirty indicator is up to date right after restore, the file needs to be opened before it refreshes. See call to `this.setDirty(true);` in `TextFileEditorModel.load`
- https://github.com/Microsoft/vscode/issues/14037 Merge backup path logic from `node/fileService.ts` into `backupService.ts`

### CODE REVIEW

File: src/vs/code/electron-main/backup.ts [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+
+export class BackupService implements IBackupService {
+
+	private filePath: string;
+	private fileContent: IBackupFormat;
+
+	constructor(
+		@IEnvironmentService private environmentService: IEnvironmentService
+	) {
+		this.filePath = path.join(environmentService.userDataPath, 'Backups', 'workspaces.json');
```
Comment (bpasero) [inline src/vs/code/electron-main/backup.ts]: This should be a key inside environment service and not being constructed, or?

File: src/vs/code/electron-main/backup.ts [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+	public getBackupWorkspaces(): string[] {
+		if (!this.fileContent) {
+			this.load();
+		}
+		return Object.keys(this.fileContent.folderWorkspaces || {});
+	}
+
+	public clearBackupWorkspaces(): void {
+		this.fileContent = {
+			folderWorkspaces: {}
```
Comment (bpasero) [inline src/vs/code/electron-main/backup.ts]: Just a personal preference to use `Object.create(null)` over `{}`

File: src/vs/code/electron-main/backup.ts [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+import * as path from 'path';
+import { createDecorator } from 'vs/platform/instantiation/common/instantiation';
+import { IEnvironmentService } from 'vs/platform/environment/common/environment';
+
+export const IBackupService = createDecorator<IBackupService>('backupService');
+
+export interface IBackupService {
+	getBackupWorkspaces(): string[];
+	clearBackupWorkspaces(): void;
+	pushBackupWorkspaces(workspaces: string[]): void;
```
Comment (bpasero) [inline src/vs/code/electron-main/backup.ts]: Not quite clear here what `workspaces` is about? Is this an identifier or absolute path?

File: src/vs/code/electron-main/windows.ts [hunk 4]
```diff
@@ -730,6 +745,12 @@ export class WindowsManager implements IWindowsService {
 		// Emit events
 		iPathsToOpen.forEach(iPath => this.eventEmitter.emit(EventTypes.OPEN, iPath));
 
+		// Add to backups
```
Comment (bpasero) [inline src/vs/code/electron-main/windows.ts]: Why are we adding these workspaces again to backup service?

File: src/vs/code/electron-main/backup.ts [hunk 5]
```diff
@@ -0,0 +1,88 @@
+/*---------------------------------------------------------------------------------------------
```
Comment (bpasero) [inline src/vs/code/electron-main/backup.ts]: So this guy is the one that manages all backups across all workspaces and the vs/platform/backup is the one per workspace for individual files?

File: src/vs/platform/backup/common/backup.ts [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+
+import { createDecorator } from 'vs/platform/instantiation/common/instantiation';
+import Uri from 'vs/base/common/uri';
+
+export const IBackupService = createDecorator<IBackupService>('backupService');
+
+export interface IBackupService {
+	_serviceBrand: any;
+
+	getBackupWorkspaces(): string[];
```
Comment (bpasero) [inline src/vs/platform/backup/common/backup.ts]: Now I am confused why this guy reaches into the territory of vs/electron-main/backup

File: src/vs/platform/files/common/files.ts [hunk 7]
```diff
@@ -105,6 +105,27 @@ export interface IFileService {
 	del(resource: URI, useTrash?: boolean): TPromise<void>;
 
 	/**
+	 * Backs up the provided file to a temporary directory to be used by the hot
+	 * exit feature and crash recovery.
+	 */
+	backupFile(resource: URI, content: string): TPromise<IFileStat>;
```
Comment (bpasero) [inline src/vs/platform/files/common/files.ts]: I think all of this should move into textfile.ts (ITextFileService) because in here we talk about all files but for hot exit we only care about text files.

File: src/vs/workbench/common/backup.ts [hunk 8]
```diff
@@ -0,0 +1,119 @@
+/*---------------------------------------------------------------------------------------------
```
Comment (bpasero) [inline src/vs/workbench/common/backup.ts]: If this is a service it should move into vs/workbench/services !

File: src/vs/workbench/common/backup.ts [hunk 9]
```diff
@@ -0,0 +1,119 @@
...
+
+	private workspaceResource: Uri;
+	private workspacesJsonFilePath: string;
+	private fileContent: IBackupFormat;
+
+	constructor(
+		@IEnvironmentService private environmentService: IEnvironmentService,
+		@IWorkspaceContextService contextService: IWorkspaceContextService
+	) {
+		this.workspacesJsonFilePath = path.join(environmentService.userDataPath, 'Backups', 'workspaces.json');
```
Comment (bpasero) [inline src/vs/workbench/common/backup.ts]: Again this should be defined inside IEnvironmentService and not constructed

File: src/vs/workbench/common/backup.ts [hunk 10]
```diff
@@ -0,0 +1,119 @@
...
+		this.workspaceResource = contextService.getWorkspace().resource;
+	}
+
+	public getBackupWorkspaces(): string[] {
+		this.load();
+		return Object.keys(this.fileContent.folderWorkspaces || {});
+	}
+
+	public clearBackupWorkspaces(): void {
```
Comment (bpasero) [inline src/vs/workbench/common/backup.ts]: Again confused why this guy seems to be doing the same work as the backup service on the main side, plus some additional things.

File: src/vs/workbench/parts/files/electron-browser/dirtyFilesTracker.ts [hunk 11]
```diff
@@ -66,6 +68,7 @@ export class DirtyFilesTracker implements IWorkbenchContribution {
 	}
 
 	private onUntitledDidChangeDirty(resource: URI): void {
+
```
Comment (bpasero) [inline src/vs/workbench/parts/files/electron-browser/dirtyFilesTracker.ts]: I prefer to not add empty lines in the beginning of a method, please stick to the coding format used elsewhere in the files.

File: src/vs/workbench/services/files/electron-browser/fileService.ts [hunk 12]
```diff
@@ -26,6 +26,7 @@ import { IEnvironmentService } from 'vs/platform/environment/common/environment'
 import { IEditorGroupService } from 'vs/workbench/services/group/common/groupService';
```
Comment (bpasero) [inline src/vs/workbench/services/files/electron-browser/fileService.ts]: Can these methods live in ITextFileService and implementation?

File: src/vs/code/electron-main/backup.ts (hunk 1 above)
Comment (Tyriar) [inline src/vs/code/electron-main/backup.ts]: I like it https://github.com/Microsoft/vscode/pull/12400/commits/5f230ed17cadf8122ec268bc2d953247dc988305

File: src/vs/code/electron-main/backup.ts (hunk 2 above)
Comment (Tyriar) [inline src/vs/code/electron-main/backup.ts]: Converted all instances https://github.com/Microsoft/vscode/pull/12400/commits/4fcfdc6accf84f63a5a1f2e691403d85f4b20d29

File: src/vs/code/electron-main/windows.ts [hunk 13]
```diff
@@ -602,6 +605,18 @@ export class WindowsManager implements IWindowsService {
 			iPathsToOpen = this.cliToPaths(openConfig.cli, ignoreFileNotFound);
 		}
 
+		// Add any existing backup workspaces
+		if (openConfig.restoreBackups) {
+			// TODO: Ensure the workspaces being added actually have backups
+			this.backupService.getBackupWorkspaces().forEach(ws => {
```
Comment (Tyriar) [inline src/vs/code/electron-main/windows.ts]: Provided I understand correctly, does opening the same folder twice restore backups? This should never happen as `openConfig.restoreBackups` is only ever true on the first window launch. https://github.com/Microsoft/vscode/pull/12400/files#diff-d8dfcbab1cae48b2cbc3cabc682c9cd4R258

File: src/vs/code/electron-main/windows.ts (hunk 4 above)
Comment (Tyriar) [inline src/vs/code/electron-main/windows.ts]: The intent here is for workspaces.json to contain a key for each workspace currently opened in order to support the crash recovery use case, so it's being added on the main process side when the window is launched.

This is also used [to determine whether a single window is opened](https://github.com/Microsoft/vscode/pull/12400/files#diff-56386098163653fba6a65ac4e37ea24bR123) (there is probably another way to do this) in order to decide whether the backups can be discarded safely, but that's not the main reason for it.

File: src/vs/code/electron-main/backup.ts (hunk 5 above)
Comment (Tyriar) [inline src/vs/code/electron-main/backup.ts]: `IBackupService` manages all I/O with what is now the `IEnvironmentService.backupHome` directory.

File: src/vs/platform/backup/common/backup.ts (hunk 6 above)
Comment (Tyriar) [inline src/vs/platform/backup/common/backup.ts]: As discussed, I'll merge these services as there is no reason for them not to share code.

File: src/vs/platform/files/common/files.ts (hunk 7 above)
Comment (Tyriar) [inline src/vs/platform/files/common/files.ts]: For hot exit we care about untitled files as well, I put this in `IFileService` as per your advice due to this?

File: src/vs/workbench/common/backup.ts (hunk 8 above)
Comment (Tyriar) [inline src/vs/workbench/common/backup.ts]: :+1: not sure whether service I copied but it must have been shuffled within the last 3 weeks.

File: src/vs/workbench/common/backup.ts (hunk 9 above)
Comment (Tyriar) [inline src/vs/workbench/common/backup.ts]: Done https://github.com/Microsoft/vscode/pull/12400/commits/5f230ed17cadf8122ec268bc2d953247dc988305

File: src/vs/workbench/common/backup.ts (hunk 10 above)
Comment (Tyriar) [inline src/vs/workbench/common/backup.ts]: Answered in https://github.com/Microsoft/vscode/pull/12400#pullrequestreview-4093389

File: src/vs/workbench/common/backup.ts [hunk 14]
```diff
@@ -0,0 +1,119 @@
...
+		this.save();
+	}
+
+	public getBackupFiles(workspace: string): string[] {
+		this.load();
+		return this.fileContent.folderWorkspaces[workspace] || [];
+	}
+
+	public getBackupUntitledFiles(workspace: string): string[] {
+		const workspaceHash = crypto.createHash('md5').update(this.workspaceResource.fsPath).digest('hex');
```
Comment (Tyriar) [inline src/vs/workbench/common/backup.ts]: Due to the restriction of a single window per folder, this is handled by hashing the (absolute) workspace path which is guaranteed to be unique.

File: src/vs/workbench/common/backup.ts [hunk 15]
```diff
@@ -0,0 +1,119 @@
...
+		const untitledDir = path.join(this.environmentService.userDataPath, 'Backups', workspaceHash, 'untitled');
+		try {
+			const untitledFiles = fs.readdirSync(untitledDir).map(file => path.join(untitledDir, file));
```
Comment (Tyriar) [inline src/vs/workbench/common/backup.ts]: This was one of the things I wanted to clean up, I was thinking I'd track them in workspaces.json as that would be needed for hot exit to work on empty (no dir) workspaces.

File: src/vs/workbench/parts/files/electron-browser/dirtyFilesTracker.ts [hunk 16]
```diff
@@ -37,6 +38,7 @@ export class DirtyFilesTracker implements IWorkbenchContribution {
 
 	constructor(
 		@ITextFileService private textFileService: ITextFileService,
+		@IFileService private fileService: IFileService,
```
Comment (Tyriar) [inline src/vs/workbench/parts/files/electron-browser/dirtyFilesTracker.ts]: Fixed https://github.com/Microsoft/vscode/pull/12400/commits/a822c887781cb6f3069c49c72bf97bf32d4ccf19

File: src/vs/workbench/parts/files/electron-browser/dirtyFilesTracker.ts (hunk 11 above)
Comment (Tyriar) [inline src/vs/workbench/parts/files/electron-browser/dirtyFilesTracker.ts]: Added to clean up section in main issue

File: src/vs/workbench/services/files/node/fileService.ts [hunk 17]
```diff
@@ -28,10 +28,16 @@ import pfs = require('vs/base/node/pfs');
 import encoding = require('vs/base/node/encoding');
```
Comment (Tyriar) [inline src/vs/workbench/services/files/node/fileService.ts]: Pending response in https://github.com/Microsoft/vscode/pull/12400#pullrequestreview-4093616

File: src/vs/workbench/services/files/electron-browser/fileService.ts (hunk 12 above)
Comment (Tyriar) [inline src/vs/workbench/services/files/electron-browser/fileService.ts]: Pending response in https://github.com/Microsoft/vscode/pull/12400#pullrequestreview-4093616

**Comment by Tyriar** [comment]
@bpasero I answered all your comments, bigger ones I moved to the main issue under a feedback section because based on my experience, tracking old review comments in a PR this size is a nightmare. Here are the ones requiring feedback from you:

- [Implementation in `IFileService`](https://github.com/Microsoft/vscode/pull/12400#pullrequestreview-4093616)
- [Naming](https://github.com/Microsoft/vscode/pull/12400#pullrequestreview-4091575)

I'll ping you again when I when I want you do a full review.

File: src/vs/platform/files/common/files.ts (hunk 7 above)
Comment (bpasero) [inline src/vs/platform/files/common/files.ts]: I meanwhile moved ITextFileService out of file contrib land into the workbench so there was a chance of layer breaking. But now that the service is in workbench core it is on the same level as untitled files.

File: src/vs/workbench/common/backup.ts (hunk 14 above)
Comment (bpasero) [inline src/vs/workbench/common/backup.ts]: Just fyi we might loosen this restriction in the near future to support more debug scenarios.

**Comment by bpasero** [comment]
@Tyriar good. one additional thing that comes to my mind: what about editing files in empty workspaces? there is a potential of opening the same files multiple times in multiple windows without workspace association (including untitled files). Currently we do not restore any UI state for empty workspaces so maybe for dirty files in those cases they should all be grouped into one window to open.

Still, you can have the same file dirty in multiple windows.

File: src/vs/workbench/common/backup.ts (hunk 14 above)
Comment (Tyriar) [inline src/vs/workbench/common/backup.ts]: Yeah I saw the issue, currently things would break pretty badly (a new window in the same directory would restore the files currently being edited in the other window).

Empty workspaces don't work currently, in fact I just tested and there's an exception during launch so the workbench doesn't load. Added to feedback.

File: src/vs/platform/files/common/files.ts (hunk 7 above)
Comment (Tyriar) [inline src/vs/platform/files/common/files.ts]: To clarify, so I should move the backup logic to `ITextFileService`?

**Comment by Tyriar** [comment]
@bpasero The intent was to not include empty workspaces in this PR but build upon it after (it's already big enough), you pointing it out made me realize it's a bit broken currently so that will be fixed obviously.

The basic idea here is for there to be another top-level property in workspaces.json for each empty workspace:

```js
{
  "folderWorkspaces": {
    "/vscode": [
      "/vscode/file.js"
    ]
  },
  "emptyWorkspaces": {
    // This value is generated from ~20 random bytes for each empty workspace and is
    // the name of the directorythat will store the files
    "12345678901234567890": [
      "/vscode/file.js"
    ]
  }
}
```

The structure for the above on disk would look something like:

Folder workspace:

```
<userDataDir>/Backups/<hash(/vscode)>/file/<hash(/vscode/file.js)>
<userDataDir>/Backups/<hash(/vscode)>/untitled/<random bytes> (for each dirty untitled file)
```

Empty workspace:

```
<userDataDir>/Backups/12345678901234567890/file/<hash(/vscode/file.js)>
<userDataDir>/Backups/12345678901234567890/untitled/<random bytes> (for each dirty untitled file)
```

**Comment by Tyriar** [comment]
Also, the system was designed to allow multiple workspaces to be restored at once in order to emulate Sublime's behavior. For completeness, here are the restore cases I wanted to support:

- (This PR) Hot exit when a single window of vscode is open, the next time vscode is opened this folder will be restored. If another folder is opened via command line, for example `code /some/other/dir`, then both `/some/other/dir` and the restored workspace will open.
- The above for empty workspaces.
- Quitting all vscode windows at once via File > Exit (cmd+q) will restore all the windows that had dirty files when closed.
- workspaces.json will be kept up to date at all times which will enable the multiple windows to be restored after a crash. This will probably need some special logic for checking whether a workspace exists in workspaces.json but is not currently open.

**Comment by bpasero** [comment]
Maybe we start adding a label for "hot-exit" so we can group all the related issues around it?

**Comment by Tyriar** [comment]
:+1: https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Ahot-exit%20

**Comment by Tyriar** [comment]
Merging this now as everything's checked off or has follow up tasks and the push/branch CI jobs are passing :tada:  (failing on master due to https://github.com/Microsoft/vscode/commit/9e1b35badbdf033b0bdfe85a7fc89008978c8ef8)

The main thing to call out here is that restoring is disabled on Mac until https://github.com/Microsoft/vscode/issues/13305 gets done.
