### PR TITLE
Set implicit context enablement

### LINKED ISSUE #280202: Full file is attached automatically
I keep ending up with the full file attachment enabled in the implicit context widget. I just found one reliable set of repro steps but it happens in other cases too. I just reload the window with any text file open, and after reloading, that file is attached.

Image

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #280202

### CODE REVIEW

File: src/vs/workbench/contrib/chat/browser/chatInputPart.ts [hunk 1]
```diff
@@ -1373,15 +1376,19 @@ export class ChatInputPart extends Disposable implements IHistoryNavigationWidge
 		this.chatInputTodoListWidgetContainer = elements.chatInputTodoListWidgetContainer;
 		this.chatInputWidgetsContainer = elements.chatInputWidgetsContainer;
 
-		if (this.options.enableImplicitContext) {
+		if (this.options.enableImplicitContext && !this._implicitContext) {
 			this._implicitContext = this._register(
 				this.instantiationService.createInstance(ChatImplicitContext),
 			);
+			this.setImplicitContextEnablement();
```
Comment (alexr00) [inline src/vs/workbench/contrib/chat/browser/chatInputPart.ts:1383]: This is the actual fix: set the enablement once we create the implicit context

File: src/vs/workbench/contrib/chat/browser/chatInputPart.ts [hunk 2]
```diff
@@ -1373,15 +1376,19 @@ export class ChatInputPart extends Disposable implements IHistoryNavigationWidge
...
 
 			this._register(this._implicitContext.onDidChangeValue(() => {
 				this._indexOfLastAttachedContextDeletedWithKeyboard = -1;
 				this._handleAttachedContextChange();
 			}));
+		} else {
+			this._implicitContext?.dispose();
+			this._implicitContext = undefined;
```
Comment (alexr00) [inline src/vs/workbench/contrib/chat/browser/chatInputPart.ts]: The `&& !this._implicitContext` check and this are not part of the fix, but it seems like we should be doing them.

File: src/vs/workbench/contrib/chat/browser/chatInputPart.ts [hunk 3]
```diff
@@ -547,6 +544,12 @@ export class ChatInputPart extends Disposable implements IHistoryNavigationWidge
 		this.validateCurrentChatMode();
 	}
 
+	private setImplicitContextEnablement() {
+		if (this.implicitContext && this.configurationService.getValue<boolean>('chat.implicitContext.suggestedContext')) {
+			this.implicitContext.enabled = this._currentModeObservable.get().kind !== ChatMode.Agent.kind;
```
Comment (alexr00) [inline src/vs/workbench/contrib/chat/browser/chatInputPart.ts:549]: I modified this check to compare the `.kind` as just comparing by reference was resulting in `false` for restored Agent mode chats. Do we actually want to include the whole file when not in agent mode?

**Review by alexr00 — COMMENTED** [review]
@justschen here are some notes on this change.

File: src/vs/workbench/contrib/chat/browser/chatInputPart.ts (hunk 3 above)
Comment (justschen) [reply src/vs/workbench/contrib/chat/browser/chatInputPart.ts:549]: this was a big point when we changed the implicit context a few iterations ago. it's intended that in every mode except agent mode, the full fiile should be automatically added

Comment (alexr00) [reply src/vs/workbench/contrib/chat/browser/chatInputPart.ts:549]: Ok, then I think my change is correct, as it seems like restored agent mode chats should count as agent mode. Though, maybe there's a separate problem that restored agent mode chats are not the same mode by reference as `ChatMode.Agent`?

File: src/vs/workbench/contrib/chat/browser/chatInputPart.ts [hunk 4]
```diff
@@ -1373,15 +1376,19 @@ export class ChatInputPart extends Disposable implements IHistoryNavigationWidge
...
 				this.instantiationService.createInstance(ChatImplicitContext),
 			);
+			this.setImplicitContextEnablement();
 
 			this._register(this._implicitContext.onDidChangeValue(() => {
 				this._indexOfLastAttachedContextDeletedWithKeyboard = -1;
 				this._handleAttachedContextChange();
 			}));
+		} else {
+			this._implicitContext?.dispose();
```
[the remark this answers is not in the document]
Comment (alexr00) [reply src/vs/workbench/contrib/chat/browser/chatInputPart.ts]: Oof. Good catch.

**Review by justschen — APPROVED** [review]
thanks! will test this out in the next build
