### PR TITLE
add plain text type to fix copy as html

### LINKED ISSUE #146427: Add Copy Output as HTML command action
I looked for this yesterday when I wanted to share output from a failed command 

Screen Shot 2022-03-31 at 8 03 37 AM

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #146427

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 1]
```diff
@@ -1153,6 +1153,9 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 			if (asHtml) {
 				const textAsHtml = await xterm.getSelectionAsHtml(command);
 				function listener(e: any) {
+					if (!e.clipboardData.types.includes('text/plain')) {
+						e.clipboardData.setData('text/plain', command?.getOutput());
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1157]: command?.getOutput() ?? ''
