### PR TITLE
fix anchor to focused cell

### LINKED ISSUE #194153: notebook.scrolling.anchorToFocusedCell is allowing cell to scroll off viewport
Testing #194069

Provided I understand the setting, the focused cell shouldn't be able to scroll off the page without user input as I've said to anchor the focused cell:

Image

I was expecting as the setting said, for the selected cell to remain steady and not move at all, while the content above changed and the scroll position was adjusted each time.

### PR DESCRIPTION
**Pull request by amunger**
fix https://github.com/microsoft/vscode/issues/194153

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/browser/view/notebookCellList.ts [hunk 1]
```diff
@@ -1205,10 +1205,6 @@ export class NotebookCellList extends WorkbenchList<CellViewModel> implements ID
 		const focused = this.getFocus();
 		const focus = focused.length ? focused[0] : null;
 
-		if (this.view.elementTop(index) >= this.view.getScrollTop()) {
```
Comment (amunger) [inline src/vs/workbench/contrib/notebook/browser/view/notebookCellList.ts:1208]: this check is part of the `scrollHeuristic` below should not determine alone where to anchor

**Review by rebornix — APPROVED** [review]
