### PR TITLE
fix sticky scroll start line number

### LINKED ISSUE #157180: Stick Scroll sticks python function's decorator line instead of the declaration line
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.70.0
- OS Version: Windows 11

Steps to Reproduce:

1. Enable sticky scroll
2. Scroll through a python function with decorator

The function:
image

When the view is scrolled, sticky line should show the definition instead of the decorator. This is what it's like currently:
image

### LINKED ISSUE #157293: New Sticky Scroll doesn't work properly
Type: <b>Bug</b>

When using the new Sticky Scroll with a .NET API project, scrolling in a controller will only show any attributes as the "sticky" heading - [ApiController] - [HttpPost], etc. 

image

image

VS Code version: Code - Insiders 1.71.0-insider (73fd3f11032e7b83c2ae011b5516e6ddd19e3db2, 2022-08-05T07:36:58.753Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (16.52GB free)|
|Process Argv|--crash-reporter-id 362817d9-b661-4b35-92b7-fe18e5872851|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
TabOut|alb|0.2.1
ng-template|Ang|14.1.0
sync-scroll|dqi|1.3.0
vs-code-xml-format|fab|0.1.5
csharpextensions|kre|1.7.0
git-graph|mhu|1.30.0
vscode-azurefunctions|ms-|1.7.4
vscode-azureresourcegroups|ms-|0.5.5
vscode-azurestorage|ms-|0.14.2
csharp|ms-|1.25.0
azure-account|ms-|0.11.1
hexeditor|ms-|1.9.8
material-icon-theme|PKi|4.19.0
quicktype|qui|12.0.46
vscode-thunder-client|ran|1.17.1
hl7tools|Rob|1.14.2
msbuild-project-tools|tin|0.4.4
vscodeintellicode|Vis|1.2.22
jwt-debugger|yok|0.4.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252

```

</details>

### LINKED ISSUE #157375: Sticky Scroll: In C#, namespace, struct, property should stick, attributes shouldn't stick
Does this issue occur when all extensions are disabled?: Almost yes (you need C# extension to make sticky scroll work, and issue happens when only C# extension is enabled)

- VS Code Version: 1.70.0 (system setup), commit: da76f93349a72022ca4670c1b84860304616aaa2
- OS Version: Windows 11 21H2 (22000.832)

### Code:
code

### Actual:
actual

Namespace, property doesn't appear, and attributes appear instead of actual class.

### Expected:
expected

Namespace, property, and actual class should appear.

### Code:
code2

### Actual:
actual2

When you scroll down, Struct doesn't appear.

### Expected:
expected2

Struct should appear.

### LINKED ISSUE #157380: Sticky Scroll: Doesn't support Vue components.
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.70
- OS Version: windows 11

Steps to Reproduce:

1. install latest VS code version: `1.70`
2.  enable sticky scroll
3. open a vue file 

**Expected Result**
Sticky should work well.

**Actual Result**

`template` remains sticky in the whole file
image

### LINKED ISSUE #157680: Sticky scrolling is broken on multiline function declarations in C
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open a C file
2. Create a function declaration and definition that spans 2 lines like so

```c
static void
func(void)
{
  // ...
}
```

When you scroll through `func`, the sticky scrolling will use `static void` instead of `func`.

image

### PR DESCRIPTION
**Pull request by DingWeizhe**
Fixes https://github.com/microsoft/vscode/issues/157680
Fixes https://github.com/microsoft/vscode/issues/157180
Fixes https://github.com/microsoft/vscode/issues/157293
Fixes https://github.com/microsoft/vscode/issues/157380
Fixes https://github.com/microsoft/vscode/issues/157375

---

fix https://github.com/microsoft/vscode/issues/157375

when class or method have decorator(TypeScript) or attribute(C#), 
range.startLineNumber is begin of decorator, but selectionRange.startLineNumber is start of method.

image

### CODE REVIEW

File: src/vs/editor/contrib/stickyScroll/browser/stickyScroll.ts [hunk 1]
```diff
@@ -139,7 +139,7 @@ class StickyScrollController extends Disposable implements IEditorContribution {
 		while (outlineElement) {
 			const kind: SymbolKind = outlineElement.symbol.kind;
 			if (kind === SymbolKind.Class || kind === SymbolKind.Constructor || kind === SymbolKind.Function || kind === SymbolKind.Interface || kind === SymbolKind.Method || kind === SymbolKind.Module) {
-				currentStartLine = outlineElement?.symbol.range.startLineNumber as number;
+				currentStartLine = outlineElement?.symbol.selectionRange.startLineNumber as number;
 				currentEndLine = outlineElement?.symbol.range.endLineNumber as number;
```
Comment (gjsjohnmurray) [inline src/vs/editor/contrib/stickyScroll/browser/stickyScroll.ts:143]: Perhaps the equivalent should also be done on the next line.

Comment (DingWeizhe) [reply src/vs/editor/contrib/stickyScroll/browser/stickyScroll.ts:143]: Thanks for your feedback
But actually selectionRange doesn't include the whole block, only the block name.

image

so it should sticky scroll from selectionRange.startLineNumber to range.endLineNumber

Comment (gjsjohnmurray) [reply src/vs/editor/contrib/stickyScroll/browser/stickyScroll.ts:143]: Thanks for the explanation.

**Comment by DingWeizhe** [comment]
https://github.com/microsoft/vscode/pull/157483 be merged with lots of changes so I rebase the PR

**Comment by aiday-mar** [comment]
@DingWeizhe Thank you for your contribution, it will be incorporated into the existing code base

**Review by alexdima — APPROVED** [review]
