### PR TITLE
Adjust command started X when prompt is reprinted

### LINKED ISSUE #241353: Zsh prompt input model not working until I ctrl+c or run a command
I think this is vanilla oh-my-zsh

Image

Image

.zshrc contents:

```sh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh
```

Could be related to https://github.com/microsoft/vscode-copilot-release/issues/4814

### PR DESCRIPTION
**Pull request by Tyriar**
This handles properly when plugins are loaded after the initial print in zsh.

fixes #241353

---

Same zsh session that was broken now working immediately:

Screenshot 2025-02-21 at 6 34 26 am

### CODE REVIEW

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 1]
```diff
@@ -330,6 +332,7 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
 		this._currentCommand.commandStartMarker = options?.marker || this._currentCommand.commandStartMarker;
 		if (this._currentCommand.commandStartMarker?.line === this._terminal.buffer.active.cursorY) {
 			this._currentCommand.commandStartX = this._terminal.buffer.active.cursorX;
+			this._onCommandStartChanged.fire(this._currentCommand as any as ITerminalCommand);
```
Comment (meganrogge) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:335]: should we just change the type of event to be `| ICurrentPartialCommand` to avoid this cast and to make it clearer?

**Review by meganrogge — APPROVED** [review]
Nice

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts (hunk 1 above)
Comment (Tyriar) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:335]: https://github.com/microsoft/vscode/pull/241493
