### PR TITLE
Git: Fixed error when staging in empty repository

### LINKED ISSUE #82026: Git: Errors when staging changes in new repository
- VSCode Version: 1.38.1
- OS Version: Windows 10 v1903

Steps to Reproduce:

1. Add a folder in workspace
2. Init a git repository in this folder
3. Create a new file in this folder
4. Stage change from the source control providers (scp) panel
5. Append/change content in the file
6. Stage change by using the blue icon in the left gutter (not from scp panel)

An error (OS) window pops up with the message "Git fatal: Not a valid object name HEAD".

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by anirudhrb**
Trying to stage a commit in an empty repository (i.e. no prior commits)
results in a git fatal error. This is because in an empty repo, HEAD
doesn't point to anything causing `git ls-tree -l HEAD ...` to fail.

To fix this, send `treeish` as `'HEAD'` to `getObjectDetails()` only if
there is at least one commit in the repo. Else, send an empty string
causing `getObjectDetails()` to use `lsFiles` instead of `lsTree`.

Fixes #82026.

### CODE REVIEW

File: extensions/git/src/git.ts [hunk 1]
```diff
@@ -1164,9 +1167,15 @@ export class Repository {
...
+		let treeish: string = '';
+		const commits = await this.log({ maxEntries: 1 });
+
+		if (commits.length > 0) {
+			treeish = 'HEAD';
+		}
 
 		try {
-			const details = await this.getObjectDetails('HEAD', path);
+			const details = await this.getObjectDetails(treeish, path);
```
Comment (Fleta) [inline extensions/git/src/git.ts]: `getObjectDetails` runs` lstree`, which runs `git ls-tree -l $ {treeish} -- ${path}`. I think it causes fatal error (not a valid object name) if `treeish` is empty. The try-catch block that surrounds `getObjectDetails` does not seem to handle errors except for `GitErrorCodes.UnknownPath`. Is it okay?

**Review by Fleta — CHANGES_REQUESTED** [review]

File: extensions/git/src/git.ts (hunk 1 above)
Comment (anirudhrb) [reply extensions/git/src/git.ts]: `getObjectDetails` doesn't run `ls-tree` if `treeish` is empty. It runs `git ls-files --stage ...` instead. Which is what I intend in this PR because `ls-tree -l HEAD ...` will fail in an empty repo.

https://github.com/microsoft/vscode/blob/c58aaab8a1cc22a7139b761166a0d4f37d41e998/extensions/git/src/git.ts#L835-L858

Comment (Fleta) [reply extensions/git/src/git.ts]: I was mistaken. Thanks for your kind feedback.

**Review by Fleta — APPROVED** [review]

**Comment by anirudhrb** [comment]
@joaomoreno ping!

**Comment by joaomoreno** [comment]
@anirudhrb pong!

**Comment by joaomoreno** [comment]
Thanks! :fireworks: 

Ended up running `getCommit` instead of `log`, found that to be more specific.
