### PR TITLE
fix: don't reshow remote source picker after it's been cancelled

### LINKED ISSUE #173941: Cancelling a remote source picker while it's searching doesn't work
1. Run `Git: Clone`
2. Choose `Clone from GitHub`
3. Type a search term
4. Immediately close quick pick with <kbd>Escape</kbd>

🐛 Search results appear eventually.

Recording 2023-02-09 at 14 17 44

### PR DESCRIPTION
**Pull request by joyceerhl**
Fixes https://github.com/microsoft/vscode/issues/173941

### CODE REVIEW

File: extensions/git-base/src/remoteSource.ts [hunk 1]
```diff
@@ -70,12 +89,17 @@ class RemoteSourceProviderQuickPick {
...
+			}
 		}
 	}
 
 	async pick(): Promise<RemoteSource | undefined> {
 		await this.query();
+		if (this.isDisposed) {
+			return;
+		}
 		const result = await getQuickPickResult(this.quickpick!);
```
Comment (TylerLeonhardt) [inline extensions/git-base/src/remoteSource.ts:103]: this function has a few events that aren't getting disposed.

**Review by TylerLeonhardt — DISMISSED** [review]

File: extensions/git-base/src/remoteSource.ts (hunk 1 above)
Comment (joyceerhl) [reply extensions/git-base/src/remoteSource.ts:107]: Good find, thanks!

**Review by TylerLeonhardt — APPROVED** [review]
