### PR TITLE
fix escaping for terminal completions for zsh/bash/fish

### LINKED ISSUE #249024: terminal completions don't escape properly
Type: <b>Bug</b>

I am working in a astro.js project and so I have files that are named `[...slug].astro` and similar. When I type `git add ` or if I type e.g. `cat src/pages/` I get completion sugestions that are correct and helpful, but if I pick `[...slug].astro` it inserts `git add src/pages/[...slug].astro` which when run complains that the file does't exist. What it should do is to insert `git add src/pages/\[...slug\].astro` which works.

VS Code version: Code 1.100.1 (Universal) (91fa95bccb027ece6a968589bb1d662fa9c8e170, 2025-05-09T15:43:50.040Z)
OS version: Darwin x64 24.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id eebde5f3-c7c2-4a64-9133-86a72e21deb5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
astro-vscode|ast|2.15.4
spellright|ban|3.0.142
vscode-intelephense-client|bme|1.14.4
vscode-tailwindcss|bra|0.14.16
solargraph|cas|0.25.0
vscode-css-modules|cli|0.5.4
vscode-eslint|dba|3.0.10
vscode-deno|den|3.44.2
xml|Dot|2.5.1
copilot|Git|1.317.0
copilot-chat|Git|0.27.0
html-tag-wrapper|hwe|0.2.3
color-picker-universal|Jer|2.6.8
deno-std-lib-snippets|lau|0.0.8
remote-ssh|ms-|0.120.0
remote-ssh-edit|ms-|0.87.0
remote-explorer|ms-|0.5.0
html-fmt-vscode|Nik|0.9.3
partial-diff|ryu|1.4.3
svelte-vscode|sve|109.7.0
even-better-toml|tam|0.21.2
vscode-mdx|uni|1.8.14

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dwnewjupyter:31046869
pythonrstrctxt:31112756
nativeloc2:31192216
5fd0e150:31155592
dwcopilot:31170013
6074i472:31201624
dwoutputs:31242946
customenabled:31248079
9064b325:31222308
copilot_t_ci:31222730
e5gg6876:31282496
pythoneinst12:31285622
bgtreat:31268568
4gafe986:31271826
9gig6300:31307012
31787653:31262186
3e8i5726:31271747
996jf627:31283433
pythonrdcb7cf:31303019
usemplatestapi:31297334
0aa6g176:31307128
7bj51361:31289155
747dc170:31275177
aj953862:31281341
generatesymbolt:31295002
convertfstringf:31295003
gendocf:31295004

```

</details>

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #249024

Screenshot 2025-06-20 at 9 28 20 AM

Screenshot 2025-06-20 at 9 28 29 AM

### CODE REVIEW

**Comment by meganrogge** [comment]
Working on pwsh now

**Comment by meganrogge** [comment]
Just realized maybe we want to handle escaping where this gets inserted instead of changing the label?

Yes, going with that instead

**Comment by meganrogge** [comment]
something weird is happening w pwsh . It gets escaped properly and sent to the terminal, but then the inserted text is wrong 

Screenshot 2025-06-20 at 9 58 35 AM
Screenshot 2025-06-20 at 9 58 56 AM

**Comment by meganrogge** [comment]
pwsh seems involved, skipping for now

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts [hunk 1]
```diff
@@ -432,45 +431,6 @@ export class TerminalCompletionService extends Disposable implements ITerminalCo
 			});
 		}
 
-		// Support $CDPATH specially for the `cd` command only
-		//
-		// - (relative) `|` -> `/foo/vscode` (CDPATH has /foo which contains vscode folder)
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts]: CDPATH support being removed?

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionEscapeHelper.ts [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+	}
+
+	// Bash/zsh/fish escaping
+	const specialCharsSet = new Set(['[', ']', '(', ')', '{', '}', `'`, '"', '\\', '$', '`', ';', '&', '|', '<', '>', '*', '?', '~', '#', '=', '%', '!']);
+	const specialCharsRegex = /[\[\]\(\)\{\}'"\\$\`;&|<>*?~#=%!]/;
+	if (!specialCharsRegex.test(label)) {
+		return label;
+	}
+	return label.split('').map(c => specialCharsSet.has(c) ? '\\' + c : c).join('');
+}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionEscapeHelper.ts]: I don't think we can do this generally, these characters may be perfectly valid in the context and this would likely introduce a host of other problems.

The safest approach here is to escape on the completion item in the provider, so escape for the git branch generator and for paths when we know it's safe to do. We also want the label to represent exactly what will be typed and this changes that.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionEscapeHelper.ts (hunk 2 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionEscapeHelper.ts]: ok, re 
> We also want the label to represent exactly what will be typed and this changes that.

That's how I initially implemented it. Then changed the approach because it looked a bit ugly 

Screenshot 2025-06-20 at 9 28 20 AM

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionEscapeHelper.ts]: went back there

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionEscapeHelper.ts]: we resolve the paths in core, not the extension, so cannot do this for just git specifically. What is a case when this is not safe or desirable?

Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionEscapeHelper.ts]: For git it would need to be in the post processing of the generator:

https://github.com/microsoft/vscode/blob/315b0949786b3807f05cb6acd13bf0029690a052/extensions/terminal-suggest/src/completions/upstream/git.ts#L54

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts [hunk 3]
```diff
@@ -432,6 +436,25 @@ export class TerminalCompletionService extends Disposable implements ITerminalCo
...
+		 * This ensures that characters like [, ], etc. are properly escaped.
+		 */
+		function escapeTerminalCompletionLabel(label: string, shellType: TerminalShellType, pathSeparator: string): string {
+			// Only escape for bash/zsh/fish; PowerShell and cmd have different rules
+			if (shellType === GeneralShellType.PowerShell || shellType === WindowsShellType.CommandPrompt) {
+				// TODO: Implement escaping for PowerShell/cmd if needed
+				return label;
+			}
+
+			const specialCharsSet = new Set(['[', ']', '(', ')', '{', '}', `'`, '"', '\\', '$', '`', ';', '&', '|', '<', '>', '*', '?', '~', '#', '=', '%', '!']);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts]: We should verify that all of these are actually needed here and have tests for each case. For example in bash I don't think we should use the escape for `=` since it works without it:

image

Starting with less that we know is wrong and adding over time would be the better approach than trying to cover everything and maybe introducing problems.

100% agree that it's more ugly with the escapes, so we should only use them when needed.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionEscapeHelper.ts (hunk 2 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionEscapeHelper.ts]: I think we should do this for more than git

**Comment by meganrogge** [comment]
I manually tested each to make sure it's necessary @Tyriar and added tests too.

**Comment by meganrogge** [comment]
@Tyriar could you pls review?

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts [hunk 4]
```diff
@@ -559,6 +563,25 @@ function addPathRelativePrefix(text: string, resourceRequestConfig: Pick<Termina
...
 }
 
+/**
+ * Escapes special characters in a file/folder label for shell completion.
+ * This ensures that characters like [, ], etc. are properly escaped.
+ */
+export function escapeTerminalCompletionLabel(label: string, shellType: TerminalShellType, pathSeparator: string): string {
+	// Only escape for bash/zsh/fish; PowerShell and cmd have different rules
+	if (shellType === GeneralShellType.PowerShell || shellType === WindowsShellType.CommandPrompt) {
+		// TODO: Implement escaping for PowerShell/cmd if needed
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts]: Let's remove unless it's needed?

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts [hunk 5]
```diff
@@ -559,6 +563,25 @@ function addPathRelativePrefix(text: string, resourceRequestConfig: Pick<Termina
...
+		return label;
+	}
+
+	const specialCharsSet = new Set(['[', ']', '(', ')', '\'', '"', '\\', '`', '*', '?', ';', '&', '|', '<', '>']);
+	const specialCharsRegex = /[\[\]\(\)'"\\\`\*\?;|&<>]/;
+	if (!specialCharsRegex.test(label)) {
+		return label;
+	}
+	return label.split('').map(c => specialCharsSet.has(c) ? '\\' + c : c).join('');
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts]: Can simplify and use just regex:

```ts
input.replace(/[\[\]\(\)'"\\\`\*\?;|&<>]/g, '\\$&');
```

image

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts [hunk 6]
```diff
@@ -402,6 +402,10 @@ export class TerminalCompletionService extends Disposable implements ITerminalCo
 				label += resourceRequestConfig.pathSeparator;
 			}
 
+			if (shellType) {
+				label = escapeTerminalCompletionLabel(label, shellType, resourceRequestConfig.pathSeparator);
+			}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts]: nit: Could move the if into the escape function and allow it to accept shellType undefined to simplify this function a little

**Review by Tyriar — DISMISSED** [review]

**Review by roblourens — APPROVED** [review]
