### PR TITLE
Fix #171757

### LINKED ISSUE #171757: Output Panel issues with Telemetry and Extension Telemetry channels
Does this issue occur when all extensions are disabled?: Yes

Version: 1.75.0-insider (user setup)
Commit: 5ae522f8563fe48b89470923f77a9732f96c0472
Date: 2023-01-19T14:51:00.913Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

Steps to Reproduce:

1. Set log level to trace 
2. Open the output window 

There are a couple of issues here:
1 - The background of the channel picker seems to be transparent now, which makes it hard to read:
image

2 - The name of the Extension Telemetry channel has changed to the log file path:

image

3 - The Telemetry channel seems to be completely missing

image

For contrast, this is how it looks in VS Code 1.74.3:

image

### PR DESCRIPTION
**Pull request by sandy081**
Fix #171757

### CODE REVIEW

File: src/vs/platform/log/common/log.ts [hunk 1]
```diff
@@ -147,7 +147,7 @@ export interface ILoggerService {
 	 *
 	 * This will also register the logger with the logger service.
 	 */
-	createLogger(resource: URI, options?: ILoggerOptions): ILogger;
+	createLogger(resource: URI, options?: ILoggerOptions, donotRegister?: boolean): ILogger;
```
Comment (hediet) [inline src/vs/platform/log/common/log.ts:150]: Maybe `doNotRegister` is better?

Though I would prefer a method `createDetachedLogger`.

**Review by hediet — DISMISSED** [review]

File: src/vs/platform/log/common/log.ts (hunk 1 above)
Comment (sandy081) [reply src/vs/platform/log/common/log.ts:150]: This argument is temporary until this is adopted https://github.com/microsoft/vscode/issues/172031 - I would remove donotRegister argument after.

Comment (hediet) [reply src/vs/platform/log/common/log.ts:150]: I think it might be helpful to indicate "temporary" with a comment :)

Comment (sandy081) [reply src/vs/platform/log/common/log.ts:150]: I agree. 

But, I am resisting this change and adopt the above item now itself so that we do not need this workaround.

File: src/vs/workbench/api/common/extHostTelemetry.ts [hunk 2]
```diff
@@ -8,38 +8,53 @@ import { createDecorator } from 'vs/platform/instantiation/common/instantiation'
...
+			if (isLogLevel(arg)) {
+				this.updateLoggerVisibility();
+			}
+		}));
 		this._outputLogger.info('Below are logs for extension telemetry events sent to the telemetry output channel API once the log level is set to trace.');
 		this._outputLogger.info('===========================================================');
 	}
 
+	private updateLoggerVisibility(): void {
+		this.loggerService.setVisibility(this.extHostTelemetryLogFile, this._level !== TelemetryLevel.NONE && this.loggerService.getLogLevel() === LogLevel.Trace);
```
Comment (lramos15) [inline src/vs/workbench/api/common/extHostTelemetry.ts:55]: We would want to show the log even when telemetry level is none because we want to show the users that nothing is flowing. We'd want to use the same `supportsTelemetry` function as before  as that's checking for `--disable-telemetry` and things of that nature.

**Review by lramos15 — APPROVED** [review]
Thanks for cleaning this up! I'll make another PR to address some telemetry specific pieces
