### PR TITLE
add command to show terminal quick fixes

### LINKED ISSUE #167416: ctrl/cmd+. doesn't show the action widget menu in the terminal
Screenshot 2022-11-28 at 9 29 52 AM

no when clauses are matched

### PR DESCRIPTION
**Pull request by meganrogge**
fix #167416

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/common/terminal.ts [hunk 1]
```diff
@@ -513,6 +513,7 @@ export const enum TerminalCommandId {
 	Split = 'workbench.action.terminal.split',
 	SplitInstance = 'workbench.action.terminal.splitInstance',
 	SplitInActiveWorkspace = 'workbench.action.terminal.splitInActiveWorkspace',
+	ShowQuickFixes = 'workbench.action.terminal.showQuickFixes',
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/terminal.ts:516]: This should be `workbench.action.terminal.quickFix` like it was before? That aligns with the editor command's wording too

File: src/vs/workbench/contrib/terminal/browser/terminalActions.ts [hunk 2]
```diff
@@ -2204,6 +2204,23 @@ export function registerTerminalActions() {
 			clearShellFileHistory();
 		}
 	});
+	registerAction2(class extends Action2 {
+		constructor() {
+			super({
+				id: TerminalCommandId.ShowQuickFixes,
+				title: { value: localize('workbench.action.terminal.showQuickFixes', "Show Terminal Quick Fixes"), original: 'Show Terminal Quick Fixes' },
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalActions.ts:2211]: 'Terminal Quick Fix...'?

image

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 3]
```diff
@@ -251,42 +258,42 @@ export class TerminalQuickFixAddon extends Disposable implements ITerminalAddon,
...
+			const delegate = {
+				onSelect: async (fix: TerminalQuickFix) => {
+					fix.action?.run();
+					this._actionWidgetService.hide();
+				},
+				onHide: () => {
+					this._terminal?.focus();
+				},
+			};
+			this._currentFixArgs = { items: toMenuItems(actionSet.validActions, true), delegate, anchor, parentElement };
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:293]: It's a little strange that this is getting created when the decoration renders, could we instead move the handling of list items into `showMenu` and use `this._quickFixes` to get it?

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalActions.ts (hunk 2 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalActions.ts:2211]: IMO, that should have a verb since it's a command

File: src/vs/workbench/contrib/terminal/common/terminal.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/common/terminal.ts:516]: I think that it should be a verb to align with all other commands

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts (hunk 3 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:293]: we need the context from the latest render, but yeah makes sense to move the list item creation to `showMenu`

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:293]: oh I had forgotten but we set `this._quickFixes` to undefined on the next command start, so that won't work

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:293]: It would be better to store the raw fixes, say as `_previousQuickFixes`, instead of constructing the actionSet, etc. and not using them

File: src/vs/workbench/contrib/terminal/common/terminal.ts (hunk 1 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/common/terminal.ts:516]: I'm convinced 🙂

**Review by Tyriar — APPROVED** [review]
