### PR TITLE
Hide the feedback form after clicking Submit a bug

### LINKED ISSUE #55713: The feedback popup should disappear after choosing to submit a bug
Issue Type: <b>Bug</b>

- Click on the smiley face in the bottom right corner
- Click on the "Submit a bug" link in the pop up

The issue reporter shows up. At this point, there is no need for the pop up to remain... well, popped up.

VS Code version: Code - Insiders 1.26.0-insider (c86cab2211d6dce686e5c89934d915b1e020ba9e, 2018-08-02T05:17:02.675Z)
OS version: Windows_NT x64 10.0.17134

### PR DESCRIPTION
**Pull request by itamark**
Fixes #55713

### CODE REVIEW

File: src/vs/workbench/parts/feedback/electron-browser/feedback.ts [hunk 1]
```diff
@@ -227,7 +228,14 @@ export class FeedbackDropdown extends Dropdown {
 			})
 			.appendTo($contactUsContainer);
 
-		$('div').append($('a').attr('target', '_blank').attr('href', this.requestFeatureLink).text(nls.localize("request a missing feature", "Request a missing feature")).attr('tabindex', '0'))
+		$('div').append($('a').attr('target', '_blank').attr('href', '#').text(nls.localize("request a missing feature", "Request a missing feature")).attr('tabindex', '0'))
+			.on('click', event => {
+				dom.EventHelper.stop(event);
+				if(!!this.requestFeatureLink){
+					shell.openExternal(this.requestFeatureLink);
```
Comment (RMacfarlane) [inline src/vs/workbench/parts/feedback/electron-browser/feedback.ts]: This looks good!

I think it would be simpler to keep the 'href' as `this.requestFeatureLink` above, and then the on click could just have `this.hide()` and let the event bubble.

Comment (itamark) [reply src/vs/workbench/parts/feedback/electron-browser/feedback.ts]: That's a really good point. I'll rework this tomorrow to use that approach.

**Comment by itamark** [comment]
@RMacfarlane updated the PR with your idea of just letting the event bubble after hiding.

**Comment by RMacfarlane** [comment]
Pushed one small change to remove an unused import. This looks good to me, thanks for your contribution!
