### PR TITLE
Fix bad terminal sticky scroll after `clear` 

### LINKED ISSUE #267408: Bad terminal sticky scroll after running `clear` in terminal
@joaomoreno mentioned that we have bad terminal sticky scroll when running `clear` in terminal.

This seems ugly, doesn't make sense that we display `clear` sticky scroll after running `clear` in the terminal: 
(Tested on Mac)
https://github.com/user-attachments/assets/27f21f61-1ed8-4113-ab11-861737bd9153

We should probably just not show `clear` as terminal sticky scroll when `clear` is run.

/cc @Tyriar

### PR DESCRIPTION
**Pull request by anthonykim1**
Resolves: https://github.com/microsoft/vscode/issues/267408 

This would make sure `user ps1> clear` doesn't show as sticky scroll inappropriately after `clear` has been typed in the terminal.

### CODE REVIEW

**Comment by anthonykim1** [comment]
Additional problem -> I also found out whichever commands that comes right after `clear` displays wrong terminal sticky scroll.
For example, running `git status` after `clear`.
If I run `git status` twice in a row everything is fine.

https://github.com/user-attachments/assets/562cdb1b-a01d-4353-b7af-d9d1b882f889

I saw https://github.com/microsoft/vscode/blob/a8a4f224dc5ef4fc6c2eb38ab8ff140d43cf97af/src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts#L315-L320 was getting set to content of `git status` command, instead of `git status` command itself:

Screenshot 2025-09-18 at 9 00 29 PM
Screenshot 2025-09-18 at 9 00 45 PM

@Tyriar Does this mean we are counting either `stickyScrollLineStart` or `stickyScrollLineCount` wrong?

**Review by meganrogge — DISMISSED** [review]

File: src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts [hunk 1]
```diff
@@ -244,6 +244,12 @@ export class TerminalStickyScrollOverlay extends Disposable {
 			return;
 		}
 
+		// Do not show sticky scroll after `clear` command
+		if (command.command && this._isClearCommand(command.command)) {
+			this._setVisible(false);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts]: I don't think we should do this, while it may end up working initially it's an edge case that will make it feel inconsistent. For example I suspect scrolling up and down will not be sticky as it should.

This is how it shows for me:

Screenshot 2025-09-26 at 8 06 50 am

The main issue is that this should not be possible where sticky scroll obscures the cursor line (or any part of the current command line).

Screenshot 2025-09-26 at 8 08 14 am

When I run another command, you can see something funny is happening with the `A` sequence which looks like the root cause as to why this is happening.

Screenshot 2025-09-26 at 8 09 23 am

The teal `A` should be at the same spot as the red `D`. Meaning we think that `echo a` starts on the following line and is therefore fine to obscure.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts (hunk 1 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts]: Contrast that with how the following command looks:

Screenshot 2025-09-26 at 8 12 03 am

Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts]: Here's a trace:

Screenshot 2025-09-26 at 8 14 32 am

`A` is in the right spot above, see just before the prompt (and before `B`). So I think when were adjusting the sequences we're messing something up. Look into how the `A` sequence is adjusted, we may need to disable that conditionally depending on if it's a clear command similar to what you do here.

Comment (anthonykim1) [reply src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts]: Yeah the A sequence should've been next to prompt not the output. I now prevent wrong adjustment of A sequence here: [f926735](https://github.com/microsoft/vscode/pull/267439/commits/f9267351c56fa7fcc4d00ec61b42e5d92dcc93fa) 

With the most recent approach,  we still won't show `clear` as sticky scroll but this is consistent with all the commands that preceded `clear`. 
It looks like we also didn't have sticky scroll for commands that preceded `clear` before this PR too.
https://github.com/user-attachments/assets/32cd31f8-3bb7-4eba-b614-044cf5f8dbb5

Is this fine?

Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts]: That fix looks a bit like a hack as well. I'm investigating this now. What I've found is that https://github.com/microsoft/vscode/commit/6b8bbf8b6f41 (https://github.com/microsoft/vscode/pull/198463 / https://github.com/microsoft/vscode/issues/198278) was done which forces the D onto the next line if it's on the same as a C which isn't necessarily always what we want.

Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts]: @anthonykim1 I spent a bunch of time trying to write a test but ended up giving up as it's a tricky edge case to cover unfortunately. Anyway, I pushed a change that I think fixes the root cause without more state/comms between hooks and the command detection capability. Could you very on your end and let's try get this in if it works for you.

Comment (anthonykim1) [reply src/vs/workbench/contrib/terminalContrib/stickyScroll/browser/terminalStickyScrollOverlay.ts]: Seems working identical to PR!: 
https://github.com/user-attachments/assets/ce14a853-ac88-44f8-be7e-f3db15942798

We still wont show clear and previous commands preceding `clear` tho

**Review by Tyriar — APPROVED** [review]

**Review by karthiknadig — APPROVED** [review]
