### PR TITLE
fix accessibility support status bar on reload and window open

### LINKED ISSUE #172688: Screenreader status in cleared on reload
Extracted from https://github.com/microsoft/vscode/issues/167627#issuecomment-1407000299

Steps to Reproduce:

1. Open VSCode Insiders
2. Enable Voice Over
3. Verify that the status bar shows `Screen Reader Optimized`
4. Reload window
5. Status bar indication is cleared

Version: 1.75.0-insider (Universal)
Commit: da0309f2514ac22ac82dcd080cfc764fe2a1f434
Date: 2023-01-27T14:19:56.997Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.2.0
Sandboxed: Yes

### LINKED ISSUE #172690: Screenreader activation status is not captured when application starts after the client
Extracted from https://github.com/microsoft/vscode/issues/167627#issuecomment-1407000299

Steps to Reproduce:

1. Enable Voice Over
2. Start VSCode Insiders
3. Application has correctly entered a11y mode, since Voice Over is able to read the contents
4. Status bar does not reflect the a11y mode

Version: 1.75.0-insider (Universal)
Commit: da0309f2514ac22ac82dcd080cfc764fe2a1f434
Date: 2023-01-27T14:19:56.997Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.2.0
Sandboxed: Yes

### PR DESCRIPTION
**Pull request by meganrogge**
fix #172690 
fix #172688

### CODE REVIEW

File: src/vs/platform/windows/electron-main/windowImpl.ts [hunk 1]
```diff
@@ -1050,6 +1050,8 @@ export class CodeWindow extends Disposable implements ICodeWindow {
 		configuration.maximized = this._win.isMaximized();
 		configuration.partsSplash = this.themeMainService.getWindowSplash();
 
+		configuration.accessibilitySupport = app.isAccessibilitySupportEnabled();
```
Comment (meganrogge) [inline src/vs/platform/windows/electron-main/windowImpl.ts:1053]: I'm not sure this is needed - it didn't seem to fix anything 🤔 but @deepak1556 pls lmk your thoughts

**Review by bpasero — DISMISSED** [review]
I was not suggesting to store this in UI state (storage service) but just in a property of the service. I do not think we can assume that after a restart, accessibility mode is still on, or can we?

I am not fully understanding why we cannot do this:
- vscode starts
- we check if a18n is on from the main process
- we pass this as value to windows on startup
- we keep the value in a variable in the a18n service
- the status bar reads it
- we also update from events as we do today

**Comment by meganrogge** [comment]
I misunderstood when I read cache because typically the storage service is where we do that. I will try that approach

**Comment by meganrogge** [comment]
@bpasero I feel like the approach I took is wrong and it's not working. How am I supposed to get the status here?

https://github.com/microsoft/vscode/blob/39954d2fef55d47a0d44553a0d4c0907e4f1e221/src/main.js#L470

**Comment by meganrogge** [comment]
@rzhao271 suggested this should maybe go in `onReady` instead. thoughts @bpasero ?

https://github.com/microsoft/vscode/blob/39954d2fef55d47a0d44553a0d4c0907e4f1e221/src/main.js#L469

File: src/main.js [hunk 2]
```diff
@@ -152,7 +152,6 @@ async function onReady() {
 
 	try {
 		const [, nlsConfig] = await Promise.all([mkdirpIgnoreError(codeCachePath), resolveNlsConfiguration()]);
-
 		startup(codeCachePath, nlsConfig);
```
Comment (meganrogge) [inline src/main.js:155]:
```suggestion

		startup(codeCachePath, nlsConfig);
```

File: src/vs/workbench/services/accessibility/electron-sandbox/accessibilityService.ts [hunk 3]
```diff
@@ -41,6 +41,7 @@ export class NativeAccessibilityService extends AccessibilityService implements
 		@INativeHostService private readonly nativeHostService: INativeHostService
 	) {
 		super(contextKeyService, _layoutService, configurationService);
+		console.log(environmentService.window.accessibilitySupport);
```
Comment (meganrogge) [inline src/vs/workbench/services/accessibility/electron-sandbox/accessibilityService.ts:44]:
```suggestion
```

File: src/main.js [hunk 4]
```diff
@@ -467,6 +467,8 @@ function registerListeners() {
 		macOpenFiles.push(path);
 	});
 
+	global['accessibilitySupportEnabled'] = app.accessibilitySupportEnabled;
```
Comment (deepak1556) [inline src/main.js:470]: Why do we need to store in `global` ? We can always read `app.accessibilitySupportEnabled` from anywhere in the main process and it will reflect the current a11y state. I feel like the global indirection is not necessary.

File: src/vs/code/electron-main/app.ts [hunk 5]
```diff
@@ -731,7 +731,7 @@ export class CodeApplication extends Disposable {
 
 	private async handleProtocolUrl(windowsMainService: IWindowsMainService, urlService: IURLService, uri: URI, options?: IOpenURLOptions): Promise<boolean> {
 		this.logService.trace('app#handleProtocolUrl():', uri.toString(true), options);
-
+		const accessibilitySupportEnabled: boolean = (<any>global).accessibilitySupportEnabled;
```
Comment (deepak1556) [inline src/vs/code/electron-main/app.ts:734]: Is the [current property](https://github.com/microsoft/vscode/blob/224472b8b914862214db6faa9385afa40427acf8/src/vs/platform/windows/electron-main/windowsMainService.ts#L1388) on the `INativeWindowConfiguration` not sufficient , why do we need to specify them at every open call site ?

File: src/vs/platform/windows/electron-main/windowImpl.ts (hunk 1 above)
Comment (deepak1556) [reply src/vs/platform/windows/electron-main/windowImpl.ts:1054]: I was thinking of removing https://github.com/microsoft/vscode/blob/224472b8b914862214db6faa9385afa40427acf8/src/vs/platform/windows/electron-main/windowImpl.ts#L1086 in favor of the current change as it will cover both load and reload path. @bpasero if we update the configuration during load path then is it necessary to define the property at the window open call site, can we remove those in favor of this change ?

**Comment by meganrogge** [comment]
@deepak1556 from your comments, I thought this was more than a UX/status bar item issue. But in my testing, it's just that.

File: src/main.js [hunk 6]
```diff
@@ -152,7 +152,6 @@ async function onReady() {
 
 	try {
 		const [, nlsConfig] = await Promise.all([mkdirpIgnoreError(codeCachePath), resolveNlsConfiguration()]);
```
Comment (meganrogge) [inline src/main.js:154]:
```suggestion
		const [, nlsConfig] = await Promise.all([mkdirpIgnoreError(codeCachePath), resolveNlsConfiguration()]);
		
```

File: src/main.js [hunk 7]
```diff
@@ -152,7 +152,7 @@ async function onReady() {
...
-
+
```
Comment (meganrogge) [inline src/main.js:155]:
```suggestion

```

File: src/main.js (hunk 2 above)
Comment (meganrogge) [inline src/main.js:155]:
```suggestion

		startup(codeCachePath, nlsConfig);
```

**Review by bpasero — APPROVED** [review]
