### PR TITLE
Fixes #153961 by checking if models are disposed.

### LINKED ISSUE #153961: Error: Model is disposed
Steps:
* open a conflict
* close
* select "Dont save"

```
ERR Model is disposed!: Error: Model is disposed!
    at TextModel._assertNotDisposed (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/editor/common/model/textModel.js:243:23)
    at TextModel.getLineMaxColumn (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/editor/common/model/textModel.js:571:18)
    at isAtEndOfLine (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/model/diffComputer.js:102:32)
    at normalizeRangeMapping (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/model/diffComputer.js:72:43)
    at rangeMappingFromCharChange (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/model/diffComputer.js:64:16)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/model/diffComputer.js:54:59
    at Array.map (<anonymous>)
    at fromLineChange (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/model/diffComputer.js:54:50)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/model/diffComputer.js:30:46
    at Array.map (<anonymous>)
    at Function.fromDiffComputationResult (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/model/diffComputer.js:30:35)
    at EditorWorkerServiceDiffComputer.computeDiff (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/model/diffComputer.js:27:61)
    at async TextModelDiffs.update (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/mergeEditor/browser/model/textModelDiffs.js:42:28)
```

### PR DESCRIPTION
**Pull request by hediet**

### CODE REVIEW

**Review by lramos15 — APPROVED** [review]

File: src/vs/workbench/contrib/mergeEditor/browser/model/diffComputer.ts [hunk 1]
```diff
@@ -24,6 +24,10 @@ export class EditorWorkerServiceDiffComputer implements IDiffComputer {
 
 	async computeDiff(textModel1: ITextModel, textModel2: ITextModel): Promise<IDiffComputerResult> {
 		const diffs = await this.editorWorkerService.computeDiff(textModel1.uri, textModel2.uri, false, 1000);
+		if (textModel1.isDisposed() || textModel2.isDisposed()) {
+			// In the meantime, models could be disposed -> early return
+			return { diffs: null };
+		}
 		if (!diffs) {
```
Comment (lramos15) [inline src/vs/workbench/contrib/mergeEditor/browser/model/diffComputer.ts:31]: Could put this all in one if since they both return the same thing, but that's just nit picking
