### PR TITLE
Expose IBackupFileService interfaces to get lists of backed up files

### LINKED ISSUE #15718: Backup service: provide a list of available backups for a workspace
This is a requirement to properly restore backups after a crash (https://github.com/Microsoft/vscode/issues/12327): Upon restart we automatically open folders that contain backups, however we miss information about the files that have backups.

The backup service should provide a method to get all untitled and file backups for a workspace so that we can reopen them. To minimize disk access and chances of staleness, I suggest to include the path within the backup file itself. E.g. the first N-bytes (up to a specific delimiter that is not allowed in file paths) can be the path and the rest is the file content. I would NOT use JSON for this and also NOT store this separately to avoid staleness issues.

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #15718 

---

@bpasero if this is close to what you had in mind feel free to merge and tweak as desired. One improvement that comes to mind is to store items in the `IBackupFilesModel` cache using `Uri.fsPath` instead of `Uri.toString`, wasn't sure if `toString` was chosen for a particular reason?

### CODE REVIEW

File: src/vs/base/node/stream.ts [hunk 1]
```diff
@@ -96,4 +96,70 @@ export function readExactlyByFile(file: string, totalBytes: number, callback: (e
...
+						return end(null, null);
+					}
+
+					return loop();
+				}
+
+				bytesRead += moreBytesRead;
+
+				const newLineIndex = buffer.indexOf(matchingString);
+				if (buffer.indexOf('\n') >= 0) {
```
Comment (bpasero) [inline src/vs/base/node/stream.ts]: @Tyriar is this an oversight? why suddenly you look for `\n` and call it `newLineIndex` if `matchingString` can be anything?

File: src/vs/workbench/services/textfile/common/textFileEditorModel.ts [hunk 2]
```diff
@@ -290,11 +290,14 @@ export class TextFileEditorModel extends BaseTextEditorModel implements ITextFil
 				diag('load() - created text editor model', this.resource, new Date());
 
 				return this.backupFileService.loadBackupResource(this.resource).then(backupResource => {
-					let resolveBackupPromise: TPromise<IRawText>;
+					let resolveBackupPromise: TPromise<string | IRawText>;
 
 					// Try get restore content, if there is an issue fallback silently to the original file's content
 					if (backupResource) {
-						resolveBackupPromise = this.textFileService.resolveTextContent(backupResource, BACKUP_FILE_RESOLVE_OPTIONS).then(backup => backup.value, error => content.value);
+						resolveBackupPromise = this.textFileService.resolveTextContent(backupResource, BACKUP_FILE_RESOLVE_OPTIONS).then(backup => {
```
Comment (bpasero) [inline src/vs/workbench/services/textfile/common/textFileEditorModel.ts]: @Tyriar this is bad, what if we resolve the text content in another place? everyone has to remove the first line? why not move the entire thing into the backup service and thus have the logic in one place where it should be. We can even get rid of `loadBackupResource` and just have 1 method to call to resolve the backup content (which can be null if there is no backup).

File: src/vs/workbench/services/backup/node/backupFileService.ts [hunk 3]
```diff
@@ -147,6 +158,10 @@ export class BackupFileService implements IBackupFileService {
 				return void 0; // return early if backup version id matches requested one
 			}
 
+			if (resource.scheme === 'file') {
+				content = `${resource.fsPath}\n${content}`;
```
Comment (bpasero) [inline src/vs/workbench/services/backup/node/backupFileService.ts]: @Tyriar I suggest to use `Uri.toString()` here and `Uri.parse()` on the other side to reconstruct.

File: src/vs/workbench/services/backup/node/backupFileService.ts [hunk 4]
```diff
@@ -147,6 +158,10 @@ export class BackupFileService implements IBackupFileService {
 				return void 0; // return early if backup version id matches requested one
 			}
 
+			if (resource.scheme === 'file') {
```
Comment (bpasero) [inline src/vs/workbench/services/backup/node/backupFileService.ts]: @Tyriar so you say that you do this only for files because untitled do not have this issue? not sure about that, what about someone that starts "`code <file name>`" where the file path does not exist and we show an untitled file with associated file path? I think we will have to store the path for untitled too in that case. Maybe untitled files should be stored differently on disk compared to today: instead of using their name (`Untitled-1`, `Untitled-2`), hash the associated file path and if there is none, hash the name.

File: src/vs/workbench/services/backup/node/backupFileService.ts [hunk 5]
```diff
@@ -64,6 +67,14 @@ export class BackupFilesModel implements IBackupFilesModel {
 		return true;
 	}
 
+	public getTextFiles(): string[] {
```
Comment (bpasero) [inline src/vs/workbench/services/backup/node/backupFileService.ts]: @Tyriar this is some crazy string magic that is not very robust, instead I suggest to use the `URI` apis we already have: use `URI.parse()` to convert the resource string into a `URI` and then you have access to `fsPath` and scheme to find out what you want.

File: src/vs/workbench/services/backup/node/backupFileService.ts [hunk 6]
```diff
@@ -172,6 +187,29 @@ export class BackupFileService implements IBackupFileService {
 		});
 	}
 
+	public getWorkspaceTextFileBackups(): TPromise<string[]> {
```
Comment (bpasero) [inline src/vs/workbench/services/backup/node/backupFileService.ts]: @Tyriar at first I thought this should move into the cache but then we would stop each and every file open waiting for this to be done. Since backups can be restored later, I think it is OK to leave this outside of the cache even though the result could probably be cached.

**Review by bpasero — CHANGES_REQUESTED** [review]
@Tyriar done with a review, thanks!

File: src/vs/base/node/stream.ts (hunk 1 above)
Comment (Tyriar) [inline src/vs/base/node/stream.ts]: https://github.com/Microsoft/vscode/pull/16194/commits/4b5e644458a088ec14da1df1e64395e1e464ed79

File: src/vs/workbench/services/textfile/common/textFileEditorModel.ts (hunk 2 above)
Comment (Tyriar) [inline src/vs/workbench/services/textfile/common/textFileEditorModel.ts]: This reintroduces the dependency issue as `TextFileService` already depends on `BackupService`, any easy way around this?

Comment (bpasero) [inline src/vs/workbench/services/textfile/common/textFileEditorModel.ts]: @Tyriar right, then at least there should be a method on the backup file service that we can go to convert a content into path and content. That way we still have the metadata logic inside backup file service and you can also write tests for it.

File: src/vs/workbench/services/backup/node/backupFileService.ts (hunk 5 above)
Comment (Tyriar) [inline src/vs/workbench/services/backup/node/backupFileService.ts]: https://github.com/Microsoft/vscode/pull/16194/commits/7847c19b35c70f159253d02c28740bd1e8e65460 https://github.com/Microsoft/vscode/pull/16194/commits/b360e0562b60d43e4b39049f04fa1462dcdea4d0

File: src/vs/workbench/services/backup/node/backupFileService.ts (hunk 4 above)
Comment (Tyriar) [inline src/vs/workbench/services/backup/node/backupFileService.ts]: https://github.com/Microsoft/vscode/pull/16194/commits/37ad5fa94d370c8f4d0abe5bbb0ef5e2d614dd4d

**Comment by Tyriar** [comment]
I included the fix for Untitled files with associated path behave very weird #15941 (hash untitled paths too) in this PR as it depends on these changes.
