### PR TITLE
Fix reporting issues on extensions in the web

### LINKED ISSUE #185820: Clicking report issue from extension context menu doesn't report issue in extension's issue management
1. Go to Running Extensions
2. Right click on extension (e.g. Vim)
3. Click report issue

Observed behavior:

Takes the user to https://github.com/Microsoft/vscode/issues/new

Expected behavior:

Takes the user to https://github.com/VSCodeVim/Vim/issues/new
Screenshot from 2023-06-22 10-11-10

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Embedder: vscode.dev

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
Fixes https://github.com/microsoft/vscode/issues/185820

### CODE REVIEW

File: src/vs/workbench/services/issue/browser/issueService.ts [hunk 1]
```diff
@@ -33,55 +32,62 @@ export class WebIssueService implements IWorkbenchIssueService {
...
-				} catch (e) {
-					this.logService.error(e);
-				}
+		const extensionId = options.extensionId;
+		// If we don't have a extensionId, treat this as a Core issue
+		if (!extensionId) {
+			if (this.productService.reportIssueUrl) {
+				const uri = this.getIssueUriFromStaticContent(this.productService.reportIssueUrl);
+				dom.windowOpenNoOpener(uri);
+				return;
```
Comment (TylerLeonhardt) [inline src/vs/workbench/services/issue/browser/issueService.ts:41]: testing ghpr

**Review by lramos15 — APPROVED** [review]
