### PR TITLE
Lint redundant activation events if extension is targeting `^1.75`

### LINKED ISSUE #173196: Activation event removal warning doesn't consider vscode engine
When developing extension the warning in `package.json`:

> This activation event can be removed as VS Code generates these automatically from your package.json contribution declarations.

is wrong because it doesn't check if the extension is supported on older VSCode versions:

```js
"engines": {
	"vscode": "^1.55.0"
},
```

### PR DESCRIPTION
**Pull request by joyceerhl**
Fix https://github.com/microsoft/vscode/issues/173196

### CODE REVIEW

File: extensions/extension-editing/src/extensionEngineValidation.ts [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+
+const VERSION_REGEXP = /^(\^|>=)?((\d+)|x)\.((\d+)|x)\.((\d+)|x)(\-.*)?$/;
+const NOT_BEFORE_REGEXP = /^-(\d{4})(\d{2})(\d{2})$/;
+
+export function isValidVersionStr(version: string): boolean {
+	version = version.trim();
+	return (version === '*' || VERSION_REGEXP.test(version));
+}
+
+export function parseVersion(version: string): IParsedVersion | null {
```
Comment (Tyriar) [inline extensions/extension-editing/src/extensionEngineValidation.ts:39]: Some unit tests should be easy to write for these and prevent possible accidents.

**Review by Tyriar — APPROVED** [review]

File: extensions/extension-editing/src/extensionEngineValidation.ts (hunk 1 above)
Comment (joyceerhl) [reply extensions/extension-editing/src/extensionEngineValidation.ts:39]: These are taken directly from our https://github.com/microsoft/vscode/blob/6cb34eb22385bc93ab25aa2e5113f59c7a2299ac/src/vs/platform/extensions/common/extensionValidator.ts which already has test coverage: https://github.com/microsoft/vscode/blob/19014d03d6a3b174840dbb5e18180c065f43e746/src/vs/platform/extensions/test/common/extensionValidator.test.ts#L31

Comment (Tyriar) [reply extensions/extension-editing/src/extensionEngineValidation.ts:39]: I'd copy the tests over with the code, but up to you
