### PR TITLE
Handle bad file nesting values

### LINKED ISSUE #178387: Unable to create tsx file in Explorer
Type: <b>Bug</b>

1. Open a folder in vscode
2. Use the ui of Explorer to create three tsx files named a.tsx, b.tsx, and c.tsx

Expected behavior: Three files were successfully created

Actual situation: After b.tsx is created, an exception occurs in the Explorer and files cannot be created using the ui

https://user-images.githubusercontent.com/73151139/227854567-444d8577-e2ae-4bc5-b909-fa2fad5423bf.mp4

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.05GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 07e1495b-cbeb-4846-afdf-9b880346d040|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30677850
functionswalk:30687959
pythonms35cf:30686773

```

</details>

### PR DESCRIPTION
**Pull request by lramos15**
Fixes #178387

### CODE REVIEW

File: src/vs/workbench/contrib/files/common/explorerModel.ts [hunk 1]
```diff
@@ -377,6 +377,7 @@ export class ExplorerItem {
 					[
 						this.getPlatformAwareName(parentPattern.trim()),
 						childrenPatterns.split(',').map(p => this.getPlatformAwareName(p.trim().replace(/\u200b/g, '')))
```
Comment (Tyriar) [inline src/vs/workbench/contrib/files/common/explorerModel.ts:379]: Should you trim after the replace?

**Review by Tyriar — DISMISSED** [review]

File: src/vs/workbench/contrib/files/common/explorerModel.ts (hunk 1 above)
Comment (lramos15) [reply src/vs/workbench/contrib/files/common/explorerModel.ts:379]: Or trim on the filter would be smart

**Review by Tyriar — APPROVED** [review]
