### PR TITLE
Don't call fireSimulatedContinuedEvent if the debug adapter sent a Stopped event before the response of the next/stepIn/etc request

### LINKED ISSUE #185785: VS Code change between 1.78.2 and 1.79.0 broke debug adapter
Stepping using the debug adapter that I helped develop has been broken by a VS Code change between 1.78.2 and 1.79.0. I used a `DebugAdapterTracker` to log the messages sent back and forth using the same extension version, but different VS Code versions. I attached the logs below. After diffing the two files, the only difference is that the "scopes" request isn't sent to the adapter after the "next" request reports a stopped event. The end result is that the debugging UI in VS Code is stuck in "running" mode even though the debug adapter is stopped, and the user has no way to advance.

[1782.txt](https://github.com/microsoft/vscode/files/11819620/1782.txt)

[1792.txt](https://github.com/microsoft/vscode/files/11819627/1792.txt)

*See https://github.com/intersystems-community/vscode-objectscript/issues/1169*

### PR DESCRIPTION
**Pull request by roblourens**
Fix #185785

### CODE REVIEW

File: src/vs/workbench/contrib/debug/browser/rawDebugSession.ts [hunk 1]
```diff
@@ -326,29 +328,43 @@ export class RawDebugSession implements IDisposable {
 	}
 
 	async next(args: DebugProtocol.NextArguments): Promise<DebugProtocol.NextResponse | undefined> {
+		this.stoppedSinceLastStep = false;
 		const response = await this.send('next', args);
-		this.fireSimulatedContinuedEvent(args.threadId);
+		if (!this.stoppedSinceLastStep) {
```
Comment (isidorn) [inline src/vs/workbench/contrib/debug/browser/rawDebugSession.ts:333]: This has a double `if`. Probably a typo.

**Review by isidorn — DISMISSED** [review]
Looks good. Found 1 typo.

File: src/vs/workbench/contrib/debug/browser/rawDebugSession.ts (hunk 1 above)
Comment (roblourens) [reply src/vs/workbench/contrib/debug/browser/rawDebugSession.ts:333]: Too much cmd+D here 👍

**Review by connor4312 — APPROVED** [review]
