### PR TITLE
fix(sash): dragging being difficult with iframe-containing extensions

### LINKED ISSUE #76866: WebView Panel having iframe with some style suffers from a non smooth resizing
- VSCode Version: Version: 1.37.0-insider
Commit: d50852db1af10ec100a71ad57cc3a04c8aead117
Date: 2019-07-08T05:33:31.335Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.7.0
- OS Version: macOS High Sierra 10.13.6 (17G7024)

Steps to Reproduce:

1. Execute the following sample code of extension.
2. Resize the WebView Panel.
3. Resizing is not smooth.

Jul-08-2019 19-37-40

```typescript
import * as vscode from 'vscode';
import * as path from 'path';

export function activate(context: vscode.ExtensionContext) {
  const rootUrl = vscode.Uri.file(context.extensionPath)
  const disposable = vscode.commands.registerCommand('extension.helloWorld', async () => {
    if (!vscode.window.activeTextEditor) {
      return;
    }
    
    const panel = vscode.window.createWebviewPanel(
      'catCoding',
      'Cat Coding',
      { viewColumn: vscode.ViewColumn.Beside },
      { enableScripts: true, localResourceRoots: [ rootUrl ] }
    );
    panel.webview.html = getHtml(rootUrl);
  });
  context.subscriptions.push(disposable);
}

function getHtml(rootUrl: vscode.Uri) {
	const html = rootUrl.with( { scheme: 'vscode-resource', path: path.join(rootUrl.path, './t.html') }).toString()
	return `
<!DOCTYPE html><html><head></head>
<iframe src="${html}" style="position:absolute; border: none; left: 0; top: 0; width: 100%; height: 100%;">
`
}
// this method is called when your extension is deactivated
export function deactivate() {}
```

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by connor4312**
It appears that (running querySelector, getElementByTagName) the
contents of electron's `<webviews>`, which contain the iframe, are
inaccessible. We were already disabling pointer events on iframes, this PR
makes sure we do so on webviews as well.

Kapture 2019-07-10 at 10 32 10

Fixes https://github.com/microsoft/vscode/issues/76866

### CODE REVIEW

**Comment by joaomoreno** [comment]
@mjbvz Maybe the fix is that simple.

**Comment by connor4312** [comment]
@joaomoreno it looks like @mjbvz's fix is identical to this one, but has some additional code cleanup elsewhere.

File: src/vs/base/browser/ui/sash/sash.ts [hunk 1]
```diff
@@ -280,7 +286,6 @@ export class Sash extends Disposable {
 
 			dispose(disposables);
 
-			const iframes = getElementsByTagName('iframe');
```
Comment (connor4312) [inline src/vs/base/browser/ui/sash/sash.ts]: I removed this so that we use the same set of frames we selected previously (`iframes` was shadowed here). No need to select them twice--even if there's new iframes/webviews that appeared whilst dragging, we don't need to 'reset' their pointer events since we didn't touch them before.

**Comment by mjbvz** [comment]
Thanks. The fix looks reasonable to me. It will be in the next 1.37 insiders build for testing
