### PR TITLE
Fix scrolling behavior in menu while zoomed in

### LINKED ISSUE #80047: Scroll Issue in Top Menu
If you enlarge the VSCode interface, then a scrollbar will appear in top menu items(View,Debug).

I found a problem with that scrollbar, if you try to scroll it to the end it scrolls back automatically in an abnormal way.

Have a look at the attached GIF for better understanding.

vscodeScrollBug

Steps to Reproduce:

1. Enlarge interface by pressing Ctrl **+** + Button until a scrollbar appears in toolbar items(View, Debug).
2.  Select **View** from toolbar and try to scroll to the end. It will scroll backward after touching the end.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes #80047

### CODE REVIEW

**Comment by sbatten** [comment]
@jeanp413 thanks for the PR. and thanks for the pointer about the chrome issue. I notice some of the changes are just rearranging of lines and additionally some changes in the submenuviewitem. Are these changes strictly necessary to address the issue? If not, I would like to keep this PR to the minimum amount of changes.

Additionally, some of the changes are in actionbar, which I am hesitant to take anything that affects more than the menu widget. So, it might be better to pull more of that code up a layer.

File: src/vs/base/browser/ui/actionbar/actionbar.ts [hunk 1]
```diff
@@ -747,7 +747,7 @@ export class ActionBar extends Disposable implements IActionRunner {
 
 	protected updateFocus(fromRight?: boolean): void {
 		if (typeof this.focusedItem === 'undefined') {
-			this.actionsList.focus();
+			this.actionsList.focus({ preventScroll: true });
```
Comment (jeanp413) [inline src/vs/base/browser/ui/actionbar/actionbar.ts]: The `{ preventScroll: true }` is necessary to avoid scrolling up when focusing the `<ul class="actions-container">`

File: src/vs/base/browser/ui/menu/menu.ts [hunk 2]
```diff
@@ -730,13 +723,7 @@ class SubmenuMenuActionViewItem extends BaseMenuActionViewItem {
...
 					this.parentData.parent.focus();
 
-					if (this.parentData.submenu) {
-						this.parentData.submenu.dispose();
-						this.parentData.submenu = undefined;
-					}
-
-					this.submenuDisposables.clear();
-					this.submenuContainer = undefined;
+					this.cleanupExistingSubmenu(true);
```
Comment (jeanp413) [inline src/vs/base/browser/ui/menu/menu.ts]: This is just some cleaning up duplicate code. Do you want me to revert this?

File: src/vs/base/browser/ui/menu/menu.ts [hunk 3]
```diff
@@ -200,26 +193,14 @@ export class Menu extends ActionBar {
 		const scrollElement = this.scrollableElement.getDomNode();
 		scrollElement.style.position = null;
 
-		menuElement.style.maxHeight = `${Math.max(10, window.innerHeight - container.getBoundingClientRect().top - 30)}px`;
-
-		this.menuDisposables.add(this.scrollableElement.onScroll(() => {
-			this._onScroll.fire();
-		}, this));
+		this.viewItems.filter(item => !(item instanceof MenuSeparatorActionViewItem)).forEach((item: BaseMenuActionViewItem, index: number, array: any[]) => {
```
Comment (jeanp413) [inline src/vs/base/browser/ui/menu/menu.ts]: Should I revert this?

File: src/vs/base/browser/ui/menu/menu.ts [hunk 4]
```diff
@@ -185,7 +178,7 @@ export class Menu extends ActionBar {
 
 		this.mnemonics = new Map<string, Array<BaseMenuActionViewItem>>();
 
-		this.push(actions, { icon: true, label: true, isMenu: true });
+		menuElement.style.maxHeight = `${Math.max(10, window.innerHeight - container.getBoundingClientRect().top - 30)}px`;
```
Comment (jeanp413) [inline src/vs/base/browser/ui/menu/menu.ts]: Should I revert this?

File: src/vs/base/browser/ui/menu/menu.ts [hunk 5]
```diff
@@ -200,26 +193,14 @@ export class Menu extends ActionBar {
...
+		});
 
-		this._register(addDisposableListener(this.menuElement, EventType.SCROLL, (e: ScrollEvent) => {
-			if (this.scrollTopHold !== undefined) {
-				this.menuElement.scrollTop = this.scrollTopHold;
-				this.scrollTopHold = undefined;
-			}
-			this.scrollableElement.scanDomNode();
-		}));
+		this.push(actions, { icon: true, label: true, isMenu: true });
```
Comment (jeanp413) [inline src/vs/base/browser/ui/menu/menu.ts]: `this.scrollableElement` must be created before calling this because now it's being used directly in `get onScroll()`

**Comment by sbatten** [comment]
@jeanp413 If it isn't necessary to fix the original issue, let's revert it. Testing it, I seet that it works and once we have it to a minimum we can see if we need to worry about the code change in actionbar.ts

**Review by sbatten — CHANGES_REQUESTED** [review]
as mentioned, let's focus the changes strictly to what's necessary

**Comment by jeanp413** [comment]
Reverted some changes. Let me know if that's enough

**Comment by sbatten** [comment]
@jeanp413 This is looking great, I hope you don't mind but I moved the logic you had in `menubar.ts` to avoid dismissing the menu on scrollbar clicking into `menu.ts`, since those clicks should not be propogated.

**Review by sbatten — APPROVED** [review]

**Comment by jeanp413** [comment]
@sbatten yeah it's great, but I found a minor issue when you click on the scrollbar it doesn't stop tracking it. Seems like it's necessary to let the event propagate because it's used here
https://github.com/microsoft/vscode/blob/ede82b16387ecbebadadcc3a72f511be13434e20/src/vs/base/browser/globalMouseMoveMonitor.ts#L87-L93

**Comment by sbatten** [comment]
@jeanp413 good catch, updated and merging

File: src/vs/base/browser/ui/menu/menubar.ts [hunk 6]
```diff
@@ -274,6 +274,10 @@ export class MenuBar extends Disposable {
 			}));
 
 			this._register(DOM.addDisposableListener(buttonElement, DOM.EventType.MOUSE_UP, (e) => {
+				if (e.defaultPrevented) {
+					return;
+				}
```
Comment (jeanp413) [inline src/vs/base/browser/ui/menu/menubar.ts]: @sbatten I tested this and it fixes the issue for level 1 menus but it doesn't fix it for submenus with level > 1
I think we need to add the same check here
https://github.com/microsoft/vscode/blob/26cb1c811c7c9d6da1490dfb65b4e4f695f86116/src/vs/base/browser/ui/menu/menu.ts#L392-L395
https://github.com/microsoft/vscode/blob/26cb1c811c7c9d6da1490dfb65b4e4f695f86116/src/vs/base/browser/ui/menu/menubar.ts#L371-L379
