### PR TITLE
Refactors code and fixes memory leak. Fixes #224943.

### LINKED ISSUE #224943: [034] potential listener LEAK detected, having 1001 listeners already. MOST frequent listener (791):
```javascript
Error
at c.create in src/vs/base/common/event.ts:902:15
at m.q [as c] in src/vs/base/common/event.ts:1109:34
at get onDidChange in src/vs/editor/common/services/languageService.ts:179:26
at U in src/vs/editor/common/model/textModel.ts:324:66
at g.J in src/vs/editor/common/services/modelService.ts:317:28
at g.createModel in src/vs/editor/common/services/modelService.ts:452:21
at P.H in src/vs/workbench/common/editor/textEditorModel.ts:154:30
at P.G in src/vs/workbench/common/editor/textEditorModel.ts:148:15
at P.Fb in src/vs/workbench/services/textfile/common/textFileEditorModel.ts:557:26
at P.Eb in src/vs/workbench/services/textfile/common/textFileEditorModel.ts:539:9
at P.Db in src/vs/workbench/services/textfile/common/textFileEditorModel.ts:464:16
at async P.resolve in src/vs/workbench/services/textfile/common/textFileEditorModel.ts:302:3
at async s.W in src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts:421:4
at async r.jb in src/vs/workbench/contrib/files/browser/editors/fileEditorInput.ts:360:4
at async N.setInput in src/vs/workbench/contrib/files/browser/editors/textFileEditor.ts:108:26
at async o.S in src/vs/workbench/browser/parts/editor/editorPanes.ts:434:4
at async o.L in src/vs/workbench/browser/parts/editor/editorPanes.ts:254:34
at async o.openEditor in src/vs/workbench/browser/parts/editor/editorPanes.ts:131:11
at async in src/vs/workbench/browser/parts/editor/editorGroupView.ts:1269:49
at async d.value in src/vs/workbench/contrib/files/browser/views/explorerView.ts:526:6
```
[Go to Errors Site](https://errors.code.visualstudio.com/card?ch=f1e16e1e6214d7c44d078b1f0607b2388f29d729&bH=903c8d60-7ee8-0dcb-dfee-a6c724e17dba)

### PR DESCRIPTION
**Pull request by hediet**
fixes #224943

### CODE REVIEW

File: src/vs/editor/common/services/languageService.ts [hunk 1]
```diff
@@ -150,51 +151,15 @@ export class LanguageService extends Disposable implements ILanguageService {
...
-			this._listener.dispose();
-			this._listener = null;
-		}
-		if (this._emitter) {
-			this._emitter.dispose();
-			this._emitter = null;
-		}
+	constructor(onDidChangeLanguages: Event<void>, selector: () => string) {
+		this._value = observableFromEvent(this, onDidChangeLanguages, () => selector());
+		this.onDidChange = Event.fromObservable(this._value);
```
Comment (Tyriar) [inline src/vs/editor/common/services/languageService.ts:159]: Do you not need to register this?

**Review by 1chooo — APPROVED** [review]

File: src/vs/editor/common/services/languageService.ts (hunk 1 above)
Comment (hediet) [reply src/vs/editor/common/services/languageService.ts:159]: Why? This is the event, not the event subscription. As for the Emitter, disposing it is optional and doesn't help here (which is easiest to see in the old implementation, where the emitter would only be disposed if the last listener unsubscribes, in which case disposing the emitter doesn't do anything).
Emitters are not considered by the disposable tracking tooling.

**Review by alexdima — APPROVED** [review]
