### PR TITLE
Do not show the dialog if the dialog is currently being shown

### LINKED ISSUE #148454: "Unusual line terminators" repeated until accepting.
Issue Type: <b>Bug</b>

I had a file with unusual line endings in it, and this happened: https://www.youtube.com/watch?v=16DfKy_L-UM the dialog kept reappearing after pressing 'ignore' until i finally relented. When I tried to create a new file with weird line endings it seemed to work, maybe since I had the file opened while the file was being generated, every time the file changed the dialog was re-enqueued even though it was already open?

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|32.00GB (0.68GB free)|
|Process Argv|--crash-reporter-id 68611f54-ccc1-4e50-bdfd-8907e222ef78|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
astro-vscode|ast|0.16.0
vscode-graphql|Gra|0.4.4
vscode-docker|ms-|1.22.0
svelte-vscode|sve|105.16.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

### PR DESCRIPTION
**Pull request by alexdima**
Fixes #148454

### CODE REVIEW

File: src/vs/editor/contrib/unusualLineTerminators/browser/unusualLineTerminators.ts [hunk 1]
```diff
@@ -85,13 +86,25 @@ export class UnusualLineTerminatorsDetector extends Disposable implements IEdito
...
+		if (this._isPresentingDialog) {
+			// we're currently showing the dialog, which is async.
+			// avoid spamming the user
+			return;
+		}
+
+		let result: IConfirmationResult;
+		try {
+			this._isPresentingDialog = true;
+			result = await this._dialogService.confirm({
```
Comment (TylerLeonhardt) [inline src/vs/editor/contrib/unusualLineTerminators/browser/unusualLineTerminators.ts:98]: I'm surprised to see the dialog service throw. When does that happen?

Comment (alexdima) [reply src/vs/editor/contrib/unusualLineTerminators/browser/unusualLineTerminators.ts:98]: Always when I have a field that I use to avoid recursion, I use a try/finally block to make sure the field gets reset. This is such that the code is always correct regardless of where execution ends up.

File: src/vs/editor/contrib/unusualLineTerminators/browser/unusualLineTerminators.ts [hunk 2]
```diff
@@ -85,13 +86,25 @@ export class UnusualLineTerminatorsDetector extends Disposable implements IEdito
...
+				message: nls.localize('unusualLineTerminators.message', "Detected unusual line terminators"),
+				detail: nls.localize('unusualLineTerminators.detail', "The file '{0}' contains one or more unusual line terminator characters, like Line Separator (LS) or Paragraph Separator (PS).\n\nIt is recommended to remove them from the file. This can be configured via `editor.unusualLineTerminators`.", basename(model.uri)),
+				primaryButton: nls.localize('unusualLineTerminators.fix', "Remove Unusual Line Terminators"),
+				secondaryButton: nls.localize('unusualLineTerminators.ignore', "Ignore")
+			});
+		} finally {
+			this._isPresentingDialog = false;
+		}
 
 		if (!result.confirmed) {
```
Comment (joaomoreno) [inline src/vs/editor/contrib/unusualLineTerminators/browser/unusualLineTerminators.ts:109]: I'm surprised to see TypeScript not complain about this. If the dialog service does throw, wouldn't that make `result` be `undefined`?

Comment (alexdima) [reply src/vs/editor/contrib/unusualLineTerminators/browser/unusualLineTerminators.ts:109]: @joaomoreno There's no `catch` block. If it throws, execution goes out of the method, but before doing that it sets `this._isPresentingDialog` to false.

Comment (joaomoreno) [reply src/vs/editor/contrib/unusualLineTerminators/browser/unusualLineTerminators.ts:109]: Oh my.

**Review by joaomoreno — APPROVED** [review]
