### PR TITLE
make webgl default renderer

### LINKED ISSUE #118064: Make the WebGL terminal renderer the default
Part of https://github.com/microsoft/vscode/issues/106202

We should also improve the fallback logic to do this:

- Try webgl
- If it threw an exception, try canvas
- If frame rendering averages > 50ms (existing detection), use DOM

We will keep the canvas renderer around for now mainly because Safari doesn't support webgl2 and can evaluate [whether we want to remove it](https://github.com/microsoft/vscode/issues/106202) again at a later date.

### PR DESCRIPTION
**Pull request by meganrogge**
and catch if loading the addon fails, going w dom in that case

This PR is a part of #106202
Fixes https://github.com/microsoft/vscode/issues/118064

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 1]
```diff
@@ -1307,13 +1307,12 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 		this._safeSetOption('macOptionClickForcesSelection', config.macOptionClickForcesSelection);
 		this._safeSetOption('rightClickSelectsWord', config.rightClickBehavior === 'selectWord');
 		this._safeSetOption('wordSeparator', config.wordSeparators);
-		if (config.rendererType === 'experimentalWebgl') {
+		if (config.rendererType === 'auto') {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1310]: I think this is more correct?

```suggestion
		if (config.rendererType === 'auto' || config.rendererType === 'experimentalWebgl') {
```

Also do we have protections to avoid double enabling the webgl renderer?

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 2]
```diff
@@ -1324,7 +1323,17 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 		}
 		const Addon = await this._terminalInstanceService.getXtermWebglConstructor();
 		this._webglAddon = new Addon();
-		this._xterm.loadAddon(this._webglAddon);
+		try {
+			this._xterm.loadAddon(this._webglAddon);
+		} catch {
+			this._disposeOfWebglRenderer();
+			this._safeSetOption('rendererType', 'dom');
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1330]: We'll want to remember this failure and not try again, I guess until the setting changes so it's possible to fix it up if for example hardware changes in the meantime by changing the setting?

**Review by Tyriar — CHANGES_REQUESTED** [review]
I was thinking about the frame measurement and maybe we don't need to do that with webgl as I don't think browsers are able to fallback to CPU for that like they do with a 2d canvas context. So we shouldn't see the massive change in render time, it just works or doesn't and throws.

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts (hunk 1 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts]: Oh I see there are protections with `if (!this._xterm || this._webglAddon) {`, all good

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts]: Yep

**Comment by meganrogge** [comment]
To do:
https://github.com/microsoft/vscode/issues/118064

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 3]
```diff
@@ -422,7 +422,7 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 			fastScrollModifier: 'alt',
 			fastScrollSensitivity: editorOptions.fastScrollSensitivity,
 			scrollSensitivity: editorOptions.mouseWheelScrollSensitivity,
-			rendererType: config.rendererType === 'auto' || config.rendererType === 'experimentalWebgl' ? 'dom' : config.rendererType,
+			rendererType: config.rendererType === 'auto' || config.rendererType === 'experimentalWebgl' ? 'canvas' : config.rendererType,
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts]: Let's use brackets around the first part, I'm not 100% sure whether the execution order is:

`(a || b) ? c : d` or `a || (b ? c : d)`

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 4]
```diff
@@ -1337,7 +1337,7 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 	private _disposeOfWebglRenderer(): void {
 		this._webglAddon?.dispose();
 		this._webglAddon = undefined;
-		this._changedRendererType = false;
+		this._storageService.store(HAS_CHANGED_RENDERER_TYPE, false, StorageScope.GLOBAL, StorageTarget.USER);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1340]: I think a simpler way to store would be to store the auto detected renderer, rather than storing whether the setting changed. That way we can evaluate one time which renderer seems like the best for that machine and store it in the storage service. Then all other reloads we can just query that if the key exists and the setting is `auto`. On changing the setting we can just delete the storage key.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 5]
```diff
@@ -1324,7 +1321,24 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 		}
 		const Addon = await this._terminalInstanceService.getXtermWebglConstructor();
 		this._webglAddon = new Addon();
-		this._xterm.loadAddon(this._webglAddon);
+		try {
+			this._xterm.loadAddon(this._webglAddon);
+			this._storageService.store(SUGGESTED_RENDERER_TYPE, 'auto', StorageScope.GLOBAL, StorageTarget.MACHINE);
+		} catch {
+			const neverMeasureRenderTime = this._storageService.getBoolean(NEVER_MEASURE_RENDER_TIME_STORAGE_KEY, StorageScope.GLOBAL, false);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1328]: When we fallback let's add a log service warn, otherwise it will be hard to tell what auto has selected or when you set webgl explicitly (I guess falling back is fine then)

**Review by Tyriar — APPROVED** [review]
