### PR TITLE
Inconsistent font size in a comment with `code` blocks

### LINKED ISSUE #146183: Inconsistent font size in a comment with inline `code` blocks
- Extension version: 0.38.1
- VSCode Version: 1.65.2
- OS: macOS 12.3

Steps to Reproduce:

1. Create a comment with some inline `code` blocks and a regular text, e.g. "\`noexcept\` for these 3 \`register\` functions?"

Screen Shot 2022-03-25 at 11 13 50

As you see, the code blocks are way larger than the regular text.

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #146183

### CODE REVIEW

**Comment by alexr00** [comment]
@mjbvz, in the comments widget we use the markdown renderer to render the comment body. The markdown renderer does a nice job applying the editors font properties in codeblocks, but in the comment widget, where the font size is 13px by default, it results in a font size that is slightly larger than the surrounding non-codeblock text. Is this an ok way to solve this from the perspective of the markdown renderer?

File: src/vs/editor/contrib/markdownRenderer/browser/markdownRenderer.ts [hunk 1]
```diff
@@ -93,6 +94,10 @@ export class MarkdownRenderer {
 					element.style.fontFamily = this._options.codeBlockFontFamily;
 				}
 
+				if (this._options.codeBlockFontSize !== undefined) {
+					element.style.fontSize = this._options.codeBlockFontSize;
```
Comment (mjbvz) [inline src/vs/editor/contrib/markdownRenderer/browser/markdownRenderer.ts:98]: I'd prefer not having the markdown render add styling like this  

Can the comment widget use css to override the default fontSize instead?

Comment (alexr00) [reply src/vs/editor/contrib/markdownRenderer/browser/markdownRenderer.ts:98]: @mjbvz I've switched over to a css approach instead now.

Comment (mjbvz) [reply src/vs/editor/contrib/markdownRenderer/browser/markdownRenderer.ts]: Sorry if I'm being stupid here, but I don't understand why the markdown renderer needs to be modifiered. Can the review widget add the required css / classes instead of having the markdown renderer do it?

Comment (alexr00) [reply src/vs/editor/contrib/markdownRenderer/browser/markdownRenderer.ts]: The problem I see is this line:

https://github.com/microsoft/vscode/blob/92bf104b5294d976c0fcfbdc69e43ba70208b6e8/src/vs/editor/contrib/markdownRenderer/browser/markdownRenderer.ts#L91-L92

It add styles directly to the element, including font size. I'm not a css expert, but my understanding is that styles added to an element get precedence and you cannot override them.

Comment (mjbvz) [reply src/vs/editor/contrib/markdownRenderer/browser/markdownRenderer.ts]: Ok thanks. I would not expect `codeBlockRenderer` to be invoked for inline code like those that #146183 seems to show. Is the issue with inline code or with actual code blocks?

Comment (alexr00) [reply src/vs/editor/contrib/markdownRenderer/browser/markdownRenderer.ts]: It's an issue with code blocks. I was able to use styles to deal with inline code, but not code blocks. I polled the team and the feedback was that code blocks and inline code should both be the same size as the surrounding non-code text in comments.

File: src/vs/editor/browser/config/domFontInfo.ts [hunk 2]
```diff
@@ -25,3 +25,14 @@ export function applyFontInfo(domNode: FastDomNode<HTMLElement> | HTMLElement, f
 		domNode.style.letterSpacing = fontInfo.letterSpacing + 'px';
 	}
 }
+
+export function applyFontInfoToStyleSheet(styleElement: HTMLStyleElement, cssClass: string, fontInfo: BareFontInfo): void {
+	styleElement.textContent = `.${cssClass} {
```
Comment (mjbvz) [inline src/vs/editor/browser/config/domFontInfo.ts:30]: Can you quickly check that the font info values are sanitized before we use them in the css here? This didn't matter for `applyFontInfo` since we were setting the individual style properties but I'm worried about this cases since we are constructing stylesheet source

File: src/vs/editor/contrib/markdownRenderer/browser/markdownRenderer.ts [hunk 3]
```diff
@@ -23,6 +24,7 @@ export interface IMarkdownRenderResult extends IDisposable {
 export interface IMarkdownRendererOptions {
 	editor?: ICodeEditor;
 	codeBlockFontFamily?: string;
+	additionalClasses?: string[];
```
Comment (mjbvz) [inline src/vs/editor/contrib/markdownRenderer/browser/markdownRenderer.ts:27]: Is `additionalClasses` needed or is this something that callers could add if they need it?

**Review by mjbvz — CHANGES_REQUESTED** [review]
Overall looks good but had two minor questions

File: src/vs/editor/browser/config/domFontInfo.ts (hunk 2 above)
Comment (alexr00) [reply src/vs/editor/browser/config/domFontInfo.ts:30]: Good catch. They are not sanitized and they shouldn't be used this way.

Comment (alexr00) [reply src/vs/editor/browser/config/domFontInfo.ts:30]: Would you be amenable to my original approach that added a `codeBlockFontSize` property to `IMarkdownRendererOptions`?

File: src/vs/editor/contrib/markdownRenderer/browser/markdownRenderer.ts (hunk 1 above)
Comment (alexr00) [reply src/vs/editor/contrib/markdownRenderer/browser/markdownRenderer.ts:98]: Per discussion, I've switched back to the original approach.

**Review by mjbvz — APPROVED** [review]
