### PR TITLE
fix windows quick fixes

### LINKED ISSUE #180721: quick fixes don't work on windows
`startLine` and `endLine` are the same and `offset` is `0` thus no lines are even looked at 🤔

### PR DESCRIPTION
**Pull request by meganrogge**
fix #180721

cc @jooyoungseo this should be ready to test on Windows soon 😄 . here are the ones that are available https://code.visualstudio.com/updates/v1_72#_terminal-quick-fixes

### CODE REVIEW

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 1]
```diff
@@ -491,7 +492,7 @@ export class CommandDetectionCapability implements ICommandDetectionCapability {
 				commandStartLineContent: this._currentCommand.commandStartLineContent,
 				hasOutput: () => !executedMarker?.isDisposed && !endMarker?.isDisposed && !!(executedMarker && endMarker && executedMarker?.line < endMarker!.line),
 				getOutput: () => getOutputForCommand(executedMarker, endMarker, buffer),
-				getOutputMatch: (outputMatcher: ITerminalOutputMatcher) => getOutputMatchForCommand(executedMarker, endMarker, buffer, this._terminal.cols, outputMatcher),
+				getOutputMatch: (outputMatcher: ITerminalOutputMatcher) => getOutputMatchForCommand(isWindows ? this._currentCommand.commandStartMarker : executedMarker, endMarker, buffer, this._terminal.cols, outputMatcher),
```
Comment (meganrogge) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:495]: we adjust the executedMarker on windows due to weirdness with conpty, thus this wasn't working

**Review by bpasero — APPROVED** [review]
