### PR TITLE
Fix interactive window to scroll as output resizes

### LINKED ISSUE #145353: Output from IW is not scrolled to
There is an issue with the IW (might be related to microsoft/vscode-jupyter#9259): the most recent output from commands entered through the interactive prompt is not shown if the windows is filled by previous output.

E.g. in this screencast: the output of `i`, `i*2`, `i/0` is not shown, manual scrolling is thus necessary.

https://user-images.githubusercontent.com/4514040/157456743-2bd74f44-8bf7-4473-b387-0d3b23b4f7c9.mp4

Also happens with the changes from microsoft/vscode-jupyter#9299 applied and `jupyter.alwaysScrollOnNewCell` does not change the behavior

Steps to reproduce:
1) fill IW output with
```
# %%
for i in range(100):
    print(i)
```
2) type something in the interactive prompt

#### Environment data
-   VS Code version: Version: 1.66.0-insider, Commit: 92f4bd7894c3b790d37b1eec3c7fb5e5f8618f70
-   Jupyter Extension version (available under the Extensions sidebar): v2022.3.1000691006
-   Python Extension version (available under the Extensions sidebar): v2022.3.10681004
-   OS:  Linux x64 5.4.0-102-generic
-   Python and/or Anaconda version: 3.8.10
-   Type of virtual environment used: venv
-   Jupyter server running: Local

### PR DESCRIPTION
**Pull request by rchiodo**
This PR fixes #145353 

Track output size in the notebook and fire off a debounced message whenever the output resizes

In the IW track this event to force scrolling.

### CODE REVIEW

File: src/vs/workbench/contrib/interactive/browser/interactive.contribution.ts [hunk 1]
```diff
@@ -711,3 +713,17 @@ registerThemingParticipant((theme) => {
...
+
+Registry.as<IConfigurationRegistry>(ConfigurationExtensions.Configuration).registerConfiguration({
+	id: 'notebook',
+	order: 100,
+	type: 'object',
+	'properties': {
+		[NotebookSetting.interactiveWindowAlwaysScrollOnNewCell]: {
+			type: 'boolean',
+			default: true,
+			markdownDescription: localize('interactiveWindow.alwaysScrollOnNewCell', "Automatically scroll the interactive window to show the output of the last statement executed. If this value is false, the window will only scroll if the last cell was already the one scrolled to.")
```
Comment (rchiodo) [inline src/vs/workbench/contrib/interactive/browser/interactive.contribution.ts:725]: Text for this came from the jupyter extension setting it's replacing.

File: src/vs/workbench/contrib/interactive/browser/interactiveEditor.ts [hunk 2]
```diff
@@ -511,107 +510,26 @@ export class InteractiveEditor extends EditorPane {
...
 	}
 
-	/**
-	 * - Init state: 0
-	 * - Will cell insertion: check if the last cell is at the bottom, false, stay 0
-	 * 						if true, state 1 (ready for auto reveal)
-	 * - receive a scroll event (scroll even already happened). If the last cell is at bottom, false, 0, true, state 1
-	 * - height change of the last cell, if state 0, do nothing, if state 1, scroll the last cell fully into view
-	 */
-	#registerExecutionScrollListener(widget: NotebookEditorWidget & IActiveNotebookEditorDelegate) {
```
Comment (rchiodo) [inline src/vs/workbench/contrib/interactive/browser/interactiveEditor.ts:534]: We don't need this tracking anymore as the resize and execute event are all that's necessary.

File: src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts [hunk 3]
```diff
@@ -1799,6 +1829,7 @@ async function webviewPreloads(ctx: PreloadContext) {
 	class OutputCell {
 
 		public readonly element: HTMLElement;
+		public readonly bottomElement: HTMLElement;
```
Comment (rchiodo) [inline src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts:1832]: Actually I don't need this change. Leftover from another idea I was trying out. I'll revert it.

File: src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts [hunk 4]
```diff
@@ -1566,6 +1578,24 @@ async function webviewPreloads(ctx: PreloadContext) {
...
+			// 250 ms. Don't need resize events that often.
+			clearTimeout(this._outputResizeTimer);
+			this._outputResizeTimer = setTimeout(() => {
+				postNotebookMessage('outputResized', {
+					cellId
+				});
+			}, 250);
+		}
+
+		private trackOutputResize(cellId: string, outputContainer: HTMLElement) {
```
Comment (rebornix) [inline src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts:1593]: Is this a duplicate of https://github.dev/rchiodo/vscode/blob/21e64f84458090e52aede145202c9940ae21172c/src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts#L2021-L2022 ?

File: src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts [hunk 5]
```diff
@@ -66,6 +67,7 @@ export interface INotebookDelegateForWebview {
 	focusNotebookCell(cell: IGenericCellViewModel, focus: 'editor' | 'container' | 'output', options?: IFocusNotebookCellOptions): Promise<void>;
 	toggleNotebookCellSelection(cell: IGenericCellViewModel, selectFromPrevious: boolean): void;
 	getCellByInfo(cellInfo: ICommonCellInfo): IGenericCellViewModel;
+	getCellByHandle(cellHandle: number): IGenericCellViewModel | undefined;
```
Comment (rebornix) [inline src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts:70]: `getCellByHandle` is not used anymore it seems.

File: src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts [hunk 6]
```diff
@@ -1817,6 +1846,7 @@ async function webviewPreloads(ctx: PreloadContext) {
 			container.appendChild(this.element);
 			this.element = this.element;
 
+
```
Comment (rebornix) [inline src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts:1849]: nit: empty line

File: src/vs/workbench/contrib/interactive/browser/interactiveEditor.ts (hunk 2 above)
Comment (rebornix) [reply src/vs/workbench/contrib/interactive/browser/interactiveEditor.ts:534]: :clap:

**Review by rebornix — CHANGES_REQUESTED** [review]
It looks great in overall, only question is if we are duplicating the resize observer, hens not approving yet.

File: extensions/vscode-api-tests/src/singlefolder-tests/notebook.test.ts [hunk 7]
```diff
@@ -59,8 +65,9 @@ class Kernel {
 		// create a single output with exec order 1 and output is plain/text
 		// of either the cell itself or (iff empty) the cell's document's uri
 		const task = this.controller.createNotebookCellExecution(cell);
-		task.start();
+		task.start(Date.now());
 		task.executionOrder = 1;
+		await sleep(10); // Force to be take some time
```
[the remark this answers is not in the document]
Comment (rchiodo) [reply extensions/vscode-api-tests/src/singlefolder-tests/notebook.test.ts:70]: Not required, makes the test behave more like a real world execution.

File: src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts (hunk 5 above)
Comment (rchiodo) [reply src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts:70]: I'm not sure why you're saying that? It's used here:
https://github.com/rchiodo/vscode/blob/e2816721e14e8e69affdd0334690e66bd7266e64/src/vs/workbench/contrib/interactive/browser/interactiveEditor.ts#L152

File: src/vs/workbench/contrib/interactive/browser/interactiveEditor.ts [hunk 8]
```diff
@@ -154,6 +148,12 @@ export class InteractiveEditor extends EditorPane {
 
 		codeEditorService.registerDecorationType('interactive-decoration', DECORATION_KEY, {});
 		this._register(this.#keybindingService.onDidUpdateKeybindings(this.#updateInputDecoration, this));
+		this._register(this.#notebookExecutionStateService.onDidChangeCellExecution((e) => {
+			const cell = this.#notebookWidget.value?.getCellByHandle(e.cellHandle);
```
Comment (rchiodo) [inline src/vs/workbench/contrib/interactive/browser/interactiveEditor.ts:152]: This is where getCellByHandle is necessary. The cellExecution change event only has the cell handle for finding the cell.

File: extensions/vscode-api-tests/src/singlefolder-tests/notebook.test.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (rchiodo) [reply extensions/vscode-api-tests/src/singlefolder-tests/notebook.test.ts:70]: I can remove it, the test will still pass, but I thought it made tests more likely to behave like real world execution - so more like testing the real thing.

File: src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts (hunk 4 above)
Comment (rchiodo) [reply src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts:1593]: It might be repurposed to do this as well as what it was already doing though. I could try that and see if it works too

**Review by amunger — DISMISSED** [review]

File: src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts (hunk 5 above)
Comment (rebornix) [reply src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts:70]: I mean it's not used in the webview code, so we don't need to declare it on `INotebookDelegateForWebview`, which is only used in webview.

Comment (rchiodo) [reply src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts:70]: Ah, I see now. Will remove.

File: src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts (hunk 4 above)
Comment (rchiodo) [reply src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts]: Looks like that works too, please have another look.

**Review by rebornix — APPROVED** [review]
