### PR TITLE
This will look for Visual Studio in the Correct directory.

### LINKED ISSUE #143478: Error Code during yarn install "*** Invalid C/C++ Compiler Toolchain. Please check https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites."
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Developement Build
- OS Version: Windows 11 Home

Steps to Reproduce:

1. Clone the vscode repo from main branch
2. run yarn install
3. if you have visual studio 2019 or 17 it will work but not for 2022 as 2022 is installed in ProgramFiles folder not in ProgramFilesx86

### PR DESCRIPTION
**Pull request by ghost**
### Previously  running yarn install was looking for visual studio workload in the programfilesx86 folder now this fix will check for visual studio in the programfilesx86 in the first and then will look on programFiles folder. 

This fix will help Visual Studio 2022 users as it is a 64b bit software so it goes to programFiles folder not in ProgramFilesx86.

This PR fixes #143478

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
I have checked the code and it works in my case

**Comment by samarmohan** [comment]
I've tried this before, and the `preinstall.js` code works fine, but Electron and `node-gyp` don't like the 64 bit version.
There was an issue regarding this a while ago but I can't find it.

**Comment by samarmohan** [comment]
Ah well, I was behind on this issue. https://github.com/microsoft/vscode/issues/138572 and https://github.com/microsoft/vscode/pull/142667

**Comment by rounaksingh557** [comment]
Yaa this will actually fix the issue and the next time no other will have the same issue. Just waiting for the maintainer to merge this pr

**Comment by rounaksingh557** [comment]
I tested the code and it worked totally fine. Let's see when the maintainer merges this pr.

**Comment by rounaksingh557** [comment]
After this fix the issue will completely resolve.

**Comment by rounaksingh557** [comment]
@paulacamargo25 please approve all the pending workflow.

**Comment by rounaksingh557** [comment]
@paulacamargo25 if there's something wrong in the code please let me know.

File: build/npm/preinstall.js [hunk 1]
```diff
@@ -63,13 +63,24 @@ function hasSupportedVisualStudioVersion() {
...
+
 		if (programFiles86Path) {
 			vsPath = `${programFiles86Path}/Microsoft Visual Studio/${version}`;
 			const vsTypes = ['Enterprise', 'Professional', 'Community', 'Preview', 'BuildTools'];
 			if (vsTypes.some(vsType => fs.existsSync(path.join(vsPath, vsType)))) {
 				availableVersions.push(version);
 				break;
 			}
+
+			else if (programFiles64Path) {
```
Comment (rzhao271) [inline build/npm/preinstall.js:76]: Can this be an additional if case outside of the `if (programFiles86Path)` block, rather than an else-if here? Also, the body can be refactored into a separate function, considering how they're doing the same thing, just that one case uses `programFiles86Path` and the other uses `programFiles64Path`.

Comment (samarmohan) [reply build/npm/preinstall.js:76]: We could check for programFiles64Path before we check for the 86 one because it should use VS2022 by default.

Comment (rounaksingh557) [reply build/npm/preinstall.js:76]: > Can this be an additional if case outside of the `if (programFiles86Path)` block, rather than an else-if here? Also, the body can be refactored into a separate function, considering how they're doing the same thing, just that one case uses `programFiles86Path` and the other uses `programFiles64Path`.

Hmmm..  I think this will be more better.. working on it.

Comment (rounaksingh557) [reply build/npm/preinstall.js:76]: ### I tested the code and it worked fine.

```js 

		if (programFiles64Path) {
			vsPath = `${programFiles64Path}/Microsoft Visual Studio/${version}`;
			const vsTypes = ['Enterprise', 'Professional', 'Community', 'Preview', 'BuildTools'];
			if (vsTypes.some(vsType => fs.existsSync(path.join(vsPath, vsType)))) {
				availableVersions.push(version);
				break;
			}
		}

		if (programFiles86Path) {
			vsPath = `${programFiles86Path}/Microsoft Visual Studio/${version}`;
			const vsTypes = ['Enterprise', 'Professional', 'Community', 'Preview', 'BuildTools'];
			if (vsTypes.some(vsType => fs.existsSync(path.join(vsPath, vsType)))) {
				availableVersions.push(version);
				break;
			}
		}

```

Comment (rounaksingh557) [reply build/npm/preinstall.js:76]: ### inside a functions 
```js 

		function findWhereIsVisualStudio() {
			if (programFiles64Path) {
				vsPath = `${programFiles64Path}/Microsoft Visual Studio/${version}`;
				const vsTypes = ['Enterprise', 'Professional', 'Community', 'Preview', 'BuildTools'];
				if (vsTypes.some(vsType => fs.existsSync(path.join(vsPath, vsType)))) {
					availableVersions.push(version);
				}
			}

			if (programFiles86Path) {
				vsPath = `${programFiles86Path}/Microsoft Visual Studio/${version}`;
				const vsTypes = ['Enterprise', 'Professional', 'Community', 'Preview', 'BuildTools'];
				if (vsTypes.some(vsType => fs.existsSync(path.join(vsPath, vsType)))) {
					availableVersions.push(version);
				}
			}
		}
```

Comment (rounaksingh557) [reply build/npm/preinstall.js:76]: @rzhao271 shall I update the code in this way

Comment (rounaksingh557) [reply build/npm/preinstall.js:76]: removed the break statement

Comment (rzhao271) [reply build/npm/preinstall.js:76]: I prefer the one where you don't move it out into a function.
We want to keep the break statements.

**Comment by rzhao271** [comment]
It is currently endgame/testing week. PR LGTM, but I plan on merging it next week.

**Comment by rounaksingh557** [comment]
No issues. Waiting for the endgame to end.

**Review by deepak1556 — APPROVED** [review]

**Comment by deepak1556** [comment]
Merging to address build failure https://github.com/microsoft/vscode/runs/5352655839?check_suite_focus=true

**Comment by deepak1556** [comment]
Thanks for the PR!
