### PR TITLE
Simplify terminal chat layout, fix width of content

### LINKED ISSUE #207488: Terminal chat is not wide enough
All content is squished:

image

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #207488
Screenshot 2024-03-15 at 2 34 52 PM

### CODE REVIEW

File: src/vs/workbench/contrib/terminalContrib/chat/browser/terminalChatWidget.ts [hunk 1]
```diff
@@ -54,73 +56,80 @@ export class TerminalChatWidget extends Disposable {
...
-		const terminalWidth = this._instance.domElement.clientWidth;
-		if (terminalWidth && terminalWidth < 640) {
-			this._inlineChatWidget.layout(new Dimension(terminalWidth - widgetWidthMargin, this._inlineChatWidget.getHeight()));
-		}
+		return this._terminalElement.clientHeight;
+		// const font = this._instance.xterm?.getFont();
+		// if (!font?.charHeight) {
+		// 	return;
+		// }
+		// return font.charHeight * font.lineHeight * this._instance.rows;
```
Comment (taufiksoleh) [inline src/vs/workbench/contrib/terminalContrib/chat/browser/terminalChatWidget.ts:132]: just delete it , if unused

**Review by alexdima — APPROVED** [review]
