### PR TITLE
Log correct tsserver path

### LINKED ISSUE #173707: [Object object] logged for TS Server log path
Type: <b>Bug</b>

1. `"typescript.tsserver.log": "verbose"`
2. Open `TypeScript` output 

**Bug**
See

```
[Info - 16:53:07.990] <syntax> Log file: [object Object]
```

The `open TS Server log command` still works

VS Code version: Code - Insiders 1.76.0-insider (Universal) (25514d899f4bd877803defb213719f8af3d997d3, 2023-02-07T05:23:26.688Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|9, 8, 5|
|Memory (System)|32.00GB (0.39GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #173707

We previously converted the TS Server log from a simple string to an object. However there were a few cases where this object was incorrectly being converted into a UI string, resulting in `[Object object]`

### CODE REVIEW

File: extensions/typescript-language-features/src/tsServer/spawner.ts [hunk 1]
```diff
@@ -142,12 +142,12 @@ export class TypeScriptServerSpawner {
 		const { args, tsServerLog, tsServerTraceDirectory } = this.getTsServerArgs(kind, configuration, version, apiVersion, pluginManager, canceller.cancellationPipeName);
 
 		if (TypeScriptServerSpawner.isLoggingEnabled(configuration)) {
-			if (!isWeb()) {
```
Comment (mjbvz) [inline extensions/typescript-language-features/src/tsServer/spawner.ts:145]: This check isn't needed anymore. On web we use the `output` channel for logging

**Review by joyceerhl — APPROVED** [review]
