### PR TITLE
Adopt registerWorkbenchContribution2 for welcome page

### LINKED ISSUE #193623: `onStartupFinished` activation event has no criteria for startup finishing
Does this issue occur when all extensions are disabled?: No - relates to plugin activation.

- VS Code Version: 1.81.1 (server)
- OS Version: Ubuntu frontend, Windows frontend

Steps to Reproduce:

1. I have a plugin that uses the `onStartupFinished` activation event and launches a walkthrough as part of its activation using the command `workbench.action.openWalkthrough`.
2. When run with VSCode Server, this will occasionally cause an error like this to appear:

image

It seems that what must be happening is that the plugin is executing its command before [this code](https://github.com/microsoft/vscode/blob/b635d3d6ae3ddcc1c7a034d02fab47914aaf0ec2/src/vs/workbench/contrib/welcomeGettingStarted/browser/startupPage.ts#L58) is run to register the URI handling for the special URI that [the command opens](https://github.com/microsoft/vscode/blob/b635d3d6ae3ddcc1c7a034d02fab47914aaf0ec2/src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.contribution.ts#L75-L113). That raises a question about the `onStartupFinished` activation event. I would consider startup to be finished only when all `IWorkbenchContributions` have been instantiated, but that condition doesn't seem to be enforced. The error is more frequent when the window in which the editor is running is in the background, presumably because it's allocated fewer resources and getting through fewer of the `requestIdleCallback`s that the application activation sequence runs through before the backend declares (unilaterally?) that startup has finished - in fact, it will just declare victory [after 10 seconds](https://github.com/microsoft/vscode/blob/b635d3d6ae3ddcc1c7a034d02fab47914aaf0ec2/src/vs/workbench/api/common/extHostExtensionService.ts#L666), even if the other (exclusively backend?) events it's waiting for don't complete.

### PR DESCRIPTION
**Pull request by bhavyaus**
Also fixes: https://github.com/microsoft/vscode/issues/193623 

There are two scenarios to consider here for the GettingStartedInput editor type:

1. The startup editor (welcome page) is opened automatically if workbench.startupEditor setting is enabled by the user or on first launch for new users.

1. OpenWalkthrough command is invoked on Activation as described by the user here https://github.com/microsoft/vscode/issues/193623

`StartupPageRunnerContribution` with `WorkbenchPhase.AfterRestored`  supports Scenario 1
`StartupPageEditorResolverContribution` with `WorkbenchPhase.BlockRestore`  supports Scenario 2 by ensuring the editorResolver has time to register the input type.

### CODE REVIEW

**Comment by bpasero** [comment]
@bhavyaus thanks! This should be good to go: the editor resolver code still needs to run very early to register the editor. Only the `run` part can then use the new mechanism, please have a look and also see if it resolves the initial issue.

**Review by bpasero — APPROVED** [review]

**Review by bpasero — CHANGES_REQUESTED** [review]
~I do not understand the revert of the changes.~

Sorry, had forgotten to push.

**Comment by bpasero** [comment]
@bhavyaus with my commit, it should work. the editor resolver needs to be there on startup for the editor to actually load.

File: src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.contribution.ts [hunk 1]
```diff
@@ -62,13 +61,16 @@ registerAction2(class extends Action2 {
 		if (walkthroughID) {
 			const selectedCategory = typeof walkthroughID === 'string' ? walkthroughID : walkthroughID.category;
 			const selectedStep = typeof walkthroughID === 'string' ? undefined : walkthroughID.step;
+			const editor = instantiationService.createInstance(GettingStartedInput,
```
Comment (bpasero) [inline src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.contribution.ts:64]: This seems not needed and should go back to how it was now that the resolver is contributed on startup.

**Review by bpasero — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.contribution.ts [hunk 2]
```diff
@@ -339,5 +338,6 @@ configurationRegistry.registerConfiguration({
 	}
 });
 
-Registry.as<IWorkbenchContributionsRegistry>(WorkbenchExtensions.Workbench)
-	.registerWorkbenchContribution(StartupPageContribution, LifecyclePhase.Restored);
+registerWorkbenchContribution2(WorkspacePlatformContribution.ID, WorkspacePlatformContribution, WorkbenchPhase.AfterRestored);
+registerWorkbenchContribution2(StartupPageEditorResolverContribution.ID, StartupPageEditorResolverContribution, WorkbenchPhase.BlockRestore);
+registerWorkbenchContribution2(StartupPageRunnerContribution.ID, StartupPageRunnerContribution, WorkbenchPhase.AfterRestored);
```
Comment (bpasero) [inline src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.contribution.ts:343]: Can we leave it to run based on `editorId`, that should work, no?

File: src/vs/workbench/contrib/welcomeGettingStarted/browser/startupPage.ts [hunk 3]
```diff
@@ -79,12 +68,35 @@ export class StartupPageContribution implements IWorkbenchContribution {
...
+		@IStorageService private readonly storageService: IStorageService,
+		@ILogService private readonly logService: ILogService,
+		@INotificationService private readonly notificationService: INotificationService
+	) {
 		this.run().then(undefined, onUnexpectedError);
 	}
 
 	private async run() {
 
+		await this.lifecycleService.when(LifecyclePhase.Restored);
```
Comment (bpasero) [inline src/vs/workbench/contrib/welcomeGettingStarted/browser/startupPage.ts:98]: Maybe for the future, add a comment as to why that is needed.

**Review by bpasero — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/welcomeGettingStarted/browser/startupPage.ts (hunk 3 above)
Comment (bhavyaus) [reply src/vs/workbench/contrib/welcomeGettingStarted/browser/startupPage.ts:99]: Was just pushing my comment commit :)

File: src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.contribution.ts (hunk 2 above)
Comment (bhavyaus) [reply src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.contribution.ts:343]: No. If no welcome page is opened before restore (example via OpenWalkthrough command), we need the Restored phase to trigger the StartupPageRunnerContribution to be instantiated so that the `workbench.startupEditor` can be setup correctly.

Comment (bpasero) [reply src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.contribution.ts:343]: But are we still fixing https://github.com/microsoft/vscode/issues/193623 then?

Comment (bpasero) [reply src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.contribution.ts:343]: Oh I see, its fixed due to the resolver.

**Review by bpasero — APPROVED** [review]

**Review by aiday-mar — APPROVED** [review]
