### PR TITLE
wait until extension is installed - if it is taking longer. Fix #245396

### LINKED ISSUE #245396: Smoke test failure
```
  1) VSCode Smoke Tests (Electron)
       Extensions
         install and enable vscode-smoketest-check extension:
     Error: Timeout: click 'div.extensions-viewlet[id="workbench.view.extensions"] .monaco-list-row[data-extension-id="ms-vscode.vscode-smoketest-check"] .extension-list-item .monaco-action-bar .action-item:not(.disabled) .extension-action.install' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/out/code.js:208:23)
      at async Code.waitAndClick (/Users/runner/work/1/s/test/automation/out/code.js:155:9)
      at async Extensions.installExtension (/Users/runner/work/1/s/test/automation/out/extensions.js:53:13)
      at async Context.<anonymous> (out/areas/extensions/extensions.test.js:18:13)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=329448&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=ecad4960-5379-5108-563e-8a65e2414e29

### PR DESCRIPTION
**Pull request by sandy081**
Fix #245396

### CODE REVIEW

**Review by bpasero — APPROVED** [review]

File: test/automation/src/extensions.ts [hunk 1]
```diff
@@ -72,6 +72,25 @@ export class Extensions extends Viewlet {
...
+
+	private async waitForExtensionToBeInstalled(): Promise<void> {
+		let attempt = 1;
+		while (true) {
+			try {
+				await this.code.waitForElement(`.extension-editor .monaco-action-bar .action-item:not(.disabled) .extension-action.uninstall`, undefined);
+				break;
+			} catch (err) {
+				if (await this.code.getElement(`.extension-editor .monaco-action-bar .action-item .extension-action.install.installing`)) {
+					if (attempt++ === 3) {
```
Comment (bpasero) [inline test/automation/src/extensions.ts:84]: There already is a `if (attempt++ === 3) {` in the calling code though :thinking:

**Review by sandy081 — COMMENTED** [review]
Yeah, they are two different attempts. New one is to wait longer if an extension installation goes for long time.

File: test/automation/src/extensions.ts (hunk 1 above)
Comment (sandy081) [reply test/automation/src/extensions.ts:84]: Yeah, they are two different attempts. New one is to wait longer if an extension installation goes for long time.
