### PR TITLE
Fixes image name including # fail to render

### LINKED ISSUE #84197: image name include # cause fail render
## Env:
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

## Steps to Reproduce:

image

Does this issue occur when all extensions are disabled?: Yes/No
Yes

### PR DESCRIPTION
**Pull request by jeanp413**
This PR fixes #84197

### CODE REVIEW

File: src/vs/workbench/contrib/webview/common/resourceLoader.ts [hunk 1]
```diff
@@ -83,7 +83,7 @@ function normalizeRequestPath(requestUri: URI) {
 
 	// Modern vscode-resources uris put the scheme of the requested resource as the authority
 	if (requestUri.authority) {
-		return URI.parse(requestUri.authority + ':' + requestUri.path);
+		return URI.parse(requestUri.authority + ':' + encodeURIComponent(requestUri.path).replace(/%2F/g, '/'));
```
Comment (mjbvz) [inline src/vs/workbench/contrib/webview/common/resourceLoader.ts]: Which operating system did you test this on. The change looks good but I'm not sure if it will work on windows

Comment (jeanp413) [reply src/vs/workbench/contrib/webview/common/resourceLoader.ts]: Ubuntu 18.04

Comment (mjbvz) [reply src/vs/workbench/contrib/webview/common/resourceLoader.ts]: What happens for windows style paths though (ones that use `\`)?

Comment (jeanp413) [reply src/vs/workbench/contrib/webview/common/resourceLoader.ts]: I don't have a windows VM at hand to be able to build from sources and test it but looking at the uri.ts file it seems that `\` characters are converted to `/` before constructing the uri object
https://github.com/microsoft/vscode/blob/ab147f8b8e2af23fd61385b563c246847bc50f2b/src/vs/base/common/uri.ts#L306-L308

and converted back again with the [fsPath getter](https://github.com/microsoft/vscode/blob/ab147f8b8e2af23fd61385b563c246847bc50f2b/src/vs/base/common/uri.ts#L201)

**Comment by jeanp413** [comment]
@mjbvz I tested this today and seems that #84667 broke this again.
I tested both PRs separately and they fix both issues (#84197 and #83165) so you need to revert one of them.
The issue is that URI.parse is called twice [here](https://github.com/microsoft/vscode/blob/9e899b556f10f09217239396af8ee95009612982/src/vs/workbench/contrib/webview/electron-browser/webviewProtocols.ts#L19) and [here](https://github.com/microsoft/vscode/blob/9e899b556f10f09217239396af8ee95009612982/src/vs/workbench/contrib/webview/common/resourceLoader.ts#L87)

- #84667 fixes it by encoding the uri twice in the extension so a filename `#.png` will be encoded as `"vscode-resource://file///home/jeanpierre/Desktop/vstest/%2523.png?version=1574091136161"` (notice `%23` is encoded as `%2523`)
- This PR fixes just by encoding the path again before calling URI.parse the second time
