### PR TITLE
Fix markdown setting scope links

### LINKED ISSUE #272118: `(Modified elsewhere)` tool-tip in `Settings` no longer links to modified scopes
Type: <b>Bug</b>

1. Open VS Code and go to Settings (File > Preferences > Settings or press Ctrl+,).
2. Search for the setting
```
"editor.defaultFormatter"
```
3. If the setting is modified by another source (e.g., workspace settings, a remote settings sync, or an extension), you should see the label
```
"(Modified elsewhere)"
```
next to the setting.

4. Hover your mouse over the `(Modified elsewhere)` label to open the tool-tip/pop-up that lists where the setting is modified (for example, workspace settings, folder settings, or extension-provided settings).
5. Observe the tool-tip content: previously, clickable hyperlinks in this pop-up navigated directly to the referenced settings (for example, clicking a workspace or extension entry opened that settings file/section).

Now, the tool-tip shows the same descriptive entries but without the useful links.

VS Code version: Code 1.105.1 (7d842fb85a0275a4a8e4d7e040d2625abbf7f084, 2025-10-14T22:33:36.618Z)
OS version: Linux x64 6.14.0-33-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4500)|
|GPU Status|2d_canvas: enabled<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>trees_in_viz: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|3, 3, 2|
|Memory (System)|31.28GB (15.38GB free)|
|Process Argv|--crash-reporter-id 9746525a-a815-4ecc-8c8a-eb4404b733be|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
binariesv615:30325510
vscrp:30673768
nativeloc1:31344060
dwcopilot:31170013
dwoutputs:31242946
copilot_t_ci:31333650
e5gg6876:31282496
pythonrdcb7:31342333
aj953862:31281341
82j33506:31327384
nes-set-on:31340697
63221493:31336333
envsactivate1:31353494
aa_t:31379598
gendocstringf:31395206
0574c672:31404437
cloudbuttont:31379625
todos-0:31390406
qwen_all_req:31402696
treatment_gpt5applypatchexclusively:31398171
42190218_ostrepl:31403339
nes-auto-10:31401735
jgh7f366:31402811
trigger-command-fix:31379601
auto_model_enabled:31385282
use-responses-api:31390855
applesignin:31399435
anonusage:31403420
dcggh915:31402680
nes-subseq-delay-0:31400949
je187915:31401254

```

</details>

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #272118

Lets markdown strings use internal uris for links that should be handled entirely by the action handler instead of the opener. Uses this to support setting scope links

### CODE REVIEW

File: src/vs/workbench/contrib/preferences/browser/settingsEditorSettingIndicators.ts [hunk 1]
```diff
@@ -505,7 +507,7 @@ export class SettingsTreeIndicatorsLabel implements IDisposable {
 
 			let defaultOverrideHoverContent;
 			if (!Array.isArray(sourceToDisplay)) {
-				defaultOverrideHoverContent = localize('defaultOverriddenDetails', "Default setting value overridden by `{0}`", sourceToDisplay);
+				defaultOverrideHoverContent = localize('defaultOverriddenDetails', "Default setting value overridden by `{ 0 } `", sourceToDisplay);
```
[the remark this answers is not in the document]
Comment (rzhao271) [reply src/vs/workbench/contrib/preferences/browser/settingsEditorSettingIndicators.ts]: @mjbvz any reason for the extra spacing here?

File: src/vs/workbench/contrib/preferences/browser/settingsEditorSettingIndicators.ts [hunk 2]
```diff
@@ -478,7 +480,7 @@ export class SettingsTreeIndicatorsLabel implements IDisposable {
 					...this.defaultHoverOptions,
 					content,
 					linkHandler: (url: string) => {
-						const [scope, language] = decodeURIComponent(url).split(':');
+						const [scope, language] = SettingScopeLink.parse(url)?.split(':');
```
Comment (rzhao271) [inline src/vs/workbench/contrib/preferences/browser/settingsEditorSettingIndicators.ts]: The question mark implies the return type might be undefined but there's no null checks after.

**Review by rzhao271 — DISMISSED** [review]
+1 to Copilot's concerns.

File: src/vs/workbench/contrib/preferences/browser/settingsEditorSettingIndicators.ts (hunk 2 above)
Comment (mjbvz) [reply src/vs/workbench/contrib/preferences/browser/settingsEditorSettingIndicators.ts]: Types are right (not null) but looks like there's an extra `?`

```suggestion
						const [scope, language] = SettingScopeLink.parse(url).split(':');
```

**Review by rebornix — APPROVED** [review]
