### PR TITLE
Disable variable line heights in diff editors

### LINKED ISSUE #248487: Incorrect alignment of variable line heights in diff editor
Side by side diff editor should synchronize line heights across the two editors to maintain diff alignment

### PR DESCRIPTION
**Pull request by aiday-mar**
fixes https://github.com/microsoft/vscode/issues/248487

### CODE REVIEW

File: src/vs/editor/common/config/editorOptions.ts [hunk 1]
```diff
@@ -5975,6 +5980,9 @@ export const EditorOptions = {
 	inDiffEditor: register(new EditorBooleanOption(
 		EditorOption.inDiffEditor, 'inDiffEditor', false
 	)),
+	allowVariableLineHeights: register(new EditorBooleanOption(
```
Comment (alexdima) [inline src/vs/editor/common/config/editorOptions.ts:5983]: Could we also place this between `accessibilityPageSize` and `ariaLabel` to maintain that these are sorted?

**Review by alexdima — CHANGES_REQUESTED** [review]
Small nit: please move the option implementation in the correct place to maintain alphabetical sorting.

File: src/vs/editor/common/config/editorOptions.ts (hunk 1 above)
Comment (aiday-mar) [reply src/vs/editor/common/config/editorOptions.ts:5983]: I think the IEditorOptions, the `accessibilityPageSize ` is currently lower placed than the `ariaLabel`, ie: the interface is currently not sorted correctly.

**Review by alexdima — DISMISSED** [review]
Looks good! But there is now a CI error due to monaco.d.ts being no longer up-to-date

**Review by lszomoru — APPROVED** [review]
