### PR TITLE
resolve glob tasks in configure default build task

### LINKED ISSUE #191745: tasks.json `isDefault` globs not working in configure default build task quickpick
This was raised before in #184003 but closed for not providing enough detail. I'll try to do better. Possibly historically related, but I really don't know: #173384. This buggy behaviour was raised to my attention on Stack Overflow in https://stackoverflow.com/q/77005448/11107541.

I have tested on Insiders with no non-builtin extensions installed, _and_ on top of that with extensions disabled:

```none
Version: 1.82.0-insider
Commit: ebd67244fb2da33ab078bb2baa96106fda29f336
Date: 2023-08-29T05:32:43.083Z
Electron: 25.5.0
ElectronBuildId: 23084831
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.2.0-26-generic snap
```

Does this issue occur when all extensions are disabled?: Yes. I also tested with a default profile.

- VS Code Version: 1.81.1, 1.82.0-insider
- OS Version: Ubuntu 22.04.2. The Stack Overflow user [here](https://stackoverflow.com/q/77005448/11107541) seems to be on windows judging by the backslash path separators, and #184003 was Windows and WSL.

Steps to Reproduce:

1. Create a new workspace folder.
2. In .vscode/tasks.json:
   ```json
   {
      "version": "2.0.0",
      "tasks": [
         {
            "label": "foo",
            "command": "echo foo",
            "type": "shell",
            "group": {
               "kind": "build",
               "isDefault": "**/*.foo.txt"
            },
         },
         {
            "label": "bar",
            "command": "echo bar",
            "type": "shell",
            "group": {
               "kind": "build",
               "isDefault": "**/*.bar.txt"
            },
         },
      ],
   }
   ```
3. In test.foo.txt: put anything. Ex. "hello world!"
4. In test.bar.txt: put anything. Ex. "hello world!"
5. Open test.foo.txt and run `Tasks: Configure Default Build Task` in the command palette, and observe that it shows the _`bar`_ task (unexpected).
6. Open test.bar.txt and run `Tasks: Configure Default Build Task` in the command palette, and observe that it shows the `bar` task (expected).
7. Now swap the order the task definitions in tasks.json
8. Open test.foo.txt and run `Tasks: Configure Default Build Task` in the command palette, and observe that it shows the `foo` task (expected).
6. test.bar.txt and run `Tasks: Configure Default Build Task` in the command palette, and observe that it shows the _`foo`_ task (unexpected).

### PR DESCRIPTION
**Pull request by meganrogge**
When running `configure default build task`, we didn't resolve glob tasks, so the quick pick would present all as options, not listing the one that was the current default. This has never worked before AFAICT.
 
The fix is to resolve the glob tasks rather than just checking if `task.isDefault` (which can be a `string` in the case of glob tasks), is defined.

fixes #191745

The issue contains good repro steps. I'm following those in the below gif to show that it works now.

https://github.com/microsoft/vscode/assets/29464607/7858f40b-35ff-417d-9900-02a640bab48a

### CODE REVIEW

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 1]
```diff
@@ -3432,10 +3440,25 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
...
+					if (!defaultTasks?.length) {
+						defaultTasks = this._getDefaultTasks(tasks, false);
+					}
+					let defaultBuildTask;
+					if (defaultTasks.length === 1) {
+						const group: string | TaskGroup | undefined = defaultTasks[0].configurationProperties.group;
+						if (group) {
+							if (typeof group === 'string' && group === TaskGroup.Build._id) {
+								defaultBuildTask = defaultTasks[0];
+							} else if ((group as any)._id === TaskGroup.Build._id) {
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:3455]: `group as TaskGroup` did not work here. not sure why

Comment (Tyriar) [reply src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:3455]: Accessing privates like this will fail in production now due to variable mangling

**Review by Tyriar — DISMISSED** [review]
We can't use as any for privates anymore

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:3455]: realized that check is unnecessary bc it's already filtered by group 

https://github.com/microsoft/vscode/blob/8bd293e87deb3d56598657a7b6207adf4e731d12/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L3444

**Review by DonJayamanne — APPROVED** [review]
