### PR TITLE
fix #102289

### LINKED ISSUE #102289: Annoying Editor Selector when New File from File menu
- VSCode Version:  1.47.0
- OS Version: macOS Catalina 10.15.5

Steps to Reproduce:
Every time when I click File -> New File, vscode always asks to select an Editor, but in the list, there is only one Built-in Text editor. it's just a very annoying unnecessary click. 
I don't know since when this has been added, I believe it's a recent change.

Tried to remove all the User settings and start without extensions, didn't help.

See the screenshot. 
Screen Shot 2020-07-12 at 9 35 03 pm

Does this issue occur when all extensions are disabled?: Yes/No
Yes

### PR DESCRIPTION
**Pull request by zcfan**
This PR fixes #102289 by open with the editor if it's the only one available.

To test it in the current master branch, disable the builtin "vscode-notebook-tests" extension and create a new file. It should open the new file without asking for picking editor.

Enable the "vscode-notebook-tests" extension will add two candidates to the editor list, when create new file the picker should show up again.

### CODE REVIEW

File: src/vs/workbench/services/editor/common/editorOpenWith.ts [hunk 1]
```diff
@@ -49,7 +49,12 @@ export async function openEditorWith(
 		return;
 	}
 
-	const overrideToUse = typeof id === 'string' && allEditorOverrides.find(([_, entry]) => entry.id === id);
+	let overrideToUse;
```
Comment (mjbvz) [inline src/vs/workbench/services/editor/common/editorOpenWith.ts:52]: @rebornix Would we ever want to show the reopen with prompt if there is only one override?

**Comment by mjbvz** [comment]
Merging this for insiders. Will see if it causes any issues for other flows, such as reopen with

**Comment by rebornix** [comment]
@mjbvz +1 for this change, showing picker when there is only one view type is weird IMHO. Great work!
