### PR TITLE
Delete breadcrumbs.filterOnType unused setting.

### LINKED ISSUE #75969: Breadcrumbs doesn't filter on type until clicking on the tree TypeFilterController
Steps to Reproduce:

1. Launch or reload vscode 
2. Set `"workbench.list.keyboardNavigation": "filter"`
3. Open a breadcrumb and start typing to filter the contents => contents are not filtered
4. Click two times on the tree TypeFilterController (to deactivate and activate filtering again) on the top right of the breadcrumb.
5. Contents are filtered from now on until reload of vscode.

Related to #55004

breadcrumbsfilter

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes #75969. Maybe #55004 should be closed too.

### CODE REVIEW

**Comment by jrieken** [comment]
Not sure how that relates to #755969

File: src/vs/workbench/browser/parts/editor/breadcrumbsPicker.ts [hunk 1]
```diff
@@ -129,13 +125,6 @@ export abstract class BreadcrumbsPicker {
 			this._layout();
 		}));
 
-		// filter on type: state
-		const cfgFilterOnType = BreadcrumbsConfig.FilterOnType.bindTo(this._configurationService);
-		this._tree.updateOptions({ filterOnType: cfgFilterOnType.getValue() });
```
Comment (jeanp413) [inline src/vs/workbench/browser/parts/editor/breadcrumbsPicker.ts]: This overrides the setting `workbench.list.keyboardNavigation` and because `breadcrumbs.filterOnType` is commented its value is undefined/false, so the BreadcrumbsPicker tree won't filter on type after a launch/reload unless the TypeFilterController widget of the tree is clicked which modifes the `filterOnType` setting

Comment (jrieken) [reply src/vs/workbench/browser/parts/editor/breadcrumbsPicker.ts]: 💡

**Review by jrieken — APPROVED** [review]
