### PR TITLE
Workaround Safari clipboard.writeText behavior

### LINKED ISSUE #106997: Clipboard API doesn’t work on Codespaces (using Safari)
- VSCode Version: Codespaces
- OS Version: MacOS Catalina and iPadOS 13

Steps to Reproduce:

It seems the **Clipboard API** is not working, at least using **Safari**

1. Create an extension using the [Clipboard API](https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-the-clipboard) which as documented, should be used on Remote Development: `env.clipboard.writeText(editor.document.getText(editor.selection));`
2. Open Codespaces and install the extension (My `alefragnani.copy-word` extension does exactly that)
3. Use its command `Copy Word: Copy`, which will select the word where the cursor is located and should copy the selected text to clipboard 
4. Navigate to other location
5. Run `Paste` command (or use `Cmd V` shortcut)
6. Doesn’t work: instead of pasting the the newly selected/copied text, it pastes the previous clipboard content (not created using the extension)

* I tested on iPadOS 13 and MacOS Catalina and it fails.
* I tested on Edge (Chromium) and it works perfectly (I guess it should work on Chrome too)
* I didn’t test on Firefox (yet).

BTW, I tried to debug my extension on Codespaces **(on iPadOS)**, but it seems not possible/supported. I’m able to build the extension and hit the Debug button. The Debug toolbar appears but no `[development ]` window/tab appears. _Is there a way to debug VSCode extensions right from Codespaces?_. 

> As described below, debugging on Desktop (macOS Catalina) works just fine. Safari just _blocks_ the window, but you click the button and the `[development ]` window correctly appears.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
In Safari, it has the following note:

"The request to write to the clipboard must be triggered during a user gesture. A call to clipboard.write or clipboard.writeText outside the scope of a user gesture(such as "click" or "touch" event handlers) will result in the immediate rejection of the promise returned by the API call."

From: https://webkit.org/blog/10855/async-clipboard-api/
	
Since extensions run in a web worker, and handle gestures in an asynchronous way, they are not classified by Safari as "in response to a user gesture" and will reject.

This function sets up some handlers to work around that behavior by leveraging the ClipboardItem API that takes in a Promise:
https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem/ClipboardItem#parameters

This PR fixes #106997

### CODE REVIEW

File: src/vs/workbench/services/clipboard/browser/clipboardService.ts [hunk 1]
```diff
@@ -38,12 +39,6 @@ export class BrowserClipboardService extends BaseBrowserClipboardService {
 				return ''; // do not ask for input in tests (https://github.com/microsoft/vscode/issues/112264)
 			}
 
-			if (isSafari) {
-				this.logService.error(error);
-
-				return ''; // Safari does not seem to provide anyway to enable cipboard access (https://github.com/microsoft/vscode-internalbacklog/issues/2162#issuecomment-852042867)
```
Comment (TylerLeonhardt) [inline src/vs/workbench/services/clipboard/browser/clipboardService.ts:44]: Safari supports readText now so this does work now.

**Review by jrieken — APPROVED** [review]
