### PR TITLE
fix: don't package detection script in legacy server

### LINKED ISSUE #9577: [Remote-SSH Bug]: ./bin/helpers/check-requirements.sh: not found
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

_No response_

### Expected Behavior

We are making use of three servers, with shared homefolders via NFS. One of the servers connects successfully, the other two give an error 

```
> /home/sumo/lwerthen/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/bin/code-server: 25: ./bin/helpers/check-requireme
> nts.sh: not found
```

### Steps To Reproduce

Connect to host (Remote SSH)

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[16:16:39.997] Log Level: 2
[16:16:40.006] SSH Resolver called for "ssh-remote+sumo-test", attempt 1
[16:16:40.007] "remote.SSH.useLocalServer": false
[16:16:40.007] "remote.SSH.useExecServer": false
[16:16:40.007] "remote.SSH.showLoginTerminal": false
[16:16:40.007] "remote.SSH.remotePlatform": {"sumo-test.intec.ugent.be":"linux","sumo-test":"linux","sumo-ai":"linux","sumo-radar":"linux"}
[16:16:40.007] "remote.SSH.path": undefined
[16:16:40.007] "remote.SSH.configFile": undefined
[16:16:40.007] "remote.SSH.useFlock": true
[16:16:40.008] "remote.SSH.lockfilesInTmp": true
[16:16:40.009] "remote.SSH.localServerDownload": auto
[16:16:40.009] "remote.SSH.remoteServerListenOnSocket": false
[16:16:40.009] "remote.SSH.showLoginTerminal": false
[16:16:40.009] "remote.SSH.defaultExtensions": []
[16:16:40.009] "remote.SSH.loglevel": 2
[16:16:40.009] "remote.SSH.enableDynamicForwarding": true
[16:16:40.009] "remote.SSH.enableRemoteCommand": false
[16:16:40.010] "remote.SSH.serverPickPortsFromRange": {}
[16:16:40.010] "remote.SSH.serverInstallPath": {}
[16:16:40.012] VS Code version: 1.86.2
[16:16:40.012] Remote-SSH version: remote-ssh@0.109.2024021915
[16:16:40.013] win32 x64
[16:16:40.014] SSH Resolver called for host: sumo-test
[16:16:40.014] Setting up SSH remote "sumo-test"
[16:16:40.018] Using commit id "903b1e9d8990623e3d7da1df3d33db3e42d80eda" and quality "stable" for server
[16:16:40.020] Install and start server if needed
[16:16:40.023] Checking ssh with "C:\Program Files\Oculus\Support\oculus-runtime\ssh.exe -V"
[16:16:40.025] Got error from ssh: spawn C:\Program Files\Oculus\Support\oculus-runtime\ssh.exe ENOENT
[16:16:40.025] Checking ssh with "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe -V"
[16:16:40.026] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[16:16:40.027] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin\ssh.exe -V"
[16:16:40.028] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin\ssh.exe ENOENT
[16:16:40.029] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\libnvvp\ssh.exe -V"
[16:16:40.030] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\libnvvp\ssh.exe ENOENT
[16:16:40.030] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\ssh.exe -V"
[16:16:40.031] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\ssh.exe ENOENT
[16:16:40.031] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp\ssh.exe -V"
[16:16:40.032] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp\ssh.exe ENOENT
[16:16:40.032] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[16:16:40.033] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[16:16:40.033] Checking ssh with "C:\Windows\ssh.exe -V"
[16:16:40.034] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[16:16:40.034] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[16:16:40.036] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[16:16:40.036] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[16:16:40.037] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[16:16:40.038] Checking ssh with "C:\Program Files\Intel\WiFi\bin\ssh.exe -V"
[16:16:40.039] Got error from ssh: spawn C:\Program Files\Intel\WiFi\bin\ssh.exe ENOENT
[16:16:40.039] Checking ssh with "C:\Program Files\Common Files\Intel\WirelessCommon\ssh.exe -V"
[16:16:40.040] Got error from ssh: spawn C:\Program Files\Common Files\Intel\WirelessCommon\ssh.exe ENOENT
[16:16:40.040] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[16:16:40.041] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[16:16:40.041] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[16:16:40.042] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[16:16:40.042] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[16:16:40.043] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[16:16:40.043] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[16:16:40.044] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[16:16:40.044] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[16:16:40.076] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[16:16:40.079] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 49918 "sumo-test" bash
[16:16:40.081] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:16:40.338] > ]0;C:\WINDOWS\System32\cmd.exe
[16:16:40.338] Got some output, clearing connection timeout
[16:16:44.534] > 5628c713fd60: running
[16:16:44.612] > Acquiring lock on /run/user/1970/vscode-remote-lock.lwerthen.903b1e9d8990623e3d7
> da1df3d33db3e42d80eda
> Found existing installation at /home/sumo/lwerthen/.vscode-server/bin/903b1e9d89
> 90623e3d7da1df3d33db3e42d80eda...
> Checking /home/sumo/lwerthen/.vscode-server/.903b1e9d8990623e3d7da1df3d33db3e42d
> 80eda.log and /home/sumo/lwerthen/.vscode-server/.903b1e9d8990623e3d7da1df3d33db
> 3e42d80eda.pid for a running server
> Looking for server with pid: 1045550
> Starting VS Code Server... "/home/sumo/lwerthen/.vscode-server/bin/903b1e9d89906
> 23e3d7da1df3d33db3e42d80eda/bin/code-server" --start-server --host=127.0.0.1 --a
> ccept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-le
> vel all   &> "/home/sumo/lwerthen/.vscode-server/.903b1e9d8990623e3d7da1df3d33db
> 3e42d80eda.log" < /dev/null
> The VS Code Server log file is /home/sumo/lwerthen/.vscode-server/.903b1e9d89906
> 23e3d7da1df3d33db3e42d80eda.log
> printenv:
>     SHELL=/bin/bash
>     CONDA_EXE=/home/sumo/lwerthen/miniconda3/bin/conda
>     _CE_M=
>     GPULAB_CERT=/home/sumo/lwerthen/gpulab_cert.pem
>     PWD=/home/sumo/lwerthen
>     LOGNAME=lwerthen
>     XDG_SESSION_TYPE=tty
>     CONDA_PREFIX=/home/sumo/lwerthen/miniconda3
>     MOTD_SHOWN=pam
>     HOME=/home/sumo/lwerthen
>     LANG=en_US.UTF-8
>     CONDA_PROMPT_MODIFIER=(base)
>     VSCODE_AGENT_FOLDER=/home/sumo/lwerthen/.vscode-server
>     SSH_CONNECTION=192.168.124.69 49919 10.10.193.45 22
>     XDG_SESSION_CLASS=user
>     PYTHONPATH=.:/home/sumo/lwerthen/ms_benchmark:
>     _CE_CONDA=
>     USER=lwerthen
>     CONDA_SHLVL=1
>     SHLVL=0
>     XDG_SESSION_ID=39
>     CONDA_PYTHON_EXE=/home/sumo/lwerthen/miniconda3/bin/python
>     LD_LIBRARY_PATH=
>     XDG_RUNTIME_DIR=/run/user/1970
>     SSH_CLIENT=192.168.124.69 49919 22
>     CONDA_DEFAULT_ENV=base
>     PATH=/home/sumo/lwerthen/bin:/home/sumo/lwerthen/miniconda3/bin:/home/sumo/l
> werthen/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/s
> bin:/bin:/usr/games:/usr/local/games:/snap/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1970/bus
>     GPULAB_DEV=False
>     _=/usr/bin/printenv
[16:16:44.627] > 
> Removing old logfile at /home/sumo/lwerthen/.vscode-server/.903b1e9d8990623e3d7d
> a1df3d33db3e42d80eda.log
> Spawned remote server: 1063114
> Waiting for server log...
[16:16:44.643] > 
[16:16:44.658] > Waiting for server log...
[16:16:44.721] > Waiting for server log...
[16:16:44.794] > Waiting for server log...
> Waiting for server log...
[16:16:44.812] > 
> Waiting for server log...
[16:16:44.873] > Waiting for server log...
> Waiting for server log...
[16:16:44.883] > 
> Waiting for server log...
[16:16:44.904] > 
[16:16:44.966] > Waiting for server log...
[16:16:45.027] > Waiting for server log...
> Waiting for server log...
[16:16:45.044] > 
> Waiting for server log...
[16:16:45.107] > Waiting for server log...
> Waiting for server log...
[16:16:45.121] > 
[16:16:45.137] > Waiting for server log...
[16:16:45.184] > Waiting for server log...
[16:16:45.246] > Waiting for server log...
> Waiting for server log...
[16:16:45.261] > 
[16:16:45.323] > Waiting for server log...
> Waiting for server log...
[16:16:45.338] > 
> Waiting for server log...
[16:16:45.354] > 
[16:16:45.385] > Waiting for server log...
[16:16:45.399] > Waiting for server log...
[16:16:45.415] > 
[16:16:45.476] > Waiting for server log...
[16:16:45.537] > Waiting for server log...
> Waiting for server log...
[16:16:45.554] > 
> Waiting for server log...
[16:16:45.616] > Waiting for server log...
> Waiting for server log...
[16:16:45.631] > 
[16:16:45.647] > Waiting for server log...
[16:16:45.709] > Waiting for server log...
[16:16:45.770] > Waiting for server log...
> Waiting for server log...
[16:16:45.786] > 
> Waiting for server log...
[16:16:45.848] > Waiting for server log...
[16:16:45.910] > Waiting for server log...
> Waiting for server log...
[16:16:45.925] > 
> Waiting for server log...
[16:16:45.941] > 
[16:16:45.986] > Waiting for server log...
[16:16:46.049] > Waiting for server log...
> Waiting for server log...
[16:16:46.064] > 
> Waiting for server log...
[16:16:46.079] > 
[16:16:46.125] > Waiting for server log...
> Waiting for server log...
[16:16:46.140] > 
[16:16:46.156] > Waiting for server log...
[16:16:46.218] > Waiting for server log...
[16:16:46.277] > Waiting for server log...
> Waiting for server log...
[16:16:46.295] > 
> Waiting for server log...
[16:16:46.357] > Waiting for server log...
[16:16:46.416] > Waiting for server log...
> Waiting for server log...
[16:16:46.434] > 
> Waiting for server log...
[16:16:46.496] > Waiting for server log...
> Waiting for server log...
[16:16:46.512] > 
[16:16:46.527] > Waiting for server log...
[16:16:46.666] > Waiting for server log...
> Waiting for server log...
[16:16:46.735] > Waiting for server log...
[16:16:46.748] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[16:16:46.767] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> 
[16:16:46.793] > Waiting for server log...
[16:16:46.855] > Waiting for server log...
> Waiting for server log...
[16:16:46.871] > Waiting for server log...
[16:16:46.884] > 
[16:16:46.930] > Waiting for server log...
[16:16:46.992] > Waiting for server log...
> Waiting for server log...
[16:16:47.010] > 
> Waiting for server log...
[16:16:47.070] > Waiting for server log...
[16:16:47.131] > Waiting for server log...
> Waiting for server log...
[16:16:47.139] > 
[16:16:47.147] > Waiting for server log...
[16:16:47.162] > 
[16:16:47.224] > Waiting for server log...
> Waiting for server log...
[16:16:47.240] > 
[16:16:47.255] > Waiting for server log...
[16:16:47.317] > Waiting for server log...
[16:16:47.349] > Waiting for server log...
[16:16:47.363] > Waiting for server log...
[16:16:47.380] > 
[16:16:47.424] > Waiting for server log...
[16:16:47.440] > Waiting for server log...
[16:16:47.456] > Waiting for server log...
[16:16:47.518] > Waiting for server log...
[16:16:47.579] > Waiting for server log...
> Waiting for server log...
[16:16:47.595] > 
> Waiting for server log...
[16:16:47.610] > 
[16:16:47.656] > Waiting for server log...
[16:16:47.715] > Waiting for server log...
> Waiting for server log...
[16:16:47.733] > 
> Waiting for server log...
[16:16:47.795] > Waiting for server log...
[16:16:47.858] > Waiting for server log...
> Waiting for server log...
[16:16:47.873] > Waiting for server log...
[16:16:47.888] > 
[16:16:47.935] > Waiting for server log...
> Waiting for server log...
[16:16:47.951] > 
[16:16:47.966] > Waiting for server log...
[16:16:48.028] > Waiting for server log...
[16:16:48.075] > Waiting for server log...
> Waiting for server log...
[16:16:48.090] > 
[16:16:48.137] > Waiting for server log...
[16:16:48.196] > Waiting for server log...
> Waiting for server log...
[16:16:48.214] > 
> Waiting for server log...
[16:16:48.276] > Waiting for server log...
[16:16:48.338] > Waiting for server log...
> Waiting for server log...
[16:16:48.354] > 
> Waiting for server log...
[16:16:48.371] > 
[16:16:48.415] > Waiting for server log...
> Waiting for server log...
[16:16:48.430] > 
[16:16:48.446] > Waiting for server log...
[16:16:48.477] > Waiting for server log...
[16:16:48.539] > Waiting for server log...
[16:16:48.600] > Waiting for server log...
> Waiting for server log...
[16:16:48.616] > 
> Waiting for server log...
[16:16:48.647] > Waiting for server log...
[16:16:48.724] > Waiting for server log...
> Waiting for server log...
[16:16:48.735] > 
[16:16:48.754] > Waiting for server log...
[16:16:48.816] > Waiting for server log...
[16:16:48.874] > Waiting for server log...
> Waiting for server log...
[16:16:48.894] > 
> Waiting for server log...
[16:16:48.955] > Waiting for server log...
[16:16:49.015] > Waiting for server log...
> Waiting for server log...
[16:16:49.033] > 
> Waiting for server log...
[16:16:49.094] > Waiting for server log...
[16:16:49.156] > Waiting for server log...
> Waiting for server log...
[16:16:49.172] > 
> Waiting for server log...
[16:16:49.234] > Waiting for server log...
> Waiting for server log...
[16:16:49.249] > 
[16:16:49.265] > Waiting for server log...
[16:16:49.327] > Waiting for server log...
[16:16:49.389] > Waiting for server log...
> Waiting for server log...
[16:16:49.404] > Waiting for server log...
[16:16:49.421] > 
[16:16:49.466] > Waiting for server log...
[16:16:49.525] > Waiting for server log...
> Waiting for server log...
[16:16:49.545] > 
> Waiting for server log...
[16:16:49.606] > Waiting for server log...
> Waiting for server log...
[16:16:49.621] > 
[16:16:49.637] > Waiting for server log...
[16:16:49.698] > Waiting for server log...
[16:16:49.759] > Waiting for server log...
> Waiting for server log...
[16:16:49.777] > 
> Waiting for server log...
[16:16:49.837] > Waiting for server log...
[16:16:49.854] > Waiting for server log...
[16:16:49.868] > Waiting for server log...
[16:16:49.944] > Waiting for server log...
[16:16:50.005] > Waiting for server log...
> Waiting for server log...
[16:16:50.023] > 
> Waiting for server log...
[16:16:50.084] > Waiting for server log...
> Waiting for server log...
[16:16:50.100] > 
[16:16:50.116] > Waiting for server log...
[16:16:50.177] > Waiting for server log...
[16:16:50.237] > Waiting for server log...
> Waiting for server log...
[16:16:50.254] > 
> Waiting for server log...
[16:16:50.300] > Waiting for server log...
[16:16:50.363] > Waiting for server log...
> Waiting for server log...
[16:16:50.371] > 
[16:16:50.378] > Waiting for server log...
[16:16:50.393] > 
[16:16:50.456] > Waiting for server log...
[16:16:50.514] > Waiting for server log...
> Waiting for server log...
[16:16:50.532] > 
> Waiting for server log...
[16:16:50.594] > Waiting for server log...
> Waiting for server log...
[16:16:50.610] > 
[16:16:50.627] > Waiting for server log...
[16:16:50.687] > Waiting for server log...
[16:16:50.746] > Waiting for server log...
> Waiting for server log...
[16:16:50.766] > 
> Waiting for server log...
[16:16:50.828] > Waiting for server log...
[16:16:50.888] > Waiting for server log...
> Waiting for server log...
[16:16:50.897] > 
[16:16:50.904] > Waiting for server log...
[16:16:50.921] > 
[16:16:50.981] > Waiting for server log...
> Waiting for server log...
[16:16:50.997] > 
[16:16:51.013] > Waiting for server log...
[16:16:51.073] > Waiting for server log...
[16:16:51.090] > Waiting for server log...
[16:16:51.105] > Waiting for server log...
[16:16:51.182] > Waiting for server log...
[16:16:51.242] > Waiting for server log...
> Waiting for server log...
[16:16:51.260] > 
> Waiting for server log...
[16:16:51.321] > Waiting for server log...
> Waiting for server log...
[16:16:51.338] > 
[16:16:51.354] > Waiting for server log...
[16:16:51.414] > Waiting for server log...
[16:16:51.475] > Waiting for server log...
> Waiting for server log...
[16:16:51.493] > Waiting for server log...
[16:16:51.507] > 
[16:16:51.553] > Waiting for server log...
[16:16:51.613] > Waiting for server log...
> Waiting for server log...
[16:16:51.630] > 
> Waiting for server log...
[16:16:51.693] > Waiting for server log...
> Waiting for server log...
[16:16:51.711] > 
[16:16:51.724] > Waiting for server log...
[16:16:51.787] > Waiting for server log...
[16:16:51.848] > Waiting for server log...
> Waiting for server log...
[16:16:51.860] > 
[16:16:51.879] > Waiting for server log...
[16:16:51.941] > Waiting for server log...
[16:16:51.999] > Waiting for server log...
> Waiting for server log...
[16:16:52.018] > 
> Waiting for server log...
[16:16:52.078] > Waiting for server log...
[16:16:52.141] > Waiting for server log...
> Waiting for server log...
[16:16:52.156] > 
> Waiting for server log...
[16:16:52.171] > 
[16:16:52.217] > Waiting for server log...
> Waiting for server log...
[16:16:52.233] > 
[16:16:52.247] > Waiting for server log...
[16:16:52.307] > Waiting for server log...
[16:16:52.328] > Waiting for server log...
[16:16:52.341] > Waiting for server log...
[16:16:52.418] > Waiting for server log...
> Waiting for server log...
[16:16:52.433] > 
[16:16:52.449] > Waiting for server log...
[16:16:52.511] > Waiting for server log...
[16:16:52.574] > Waiting for server log...
> Waiting for server log...
[16:16:52.588] > 
> Waiting for server log...
[16:16:52.604] > 
[16:16:52.652] > Waiting for server log...
[16:16:52.712] > Waiting for server log...
> Waiting for server log...
[16:16:52.721] > 
[16:16:52.727] > Waiting for server log...
[16:16:52.743] > 
[16:16:52.805] > Waiting for server log...
> Waiting for server log...
[16:16:52.821] > 
[16:16:52.895] > Waiting for server log...
> Waiting for server log...
[16:16:52.912] > 
> Waiting for server log...
[16:16:52.975] > Waiting for server log...
> Waiting for server log...
[16:16:52.991] > 
[16:16:53.006] > Waiting for server log...
[16:16:53.066] > Waiting for server log...
[16:16:53.082] > Waiting for server log...
[16:16:53.097] > Waiting for server log...
[16:16:53.145] > Waiting for server log...
[16:16:53.175] > Waiting for server log...
[16:16:53.237] > Waiting for server log...
[16:16:53.296] > Waiting for server log...
> Waiting for server log...
[16:16:53.314] > 
> Waiting for server log...
[16:16:53.376] > Waiting for server log...
[16:16:53.437] > Waiting for server log...
> Waiting for server log...
[16:16:53.454] > 
> Waiting for server log...
[16:16:53.516] > Waiting for server log...
[16:16:53.574] > Waiting for server log...
> Waiting for server log...
[16:16:53.593] > 
> Waiting for server log...
[16:16:53.638] > Waiting for server log...
[16:16:53.701] > Waiting for server log...
> Waiting for server log...
[16:16:53.716] > 
> Waiting for server log...
[16:16:53.731] > 
[16:16:53.778] > Waiting for server log...
[16:16:53.837] > Waiting for server log...
> Waiting for server log...
[16:16:53.855] > 
> Waiting for server log...
[16:16:53.917] > Waiting for server log...
[16:16:53.979] > Waiting for server log...
> Waiting for server log...
[16:16:53.996] > 
> Waiting for server log...
[16:16:54.010] > 
[16:16:54.056] > Waiting for server log...
> Waiting for server log...
[16:16:54.071] > 
[16:16:54.087] > Waiting for server log...
[16:16:54.149] > Waiting for server log...
[16:16:54.211] > Waiting for server log...
> Waiting for server log...
[16:16:54.227] > 
> Waiting for server log...
[16:16:54.242] > 
[16:16:54.288] > Waiting for server log...
[16:16:54.351] > Waiting for server log...
> Waiting for server log...
[16:16:54.366] > 
> Waiting for server log...
[16:16:54.382] > 
[16:16:54.428] > Waiting for server log...
> Waiting for server log...
[16:16:54.444] > 
[16:16:54.460] > Waiting for server log...
[16:16:54.522] > Waiting for server log...
[16:16:54.584] > Waiting for server log...
> Waiting for server log...
[16:16:54.599] > Waiting for server log...
[16:16:54.614] > 
[16:16:54.660] > Waiting for server log...
[16:16:54.676] > Waiting for server log...
[16:16:54.707] > Waiting for server log...
[16:16:54.768] > Waiting for server log...
[16:16:54.828] > Waiting for server log...
> Waiting for server log...
[16:16:54.846] > 
> Waiting for server log...
[16:16:54.908] > Waiting for server log...
[16:16:54.968] > Waiting for server log...
> Waiting for server log...
[16:16:54.985] > 
> Waiting for server log...
[16:16:55.046] > Waiting for server log...
> Waiting for server log...
[16:16:55.062] > 
[16:16:55.078] > Waiting for server log...
[16:16:55.140] > Waiting for server log...
[16:16:55.200] > Waiting for server log...
> Waiting for server log...
[16:16:55.218] > 
> Waiting for server log...
[16:16:55.263] > Waiting for server log...
[16:16:55.325] > Waiting for server log...
> Waiting for server log...
[16:16:55.334] > 
[16:16:55.341] > Waiting for server log...
[16:16:55.359] > 
[16:16:55.418] > Waiting for server log...
[16:16:55.479] > Waiting for server log...
> Waiting for server log...
[16:16:55.496] > 
> Waiting for server log...
[16:16:55.558] > Waiting for server log...
> Waiting for server log...
[16:16:55.573] > 
[16:16:55.590] > Waiting for server log...
[16:16:55.666] > Waiting for server log...
> Waiting for server log...
[16:16:55.676] > 
> Waiting for server log...
[16:16:55.697] > 
[16:16:55.759] > Waiting for server log...
[16:16:55.821] > Waiting for server log...
> Waiting for server log...
[16:16:55.837] > 
> Waiting for server log...
[16:16:55.899] > Waiting for server log...
> Waiting for server log...
[16:16:55.914] > 
[16:16:55.930] > Waiting for server log...
[16:16:55.993] > Waiting for server log...
[16:16:56.054] > Waiting for server log...
> Waiting for server log...
[16:16:56.071] > 
> Waiting for server log...
[16:16:56.132] > Waiting for server log...
[16:16:56.160] > Waiting for server log...
[16:16:56.177] > Waiting for server log...
[16:16:56.240] > Waiting for server log...
> Waiting for server log...
[16:16:56.254] > 
[16:16:56.270] > Waiting for server log...
[16:16:56.332] > Waiting for server log...
[16:16:56.392] > Waiting for server log...
> Waiting for server log...
[16:16:56.410] > 
> Waiting for server log...
[16:16:56.471] > Waiting for server log...
[16:16:56.533] > Waiting for server log...
> Waiting for server log...
[16:16:56.549] > 
> Waiting for server log...
[16:16:56.565] > 
[16:16:56.610] > Waiting for server log...
[16:16:56.671] > Waiting for server log...
> Waiting for server log...
[16:16:56.687] > 
> Waiting for server log...
[16:16:56.750] > Waiting for server log...
[16:16:56.812] > Waiting for server log...
> Waiting for server log...
[16:16:56.827] > 
> Waiting for server log...
[16:16:56.890] > Waiting for server log...
> Waiting for server log...
[16:16:56.905] > 
[16:16:56.920] > Waiting for server log...
[16:16:56.982] > Waiting for server log...
[16:16:57.043] > Waiting for server log...
> Waiting for server log...
[16:16:57.060] > 
> Waiting for server log...
[16:16:57.121] > Waiting for server log...
[16:16:57.182] > Waiting for server log...
> Waiting for server log...
[16:16:57.199] > 
> Waiting for server log...
[16:16:57.262] > Waiting for server log...
[16:16:57.321] > Waiting for server log...
> Waiting for server log...
[16:16:57.339] > 
> Waiting for server log...
[16:16:57.400] > Waiting for server log...
[16:16:57.461] > Waiting for server log...
> Waiting for server log...
[16:16:57.477] > 
> Waiting for server log...
[16:16:57.493] > 
[16:16:57.540] > Waiting for server log...
[16:16:57.599] > Waiting for server log...
> Waiting for server log...
[16:16:57.617] > 
> Waiting for server log...
[16:16:57.678] > Waiting for server log...
[16:16:57.740] > Waiting for server log...
> Waiting for server log...
[16:16:57.755] > 
> Waiting for server log...
[16:16:57.771] > 
[16:16:57.817] > Waiting for server log...
> Waiting for server log...
[16:16:57.834] > 
[16:16:57.848] > Waiting for server log...
[16:16:57.910] > Waiting for server log...
[16:16:57.971] > Waiting for server log...
> Waiting for server log...
[16:16:57.987] > 
> Waiting for server log...
[16:16:58.049] > Waiting for server log...
[16:16:58.109] > Waiting for server log...
> Waiting for server log...
[16:16:58.128] > 
> Waiting for server log...
[16:16:58.190] > Waiting for server log...
[16:16:58.249] > Waiting for server log...
> Waiting for server log...
[16:16:58.266] > 
> Waiting for server log...
[16:16:58.328] > Waiting for server log...
> Waiting for server log...
[16:16:58.343] > 
[16:16:58.360] > Waiting for server log...
[16:16:58.420] > Waiting for server log...
[16:16:58.480] > Waiting for server log...
> Waiting for server log...
[16:16:58.498] > 
> Waiting for server log...
[16:16:58.544] > Waiting for server log...
[16:16:58.606] > Waiting for server log...
> Waiting for server log...
[16:16:58.614] > 
[16:16:58.621] > Waiting for server log...
[16:16:58.638] > 
[16:16:58.698] > Waiting for server log...
[16:16:58.714] > Waiting for server log...
[16:16:58.730] > 
> Waiting for server log...
[16:16:58.745] > 
[16:16:58.778] >  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
> 
> Server did not start successfully. Full server log at /home/sumo/lwerthen/.vscode-server/.903b1e9d8990623e3d7da1df3d33db3e42d80eda
> .log >>>
> /home/sumo/lwerthen/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/bin/code-server: 25: ./bin/helpers/check-requireme
> nts.sh: not found
> <<< End of server log
> 5628c713fd60: start
> exitCode==32==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1970==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==14154==
> 5628c713fd60: end
[16:16:58.778] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1970==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==14154==

[16:16:58.780] Resolver error: Error: The VS Code Server failed to start
	at g.ServerInstallError (c:\Users\Lorin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.2024021915\out\extension.js:2:460274)
	at d (c:\Users\Lorin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.2024021915\out\extension.js:2:453617)
	at t.handleInstallOutput (c:\Users\Lorin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.2024021915\out\extension.js:2:455887)
	at t.tryInstall (c:\Users\Lorin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.2024021915\out\extension.js:2:581195)
	at async c:\Users\Lorin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.2024021915\out\extension.js:2:541053
	at async t.withShowDetailsEvent (c:\Users\Lorin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.2024021915\out\extension.js:2:544359)
	at async k (c:\Users\Lorin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.2024021915\out\extension.js:2:538018)
	at async t.resolve (c:\Users\Lorin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.2024021915\out\extension.js:2:541730)
	at async c:\Users\Lorin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.2024021915\out\extension.js:2:807898
[16:16:58.783] ------




[16:16:59.028] > 
[16:17:00.070] "install" terminal command done
[16:17:00.070] Install terminal quit with output: 
```

</p>
</details>

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by deepak1556**
Refs https://github.com/microsoft/vscode/issues/206790
Fixes https://github.com/microsoft/vscode-remote-release/issues/9577

### CODE REVIEW

File: resources/server/bin/code-server-linux.sh [hunk 1]
```diff
@@ -21,7 +21,7 @@ if [ -f "/tmp/vscode-skip-server-requirements-check" ]; then
 fi
 
 # Check platform requirements
-if [ "$(echo "$@" | grep -c -- "--skip-requirements-check")" -eq 0 ] && [ $skip_check -eq 0 ]; then
+if [ "$(echo "$@" | grep -c -- "--skip-requirements-check")" -eq 0 ] && [ $skip_check -eq 0 ] && [ -f $ROOT/bin/helpers/check-requirements.sh ]; then
```
Comment (aeschli) [inline resources/server/bin/code-server-linux.sh:24]: The cleanest is to no have that check at all. 
I suggest to create a `code-server-linux-legacy.sh` file and let the build script pick one or the other.

image

You can also add some additional echo there that warns that this is a legacy build that is unsupported.

**Comment by aeschli** [comment]
I thought having a separate `code-server-linux-legacy.sh` without all the check code is much more elegant and less confusing. Why doing all the checks `/tmp/vscode-skip-server-requirements-check` `"$(echo "$@" | grep -c -- "--skip-requirements-check")" -eq 0 ]` having the extra file is there's not really any checking going on?


```
#!/usr/bin/env sh
#
# Copyright (c) Microsoft Corporation. All rights reserved.
#

case "$1" in
	--inspect*) INSPECT="$1"; shift;;
esac

ROOT="$(dirname "$(dirname "$(readlink -f "$0")")")"

"$ROOT/node" ${INSPECT:-} "$ROOT/out/server-main.js" "$@"
```

just as it was before.

**Comment by deepak1556** [comment]
Sorry I misunderstood your comment, are you suggesting that extensions should make sure to call the `check-requirements.sh` before running the server and we remove the script from the server entry point script ?

**Comment by deepak1556** [comment]
@chrmarti this PR does 3 things

1) Removes `check-requirements.sh` from the server entry script. The extension should call the script explicitly before starting the server which I think you already do it for devcontainers. So the flag `--skip-requirements-check` can be removed
2) Renames asset from `legacy-server-linux-*` => `server-linux-legacy-*`
3) Adds a dummy `check-requirements.sh` as part of the legacy server

**Review by joaomoreno — APPROVED** [review]

**Comment by aeschli** [comment]
> Removes check-requirements.sh from the server entry script.
It's still there (for both legacy and normal), but for legacy it doesn't do anything except printing a message.
Not my favourite solution, but good for now. I would polish that next milestone, if that's ok.

**Review by chrmarti — COMMENTED** [review]
LGTM!

**Review by Imebeez — COMMENTED** [review]
[]()
