### PR TITLE
Ensure `ItemActivation.NONE` fires an onDidChange event

### LINKED ISSUE #207832: Cannot "Open Folder" anymore
Steps to Reproduce:

1. run `scripts/code-server.sh`
2. open the web UI
3. pick "Open Folder"
4. fill in a path that exists on disk and enter

image

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
Fixes https://github.com/microsoft/vscode/issues/207832

### CODE REVIEW

File: src/vs/platform/quickinput/browser/quickInput.ts [hunk 1]
```diff
@@ -1069,13 +1069,23 @@ export class QuickPick<T extends IQuickPickItem> extends QuickInput implements I
...
 			this.ui.count.setCount(this.ui.list.getCheckedCount());
 			switch (this._itemActivation) {
 				case ItemActivation.NONE:
+					// Handle the case where we had active items (i.e. someone chose an item)
+					// but the initial item activation is set to none. Calling clearFocus will
+					// not trigger the onDidFocus event because when the tree receives new elements,
+					// it sets the focus to no elements. So we need to set & fire the active items
+					// accordingly to reflect the state change after setting the items.
+					if (currentActiveItems.length > 0) {
+						this._activeItems = new Array<T>();
```
Comment (Tyriar) [inline src/vs/platform/quickinput/browser/quickInput.ts:1086]: Any reason to not use `[]`?

**Review by Tyriar — APPROVED** [review]

File: src/vs/platform/quickinput/browser/quickInput.ts (hunk 1 above)
Comment (TylerLeonhardt) [reply src/vs/platform/quickinput/browser/quickInput.ts:1086]: force of habit! will fix in follow up

**Comment by youcandanch** [comment]
This was driving me _nuts_ -- thought I busted something on my filesystem. Thanks for the quick fix, @TylerLeonhardt!
