### PR TITLE
Fix renderHeight being undefined

### LINKED ISSUE #165343: Cannot read properties of undefined (reading 'renderHeight')
```
Version: 1.74.0-insider (Universal)
Commit: 86f0f9bfa268fe21af7efae37d8f0da1dba8137f
Date: 2022-11-03T05:38:29.744Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: Yes
```

image

```
   ERR Cannot read properties of undefined (reading 'renderHeight'): TypeError: Cannot read properties of undefined (reading 'renderHeight')
    at get pageSize [as pageSize] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2576:41515)
    at ie.clear (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2576:44123)
    at ie.loadTimeline (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2576:44682)
    at ie.onProvidersChanged (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2576:43177)
    at f.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…p/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:145)
    at r.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:2559)
    at l.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:2137)
    at I.registerTimelineProvider (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1307:24724)
    at I.$registerTimelineProvider (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1714:67885)
    at v._doInvokeHandler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1721:12969)
    at v._invokeHandler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1721:12651)
    at v._receiveRequest (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1721:11421)
    at v._receiveOneMessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1721:10123)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1721:8230
    at f.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…p/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:145)
    at r.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:2559)
    at l.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:83:2137)
    at n.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:548:16856)
    at ie.onmessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ontents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1967:1718)
```

### PR DESCRIPTION
**Pull request by lramos15**
Fixes #165343

Not sure if there was a cahnge recently to optimize how we render views, but seems like `renderBody` now doesn't get called if a view is collapsed meaning the tree stays undefined. This wasn't caught because the tree is non-null asserted. I didn't change that, but I do catch the case when we try to render without a tree.

### CODE REVIEW

File: src/vs/workbench/contrib/timeline/browser/timelinePane.ts [hunk 1]
```diff
@@ -328,7 +328,7 @@ export class TimelinePane extends ViewPane {
 		let pageSize = this.configurationService.getValue<number | null | undefined>('timeline.pageSize');
 		if (pageSize === undefined || pageSize === null) {
 			// If we are paging when scrolling, then add an extra item to the end to make sure the "Load more" item is out of view
-			pageSize = Math.max(20, Math.floor((this.tree.renderHeight / ItemHeight) + (this.pageOnScroll ? 1 : -1)));
+			pageSize = Math.max(20, Math.floor((this.tree?.renderHeight ?? 0 / ItemHeight) + (this.pageOnScroll ? 1 : -1)));
```
Comment (alexr00) [inline src/vs/workbench/contrib/timeline/browser/timelinePane.ts:331]: Should the `!` be removed here too?

https://insiders.vscode.dev/github/microsoft/vscode/blob/d1c586beeea0e473423217c00c0dc2bb24dfff1a/src/vs/workbench/contrib/timeline/browser/timelinePane.ts#L238-L239

**Review by alexr00 — APPROVED** [review]

File: src/vs/workbench/contrib/timeline/browser/timelinePane.ts (hunk 1 above)
Comment (lramos15) [reply src/vs/workbench/contrib/timeline/browser/timelinePane.ts:331]: That would be a much larger change which I didn't want to do at the moment which is why I held off as described by the PR description. In the end though, yes I will probably change that as it provides a false sense of security
