### PR TITLE
Fix #26821 Memento

### LINKED ISSUE #26821: Do not keep saved what I researched in the search bar.
- VSCode Version: 1.13.0 - insiders
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Steps to Reproduce:

First Situation:

1. Use the search in Active Bar (Ctrl + Shift + F)
2. Go back to the Explorer (or not).
3. Close VSCode or use Reload a Window
4. Open again (ignore if you use Reload a Window)
5. Open the search in Active Bar (Ctrl + Shift + F)
6. See that the item searched for is still there.

Second Situation

1. Use the search in Active Bar (Ctrl + Shift + F)
2. Clear the search.
3. Go back to the Explorer (or not).
4. Close the VSCode or use Reload a Window
5. Open again (ignore if you use Reload a Window)
6. Open the search in Active Bar (Ctrl + Shift + F)
7. See that the item searched is still there.

Note: If I had not used 'Clear Search' and had used 'Reload Window' I could agree to keep. But from the moment I closed the VSCode, I do not agree to keep what I researched ..

Any way to avoid this? This is very boring.

### PR DESCRIPTION
**Pull request by Lixire**
- Search now remembers if you cleared your input before shutdown

Right now, mementos are changed when the query changes. This means that when someone erases the search input and immediately closes/reloads, the text is persisted anyways. One way to fix it is to change and save the memento only when the user closes/reloads vscode. However, I wasn't sure if this new behaviour is okay. What are your thoughts? If this is fine, then can we move all the memento's into `shutdown()`?

Also, it looks like the search viewlet's `dispose()` is not being called. Is this expected behaviour?

### CODE REVIEW

File: src/vs/workbench/parts/search/browser/searchViewlet.ts [hunk 1]
```diff
@@ -1349,6 +1349,13 @@ export class SearchViewlet extends Viewlet {
 		];
 	}
 
+	public shutdown(): void {
+		this.viewletSettings['query.contentPattern'] = this.searchWidget.searchInput.getValue();
+		this.saveMemento();
```
Comment (roblourens) [inline src/vs/workbench/parts/search/browser/searchViewlet.ts]: I think saveMemento is done by super.shutdown, right?

**Review by roblourens — CHANGES_REQUESTED** [review]

File: src/vs/workbench/parts/search/browser/searchViewlet.ts (hunk 1 above)
Comment (Lixire) [inline src/vs/workbench/parts/search/browser/searchViewlet.ts]: Yes, whoops

**Review by roblourens — APPROVED** [review]

**Comment by roblourens** [comment]
I think it makes sense to override `shutdown` and write all the memento properties in there, since `super.shutdown` is what saves it. It might be that `dispose` is just called too late for writing to the memento?

**Review by roblourens — APPROVED** [review]
