### PR TITLE
#84678 add language-specific overrides for breadcrumb and outline settings

### LINKED ISSUE #84678: Make type filters for outline and breadcrumbs language specific
Is it possible to make type filters for outline and breadcrumbs (new in V1.4) language specific?
For example something like this:
```
{
    "[python]": {
        "outline.showConstants": false,
        "outline.showConstructors": false,
        "outline.showVariables": false,        
    },
}
```
It seems it will not work currently. I got the error: `Unknown Identifier. Use language identifiers`

### PR DESCRIPTION
**Pull request by pjvan**
This PR fixes #84678 by setting the relevant configuration options as overridable and including override details when getting these values from the configuration.

I'm still working on getting the outline settings working the same way, but I'm opening this PR up early for any potential feedback and guidance.

## Affected Settings
Affected settings include all of the settings in [outline.contribution.ts](https://github.com/microsoft/vscode/blob/73e605653d45e8c64ee6390d5c5f5bcfabd3e7d0/src/vs/workbench/contrib/outline/browser/outline.contribution.ts#L30)and [breadcrumbs.ts](https://github.com/microsoft/vscode/blob/14208840271c9f764ac759db4d412365e7ab31ba/src/vs/workbench/browser/parts/editor/breadcrumbs.ts#L116) that have a corresponding `filteredTypes` setting.

## Questions / Guidance

* I'm currently trying to find out how to get the class responsible for filtering outlines [OutlineFilter](https://github.com/microsoft/vscode/blob/3d8a749238cf85052bcf76039166ae3494422a91/src/vs/editor/contrib/documentSymbols/outlineTree.ts#L221) to have the correct context when reading the config. It seems like I either have to include a relevant service [codeEditorService](https://github.com/microsoft/vscode/blob/a38ca5b5373b68afc899ea05c81bbfe419b77e9b/src/vs/editor/browser/services/codeEditorService.ts#L15) or pass [OutlineFilter.update](https://github.com/microsoft/vscode/blob/3d8a749238cf85052bcf76039166ae3494422a91/src/vs/editor/contrib/documentSymbols/outlineTree.ts#L290) the necessary context. Does anyone have any thoughts? Currently leaning towards the former but I don't know the full implications that that might have.

* When listening for configuration updates in the breadcrumbs model, I'm just checking for changes to configurations with either `breadcrumbs` or `[<current language>]` and updating that breadcrumb's outline if those are affected. Is this the way to do it or can I be more specific? It seems like the configuration service can only notify changes from the first layer of the configuration tree.

## Testing
I haven't written any tests yet because I'm not sure if features like this are supposed to get them, but I can write some if that would be preferred.

### CODE REVIEW

File: src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts [hunk 1]
```diff
@@ -250,7 +261,16 @@ export class EditorBreadcrumbsModel {
...
+
+			// If possible, look for language specific overrides when reading configuration.
+			if (this._editor && this._editor.getModel()) {
+				const model = this._editor.getModel() as ITextModel;
+				return !this._configurationService.getValue<boolean>(key, {
+					overrideIdentifier: model.getLanguageIdentifier().language
+				});
+			}
+
+			return this._configurationService.getValue<boolean>(key);
```
Comment (jrieken) [inline src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts]: You can use the [ITextResourceConfigurationService](https://github.com/microsoft/vscode/blob/9727eb60500657cd2c30e4a3992e17940c2cefba/src/vs/workbench/api/common/extHostTypeConverters.ts#L243) which makes this a lot simpler

File: src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts [hunk 2]
```diff
@@ -142,6 +143,16 @@ export class EditorBreadcrumbsModel {
...
 				this._updateOutline(true);
+				return;
+			}
+			if (this._editor && this._editor.getModel()) {
+				const editorModel = this._editor.getModel() as ITextModel;
+				const languageName = editorModel.getLanguageIdentifier().language;
+
+				// checking for changes in the current language override config
+				if (e.affectsConfiguration(`[${languageName}]`)) {
+					this._updateOutline(true);
```
Comment (jrieken) [inline src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts]: @sandy081 Is this the only why of knowing if a language-overidden setting has changed? doesn't the check on line 144 cover this?

**Comment by jrieken** [comment]
> r pass OutlineFilter.update the necessary context. Does anyone have any thoughts? Currently leaning towards the former but I don't know the full implications that that might have.

Also use the `ITextResourceConfigurationService` and inside filter use the `OutlineModel.get(element).textModel.uri`

File: src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts (hunk 2 above)
Comment (sandy081) [reply src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts]: Yeah, unfortunately the event only knows about root keys. I would be improving this when  I extend lang specific settings for extensions. I will keep a note of it and remove this.

File: src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts (hunk 1 above)
Comment (petevdp) [reply src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts]: I tried this implementation:
```typescript
if (this._editor && this._editor.getModel()) {
	const model = this._editor.getModel() as ITextModel;
	return this._textResourceConfigurationService.getValue<boolean>(model.uri, key);
}
```

It works great, except for the boolean value being flipped! The values are always opposite of what's expected.

This is true for both language-specific overrides and the base config.

File: src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts (hunk 2 above)
Comment (petevdp) [reply src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts]: I'll include a comment explaining this as well.

Comment (petevdp) [reply src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts]: 9497acd875493a3dd6d240ea401422b3cc797fda

File: src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts (hunk 1 above)
Comment (petevdp) [reply src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts]: How's this? 9d9a99d67562315c34c195865c0720abff96c721

**Comment by petevdp** [comment]
> > r pass OutlineFilter.update the necessary context. Does anyone have any thoughts? Currently leaning towards the former but I don't know the full implications that that might have.
> 
> Also use the `ITextResourceConfigurationService` and inside filter use the `OutlineModel.get(element).textModel.uri`

implementation: 25a1bbb9db54401b7dc6248f369bd412d9a18136

**Comment by petevdp** [comment]
a callback is registered [here](https://github.com/microsoft/vscode/blob/25a1bbb9db54401b7dc6248f369bd412d9a18136/src/vs/workbench/contrib/outline/browser/outlinePanel.ts#L371) which refilters the outline tree on config reload. Like [this similar logic](url) for breadcrumbs,

**Comment by jrieken** [comment]
> A temporary fix would be to always filter on configuration change, but that wouldn't be ideal.

Ideally we get a better API here but what you could try is `e.affectedKeys` - it lists all changed keys and you could check for the occurrence of `outline` in there, e.g search for `/$\.?outline\./`

**Comment by petevdp** [comment]
affectedKeys is subject to the same limitation unfortunately, but maybe I could regex `outline` and language specific sections e.g `/(outline|\[\w+\])/`

File: src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts [hunk 3]
```diff
@@ -53,9 +55,9 @@ export class EditorBreadcrumbsModel {
 		private readonly _uri: URI,
 		private readonly _editor: ICodeEditor | undefined,
 		@IConfigurationService private readonly _configurationService: IConfigurationService,
+		@ITextResourceConfigurationService private readonly _textResourceConfigurationService: ITextResourceConfigurationService,
```
Comment (jrieken) [inline src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts]: The "normal" ICOnfigurationService shouldn't be needed anymore and everything should be possible using the text resource based service

File: src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts [hunk 4]
```diff
@@ -168,6 +169,7 @@ export class BreadcrumbsControl {
 		@IThemeService private readonly _themeService: IThemeService,
 		@IQuickOpenService private readonly _quickOpenService: IQuickOpenService,
 		@IConfigurationService private readonly _configurationService: IConfigurationService,
+		@ITextResourceConfigurationService private readonly _textResourceConfigurationService: ITextResourceConfigurationService,
```
Comment (jrieken) [inline src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts]: Don't have two configuration services (see below)

File: src/vs/editor/contrib/documentSymbols/outlineTree.ts [hunk 5]
```diff
@@ -278,27 +280,26 @@ export class OutlineFilter implements ITreeFilter<OutlineItem> {
...
+
+		if (outline) {
+			uri = outline.textModel.uri;
+		}
+
+		if (!(element instanceof OutlineElement)) {
+			return true;
+		}
+
+		const configName = (OutlineFilter.kindToConfigName as any)[element.symbol.kind] as string;
```
Comment (jrieken) [inline src/vs/editor/contrib/documentSymbols/outlineTree.ts]: why this casted to ` any`?

**Review by jrieken — CHANGES_REQUESTED** [review]

File: src/vs/editor/contrib/documentSymbols/outlineTree.ts (hunk 5 above)
Comment (petevdp) [reply src/vs/editor/contrib/documentSymbols/outlineTree.ts]: I honestly don't remember, apologies. I took out the typecasts and got no type errors. Sorry about that! e88573e26b71e1471dd1abc6458c6cb7fefba17d

File: src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts (hunk 3 above)
Comment (petevdp) [reply src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts]: `TextResourceConfigurationService` doesn't appear to be a strict superset of ConfigurationService, and unfortunately [BreadcrumbsConfig](https://github.com/microsoft/vscode/blob/14208840271c9f764ac759db4d412365e7ab31ba/src/vs/workbench/browser/parts/editor/breadcrumbs.ts#L56) uses one of the unported methods `updateValue` right [here](https://github.com/microsoft/vscode/blob/14208840271c9f764ac759db4d412365e7ab31ba/src/vs/workbench/browser/parts/editor/breadcrumbs.ts#L101) in method `BreadcrumbsConfig.updateValue` This method is, in turn, bound and used by two breadcrumb configuration options, [here](https://github.com/microsoft/vscode/blob/9d9a99d67562315c34c195865c0720abff96c721/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L532) and [here](https://github.com/microsoft/vscode/blob/9d9a99d67562315c34c195865c0720abff96c721/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L585).

This more directly relates to your other coment on `BreadcrumbsControl` since the references to `updateValue` are all in there, but I'm guessing we don't want to have to remove `BreadcrumbsConfig` as a dependency of either class.

What I have right now definitely isn't the ideal solution though, so I could  try to bring `TextResourceConfigurationService` in line with `ConfigurationService` either in this PR, or get another pr merged first if this issue is too tangential.

I didn't really check to see if I could just use the one config service though, so thanks for pointing it out!

File: src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts (hunk 4 above)
Comment (petevdp) [reply src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts]: Left a reply over there as well which is relevant here.

File: src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts (hunk 3 above)
Comment (jrieken) [reply src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts]: That's for the explaining - I learnt something :-). Yeah, the `TextResourceConfigService` seems to be limiting and causing less pretty code /cc @sandy081. Let's keep the PR free from cleaning that up.

**Review by jrieken — APPROVED** [review]

**Comment by jrieken** [comment]
This is looking good. @petevdp Can you fix merge conflicts and then I'll bring this in for the Nov release

**Comment by petevdp** [comment]
Apologies, this merge is going to be broken... Not sure why I thought it would be a good idea to push this without at least testing it. doh. I'll try to resolve this shortly.

File: src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts (hunk 3 above)
Comment (sandy081) [reply src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts]: Filed https://github.com/microsoft/vscode/issues/85884 to enhance `ITextResourceConfigService `

File: src/vs/workbench/contrib/outline/browser/outlinePane.ts [hunk 6]
```diff
@@ -372,8 +372,9 @@ export class OutlinePane extends ViewletPane {
 			if (e.affectsConfiguration(OutlineConfigKeys.icons)) {
 				this._tree.updateChildren();
 			}
-			if (e.affectsConfiguration('outline')) {
-				this._treeFilter.update();
+			// This is a temporary solution to try and minimize refilters while
+			// ConfigurationChangeEvents only provide the first section of the config path.
+			if (e.affectedKeys.some(key => key.search(/(outline|\[\w+\])/))) {
```
Comment (jrieken) [inline src/vs/workbench/contrib/outline/browser/outlinePane.ts]: fyi - this lacks a check for `=== 0`. I will fix this one master after merge.

**Comment by petevdp** [comment]
Thanks for everyone's help!
