### PR TITLE
fix task reconnection

### LINKED ISSUE #186373: Reconnected default build task not used
1. Have default build task already running
2. Reload window, reconnected to existing default build task
3. Ctrl+Shift+B
4. :bug: new set of default build tasks starts running (this is in the VS Code repo)

image

### LINKED ISSUE #186749: task reconnection doesn't work
Repro:

1. Open vscode repo
2. Run default build task
3. Wait for it to finish
4. Reload window
5. Run default build task

See no tick/cross in the tab:

Screenshot 2023-06-30 at 7 50 38 am

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #186749
fixes #186373

very similar issue to the one where the build task wasn't discovered -- if the task that's getting reconnected to belongs to an execution which has not yet been registered, then the reconnection will fail and you'll see both of these error messages. 

Screenshot 2023-07-07 at 1 13 12 PM

The first message occurs when `_jsonTasksSupported` is false, which is this case when one or both of these hasn't yet been set.

https://github.com/microsoft/vscode/blob/0e5c0111e868d4b270273f850c36ee334d690468/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L2264-L2266

The second is a byproduct of that since the call to activate that provider doesn't happen

We have a new event which waits for all supported executions or times out. 

What we could do is store a variable on before reload which dictates which executions need to be supported for the reconnection to happen. but maybe that's overkill

### CODE REVIEW

**Comment by meganrogge** [comment]
> What we could do is store a variable on before reload which dictates which executions need to be supported for the reconnection to happen. but maybe that's overkill

this is easy enough - i'll add this

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 1]
```diff
@@ -224,7 +224,9 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
 	protected _outputChannel: IOutputChannel;
 	protected readonly _onDidStateChange: Emitter<ITaskEvent>;
 	private _waitForSupportedExecutions: Promise<void>;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:226]: wait for one supported execution?

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 2]
```diff
@@ -2202,6 +2210,11 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
 			return new Map();
 		}
 		await this._waitForSupportedExecutions;
+		if (runSource === TaskRunSource.Reconnect) {
+			await raceTimeout(this._waitForAllSupportedExecutions, 500, () => {
+				console.warn('Timed out waiting for all supported executions for task reconnection');
```
Comment (Tyriar) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:2215]: log service?

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Review by Tyriar — APPROVED** [review]
