### PR TITLE
fine tune shell integration messaging

### LINKED ISSUE #148839: Polish shell integration messaging
Action items after a discussion:

- [x] Explain when shell integration may fail to activate in the setting docs, ie. complex prompt command for example (debug trap specified?)
- [x] Remove in-terminal shell integration disabled warning
- [x] Hide shell integration activated message in favor of an item in the command decoration? How does this work? Learn more?
  - The reason we had the activated message to begin with was to disclose to people that we have performed some script injection. We believe it's sufficient now just showing the rich command decorations (and the terminal tab hover) as an indicator, also with documentation on the website that explains how the terminal works.
- [x] Remove capabilities from tab hover, only say "Shell integration activated" or "Shell integration failed to activate"

### LINKED ISSUE #148871: Remote Containers: Shell integration cannot be activated due to complex PROMPT_COMMAND: prompt;history -a
Tried opening the C# remote container sample, see ugly warning on every terminal. Ideally we'd not be broken here, but at minimum maybe only show the error once? 

image

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #148839 
Fixes #148871

### CODE REVIEW

File: src/vs/platform/terminal/node/terminalEnvironment.ts [hunk 1]
```diff
@@ -131,9 +131,8 @@ export function getShellIntegrationInjection(
 				return undefined;
 			}
 			if (newArgs) {
-				const additionalArgs = options.showWelcome ? '' : ' -HideWelcome';
 				newArgs = [...newArgs]; // Shallow clone the array to avoid setting the default array
-				newArgs[newArgs.length - 1] = format(newArgs[newArgs.length - 1], appRoot, additionalArgs);
+				newArgs[newArgs.length - 1] = format(newArgs[newArgs.length - 1], appRoot);
```
Comment (meganrogge) [inline src/vs/platform/terminal/node/terminalEnvironment.ts]: this line is a bit confusing to me

File: src/vs/workbench/contrib/terminal/browser/terminalTooltip.ts [hunk 2]
```diff
@@ -6,33 +6,25 @@
...
 	}
+	let shellIntegrationString = '';
 	if (shellIntegrationCapabilities.length > 0) {
-		shellIntegrationString += `${markdown ? '\n\n---\n\n' : '\n\n'} ${localize('shellIntegration.enabled', "Shell integration is enabled")}`;
-		for (const capability of shellIntegrationCapabilities) {
-			shellIntegrationString += `\n- ${getCapabilityName(capability)}`;
-		}
+		shellIntegrationString += `${markdown ? '\n\n---\n\n' : '\n\n'} ${localize('shellIntegration.enabled', "Shell integration activated")}`;
+	} else {
+		shellIntegrationString += `${markdown ? '\n\n---\n\n' : '\n\n'} ${localize('shellIntegration.activationFailed', "Shell integration failed to activate")}`;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalTooltip.ts:27]: This is technically "did not activate", should we say that until we have a time based mechanism that expected it to activate after a few seconds?

File: test/smoke/src/areas/terminal/terminal-shellIntegration.test.ts [hunk 3]
```diff
@@ -22,33 +22,28 @@ export function setup() {
 			describe('Activation', function () {
 				it('should activate shell integration on creation of a terminal', async () => {
```
Comment (Tyriar) [inline test/smoke/src/areas/terminal/terminal-shellIntegration.test.ts:23]: This test doesn't do anything anymore, can be removed

**Review by Tyriar — DISMISSED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalTooltip.ts (hunk 2 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalTooltip.ts:27]: Well "did not activate" can happen because it is not enabled with the setting. In this case, we tried to activate it and it failed.

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalTooltip.ts:27]: But it hasn't necessarily failed yet, consider the case of creating a shell that takes a few seconds to load and you hover it immediately. Small thing and I guess we could improve as part of https://github.com/microsoft/vscode/issues/148840 since we'll do the timeout thing there?

**Review by Tyriar — APPROVED** [review]
