### PR TITLE
markdown-language-features: Fix Windows Preview Link Uri

### LINKED ISSUE #119163: Strange file input created when opening link from Markdown preview
On Windows:

1. Open a local empty folder
1. Create an empty `file.json`
2. Create a `file.md` with the following contents: `[Click Here](/file.json)`
3. Open the Markdown preview
4. Click the `Click Here` link

🐛 File opens with a strange input, as if its entire path is the file name. Also, if you open `file.json` from the Explorer, it now appears twice in Quick Open: once normally and another in the weird long format.

image

### PR DESCRIPTION
**Pull request by sangxxh**
This PR fixes #119163

Correct preview link file path.

Unfortunately, I don't have a Mac OS or Linux so I can't test on those platforms.

## Result

119163_20210329_After

### CODE REVIEW

File: extensions/markdown-language-features/src/features/preview.ts [hunk 1]
```diff
@@ -434,14 +434,14 @@ class MarkdownPreview extends Disposable implements WebviewResourceProvider {
...
 
-		// We perviously already resolve absolute paths.
-		// Now make sure we handle relative file paths
 		if (hrefPath[0] !== '/') {
-			// Fix #93691, use this.resource.fsPath instead of this.resource.path
-			hrefPath = path.join(path.dirname(this.resource.fsPath), hrefPath);
+			// We perviously already resolve absolute paths.
+			// Now make sure we handle relative file paths
+			const dirname = path.dirname(this.resource.path);
+			hrefPath = vscode.Uri.file(path.join(dirname, hrefPath)).path;
```
Comment (mjbvz) [inline extensions/markdown-language-features/src/features/preview.ts:441]: Instead of using `path.join` and `Uri.file`, can you switch to use `Uri.joinPaths` instead? 

Also since this changes to use `fsPath` instead of `path`, please test to make sure this works properly for UNC paths and networks share

Comment (hantatsang) [reply extensions/markdown-language-features/src/features/preview.ts]: Thanks.

- `Uri.joinPaths` works

I'm using `fsPath` caused the original issue so I use `path` instead. Will check with UNC paths and network share 🤞

Comment (hantatsang) [reply extensions/markdown-language-features/src/features/preview.ts]: Update: I just checked network share and both this PR, existing VSCode and VSCode Insider can't open the link. Will take me a while to figure out this one

Comment (hantatsang) [reply extensions/markdown-language-features/src/features/preview.ts]: @mjbvz I'm not familiar with network share and UNC paths. Happy to let someone take over/close the PR.

**Comment by mjbvz** [comment]
Thanks! Let's try this in insiders an see if it causes any issues
