### PR TITLE
setting to anchor to focused cell

### LINKED ISSUE #169038: Scroll top improvement based on context
Currently the scroll top position update is not context-aware, meaning when we have cell height changes, we don't know if it's because output height change, or users re-run a cell and outputs are updated/replaced, or users shift+enter to run cell and navigate to next cell. Users might have different expectations for each scenario but currently our heuristics for updating the scroll top didn't take the context into account.

Let's use this issue to finalize the desired behavior of scroll top update. The polished/new design should cover

* [ ] Update element height API respects context (execution, execute+create, output update)
* [ ] Reveal API should handle out of sync view/content height

---

## Execute focused cell

* Click the run button or press Ctrl+Enter to run focused cell
* If there is no enough room/space after the cell (e.g., the focused cell is the last cell)
  * Users have `editor.scrollBeyondLastLine` disabled
    * [ ] There is no output before execution, the view should scroll up to reveal the output fully
      * [ ] Some users might want the bottom of the output to be fully revealed, when the output is larger than the viewport https://github.com/microsoft/vscode-jupyter/issues/5186
    * [ ] There is output before execution, the cell position should be persistent 
  * Users have `editor.scrollBeyondLastLine` enabled
    * [ ] Reveal cell output
* If there is enough room after the cell
   * [ ] Reveal cell output
* [ ] If the cell input is larger than the viewport, execute cell should reveal the output properly https://github.com/microsoft/vscode/issues/129440

## Operations on focused cell

* [ ] Collapse focused cell output should always keep the cell in viewport https://github.com/microsoft/vscode/issues/114866
* [ ] Type/Pasting content into focused cell should keep the cell in viewport 
  * [x] https://github.com/microsoft/vscode/issues/165415
  * [ ] Notebook cell list reveal api might reveal a position on a cell whose view height is not synced with real editor height yet.

## Operations on non-focused cell

* [ ] ❓ Execute non-focused cell, should it keep the focused cell position persistent or keep the top of the target cell persistent? https://github.com/microsoft/vscode/issues/121723
* [ ] Non focused cell output height change should not change scroll top on scroll https://github.com/microsoft/vscode/issues/142439
* [ ] Shift+enter executes and moves focus to next cell, then new focused cell should always be in viewport https://github.com/microsoft/vscode/issues/134607

## Split view 
* [x] Scroll top position of inactive notebook editor should not change if the first partially visible cell's height change https://github.com/microsoft/vscode/issues/145340

### LINKED ISSUE #193231: notebook scrolls up incorrectly when adjusting output heights
1. create a notebook that has several cells, and put this code in the second to last cell

```
import time
time.sleep(2)
for i in range(18):
    print(i)
print('end of output')
```

2. execute the cell so that it has output, and shrink the window so that the single cell+output takes up the whole scrollable region
3. execute the cell again with shift+enter

:bug: the notebook ends up scrolling up, instead of showing the full output and next cell.

Recording 2023-09-15 at 11 31 00

### PR DESCRIPTION
**Pull request by amunger**
fixes https://github.com/microsoft/vscode/issues/169038
fixes https://github.com/microsoft/vscode/issues/193231

previously (in stable currently), the focused cell would be anchored only if the cell changing size was partially visible as shown in https://github.com/microsoft/vscode/issues/193231. This will set the focused cell as anchored consistently by default, with a setting to disable that behavior.

Also changes the reveal full cell behavior back to revealing in the center, rather than pinning it to the bottom, which ended up focusing on the next cells output.

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts [hunk 1]
```diff
@@ -1019,16 +1019,25 @@ configurationRegistry.registerConfiguration({
...
-				nls.localize('notebook.revealNextOnExecuteBehavior.fullCell.description', 'Scroll to fully reveal the next cell.'),
-				nls.localize('notebook.revealNextOnExecuteBehavior.firstLine.description', 'Scroll to reveal the first line of the next cell.'),
-				nls.localize('notebook.revealNextOnExecuteBehavior.nonedescription', 'Do not scroll to reveal the next cell.'),
+				nls.localize('notebook.scrolling.revealCellBehavior.fullCell.description', 'Scroll to fully reveal the selected cell.'),
+				nls.localize('notebook.scrolling.revealCellBehavior.firstLine.description', 'Scroll to reveal the first line of the selected cell.'),
+				nls.localize('notebook.scrolling.revealCellBehavior.nonedescription', 'Do not scroll to reveal the selected cell.'),
 			],
 			default: 'fullCell'
+		},
+		[NotebookSetting.anochorToFocusedCell]: {
```
Comment (Yoyokrazy) [inline src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts:1033]: spelling. anocher vs anchor

File: src/vs/workbench/contrib/notebook/browser/view/notebookCellList.ts [hunk 2]
```diff
@@ -1203,24 +1203,16 @@ export class NotebookCellList extends WorkbenchList<CellViewModel> implements ID
...
-			return this.view.updateElementHeight(index, size, focus);
-		}
-
-		// the `element` is in the viewport, it's very often that the height update is triggerred by user interaction (collapse, run cell)
-		// then we should make sure that the `element`'s visual view position doesn't change.
+		const focus = focused.length ? focused[0] : null;
 
-		if (this.view.elementTop(index) >= this.view.getScrollTop()) {
-			return this.view.updateElementHeight(index, size, index);
+		const anchorFocusedSetting = this.configurationService.getValue(NotebookSetting.anochorToFocusedCell);
```
Comment (Yoyokrazy) [inline src/vs/workbench/contrib/notebook/browser/view/notebookCellList.ts:1208]: spelling -- `anocher`

File: src/vs/workbench/contrib/notebook/common/notebookCommon.ts [hunk 3]
```diff
@@ -964,7 +964,8 @@ export const NotebookSetting = {
 	confirmDeleteRunningCell: 'notebook.confirmDeleteRunningCell',
 	remoteSaving: 'notebook.experimental.remoteSave',
 	gotoSymbolsAllSymbols: 'notebook.gotoSymbols.showAllSymbols',
-	cellExecutionScroll: 'notebook.revealNextOnExecuteBehavior'
+	scrollToRevealCell: 'notebook.scrolling.revealCellBehavior',
+	anochorToFocusedCell: 'notebook.scrolling.anchorToFocusedCell'
```
Comment (Yoyokrazy) [inline src/vs/workbench/contrib/notebook/common/notebookCommon.ts:968]: spelling -- anocher

File: src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts [hunk 4]
```diff
@@ -2382,8 +2382,6 @@ export class NotebookEditorWidget extends Disposable implements INotebookEditorD
 				if (typeof options?.focusEditorLine === 'number') {
 					this._cursorNavMode.set(true);
 					this.revealInView(cell);
-				} else if (options?.revealBehavior === ScrollToRevealBehavior.fullCell) {
```
Comment (Yoyokrazy) [inline src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts:2385]: Just double checking, I'm assuming this behavior is covered by `revealInCenterIfOutsideViewport(cell)` and therefore the check against this setting is unnecessary?

Comment (amunger) [reply src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts:2385]: yeah, scroll to the center instead of scrolling that will pin it to the bottom

**Review by Yoyokrazy — APPROVED** [review]

File: src/vs/base/browser/ui/list/listView.ts [hunk 5]
```diff
@@ -528,7 +528,7 @@ export class ListView<T> implements IListView<T> {
 			// do not scroll the viewport if resized element is out of viewport
 			heightDiff = size - originalSize;
 		} else {
-			if (anchorIndex !== null && anchorIndex > index && anchorIndex <= lastRenderRange.end) {
```
[the remark this answers is not in the document]
Comment (joaomoreno) [reply src/vs/base/browser/ui/list/listView.ts:531]: Nice!

**Comment by joaomoreno** [comment]
Unsure if this broke scrolling further, please read https://github.com/microsoft/vscode/issues/193231#issuecomment-1733046390
