### PR TITLE
mcp: allow resource domains in script-src and style-src CSP

### LINKED ISSUE #286689: MCP apps cannot load external scripts/styles from resource domains
Image

### Bug Description
MCP apps that specify `resourceDomains` in their CSP configuration cannot load external scripts and stylesheets from those domains. The CSP (Content Security Policy) currently only includes resource domains for `connect-src`, `img-src`, and `font-src`, but not for `script-src` and `style-src`.

### Steps to Reproduce
1. Create a Skybridge template MCP server:
   ```bash
   npm create skybridge@latest
   ```

2. In VSCode, add MCP server via HTTP:
   - Open MCP settings
   - Add server with HTTP endpoint: `http://localhost:3000/mcp`

3. Add the following to your user settings:
   ```json
   {
       "chat.mcp.apps.enabled": true
   }
   ```

4. In the chat, send the following message:
   ```
   Magic Ball : tell me, am i the greatest developer
   ```

5. Open Developer Tools (Help > Toggle Developer Tools)

6. Check the Console for CSP violation errors

### Expected Behavior
External scripts and stylesheets from domains specified in the MCP app's `resourceDomains` configuration should be allowed to load without CSP violations.

### Actual Behavior
Scripts and styles are blocked by CSP with errors in the console, even though the domains are specified in the app's configuration.

### Environment
- VSCode Version: 1.109.0-insider
- Commit: 7c62052af606ba507cbb8ee90b0c22957bb175e7
- OS: Darwin arm64 25.1.0

### Location in Code
File: `src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatMcpAppModel.ts:254-255`

The CSP configuration needs to include `${cleanDomains(csp?.resourceDomains)}` in both `script-src` and `style-src` directives, similar to how it's already included in `img-src` and `font-src`.

### PR DESCRIPTION
**Pull request by qchuchu**
## Summary
Fixes #286689

This PR fixes an issue where MCP apps cannot load external scripts and stylesheets from domains specified in their CSP `resourceDomains` configuration.

## Changes
- Added `resourceDomains` to `script-src` CSP directive in [chatMcpAppModel.ts:254](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatMcpAppModel.ts#L254)
- Added `resourceDomains` to `style-src` CSP directive in [chatMcpAppModel.ts:255](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatMcpAppModel.ts#L255)

This aligns the CSP configuration for scripts and styles with the existing pattern already used for `img-src` and `font-src`.

## Test Plan
- [ ] Follow reproduction steps in issue #286689
- [ ] Verify that scripts and styles from resource domains now load without CSP violations
- [ ] Check that other CSP directives continue to work as expected

### CODE REVIEW

File: src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatMcpAppModel.ts [hunk 1]
```diff
@@ -251,8 +251,8 @@ export class ChatMcpAppModel extends Disposable {
 
 		const cspContent = `
 			default-src 'none';
-			script-src 'self' 'unsafe-inline';
-			style-src 'self' 'unsafe-inline';
```
Comment (connor4312) [inline src/vs/workbench/contrib/chat/browser/widget/chatContentParts/toolInvocationParts/chatMcpAppModel.ts:255]: thanks! This is actually not in the spec https://github.com/modelcontextprotocol/ext-apps/blob/main/specification/draft/apps.mdx#4-content-security-policy-enforcement will raise over there

**Review by connor4312 — APPROVED** [review]
Clarified in https://github.com/modelcontextprotocol/ext-apps/issues/223#issuecomment-3729776774 that this is a spec bug, so let's merge!

**Review by dmitrivMS — APPROVED** [review]
