### PR TITLE
Fix detection of CSS Preprocessor Comments at Start of File in Emmet Extension

### LINKED ISSUE #142109: VSCode becomes unresponsive after changing colors in large scss files
Issue Type: <b>Bug</b>

While doing some experimentation with Bootstrap and the corresponding scss files, I encountered an issue while changing hexcolor codes. I was able to reproduce it on a different Windows machine (Windows 11 in that case) as well as on macOS (Monterey).

Steps to reproduce:

1.  Open a large css file. In my case, I used [this file](https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss) from the Bootstrap framework.
2.  Start changing a color by typing a different hex value. The issue only happened when changing at least two of the six digits and sometimes only after making a couple of changes. It did not happen when using the color picker.
3. VSCode will become unresponsive eventually. For example the color pickers do not show up anymore, saving a file takes multiple seconds and the git integration stops working entirely.

When the builtin SCSS extension is disabled, everything works fine. Therefore I would assume that this extension is causing the issue.

---

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 3792)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.13GB free)|
|Process Argv|. --crash-reporter-id 14734666-610e-4444-bcab-9be4361cb08b|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop341:30404997
vsrem710cf:30416617

```

</details>

### PR DESCRIPTION
**Pull request by tharbakim**
This PR fixes #142109

### CODE REVIEW

File: extensions/emmet/src/util.ts [hunk 1]
```diff
@@ -227,10 +227,14 @@ export function parsePartialStylesheet(document: vscode.TextDocument, position:
...
 		if (stream.peek() === slash) {
-			if (stream.backUp(1) === star) {
-				stream.pos = findOpeningCommentBeforePosition(stream.pos) ?? startOffset;
-			} else {
-				stream.next();
+			switch (stream.backUp(1)) {
+				case star:
+					stream.pos = findOpeningCommentBeforePosition(stream.pos) ?? startOffset;
+					break;
+				case slash:
```
Comment (rzhao271) [inline extensions/emmet/src/util.ts:234]: I wonder if this might affect `//` comments?
Also, if the issue only occurs when we're at offset 0, then I'm thinking we can check for that instead.
There's `document.offsetAt` and `document.positionAt` to convert back and forth.

Comment (tharbakim) [reply extensions/emmet/src/util.ts]: I don't believe `//` comments should be effected, as the same loop checks the entire line for the presence of `//`. Yes, some lines that only have one character on them may be skipped, but it isn't possible to have `//` on a line with one character.

I initially approached the resolution this way as I thought it was possible to trigger the issue with positions that aren't offset 0, but I now believe it isn't possible. You're right, checking that we're currently at offset 0 is the better fix. I'll modify this PR to check for start of file.

**Review by rzhao271 — APPROVED** [review]
Good check, thanks!
