### PR TITLE
fix next/prev navigation in the accessible view

### LINKED ISSUE #221497: go to next/previous in the accessible view no longer work
1. run a few chat responses
2. open the accessible view
3. try to go to next and previous 
4. 🐛 chat list is focused instead

### LINKED ISSUE #221521: go to next/previous in accessible view for inline completions doesn't work
I noticed this when working on #221497, which has a different cause I am currently fixing. Wanted to note that it doesn't work _before_ my changes here 😄 

https://github.com/user-attachments/assets/2777805a-2dff-4751-a5be-3da51a7e2194

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #221497
fixes https://github.com/microsoft/vscode/issues/221521

When I got rid of calling `show` directly on the `AccessibleViewService` from within implementations of accessible views with the adoption of the `AccessibleViewRegistry`, https://github.com/microsoft/vscode/pull/212138, it broke `next/previous navigation` in the accessible view.

This was for the best - as before, in order to navigate to the `next/previous`, we would focus the actual element, which would hide the view, and reopen the view entirely. 

This was not reliable and involved hacks to make it work. Furthermore, we had to alert screen reader users to indicate the focus change that was happening. Now, we have a better approach for `next/previous` navigation, and we use it - implementations provide string values in their `provideNextContent/providePreviousContent` functions, and the `AccessibleViewService` takes care of the rest.

As a result, the content of the accessible view is updated and there's no focus change.

There were a few places where we were returning `''` from `provideContent`, which should never happen. I've improved the `when` clauses so providers only get created if there's going to be content and will throw now for unexpected cases. @hediet and @alexr00 inline completions and comments are examples of that if you want to look at those changes.

### CODE REVIEW

File: src/vs/editor/contrib/inlineCompletions/browser/inlineCompletionsAccessibleView.ts [hunk 1]
```diff
@@ -3,13 +3,21 @@
  *  Licensed under the MIT License. See License.txt in the project root for license information.
  *--------------------------------------------------------------------------------------------*/
 
+import { Emitter, Event } from 'vs/base/common/event';
+import { ICodeEditor } from 'vs/editor/browser/editorBrowser';
 import { ICodeEditorService } from 'vs/editor/browser/services/codeEditorService';
 import { InlineCompletionContextKeys } from 'vs/editor/contrib/inlineCompletions/browser/inlineCompletionContextKeys';
 import { InlineCompletionsController } from 'vs/editor/contrib/inlineCompletions/browser/inlineCompletionsController';
```
Comment (meganrogge) [inline src/vs/editor/contrib/inlineCompletions/browser/inlineCompletionsAccessibleView.ts:10]: test comment 1

File: src/vs/editor/contrib/inlineCompletions/browser/inlineCompletionsAccessibleView.ts [hunk 2]
```diff
@@ -18,44 +26,62 @@ export class InlineCompletionsAccessibleView implements IAccessibleViewImplentat
...
-					model.next();
-					setTimeout(() => resolveProvider(), 50);
-				},
-				() => {
-					model.previous();
-					setTimeout(() => resolveProvider(), 50);
-				},
-			);
+		const editor = codeEditorService.getActiveCodeEditor() || codeEditorService.getFocusedCodeEditor();
+		if (!editor) {
```
Comment (meganrogge) [inline src/vs/editor/contrib/inlineCompletions/browser/inlineCompletionsAccessibleView.ts:30]: test comment 2

**Review by mjbvz — APPROVED** [review]
