### PR TITLE
Send ctrl c sequence to terminal when ctrl c is pressed on an ipad

### LINKED ISSUE #114009: iPadOS: Ctrl + C in terminal doesn’t kill running process
## Description 

Hitting `ctrl` + `c` with the terminal focused and a process running (i.e. `yarn start` in a React app) does not kill the process. 

If someone is able to provide a good starting point, I would be willing to take a stab at this.

- VSCode Version: 1.53.0-insider
- OS Version: iPadOS 14.1 (18A8395)
- Commit: 01089c0a5052432594a177f90ad9f3148ec2a6a2
- Date: 2021-01-07T05:25:51.740Z (16 hrs ago)
- Browser: Mozilla/5.0 (iPad; CPU OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.77 Mobile/15E148 Safari/604.1

## Steps to Reproduce:

1. On iPad, open Codespaces environment in Chrome
2. Open integrated Terminal
3. Start application (i.e. like a create-react-app - `yarn start`)
4. Focus terminal and hit `ctrl` + `c`

## Expected

Process (`yarn start`) should stop running

## Actual
Terminal receives new line

https://user-images.githubusercontent.com/3806031/103948200-a11ad800-50f6-11eb-8cb4-87e951735911.MP4

Does this issue occur when all extensions are disabled?: Yes

Related:
- https://github.com/cdr/code-server/issues/1343

### PR DESCRIPTION
**Pull request by meganrogge**

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 1]
```diff
@@ -568,6 +569,10 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 				this.hasHadInput = true;
 			}
 
+			if (isIPad && event.key === 'c' && standardKeyboardEvent.ctrlKey) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:572]: This would be better put into VS Code's keybinding system, rather than inline in the terminal's key processing. So a special `isIPad` keybinding here: https://github.com/Microsoft/vscode/blob/3021226eefdfc149c0b7b7f3a4a162524ada01e6/src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts#L116-L116

That way it will show up in keybindings.json, can be removed, is more declarative, etc.

**Review by Tyriar — CHANGES_REQUESTED** [review]
Good to merge after the one comment
