### PR TITLE
Disable `installation folder` banner warning when debugging extensions

### LINKED ISSUE #251262: Disable `installation folder` banner warning when debugging extensions
when debugging extensions a useless banner pops up when adding the extensions folder to the workspace

```js
Files you store within the installation folder ('{0}') may be OVERWRITTEN or DELETED IRREVERSIBLY without warning at update time.
```
why is it when I'm debugging extensions, does VSCode complain that I'm looking at the extension files??

PR:
* https://github.com/microsoft/vscode/pull/244305

Steps to Reproduce:

1. Debug any VSCode extension
2. add VSCodes installed extensions folder to the workspace
  https://code.visualstudio.com/docs/configure/extensions/extension-marketplace#_where-are-extensions-installed
4. reload the window
5. Banner pops up

Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: v1.100.3
- OS Version: Windows 11

### PR DESCRIPTION
**Pull request by RedCMD**
fixes https://github.com/microsoft/vscode/issues/251262

related
#176164
#225801

disables warning banner when debugging extensions

image

### CODE REVIEW

**Review by Abdullah4345 — COMMENTED** [review]
Nice

**Comment by bpasero** [comment]
How is this related at all to the referenced issues?

**Comment by RedCMD** [comment]
doesn't fix the issues
but is step in right direction

**Comment by RedCMD** [comment]
shall I create a new issue for this then?

**Comment by RedCMD** [comment]
* https://github.com/microsoft/vscode/issues/251262

File: src/vs/workbench/electron-sandbox/window.ts [hunk 1]
```diff
@@ -704,7 +704,7 @@ export class NativeWindow extends BaseWindow {
 		})();
 
 		// Installation Dir Warning
-		if (this.environmentService.isBuilt) {
+		if (this.environmentService.isBuilt && !this.environmentService.debugExtensionHost.debugId) {
```
Comment (bpasero) [inline src/vs/workbench/electron-sandbox/window.ts]: Should this be `extensionDevelopmentLocationURI` to scope it down really to extension development scenarios only?

**Review by bpasero — CHANGES_REQUESTED** [review]

**Review by bpasero — COMMENTED** [review]
There also appear to be conflicts.

File: src/vs/workbench/electron-sandbox/window.ts (hunk 1 above)
Comment (RedCMD) [reply src/vs/workbench/electron-sandbox/window.ts]: done

**Review by bpasero — APPROVED** [review]

**Review by sandy081 — APPROVED** [review]
