### PR TITLE
fix: new command stageAllMerge

### LINKED ISSUE #96640: Source Control stages Merge Changes when trying to stage all Changes
Issue Type: <b>Bug</b>

During a rebase (not sure if that's the only scenario), my SOURCE CONTROL tab display three sections, MERGE CHANGES, STAGED CHANGES and CHANGES. 

If I click the + button on the CHANGES section, in order to stage all items below CHANGES, VS Code also adds everything on MERGE CHANGES.

VS Code version: Code - Insiders 1.45.0-insider (4bd206856db30c27d38aa0f1fbe74bac6156edc7, 2020-04-29T05:33:59.143Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (1.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.5.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
plantuml|jeb|2.13.8
svg|joc|1.1.8
vscode-peacock|joh|3.7.0
chat|kar|0.33.0
rust-analyzer|mat|0.2.151
vscode-todo-parser|min|1.9.1
remote-wsl|ms-|0.44.2
vsliveshare|ms-|1.0.2104
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.3.4
vscode-xml|red|0.11.0
vscode-yaml|red|0.7.2
crates|ser|0.4.9
vscode-hexdump|sle|1.7.2
markdown-all-in-one|yzh|2.8.0

</details>

### PR DESCRIPTION
**Pull request by pfongkye**
This PR fixes #96640 

First attempt in using stageAllUntracked instead of stageAll on changes.
@joaomoreno can you tell me if I'm on the right track please?
Or should I implement a new command?
Also, let me know if I need to add tests.
Thanks.

### CODE REVIEW

**Comment by pfongkye** [comment]
Also, do I need to change https://github.com/microsoft/vscode/blob/62ebd1cdb23edb3d75c225e46633893fc3f4b88f/extensions/git/package.json#L925?

File: extensions/git/src/commands.ts [hunk 1]
```diff
@@ -1076,7 +1076,9 @@ export class CommandCenter {
 			.filter(r => r.type === Status.UNTRACKED || r.type === Status.IGNORED);
 		const uris = resources.map(r => r.resourceUri);
 
-		await repository.add(uris);
+		if (uris.length > 0) {
```
Comment (pfongkye) [inline extensions/git/src/commands.ts:1079]: Trying to fix the following scenario (when clicking the + when no changes):
image
The actual result: 
image
The expected result:
image

File: extensions/git/package.json [hunk 2]
```diff
@@ -932,7 +932,7 @@
           "group": "inline"
         },
         {
-          "command": "git.stageAll",
+          "command": "git.stageAllUntracked",
```
Comment (joaomoreno) [inline extensions/git/package.json:935]: This command would still be wrong, since users would simply like to stage all files which are *not* in the merge group. And this command would simply stage all untracked files.

Comment (pfongkye) [reply extensions/git/package.json:935]: So we need to implement a new command then?

Comment (joaomoreno) [reply extensions/git/package.json:935]: I believe we should yes, it should be visible only when there are actually Merge changes present.

Comment (pfongkye) [reply extensions/git/package.json:935]: OK. I'll try to do this. Thanks 👍

Comment (pfongkye) [reply extensions/git/package.json]: Hello @joaomoreno 
I've updated the branch with a new command `git.stageAllButMerge` which will be visible if `git.hasMergeChanges` is true.
If I'm on the right track, I will implement the `cleanAllButMerge` command also and add any test necessary (smoke tests?)
Also, I'm not quite sure if I'm setting the context `git.hasMergeChanges` at the right place in the code or if it's the right way to implement this.
Cheers.

Comment (joaomoreno) [reply extensions/git/package.json]: Unfortunately contexts are global, so this won't work, since one can have multiple repositories open.

Let's try another approach: let's just have the `stageAll` command simply stage all but the merged changes. And then have a new command `stageAllMerge` which would stage all merge conflicting files, and we'd put that command to the right of the `MERGE CHANGES` section, what do you think?

Comment (pfongkye) [reply extensions/git/package.json]: This sounds a better approach than mingling with global contexts. It feels like a better separation of concerns. I'll make the necessary modifications.
 But how about the naming, we keep `stageAll` name or we make it more explicit?

Comment (joaomoreno) [reply extensions/git/package.json]: We gotta keep that name, yeah, since other extensions might already depend on it. No worries about that. 👍  Looking forward to the changes!

Comment (pfongkye) [reply extensions/git/package.json]: :+1:

Comment (swapnilmisal) [reply extensions/git/package.json]: @joaomoreno @pfongkye I have opened a PR #97386 that keeps the same name `stageAll` across all the resource groups.
It's basically done based on the fact that reference for the resource group is sent to the stageAll function as a second argument. So that we can use this reference to fetch files that are needed to be staged.
let me know what do you think.

**Comment by joaomoreno** [comment]
Thanks! 🍻
