### PR TITLE
copy from terminal doesn't work #31902

### LINKED ISSUE #31902: Copy from terminal doesn't work [Windows/Insiders]
Steps to Reproduce:

1. open the integrated terminal and have it output some text so that scrolling happens
2. scroll up a little and select some text (see screenshot1)
3. press ctrl+c
4. press ctrl+v

Screenshot1:
copypaste1

What happens: terminal scrolls to the bottom and the text that was previously in the clipboard (here `that's not what I copied`) is pasted, instead of the one I just copied using ctrl+c

Now, if I don't end the selection (ie: release the left mouse button) before reaching the left side of the screen, it will work:

copypaste2

I am using the latest insider build (211ffdf) on Windows 10 (64bit).

I tried and could not reproduce the problem on a standard cmd prompt.

### PR DESCRIPTION
**Pull request by warpdesign**
Copy from terminal panel didn't work if the mouse was released outside of the _xterm.element: in this case, the `mouseup` event wasn't triggered.

I fixed the problem by adding a boolean to track down when the `mousedown` event is triggered on _xterm.element. In this case, the selection is refreshed when the mouseup event bubbles up to the document.

Fixes #31902

### CODE REVIEW

File: src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts [hunk 1]
```diff
@@ -328,10 +331,20 @@ export class TerminalInstance implements ITerminalInstance {
...
+
+		this._instanceDisposables.push(dom.addDisposableListener(this._xterm.element, 'mousedown', (event: KeyboardEvent) => {
+			// Track down the mousedown event since we may not have the corresponding mouseup:
+			// in case the mouse is released outside of _xterm.element.
+			this._selectionStarted = true;
+		}));
+
+		// We need to listen to the mouseup event up to the document since the user may release the mouse button anywhere
+		// outside of _xterm.element.
+		this._instanceDisposables.push(dom.addDisposableListener(document, 'mouseup', (event: KeyboardEvent) => {
```
Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: I'd prefer if this listener was only active after a mousedown and disposed of itself on mouseup, otherwise this will run on every mouse click. You can probably do this all within the mousedown listener without the need to introduce more properties to `TerminalInstance`.

Also this listener will also make it very easy to implement https://github.com/Microsoft/vscode/issues/36271 :+1:

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts (hunk 1 above)
Comment (warpdesign) [reply src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: Oh you're right: that's much better.

**Comment by nico-onmap** [comment]
@Tyriar I think I made the necessary changes: could you review it again?

This bug is driving me crazy :)

**Comment by warpdesign** [comment]
@Tyriar I think I made the necessary changes: could you review it again?

This bug is driving me crazy :)

**Comment by Tyriar** [comment]
And I'm back! I can't actually seem to reproduce, on mac at least. Am I missing something?

1. Open terminal
2. `ll` (generated a bunch of output)
3. Scroll up a little
4. Select some text, trigger `mouseup` when it's to the left of the terminal panel
5. ctrl/cmd+c
6. ctrl/cmd+v

**Comment by warpdesign** [comment]
I can reproduce it with Windows 10: maybe this is Windows only ?

 1. downloaded insider build
 2. activated the option to copy on selection
 3. select text and release the mouse outside of terminal div
 4. paste: ctrl+v

Nothing is pasted. If I release the mouse inside the terminal div it works as expected.

**Comment by Tyriar** [comment]
@warpdesign yeah you're right, the problem is actually with the Windows only keybinding which is why I couldn't see it

**Review by Tyriar — APPROVED** [review]

**Comment by Tyriar** [comment]
Made a few tweaks, will merge after CI is happy
