### PR TITLE
Fix editor commands context

### LINKED ISSUE #213155: Debt: consolidate and cleanup context methods in `editorCommands.ts`
We now have collected: `getEditorsContext` , `resolveEditorsContext`, `getCommandsContext`, `resolveCommandsContext`, `getMultiSelectedEditorContexts` in `editorCommands.ts` with each having some complexity. 

Challenge for new actions is to know which one to use and for existing actions to call the right thing. Also there is questionable overlap with group identifiers and groups sitting next to each other, so we should consolidate.

### PR DESCRIPTION
**Pull request by benibenj**
All editor commands can use `resolveCommandsContext` to retrieve the editor groups and editors related to the commands context. The function returns a `IResolvedEditorCommandsContext` which groups editors together with their editor group.

I'm not really sure about the names I picked, open for other suggestions for:
- `resolveCommandsContext`
- `IResolvedEditorCommandsContext`
- `IResolvedEditorCommandsContext.groupedEditors`

fixes #213155

### CODE REVIEW

File: src/vs/workbench/browser/parts/editor/editorCommandsContext.ts [hunk 1]
```diff
@@ -0,0 +1,200 @@
...
+import { EditorInput } from 'vs/workbench/common/editor/editorInput';
+import { IEditorGroup, IEditorGroupsService, isEditorGroup } from 'vs/workbench/services/editor/common/editorGroupsService';
+import { IEditorService } from 'vs/workbench/services/editor/common/editorService';
+
+export interface IResolvedEditorCommandsContext {
+	groupedEditors: {
+		group: IEditorGroup;
+		editors: EditorInput[];
+	}[];
+	preserveFocus: boolean;
```
Comment (bpasero) [inline src/vs/workbench/browser/parts/editor/editorCommandsContext.ts:21]: I prefer using `readonly` as much as possible.

File: src/vs/workbench/browser/parts/editor/editorCommandsContext.ts [hunk 2]
```diff
@@ -0,0 +1,200 @@
...
+	if (isEditorGroup(element)) {
+		return { groupId: element.id, editorIndex: undefined, preserveFocus };
+	}
+
+	const group = editorGroupsService.getGroup(element.groupId);
+
+	return { groupId: element.groupId, editorIndex: group ? group.getIndexOfEditor(element.editor) : -1, preserveFocus };
+}
+
+function isGroupOrEditor(element: any): element is IEditorIdentifier | IEditorGroup {
```
Comment (bpasero) [inline src/vs/workbench/browser/parts/editor/editorCommandsContext.ts:184]: I would use `unknown` instead of `any` so that you know you are checking for all cases.

File: src/vs/workbench/browser/parts/editor/editorActions.ts [hunk 3]
```diff
@@ -1169,11 +1171,13 @@ export class ToggleMaximizeEditorGroupAction extends Action2 {
...
 	}
 
-	override async run(accessor: ServicesAccessor, resourceOrContext?: URI | IEditorCommandsContext, context?: IEditorCommandsContext): Promise<void> {
+	override async run(accessor: ServicesAccessor, ...args: unknown[]): Promise<void> {
 		const editorGroupsService = accessor.get(IEditorGroupsService);
 
-		const { group } = resolveCommandsContext(editorGroupsService, getCommandsContext(accessor, resourceOrContext, context));
-		editorGroupsService.toggleMaximizeGroup(group);
+		const resolvedContext = resolveCommandsContext(accessor, args);
+		if (!resolvedContext.groupedEditors.length) {
```
Comment (bpasero) [inline src/vs/workbench/browser/parts/editor/editorActions.ts:1178]: Is the leading `!` wrong here?

**Review by bpasero — CHANGES_REQUESTED** [review]
Looks cleaner than before ✅

File: src/vs/workbench/browser/parts/editor/editorActions.ts (hunk 3 above)
Comment (benibenj) [reply src/vs/workbench/browser/parts/editor/editorActions.ts:1178]: You are right, good catch

**Review by bpasero — APPROVED** [review]
