### PR TITLE
Fix chat session view leak warnings

### LINKED ISSUE #264772: Leak warnings when opening chat sessions view
Testing https://github.com/microsoft/vscode/issues/264256

1. Open chat sessions view

**Bug**
Dev tools shows a number of potential leak warnings

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #264772

- Making everything readonly to prevent easy leaks
- Don't use assignment as this leaks disposable values
- Make sure other disposables are reset in `disposeElement`

### CODE REVIEW

File: src/vs/workbench/contrib/chat/browser/chatSessions.ts [hunk 1]
```diff
@@ -993,18 +993,13 @@ class SessionsRenderer extends Disposable implements ITreeRenderer<IChatSessionI
 		const session = element.element;
 		const sessionWithProvider = session as ChatSessionItemWithProvider;
 
-		// Clear previous element disposables
-		templateData.elementDisposable.clear();
```
Comment (mjbvz) [inline src/vs/workbench/contrib/chat/browser/chatSessions.ts:997]: Already handled in `disposeElement`

**Review by roblourens — APPROVED** [review]
