### PR TITLE
remote: fix exceptions during disconnect stalling window

### LINKED ISSUE #225752: Reloading the window is longer...
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2(user setup)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Use the Remote for ssh open a folder
2. Click **File** -> **Save workspace as ...**
3. Choose a folder to save the workspace file
4. Reload the windows, then we can get a message 'Reloading the window is longer...'😣
image

5. This vscode window is hanged up and can not closed manually.😂
6. The only way to reopen it is force close it by **Task Manager**.

I can give more information if it need. 🙂

### PR DESCRIPTION
**Pull request by connor4312**
Fixes #225752

### CODE REVIEW

**Review by Tyriar — APPROVED** [review]

File: src/vs/workbench/services/extensions/common/abstractExtensionService.ts [hunk 1]
```diff
@@ -201,9 +201,13 @@ export abstract class AbstractExtensionService extends Disposable implements IEx
...
 					// management connection has a chance to send its disconnection message.
-					await this._remoteAgentService.endConnection();
-					await this._doStopExtensionHosts();
-					this._remoteAgentService.getConnection()?.dispose();
+					try {
+						await this._remoteAgentService.endConnection();
+						await this._doStopExtensionHosts();
+						this._remoteAgentService.getConnection()?.dispose();
+					} catch {
+						this._logService.warn('Error while disconnecting remote agent');
```
Comment (rzhao271) [inline src/vs/workbench/services/extensions/common/abstractExtensionService.ts:209]: Nit: would it make sense to include the error message?

Comment (connor4312) [reply src/vs/workbench/services/extensions/common/abstractExtensionService.ts:209]: Probably, though network errors are generally already logged internally by the connection infrastructure so we don't miss a whole lot at the moment
