### PR TITLE
Don't include internal schemes in references/implementation results

### LINKED ISSUE #1055: Functions in Cached Chat files are being discovered as a reference in Visual Studio Code
Hi There

Function names that appear in cached Copilot chat files are being listed in the reference list of functions in the visual studio code editor. Screenshot and Steps to reproduce below.
Q: Is it related to [Problems tab issue](https://github.com/microsoft/vscode/issues/206644)?
I was unsure if this issue was the same or similar to the now resolved issue that was related to Cached Chat files that were being read and reported on in the Problems tab.

Example of the references index above a function that includes Copilot cached chat files:
image

Version: 1.87.2 (user setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Electron: 27.3.2

- VS Code Version: 1.87.2 (user setup)
- OS Version: Windows_NT x64 10.0.22631
- Logs:

Steps to Reproduce:
1. Ask copilot chat to create a function that outputs the numbers 1 to 10 
2. If not already provided, Ask CoPilot show an example of how to use the function.
3. Copy and paste the function from step 1 into a new ps1 or psm1 file.
4. Wait a second or two for Visual Studio Code to add the references link above the function name in your newly created ps file.
5. Click on the references link above the function name and you will see that the Copilot Chats cache files are listed as references.

Edit 27Mar24: Improved the steps to reproduce. After reading the reply from @selfagency I Improved the introductory paragraph at the top of this post.

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes https://github.com/microsoft/vscode-copilot-release/issues/1055

This filters out references to code in chat and walkthroughts. Doing this in core because otherwise we will need each extension/language to add this filtering themselves

### CODE REVIEW

File: src/vs/editor/contrib/gotoSymbol/browser/goToSymbol.ts [hunk 1]
```diff
@@ -14,6 +15,20 @@ import { ITextModel } from 'vs/editor/common/model';
...
 
+function shouldIncludeLocationLink(sourceModel: ITextModel, loc: LocationLink): boolean {
+	// Always allow the location if the request comes from a document with the same scheme.
+	if (loc.uri.scheme === sourceModel.uri.scheme) {
+		return true;
+	}
+
+	// Otherwise filter out locations from internal schemes
+	if (matchesSomeScheme(loc.uri, Schemas.walkThroughSnippet, Schemas.vscodeChatCodeBlock)) {
+		return false;
```
Comment (jrieken) [inline src/vs/editor/contrib/gotoSymbol/browser/goToSymbol.ts:26]: I have recently added `vscodeChatCodeCompreBlock` which I believe should also be blocked. We also have https://github.com/microsoft/vscode/blob/fd518e4db7bcf89d7e19bf29522786d0cd16a9a6/src/vs/platform/markers/common/markerService.ts#L15 which has some overlap but isn't the same. Maybe it is time to pull this into a single/shared place?

**Review by jrieken — CHANGES_REQUESTED** [review]

**Comment by mjbvz** [comment]
I'd like to get this merged but agree we should think about how to handle this more elegantly. Some of it does need to be handled on a case by case basis but maybe there's also some generic list of simple language feature schemes we can support

**Review by roblourens — DISMISSED** [review]

**Review by justschen — APPROVED** [review]

**Review by jrieken — APPROVED** [review]
