### PR TITLE
Fixes #70832: Never guess tabSize when inserting tabs

### LINKED ISSUE #70832: Tabs displayed incorrectly.
Issue Type: <b>Bug</b>

All of the files in our project are 4 space tabs. Recently VSCode will display some of these files at having 2 space tabs. If I open them in another editor or notepad++ they show as having 4 tab spaces.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.96GB (17.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.8.1
coldfusion|ili|1.0.1
indent-rainbow|ode|7.4.0
vscode-react-native|vsm|0.9.0

</details>

### PR DESCRIPTION
**Pull request by alexdima**

### CODE REVIEW

File: src/vs/editor/common/model/indentationGuesser.ts [hunk 1]
```diff
@@ -177,22 +177,26 @@ export function guessIndentation(source: ITextBuffer, defaultTabSize: number, de
 	}
 
 	let tabSize = defaultTabSize;
-	let tabSizeScore = (insertSpaces ? 0 : 0.1 * linesCount);
 
-	// console.log("score threshold: " + tabSizeScore);
+	// Guess tabSize only if inserting spaces...
```
Comment (alexandrudima) [inline src/vs/editor/common/model/indentationGuesser.ts]: @penlv How are you
