### PR TITLE
Fix timeline view leaks event listeners

### LINKED ISSUE #241536: Timeline view leaks event listeners
On OSS:

1. Open a workspace.
2. Open the Timeline view.
3. Open different files one at a time in the editor so the Timeline view refreshes.
4. :bug: The Timeline view leaks event listeners.

```
[30656:0221/145939.131:INFO:CONSOLE(23)] "[LEAKED DISPOSABLE] Error: CREATED via:
    at GCBasedDisposableTracker.trackDisposable (vscode-file://vscode-app/c:/Users/raymondzhao/work/vscode/out/vs/base/common/lifecycle.js:27:23)
    at trackDisposable (vscode-file://vscode-app/c:/Users/raymondzhao/work/vscode/out/vs/base/common/lifecycle.js:198:24)
    at toDisposable (vscode-file://vscode-app/c:/Users/raymondzhao/work/vscode/out/vs/base/common/lifecycle.js:276:18)
    at MutableToken._event (vscode-file://vscode-app/c:/Users/raymondzhao/work/vscode/out/vs/base/common/event.js:876:28)
    at TimelinePane.loadTimelineForSource (vscode-file://vscode-app/c:/Users/raymondzhao/work/vscode/out/vs/workbench/contrib/timeline/browser/timelinePane.js:481:35)
    at TimelinePane.loadTimeline (vscode-file://vscode-app/c:/Users/raymondzhao/work/vscode/out/vs/workbench/contrib/timeline/browser/timelinePane.js:425:36)
    at TimelinePane.setUriCore (vscode-file://vscode-app/c:/Users/raymondzhao/work/vscode/out/vs/workbench/contrib/timeline/browser/timelinePane.js:268:14)
    at TimelinePane.onActiveEditorChanged (vscode-file://vscode-app/c:/Users/raymondzhao/work/vscode/out/vs/workbench/contrib/timeline/browser/timelinePane.js:314:14)
    at Emitter._deliver (vscode-file://vscode-app/c:/Users/raymondzhao/work/vscode/out/vs/base/common/event.js:939:22)
    at Emitter._deliverQueue (vscode-file://vscode-app/c:/Users/raymondzhao/work/vscode/out/vs/base/common/event.js:950:18)", source: vscode-file://vscode-app/c:/Users/raymondzhao/work/vscode/out/vs/base/common/lifecycle.js (23)
```

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes #241536

### CODE REVIEW

File: src/vs/workbench/contrib/timeline/common/timelineService.ts [hunk 1]
```diff
@@ -60,6 +60,8 @@ export class TimelineService implements ITimelineService {
 			return undefined;
 		}
 
+		const disposables = new DisposableStore();
+		disposables.add(tokenSource);
```
Comment (bpasero) [inline src/vs/workbench/contrib/timeline/common/timelineService.ts:64]: This seems wrong: the token source was not created in here, yet is being tracked for disposal?

File: src/vs/workbench/contrib/timeline/browser/timelinePane.ts [hunk 2]
```diff
@@ -601,7 +602,7 @@ export class TimelinePane extends ViewPane {
 				}
 			}
 		}
-		request?.tokenSource.dispose(true);
+		request?.disposables.dispose();
```
Comment (bpasero) [inline src/vs/workbench/contrib/timeline/browser/timelinePane.ts:605]: This misses to cancel the token source, no?

**Review by bpasero — CHANGES_REQUESTED** [review]

**Review by bpasero — DISMISSED** [review]
@jeanp413 please see my last change, I decided to encapsulate the disposable logic internally, I think we shouldn't expose the disposable to the interface outside.

Thanks!

**Review by chrmarti — DISMISSED** [review]

**Review by chrmarti — APPROVED** [review]

**Review by bpasero — APPROVED** [review]
