### PR TITLE
Fixes #17701 - Integrated Terminal Context Menu is triggered via contextmenu event instead of mousedown

### LINKED ISSUE #17701: Integrated terminal context menu should trigger via contextmenu event not mousedown
- VSCode Version: 1.8.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open Integrated terminal
2. Click and hold right mouse button

Expected: nothing happens yet and the context menu shows up on when the user releases the button
Actual: context menu shows up

### PR DESCRIPTION
**Pull request by chirag64**
Before this change, the Context Menu used to show up on mousedown event in the integrated terminal, but on mouseup (contextmenu event) inside the editor. This change is clearly visible on Windows rather than OS X or Linux when you hold the right-click button.

Now the behavior of the context menu of integrated terminal should be consistent with that of the editor

### CODE REVIEW

**Comment by Tyriar** [comment]
Thanks @chirag64, I'll look at this in a week or so since we're in the process of finishing up/verifying the next release.

File: src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts [hunk 1]
```diff
@@ -148,31 +148,32 @@ export class TerminalPanel extends Panel {
...
-					if (terminal.hasSelection()) {
-						terminal.copySelection();
-						terminal.clearSelection();
-					} else {
-						terminal.paste();
-					}
+			}
+		}));
+		this._register(DOM.addDisposableListener(this._parentDomElement, 'contextmenu', (event: MouseEvent) => {
+			if (this._terminalService.configHelper.getRightClickCopyPaste()) {
```
Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts]: Should the right click copy/paste stuff still be in the mousedown handler and cancel the event if it goes off? I think cmd copies/pastes on mousedown rather than mouseup.

Comment (chirag64) [inline src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts]: I can confirm that cmd in Windows copy-pastes on 'mousedown' rather than 'mouseup'. Do you want me to keep the code inside the if condition within 'mousedown' and just move the else condition code in 'contextmenu' event?

Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts]: Yeah I think that's ideal :+1: and make sure the event is canceled such that a `rightClickCopyPaste` `mousedown` event does not trigger the `contextmenu` event.

Comment (chirag64) [inline src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts]: I was thinking I can use the if condition of `getRightClickCopyPaste` in the `mousedown` event and revert the if condition of `getRightClickCopyPaste` in the `contextmenu` event. Not sure how I can `cancel` the triggering of the event any other way, maybe I'm missing something obvious here.

Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts]: Try returning false inside the `mousedown` handler when the rightClickCopyPaste is done, I would expect that to prevent the contextmenu event.

Comment (chirag64) [inline src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts]: Just tried this, returning `false` as the last line inside the if condition of `getRightClickCopyPaste` within `mousedown` event still triggers the `contextmenu` event.

Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts]: Do `event.preventDefault` or `event.stopPropagation()` work?

Comment (chirag64) [inline src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts]: Tried both, but didn't work. I was sure one of these would work.

Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts]: One last try: `stopImmediatePropagation()` :stuck_out_tongue:

Comment (chirag64) [inline src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts]: Tried all 4 together, no luck. ☹

Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts]: Well we don't want to regress with right click copy paste so we'll probably want to keep a boolean member variable that we'll use to "cancel" the contextmenu event.

**Comment by chirag64** [comment]
@Tyriar Can you please review my recent commit 184e728? I've added a boolean variable that we can use to 'cancel' the contextmenu event.

**Comment by Tyriar** [comment]
Perfect! Thanks for the contribution 😃
