### PR TITLE
Fix remote explorer views getting changed across windows

### LINKED ISSUE #112200: Remote explorer showing more than 1 view at the time (though one is dead)
Not sure how I got into this state exactly, but I did have both a Codespace and a WSL session open. I closed the WSL session, and went back to the Codespace and saw this:

image

The GitHub Codespaces view seems dead -- refresh doesn't do anything, while the WSL view seems to work.

If I switch views via the dropdown, then it fixed things.

I also for some reason seem to have 2 Codespaces items in the dropdown:

image

The GitHub Codespaces one works, while the other wants me to sign in via the Azure account extension (which isn't installed)

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #112200

### CODE REVIEW

File: src/vs/workbench/api/browser/viewsExtensionPoint.ts [hunk 1]
```diff
@@ -501,7 +501,8 @@ class ViewsExtensionHandler implements IWorkbenchContribution {
 						originalContainerId: entry.key,
 						group: item.group,
 						remoteAuthority: item.remoteName || (<any>item).remoteAuthority, // TODO@roblou - delete after remote extensions are updated
-						hideByDefault: initialVisibility === InitialVisibility.Hidden
+						hideByDefault: initialVisibility === InitialVisibility.Hidden,
+						workspace: viewContainer?.id === REMOTE ? true : undefined
```
Comment (rheh) [inline src/vs/workbench/api/browser/viewsExtensionPoint.ts:505]: As far as I can tell from the interface workspace is a boolean so is the ternary required?  Could we simplyfy to:
```
workspace: viewContainer?.id === REMOTE
```

**Review by sandy081 — APPROVED** [review]
LGTM
