### PR TITLE
Command inputs should be consistent with keybindings

### LINKED ISSUE #72935: It's not possible to give an args array on inputs.
I am trying to use an input in tasks.json

`    "inputs":
    [{
        "id": "terminate",
        "type": "command",
        "command": "workbench.action.tasks.terminate",
        "args": ["terminateAll"]
    }]`

However it doesn't work since somehow "args" seems to accept only an object. Now, I know "args" is also meant to be an array in other parts of vscode, for instance:

`{
		"key": "ctrl+shift+alt+t",
		"command": "workbench.action.tasks.terminate",
		"args": ["terminateAll"]
	}
`
After reading vscode's code, I couldn't figure out how to solve this issue.

The task I want to terminate is the "preLaunchTask" for debug, and I want to terminate it in the "postDebug" task.

I use the "preLaunchTask" to launch a game boy advance emulator that runs a gdb server. All I want is to terminate the task "preLaunchTask" without any prompt when the debugging is done.
Thank you!
Paul.

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #72935

### CODE REVIEW

File: src/vs/workbench/services/configurationResolver/common/configurationResolver.ts [hunk 1]
```diff
@@ -57,7 +57,7 @@ export interface CommandInputInfo {
 	id: string;
 	type: 'command';
 	command: string;
-	args?: any;
+	args?: any[];
```
Comment (weinand) [inline src/vs/workbench/services/configurationResolver/common/configurationResolver.ts]: Changing args to be an array breaks all old launch configs not using arrays. So we will have to support both `any | any[]`.

File: src/vs/workbench/services/configurationResolver/common/configurationResolverSchema.ts [hunk 2]
```diff
@@ -102,7 +102,7 @@ export const inputsSchema: IJSONSchema = {
 								description: nls.localize('JsonSchema.input.command.command', "The command to execute for this input variable.")
 							},
 							args: {
-								type: 'object',
+								type: 'array',
```
Comment (weinand) [inline src/vs/workbench/services/configurationResolver/common/configurationResolverSchema.ts]: Changing args to be an array breaks all old launch configs not using arrays. So we will have to support both: args can be an object or an array of objects.

File: src/vs/workbench/services/configurationResolver/common/configurationResolver.ts (hunk 1 above)
Comment (weinand) [inline src/vs/workbench/services/configurationResolver/common/configurationResolver.ts]: for backward compatibility args need to be `any | any[]`.

File: src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts [hunk 3]
```diff
@@ -555,7 +555,7 @@ class TaskService extends Disposable implements ITaskService {
 		CommandsRegistry.registerCommand({
 			id: 'workbench.action.tasks.runTask',
 			handler: (accessor, arg) => {
-				this.runTaskCommand(arg);
+				this.runTaskCommand(Types.isArray(arg) ? arg[0] : arg);
```
Comment (weinand) [inline src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts]: I do not understand why these changes are needed? The only other place where we have to pass an array instead of a single object is here: https://github.com/microsoft/vscode/blob/7bc29bf67c17608b11e23a8497c8f1de5a0922cf/src/vs/workbench/services/configurationResolver/browser/configurationResolverService.ts#L279

File: src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts [hunk 4]
```diff
@@ -569,15 +569,15 @@ class TaskService extends Disposable implements ITaskService {
 		});
 
 		CommandsRegistry.registerCommand('workbench.action.tasks.reRunTask', (accessor, arg) => {
-			this.reRunTaskCommand(arg);
+			this.reRunTaskCommand(Types.isArray(arg) ? arg[0] : arg);
```
Comment (weinand) [inline src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts]: not needed

File: src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts [hunk 5]
```diff
@@ -569,15 +569,15 @@ class TaskService extends Disposable implements ITaskService {
...
 		});
 
 		CommandsRegistry.registerCommand('workbench.action.tasks.restartTask', (accessor, arg) => {
-			this.runRestartTaskCommand(arg);
+			this.runRestartTaskCommand(Types.isArray(arg) ? arg[0] : arg);
```
Comment (weinand) [inline src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts]: not needed

File: src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts [hunk 6]
```diff
@@ -569,15 +569,15 @@ class TaskService extends Disposable implements ITaskService {
...
 		});
 
 		CommandsRegistry.registerCommand('workbench.action.tasks.terminate', (accessor, arg) => {
-			this.runTerminateCommand(arg);
+			this.runTerminateCommand(Types.isArray(arg) ? arg[0] : arg);
```
Comment (weinand) [inline src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts]: not needed

**Review by weinand — CHANGES_REQUESTED** [review]
Since supporting an args array should not break existing launch configs, we will have to support both an object and an array in the schema. And when launching a command with an args array from an input command, we need to pass all arguments to `commandService.executeCommand` instead of only one.

And we'll have to update the documentation...

File: src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts (hunk 3 above)
Comment (alexr00) [reply src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts]: Since commands in keybindings.json take an array, it seems likely to me that many commands are already written to take an array. This is the case for the terminate task command. Command inputs will be more useful if we don't require existing commands to be rewritten.

File: src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts (hunk 4 above)
Comment (alexr00) [reply src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts]: Removed, since rerun actually ignores.

File: src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts (hunk 5 above)
Comment (alexr00) [reply src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts]: Restart only pays attention to the one string. If an array is passed in, then it can only handle the first element.

File: src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts (hunk 6 above)
Comment (alexr00) [reply src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts]: Terminate only pays attention to one string. If an array is passed in, then it can only handle the first element.

File: src/vs/workbench/services/configurationResolver/common/configurationResolver.ts (hunk 1 above)
Comment (alexr00) [reply src/vs/workbench/services/configurationResolver/common/configurationResolver.ts]: Switched back to any, since that's all-encompassing.

File: src/vs/workbench/services/configurationResolver/common/configurationResolverSchema.ts (hunk 2 above)
Comment (alexr00) [reply src/vs/workbench/services/configurationResolver/common/configurationResolverSchema.ts]: Updated to allow object, array, and also string. This provides backward compatibility and makes it totally consistent with keybindings.

File: src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts (hunk 6 above)
Comment (alexr00) [reply src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts]: Fixed by allowing string as the args.

**Comment by alexr00** [comment]
Tested with various objects and arrays to make sure that the behavior is the same for those between input and commands. They behave the same. The command receives only one argument and can handle it however it wants.
