### PR TITLE
fix: copilot external reporting

### LINKED ISSUE #209055: issue report on copilot does not work
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. command palette -> `Help: Report issue...` -> select copilot
2. fill in some data
3. note that there are no similar issues
4. if logged out of github: preview issue gives a 404 
5. if logged into github: create issue gives a console error

### PR DESCRIPTION
**Pull request by justschen**
fixes https://github.com/microsoft/vscode/issues/209055

### CODE REVIEW

File: src/vs/code/electron-sandbox/issue/issueReporterService.ts [hunk 1]
```diff
@@ -1086,13 +1091,15 @@ export class IssueReporter extends Disposable {
 	private parseGitHubUrl(url: string): undefined | { repositoryName: string; owner: string } {
 		// Assumes a GitHub url to a particular repo, https://github.com/repositoryName/owner.
 		// Repository name and owner cannot contain '/'
-		const match = /^https?:\/\/github\.com\/([^\/]*)\/([^\/]*).*/.exec(url);
+		const match = /^https?:\/\/github\.com\/([^\/]*)\/([^\/]*)$/.exec(url);
```
Comment (justschen) [inline src/vs/code/electron-sandbox/issue/issueReporterService.ts:1094]: this is a tighter parse. 

this makes the assumption that the url we're checking is `https://github.com/repo-owner/repo` and nothing more. (in this case, we're basically grabbing the extension URL from the package.json, not the existing bugsUrl)

Comment (TylerLeonhardt) [reply src/vs/code/electron-sandbox/issue/issueReporterService.ts:1094]: Wouldn't it be better to fix `getExtensionGitHubUrl` so that if the url configured is a discussion URL, then that just returns `''` which seems to already be handled in this code?

Comment (justschen) [reply src/vs/code/electron-sandbox/issue/issueReporterService.ts:1094]: hmm yes that's true, i didn't see that function actually - will have a fix with that instead 😵‍💫

File: src/vs/code/electron-sandbox/issue/issueReporterService.ts [hunk 2]
```diff
@@ -1024,10 +1049,15 @@ export class IssueReporter extends Disposable {
 		const bugsUrl = this.getExtensionBugsUrl();
 		const extensionUrl = this.getExtensionRepositoryUrl();
 		// If given, try to match the extension's bug url
-		if (bugsUrl && bugsUrl.match(/^https?:\/\/github\.com\/(.*)/)) {
+		if (bugsUrl && bugsUrl.match(/^https?:\/\/github\.com\/([^\/]*)\/([^\/]*)\/([^\/]*)$/)) {
```
Comment (TylerLeonhardt) [inline src/vs/code/electron-sandbox/issue/issueReporterService.ts:1052]: This should also allow a repo like: `https://github.com/owner/repo` sometimes people do that.

Comment (TylerLeonhardt) [reply src/vs/code/electron-sandbox/issue/issueReporterService.ts:1052]: Also this regex matches discussions?
image

Comment (TylerLeonhardt) [reply src/vs/code/electron-sandbox/issue/issueReporterService.ts]: This is a real link:
http://github.com/microsoft/vscode-discussions/discussions

Comment (TylerLeonhardt) [reply src/vs/code/electron-sandbox/issue/issueReporterService.ts]: so is this: https://github.com/community/community/discussions

Comment (TylerLeonhardt) [reply src/vs/code/electron-sandbox/issue/issueReporterService.ts]: I feel like we should allow either:
* `https://github.com/org/repo`
* `https://github.com/org/repo/issues`

Comment (justschen) [reply src/vs/code/electron-sandbox/issue/issueReporterService.ts]: hmm good point. maybe we just have the `bugsUrl` requirements for this case be:

`https://github.com/owner/repo` or `https://github.com/owner/repo/issues`

**Review by TylerLeonhardt — APPROVED** [review]
