### PR TITLE
Removed erroneous references to PREFIX environment variable

### LINKED ISSUE #160748: PREFIX environment variable displayed in PS1 in integrated terminal
Type: <b>Bug</b>

In the new shell integration options for Bash and Zsh, VS Code wraps the PS1 prompt variable to support new functionality.
However, when it does this, it *prefixes* the PREFIX environment variable to the existing PS1 when creating the new PS1 prompt. See the picture below for an example.

image

For Bash, the problem is at: https://github.com/microsoft/vscode/blob/29234f0219bdbf649d6107b18651a1038d6357ac/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh#L101
For Zsh, see:
https://github.com/microsoft/vscode/blob/ef7831e9c52d3283a9d309de07da13818a90a910/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh#L94

Steps to reproduce:
1. Using either Bash or Zsh, enable the integrated terminal
2. Assign a value to a variable named PREFIX in the integrated terminal
3. Observe that the value you assigned to PREFIX is prepended to the prompt

The PREFIX environment variable is commonly used across a variety of projects in the Linux world for configuring and building applications (grepping for '\$PREFIX' in some repos I have cloned shows it is used in gcc, and picolibc). This bug is annoying because in my project I use $PREFIX during the build process and it makes the terminal hard to use.

This issue is the cause of #159645.

I can submit a pull request for this if you'd like.

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

### PR DESCRIPTION
**Pull request by CKeilbar**
Closes #160748.

This patch removes references to the PREFIX environment variable in the Bash and Zsh integrated terminals.
Without this change, the PS1 prompt for both of these shells contained $PREFIX, which is a common environment variable users tend to set.

To test these changes:
1. Enable the integrated terminal for Bash or Zsh
2. In the terminal, assign a value to a variable called PREFIX
3. Nothing should happen to the prompt

### CODE REVIEW

**Review by Tyriar — APPROVED** [review]

File: src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh [hunk 1]
```diff
@@ -98,7 +98,7 @@ __vsc_update_prompt() {
 		# means the user re-exported the PS1 so we should re-wrap it
 		if [[ "$__vsc_custom_PS1" == "" || "$__vsc_custom_PS1" != "$PS1" ]]; then
 			__vsc_original_PS1=$PS1
-			__vsc_custom_PS1="\[$(__vsc_prompt_start)\]$PREFIX$__vsc_original_PS1\[$(__vsc_prompt_end)\]"
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh:101]: @Tyriar do you know why this was needed / added before?

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh:101]: I think this came across when switching to starship's method, so probably not needed

**Review by meganrogge — APPROVED** [review]
