### PR TITLE
Check save settings before debug restart

### LINKED ISSUE #149885: Files automatically saved when restarting debugger, even though it is set not to
Issue Type: <b>Bug</b>

Files are not set to save when starting the debugger, and this appears to work correctly only when doing a START, but not a RESTART.

I edit a file, then CTRL+F5 start debugger. File is not saved. Correct.

Then CTRL+SHIFT+F5 to restart debugger, and it automatically saves..... Incorrect.

very frustrating.

image

image

image

image

image

image

image

image

image

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (6.06GB free)|
|Process Argv|--crash-reporter-id 9d1b4a74-6c23-44d3-9db5-383def926efe|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|24.91GB (9.54GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.4
remote-containers|ms-|0.234.0
remote-wsl|ms-|0.66.3
gitlens|eam|12.0.6
restore-terminals|Eth|1.1.7
vscode-graphql|Gra|0.4.4
vsliveshare|ms-|1.0.5561
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.35.0
prisma|Pri|3.14.0
indenticator|Sir|0.7.0
language-stylus|sys|1.15.0
vscodeintellicode|Vis|1.2.21

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

### PR DESCRIPTION
**Pull request by andreamah**
Debugger now checks configuration when restarting.

This PR fixes #149885

### CODE REVIEW

File: src/vs/workbench/contrib/debug/browser/debugService.ts [hunk 1]
```diff
@@ -701,7 +701,7 @@ export class DebugService implements IDebugService {
 	}
 
 	async restartSession(session: IDebugSession, restartData?: any): Promise<any> {
-		await this.editorService.saveAll();
+		await saveAllBeforeDebugStart(this.configurationService, this.editorService);
```
Comment (roblourens) [inline src/vs/workbench/contrib/debug/browser/debugService.ts:704]: When debugging starts, there is some other logic in deciding whether to save, and we should respect that here. For example, extensions, can set a flag to suppress the save:

https://github.com/microsoft/vscode/blob/5bbf85a112e6cd8b024059bc99f6baef2bb43b29/src/vs/workbench/api/browser/mainThreadDebugService.ts#L236-L237

Comment (andreamah) [reply src/vs/workbench/contrib/debug/browser/debugService.ts:704]: I see this in the source code, but I'm looking at the extension API and I'm not seeing the `supressSaveBeforeStart` flag under debug options https://code.visualstudio.com/api/references/vscode-api#DebugSessionOptions

Comment (roblourens) [reply src/vs/workbench/contrib/debug/browser/debugService.ts:704]: That is proposed API: https://github.com/microsoft/vscode/blob/a72212f1f4950dac3bcb7dbfcf805d96adf3c564/src/vscode-dts/vscode.proposed.notebookDebugOptions.d.ts#L27

Comment (andreamah) [reply src/vs/workbench/contrib/debug/browser/debugService.ts:704]: Ideally, `surpressSaveBeforeStart` would be an attribute in `IDebugSessionOptions` so that it could be stored in the session here https://github.com/microsoft/vscode/blob/e790fa3b059584b9d7f187ce461c9adae985698d/src/vs/workbench/contrib/debug/browser/debugSession.ts#L47 and there would be a getter for it (`this._options.surpressSaveBeforeStart`) on the `DebugSession` that could be used when we restart. Is that what you were thinking?

Comment (andreamah) [reply src/vs/workbench/contrib/debug/browser/debugService.ts:704]: However, I also see that `startDebugging` currently takes the `supressSaveBeforeStart` info as an extra argument, so is there a reason why these are separate?

Comment (roblourens) [reply src/vs/workbench/contrib/debug/browser/debugService.ts:704]: Yes, I think what you describe is what we need. The original reason that flag wasn't on the options already was just that we considered it a flag that we need for starting the session, not something that has to stick around as a property of the session. But now since we need it later, I guess it is actually a property of the session.

**Review by roblourens — APPROVED** [review]
