### PR TITLE
notebook editor widgets should be independent by editor type

### LINKED ISSUE #225986: re-opening notebook with repl editor shows an error because of a disposed widget
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. open a saved notebook
2. right click the tab and reopen with the repl editor

:bug:
image

The notebook widgets are only distinct by editor group and resource in the [notebookEditorService](https://github.com/microsoft/vscode/blob/6b35f9e5d32b214bf4bfdecd2dff0de8f683a85a/src/vs/workbench/contrib/notebook/browser/services/notebookEditorServiceImpl.ts#L39), so the same editor widget is resolved for the REPL (opened in the same group with the same resource) and then disposed when the notebook editor is closed.

### PR DESCRIPTION
**Pull request by amunger**
fix https://github.com/microsoft/vscode/issues/225986

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/common/notebookEditorInput.ts [hunk 1]
```diff
@@ -373,9 +373,8 @@ export function isCompositeNotebookEditorInput(thing: unknown): thing is ICompos
 		&& ((<ICompositeNotebookEditorInput>thing).editorInputs.every(input => input instanceof NotebookEditorInput));
 }
 
-export function isNotebookEditorInput(thing: unknown): thing is NotebookEditorInput {
+export function isNotebookEditorInput(thing: EditorInput | undefined): thing is NotebookEditorInput {
 	return !!thing
 		&& typeof thing === 'object'
-		&& thing instanceof NotebookEditorInput
-		&& thing.editorId === NotebookEditorInput.ID;
```
Comment (amunger) [inline src/vs/workbench/contrib/notebook/common/notebookEditorInput.ts:380]: this was wrong, editorId is the notebook type

**Review by rebornix — APPROVED** [review]
