### PR TITLE
Pending edits for vscode.CommentMode.Editing lost when switching file tabs

### LINKED ISSUE #166693: Pending edits for vscode.CommentMode.Editing lost when switching file tabs
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2-dev
- OS Version: web

Steps to Reproduce:

1. Create a `vscode.CommentThread` with a list of comments where one comment has a non-empty `body` and its `mode` set to `vscode.CommentMode.Editing`.
2. Type something in the open editor for that comment.
3. Switch to another file, in another tab. (original file stays open, but is temporarily not shown)
4. Switch back to the file with the comment.

Expected results:

- User input is preserved: the comment opened for edit has the latest content from before switching tabs.

Observed results:

- The comment has the `body` it was originally created with. Unsaved user input is lost.

This seems to happen because `CommentThreadWidget.dispose()` is called when switching tabs and contrary to the "pending comment" from the "Reply" input, any pending content in comments in edit mode is not saved by VS Code.

From what we can tell, there is also currently no way for extensions to be notified (in general, or just before `dispose()`) of unsaved changes of comments in edit mode, which would enable us to manually save these pending edits.

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #166693

### CODE REVIEW

**Review by TylerLeonhardt — APPROVED** [review]

File: src/vs/workbench/contrib/comments/browser/commentNode.ts [hunk 1]
```diff
@@ -88,6 +88,7 @@ export class CommentNode<T extends IRange | ICellRange> extends Disposable {
 	constructor(
 		private commentThread: languages.CommentThread<T>,
 		public comment: languages.Comment,
```
Comment (mlincyy) [inline src/vs/workbench/contrib/comments/browser/commentNode.ts:90]: 1111
