### PR TITLE
Fix: use default paste when only text is pasted

### LINKED ISSUE #186292: Weird selection update when pasting over selection
Testing #186236

Probably unrelated to the new formatted paste. 
1. Select some text in a markdown. For example the word "extensions"
2. Have the word "github" in your clipboard and paste it over the selected "extensions"
3. Notice that "thub" part of "github" is selected. I would expect that nothing is selected. Which is the behaviour I get in non markdown editors

Screenshot 2023-06-27 at 11 25 01

### PR DESCRIPTION
**Pull request by MeghanKulkarni**
Quick fix for ensuring that when the new markdown link provider (PasteLinkEditProvider) does not return a uri edit, the default paste functionality is used. This is to avoid any letters being highlighted & selected after pasting when the "paste as" setting is enabled.

Fix: https://github.com/microsoft/vscode/issues/186292

### CODE REVIEW

File: src/vs/editor/contrib/dropOrPasteInto/browser/copyPasteController.ts [hunk 1]
```diff
@@ -282,6 +282,12 @@ export class CopyPasteController extends Disposable implements IEditorContributi
 					return;
 				}
 
+				// If the PasteLinkEditProvider does not return anything, use the default paste handler
+				if (supportedProviders[0].pasteMimeTypes?.length === 1 && supportedProviders[0].pasteMimeTypes[0] === 'text/plain' && providerEdits.length === 1 && providerEdits[0].id === 'text') {
+					await this.applyDefaultPasteHandler(dataTransfer, metadata, tokenSource.token);
+					return;
+				}
+
```
Comment (joyceerhl) [inline src/vs/editor/contrib/dropOrPasteInto/browser/copyPasteController.ts:290]: Wondering if we could get away with simplifying this condition to match the one on line 274 above? I did a little testing and this seems to also address https://github.com/microsoft/vscode/issues/186343, but please do some testing before accepting this suggestion :) 

```suggestion
				if (providerEdits.length === 1 && providerEdits[0].id === 'text') {
					// Only our default text provider returned edits
					await this.applyDefaultPasteHandler(dataTransfer, metadata, tokenSource.token);
					return;
				}
```

**Review by joyceerhl — APPROVED** [review]

**Review by joyceerhl — APPROVED** [review]
