### PR TITLE
sync xterm's textarea with buffer contents

### LINKED ISSUE #186904: A11y_VisualStudioCodeClient_Terminal_ScreenReader: NVDA/JAWS Announces Blank when Using Arrow Keys on Terminal Commands
**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver".**

## GitHub bugs
#A11ySev2; #A11yTCS; #A11yMAS; #DesktopApp; #Visual Studio Code Client; #WCAG1.3.1; #DesktopApp; #BM-VisualStudioCodeClient-Win32-Aug2022; #NVDA; #Win32; #Win11; #A11yeDAD; #ScreenReader; #FTP; #NVDA; #AINotInScope;

## Actual:

Upon using the left or right arrow key to navigate the characters in the Terminal command, NVDA announces a blank instead of correctly providing the character feedback. 

## Expected:

As the arrow keys are pressed, NVDA should announce the characters in the command being navigated.

## Environment Details:​

Application Name: Visual Studio Code
Version: 1.80.0-insider (user setup)
V8: 10.8.168.25-electron.0
Windows 11 22H2 OS build 25869.1000
Screen Reader: NVDA (2023.1)

## Repro Steps:

1.Launch Terminal in Visual studio Code.
2.Turn on NVDA.
3.In terminal, type any command.
4.Use left/ right arrow key to move NVDA focus within the written command.
5.Check NVDA behavior

## User Impact:

The incorrect feedback provided by NVDA/JAWS affects the accessibility and usability of the Terminal application for users who rely on screen readers. This behavior hinders their ability to navigate and interact with command-line interfaces effectively.

"[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier."

## Attachments:

https://github.com/microsoft/vscode/assets/105198219/8e2b2bad-e04e-4424-ba57-5414199a3f5f

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #186904

### CODE REVIEW

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 1]
```diff
@@ -145,6 +166,7 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
 		//
 		// This is mostly a workaround for Windows but applies to all OS' because of the tsc watch
 		// case.
+
```
Comment (meganrogge) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:169]:
```suggestion
```

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 2]
```diff
@@ -422,6 +422,14 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 				});
 			} else if (e === TerminalCapability.CommandDetection) {
 				const commandCapability = this.capabilities.get(TerminalCapability.CommandDetection);
+				commandCapability?.onRequestWriteToTextArea(text => {
+					const textArea = this.xterm?.raw.textarea;
+					if (textArea) {
+						// Sync the textarea using shell integration so screen
+						// readers can read the command
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:429]:
```suggestion
						// readers can review the command with left/ right arrow keys
```

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 3]
```diff
@@ -110,9 +110,12 @@ export class CommandDetectionCapability extends Disposable implements ICommandDe
 	readonly onCommandInvalidated = this._onCommandInvalidated.event;
 	private readonly _onCurrentCommandInvalidated = this._register(new Emitter<ICommandInvalidationRequest>());
 	readonly onCurrentCommandInvalidated = this._onCurrentCommandInvalidated.event;
+	private readonly _onRequestWriteToTextArea = this._register(new Emitter<string>());
+	readonly onRequestWriteToTextArea = this._onRequestWriteToTextArea.event;
 
 	constructor(
 		private readonly _terminal: Terminal,
+		private readonly _isScreenReaderOptimized: boolean,
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:118]: Since we only want this to run on the renderer side, not the pty host, I think we should have a component that builds on `ICommandDetectionCapability` similar to `MarkNavigationAddon`

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 4]
```diff
@@ -422,6 +422,14 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 				});
 			} else if (e === TerminalCapability.CommandDetection) {
 				const commandCapability = this.capabilities.get(TerminalCapability.CommandDetection);
+				commandCapability?.onRequestWriteToTextArea(text => {
+					const textArea = this.xterm?.raw.textarea;
+					if (textArea) {
+						// Sync the textarea using shell integration so screen
+						// readers can review the command with left/ right arrow keys
+						textArea.textContent = text;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:430]: We also want to sync the cursor position

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Comment by meganrogge** [comment]
@Tyriar mostly working now, except if I do `cmd+backspace`. When I put a breakpoint here, it works 🤔 

https://github.com/microsoft/vscode/assets/29464607/9aaaa6fa-69a4-4577-8755-fe69971a9127

https://github.com/microsoft/vscode/blob/84f841784d7cd3d77f329929500d9e29cd860976/src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts#L283

File: src/vs/workbench/contrib/terminal/browser/media/xterm.css [hunk 5]
```diff
@@ -78,6 +78,19 @@
...
+	opacity: 1 !important;
+	left: 0 !important;
+	width: fit-content !important; */
+}
+
+.monaco-workbench .xterm .xterm-helper-textarea:focus {
+	/* Override the general vscode style applies `opacity:1!important` to textareas */
+	opacity: 0 !important;
+
+	/** Uncomment the below for testing purposes */
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/media/xterm.css:92]:
```suggestion
	/** Uncomment the below for textarea testing purposes */
```

**Comment by meganrogge** [comment]
surprising errors given I didn't change this line 🤔 https://github.com/microsoft/vscode/blob/e151ba5aca1227cdebeb57ea1e6cbea80bb16872/src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts#L14-L16

File: src/vs/workbench/contrib/terminal/browser/xterm/textAreaSyncAddon.ts [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+	cursorX: number;
+}
+
+export class TextAreaSyncAddon extends Disposable implements ITerminalAddon {
+	private _terminal: Terminal | undefined;
+	private readonly _onDidRequestUpdateTextArea = this._register(new Emitter<ITextAreaData>());
+	readonly onDidRequestUpdateTextArea = this._onDidRequestUpdateTextArea.event;
+	activate(terminal: Terminal): void {
+		this._terminal = terminal;
+		this._register(this._terminal.onCursorMove(() => this._refreshTextArea()));
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/textAreaSyncAddon.ts:23]: You should listen to accessibility mode changed and only have this listener installed when it's on, otherwise we have an event handler firing a lot without getting handled. `MutableDisposable` will be handy for keeping the optional onCursorMove listener.

File: src/vs/workbench/contrib/terminal/browser/xterm/textAreaSyncAddon.ts [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+				// Left prompt
+				content = line.substring(currentCommand.commandStartX).trim();
+				commandStartX = currentCommand.commandStartX;
+			} else if (currentCommand.commandRightPromptStartX) {
+				// Right prompt
+				content = line.substring(0, currentCommand.commandRightPromptStartX).trim();
+				commandStartX = 0;
+			}
+			if (commandStartX) {
+				this._onDidRequestUpdateTextArea.fire({ content, cursorX: buffer.cursorX - commandStartX });
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/textAreaSyncAddon.ts]: Can we only update when it differs from `this._terminal.textarea.value`?

Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/textAreaSyncAddon.ts]: No need to handle the event or bring `XtermTerminal` into this since `textarea` is on xterm.js' public API. With this it should be able to live entirely in `terminalContrib/accessibility`, reducing complexity of the core code.

File: src/vs/workbench/contrib/terminal/browser/media/terminal.css [hunk 8]
```diff
@@ -248,11 +248,6 @@
 	top: 0;
 }
 
-.monaco-workbench .xterm .xterm-helper-textarea:focus {
-	/* Override the general vscode style applies `opacity:1!important` to textareas */
-	opacity: 0 !important;
-}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/media/terminal.css:254]: I think we need this?

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/media/terminal.css (hunk 8 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/media/terminal.css:254]: Moved that to xterm.css

File: src/vs/workbench/contrib/terminal/browser/media/terminal.css [hunk 9]
```diff
@@ -53,11 +53,28 @@
...
+	/* Override the general vscode style applies `opacity:1!important` to textareas */
+	opacity: 0 !important;
+}
+
 .monaco-workbench .terminal-tab::before {
 	font-family: 'codicon' !important;
 	font-size: 16px !important;
 }
 
+
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/media/terminal.css:77]:
```suggestion
```

File: src/vs/workbench/contrib/terminal/browser/media/terminal.css (hunk 8 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/media/terminal.css:254]: I moved it up by the other textarea blocks

File: src/vs/workbench/contrib/terminal/browser/media/xterm.css [hunk 10]
```diff
@@ -80,6 +80,11 @@
 	resize: none;
 }
 
+.monaco-workbench .xterm .xterm-helper-textarea:focus {
+	/* Override the general vscode style applies `opacity:1!important` to textareas */
+	opacity: 0 !important;
+}
+
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/media/xterm.css:87]:
```suggestion
```

File: src/vs/workbench/contrib/terminalContrib/accessibility/browser/textAreaSyncAddon.ts [hunk 11]
```diff
@@ -0,0 +1,105 @@
...
+			return;
+		}
+
+		const textArea = this._terminal.textarea;
+		if (!textArea) {
+			this._logService.debug(`TextAreaSyncAddon#refreshTextArea: no textarea`);
+			return;
+		}
+
+		this._logService.debug(`TextAreaSyncAddon#refreshTextArea: content is "${content}"`);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminalContrib/accessibility/browser/textAreaSyncAddon.ts:88]: these logs aren't showing up in the terminal output channel 🤔

**Comment by meganrogge** [comment]
I think this should be a contribution rather than an addon

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 12]
```diff
@@ -755,6 +755,7 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 		const lineDataEventAddon = this._register(new LineDataEventAddon(initialTextWrittenPromise));
 		lineDataEventAddon.onLineData(e => this._onLineData.fire(e));
 		this._lineDataEventAddon = lineDataEventAddon;
+
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:758]:
```suggestion
```

File: src/vs/workbench/contrib/terminalContrib/developer/browser/terminal.developer.contribution.ts [hunk 13]
```diff
@@ -102,3 +107,32 @@ registerTerminalAction({
...
+				const devMode: boolean = this._configurationService.getValue(TerminalSettingId.DevMode) || false;
+				this._xterm?.raw.element?.classList.toggle(this.devModeClass, devMode);
+			}
+		}));
+	}
+	xtermReady(xterm: IXtermTerminal & { raw: Terminal }): void {
+		this._xterm = xterm;
+		if (this._configurationService.getValue(TerminalSettingId.DevMode)) {
+			this._xterm.raw.element?.classList.add(this.devModeClass);
+		}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/developer/browser/terminal.developer.contribution.ts:135]: Can this be put in a private method and called twice?

```ts
const devMode: boolean = this._configurationService.getValue(TerminalSettingId.DevMode) || false;
this._xterm.raw.element?.classList.toggle(this.devModeClass, devMode)
```

File: src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminal.accessibility.contribution.ts [hunk 14]
```diff
@@ -22,8 +22,32 @@ import { ITerminalProcessManager, TerminalCommandId } from 'vs/workbench/contrib
...
+		private readonly _instance: ITerminalInstance,
+		processManager: ITerminalProcessManager,
+		widgetManager: TerminalWidgetManager,
+		@IInstantiationService private readonly _instantiationService: IInstantiationService
+	) {
+		super();
+	}
+	xtermReady(xterm: IXtermTerminal & { raw: Terminal }): void {
+		const addon = this._instantiationService.createInstance(TextAreaSyncAddon, this._instance.capabilities);
+		this._xterm?.raw.loadAddon(addon);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminal.accessibility.contribution.ts:45]:
```suggestion
		xterm.raw.loadAddon(addon);
```

**Review by Tyriar — CHANGES_REQUESTED** [review]
Looks good after the couple of comments

Not sure about the monaco check failure, @hediet do you know why it thinks platform/terminal is part of monaco?

**Review by Tyriar — APPROVED** [review]
