### PR TITLE
fix undefined check, get textarea sync to work for windows

### LINKED ISSUE #186904: A11y_VisualStudioCodeClient_Terminal_ScreenReader: NVDA/JAWS Announces Blank when Using Arrow Keys on Terminal Commands
**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver".**

## GitHub bugs
#A11ySev2; #A11yTCS; #A11yMAS; #DesktopApp; #Visual Studio Code Client; #WCAG1.3.1; #DesktopApp; #BM-VisualStudioCodeClient-Win32-Aug2022; #NVDA; #Win32; #Win11; #A11yeDAD; #ScreenReader; #FTP; #NVDA; #AINotInScope;

## Actual:

Upon using the left or right arrow key to navigate the characters in the Terminal command, NVDA announces a blank instead of correctly providing the character feedback. 

## Expected:

As the arrow keys are pressed, NVDA should announce the characters in the command being navigated.

## Environment Details:​

Application Name: Visual Studio Code
Version: 1.80.0-insider (user setup)
V8: 10.8.168.25-electron.0
Windows 11 22H2 OS build 25869.1000
Screen Reader: NVDA (2023.1)

## Repro Steps:

1.Launch Terminal in Visual studio Code.
2.Turn on NVDA.
3.In terminal, type any command.
4.Use left/ right arrow key to move NVDA focus within the written command.
5.Check NVDA behavior

## User Impact:

The incorrect feedback provided by NVDA/JAWS affects the accessibility and usability of the Terminal application for users who rely on screen readers. This behavior hinders their ability to navigate and interact with command-line interfaces effectively.

"[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier."

## Attachments:

https://github.com/microsoft/vscode/assets/105198219/8e2b2bad-e04e-4424-ba57-5414199a3f5f

### PR DESCRIPTION
**Pull request by meganrogge**
fix #186904

### CODE REVIEW

**Review by Tyriar — DISMISSED** [review]
Looks fairly safe to me 👍

**Comment by meganrogge** [comment]
turns out that did cause issues on mac, so glad I checked.

**Comment by meganrogge** [comment]
saw this working on windows before and now it's not for me 👀

File: src/vs/workbench/contrib/terminalContrib/accessibility/browser/textAreaSyncAddon.ts [hunk 1]
```diff
@@ -100,9 +101,10 @@ export class TextAreaSyncAddon extends Disposable implements ITerminalAddon {
...
 			return;
 		}
-		if (!!currentCommand) {
-			this._currentCommand = commandLine.substring(currentCommand.commandStartX ?? 0);
-			this._cursorX = buffer.cursorX - (currentCommand.commandStartX ?? 0);
+		const startX = isMacintosh ? currentCommand.commandStartX : 0;
+		if (!!currentCommand && !!startX) {
+			this._currentCommand = commandLine.substring(startX);
+			this._cursorX = buffer.cursorX - startX;
 		} else {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/accessibility/browser/textAreaSyncAddon.ts]: Actually, it would be better to encapsulate any workarounds inside `CommandDetectionCapability` using `_isWindowsPty`. We don't want Windows quirks coming outside `CommandDetectionCapability` as then they'll end up being peppered all over the place.

Something I'm a little confused about with this is why command started would not come through at all, since if it does at all `commandStartX` should be a number:

https://github.com/microsoft/vscode/blob/414606b665b564d5ea4cce008531c7b23555bdd0/src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts#L365

Could you look at the sequences and see in which order it comes through? It might be firing before command finished as I think that's the only place we clear `commandStartX`?

https://github.com/microsoft/vscode/blob/414606b665b564d5ea4cce008531c7b23555bdd0/src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts#L517

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminalContrib/accessibility/browser/textAreaSyncAddon.ts [hunk 2]
```diff
@@ -100,7 +100,7 @@ export class TextAreaSyncAddon extends Disposable implements ITerminalAddon {
 			this._logService.debug(`TextAreaSyncAddon#updateCommandAndCursor: no line`);
 			return;
 		}
-		if (!!currentCommand.commandStartX) {
+		if (currentCommand?.commandStartX !== undefined) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/accessibility/browser/textAreaSyncAddon.ts:103]: Much better fix! You shouldn't need the `?` though as we have an early return on `!currentCommand` above:

```suggestion
		if (currentCommand.commandStartX !== undefined) {
```

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Review by Tyriar — APPROVED** [review]
