### PR TITLE
Fix #182013

### LINKED ISSUE #182013: Forward and backward of trackpad in Webview should be disabled?
Does this issue occur when all extensions are disabled?: Yes

Anywhere in the whole workspace except Webview(there may be other places), the trackpad behavior is prohibited, including forward and backward, zoom, etc,  Of course the zoom behavior via (ctrl++/--) is available.   But in Webview area,  forward, backward and zoom of trackpad, can be used.  

It's strange to be able to step back here,  It is easy to misoperate. I think it should probably be disabled here.

image

- VS Code Version:  latest vscode.dev
- OS Version:  Mac os Intel 

Steps to Reproduce:

1.  Open `https://vscode.dev`
2. Open a remote repo or any other folder.
3. Click a markdown file and Preview it, or any other operation that opens the webview
4. Use backward gesture

### PR DESCRIPTION
**Pull request by Kalmaegi**
Fix #182013

### CODE REVIEW

File: extensions/markdown-language-features/src/preview/documentRenderer.ts [hunk 1]
```diff
@@ -103,7 +105,7 @@ export class MdDocumentRenderer {
 				${this._getStyles(resourceProvider, sourceUri, config, imageInfo)}
 				<base href="${resourceProvider.asWebviewUri(markdownDocument.uri)}">
 			</head>
-			<body class="vscode-body ${config.scrollBeyondLastLine ? 'scrollBeyondLastLine' : ''} ${config.wordWrap ? 'wordWrap' : ''} ${config.markEditorSelection ? 'showEditorSelection' : ''}">
+			<body class="vscode-body ${config.scrollBeyondLastLine ? 'scrollBeyondLastLine' : ''} ${config.wordWrap ? 'wordWrap' : ''} ${config.markEditorSelection ? 'showEditorSelection' : ''} ${isWeb ? 'style="overscroll-behavior-x: none;"' : ''}">
```
Comment (mjbvz) [inline extensions/markdown-language-features/src/preview/documentRenderer.ts:108]: Can we just disable `overscroll-behavior-x`. I don't think we want it on desktop either

Comment (weartist) [reply extensions/markdown-language-features/src/preview/documentRenderer.ts]: sure~

**Review by mjbvz — APPROVED** [review]

**Review by meganrogge — APPROVED** [review]
