### PR TITLE
Handle Run Active when terminal executible is WSL

### LINKED ISSUE #36897: Run Active File In Active Terminal doesn't work in WSL (or other non-cmd/powershell shells)
- VSCode Version: 1.17.2
- OS Version: Win10

Steps to Reproduce:

1. Set Terminal to bash
2. Press <Ctrl>+<Shift>+<P> and type "run active file"
3. run command
4. Does not work because path to the file is windows-style and <.> is missing in front.

### PR DESCRIPTION
**Pull request by alexr00**
Note that this only works on Windows builds greater than 17063.
Fixes #36897

### CODE REVIEW

File: src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts [hunk 1]
```diff
@@ -657,22 +657,39 @@ export class RunActiveFileInTerminalAction extends Action {
...
 		let uriPath: string = uri.fsPath;
 		const hasSpace = uriPath.indexOf(' ') !== -1;
-		if (hasSpace && isWindows) {
-			uriPath = '"' + uriPath + '"';
-		} else if (!isWindows) {
-			if (uriPath.indexOf('\\') !== 0) {
-				uriPath = uriPath.replace(/\\/g, '\\\\');
+		if (isWindows) {
+			const exe = this.terminalService.getActiveInstance().shellLaunchConfig.executable;
+			const osVersion = (/(\d+)\.(\d+)\.(\d+)/g).exec(os.release());
```
Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts]: We could expose a `ITerminalInstance.preparePathForTerminal` method which takes a path and quotes it/runs it through `wslpath`, then this stuff is contained inside `TerminalInstance` with similar code (the `os.release()` parsing can be shared).

File: src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts [hunk 2]
```diff
@@ -657,22 +657,39 @@ export class RunActiveFileInTerminalAction extends Action {
...
+			if (osVersion && osVersion.length === 4) {
+				buildNumber = parseInt(osVersion[3]);
 			}
-			const hasDoubleQuote = uriPath.indexOf('"') !== -1;
-			if (!hasSpace && hasDoubleQuote) {
-				uriPath = '\'' + uriPath + '\'';
+			// 17063 is the build number where wsl path was introduced.
+			// Update Windows uriPath to be executed in WSL.
+			if (((exe.indexOf('wsl') !== -1) || ((exe.indexOf('bash.exe') !== -1) && (exe.indexOf('git') === -1))) && (buildNumber >= 17063)) {
+				uriPath = 'runActive="$(wslpath ' + this._escapeNonWindowsPath(uriPath) + ')" && "${runActive}"';
```
Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts]: This can be async as run already returns a promise, we could resolve by shelling out to `wslpath` and send a nicer path to the shell?

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts (hunk 2 above)
Comment (alexr00) [reply src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts]: wslpath can only be run from WSL. I haven't found a better way to do this 😞

Comment (Tyriar) [reply src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts]: Can you run `system32/bash.exe`, `['-c', 'wslpath path']`?

Comment (alexr00) [reply src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts]: From cmd, yes, but not using execFile.
