### PR TITLE
using padding so editor hover is not visible at the same time as selection is made

### LINKED ISSUE #245728: [Annoyance] when selecting code, tooltips can overlap over text I'm selecting.
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.99
- OS Version: MacOS 15.3.2 Sequoia,...

Steps to Reproduce:

1. When I hover over code, I expect tooltip to be shown, but when I click (in area outside of tooltip), and start to "drag", e.g. selecting code, tooltip should go away.
2. Holding left button of mouse and moving cursor over code causes that I'm selecting code I don't see, because tooltip is overlapping it (this makes impossible to select code correctly, as you don't see end position of cursor under tooltip).

### LINKED ISSUE #256835: Hover tooltips are preventing selection
Type: <b>Bug</b>

The issue is really simple: hover tooltips are preventing selection. It looks like there is some timing issue, because it happens only if you are "lucky". See this video:

https://github.com/user-attachments/assets/27c58dd7-6701-48b4-bab2-a0e53e153de5

VS Code version: Code 1.102.1 (Universal) (7adae6a56e34cb64d08899664b814cf620465925, 2025-07-15T16:41:17.147Z)
OS version: Darwin x64 23.6.0
Modes:

<details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
biome|bio|3.1.0
vscode-eslint|dba|3.0.10
vscode-deno|den|3.45.0
gitlens|eam|17.3.1
RunOnSave|eme|0.2.7
prettier-vscode|esb|11.0.0
vscode-highlight|fab|1.9.0
wgsl-literal|ggs|0.0.3
copilot|Git|1.344.0
copilot-chat|Git|0.29.1
black-formatter|ms-|2025.2.0
debugpy|ms-|2025.10.0
python|ms-|2025.10.0
vscode-pylance|ms-|2025.6.2
jupyter|ms-|2025.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.3.0
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
vsliveshare|ms-|1.0.5948
csv-to-table|php|1.4.1
wgsl|Pol|0.1.17
table-editor|ssw|0.3.16
code-spell-checker|str|4.0.47
sort-lines|Tyr|1.12.0
vscode-svg-previewer|vit|0.7.0
vscode-css-variables|vun|2.7.1
vscode-zig|zig|0.6.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
binariesv615:30325510
0bi6i642:31350688
h48ei257:31000450
nativeloc1:31344060
5fd0e150:31155592
dwcopilot:31170013
6074i472:31201624
dwoutputs:31242946
hdaa2157:31222309
copilot_t_ci:31333650
e5gg6876:31282496
pythoneinst12:31285622
c7cif404:31314491
pythonpulldiag:31343502
996jf627:31283433
pythonrdcb7:31342333
usemplatestapi:31297334
0aa6g176:31307128
747dc170:31275177
aj953862:31281341
generatesymbolt:31295002
convertfstringf:31295003
pylancequickfixt:31350061
9d2cg352:31346308
usemarketplace:31343026
nesew2to5:31336538
agentclaude:31350858
nes-diff-11:31337487
replacestringexc:31350595
testaa123:31335226
6abeh943:31336334
yijiwantestdri0626-t:31336930
0927b901:31350571
f76d9909:31348711
7g84e740:31350607
a02b4192-color:31350622

```

</details>

### PR DESCRIPTION
**Pull request by aiday-mar**
fixes https://github.com/microsoft/vscode/issues/245728
fixes https://github.com/microsoft/vscode/issues/256835

### CODE REVIEW

File: src/vs/editor/contrib/hover/browser/hoverUtils.ts [hunk 1]
```diff
@@ -6,12 +6,14 @@
 import * as dom from '../../../../base/browser/dom.js';
 import { IEditorMouseEvent } from '../../../browser/editorBrowser.js';
 
+const PADDING = 3;
```
Comment (Tyriar) [inline src/vs/editor/contrib/hover/browser/hoverUtils.ts]: If you make this a const enum the 3 will be inlined at compile time

**Review by Tyriar — DISMISSED** [review]

File: src/vs/editor/contrib/hover/browser/hoverUtils.ts (hunk 1 above)
Comment (aiday-mar) [reply src/vs/editor/contrib/hover/browser/hoverUtils.ts]: Thanks for the tip

**Review by alexr00 — APPROVED** [review]
