### PR TITLE
Ensure ipynb serializer supports node environments and large # of outputs

### LINKED ISSUE #129212: Can't save notebook because of maximum call stack size exceeded
Issue Type: <b>Bug</b>

I was working on a notebook with lots of print output for debugging.

10min in, I could not save and got a notification of "Maximum call stack size exceeded".

image

The kernel script was still running and printing hefty objects in a loop. I remember once crashing VS Code with long notebook output, so maybe this is related.

Console log:

```
  ERR RangeError: Maximum call stack size exceeded
    at vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ipynb/dist/ipynbMain.js:1
    at Array.reduceRight (<anonymous>)
    at p (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ipynb/dist/ipynbMain.js:1)
    at d (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ipynb/dist/ipynbMain.js:1)
    at Array.map (<anonymous>)
    at vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ipynb/dist/ipynbMain.js:1
    at e.createJupyterCellFromNotebookCell (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ipynb/dist/ipynbMain.js:1)
    at vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ipynb/dist/ipynbMain.js:1
    at Array.map (<anonymous>)
    at e.NotebookSerializer.serialize (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ipynb/dist/ipynbMain.js:1)
    at e.NotebookSerializer.serializeNotebook (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ipynb/dist/ipynbMain.js:1)
    at _.$notebookToData (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85)
    at d._doInvokeHandler (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89)
    at d._invokeHandler (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89)
    at d._receiveRequest (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89)
    at d._receiveOneMessage (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89)
    at vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89
    at u.fire (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
    at l.fire (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
    at vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104
    at u.fire (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
    at l.fire (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
    at r._receiveMessage (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
    at vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65
    at u.fire (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
    at v.acceptChunk (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
    at vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65
    at Socket.w (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104)
    at Socket.emit (events.js:315)
    at addChunk (internal/streams/readable.js:309)
    at readableAddChunk (internal/streams/readable.js:284)
    at Socket.Readable.push (internal/streams/readable.js:223)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188)
```

Extension version: 2021.8.1055544705
VS Code version: Code - Insiders 1.59.0-insider (e8a59bc6f920e731b47f0bc72263e82aba8b796e, 2021-07-22T05:13:00.851Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.25-linuxkit
Fetching remote diagnostics for 'dev-container+7b22686f737450617468223a222f55736572732f64696769746172616c642f7265706f732f6465766469762d6d6574726963732d616e642d616e616c79736573222c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d7d' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (4.25GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Azure Machine Learning @ desktop-linux|
|OS|Linux x64 5.10.25-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (12 x 2400)|
|Memory (System)|13.67GB (11.00GB free)|
|VM|0%|

Fetching remote diagnostics for 'dev-container+7b22686f737450617468223a222f55736572732f64696769746172616c642f7265706f732f6465766469762d6d6574726963732d616e642d616e616c79736573222c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d7d' timed out.
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
00j7a122:30294756
vscod805:30301674
pythonvspyt200:30323110
vscextlang:30310088
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490

```

</details>

### PR DESCRIPTION
**Pull request by DonJayamanne**
This PR fixes #129212

### CODE REVIEW

File: extensions/ipynb/src/helpers.ts [hunk 1]
```diff
@@ -27,6 +27,7 @@ export function getPreferredLanguage(metadata?: nbformat.INotebookMetadata) {
 	return translateKernelLanguageToMonaco(jupyterLanguage || defaultLanguage);
 }
 
+const textDecoder = new TextDecoder();
```
Comment (DonJayamanne) [inline extensions/ipynb/src/helpers.ts:30]: Not sure we need to keep creating this every single time, this should make a tiny bit of dfference, specially with larger output counts

File: extensions/ipynb/src/helpers.ts [hunk 2]
```diff
@@ -108,8 +109,12 @@ function convertJupyterOutputToBuffer(mime: string, value: unknown): NotebookCel
 		} else if (mime.startsWith('image/') && typeof value === 'string' && mime !== 'image/svg+xml') {
 			// Images in Jupyter are stored in base64 encoded format.
 			// VS Code expects bytes when rendering images.
-			const data = Uint8Array.from(atob(value), c => c.charCodeAt(0));
-			return new NotebookCellOutputItem(data, mime);
+			if (typeof Buffer !== 'undefined' && typeof Buffer.from === 'function') {
```
Comment (DonJayamanne) [inline extensions/ipynb/src/helpers.ts:112]: Fixes the issue where previously this part of the code would fail in desktop (node)

File: extensions/ipynb/src/helpers.ts [hunk 3]
```diff
@@ -369,7 +374,7 @@ function convertStreamOutput(output: NotebookCellOutput): JupyterOutput {
 	const outputs = output.items
 		.filter((opit) => opit.mime === CellOutputMimeTypes.stderr || opit.mime === CellOutputMimeTypes.stdout)
 		.map((opit) => convertOutputMimeToJupyterOutput(opit.mime, opit.data as Uint8Array) as string)
-		.reduceRight<string[]>((prev, curr) => (Array.isArray(curr) ? prev.concat(...curr) : prev.concat(curr)), []);
+		.reduceRight<string[]>((prev, curr) => prev.concat(curr), []);
```
Comment (DonJayamanne) [inline extensions/ipynb/src/helpers.ts:377]: Fixes the issue here https://github.com/microsoft/vscode/issues/129212

Comment (rebornix) [reply extensions/ipynb/src/helpers.ts:373]: I'll recommend we stop using `concat` completely. Filed separate issue and suggestions of improving the performance and  memory usage of `convertStreamOutput` https://github.com/microsoft/vscode/issues/129370#issue-952511326

File: extensions/ipynb/src/helpers.ts [hunk 4]
```diff
@@ -381,21 +386,29 @@ function convertOutputMimeToJupyterOutput(mime: string, value: Uint8Array) {
 		return '';
 	}
 	try {
-		const stringValue = new TextDecoder().decode(value.buffer.slice(value.byteOffset));
 		if (mime === CellOutputMimeTypes.error) {
+			const stringValue = textDecoder.decode(value.buffer.slice(value.byteOffset));
```
Comment (roblourens) [inline extensions/ipynb/src/helpers.ts:390]: Oops, the lines that call slice should just be passing the UIntArray, I will fix those when this is merged.

**Review by roblourens — APPROVED** [review]
Thanks!
