### PR TITLE
Retry MCP Auth on a 401

### LINKED ISSUE #270383: MCP OAuth authentication fails to retry after server restart when scopes unchanged
The source of the problem: https://github.com/microsoft/vscode/blob/3ec367371fdb761eaf951bfeeb9b68b61272d21c/src/vs/workbench/api/common/extHostMcp.ts#L735

### Summary
VS Code's MCP client fails to retry OAuth authentication after server restarts when the OAuth scopes remain the same, leading to permanent connection failures until VS Code is restarted.

### Environment
- VS Code version: Latest (1.104.3)
- Extension: Model Context Protocol (MCP) built-in support

### Steps to Reproduce
1. Set up an MCP server with OAuth authentication using in-memory token storage
2. Connect VS Code to the server and complete OAuth flow successfully
3. Restart the MCP server (invalidating all stored tokens)
4. VS Code attempts to reconnect using cached token
5. Server responds with 401 and same WWW-Authenticate scopes as before

### Expected Behavior
VS Code should detect the 401 response and initiate a fresh OAuth flow to obtain a new valid token.

### Actual Behavior
VS Code gives up after the second 401 response and marks the connection as failed with "Server exited before responding to `initialize` request."

### Root Cause Analysis
The issue is in the `_fetchWithAuthRetry` method in `McpHTTPHandle` ([source](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostMcp.ts)):

```typescript
} else {
    // We have auth metadata, but got a 401. Check if the scopes changed.
    const { scopesChallenge } = this._parseWWWAuthenticateHeader(res);
    if (!scopesMatch(scopesChallenge, this._authMetadata.scopes)) {
        // Only retries here if scopes are different
        this._authMetadata.scopes = scopesChallenge;
        await this._addAuthHeader(headers);
        // ... retry logic
    }
    // NO RETRY if scopes match but token is invalid!
}
```

**Problem**: VS Code assumes that if OAuth scopes haven't changed, the cached token should still be valid. It doesn't account for server restarts that invalidate tokens while keeping scopes the same.

### Logs
VS Code client logs show:
```
[trace] Fetching http://localhost:3000/mcp (initial request)
[trace] Fetched: {"status":401} (no auth header)
[trace] Fetching http://localhost:3000/.well-known/oauth-authorization-server 
[trace] Fetched: {"status":200} (discovery successful)
[trace] Fetching http://localhost:3000/mcp with "Authorization":"***"
[trace] Fetched: {"status":401} (cached token rejected)
[info] Connection state: Error 401 status
[error] Server exited before responding to `initialize` request.
```

### Proposed Solution
The `_fetchWithAuthRetry` method should have a fallback when scopes match but authentication fails:

```typescript
} else {
    // We have auth metadata, but got a 401. Check if the scopes changed.
    const { scopesChallenge } = this._parseWWWAuthenticateHeader(res);
    if (!scopesMatch(scopesChallenge, this._authMetadata.scopes)) {
        this._log(LogLevel.Debug, `Scopes changed, updating and retrying`);
        this._authMetadata.scopes = scopesChallenge;
        await this._addAuthHeader(headers);
        if (headers['Authorization']) {
            init.headers = headers;
            res = await doFetch();
        }
    } else {
        // NEW: Retry even with same scopes - token might be invalid due to server restart
        this._log(LogLevel.Debug, `Token rejected but scopes unchanged, forcing fresh token`);
        await this._addAuthHeader(headers);
        if (headers['Authorization']) {
            init.headers = headers;
            res = await doFetch();
        }
    }
}
```

### Additional Context
This affects any MCP server using:
- OAuth authentication 
- In-memory token storage (common in development)
- Server restart scenarios (common in development and deployment)

The issue prevents proper development workflows and reduces the reliability of MCP authentication in production environments with rolling deployments.

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
If we have an Authorization header and still get a 401 when trying to connect to an MCP Server, we should retry with a new auth registration.

This fix was for the local MCP dev loop, where you may use an in-memory OAuth server. If you kill the server and start it again, any tokens will be rejected. This PR allows us to react to that by re-doing the auth flow.

Fixes https://github.com/microsoft/vscode/issues/270383

### CODE REVIEW

File: src/vs/workbench/api/common/extHostMcp.ts [hunk 1]
```diff
@@ -651,10 +651,22 @@ export class McpHTTPHandle extends Disposable {
 		} while (!chunk.done);
 	}
 
-	private async _addAuthHeader(headers: Record<string, string>) {
+	private async _addAuthHeader(headers: Record<string, string>, forceNewRegistration?: boolean) {
```
Comment (dmitrivMS) [inline src/vs/workbench/api/common/extHostMcp.ts:654]: stuff like this can really benefit from unit-tests...

**Review by dmitrivMS — APPROVED** [review]

File: src/vs/workbench/api/common/extHostMcp.ts (hunk 1 above)
Comment (TylerLeonhardt) [reply src/vs/workbench/api/common/extHostMcp.ts:654]: I know, I wanted to unblock the user first. This file doesn't have any unit tests yet, but I am slowly pulling out logic from here and moving into `oauth.ts` that does have unit tests.
