### PR TITLE
Run configurationResolver on terminal env vars

### LINKED ISSUE #34337: Prepending current PATH to PATH defined in "terminal.integrated.env.osx"
- VSCode Version: 1.15.1
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Update workspace settings to something like
```json
{
  "terminal.integrated.env.osx": {
    "PATH": "/home"
  }
}
```
2. Now open Terminal and look at PATH
```bash
echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/home
```

On Windows, having the same setting will not result in the current `PATH` being prepended, but instead, just setting the path to whatever is defined in `terminal.integrated.env.*`

Reproduces without extensions: Yes

### PR DESCRIPTION
**Pull request by ramya-rao-a**
Fixes #34337

### CODE REVIEW

File: src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts [hunk 1]
```diff
@@ -585,16 +589,34 @@ export class TerminalInstance implements ITerminalInstance {
 		if (!this._shellLaunchConfig.executable) {
 			this._configHelper.mergeDefaultShellPathAndArgs(this._shellLaunchConfig);
 		}
-		this._initialCwd = this._getCwd(this._shellLaunchConfig, this._historyService.getLastActiveWorkspaceRoot('file'));
 
-		// Merge process env with the env from config
-		const envFromConfig = { ...process.env };
+		const lastActiveWorkspaceRootUri = this._historyService.getLastActiveWorkspaceRoot('file');
+		const lastActiveWorkspaceRoot = this._workspaceContextService.getWorkspaceFolder(lastActiveWorkspaceRootUri);
```
Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: Let's move this variable down to the other chunk to make it clear that it's not used in the following line.

File: src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts [hunk 2]
```diff
@@ -585,16 +589,34 @@ export class TerminalInstance implements ITerminalInstance {
...
+		this._initialCwd = this._getCwd(this._shellLaunchConfig, lastActiveWorkspaceRootUri);
+
+		// Resolve env vars from config and shell
 		const envSettingKey = platform.isWindows ? 'windows' : (platform.isMacintosh ? 'osx' : 'linux');
-		TerminalInstance.mergeEnvironments(envFromConfig, this._configHelper.config.env[envSettingKey]);
+		const envFromConfig = { ...this._configHelper.config.env[envSettingKey] };
+		Object.keys(envFromConfig).forEach((key) => {
```
Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: This section's getting a bit crazy, how about we organize it like this:

- `mergeEnvironments` now takes a base environment and an array of secondary environments
- The secondary environments are filtered through a `resolveConfigurationVariables`

I think we could then minimize the number of lines dealing with the env in this function and de-duplicate the `_configurationResolverService` parts. What do you think?

Comment (ramya-rao-a) [reply src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: I thought exactly that about the `mergeEnvironments`. Wasnt sure what you'd prefer. I'll make the changes

Comment (ramya-rao-a) [reply src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: One issue with that though is that `mergeEnvironments` is static. Resolving of variables need the `configurationResolverService` and the workspaceRoot

File: src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts [hunk 3]
```diff
@@ -794,14 +799,23 @@ export class TerminalInstance implements ITerminalInstance {
 		}
 	}
 
-	// TODO: This should be private/protected
 	// TODO: locale should not be optional
-	public static createTerminalEnv(parentEnv: IStringDictionary<string>, shell: IShellLaunchConfig, cwd: string, locale?: string, cols?: number, rows?: number): IStringDictionary<string> {
+	protected createTerminalEnv(parentEnv: IStringDictionary<string>, shell: IShellLaunchConfig, cwd: string, locale?: string, cols?: number, rows?: number): IStringDictionary<string> {
```
Comment (ramya-rao-a) [inline src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: @Tyriar How about making createTerminalEnv non static?

Comment (Tyriar) [reply src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: I'm all for that, the only reason it's still like that is because the tests were written that way. It would be better to do protected and inherit in a super testing class. You would probably have to block out the terminal process launching stuff from launching during tests for that to work though which might be too much work for this PR.

File: src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts (hunk 2 above)
Comment (Tyriar) [reply src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: If changing the static is too much work then you can pass in _configurationResolveService as a param.

File: src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts (hunk 3 above)
Comment (ramya-rao-a) [reply src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: In that case, I'll revert that change

**Comment by Tyriar** [comment]
Moved the variable resolving into its own function and tested, looks good :ok_hand: 

image

**Comment by Tyriar** [comment]
Good to merge after CI passes
