### PR TITLE
testing: ensure discovery happens before "run at cursor" executes

### LINKED ISSUE #157656: The "Run Test at Cursor" should save the file and rediscover tests before executing
# Behaviour
The "Run Test at Cursor" command doesn't save the file first.

## Expected vs. Actual
Two notable things happen when this command is executed immediately after making changes to the test in which the cursor lies:
1. The changes you just made will not be executed. The file is saved, though, so if you repeat the command, they will be.
2. If this is the last test in the file, and you've added lines at the end of the file and the cursor is in one of the new lines, the test doesn't execute at all because "the cursor is not inside a test".

The command should save the file and wait for test discovery before checking the cursor position to decide which test to run.

(I am using Pytest)

## Steps to reproduce:

1. Create a test file and create two unit tests. Save the file.
2. Add a new line in the top unit test. Do not save the file. Put the cusor on the first line of the test and execute the command. This new line will not have run.
3. Execute the command again. The line you added will be included.
4. Go to the second unit test in the file. Add a line. Do not save the file. Leave the cursor on that line. Execute the command. You'll observe the test does not execute at all.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Default

languageServer: "Pylance"

linting
• flake8Enabled: true
• flake8Path: "<placeholder>"
• mypyEnabled: true
• mypyPath: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"

testing
• pytestEnabled: true

```

</p>
</details>

### PR DESCRIPTION
**Pull request by connor4312**
With this change, when "run at cursor" is executed, we'll:

1. Save the file
2. Forcefully sync tests from the ext host (normally they're on a 300ms throttle)
3. Wait for `busy = false` on all tests whose URIs are a parent or equal to the current file.

Fixes #157656

### CODE REVIEW

File: src/vs/workbench/contrib/testing/common/testService.ts [hunk 1]
```diff
@@ -156,12 +157,30 @@ export const getAllTestsInHierarchy = async (collection: IMainThreadTestCollecti
...
 
+/**
+ * Waits for the test to no longer be in the "busy" state.
+ */
+export const waitForTestToBeIdle = (testService: ITestService, test: IncrementalTestCollectionItem) => {
+	if (!test.item.busy) {
+		return;
+	}
+
+	return new Promise<void>(resolve => {
```
Comment (connor4312) [inline src/vs/workbench/contrib/testing/common/testService.ts:168]: This could be more efficient, but since it'll be used rarely and never in a very hot path (we'll only be waiting on a single test at any given time, and only when the user runs a command) I think this is fine.

**Review by mjbvz — APPROVED** [review]
