### PR TITLE
Implemented fix for first parameter being a substring of the second p…

### LINKED ISSUE #106129: Signature Help highlighting wrong parameter
Adapted from https://github.com/microsoft/monaco-editor/issues/1986

* `package.json`:
```json
{
    "name": "1986",
    "publisher": "alex",
    "version": "1.0.0",
    "engines": {
        "vscode": "^1.30.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "./index.js"
}
```
* `index.js`:
```js
const vscode = require("vscode");

exports.activate = function () {
  console.log(`I am running!`);
  vscode.languages.registerSignatureHelpProvider(
    "*",
    {
      provideSignatureHelp: (doc, pos) => {
        console.log(`providing signature help`);
        const value = new vscode.SignatureHelp();
        value.signatures = [
          {
            label: "test(param, parameter)",
            parameters: [
              {
                label: "param",
                documentation: "param 1",
              },
              {
                label: "parameter",
                documentation: "param 2",
              },
            ],
          },
        ];
        value.activeSignature = 0;
        value.activeParameter = 0;
        return value;
      },
    },
    "(",
    ","
  );
};
```
* open a plain text file and type `aaa(`
* observe the second parameter getting highlighted:

image

### PR DESCRIPTION
**Pull request by tomerstav**
[
Screen Shot 2020-09-10 at 6 15 57 PM
](url)

Problem was that 'param' was a substring of 'parameter'. Fixed it such that lookup in the signature label requires parameters to either end with a comma or bracket.

This PR fixes #106129

### CODE REVIEW

File: src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts [hunk 1]
```diff
@@ -312,7 +312,7 @@ export class ParameterHintsWidget extends Disposable implements IContentWidget {
 		} else if (Array.isArray(param.label)) {
 			return param.label;
 		} else {
-			const idx = signature.label.lastIndexOf(param.label);
+			const idx = signature.label.lastIndexOf(`${param.label},`) ?? signature.label.lastIndexOf(`${param.label})`);
```
Comment (mjbvz) [inline src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts:315]: I don't think the part after  `??` will ever be executed since `lastIndexOf` always returns a number

**Review by mjbvz — CHANGES_REQUESTED** [review]
@alexdima We allow extensions to return an index range for the parameter. This means that VS Code never has to compute the range itself from the text. I believe that is the approach we want to encourage

File: src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts (hunk 1 above)
Comment (tomerstav) [reply src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts]: Yes that's correct. I have updated my PR. Also took into account these scenarios for idx. Note that I add one because lookup contains additional character at start.
	                //() -> 0
			//(param) -> 1
			//(param, xparam) -> 1
			//(xparam,param) -> 8
			//(xparam,param,yparam) -> 8
			//(xparam, param,yparam) -> 9
			//(xparam, param) -> 9
			//(xparam,param) -> 9

**Comment by alexdima** [comment]
@mjbvz I'm sorry I'm not familiar with this code

ping @joaomoreno

File: src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts [hunk 2]
```diff
@@ -312,8 +312,14 @@ export class ParameterHintsWidget extends Disposable implements IContentWidget {
 		} else if (Array.isArray(param.label)) {
 			return param.label;
 		} else {
-			const idx = signature.label.lastIndexOf(param.label);
-			return idx >= 0
+			const idx = Math.max(
```
Comment (mjbvz) [inline src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts:315]: This fix seems specific to JavaScript style signatures. How about looking for the last match of a regular expression such as `\b${param.label}\b` which would check for the param label surrounded by word boundaries? Not perfect but that way `param` would not match `parameter`

Comment (tomerstav) [reply src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts:315]: Thanks for your feedback. Let me give that a shot

Comment (tomerstav) [reply src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts]: Updated. Let me know what you think

File: src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts [hunk 3]
```diff
@@ -312,9 +312,11 @@ export class ParameterHintsWidget extends Disposable implements IContentWidget {
 		} else if (Array.isArray(param.label)) {
 			return param.label;
 		} else {
-			const idx = signature.label.lastIndexOf(param.label);
+			const regex = new RegExp(`\\b${param.label}\\b`, 'g');
```
Comment (mjbvz) [inline src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts:315]: In case the `param.label` contains special regular expression, make sure to use [`escapeRegExpCharacters`](https://github.com/microsoft/vscode/blob/25ad7485b3aa2dea43ab945b4f6af94cf0537b09/src/vs/base/common/strings.ts#L68)

**Review by mjbvz — CHANGES_REQUESTED** [review]
Looks good overall. Just one minor change and then I think we can merge this

**Comment by mjbvz** [comment]
Thanks! This will be in the next VS Code insiders build and is scheduled to ship with VS Code 1.50

**Comment by tomerstav** [comment]
> Thanks! This will be in the next VS Code insiders build and is scheduled to ship with VS Code 1.50

Awesome happy to help!
