### PR TITLE
always fallback to plain text (#115860)

### LINKED ISSUE #115860: The default extension for untitled files is not .txt
- VSCode Version: 1.53.0 (updated from 1.52)
- OS Version: Windows 10 version 1909 build 18363.1316

Steps to Reproduce:

1. create a new empty file
2. file > save

The proposed extension is the first in the list (example Untitled-1.**bat**).
Expected result: Untitled-1.**txt**

immagine

Does this issue occur when all extensions are disabled?: Yes

.

### PR DESCRIPTION
**Pull request by bpasero**
This PR fixes #115860

Previously we just got lucky that "Plain Text" was the second filter for the dialog but now that we sort the list, this is no longer the case. On Windows there is this weird behaviour in Electron that the second filter will be used as default (not the first). And also there is no API to set the selected one somehow.

### CODE REVIEW

File: src/vs/workbench/services/dialogs/browser/abstractFileDialogService.ts [hunk 1]
```diff
@@ -285,7 +286,7 @@ export abstract class AbstractFileDialogService implements IFileDialogService {
 
 			const filter: IFilter = { name: languageName, extensions: distinct(extensions).slice(0, 10).map(e => trim(e, '.')) };
 
-			if (ext && extensions.indexOf(ext) >= 0 && !matchingFilter) {
+			if (!matchingFilter && extensions.indexOf(ext || PLAINTEXT_EXTENSION /* // https://github.com/microsoft/vscode/issues/115860 */) >= 0) {
```
Comment (isidorn) [inline src/vs/workbench/services/dialogs/browser/abstractFileDialogService.ts:289]: Nitpick: you have double commenting here, remove `//` to make it more readable

**Comment by isidorn** [comment]
Code looks good. I am now verifying this indeed fixes the issue on my Windows vm

File: src/vs/workbench/services/dialogs/browser/abstractFileDialogService.ts (hunk 1 above)
Comment (bpasero) [reply src/vs/workbench/services/dialogs/browser/abstractFileDialogService.ts]: Thanks, pushed a fix.

**Comment by isidorn** [comment]
I have verified this works fine now and plain text as choosen as the default option -> approved

Screenshot 2021-02-09 at 12 13 47

**Review by isidorn — APPROVED** [review]
