### PR TITLE
fix #207712

### LINKED ISSUE #207712: Incorrect link in text "This extension is enabled in the Remote Extension Host because it prefers to run there. Learn More"
Type: <b>Bug</b>

In the below image, clicking the link _Learn More_ brings you to https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-types. However, that section (id) does not exist on https://code.visualstudio.com/api/advanced-topics/remote-extensions.

The link is most likely supposed to go to https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-kinds

image

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.4.0-173-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1245U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.64GB (18.28GB free)|
|Process Argv|--crash-reporter-id 59df0552-792a-4e7c-92f1-327caa3dd76d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vm|
|OS|Linux x64 5.4.0-173-generic|
|CPUs|Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (8 x 2394)|
|Memory (System)|31.32GB (27.86GB free)|
|VM|100%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
yang|mar|0.1.3
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.348.0
remote-ssh|ms-|0.109.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.86.0
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.1
vscode-openapi|42C|4.25.1
vscode-fish|bma|1.0.38
ruff|cha|2024.16.0
vale-vscode|chr|0.18.5
vscode-markdownlint|Dav|0.54.0
gitlens|eam|14.9.0
prettier-vscode|esb|10.1.0
code-runner|for|0.12.1
go|gol|0.41.1
restructuredtext|lex|189.3.0
direnv|mkh|0.17.0
vscode-azureresourcegroups|ms-|0.8.4
vscode-cosmosdb|ms-|0.20.1
vscode-docker|ms-|1.29.0
vscode-kubernetes-tools|ms-|1.3.15
python|ms-|2024.2.1
azure-account|ms-|0.11.6
vscode-yaml|red|1.14.0
code-spell-checker|str|3.0.1
even-better-toml|tam|0.19.2
shellcheck|tim|0.37.0
simple-rst|tro|1.5.4
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30986171
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30981707
cppperfcontrol:30979541
8082a590:30971561
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30958157
dsvsc020:30976470
7ghi1836:30988842

```

</details>

### PR DESCRIPTION
**Pull request by sandy081**
fix #207712

### CODE REVIEW

**Review by lramos15 — APPROVED** [review]

File: src/vs/workbench/contrib/extensions/browser/extensionsActions.ts [hunk 1]
```diff
@@ -2475,23 +2475,23 @@ export class ExtensionStatusAction extends ExtensionAction {
 				if (this.extensionManagementServerService.localExtensionManagementServer === this.extension.server) {
 					if (this.extensionManifestPropertiesService.prefersExecuteOnWorkspace(this.extension.local.manifest)) {
 						if (this.extensionManagementServerService.remoteExtensionManagementServer) {
-							message = new MarkdownString(`${localize('Install in remote server to enable', "This extension is disabled in this workspace because it is defined to run in the Remote Extension Host. Please install the extension in '{0}' to enable.", this.extensionManagementServerService.remoteExtensionManagementServer.label)} [${localize('learn more', "Learn More")}](https://aka.ms/vscode-remote/developing-extensions/architecture)`);
+							message = new MarkdownString(`${localize('Install in remote server to enable', "This extension is disabled in this workspace because it is defined to run in the Remote Extension Host. Please install the extension in '{0}' to enable.", this.extensionManagementServerService.remoteExtensionManagementServer.label)} [${localize('learn more', "Learn More")}](https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-kinds)`);
```
Comment (lramos15) [inline src/vs/workbench/contrib/extensions/browser/extensionsActions.ts:2478]: @digitarald Not sure if we have any guidance on aka.ms vs direct code.visualstudio.com links

Comment (digitarald) [reply src/vs/workbench/contrib/extensions/browser/extensionsActions.ts:2478]: `aka.ms` links help to stay updated and track engagement. The link here could have been updated in aka.ms as well
