### PR TITLE
Node module resolution for CSS import

### LINKED ISSUE #136: Ctrl+click (go to file) doesn't work for saas-loader ~ imports (node_modules)
Trying to Ctrl+click on the imported module name fails:
```scss
@import '~bootstrap/scss/bootstrap';
```
with this error:

```
Unable to open '_bootstrap.scss': File not found (file:///PROJECT/src/styles/~bootstrap/scss/_bootstrap.scss).
```

The reason is that I'm using `webpack` with `saas-loader`, and `saas-loader` treats an import path starting with `~` as an import from `node_modules`: https://github.com/webpack-contrib/sass-loader#imports

So the actual location from where the import should be loaded is:
```
file:///PROJECT/node_modules/bootstrap/scss/_bootstrap.scss
```

### PR DESCRIPTION
**Pull request by penx**
Add 'Go to definition' support for
```css
@import "~bootstrap/dist/css/bootstrap";
```
as per
- https://github.com/webpack-contrib/sass-loader#imports
- https://github.com/webpack-contrib/css-loader#import

Fixes Microsoft/vscode-css-languageservice#136

Also see https://stackoverflow.com/questions/48499853/how-to-jump-to-definition-for-a-file-in-node-modules-from-vs-code

### CODE REVIEW

File: extensions/css-language-features/server/src/utils/documentContext.ts [hunk 1]
```diff
@@ -32,6 +40,12 @@ export function getDocumentContext(documentUri: string, workspaceFolders: Worksp
 					}
 				}
 			}
+			if (ref[0] === '~' && ref[1] !== '/') {
+				const moduleName = getModuleNameFromPath(ref.substring(1));
+				const modulePath = require.resolve(moduleName, { paths: [base] });
```
Comment (penx) [inline extensions/css-language-features/server/src/utils/documentContext.ts]: If the referenced module has "main" set to a sub directory in its package.json, would modulePath refer to the subdir and therefore cause pathInModule to be resolved relative to the wrong directory?

File: extensions/css-language-features/server/src/utils/documentContext.ts [hunk 2]
```diff
@@ -32,6 +40,16 @@ export function getDocumentContext(documentUri: string, workspaceFolders: Worksp
 					}
 				}
 			}
+			// Following [css-loader](https://github.com/webpack-contrib/css-loader#url)
+			// and [sass-loader's](https://github.com/webpack-contrib/sass-loader#imports)
+			// convention, if an import path starts with ~ then use node module resolution
+			// *unless* it starts with "~/" as this refers to the user's home directory.
+			if (ref[0] === '~' && ref[1] !== '/') {
```
Comment (penx) [inline extensions/css-language-features/server/src/utils/documentContext.ts]: I'm not sure how this can be unit tested, I guess I'd need to mock require.resolve, I don't see an equivalent test for
https://github.com/Microsoft/vscode-languageserver-node/blob/master/server/src/resolve.ts

File: extensions/css-language-features/server/src/utils/documentContext.ts [hunk 3]
```diff
@@ -8,6 +8,14 @@ import { endsWith, startsWith } from '../utils/strings';
 import * as url from 'url';
 import { WorkspaceFolder } from 'vscode-languageserver';
 
+function getModuleNameFromPath(path: string) {
```
Comment (penx) [inline extensions/css-language-features/server/src/utils/documentContext.ts]: I could add unit tests for this fairly easily, but that would lead me to put it in its own module, which in turn makes me wonder if there's an existing util in vscode that already does this that I could use instead?

Comment (penx) [reply extensions/css-language-features/server/src/utils/documentContext.ts]: the unit tests for this part of the code (completion.test.ts) only seem to be testing the public API rather than internal functions so I'm not going to add unit tests for now. Happy to take direction on this if you want unit tests adding!

**Comment by penx** [comment]
@octref previous build issues were not related to this PR. All solved now after rebase off master.

Please let me know if you'd like any changes

**Comment by octref** [comment]
You are also in this thread: https://github.com/sass/sass/issues/2350.

I'm not sure if VS Code should add such url resolving mechanism. It's not part of css or sass language, and only comes from some webpack plugins that you have configured. Ping @aeschli

**Comment by penx** [comment]
> some webpack plugins that you have configured

sass-loader and css-loader are the standard webpack loaders for styling and the behaviour this PR supports is for their default behaviour without any additional configuration/

https://webpack.js.org/loaders#styling

These loaders are used by many config-less uses of webpack, e.g. when using create-react-app 

I agree that this isn't in the underlying spec for Sass, however I suspect that a very large number of people using VSCode to write Sass are using sass-loader under the hood. Even more so, I think it's safe to assume that near to 100% of vscode users that encounter `@import "~something";` in a Sass file would be expecting this to be using node module resolution when compiled.

If you're still against this being the default behaviour of "Go to definition" in VSCode then perhaps it can be behind a config option instead? I personally would find this very useful, and I use what I believe are fairly standard build setups for writing CSS/Sass.

**Comment by minkir014** [comment]
Can't you provide autocompletion also??

**Comment by penx** [comment]
Waiting for @aeschli to confirm this feature can be merged first!

**Comment by minkir014** [comment]
@penx This feature is needed too much. if you can do that please post another PR.

**Comment by aeschli** [comment]
@penx Thanks, sorry for the delay!

**Comment by aeschli** [comment]
Tests would be very appreciated. I created a first link tests: ae6be6369818213851ecfc089b8cb7f785d878fe
Would be great if you can add one for your feature.

**Comment by minkir014** [comment]
@penx This PR has finally been merged. Please start another PR that provides variables completion across files.

**Comment by aeschli** [comment]
I had to rewrite the code as we can't use `require`: The code is webpackaged and webpack is very against `require`. See 8f7293470661319099bdda43eecc386a43c87189
@penx You want to look at my changes and fix it if I misunderstood how this works.

**Comment by penx** [comment]
@aeschli sorry for the delay in responding, yes unfortunately what you have written assumes that `join(documentFolder, 'node_modules', _moduleName, 'package.json');` will resolve the correct location, but this will not work in many cases. e.g. nested dependencies, npm link, peerDependencies, yarn PnP, yarn portal.

See:
https://medium.com/@penx/managing-dependencies-in-a-node-package-so-that-they-are-compatible-with-npm-link-61befa5aaca7
https://twitter.com/arcanis/status/1052305689886875648

`require` is exactly what we want here as we want to know where node resolves the file to on disk.

Is it possible that we do something like `if(require)` or `if(webpacked)` and use require only in safe environments?

**Comment by aeschli** [comment]
I you find a way to trick webpack, I'm happy to take a PR.

**Comment by penx** [comment]
@aeschli ok I should be able to look in to this, is there a way I can replicate the issue? Is there a particular build task I need to run to get the webpacked version that was causing the issue?

**Comment by penx** [comment]
From what I understand, the development build I was using is not webpacked, but when you do a production/distribution build it is.

If I run `yarn gulp -- vscode-darwin` I guess this should produce a Mac OS X application that I can test, though on my branch this results in

    Error: ModuleDependencyWarning: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Which I guess is the issue you encountered when you merged my PR.

**Comment by aeschli** [comment]
You can manually invoke webpack by calling
`npx webpack-cli --config=extension.webpack.config.js`
in `extensions/css-language-features`

**Comment by penx** [comment]
I'm still thinking about this but have had limited time. From some initial tests I think the current implementation only works if you're editing an scss file that's in the same directory as the node_modules folder you want to jump in to, which is rarely the case.
