### PR TITLE
CLI - Add a 1 second timeout for flushing the telemetry

### LINKED ISSUE #77201: Code --list-extensions slow
- VSCode Version: 1.35, 1.36
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Call ``code --list-extensions``
2. VSCode lists all extensions
3. VSCode takes > 30 seconds to return, even if no extensions are installed

I tried uninstalling all extensions, uninstalling VSCode (also deleting ``$HOME/.vscode`` and ``$HOME/.config/Code``) and upgrading to the newest version, the behavior persists.

Does this issue occur when all extensions are disabled?: N/A

### PR DESCRIPTION
**Pull request by lszomoru**
This PR fixes #77201

### CODE REVIEW

File: src/vs/code/node/cliProcessMain.ts [hunk 1]
```diff
@@ -361,8 +361,20 @@ export async function main(argv: ParsedArgs): Promise<void> {
 
 		try {
 			await main.run(argv);
+
 			// Flush the remaining data in AI adapter.
-			await combinedAppender(...appenders).flush();
+			// If it does not complete in 1 second, exit the process.
+			const flushTelemetry = (promise: Promise<any>, ms: number): Promise<any> => {
+				const timeout = new Promise((resolve) => {
```
Comment (joaomoreno) [inline src/vs/code/node/cliProcessMain.ts:368]: Check this out: https://github.com/microsoft/vscode/blob/613bcf26c1cb4c3d4735a34c660bc5fea7e0bbae/src/vs/base/common/async.ts#L59-L59

**Review by joaomoreno — APPROVED** [review]
Works like a charm!
