### PR TITLE
Fix background markdown rendering issues

### LINKED ISSUE #151252: Background CPU usage when opening a notebook with folded markdown cells
- Open a notebook, fold some markdown headers that include markdown cells
- Close and reopen the notebook so the folded cells are persisted as folded
- See the renderer process using CPU

I took a profile and saw that we keep trying to prerender a markdown cell, but then stop because it is folded:

https://github.com/microsoft/vscode/blob/97dddde1f742d43184bd8988958a5d9618dbc5f5/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L2628

so the code here:

https://github.com/microsoft/vscode/blob/97dddde1f742d43184bd8988958a5d9618dbc5f5/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L1198

should not retry the same cell over and over

Not any recent regression as far as I can tell

### PR DESCRIPTION
**Pull request by roblourens**
This fixes background markdown rendering quitting after the first run, and running forever on folded cells, and rendering the last hidden item of the folded range.

@rebornix please decide whether you want to take it and merge it if so

Fixes #151252

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts [hunk 1]
```diff
@@ -1153,22 +1153,25 @@ export class NotebookEditorWidget extends Disposable implements INotebookEditorD
 		const endTime = Date.now() + deadline.timeRemaining();
 
 		const execute = () => {
-			this._backgroundMarkdownRenderRunning = false;
-			if (this._isDisposed) {
-				return;
-			}
+			try {
+				this._backgroundMarkdownRenderRunning = true;
```
Comment (roblourens) [inline src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts:1157]: Fixing this flag so that `_backgroundMarkdownRendering` doesn't bail on the second time through.

File: src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts [hunk 2]
```diff
@@ -2585,6 +2585,12 @@ export class NotebookEditorWidget extends Disposable implements INotebookEditorD
 		});
 	}
 
+	private cellIsHidden(cell: ICellViewModel): boolean {
+		const modelIndex = this.viewModel!.getCellIndex(cell);
+		const foldedRanges = this.viewModel!.getHiddenRanges();
+		return foldedRanges.some(range => modelIndex >= range.start && modelIndex <= range.end);
```
Comment (roblourens) [inline src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts:2591]: Changed from < to <=, that seems correct here.

Comment (roblourens) [reply src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts:2591]: Not sure what other issue might have been triggered by this though.

File: src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts [hunk 3]
```diff
@@ -1153,22 +1153,25 @@ export class NotebookEditorWidget extends Disposable implements INotebookEditorD
...
-			}
+				if (!this.viewModel) {
+					return;
+				}
 
-			const firstMarkupCell = this.viewModel.viewCells.find(cell => cell.cellKind === CellKind.Markup && !this._webview?.markupPreviewMapping.has(cell.id)) as MarkupCellViewModel | undefined;
-			if (!firstMarkupCell) {
-				return;
-			}
+				const firstMarkupCell = this.viewModel.viewCells.find(cell => cell.cellKind === CellKind.Markup && !this._webview?.markupPreviewMapping.has(cell.id) && !this.cellIsHidden(cell)) as MarkupCellViewModel | undefined;
```
Comment (roblourens) [inline src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts:1166]: And here, don't take the cell if it is hidden.

**Review by rebornix — APPROVED** [review]
