### PR TITLE
Fix Notebook Cell URI

### LINKED ISSUE #122720: Notebook cell revealing (via outline, breakcrumbs) only works when editor is default editor
* install "markdown notebook" extension
* make sure the default editor for MD files is the _text_ editor
* open a MD file (opens as text)
* re-open with markdown notebook
* select an entry from outline or breadcrumbs
* :bug: a text editor opens

### PR DESCRIPTION
**Pull request by lramos15**
This PR fixes #122720

Same as https://github.com/microsoft/vscode/pull/122746 just to the release branch as well.

### CODE REVIEW

**Review by rebornix — APPROVED** [review]

File: src/vs/workbench/services/editor/common/editorOverrideService.ts [hunk 1]
```diff
@@ -260,7 +260,7 @@ export function globMatchesResource(globPattern: string | glob.IRelativePattern,
 		return false;
 	}
 	const matchOnPath = typeof globPattern === 'string' && globPattern.indexOf(posix.sep) >= 0;
-	const target = matchOnPath ? resource.path : basename(resource);
+	const target = matchOnPath ? `${resource.scheme}:${resource.path}` : basename(resource);
```
Comment (roblourens) [inline src/vs/workbench/services/editor/common/editorOverrideService.ts:263]: I'm suspicious of including the scheme in a glob, that isn't typical. Where do the glob patterns come from? This could make my `foo` glob stop matching `/foo`

Comment (lramos15) [reply src/vs/workbench/services/editor/common/editorOverrideService.ts:263]: This doesn't change glob matching logic, just for custom editors and notebooks. The glob patterns come from all the registers, normally in the from of `*.ext`, but can be anything. For notebooks and custom editors they primarily come from extensions

Comment (roblourens) [reply src/vs/workbench/services/editor/common/editorOverrideService.ts:263]: Yeah but are extensions writing globs like `vscode-notebook-cell://**/...`? Or where does that come from?

Comment (lramos15) [reply src/vs/workbench/services/editor/common/editorOverrideService.ts:263]: The extensions write globs likes `*.md` and then I saw that since they're a notebook they also handle cell URIs so I form the glob `vscode-notebook-cell:/**/*.md`

Comment (roblourens) [reply src/vs/workbench/services/editor/common/editorOverrideService.ts:263]: I guess it's ok for a candidate, but I think a better way to do this would be to register the scheme and file pattern separately, like `{ scheme: 'vscode-notebook-cell', pattern: extensionGlobPattern }`. These are separate things and it feels weird to combine them

**Review by roblourens — APPROVED** [review]
