### PR TITLE
fix quick fix css

### LINKED ISSUE #161598: Use a background color on the terminal quick fix icon
Otherwise the decoration underneath bleeds through:

image

Since it's partially transparent you can also see the circle outline on the yellow part

### PR DESCRIPTION
**Pull request by meganrogge**
fix #161598

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 1]
```diff
@@ -115,8 +119,12 @@ export class TerminalQuickFixAddon extends Disposable implements ITerminalAddon,
 		decoration?.onRender((e: HTMLElement) => {
 			if (!this._decorationMarkerIds.has(decoration.marker.id)) {
 				this._currentQuickFixElement = e;
-				e.classList.add(DecorationSelector.QuickFix, DecorationSelector.Codicon, DecorationSelector.CommandDecoration, DecorationSelector.XtermDecoration);
+				e.classList.add(DecorationSelector.QuickFix, DecorationSelector.LightBulb, DecorationSelector.Codicon, DecorationSelector.CommandDecoration, DecorationSelector.XtermDecoration);
 				e.style.color = '#ffcc00';
+				// must be inlined to override the styles
+				// applied inline in xterm.js
+				e.style.zIndex = '7';
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:126]: Is it these that it's overriding?

https://github.com/Tyriar/xterm.js/blob/23328a394bbb10790014d78f888d96174e1aae98/css/xterm.css#L176-L192

If so you can do `z-index: 7 !important` in the CSS class and it'll work.

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 2]
```diff
@@ -115,8 +119,12 @@ export class TerminalQuickFixAddon extends Disposable implements ITerminalAddon,
...
+				e.style.borderRadius = '5px';
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:127]: Better to move to .css

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 3]
```diff
@@ -115,8 +119,9 @@ export class TerminalQuickFixAddon extends Disposable implements ITerminalAddon,
 		decoration?.onRender((e: HTMLElement) => {
 			if (!this._decorationMarkerIds.has(decoration.marker.id)) {
 				this._currentQuickFixElement = e;
-				e.classList.add(DecorationSelector.QuickFix, DecorationSelector.Codicon, DecorationSelector.CommandDecoration, DecorationSelector.XtermDecoration);
-				e.style.color = '#ffcc00';
+				e.classList.add(DecorationSelector.QuickFix, DecorationSelector.LightBulb, DecorationSelector.Codicon, DecorationSelector.CommandDecoration, DecorationSelector.XtermDecoration);
+				// must be inlined
+				e.style.color = '#ddb100';
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:124]: This should live in css so we can pull the theme's color, otherwise we'll get accessibility bugs. Should be able to use the `!important` trick here too

**Review by Tyriar — APPROVED** [review]
