### PR TITLE
Fix leaking comment thread when CellComment is reused.

### LINKED ISSUE #214585: Code review comments on one notebook cell leak into other notebook cells as the Browser renderer reuses DOM which is not properly cleaned up
- VS Code Version: vscode.dev/ (Browser code)
- OS Version: Irrelevant

This is an issue with the browser code, which happens for code review comments on notebook cells. I do not have a public repro, but I can describe line by line why this happens, and am happy to send a PR to fix it:

* Cells in a notebook are rendered as a `ListView`. ListView uses a cache to reuse widgets and DOM: https://github.com/microsoft/vscode/blob/6e6d38007e3c76ac7686c97502d9c6deefe44b7a/src/vs/base/browser/ui/list/listView.ts#L905
* As a result, `CellComments`, a `CellContentPart`, is reused, by calling `renderCell`/`unrenderCell`: https://github.com/microsoft/vscode/blob/6facfe23b300eb448c35d07291cad7ad98625302/src/vs/workbench/contrib/notebook/browser/view/cellParts/markupCell.ts#L73
* The HTMLElement `container` is passed in upon construction and held on to: https://github.com/microsoft/vscode/blob/6facfe23b300eb448c35d07291cad7ad98625302/src/vs/workbench/contrib/notebook/browser/view/cellParts/cellComments.ts#L28-L30
* For existing comments, a `CommentThreadWidget` is constructed during initialization of a `CellComments`, which is called on the first `renderCell`, and then skipped for subsequent calls: https://github.com/microsoft/vscode/blob/6facfe23b300eb448c35d07291cad7ad98625302/src/vs/workbench/contrib/notebook/browser/view/cellParts/cellComments.ts#L47-L58
* `CommentThreadWidget` appends to  `container` and installs some listeners: https://github.com/microsoft/vscode/blob/6facfe23b300eb448c35d07291cad7ad98625302/src/vs/workbench/contrib/comments/browser/commentThreadWidget.ts#L106 
* CommentThreadWidget.dispose() cleans up listeners, but the appended DOM elements are not removed: https://github.com/microsoft/vscode/blob/6facfe23b300eb448c35d07291cad7ad98625302/src/vs/workbench/contrib/comments/browser/commentThreadWidget.ts#L263-L267
* Similarly, CellComments does not override `unrenderCell()`, and the base class `CellContentPart.unrenderCell()` removes listeners (that CellComents put into the corresponding DisposableStore), but does not unset `_initialized`, clean up `_commentThreadWidget`, or call `CommentThreadWidget.dispose()`- they all leak
* Only when `onDidUpdateCommentThreads` fires, will `_commentThreadWidget` be disposed (which as seen above does not remove the elements from the DOM - only the layout is reset to hide it, or replaced

I think we need to do the following to fix this issue:
* `CommentThreadWidget` and its children (CommentThreadHeader) should remove the DOM elements they added to `container` when they are disposed(). That seems like good practice in general, and seems to be done at least in some other places in VSCode, e.g. https://github.com/microsoft/vscode/blob/6125cc2332d2d21805f1887c7b944a81ffce423e/src/vs/base/browser/ui/tree/abstractTree.ts#L798-L799
* `CellComments` should, instead of initializing only once, check if the ICellViewModel has changed in on `didRender`, and if so, run the same logic it runs `onDidUpdateCommentThreads`, which will remove, created, or update the comment thread.

I'll send a pull request to make this more concrete, happy to talk about other solutions to the problem, too. 

@alexr00 @rebornix

### PR DESCRIPTION
**Pull request by rehmsen**
Fixes #214585.

As none of the involved classes are covered by unit tests, to test this one needs to create a notebook with a code cell, then a page long markup cell, then a code cell, so that the two code cells are not visible at the same time, and the renderer reuses the same CellComments for them as you scroll up and down. Then you need to put a notebook comment onto the first cell. Before this change, that comment also is shown incorrectly on the second code cell when scrolling down as it is not correctly cleaned up. with this change, this does not happen,  the CommentThreadWidget and associated DOM elements are removed, and then added back again cleanly when scrolling back up to the first code cell.

### CODE REVIEW

**Review by rehmsen — COMMENTED** [review]
Remove accidental change in test/automation/package.json.

**Review by rebornix — DISMISSED** [review]
Thanks!

**Comment by rehmsen** [comment]
Hi @alexr00, did you have a chance to look at this? Do you have any questions? It would be cool to get this fix in. Thanks!

**Review by alexr00 — COMMENTED** [review]
I just have one question:

File: src/vs/workbench/contrib/notebook/browser/view/cellParts/cellComments.ts [hunk 1]
```diff
@@ -45,21 +44,17 @@ export class CellComments extends CellContentPart {
...
 		}
 
-		this._initialized = true;
-		const info = await this._getCommentThreadForCell(element);
-
-		if (info) {
-			await this._createCommentTheadWidget(info.owner, info.thread);
-		}
+		this.currentElement = element as CodeCellViewModel;
+		this._updateThread();
```
[the remark this answers is not in the document]
Comment (rehmsen) [reply src/vs/workbench/contrib/notebook/browser/view/cellParts/cellComments.ts:52]: Thanks for checking.

I think at the moment it does not change anything, because the call to `initialize()` in line 160 is not awaited (neither before nor after this change). The API of `didRenderCell` does not allow returning a promise.  

I could either remove the "async" from initialize (or inline the method altogether since it is only called from that one place), or could await here. 

Do you have a preference?

File: src/vs/workbench/contrib/notebook/browser/view/cellParts/cellComments.ts [hunk 2]
```diff
@@ -87,41 +82,46 @@ export class CellComments extends CellContentPart {
...
+			this.container.style.top = `${layoutInfo.outputContainerOffset + layoutInfo.outputTotalHeight}px`;
+			this.currentElement.commentHeight = this._calculateCommentThreadHeight(this._commentThreadWidget!.getDimensions().height);
+			return;
+		}
+
+		if (this._commentThreadWidget) {
+			if (!info) {
+				this._commentThreadDisposables.clear();
+				this._commentThreadWidget.dispose();
+				this._commentThreadWidget = null;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/notebook/browser/view/cellParts/cellComments.ts:113]: @alexr00 a MutableDisposable is a nicer pattern for as it helps you not forget to dispose when unsetting

**Review by Tyriar — DISMISSED** [review]

File: src/vs/workbench/contrib/notebook/browser/view/cellParts/cellComments.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (alexr00) [reply src/vs/workbench/contrib/notebook/browser/view/cellParts/cellComments.ts:52]: I would `await` here since that should help if a future refactor causes `initialize` to be called from somewhere where it can be awaited.

File: src/vs/workbench/contrib/notebook/browser/view/cellParts/cellComments.ts (hunk 2 above)
Comment (rehmsen) [reply src/vs/workbench/contrib/notebook/browser/view/cellParts/cellComments.ts]: Thanks, I have changed the code to use this.

File: src/vs/workbench/contrib/notebook/browser/view/cellParts/cellComments.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (rehmsen) [reply src/vs/workbench/contrib/notebook/browser/view/cellParts/cellComments.ts]: Sounds good. Done. Please take another look.

File: test/automation/package.json [hunk 3]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "vscode-automation",
-  "version": "1.71.0",
+  "version": "1.91.0",
```
Comment (alexr00) [inline test/automation/package.json:3]: Looks like there's still an unintentional change here.

**Review by alexr00 — COMMENTED** [review]
Other than the change to test/automation/package.json I'm happy with the change!

File: test/automation/package.json (hunk 3 above)
Comment (rehmsen) [reply test/automation/package.json]: Thanks for noticing. There is apparently some automation that keeps changing that, and which crept in again in the last commit fixing the requested things. I have undone it again.

**Review by alexr00 — APPROVED** [review]
Looks good, thank you! I'll just let @rebornix re-review.

**Review by rebornix — APPROVED** [review]
Looks great!

**Comment by rebornix** [comment]
@rehmsen sorry for the late response, the code looks great! Thank you for the contribution ❤️

**Review by GregKruz — APPROVED** [review]
