### PR TITLE
pass back profile instead of just shell

### LINKED ISSUE #270609: Copilot terminals does not load the same profile as normal terminals do
Type: <b>Bug</b>

I have nvm installed on .zprofile. The nodejs commands work well on a normal terminals, however copilot terminals keep failing to find the nodejs command when the copilot agent launched them to do the same commands.

The discrepancy is that the copilot terminals use `zsh -i` unless the normal terminals use `zsh -il`.

VS Code version: Code - Insiders 1.105.0-insider (Universal) (03c265b1adee71ac88f833e065f7bb956b60550a, 2025-10-08T14:07:41.558Z)
OS version: Darwin arm64 25.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: enabled_on<br>trees_in_viz: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|8, 10, 14|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|. --crash-reporter-id d2329c78-39f2-401c-96bd-afc18cc51c9b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.16
gitlens|eam|17.6.1
prettier-vscode|esb|11.0.0
copilot|Git|1.378.1798
copilot-chat|Git|0.32.2025100703
vscode-pull-request-github|Git|0.118.2
vscode-azure-github-copilot|ms-|1.0.117
vscode-azure-mcp-server|ms-|0.8.5
vscode-azureresourcegroups|ms-|0.11.4
debugpy|ms-|2025.10.0
python|ms-|2025.14.0
vscode-pylance|ms-|2025.8.3
vscode-python-envs|ms-|1.8.0
remote-containers|ms-|0.429.0
extension-test-runner|ms-|0.0.12
vscode-github-issue-notebooks|ms-|0.0.133
native-preview|Typ|0.20251009.1
vscode-selfhost-test-provider|ms-|0.4.0
vscode-selfhost-import-aid|ms-|0.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
pythonvspyt551cf:31249598
cmp-cht-unified-ctrl3:31396547
nativeloc1:31118317
dwcopilot:31158714
471b6256:31240254
dwoutputs:31242946
copilot_t_ci:31333650
g012b348:31231168
6gi0g917:31259950
pythonrdcb7:31268811
usemplatestapi:31297334
6518g693:31302842
0g1h6703:31329154
cs4_fixed:31398790
6abeh943:31336334
envsactivate1:31349248
ovs_pri_t:31398872
editstats-enabled:31346256
aa_c:31379597
cloudbuttont:31366566
qwen_all_req:31396049
multireplacestring:31382717
nb255704_tf:31377673
3efgi100_wstrepl:31382709
ge3cd652:31390471
trigger-command-fix:31379601
auto_model_enabled:31396818
grok-control-prompt:31384642
use-responses-api:31390341
copilot-gpt-5-mini:31396488
c91a3477:31396429

```

</details>

### PR DESCRIPTION
**Pull request by meganrogge**
fixes https://github.com/microsoft/vscode/issues/270609

There was a discrepancy between a user created `zsh` terminal and one created by the agent because the `-l` arg was missing from the latter.

This was because we were only passing the `shell` back. Unclear to me if this was intentional, but seems like these experiences should be aligned. 

Not having `-l` would cause some env that was set in a `.zprofile` to be missing, so when the agent would try to run a command, it might fail. 

Screenshot 2025-10-09 at 1 18 55 PM

### CODE REVIEW

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts [hunk 1]
```diff
@@ -701,7 +705,7 @@ export class RunInTerminalTool extends Disposable implements IToolImpl {
 			this._terminalToolCreator.refreshShellIntegrationQuality(cachedTerminal);
 			return cachedTerminal;
 		}
-		const shellOrProfile = await this._getCopilotShellOrProfile();
+		const shellOrProfile = await this._getCopilotProfile();
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts]: `shellOrProfile` is no longer accurate

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts [hunk 2]
```diff
@@ -626,21 +626,25 @@ export class RunInTerminalTool extends Disposable implements IToolImpl {
...
+			};
 		}
 
-		return defaultShell;
+		return defaultProfile;
 	}
 
 	private async _getCopilotShell(): Promise<string> {
-		const shellOrProfile = await this._getCopilotShellOrProfile();
+		const shellOrProfile = await this._getCopilotProfile();
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts]: `shellOrProfile` no longer accurate

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts [hunk 3]
```diff
@@ -626,21 +626,25 @@ export class RunInTerminalTool extends Disposable implements IToolImpl {
...
 		if (typeof shellOrProfile === 'string') {
 			return shellOrProfile;
 		}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts]: Not needed

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts [hunk 4]
```diff
@@ -626,21 +626,25 @@ export class RunInTerminalTool extends Disposable implements IToolImpl {
...
+				path: 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe',
+				profileName: 'PowerShell'
+			};
 		}
 
-		return defaultShell;
+		return defaultProfile;
 	}
 
 	private async _getCopilotShell(): Promise<string> {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts:646]: The implementation could be just `return (await this._getCopilotProfile()).path` now.

**Review by Tyriar — DISMISSED** [review]

**Review by joaomoreno — APPROVED** [review]
