### PR TITLE
Fix terminal mouse reporting via binary events

### LINKED ISSUE #96058: Integrated terminal mouse reporting not working
- VSCode 1.44.2
- macOS 10.14.6

Steps to Reproduce:

1. Open a file in vim by running `vim <file>` in the integrated terminal
2. Type `:set mouse=a` and press enter, to enable mouse reporting
3. Now, selecting text in the file you opened does not work

This apparently does not affect tmux.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #96058

### CODE REVIEW

**Comment by meganrogge** [comment]
It looks correct to me and the event is getting piped through. I think there's something wrong here https://github.com/microsoft/vscode/blob/0a9cb852d8dd4f6c218396586edeefcbc04fd144/src/vs/platform/terminal/node/terminalProcess.ts#L353-L353

But it takes forever to make a custom build and test in WSL

File: src/vs/platform/terminal/node/terminalProcess.ts [hunk 1]
```diff
@@ -341,10 +345,16 @@ export class TerminalProcess extends Disposable implements ITerminalChildProcess
...
 
-	private _doWrite(): void {
+	private _doWrite(isBinary?: boolean): void {
+		console.info('writing binary', isBinary);
 		const data = this._writeQueue.shift()!;
-		this._logService.trace('IPty#write', `${data.length} characters`);
-		this._ptyProcess!.write(data);
+		if (isBinary) {
+			this._logService.info('IPty#writeBinary', `${data.length} characters`);
+			this._ptyProcess!.write(Buffer.from(data, 'binary').toString('binary'));
```
Comment (Tyriar) [inline src/vs/platform/terminal/node/terminalProcess.ts:353]: @jerch does this look right for writing binary to node-pty (on all platforms)?

Comment (jerch) [reply src/vs/platform/terminal/node/terminalProcess.ts:353]: I fear not, given that the event data is a proper bytestring (only containing codepoints in 0..255), it basically sends the input string unchanged. NodeJS will always try to do a string-UTF8 conversion at OS barriers for string types.

The only proper fix I can think of would be to send the binary buffer directly skipping NodeJS' attempt to convert anything:
```typescript
this._ptyProcess!.write(Buffer.from(data, 'binary'));
```

If thats not supported (I think `node-pty`'s conpty integration only supports string currently?), there is still a possibility to get at least lower coords through:

```typescript
function isAscii(data: string): boolean {
  return Array.from(data).every(el => el.charCodeAt(0) < 0x80)
}
...
// only support coords in ASCII range for now:
if (isAscii(data)) {
  this._ptyProcess!.write(data);
}
```

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/platform/terminal/node/terminalProcess.ts [hunk 2]
```diff
@@ -310,23 +310,27 @@ export class TerminalProcess extends Disposable implements ITerminalChildProcess
...
-	public input(data: string): void {
+	public input(data: string, isBinary?: boolean): void {
 		if (this._isDisposed || !this._ptyProcess) {
 			return;
 		}
 		for (let i = 0; i <= Math.floor(data.length / WRITE_MAX_CHUNK_SIZE); i++) {
 			this._writeQueue.push(data.substr(i * WRITE_MAX_CHUNK_SIZE, WRITE_MAX_CHUNK_SIZE));
 		}
-		this._startWrite();
+		this._startWrite(isBinary);
```
Comment (Tyriar) [inline src/vs/platform/terminal/node/terminalProcess.ts:320]: Let's store isBinary inside the queue, like `{ isBinary: boolean, data: string }`

File: src/vs/platform/terminal/node/terminalProcess.ts [hunk 3]
```diff
@@ -341,10 +345,16 @@ export class TerminalProcess extends Disposable implements ITerminalChildProcess
 		}, WRITE_INTERVAL_MS);
 	}
 
-	private _doWrite(): void {
+	private _doWrite(isBinary?: boolean): void {
+		console.info('writing binary', isBinary);
```
Comment (Tyriar) [inline src/vs/platform/terminal/node/terminalProcess.ts:349]: remove

File: src/vs/workbench/api/common/extHostTerminalService.ts [hunk 4]
```diff
@@ -225,6 +225,10 @@ export class ExtHostPseudoterminal implements ITerminalChildProcess {
 		}
 	}
 
+	processBinary(data: string) {
+		throw new Error('not implemented');
+	}
```
Comment (Tyriar) [inline src/vs/workbench/api/common/extHostTerminalService.ts:230]: Let's fail silently here with a comment

File: src/vs/workbench/contrib/terminal/browser/terminalProcessExtHostProxy.ts [hunk 5]
```diff
@@ -102,6 +102,10 @@ export class TerminalProcessExtHostProxy extends Disposable implements ITerminal
 		}
 	}
 
+	processBinary(data: string): void {
+		throw new Error('not implemented');
+	}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalProcessExtHostProxy.ts:107]: Let's pass through here and let the actual Pseudoterminal object fail (instead of having no ops all over the place)

File: src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts [hunk 6]
```diff
@@ -499,6 +499,10 @@ export class TerminalProcessManager extends Disposable implements ITerminalProce
 		}
 	}
 
+	public processBinary(data: string): void {
+		this._process?.processBinary(data);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts:503]: Let's do this here too:

```
		await this.ptyProcessReady;
		this._dataFilter.triggerSwap();
		this._hasWrittenData = true;
```

File: src/vs/workbench/test/browser/workbenchTestServices.ts [hunk 7]
```diff
@@ -1521,6 +1521,9 @@ export class TestLocalTerminalService implements ILocalTerminalService {
 	async listProcesses(reduceGraceTime: boolean): Promise<IProcessDetails[]> { throw new Error('Method not implemented.'); }
 	async setTerminalLayoutInfo(argsOrLayout?: ISetTerminalLayoutInfoArgs | ITerminalsLayoutInfoById) { throw new Error('Method not implemented.'); }
 	async getTerminalLayoutInfo(): Promise<ITerminalsLayoutInfo | undefined> { throw new Error('Method not implemented.'); }
+	processBinary(id: number, data: string): void {
+		throw new Error('Method not implemented.');
+	}
```
Comment (Tyriar) [inline src/vs/workbench/test/browser/workbenchTestServices.ts:1526]: Don't think this is needed

File: src/vs/workbench/test/browser/workbenchTestServices.ts [hunk 8]
```diff
@@ -1544,6 +1547,9 @@ class TestTerminalChildProcess implements ITerminalChildProcess {
 	async getInitialCwd(): Promise<string> { return ''; }
 	async getCwd(): Promise<string> { return ''; }
 	async getLatency(): Promise<number> { return 0; }
+	processBinary(data: string): void {
+		throw new Error('not implemented');
+	}
```
Comment (Tyriar) [inline src/vs/workbench/test/browser/workbenchTestServices.ts:1552]: Let's no op like `input`

**Review by Tyriar — APPROVED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalProcessExtHostProxy.ts (hunk 5 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalProcessExtHostProxy.ts:107]: There are no listeners to `onBinary` right now by design. Don't think we want to add any until or unless this is something we want to allow. 
https://github.com/microsoft/vscode/blob/b45caa2ebeea1219818669e92e5b550b0eabd41b/src/vs/workbench/contrib/terminal/browser/terminalProcessExtHostProxy.ts#L131-L134

**Comment by nojvek** [comment]
@meganrogge, this is awesome. Thanks for pushing this to the finish line. Very excited that now vscode can do mouse events in terminal.
