### PR TITLE
Notebook multi select -- decorations + general improvements

### LINKED ISSUE #226848: Notebook Multi Cursor doesn't support arrow left/right
Testing #226681

In single editor, an arrow left/right will collapse all selections to their begin or end positions but it doesn't work across cells.

### LINKED ISSUE #226849: Decorations in cells outside of viewport are not restored properly
Testing #226681

* cmd+d multiple times until some matches are scrolled out of the viewport
* scroll back 
* the matches are no longer highlighted

https://github.com/user-attachments/assets/c4f5dba6-0e27-4533-92f1-474ce1586d3d

### PR DESCRIPTION
**Pull request by Yoyokrazy**
Fixes: #226848, #226849

Re: #141673

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/common/notebookCommon.ts [hunk 1]
```diff
@@ -1021,6 +1021,7 @@ export const NotebookSetting = {
 	InteractiveWindowPromptToSave: 'interactiveWindow.promptToSaveOnClose',
 	cellFailureDiagnostics: 'notebook.cellFailureDiagnostics',
 	outputBackupSizeLimit: 'notebook.backup.sizeLimit',
+	multiSelect: 'notebook.multiSelect.enabled',
```
Comment (rebornix) [inline src/vs/workbench/contrib/notebook/common/notebookCommon.ts:1024]: should we name it `multiCursor`?

**Review by rebornix — APPROVED** [review]
