### PR TITLE
Fix jupyter issue 8316 - Jupyter renderer extension not used for IW

### LINKED ISSUE #8316: Latex cells aren't rendering at all in insiders
I get this:

image

Seems pretty important to fix.

### PR DESCRIPTION
**Pull request by rchiodo**
This PR fixes https://github.com/microsoft/vscode-jupyter/issues/8316

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts [hunk 1]
```diff
@@ -333,7 +334,7 @@ export class NotebookOutputRendererInfoStore {
 				const rendererExtId = renderer.extensionId.value;
 				const reuseScore = preferred === renderer.id
 					? ReuseOrder.PreviouslySelected
-					: rendererExtId === notebookExtId || RENDERER_EQUIVALENT_EXTENSIONS.get(rendererExtId)?.has(notebookExtId!)
+					: rendererExtId === notebookExtId || RENDERER_EQUIVALENT_EXTENSIONS.get(rendererExtId)?.has(notebookId!)
```
Comment (rchiodo) [inline src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts:337]: The interactive window doesn't have an extension id associated with it, so I used the ```notebookProviderInfo.id``` instead.

**Review by rebornix — APPROVED** [review]
Thanks, LGTM.
