### PR TITLE
Change the default of `editor.renderFinalNewline` to `dimmed` on Linux

### LINKED ISSUE #141169: Trimming final newline is not POSIX standards compliant
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Type anything in the editor and save it to a file
2. Run `cat` to read the file

I am becoming increasingly annoyed by Visual Studio Code users because files are created without final newline.

Screenshot from 2022-01-21 19-23-19

This results in mangled shell prompt as shown above. In a sane world shell prompt starts on a new line.

Feel free to do this on Windows, but don't bring this madness to Linux and Mac. You're just wasting our time explaining how to turn off trimming and why trimming is bad.

In POSIX line ends with newline:
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
and text file consists of 0 or more lines: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_403
Hence text file ends with a newline character

### PR DESCRIPTION
**Pull request by alexdima**
Fixes #141169

### CODE REVIEW

File: src/vs/editor/browser/viewParts/lineNumbers/lineNumbers.ts [hunk 1]
```diff
@@ -190,3 +190,13 @@ export class LineNumbersOverlay extends DynamicViewOverlay {
...
 }
+
+registerThemingParticipant((theme, collector) => {
+	const editorLineNumbersColor = theme.getColor(editorLineNumbers);
+	const editorDimmedLineNumberColor = theme.getColor(editorDimmedLineNumber);
+	if (editorDimmedLineNumberColor) {
+		collector.addRule(`.monaco-editor .line-numbers.dimmed-line-number { color: ${editorDimmedLineNumberColor}; }`);
+	} else if (editorLineNumbersColor) {
+		collector.addRule(`.monaco-editor .line-numbers.dimmed-line-number { color: ${editorLineNumbersColor.transparent(0.4)}; }`);
+	}
```
Comment (Tyriar) [inline src/vs/editor/browser/viewParts/lineNumbers/lineNumbers.ts:201]: The first could move to css easily, I don't know of a good way for the second unless it doesn't back a background color set in which case you can use `opacity: 0.4`

**Review by Tyriar — APPROVED** [review]

File: src/vs/editor/browser/viewParts/lineNumbers/lineNumbers.ts (hunk 1 above)
Comment (alexdima) [reply src/vs/editor/browser/viewParts/lineNumbers/lineNumbers.ts:201]: I thought about using opacity, but didn't go with that because that can't be configured via a color customization / theme.

I agree about the first rule could be written in CSS. I kept it here because of the `else if`. I could have written the code better e.g.:

```
const editorDimmedLineNumberColor = theme.getColor(editorDimmedLineNumber) || editorLineNumbersColor.transparent(0.4);
```
