### PR TITLE
scale instead of zoom

### LINKED ISSUE #141388: Layout menu appears in wrong location
Testing #141357

With the window split in half:
Recording 2022-01-25 at 11 44 09

### PR DESCRIPTION
**Pull request by sbatten**
This PR fixes #141388

I tested this on Windows with menubar hidden and macOS with the custom titlebar. The change is to counteract the zooming of the window with scaling instead of the zoom property. This is helpful because we can avoid the "accidental" translation of the coordinates in the titlebar.

### CODE REVIEW

File: src/vs/workbench/browser/parts/titlebar/titlebarPart.ts [hunk 1]
```diff
@@ -557,15 +559,13 @@ export class TitlebarPart extends Part implements ITitleService {
 		if (getTitleBarStyle(this.configurationService) === 'custom') {
 			// Only prevent zooming behavior on macOS or when the menubar is not visible
 			if ((!isWeb && isMacintosh) || this.currentMenubarVisibility === 'hidden') {
-				(this.title.style as any).zoom = `${1 / getZoomFactor()}`;
-				if (this.windowControls) {
-					(this.windowControls.style as any).zoom = `${1 / getZoomFactor()}`;
-				}
+				(this.rootContainer.style as any).height = `${100.0 * getZoomFactor()}%`;
```
Comment (bpasero) [inline src/vs/workbench/browser/parts/titlebar/titlebarPart.ts:562]: No need to use `any` for properties `height`, `width` and `transform`.

File: src/vs/workbench/electron-sandbox/parts/titlebar/titlebarPart.ts [hunk 2]
```diff
@@ -224,29 +224,14 @@ export class TitlebarPart extends BrowserTitleBarPart {
...
-				if (isWindows || isLinux) {
-					if (this.appIcon) {
-						(this.appIcon.style as any).zoom = `${1 / getZoomFactor()}`;
-					}
-				}
-
-				if (this.windowControls) {
-					(this.windowControls.style as any).zoom = `${1 / getZoomFactor()}`;
-				}
+				(this.rootContainer.style as any).height = `${100.0 * getZoomFactor()}%`;
```
Comment (bpasero) [inline src/vs/workbench/electron-sandbox/parts/titlebar/titlebarPart.ts:228]: No need to use `any` for properties `height`, `width` and `transform`.

**Review by bpasero — APPROVED** [review]
Yeah I think this is a good approach. Just think you can drop the use of `any` now. I suggest to add a test plan item for this on all platforms.
