### PR TITLE
Fix race when loading notebook webviews

### LINKED ISSUE #161520: Markup cell initialize fail on window reload
This is hard to have stable reproduce but almost every one in the notebook v-team ran into this in last few weeks: when reloading the window with a notebook editor open, the notebook editor might not open successfully, closing it and reopening the same document can fix it.

Debugged with log points in Insiders and I found it failed in `BacklayerWebview#initializeMarkup`

https://github.com/microsoft/vscode/blob/d847171943679c45058838150104741512743d41/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L1159-L1182

The `initializeMarkup` message is sent to the webview (at least we called the webview `postMessage`) but the response never came back. When this happens, the webview/iframe contains the `html` content, Jupyter notebook renderers' styles, but it doesn't have anything related to the markup renderers (no markup css).

@mjbvz please help take a look, we can have a call to do some debugging together.

### PR DESCRIPTION
**Pull request by mjbvz**
This tries to fix #161520 by doing the following:

- Wait for basic initialization to finish before posting messages
- `initializedMarkup` should wait  for the correct response instead of the first response

This fixes the issue in my testing, but causes the layout to shift around during load. @rebornix  let's try to debug this next week

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts [hunk 1]
```diff
@@ -1160,15 +1172,11 @@ var requirejs = (function() {
...
-		// TODO: use proper handler
-		const p = new Promise<void>(resolve => {
-			const sub = this.webview?.onMessage(e => {
-				if (e.message.type === 'initializedMarkup') {
-					resolve();
-					sub?.dispose();
-				}
-			});
-		});
+		this.firstInit = false;
```
Comment (rebornix) [inline src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts:1175]: `this.firstInit` is set to `false` when we request viewport warmup. Then when the webview preloads sends back `initialized`event, we will run `initializeWebViewState`. Since `this.firstInit` is set to `false`, it will trigger `initializeMarkup` again, which will `complete` the warmup promise immediately.

I think we want to make sure that we only send requests after `initialized` event come back, then only one single request to `intializeMarkup` for viewport is sent.

**Review by rebornix — APPROVED** [review]
The code changes look good. The only catch is the webview or renderers didn't seem to be ready in integration tests thus all notebook open related tests fail sometimes.
