### PR TITLE
Disable bash integration when PROMPT_COMMAND has space and semi-colon

### LINKED ISSUE #145016: Error with shell integration enabled: Unexpected EOF
Issue Type: <b>Bug</b>

Get following error when shell integratino is enabled.. Same on WSL and remote SSH
```
Shell integration activated
bash: eval: line 6: unexpected EOF while looking for matching `"'
bash: eval: line 7: syntax error: unexpected end of file
bash: eval: line 6: unexpected EOF while looking for matching `"'
bash: eval: line 7: syntax error: unexpected end of file
```

VS Code version: Code - Insiders 1.66.0-insider (3e5c7e2c570a729e664253baceaf443b69e82da6, 2022-03-14T05:15:38.097Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 4.18.0-348.12.2.el8_5.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (15.97GB free)|
|Process Argv|--crash-reporter-id fb8a6a46-aa24-476b-b87f-4ed0171d369a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS8-stream|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|Memory (System)|24.86GB (22.87GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: zalent|
|OS|Linux x64 4.18.0-348.12.2.el8_5.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E3-1240 v5 @ 3.50GHz (4 x 3504)|
|Memory (System)|7.59GB (0.64GB free)|
|VM|100%|
</details><details><summary>Extensions (72)</summary>

Extension|Author (truncated)|Version
---|---|---
debian-vscode|daw|0.1.2
python-ultisnippets|eli|2.7.0
LogFileHighlighter|emi|2.15.0
vscode-systemd-support|han|1.0.1
saltstack|kor|0.0.9
dotenv|mik|1.0.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.226.0
remote-ssh|ms-|0.77.2022031115
remote-ssh-edit|ms-|0.76.1
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
sublime-keybindings|ms-|4.0.10
material-icon-theme|PKi|4.14.1
shellman|Rem|5.6.0
shebang-snippets|rpi|0.1.4
jinjahtml|sam|0.17.0
errorlens|use|3.4.2
vscode-icons|vsc|11.10.0
vscode-todo-highlight|way|1.0.5
vscode-nginx-conf|ahm|0.1.3
github-markdown-preview|bie|0.2.0
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-footnotes|bie|0.0.7
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
gitignore|cod|0.7.0
vscode-markdownlint|Dav|0.46.0
gitlens|eam|12.0.4
EditorConfig|Edi|0.16.4
opensslutils|ffa|1.1.1
code-runner|for|0.11.7
shell-format|fox|7.2.2
vscode-pull-request-github|Git|0.39.2022031015
todo-tree|Gru|0.0.215
vscode-systemd-support|han|1.0.1
vscode-guid|hea|1.4.20
rest-client|hum|0.24.6
path-autocomplete|ion|1.19.1
rpm-spec|Lau|0.3.2
vscode-swissknife|lui|1.4.0
jenkins-doc|Maa|1.7.0
bash-ide-vscode|mad|1.12.1
rainbow-csv|mec|2.0.0
git-graph|mhu|1.30.0
ecdc|mit|1.4.0
vscode-filesize|mkx|3.1.0
python|ms-|2022.2.1924087327
vscode-pylance|ms-|2022.3.2-pre.1
hexeditor|ms-|1.9.5
powershell-preview|ms-|2022.3.0
markdown-github-dark|oza|0.1.0
linesinfostatusbar|pet|0.0.7
vscode-versionlens|pfl|1.0.9
ansible|red|0.8.1
vscode-commons|red|0.0.6
vscode-xml|red|0.19.1
vscode-yaml|red|1.5.1
vscode-coverage-gutters|rya|2.9.1
trailing-spaces|sha|0.3.1
vscode-fileutils|sle|3.5.0
vscode-hexdump|sle|1.8.1
vscode-taskexplorer|spm|2.9.1
code-spell-checker|str|2.1.7
tabnine-vscode|Tab|3.5.26
even-better-toml|tam|0.14.2
shellcheck|tim|0.18.9
vscode-counter|uct|3.0.3
vscodeintellicode|Vis|1.2.17
salt-lint|war|0.1.0
markdown-all-in-one|yzh|3.4.0

</details>

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #145016

### CODE REVIEW

**Comment by meganrogge** [comment]
with 

```
PROMPT_COMMAND= "hi;c custom"
```
in my `.bashrc`, I see the shell integration activated message and don't see the expected message.

**Comment by meganrogge** [comment]
also tried without the quotes wrapping it and same thing happens

File: src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh [hunk 1]
```diff
@@ -18,6 +18,12 @@ else
 	VSCODE_SHELL_LOGIN=""
 fi
 
+if [[ "$PROMPT_COMMAND" =~ ^.*(\s.*\;)|(\;.*\s).*$ ]]; then
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh:21]:
```suggestion
if [[ "$PROMPT_COMMAND" =~ ^.*(' '.*\;)|(\;.*' ').*$ ]]; then
```
