### PR TITLE
Make Neo keyboard layout (layer 4) arrow keys work in explorer view

### LINKED ISSUE #97946: Neo keyboard layout: Arrow keys don't work in Explorer
- VSCode Version: 1.45.1
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Activate any of these keyboard layouts (in Linux):
- `setxkbmap de neo_qwerty`
- `setxkbmap de neo_qwertz`
- `setxkbmap de neo`
- `setxkbmap de adnw`
- `setxkbmap de koy`
- `setxkbmap de bone`

I recommend the first of these layouts for testing. This gives you a QWERTY layout but with additional layers. When you press a key while holding AltGr/Right Alt key, you get these symbols:

grafik

(`AltGr`+ `D` is ArrowDown, `AltGr` + `E` is ArrowUp.)

2. Start VS Code and set _Keyboard: Dispatch_ to _keyCode_

3. Click into the `EXPLORER` and use `AltGr` + `D`/`E` for going up and down in the file list. This doesn't work. Instead you see a popup like this:

grafik

Arrow keys on layer 4 (`AltGr` + `D`/`E`) work in the Editor and also in the Settings. Only the Explorer doesn't work.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by MaxGyver83**
This PR fixes #97946.

The Neo2 keyboard layout (and others) have special keys (arrow keys, page up/down, tab, return, escape, ...) on layer 4. For example: `AltGr`+`D` = `DownArrow`. This bugfix makes the explorer view behave as expected if such a layer 4 down arrow (or any other arrow) is pressed.

grafik

### For testing:

* Activate for example the keyboard layout *Neo_qwerty* in Linux: `setxkbmap de neo_qwerty`
* Set _Keyboard: Dispatch_ to _keyCode_
* Click into the explorer view
* Press `AltGr` + `E` or `D` for going up and down
* Press `AltGr` + `S` or `F` for folding/unfolding folders

### CODE REVIEW

File: src/vs/base/browser/ui/tree/abstractTree.ts [hunk 1]
```diff
@@ -707,7 +707,7 @@ class TypeFilterController<T, TFilterData> implements IDisposable {
 			.map(e => new StandardKeyboardEvent(e))
 			.filter(this.keyboardNavigationEventFilter || (() => true))
 			.filter(() => this.automaticKeyboardNavigation || this.triggered)
-			.filter(e => this.keyboardNavigationDelegate.mightProducePrintableCharacter(e) || ((this.pattern.length > 0 || this.triggered) && ((e.keyCode === KeyCode.Escape || e.keyCode === KeyCode.Backspace) && !e.altKey && !e.ctrlKey && !e.metaKey) || (e.keyCode === KeyCode.Backspace && (isMacintosh ? (e.altKey && !e.metaKey) : e.ctrlKey) && !e.shiftKey)))
+			.filter(e => this.keyboardNavigationDelegate.mightProducePrintableCharacter(e) && !(e.keyCode === KeyCode.DownArrow || e.keyCode === KeyCode.UpArrow || e.keyCode === KeyCode.LeftArrow || e.keyCode === KeyCode.RightArrow) || ((this.pattern.length > 0 || this.triggered) && ((e.keyCode === KeyCode.Escape || e.keyCode === KeyCode.Backspace) && !e.altKey && !e.ctrlKey && !e.metaKey) || (e.keyCode === KeyCode.Backspace && (isMacintosh ? (e.altKey && !e.metaKey) : e.ctrlKey) && !e.shiftKey)))
```
Comment (joaomoreno) [inline src/vs/base/browser/ui/tree/abstractTree.ts:710]: I'm not a huge fan of having `&&` in the same level as `||` as it might appear ambiguous to unsuspecting readers. Please make it explicit by wrapping what needs to be wrapped in parenthesis.

**Review by joaomoreno — CHANGES_REQUESTED** [review]

File: src/vs/base/browser/ui/tree/abstractTree.ts (hunk 1 above)
Comment (MaxGyver83) [reply src/vs/base/browser/ui/tree/abstractTree.ts]: Sure, I made a commit for that. Thanks for your review!

**Comment by MaxGyver83** [comment]
@joaomoreno : After I have added the parantheses (which didn't change the code logic), some checks failed. But these failures don't seem to caused by my commits. I already tried merging upstream master several times but the checks keep failing (although the failures vary).

What can I do?

**Comment by joaomoreno** [comment]
All good, thanks for this! 🍻

**Comment by MaxGyver83** [comment]
Thank you for merging! 👍🏻
