### PR TITLE
Fix regression package.json task fail to re-run

### LINKED ISSUE #270296: The npm task failed to restart
Type: <b>Bug</b>

I started an npm task and it ran normally. When I clicked the restart button of the task, a pop-up prompt appeared :" The task watch-debug no longer exists or has been modified." It cannot be restarted.

VS Code version: Code 1.104.3 (385651c938df8a906869babee516bffd0ddb9829, 2025-10-02T12:30:51.747Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-14700KF (28 x 3418)|
|GPU Status|2d_canvas: enabled<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>trees_in_viz: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.85GB (17.35GB free)|
|Process Argv|--crash-reporter-id 4b7c247b-17d0-404b-8b9b-64063a299416|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
EnglishChineseDictionary|Cod|1.1.1
code-runner|for|0.12.2
copilot|Git|1.372.0
copilot-chat|Git|0.31.5
vscode-github-actions|git|0.28.0
gemini-cli-vscode-ide-companion|goo|0.7.0
jshook-vscode-extension|Jso|1.0.3
intellij-idea-keybindings|k--|1.7.5
vscode-language-pack-zh-hans|MS-|1.104.2025091009
vscode-python-envs|ms-|1.8.0
remote-wsl|ms-|0.104.3
vscode-typescript-next|ms-|6.0.20251007
gitmoji-vscode|sea|1.3.0
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
migrate-java-to-azure|vsc|1.5.2
vscode-gradle|vsc|3.17.0
vscode-java-upgrade|vsc|1.6.1
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
pythonvspyt551cf:31249601
binariesv615:30325510
nativeloc1:31344060
dwcopilot:31170013
dwoutputs:31242946
copilot_t_ci:31333650
e5gg6876:31282496
pythonrdcb7:31342333
usemplatestapi:31297334
6518g693:31334701
aj953862:31281341
cs4_fixed:31391938
b6b4d950:31327385
nes-set-on:31351930
6abeh943:31336334
envsdeactivate2:31353495
0cj2b977:31352657
gendocstringt:31395207
0574c672:31362109
cloudbuttont:31379625
todos-0:31390406
qwen_all_req:31396636
treatment_gpt5applypatchexclusively:31398171
3efgi100_wstrepl:31382709
trigger-command-fix:31379601
cmp-cht-code-control1:31397677
auto_model_enabled:31385282
use-responses-api:31390855
gemagent1cf:31396483
dcggh915:31397497

```

</details>

### PR DESCRIPTION
**Pull request by anthonykim1**
Task from package.json fail to re-run when ran by command palette.
/cc @meganrogge 
Resolves: https://github.com/microsoft/vscode/issues/270296

### CODE REVIEW

**Review by rzhao271 — DISMISSED** [review]

**Review by rzhao271 — DISMISSED** [review]

**Review by rzhao271 — DISMISSED** [review]

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 1]
```diff
@@ -2190,8 +2190,11 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
 			if (updatedTask) {
 				await this.run(updatedTask);
 			} else {
-				// Task no longer exists, show warning
-				this._notificationService.warn(nls.localize('TaskSystem.taskNoLongerExists', 'Task {0} no longer exists or has been modified. Cannot restart.', task.configurationProperties.name));
+				const success = await this.run(task);
+				if (success?.exitCode === 1 || success?.exitCode === 127) {
```
Comment (anthonykim1) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts]: Did not do non-zero here.
Realized success task could return exitCode undefined => 0, which we dont want to show notification.

**Review by rzhao271 — APPROVED** [review]

**Review by meganrogge — APPROVED** [review]
