### PR TITLE
Fix middle mouse button opening broken release notes link in browser

### LINKED ISSUE #76042: Inside VScode, in release notes, middle-clicking links opens broken link in browser
When middle clicking any of the links in the image, it opens the browser with a broken url

For example for the *remote development* link, the url is:
https://code.visualstudio.com/raw/#remote-development-preview

image

I'm Using Ubuntu 18.04

### PR DESCRIPTION
**Pull request by devsqrl**
Fixes #76042

The middle mouse button now has the same effect as the left and right mouse button. 
Clicking a link with the middle mouse button scrolls down to the clicked section instead of opening a broken link in the browser.

I tested this by temporarily changing the product version to 1.35 in package.json. Otherwise I was not able to open the release notes. I changed it back to 1.37 for this commit.

### CODE REVIEW

File: src/vs/workbench/contrib/webview/browser/pre/main.js [hunk 1]
```diff
@@ -443,7 +448,7 @@
 					});
 
 					// Bubble out link clicks
-					newFrame.contentWindow.addEventListener('click', handleInnerClick);
+					newFrame.contentWindow.addEventListener('mousedown', handleInnerClick);
```
Comment (diguifi) [inline src/vs/workbench/contrib/webview/browser/pre/main.js]: Why is this needed?

Comment (infmja) [reply src/vs/workbench/contrib/webview/browser/pre/main.js]: Because the click event only fires on left mouse button clicks. To prevent the middle mouse button from opening broken links in the browser, I needed to have an event that fires on middle clicks as well.

**Review by diguifi — APPROVED** [review]

**Comment by mjbvz** [comment]
Thanks! This will be in the next VS Code insiders build. We will see if it causes any problem for people using various input setups
