### PR TITLE
Git gutter not shown in workspace with multiple folders

### LINKED ISSUE #176738: Git gutter not shown in workspace with multiple folders
Type: <b>Bug</b>

To reproduce:
1. open VS Code
2. open a folder and choose a git repo with changes
3. open a file with changes and notice the gutter is shown
4. add a folder to the workspace and choose a git repo
5. notice the gutter is still visible
6. now close the file and reopen it

Expected behavior: the gutter is shown
Actual behavior: the gutter is not shown

@alexr00 this may be related to #176051. @joyceerhl actually [described](https://github.com/microsoft/vscode/issues/176051#issuecomment-1460604807) pretty much the same issue. However a reload (I assume that is `Developer: Reload Window`) doesn't help in this case.

VS Code version: Code - Insiders 1.77.0-insider (b60db78000bfa99d1b290194ed4651c4ceef02cc, 2023-03-10T05:24:23.805Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.61GB (2.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30659908
pythonb192cf:30661257
funwalk2cf:30682975
pythonms35:30671666
19089226:30680468
7ij38806:30677315

```

</details>

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #176738

When adding a folder to a workspace extension re-contribute their SCM. In this case, the old quick diff wasn't getting disposed.

This wasn't fixed by simply reloading becasue there was still a URI mismatch: the git extension gave the root URI with a lower case drive letter and the VS Code core often (depends on how the file was opened) give the file URI with an upper case drive letter.

### CODE REVIEW

File: src/vs/workbench/api/common/extHostSCM.ts [hunk 1]
```diff
@@ -757,7 +760,7 @@ export class ExtHostSCM implements ExtHostSCMShape {
 		});
 
 		const handle = ExtHostSCM._handlePool++;
-		const sourceControl = new ExtHostSourceControl(extension, this._proxy, this._commands, id, label, rootUri);
+		const sourceControl = new ExtHostSourceControl(extension, this._proxy, this._commands, id, label, rootUri ? normalizePath(rootUri.with({ path: toPosixPath(normalizeDriveLetter(rootUri.fsPath)) })) : undefined);
```
Comment (alexr00) [inline src/vs/workbench/api/common/extHostSCM.ts:763]: @joaomoreno I have no idea if this is safe to do for all of SCM. I can move it into the quick diff service if that would be better.

**Review by lszomoru — APPROVED** [review]
