### PR TITLE
Fix watch view context menu when Variables pane is hidden

### LINKED ISSUE #273721: Context menu in watch during debugging not working
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.105.1
- OS Version: Kubuntu 24.04

Hello,
since a few weeks, I’ve been unable to open the context menu in the Watch window during debugging (for example, to copy values).

Debugger: gdb
Language: C++

### PR DESCRIPTION
**Pull request by bryanchen-d**
## Problem
The context menu in the Watch view fails to appear during debugging when the Variables pane is hidden/collapsed. This prevents users from accessing debugging actions like "Break on Value Change", "Copy Value", etc.

Fixes: #273721

## Root Cause
When the Variables pane is hidden, we never fetches scope variables from the debug adapter. When the Watch view tries to get data breakpoint info for expressions, the debug adapter doesn't have the necessary variable context and throws "Unable to find child property" errors.

## Solution
Before requesting data breakpoint info, ensure the debug adapter has the necessary context:

For nested variable `s` (like x within expanded s):

* Fetch the parent's children to populate adapter state
* Pass the parent's `variablesReference`

For simple expressions (like `s` or `a`):
* Get the local scope from the focused stack frame
* Fetch the scope's variables to populate adapter state
* Pass the scope's `variablesReference`

For complex expressions (like `s.x`):

* Pass the expression with `frameId` and let the adapter parse it
* Fall back gracefully if not supported

Error handling:

* Wrap `dataBreakpointInfo()` calls in try-catch
* On failure, silently continue without data breakpoint menu items

### CODE REVIEW

File: src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts [hunk 1]
```diff
@@ -409,14 +408,65 @@ function getContextForWatchExpressionMenu(parentContext: IContextKeyService, exp
...
+						scopeReference = localScope.reference || 0;
+					}
+				}
+
+				dataBreakpointInfoResponse = await session.dataBreakpointInfo(
+					expressionName,
+					scopeReference
+				);
+			}
+		}
```
Comment (connor4312) [inline src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts:449]: I think passing the frameId is good but I'm confused why we need to look at scopes or check if the expression is nested. evaluateName is always expected to be based on the stackframe, so a scope reference is not needed. If there isn't an evaluate name, we should evaluate `expression.name` in the parent context which is `expression.parent`.

**Review by connor4312 — CHANGES_REQUESTED** [review]
comment

File: src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts (hunk 1 above)
Comment (bryanchen-d) [reply src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts:449]: When the Variables window is off, the scopes are not populated so here we have to populate the scope and pass it in. 
From my test, if we don't pass a scope reference here, the `dataBreakpointInfo()` throws "Unable to find child property".

Regarding the expression.parent, from my debug, it is undefined for a top-level expression like `s.x` (accessing a member variable in a struct object) or `a` (a simple variable)

Comment (connor4312) [reply src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts:449]: I'm still not sure why we need scopes. There's nothing in DAP that ties scopes to the `dataBreakpointInfo`. It needs only a name, and optionally variablesReference/frameId. We didn't pass the frameId before, and you fixed that here, which I think is good.

> Regarding the expression.parent, from my debug, it is undefined for a top-level expression like s.x (accessing a member variable in a struct object) or a (a simple variable)

Yea, that is intended. It's only defined for children of DAP Variables.

File: src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts [hunk 2]
```diff
@@ -408,63 +410,22 @@ function getContextForWatchExpressionMenu(parentContext: IContextKeyService, exp
...
-				}
-
-				dataBreakpointInfoResponse = await session.dataBreakpointInfo(
-					expressionName,
-					scopeReference
-				);
-			}
-		}
+		const expressionName = 'evaluateName' in expression ? expression.evaluateName as string : expression.name;
+		dataBreakpointInfoResponse = await session.dataBreakpointInfo(expressionName, undefined, stackFrame?.frameId);
```
Comment (connor4312) [inline src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts]: you had another change we should keep here:

- If there's an `expression.evaluateName`, then calling it as `evaluateName, undefined, frameId` is good
- If there's no `expression.evaluateName`, we should call it as `name, expression.parent.reference, frameId` when available

evaluateName is absolute, but `variable.name` is relative to its parent, so the parent reference should be preserved when possible

Comment (bryanchen-d) [reply src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts]: From the strong typing and also from my debugging, `expression.parent` is only avaiable when `expression instanceof Variable` is true. Can we assume when there is no `evaluateName` , the expression is a Variable?

Comment (bryanchen-d) [reply src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts]: From what I see in debugging, when there is a top level expression, for example, if user type `s` or `s.x` in the expression,  there is no evaluateName, nor expression.parent.

Comment (connor4312) [reply src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts]: For the top level expression, there will not be an expression.parent. For properties of the object/expression result, there will be a parent.

> expression.parent is only avaiable when expression instanceof Variable

Yes, if this is the case we should pass in the parent refrence when there is no `evaluateName`

**Review by connor4312 — APPROVED** [review]
