### PR TITLE
Fix branch checkout after git clone

### LINKED ISSUE #158386: Git uri handler clone should preserve branch
1. Invoke vscode-insiders://git.clone?https://github.com/microsoft/vscode/tree/release/1.70
2. Select a directory to clone your repo into
3. Open cloned repo
4. :bug: branch context is not preserved

This impacts Continue Working On--branch context is preserved for Clone in Container and Create New Codespace.
 
I propose adding a new optional query parameter to the uri handler here:
https://github.com/microsoft/vscode/blob/6cc52565f2ca557a3b0919aee29ac259be02c02f/extensions/git/src/protocolHandler.ts#L26-L33

and passing that to the `git.clone` command as an optional argument here
https://github.com/microsoft/vscode/blob/6cc52565f2ca557a3b0919aee29ac259be02c02f/extensions/git/src/protocolHandler.ts#L59

Then after cloning here:
https://github.com/microsoft/vscode/blob/6cc52565f2ca557a3b0919aee29ac259be02c02f/extensions/git/src/commands.ts#L517-L521
and before opening the repo in a new window, we would perform the ref checkout:
```ts
if (ref) {
    const repository = this.model.getRepository(Uri.file(repositoryPath));
    await repository?.checkout(ref);
}
```

### PR DESCRIPTION
**Pull request by joyceerhl**
This PR fixes https://github.com/microsoft/vscode/issues/158386

The previous implementation would always fail to discover the repository we were interested in, because `getRepository` only looks at repositories that are already known to the git extension, and the newly cloned git repo needs to be explicitly opened with `openRepository` first.

### CODE REVIEW

File: extensions/git/src/commands.ts [hunk 1]
```diff
@@ -519,9 +519,16 @@ export class CommandCenter {
...
-				const repository = this.model.getRepository(Uri.file(repositoryPath));
-				await repository?.checkout(options.ref);
+			const refToCheckoutAfterClone = options.ref;
+			if (refToCheckoutAfterClone !== undefined) {
+				await window.withProgress(
+					{
+						location: ProgressLocation.Notification,
+						title: localize('checking out ref', "Checking out ref '{0}'...", options.ref)
+					}, async () => {
+						const repository = await this.model.openRepository(repositoryPath).then(() => this.model.getRepository(repositoryPath));
```
Comment (lszomoru) [inline extensions/git/src/commands.ts:529]: Is there a particular reason why we are mixing `await` and `.then()`. Can't we do:
```ts
await this.model.openRepository(repositoryPath);
const repository = this.model.getRepository(repositoryPath);
await repository?.checkout(refToCheckoutAfterClone);
```

**Review by lszomoru — APPROVED** [review]
