### PR TITLE
Handle tree data provider error in getChildren

### LINKED ISSUE #4002: "No tree view with id 'github:compareChanges' registered" after opening PR
Testing #3985

After I created the PR, I got the error "No tree view with id 'github:compareChanges' registered."

I think these logs are related:
```
[Debug 1664465581.808s] PullRequestTree> Creating file and commit nodes for PR #2
[Debug 1664465582.89s] PullRequestOverviewPanel> pr.initialize
[Debug 1664465583.06s] PullRequestChangesTreeDataProvider> Error: TreeError [prStatus:github] Tree element not found: [object Object]
```

### PR DESCRIPTION
**Pull request by alexr00**
Fixes https://github.com/microsoft/vscode-pull-request-github/issues/4002

### CODE REVIEW

File: src/vs/workbench/browser/parts/views/treeView.ts [hunk 1]
```diff
@@ -344,8 +344,16 @@ abstract class AbstractTreeView extends Disposable implements ITreeView {
...
-						children = node.children ?? [];
+						try {
+							node.children = await (node instanceof Root ? dataProvider.getChildren() : dataProvider.getChildren(node));
+							children = node.children ?? [];
+						} catch (e) {
+							// It can happen that a tree view is hidden right as `getChildren` is called. This results in an error because the data provider gets removed.
+							// The tree will shortly get cleaned up in this case. We just need to handle the error here.
+							node.children = [];
+							children = [];
+							return children;
```
Comment (hediet) [inline src/vs/workbench/browser/parts/views/treeView.ts:355]: I think this is problematic, as it swallows arbitrary errors and makes debugging very hard.
What is the error that you want to catch?

**Review by hediet — CHANGES_REQUESTED** [review]
See comment. I think catch all clauses should be avoided as much as possible.

**Review by hediet — APPROVED** [review]
