### PR TITLE
remove microtask delay when refiltering suggestions

### LINKED ISSUE #161883: Pressing enter on autocomplete should always apply the selected dropdown completion, not a different, hidden one
- _VS Code Version_: 1.71.2
- _OS Version_: Windows 10 x64

**Steps to Reproduce**:

I'm experiencing this when using TypeScript. I'm not 100% sure why this happens but many times when typing a partial text, say like:
```
filter
```

I receive a list of completions, say the first one is:
```
filterBankSize
```
However, when pressing enter, instead of applying the completion, it applies a different completion that is not listed in the dropdown menu!

For example, in this case, it found a module that contained a function called `filter` and decided to import the `filter` function from it. However, a suggestion for `filter` did not appear on the dropdown!

After experimenting a bit with this I realized that the suggestion _did_ later appear in the dropdown (?), but not initially.

This is so strange. Is this an issue specific to the built-in TypeScript extension? (not sure?) or maybe has to do with the dropdown menu showing partial results (incremental loading?).

This kind of subtle unexpected behavior is actually kind of tricky to notice. I usually type so fast that I tend to ignore / overlook it and simply undo it immediately (it happens **a lot**!). It took a while until I came to realize there might be an issue here (I verified several times that a suggestion for "filter" did not appear initially, yet it still used it as a completion).

### PR DESCRIPTION
**Pull request by jrieken**
It seems now safe to read the editor position at the time of a document change event. This removes nasty faulty completion insertion for fast typists

fixes https://github.com/microsoft/vscode/issues/161883

### CODE REVIEW

File: src/vs/editor/contrib/suggest/browser/suggestModel.ts [hunk 1]
```diff
@@ -424,23 +425,12 @@ export class SuggestModel implements IDisposable {
 	}
 
 	private _refilterCompletionItems(): void {
-		// Re-filter suggestions. This MUST run async because filtering/scoring
-		// uses the model content AND the cursor position. The latter is NOT
-		// updated when the document has changed (the event which drives this method)
-		// and therefore a little pause (next mirco task) is needed. See:
-		// https://stackoverflow.com/questions/25915634/difference-between-microtask-and-macrotask-within-an-event-loop-context#25933985
-		Promise.resolve().then(() => {
-			if (this._state === State.Idle) {
```
Comment (jrieken) [inline src/vs/editor/contrib/suggest/browser/suggestModel.ts:433]: @alexdima In past this microtask delay was needed because document change listeners that read the position of the matching editor had a chance of retrieving the old position. 

I believe we briefly touched on this in the past that it isn't needed anymore and my testing shows that this might be true. Please confirm and review

Comment (alexdima) [reply src/vs/editor/contrib/suggest/browser/suggestModel.ts:433]: Yes, this is safe now since https://github.com/microsoft/vscode/commit/00b43acca3174313700d5e78ec0c61c794841cac

**Review by alexdima — APPROVED** [review]
