### PR TITLE
fix decoration padding problems

### LINKED ISSUE #144259: left padding is removed when clear is run
context: when shell integration or command decorations are disabled, the  class `shell-integration` should be removed from `xterm` so that the left-padding for split terminal 2 and beyond is `10px` instead of `20px`.

to reproduce the bug:
- on mac, with shell integration and command decorations enabled, create 2-3 split terminals
- run `clear` in the 2nd or 3rd split
- 🐛  the left padding of that terminal has gone from `20px` to `10px`

### LINKED ISSUE #144263: Shell integration gutter padding problems
Recording 2022-03-02 at 09 37 11

Notice:

- The left-most terminal should always have this padding, regardless of whether shell integration is on or off.
- When creating a new terminal the terminal starts with a small amount of padding and then the text shifts to the right shortly afterwards.

We may be checking something about the terminal to determine this padding but I think the setting should just have this padding on all terminals regardless of their status to avoid this text shifting problem. Resizing xterm.js is also an expensive action that could resize the cols, which could lead to weird behavior.

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #144259
fixes #144263

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 1]
```diff
@@ -167,12 +166,12 @@ export class DecorationAddon extends Disposable implements ITerminalAddon {
 		if (!command.marker) {
 			throw new Error(`cannot add a decoration for a command ${JSON.stringify(command)} with no marker`);
 		}
-
 		const decoration = this._terminal.registerDecoration({ marker: command.marker });
 		if (!decoration) {
 			return undefined;
 		}
 		decoration.onRender(element => {
+			decoration.onDispose(() => this._decorations.delete(decoration.marker.id));
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:174]: before, the decorations weren't getting updated when:
clear -> marker dispose -> decoration dispose

File: src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts [hunk 2]
```diff
@@ -89,15 +89,17 @@ export class DecorationAddon extends Disposable implements ITerminalAddon {
...
+		if (disableDecorations) {
 			this._commandStartedListener?.dispose();
 			this._commandFinishedListener?.dispose();
 		}
 		this._placeholderDecoration?.dispose();
 		this._placeholderDecoration?.marker.dispose();
 		for (const value of this._decorations.values()) {
-			value.decoration.element?.parentElement?.parentElement?.parentElement?.classList.remove(DecorationSelector.ShellIntegration);
+			if (disableDecorations) {
+				value.decoration.element?.parentElement?.parentElement?.parentElement?.classList.remove(DecorationSelector.ShellIntegration);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts:101]: actually still a wip bc just realized this element is undefined by this time

File: src/vs/workbench/contrib/terminal/browser/media/terminal.css [hunk 3]
```diff
@@ -93,6 +93,7 @@
 	display: block;
 }
 
+.monaco-workbench .pane-body.integrated-terminal .terminal-group .monaco-split-view2.horizontal .split-view-view:first-child .xterm,
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/media/terminal.css:96]: I think it would be better to have this at the view level since it's a global terminal thing, similar to bold:

https://github.com/microsoft/vscode/blob/210f772b0174eb7c3d3ebb17ddbba67d887e5fe2/src/vs/workbench/contrib/terminal/browser/media/terminal.css#L165-L172

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/media/terminal.css (hunk 3 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/media/terminal.css:96]: Not sure what you're proposing 🤔

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/media/terminal.css:96]: need to have access to the `split-view-view` in order to know if it's the `first-child`

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/media/terminal.css:96]: Oh the bold rule doesn't seem to be used anymore 🤔 

I mean moving assigning the class into `terminalView`, so it's set/unset on only a single element

Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/media/terminal.css:96]: not sure why, but this at the moment only applies to the last created terminal (as opposed to the leftmost)

File: src/vs/workbench/contrib/terminal/browser/terminalView.ts [hunk 4]
```diff
@@ -110,6 +110,22 @@ export class TerminalViewPane extends ViewPane {
 				this._terminalTabbedView?.rerenderTabs();
 			}
 		}));
+		configurationService.onDidChangeConfiguration(e => {
+			if ((e.affectsConfiguration(TerminalSettingId.ShellIntegrationDecorationsEnabled) && !configurationService.getValue(TerminalSettingId.ShellIntegrationDecorationsEnabled)) ||
+				(e.affectsConfiguration(TerminalSettingId.ShellIntegrationEnabled) && !configurationService.getValue(TerminalSettingId.ShellIntegrationEnabled))) {
+				this._parentDomElement?.children[2].querySelectorAll(`.xterm`).forEach(e => e.classList.remove('shell-integration'));
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalView.ts:116]: Can we set it on this element so we don't need to do it for every terminal? Simpler and this will probably fall apart when adding new terminals

Screen Shot 2022-03-02 at 2 58 49 pm

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalView.ts (hunk 4 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalView.ts:116]: We need to adjust the left padding for each terminal though in order to make room for the decoration

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalView.ts:116]: I mean doing this:

```css
.integrated-terminal.shell-integration-enabled .xterm {
	padding-left: 20px !important;
}
```

Instead of:

```css
.monaco-split-view2.vertical .split-view-view .xterm.shell-integration {
	padding-left: 20px !important;
}
```
