### PR TITLE
Write selection text to hidden textarea on macOS

### LINKED ISSUE #27799: macOS: OS services cannot pick up selected text from editor
Testing #1628

**steps to reproduce**
- On a mac, open a text file and try selecting a line of text in the editor
- Run the `create sticky note` service. This is under the `code -> Services` menu or can be triggered with `cmd + shift + y`

**Expected**
The selected text in the editor is opened in a new sticky note

**Actual**
Some other text is opened in the new sticky note. I'm not sure where we are getting it from

### PR DESCRIPTION
**Pull request by pingren**
Fixes https://github.com/microsoft/vscode/issues/27799

#### Explanation

- macOS services will use `textarea` content and selection as an input source.

- this hidden `textarea` is originally for screen readers or accessibility devices. However, the textarea could be empty when user selecting text on macOS.
- read more details in
https://github.com/microsoft/vscode/issues/27799#issuecomment-1200088452

#### Before

macOS services are not available when `editor.accessibilitySupport` setting is `off` or `auto`

#### After (hidden textarea is made visible for illustration)

https://user-images.githubusercontent.com/5123601/181925024-a5528308-e13c-427f-94b2-ba6d40e7be32.mp4

### CODE REVIEW

**Review by hediet — DISMISSED** [review]

File: src/vs/editor/browser/controller/textAreaHandler.ts [hunk 1]
```diff
@@ -242,6 +242,17 @@ export class TextAreaHandler extends ViewPart {
 							return new TextAreaState(textBefore, textBefore.length, textBefore.length, position, position);
 						}
 					}
+					// on macOS, write current selection into textarea will allow system text services pick selected text
+					// https://github.com/microsoft/vscode/issues/27799#issuecomment-1200088452
+					if (platform.isMacintosh && !selection.isEmpty()) {
```
Comment (bpasero) [inline src/vs/editor/browser/controller/textAreaHandler.ts:247]: I am a little bit concerned about performance here, maybe I have a 2 GB text file open and select all. This would mean we end up converting 2 GB of text into a string only then to `substring` it.

Could we do some heuristics and check how large the selection is and not do this if the number of selected text is already exceeding our limit? There maybe API to figure out the selection size efficiently, or we just guess it.

Tbh I would not expect this to work with a substring of my selection, I would rather expect the text area to be empty when we hit the limit, otherwise the user may be very confused why only parts of the text are taken over?

**Review by bpasero — CHANGES_REQUESTED** [review]

File: src/vs/editor/browser/controller/textAreaHandler.ts (hunk 1 above)
Comment (isidorn) [reply src/vs/editor/browser/controller/textAreaHandler.ts:247]: +1 make sure to keep in mind the performance limiation of Chromium for large text areas
Issue with more details on Chromium side https://bugs.chromium.org/p/chromium/issues/detail?id=1076525

**Review by bpasero — APPROVED** [review]
Pushed a change to use `getValueLengthInRange` to avoid large allocations.

File: src/vs/editor/browser/controller/textAreaHandler.ts (hunk 1 above)
Comment (bpasero) [reply src/vs/editor/browser/controller/textAreaHandler.ts]: via https://github.com/microsoft/vscode/pull/156717/commits/8086f29bc26154eb2bbae8df8d9f41a4f5451dec

**Review by hediet — APPROVED** [review]

**Comment by pingren** [comment]
I have read comments, but I am too busy to pick this up. Thank you for the improvement! Couldn't agree more!
