### PR TITLE
Fix #114432: Multiple save dialogs appearing on Windows if Ctrl+S is pressed multiple times

### LINKED ISSUE #114432: Repeated CTRL+S Causes Multiple Save Dialogues
Issue Type: <b>Bug</b>

If you create a new file and then CNTL+S several times, clicking Cancel causes another save dialogue to show up. I have a tendendy to slam this keyboard shortcut many times (maybe some sort of nervous tick :-) ) but then I have to sit there and hit Cancel as many times as I pressed the keys.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (15.76GB free)|
|Process Argv|--crash-reporter-id 22865162-8583-4afc-9d43-fef955820053|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
vscode-sbt-scala|lig|0.2.4
vscode-docker|ms-|1.9.0
csharp|ms-|1.23.8
vscode-postgresql|ms-|0.3.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.2
remote-wsl|ms-|0.52.0
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.3.3
java|red|0.73.0
vscode-xml|red|0.14.0
rust|rus|0.7.8
scala|sca|0.5.0
code-spell-checker|str|1.10.2
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.17.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.27.0
vscode-maven|vsc|0.27.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt700:30244268
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30242242
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30236629

```

</details>

### PR DESCRIPTION
**Pull request by CameronIrvine**
This PR fixes #114432

I've added a basic condition check to the pickFileToSave method inside the FileDialogService.

This ensures that the file save dialog will only appear if there isn't one already open and will prevent multiple dialogs appearing if Ctrl+S is spammed a few times on Windows.

This is my first contribution here and I'm still very new to this codebase, so please let me know if there is a more elegant solution (or if Electron provides this kind of functionality somewhere).

### CODE REVIEW

**Comment by alexr00** [comment]
The simple file dialog won't have this problem. I can't actually repro the original issue on Windows.

**Comment by CameronIrvine** [comment]
Doesn't seem to affect anything other than the native save dialogs for Windows. I've been able to repro this by repeatedly pressing Ctrl+S (holding it down doesn't seem to do anything).

It looks like it could be an issue with Electron's `dialog.showSaveDialog` but I could be wrong.

**Review by bpasero — CHANGES_REQUESTED** [review]
I was able to reproduce this even for the "Open" dialog but it is harder. Looking at the code, we already seem to be queueing up requests for dialogs per window:

https://github.com/microsoft/vscode/blob/878bf135043770f5e2270378b2376bc5e3f8deac/src/vs/platform/dialogs/electron-main/dialogMainService.ts#L126-L138

I cannot recall why this queue was added but now that I think about it, it would imho make more sense to not queue requests but rather ignore them per window when a dialog is already showing. I would try with that approach instead.

**Comment by CameronIrvine** [comment]
Thanks @bpasero for pointing me in the right direction.

I've updated my solution with changes now focused on the dialogMainService.

With this change only 1 instance of either the open file dialog or save file dialog can exist for a given window. I've left the queueing stuff there for the message box dialogs though as I think there may still be a use for it (can be easily changed if this isn't the case).

**Comment by bpasero** [comment]
@CameronIrvine I pushed https://github.com/microsoft/vscode/pull/114450/commits/0ba463585e42dd41e7752861f828593740ec87b3 to your branch and now I am asking you for a review + testing. Summary:
* change method to `acquireFileDialogLock` and simplify by returning a `IDisposable` for releasing
* make sure to preserve the previous semantic of waiting on any queued message box via `joinMessageBoxQueue`
* most importantly: throw an `Error` when a file dialog is already opened instead of returning a bogus result

**Comment by bpasero** [comment]
Now that I think more about it: should we only block dialogs that have the same options? Imho it would still be valid to queue save/open dialog that have different properties, because the only thing we really want to block is the same dialog opening again (e.g. when you hit `Ctrl+S` multiple times).

**Comment by alexr00** [comment]
It is possible that a dialog could have the same options but become from a different source, so I'm not sure that gating the queueing on whether the options are the same will be helpful.

**Comment by bpasero** [comment]
Yeah it is a tradeoff, I am open for better ideas.

**Comment by CameronIrvine** [comment]
Those changes look good to me @bpasero, definitely a lot nicer returning errors rather than falsified dialog results. I've manually tested them and can confirm they're behaving as expected.

As for queueing I'm not sure if there's a better alternative to using options. One other way I thought of is if we sent a source ID string along with each dialog request but that might not be ideal and could probably get messy.

**Comment by bpasero** [comment]
Yeah agree, I would go with queueing by options for now. We have a `hash` utility in `base` that could be used I think.

**Comment by CameronIrvine** [comment]
I've made some changes based on your suggestions @bpasero.

Dialog requests for each window are now queued if their options don't match the hash of a currently queued dialog's options.

File: src/vs/platform/dialogs/electron-main/dialogMainService.ts [hunk 1]
```diff
@@ -123,31 +124,45 @@ export class DialogMainService implements IDialogMainService {
...
-		return this.getDialogQueue(window).queue(async () => {
-			if (window) {
-				return dialog.showMessageBox(window, options);
-			}
+	async showMessageBox(options: MessageBoxOptions, window?: BrowserWindow): Promise<MessageBoxReturnValue> {
 
-			return dialog.showMessageBox(options);
-		});
+		// prevent duplicates of the same dialog queueing at the same time
+		const fileDialogLock = await this.acquireFileDialogLock(options, window);
```
Comment (bpasero) [inline src/vs/platform/dialogs/electron-main/dialogMainService.ts:147]: I would not have expected the use of `fileDialogLock` inside the `showMessageBox` method. I would leave the newly introduced lock only for `showSaveDialog` and `showOpenDialog`

File: src/vs/platform/dialogs/electron-main/dialogMainService.ts [hunk 2]
```diff
@@ -181,27 +206,71 @@ export class DialogMainService implements IDialogMainService {
...
+				result.filePaths = normalizePaths(result.filePaths);
+
+				return result;
+			});
+		} finally {
+			dispose(fileDialogLock);
+		}
+	}
+
+	private async acquireFileDialogLock(options: any = {}, window?: BrowserWindow): Promise<IDisposable | undefined> {
```
Comment (bpasero) [inline src/vs/platform/dialogs/electron-main/dialogMainService.ts:241]:
```suggestion
	private async acquireFileDialogLock(options: SaveDialogOptions | OpenDialogOptions, window?: BrowserWindow): Promise<IDisposable | undefined> {
```

File: src/vs/platform/dialogs/electron-main/dialogMainService.ts [hunk 3]
```diff
@@ -181,27 +206,71 @@ export class DialogMainService implements IDialogMainService {
...
+		}
+
+		// if a window is provided, only allow a single dialog
+		// at the same time because dialogs are modal and we
+		// do not want to open one dialog after the other
+		// (https://github.com/microsoft/vscode/issues/114432)
+		let windowDialogLocks = this.windowDialogLocks.get(window.id);
+		const optionsHash = hash(options);
+
+		if (windowDialogLocks?.has(optionsHash)) {
```
Comment (bpasero) [inline src/vs/platform/dialogs/electron-main/dialogMainService.ts:256]:
```suggestion

		// figure out if a dialog with these options is already
		// showing by hashing the options
		const optionsHash = hash(options);
		if (windowDialogLocks?.has(optionsHash)) {
```

File: src/vs/platform/dialogs/electron-main/dialogMainService.ts [hunk 4]
```diff
@@ -181,27 +206,71 @@ export class DialogMainService implements IDialogMainService {
...
+			return undefined;
+		}
 
-			return result;
+		if (!windowDialogLocks) {
+			windowDialogLocks = new Set([optionsHash]);
+			this.windowDialogLocks.set(window.id, windowDialogLocks);
+		}
+		windowDialogLocks.add(optionsHash);
```
Comment (bpasero) [inline src/vs/platform/dialogs/electron-main/dialogMainService.ts:264]:
```suggestion
		if (!windowDialogLocks) {
			windowDialogLocks = new Set();
			this.windowDialogLocks.set(window.id, windowDialogLocks);
		}
		
		windowDialogLocks.add(optionsHash);
```

File: src/vs/platform/dialogs/electron-main/dialogMainService.ts [hunk 5]
```diff
@@ -181,27 +206,71 @@ export class DialogMainService implements IDialogMainService {
...
+
+		return toDisposable(() => {
+			const windowDialogLocks = this.windowDialogLocks.get(window.id);
+			windowDialogLocks?.delete(optionsHash);
+
+			// if the window has no more dialog locks, delete it from windowDialogLocks
```
Comment (bpasero) [inline src/vs/platform/dialogs/electron-main/dialogMainService.ts:270]:
```suggestion
			// if the window has no more dialog locks, delete it from the set of locks
```

File: src/vs/platform/dialogs/electron-main/dialogMainService.ts [hunk 6]
```diff
@@ -181,27 +206,71 @@ export class DialogMainService implements IDialogMainService {
...
+			if (!this.windowDialogLocks.get(window.id)?.size) {
```
Comment (bpasero) [inline src/vs/platform/dialogs/electron-main/dialogMainService.ts:271]:
```suggestion
			if (windowDialogLocks?.size === 0) {
```

File: src/vs/platform/dialogs/electron-main/dialogMainService.ts [hunk 7]
```diff
@@ -157,21 +172,31 @@ export class DialogMainService implements IDialogMainService {
...
 
-		return this.getDialogQueue(window).queue(async () => {
-			let result: SaveDialogReturnValue;
-			if (window) {
-				result = await dialog.showSaveDialog(window, options);
-			} else {
-				result = await dialog.showSaveDialog(options);
-			}
+		// prevent duplicates of the same dialog queueing at the same time
+		const fileDialogLock = await this.acquireFileDialogLock(options, window);
```
Comment (bpasero) [inline src/vs/platform/dialogs/electron-main/dialogMainService.ts:176]: Why is `acquireFileDialogLock` awaited, this method is not using any promises? I would remove the `async` from it.

File: src/vs/platform/dialogs/electron-main/dialogMainService.ts [hunk 8]
```diff
@@ -48,14 +50,13 @@ export class DialogMainService implements IDialogMainService {
 
 	private static readonly workingDirPickerStorageKey = 'pickerWorkingDir';
 
-	private readonly mapWindowToDialogQueue: Map<number, Queue<void>>;
-	private readonly noWindowDialogQueue: Queue<void>;
+	private readonly windowDialogLocks = new Map<number, Set<number>>();
+	private readonly windowDialogQueues = new Map<number, Queue<any>>();
+	private readonly noWindowDialogueQueue = new Queue<any>();
```
Comment (bpasero) [inline src/vs/platform/dialogs/electron-main/dialogMainService.ts:55]: I know we had `any` before already but I would really like us to remove `any` and rather use the or type `MessageBoxReturnValue | SaveDialogReturnValue | OpenDialogReturnValue` here because that is what the queue is used for. This needs a few tweaks in `getWindowDialogQueue`, i.e. change that method to:

```ts
private getWindowDialogQueue<T extends MessageBoxReturnValue | SaveDialogReturnValue | OpenDialogReturnValue>(window?: BrowserWindow): Queue<T> {
```

but I think that makes it clear.

**Review by bpasero — CHANGES_REQUESTED** [review]

File: src/vs/platform/dialogs/electron-main/dialogMainService.ts (hunk 7 above)
Comment (CameronIrvine) [reply src/vs/platform/dialogs/electron-main/dialogMainService.ts]: Oops, fixed in 1e9e036

File: src/vs/platform/dialogs/electron-main/dialogMainService.ts (hunk 1 above)
Comment (CameronIrvine) [reply src/vs/platform/dialogs/electron-main/dialogMainService.ts]: Agreed, fixed in 7106e19

File: src/vs/platform/dialogs/electron-main/dialogMainService.ts (hunk 8 above)
Comment (CameronIrvine) [reply src/vs/platform/dialogs/electron-main/dialogMainService.ts:55]: Changed to what you've suggested in ae5d9e4

Comment (bpasero) [inline src/vs/platform/dialogs/electron-main/dialogMainService.ts:55]: Can we still get rid of these 2 `any` usages somehow?

File: src/vs/platform/dialogs/electron-main/dialogMainService.ts [hunk 9]
```diff
@@ -123,22 +124,25 @@ export class DialogMainService implements IDialogMainService {
...
+			return windowDialogQueue;
+		} else {
+			return this.noWindowDialogueQueue;
+		}
 	}
 
-	showMessageBox(options: MessageBoxOptions, window?: BrowserWindow): Promise<MessageBoxReturnValue> {
-		return this.getDialogQueue(window).queue(async () => {
+	async showMessageBox(options: MessageBoxOptions, window?: BrowserWindow): Promise<MessageBoxReturnValue> {
+		return await this.getWindowDialogQueue<MessageBoxReturnValue>(window).queue(async () => {
```
Comment (bpasero) [inline src/vs/platform/dialogs/electron-main/dialogMainService.ts:145]:
```suggestion
	showMessageBox(options: MessageBoxOptions, window?: BrowserWindow): Promise<MessageBoxReturnValue> {
		return this.getWindowDialogQueue<MessageBoxReturnValue>(window).queue(async () => {
```

File: src/vs/platform/dialogs/electron-main/dialogMainService.ts [hunk 10]
```diff
@@ -157,21 +161,31 @@ export class DialogMainService implements IDialogMainService {
...
-			let result: SaveDialogReturnValue;
-			if (window) {
-				result = await dialog.showSaveDialog(window, options);
-			} else {
-				result = await dialog.showSaveDialog(options);
-			}
+		// prevent duplicates of the same dialog queueing at the same time
+		const fileDialogLock = this.acquireFileDialogLock(options, window);
+		if (!fileDialogLock) {
+			throw new Error('A dialog is already showing for the window');
```
Comment (bpasero) [inline src/vs/platform/dialogs/electron-main/dialogMainService.ts:167]:
```suggestion
			throw new Error('A file save dialog is already showing for the window with the same configuration');
```

File: src/vs/platform/dialogs/electron-main/dialogMainService.ts [hunk 11]
```diff
@@ -181,27 +195,74 @@ export class DialogMainService implements IDialogMainService {
...
+			const pathExists = await exists(options.defaultPath);
+			if (!pathExists) {
+				options.defaultPath = undefined;
+			}
+		}
+
+		// prevent duplicates of the same dialog queueing at the same time
+		const fileDialogLock = this.acquireFileDialogLock(options, window);
+		if (!fileDialogLock) {
+			throw new Error('A dialog is already showing for the window');
```
Comment (bpasero) [inline src/vs/platform/dialogs/electron-main/dialogMainService.ts:209]:
```suggestion
			throw new Error('A file open dialog is already showing for the window with the same configuration');
```

**Review by bpasero — CHANGES_REQUESTED** [review]
Thanks, almost there...

File: src/vs/platform/dialogs/electron-main/dialogMainService.ts (hunk 8 above)
Comment (CameronIrvine) [reply src/vs/platform/dialogs/electron-main/dialogMainService.ts:55]: Not quite sure of the best approach for this. I've attempted to use `MessageBoxReturnValue | SaveDialogReturnValue | OpenDialogReturnValue` for the queues but have had some trouble with getting them to work in `getWindowDialogQueue`.

I don't have a lot of experience with TS generics so I might be missing something really obvious here.

Open to any suggestions.

**Comment by bpasero** [comment]
Ok I will go ahead and merge this, I can look into the typing issue. Thanks a lot!
