### PR TITLE
Move profile resolving to pty service

### LINKED ISSUE #121760: If terminal.integrated.shell doesn't have a matching terminal.integrated.profiles entry the shell path will be ' '
- VS Code Version: 1.55.1
- OS Version: Windows 10 20H2 build 19042.867

Hello 👋 The Python extension uses [the content of the `terminal.integrated.shell.<os>` setting](https://github.com/microsoft/vscode-python/blob/main/src/client/common/terminal/shellDetectors/settingsShellDetector.ts#L30-L51) to determine which shell is currently used and which virtual environment activation command should be sent.

However, as reported in https://github.com/microsoft/vscode-python/issues/15919#issuecomment-820354564, if the path specified in `terminal.integrated.shell.<os>` does not have a corresponding `terminal.integrated.profiles.<os>` entry, the value returned by `terminal.integrated.shell.<os>` will be '', and terminal type detection will fail.

Steps to Reproduce:

1. Install Powershell 7 in a non-standard path (for example, outside of the system drive)
2. Add the path to the newly installed shell to `terminal.integrated.shell.windows`
3. Retrieve the value of `terminal.integrated.shell.windows` using `workspace.getConfiguration()`

Does this issue occur when all extensions are disabled?: Yes

### LINKED ISSUE #122534: Profile evaluation should happen on the pty host, not extension host
Right now we fetch profiles on the extension host regardless of whether the window is local or remote, this would be better if it was moved to the pty host because:

- That's where similar functions related to terminal management are
- Initial profile fetching won't be blocked by the extension host's delayed start up time
- We can simplify the extension host implementation as it won't need to deal with profiles (default shell stuff should also be moved out eventually)

### LINKED ISSUE #123163: VsCode 1.56 - When start debuging, Windows Powershell terminal is opened instead of Git Bash
- VS Code Version: 1.56.0
- OS Version: Windows 10

Steps to Reproduce:

1.Open Visual Studio code
2. Do CTRL + SHIFT + P  , and select "Terminal: Select Default Profile".
3. Select Git Bash.
4. Close all the terminal.
5. On the main menu, click Terminal >  New Terminal ( a bash Terminal is opened ok)
6. Click Run > Start debuging ,  the terminal switch to powershell

The only workaround is to keep using the following information in the user setting.json files 
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  But it is mentioned as deprecated
 
If I use the following setting , the same problems occurs ( windows powershell terminal opens instead of git bash)
```
   "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "path": [
                "C:\\Program Files\\Git\\bin\\bash.exe",
            ],
            "source": "Git Bash",
            "icon": "terminal-bash"
        },
        "Windows PowerShell": {
            "path": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
        }
    },
```
Thanks in advance

Does this issue occur when all extensions are disabled?: Yes

### LINKED ISSUE #123188: terminal.integrated.defaultProfile.windows not working on startup
Issue Type: <b>Bug</b>

Hello!

## current behavior:
From when I upgraded to this version when I set the default terminal to git bash and start VScode, for less than 2 seconds it shows `starting...` in the terminal's drop-down menu and then opens `PowerShell`  but after that when I add a new terminal `git bash` opens which is the default.

## Expected behavior:
I expect `git bash` which I have set as my default terminal profile to be opened at startup and afterward.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) II X2 270 Processor (2 x 3416)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.00GB (2.82GB free)|
|Process Argv|--crash-reporter-id 175e6498-4ca0-4d8a-815a-1ce71fc18411|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30294352

```

</details>

### LINKED ISSUE #123479: Default profile doesn't apply to tasks
From @alumni in https://github.com/microsoft/vscode/issues/96732#issuecomment-836798731

One more thing, after the addition of shell profiles. Currently I have the following setting:
```json
"terminal.integrated.defaultProfile.windows": "Git Bash",
```
However, NPM scripts are still running with PowerShell. I'm looking forward for this `automationProfile` to be added, but it would also be nice if `defaultProfile` would work if `automationProfile` is not set.

### LINKED ISSUE #123732: Don't go to the ext host for default terminal shell/args in tasks
I noticed this call here which goes to the exthost:

https://github.com/microsoft/vscode/blob/2e2dc1594518fb0e907a6a4c0a7888015d00e327/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1024-L1024

It seems to be the only usage of that proxy call, you can now call this on the renderer for the same thing:

```ts
ITerminalProfileResolverService.getDefaultProfile({
  os: terminalBackendOS, // probably remoteAgentService.getEnvironment().os || OS
  remoteAuthority: terminalBackendRemoteAuthority,
  allowAutomationShell: true
});
```

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #122534
Fixes #123188
Fixes #123479
Fixes #123163
Fixes #123732
Fixes #121760
Related microsoft/vscode-python#16175

---

TODO:

- [x] Test env.shell
- [x] Clean up/todos
- [x] Resync main

### CODE REVIEW

File: src/vs/platform/configuration/common/configurationModels.ts [hunk 1]
```diff
@@ -210,6 +210,7 @@ export class DefaultConfigurationModel extends ConfigurationModel {
 				});
 			}
 		}
+		console.log({ contents, keys, overrides });
```
Comment (meganrogge) [inline src/vs/platform/configuration/common/configurationModels.ts]: remove?

File: src/vs/platform/configuration/common/configurationRegistry.ts [hunk 2]
```diff
@@ -195,6 +195,7 @@ class ConfigurationRegistry implements IConfigurationRegistry {
 	}
 
 	public registerConfiguration(configuration: IConfigurationNode, validate: boolean = true): void {
+		console.trace('registerConfiguration', configuration);
```
Comment (meganrogge) [inline src/vs/platform/configuration/common/configurationRegistry.ts]: remove?

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 3]
```diff
@@ -329,26 +330,28 @@ export class TerminalService implements ITerminalService {
...
 	private async _detectProfiles(configuredProfilesOnly: boolean): Promise<ITerminalProfile[]> {
-		await this._extensionService.whenInstalledExtensionsRegistered();
-		// Wait for the remoteAuthority to be ready (and listening for events) before firing
-		// the event to spawn the ext host process
-		const conn = this._remoteAgentService.getConnection();
-		const remoteAuthority = conn ? conn.remoteAuthority : 'null';
-		await this._whenExtHostReady(remoteAuthority);
-		return new Promise(r => this._onRequestAvailableProfiles.fire({ callback: r, configuredProfilesOnly: configuredProfilesOnly }));
+		const offProcService = this._offProcessTerminalService;
+		console.log('offProcService?', offProcService);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:344]: remove?

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 4]
```diff
@@ -329,26 +330,28 @@ export class TerminalService implements ITerminalService {
...
+		return offProcService?.getProfiles(!configuredProfilesOnly);
 	}
 
-	private async _whenExtHostReady(remoteAuthority: string): Promise<void> {
-		this._createExtHostReadyEntry(remoteAuthority);
-		return this._extHostsReady[remoteAuthority]!.promise;
-	}
+	// private async _whenExtHostReady(remoteAuthority: string): Promise<void> {
+	// 	this._createExtHostReadyEntry(remoteAuthority);
+	// 	return this._extHostsReady[remoteAuthority]!.promise;
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:353]: remove?

File: src/vs/platform/terminal/node/ptyService.ts [hunk 5]
```diff
@@ -177,6 +177,12 @@ export class PtyService extends Disposable implements IPtyService {
 		return getSystemShell(osOverride, process.env);
 	}
 
+	// async getProfiles(includeDetectedProfiles: boolean = false): Promise<ITerminalProfile[]> {
```
Comment (meganrogge) [inline src/vs/platform/terminal/node/ptyService.ts:180]: remove?

File: src/vs/workbench/api/node/extHostTerminalService.ts [hunk 6]
```diff
@@ -3,52 +3,18 @@
...
-import { IWorkspaceFolder } from 'vs/platform/workspace/common/workspace';
-import { IShellAndArgsDto } from 'vs/workbench/api/common/extHost.protocol';
-import { ExtHostConfigProvider, ExtHostConfiguration, IExtHostConfiguration } from 'vs/workbench/api/common/extHostConfiguration';
-import { ExtHostVariableResolverService } from 'vs/workbench/api/common/extHostDebugService';
-import { ExtHostDocumentsAndEditors, IExtHostDocumentsAndEditors } from 'vs/workbench/api/common/extHostDocumentsAndEditors';
-import { IExtHostEditorTabs } from 'vs/workbench/api/common/extHostEditorTabs';
 import { IExtHostRpcService } from 'vs/workbench/api/common/extHostRpcService';
 import { BaseExtHostTerminalService, ExtHostTerminal } from 'vs/workbench/api/common/extHostTerminalService';
-import { ExtHostWorkspace, IExtHostWorkspace } from 'vs/workbench/api/common/extHostWorkspace';
-import { ITerminalProfile, TerminalSettingId } from 'vs/workbench/contrib/terminal/common/terminal';
```
Comment (meganrogge) [inline src/vs/workbench/api/node/extHostTerminalService.ts:21]: woah 👀 💣

File: src/vs/workbench/contrib/terminal/browser/terminalProfileResolverService.ts [hunk 7]
```diff
@@ -149,12 +149,16 @@ export abstract class BaseTerminalProfileResolverService implements ITerminalPro
 		// If either shell or shellArgs are specified, they will take priority for now until we
 		// allow users to migrate, see https://github.com/microsoft/vscode/issues/123171
 		const shellSettingProfile = await this._getUnresolvedShellSettingDefaultProfile(options);
+		console.log('shellSettingProfile', shellSettingProfile);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalProfileResolverService.ts:152]: remove?

File: src/vs/workbench/contrib/terminal/browser/terminalProfileResolverService.ts [hunk 8]
```diff
@@ -149,12 +149,16 @@ export abstract class BaseTerminalProfileResolverService implements ITerminalPro
...
 		if (shellSettingProfile) {
 			return shellSettingProfile;
 		}
 
-		// Return the real default profile if it exists and is valid
+		// Return the real default profile if it exists and is valid, wait for profiles to be ready
+		// if the window just opened
+		await this._terminalService.profilesReady;
 		const defaultProfile = this._getUnresolvedRealDefaultProfile(options.os);
+		console.log('defaultProfile', defaultProfile);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalProfileResolverService.ts:161]: remove?

File: src/vs/workbench/contrib/terminal/browser/terminalProfileResolverService.ts [hunk 9]
```diff
@@ -166,7 +170,9 @@ export abstract class BaseTerminalProfileResolverService implements ITerminalPro
 
 	private _getUnresolvedRealDefaultProfile(os: OperatingSystem): ITerminalProfile | undefined {
 		const defaultProfileName = this.getSafeConfigValue('defaultProfile', os);
+		console.log('defaultProfileName', defaultProfileName);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalProfileResolverService.ts:173]: remove?

File: src/vs/workbench/contrib/terminal/browser/terminalProfileResolverService.ts [hunk 10]
```diff
@@ -166,7 +170,9 @@ export abstract class BaseTerminalProfileResolverService implements ITerminalPro
...
 		if (defaultProfileName && typeof defaultProfileName === 'string') {
+			console.log('this._terminalService.availableProfiles', this._terminalService.availableProfiles);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalProfileResolverService.ts:175]: remove?

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 11]
```diff
@@ -192,23 +190,26 @@ export class TerminalService implements ITerminalService {
 
 		const enableTerminalReconnection = this.configHelper.config.enablePersistentSessions;
 
-		const conn = this._remoteAgentService.getConnection();
-		const remoteAuthority = conn ? conn.remoteAuthority : 'null';
-		this._whenExtHostReady(remoteAuthority).then(() => {
-			this._refreshAvailableProfiles();
-		});
+		// const conn = this._remoteAgentService.getConnection();
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:193]: remove?

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 12]
```diff
@@ -192,23 +190,26 @@ export class TerminalService implements ITerminalService {
...
-		this._offProcessTerminalService = isPersistentRemote ? this._remoteTerminalService :
-			enableTerminalReconnection ? this._localTerminalService : undefined;
+		let initPromise: Promise<any> = isPersistentRemote
+			? this._remoteTerminalsInitPromise = this._reconnectToRemoteTerminals()
+			: enableTerminalReconnection
+				? this._localTerminalsInitPromise = this._reconnectToLocalTerminals()
+				: Promise.resolve();
+		this._offProcessTerminalService = !!this._environmentService.remoteAuthority ? this._remoteTerminalService : this._localTerminalService;
 		initPromise.then(() => this._setConnected());
+
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:210]: 5 seconds seems like a lot?

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 13]
```diff
@@ -329,26 +330,28 @@ export class TerminalService implements ITerminalService {
 	@throttle(10000)
 	private async _refreshAvailableProfiles(): Promise<void> {
 		const result = await this._detectProfiles(true);
+		console.log('detectProfiles result', result);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:333]: remove?

File: src/vs/platform/terminal/node/terminalProfiles.ts [hunk 14]
```diff
@@ -29,9 +35,9 @@ export function detectAvailableProfiles(configuredProfilesOnly: boolean, safeCon
 			configuredProfilesOnly,
 			fsProvider,
 			logService,
-			safeConfigProvider(TerminalSettingId.UseWslProfiles) || true,
-			safeConfigProvider(TerminalSettingId.ProfilesWindows),
-			safeConfigProvider(TerminalSettingId.DefaultProfileWindows),
+			safeConfigProvider('terminal.integrated.useWslProfiles') || true,
```
Comment (Tyriar) [inline src/vs/platform/terminal/node/terminalProfiles.ts:38]: Need to bring these back since TerminalSettingId is in platform now

**Comment by meganrogge** [comment]
Think this was accidentally added? `extensions/git/resources/icons/git.png`

File: src/vs/platform/terminal/node/terminalProfiles.ts [hunk 15]
```diff
@@ -40,15 +46,24 @@ export function detectAvailableProfiles(configuredProfilesOnly: boolean, safeCon
 		fsProvider,
 		logService,
 		configuredProfilesOnly,
-		safeConfigProvider(isMacintosh ? TerminalSettingId.ProfilesMacOs : TerminalSettingId.ProfilesLinux),
```
Comment (meganrogge) [inline src/vs/platform/terminal/node/terminalProfiles.ts:43]: same as above for these

File: src/vs/platform/terminal/node/terminalProfiles.ts [hunk 16]
```diff
@@ -40,15 +46,24 @@ export function detectAvailableProfiles(configuredProfilesOnly: boolean, safeCon
...
+		safeConfigProvider(`terminal.integrated.profiles.${isMacintosh ? 'osx' : 'linux'}`),
+		safeConfigProvider(`terminal.integrated.defaultProfile.${isMacintosh ? 'osx' : 'linux'}`),
 		testPaths,
 		variableResolver,
 		workspaceFolder
 	);
 }
 
-async function detectAvailableWindowsProfiles(configuredProfilesOnly: boolean, fsProvider: IFsProvider, logService?: ILogService, useWslProfiles?: boolean, configProfiles?: { [key: string]: ITerminalProfileObject }, defaultProfileName?: string, variableResolver?: ExtHostVariableResolverService, workspaceFolder?: IWorkspaceFolder): Promise<ITerminalProfile[]> {
+async function detectAvailableWindowsProfiles(
```
Comment (meganrogge) [inline src/vs/platform/terminal/node/terminalProfiles.ts:57]: looks so much better

File: src/vs/platform/terminal/node/terminalProfiles.ts [hunk 17]
```diff
@@ -115,7 +130,7 @@ async function detectAvailableWindowsProfiles(configuredProfilesOnly: boolean, f
 	return resultProfiles;
 }
 
-async function transformToTerminalProfiles(entries: IterableIterator<[string, ITerminalProfileObject]>, defaultProfileName: string | undefined, fsProvider: IFsProvider, logService?: ILogService, variableResolver?: ExtHostVariableResolverService, workspaceFolder?: IWorkspaceFolder): Promise<ITerminalProfile[]> {
+async function transformToTerminalProfiles(entries: IterableIterator<[string, ITerminalProfileObject]>, defaultProfileName: string | undefined, fsProvider: IFsProvider, logService?: ILogService, variableResolver?: (text: string[]) => Promise<string[]>, workspaceFolder?: IWorkspaceFolder): Promise<ITerminalProfile[]> {
```
Comment (meganrogge) [inline src/vs/platform/terminal/node/terminalProfiles.ts:133]: might benefit from horizontal layout like the arguments for `detectAvailableWindowsProfiles`

File: src/vs/workbench/api/browser/mainThreadTerminalService.ts [hunk 18]
```diff
@@ -89,14 +87,27 @@ export class MainThreadTerminalService implements MainThreadTerminalServiceShape
 			this._proxy.$initEnvironmentVariableCollections(serializedCollections);
 		}
 
-		this._terminalService.extHostReady(extHostContext.remoteAuthority!); // TODO@Tyriar: remove null assertion
+		remoteAgentService.getEnvironment().then(async env => {
```
Comment (meganrogge) [inline src/vs/workbench/api/browser/mainThreadTerminalService.ts:90]: I think `getEnvironment()` can return null? https://github.com/microsoft/vscode/blob/39bd9df739ffd09ce5631757bb12daa14b77c403/src/vs/workbench/services/remote/common/abstractRemoteAgentService.ts#L54-L56

File: src/vs/workbench/api/browser/mainThreadTerminalService.ts [hunk 19]
```diff
@@ -89,14 +87,27 @@ export class MainThreadTerminalService implements MainThreadTerminalServiceShape
...
+			this._os = env?.os || OS;
+			this._updateDefaultProfile();
+		});
+		this._terminalService.onDidChangeAvailableProfiles(() => this._updateDefaultProfile());
+
+		this._terminalService.extHostReady(_extHostContext.remoteAuthority!); // TODO@Tyriar: remove null assertion
```
Comment (meganrogge) [inline src/vs/workbench/api/browser/mainThreadTerminalService.ts:96]: is terminal service's `extHostReady` even needed now?

File: src/vs/workbench/contrib/terminal/browser/remoteTerminalService.ts [hunk 20]
```diff
@@ -122,6 +132,13 @@ export class RemoteTerminalService extends Disposable implements IRemoteTerminal
 					this._onPtyHostResponsive.fire();
 				}));
 			}
+			this._register(channel.onPtyHostRequestResolveVariables(async e => {
+				const activeWorkspaceRootUri = historyService.getLastActiveWorkspaceRoot(Schemas.file);
+				const lastActiveWorkspaceRoot = activeWorkspaceRootUri ? withNullAsUndefined(workspaceContextService.getWorkspaceFolder(activeWorkspaceRootUri)) : undefined;
+				const resolveCalls: Promise<string>[] = e.text.map(t => configurationResolverService.resolveAsync(lastActiveWorkspaceRoot, t));
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/remoteTerminalService.ts:138]: hard to understand this line. what is `text`?

**Review by meganrogge — APPROVED** [review]

File: src/vs/workbench/api/browser/mainThreadTerminalService.ts (hunk 19 above)
Comment (Tyriar) [reply src/vs/workbench/api/browser/mainThreadTerminalService.ts:96]: Removed :tada:

File: src/vs/workbench/api/browser/mainThreadTerminalService.ts (hunk 18 above)
Comment (Tyriar) [reply src/vs/workbench/api/browser/mainThreadTerminalService.ts:90]: Yep, this is unexpected for remotes but we fallback to the renderer's os (`OS`) so that should be fine

File: src/vs/workbench/contrib/terminal/browser/remoteTerminalService.ts (hunk 20 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/remoteTerminalService.ts:138]: It's the original text, will improve

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 21]
```diff
@@ -1019,20 +1019,15 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
...
-					remoteAuthority: this.environmentService.remoteAuthority
-				});
-				defaultConfig = {
-					shell: defaultProfile.path,
-					args: defaultProfile.args
-				};
-			}
+			const defaultProfile = await this.terminalProfileResolverService.getDefaultProfile({
+				allowAutomationShell: true,
+				os: Platform.OS,
```
Comment (alexr00) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1024]: @Tyriar `Platform.OS` could be the wrong OS if connected to a remote. Will `getDefaultProfile` ignore the wrong platform in that case?

Comment (alexr00) [reply src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1024]: Yep, tasks when connected to a remote are broken.
