### PR TITLE
fixes #68549

### LINKED ISSUE #68549: [read-only]: cannot apply workspace edit for read-only workspace provider
Reopening https://github.com/Microsoft/vscode/issues/65324 as it still repros and breaks the very important read-only scenario for VS Live Share. Related: https://github.com/Microsoft/vscode/issues/57032.

- VSCode Version: `1.32.0 Insider`, `1.31.0 Stable`
- OS Version: `10.14.2`

Steps to Reproduce:

Use the modified `MemFS` extension: [fsprovider-sample.zip](https://github.com/Microsoft/vscode/files/2852928/fsprovider-sample.zip)

1. Lunch the extension and run `MemFS: Workspace Setup` in the command palette.
2. Run `MemFS: Create Files` in the command palette.
3. Run `MemFS: Start Bash` using VSCode stable(1.31.0).

The extension will try to insert a current timestamp string into the beginning of the `file.yaml` in the root of the workspace with an interval of `1 second`. It logs the same message to the `debug console` for testing purposes. Notice that if the `file.yaml` is open in the background, the edits come through, but if a user makes the file active, the edits no longer applied.

Does this issue occur when all extensions are disabled?: Yes

`Note:` The related pieces in the extension source code marked with `/* EDIT */` markers.

cc. @IlyaBiryukov

### PR DESCRIPTION
**Pull request by isidorn**
https://github.com/Microsoft/vscode/issues/68549

By bisecting I found that the initial cause of this issue is 
https://github.com/Microsoft/vscode/commit/952faa486a3d1ac95e54031eb70e8df7ce93cffd

So a strict null change. Upon closer inspection the only functional difference is the change to use `codeEditor` instead of `options.editor`. I am not sure what was the intention of the change, but I think it was not intentional and happend as an accident. @mattbierner can confirm this

This PR simply reverts that unintentonal change.
I have confirmed this indeed fixes the LiveShare issue.
fyi @kieferrm

### CODE REVIEW

**Comment by bpasero** [comment]
@isidorn I am unassigning myself because I feel uncertain about the consequences of this change that @jrieken can probably better oversee. This is not just a strict null change, this is also a semantic change that we try to look up the editor based on the active editor if no editor was passed in. That means, that we prefer to do the edit in the context of the editor if the active editor has the model opened. After your change, we loose the code that was added from Joh:

```ts
// try to find code editor
// todo@joh, prefer edit that gets edited
if (!codeEditor) {
	let candidate = this._editorService.activeTextEditorWidget;
	if (isCodeEditor(candidate)) {
		codeEditor = candidate;
	}
}
```

**Review by mjbvz — DISMISSED** [review]
Yes I do not remember why I made this change. It does look like and unintentional change to me

File: src/vs/workbench/services/bulkEdit/browser/bulkEditService.ts [hunk 1]
```diff
@@ -410,7 +410,7 @@ export class BulkEditService implements IBulkEditService {
 			}
 		}
 
-		const bulkEdit = new BulkEdit(codeEditor, options.progress, this._logService, this._textModelService, this._fileService, this._textFileService, this._labelService, this._configurationService);
+		const bulkEdit = new BulkEdit(options.editor, options.progress, this._logService, this._textModelService, this._fileService, this._textFileService, this._labelService, this._configurationService);
```
Comment (jrieken) [inline src/vs/workbench/services/bulkEdit/browser/bulkEditService.ts]: This is a huge change because it affects all users of bulk edit that rely on it, automatically trying to perform an edit using the editor. That's important so that selections and decorations stay stable whenever bulk edit affects a file that opened in an editor. 

If the "culprit" is the editor, checking that a model is readonly, (@isidorn please confirm, you have investigated this issue) then you wanna have a way of tell bulk edit to not use an editor. How about another property in `IBulkEditOptions` like `{ noFallbackEditor: boolean }` or using `{ editor: null }`?

**Comment by isidorn** [comment]
@bpasero you are correct
@mjbvz your change was actually good. You found that the `codeEditor` is not being used, which @jrieken introduced and accidently did not pass in the edit. You correctly passed it in which @jrieken probably wanted to do.

@jrieken has more details and I can let him comment

Bottom line is that my fix is not good since it changes many other code actions and should probably not be a part of the recovery release

**Review by jrieken — CHANGES_REQUESTED** [review]

File: src/vs/workbench/services/bulkEdit/browser/bulkEditService.ts (hunk 1 above)
Comment (isidorn) [reply src/vs/workbench/services/bulkEdit/browser/bulkEditService.ts]: Yes I confirm. The culprit is the editor.

**Comment by jrieken** [comment]
> This is not just a strict null change, this is also a semantic change that we try to look up the editor based on the active editor if no editor was passed in. 

Yes, that was a good fix, albeit not strict-null related. In essence it's better to use an editor to edit a file, then just a model. With the former selection and decoration updates are smoother. That's why we have this logic and because in some (new-ish?) places we rely on this fallback so I don't think that we should remove this.

**Comment by isidorn** [comment]
@jrieken thanks for the suggestions. I have pushed an alternative fix which follows your adivce of passing editor: undefined for readonly editors, so the bulk edits can be applied.
I tested this and it works for the live share case.
Let me know what you think

**Review by jrieken — APPROVED** [review]
lgtm
