### PR TITLE
Workspace trust - Remote indicator stuck in 'Initializing' when resolver fails

### LINKED ISSUE #126057: Remote indicator stuck in 'Initializing' when resolver fails
Version: 1.58.0-insider (user setup) 
Commit: 012b14606f75ec4fed90d7ab4154f63dffab9503 
Date: 2021-06-11T05:14:11.473Z
OS: Windows_NT x64 10.0.19043

- run from sources
- in the settings set `"testresolver.startupError": true,`
- open a testresolver window
- the resolver fails (as configured), a dialog shows up, press ignore
- the remote indicator continues to spin, the workbench is blocked

The workbench is stuck in `_startLocalExtensionHost`:
https://github.com/microsoft/vscode/blob/edba477349fbf7b7caee6ed553f511eb5754d923/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L421

_startLocalExtensionHost (extensionService.js:301)
_scanAndHandleExtensions (extensionService.js:264)
processTicksAndRejections (internal/process/task_queues.js:93)
await in processTicksAndRejections (async)
_initialize (abstractExtensionService.js:382)
(anonymous) (extensionService.js:43)
requestIdleCallback (async)
exports.runWhenIdle (async.js:665)
(anonymous) (extensionService.js:42)
Promise.then (async)
ExtensionService (extensionService.js:40)
_createInstance (instantiationService.js:90)
_createServiceInstance (instantiationService.js:197)
_createServiceInstanceWithOwner (instantiationService.js:185)
_createAndCacheServiceInstance (instantiationService.js:175)
_safeCreateAndCacheServiceInstance (instantiationService.js:128)
_getOrCreateServiceInstance (instantiationService.js:115)
get (instantiationService.js:38)
initLayout (layout.js:145)
(anonymous) (workbench.js:69)

### PR DESCRIPTION
**Pull request by lszomoru**
This PR fixes #126057

### CODE REVIEW

File: src/vs/workbench/services/workspaces/common/workspaceTrust.ts [hunk 1]
```diff
@@ -126,23 +126,26 @@ export class WorkspaceTrustManagementService extends Disposable implements IWork
...
-			await this.updateWorkspaceTrust();
-
-			this._workspaceResolvedPromiseResolve();
-			if (!this.environmentService.remoteAuthority) {
-				this._workspaceTrustInitializedPromiseResolve();
-			}
-		});
+		this.resolveCanonicalWorkspaceUris()
+			.then(async () => {
+				this._initialized = true;
```
Comment (sbatten) [inline src/vs/workbench/services/workspaces/common/workspaceTrust.ts:131]: is the intent that we stay uninitialized?

Comment (lszomoru) [reply src/vs/workbench/services/workspaces/common/workspaceTrust.ts:131]: This is a field that represents an internal state to the service. The promises, which are the signals to the outside world will be resolved. But if the canonical URIs could not be resolved, I think that it is safe to stay in restricted mode which we can ensure by not setting `this._initialized = true;`

**Review by sbatten — APPROVED** [review]
