### PR TITLE
use correct icons for terminal opener quick fixes

### LINKED ISSUE #167876: use correct icon for terminal quick fix link types
We reverted this change since it's not an important fix, but can cherry pick for December

https://github.com/microsoft/vscode/pull/167784/commits/f2e4087c0c2cb14729fe115f48f98801493eca09

### PR DESCRIPTION
**Pull request by meganrogge**
while at the top of mind before additional changes come in

fixes https://github.com/microsoft/vscode/issues/167876

Screenshot 2022-12-02 at 10 38 13 AM

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 1]
```diff
@@ -274,6 +275,8 @@ export class TerminalQuickFixAddon extends Disposable implements ITerminalAddon,
 
 export interface ITerminalAction extends IAction {
 	source: string;
+	uri?: URI;
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:278]: I considered using some other property here instead of passing in either of these since they don't seem to get used elsewhere, but figured that would be more confusing

File: src/vs/workbench/contrib/terminal/browser/widgets/terminalQuickFixMenuItems.ts [hunk 2]
```diff
@@ -62,8 +63,10 @@ export function toMenuItems(inputQuickFixes: readonly TerminalQuickFix[], showHe
 function getQuickFixIcon(quickFix: TerminalQuickFix): { codicon: Codicon } {
 	switch (quickFix.type) {
 		case TerminalQuickFixType.Opener:
-			// TODO: if it's a file link, use the open file icon
-			return { codicon: Codicon.link };
+			if ('uri' in quickFix.action && quickFix.action.uri?.scheme) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/widgets/terminalQuickFixMenuItems.ts:66]: I think scheme is required?

https://github.com/microsoft/vscode/blob/3b4e310d429412f061325912c8673bbe186739a2/src/vs/base/common/uri.ts#L121

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Review by Tyriar — APPROVED** [review]
