### PR TITLE
Stop servers when auth is not available.

### LINKED ISSUE #278407: Stop MCP Server if auth no longer is available
Steps to Reproduce:

1. Connect to an MCP Server with auth
2. Sign out of the account that you used with the MCP Server
3. 🐛 MCP Server still says it's running

Expected:

It should stop since the auth is no longer available.

FYI @connor4312

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
Fixes https://github.com/microsoft/vscode/issues/278407

### CODE REVIEW

File: src/vs/workbench/api/browser/mainThreadMcp.ts [hunk 1]
```diff
@@ -403,3 +445,51 @@ class ExtHostMcpServerLaunch extends Disposable implements IMcpMessageTransport
...
+	// Provider ID -> Array of serverId and scopes used
+	private readonly _tracking = new Map<string, Array<{ serverId: number; scopes: string[] }>>();
+
+	/**
+	 * Track authentication for a server with a specific provider.
+	 * Replaces any existing tracking for this server/provider combination.
+	 */
+	track(providerId: string, serverId: number, scopes: string[]): void {
+		const servers = this._tracking.get(providerId) || [];
+		const filtered = servers.filter(s => s.serverId !== serverId);
```
Comment (dmitrivMS) [inline src/vs/workbench/api/browser/mainThreadMcp.ts:463]: have to ask... is serverId case-sensitive?

**Review by dmitrivMS — APPROVED** [review]

File: src/vs/workbench/api/browser/mainThreadMcp.ts (hunk 1 above)
Comment (TylerLeonhardt) [reply src/vs/workbench/api/browser/mainThreadMcp.ts:463]: yes
