### PR TITLE
Reconfigure default build and test tasks should update tasks.json

### LINKED ISSUE #38657: Can't use "Configure Default Build/Test Task" commands to change the default.
- VSCode Version: 1.18.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. Create 2 or more build tasks.
2. Use "Configure Default Build Task" command to make one of them default.
3. Try to use "Configure Default Build Task" again to change the default. 

VSCode says "XXXXXXX is already marked as the default build task".   This behavior is not very useful.  I'd rather it just let me pick another task as default and make appropriate changes to tasks.json. 

Same applies to "Configure Default Test Task".

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #38657

### CODE REVIEW

File: src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts [hunk 1]
```diff
@@ -1884,8 +1884,8 @@ class TaskService extends Disposable implements ITaskService {
 			}
 		};
 		return this.quickInputService.pick(_createEntries().then((entries) => {
-			if (entries.length === 0 && defaultEntry) {
-				entries.push(defaultEntry);
+			if (defaultEntry) {
```
Comment (dbaeumer) [inline src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts]: The `showQuickPick` is called from many different places and no inserting the default entry always at the front might break other places. Have you considered this?

Comment (dbaeumer) [reply src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts]: IMo this needs to be addressed here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L2336 and the tasks still need to be listed with the default task being at top.

**Review by dbaeumer — CHANGES_REQUESTED** [review]
See comments.

File: src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts (hunk 1 above)
Comment (alexr00) [reply src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts]: I checked where showQuickPick is called from and didn't see anywhere that this would be a problem. I will double check.

Comment (alexr00) [reply src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts]: I checked again. The only place that a default entry is used is in the configure build and test tasks. Do you still prefer that this be addressed at https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L2336  ?

Comment (dbaeumer) [reply src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts]: Actually I would. Main reason is that it will be easier to understand later on. The idea of the default entry for `showQuickPick` was to show it when no other elements are provided.

**Comment by dbaeumer** [comment]
In general whenever possible we should show the quick pick UI as early as possible since it will the the part showing progress to the user.  I am not usre how the new behaviour will be but I would do the following:

- show all tasks as if not default build / test task is set
- if one is set show it in the list with some additional label [current default]
- preselect the current default.

**Review by dbaeumer — APPROVED** [review]
LGTM.
