### PR TITLE
Terminal profile fixes

### LINKED ISSUE #117935: Terminal is not always focused when opening panel
- Focus the terminal, close the panel and reload the window
- Press cmd+J to show the panel, with the terminal persisted to be the active view
- The terminal should be created and focused. Sometimes, it's not

I think this is new in 1.54. Seems like it usually reproes the first time the panel is opened. But, if I kill all terminals, causing the panel to close, then press cmd+J again, it focuses the new terminal correctly.

### LINKED ISSUE #119320: Profiles shouldn't use pathOrPaths in settings schema
I didn't realize you also pulled this into the settings schema:

Screen Shot 2021-03-19 at 5 40 13 AM

`path` is better here as it's typically just a string. If we wanted to we could have the interface be this to make it obvious about the fallbacks:

```
{ path: string } | { paths: string[] } | { source: ProfileSource }
```

### LINKED ISSUE #119321: Custom profiles should show up in select default profiles
Repro:

Add custom profile like this:

```
"terminal.integrated.profiles.osx": {
  "bash (login)": {
    "pathOrPaths": "bash",
    "args": ["-l"]
  }
}
```

Run the `Select Default Profile` command, the custom profile should show up in the list.

Actual:

Screen Shot 2021-03-19 at 5 45 22 AM

### PR DESCRIPTION
**Pull request by meganrogge**
Fixes #119320 
Fixes #119321
Fixes #117935

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalActions.ts [hunk 1]
```diff
@@ -1470,36 +1468,31 @@ export function registerTerminalActions() {
...
-				let launchConfig = detectedProfiles?.find((profile: { profileName: string; }) => profile.profileName === profileSelection);
-				if (launchConfig && !launchConfig.isWorkspaceProfile) {
-					const instance = terminalService.createTerminal({ executable: launchConfig.path, args: launchConfig.args });
-					terminalService.setActiveInstance(instance);
-				} else if (launchConfig && launchConfig.isWorkspaceProfile) {
-					if (!storageService.getBoolean(`${QUICK_LAUNCH_PROFILE_CHOICE}-${item}-${launchConfig.path}`, StorageScope.WORKSPACE, false)) {
-						notificationService.prompt(Severity.Info, `Do you allow this workspace to modify your terminal profile? ${item} with path ${launchConfig?.path}`,
+				const launchConfig = detectedProfiles?.find((profile: { profileName: string; }) => profile.profileName === profileSelection);
+				if (launchConfig) {
+					if (!terminalService.configHelper.checkWorkspaceShellPermissions() || !launchConfig.isWorkspaceProfile) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalActions.ts:1475]: `checkWorkspaceShellPermissions` won't work like this because it will only check if there are customizations to `shell` and `shellArgs`. But you're right that we should be using that function. I think we need to pass in to it whether we're checking a `profile` or `shell`/`shellArgs`.

This is what I'm thinking:

```ts
checkWorkspaceShellPermissions(profile?: ITerminalProfile)
```

Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalActions.ts:1475]: I was about to say we want to check `isWorkspaceProfile` and fall through first before attempting to call `checkWorkspaceShellPermissions` since it triggers a notification, but we don't need to check it at all. `checkWorkspaceShellPermissions` will check not only the shell and args for us but also if `env` is set which is also important.

File: src/vs/workbench/contrib/terminal/browser/terminalActions.ts [hunk 2]
```diff
@@ -1470,36 +1468,31 @@ export function registerTerminalActions() {
...
+						const instance = terminalService.createTerminal({ executable: launchConfig.path, args: launchConfig.args });
+						terminalService.setActiveInstance(instance);
+					} else {
+						notificationService.prompt(Severity.Info, `Do you allow this workspace to modify your terminal profile? ${profileSelection} with path ${launchConfig.path}`,
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalActions.ts:1479]: I don't think we need this anymore if we're using `checkWorkspaceShellPermissions`

File: src/vs/workbench/contrib/terminal/node/terminalProfiles.ts [hunk 3]
```diff
@@ -57,9 +46,9 @@ async function detectAvailableWindowsProfiles(quickLaunchOnly: boolean, logServi
 				`${process.env['ProgramW6432']}\\Git\\usr\\bin\\bash.exe`,
 				`${process.env['ProgramFiles']}\\Git\\bin\\bash.exe`,
 				`${process.env['ProgramFiles']}\\Git\\usr\\bin\\bash.exe`,
-				`${process.env['LocalAppData']}\\Programs\\Git\\bin\\bash.exe`,
+				`${process.env['LocalAppData']}\\Programs\\Git\\bin\\bash.exe`
 			],
-			args: ['--login']
+			args: ['-l']
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/node/terminalProfiles.ts:51]: Let's switch this back to `--login`, that way it's a little clearer what it is to the user, more than `-l` anyway.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalActions.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalActions.ts]: `isWorkspaceProfile` already checks this

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalActions.ts]: https://github.com/microsoft/vscode/blob/9093f265a64f640c3fb385195f6b1883deea2b93/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L298-L298

**Comment by meganrogge** [comment]
The build failures keep saying
`Error: D:/a/vscode/vscode/src/vs/workbench/contrib/terminal/browser/terminalService.ts(861,6): Type '{ pathOrPaths: string; args: string | string[] | undefined; }' is not assignable to type `
inexplicably when I no longer use pathOrPaths anywhere other than as a reference variable

**Comment by meganrogge** [comment]
In a custom build, I tested the linux profiles and they are once again duplicated. not sure why. need to investigate this

**Comment by meganrogge** [comment]
to do - comment out failing tests

File: src/vs/workbench/contrib/terminal/browser/terminalActions.ts [hunk 4]
```diff
@@ -1462,44 +1459,24 @@ export function registerTerminalActions() {
...
-						const instance = terminalService.createTerminal({ executable: launchConfig?.path, args: launchConfig?.args });
+
+			const quickSelectProfiles = await terminalService.getAvailableProfiles();
+
+			// Remove 'New ' from the selected item to get the profile name
+			const profileSelection = item.substring(4);
+			if (quickSelectProfiles) {
+				const launchConfig = quickSelectProfiles.find(profile => profile.profileName === profileSelection);
+				if (launchConfig) {
+					if (!terminalService.configHelper.checkWorkspaceShellPermissions(undefined, launchConfig.isWorkspaceProfile)) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalActions.ts:1474]: I think `checkWorkspaceShellPermissions` should return true if it's ok to launch, it seems to be inverted?

File: src/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.ts [hunk 5]
```diff
@@ -5,55 +5,111 @@
...
+						},
+						showQuickLaunchWslProfiles: false
+					};
+					const profiles = await detectAvailableProfiles(true, undefined, config, undefined, undefined, createStatProvider(_paths));
+					const expected = [{ profileName: 'Command Prompt', path: _paths[0] }];
+					assert.deepStrictEqual(expected, profiles);
+				});
+			}
+			);
+		} else if (isMacintosh) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.ts:50]: I think we can merge the mac and linux tests into one

File: src/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.ts [hunk 6]
```diff
@@ -5,55 +5,111 @@
...
+			suite.skip('detectAvailableOsxProfiles', async () => {
+				test('should detect bash, zsh, tmux, fish', async () => {
+					const _paths = ['bash', 'zsh', 'tmux', 'fish'];
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.ts:53]: We could remove one of these (tmux?) to test the stat provider returning false.

File: src/vs/workbench/contrib/terminal/node/terminalProfiles.ts [hunk 7]
```diff
@@ -9,29 +9,18 @@ import { coalesce } from 'vs/base/common/arrays';
 import { normalize, basename } from 'vs/base/common/path';
 import { enumeratePowerShellInstallations } from 'vs/base/node/powershell';
 import { getWindowsBuildNumber } from 'vs/platform/terminal/node/terminalEnvironment';
-import { ITerminalConfiguration, ITerminalExecutable, ITerminalProfile, ITerminalProfileSource } from 'vs/workbench/contrib/terminal/common/terminal';
+import { ITerminalConfiguration, ITerminalExecutable, ITerminalProfile, ITerminalProfileObject, ITerminalProfileSource } from 'vs/workbench/contrib/terminal/common/terminal';
 import * as cp from 'child_process';
 import { ExtHostVariableResolverService } from 'vs/workbench/api/common/extHostDebugService';
 import { IWorkspaceFolder } from 'vs/platform/workspace/common/workspace';
 import { ITestTerminalConfig } from 'vs/workbench/contrib/terminal/test/node/terminalProfiles.test';
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/node/terminalProfiles.ts:16]: We don't want to import something from a test file as it could potentially pull the test into the compiled sources. My typical solution to this is to be more relaxed on types in tests, you could still use ITestTerminalConfig to create the object, but then cast it as api when passing it into `detectAvailableProfiles`.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.ts (hunk 5 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.ts:50]: you'll see these are both skipped bc they were failing (even though locally in WSL, it looks good). can't run them locally on windows. made a note of and deferring to #118997
