### PR TITLE
Fix shifting in cell editors that have horizontal scrollba

### LINKED ISSUE #153708: Notebook scrolling out of sync
related https://github.com/microsoft/vscode/issues/148164

* have my-endgame-GHINB
* run all cell, scroll to the bottom, and run `touch <path>`
* scroll upwards
* 🧀 notice an occasional layout shift, the alignment of code and MD cells is getting out of sync

##### Recording of the recording

https://user-images.githubusercontent.com/1794099/176478910-74a1eb2f-a83e-4557-bf47-58931482a824.mov

##### Recording of the scroll

https://user-images.githubusercontent.com/1794099/176479002-7df7ca80-24ff-4676-8911-ffd0e76fbe5a.mov

### PR DESCRIPTION
**Pull request by roblourens**
Fixes #153708

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/browser/viewModel/codeCellViewModel.ts [hunk 1]
```diff
@@ -329,16 +339,16 @@ export class CodeCellViewModel extends BaseCellViewModel implements ICellViewMod
...
 		} else {
 			return this._layoutInfo.totalHeight;
 		}
 	}
 
-	private estimateEditorHeight(lineHeight: number | undefined = 20): number {
+	private estimateEditorHeight(lineHeight: number | undefined = 20): { editorHeight: number; hasHorizontalScrolling: boolean } {
 		let hasScrolling = false;
-		if (this.layoutInfo.fontInfo) {
+		if (this.layoutInfo.fontInfo && !this.viewContext.notebookOptions.getLayoutConfiguration().wordWrap) {
```
Comment (rebornix) [inline src/vs/workbench/contrib/notebook/browser/viewModel/codeCellViewModel.ts:351]: We may want to read `BaseCellEditorOptions.wordWrap` which takes language override into account instead of checking `editor.wordwrap`.

**Review by rebornix — DISMISSED** [review]
It looks great in overall, only one that might need to be changed is listening to wordwrap options change on cell editor options instead of notebook options.

File: src/vs/workbench/contrib/notebook/browser/viewModel/codeCellViewModel.ts (hunk 1 above)
Comment (roblourens) [reply src/vs/workbench/contrib/notebook/browser/viewModel/codeCellViewModel.ts:351]: I don't think I knew about that class. I can't really do that because that class depends on the notebook editor, but all the layout is at the VM level. Seems like that is just configuration that I should be able to get from here

Comment (roblourens) [reply src/vs/workbench/contrib/notebook/browser/viewModel/codeCellViewModel.ts:351]: I guess it could be accessed through the ViewContext? Seems like just a backdoor though

**Review by joyceerhl — APPROVED** [review]
