### PR TITLE
fix focus response/input terminal inline chat actions

### LINKED ISSUE #208731: cannot focus message response via keyboard
Note that both of these scenarios used to work.

In the terminal inine chat, run a command like `slkfjsdkjf` which yields just a chat message response.

Try to tab to it. 🐛  one cannot

Run a command like `ls` which yields a code block response. Try to use `cmd+up/down arrow` to go from the input box to a code block response and vice versa. 🐛 one cannot

### PR DESCRIPTION
**Pull request by meganrogge**
this regressed recently and is important for SR / keyboard users so they don't have to tab a bunch. we also mention these in our accessibility help dialog, so need to ensure they work.

fix #208731

https://github.com/microsoft/vscode/assets/29464607/e2cfbaa9-9338-4904-9593-0b8e8f8fea57

### CODE REVIEW

File: src/vs/workbench/contrib/terminalContrib/chat/browser/terminalChatWidget.ts [hunk 1]
```diff
@@ -159,7 +159,7 @@ export class TerminalChatWidget extends Disposable {
 		this._inlineChatWidget.focus();
 	}
 	focusResponse(): void {
-		const responseElement = this._inlineChatWidget.domNode.querySelector(ChatElementSelectors.ResponseEditor) || this._inlineChatWidget.domNode.querySelector(ChatElementSelectors.ResponseMessage);
+		const responseElement = this._inlineChatWidget.domNode.querySelector('.monaco-list');
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/chat/browser/terminalChatWidget.ts:162]: Resorting to querySelector is essentially using private API that could break. Can we do this via `this._inlineChatWidget.chatWidget.focusLastMessage()` or similar?

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Review by Tyriar — APPROVED** [review]
