### PR TITLE
fix #213971

### LINKED ISSUE #213971: Switching to release and back to pre-release version of an extension is not working
Steps to Reproduce:

1. Install an pre-release version of an extension
2. Switch to release version and restart extension host
3. Switch back to pre-release version and refresh extensions view
🐛 Extension is still release version

### PR DESCRIPTION
**Pull request by sandy081**
fix #213971

### CODE REVIEW

**Review by benibenj — APPROVED** [review]

File: src/vs/platform/extensionManagement/node/extensionManagementService.ts [hunk 1]
```diff
@@ -972,22 +974,22 @@ class InstallExtensionInProfileTask extends AbstractExtensionTask<ILocalExtensio
...
+				local = await this.extensionsScanner.updateMetadata(existingExtension, metadata);
+			} else {
+				// Unset if the extension is uninstalled and return the unset extension.
+				local = await this.unsetIfUninstalled(this.extensionKey);
 			}
 		}
 
 		if (token.isCancellationRequested) {
 			throw toExtensionManagementError(new CancellationError());
 		}
```
Comment (joaomoreno) [inline src/vs/platform/extensionManagement/node/extensionManagementService.ts:986]: This comment is unrelated to the changes in this PR, but if indeed cancellation happens and the function exits at this point, won't we have inconsistent data? For example, `initializeDefaultProfileExtensions` or `addExtensionsToProfile` will never be called. Is it really safe to exit the method here, even after having called `updateMetadata` or `unsetIfUninstalled`?

Same comment applies to the other `token.isCancellationRequested` check below.
