### PR TITLE
Fix TS/JS Completion Item Provider for Completions that are not whole words

### LINKED ISSUE #16888: Autocomplete with dash
- VSCode Version: Code - Insiders 1.8.0-insider (0d65ced0fa7398dc9d50c39a23a2a8cc8406ff18, 2016-12-07T07:05:09.124Z)
- OS Version: Darwin x64 16.1.0
---

Steps to Reproduce:

1. TypeScript
2.
image

3. Hit Enter
4. 
image

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #16888

**Bug**
The js/ts completion provider can currently only complete whole words in most cases (as defined by `TextDocument.getWordRangeAtPosition`). This causes completion of literal string types to fail if they are not a whole word.

dec-08-2016 17-01-45

**Fix**
Instead of relaying on the default range, compute a range by taking the longest match of the replacement text backwards from the current position.

dec-08-2016 17-03-24

### CODE REVIEW

File: extensions/typescript/src/features/completionItemProvider.ts [hunk 1]
```diff
@@ -18,15 +18,25 @@ class MyCompletionItem extends CompletionItem {
...
 		this.kind = MyCompletionItem.convertKind(entry.kind);
+		this.position = position;
+		this.document = document;
 		if (entry.replacementSpan) {
 			let span: protocol.TextSpan = entry.replacementSpan;
 			// The indexing for the range returned by the server uses 1-based indexing.
 			// We convert to 0-based indexing.
 			this.textEdit = TextEdit.replace(new Range(span.start.line - 1, span.start.offset - 1, span.end.line - 1, span.end.offset - 1), entry.name);
+		} else {
+			const text = document.getText(new Range(position.line, Math.max(0, position.character - entry.name.length), position.line, position.character));
```
Comment (mjbvz) [inline extensions/typescript/src/features/completionItemProvider.ts]: This assume that the replacement text will always start with the replaced text. @dbaeumer is this a safe assumption to make. It worked in all cases in my testing, but we may want to scope the fix by only applying it to certain kinds of completion entries

**Comment by mjbvz** [comment]
The completions for the literal types are new in TS 2.1.x. In VSCode 1.7.2, we just treated the string values being completed as normal strings instead of types. 

I think we should hold off on merging this fix until post 1.8. I would like a period of testing in insiders for this.
