### PR TITLE
Fix on `useCustomCodeActionMenu` setting

### LINKED ISSUE #158587: `useCustomCodeActionMenu` settings behave oddly when resetting default
Type: <b>Bug</b>

Go to Settings Editor, search for 'customcodeactionmenu', then use gearwheel menu on the first item to reset its default. Observe that the checkbox of the second item changes. Repeat the reset on the first item and the second one changes again.

junk

VS Code version: Code - Insiders 1.71.0-insider (28f604dec81b609dd7e69362585f7a99d4c48f88, 2022-08-19T05:17:14.894Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

### PR DESCRIPTION
**Pull request by justschen**
Fixes https://github.com/microsoft/vscode/issues/158587

### CODE REVIEW

File: src/vs/editor/contrib/codeAction/browser/codeActionMenu.ts [hunk 1]
```diff
@@ -441,7 +441,7 @@ export class CodeActionMenu extends Disposable implements IEditorContribution {
 		const totalActionEntries: (IAction | string)[] = [];
 
 		// Checks if headers are disabled.
-		if (this.isCodeActionWidgetHeadersDisabled(model)) {
+		if (!this.isCodeActionWidgetHeadersDisabled(model)) {
```
Comment (rzhao271) [inline src/vs/editor/contrib/codeAction/browser/codeActionMenu.ts:444]: The code doesn't seem to agree with the comment here.

**Review by rzhao271 — APPROVED** [review]
