### PR TITLE
Fix bug causing workspace recommendations to go away upon ignoring a recommendation

### LINKED ISSUE #55596: "Ignore Recommendation" makes all workspace recommendations go away
- Open a workspace with recommended extensions e.g. vscode
- See the 3 recommended extensions in the viewlet
- Click Debugger For Chrome, click "Ignore Recommendation"
- All 3 workspace recommendations disappear :bug:
- Refresh the viewlet, now just 2 recommendations appear ✔️

### PR DESCRIPTION
**Pull request by JacksonKearl**
Fixes #55596, where all workspace recommendations (the pane in the `@recommended` search view) would vanish after ignoring any recommendation. 

I think this should be in July becuase it is pretty jarring and unexpected, and it happens any time you're in the `@recommended` search view and ignore any recommenedation

### CODE REVIEW

File: src/vs/workbench/parts/extensions/electron-browser/extensionsViews.ts [hunk 1]
```diff
@@ -801,7 +801,7 @@ export class WorkspaceRecommendedExtensionsView extends ExtensionsListView {
 	}
 
 	async show(query: string): Promise<IPagedModel<IExtension>> {
-		let model = await ((query && query.trim() !== '@recommended') ? this.showEmptyModel() : super.show(this.recommendedExtensionsQuery));
+		let model = await (/@recommended/.test(query) ? super.show(this.recommendedExtensionsQuery) : this.showEmptyModel());
```
Comment (ramya-rao-a) [inline src/vs/workbench/parts/extensions/electron-browser/extensionsViews.ts]: In the scenario which we are trying to fix, what is the value of `query`?

Comment (JacksonKearl) [reply src/vs/workbench/parts/extensions/electron-browser/extensionsViews.ts]: `@recommened:workspace`

Comment (ramya-rao-a) [reply src/vs/workbench/parts/extensions/electron-browser/extensionsViews.ts]: Then the right fix should be that we should check with `this.recommendedExtensionsQuery` instead of `@recommended`

Comment (ramya-rao-a) [reply src/vs/workbench/parts/extensions/electron-browser/extensionsViews.ts]: We wouldn't want the `WorkspaceRecommendedExtensionsView` to run its query in case of say `@recommended Go`. So the right fix here would be `query && query.trim() !== '@recommended' && query.trim() !== '@recommended:workspace'

File: src/vs/workbench/parts/extensions/electron-browser/extensionsViews.ts [hunk 2]
```diff
@@ -801,7 +801,8 @@ export class WorkspaceRecommendedExtensionsView extends ExtensionsListView {
 	}
 
 	async show(query: string): Promise<IPagedModel<IExtension>> {
-		let model = await ((query && query.trim() !== '@recommended') ? this.showEmptyModel() : super.show(this.recommendedExtensionsQuery));
+		let shouldShowWorkspaceRecommended = query && (query.trim() === '@recommended' || query.trim() === '@recommended:workspace');
```
Comment (ramya-rao-a) [inline src/vs/workbench/parts/extensions/electron-browser/extensionsViews.ts]: When `query` is an empty string, this will end up showing the empty model, where as all the other views do not do so. So we are not being consistent

**Review by ramya-rao-a — APPROVED** [review]
