### PR TITLE
fix uri fragment slugification #94508

### LINKED ISSUE #94508: Markdown Rendering drops '=' from relative paths
Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. call in extension's `activate` function 
```js
vscode.commands.executeCommand('markdown.api.render', '[page=42](doc/myfile.pdf#page=42)').then(result => {
    console.log(`rendered markdown: ${result}`);
});
```
gives ...
```
<p data-line="0" class="code-line"><a href="doc/myfile.pdf#page42" data-href="doc/myfile.pdf#page42">page=42</a></p>
```
'=' character was dropped !

2. call in extension's `activate` function 
```js
vscode.commands.executeCommand('markdown.api.render', '[page=42](file://///server/path/doc/myfile.pdf#page=42)').then(result => {
    console.log(`rendered markdown: ${result}`);
});
```
gives ...
```
<p data-line="0" class="code-line"><a href="file://///server/path/doc/myfile.pdf#page=42" data-href="file://///server/path/doc/myfile.pdf#page=42">page=42</a></p>
```
'=' character was **not** dropped !

Does this issue occur when all extensions are disabled?:  Hmm ... extension is needed in this case.

### PR DESCRIPTION
**Pull request by iliazeus**
Previously, all links to local files had their fragment parts normalized (e.g. `foo.md#Bar baz` became `foo.md#bar-baz`). This allowed links to specific sections of other markdown files (`file#Section header`), but broke many other links.

This PR limits the normalization to paths without a file extension (as per [suggestion](https://github.com/microsoft/vscode/issues/94508#issuecomment-610620509)).

This may, however, have an unfortunate side effect of breaking some markdown links that do have an extension (e.g. `foo.md#Bar baz` won't work, but `foo#Bar baz` will).

This PR fixes #94508

### CODE REVIEW

File: extensions/markdown-language-features/src/markdownEngine.ts [hunk 1]
```diff
@@ -251,7 +251,7 @@ export class MarkdownEngine {
 						}
 					}
 
-					if (uri.fragment) {
+					if (uri.fragment && !path.extname(uri.fsPath)) {
```
Comment (mjbvz) [inline extensions/markdown-language-features/src/markdownEngine.ts:254]: We should also normalize links that appear to be markdown files from their extension (such as ending in `.md`)

Comment (iliazeus) [reply extensions/markdown-language-features/src/markdownEngine.ts:254]: Should we do this for all the possible markdown extensions (as recognized by vscode), or just for `.md`?

https://github.com/microsoft/vscode/blob/5c9a1b5d40f06c92c66bb2dc5f80c92eac374b88/extensions/markdown-basics/package.json#L19-L29

Comment (mjbvz) [reply extensions/markdown-language-features/src/markdownEngine.ts:254]: Sure, seems like a good idea

**Comment by iliazeus** [comment]
Added an additional check for known markdown file extensions. Now links are slugified if they have a markdown file extensions or do not have an extension at all.

**Comment by mjbvz** [comment]
Thanks! This change will be in the next VS code insiders build and is scheduled to go out with VS Code 1.45
