### PR TITLE
Render markdown preview cells inside a shadow dom

### LINKED ISSUE #119971: CSS in custom renderer messes up markdown rendering
- VS Code Version: 1.55.0-insiders
- OS Version:  Darwin x64 19.6.0

Steps to Reproduce:
1. Use the yeoman generator to create a Notebook or use the Notebook here: https://github.com/tanhakabir/vscode-notebooks-demo at branch `complete`
2. Verify/Make the renderer render a list
3. Verify/Make the css of the list have a weird font
4. Run the Notebook in Extension Host
5. Create a markdown cell with a list
6. See that your css change for lists in the renderer was also applied to the list in the markdown

recording (23)

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #119971

This moves all markdown previews into shadow doms. This lets us prevent styles from outside the preview leaking into the preview, and also prevents styles from the preview leaking out into the rest of the notebook

### CODE REVIEW

File: extensions/markdown-language-features/notebook/index.ts [hunk 1]
```diff
@@ -24,5 +24,10 @@ type extendMarkdownItFnType = (
 	notebook.onDidCreateMarkdown(({ element, content }: any) => {
 		const rendered = markdownIt.render(content);
 		element.innerHTML = rendered;
+
+		// Insert styles into markdown preview shadow dom so that they are applied
+		for (const markdownStyleNode of document.getElementsByClassName('markdown-style')) {
```
Comment (mjbvz) [inline extensions/markdown-language-features/notebook/index.ts:29]: In the future, we should look into pulling in contributed styles through some explicit contribution point instead of this implicit convention

**Comment by mjbvz** [comment]
Merging this to get additional testing in insiders
