### PR TITLE
Implement multiLinePasteWarning in VSCode terminal，fix the #122683

### LINKED ISSUE #122683: Implement multiLinePasteWarning in VSCode terminal, similar to Windows Terminal behavior
Please implement a [multiLinePasteWarning](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/interaction#warn-when-the-text-to-paste-contains-multiple-lines) for the VSCode integrated terminal, similar to Windows Terminal.

image

More times than I care to admit, I've accidentally pasted bad text into a VSCode integrated terminal session - often due to either the wrong panel being in focus, or fat fingering an unintended right-mouse-click at a bad place/time.

VSCode workspaces have replaced 99% of my standalone terminal usage these days. Having that safety net is _by far_ the top of my missing-features wish list.

(... and I was surprised to come up empty handed when searching for an existing setting or open issue.)

### PR DESCRIPTION
**Pull request by Kalmaegi**
This PR fixes #122683

### CODE REVIEW

**Review by Harry-Hopkinson — APPROVED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 1]
```diff
@@ -1058,6 +1060,47 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
...
+		if (textForLines.length === 1 || this._configurationService.getValue<boolean>(TerminalSettingId.MultiLinePasteWarning) === false) {
+			confirmation = { confirmed: true };
+		} else {
+			let message = nls.localize('confirmMoveTrashMessageFilesAndDirectories', "Are you sure you want to paste the following {0} lines to the terminal?", text.split(/\r\n|\n|\r/).length);
+
+			let displayItemsCount = 3;
+			let detail = textForLines.slice(0, displayItemsCount).join('');
+			if (textForLines.length > displayItemsCount) {
+				detail += '...';
+			}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1077]: We could also truncate each individual line to fix the case you called out in https://github.com/microsoft/vscode/issues/122683#issuecomment-1025093731. How does a max line length of 30 work, using `…` on each line if exceeded?

File: src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts [hunk 2]
```diff
@@ -133,6 +133,11 @@ const terminalConfiguration: IConfigurationNode = {
 			type: 'boolean',
 			default: false
 		},
+		[TerminalSettingId.MultiLinePasteWarning]: {
+			description: localize('terminal.integrated.multiLinePasteWarning', "show the warning indicator when the terminal does a multi-line paste."),
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts:137]:
```suggestion
			description: localize('terminal.integrated.multiLinePasteWarning', "Show a warning dialog when pasting multiple lines into the terminal."),
```

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 3]
```diff
@@ -1136,8 +1179,14 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 		if (!this.xterm) {
 			return;
 		}
+
+		let currentText: string = await this._clipboardService.readText();
+		if (await this._shouldPasteText(currentText) === false) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1184]:
```suggestion
		if (!(await this._shouldPasteText(currentText))) {
```

File: src/vs/platform/terminal/common/terminal.ts [hunk 4]
```diff
@@ -49,6 +49,7 @@ export const enum TerminalSettingId {
 	MacOptionClickForcesSelection = 'terminal.integrated.macOptionClickForcesSelection',
 	AltClickMovesCursor = 'terminal.integrated.altClickMovesCursor',
 	CopyOnSelection = 'terminal.integrated.copyOnSelection',
+	MultiLinePasteWarning = 'terminal.integrated.multiLinePasteWarning',
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/terminal.ts:52]: Let's change the setting to `enableMultiLinePasteWarning` to align closer with most other boolean settings

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 5]
```diff
@@ -1058,6 +1060,47 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 		this._terminalAltBufferActiveContextKey.set(!!(this.xterm && this.xterm.raw.buffer.active === this.xterm.raw.buffer.alternate));
 	}
 
+	private async _shouldPasteText(text: string): Promise<boolean> {
+		let textForLines = text.split(/(\r\n|\n|\r)/);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1064]: Should be equivalent:

```suggestion
		let textForLines = text.split(/(\r?\n)/);
```

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 6]
```diff
@@ -1058,6 +1060,47 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
...
+		// If the clipboard has only one line, no prompt will be triggered
+		if (textForLines.length === 1 || this._configurationService.getValue<boolean>(TerminalSettingId.MultiLinePasteWarning) === false) {
+			confirmation = { confirmed: true };
+		} else {
+			let message = nls.localize('confirmMoveTrashMessageFilesAndDirectories', "Are you sure you want to paste the following {0} lines to the terminal?", text.split(/\r\n|\n|\r/).length);
+
+			let displayItemsCount = 3;
+			let detail = textForLines.slice(0, displayItemsCount).join('');
+			if (textForLines.length > displayItemsCount) {
+				detail += '...';
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1076]: Can use the ellipsis character here

```suggestion
				detail += '…';
```

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 7]
```diff
@@ -1058,6 +1060,47 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
...
+		let textForLines = text.split(/(\r\n|\n|\r)/);
+		let confirmation: IConfirmationResult;
+
+		// If the clipboard has only one line, no prompt will be triggered
+		if (textForLines.length === 1 || this._configurationService.getValue<boolean>(TerminalSettingId.MultiLinePasteWarning) === false) {
+			confirmation = { confirmed: true };
+		} else {
+			let message = nls.localize('confirmMoveTrashMessageFilesAndDirectories', "Are you sure you want to paste the following {0} lines to the terminal?", text.split(/\r\n|\n|\r/).length);
+
+			let displayItemsCount = 3;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1073]: const?

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 8]
```diff
@@ -1058,6 +1060,47 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
...
 	}
 
+	private async _shouldPasteText(text: string): Promise<boolean> {
+		let textForLines = text.split(/(\r\n|\n|\r)/);
+		let confirmation: IConfirmationResult;
+
+		// If the clipboard has only one line, no prompt will be triggered
+		if (textForLines.length === 1 || this._configurationService.getValue<boolean>(TerminalSettingId.MultiLinePasteWarning) === false) {
+			confirmation = { confirmed: true };
+		} else {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1070]: Exit early here?

```suggestion
		if (textForLines.length === 1 || this._configurationService.getValue<boolean>(TerminalSettingId.MultiLinePasteWarning) === false) {
			return true;
		}
```

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 9]
```diff
@@ -1058,6 +1060,47 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
...
+		if (!confirmation.confirmed) {
+			return false;
+		}
+
+		// Check for confirmation checkbox
+		if (confirmation.confirmed && confirmation.checkboxChecked === true) {
+			await this._configurationService.updateValue(TerminalSettingId.MultiLinePasteWarning, false);
+		}
+		return true;
+	}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1101]: Could be simplified:

```suggestion
		// Don't ask again if the checkbox is checked
		if (confirmation.confirmed && confirmation.checkboxChecked) {
			await this._configurationService.updateValue(TerminalSettingId.MultiLinePasteWarning, false);
		}
		
		return confirmation.confirmed;
	}
```

**Review by Tyriar — CHANGES_REQUESTED** [review]
Thanks @slidoooor, looks great! Just some minor comments

File: src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts (hunk 2 above)
Comment (slidoooor) [reply src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts:137]: thanks! My English is bad

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts (hunk 1 above)
Comment (slidoooor) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts]: I agree, deal with https://github.com/slidoooor/vscode/blob/0bb6cac9f79af64a07126d23ca1a86b2c8363280/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1078

Comment (slidoooor) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts]: > We could also truncate each individual line to fix the case you called out in [#122683 (comment)](https://github.com/microsoft/vscode/issues/122683#issuecomment-1025093731). How does a max line length of 30 work, using `…` on each line if exceeded?

I agree, deal with:
https://github.com/slidoooor/vscode/blob/0bb6cac9f79af64a07126d23ca1a86b2c8363280/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1078

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts (hunk 7 above)
Comment (slidoooor) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts]: yes! XD

File: src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts (hunk 2 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts]: No worries 🙂

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 10]
```diff
@@ -1058,6 +1060,47 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
...
+		} else {
+			const message = nls.localize('confirmMoveTrashMessageFilesAndDirectories', "Are you sure you want to paste the following {0} lines to the terminal?", text.split(/\r\n|\n|\r/).length);
+
+			const displayItemsCount = 3;
+			const ellipsis = '…';
+
+			let detail = textForLines
+				.slice(0, displayItemsCount)
+				.map(s => s.length >= 30 ? s.slice(0, 30) + ellipsis : s)
+				.join('');
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1079]: Think we need to join with \n?

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts (hunk 10 above)
Comment (slidoooor) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1079]: > Think we need to join with \n?

I think we don’t need join with \n, Because  we split ’textForLines‘ is included \n, we show the first three parts, Ideally it contains two lines of text and a \n

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts]: Ah ok, reading that part of the code was a little confusing.

**Review by Tyriar — APPROVED** [review]
Thanks for the contribution @slidoooor, I just made some clean up changes in my last commit.

**Comment by slidoooor** [comment]
> Thanks for the contribution @slidoooor, I just made some clean up changes in my last commit.

Thank you for helping me improve！
