### PR TITLE
Preserve execution summary when converting dto

### LINKED ISSUE #124548: Notebook serializer does not contain cell execution summary info
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders
- OS Version: Mac

Steps to Reproduce:

1. Create a serializer
2. Save a document with cells having an execution order
3. The execution order is not available in the cells

### PR DESCRIPTION
**Pull request by DonJayamanne**
This PR fixes #124548
@jrieken @rebornix /cc

### CODE REVIEW

File: src/vs/workbench/api/common/extHostTypeConverters.ts [hunk 1]
```diff
@@ -1433,6 +1433,18 @@ export namespace NotebookCellMetadata {
 	}
 }
 
+export namespace NotebookCellInternalMetadata {
```
Comment (jrieken) [inline src/vs/workbench/api/common/extHostTypeConverters.ts:1436]: There already exists `NotebookCellExecutionSummary.from` and we should merge the `to` util into that

**Review by jrieken — CHANGES_REQUESTED** [review]

**Review by jrieken — APPROVED** [review]
