### PR TITLE
ensure quick fix selector is registered before provider

### LINKED ISSUE #168154: Error: No registered selector for ID: ms-vscode.npm-command
Running out of sources I see this:

```
[66219:1206/102201.181288:INFO:CONSOLE(216)] "%c  ERR color: #f33 No registered selector for ID: ms-vscode.npm-command: Error: No registered selector for ID: ms-vscode.npm-command
    at TerminalQuickFixService.registerQuickFixProvider (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/terminal/browser/terminalQuickFixService.js:26:23)
    at MainThreadTerminalService.$registerQuickFixProvider (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/api/browser/mainThreadTerminalService.js:205:75)
    at RPCProtocol._doInvokeHandler (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:381:27)
    at RPCProtocol._invokeHandler (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:366:45)
    at RPCProtocol._receiveRequest (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:307:32)
    at RPCProtocol._receiveOneMessage (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:234:26)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:115:52
    at Listener.invoke (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:514:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:688:38)
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:653:37)
    at BufferedEmitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.net.js:480:35)
    at PersistentProtocol._receiveMessage (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.net.js:746:45)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.net.js:627:83
    at Listener.invoke (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:514:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:688:38)
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:653:37)
    at ProtocolReader.acceptChunk (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.net.js:271:37)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.net.js:238:61
    at Socket.listener (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/node/ipc.net.js:63:17)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

### LINKED ISSUE #170849: No registered selector for ID: ms-vscode.npm-command
```javascript
Error: No registered selector for ID: ms-vscode.npm-command
at R.registerQuickFixProvider in src/vs/workbench/contrib/terminal/browser/terminalQuickFixService.ts:39:10
at a.$registerQuickFixProvider in src/vs/workbench/api/browser/mainThreadTerminalService.ts:253:65
at b.N in src/vs/workbench/services/extensions/common/rpcProtocol.ts:455:17
at b.M in src/vs/workbench/services/extensions/common/rpcProtocol.ts:440:32
at b.H in src/vs/workbench/services/extensions/common/rpcProtocol.ts:370:19
at b.G in src/vs/workbench/services/extensions/common/rpcProtocol.ts:296:10
at <anonymous> in src/vs/workbench/services/extensions/common/rpcProtocol.ts:161:42
at u.invoke in src/vs/base/common/event.ts:692:17
at n.deliver in src/vs/base/common/event.ts:899:22
at d.fire in src/vs/base/common/event.ts:860:24
at a.fire in src/vs/base/parts/ipc/common/ipc.net.ts:671:19
at k.E in src/vs/base/parts/ipc/common/ipc.net.ts:1109:23
at <anonymous> in src/vs/base/parts/ipc/common/ipc.net.ts:955:72
at u.invoke in src/vs/base/common/event.ts:692:17
at n.deliver in src/vs/base/common/event.ts:899:22
at d.fire in src/vs/base/common/event.ts:860:24
at h.acceptChunk in src/vs/base/parts/ipc/common/ipc.net.ts:415:21
at <anonymous> in src/vs/base/parts/ipc/common/ipc.net.ts:371:51
at listener in src/vs/platform/remote/browser/browserSocketFactory.ts:230:39
at u.invoke in src/vs/base/common/event.ts:692:17
at n.deliver in src/vs/base/common/event.ts:899:22
at d.fire in src/vs/base/common/event.ts:860:24
at E.i.onload in src/vs/platform/remote/browser/browserSocketFactory.ts:91:17
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=727d2d32aea02baf7d13fa38787e8ed64dd858d0&bH=f8b57c4d-c066-cc2b-8f36-19c978b70cee)

### PR DESCRIPTION
**Pull request by meganrogge**
fix #168154
fix #170849

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/test/browser/terminalProfileService.integrationTest.ts [hunk 1]
```diff
@@ -90,7 +90,7 @@ class TestTerminalExtensionService extends TestExtensionService {
 class TestTerminalContributionService implements ITerminalContributionService {
 	_serviceBrand: undefined;
 	terminalProfiles: readonly IExtensionTerminalProfile[] = [];
-	quickFixes: ITerminalCommandSelector[] = [];
+	quickFixes: Promise<ITerminalCommandSelector[]> = new Promise((r) => { r([]); });
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/test/browser/terminalProfileService.integrationTest.ts:93]: Nicer way of doing this: `Promise.resolve([])`

**Review by Tyriar — APPROVED** [review]
