### PR TITLE
Dispose all Disposables from tests

### LINKED ISSUE #114125: Flaky test: ConfigurationEditingService
Noticed failure on Windows: https://dev.azure.com/vscode/VSCode/_build/results?buildId=61555&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=d494b5db-eef8-5766-984e-01186010c86f

```
  6402 passing (2m)
  52 pending
  1 failing

  1) ConfigurationEditingService
       "after each" hook for "write one setting - existing file":
     Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\VSSADM~1\AppData\Local\Temp\vsctests\7322e17d-a1c4-43dd-86e9-cdd8bbe034f9\workspaceconfig\7322e17d-a1c4-43dd-86e9-cdd8bbe034f9'
```

The failure is in rimraf in the cleanup part of the test. This indicates that there are still fs operations running after the test has signaled completion. I am looking into a PR to improve things.

### PR DESCRIPTION
**Pull request by alexdima**
Fixes #114125

In investigating #114125 I have added two troubleshooting helpers for tests. They are aready on `master` and they are about logging FS calls and tracking disposables. This change glues the needed things together such that each test disposes every Disposable that is created.

The change in `fileService.ts` is cosmetic, but avoids having always a false positive where a disposable iscreated via `toDisposable` but it is never disposed.

### CODE REVIEW

File: src/vs/platform/files/common/fileService.ts [hunk 1]
```diff
@@ -901,19 +901,19 @@ export class FileService extends Disposable implements IFileService {
 
 	watch(resource: URI, options: IWatchOptions = { recursive: false, excludes: [] }): IDisposable {
 		let watchDisposed = false;
-		let watchDisposable = toDisposable(() => watchDisposed = true);
+		let disposeWatch = () => { watchDisposed = true; };
```
Comment (bpasero) [inline src/vs/platform/files/common/fileService.ts:904]: This is just a :lipstick: change right?

File: src/vs/workbench/services/configuration/browser/configuration.ts [hunk 2]
```diff
@@ -415,6 +415,11 @@ export class WorkspaceConfiguration extends Disposable {
 		this._workspaceConfiguration = this._cachedConfiguration = new CachedWorkspaceConfiguration(configurationCache);
 	}
 
+	public dispose() {
```
Comment (bpasero) [inline src/vs/workbench/services/configuration/browser/configuration.ts:418]:
```suggestion
	dispose() {
```

File: src/vs/workbench/services/configuration/browser/configuration.ts [hunk 3]
```diff
@@ -415,6 +415,11 @@ export class WorkspaceConfiguration extends Disposable {
...
+		super.dispose();
+		this._workspaceConfiguration.dispose();
```
Comment (bpasero) [inline src/vs/workbench/services/configuration/browser/configuration.ts:420]: I think a `MutableDisposable` would be easier to use here.

File: src/vs/workbench/services/configuration/browser/configurationService.ts [hunk 4]
```diff
@@ -462,7 +462,7 @@ export class WorkspaceService extends Disposable implements IWorkbenchConfigurat
 
 			if (!this.localUserConfiguration.hasTasksLoaded) {
 				// Reload local user configuration again to load user tasks
-				runWhenIdle(() => this.reloadLocalUserConfiguration(), 5000);
+				this._register(runWhenIdle(() => this.reloadLocalUserConfiguration(), 5000));
```
Comment (bpasero) [inline src/vs/workbench/services/configuration/browser/configurationService.ts:465]: I am not sure since I did not write this code, but is this adding disposables over and over?

**Review by bpasero — APPROVED** [review]
Thanks, left some comments inline.

File: src/vs/platform/files/common/fileService.ts (hunk 1 above)
Comment (alexdima) [reply src/vs/platform/files/common/fileService.ts:904]: Yes, it is a cosmetic change to avoid a false positive with the Disposable tracking that I added. The initial version was creating a Disposable via `toDisposable` which was setting the flag to true. But that particular initial disposable was never disposed in the happy case, since it got overwritten with the real disposable. The tool I wrote to detect Disposable leaks would always flag this particular code location. It is technically accurate, that the Disposable was "leaking", but this was not a real Disposable, it was just a code pattern kind of Disposable. So long story short, I just switched to use a simple method.

File: src/vs/workbench/services/configuration/browser/configurationService.ts (hunk 4 above)
Comment (alexdima) [reply src/vs/workbench/services/configuration/browser/configurationService.ts:465]: It apepared to be called only once from `initialize`, but leaving it off to @sandy081 to decide.

File: src/vs/workbench/services/configuration/browser/configuration.ts (hunk 3 above)
Comment (alexdima) [reply src/vs/workbench/services/configuration/browser/configuration.ts:420]: I agree, also another variant would be to wrap with `this._register` a few lines above in the ctor. Leaving to @sandy081 to decide.

Comment (sandy081) [reply src/vs/workbench/services/configuration/browser/configuration.ts]: Refactored. Please check latest changes.

File: src/vs/workbench/services/configuration/browser/configurationService.ts (hunk 4 above)
Comment (sandy081) [reply src/vs/workbench/services/configuration/browser/configurationService.ts:465]: Makes sense

**Review by sandy081 — APPROVED** [review]
