### PR TITLE
Go To Line bug fixes

### LINKED ISSUE #275000: Help text doesn't update when toggling offsetmode
Testing #274949 

* open go to line
* type `::` for offset mode
* help text says "Type ... from 1 to ..." 
* toggle offset mode
* :bug: the message never updates to "... from 0 to ..."

### LINKED ISSUE #275001: Revisit setting `workbench.quickOpen.useZeroBasedOffset`
Testing #274949 

There is the `workbench.quickOpen.useZeroBasedOffset` which uses a too generic name, because this isn't about quickOpen in general but about go to line specifically. Then, I seriously question the use of a setting here. IMO this is a prime use-case for workspace state just like find modes (Match Case, Match Word etc)

### LINKED ISSUE #275321: [Nitpick] Go To Line command: Recommended Text Updates
Testing #274949

Tiny nitpick: I feel like the message `Type an offset in the file from 1 to X to go to` is easier to understand at a glance what the feature is doing since I rarely think about "jumping to a character number"
Image

### PR DESCRIPTION
**Pull request by dmitrivMS**
Fixes #275000
Fixes #275001
Fixes #275321

Moved zero-based offset setting to workspace storage.
Updated guidance text per suggestions.
Make sure guidance for offset is updated when toggle state is changed.

### CODE REVIEW

File: src/vs/workbench/contrib/codeEditor/browser/quickaccess/gotoLineQuickAccess.ts [hunk 1]
```diff
@@ -20,26 +20,29 @@ import { KeybindingWeight } from '../../../../../platform/keybinding/common/keyb
...
-	private static zeroBasedOffsetSetting = 'workbench.quickOpen.useZeroBasedOffset';
+	private static readonly ZERO_BASED_OFFSET_STORAGE_KEY = 'gotoLine.useZeroBasedOffset';
 	protected readonly onDidActiveTextEditorControlChange: Event<void>;
 
 	constructor(
 		@IEditorService private readonly editorService: IEditorService,
 		@IEditorGroupsService private readonly editorGroupService: IEditorGroupsService,
-		@IConfigurationService private readonly configurationService: IConfigurationService
+		@IConfigurationService private readonly configurationService: IConfigurationService,
+		@IStorageService private readonly storageService: IStorageService
```
Comment (TylerLeonhardt) [inline src/vs/workbench/contrib/codeEditor/browser/quickaccess/gotoLineQuickAccess.ts:34]: Haven't thought it fully through but `IStorageService` is in platform... could we just use this in the base class?

**Review by mjbvz — APPROVED** [review]

File: src/vs/workbench/contrib/codeEditor/browser/quickaccess/gotoLineQuickAccess.ts [hunk 2]
```diff
@@ -20,26 +20,29 @@ import { KeybindingWeight } from '../../../../../platform/keybinding/common/keyb
...
-				return configurationService.getValue<boolean>(GotoLineQuickAccessProvider.zeroBasedOffsetSetting);
+				return storageService.getBoolean(GotoLineQuickAccessProvider.ZERO_BASED_OFFSET_STORAGE_KEY, StorageScope.WORKSPACE, false);
 			},
 			set value(value: boolean) {
-				configurationService.updateValue(GotoLineQuickAccessProvider.zeroBasedOffsetSetting, value);
+				storageService.store(GotoLineQuickAccessProvider.ZERO_BASED_OFFSET_STORAGE_KEY, value, StorageScope.WORKSPACE, StorageTarget.MACHINE);
 			}
 		});
 		this.onDidActiveTextEditorControlChange = this.editorService.onDidActiveEditorChange;
+		void this.storageService; // workaround for unused variable warning
```
Comment (TylerLeonhardt) [inline src/vs/workbench/contrib/codeEditor/browser/quickaccess/gotoLineQuickAccess.ts:45]: You should be able to remove `private readonly` from `storageService` instead of this
