### PR TITLE
Semantic highlighting fixes for 1.43.1

### LINKED ISSUE #92740: Semantic highlighting improvements for 1.43.1
As mentioned in https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#semantic-highlighting, the goal is to improve the first impression of semantic highlighting as well allow themes to opt-in to semantic highlighting.

- give themes a way to opt-in to semantic highlighting
- enable semantic coloring by default only the built-in themes. All other themes can be enabled by the theme author or in the user settings.
- show a notification when semantic coloring shows up the first time. The notification will point to the docs with background and information on how to configure the feature.
- fix the bugs found related to wrong token classification and color lookup.
- no longer show semantic color in imports

### PR DESCRIPTION
**Pull request by aeschli**
Semantic highlighting fixes for 1.43.1 as discussed in https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#semantic-highlighting

https://github.com/microsoft/vscode/pull/92737/commits/f8a038284bde2e40a8fbb58000f2a9d76bbfb62f
- fix for the style lookup found in #92536. For a given Text Mate scope, find the the theming rule in the current theme. When there are multiple rules matching, use the most specific one. The bug was to take the last, but not most specific rule.

https://github.com/microsoft/vscode/pull/92737/commits/53619cda496ac3cc64901d41bf71bf48a5d3fcb0
- Contains multiple fixed in the TypeScript server plugin. All covered by test cases.
  - https://github.com/aeschli/typescript-vscode-sh-plugin/commit/48034c886eeae91426dead7c9f866ebc0914c505 if the type of a variable is callable, it becomes a function except if also has properties and is not used in a callExpression, Examples: `require`, `describe`
  - https://github.com/aeschli/typescript-vscode-sh-plugin/commit/d155c22e7da8740508c3706926914640f1339718 variables that resolve to a type with a constructor function become a class. Example `Promise`, `Number`, `String`
  - https://github.com/aeschli/typescript-vscode-sh-plugin/commit/653598165fa6f2b3bae86becc601d1412ea4cb55 No highlighting in import (reduce the number of color changes)
  - https://github.com/aeschli/typescript-vscode-sh-plugin/commit/4efdc9d1b2d4d97c68d7ad8617d3bf86563e9990 fix the bug that references to properties declared in constructors where classified as parameters, not properties
`constructor(private readonly name) { console.log(this.name); }`

https://github.com/microsoft/vscode/pull/92737/commits/76e9946d1c7db978ce9b24d9169a02c2b90f182b
- add a new property to color theme definition files: `semanticHighlighting: boolean`. Themes can control whether semanticHighlighting is enabled.
- all built-in themes have it enabled
- can be overwritten in the settings. For all themes, or per theme:
```
    "editor.tokenColorCustomizations": {
        "[Rouge 2]": {
            "semanticHighlighting": true
        }
    }
```
- part of the persisted properties for quick restore of theme
- onDidColorThemeChange is emited when property changes (by user settings, or load/reload)

### CODE REVIEW

File: src/vs/workbench/services/themes/common/colorThemeData.ts [hunk 1]
```diff
@@ -574,10 +591,10 @@ function _loadColorTheme(extensionResourceLoaderService: IExtensionResourceLoade
 						return Promise.reject(new Error(nls.localize({ key: 'error.invalidformat.tokenColors', comment: ['{0} will be replaced by a path. Values in quotes should not be translated.'] }, "Problem parsing color theme file: {0}. Property 'tokenColors' should be either an array specifying colors or a path to a TextMate theme file", themeLocation.toString())));
 					}
 				}
-				let tokenStylingRules = contentValue.tokenStylingRules;
-				if (tokenStylingRules && typeof tokenStylingRules === 'object') {
-					result.stylingRules = readCustomTokenStyleRules(tokenStylingRules, result.stylingRules);
-				}
+				// let tokenStylingRules = contentValue.tokenStylingRules;
```
Comment (aeschli) [inline src/vs/workbench/services/themes/common/colorThemeData.ts]: this feature is not yet working, so I commented it out

**Review by alexdima — APPROVED** [review]
The changes here LGTM.

I have not reviewed the changes in the typescript semantic provider plugin. I tried to, but I believe those should be done via individual issue verification where code samples are provided, because by looking at the code it is difficult to understand how the AST looks and form a good opinion, etc.
