### PR TITLE
cap lines based on max buffer size

### LINKED ISSUE #177310: When executing a command with very large output, it seems that the last line of the accessible buffer is bringing some garbage
Type: <b>Bug</b>
cc: @meganrogge @isidorn 

Steps to reproduce:

1. Open a terminal in VSCode and run the following command:
```
ls -l /usr/bin
```
2. After receiving the response from the command executed in step 1, also execute the following command:
```
pwd
```
3. Press shift+tab and examine the contents of the last line of the accessible buffer.

The expected result, at least in my understanding, is that the content of the last line was the prompt displayed in the terminal. However, what is being displayed looks like a line displayed by the ls command executed in the first step.

```
'-rwxr-xr-x  1 root root      141080 Oct  5 08:48  ps-rwxr-xr-x  1 root root      141080 Oct  5 08:48  ps'
```

VS Code version: Code - Insiders 1.77.0-insider (215351a4cf2bada6f5be0857e716e5386a21cb1b, 2023-03-15T05:21:59.212Z)
OS version: Linux x64 6.1.15-200.fc37.x86_64
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|15.27GB (8.10GB free)|
|Process Argv|-n --crash-reporter-id bc02adbd-6c3a-44b8-af92-55103a608af7|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.49.0
vscode-chatgpt|gen|3.9.5
rest-client|hum|0.25.1
better-cpp-syntax|jef|1.17.2
azure-pipelines|ms-|1.208.0
vscode-docker|ms-|1.24.0
csharp|ms-|1.25.4
vscode-dotnet-runtime|ms-|1.6.0
vscode-kubernetes-tools|ms-|1.3.11
remote-containers|ms-|0.284.0
remote-ssh|ms-|0.99.2023031515
remote-ssh-edit|ms-|0.84.0
azure-account|ms-|0.11.3
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.6.0
powershell-preview|ms-|2023.3.0
remote-explorer|ms-|0.3.2023021509
vsliveshare|ms-|1.0.5834
oracledevtools|Ora|21.5.0
fabric8-analytics|red|0.3.6
java|red|1.16.2023031504
vscode-xml|red|0.25.2023031109
vscode-yaml|red|1.12.1
sonarlint-vscode|Son|3.15.1
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.45.0
vscode-java-debug|vsc|0.49.2023022723
vscode-java-dependency|vsc|0.21.2023030900
vscode-java-pack|vsc|0.25.2023031100
vscode-java-test|vsc|0.38.2023030203
vscode-maven|vsc|0.40.2023031403
vscode-spring-boot-dashboard|vsc|0.11.1
vscode-spring-initializr|vsc|0.11.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstes627cf:30244335
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
6233i204:30659907
pythonb192:30661256
defaultazurewalk:30687958
pythonms35:30671666
cai9j608:30680470
24365598:30687740

```

</details>

### PR DESCRIPTION
**Pull request by meganrogge**
fix #177310

### CODE REVIEW

File: src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminalAccessibleBuffer.ts [hunk 1]
```diff
@@ -229,7 +230,7 @@ export class AccessibleBufferWidget extends DisposableStore {
 		if (!buffer) {
 			return '';
 		}
-		const end = buffer.length;
+		const end = Math.min(Constants.MaxBufferSize, buffer.length);
 		for (let i = startLine ?? 0; i <= end; i++) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminalAccessibleBuffer.ts:234]: If scrollback > 1000, doesn't this mean it will not write the content in the viewport (or anything below the top 1024 lines)?

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminalAccessibleBuffer.ts:234]: We don't currently write the scroll-back to the buffer, but can consider doing that. This change makes it so the most recent 1024 lines are in there

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminalAccessibleBuffer.ts:234]: do we want to support scroll-back? if so, does that mean we'd need to save it somewhere when it goes outside of the viewport? does such a thing exist already?

Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminalAccessibleBuffer.ts:234]: You check > `Terminal.rows`, so you do write the scrollbak. Since you're using `getLine`, you don't want to start at index 0 through 1024, but `buffer.length - 1024` through `buffer.length`?

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminalAccessibleBuffer.ts:234]: I run `ls -l /usr/bin`, `ls -la` a bunch, and other commands. What I see when I focus the buffer is the most recently run 1024 lines, which is what I expect. Is that also what you expect?

Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminalAccessibleBuffer.ts:234]: The default scrollback is 1000 lines though, you're only displaying up to a maximum of line 1024. So if scrollback is 5000, it won't work when you have filled it? I haven't tested it, but I'm pretty sure this is an issue, try setting scrollback to 5000 and run `ls -lR ~` to fill it.

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminalAccessibleBuffer.ts:234]: won't starting at `buffer.length - 1024` in some cases be negative and in others, not include lines that we want?

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminalAccessibleBuffer.ts:234]: maybe i'm confused about why the max size of the buffer is 1024. is it scrollback + terminal.rows = buffer size? i'll do some logging in a bit to figure that out

Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminalAccessibleBuffer.ts:234]: With a scrollback fill where scrollback is 5000 and rows is 20, the oldest line will be `getLine(0)` and the newest line will be `getLine(5000+20-1)`. Currently you force a maximum line index of 1024 via `Math.min(Constants.MaxBufferSize, buffer.length);`. So once the scrollback has more than ~1000 lines, you'll start losing content and only be pulling old content.

**Review by Tyriar — APPROVED** [review]
