### PR TITLE
Fix navigation to single match in tree find

### LINKED ISSUE #236478: When searching in outline view, if a search mathes only one entry, I cannot jump to that match
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.96.0
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. open outline view
2. ctrl+alt+f
3. type text that matches only one entry
4. press Enter
5. focused position does not change

If the search mathes multiple entries, pressing Enter correctly navigates to the first match.

### PR DESCRIPTION
**Pull request by benibenj**
Fixes #236478

### CODE REVIEW

File: src/vs/base/browser/ui/tree/abstractTree.ts [hunk 1]
```diff
@@ -1177,7 +1177,7 @@ export class FindController<T, TFilterData> extends AbstractFindController<T, TF
 		this.tree.refilter();
 
 		if (pattern) {
-			this.tree.focusNext(0, true, undefined, (node) => this.shouldAllowFocus(node));
+			this.tree.focusNext(0, true, undefined, (node) => !FuzzyScore.isDefault(node.filterData as any as FuzzyScore));
```
Comment (Tyriar) [inline src/vs/base/browser/ui/tree/abstractTree.ts:1180]: Risky cast 😱

**Review by Tyriar — APPROVED** [review]
