### PR TITLE
add new line when running extension quick fix command

### LINKED ISSUE #167657: terminal quick fix contribution: command is inserted but not actually run
Testing #166762

For built-in quick fixes, the command is automatically run after selecting it. However, for custom ones, it just emits a ctrl+c and writes out the command without actually running it

Recording 2022-11-29 at 15 07 47

### PR DESCRIPTION
**Pull request by meganrogge**
fix #167657

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts [hunk 1]
```diff
@@ -339,13 +338,12 @@ export async function getQuickFixesForCommand(
 									run: () => {
 										onDidRequestRerunCommand?.fire({
 											command: fix.terminalCommand,
-											addNewLine: fix.addNewLine
+											addNewLine: !!fix.addNewLine ? fix.addNewLine : true
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts:341]: I think this will always use true, verify via the free port quick fix. This would be nicer also:

```suggestion
											addNewLine: fix.addNewLine ?? true
```

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Review by Tyriar — APPROVED** [review]
