### PR TITLE
Reland fix custom task shell doesn't work without manually passing in "run command" arg/flag

### LINKED ISSUE #169821: VS Code is still adding `/d /c` to task commands
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2
- OS Version: Windows 11

Steps to Reproduce (on Windows):

1. Have an `npm` task that starts a script.
2. In the User Preferences, set `"terminal.integrated.automationProfile.windows"` as such:
    ```json
    "terminal.integrated.automationProfile.windows": {
        "path": "nu.exe",
        "args": ["-c"],
    },
    ```
    This is an example; this also works with, e.g. `pwsh.exe` / `["-Command"]`.
3. Run the task.
4. VS Code will run `nu.exe -c /d /c yarn run name` rather than `nu.exe -c "yarn run name"`.

This was marked as fixed in #93437, but it isn't. A [workaround](https://github.com/microsoft/vscode/issues/93437#issuecomment-814330206) is given, but is IMO unacceptable. If I modify my shell in _user_ settings, I shouldn't have to modify a `tasks.json` that many users will use, and whose preferred shells are different. More importantly, a single shell can be specified, so `/bin/sh` won't work for users on Windows, and `cmd.exe` / `pwsh.exe` / whatever won't work for users on Linux. This makes `terminal.integrated.automationProfile.*` essentially useless.

Since `terminal.integrated.automationProfile.*` takes an `args` argument, why add unwanted arguments to it? I understand why defaults may be nice (e.g. set `args` to `["-Command"]` when `path` is `pwsh.exe`), but if preferences are explicitly specified, why append new arguments to them if they only work with a single shell?

### LINKED ISSUE #181302: Custom task shell executable doesn't work
Does this issue occur when all extensions are disabled?: Yes/No

Yes

Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

pwsh:

image

git bash:

image

without custom shell executable (default pwsh)

image

### PR DESCRIPTION
**Pull request by Legend-Master**
This PR relands #181760

Fix https://github.com/microsoft/vscode/issues/181302
Fix https://github.com/microsoft/vscode/issues/169821

### CODE REVIEW

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 1]
```diff
@@ -1120,12 +1119,12 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
 						shellLaunchConfig.args = undefined;
 					}
 					shellLaunchConfig.executable = await this._resolveVariable(variableResolver, shellOptions.executable);
-					shellSpecified = true;
 				}
 				if (shellOptions.args) {
 					shellLaunchConfig.args = await this._resolveVariables(variableResolver, shellOptions.args.slice());
 				}
 			}
+			const taskShellArgsSpecified = shellOptions?.args !== undefined;
```
Comment (Legend-Master) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:1127]: The difference between #181760 is that we check for `shellOptions?.args` instead of `shellLaunchConfig.args` here, so that the default profile's args don't affect us from adding in args like `-c`

**Review by meganrogge — CHANGES_REQUESTED** [review]
Tested various repos - this causes the default build task to fail in xterm.js for example

**Comment by Legend-Master** [comment]
> Tested various repos - this causes the default build task to fail in xterm.js for example

I just tested the change in the https://github.com/xtermjs/xterm.js repo but I don't see any differences between with this change and without, do you mind adding some more details about how it failed?

**Comment by meganrogge** [comment]
> > Tested various repos - this causes the default build task to fail in xterm.js for example
> 
> I just tested the change in the https://github.com/xtermjs/xterm.js repo but I don't see any differences between with this change and without, do you mi
Screenshot 2024-12-16 at 10 33 40 AM
nd adding some more details about how it failed?

**Review by meganrogge — APPROVED** [review]

**Comment by meganrogge** [comment]
Yep, my bad 🤦🏼‍♀️ 😄

**Review by roblourens — APPROVED** [review]
