### PR TITLE
Fix --max-memory argument incorrect parsing

### LINKED ISSUE #68279: Starting with `--max-memory=4096` fails due to < 2048 MB check
- VSCode Version: **1.31.0**
- OS Version: Windows **10.0.16299**

Also tested with Insider build and was able to reproduce. VSCode Version 1.30.2 does not exhibit this behavior.

Steps to Reproduce:

1. Run `code --max-memory=4096` (for large file support)
2. Receive error `The max-memory argument cannot be specified lower than 2048 MB.`

This also occurs with the in-editor prompt to restart VSCode when attempting to open a large file.

Does this issue occur when all extensions are disabled?: **Yes**

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes #68279

### CODE REVIEW

**Review by wppoland — APPROVED** [review]

**Comment by rebornix** [comment]
@jeanp413 thanks for your help!

File: src/vs/platform/environment/node/argvHelper.ts [hunk 1]
```diff
@@ -17,7 +17,8 @@ function validate(args: ParsedArgs): ParsedArgs {
 	}
 
 	if (args['max-memory']) {
-		assert(args['max-memory'] >= MIN_MAX_MEMORY_SIZE_MB, `The max-memory argument cannot be specified lower than ${MIN_MAX_MEMORY_SIZE_MB} MB.`);
+		console.log(parseInt(args['max-memory']));
```
Comment (jrieken) [inline src/vs/platform/environment/node/argvHelper.ts]: @rebornix there is still a console.log left

Comment (rebornix) [reply src/vs/platform/environment/node/argvHelper.ts]: Thanks!
