### PR TITLE
joh/innocent tiger

### LINKED ISSUE #155293: Wrong use of nls-utils in `untitledTextEditorHint.ts`
* `src/vs/workbench/contrib/codeEditor/browser/untitledTextEditorHint.ts`
* there is string concatenation of nls-strings, like [this](https://github.com/microsoft/vscode/blob/ab86e0229d6b4d0cb49cfd6747c92cafcd2bd4af/src/vs/workbench/contrib/codeEditor/browser/untitledTextEditorHint.ts#L134-L141) and much more
* This is usually wrong because it assumes that all languages use similar sequences. The `localize`-function support replacements for cases like this and in this specific case we might be better off using a markdown string with command-links

/cc @isidorn who original did this: please speak up if there is more code like this

### PR DESCRIPTION
**Pull request by jrieken**
This is the first cut for https://github.com/microsoft/vscode/issues/145929, a bunch of debt/refactoring works, and small tweaks to surround-with

- surround with code action needs non-empty selection, uses active end of selection
- no hidden snippets as code action
- add concept of top level snippet and allow to get snippets without language filter
- make snippet-contribution a proper contrib-file, remove local registration into contrib-file, move command into their own folder, have a command to populate a file from a top-level snippet
- tweak label
- add "start with snippet" to empty editor text, change things to use formatted text renderer (fixes https://github.com/microsoft/vscode/issues/155293)

### CODE REVIEW

File: src/vs/workbench/contrib/codeEditor/browser/untitledTextEditorHint.ts [hunk 1]
```diff
@@ -107,59 +108,56 @@ class UntitledTextEditorHintContentWidget implements IContentWidget {
...
-			this.domNode.appendChild(dontShow);
+			const hintElement = renderFormattedText(hintMsg, {
+				actionHandler: hintHandler,
+				renderCodeSegments: false,
+			});
+			this.domNode.append(hintElement);
+
+			// ugly way to associate keybindings...
+			const keybindingsLookup = [ChangeLanguageAction.ID, SelectSnippetForEmptyFile.Id, 'welcome.showNewFileEntries'];
+			for (const anchor of hintElement.querySelectorAll('A')) {
```
Comment (connor4312) [inline src/vs/workbench/contrib/codeEditor/browser/untitledTextEditorHint.ts:140]: `getElementsByTagName` is slightly faster

**Review by connor4312 — APPROVED** [review]
