### PR TITLE
Fix image preview after image update

### LINKED ISSUE #227447: mouse zoomer in the picture preview window stops working after the file is externally modified
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2
- OS Version: Windows 10 professional 22H2

Steps to Reproduce:

1. preview an image(title font is italic)
2. modify the image(e.g. regenerate the same-name picture by an executable program)
3. then the mouse zoomer won't work while left-click or right-click doesn't get response

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #227447

### CODE REVIEW

File: extensions/media-preview/src/imagePreview/index.ts [hunk 1]
```diff
@@ -157,6 +155,10 @@ class ImagePreview extends MediaPreview {
 			this.zoomStatusBarEntry.hide(this);
 		}
 	}
+	protected override async render(): Promise<void> {
+		await super.render();
+		this.webviewEditor.webview.postMessage({ type: 'setActive', value: this.webviewEditor.active });
```
Comment (Tyriar) [inline extensions/media-preview/src/imagePreview/index.ts:160]: Could stick an `onDidRender` event on `MediaPreview` to save the override?

**Review by Tyriar — APPROVED** [review]
