### PR TITLE
Fix focus issue when entering/exiting Zen Mode

### LINKED ISSUE #244180: Entering Zen Mode removes focus from the active Text Editor?
1. Zen mode disabled
2. Toggle Zen Mode `workbench.action.toggleZenMode`
3. Focus is moved somewhere (requires to press <kbd>Tab</kbd> multiple times to return it to the editor)

Commit: 90dde06fb64726923ebef8121bd63836529b7d8b
OS: Windows_NT x64 10.0.26100

### PR DESCRIPTION
**Pull request by benibenj**
```Copilot Generated Description:``` Address the focus loss issue when toggling Zen Mode by restoring focus to the previously active part or defaulting to the editor if the part is not visible.

Fixes microsoft/vscode#244180

### CODE REVIEW

**Review by lszomoru — APPROVED** [review]

File: src/vs/workbench/browser/layout.ts [hunk 1]
```diff
@@ -1484,6 +1494,17 @@ export abstract class Layout extends Disposable implements IWorkbenchLayoutServi
 			this.hostService.toggleFullScreen(mainWindow);
 		}
 
+		// restore focus if part is still visible, otherwise fallback to editor
```
Comment (bpasero) [inline src/vs/workbench/browser/layout.ts:1497]: I think it would be safer to store the window and the focused part together, because maybe they become different here?
