### PR TITLE
mainThreadLangFeat isDisposed check

### LINKED ISSUE #196949: TextModelPart is disposed!
```javascript
Error: TextModelPart is disposed!
at d.g in src/vs/editor/common/model/textModelPart.ts:17:10
at d.getWordAtPosition in src/vs/editor/common/model/tokenizationTextModelPart.ts:208:8
at W.getWordAtPosition in src/vs/editor/common/model/textModel.ts:1964:42
at T.D in src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts:536:21
at T.F in src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts:619:22
at T.C in src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts:528:8
at u.value in src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts:302:9
at f.y in src/vs/base/common/event.ts:1140:13
at f.z in src/vs/base/common/event.ts:1151:9
at f.fire in src/vs/base/common/event.ts:1175:9
at u.value in src/vs/editor/browser/widget/codeEditorWidget.ts:1714:38
at f.y in src/vs/base/common/event.ts:1140:13
at f.fire in src/vs/base/common/event.ts:1171:9
at I.s in src/vs/editor/common/viewModelEventDispatcher.ts:64:18
at I.endEmitViewEvents in src/vs/editor/common/viewModelEventDispatcher.ts:109:8
at p.S in src/vs/editor/common/viewModel/viewModelImpl.ts:1092:26
at p.setCursorStates in src/vs/editor/common/viewModel/viewModelImpl.ts:987:15
at Q.runCoreEditorCommand in src/vs/editor/browser/coreCommands.ts:1639:14
at L.n in src/vs/editor/browser/view/viewController.ts:257:37
at L.dispatchMouse in src/vs/editor/browser/view/viewController.ts:177:12
at i.G in src/vs/editor/browser/controller/mouseHandler.ts:610:24
at i.start in src/vs/editor/browser/controller/mouseHandler.ts:485:8
at v.G in src/vs/editor/browser/controller/mouseHandler.ts:327:29
at <anonymous> in src/vs/editor/browser/controller/mouseHandler.ts:130:83
at callback in src/vs/editor/browser/editorDom.ts:165:4
```
[Go to Errors Site](https://errors.code.visualstudio.com/card?ch=35419fc016b8d3d5dbc59aa11a0be957b0897309&bH=188c6754-b59f-53c3-ec65-0fe10f17b352)

### PR DESCRIPTION
**Pull request by Yoyokrazy**
Fixes: #196949

### CODE REVIEW

**Review by amunger — APPROVED** [review]

File: src/vs/workbench/api/browser/mainThreadLanguageFeatures.ts [hunk 1]
```diff
@@ -302,6 +302,15 @@ export class MainThreadLanguageFeatures extends Disposable implements MainThread
 			}),
 			this._languageFeaturesService.multiDocumentHighlightProvider.register(selector, <languages.MultiDocumentHighlightProvider>{
 				provideMultiDocumentHighlights: (model: ITextModel, position: EditorPosition, otherModels: ITextModel[], token: CancellationToken): Promise<Map<URI, languages.DocumentHighlight[]>> => {
+					if (model.isDisposed()) {
```
Comment (jrieken) [inline src/vs/workbench/api/browser/mainThreadLanguageFeatures.ts:305]: @Yoyokrazy I understand the check on line330 but this should never happen or did you really encounter that? It would be an issue with how we invoke the provider and the right fix wouldn't be here but in the invocation logic because nothing done here helps the monaco editor nor internal API users

Comment (amunger) [reply src/vs/workbench/api/browser/mainThreadLanguageFeatures.ts:305]: https://github.com/microsoft/vscode/pull/197583

Comment (Yoyokrazy) [reply src/vs/workbench/api/browser/mainThreadLanguageFeatures.ts:305]: Looked this over, approved since it looks like Aaron's machine wasn't hitting the error anymore. Continuing to keep an eye on error telemetry to see if there are any other odd cases that arise.
