### PR TITLE
Enable nearest Quick Fix by default and settings fix

### LINKED ISSUE #194581: New setting should be "Quick Fixes" not "QuickFixes"
- VS Code Version: 1.83 Insiders
- OS Version: Windows 11

The friendly Settings editor name for `editor.codeActionWidget.includeNearbyQuickfixes` should be "Editor > Code Action Widget: Include Nearby Quick Fixes" not "Quickfixes".

Description should also be "...nearest Quick Fix within a line..." to make other mentions of Quick Fix.

image

### PR DESCRIPTION
**Pull request by justschen**
fixes https://github.com/microsoft/vscode/issues/194581 and turns on the new quick fix feature by default.

### CODE REVIEW

**Review by Tyriar — APPROVED** [review]

File: src/vs/editor/contrib/codeAction/browser/codeActionContributions.ts [hunk 1]
```diff
@@ -40,8 +40,8 @@ Registry.as<IConfigurationRegistry>(Extensions.Configuration).registerConfigurat
 		'editor.codeActionWidget.includeNearbyQuickfixes': {
```
Comment (gregvanl) [inline src/vs/editor/contrib/codeAction/browser/codeActionContributions.ts:40]: Shouldn't the setting name casing also be changed to be `includeNearbyQuickFixes`?
I think that will fix the spacing and casing in the Settings editor

Comment (justschen) [reply src/vs/editor/contrib/codeAction/browser/codeActionContributions.ts:40]: good catch - i thought i had changed that but must have reverted it at some point while i was pushing
