### PR TITLE
fix regression on open cell output in editor

### LINKED ISSUE #245667: error when open notebook cell output in a new tag text editor
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  x64 1.99.0
- OS Version: 

Steps to Reproduce:
1.  run long content print in notebook cell --> Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...
2.  click "text editor."

new tag shows "The editor could not be opened due to an unexpected error. Please consult the log for more details." and with a "try again" botton. 
click "try again", then a window pop out "unable to open output, invalid cell URL"

solved by downgrade to x64 1.98.2

### PR DESCRIPTION
**Pull request by eleanorjboyd**
fixes https://github.com/microsoft/vscode/issues/245667

### CODE REVIEW

File: src/vs/workbench/browser/labels.ts [hunk 1]
```diff
@@ -492,31 +492,33 @@ class ResourceLabelWidget extends IconLabel {
...
-					`${outputIndex + 1}`
-				);
-			} else if (cellIndex !== undefined && typeof label.name === 'string') {
-				label.name = localize(
-					'notebookCellOutputLabelSimple',
-					"{0} • Cell {1} • Output",
-					label.name,
-					`${cellIndex + 1}`
-				);
+			if (outputUriData?.cellFragment) {
```
Comment (eleanorjboyd) [inline src/vs/workbench/browser/labels.ts:495]: in this file the only changes are 

 adding `if (outputUriData?.cellFragment) {`
changing `if (!outputUriData?.notebook || !outputUriData.cellFragment) {` -> `if (!outputUriData?.notebook) {`

everything else is just indented so that is what the diff is showing

File: src/vs/workbench/services/notebook/common/notebookDocumentService.ts [hunk 2]
```diff
@@ -79,17 +79,18 @@ export function extractCellOutputDetails(uri: URI): { notebook: URI; openIn: str
 	const outputId = params.get('outputId') ?? undefined;
 	const parsedCell = parse(uri.with({ scheme: Schemas.vscodeNotebookCell, query: null }));
 	const outputIndex = params.get('outputIndex') ? parseInt(params.get('outputIndex') || '', 10) : undefined;
-
-	if (parsedCell?.notebook === undefined || parsedCell?.handle === undefined) {
-		throw new Error('Invalid cell URI');
-	}
+	const notebookUri = parsedCell ? parsedCell.notebook : uri.with({
```
Comment (DonJayamanne) [inline src/vs/workbench/services/notebook/common/notebookDocumentService.ts:82]: If the `parsedCell` is invalid, then doesn't this mean the cell no longer exists?
Also shouldn't we then just return `undefined `here, instead of returning something invalid by making up the details, as that could lead to other issues.
I.e. returning `undefined` instead of throwing an error might be better.

**Review by DonJayamanne — CHANGES_REQUESTED** [review]
Why not return undefined instead of returning some invalid Uri.

File: src/vs/workbench/services/notebook/common/notebookDocumentService.ts (hunk 2 above)
Comment (eleanorjboyd) [reply src/vs/workbench/services/notebook/common/notebookDocumentService.ts:82]: like @amunger said, for the old style of open output in a text editor, we don't have the cell fragment in the URI just the output ID. We then want to return the notebook but do not mind that the cell fragment doesn't exist in this instance.

**Review by DonJayamanne — APPROVED** [review]

**Comment by aeschli** [comment]
1.99.2 PR: https://github.com/microsoft/vscode/pull/246021
