### PR TITLE
Fix syncing UI state if some containers are generated and containers have been moved

### LINKED ISSUE #148363: Syncing UI State with multiple moved view containers will break
Issue Type: <b>Bug</b>

Repro using Profiles Feature
1. Create a new user data dir and launch VS Code.
2. Move timeline to its own container in the activity bar
3. Move search container to secondary side bar
4. Export the profile

5. Create a new user data dir and launch VS Code.
6. Import the profile

:bug: => the timeline container will not be created and timeline will remain in the explorer view

cc @sandy081 

VS Code version: Code - Insiders 1.67.0-insider (410fe0fc7890ef563830bb86cbcd763995bfc65f, 2022-04-27T05:15:39.871Z)
OS version: Windows_NT x64 10.0.22593
Restricted Mode: No

### PR DESCRIPTION
**Pull request by sbatten**
skip writing to disk cache when a storage write contains container moves
precisely this matters if some of the containers are generated as a
result of view movement

This PR fixes #148363

### CODE REVIEW

File: src/vs/workbench/services/views/browser/viewDescriptorService.ts [hunk 1]
```diff
@@ -608,7 +616,7 @@ export class ViewDescriptorService extends Disposable implements IViewDescriptor
 
 		// Execute View Container Movement
 		for (const [container, location] of viewContainersToMove) {
-			this.moveViewContainerToLocation(container, location);
+			this.doMoveViewContainerToLocation(container, location, undefined, true);
```
Comment (sandy081) [inline src/vs/workbench/services/views/browser/viewDescriptorService.ts:619]: Shall we follow the same pattern while moving views here -

https://github.com/microsoft/vscode/blob/51895f6397ebfa712ed133f9670d7c79e8f95599/src/vs/workbench/services/views/browser/viewDescriptorService.ts#L588

**Comment by sandy081** [comment]
Change looks good to me.

**Review by sandy081 — APPROVED** [review]

File: src/vs/workbench/services/views/browser/viewDescriptorService.ts (hunk 1 above)
Comment (sandy081) [reply src/vs/workbench/services/views/browser/viewDescriptorService.ts:619]: If you agree, you can change this for next milestone as debt
