### PR TITLE
Action Widget won't show label for edits in hover when no edits are available

### LINKED ISSUE #175008: Code action command with kind `CodeActionKind.QuickFix` and no edits has tooltip with preview option
VS Code Version: 1.74.0 (user setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Steps to Reproduce:**

1. Create a code action command with `CodeActionKind` set to `QuickFix` and no edits.
2. Display the command via light blub and hover over the command to display tooltip. The tooltip text has the preview option "Ctrl+Enter to preview".
3. Executing the command with either "Enter to apply" or "Ctrl+Enter to preview" results in the same behavior.
image

Example shown is from [C++ extension](https://github.com/Microsoft/vscode-cpptools)

**Expected behavior:**
Only code action commands with edits should offer the preview option.

### PR DESCRIPTION
**Pull request by justschen**
Fixes: https://github.com/microsoft/vscode/issues/175008

### CODE REVIEW

File: src/vs/platform/actionWidget/browser/actionList.ts [hunk 1]
```diff
@@ -24,6 +24,7 @@ export const previewSelectedActionCommand = 'previewSelectedCodeAction';
 export interface IActionListDelegate<T> {
 	onHide(didCancel?: boolean): void;
 	onSelect(action: T, preview?: boolean): void;
+	onFocus(action: T): Promise<boolean> | undefined;
```
Comment (Tyriar) [inline src/vs/platform/actionWidget/browser/actionList.ts:27]: It's not clear what the return here does, jsdoc would be nice on the interface as a minimum but it seems a little weird for a focus event to return a boolean. Should this be a named object instead? `Promise<{ theThing: boolean }>`?

Also should onFocus be optional as the terminal doesn't need to implement it?

**Comment by justschen** [comment]
tagging @mattbierner as well

**Comment by Tyriar** [comment]
@justschen @mjbvz is the one you're after

File: src/vs/editor/contrib/codeAction/browser/codeActionController.ts [hunk 2]
```diff
@@ -251,6 +252,10 @@ export class CodeActionController extends Disposable implements IEditorContribut
 			},
 			onHide: () => {
 				this._editor?.focus();
+			},
+			onFocus: async (action: CodeActionItem) => {
+				await action.resolve(CancellationToken.None);
```
Comment (mjbvz) [inline src/vs/editor/contrib/codeAction/browser/codeActionController.ts:257]: Can we cancel this when the code action widget hides, either because the user dismissed it or because they selected another action

Also just double check that hovering multiple times only results in a single `resolve` for a code action that takes a long time to resolve

File: src/vs/platform/actionWidget/browser/actionList.ts [hunk 3]
```diff
@@ -302,7 +303,23 @@ export class ActionList<T> extends Disposable {
...
+
+		const element = e.element;
+		if (element) {
+			if (element.item && this.focusCondition(element)) {
+				if (this._delegate.onFocus) {
+					const result = await this._delegate.onFocus(element.item);
+					element.canPreview = result.canPreview;
+				}
+				if (e.index) {
+					this._list.splice(e.index, 1, [element]);
```
Comment (mjbvz) [inline src/vs/platform/actionWidget/browser/actionList.ts:316]: Do you need both the `splice` and the call to `rerender`? Or is `rerender` enough

**Review by mjbvz — APPROVED** [review]
