### PR TITLE
Git clone fix to use basename

### LINKED ISSUE #59544: Git: Clone with network drive
- VSCode Version: 1.27.2
- OS Version: Windows 10

Steps to Reproduce:

1. Have a git repo on a network drive.
2. Ctrl+Shift+P > Git: Clone and hit enter
3. Paste the URL of the repo on the network drive. Hit enter
4. Select the folder for the repo location and click Select Repository Location.
5. Receive a 'Git fatal: could not create leading directories of...'

Does this issue occur when all extensions are disabled?: Yes

I'm not sure if this is working as designed or not, but I guess it's relative obvious as to what is going on.
I know it says URL, but I was hoping the integrated commands should work if the equivalent terminal commands do.

### PR DESCRIPTION
**Pull request by OneThatWalks**
Fixes #59544 
leverage path to get basename regardless of the string url parameter.

Fix for network drives as relative paths, and will also work with real URI's.

### CODE REVIEW

File: extensions/git/src/git.ts [hunk 1]
```diff
@@ -334,7 +334,7 @@ export class Git {
 	}
 
 	async clone(url: string, parentPath: string, cancellationToken?: CancellationToken): Promise<string> {
-		let baseFolderName = decodeURI(url).replace(/^.*\//, '').replace(/\.git$/, '') || 'repository';
+		let baseFolderName = path.win32.basename(decodeURI(url), '.git') || 'repository';
```
Comment (joaomoreno) [inline extensions/git/src/git.ts]: This won't work for URLs with forward slashes (the most common use case).

How about instead of `.replace(/^.*\//, '')` we do `.replace(/^.*[\/\\]/, '')`?

**Review by joaomoreno — CHANGES_REQUESTED** [review]

File: extensions/git/src/git.ts (hunk 1 above)
Comment (OneThatWalks) [reply extensions/git/src/git.ts]: I'll run some test cases on this, thanks!

Comment (OneThatWalks) [reply extensions/git/src/git.ts]: @joaomoreno this may be a newbie issue on the project.  I've looked through issues in the past to try and resolve this as well to no avail.  When I run the 'Debug: Git Unit Tests' launch configuration I get a "Cannot find module 'vscode'".  I can't seem to run the mocha tests for the git extension.  I was wanting to add tests to this pr if possible.

Anyways, both your Regex and the path.win32.basename seem to work fine.  I tried these paths against both fixes.  The baseFolderName just needs to resolve the name of the directory to clone the repo into.
```
https://foo/bar.git <-- resolves as 'bar'
T:\__SharedAssets\Assets_Houdini_Dev\houdini16.5\python2.7libs <-- resolves as 'python2.7libs'
/home/bob.git <-- resolves as 'bob'
```
Let me know if there is a path I may not have addressed, I can commit the regex update with tests if I can resolve that issue above.

Comment (joaomoreno) [reply extensions/git/src/git.ts]: The test suite might be broken now. Just push the change, we´ll take it.

Comment (OneThatWalks) [reply extensions/git/src/git.ts]: It is pushed, thanks João!

**Comment by joaomoreno** [comment]
Thanks! 🍻
