### PR TITLE
Fix drag and dropping of editors for webviews

### LINKED ISSUE #25854: Can't drag Markdown preview to start a new editor group
- VSCode Version: 1.12 Insiders
- OS Version: Windows 7, 10

Steps to Reproduce:

1. With a single editor group, open a Markdown file, then Markdown: Open Preview (Ctrl+Shift+V)
2. Now try to drag the markdown preview to the side to start a new editor group

The drop is blocked.

If you select another file and then try to drag the markdown preview with only the tabbed heading, it works.

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #25854

This change does the following:

- Have the webview editor create an `EditorDropTarget`. This is required because the webview itself is not part of the normal editor dom (it exists as a top level node in the workbench so that we never reparent it). This means that the standard `EditorDropTarget` does not work.

- Make webviews set `pointer-events: none` while a drag is happening. When a drag happens on Electron's webviews or a normal iframe, no  drag and drop events seem to get generated. The fix is to set `pointer-events: none` while the drag is happening. But it's also difficult to detect when the drag is happening because the  `EditorDropTargets` class eats the drop event itself. The only reliable seeming way I could find to determine when a drag starts and ends is looking at global events on the window.

This workaround is pretty ugly. Unfortunately I haven't been able to find a better way to do this

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
@mjbvz even though maybe you need to use hacks, the result is sweet 👍 

My only concern with the approach is how you depend on editor interna to get the drop target to show. Instead, I would make a method on `IEditorGroupsService` to draw this target if a component needs it. Since this is an internal workbench service anyways, I see no harm in having it.

**Comment by mjbvz** [comment]
@bpasero Thanks for the feedback and good suggestion. I had to add the new method on the `EditorPart` class instead of on on the `IEditorGroupsService` interface since we use the `HTMLElement` type

File: src/vs/workbench/browser/parts/editor/editorPart.ts [hunk 1]
```diff
@@ -1046,6 +1046,10 @@ export class EditorPart extends Part implements IEditorGroupsService, IEditorGro
 			type: Parts.EDITOR_PART
 		};
 	}
+
+	createDropTargets(container: HTMLElement, delegate: EditorDropTargetDelegate): IDisposable {
```
Comment (bpasero) [inline src/vs/workbench/browser/parts/editor/editorPart.ts]: @mjbvz I use folding in that file and would prefer if this new method could move up below `private assertGroupView`

Comment (bpasero) [inline src/vs/workbench/browser/parts/editor/editorPart.ts]: @mjbvz maybe a better name would be `createEditorDropTarget`

File: src/vs/workbench/contrib/webview/browser/webviewEditor.ts [hunk 2]
```diff
@@ -178,8 +179,33 @@ export class WebviewEditor extends BaseEditor {
 			this._content.setAttribute('aria-flowto', input.webview.container.id);
 		}
 
+		this._webviewVisibleDisposables.clear();
+
+		// Webviews are not part of the normal editor dom, so we have to register our own drag and drop handler on them.
+		this._webviewVisibleDisposables.add((this._editorGroupsService as EditorPart).createDropTargets(input.webview.container, {
```
Comment (bpasero) [inline src/vs/workbench/contrib/webview/browser/webviewEditor.ts]: @mjbvz I think one step further is to make this new method available from `IEditorGroupsService` to prevent this ugly cast.

**Review by bpasero — APPROVED** [review]
@mjbvz after you addressed my minor feeback I think this can be merged

File: src/vs/workbench/contrib/webview/browser/webviewEditor.ts (hunk 2 above)
Comment (mjbvz) [reply src/vs/workbench/contrib/webview/browser/webviewEditor.ts]: Not sure if this is possible. `IEditorGroupsService` is in common so it can't reference `HTMLElement`. I've replaced the cast with an instanceof check which should be safer

Comment (bpasero) [reply src/vs/workbench/contrib/webview/browser/webviewEditor.ts]: I filed https://github.com/microsoft/vscode/issues/82968 to follow up.
