### PR TITLE
don't try to refresh cwd for extension/feature terminals

### LINKED ISSUE #144085: refreshProperty is not suppported in TestOutputProcesses. property: cwd
```javascript
Error: refreshProperty is not suppported in TestOutputProcesses. property: cwd
at p.refreshProperty in src/vs/workbench/contrib/testing/browser/testingOutputTerminalService.ts:237:9
at R.refreshProperty in src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts:586:24
at _i.refreshProperty in src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1978:31
at async _i._updateProcessCwd in src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1547:15
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=f80445acd5a3dadef24aa209168452a3d97cc326&bH=bd1e421b-9e8b-1f98-f70d-c1d603f4fddf)

### LINKED ISSUE #144202: cwd is not a string
```javascript
Error: cwd is not a string
at _i._updateProcessCwd in src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1549:10
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=f80445acd5a3dadef24aa209168452a3d97cc326&bH=c0d09d8d-181d-676a-12a8-89aea8408f54)

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #144202
fixes #144085

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 1]
```diff
@@ -1737,7 +1737,7 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 
 	@debounce(2000)
 	private async _updateProcessCwd(): Promise<void> {
-		if (this._isDisposed) {
+		if (this._isDisposed || this.shellLaunchConfig.isExtensionOwnedTerminal || this.shellLaunchConfig.isFeatureTerminal) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1740]: I think the right check here is actually `this.shellLaunchConfig.customPtyImplementation` since we want cwd to be updated on task/debug/extension owned/etc. terminals.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1740]: It's not getting updated currently for those, for example:

https://github.com/microsoft/vscode/blob/7f2580fa2ee290d1a87bf8ec0789f1bc2b7990f2/src/vs/workbench/contrib/testing/browser/testingOutputTerminalService.ts#L227-L238

or this
https://github.com/microsoft/vscode/blob/6b0442b3152cf4c3144be945bb295163946f4284/src/vs/workbench/api/common/extHostTerminalService.ts#L262-L269

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts]: `customPtyImplementation` should be set for both of them, One to this:

https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/workbench/contrib/terminal/browser/terminalProcessExtHostProxy.ts#L12

Other to this:

https://github.com/microsoft/vscode/blob/7f2580fa2ee290d1a87bf8ec0789f1bc2b7990f2/src/vs/workbench/contrib/testing/browser/testingOutputTerminalService.ts#L159

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts]: Keeping isFeatureTerminal/isExtensionTerminal means no cwd updating which means no fallback mechanism to fetch the cwd if shell integration is disabled for tasks/debug/extension owned terminals.

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts]: Okay thanks I see. I didn't realize a terminal could simultaneously have `isFeatureTerminal`/`isExtensionOwnedTerminal` and `isCustomPtyImplementation`, but that makes sense

**Review by Tyriar — APPROVED** [review]
