### PR TITLE
views: support auxiliary bar in OpenViewContainerAction

### LINKED ISSUE #169907: Testing menu item broken, missing from activity bar
Type: <b>Bug</b>

At some point recently the "view" -> "testing" menu stopped opening the testing view. The menu item is present but clicking it has no observable effect. Additionally, the option is no longer available in the activity bar on the left. Note that it's not simply hidden. It's also missing from the context menu to show / hide items as well. This was working up until a few days ago.

What does work is the command pallette. I can see from the logs that the extension is loaded, and by typing "testing" into the command pallette, I can still open the view, and from there on it functions normally.

VS Code version: Code 1.74.2 (Universal) (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:26:09.430Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id c4df81d1-111d-4c6e-9fb3-be55d46a3622|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
aws-toolkit-vscode|ama|1.60.0
better-tests|and|0.3.1
atlascode|atl|2.10.12
emmet-jss|car|1.0.0
path-intellisense|chr|2.8.4
dart-code|Dar|3.56.0
flutter|Dar|3.56.0
vscode-markdownlint|Dav|0.48.1
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.3
vscode-pull-request-github|Git|0.56.0
go|gol|0.37.0
rest-client|hum|0.25.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
djlint|mon|2022.10.1
vscode-docker|ms-|1.23.3
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.266.1
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.8
cpptools-extension-pack|ms-|1.3.0
vsliveshare|ms-|1.0.5788
awesome-flutter-snippets|Nas|4.0.1
printcode|nob|3.0.0
material-icon-theme|PKi|4.23.0
gotestexplorer|pre|0.1.13
vscode-yaml|red|1.10.1
LiveServer|rit|5.7.9
pdf|tom|1.2.2
cmake|twx|0.0.17
alphabetical-sorter|ue|2.0.1
vscode-maven|vsc|0.40.2
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723

```

</details>

### PR DESCRIPTION
**Pull request by connor4312**
Fixes #169907

### CODE REVIEW

File: src/vs/workbench/browser/parts/views/viewsService.ts [hunk 1]
```diff
@@ -367,13 +367,16 @@ export class ViewsService extends Disposable implements IViewsService {
 					const viewsService = serviceAccessor.get(IViewsService);
 					const viewContainerLocation = viewDescriptorService.getViewContainerLocation(viewContainer);
 					switch (viewContainerLocation) {
-						case ViewContainerLocation.Sidebar:
-							if (!viewsService.isViewContainerVisible(viewContainer.id) || !layoutService.hasFocus(Parts.SIDEBAR_PART)) {
+						case ViewContainerLocation.AuxiliaryBar:
```
Comment (sbatten) [inline src/vs/workbench/browser/parts/views/viewsService.ts:370]: Thanks for this change @connor4312 ... Looks like this command got forgotten in the changes with the views. Your fix actually highlights another problem with this command. The title of the command is Show X or Toggle X depending on where the view container lives *at startup*. The behavior however is based on the location at execution. I'm not really sure if there is a strong reason for having this differentation so I suggest we stick to the same behavior for all locations: Show X and simplify here. @sandy081 what do you think?

Comment (sandy081) [reply src/vs/workbench/browser/parts/views/viewsService.ts:370]: @sbatten This was brought multiple times and got dropped. See the discussion here https://github.com/microsoft/vscode/issues/7540. I agree the change would be simple and consistent but not might be acceptable by all users who got used to it.

**Review by sandy081 — APPROVED** [review]

**Comment by sandy081** [comment]
Oops, My approval auto merged it and I did not see the auto merge is enabled. Sorry about it.

@sbatten Feel free to suggest any additional comments if you have.

File: src/vs/workbench/browser/parts/views/viewsService.ts (hunk 1 above)
Comment (sbatten) [reply src/vs/workbench/browser/parts/views/viewsService.ts:370]: If we don't go for consistency, we need to fix the bug where the command name doesn't reflect the behavior. And we also need to make a decision on whether the Secondary Side Bar acts more like the panel or more like the Primary Side Bar. I would say Side Bar behavior, since that's what its called and that would be my vote for all view "commands".
