### PR TITLE
don't set quick pick items every time value changes

### LINKED ISSUE #164629: Typing to filter in second level of tasks quick pick doesn't work
1. Open a folder with some npm tasks
2. Run the command "Tasks: Run Task"
3. Type `npm` and choose the npm folder
4. ✅ npm tasks are listed
5. Start typing `install`, with the idea being that the quick pick will filter so that you can just hit enter to run `install`
6. Instead of filtering, the quick pick seems to go back to the previous level.

### PR DESCRIPTION
**Pull request by meganrogge**
fix #164629

### CODE REVIEW

File: src/vs/workbench/contrib/tasks/browser/taskQuickPick.ts [hunk 1]
```diff
@@ -280,12 +280,14 @@ export class TaskQuickPick extends Disposable {
 					picker.dispose();
 					return undefined;
 				}
-				const selectedEntry = await this.doPickerSecondLevel(picker, firstLevelTask);
+				const selectedEntry = await this.doPickerSecondLevel(picker, firstLevelTask, name);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/taskQuickPick.ts:283]:
```suggestion
				const selectedEntry = await this.doPickerSecondLevel(picker, firstLevelTask);
```

File: src/vs/workbench/contrib/tasks/browser/taskQuickPick.ts [hunk 2]
```diff
@@ -281,11 +281,13 @@ export class TaskQuickPick extends Disposable {
 					return undefined;
 				}
 				const selectedEntry = await this.doPickerSecondLevel(picker, firstLevelTask);
+
+
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/taskQuickPick.ts:285]:
```suggestion
```

File: src/vs/workbench/contrib/tasks/browser/taskQuickPick.ts [hunk 3]
```diff
@@ -304,8 +304,6 @@ export class TaskQuickPick extends Disposable {
 		return;
 	}
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/taskQuickPick.ts:306]:
```suggestion



```

File: src/vs/platform/quickinput/browser/quickPickPin.ts [hunk 4]
```diff
@@ -29,10 +29,6 @@ export async function showWithPinnedItems(storageService: IStorageService, stora
 			quickPick.items = quickPick.value ? itemsWithoutPinned : itemsWithPinned;
 		}
 	});
```
Comment (meganrogge) [inline src/vs/platform/quickinput/browser/quickPickPin.ts:31]: the idea here was to not show pinned items when searching. this breaks things though. @TylerLeonhardt is there a better way to accomplish this?

Comment (TylerLeonhardt) [reply src/vs/platform/quickinput/browser/quickPickPin.ts:31]: not really... you have to setup the event listener to know when you go from no `value` to `value`... I guess one thing you could do is detect when the value goes from `""` to `"a"`, set items, then from `"a"` to `"ab"` you just no-op because you already filtered out the pinned items.

Comment (meganrogge) [reply src/vs/platform/quickinput/browser/quickPickPin.ts:31]: I think it's not worth filtering the pinned ones out given the cost (the items erroneously get reset to be the top level ones instead of the current second level ones)

Comment (TylerLeonhardt) [reply src/vs/platform/quickinput/browser/quickPickPin.ts:31]: idk I'd need to play around with it/see a gif of the change.

Are you sorting the results so the pinned ones get mixed in with the others?

Comment (meganrogge) [reply src/vs/platform/quickinput/browser/quickPickPin.ts:31]: https://user-images.githubusercontent.com/29464607/199295564-f5b06418-7c22-4165-ab64-8da2543f77de.mov

Comment (meganrogge) [reply src/vs/platform/quickinput/browser/quickPickPin.ts:31]: and here's the bug https://github.com/microsoft/vscode/issues/164629#issuecomment-1298858479

**Review by alexr00 — APPROVED** [review]
