### PR TITLE
Normalize paths when matching problems

### LINKED ISSUE #77804: Tasks only: Problems panel re-opens file if a path is not normalized
- VSCode Version: Tested with 1.36.1 and 1.37.0-insider
- OS Version: macOS 10.14.5

Steps to Reproduce:

1. Open a file `/Users/foo/dev/project/main.cpp`
2. Create a task with a problem matcher that uses absolute file locations
3. Start a task that generates an error with an unnormalized path: `/Users/foo/dev/project/output/../main.cpp:48:7: error:`
4. Click on the error in the problems pane

Expected: The cursor jumps to the position in the open editor view
Actual: A new editor is opened containing the relative part of the path. The file history contains a new entry. When using "Go to file", both file locations are offered.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by csk-ableton**
Fixes https://github.com/microsoft/vscode/issues/77804

### CODE REVIEW

File: src/vs/workbench/contrib/tasks/common/problemMatcher.ts [hunk 1]
```diff
@@ -220,6 +220,7 @@ export async function getResource(filename: string, matcher: ProblemMatcher, fil
 	if (fullPath[0] !== '/') {
 		fullPath = '/' + fullPath;
 	}
+	fullPath = normalize(fullPath);
```
Comment (diguifi) [inline src/vs/workbench/contrib/tasks/common/problemMatcher.ts]: I'm a beginner on vscode's code, could you explain to me how does this line avoids this:
>Actual: A new editor is opened containing the relative part of the path. The file history contains a new entry. When using "Go to file", both file locations are offered.

?

Comment (csk-ableton) [reply src/vs/workbench/contrib/tasks/common/problemMatcher.ts]: Without this change, two editors will be opened. One for `/Users/foo/dev/project/main.cpp` and one for `/Users/foo/dev/project/output/../main.cpp`, even though it refers to the same file. By normalizing it upfront, the seconds path will be identical to the first one.

Ideally, vscode normalizes the paths before opening an editor but that sounded like a bigger change to me.

**Review by diguifi — APPROVED** [review]

**Review by alexr00 — APPROVED** [review]
Nice bug, thank you for the fix!
