### PR TITLE
Expose adjustWhitespace to TextEditor API.

### LINKED ISSUE #63129: editor.insertSnippet() messes with indenting of the SnippetString
This is a very similar issue to #44200/#57093 but that fix appears to be only being applied to completions, but applying snippets causes the same issues.

Here's a repro:

```ts
vs.workspace.openTextDocument(vs.Uri.parse(`untitled:${os.tmpdir}/a.dart`)).then(async (document) => {

	const originalCode = `main() {
  // code indented with two spaces
}`;
	const editor = await vs.window.showTextDocument(document);
	await editor.edit((eb) => eb.insert(new vs.Position(0, 0), originalCode));

	const startOffset = originalCode.indexOf("// code indented with two spaces");
	const endOffset = originalCode.indexOf("\n}");
	const snippetString = new vs.SnippetString("// new code indented with two spaces\n  // newer code indented with two spaces");

	await editor.insertSnippet(snippetString, new vs.Range(document.positionAt(startOffset), document.positionAt(endOffset)));
});
```

This creates a doc and inserts into it the code:

```dart
main() {
  // code indented with two spaces
}
```

It then applies a snippet string that includes an additional line that is also indented by two spaces. However what you end up with is:

```dart
main() {
  // new code indented with two spaces
    // newer code indented with two spaces
}
```

The inserted line has been re-indented.

Whilst this behaviour may be useful if applying basic hard-coded strings, it's incorrect for language servers that are correctly calculating edits to leave the file indented/formatted correctly (I guess for the same reasons that left to #57093).

### PR DESCRIPTION
**Pull request by rgrunber**
- Disable adjustWhitespace in text edits with snippets so that code actions do not adjust snippet indentation by default
- Add testcase
- Fixes #63129 

Based on comments like https://github.com/microsoft/language-server-protocol/pull/1892#issuecomment-1964186341 , snippet edits should probably not be adjusting whitespace by default. For language support, once workspace edits have a property like, https://github.com/microsoft/vscode/blob/275faf6f08b7aa50843f3c18406b4d5969784e52/src/vscode-dts/vscode.d.ts#L4996-L5001 we could set the snippet insertion to respect that.

**Before**

https://github.com/user-attachments/assets/7e1c4819-e127-45f5-82e9-5bede1c26d03

**After**

https://github.com/user-attachments/assets/ae65bbcf-af10-4103-9fc4-31165aefa59f

### CODE REVIEW

**Comment by rgrunber** [comment]
@microsoft-github-policy-service agree [company="Red Hat"]

**Review by 818Nawaf — APPROVED** [review]

File: src/vscode-dts/vscode.d.ts [hunk 1]
```diff
@@ -1312,6 +1312,10 @@ declare module 'vscode' {
 			 * Add undo stop after making the edits.
 			 */
 			readonly undoStopAfter: boolean;
+			/**
+			 * Adjust the indentation of the snippet.
+			 */
+			readonly adjustWhitespace?: boolean;
```
Comment (jrieken) [inline src/vscode-dts/vscode.d.ts:1318]: In the API optional properties default to `false` and that's not the case here and also undesirable (we cannot change the existing behaviour here). We would need a name that's the other way around, I suggest `keepWhitespace` which is already used for `CompletionItem` for the same/similar purpose

Comment (jrieken) [reply src/vscode-dts/vscode.d.ts:1318]: to double-click. Only change the API name and do the conversion in the API implementation [here](https://github.com/microsoft/vscode/blob/0c7bdaaae9b654d97ee5b212bbf4b81bd871540f/src/vs/workbench/api/common/extHostTextEditor.ts#L524)

File: src/vs/workbench/contrib/bulkEdit/browser/bulkTextEdits.ts [hunk 2]
```diff
@@ -156,7 +156,7 @@ class EditorEditTask extends ModelEditTask {
 						});
 					}
 				}
-				snippetCtrl.apply(snippetEdits, { undoStopBefore: false, undoStopAfter: false });
+				snippetCtrl.apply(snippetEdits, { undoStopBefore: false, undoStopAfter: false, adjustWhitespace: false });
```
Comment (jrieken) [inline src/vs/workbench/contrib/bulkEdit/browser/bulkTextEdits.ts:159]: This seems like an unrelated and unwanted change

File: extensions/emmet/src/abbreviationActions.ts [hunk 3]
```diff
@@ -636,7 +636,7 @@ async function expandAbbreviationInRange(editor: vscode.TextEditor, expandAbbrLi
 		for (const expandAbbrInput of expandAbbrList) {
 			const expandedText = expandAbbr(expandAbbrInput);
 			if (expandedText) {
-				await editor.insertSnippet(new vscode.SnippetString(expandedText), expandAbbrInput.rangeToReplace, { undoStopBefore: false, undoStopAfter: false });
+				await editor.insertSnippet(new vscode.SnippetString(expandedText), expandAbbrInput.rangeToReplace, { undoStopBefore: false, undoStopAfter: false, adjustWhitespace: true });
```
Comment (jrieken) [inline extensions/emmet/src/abbreviationActions.ts:639]: This isn't needed when `keepWhitespace` is used as API

File: extensions/emmet/src/abbreviationActions.ts [hunk 4]
```diff
@@ -650,7 +650,7 @@ async function expandAbbreviationInRange(editor: vscode.TextEditor, expandAbbrLi
 	const expandedText = expandAbbr(anyExpandAbbrInput);
 	const allRanges = expandAbbrList.map(value => value.rangeToReplace);
 	if (expandedText) {
-		return editor.insertSnippet(new vscode.SnippetString(expandedText), allRanges);
+		return editor.insertSnippet(new vscode.SnippetString(expandedText), allRanges, { undoStopBefore: true, undoStopAfter: true, adjustWhitespace: true });
```
Comment (jrieken) [inline extensions/emmet/src/abbreviationActions.ts:653]: Same, not needed when having `keepWhitespace`

**Review by jrieken — CHANGES_REQUESTED** [review]
Thanks for this

File: src/vscode-dts/vscode.d.ts (hunk 1 above)
Comment (rgrunber) [reply src/vscode-dts/vscode.d.ts]: I have addressed this (I think). I didn't know `extHostTextEditor` ends up calling `mainThreadEditor` but that makes more sense now. So `keepWhitespace` is optional, and when undefined, we set it to `false` (current default behaviour).

File: src/vs/workbench/contrib/bulkEdit/browser/bulkTextEdits.ts (hunk 2 above)
Comment (rgrunber) [reply src/vs/workbench/contrib/bulkEdit/browser/bulkTextEdits.ts:159]: Just to explain why I added this. Yes, the main change is about adding an optional flag to `insertSnippet`, but I noticed that when a provided code action is applied, it doesn't go through the text editor `insertSnippet`. It seems to directly call the `SnippetController` here. This is what affects the actual behaviour for all extensions providing code actions. So any extension with a code action provider that includes snippets (eg. https://github.com/redhat-developer/vscode-java/issues/3686), and don't want VS Code re-adjusting indentation won't be resolved without this change. I also thought I could change the default behaviour (adjust indentation for snippets) based on comments like https://github.com/microsoft/language-server-protocol/pull/1892#issuecomment-1964186341 .

If this change to the default isn't wanted, would you support (in this PR) adding a field to `vscode.CodeAction`, `keepWhitespace`, much like is done for `vscode.CompletionItem`, and have it be honoured at https://github.com/microsoft/vscode/blob/12b060f0a812fcd7e4cabf9c65e8267f48519459/src/vs/editor/contrib/codeAction/browser/codeAction.ts#L299-L306 .

Comment (jrieken) [reply src/vs/workbench/contrib/bulkEdit/browser/bulkTextEdits.ts:159]: I understand but also here we cannot change the existing behaviour. I think this would be `keepWhitespace` for the `SnippetTextEdit` type

Comment (rgrunber) [reply src/vs/workbench/contrib/bulkEdit/browser/bulkTextEdits.ts]: Sorry for the delay. I've removed this line from the `snippetCtrl.apply(..)` call in `bulkTextEdits`. I've introduced an optional property `keepWhitespace`, for `SnippetTextEdit`. If set, it and it will end up passed down into the snippet session logic, where it will influence `adjustIndentation`. If not set, then the default behaviour wins out (indentation is adjusted).

So to summarize we have 2 ways to influence the indentation of a code action with a snippet text edit. As a separate option passed into `TextEditor.insertSnippet(..)` or as an option embedded in the `SnippetTextEdit` so that it works through the language provider.

Comment (jrieken) [reply src/vs/workbench/contrib/bulkEdit/browser/bulkTextEdits.ts]: Nice. Thanks for that!

**Review by jrieken — APPROVED** [review]

**Comment by jrieken** [comment]
Also asking @mjbvz to review because this adds new API without going the proposed api flow

**Review by mjbvz — APPROVED** [review]

**Comment by superle3** [comment]
@jrieken  https://github.com/microsoft/vscode/issues/214757 is not a duplicate of this issue.
This issue is about whitespace, while https://github.com/microsoft/vscode/issues/214757 is about snippets not merging. I tested the issue on the latest commit (25418c6a590442002093b95e8764e59c551e7712) and it still persists. Could you please reopen that issue.
