### PR TITLE
Fix some edge cases in shell integration conpty handling

### LINKED ISSUE #143894: Command decorations after starting are moving up incorrectly
Seeing this in today's build:

image

Might be related to the fix https://github.com/microsoft/vscode/issues/143798

### PR DESCRIPTION
**Pull request by Tyriar**
This starts to listen for cursor moves on the next frame to avoid listening when
the cursor is on the wrong line (if conpty renders the sequence in the wrong spot).
There is also some handling for when that handler doesn't trigger before command
finished does.

Fixes #143894

---

This fix seems pretty reliable, the only place I could break it is rarely this would happen for skipped commands:

image

Typed commands seemed to pretty much always work.

### CODE REVIEW

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 1]
```diff
@@ -108,18 +108,20 @@ export class CommandDetectionCapability implements ICommandDetectionCapability {
...
-					if (marker) {
-						this._commandMarkers.push(marker);
-					}
-				}
-			});
 			// HACK: Fire command started on the following frame on Windows to allow the cursor
 			// position to update as conpty often prints the sequence on a different line to the
 			// actual line the command started on.
 			timeout(0).then(() => {
+				if (!this._currentCommand.commandExecutedMarker) {
```
Comment (meganrogge) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:115]: if conpty does fire command started for the actual line it was started on, are there any consequences of this happening again?

I think we dispose of the placeholder decoration every time register decoration is called, which should prevent duplicates

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 2]
```diff
@@ -177,7 +179,18 @@ export class CommandDetectionCapability implements ICommandDetectionCapability {
 		// executed markers. This is done on command finished just in case command executed never
 		// happens (for example PSReadLine tab completion)
 		if (this._isWindowsPty) {
-			this._commandMarkers = this._commandMarkers.sort((a, b) => a.line - b.line);
+			if (this._commandMarkers.length === 0) {
+				// If the command start timeout doesn't happen before command finished, just use the
+				// current marker.
+				if (!this._currentCommand.commandStartMarker) {
```
Comment (meganrogge) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:185]: since the timeout is 0, when will this happen?

**Review by meganrogge — APPROVED** [review]

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts (hunk 2 above)
Comment (Tyriar) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:185]: It may happen when running a command while another is running, I don't think it does in practice currently due to event loop related things in node-pty/conpty where data but it might and could in the future.

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts (hunk 1 above)
Comment (Tyriar) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:115]: We only want to listen to cursor moves between start and executed, doing it outside that would be a waste as we wouldn't use it.
