### PR TITLE
🎁 Add `killOnServerStop` to debug configuration

### LINKED ISSUE #163124: Actions launched from a server ready action in compound launch configs don't honor the `stopAll` flag
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Create a compound launch configuration with `"stopAll": true`  where one of the configs includes `serverReadyAction`
2. Launch a debug session with this configuration
3. Press the stop button
   - **Expected:** All sessions stop
   - **Actual:** The sessions enumerated in the compound `configurations` stop, but the session launched under `serverReadyAction` does not. The user must click stop twice for all sessions to cease.

My launch config:
```json
{
  "version": "0.2.0",
  "compounds": [
    {
      "name": "Debug app",
      "configurations": ["Django", "Vite"],
      "stopAll": true
    }
  ],
  "configurations": [
    {
      "name": "Django",
      "type": "python",
      "request": "launch",
      "program": "${workspaceFolder}/manage.py",
      "args": ["runserver"],
      "django": true,
      "justMyCode": true,
      "presentation": { "hidden": true },
      "cwd": "${workspaceFolder}",
      "serverReadyAction": {
        "pattern": ".*(https?:\\/\\/\\S+:[0-9]+\\/?).*",
        "uriFormat": "%s",
        "action": "debugWithChrome"
      }
    },
    {
      "name": "Vite",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "npm",
      "runtimeArgs": ["run", "dev"],
      "presentation": { "hidden": true },
      "cwd": "${workspaceFolder}"
    }
  ]
}
```

Video demonstrating the behavior:
https://user-images.githubusercontent.com/356814/194767649-e8ce11fa-1649-414a-bb6c-1ea277f58e1d.mp4

### PR DESCRIPTION
**Pull request by babakks**
Fixes #163124

A new configuration parameter, named `killOnServerStop`, is added. When this parameter is enabled, child debug sessions will be stopped whenever the server (the parent session) stops. The default value for the parameter is `false` to keep the existing behavior unchanged.

## Verification

To verify this PR, use [babakks/vscode-verify-kill-on-server-stop](https://github.com/babakks/vscode-verify-kill-on-server-stop) which is made for this purpose. Instructions are available in the `README.md` of the repo.

### CODE REVIEW

File: extensions/debug-server-ready/src/extension.ts [hunk 1]
```diff
@@ -183,14 +191,78 @@ class ServerReadyDetector extends vscode.Disposable {
...
+		const trackerId = randomUUID();
+		const newSessionPromise = new Promise<vscode.DebugSession>(resolve => {
+			const listener = vscode.debug.onDidStartDebugSession(newSession => {
+				if (newSession.configuration.trackerId === trackerId) {
+					listener.dispose();
+					resolve(newSession);
+				}
+			});
+			this.lateDisposables.push(listener); // In case `trackerId` of interest was never caught anyhow.
+		});
```
Comment (connor4312) [inline extensions/debug-server-ready/src/extension.ts:210]: Applicable to here and below:

- The listener will be leaked if `startDebugging` returns false
- Even after the listener resolves, `lateDisposables` will keep growing indefinitely.

Maybe `lateDisposables` should be a `Set` that you can delete disposables from.

Comment (babakks) [reply extensions/debug-server-ready/src/extension.ts:210]: You're right. Will push a fix soon.

Comment (babakks) [reply extensions/debug-server-ready/src/extension.ts]: Made the changes as you suggested. the `lateDisposables` is a `Set` now. Also used `vscode.CancellationToken` for signalling whether to stop listening for events anymore.

**Review by connor4312 — DISMISSED** [review]
looks sane to me, cc @roblourens

File: extensions/debug-server-ready/src/extension.ts [hunk 2]
```diff
@@ -183,13 +191,104 @@ class ServerReadyDetector extends vscode.Disposable {
...
+
+	private startBrowserDebugSession(type: string, session: vscode.DebugSession, uri: string, trackerId?: string) {
 		return vscode.debug.startDebugging(session.workspaceFolder, {
 			type,
 			name: 'Browser Debug',
 			request: 'launch',
 			url: uri,
-			webRoot: session.configuration.serverReadyAction.webRoot || WEB_ROOT
+			webRoot: session.configuration.serverReadyAction.webRoot || WEB_ROOT,
+			trackerId,
```
Comment (roblourens) [inline extensions/debug-server-ready/src/extension.ts:235]: Please use a more unique name for this. Since it's being added to another extension's launch config, I think it should reflect where it came from and the fact that it's sort of internal, I suggest `_debugServerReadySessionId`.

Actually it's interesting that startDebugging doesn't return a DebugSession, I sort of expected it would. That would make this easier.

Comment (connor4312) [reply extensions/debug-server-ready/src/extension.ts:235]: It would indeed. But getting an API change in for that would be awkward, we'd need to duplicate the method 😕

**Comment by roblourens** [comment]
There's also a merge conflict here

File: extensions/debug-server-ready/src/extension.ts (hunk 2 above)
Comment (babakks) [reply extensions/debug-server-ready/src/extension.ts]: Done.

**Comment by babakks** [comment]
> There's also a merge conflict here

Merged with the `main`.

**Review by roblourens — APPROVED** [review]
Works great, thanks for this!
