### PR TITLE
fix terminal suggest sorting for files/folders 

### LINKED ISSUE #239012: Sorting seems to be off
Testing #238901

The folder `vscode` is shown at the bottom in the terminal whereas it shown on the top in the folder picker. I think the latter is correct.

Image

Image

### PR DESCRIPTION
**Pull request by meganrogge**
Fix #239012
Screenshot 2025-01-30 at 12 21 58 PM

### CODE REVIEW

File: src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts [hunk 1]
```diff
@@ -209,8 +209,14 @@ export class SimpleCompletionModel {
 				score = a.fileExtLow.length - b.fileExtLow.length;
 			}
 			if (score === 0 || fileExtScore(a.fileExtLow) === 0 && fileExtScore(b.fileExtLow) === 0) {
-				// both files or directories, sort alphabetically
-				score = a.completion.label.localeCompare(b.completion.label);
+			// both files or directories, sort alphabetically
```
Comment (meganrogge) [inline src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts:212]:
```suggestion
			    // both files or directories, sort alphabetically
```

File: src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts [hunk 2]
```diff
@@ -209,8 +209,14 @@ export class SimpleCompletionModel {
 				score = a.fileExtLow.length - b.fileExtLow.length;
 			}
 			if (score === 0 || fileExtScore(a.fileExtLow) === 0 && fileExtScore(b.fileExtLow) === 0) {
-				// both files or directories, sort alphabetically
-				score = a.completion.label.localeCompare(b.completion.label);
+			    // both files or directories, sort alphabetically
```
Comment (meganrogge) [inline src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts:212]:
```suggestion
			      // both files or directories, sort alphabetically
```

File: src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts [hunk 3]
```diff
@@ -209,8 +209,14 @@ export class SimpleCompletionModel {
 				score = a.fileExtLow.length - b.fileExtLow.length;
 			}
 			if (score === 0 || fileExtScore(a.fileExtLow) === 0 && fileExtScore(b.fileExtLow) === 0) {
-				// both files or directories, sort alphabetically
-				score = a.completion.label.localeCompare(b.completion.label);
+			      // both files or directories, sort alphabetically
```
Comment (meganrogge) [inline src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts:212]:
```suggestion
			        // both files or directories, sort alphabetically
```

File: src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts [hunk 4]
```diff
@@ -209,8 +209,14 @@ export class SimpleCompletionModel {
 				score = a.fileExtLow.length - b.fileExtLow.length;
 			}
 			if (score === 0 || fileExtScore(a.fileExtLow) === 0 && fileExtScore(b.fileExtLow) === 0) {
-				// both files or directories, sort alphabetically
-				score = a.completion.label.localeCompare(b.completion.label);
+			        // both files or directories, sort alphabetically
```
Comment (meganrogge) [inline src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts:212]:
```suggestion
			        // Both files or directories
```

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts [hunk 5]
```diff
@@ -209,8 +209,14 @@ export class SimpleCompletionModel {
...
 			}
 			if (score === 0 || fileExtScore(a.fileExtLow) === 0 && fileExtScore(b.fileExtLow) === 0) {
-				// both files or directories, sort alphabetically
-				score = a.completion.label.localeCompare(b.completion.label);
+			        // Both files or directories
+				// Sort by label length ascending
+				score = a.completion.label.length - b.completion.label.length;
+				if (score !== 0) {
+					return score;
+				}
```
[the remark this answers is not in the document]
Comment (meganrogge) [reply src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts]: fixed 
Screenshot 2025-01-30 at 10 31 16 AM

File: src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts [hunk 6]
```diff
@@ -208,10 +208,33 @@ export class SimpleCompletionModel {
 				// Then by file extension length ascending
 				score = a.fileExtLow.length - b.fileExtLow.length;
 			}
```
Comment (Tyriar) [inline src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts:210]: Early exit for already completed ones to simplify flow of function:

```ts
			if (score !== 0) {
				return score;
			}
```

This could sit inside the `if (!isArg...)` block, then remove the `score === 0` case from the if below.

File: src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts [hunk 7]
```diff
@@ -208,10 +208,33 @@ export class SimpleCompletionModel {
...
-			if (score === 0 || fileExtScore(a.fileExtLow) === 0 && fileExtScore(b.fileExtLow) === 0) {
-				// both files or directories, sort alphabetically
```
Comment (Tyriar) [inline src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts:212]: I probably wrote this comment, but I don't think this is actually true and non-files can enter this block.

File: src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts [hunk 8]
```diff
@@ -208,10 +208,33 @@ export class SimpleCompletionModel {
...
-				score = a.completion.label.localeCompare(b.completion.label);
+			if (score === 0 || (fileExtScore(a.fileExtLow) === 0 && fileExtScore(b.fileExtLow) === 0)) {
```
Comment (Tyriar) [inline src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts:211]: Should this check `a`/`b` `.isFile`/`.isDirectory` instead? I can't remember why `fileExtScore` is used here.

File: src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts [hunk 9]
```diff
@@ -208,10 +208,33 @@ export class SimpleCompletionModel {
...
+				// Both are files or directories
+
+				// Remove trailing slashes for comparison so that /dir/vscode/ is considered a prefix of /dir/vscode-copilot/
+				const labelA = a.completion.label.replace(/\/$/, '');
+				const labelB = b.completion.label.replace(/\/$/, '');
```
Comment (Tyriar) [inline src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts:216]: This is a good case to add a precomputed value to the completion, like `labelLowExcludeTrailingSep`

File: src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts [hunk 10]
```diff
@@ -208,10 +208,33 @@ export class SimpleCompletionModel {
...
+
+				// Count depth of path (number of '/' occurrences)
+				const depthA = (labelA.match(/\//g) || []).length;
+				const depthB = (labelB.match(/\//g) || []).length;
```
Comment (Tyriar) [inline src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts:220]: We can do this without generating an array via `count` from strings.ts. Will also make it more readable.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts (hunk 8 above)
Comment (meganrogge) [reply src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts]: I think this case is always true on mac - only true for directories on windows?

Comment (meganrogge) [reply src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts]: Perhaps this condition should just be removed?

File: src/vs/workbench/services/suggest/browser/simpleCompletionItem.ts [hunk 11]
```diff
@@ -73,6 +74,7 @@ export class SimpleCompletionItem {
 		// ensure lower-variants (perf)
 		this.labelLow = this.completion.label.toLowerCase();
 		this.labelLowExcludeFileExt = this.labelLow;
+		this.labelLowExcludeTrailingFileSep = this.labelLowExcludeFileExt.replace(/\/$/, '');
 		if (completion.isFile) {
 			if (isWindows) {
 				this.labelLow = this.labelLow.replaceAll('/', '\\');
```
Comment (Tyriar) [inline src/vs/workbench/services/suggest/browser/simpleCompletionItem.ts:80]: This actually won't work properly on Windows. as it could contain `/` or `\` Let's also take `isDirectory` into account for this.

Comment (Tyriar) [reply src/vs/workbench/services/suggest/browser/simpleCompletionItem.ts:80]: For `isWindows` we could normalize the separator here so we only need to check `count(, /)`?

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts (hunk 8 above)
Comment (Tyriar) [reply src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts]: I think it depends on how we want file/dir completion sorting should interact with other completions. This is what we do in insiders:

image

Scores at 18, 18, 18, 18, 1, -2, -2, -2, -2, -2, -8, ...

Seems like the files should be above VSSVC.exe (score 1) in this case.

File: src/vs/workbench/services/suggest/browser/simpleCompletionItem.ts (hunk 11 above)
Comment (meganrogge) [reply src/vs/workbench/services/suggest/browser/simpleCompletionItem.ts]: I'm wondering if it's weird to even have this set for files, given it'll be the same as `labelLow`.

File: src/vs/workbench/services/suggest/browser/simpleCompletionItem.ts [hunk 12]
```diff
@@ -75,13 +76,17 @@ export class SimpleCompletionItem {
 		this.labelLowExcludeFileExt = this.labelLow;
 		if (completion.isFile) {
 			if (isWindows) {
+				// Normalize for windows
```
Comment (meganrogge) [inline src/vs/workbench/services/suggest/browser/simpleCompletionItem.ts:79]:
```suggestion
```

**Review by Tyriar — APPROVED** [review]

**Review by legomushroom — APPROVED** [review]
LGTM 🚀
