### PR TITLE
Fix inlay hint location links problem

### LINKED ISSUE #167564: Inlay hint location links goto definition goes to the nearest symbol
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.73.1
- OS Version: Pop!_OS 22.04 LTS

Steps to Reproduce:

Recording 2022-11-29 at 19 41 44

It should use the location data which the language server provides if I ctrl+click on the linked part, but instead it runs go to definition for the nearest token (which is colored in addition to the inlay hint part which is under cursor).

### PR DESCRIPTION
**Pull request by hkalbasi**
fix #167564 

The changes in `goToDefinitionAtPosition.ts` disable decoration of the nearest token on hover with Ctrl, and the other changes fix the target when clicking. I didn't find out how to add a test for it but I can do that with some mentoring if needed.

### CODE REVIEW

File: src/vs/editor/contrib/gotoSymbol/browser/link/goToDefinitionAtPosition.ts [hunk 1]
```diff
@@ -117,6 +119,14 @@ export class GotoDefinitionAtPositionEditorContribution implements IEditorContri
 			return;
 		}
 
+		// check if mouse event is on an inlay hint
+		if (mouseEvent.target.type === MouseTargetType.CONTENT_TEXT) {
```
Comment (jrieken) [inline src/vs/editor/contrib/gotoSymbol/browser/link/goToDefinitionAtPosition.ts:123]: This brings in a dependency between inlay hints and gotoSymbol and that's not really wanted. I'd say it's sufficient to check on L116 that mouse if over `CONTEXT_TEXT`, e.g if it's not don't start definition from mouse

File: src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts [hunk 2]
```diff
@@ -249,6 +249,33 @@ export abstract class SymbolNavigationAction extends EditorAction2 {
 	}
 }
 
+export class KnownTargetNavigationAction extends SymbolNavigationAction {
```
Comment (jrieken) [inline src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts:252]: Not really sure why this was added. Please explain or remove to keep the PR minimal and focused on the actual issue

**Review by jrieken — CHANGES_REQUESTED** [review]
Thanks so far. Left a suggestion to avoid a dependency between inlay and goto contributions

File: src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts (hunk 2 above)
Comment (HKalbasi) [reply src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts:252]: Previously, `DefinitionAction` was used for inlay hints, and `DefinitionAction` always goes to the definition of token under cursor. This one is similar to `DefinitionAction` and other classes in this category, but it gets the target of navigation in its constructor. It is used instead of `DefinitionAction` in `inlayHintsLocation.ts`.

File: src/vs/editor/contrib/gotoSymbol/browser/link/goToDefinitionAtPosition.ts (hunk 1 above)
Comment (HKalbasi) [reply src/vs/editor/contrib/gotoSymbol/browser/link/goToDefinitionAtPosition.ts:123]: I don't think that works, since both normal text and inlay hint has `CONTEXT_TEXT`. But we probably can remove the `options?.attachedData instanceof RenderedInlayHintLabelPart` part and disable definition for all forms of `ModelDecorationInjectedTextOptions`. Would it be fine in this way?

Comment (HKalbasi) [reply src/vs/editor/contrib/gotoSymbol/browser/link/goToDefinitionAtPosition.ts:123]: I don't think that works, since both normal text and inlay hint has `CONTEXT_TEXT`. But we probably can remove the `options?.attachedData instanceof RenderedInlayHintLabelPart` part and disable definition for all forms of `ModelDecorationInjectedTextOptions`. Would it be fine in this way?

File: src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts (hunk 2 above)
Comment (jrieken) [reply src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts:252]: > but it gets the target of navigation in its constructor. It is used instead of DefinitionAction in inlayHintsLocation.ts.

Careful with that. While `InlayHintLabelPart#location` looks like (and usually is) the definition of the symbol it must not be that. The contract is to give a location at which calling go-to-def is doing the right thing. The easiest way to think about this is symbols with multiple definition locations. We don't want that to surface in the inlay hint label but still want to do the right thing. That'd why we cannot take it as result/target but only as anchor (for a result)

**Review by jrieken — CHANGES_REQUESTED** [review]

File: src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts (hunk 2 above)
Comment (HKalbasi) [reply src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts]: Thanks for explanation. I now understand why it was the way it was, and so I found out that my changes were unnecessary and a small tweak was enough to make it working. `KnownTargetNavigationAction` is now removed.

File: src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts [hunk 3]
```diff
@@ -103,7 +103,8 @@ export abstract class SymbolNavigationAction extends EditorAction2 {
 		SymbolNavigationAction._allSymbolNavigationCommands.set(opts.id, this);
 	}
 
-	override runEditorCommand(accessor: ServicesAccessor, editor: ICodeEditor, arg?: SymbolNavigationAnchor | unknown, range?: Range): Promise<void> {
+	override runEditorCommand(accessor: ServicesAccessor, editor: ICodeEditor, args: [ICodeEditor, SymbolNavigationAnchor | unknown, Range | undefined]): Promise<void> {
```
Comment (jrieken) [inline src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts:106]: I don't think this change is needed and I do believe that it will break existing callers

**Review by jrieken — CHANGES_REQUESTED** [review]

File: src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts (hunk 3 above)
Comment (HKalbasi) [reply src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts:106]: There was a mismatch between callers and this before my PR, and it was the reason it wasn't working correctly. So either the caller in `editorExtensions.ts:455` or here needs to be changed. And the caller is more generic, so I think changing here is correct. And other inherited classes of `EditorAction2` all have an `args` argument as third argument, and no more arguments:
```
src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts
106:    override runEditorCommand(accessor: ServicesAccessor, editor: ICodeEditor, args: [ICodeEditor, SymbolNavigationAnchor | unknown, Range | undefined]): Promise<void> {

src/vs/editor/contrib/folding/browser/folding.ts
529:    public override runEditorCommand(accessor: ServicesAccessor, editor: ICodeEditor, args: T): void | Promise<void> {
src/vs/editor/browser/coreCommands.ts
36:     public runEditorCommand(accessor: ServicesAccessor | null, editor: ICodeEditor, args?: Partial<T> | null): void {
1885:           public runEditorCommand(accessor: ServicesAccessor, editor: ICodeEditor, args: unknown): void {
1961:           public runEditorCommand(accessor: ServicesAccessor, editor: ICodeEditor, args: unknown): void {
2095:           public runEditorCommand(accessor: ServicesAccessor | null, editor: ICodeEditor, args: unknown): void | Promise<void> {
2110:           public runEditorCommand(accessor: ServicesAccessor | null, editor: ICodeEditor, args: unknown): void | Promise<void> {

src/vs/editor/browser/editorExtensions.ts
276:                    public runEditorCommand(accessor: ServicesAccessor, editor: ICodeEditor, args: any): void {
377:    public runEditorCommand(accessor: ServicesAccessor, editor: ICodeEditor, args: any): void | Promise<void> {

src/vs/editor/contrib/wordOperations/browser/wordOperations.ts
44:     public runEditorCommand(accessor: ServicesAccessor, editor: ICodeEditor, args: any): void {
333:    public runEditorCommand(accessor: ServicesAccessor, editor: ICodeEditor, args: any): void {

src/vs/editor/contrib/codeAction/browser/codeActionCommands.ts
210:    public runEditorCommand(_accessor: ServicesAccessor, editor: ICodeEditor, userArgs: any) {

src/vs/workbench/contrib/testing/browser/testingOutputPeek.ts
1675:   public runEditorCommand(accessor: ServicesAccessor, editor: ICodeEditor) {
1705:   public runEditorCommand(accessor: ServicesAccessor, editor: ICodeEditor) {
1723:   public runEditorCommand(accessor: ServicesAccessor, editor: ICodeEditor) {
1750:   public runEditorCommand(accessor: ServicesAccessor, editor: ICodeEditor) {
```

Comment (jrieken) [reply src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts:106]: You are right. Tho, I would fix this at the few special callers that we have. Usually these commands are invoked via the "normal command execution" but some are special: namely inlay hint and definition links. [This](https://github.com/microsoft/vscode/blob/356b57c157a39ef957bca466240711e682ccca54/src/vs/editor/contrib/gotoSymbol/browser/link/goToDefinitionAtPosition.ts#L304) and [this](https://github.com/microsoft/vscode/blob/ab1a31add4608f484d555e3c791f03321a4dda5f/src/vs/editor/contrib/inlayHints/browser/inlayHintsLocations.ts#L108) invocation should be changed so that the editor isn't passed anymore

**Review by jrieken — COMMENTED** [review]
I pushed some changes as described and I am going ahead to merge this PR. Thanks!

**Review by jrieken — APPROVED** [review]

**Review by lszomoru — APPROVED** [review]

**Comment by HKalbasi** [comment]
@jrieken the problem appears again after your changes.
