### PR TITLE
use consistent key for reconnecting tasks

### LINKED ISSUE #156899: task reconnection doesn't work on windows
once this is fixed, can be enabled by default

### PR DESCRIPTION
**Pull request by meganrogge**
fix #156899
two remaining issues (windows-only) that I'm deferring
- https://github.com/microsoft/vscode/issues/150055 - see issue comment for details can reproduce this 
- https://github.com/microsoft/vscode/issues/157136

### CODE REVIEW

File: src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts [hunk 1]
```diff
@@ -963,13 +963,6 @@ export class TerminalTaskSystem extends Disposable implements ITaskSystem {
 				for (let i = bufferLines.length - 1; i >= 0; i--) {
 					watchingProblemMatcher.processLine(bufferLines[i]);
 				}
-				if (!delayer) {
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts:966]: don't think this is needed -  it's used in the other place processLine is called, but that's bc it's within `onData` and thus needs to not process lines all of the time

**Review by Tyriar — APPROVED** [review]
