### PR TITLE
fix terminal find bugs

### LINKED ISSUE #148107: Match decorations not cleared when terminal is resized
Testing #148060

1. Run a query which results in matches
2. Resize the terminal (e.g. expand or collapse explorer)
3. :bug: match decorations remain 
image

### LINKED ISSUE #148109: Terminal find match count is incorrect
Testing #148060

1. Create a new terminal
2. Run a script which logs the same text 2000 times
3. Run a query, ✅ find widget says there are 2000 matches
4. Resize the terminal (e.g. collapse and expand the side bar)
5. :bug: the number of matches is now less even though the same amount of scrollback is visible, moreover deleting and reentering the query doesn't reset the match count

image

### LINKED ISSUE #148133: No results not rendered in terminal find widget
Refs: #148060

macOS, zsh shell

Search for something in the terminal that does not exist -> "no results" is not rendered.

Screenshot 2022-04-26 at 13 23 02

### LINKED ISSUE #148134: No results in terminal find should not be red if input is empty
Testing #148060

Notice how the "no results" is grey in the editor when the find input is empty.
In the terminal it is red 🐛 

Screenshot 2022-04-26 at 13 25 37

### LINKED ISSUE #148136: Terminal find widget count always says 1/n or n/n
Testing #148060

macOS, zsh

1.  Do a couple of ls calls
2. Search for something that has multiple matches in the terminal
3. Navigate using the Down or Up arrow -> notice how the count is always wrong 🐛 

Recording 2022-04-26 at 13 30 46

### PR DESCRIPTION
**Pull request by meganrogge**
This PR 
fixes #148109
fixes #148136
fixes #148107
fixes #148133
fixes #148134

### CODE REVIEW

File: src/vs/workbench/contrib/codeEditor/browser/find/simpleFindWidget.ts [hunk 1]
```diff
@@ -308,14 +308,17 @@ export abstract class SimpleFindWidget extends Widget {
 			this._matchesCount.className = 'matchesCount';
 		}
 		this._matchesCount.innerText = '';
-		let label;
-		if (count?.resultCount === -1) {
-			label = '';
-		} else {
-			label = count === undefined || count.resultCount === 0 ? NLS_NO_RESULTS : strings.format(NLS_MATCHES_LOCATION, count.resultIndex + 1, count?.resultCount);
+		let label = '';
```
Comment (meganrogge) [inline src/vs/workbench/contrib/codeEditor/browser/find/simpleFindWidget.ts:311]: remove the `@` and move services to bottom
