### PR TITLE
Fixed explorer modified sort order not working in some cases

### LINKED ISSUE #72474: Refresh explorer button changes sort order
I've set "explorer.sortOrder": "modified" but the explorer does switch back to default sort order. 

- VSCode Version:1.33.1
- OS Version:Windows 10 1809

Steps to Reproduce:

1.When I push multiple times the "Refresh explorer" button in explorer on an opened folder the sort order changes between default and modified randomly. It can reproduced by fast clicking the button, the last order will persist.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by jmbockhorst**
Fixed explorer modified sort order not working in some cases due to metadata not being loaded. Fixes #72474.

### CODE REVIEW

File: src/vs/workbench/contrib/files/common/explorerService.ts [hunk 1]
```diff
@@ -155,7 +155,7 @@ export class ExplorerService implements IExplorerService {
 		}
 
 		// Stat needs to be resolved first and then revealed
-		const options: IResolveFileOptions = { resolveTo: [resource], resolveMetadata: false };
+		const options: IResolveFileOptions = { resolveTo: [resource], resolveMetadata: this.sortOrder === 'modified' ? true : false };
```
Comment (gndelia) [inline src/vs/workbench/contrib/files/common/explorerService.ts]: given that `this.sortOrder === 'modified'` already returns a boolean, why do not we use that directly ?
```suggestion
		const options: IResolveFileOptions = { resolveTo: [resource], resolveMetadata: this.sortOrder === 'modified' };
```

**Comment by isidorn** [comment]
Great fix, thanks a lot!
