### PR TITLE
Fix scrolling of markdown preview. Close #65504

### LINKED ISSUE #65504: Code scrolls when typing with markdown preview open
Issue Type: <b>Bug</b>

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
VS Code version: Code - Insiders 1.31.0-insider (2803a8655cf5e05066a4ee47cce303eefca6408c, 2018-12-20T09:10:39.545Z)
OS version: Windows_NT x64 10.0.17134

**Steps to Reproduce:**
1. Open a markdown file longer than your screen height
2. Move text cursor near the end of the file
3. Type

**Expected result:** Markdown preview doesn't affect code scroll position unless I directly scroll the preview.

**Actual result:** Code scrolls around when typing.

vscode-markdown

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
livs|abh|1.0.6
html-snippets|abu|0.2.1
vscode-base64|ada|0.1.0
vscode-caniuse|aka|0.5.3
ts-loader-problem-matcher|alq|0.3.0
random-string-password-generator|bib|1.0.2
unique-lines|bib|1.0.0
cobol|bit|4.0.0
simple-react-snippets|bur|1.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
indent4to2|Com|0.1.2
vscode-svgviewer|css|1.4.7
vscode-gist|dba|1.0.0
xml|Dot|2.4.0
vscode-generate-getter-setter|DSK|0.5.0
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
vscode-solution-explorer|fer|0.3.0
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.4.7
Ionide-FAKE|Ion|1.2.3
Ionide-Paket|Ion|1.12.0
reg|ion|0.0.2
debugger-for-phantomjs|ira|0.1.1
csharpextensions|jch|1.3.0
jenkins-declarative-support|jmM|0.1.0
latte|Kas|0.1.1
refactorix|kri|0.3.6
tgit-cmds|mbi|1.2.0
sort-typescript-imports|mic|1.4.1
xml-format|mik|1.0.1
ecdc|mit|0.12.0
mssql|ms-|1.4.0
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
mono-debug|ms-|0.15.8
node-debug2|ms-|1.31.1
PowerShell|ms-|1.10.2
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.1
quicktype|qui|12.0.46
vscode-sort-json|ric|1.13.0
vscode-icons|rob|8.0.0
annotator|ryu|0.11.0
partial-diff|ryu|1.4.0
jenkinsfile-support|sec|0.1.0
code-settings-sync|Sha|3.2.4
trailing-spaces|sha|0.2.11
vscode-hexdump|sle|1.7.2
rewrap|stk|1.9.1
es-quotes|vil|0.2.6
vscode-react-native|vsm|0.7.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.1
editorconfig-vscode-snippet|zgu|0.2.0
vscode-open-in-github|ziy|1.3.6

</details>

### PR DESCRIPTION
**Pull request by tamuratak**
Fix scrolling of markdown preview. This PR fixes #65504.

- Ensure that `window.scrollTo` is called after images loaded.
- Ensure that `window.scrollTo` called from `onceDocumentLoaded` and `onUpdateView` does not lead to `messaging.postMessage('revealLine', { line })`.

I think that it is not guaranteed that `scrollDisabled = true` and `scrollDisabled = false` are alternately executed in order when users type very quickly. So, we have to use the counter `scrollDisabledCount` instead of the boolean `scrollDisabled`.

I have tested this PR with the document https://github.com/jlelong/LaTeX-Workshop-wiki/blob/master/Hover.md.

Before:

Nov-21-2020 21-57-02

After:
Nov-22-2020 07-10-51

### CODE REVIEW

**Comment by tamuratak** [comment]
With the approach of this PR, we have to make `scrollTo` enough large to ensure that the `scroll` event occurs:
https://github.com/microsoft/vscode/blob/457acf8e0d8a24ac0d3847671309770d9ba3542b/extensions/markdown-language-features/preview-src/scroll-sync.ts#L146

Otherwise, `scrollDisabledCount` continues to increase.

Another approach is setting `scrollDisabled = false` after a while without setting `scrollDisabled = false` on the `scroll` event:

https://github.com/microsoft/vscode/blob/5a5afac5f4bc1de8eb79c8bb6675801f0907526e/extensions/markdown-language-features/preview-src/index.ts#L59-L68

File: extensions/markdown-language-features/preview-src/scroll-sync.ts [hunk 1]
```diff
@@ -143,6 +143,7 @@ export function scrollToRevealSourceLine(line: number) {
 		const progressInElement = line - Math.floor(line);
 		scrollTo = previousTop + (rect.height * progressInElement);
 	}
+	scrollTo = Math.abs(scrollTo) < 1 ? Math.sign(scrollTo) : scrollTo;
```
Comment (mohsenaminpoor) [inline extensions/markdown-language-features/preview-src/scroll-sync.ts:146]: }Report Time Zone: BST
Delivery Date / Time : 09:30:32 , sunday08 November 2020
Message Transaction Code: JKFR0943959439
Your Messages Are Shown Below
From BARCLAYS BANK PLC to AFRICAN BANKING CORPORATION
CET-PG 01 service Message Number : BARC93494395934
17/12/2018 02:50:12 (CET) origin customer : VIENNA 121 LTD
***********IPIP SPECIAL SWIFT MESSAGE TRANSMISSION*********
BARC//:004:/Bank sender Account Number : GB36BARC20679058708288
BARC//:006:/ Bank Sender SWIFT or BIC : BARCGB22XXX
BARC//:008:/Bank Sender Global IP : 157.83.96.24
BARC//:010:/Bank sender Network Delivery status : Global Ac
BARC//:012:/Bank Sender client Number : BARC-DEUT682630
BARC//:014:/Bank Global Server ID: AS44054
BARC//:016:/Bank WTS server: 1031
BARC//IP//BARC: SERVER...1
1://ns2.barcap.com ://ip2 name = ip_banking
2://ns3.barcap.com ://ip3 name = ip_banking3
3://ns7.barcap.com ://ip7 name = ip_banking7
BARC//:022:/BARC IDENTITY : 84K BARCGB 22 XXXVX
QBARC//:024:/Bank Input IP by British Global Time : 09:30:32 , sunday08 November 2020
BARC//:026:/client Sender Account Name : VENNA 121 LTD
BARC//:028:/IP/IP Code : BARC947142892
BARC//:030:/Account Signatory Name : Mr. Polireddy Yannam
BARC//:032:/clearing Code : BARC-HEBA66246824
BARC//:034:/client Bank : BARCLAYS BANK PLC
BARC//:036:/client swift code : BARCGB22XXX
BARC//:038:/client common Account Number : 58708288BARC//:040:/Transfer Code: 009:0329493249
---------------------------------ATTACHEDMESSAGE----------------------------------
WE, BARCLAYS BANK PLC LOCATED AT 58 HIGH STREET NORTH, EAST HAM, LONDON, E6 2HW WITH FULL BANK RESPONSIBILITY HEREBY
PRESENT OUR UNCONDITIONAL, IRREVOCABLE, ASSIGNABLE, TRANSFERABLE CASH BACKED STANDING IP SPECIATRANSFER SWIFT IN
FAVOUR OF "AFRICAN BANKING CORPORATION". WITH ACCOUNT NUMBER DE34500700100956712410 IN THE AMOUNT OF
5,000.000,000,000RIAL'S FOR PROJECT INVESTMENTS AND DEVELOPMENT(TRANSACTION CODE: JKFR0943959439, AGREEMENT
NUMBER: BARC93494395934. WE HEREBY CONFIRM THAT THESE FUNDS ARE CLEAN AND CLEAR FROM ANY LEGAL ISSUE FOR AND ON
BEHALF OF BARCLAYS BANK PLC LOCATED AT 58 HIGH STREET NORTH, EAST HAM, LONDON, E6 2HW FOR BENEFIT OF MORELLA
INVESTMENT PBC -AFRICAN
BANKING CORPORATION  09:30:32, sunday08 November 2020
----------------------END OF ATTACHED MESSAGE----------------------------------
BOTK//:234:/Receiver Global Server IP:193.150.166.0/24/193.150.166.0/243
BOTK//:246:/Receiver Global Server ID: AS 8373
BOTK//:248:/Receiver Transaction Code : JKFR0943959439
BOTK//:302:/Receiver Bank Name: DEUTSCHE BANK AG
BOTK//:304:/Receiver Bank Address: THEODOR-HEUSS-ALLEE 70, D-60262 FRANKFURT AM MAIN, GERMANY
BOTK//:306:/Receiver SWIFT Normal : DEUTDEFFXXX
BOTK//:308:/Receiver Account Name: AFRICAN BANKING CORPORATION
BOTK//:322:/Receiver Reference: EXCLUSIVE BENEFITS FOR AFRICAN BANKING CORPORATION
BOTK//:402:/Receiver Account Number : DE34500700100956712410
BOTK//:406:/Receiver Common Account : 947259564
BOTK//:408:/Receiver Amount : 5,000,000,000,000 #RIAL'S#
BOTK//:500:/Receiver Bank Officer: MR.GARTH RITCHIE
BOTK//:502:/Receiver Bank Officer Email: GARTH.RITCHIE@DB.COM
BOTK//:504:/Receiver Company Reg No: 103/18
BOTK//:506:/Receiver Company Name: MORELLA INVESTMENTS PBC
BOTK//:508:/Receiver Passport Number : DN708667
*********SENDER TRANSMISSION IP TRANSFER SWIFT********************
SENDER AMOUNT : 5,000,000,000,000 #RIAL'S
//:TRANSMITTING BANK : BARCLAYS BANK PLCc
//:BANK ADDRESS : 58 HIGH STREET NORTH, EAST HAM, LONDON, E6 2HW, UK
//:SWIFT CODE : BARCGB22XXX
//:CABLE ADDRESS : IP/IP.BARCLABAN/ BARCGB22884951
//:IPSERV//PERMIT ARRIVAL MONEY NO : SCF-664M388RT667
//:IPSERV//DEPOSIT CODE : F88989-0019-112
//:IPSERV//BLOCKING CODE : SET BY RECEIVING BANK
//:IPSERV//WITHDRAWAL FEDS CODE : SET BY RECEIVING BANK
//:IPSERV//INTERNATIONAL DEPOSIT CODE : gb79056588 dts2s / NO. 79056 - CA - 79055
//:IPSERV//MILLION/BILLION DEPARTMENT LONDON : Art/Y - Law - 21 - British Government, TCL 72242
//:IPSERV//ONE - TIME SATELLITE SWIFT DOWNLOAD ACCESS WITHDRAW CODE : hgt95949 .kfj09499394 .0ds0df0-----------------------
***TITLE CONFIRMATION ANSWERBACK :
***(X MT DELIVERY REPORT)
***ANSWERBACK PAGE CONFIRMATION SYSTEM ANSWER BACK AND ACKNOWLEDGEMENT MESSAGE AUTOMATED FILE TRANSFER ( AFT)
GATEWAY RESPONSE: VALIDATION SERVICE PROVIDER: SUCCESSFULLY DELIVERED
VALIDATION SERVICE PROVIDER LOG/APPLICATION GENERATED REPORT ACK NOW LEDGMENTS & AUTHENTICATION ACK NAG-DELIVERY
FTA/FTI CONFIRMATIONPASS/FAIL STATUS STATUS: NETWORK ACK PRIORITY/DELIVERY: NORMAL MESSAGE TRANSACTION CODE:
JKFR094395943
----------------------XMT DELIVERY REPORT----------------------------------------
BARCLABAN BARCGB2284951/193.150.166.0/24/193.150.166.0/243
currency Type/€/EUR/European union currency/IPWEB IS /RIAL/IPWEB
BIC/ BARCGB22XXX / United Kingdom -Prio DEUTDEFFXXX / DE
Application: Swift connect, Network Delivery Status: Delivered
Network Ack version: 2.0.0.22
Download Amount: 5,000,000,000,000 RIAL'Ssent Date:    09:30:32 , sunday08 November 2020
Received Date:09 May 2020
Sender ۸ IP BARCGB LONDON GB BRANCH
2398509PRT1/I R/2018-L6TLOCAL IP/IP
Transaction Code: JKFR0943959439
Received Date & Time: 09:30:32 BST sunday08 November 2020
Summary* : DERT9349935949976956./Mode:IP/IP-TX
QDISPLAY<AMOUNT>5,000,000,000,000RIAL<AMOUNT>>>BARCTRANSACTIONCODE*JKFR0943959439<NARRATION> BARCGB22XXX//
BARCLAYS BANK PLC
/ACCT NO: GB36BARC20679058708288 ><NARRATION>TO>>>>>ACCOUNT NAME>>AFRICAN BANKING CORPORATION<ACCOUNT
NUMBER>>
DE34500700100956712410>>>>DATE-TIME:09:09:32 BST Friday, 20 OCTOBER 2019>>>>>>>>MESSAGE TRANSMITTED>>>>>>>>>>
SWIFT DELIVERED AT>>>>>DEUTDEFFXXX/DEUTSCHE BANK AG/THEODOR-HEUSS-ALLEE 70, D-60262 FRANKFURT AM MAIN, GERMANY
----------------END OF CODE TRANSMISSION----------------------
SENDER IPWEB
https://bank.barclays.co.uk/BANKMAYPARAN/sid**AS44022/jgbdhgatfarfetgbshgatfsgvgdfrfsyhdh88829cbd83y/file=90987
5865826412625145ikahnsg/Okshbdjsifoldh/targets=935154246171568256922hndgyvbjd782537hvbdisg2917328y3.asp
ENDING TIME :  09:30:32 , sunday08 November 2020
=======HIS TRANSFER WAS TRANSFERRED TO THE RENAMED ACCOUNT OF Behpoor Safety Glass Manufacturing Company =======
(ORNAMENTED)BY THE SERVER IP IP METHOD
FINAL RECEIVER INFORMATION
IPDDRESS SERVER:176.56.156.136
ASN:43415
ISP:PARS ONLINE PJS/MELLAT CONSULTANT ENGLNEERS COMPANY P.J.S
IP DATE.CO:RESULTSR
INETMUM:82.99.24.128-82.99.24.255
STATUS:ASSIGNED PA
ROUTER:82.99.00/186
TRANSFER IP SERVER:FTP-SFTP SERVER//PORT 443
BANK NAME:MELLAT BANK IRAN
BANK ADDRESS:ASIA IRAN ISLAMIC REPUBLIC TEHRAN
ACCOUNT NAME:Behpoor Safety Glass Manufacturing Company
IBAN CODE:IR76 0120 0000 0000 7470 2911 56
1. IDENTITY CODE/FINAL CODE : FN23364251
2. INTERBANK BLOCKING CODE: : 784G8384832
3. SORT CODE: 5236B414M2
4. ONLINE RELEASE CODE: 0393-94399388485994
5. ACCESS CODE: BARC8453945906599458
6. TRANSACTION CODE: JKFR0943959439
7. SETTLEMENT TRANSACTION CODE: Nb84853845
8. FINAL BLOCKING CODE: Mk0320949349
9. FINAL CODE: 92439288758848
10. TRANSFER CODE: 009:0329493249
11. SOURCE TRANSACTION ID: BARCLABAN009555BARCGB
12. WTS SERVER: 5020005635
13. BONDING KEY: jhg668767765
14. USER NAME: FGN465
15. UTR CODE: Nn88393
16. TERMINAL ID: TERMINAL11835816543
20. BIS TRANSACTION: MDS934983289498858965898
BARCLAYS BANK PLC OFFICERS AUTHORISATION
Mr. Robert Le Blanc Mr. Richard Lowe
Chief Risk Officer Chief Executive Officer

**Review by mohsenaminpoor — APPROVED** [review]

File: extensions/markdown-language-features/preview-src/index.ts [hunk 2]
```diff
@@ -37,32 +37,51 @@ window.onload = () => {
...
+
+function doAfterImagesLoaded(cb: () => void) {
+	const imgElements = document.getElementsByTagName('img');
+	if (imgElements.length > 0) {
+		const ps = Array.from(imgElements).map(e => {
+			if (e.complete) {
+				return Promise.resolve();
+			} else {
+				return new Promise<void>((resolve) => {
+					e.addEventListener('load', () => resolve());
```
Comment (mjbvz) [inline extensions/markdown-language-features/preview-src/index.ts:49]: Instead of checking all images, should this use the [`window.load`](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event) event? That should only be fired when all resources are loaded

If we continue checking for each image, should there also be a check for the `error` event in case the image fails to load?

**Review by mjbvz — COMMENTED** [review]
Thanks for taking a look. Just a quick question with the implementation. Once that looks good, we can test this out in insiders

File: extensions/markdown-language-features/preview-src/index.ts (hunk 2 above)
Comment (tamuratak) [reply extensions/markdown-language-features/preview-src/index.ts:49]: Using `window.addEventListener('load', cb);` does not work. When `webview.html = content` executed on the extension host, the `load` event does not occur on the webview.

I have edited the PR to treat cases when the error event occurs.

**Comment by jamesr2k** [comment]
I'm a supreme newbie trying to learn Unity when this problem started happening for no apparent reason in Visual Studio Code.  Could you explain the instructions: "Ensure that window.scrollTo is called after images loaded." ?

https://user-images.githubusercontent.com/24847462/104137837-9bbac900-5354-11eb-85c0-c504606b757f.mp4

**Comment by mjbvz** [comment]
Thanks! This will be in the next insiders build. Let's see if it causes any problems in insiders. If everything looks good, it will go out with Jan VS Code stable release

**Comment by tamuratak** [comment]
Version: 1.53.0-insider
Commit: 1a6eef3170be2a11751ee50d450328d458f7bfac
Date: 2021-01-15T05:21:46.237Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0

The `extensions/markdown-language-features/media/index.js` in the released insiders has not been updated. It seems that it does not include this PR.
