### PR TITLE
Add gulp targets, fix build for Windows on Arm.

### LINKED ISSUE #33620: Support ARM64 build for Windows
New devices are coming to market in a couple months. These are ARM64 devices running the Windows 10 OS. Can we get an officially supported build of VS Code that runs native on ARM64?

### PR DESCRIPTION
**Pull request by richard-townsend-arm**
This PR partially fixes #33620, #81854

This PR doesn't get us all the way there because of a problem with `vscode-sqlite3`. (Essentially, it doesn't build with right version of Visual Studio - 2017 or later is needed, the node-gyp config is slightly wrong and I don't have legal approval to fix it). Once that issue is fixed, you'll be able to do the following to build for Windows on Arm, assuming Node v12.13.1 and node-gyp 5.0.5:

```
set npm_config_arch=arm64
yarn install --force
yarn run gulp vscode-win32-arm64-archive
```

Make sure to set up an ARM64 cross-compilation terminal as documented [in Electron's upstream instructions](https://electronjs.org/docs/tutorial/windows-arm).

The result is a zip file which you can manually install and run on the device - seems to work well, built-in extensions like syntax highlighting, PowerShell prompt all seem to function, performance is good too. 

PTAL and I'll try to fix any non-SQLite issues which come up. CC @deepak1556 

Update: 2020-March-10: the revised SQlite3 module has been published.

### CODE REVIEW

File: build/npm/postinstall.js [hunk 1]
```diff
@@ -23,9 +23,17 @@ function yarnInstall(location, opts) {
...
+		// Temporarily set remote arch to x86, because remote portion builds
+		// against node, which is not consistently supported on Windows on Arm
+		// (yet).
+		process.env["npm_config_arch"] = "ia32"
+	}
 	console.log(`$ yarn ${args.join(' ')}`);
 	const result = cp.spawnSync(yarn, args, opts);
-
+	// Restore the architecture, if temporarily swapped.
+	process.env["npm_config_arch"] = oldConfigArch
```
Comment (richard-townsend-arm) [inline build/npm/postinstall.js]: I think the build error may come from here. Probably should strengthen the check so it fires only on Windows.

File: build/lib/electron.js [hunk 2]
```diff
@@ -99,6 +99,9 @@ function getElectron(arch) {
     };
 }
 async function main(arch = process.arch) {
```
Comment (joaomoreno) [inline build/lib/electron.js]: How about this instead?

```suggestion
 async function main(arch = process.env["npm_config_arch"] || process.arch) {
```

File: build/npm/postinstall.js [hunk 3]
```diff
@@ -23,9 +23,17 @@ function yarnInstall(location, opts) {
...
 	console.log(`Installing dependencies in ${location}...`);
+	const oldConfigArch = process.env['npm_config_arch']
+	if (location.startsWith("remote") && oldConfigArch == "arm64") {
+		// Temporarily set remote arch to x86, because remote portion builds
+		// against node, which is not consistently supported on Windows on Arm
+		// (yet).
+		process.env["npm_config_arch"] = "ia32"
+	}
 	console.log(`$ yarn ${args.join(' ')}`);
 	const result = cp.spawnSync(yarn, args, opts);
```
Comment (joaomoreno) [inline build/npm/postinstall.js]: Shouldn't the new environment flag simply be added to the `opts`, instead of fiddling around with the current process env?

**Review by joaomoreno — CHANGES_REQUESTED** [review]
Build error is this, notice the `undefined`:

```
LINK : fatal error LNK1104: cannot open file 'C:\Users\runneradmin\AppData\Local\node-gyp\Cache\12.4.0\undefined\node.lib' [D:\a\vscode\vscode\remote\node_modules\native-watchdog\build\watchdog.vcxproj]
```

File: build/npm/postinstall.js (hunk 3 above)
Comment (deepak1556) [reply build/npm/postinstall.js]: Agreed, setting the env through `opts` will be cleaner.

**Comment by voronoipotato** [comment]
@richard-townsend-arm  Don't forget to sign the CLA, that way it will get released :). I'm happy to help test this on my surface pro x.

**Comment by richard-townsend-arm** [comment]
OK, CLA is now signed. I meant to get another patchset out last week, but there've been a few last-minute issues before branching Chromium 80 / Electron 8 which have been consuming my attention. Hopefully get an update out in a few days time.

**Comment by bpasero** [comment]
Change itself looks OK to me, but I think we need to validate the build once we ran it since these changes are all in build scripts. Unassigning myself from review.

**Comment by richard-townsend-arm** [comment]
OK. I'm unsure why the CI is failing to fetch all the deps (something to do with --frozen-lockfile?) There haven't been any changes to packages.json so I'm unsure why it's doing this...

**Comment by richard-townsend-arm** [comment]
Cool, looks like the CI has come back clean this time. Ready for review.

**Comment by richard-townsend-arm** [comment]
Hi guys, happy new year! Any review thoughts?

**Comment by snickler** [comment]
I'd love to see this merged in soon. I built from your branch last month and it has been running perfectly for me on my Surface Pro X @richard-townsend-arm .

**Comment by voronoipotato** [comment]
Indeed do we have a date estimate for review @joaomoreno  / @deepak1556 ? It appears that @richard-townsend-arm has completed your changes.

**Review by deepak1556 — APPROVED** [review]
Sorry for the delay on this, LGTM

**Comment by richard-townsend-arm** [comment]
I'm not authorized to merge this change atm.

**Comment by snickler** [comment]
It needs @joaomoreno to review it before you can merge.

**Comment by nathansoz** [comment]
Would love to see this get merged soon! Built from source but am unable to use the remote development extensions :/

File: build/gulpfile.reh.js [hunk 4]
```diff
@@ -37,6 +38,7 @@ const BUILD_TARGETS = [
 
 const noop = () => { return Promise.resolve(); };
 
+gulp.task('vscode-reh-win32-arm64-min', noop);
```
Comment (joaomoreno) [inline build/gulpfile.reh.js]: This is not needed

File: build/gulpfile.reh.js [hunk 5]
```diff
@@ -45,6 +47,7 @@ gulp.task('vscode-reh-linux-armhf-min', noop);
 gulp.task('vscode-reh-linux-arm64-min', noop);
 gulp.task('vscode-reh-linux-alpine-min', noop);
 
+gulp.task('vscode-reh-web-win32-arm64-min', noop);
```
Comment (joaomoreno) [inline build/gulpfile.reh.js]: This is not needed

File: build/gulpfile.vscode.win32.js [hunk 6]
```diff
@@ -110,8 +110,10 @@ function defineWin32SetupTasks(arch, target) {
 	gulp.task(task.define(`vscode-win32-${arch}-${target}-setup`, task.series(cleanTask, buildWin32Setup(arch, target))));
 }
 
+defineWin32SetupTasks('arm64', 'system');
```
Comment (joaomoreno) [inline build/gulpfile.vscode.win32.js]: Not needed

File: build/gulpfile.vscode.win32.js [hunk 7]
```diff
@@ -110,8 +110,10 @@ function defineWin32SetupTasks(arch, target) {
...
 defineWin32SetupTasks('ia32', 'system');
 defineWin32SetupTasks('x64', 'system');
+defineWin32SetupTasks('arm64', 'user');
```
Comment (joaomoreno) [inline build/gulpfile.vscode.win32.js]: Not needed

File: build/gulpfile.vscode.win32.js [hunk 8]
```diff
@@ -142,10 +145,11 @@ function updateIcon(executablePath) {
 	};
 }
 
+gulp.task(task.define('vscode-win32-arm64-inno-updater', task.series(copyInnoUpdater('ia32'), updateIcon(path.join(buildPath('ia32'), 'tools', 'inno_updater.exe')))));
```
Comment (joaomoreno) [inline build/gulpfile.vscode.win32.js]: Not needed

File: build/npm/postinstall.js [hunk 9]
```diff
@@ -23,9 +23,14 @@ function yarnInstall(location, opts) {
 	const args = original.filter(arg => arg === '--ignore-optional' || arg === '--frozen-lockfile');
 
 	console.log(`Installing dependencies in ${location}...`);
+	if (location.startsWith("remote") && process.env["npm_config_arch"] == "arm64") {
```
Comment (joaomoreno) [inline build/npm/postinstall.js]: Just move this further down to when we call `yarnInstall('remote')` and add the option as an argument.

**Review by joaomoreno — CHANGES_REQUESTED** [review]
Merging this will only enable building the OSS bits. We will not distribute whatever targets this enables building since that's a much much larger work item and infrastructure investment.

**Comment by snickler** [comment]
> Merging this will only enable building the OSS bits. We will not distribute whatever targets this enables building since that's a much much larger work item and infrastructure investment.

Is there any guidance on the remaining things that would enable a true VS Code build for Windows ARM64? This is something that many of us running WoA would absolutely love to have.

**Comment by joaomoreno** [comment]
@snickler As you can imagine, writing the code to build VS Code is only half the story. We have a lot of infrastructure and manual steps to ensure the quality of the bits that we ship to our customers. Basically, if we distribute it, it becomes part of our endgame and continuous testing efforts. We currently don't have the hardware or selfhosting motivation to push this forward. Upvoting https://github.com/microsoft/vscode/issues/33620 will help with that.

**Comment by voronoipotato** [comment]
@joaomoreno Firstly, thanks for taking the time to read and review the pull request. I understand this is a lot of extra work. VS Code and the work you do here is extremely important for Microsoft's Arm initiative. Visual Studio proper can't be meaningfully ported in the near future and emulation of Visual Studio just isn't there yet. Without a tool to write software for windows on ARM there never will be "software for windows on arm". VS Code should be the primary tool for writing code on ARM devices. If you aren't allocated the hardware to test this, and it has downstream impacts that might prevent ARM on windows from being a profitable niche, and that should be remedied. Perhaps you could reach out to the Dot Net team and see what they can do to help connect you with the resources so that ARM has a fair chance in the market. They are currently working on an installer for dotnet core on ARM, and it may be helpful to market this as a coordinated release.  Again, thank you for having the patience and compassion to read through the code review. I know you're not heavily incentivized to merge in outside pull requests, so it means a lot. ❤️ 

https://github.com/dotnet/runtime/issues/1529

**Comment by richard-townsend-arm** [comment]
Cool, so I've tested 8b73106 on a device and everything seems OK. Ready for review.

File: build/npm/postinstall.js (hunk 9 above)
Comment (richard-townsend-arm) [reply build/npm/postinstall.js]: This has been replaced with a new method which applies the the override for `remote/` portions.

**Comment by pmsjt** [comment]
@voronoipotato  - thanks for the comment. I agree with you, having VSCode running natively would be a great addition and a great improvement to the development experience on the device.

That said, I do use VS2019 on a daily basis on my device and, as I cannot say it is fast, I consider it usable. Startup and load times are not great, but once you get going, the rebuild cycle get better. That the device I use for, for example, building the QEMU device drivers for ARM64, so I even have the DDK installed.

We will soon release some emulator optimizations in the Fast Channel that will make emulation of .net code significantly faster. That helps too. Stay tuned. BTW, which device are you using?

@joaomoreno - There is plenty of interest in selfhosting ARM64 native in our team. We may also be able to help with devices for testing as we are bringing up test VMs. Please reach out internally.

**Comment by joaomoreno** [comment]
@pmsjt I can't seem to find you internally, mind dropping me an email? Thanks.

**Comment by voronoipotato** [comment]
@pmsjt I'm using the surface pro x 8gb .  I do appreciate that you're testing and using Visual Studio for ARM (via emulation). I am a Visual Studio subscriber and I do use it on my desktop, I love how it is full featured and it has gotten much much faster for large projects and does not appear to crash any more on large files. Perhaps my opinions on visual studio are more to do with the size of the projects I tend to manage with visual studio than they are to do visual studio itself. However I do prefer vscode for "light duty" environments like say ultrabooks and my surface pro, even for some .NET development! Right now I remote into my home desktop when I want to use visual studio, however perhaps that will change as you improve it :). Keep me posted! I still very much would appreciate having vscode for ARM, as it is a daily complement to Visual Studio even on desktop.

**Comment by richard-townsend-arm** [comment]
So... any thoughts on getting this merged soon? Even if Microsoft does not plan to distribute it an official binary, it'd be useful for a lot of people (me included!)

**Comment by snickler** [comment]
> So... any thoughts on getting this merged soon? Even if Microsoft does not plan to distribute it an official binary, it'd be useful for a lot of people (me included!)

Agreed. There's a lot of ARM64 Windows users that would greatly benefit from using this. I've even gone so much as compiling the .NET Core SDK and and ASP.NET Core Runtime for ARM64 and it works pretty nice with it (minus a few issues around launching the debugger). We're just looking to help out the community by having support on an architecture where the core build components are already supported on.

**Comment by richard-townsend-arm** [comment]
I noticed that in https://github.com/mapbox/node-sqlite3/pull/1242, the vscode-sqlite3 issue was fixed (but vscode needs to upgrade to that version).

**Comment by richard-townsend-arm** [comment]
CC'ing @bpasero (seems that you look after the sqlite3 dependency).

**Comment by bpasero** [comment]
I think we can try to update to latest. If you make the PR, I can look into it. Note that we use a fork with some changes so they would have to go into our repo.

**Comment by richard-townsend-arm** [comment]
@bpasero: I think the npm.js package (https://www.npmjs.com/package/vscode-sqlite3) would need to be updated first, otherwise any CI attached would fail. If it is a fork, the relevant change could be incorporated safely by cherry-picking https://github.com/mapbox/node-sqlite3/pull/1242/commits/f2f3b7df1130e8129ab76ad9cf0904634ba7cf38, but it would still probably need at least a version bump.

**Comment by bpasero** [comment]
@richard-townsend-arm oh nice, a cherry-pick would be good because that reduces the chances of breakage. I am happy to accept a PR there and publish a newer version.

**Comment by richard-townsend-arm** [comment]
OK, I'll need to check that this component is covered under our our existing legal approval to contribute to VsCode. Can you confirm that [this](https://github.com/bpasero/node-sqlite3) is the place where the PR should be sent?

**Comment by bpasero** [comment]
@richard-townsend-arm it should be https://github.com/microsoft/vscode-node-sqlite3

**Comment by richard-townsend-arm** [comment]
OK, so I don't have legal approval yet to contribute the backport. It's in progress (might take some time.)

**Comment by richard-townsend-arm** [comment]
Still having some issues with vscode-sqlite3: it looks like `yarn install` does not use the variables from the `binary` section of vscode-sqlite3's `package.json`, so you end up with an error like this:
<pre>
gyp info using node-gyp@5.0.5
gyp info using node@12.13.1 | win32 | x64
gyp info find Python using Python version 2.7.16 found at "C:\Python27\python.exe"
gyp info find VS using VS2017 (15.9.28307.812) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\rictow01\\vscode\\node_modules\\vscode-sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\rictow01\\AppData\\Local\\node-gyp\\Cache\\7.1.11\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\rictow01\\AppData\\Local\\node-gyp\\Cache\\7.1.11',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\rictow01\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\7.1.11\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\rictow01\\vscode\\node_modules\\vscode-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\rictow01\\vscode\\node_modules\\vscode-sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: Undefined variable module_path in binding.gyp while trying to load binding.gyp
</pre>

Hopefully this is something that can be addressed by packing appropriately with node-pre-gyp.

**Comment by richard-townsend-arm** [comment]
OK, so the error turned out to be because the published package contains additional changes (including typescript definitions etc) from the source code that's in microsoft/vscode-node-sqlite3, so naively doing `yarn link` was not going to work. Hopefully open the pull request to backport the change tomorrow.

**Comment by richard-townsend-arm** [comment]
sqlite3 request opened: https://github.com/microsoft/vscode-node-sqlite3/pull/7 @bpasero

**Comment by voronoipotato** [comment]
Thank you for continuing to put in work into this!!! :) Let me know if you have a way for me to buy you a coffee/beer.

**Comment by richard-townsend-arm** [comment]
Whilst testing the new sqlite3, it emerged that the previous way of building the remote extensions no longer works correctly, the latest update should fix it again.

**Comment by deepak1556** [comment]
Verified that the build works fine and was able to test on a local device. Thanks @richard-townsend-arm for all the work on this 👍

**Comment by bpasero** [comment]
Published `vscode-sqlite3@4.0.10`

**Comment by richard-townsend-arm** [comment]
Unsure as to why one of the checks has still not come back, but ready to review.

**Comment by harrisonmetz** [comment]
Would be great to have this merged. Is it just waiting for @joaomoreno to approve or were more changes requested? It looks like all the checks have passed at this point.

**Comment by hwchong** [comment]
> Would be great to have this merged. Is it just waiting for @joaomoreno to approve or were more changes requested? It looks like all the checks have passed at this point.

It's sad to think this is being blocked by internal politics at Microsoft.

**Comment by harrisonmetz** [comment]
> 
> 
> > Would be great to have this merged. Is it just waiting for @joaomoreno to approve or were more changes requested? It looks like all the checks have passed at this point.
> 
> It's sad to think this is being blocked by internal politics at Microsoft.

Internal politics? The PR is appropriately licensed, and if it works all that is left is to hit the merge button. It's not even that large of a code change. I'd be happy to click the merge button for someone else if they don't feel they can.

**Comment by voronoipotato** [comment]
I hope @joaomoreno is alright 😕, hopefully they're just on vacation and not hit with the virus.

**Comment by voronoipotato** [comment]
hello @joaomoreno !  It appears that you're back. Hopefully all is well. I understand that times have been rough for all and please take the time you need to recenter and breathe. Nobody is as productive as they would like during a pandemic.

If you find that you have the time it would mean a lot to us if you could merge even with an early access or alpha label that way people can use and install it but you don't have as much pressure to work tickets to resolve them, merely merging fixes as you can. Hopefully that could be a decent middle path that allows people to have an option. I personally have not been using my surface pro x as much as I would like in part because it has no native vscode. I really had expected Microsoft to have a unified approach but it appears they have left your team behind in resources. Sorry to hear about that, as I think Code is one of Microsoft's best products.

**Comment by joaomoreno** [comment]
@voronoipotato, and everyone else: merging this PR does not mean, by all means, that we will start releasing VS Code for ARM. That is a whole different undertaking and requires proper planning and time allocation for our PM team, who is very much aware of the demand for VS Code on ARM for Windows.

This PR will simply enable you to build the Code OSS build for Windows ARM. You can already do that today, you don't need to wait for me:

1. Clone this repo
2. Checkout this PR
3. Build

---

I will look into merging the PR in April.

**Comment by snickler** [comment]
> @voronoipotato, and everyone else: merging this PR does not mean, by all means, that we will start releasing VS Code for ARM. That is a whole different undertaking and requires proper planning and time and resource allocation for our PM team, who is very much aware of the demand for VS Code on ARM for Windows.
> 
> This PR will simply enable you to build the Code OSS build for Windows ARM. You can already do that today, you don't need to wait for me:
> 
> 1. Clone this repo
> 2. Checkout this PR
> 3. Build
> 
> I will look into merging the PR in April.

Nevertheless, we appreciate you looking into this. It'll make it easier for those who wish to create automated Code OSS builds for WoA. After what I've tried to do personally with building some of the components for ARM64, I definitely understand the amount of roadblocks involved with enabling this to be a fully supported VS Code build. After .NET 5 is released, I know a few of those roadblocks will be fixed. 

If testers, or ANY help is desired - the team definitely has a group of people they can call upon.

I ask that each of us awaiting this, continue to be patient and contribute any way we can.

File: build/gulpfile.reh.js [hunk 10]
```diff
@@ -25,6 +25,7 @@ const cp = require('child_process');
 const REPO_ROOT = path.dirname(__dirname);
 
 const BUILD_TARGETS = [
+	{ platform: 'win32', arch: 'arm64', pkgTarget: 'node8-win-arm64' },
```
Comment (joaomoreno) [inline build/gulpfile.reh.js:28]: Let's remove this and focus on the client bits for now.

File: build/gulpfile.vscode.win32.js [hunk 11]
```diff
@@ -146,6 +147,6 @@ gulp.task(task.define('vscode-win32-ia32-inno-updater', task.series(copyInnoUpda
 gulp.task(task.define('vscode-win32-x64-inno-updater', task.series(copyInnoUpdater('x64'), updateIcon(path.join(buildPath('x64'), 'tools', 'inno_updater.exe')))));
 
 // CodeHelper.exe icon
-
+gulp.task(task.define('vscode-win32-arm64-code-helper', task.series(updateIcon(path.join(buildPath('ia32'), 'resources', 'app', 'out', 'vs', 'platform', 'files', 'node', 'watcher', 'win32', 'CodeHelper.exe')))));
```
Comment (joaomoreno) [inline build/gulpfile.vscode.win32.js:150]: Don't we need an ARM64 compiled version of `CodeHelper.exe` for this?

File: build/lib/electron.ts [hunk 12]
```diff
@@ -107,7 +107,7 @@ function getElectron(arch: string): () => NodeJS.ReadWriteStream {
 	};
 }
 
-async function main(arch = process.arch): Promise<void> {
+async function main(arch = process.env["npm_config_arch"] || process.arch): Promise<void> {
```
Comment (joaomoreno) [inline build/lib/electron.ts:110]: We don't need this, since the build isn't fetching electron from here.

File: build/npm/postinstall.js [hunk 13]
```diff
@@ -25,17 +25,28 @@ function yarnInstall(location, opts) {
 	console.log(`Installing dependencies in ${location}...`);
 	console.log(`$ yarn ${args.join(' ')}`);
 	const result = cp.spawnSync(yarn, args, opts);
-
 	if (result.error || result.status !== 0) {
 		process.exit(1);
 	}
 }
 
+function remoteOpts() {
```
Comment (joaomoreno) [inline build/npm/postinstall.js:33]: Again, let's remove this and leave `remote` for another day.

**Review by joaomoreno — CHANGES_REQUESTED** [review]
I think we should focus on the client bits for now. Let's remove the unnecessary parts and get this in.

**Comment by joaomoreno** [comment]
May I ask, how is anybody testing this? With what hardware?

**Comment by snickler** [comment]
I've tested this compiling it from my ASUS NovaGo and most recently my Surface Pro X using the instructions above. I was able to compile a build from this PR while even merging master into it.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by hwchong** [comment]
Surface Pro X here.


-------- Original message --------

**Comment by harrisonmetz** [comment]
Maybe Microsoft should send Surface Pro X's to the entire development team of VS code!

**Comment by joaomoreno** [comment]
Got it. Let's see if I can get my hands on one of those.

File: build/gulpfile.vscode.win32.js (hunk 11 above)
Comment (richard-townsend-arm) [reply build/gulpfile.vscode.win32.js:150]: That would be ideal, but it currently runs fine under x86 emulation (and it's running in the background, so the performance degradation is not as noticeable).

**Comment by pmsjt** [comment]
There are quite a few options available for ARM64 based devices. For doing dev work I'd certainly limit the options to those with 8GiB RAM or more. Surface ProX is an obvious choice, especially to MS employees who can get them internally. But the Yoga C630 is an inexpensive candidate, being featured for sale in many stores, being previous generation.

Qualcomm 8cx based:
- Surface ProX
- Samsung Galaxy Book S

Qualcomm 850 based:
- Samsung Galaxy Book 2
- Lenovo Yoga C630 Snapdragon

Qualcomm 835 based:
- Asus NovaGo
- HP Envy x2 Snapdragon
- Lenovo Miix 630

**Comment by voronoipotato** [comment]
https://github.com/wixtoolset/issues/issues/5558 

Looks like wix is ready to go for this too!

**Comment by snickler** [comment]
> [wixtoolset/issues#5558](https://github.com/wixtoolset/issues/issues/5558)
> 
> Looks like wix is ready to go for this too!

Yup. Hopefully the 3.14 release comes soon. I was able to pull THIS off using the latest WiX dev release (with a bunch of horrible changes that I could never commit lol)

https://twitter.com/sinclairinat0r/status/1241059487139717121

**Comment by joaomoreno** [comment]
This is now merged, so you should be able to compile VS Code for ARM.

There's a Surface Pro X on the way, so we'll be able to test this soon and evaluate having an official VS Code version.

**Comment by voronoipotato** [comment]
Thank you so much Joao!!! This means so much to me, I really appreciate it. I think once you realize just how amazing it is to not worry about outlets on the go or lugging around a heavy machine you will also come to love the Surface Pro x, and now the battery footprint of VSCode is going to be so tiny! It really is night and day. Truly the killer app for the killer laptop.

**Comment by hwchong** [comment]
Thank you very much for merging this and for working to implement full support for WOA! I've managed to transition almost all my development work to the Surface Pro X with the exception of remote WSL and C/CPP, and so I still keep the x86 binary around for that. Otherwise it works perfectly for most of the other interpreted languages 😊
