### PR TITLE
use shell integration for richer terminal accessible buffer

### LINKED ISSUE #173067: Add semantics to the a11y buffer through shell integration
We now have a new more accessible buffer view, we could shell integration to add semantics to the buffer such that terminal commands can be navigated via header tags and it's split up into sections. To do this, xterm.js could delegate the creation of the elements to VS Code as it doesn't have knowledge about shell integration.

For example the DOM structure could be:

```
<h2>command 1</h2>
<div>command 1 output</div>
<h2>command 2</h2>
<div>command 2 output</div>
...
<h2>last command</h2>
<div>
  command 1 output
  <div tabindex="0">cursor line</div>
</div>
```

The special line for the cursor is an idea to help the screen reader announce the cursor line first when entering the mode. This could be any line though, we should leave it up to vscode where to position the focused line. A non-screen reader example is ctrl/cmd+up to navigate between commands and then shift+tab to enter keyboard selection at that line, instead of scroll resetting.

### LINKED ISSUE #173532: I can no longer access terminal accessibility buffer with orca
Type: <b>Bug</b>

CC: @meganrogge 
CC: @isidorn 
Today I updated the VScode insiders version and noticed that it is no longer possible to navigate with arrows in the terminal accessibility buffer.

I create a new terminal, type any command, press shift+tab and try to use the arrow keys to read the result of the command. Nothing is read by orca, no matter what keys I use.
I also tested disabling all extensions and the result was the same.

VS Code version: Code - Insiders 1.76.0-insider (c9e3ef865539061b5602c6b9ac6030332aa1ce70, 2023-02-06T05:24:21.999Z)
OS version: Linux x64 6.1.9-200.fc37.x86_64
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.27GB (10.91GB free)|
|Process Argv|-n --crash-reporter-id bc02adbd-6c3a-44b8-af92-55103a608af7|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.49.0
vscode-chatgpt|gen|3.5.5
rest-client|hum|0.25.1
better-cpp-syntax|jef|1.17.2
azure-pipelines|ms-|1.208.0
vscode-docker|ms-|1.23.3
csharp|ms-|1.25.4
vscode-kubernetes-tools|ms-|1.3.11
remote-containers|ms-|0.276.0
remote-ssh|ms-|0.97.2023020215
remote-ssh-edit|ms-|0.84.0
azure-account|ms-|0.11.3
cmake-tools|ms-|1.13.45
cpptools|ms-|1.14.1
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.6.0
powershell-preview|ms-|2023.2.0
remote-explorer|ms-|0.2.0
vsliveshare|ms-|1.0.5828
fabric8-analytics|red|0.3.6
java|red|1.15.2023020403
vscode-xml|red|0.25.2023020103
vscode-yaml|red|1.11.0
sonarlint-vscode|Son|3.14.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.44.0
vscode-java-debug|vsc|0.48.0
vscode-java-dependency|vsc|0.21.2023013100
vscode-java-pack|vsc|0.25.2022112900
vscode-java-test|vsc|0.37.2023013002
vscode-maven|vsc|0.40.2023020103
vscode-spring-boot-dashboard|vsc|0.10.1
vscode-spring-initializr|vsc|0.11.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstes627cf:30244335
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
hidelangstatbar:30657380

```

</details>

### PR DESCRIPTION
**Pull request by meganrogge**
fix https://github.com/microsoft/vscode/issues/173067
fix https://github.com/microsoft/vscode/issues/173532

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 1]
```diff
@@ -1114,6 +1114,34 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 		const font = this.xterm.getFont();
 		const lineHeight = font?.charHeight ? font.charHeight * font.lineHeight + 'px' : '';
 		this._accessibilityBuffer.style.lineHeight = lineHeight;
+		const commands = this.capabilities.get(TerminalCapability.CommandDetection)?.commands;
+		if (!commands?.length) {
+			const noContent = document.createElement('div');
+			const noContentLabel = nls.localize('terminal.integrated.noContent', "No terminal content available for this session.");
+			noContent.ariaLabel = noContentLabel;
+			noContent.textContent = noContentLabel;
+			this.xterm.raw.setAccessibilityBufferElements([noContent]);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1123]: Is it possible for this API to be the other way around? Like `registerBufferElementProvider()` such that xterm.js requests the elements only when needed?

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 2]
```diff
@@ -1104,17 +1105,53 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 		if (!this.xterm?.raw.element) {
 			return;
 		}
+		this._bufferElementProvider?.dispose();
 		this._accessibilityBuffer = this.xterm.raw.element.querySelector('.xterm-accessibility-buffer') as HTMLElement || undefined;
 		if (!this._accessibilityBuffer) {
 			return;
 		}
-		const accessibleBufferContentEditable = this._configurationService.getValue(TerminalSettingId.AccessibleBufferContentEditable);
+		const accessibleBufferContentEditable = isLinux ? 'on' : this._configurationService.getValue(TerminalSettingId.AccessibleBufferContentEditable);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1113]: A comment here to avoid digging to find the reason would be handy

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 3]
```diff
@@ -1104,17 +1105,53 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
...
+			output.tabIndex = -1;
+			output.textContent = command.getOutput()?.replace(new RegExp(' ', 'g'), '\xA0') || '';
+			shellIntegrationFragment.appendChild(header);
+			shellIntegrationFragment.appendChild(output);
+		}
+		if (header) {
+			// focus the cursor line's header
+			header.tabIndex = 0;
+		}
+		this._bufferElementProvider = this._register(this.xterm.raw.registerBufferElementProvider({ provideBufferElements: () => shellIntegrationFragment }));
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1149]: Can we register this once when xterm is opened?

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 4]
```diff
@@ -1104,17 +1105,53 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
...
+			const noContentLabel = nls.localize('terminal.integrated.noContent', "No terminal content available for this session.");
+			noContent.ariaLabel = noContentLabel;
+			noContent.textContent = noContentLabel;
+			const fragment = document.createDocumentFragment();
+			fragment.appendChild(noContent);
+			this._bufferElementProvider = this._register(this.xterm.raw.registerBufferElementProvider({ provideBufferElements: () => fragment }));
+			this._accessibilityBuffer.focus();
+			return;
+		}
+		const shellIntegrationFragment = document.createDocumentFragment();
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1131]: This could move above and get shared between the 2 paths

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 5]
```diff
@@ -1104,17 +1105,53 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
...
 		this._accessibilityBuffer.contentEditable = accessibleBufferContentEditable === 'on' || (accessibleBufferContentEditable === 'auto' && !this._accessibilityService.isScreenReaderOptimized()) ? 'true' : 'false';
 		// The viewport is undefined when this is focused, so we cannot get the cell height from that. Instead, estimate using the font.
 		const font = this.xterm.getFont();
 		const lineHeight = font?.charHeight ? font.charHeight * font.lineHeight + 'px' : '';
 		this._accessibilityBuffer.style.lineHeight = lineHeight;
+		const commands = this.capabilities.get(TerminalCapability.CommandDetection)?.commands;
+		if (!commands?.length) {
+			const noContent = document.createElement('div');
+			const noContentLabel = nls.localize('terminal.integrated.noContent', "No terminal content available for this session.");
+			noContent.ariaLabel = noContentLabel;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1123]: You shouldn't need an `aria-label` if it's the same as the `textContent`

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts (hunk 3 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1149]: we won't have the elements at that time so don't think so

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts]: neat 😄

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 6]
```diff
@@ -1108,13 +1111,54 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
...
+				replaceChildren = false;
+			} else {
+				this._bufferElementFragment.appendChild(header);
+				this._bufferElementFragment.appendChild(output);
+			}
+		}
+		if (header) {
+			// focus the cursor line's header
+			header.tabIndex = 0;
+		}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1152]: Can we move this stuff into `_provideBufferElements`'s implementation? Consider the user manually focusing the a11y buffer somehow, we should give xterm.js an up to date view when it requests it.

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1152]: Seems like quite an edge case that can be deferred

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1152]: https://github.com/microsoft/vscode/issues/173734

**Review by Tyriar — APPROVED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts (hunk 6 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:1152]: Thanks
