### PR TITLE
#82352 Implement sorting for search results

### LINKED ISSUE #82352: Filename number sort in search result
Like below, you can set the sort options in Settings, I also want to sort the file in search result.
image

---
https://github.com/Microsoft/vscode/issues/5066

### LINKED ISSUE #83252: debugger running MS Edge Dev sets navigator.webdriver
Issue Type: <b>Bug</b>

When I run the VSCode debugger against MS Edge Dev it sets `navigator.webdriver` to true.  This is not supposed to happen.  Doesn't happen if I run against Chrome.

Debugger configuration:

```
    {
      "name": "Edge with Webpack Debugging Server",
      "type": "edge",
      "version": "dev",
      "request": "launch",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceRoot}/src",
      "userDataDir": "${workspaceRoot}/.chrome",
      // "trace": true,
      "sourceMaps": true,
      "smartStep": true,
      "skipFiles": [
        "${workspaceFolder}/src/node_modules/tslib/*.js",
      ],
      "sourceMapPathOverrides": {
        "webpack:///./src/*": "${webRoot}/*"
      },
      "runtimeArgs": [
        "--disable-session-crashed-bubble",
        "--disable-infobars"
      ],
      "internalConsoleOptions": "openOnSessionStart"
    },
```

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (7.94GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/dkent/Documents/Projects/GitHub/DAOStack/alchemy|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.1
EditorConfig|Edi|0.14.2
vscode-npm-script|eg2|0.3.9
vscode-pull-request-github|Git|0.12.0
vscode-react-typescript|inf|1.3.1
vscode-edge-devtools|ms-|1.0.4
remote-wsl|ms-|0.39.9
powershell|ms-|2019.9.0
typescript-javascript-grammar|ms-|0.0.53
debugger-for-chrome|msj|4.12.0
debugger-for-edge|msj|1.0.12
vscode-react-native|msj|0.12.1
code-settings-sync|Sha|3.4.3
shell-launcher|Tyr|0.3.0

</details>

### PR DESCRIPTION
**Pull request by jzyrobert**
This PR fixes #82352

Added a setting to allow sorting of search results.
Demo:
wKM1bhwi6K

The following are the possible options:

- **default**: As before, sorts by folder path first and then by file name. Uses `compareFileNames` to correct the ordering of numeral files (e.g. file1 is now in front of file10)
- **filesOnly**: Ignore the path name and sort only by file name
- **type**: Sort by extension name (Taken from Explorer sort)
- **modified**: Sort by last modified date (Taken from Explorer sort)
- **countDescending**: Sort by most results per file
- **countAscending**: Sort by least results per file (Should these fallback to name if results match?)

The `modified` sorting is implemented as follows:

- Whenever `refreshTree` is called, we ensure that if the `sortOrder === modified` all `fileMatch` items have a existing `IFileStatWithMetaData`, or it will retrieve it.
- Whenever `onFilesChanged` is called, modified files are retrieved and have their `fileStat` updated.
- Whenever `sortOrder` is set away from `modified`, remove `fileStat` information so it is re-calculated when it is set to `modified again`.

I think this is fair on performance, always tracking all meta-data would be performance intensive.
I'm not sure how I would add tests for the modified/count settings as you would have to set several properties.

### CODE REVIEW

**Comment by jzyrobert** [comment]
Whoops mis-spelled the issue number

**Comment by jzyrobert** [comment]
Things to look at:

- Did the path comparison break on other OS?
- Add a way to re-sort the tree elements without having to recreate them?

**Comment by jzyrobert** [comment]
So it turns out that:

- The searchViewlet.test.ts have been wrong all the time, C:\ was being added to each path even though the hard-coded paths already had C:\
Code_GRNr8aX8PO
- The tests use hard-coded windows paths which leads to incorrect behaviour on posix
- `FileMatch.name()` calls `getBaseLabel` which calls `basename` from `resources.ts`. @aeschli committed the fact that [only non-file URIs should call this function](https://github.com/microsoft/vscode/commit/8f2a6fe3f51cc8371e1868b975e1057e105e7fcd) so I think something went wrong while creating the `FileMatch` class.
- @bpasero committed a fix for this [here](https://github.com/microsoft/vscode/commit/97bfb45f8723f26a13e81804efee6f111541f067), however this was [reverted right away](https://github.com/microsoft/vscode/commit/d3b57e3bf1b2a6fc49179a7b7dc07492e978a809).

I have:

- Corrected the tests to use windows/posix paths
- Added a new `getFileBaseLabel` and `fileBaselabel` function to bypass this and call `paths.basename` without forcing it to be posix. I assume that a function to get the filename from a file URI already exists somewhere, if someone could point me to it?

**Comment by jeanp413** [comment]
@jzyrobert The URI class [converts](https://github.com/microsoft/vscode/blob/2bb6cfc16a88281b75cfdaced340308ff89a849e/src/vs/base/common/uri.ts#L307) `\` characters to `/` for windows paths so `getFileBaseLabel` should be fine.

**Comment by aeschli** [comment]
Please keep using resource.getBaseName. It's designed to work for any schema, also for the file scheme.

**Comment by jzyrobert** [comment]
I see, thanks guys.
I will see if I can make some more improvements on this.

File: src/vs/workbench/contrib/search/common/searchModel.ts [hunk 1]
```diff
@@ -406,6 +409,19 @@ export class FileMatch extends Disposable implements IFileMatch {
 		}
 	}
 
+	async resolveFileStat(fileService: IFileService): Promise<void> {
+		this._fileStat = await fileService.resolve(this.resource, { resolveMetadata: true });
+		return Promise.resolve();
```
Comment (roblourens) [inline src/vs/workbench/contrib/search/common/searchModel.ts]: You don't need to explictly return a promise in an `async` function, this line can be removed.

**Review by roblourens — APPROVED** [review]
This looks awesome, thanks for the PR! I am actually not clear what `getBaseName` refers to but it sounds like you are on top of it

File: src/vs/workbench/contrib/search/browser/searchView.ts [hunk 2]
```diff
@@ -1757,6 +1788,28 @@ export class SearchView extends ViewletPane {
 		super.saveState();
 	}
 
+	private async retrieveFileStats(): Promise<void> {
+		for (const fileMatch of this.searchResult.matches()) {
+			if (!fileMatch.fileStat) {
+				await fileMatch.resolveFileStat(this.fileService);
+			}
+		}
+		return Promise.resolve(undefined);
```
Comment (JacksonKearl) [inline src/vs/workbench/contrib/search/browser/searchView.ts]: Again here, you don't need to explicity return a promise in async functions.

File: src/vs/workbench/contrib/search/browser/searchView.ts [hunk 3]
```diff
@@ -1678,14 +1700,23 @@ export class SearchView extends ViewletPane {
 	}
 
 	private onFilesChanged(e: FileChangesEvent): void {
-		if (!this.viewModel || !e.gotDeleted()) {
+		if (this.searchConfig.sortOrder !== 'modified' && (!this.viewModel || !e.gotDeleted())) {
```
Comment (JacksonKearl) [inline src/vs/workbench/contrib/search/browser/searchView.ts]: Should this be `||`? Otherwise `const matches = this.viewModel.searchResult.matches();` below will throw when the search order is modified but the `viewModel` is `undefined`

File: src/vs/workbench/contrib/search/browser/searchView.ts [hunk 4]
```diff
@@ -1757,6 +1788,28 @@ export class SearchView extends ViewletPane {
...
+			if (!fileMatch.fileStat) {
+				await fileMatch.resolveFileStat(this.fileService);
+			}
+		}
+		return Promise.resolve(undefined);
+	}
+
+	private async updateFileStats(elements: FileMatch[]): Promise<void> {
+		for (const fileMatch of elements) {
+			await fileMatch.resolveFileStat(this.fileService);
```
Comment (JacksonKearl) [inline src/vs/workbench/contrib/search/browser/searchView.ts]: This will check each file syncronously. You might consider using Promise.all to run these in parallel.

Comment (jzyrobert) [reply src/vs/workbench/contrib/search/browser/searchView.ts]: Thanks, I was going to look into that

File: src/vs/workbench/contrib/search/common/searchModel.ts [hunk 5]
```diff
@@ -418,6 +434,7 @@ export interface IChangeEvent {
 	elements: FileMatch[];
 	added?: boolean;
 	removed?: boolean;
+	modified?: boolean;
```
Comment (JacksonKearl) [inline src/vs/workbench/contrib/search/common/searchModel.ts]: Is this used?

File: src/vs/workbench/services/search/common/search.ts [hunk 6]
```diff
@@ -311,6 +311,17 @@ export class OneLineRange extends SearchRange {
 	}
 }
 
+export const SearchSortOrderConfiguration = {
```
Comment (JacksonKearl) [inline src/vs/workbench/services/search/common/search.ts]: These two can be unified into a single `const enum`. Following that, the `== 'modified'`-style checks elsewhere should be changed to `== SearchSortOrder.Modified`. Also we aren't super consistent about `CAPS_CASE` vs. `PascalCase` for `const enums` in elsewhere in vscode, but I think here `PascalCase` feels better. Up to you.

**Review by JacksonKearl — CHANGES_REQUESTED** [review]
Thanks for working on this! I have left some comments throughout.

File: src/vs/workbench/contrib/search/browser/search.contribution.ts [hunk 7]
```diff
@@ -823,7 +823,21 @@ configurationRegistry.registerConfiguration({
...
 			description: nls.localize('search.enableSearchEditorPreview', "Experimental: When enabled, allows opening workspace search results in an editor.")
-		}
+		},
+		'search.sortOrder': {
+			'type': 'string',
+			'enum': [SearchSortOrderConfiguration.DEFAULT, SearchSortOrderConfiguration.FILES_ONLY, SearchSortOrderConfiguration.TYPE, SearchSortOrderConfiguration.MODIFIED, SearchSortOrderConfiguration.COUNT_DESCENDING, SearchSortOrderConfiguration.COUNT_ASCENDING],
+			'default': SearchSortOrderConfiguration.DEFAULT,
+			'enumDescriptions': [
+				nls.localize('searchSortOrder.default', 'Results are sorted by folder and file names, in alphabetical order.'),
+				nls.localize('searchSortOrder.filesOnly', 'Results are sorted by file names ignoring folder order, in alphabetical order.'),
```
Comment (roblourens) [inline src/vs/workbench/contrib/search/browser/search.contribution.ts]: I think a better name for this one would be `fileNames`

**Comment by jzyrobert** [comment]
@roblourens @JacksonKearl I've made the requested changes.

I went with the object + type initially instead of the enum because the explorer sort uses that, should that be refactored into an enum too?

I also did not see an easy way to retrieve the elements out of the tree for re-ordering, is it an acceptable performance hit to resolve the search results every time when a file match count is updated?

**Comment by JacksonKearl** [comment]
@jzyrobert We probably don't want to touch Explorer files in this, as it would add another reviewer and complexity just for a minor refactoring. 

> is it an acceptable performance hit to resolve the search results every time when a file match count is updated?

What do you mean by "resolve"? The search isn't run again, correct? Are you referring to this
```ts
	// If updated counts affect our search order, re-sort the view.
			if (this.searchConfig.sortOrder === SearchSortOrder.CountAscending ||
				this.searchConfig.sortOrder === SearchSortOrder.CountDescending) {
				this.tree.setChildren(null, this.createResultIterator(collapseResults));
			}
```
? 


That shouldn't be a particularly expensive operation. I played around with it and even with the max of 10000 results I didn't notice a problem. If it comes up as an issue we can look at it then.

I should have been more clear about the `const enum` thing, you need to additionally declare the values, or else they default to numbers:
```ts
export const enum SearchSortOrder {
	Default = 'default',
	FileNames = 'fileNames',
	Type = 'type',
	Modified = 'modified',
	CountDescending = 'countDescending',
	CountAscending = 'countAscending'
}
```

**Review by JacksonKearl — APPROVED** [review]
LGTM conditional on the 
```ts
export const enum SearchSortOrder {
	Default = 'default',
	FileNames = 'fileNames',
	Type = 'type',
	Modified = 'modified',
	CountDescending = 'countDescending',
	CountAscending = 'countAscending'
}
```

File: src/vs/workbench/contrib/search/browser/searchView.ts [hunk 8]
```diff
@@ -1757,6 +1789,22 @@ export class SearchView extends ViewPane {
 		super.saveState();
 	}
 
+	private async retrieveFileStats(): Promise<void> {
+		const files = this.searchResult.matches().filter(f => !f.fileStat).map(f => f.resolveFileStat(this.fileService));
+		await Promise.all(files);
+	}
+
+	private async updateFileStats(elements: FileMatch[]): Promise<void> {
```
Comment (roblourens) [inline src/vs/workbench/contrib/search/browser/searchView.ts]: Looks like it's updating all file stats, when just `elements` would be preferable

**Review by roblourens — APPROVED** [review]
> is it an acceptable performance hit to resolve the search results every time when a file match count is updated?

Or if you are referring to resolving file stats, then I think it should only be done once per search. If I am reading the code correctly, it looks like that is the case now right?

**Comment by jzyrobert** [comment]
@JacksonKearl

> @jzyrobert We probably don't want to touch Explorer files in this, as it would add another reviewer and complexity just for a minor refactoring.

I could make it another PR if this is refactoring that should be done.

> That shouldn't be a particularly expensive operation. I played around with it and even with the max of 10000 results I didn't notice a problem. If it comes up as an issue we can look at it then.

Sounds good. I tried it as well with the maximum results and it was very fast, but I have a (and you probably do) quite powerful machine, and I was thinking of users with older CPUs.

> I should have been more clear about the `const enum` thing, you need to additionally declare the values, or else they default to numbers:
> 
> ```ts
> export const enum SearchSortOrder {
> 	Default = 'default',
> 	FileNames = 'fileNames',
> 	Type = 'type',
> 	Modified = 'modified',
> 	CountDescending = 'countDescending',
> 	CountAscending = 'countAscending'
> }
> ```

I see the values are used for the actual option values, should have checked for that.

@roblourens 

> Looks like it's updating all file stats, when just `elements` would be preferable

`const files = this.searchResult.matches().filter(f => !f.fileStat).map(f => f.resolveFileStat(this.fileService));`

The matches are filtered for those that don't already have a fileStat file.
This is called during `refreshTree` so that we ensure all files _do_ have a fileStat (maybe if new ones were added) if the setting is "modified", but not every file stat is re-calculated.

It relies on `onFilesChanged` updating the file stats for files that have changed, so it is kept up to date.

**Comment by roblourens** [comment]
I'm commenting on the one that does

```
		const files = this.searchResult.matches().map(f => f.resolveFileStat(this.fileService));
```

and the function is already taking `elements` which, I think, are the elements that need to be updated

**Comment by jzyrobert** [comment]
> I'm commenting on the one that does
> 
> ```
> 		const files = this.searchResult.matches().map(f => f.resolveFileStat(this.fileService));
> ```
> 
> and the function is already taking `elements` which, I think, are the elements that need to be updated

Oh I see, sorry about that. Yes you're right, I forgot to correct the mapping.
