### PR TITLE
fix: inheriting NODE_OPTIONS on macOS with integrated terminal

### LINKED ISSUE #204005: Warning about Node.js environment variables on launch
Type: <b>Bug</b>

If you have a `NODE_EXTRA_CA_CERTS` environment variable in place, then when launching VS Code from a command line, a warning message is displayed:

`[0201/100616.044843:ERROR:node_main.cc(135)] Node.js environment variables are disabled because this process is invoked by other apps.`

The extra certificates are required for our environment to support proxy/VPN connectivity. Ideally these values _would be used_ in VS Code; but, at the very least, the warning shouldn't show up on the console during launch.

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:29:11.933Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|32.00GB (3.50GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 1021646e-a5d4-4a1c-bf5d-3f1296f9cf93|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30951795
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928

```

</details>

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes https://github.com/microsoft/vscode/issues/204005

With https://github.com/electron/electron/pull/40770 `NODE_OPTIONS` and `NODE_REPL_EXTERNAL_MODULE` will be removed if the application launching the VS Code application does not share the same codesign attributes. This is to prevent sandboxed applications on macOS from bypassing the sandbox by using the `ELECTRON_RUN_AS_NODE` mode of our application.

One downside with the detection is that launching the application from CLI will remove these variables if the user had set them in their terminal config files, so any external applications like nodejs binary cannot use these variables from integrated terminal if shell integration is not in play. This patch adds a workaround to temporarily store the variables in `VSCODE_` and restore them in the terminal environment.

Alternative take on https://github.com/microsoft/vscode/pull/204396 /cc @forivall

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts [hunk 1]
```diff
@@ -269,6 +269,26 @@ export async function createTerminalEnvironment(
...
+		// We should restore the following environment variables when a user
+		// launches the application using the CLI so that integrated terminal
+		// can still inherit these variables.
+		// We are not bypassing the restrictions implied in https://github.com/electron/electron/pull/40770
+		// since this only affects integrated terminal and not the application itself.
+		if (isMacintosh) {
+			// Restore NODE_OPTIONS if it was set
+			if (env['VSCODE_NODE_OPTIONS']) {
+				env['NODE_OPTIONS'] = env['VSCODE_NODE_OPTIONS'];
+				delete env['VSCODE_NODE_OPTIONS'];
```
Comment (deepak1556) [inline src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts:282]: `sanitizeProcessEnvironment` will remove `VSCODE_` variables, this is not necessary but no harm in being explicit.

**Review by bpasero — COMMENTED** [review]
Curious why we would only do this on macOS and not other platforms?

**Comment by deepak1556** [comment]
The equivalent on windows would be app container but we don't have a demonstration of similar issue there. This is only an issue on macOS (where we also got the report) since LaunchServices allows calling into an unsandboxed app from a sandboxed app.

**Review by bpasero — APPROVED** [review]

File: src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts (hunk 1 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts:282]: We do this so as to not leak our own `NODE_OPTIONS` into terminal/debug processes where it could cause problems.

**Review by Tyriar — APPROVED** [review]
fyi @connor4312 in case this new NODE_OPTIONS info is going to break JS debug terminals.

**Comment by GBrachetta** [comment]
Will this be on 1.87?
So far (1.86.1) the issue is still there.

**Comment by deepak1556** [comment]
@GBrachetta yes this will be on `1.87` and latest insiders should have the fixes. I will see if we can backport to `1.86.2` for next week but that will require some runtime changes as well to include the changes mentioned in https://github.com/microsoft/vscode/issues/204005#issuecomment-1935121440
