### PR TITLE
Pass the check if any one of the library (of the arch) satisfies the requirement.

### LINKED ISSUE #9475: check-requirements.sh fails when attaching to container
This issue is container specific, I'm trying to use gcc:13.2 docker image.

The extension is running a bunch of code when attaching to containers, among other things, this script:
```
~/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/bin/helpers/check-requirements.sh
```
Since I've updated VSCode yesterday, this script fails without any error messages.

As far as I understand, this script tries to find an instance of libstdc++.so.6, and runs this ( in several steps, not in one line ):
```
/sbin/ldconfig -p | grep 'libstdc++.so.6' | grep x86-64
```
In most/some containers this will return one path, but in this image this returns two, and that is not handled in this script.
Same result with extension version 'v0.339.0 (pre-release)'

- VSCode Version: 1.86.0
- Local OS Version: Windows 11 23H2 22631.3007
- Remote OS Version: Debian GNU/Linux 12 (bookworm)
- Remote Extension/Connection Type: Container

<details>
  <summary>Logs:</summary>

```
[248 ms] Dev Containers 0.338.1 in VS Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937).
[248 ms] Start: Resolving Remote
[249 ms] Setting up container: /attach-to-me
[251 ms] Start: Run: docker inspect --type container /attach-to-me
[477 ms] Start: Run: wsl -l -v
[605 ms] Start: Run: wsl -d Ubuntu-22.04 -e /bin/sh -c echo ~
[805 ms] Start: Run: wsl -d Ubuntu-22.04 -e /bin/sh -c cd '/home/<username>' && /bin/sh
[812 ms] Start: Run in host: id -un
[956 ms] <username>
[957 ms] 
[957 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd '<username>' || grep -E '^<username>|^[^:]*:[^:]*:<username>:' /etc/passwd || true)
[960 ms] Start: Run in host: echo ~
[961 ms] /home/<username>
[961 ms] 
[962 ms] Start: Run in host: test -x '/home/<username>/.vscode-remote-containers/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/node'
[963 ms] 
[963 ms] 
[963 ms] Exit code 1
[964 ms] Start: Run in host: test -x '/home/<username>/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/node'
[965 ms] 
[965 ms] 
[965 ms] Start: Run in host: test -f '/home/<username>/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/node_modules/node-pty/package.json'
[966 ms] 
[967 ms] 
[967 ms] Start: Run in host: test -f '/home/<username>/.vscode-remote-containers/dist/vscode-remote-containers-server-0.338.1.js'
[968 ms] 
[969 ms] 
[972 ms] userEnvProbe: loginInteractiveShell (default)
[972 ms] userEnvProbe: not found in cache
[973 ms] userEnvProbe shell: /bin/bash
[1133 ms] userEnvProbe PATHs:
Probe:     '/home/<username>/.local/bin:/home/<username>/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/c/Windows/System32/OpenSSH/:/c/Program Files/Git/cmd:/c/Program Files/Docker/Docker/resources/bin:/c/Program Files/Tailscale/:/c/Program Files/PowerShell/7/:/c/Program Files/Conan/conan:/c/Users/<username>/AppData/Local/Programs/Python/Python312/Scripts/:/c/Users/<username>/AppData/Local/Programs/Python/Python312/:/c/Users/<username>/AppData/Local/Programs/Python/Launcher/:/c/Users/<username>/AppData/Local/Microsoft/WindowsApps:/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code/bin:/c/Users/<username>/AppData/Roaming/Code/User/globalStorage/ms-vscode-remote.remote-containers/cli-bin:/snap/bin:/scripts/'
Container: None
[1145 ms] Start: Run in Host: wslpath -w /run/user/1000/wayland-0
[1152 ms] Start: Check Docker is running
[1153 ms] Start: Run: docker version
[1401 ms] Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:48 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.25.2 (129061)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[1409 ms] Start: Run: C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\Users\<username>\tmp\vscode\ext\ms-vscode-remote.remote-containers-0.338.1\dist\spec-node\devContainersSpecCLI.js set-up --container-id fa71d9d4eb61c3ebbd4059fff096bcff29a8fd204d6f6ecc5db501c75e21d5e0 --user-data-folder c:\Users\<username>\tmp\vscode\data\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-5a631db1-fe55-4b91-b9c5-122fd105efda1706866727842 --log-level debug --log-format json --default-user-env-probe loginInteractiveShell --skip-post-create
[2008 ms] @devcontainers/cli 0.56.0. Node.js v18.17.1. win32 10.0.22631 x64.
[2008 ms] Start: Run: docker buildx version
[2664 ms] github.com/docker/buildx v0.11.2-desktop.5 f20ec1393426619870066baba9618cf999063886
[2664 ms] 
[2664 ms] Start: Run: docker inspect --type container fa71d9d4eb61c3ebbd4059fff096bcff29a8fd204d6f6ecc5db501c75e21d5e0
[2910 ms] Start: Inspecting container
[2910 ms] Start: Run: docker inspect --type container fa71d9d4eb61c3ebbd4059fff096bcff29a8fd204d6f6ecc5db501c75e21d5e0
[3138 ms] Start: Run in container: /bin/sh
[3149 ms] Start: Run in container: uname -m
[3408 ms] x86_64
[3408 ms] 
[3408 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[3414 ms] PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[3414 ms] 
[3414 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[3420 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcEnvironmentMarker'
[3425 ms] 
[3425 ms] 
[3425 ms] Exit code 1
[3425 ms] Start: Run in container: test ! -f '/var/devcontainer/.patchEtcEnvironmentMarker' && set -o noclobber && mkdir -p '/var/devcontainer' && { > '/var/devcontainer/.patchEtcEnvironmentMarker' ; } 2> /dev/null
[3438 ms] 
[3438 ms] 
[3439 ms] Start: Run in container: cat >> /etc/environment <<'etcEnvrionmentEOF'
[3445 ms] 
[3445 ms] 
[3446 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcProfileMarker'
[3451 ms] 
[3451 ms] 
[3451 ms] Exit code 1
[3452 ms] Start: Run in container: test ! -f '/var/devcontainer/.patchEtcProfileMarker' && set -o noclobber && mkdir -p '/var/devcontainer' && { > '/var/devcontainer/.patchEtcProfileMarker' ; } 2> /dev/null
[3459 ms] 
[3459 ms] 
[3459 ms] Start: Run in container: sed -i -E 's/((^|\s)PATH=)([^\$]*)$/\1${PATH:-\3}/g' /etc/profile || true
[3468 ms] 
[3468 ms] 
[3485 ms] Start: Run: C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\Users\<username>\tmp\vscode\ext\ms-vscode-remote.remote-containers-0.338.1\dist\spec-node\devContainersSpecCLI.js read-configuration --container-id fa71d9d4eb61c3ebbd4059fff096bcff29a8fd204d6f6ecc5db501c75e21d5e0 --log-level debug --log-format json --include-merged-configuration --mount-workspace-git-root
[3895 ms] @devcontainers/cli 0.56.0. Node.js v18.17.1. win32 10.0.22631 x64.
[3895 ms] Start: Run: docker inspect --type container fa71d9d4eb61c3ebbd4059fff096bcff29a8fd204d6f6ecc5db501c75e21d5e0
[4100 ms] Start: Inspecting container
[4100 ms] Start: Run: docker inspect --type container fa71d9d4eb61c3ebbd4059fff096bcff29a8fd204d6f6ecc5db501c75e21d5e0
[4304 ms] Start: Run in container: /bin/sh
[4320 ms] Start: Run in container: uname -m
[4568 ms] x86_64
[4568 ms] 
[4568 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[4575 ms] PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[4576 ms] 
[4576 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[4584 ms] Start: Run in container: test -d '/root/.vscode-server'
[4594 ms] 
[4595 ms] 
[4595 ms] Exit code 1
[4595 ms] Start: Run in container: test -d '/root/.vscode-remote'
[4599 ms] 
[4600 ms] 
[4600 ms] Exit code 1
[4600 ms] Start: Run in container: test ! -f '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[4618 ms] 
[4618 ms] 
[4619 ms] Start: Run in container: cat /root/.vscode-server/data/Machine/settings.json
[4627 ms] 
[4627 ms] cat: /root/.vscode-server/data/Machine/settings.json: No such file or directory
[4627 ms] Exit code 1
[4628 ms] Start: Run in container: test -d '/root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937'
[4636 ms] 
[4637 ms] 
[4637 ms] Exit code 1
[4638 ms] Installing VS Code Server for commit 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
[4638 ms] Start: Installing VS Code Server
[4639 ms] Start: Run in container: mkdir -p /root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937_1706866733098
[4646 ms] 
[4646 ms] 
[4696 ms] Start: Run in container: (dd iflag=fullblock bs=8192 count=6987 2>/dev/null; dd iflag=fullblock bs=7632 count=1 2>/dev/null) | tar --no-same-owner -xz -C /root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937_1706866733098
[6579 ms] 
[6580 ms] 
[6580 ms] Start: Run in container: mv -n /root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937_1706866733098/* /root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937 && rmdir /root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937_1706866733098
[6593 ms] 
[6593 ms] 
[6594 ms] Start: Run in container: test -x '/root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/bin/helpers/check-requirements.sh'
[6603 ms] 
[6603 ms] 
[6603 ms] Start: Run in container: '/root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/bin/helpers/check-requirements.sh'
[6633 ms] 
[6633 ms] 
[6633 ms] Exit code 1
[6638 ms] Command in container failed: '/root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/bin/helpers/check-requirements.sh'
[6638 ms] Exit code 1

```

</details>

Steps to Reproduce:

1. `docker run -it --rm --name attach-to-me gcc:13.2 bash`
2. In VSCode, ctrl+shift+p, type `Dev Containers: Attach to Running Container...`, select container `attach-to-me`

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by owlhuang**
Pass the check if any one of the library (of the arch) satisfies the requirement.

Fixes https://github.com/microsoft/vscode-remote-release/issues/9475

### CODE REVIEW

**Comment by owlhuang** [comment]
@microsoft-github-policy-service agree

**Comment by gjsjohnmurray** [comment]
Pinging @deepak1556

File: resources/server/bin/helpers/check-requirements-linux.sh [hunk 1]
```diff
@@ -90,24 +94,28 @@ if [ -z "$(ldd --version 2>&1 | grep 'musl libc')" ]; then
...
         libc_version=$(cat "$libc_real_path" | sed -n 's/.*release version \([0-9]\+\.[0-9]\+\).*/\1/p')
         if [ "$(printf '%s\n' "2.28" "$libc_version" | sort -V | head -n1)" = "2.28" ]; then
             found_required_glibc=1
-        else
-            echo "Warning: Missing GLIBC >= 2.28! from $libc_real_path"
+            break
         fi
+	libc_path="$(echo "$libc_path" | tail -n +2)"    # remove first line
+    done
+    if [ -z "$libc_path" ]; then
```
Comment (deepak1556) [inline resources/server/bin/helpers/check-requirements-linux.sh:117]:
```suggestion
    if [ "$found_required_glibc" = "0" ]; then
```

File: resources/server/bin/helpers/check-requirements-linux.sh [hunk 2]
```diff
@@ -90,24 +94,28 @@ if [ -z "$(ldd --version 2>&1 | grep 'musl libc')" ]; then
...
+        libc_path_line="$(echo "$libc_path" | head -n1)"
+	libc_real_path=$(readlink -f "$libc_path_line")
         libc_version=$(cat "$libc_real_path" | sed -n 's/.*release version \([0-9]\+\.[0-9]\+\).*/\1/p')
         if [ "$(printf '%s\n' "2.28" "$libc_version" | sort -V | head -n1)" = "2.28" ]; then
             found_required_glibc=1
-        else
-            echo "Warning: Missing GLIBC >= 2.28! from $libc_real_path"
+            break
         fi
+	libc_path="$(echo "$libc_path" | tail -n +2)"    # remove first line
```
Comment (deepak1556) [inline resources/server/bin/helpers/check-requirements-linux.sh:115]:
```suggestion
	libc_path=$(echo "$libc_path" | tail -n +2)    # remove first line
```

File: resources/server/bin/helpers/check-requirements-linux.sh [hunk 3]
```diff
@@ -90,24 +94,28 @@ if [ -z "$(ldd --version 2>&1 | grep 'musl libc')" ]; then
...
     else
         echo "Warning: Can't find libc.so or ldconfig, can't verify libc version"
     fi
 
-    if [ -n "$libc_path" ]; then
+    while [ -n "$libc_path" ]; do
 		# Rather than trusting the output of ldd --version (which is not always accurate)
 		# we instead use the version of the cached libc.so.6 file itself.
-        libc_real_path=$(readlink -f "$libc_path")
+        libc_path_line="$(echo "$libc_path" | head -n1)"
```
Comment (deepak1556) [inline resources/server/bin/helpers/check-requirements-linux.sh:108]:
```suggestion
        libc_path_line=$(echo "$libc_path" | head -n1)
```

File: resources/server/bin/helpers/check-requirements-linux.sh [hunk 4]
```diff
@@ -56,26 +56,30 @@ elif [ -f /sbin/ldconfig ]; then
...
     libstdcpp_version=$(echo "$libstdcpp_real_path" | awk -F'\\.so\\.' '{print $NF}')
     if [ "$(printf '%s\n' "6.0.25" "$libstdcpp_version" | sort -V | head -n1)" = "6.0.25" ]; then
         found_required_glibcxx=1
-    else
-        echo "Warning: Missing GLIBCXX >= 3.4.25! from $libstdcpp_real_path"
+        break
     fi
+    libstdcpp_path="$(echo "$libstdcpp_path" | tail -n +2)"    # remove first line
+done
+if [ -z "$libstdcpp_path" ]; then
```
Comment (deepak1556) [inline resources/server/bin/helpers/check-requirements-linux.sh:81]:
```suggestion
if [ "$found_required_glibcxx" = "0" ]; then
```

File: resources/server/bin/helpers/check-requirements-linux.sh [hunk 5]
```diff
@@ -56,26 +56,30 @@ elif [ -f /sbin/ldconfig ]; then
...
+    libstdcpp_path_line="$(echo "$libstdcpp_path" | head -n1)"
+    libstdcpp_real_path=$(readlink -f "$libstdcpp_path_line")
     libstdcpp_version=$(echo "$libstdcpp_real_path" | awk -F'\\.so\\.' '{print $NF}')
     if [ "$(printf '%s\n' "6.0.25" "$libstdcpp_version" | sort -V | head -n1)" = "6.0.25" ]; then
         found_required_glibcxx=1
-    else
-        echo "Warning: Missing GLIBCXX >= 3.4.25! from $libstdcpp_real_path"
+        break
     fi
+    libstdcpp_path="$(echo "$libstdcpp_path" | tail -n +2)"    # remove first line
```
Comment (deepak1556) [inline resources/server/bin/helpers/check-requirements-linux.sh:79]:
```suggestion
    libstdcpp_path=$(echo "$libstdcpp_path" | tail -n +2)    # remove first line
```

File: resources/server/bin/helpers/check-requirements-linux.sh [hunk 6]
```diff
@@ -56,26 +56,30 @@ elif [ -f /sbin/ldconfig ]; then
...
 fi
 
-if [ -n "$libstdcpp_path" ]; then
+while [ -n "$libstdcpp_path" ]; do
 	# Extracts the version number from the path, e.g. libstdc++.so.6.0.22 -> 6.0.22
 	# which is then compared based on the fact that release versioning and symbol versioning
 	# are aligned for libstdc++. Refs https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html
 	# (i-e) GLIBCXX_3.4.<release> is provided by libstdc++.so.6.y.<release>
-    libstdcpp_real_path=$(readlink -f "$libstdcpp_path")
+    libstdcpp_path_line="$(echo "$libstdcpp_path" | head -n1)"
```
Comment (deepak1556) [inline resources/server/bin/helpers/check-requirements-linux.sh:72]:
```suggestion
    libstdcpp_path_line=$(echo "$libstdcpp_path" | head -n1)
```

**Review by deepak1556 — COMMENTED** [review]
Makes sense, thanks!

**Comment by n8falke** [comment]
The loop over `libstdc++.so.6` works on my system. Looks good for me. Thanks.

I've no system with more than one `libc.so.6` (which is probably very problematic).

**Comment by deepak1556** [comment]
Thanks for confirming!

**Comment by owlhuang** [comment]
@deepak1556 The suggestions all look good to me.  Do I need to commit the suggestions or resolve the comments?

**Comment by deepak1556** [comment]
Feel free to do either, commit suggestions from github or make the changes locally and commit them (which will also resolve the comments)

**Review by deepak1556 — DISMISSED** [review]
LGTM, thanks!

**Comment by owlhuang** [comment]
I like your exit checks.  Easier to read!  Thanks for all the efforts on VSCode!

**Review by DonJayamanne — DISMISSED** [review]

**Review by rzhao271 — APPROVED** [review]

**Review by connor4312 — APPROVED** [review]
