### PR TITLE
Fixes https://github.com/microsoft/monaco-editor/issues/3090

### LINKED ISSUE #3090: [Bug] Markdown Errors On Mouse Clicks
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

###  Animated GIF of error

Pxzy1vu

### Actual Behavior

languageConfigurationRegistry.ts:129 Uncaught Error: Unexpected languageId whenever you click in a Markdown scenario

### Expected Behavior

No uncaught errors

### Additional Context

Running Chrome

### PR DESCRIPTION
**Pull request by hediet**
Fixes https://github.com/microsoft/monaco-editor/issues/3090

### CODE REVIEW

File: src/vs/editor/common/languages/languageConfigurationRegistry.ts [hunk 1]
```diff
@@ -127,7 +127,9 @@ function computeConfig(
 
 	if (!languageConfig) {
 		if (!languageService.isRegisteredLanguageId(languageId)) {
-			throw new Error(`Language id "${languageId}" is not configured nor known`);
+			// this happens for the null language, which can be returned by monarch.
```
Comment (Tyriar) [inline src/vs/editor/common/languages/languageConfigurationRegistry.ts:130]: Do you mean monaco?

**Review by Tyriar — APPROVED** [review]
