### PR TITLE
Blank Window on Dev Container (fix #220007)

### LINKED ISSUE #220007: Blank Window on Dev Container
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- 1.91.0
ea1445cc7016315d0f5728f8e8b12a45dc0a7286
x64
- OS Version: Fedora 40; Kernel 6.9.7 generic. Intel 1075H, Nvidia 3080 (Driver 550.78)

Steps to Reproduce:

1. VS-Code
2. Open folder with a `.devcontainer` file -> Blank Window.

Using `code --verbose`, i get the following repeated errors:

To begin with, the terminal is filled with:
```bash
[6943:0704/221245.080344:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unable to create workbench contribution 'workbench.contrib.nativeWorkingCopyBackupTracker'. TypeError: Cannot read properties of undefined (reading 'autoSave')", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
[6943:0704/221245.083270:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unable to create workbench contribution 'workbench.contrib.textFileEditorTracker'. TypeError: Cannot read properties of undefined (reading 'autoSave')", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
[6943:0704/221245.083423:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unable to create workbench contribution 'workbench.contrib.textFileSaveErrorHandler'. TypeError: Cannot read properties of undefined (reading 'autoSave')", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
[6943:0704/221245.084092:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unable to create workbench contribution 'workbench.contrib.dirtyFilesIndicator'. TypeError: Cannot read properties of undefined (reading 'autoSave')", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
[6943:0704/221245.084456:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unable to create workbench contribution 'workbench.contrib.preferencesActions'. TypeError: Cannot read properties of undefined (reading 'autoSave')", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
[6943:0704/221245.084743:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unable to create workbench contribution 'workbench.contrib.preferences'. TypeError: Cannot read properties of undefined (reading 'autoSave')", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
[6943:0704/221245.088145:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unable to create workbench contribution 'workbench.contrib.cellContentProvider'. TypeError: Cannot read properties of undefined (reading 'autoSave')", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
[6943:0704/221245.088416:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unable to create workbench contribution 'workbench.contrib.cellInfoContentProvider'. TypeError: Cannot read properties of undefined (reading 'autoSave')", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
[6943:0704/221245.089745:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unable to create workbench contribution 'workbench.contrib.replacePreviewContentProvider'. TypeError: Cannot read properties of undefined (reading 'autoSave')", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
[6943:0704/221245.090823:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unable to create workbench contribution 'workbench.contrib.linuxAccessibility'. TypeError: Cannot read properties of undefined (reading 'autoSave')", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
[6943:0704/221245.093957:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unable to create workbench contribution 'comments.input.contentProvider'. TypeError: Cannot read properties of undefined (reading 'autoSave')", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
[6943:0704/221245.094927:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unable to create workbench contribution 'workbench.contrib.editorAutoSave'. TypeError: Cannot read properties of undefined (reading 'autoSave')", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
[6943:0704/221245.095415:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unable to create workbench contribution 'workbench.contrib.editorStatus'. TypeError: Cannot read properties of undefined (reading 'autoSave')", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
[6943:0704/221245.095876:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unable to create workbench contribution 'workbench.contrib.userDataProfiles'. TypeError: Cannot read properties of undefined (reading 'autoSave')", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
```

Then, multiple errors of:
```bash
43:0704/221245.098860:INFO:CONSOLE(660)] "%c  ERR color: #f33 Cannot read properties of undefined (reading 'autoSave'): TypeError: Cannot read properties of undefined (reading 'autoSave')
```

Within those, there is:
```bash
Error: [UriError]: cannot call joinPath on URI without path
    at c.joinPath (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:138:47723)
    at v.joinPath (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:139:9208)
    at new I (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1247:20805)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2087:31334
    at Array.map (<anonymous>)
    at W.Eb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2087:31289)
    at W.qb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2087:25255)
    at W.jb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2087:24429)
    at async W.hb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2087:23122)
    at async W.initialize (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2087:21130)
    at async te.n (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2412:131957)
    at async Promise.all (index 0)
    at async te.j (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2412:131120)
    at async Promise.all (index 0)
    at async te.open (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2412:128582)
    at async vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.js:4:9561", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (7)
```

and the last error before output stops is:
```bash
[6943:0704/221245.430872:INFO:CONSOLE(660)] "%c  ERR color: #f33 Unknown actor MainThreadTask: Error: Unknown actor MainThreadTask
    at S (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1678:14480)
    at S.Q (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1678:14396)
    at S.M (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1678:13429)
    at S.L (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1678:12264)
    at d.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1678:10959)
    at l.B (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:732)
    at l.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:949)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:620:14823)
    at x.onmessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1693:8186)", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (660)
```

And this is the window throughout:
image

### PR DESCRIPTION
**Pull request by bpasero**

### CODE REVIEW

File: src/vs/workbench/contrib/files/browser/views/explorerView.ts [hunk 1]
```diff
@@ -660,7 +660,7 @@ export class ExplorerView extends ViewPane implements IExplorerView {
 		this.setContextKeys(stat);
 
 		if (stat) {
-			const enableTrash = this.configurationService.getValue<IFilesConfiguration>().files.enableTrash;
+			const enableTrash = Boolean(this.configurationService.getValue<IFilesConfiguration>().files?.enableTrash);
```
Comment (rzhao271) [inline src/vs/workbench/contrib/files/browser/views/explorerView.ts:663]: Alternatively, !!

**Review by rzhao271 — APPROVED** [review]
