### PR TITLE
fix: improve settings descriptions for actions triggered on save

### LINKED ISSUE #230051: Confusing settings descriptions about actions and auto save
### The problem
In VSCode settings, `editor.formatOnSave` setting has the following description:
> Format a file on save. A formatter must be available, the file must not be saved after delay, and the editor must not be shutting down.

"the file must not be saved after delay" part made me assume that the format on save feature will never work when `files.autoSave` is set to `afterDelay`.
But that's not true because the formatting is still applied when the file is saved explicitly.

I understand that what you're trying to communicate is that the formatting won't be applied _automatically_, when the file is saved automatically. But it can still be applied _manually_ when the file is explicitly saved.

The same is true for the descriptions of `notebook.formatOnSave` and `notebook.codeActionsOnSave` settings. `editor.codeActionsOnSave` is an outlier since it doesn't contain that part in the description, but the same is true for this option as well, so it can be updated for consistency.

Attaching related screencasts, to demonstrate.

`editor.formatOnSave` with auto save set to "off":

https://github.com/user-attachments/assets/d6c4a22e-d6dc-4bb5-8e83-fa9b83bd47e2

`editor.formatOnSave` with auto save set to "afterDelay":

https://github.com/user-attachments/assets/fce93c1a-fc9d-43f1-b3b4-e188b1b5bc05

### Does this issue occur when all extensions are disabled?
Yes

### System info

- VS Code Version: `1.93.1 (Universal)`
- OS Version: `Darwin arm64 23.6.0`
```
Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

Steps to Reproduce:

You can try to reproduce what is depicted in the [second video](https://github.com/user-attachments/assets/fce93c1a-fc9d-43f1-b3b4-e188b1b5bc05) above.

1. Set `editor.defaultFormatter` setting to `vscode.typescript-language-features`.
2. Enable `editor.formatOnSave` setting.
3. Set `files.autoSave` to `afterDelay`.
4. Open a TypeScript file, e.g. https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/files/browser/files.contribution.ts
5. Make a whitespace change, e.g. add a few spaces to the end of a line.
6. Save the file manually.
 
The file is not auto-formatted after step 5 even though the file is auto saved, but it is after step 6 (the whitespace added in step 5 is gone).

### PR DESCRIPTION
**Pull request by elias-pap**
closes #230051

### CODE REVIEW

**Comment by elias-pap** [comment]
@microsoft-github-policy-service agree

**Review by ThDev-only — APPROVED** [review]

File: src/vs/workbench/contrib/codeActions/browser/codeActionsContribution.ts [hunk 1]
```diff
@@ -64,7 +64,7 @@ const codeActionsOnSaveSchema: IConfigurationPropertySchema = {
 			items: { type: 'string' }
 		}
 	],
-	markdownDescription: nls.localize('editor.codeActionsOnSave', 'Run Code Actions for the editor on save. Code Actions must be specified and the editor must not be shutting down. Example: `"source.organizeImports": "explicit" `'),
+	markdownDescription: nls.localize('editor.codeActionsOnSave', 'Run Code Actions for the editor on save. Code Actions must be specified and the editor must not be shutting down. When [auto save](https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save) is set to `afterDelay`, Code Actions will run when the file is saved explicitly, not when saved automatically. Example: `"source.organizeImports": "explicit" `'),
```
Comment (justschen) [inline src/vs/workbench/contrib/codeActions/browser/codeActionsContribution.ts:67]: for this and all cases below, instead of pointing towards documentation, please point it towards the auto save setting

**Review by justschen — COMMENTED** [review]
Please also take a look at `editor.codeActions.triggerOnFocusChange`, which will save in certain scenarios:
1. auto save is `afterDelay`
2. editor code actions on save are set to `always`.
3. focus is changed 

note that this only works atm for editor code actions on save, and not notebooks.

File: src/vs/workbench/contrib/codeActions/browser/codeActionsContribution.ts (hunk 1 above)
Comment (justschen) [reply src/vs/workbench/contrib/codeActions/browser/codeActionsContribution.ts:67]: nit: change to `....will be run only when the file is saved explicitly.`

Comment (elias-pap) [reply src/vs/workbench/contrib/codeActions/browser/codeActionsContribution.ts]: Addressed in 2de9ac0 and 242ad96

**Comment by elias-pap** [comment]
> Please also take a look at `editor.codeActions.triggerOnFocusChange`, which will save in certain scenarios:

Not sure what you mean. This setting does not "save" in certain scenarios, it just triggers the code actions under some conditions, one of them being `auto save` is set to `afterDelay`. So the save happens automatically after delay, not from this setting.

**Comment by justschen** [comment]
@elias-pap sorry, that's what I meant. I added that setting a few iterations ago since users with `afterDelay` on wanted to still be able to run code actions. 

my point of bringing it up is because we don't mention that this setting which _will_ run code actions when the file isn't saved explicitly.

maybe adding a mention of this setting somehow could be helpful!

File: src/vs/workbench/contrib/codeActions/browser/codeActionsContribution.ts [hunk 2]
```diff
@@ -64,7 +64,7 @@ const codeActionsOnSaveSchema: IConfigurationPropertySchema = {
 			items: { type: 'string' }
 		}
 	],
-	markdownDescription: nls.localize('editor.codeActionsOnSave', 'Run Code Actions for the editor on save. Code Actions must be specified and the editor must not be shutting down. Example: `"source.organizeImports": "explicit" `'),
+	markdownDescription: nls.localize('editor.codeActionsOnSave', 'Run Code Actions for the editor on save. Code Actions must be specified and the editor must not be shutting down. When `#files.autoSave#` is set to `afterDelay`, Code Actions will only be run when the file is saved explicitly. Example: `"source.organizeImports": "explicit" `'),
```
Comment (justschen) [inline src/vs/workbench/contrib/codeActions/browser/codeActionsContribution.ts:67]: for this an all below:

```ts
markdownDescription: nls.localize('editor.codeActionsOnSave', 'Run Code Actions for the editor on save. 
Code Actions must be specified and the editor must not be shutting down. When {0} is set to `afterDelay`, 
Code Actions will only be run when the file is saved explicitly. Example: `"source.organizeImports": 
"explicit" `', '`#files.autoSave#`'),
```

**Comment by elias-pap** [comment]
> @elias-pap sorry, that's what I meant. I added that setting a few iterations ago since users with `afterDelay` on wanted to still be able to run code actions.

Right, that's what I had guessed.
> 
> my point of bringing it up is because we don't mention that this setting which _will_ run code actions when the file isn't saved explicitly.
> 
> maybe adding a mention of this setting somehow could be helpful, although it is getting a bit verbose

I agree that it's a bit overkill. These settings are called "formatOnSave" and "codeActionsOnSave", so it's better to focus on what happens _on save_ instead of repeating descriptions from other settings. The word "only" can be removed to avoid contradictions (`"will only be run when the file is saved explicitly"` -> `"will be run when the file is saved explicitly"`).

The point of this fix is to clarify that the user can both have autoSave -> afterDelay enabled, and format the file (or run code actions) by saving manually, at the same time.

**Review by rzhao271 — APPROVED** [review]

**Review by justschen — APPROVED** [review]
awesome! thanks for the patience, looks good to me 👍
