### PR TITLE
play terminal command failed signal when a command w non zero exit code is navigated to in accessible terminal view

### LINKED ISSUE #209580: play terminal failed command sound on navigation to command in accessible view
@jooyoungseo, I was thinking about it. Would it be useful if we played the terminal failed command sound as you navigate in the accessible view using `alt+up/down arrow` when it lands on a command with a non-zero exit code?

That way, you could quickly scan for the command with output you're interested in?

### PR DESCRIPTION
**Pull request by meganrogge**
fix #209580

### CODE REVIEW

File: src/vs/workbench/contrib/accessibility/browser/accessibilityConfiguration.ts [hunk 1]
```diff
@@ -242,7 +242,7 @@ const configuration: IConfigurationNode = {
 			...baseAlertProperty
 		},
 		[AccessibilityAlertSettingId.TerminalCommandFailed]: {
-			'markdownDescription': localize('announcement.terminalCommandFailed', "Indicates when a terminal command fails (non-zero exit code). Also see {0}.", '`#audioCues.terminalCommandFailed#`'),
+			'markdownDescription': localize('announcement.terminalCommandFailed', "Indicates when a terminal command fails (non-zero exit code). Also see {0}. This will ", '`#audioCues.terminalCommandFailed#`'),
```
Comment (meganrogge) [inline src/vs/workbench/contrib/accessibility/browser/accessibilityConfiguration.ts:245]:
```suggestion
			'markdownDescription': localize('announcement.terminalCommandFailed', "Indicates when a terminal command fails (non-zero exit code). Also see {0}.", '`#audioCues.terminalCommandFailed#`'),
```

File: src/vs/workbench/contrib/accessibility/browser/accessibilityConfiguration.ts [hunk 2]
```diff
@@ -428,14 +428,14 @@ const configuration: IConfigurationNode = {
...
+			'description': localize('accessibility.signals.terminalCommandFailed', "Plays a signal when a terminal command fails (non-zero exit code) or when a command with such an exit code is navigated to in the accessible view."),
 			'properties': {
 				'sound': {
-					'description': localize('accessibility.signals.terminalCommandFailed.sound', "Plays a sound when a terminal command fails (non-zero exit code)."),
+					'description': localize('accessibility.signals.terminalCommandFailed.sound', "Plays a sound when a terminal command fails (non-zero exit code) or when a command with such an exit code is navigated to in the accessible view.."),
 					...soundFeatureBase
 				},
 				'announcement': {
-					'description': localize('accessibility.signals.terminalCommandFailed.announcement', "Indicates when a terminal command fails (non-zero exit code)."),
+					'description': localize('accessibility.signals.terminalCommandFailed.announcement', "Indicates when a terminal command fails (non-zero exit code) or when a command with such an exit code is navigated to in the accessible view.."),
```
Comment (meganrogge) [inline src/vs/workbench/contrib/accessibility/browser/accessibilityConfiguration.ts:438]:
```suggestion
					'description': localize('accessibility.signals.terminalCommandFailed.announcement', "Indicates when a terminal command fails (non-zero exit code) or when a command with such an exit code is navigated to in the accessible view."),
```

File: src/vs/workbench/contrib/accessibility/browser/accessibilityConfiguration.ts [hunk 3]
```diff
@@ -428,14 +428,14 @@ const configuration: IConfigurationNode = {
 		},
 		'accessibility.signals.terminalCommandFailed': {
 			...signalFeatureBase,
-			'description': localize('accessibility.signals.terminalCommandFailed', "Plays a signal when a terminal command fails (non-zero exit code)."),
+			'description': localize('accessibility.signals.terminalCommandFailed', "Plays a signal when a terminal command fails (non-zero exit code) or when a command with such an exit code is navigated to in the accessible view."),
 			'properties': {
 				'sound': {
-					'description': localize('accessibility.signals.terminalCommandFailed.sound', "Plays a sound when a terminal command fails (non-zero exit code)."),
+					'description': localize('accessibility.signals.terminalCommandFailed.sound', "Plays a sound when a terminal command fails (non-zero exit code) or when a command with such an exit code is navigated to in the accessible view.."),
```
Comment (meganrogge) [inline src/vs/workbench/contrib/accessibility/browser/accessibilityConfiguration.ts:434]:
```suggestion
					'description': localize('accessibility.signals.terminalCommandFailed.sound', "Plays a sound when a terminal command fails (non-zero exit code) or when a command with such an exit code is navigated to in the accessible view."),
```

File: src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminal.accessibility.contribution.ts [hunk 4]
```diff
@@ -179,7 +181,11 @@ export class TerminalAccessibleViewContribution extends Disposable implements IT
 		if (!filteredCommands.length) {
 			return;
 		}
-		this._accessibleViewService.setPosition(new Position(filteredCommands[0].lineNumber, 1), true);
+		const command = filteredCommands[0];
+		this._accessibleViewService.setPosition(new Position(command.lineNumber, 1), true);
+		if (command.exitCode && command.exitCode !== 0) {
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminalContrib/accessibility/browser/terminal.accessibility.contribution.ts:186]:
```suggestion
		if (command.exitCode) {
```

**Review by sandy081 — APPROVED** [review]
