### PR TITLE
fix code action race condition

### LINKED ISSUE #232679: Code actions not provided if code action provider takes ~2 seconds or longer
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.95.0
- OS Version: Win 11 24h2

Issue:
If a code action provider takes ~2 seconds (or longer) to provide code actions, actions from that provider will not be shown in the lightbulb.  This seems to be a behavior change between 1.94.2 and 1.95.0.  

Image

I suspect that this will be a fairly impactful issue for the C# extension.  We first noticed this when all our code action integration tests started failing after the update to 1.95.0 with all our code actions missing from the lightbulb (we 'fixed' it by rolling back the vscode version temporarily - https://github.com/dotnet/vscode-csharp/pull/7708).

This vscode side change looks potentially related - https://github.com/microsoft/vscode/commit/7f269ef38ff355019d5b8460114698e2abcf9b9a#diff-de403ad3613f99afdc0e0c040d79b78e556bbd6bdc462cfb40bd857e354f0a43L122

I'm not sure if this was intentionally applied to all lightbulb invocations (instead of just on save), but if it was I would ask to reconsider.  While we endeavor to provide code actions quickly, there are many scenarios where it can take additional time.  For example, slow analyzers, running source generators, or during project loading.   The timeout is quite short, and I have hit this at least a few times already today while using our extension. 

Steps to Reproduce:

For a repro, see this commit - https://github.com/dibarbet/vscode-extension-samples/commit/18b3a30df51dcbb8b8a8b228c231265daa13c010

### PR DESCRIPTION
**Pull request by justschen**
fix https://github.com/microsoft/vscode/issues/232679

cc. @jrieken

### CODE REVIEW

File: src/vs/editor/contrib/codeAction/browser/codeAction.ts [hunk 1]
```diff
@@ -124,9 +124,8 @@ export async function getCodeActions(
 	const disposables = new DisposableStore();
 	const promises = providers.map(async provider => {
 		try {
-			const codeActionsPromise = Promise.resolve(provider.provideCodeActions(model, rangeOrSelection, codeActionContext, cts.token));
```
Comment (justschen) [inline src/vs/editor/contrib/codeAction/browser/codeAction.ts:127]: what was the purpose of the 1.25 second race condition? 

if we want that in, we'd have to change it to something a little higher (maybe 5000 ms), but I think reverting to this should be okay?

Comment (jrieken) [reply src/vs/editor/contrib/codeAction/browser/codeAction.ts:127]: This is really important to keep because it ensures progress for code actions isn't reported too eager. The race timeout is actually not a 'race condition', it only makes sure the callback is only called when the given promise takes longer than N millis. So, no progress for fast code actions which is the goal here. 

What's the context here and why do you want to change this?

**Review by jrieken — DISMISSED** [review]

File: src/vs/editor/contrib/codeAction/browser/codeAction.ts (hunk 1 above)
Comment (jrieken) [reply src/vs/editor/contrib/codeAction/browser/codeAction.ts:127]: I have pushed [8d6b278](https://github.com/microsoft/vscode/pull/232690/commits/8d6b278d7243458c848c1f5fee2fc9d8e0073747) which keeps your fix intact and still delays progress reporting

**Review by bhavyaus — APPROVED** [review]
