### PR TITLE
code --status displays a lot of errors before actual status output (fix #183787)

### LINKED ISSUE #183787: code --status displays a lot of errors before actual status output
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2 (installed via snap)
- OS Version: Ubuntu 23.04

Steps to Reproduce:

1. Run `code --status`

```
[79076:0530/132835.062279:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
[79103:0530/132835.109953:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[79103:0530/132835.110053:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[79103:0530/132835.110092:ERROR:gl_display.cc(920)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[79103:0530/132835.113137:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[79103:0530/132835.113194:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[79103:0530/132835.113230:ERROR:gl_display.cc(920)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[79103:0530/132835.113267:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[79103:0530/132835.114696:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
[79114:0530/132835.177975:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[79114:0530/132835.178069:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[79114:0530/132835.178125:ERROR:gl_display.cc(920)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[79114:0530/132835.181294:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[79114:0530/132835.181394:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[79114:0530/132835.181472:ERROR:gl_display.cc(920)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[79114:0530/132835.181559:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[79114:0530/132835.183344:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[79134:0530/132835.219654:WARNING:sandbox_linux.cc(380)] InitializeSandbox() called with multiple threads in process gpu-process.
MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: iris
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load swrast driver
Version:          Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:47:05.613Z)
OS Version:       Linux x64 6.2.0-20-generic
CPUs:             Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 799)
Memory (System):  7.65GB (3.82GB free)
Load (avg):       1, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:     --no-sandbox --force-user-env --unity-launch
GPU Status:       2d_canvas:                              unavailable_software
                  canvas_oop_rasterization:               disabled_off
                  direct_rendering_display_compositor:    disabled_off_ok
                  gpu_compositing:                        disabled_software
                  multiple_raster_threads:                enabled_on
                  opengl:                                 disabled_off
                  rasterization:                          disabled_software
                  raw_draw:                               disabled_off_ok
                  video_decode:                           disabled_software
                  video_encode:                           disabled_software
                  vulkan:                                 disabled_off
                  webgl:                                  unavailable_software
                  webgl2:                                 unavailable_software
                  webgpu:                                 disabled_off

CPU %	Mem MB	   PID	Process
    0	   157	 78834	code main
    0	    39	 78836	   zygote
    0	    63	 78889	     gpu-process
    0	    39	 78837	   zygote
    0	    63	 78875	   utility-network-service
    0	   282	 78906	window [1] (Visual Studio Code)
    0	   118	 78948	shared-process
    0	    71	 78994	     ptyHost
    0	    78	 78949	fileWatcher [1]
    0	   157	 78968	extensionHost [1]
    0	    63	 79018	     electron-nodejs (/snap/code/129/usr/share/code/code --ms-enable-electron-run-as-node /snap/code/129/usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=78968)
``` 

### Expected behaviour: 
Just the status is displayed

### Actual behaviour: 
Lots of errors are displayed before the actual status output

### PR DESCRIPTION
**Pull request by bpasero**

### CODE REVIEW

File: src/vs/code/node/cli.ts [hunk 1]
```diff
@@ -413,6 +413,9 @@ export async function main(argv: string[]): Promise<any> {
 
 		let child: ChildProcess;
 		if (!isMacOSBigSurOrNewer) {
+			if (!verbose && args.status) {
```
Comment (deepak1556) [inline src/vs/code/node/cli.ts:416]: Can L410 be instead changed to `!verbose || !args.status` ?

Comment (bpasero) [reply src/vs/code/node/cli.ts:416]: @deepak1556 I thought about it, but for when we use `open` we do not really want the output of `open` right? We have a different solution in that case to track output.

**Review by deepak1556 — APPROVED** [review]
