### PR TITLE
Resolve Terminal arguments

### LINKED ISSUE #65817: Resolve environment variables in terminal.integrated.shell* and terminal.integrated.shellArgs*
There is a similar bug reported #57452, however environment variables in Windows are not in the scope of the bug. If you have an environment variable with a space, when it is read in `terminal.integrated.shellArgs.windows` it results in the same error as in #57452 

Version: 1.30.1 (user setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:

1. Create an environment variable with a space in it
2. Call that environment variable in the `terminal.integrated.shellArgs.windows` like so `%env_var%\\path`

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by lramos15**
Currently placing an environment variable in `terminal.integrated.args.*` does not resolve that environment variable to its value. This should not resolve the values so the behavior works the same as the external terminal.

To test on windows:
```json
    "terminal.integrated.shellArgs.windows": [
        "/k",
        "echo ${env:windir}"
    ],
```
Before this would just echo `${env:windir}` now it echos `C:\Windows`. 

Fixes https://github.com/microsoft/vscode/issues/65817

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts [hunk 1]
```diff
@@ -235,6 +235,17 @@ export function createTerminalEnvironment(
 			if (shellLaunchConfig.env) {
 				resolveConfigurationVariables(configurationResolverService, shellLaunchConfig.env, lastActiveWorkspace);
 			}
+			if (shellLaunchConfig.args) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts]: Can you do this for `.executable` as well? That maps to `terminal.integrated.shell.<platform>`, this should be done in `getDefaultShell`.

File: src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts [hunk 2]
```diff
@@ -235,6 +235,17 @@ export function createTerminalEnvironment(
...
+				if (Array.isArray(shellLaunchConfig.args)) {
+					const resolvedArgs: string[] = [];
+					for (const arg of shellLaunchConfig.args) {
+						resolvedArgs.push(configurationResolverService.resolve(undefined, arg));
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts]: The resolving should move over to `getDefaultShellArgs`

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/electron-browser/terminalInstanceService.ts [hunk 3]
```diff
@@ -65,19 +66,21 @@ export class TerminalInstanceService implements ITerminalInstanceService {
 		return this._storageService.getBoolean(IS_WORKSPACE_SHELL_ALLOWED_STORAGE_KEY, StorageScope.WORKSPACE, false);
 	}
 
-	public getDefaultShellAndArgs(platformOverride: Platform = platform): Promise<{ shell: string, args: string[] | undefined }> {
+	public getDefaultShellAndArgs(configurationResolverService: IConfigurationResolverService, platformOverride: Platform = platform): Promise<{ shell: string, args: string[] | undefined }> {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/electron-browser/terminalInstanceService.ts]: Use DI to acquire the service here

**Review by Tyriar — CHANGES_REQUESTED** [review]
Let's chat tomorrow morning so I can explain how the ext host proxy works :)

File: src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts [hunk 4]
```diff
@@ -190,17 +191,29 @@ export function getDefaultShell(
...
-	platformOverride: platform.Platform = platform.platform
+	configurationResolverService: IConfigurationResolverService | undefined,
+	platformOverride: platform.Platform = platform.platform,
 ): string[] {
 	const platformKey = platformOverride === platform.Platform.Windows ? 'windows' : platformOverride === platform.Platform.Mac ? 'osx' : 'linux';
 	const shellArgsConfigValue = fetchSetting(`terminal.integrated.shellArgs.${platformKey}`);
-	const args = (isWorkspaceShellAllowed ? <string[]>shellArgsConfigValue.value : <string[]>shellArgsConfigValue.user) || <string[]>shellArgsConfigValue.default;
+	let args = (isWorkspaceShellAllowed ? <string[]>shellArgsConfigValue.value : <string[]>shellArgsConfigValue.user) || <string[]>shellArgsConfigValue.default;
+	if (configurationResolverService) {
+		const resolvedArgs: string[] = [];
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts]: Just replace `args` in place instead of using `let` and creating a new array

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/api/node/extHost.api.impl.ts [hunk 5]
```diff
@@ -258,7 +258,7 @@ export function createApiFactory(
 				return extHostClipboard;
 			},
 			get shell() {
-				return extHostTerminalService.getDefaultShell(configProvider);
+				return extHostTerminalService.getDefaultShell(configProvider, undefined);
```
Comment (Tyriar) [inline src/vs/workbench/api/node/extHost.api.impl.ts]: Actually we need this to be synchronous, so let's create the resolver and hang onto it in `ExtHostTerminalService.ctor`

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts (hunk 4 above)
Comment (lramos15) [reply src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts]: What do you mean by replacing it in place? If I try to loop through and resolve like `args[I] = resolved(args[I])` I get runtime errors and I'm unsure why.

File: src/vs/workbench/api/node/extHostTerminalService.ts [hunk 6]
```diff
@@ -358,7 +358,7 @@ export class ExtHostTerminalService implements ExtHostTerminalServiceShape {
 		return renderer;
 	}
 
-	public getDefaultShell(configProvider: ExtHostConfigProvider): string {
+	public getDefaultShell(configProvider: ExtHostConfigProvider, configurationResolverService: ExtHostVariableResolverService | undefined): string {
```
[the remark this answers is not in the document]
Comment (lramos15) [reply src/vs/workbench/api/node/extHostTerminalService.ts]: If I do that then getting the shell becomes async

File: src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts [hunk 7]
```diff
@@ -190,17 +191,29 @@ export function getDefaultShell(
...
+		for (const arg of args) {
+			resolvedArgs.push(configurationResolverService.resolve(undefined, arg));
```
[the remark this answers is not in the document]
Comment (lramos15) [reply src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts]: I'm not sure, It didn't have any effects on the tests I did

File: src/vs/workbench/api/node/extHostTerminalService.ts [hunk 8]
```diff
@@ -310,6 +311,11 @@ export class ExtHostTerminalService implements ExtHostTerminalServiceShape {
 		private _logService: ILogService,
 	) {
 		this._proxy = mainContext.getProxy(MainContext.MainThreadTerminalService);
+		this._extHostConfiguration.getConfigProvider().then((configProvider) => {
+			this._extHostWorkspace.getWorkspaceFolders2().then((workspaceFolders) => {
```
Comment (Tyriar) [inline src/vs/workbench/api/node/extHostTerminalService.ts]: You can use await here if you make the anonymous function async

File: src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts (hunk 4 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts]: Ah ok, they come from the config service frozen I guess.

File: src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts]: It would only do anything in a multi-root workspace, not sure exactly what it would change but it would be safest to add that in.

File: src/vs/workbench/api/node/extHostTerminalService.ts [hunk 9]
```diff
@@ -370,18 +376,20 @@ export class ExtHostTerminalService implements ExtHostTerminalServiceShape {
...
 			getSystemShell(platform.platform),
 			process.env.hasOwnProperty('PROCESSOR_ARCHITEW6432'),
-			process.env.windir
+			process.env.windir,
+			this._variableResolver
 		);
 	}
 
-	private _getDefaultShellArgs(configProvider: ExtHostConfigProvider): string[] | string | undefined {
+	private _getDefaultShellArgs(configProvider: ExtHostConfigProvider): string[] {
```
Comment (Tyriar) [inline src/vs/workbench/api/node/extHostTerminalService.ts]: Shouldn't this return `string[] | string`?

File: src/vs/workbench/api/node/extHostTerminalService.ts [hunk 10]
```diff
@@ -310,6 +311,11 @@ export class ExtHostTerminalService implements ExtHostTerminalServiceShape {
 		private _logService: ILogService,
 	) {
 		this._proxy = mainContext.getProxy(MainContext.MainThreadTerminalService);
+		this._extHostConfiguration.getConfigProvider().then((configProvider) => {
```
Comment (Tyriar) [inline src/vs/workbench/api/node/extHostTerminalService.ts]: We should pull this into a function and do it whenever the active workspace changes

File: src/vs/workbench/api/node/extHostTerminalService.ts [hunk 11]
```diff
@@ -286,6 +286,7 @@ export class ExtHostTerminalService implements ExtHostTerminalServiceShape {
 	private _terminalProcesses: { [id: number]: ITerminalChildProcess } = {};
 	private _terminalRenderers: ExtHostTerminalRenderer[] = [];
 	private _getTerminalPromises: { [id: number]: Promise<ExtHostTerminal> } = {};
+	private _variableResolver: ExtHostVariableResolverService | undefined;
```
Comment (Tyriar) [inline src/vs/workbench/api/node/extHostTerminalService.ts]: This could be a `{ [workspaceRoot: string]: ExtHostVariableResolverService }`

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/api/node/extHostTerminalService.ts (hunk 11 above)
Comment (Tyriar) [reply src/vs/workbench/api/node/extHostTerminalService.ts]: Actually I think we're meant to rebuild this._variableResolver whenever a folder is added or removed from the workspace?

Comment (lramos15) [reply src/vs/workbench/api/node/extHostTerminalService.ts]: So I should register that on the onWorkspaceChange listener and calculate it then.

File: src/vs/workbench/api/node/extHostTerminalService.ts (hunk 9 above)
Comment (lramos15) [reply src/vs/workbench/api/node/extHostTerminalService.ts]: `let args = (isWorkspaceShellAllowed ? <string[]>shellArgsConfigValue.value : <string[]>shellArgsConfigValue.user) || <string[]>shellArgsConfigValue.default;`. This will always become a string[]

Comment (Tyriar) [reply src/vs/workbench/api/node/extHostTerminalService.ts]: I fixed this up

**Review by Tyriar — APPROVED** [review]
🕺
