### PR TITLE
chat: polishes for steering/queued messages

### LINKED ISSUE #278614: the Run or Debug button no longer remembers my last choice
- VS Code Version: 1.106.2
- OS Version: Windows 10 22H2

Steps to Reproduce:
1.  open a .c file
2.  click the run C/C++ tile in the dropdown menu
3.  the Run or Debug button no longer remembers my last choice
Am I the only one meeting this problem? Or is the feature deprecated?
https://code.visualstudio.com/updates/v1_59#_debugging

### PR DESCRIPTION
**Pull request by connor4312**
Steering messages are not quite wired up in the extension but I'm happy with the UX. Quick runthrough of various states: https://memes.peet.io/img/26-02-81ac36ef-1319-46b2-9093-3c05628291dc.mp4

Incidentally fixes #278614 since I ran into that same bug here.

Refs #260330

### CODE REVIEW

File: src/vs/platform/actions/browser/menuEntryActionViewItem.ts [hunk 1]
```diff
@@ -468,14 +469,18 @@ export class DropdownWithDefaultActionViewItem extends BaseActionViewItem {
...
-			this._register(this._dropdown.actionRunner.onDidRun((e: IRunEvent) => {
-				if (e.action instanceof MenuItemAction) {
-					this.update(e.action);
-				}
-			}));
+			this.registerTogglePrimaryActionListener();
 		}
 	}
 
+	private registerTogglePrimaryActionListener(): void {
```
Comment (connor4312) [inline src/vs/platform/actions/browser/menuEntryActionViewItem.ts:476]: This was the bug from #278614. We now sometimes change the `actionRunner` but we didn't move the listener over to the new runner. I wanted to use this behavior for the queue/steer button as well, so fixed that as part of this PR

**Review by bpasero — APPROVED** [review]
