### PR TITLE
[remote tunnel] cannot start with a host name that starts with dash

### LINKED ISSUE #168736: [remote tunnel] cannot start with a host name that starts with dash
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:
- VS Code Version: 1.74
- OS Version:  Windows 11 Pro Developers Build 

1. vsERR
Error Code image attached 

2.  Passes an invalid argument upon launch using the latest vs code Version 1.74

### PR DESCRIPTION
**Pull request by aeschli**
Fixes #168736

### CODE REVIEW

File: src/vs/platform/remoteTunnel/electron-browser/remoteTunnelService.ts [hunk 1]
```diff
@@ -285,8 +286,19 @@ export class RemoteTunnelService extends Disposable implements IRemoteTunnelServ
 
 	private _getHostName(): string | undefined {
 		let name = this.configurationService.getValue<string>(CONFIGURATION_KEY_HOST_NAME) || hostname();
-		name = name.replace(/[^\w-]/g, '').substring(0, 20);
+		name = _removeLeadingDashes(name).replace(/[^\w-]/g, '').substring(0, 20);
```
Comment (jrieken) [inline src/vs/platform/remoteTunnel/electron-browser/remoteTunnelService.ts:289]: I believe `replace(/^-+/g, '')` is shorter and faster

**Review by jrieken — APPROVED** [review]

File: src/vs/platform/remoteTunnel/electron-browser/remoteTunnelService.ts (hunk 1 above)
Comment (aeschli) [reply src/vs/platform/remoteTunnel/electron-browser/remoteTunnelService.ts:289]: Ah, nice, I didn't think of that. New PR on the way.

Comment (aeschli) [reply src/vs/platform/remoteTunnel/electron-browser/remoteTunnelService.ts:289]: https://github.com/microsoft/vscode/pull/168975
