### PR TITLE
fix suggest bug when in `selectionMode:never`

### LINKED ISSUE #253183: Terminal suggest warning: Cannot read properties of undefined (reading 'completion')
Testing #253098

Testing with the latest VS Code Insiders:

```
Version: 1.102.0-insider (user setup)
Commit: 28d57516d00e818edf89848fc36a8c97fa882e58
Date: 2025-07-01T05:03:31.371Z
Electron: 35.6.0
ElectronBuildId: 11847422
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Windows_NT arm64 10.0.26100
```

- Set `terminal.integrated.suggest.selectionMode` to `never`
- Start typing in terminal, get suggestions
     - Image
- Hit Enter or Tab
- ❔ Get warning `Cannot read properties of undefined (reading 'completion')`
     - Image

### PR DESCRIPTION
**Pull request by meganrogge**
fix #253183

### CODE REVIEW

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalSuggestAddon.ts [hunk 1]
```diff
@@ -814,8 +814,9 @@ export class SuggestAddon extends Disposable implements ITerminalAddon, ISuggest
 		if (!suggestion) {
 			suggestion = this._suggestWidget?.getFocusedItem();
 		}
+
 		const initialPromptInputState = this._mostRecentPromptInputState;
-		if (!suggestion || !initialPromptInputState || this._leadingLineContent === undefined || !this._model) {
+		if (!suggestion?.item || !initialPromptInputState || this._leadingLineContent === undefined || !this._model) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalSuggestAddon.ts:821]: This check looks fine, but shouldn't the command never be run to begin with due to context keys?

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalSuggestAddon.ts:821]: oh, maybe this is fixed now that we don't automatically push the inline suggestion (earlier pr?)

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalSuggestAddon.ts:821]: no, it's not

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalSuggestAddon.ts:821]: https://github.com/microsoft/vscode/blob/f79494158437524b82cc9bb7444594e68b50b45d/src/vs/workbench/contrib/terminalContrib/suggest/browser/terminal.suggest.contribution.ts#L428-L430

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalSuggestAddon.ts:821]: pushed new `when` for `tab` keybinding, but think we should keep this to be safe. tested without this and it worked via when clause

**Review by Tyriar — DISMISSED** [review]

**Review by Tyriar — APPROVED** [review]

**Review by bpasero — APPROVED** [review]
