### PR TITLE
fix layout/contrast issues with tip widget

### LINKED ISSUE #294972: Chat tip doesn't take up whole input box and has bad contrast
Image

Saw this after doing `code-insiders --transient`

Also it can overflow

Image

### LINKED ISSUE #294973: tip not appearing on chat welcome view
It should be showing up right by the input box

### PR DESCRIPTION
**Pull request by meganrogge**
fix https://github.com/microsoft/vscode/issues/294972
fix https://github.com/microsoft/vscode/issues/294973

https://github.com/user-attachments/assets/cb3c441e-7a0c-4ce3-a8ae-0337c052c37c

### CODE REVIEW

**Review by sandy081 — DISMISSED** [review]

File: src/vs/workbench/contrib/chat/browser/widget/chatWidget.ts [hunk 1]
```diff
@@ -2489,6 +2489,11 @@ export class ChatWidget extends Disposable implements IChatWidget {
 
 		this.bodyDimension = new dom.Dimension(width, height);
 
+		// Ensure the container's rendered height matches the JS-calculated
+		// layout height so that absolutely-positioned children (e.g. the
+		// getting-started tip) are correctly placed relative to the container.
+		this.container.style.height = `${height}px`;
```
Comment (roblourens) [inline src/vs/workbench/contrib/chat/browser/widget/chatWidget.ts]: Why are tips absolutely-positioned? They sit on top of the input, same as the edit list, todo container, etc right?

File: src/vs/workbench/contrib/chat/browser/widget/chatWidget.ts [hunk 2]
```diff
@@ -2505,6 +2510,12 @@ export class ChatWidget extends Disposable implements IChatWidget {
 
 		this.welcomeMessageContainer.style.height = `${contentHeight}px`;
 
+		// Keep getting-started tip aligned with the input after resize,
+		// but only when the tip is actually present to avoid unnecessary layout work.
+		if (this.container.classList.contains('chat-has-getting-started-tip')) {
```
Comment (roblourens) [inline src/vs/workbench/contrib/chat/browser/widget/chatWidget.ts]: Please avoid using hardcoded string classes in multiple places. No type safety, the DOM should not be the source of truth for your UI state.

Comment (roblourens) [reply src/vs/workbench/contrib/chat/browser/widget/chatWidget.ts]: I know we have code like this, people keep doing it, but it's an anti-pattern

**Review by roblourens — DISMISSED** [review]

File: src/vs/workbench/contrib/chat/browser/widget/chatWidget.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/chat/browser/widget/chatWidget.ts]: Good point, I'll try to align with those in another PR

File: src/vs/workbench/contrib/chat/browser/widget/chatWidget.ts [hunk 3]
```diff
@@ -236,7 +236,7 @@ export class ChatWidget extends Disposable implements IChatWidget {
 	private welcomeMessageContainer!: HTMLElement;
 	private readonly welcomePart: MutableDisposable<ChatViewWelcomePart> = this._register(new MutableDisposable());
 
-	private gettingStartedTipContainer: HTMLElement | undefined;
+
```
Comment (meganrogge) [inline src/vs/workbench/contrib/chat/browser/widget/chatWidget.ts]:
```suggestion
```

**Review by rzhao271 — DISMISSED** [review]

**Review by rzhao271 — APPROVED** [review]
