### PR TITLE
fix: remove TypeScript from ExtensionSuggestions

### LINKED ISSUE #82053: Replace TSLint with ESLint in ExtensionPack Suggestion on Welcome
First, thanks for making VSCode soooo awesome! Wouldn't be as productive as I am without it 💙

### Problem: 

Currently, VSCode suggests installing the [TSLint extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin) to have support for TypeScript.

However, [TSLint](https://github.com/palantir/tslint) is supposedly going to be deprecated sometime this year. 

image

### Proposed Solution:

Change the suggested extension to ESLint instead. This way, we're providing a solution to the community that is future-proof (at least for the foreseeable future) 😄

I'd be happy to open a PR if you were to accept this proposed solution. 

(it looks like this would be a matter of replacing the extension id here: [line 148](https://github.com/microsoft/vscode/blob/e81ee538090aa08b348f61414fcb74548506a2e8/src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts#L148))

### PR DESCRIPTION
**Pull request by jsjoeio**
This PR resolves #82053 

### Changes
- removes (comment out) the TypeScript section on the Welcome Page

### Screenshot
Screen Shot 2019-10-08 at 2 56 09 PM

### Additional Context

Originally, the Welcome page suggested users working with TypeScript install the TSLint extension. However, the TSLint extension is being deprecated in favor of ESLint. Instead of recommending ESLint, @mjbvz suggested dropping the TypeScript section altogether for now.

### CODE REVIEW

File: src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts [hunk 1]
```diff
@@ -146,7 +146,7 @@ interface ExtensionSuggestion {
 
 const extensionPacks: ExtensionSuggestion[] = [
 	{ name: localize('welcomePage.javaScript', "JavaScript"), id: 'dbaeumer.vscode-eslint' },
-	{ name: localize('welcomePage.typeScript', "TypeScript"), id: 'ms-vscode.vscode-typescript-tslint-plugin' },
+	// { name: localize('welcomePage.typeScript', "TypeScript"), id: 'ms-vscode.vscode-typescript-tslint-plugin' },
```
Comment (mjbvz) [inline src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts]: Can you please just delete this line instead. No reason to keep it around

Comment (jsjoeio) [reply src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts]: Sure thing!

**Comment by mjbvz** [comment]
Thanks!
