### PR TITLE
tools: update tools of a chat request when they change

### LINKED ISSUE #254684: Copilot Chat Session cannot access available MCP tools after tool change notification is received.
Does this issue occur when all extensions are disabled?: Yes - Cannot disable extensions as it requires Copilot Chat to call the MCP server.

- VS Code Version: 1.102.0-insider (Universal) Commit: 7631de29bf9a2e31020ab93d3d1611965dc5b62e
- OS Version: Mac OS 15.5 (24F74)

When a MCP server sends a `notifications/tools/list_changed` event, the session is unable to access the new tools until a subsequent message is sent.

Here is a Gif showing the behaviour: 

Image

As you can see, when sending the prompt that requires further tools, the agent correctly prompts the tool to suggest toolsets and enables a relevant toolset. This `enable_toolset` call triggers a `notifications/tools/list_changed` event on an upgraded SSE stream (via Streamable HTTP), and VSCode correctly updates the chat session with the additional 8 tools.
However, during the subsequent actions by the agent, it seems that it is unable to see the new tools are available.

Stopping the currently running message and sending an identical message results in the agent correctly selecting the newly available tool and completing the request.

Steps to Reproduce:

1. Configure an MCP server that provides `notifications/tools/list_changed` events in response to a tool call.
2. Prompt the agent in a way that triggers this tool call to enable additional tools, and that should subsequently trigger a call of these new tools.
3. Observe that the agent correctly attempts to enable a new tool, but is unable to use it.
4. Stop the running agent process
5. Prompt the agent again in the same way
6. Observe that the agent correctly calls the newly added tool.

I will try and put together a basic repro server for testing and add it to this issue.

### PR DESCRIPTION
**Pull request by connor4312**
Makes the `userSelectedTools` passed into the chat agent service
observable such that the tools of the ongoing request update as new
tools come in. The benefit of this versus other (previous) approaches
is that it reflects the enablement/disablement state of the picker
(which is likely to get additional controls in the future) and works
without special tagging.

@roblourens / @DonJayamanne I think with this we can get rid of

https://github.com/microsoft/vscode-copilot-chat/blob/0d6f5516d2fef455340228fd7bc34a4f501725d3/src/extension/tools/vscode-node/toolsService.ts#L118-L122

which was added for Jupyter iirc.

Closes #254684

### CODE REVIEW

File: src/vs/workbench/api/common/extHostChatAgents2.ts [hunk 1]
```diff
@@ -519,6 +523,19 @@ export class ExtHostChatAgents2 extends Disposable implements ExtHostChatAgentsS
...
 
+	async $setRequestTools(requestId: string, tools: Pick<IChatAgentRequest, 'userSelectedTools'>) {
+		const request = [...this._inFlightRequests].find(r => r.requestId === requestId);
+		if (!request) {
+			return;
+		}
+
+		request.extRequest.tools.clear();
+		for (const [k, v] of this.getToolsForRequest(request.extension, tools)) {
+			request.extRequest.tools.set(k, v);
```
Comment (roblourens) [inline src/vs/workbench/api/common/extHostChatAgents2.ts:534]: Need an ObservableMap in our extension API 😄

**Review by roblourens — APPROVED** [review]
