### PR TITLE
Set terminal.integrated.altClickMovesCursor: false by default, considering multiCursorModifier

### LINKED ISSUE #101136: Terminal filled with ^[[D^[[D^[[D^[[D when alt-clicking a link
- VSCode Version: 1.46.1
- OS Version: Ubuntu 20.04 LTS x86_64
- shell: bash

When alt-clicking in terminal (e. g. to open a file or URL), it gets filled up with lots of `^[[D^[[D^[[D^[[D` or `^[[C^[[C^[[C^[[C`:

image

Steps to Reproduce:

1. Open integrated terminal
2. Run `read` (or, for a more practical example, `yarn create react-app . && yarn start` in a temp dir)
3. Alt-click anywhere 

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by meganrogge**
Fixed #101136

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts [hunk 1]
```diff
@@ -93,7 +93,7 @@ export const terminalConfiguration: IConfigurationNode = {
 		'terminal.integrated.altClickMovesCursor': {
 			description: localize('terminal.integrated.altClickMovesCursor', "If enabled, alt/option + click will move the prompt cursor to position underneath the mouse. This may not work reliably depending on your shell."),
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts:94]: Let's document the interaction with `multiCursorModifier` here.

File: src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts [hunk 2]
```diff
@@ -93,7 +93,7 @@ export const terminalConfiguration: IConfigurationNode = {
...
 			type: 'boolean',
-			default: true
+			default: false
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts:96]: We want true by default, but overriding to false when `multiCursorModifier` is changed.

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Comment by Tyriar** [comment]
Let's link the issue with "Fixed #" in the PR description too so it gets auto closed.

**Review by Tyriar — APPROVED** [review]
