### PR TITLE
Fix dirty setting update logic

### LINKED ISSUE #58537: Auto save in new settings results in multiple validation errors when typing text
Steps to Reproduce:

1. Open new settings editor, search for "emmet extension"
2. `Emmet: Extensions Path` is a setting that takes path to a directory. Start typing a path

Since we auto-save in 100ms, the config change event is fired for almost every other character typed, which results in validation checks from the emmet extension resulting in a series of error notifications.

There might be other extensions in the marketplace that do such validations after listening the config change event.

### PR DESCRIPTION
**Pull request by guywaldman**
This PR closes #58537.

Setting that are dirty will now update:
* On changes when focused - with a debounce of _1000ms_
* On blur - immediately

### CODE REVIEW

File: src/vs/base/common/async.ts [hunk 1]
```diff
@@ -238,6 +238,15 @@ export class Delayer<T> {
 		}
 	}
 
+	async fire(): TPromise<void> {
```
Comment (roblourens) [inline src/vs/base/common/async.ts]: Why async? Unless it returns the completionPromise.

Comment (roblourens) [reply src/vs/base/common/async.ts]: FYI @joaomoreno

Comment (guywald1) [reply src/vs/base/common/async.ts]: You're right, it shouldn't be. I used `await` and didn't remove the `async`. Will change

**Comment by roblourens** [comment]
I'm not sure, I liked the comment that only text setting updates should have a slow debounce, and other types should be committed as fast as possible. What do you think? Should we send the type with onDidChangeSetting, and debounce differently based on the type?

File: src/vs/workbench/services/preferences/common/preferences.ts [hunk 2]
```diff
@@ -50,7 +63,7 @@ export interface ISetting {
 	deprecationMessage?: string;
 
 	scope?: ConfigurationScope;
-	type?: string | string[];
+	type?: SettingValueType | SettingValueType[];
```
Comment (guywald1) [inline src/vs/workbench/services/preferences/common/preferences.ts]: Possibly other fields should be changed as well?

File: src/vs/workbench/parts/preferences/browser/settingsEditor2.ts [hunk 3]
```diff
@@ -126,7 +138,8 @@ export class SettingsEditor2 extends BaseEditor {
 		this.viewState = { settingsTarget: ConfigurationTarget.USER };
 		this.delayRefreshOnLayout = new Delayer(100);
 
-		this.settingUpdateDelayer = new Delayer<void>(200);
+		this.settingFastUpdateDelayer = new Delayer<void>(SettingsEditor2.SETTING_UPDATE_FAST_DEBOUNCE);
```
Comment (guywald1) [inline src/vs/workbench/parts/preferences/browser/settingsEditor2.ts]: Possibly should just invoke callbacks without a debounce? Only makes sense for text inputs, but for future-proofing could be useful to keep.

**Comment by guywald1** [comment]
@roblourens Updated :)

File: src/vs/workbench/services/preferences/common/preferencesModels.ts [hunk 4]
```diff
@@ -616,7 +616,7 @@ export class DefaultSettings extends Disposable {
 					descriptionRanges: [],
 					overrides,
 					scope: prop.scope,
-					type: prop.type,
+					type: prop.type as SettingValueType,
```
Comment (roblourens) [inline src/vs/workbench/services/preferences/common/preferencesModels.ts]: I think prop.type is probably a subset of SettingValueType, but I don't want to use SettingValueType at this level because it gives the wrong impression. It's not really a type of the setting itself but has some info about what kind of control should be used to edit it.

File: src/vs/workbench/parts/preferences/browser/settingsEditor2.ts [hunk 5]
```diff
@@ -53,11 +54,21 @@ export class SettingsEditor2 extends BaseEditor {
...
 	private static readonly SUGGESTIONS: string[] = [
 		'@modified', '@tag:usesOnlineServices'
 	];
 
+	private static shouldSettingUpdateFast(type: SettingValueType | SettingValueType[]): boolean {
+		if (isArray(type)) {
+			// nullable integer/number or complex
+			return true;
+		}
+		return type !== SettingValueType.Enum && type !== SettingValueType.Complex;
```
Comment (roblourens) [inline src/vs/workbench/parts/preferences/browser/settingsEditor2.ts]: Why should enum be slow?

File: src/vs/workbench/parts/preferences/browser/settingsEditor2.ts (hunk 3 above)
Comment (roblourens) [reply src/vs/workbench/parts/preferences/browser/settingsEditor2.ts]: I think we should keep the fast debounce. Lots of stuff happens when configuration changes, whether it was for anything important or not, and we should at least sort of avoid updating the config every time if someone clicks a checkbox as fast as they can.

File: src/vs/workbench/parts/preferences/browser/settingsEditor2.ts [hunk 6]
```diff
@@ -580,15 +596,24 @@ export class SettingsEditor2 extends BaseEditor {
...
 		this.pendingSettingUpdate = { key, value };
-		this.settingUpdateDelayer.trigger(() => this.updateChangedSetting(key, value));
+		if (SettingsEditor2.shouldSettingUpdateFast(type)) {
+			this.settingFastUpdateDelayer.trigger(() => this.updateChangedSetting(key, value));
+		} else {
+			this.settingSlowUpdateDelayer.trigger(() => this.updateChangedSetting(key, value));
+		}
+	}
+
+	private _onDidBlurSetting(element: SettingsTreeSettingElement) {
```
Comment (roblourens) [inline src/vs/workbench/parts/preferences/browser/settingsEditor2.ts]: I'm not sure this is necessary. You would have to click away from the setting pretty quickly for it to be worth it.

File: src/vs/workbench/services/preferences/common/preferences.ts (hunk 2 above)
Comment (roblourens) [reply src/vs/workbench/services/preferences/common/preferences.ts]: See comment below, is it possible to keep this as 'string' and only use SettingValueType inside the tree code?

File: src/vs/workbench/parts/preferences/browser/settingsEditor2.ts (hunk 5 above)
Comment (guywald1) [reply src/vs/workbench/parts/preferences/browser/settingsEditor2.ts]: Misnamed the constants (fast should be be named slow and vice versa), will fix

File: src/vs/workbench/parts/preferences/browser/settingsEditor2.ts (hunk 6 above)
Comment (guywald1) [reply src/vs/workbench/parts/preferences/browser/settingsEditor2.ts]: From the discussion I figured that this was the desired behavior (having the change take effect immediately when tabbing for instance), but I agree with you as the debounce is pretty short.
So should I remove the blur event emitter for the renderer &`Delayer.fire` altogether?

File: src/vs/workbench/parts/preferences/browser/settingsEditor2.ts (hunk 5 above)
Comment (guywald1) [reply src/vs/workbench/parts/preferences/browser/settingsEditor2.ts]: My logic was negated here (also the naming of the debounces). *Sigh*, That's what happens when you don't get enough sleep. Will fix

File: src/vs/base/common/async.ts [hunk 7]
```diff
@@ -238,6 +238,15 @@ export class Delayer<T> {
 		}
 	}
 
+	fire(): void {
```
Comment (roblourens) [inline src/vs/base/common/async.ts]: I think this isn't used anymore right?

File: src/vs/workbench/parts/preferences/browser/settingsEditor2.ts (hunk 6 above)
Comment (roblourens) [reply src/vs/workbench/parts/preferences/browser/settingsEditor2.ts]: I think that committing on blur was an alternative to debouncing, so yeah I think you can remove those things.

File: src/vs/base/common/async.ts (hunk 7 above)
Comment (guywald1) [reply src/vs/base/common/async.ts]: Yes, removed the blur event emitter but wasn't sure whether to remove this as it might be useful to keep so waited for comments. Better to remove altogether if not used?

Comment (guywald1) [reply src/vs/base/common/async.ts]: Yes, removed the blur event emitter but wasn't sure whether to remove this as it might be useful to keep so waited for comments. Will remove based on your other comment.

**Review by roblourens — APPROVED** [review]
Thanks!!

**Comment by guywald1** [comment]
@roblourens Just making sure - unit tests seem to be failing on Linux, but it seems that the problem is not with my changes. Is it OK?

**Comment by roblourens** [comment]
Yeah I checked it out and it looked like a flaky test
