### PR TITLE
Respect viewtype for reopen with in notebooks

### LINKED ISSUE #119954: `Reopen Editor With...` picks wrong notebook editor
Verifying  #115631

Version: 1.55.0-insider
Commit: 6ebe2a14f3722bc2582ecd8108d0a71dfdd46036
Date: 2021-03-25T16:24:13.227Z

 - clone https://github.com/microsoft/vscode-markdown-notebook and open in vscode 
 - add a `console.log('openContext', openContext);` to `openNotebook`
 - F5 to run the extension
 - Open an untitled file
 - In the editor's tab, choose `Reopen Editor With...` from the context menu, pick `Markdown Notebook`
 
image

- a different notebook is opened, no console log statement printed
image

### PR DESCRIPTION
**Pull request by lramos15**
This PR fixes #119954 

Currently when we resolve the notebook data provider using `withNotebookDataProvider` we only use the resource. This can cause issues when the resource can be mapped to multiple providers. This is especially noticeable for untitled files which map to all resources. This PR makes it so that if we know the viewType we want to open we ensure that the data provider we select is the one for that viewType. Marking this as a candidate as it would break the flow when there are two notebooks for the same glob pattern.

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts [hunk 1]
```diff
@@ -480,15 +480,20 @@ export class NotebookService extends Disposable implements INotebookService, IEd
...
 
-	async withNotebookDataProvider(resource: URI): Promise<ComplexNotebookProviderInfo | SimpleNotebookProviderInfo> {
-		const [first] = this._notebookProviderInfoStore.getContributedNotebook(resource);
-		if (!first) {
+	async withNotebookDataProvider(resource: URI, viewType?: string): Promise<ComplexNotebookProviderInfo | SimpleNotebookProviderInfo> {
+		const providers = this._notebookProviderInfoStore.getContributedNotebook(resource);
+		let selected = providers[0];
+		// If we have a viewtype specified we want that data provider, as the resource won't always map correctly
+		if (viewType) {
+			selected = providers.filter(provider => provider.id === viewType)[0];
```
Comment (jrieken) [inline src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts:488]: for the future: better use `Array#first`

**Review by jrieken — APPROVED** [review]
