### PR TITLE
fire `onDidReconnectToTasks` when there are no task terminals to reconnect to so tasks run on `folderOpen` 

### LINKED ISSUE #193475: Tasks using `"runOn": "folderOpen"` are broken
* have a task with `"runOn": "folderOpen"`, like https://github.com/microsoft/vscode-github-issue-notebooks/blob/e017704a5eb4bb6080322a3d489c76d421089111/.vscode/tasks.json#L18
* make sure it ran once
* reload/reopen folder
* 🐛 task doesn't run

### PR DESCRIPTION
**Pull request by meganrogge**
fix #193475

### CODE REVIEW

File: src/vs/workbench/contrib/tasks/browser/runAutomaticTasks.ts [hunk 1]
```diff
@@ -28,11 +28,10 @@ export class RunAutomaticTasks extends Disposable implements IWorkbenchContribut
 		@IWorkspaceTrustManagementService private readonly _workspaceTrustManagementService: IWorkspaceTrustManagementService,
 		@ILogService private readonly _logService: ILogService) {
 		super();
-		this._taskService.onDidReconnectToTasks((() => {
-			if (this._workspaceTrustManagementService.isWorkspaceTrusted()) {
-				this._tryRunTasks();
-			}
-		}));
+		this._taskService.onDidReconnectToTasks((() => this._tryRunTasks()));
```
Comment (Tyriar) [inline src/vs/workbench/contrib/tasks/browser/runAutomaticTasks.ts:31]: This listener should be registered

File: src/vs/workbench/contrib/tasks/browser/runAutomaticTasks.ts [hunk 2]
```diff
@@ -28,11 +28,10 @@ export class RunAutomaticTasks extends Disposable implements IWorkbenchContribut
...
+		if (this._taskService.isReconnected) {
+			this._tryRunTasks();
+		}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/tasks/browser/runAutomaticTasks.ts:34]: Is this better?

```ts
if (this._taskService.isReconnected) {
	this._tryRunTasks();
} else {
	this._register(Event.once(this._taskService.onDidReconnectToTasks)(() => this._tryRunTasks());
}
```

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Review by Tyriar — APPROVED** [review]
