### PR TITLE
fix wrongly handled part dispose:

### LINKED ISSUE #264761: Chat jiggles after a code block
repro

1. put cursor a function name within an editor
2. open chat in ask mode
3. type `/tests` and press enter 
4. :bug: chat starts to stream a code block at some point, and starts to jiggle after the code block 

https://github.com/user-attachments/assets/012944d2-1122-4a61-bbd5-772fcb0c2ace

https://github.com/user-attachments/assets/a94afac0-9a72-4870-8b6e-f500f3ce6d95

Version: 1.104.0-insider
Commit: a2b1ec5f3ba438c7e65b47303a4994543bab72c2
Date: 2025-09-02T15:56:07.546Z
Electron: 37.3.1
ElectronBuildId: 12259562
Chromium: 138.0.7204.235
Node.js: 22.18.0
V8: 13.8.258.31-electron.0
OS: Darwin arm64 24.6.0

### PR DESCRIPTION
**Pull request by justschen**
fix https://github.com/microsoft/vscode/issues/264761

### CODE REVIEW

**Review by bpasero — APPROVED** [review]

File: src/vs/workbench/contrib/chat/browser/chatListRenderer.ts [hunk 1]
```diff
@@ -970,12 +970,16 @@ export class ChatListItemRenderer extends Disposable implements ITreeRenderer<Ch
 			const alreadyRenderedPart = templateData.renderedParts?.[contentIndex];
 
 			// keep existing thinking part instance during streaming and update it in place
-			if (alreadyRenderedPart && partToRender.kind === 'thinking' && alreadyRenderedPart instanceof ChatThinkingContentPart) {
-				if (!Array.isArray(partToRender.value)) {
-					alreadyRenderedPart.updateThinking(partToRender);
+			if (alreadyRenderedPart) {
+				if (partToRender.kind === 'thinking' && alreadyRenderedPart instanceof ChatThinkingContentPart) {
+					if (!Array.isArray(partToRender.value)) {
+						alreadyRenderedPart.updateThinking(partToRender);
```
Comment (roblourens) [inline src/vs/workbench/contrib/chat/browser/chatListRenderer.ts:976]: This makes sense, probably other parts could benefit from this mechanism but I would recommend making it part of the `IChatContentPart` interface rather than doing a one-off for one type of content inside the generic rendering loop.
