### PR TITLE
Prevent unexpected rename cancellation

### LINKED ISSUE #92507: [BUG] [Regression] "Rename failed to execute" when renaming a variable in TypeScript
Regression on 
"Rename failed to execute" when renaming a variable in TypeScript #81125

Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

### PR DESCRIPTION
**Pull request by ChrisPapp**
This PR fixes #92507

The problem was that the rename command was getting cancelled. When moving the cursor's position (but still staying within the rename target's range) the cancellation token thinks it should cancel because the cursor moved...
https://github.com/microsoft/vscode/blob/d76919141d77f2b9dd6a7daf540b0794af6eba50/src/vs/editor/contrib/rename/rename.ts#L146

... but the input field thinks we didn't cancel because the cursor is still within range.

https://github.com/microsoft/vscode/blob/d76919141d77f2b9dd6a7daf540b0794af6eba50/src/vs/editor/contrib/rename/renameInputField.ts#L188-L193

Therefore we can either update the input field's logic to be in line with the cancellation token rules, or we can temporarily stop using the cancellation token.
I implemented the latter.

### CODE REVIEW

File: src/vs/editor/contrib/rename/rename.ts [hunk 1]
```diff
@@ -190,6 +193,8 @@ class RenameController implements IEditorContribution {
 			return undefined;
 		}
 
+		this._cts = new EditorStateCancellationTokenSource(this.editor, CodeEditorStateFlag.Position | CodeEditorStateFlag.Value);
```
Comment (jrieken) [inline src/vs/editor/contrib/rename/rename.ts:196]: How about allowing to define a range in which position changes are OK? You could pass the rename-range into the ctor and test if the position is still within the range when selection or position changes happen

**Review by jrieken — CHANGES_REQUESTED** [review]

File: src/vs/editor/contrib/rename/rename.ts (hunk 1 above)
Comment (ChrisPapp) [reply src/vs/editor/contrib/rename/rename.ts]: I updated it. Since the token is used before the range is calculated, I also added a setter method. Could synchronization issues could arise in the future?

File: src/vs/editor/contrib/rename/rename.ts [hunk 2]
```diff
@@ -173,14 +173,15 @@ class RenameController implements IEditorContribution {
 		let selection = this.editor.getSelection();
 		let selectionStart = 0;
 		let selectionEnd = loc.text.length;
+		(this._cts as EditorStateCancellationTokenSource).range = loc.range;
```
Comment (jrieken) [inline src/vs/editor/contrib/rename/rename.ts:176]: This is not nice. The `range` property should not be mutable as that counters the idea of capturing a state to compare it against a future state. How about creating a new token?  E.g. the token from line 146 is used to resolve the rename locations, then here dispose it and create new token with a (readonly) range

**Review by jrieken — CHANGES_REQUESTED** [review]

File: src/vs/editor/contrib/rename/rename.ts (hunk 2 above)
Comment (ChrisPapp) [reply src/vs/editor/contrib/rename/rename.ts]: Done!

**Review by jrieken — APPROVED** [review]

**Comment by jrieken** [comment]
Thanks
