### PR TITLE
Place edit context dom node always inside the viewport for correct focusing behavior

### LINKED ISSUE #235231: EditContext: cursor jumps with accessibility mode and the `toggle terminal` command
Version: 1.96.0-insider
Commit: a40fbb1ac10ad5c797d331eb75d1d99332ef9cbe
Date: 2024-12-03T10:12:24.933Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin x64 22.6.0

Steps to Reproduce:

1. Set
```json
{
    "editor.accessibilitySupport": "on",
    "window.zoomLevel": 1.7,
    "workbench.colorTheme": "Default Light+",
    "editor.acceptSuggestionOnEnter": "smart",
    "editor.bracketPairColorization.enabled": false,
    "editor.cursorBlinking": "solid",
    "editor.experimentalEditContextEnabled": true,
    "editor.fontFamily": "Monaco, 'Courier New', monospace",
    "editor.inlineSuggest.enabled": true,
    "editor.lightbulb.enabled": "off",
    "editor.lineHeight": 15,
    "editor.minimap.enabled": false,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.occurrencesHighlight": "off",
    "editor.pasteAs.enabled": false,
    "editor.renderControlCharacters": true,
    "editor.renderLineHighlight": "none",
    "editor.renderWhitespace": "none",
    "editor.smoothScrolling": true,
    "editor.stickyScroll.enabled": false,
    "editor.wordWrap": "on",
}
```
1.  Open the terminal.
2.  Focus at the last line of the editor.
3. Scroll to the top with the mouse scroll.
4. Execute `Toggle Termina` 3 times.
5. Click the editor.
6. The cursor jumps to the last line.

CC:  @aiday-mar

In the following video, the `Screen Reader Optimized` banner is hidden because the window size is small.

https://github.com/user-attachments/assets/6d4edba4-ceb4-45eb-a954-fdb8a4f88043

### PR DESCRIPTION
**Pull request by aiday-mar**
+ re-render the edit context dom node on different events (mirrors text area)

fixes https://github.com/microsoft/vscode/issues/235231

### CODE REVIEW

File: src/vs/editor/browser/controller/editContext/native/screenReaderSupport.ts [hunk 1]
```diff
@@ -59,7 +61,7 @@ export class ScreenReaderSupport {
 	public onConfigurationChanged(e: ViewConfigurationChangedEvent): void {
 		this._updateConfigurationSettings();
 		this._updateDomAttributes();
-		if (this._accessibilityService.isScreenReaderOptimized()) {
+		if (this._accessibilityService.isScreenReaderOptimized() && e.hasChanged(EditorOption.accessibilitySupport)) {
 			this.writeScreenReaderContent();
 		}
```
Comment (Tyriar) [inline src/vs/editor/browser/controller/editContext/native/screenReaderSupport.ts:66]: We don't need to remove it if it turns off?

**Review by Tyriar — APPROVED** [review]

File: src/vs/editor/browser/controller/editContext/native/screenReaderSupport.ts (hunk 1 above)
Comment (aiday-mar) [reply src/vs/editor/browser/controller/editContext/native/screenReaderSupport.ts:66]: Hi @Tyriar that is a good point, I will make a PR to clear the dom node when the screen reader is not optimized in a subsequent PR

After some investigation already before the method `writeScreenReaderContent` would not clear the dom node on disabling the screen reader mode.

Comment (aiday-mar) [reply src/vs/editor/browser/controller/editContext/native/screenReaderSupport.ts:66]: PR https://github.com/microsoft/vscode/pull/235281
