### PR TITLE
fixes issue #662 (enables Pointer Lock Web API)

### LINKED ISSUE #662: [json] Don't propose keys that are already existing
# Problem
When authoring a JSON file, such as a Microsoft Azure Resource Manager (ARM) JSON Template, the Visual Studio Code editor is showing all of the available properties for an object, instead of only showing the properties that the user has *not yet specified*.

screen shot 2015-11-25 at 2 10 22 pm

# Expected Result

I would naturally expect that the Visual Studio Code Intellisense returns only the JSON properties that the user hasn't defined yet. I shouldn't be prompted to insert a duplicate key.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

### LINKED ISSUE #662: Please add a minimal sample for creating an LSP client.
The LSP samples are fairly confusing to me. Wondering if you could add a sample like this one?

https://gitlab.com/torokati44/vscode-glspc

### LINKED ISSUE #221593: Pointer lock doesn't work with webview panel in extension
I am building a vscode extension that creates a webview panel. This panel has a canvas which renders successfully. No matter what I try, I cannot get the pointer to lock to the canvas with the scene and in the webview developer tools console, I see this message whenever I requestPointerLock()

"Uncaught (in promise) DOMException: The root document of this element is not valid for pointer lock"

This took me into the world of iframes which webview panels use to create the html document however all the iframes that are created as part of the webview panel have "allow-pointer-lock" - as mentioned here https://github.com/microsoft/vscode/issues/104169 - so I don't think that is the problem. I am not finding anything about the error "Uncaught (in promise) DOMException: The root document of this element is not valid for pointer lock" online

### PR DESCRIPTION
**Pull request by whistlegraph**
This change fixes microsoft/vscode-extension-samples#662
fixes https://github.com/microsoft/vscode/issues/221593

By explicitly allowing the `pointerLock` permission in the root document of the VS Code window.

*Testing*
  - You can test this change using the `aesthetic-computer.aesthetic-computer-code` extension in the Marketplace. 
  - Open the `Aesthetic Computer` pane from the Activity Bar.
  - Enter `fps` and press `[Enter]`.
  - Press `[Escape]` to end the Pointer Lock.

### CODE REVIEW

File: src/vs/code/electron-main/app.ts [hunk 1]
```diff
@@ -166,7 +166,10 @@ export class CodeApplication extends Disposable {
 
 		const isUrlFromWebview = (requestingUrl: string | undefined) => requestingUrl?.startsWith(`${Schemas.vscodeWebview}://`);
 
+		const allowedPermissions = new Set(['pointerLock']);
```
Comment (mjbvz) [inline src/vs/code/electron-main/app.ts:169]: Does this need to be enabled for the root document too? The only use case seems to be for webviews

Comment (whistlegraph) [reply src/vs/code/electron-main/app.ts:169]: Yes the permission did not work until I added it to the root. That is to say I also needed the permission on the containing frame in order for the child to function in my extension's Webview.

**Review by mjbvz — APPROVED** [review]

**Review by mjbvz — APPROVED** [review]

**Review by roblourens — APPROVED** [review]
