### PR TITLE
handle updates while outputs are collapsed

### LINKED ISSUE #196304: Updating Notebook results while the output is collapsed makes the output invisble when expanded again.
Type: <b>Bug</b>

When a notebook updates text in a collapsed cells unexpected things happen.

The Jupyter Notebook renders the output while still showing that the output is collapsed.

Node.JS Notebooks and httpBook show empty cells and will only show the output again when expanded, collapsed, expanded again

https://github.com/microsoft/vscode-jupyter/assets/66731536/e6a3bae7-7b3d-4519-aef0-495772f2e8ab

In the [node.js notebook extension](https://marketplace.visualstudio.com/items?itemName=donjayamanne.typescript-notebook) the result looks like this:
broken interaction in nodejs notebook

Issue created to hopefully follow up https://github.com/AnWeber/httpbook/issues/100

Extension version: 2023.9.1102792234
VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by amunger**
fix https://github.com/microsoft/vscode/issues/196304

this fixes two separate scenarios 
- when an output is simply updated for a single renderer - prevent the render from happening (#196304)
- when an output is replaced (switched mime types) - the CellOutputContainer needs to track that it's output entries are out of date and need to be recreated

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.ts [hunk 1]
```diff
@@ -477,11 +478,16 @@ const enum CellOutputUpdateContext {
...
 export class CellOutputContainer extends CellContentPart {
 	private _outputEntries: OutputEntryViewHandler[] = [];
+	private _staleOutputs: boolean = false;
 
 	get renderedOutputEntries() {
 		return this._outputEntries;
 	}
 
+	unrenderedChanges() {
+		this._staleOutputs = true;
```
Comment (rzhao271) [inline src/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.ts:488]: Nit: variable name could be `_hasStaleOutputs`

File: src/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.ts [hunk 2]
```diff
@@ -183,6 +183,7 @@ class CellOutputElement extends Disposable {
 		const index = this.viewCell.outputsViewModels.indexOf(this.output);
 
 		if (this.viewCell.isOutputCollapsed || !this.notebookEditor.hasModel()) {
+			this.cellOutputContainer.unrenderedChanges();
```
Comment (rzhao271) [inline src/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.ts:186]: Nit: method name could be `flagAsStale()`

**Review by rzhao271 — DISMISSED** [review]

File: src/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.ts (hunk 2 above)
Comment (amunger) [reply src/vs/workbench/contrib/notebook/browser/view/cellParts/cellOutput.ts:186]: I was trying to think of a better name for quite a while, thanks

**Review by rzhao271 — APPROVED** [review]
