### PR TITLE
Make high contrast detection configurable

### LINKED ISSUE #17279: Add a setting to disable Auto-Detection of High Contrast
- VSCode Version: 1.8.0
- OS Version: Windows Version 6.3.9600 (Windows 8.1 Enterprise)

Steps to Reproduce:

1. Enable High Contrast on Windows
2. Start VS Code, look at the glorious High Contrast theme
3. Select a different theme, because you would rather work in that
4. Restart VS Code, your theme choice gets overridden.

Essentially, I'd like to be able to disable the auto-detection of the High Contrast theme I'm using in Windows via some setting, because while I prefer Windows in High Contrast mode, I dislike looking at VS Code's High Contrast theme.

### PR DESCRIPTION
**Pull request by geirsagberg**
Add a new option 'window.autoDetectHighContrast', defaults to true. If false, VS Code theme will ignore Windows High Contrast theme.

Fixes #17279

### CODE REVIEW

File: src/vs/workbench/electron-browser/main.contribution.ts [hunk 1]
```diff
@@ -203,6 +203,14 @@ let properties: { [path: string]: IJSONSchema; } = {
 	}
 };
 
+if (platform.isWindows) {
+	properties['window.autoDetectHighContrast'] = {
+		'type': 'boolean',
+		'default': true,
+		'description': nls.localize('autoDetectHighContrast', "If enabled, will automatically change to high contrast theme if Windows is using a high contrast theme.")
+	}
```
Comment (bpasero) [inline src/vs/workbench/electron-browser/main.contribution.ts]: Missing trailing comma.

File: src/vs/workbench/electron-browser/window.ts [hunk 2]
```diff
@@ -258,15 +258,21 @@ export class ElectronWindow {
 
 		// High Contrast Events
 		ipc.on('vscode:enterHighContrast', (event) => {
-			this.partService.joinCreation().then(() => {
-				this.themeService.setColorTheme(VS_HC_THEME, false);
-			});
+			const windowConfig = this.configurationService.getConfiguration<IWindowSettings>('window');
+			if (windowConfig.autoDetectHighContrast) {
```
Comment (bpasero) [inline src/vs/workbench/electron-browser/window.ts]: `windowConfig` can be null

File: src/vs/workbench/electron-browser/window.ts [hunk 3]
```diff
@@ -258,15 +258,21 @@ export class ElectronWindow {
...
+					this.themeService.setColorTheme(VS_HC_THEME, false);
+				});
+			}
 		});
 
 		ipc.on('vscode:leaveHighContrast', (event) => {
-			this.partService.joinCreation().then(() => {
-				this.themeService.setColorTheme(VS_DARK_THEME, false);
-			});
+			const windowConfig = this.configurationService.getConfiguration<IWindowSettings>('window');
```
Comment (bpasero) [inline src/vs/workbench/electron-browser/window.ts]: I think we can ignore the setting in this case because leaving HC on Windows you want to switch back to dark theme. Or otherwise the setting should be clearer that it prevents switching in both ways, not just from normal to HC theme.

**Review by bpasero — CHANGES_REQUESTED** [review]
@geirsagberg very cool, only minor feedback!

File: src/vs/workbench/electron-browser/window.ts (hunk 3 above)
Comment (geirsagberg) [inline src/vs/workbench/electron-browser/window.ts]: I have expanded the setting description. I feel if this settings is disabled, nothing should happen automatically when changing to/from windows HC theme.

**Comment by geirsagberg** [comment]
I have signed the CLA; do I need to do anything to make the bot accept it?

**Comment by bpasero** [comment]
@geirsagberg I think it can take some minutes to be picked up 👍

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by bpasero** [comment]
LGTM, thanks for the prompt fix.

**Review by bpasero — APPROVED** [review]
