### PR TITLE
Fixes #18990, #21693 - Shutdown terminal pty process more gracefully

### LINKED ISSUE #18990: Shutdown terminal pty process more gracefully
Particularly on Windows, `pty.kill()` should be called to terminate the process. This will ensure the sockets are closed and the pty agent is shutdown.

### LINKED ISSUE #21693: Multiple Instances with bash shells, histories not restored correctly
- VSCode Version: 1.10.1
- OS Version: OSX 10.11.6

Steps to Reproduce:
0. Have multiple workspaces open each with bash and do stuff in each
1. Restart Code either by update or reboot
2. observe that bash histories are not restored

useful when you run a complex command to run a project in a particular way.

### PR DESCRIPTION
**Pull request by chirag64**
This should terminate the integrated terminal process more gracefully before VS Code's exit. This should fix #18990 and other potential issues like #21693.

Fixes #18990 
Fixes #21693

### CODE REVIEW

File: src/vs/workbench/parts/terminal/electron-browser/terminalProcess.js [hunk 1]
```diff
@@ -48,6 +48,7 @@ ptyProcess.on('data', function (data) {
 });
 
 ptyProcess.on('exit', function (exitCode) {
+	ptyProcess.kill();
```
Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalProcess.js]: Thanks @chirag64!

Does everything seem to work fine? It's worth testing on Windows if you haven't. I was thinking we might need a timeout here before we kill `terminalProcess` or it could mess with the pty processes' shutdown.

Comment (chirag64) [inline src/vs/workbench/parts/terminal/electron-browser/terminalProcess.js]: I'll try this out on Windows, haven't tested it yet. What do you think would be a good timeout before we kill `terminalProcess`? 500 ms?

Comment (chirag64) [inline src/vs/workbench/parts/terminal/electron-browser/terminalProcess.js]: Tested this in Windows too.

So when I start Integrated terminal in VS Code, I see one extra instance of bash (in Linux or PowerShell in Windows) and when I exit VS Code, that instance disappears from the task manager. Let me know if there's anything else you think I should be testing for this.

Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalProcess.js]: @chirag64 well it was just a suspicious that we may need a timeout, if it works fine without it that's fine.

**Comment by Tyriar** [comment]
Thanks @chirag64, I'm not 100% sure if this will fix https://github.com/Microsoft/vscode/issues/21693 as it's kind of tricky to repro, but it's the only thing I can think of that might. I believe the test failure is unrelated so I'll merge this :+1:
