### PR TITLE
Fix cannot read properties of undefined (reading 'searchInput')

### LINKED ISSUE #181948: Cannot read properties of undefined (reading 'searchInput')
```javascript
TypeError: Cannot read properties of undefined (reading 'searchInput')
at Hu.saveState in src/vs/workbench/contrib/search/browser/searchView.ts:2005:25
at <anonymous> in src/vs/workbench/browser/parts/views/viewPaneContainer.ts:736:37
at Array.forEach (<anonymous>)
at e.ViewPaneContainer.F in src/vs/workbench/browser/parts/views/viewPaneContainer.ts:736:14
at <anonymous> in src/vs/workbench/common/component.ts:27:9
at g.invoke in src/vs/base/common/event.ts:862:17
at o.deliver in src/vs/base/common/event.ts:1075:22
at s.fire in src/vs/base/common/event.ts:1031:24
at E.flush in src/vs/platform/storage/common/storage.ts:507:25
at <anonymous> in src/vs/platform/storage/common/storage.ts:281:10
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=f5d658848a7d39546e48b9393690b5ff18473a7b&bH=c8830c10-6719-574b-b825-847faf9b583c)

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes #181948

### CODE REVIEW

File: src/vs/workbench/contrib/search/browser/searchView.ts [hunk 1]
```diff
@@ -1995,6 +1994,11 @@ export class SearchView extends ViewPane {
 	}
 
 	public override saveState(): void {
+		// This can be called before renderBody() method gets called for the first time
```
Comment (andreamah) [inline src/vs/workbench/contrib/search/browser/searchView.ts:1997]: good catch. Could you actually do the check before checking `this.searchWidget.searchInput` on line 2009? (ie: 
```
if (this.searchWidget.searchInput)
```

becomes 
```
if (this.searchWidget && this.searchWidget.searchInput)
```

Just a nitpick.

**Review by andreamah — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/search/browser/searchView.ts (hunk 1 above)
Comment (jeanp413) [reply src/vs/workbench/contrib/search/browser/searchView.ts:1997]: The same applies for `inputPatternExcludes`, `searchAndReplaceWidget`, etc, it's fine to return early in this case as the saved state is from dom elements, also it's safer this way so we don't override state for example `this.inputPatternExcludes?.getValue().trim() ?? '';` will override the state with `''` because it's not set yet in the `renderBody` method

**Review by andreamah — APPROVED** [review]
Thanks so much for the contrib!

**Review by connor4312 — APPROVED** [review]
