### PR TITLE
Issue #93589: Rename 'renameShorthandProperties' setting to 'useAliasesForRenames'

### LINKED ISSUE #93589: `renameShorthandProperties` has confusing name
- VSCode Version: 1.43.2
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. Try to understand the `renameShorthandProperties` setting

I have been trying to get my head around the `renameShorthandProperties` setting. After reading through https://github.com/microsoft/TypeScript/issues/29238 and running some tests, it seems that this setting may have been named or configured incorrectly. For this reason, I am suggesting some changes.

As far as I can tell, the setting name represents what the setting will do when disabled—_not_ what it will do when it's enabled (the default).

Example from https://github.com/microsoft/TypeScript/issues/29238#issuecomment-457664835:

```ts
const x = {
	y: 'value'
//  ^- rename at key
}
const { y } = x;
//      ^- rename at declaration
console.log(y);
//          ^- rename at use
```

What happens if I rename at use (with the default setting)?

The setting name ("rename shorthand properties") and its default value of `true` would seem to suggest that an alias should not be introduced, and the destructured property (aka "shorthand property") should also be renamed:

```ts
const x = {
    s: 'value',
};
const { s } = x;
console.log(s);
```

However, the opposite will happen: the destructured property will be aliased, not renamed:

```ts
const x = {
    y: 'value',
};
const { y: s } = x;
console.log(s);
```

Am I right in thinking this is potentially confusing, or do I misunderstand something?

If my thinking is correct, I believe the setting should be renamed (to avoid confusion), _or_ the current name can stay but the default should be flipped from `true` to `false`, to reflect what the setting is actually doing. Note however that this would be a breaking change.

Does this issue occur when all extensions are disabled?: Yes

Related:
- https://github.com/microsoft/vscode/commit/b4522997ac7ff1e76d49b951868c63ad683618cf
- https://github.com/microsoft/TypeScript/issues/29238

### PR DESCRIPTION
**Pull request by swiz115**
This PR fixes #93589

The original setting name 'renameShorthandProperties' represents what the setting will do when disabled—not what it will do when it's enabled (the default). Changing the setting name to 'useAliasesForRenames' is better suited.

### CODE REVIEW

File: extensions/typescript-language-features/src/features/fileConfigurationManager.ts [hunk 1]
```diff
@@ -186,7 +186,7 @@ export default class FileConfigurationManager extends Disposable {
 			importModuleSpecifierPreference: getImportModuleSpecifierPreference(config),
 			importModuleSpecifierEnding: getImportModuleSpecifierEndingPreference(config),
 			allowTextChangesInNewFiles: document.uri.scheme === fileSchemes.file,
-			providePrefixAndSuffixTextForRename: config.get<boolean>('renameShorthandProperties', true),
+			providePrefixAndSuffixTextForRename: config.get<boolean>('useAliasesForRenames', true),
```
Comment (mjbvz) [inline extensions/typescript-language-features/src/features/fileConfigurationManager.ts:189]: This should read both the old and new setting value for migration

File: extensions/typescript-language-features/package.json [hunk 2]
```diff
@@ -674,16 +674,16 @@
           "description": "%typescript.preferences.importModuleSpecifierEnding%",
           "scope": "resource"
         },
-        "javascript.preferences.renameShorthandProperties": {
+        "javascript.preferences.useAliasesForRenames": {
           "type": "boolean",
           "default": true,
-          "description": "%typescript.preferences.renameShorthandProperties%",
+          "description": "%typescript.preferences.useAliasesForRenames%",
```
Comment (mjbvz) [inline extensions/typescript-language-features/package.json:680]: Instead of renaming this property, create a copy of it and than mark `renameShorthandProperties` with a deprecated message that points to the new property

**Review by mjbvz — CHANGES_REQUESTED** [review]
Thanks for taking a look! The name looks good but we also need to make sure migration to the new property is handled

File: extensions/typescript-language-features/src/features/fileConfigurationManager.ts (hunk 1 above)
Comment (smithjosh115) [reply extensions/typescript-language-features/src/features/fileConfigurationManager.ts:189]: Thanks you guidance! This was an attempt at my first PR. I'll keep this in mind with my future contributions.

Comment (mjbvz) [reply extensions/typescript-language-features/src/features/fileConfigurationManager.ts:189]: Until we remove the deprecated setting, we should make sure we respect previous setting value. Something like:

```ts
config.get<boolean>('renameShorthandProperties', true) === false ? false : config.get<boolean>('useAliasesForRenames', true)
```

**Review by mjbvz — CHANGES_REQUESTED** [review]

File: extensions/typescript-language-features/src/features/fileConfigurationManager.ts (hunk 1 above)
Comment (smithjosh115) [reply extensions/typescript-language-features/src/features/fileConfigurationManager.ts]: I apologize. Not sure how I missed this in the previous attempt at fixing my first commit.

**Comment by mjbvz** [comment]
Thanks! Will be the next VS Code insiders build and is scheduled to go out with VS code 1.45
