### PR TITLE
fix: add cancellation token support to ChatAgentResponseStream

### LINKED ISSUE #291295: Pressing Stop does not stop Agent session if using Ask tool
https://github.com/user-attachments/assets/692cd479-b7b9-4d69-8e82-f02cc636c349

cc @digitarald @roblourens

### PR DESCRIPTION
**Pull request by karthiknadig**
fixes: https://github.com/microsoft/vscode/issues/291295

### CODE REVIEW

**Review by bpasero — APPROVED** [review]

File: src/vs/workbench/api/common/extHostChatAgents2.ts [hunk 1]
```diff
@@ -330,8 +331,8 @@ export class ChatAgentResponseStream {
 
 					_report(dto);
 
-					// Wait for the user to submit answers
-					return deferred.p;
+					// Wait for the user to submit answers, but respect cancellation
+					return raceCancellation(deferred.p, that._token);
```
Comment (roblourens) [inline src/vs/workbench/api/common/extHostChatAgents2.ts:335]: Why is this tool implemented in the extension when it has this tight coupling with UI? The `ChatAgentResponseStream` is not supposed to return a value to the caller, that's contrary to the concept of a "stream" IMO

Comment (karthiknadig) [reply src/vs/workbench/api/common/extHostChatAgents2.ts:335]: I will create an issue to move this into main and get rid of this part.

Comment (karthiknadig) [reply src/vs/workbench/api/common/extHostChatAgents2.ts:335]: https://github.com/microsoft/vscode/issues/291349
