### PR TITLE
fix already in transaction error

### LINKED ISSUE #270011: Chat view screen cheese
Type: <b>Bug</b>

Sorry, not steps. I see screen cheese in the chat view and a couple of stacktraces/error logs like thise

```
ERR Already in transaction: Error: Already in transaction
    at fYi.transact (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:290:5907)
    at bPi.db (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:290:17336)
    at bPi.updateElementHeight (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:290:13496)
    at yss.updateElementHeight (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:333:7801)
    at Jk.updateElementHeight (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:429:15831)
    at Bae.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1701:5734)
    at E.C (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:29:2392)
    at E.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:29:2611)
    at F1e.nb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1653:25071)
    at Bae.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1653:35992)
```

VS Code version: Code - Insiders 1.105.0-insider (72f7c60cfcc01d4e8a437f4a1704b8bbd3229411, 2025-10-03T20:13:56.017Z)
OS version: Darwin arm64 24.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: enabled_on<br>trees_in_viz: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 5, 5|
|Memory (System)|32.00GB (1.65GB free)|
|Process Argv|--log info --log github.copilot-chat=info --crash-reporter-id c8f02c9c-0a89-4cf8-a88c-8204c6be2a75|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-opennewinstance|chr|0.0.15
css-theme-completions|con|0.0.5
vscode-eslint|dba|3.0.19
codespaces|Git|1.17.4
copilot|Git|1.376.1794
copilot-chat|Git|0.32.2025100302
remotehub|Git|0.65.2025081801
vscode-pull-request-github|Git|0.119.2025100204
vscode-postfix-ts|ipa|1.13.2
browser-links|jri|0.0.11
references-plusplus|jri|0.0.5
regex-notebook|jri|0.0.6
vscode-pr-pinger|jri|0.0.6
vscode-codemetrics|kis|1.26.1
template-string-converter|meg|0.6.1
python|ms-|2025.14.0
vscode-python-envs|ms-|1.8.0
remote-containers|ms-|0.429.0
remote-ssh|ms-|0.121.2025093015
remote-ssh-edit|ms-|0.87.0
azure-repos|ms-|0.40.0
extension-test-runner|ms-|0.0.12
hexeditor|ms-|1.11.1
js-debug-nightly|ms-|2025.10.117
remote-explorer|ms-|0.6.2025081809
remote-repositories|ms-|0.43.2025081801
remote-server|ms-|1.6.2025091709
ts-file-path-support|ms-|1.0.0
vscode-copilot-vision|ms-|0.2.2025032409
vscode-github-issue-notebooks|ms-|0.0.133
vscode-typescript-next|ms-|6.0.20251005
toggle|reb|0.0.2
vscode-todo-highlight|way|1.0.5
vscode-selfhost-import-aid|ms-|0.0.1
vscode-selfhost-test-provider|ms-|0.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
pythonvspyt551:31249597
nativeloc1:31118317
dwcopilot:31158714
dwoutputs:31242946
copilot_t_ci:31333650
g012b348:31231168
6gi0g917:31259950
pythonrdcb7:31268811
usemplatestapi:31297334
6518g693:31302842
0g1h6703:31329154
cs4_fixed:31391938
testaa123:31335226
6abeh943:31336334
envsactivate1:31349248
editstats-enabled:31346256
aa_t:31379596
cloudbuttont:31366566
todos-0:31366869
qwen_all_req:31396049
multireplacestring:31382717
nb255704_tf:31377673
3efgi100_wstrepl:31382709
nes-auto-20:31394061
ae882133:31390472
trigger-command-fix:31379601
chat-sessions-view-c:31392542
auto_model_enabled:31396818
node-fetch:31395554
grok-control-prompt:31384642
use-responses-api:31390341
ic2f3768:31396430

```

</details>

### PR DESCRIPTION
**Pull request by justschen**
should fix https://github.com/microsoft/vscode/issues/270011

cc @roblourens 

382-Kyogre

### CODE REVIEW

**Review by dmitrivMS — DISMISSED** [review]

File: src/vs/workbench/contrib/chat/browser/chatContentParts/chatThinkingContentPart.ts [hunk 1]
```diff
@@ -194,7 +191,6 @@ export class ChatThinkingContentPart extends ChatCollapsibleContentPart implemen
 			if (this.headerButton) {
 				this.headerButton.icon = collapsed ? Codicon.chevronRight : Codicon.chevronDown;
 			}
-			this._onDidChangeHeight.fire();
```
Comment (roblourens) [inline src/vs/workbench/contrib/chat/browser/chatContentParts/chatThinkingContentPart.ts:197]: Don't you still need to fire this when the thing is clicked?

Comment (justschen) [reply src/vs/workbench/contrib/chat/browser/chatContentParts/chatThinkingContentPart.ts:197]: 🤦🏻 you're right

Comment (roblourens) [reply src/vs/workbench/contrib/chat/browser/chatContentParts/chatThinkingContentPart.ts:197]: But it looks like these can also be called during the list render call eg because `setPerItemCollapsedState` is also called to initialize the part.

Comment (justschen) [reply src/vs/workbench/contrib/chat/browser/chatContentParts/chatThinkingContentPart.ts:197]: i'll fire these only on button click yeah

**Review by bpasero — APPROVED** [review]

**Review by roblourens — APPROVED** [review]
