### PR TITLE
Move shell integration ps1 into module 

### LINKED ISSUE #250000: `shellIntegration.ps1` Leaks Variables To Global Scope
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
```pwsh
1.100.2
848b80aeb52026648a8ff9f7c45a9b0a80641e2e
x64
```
- OS Version: _Microsoft Windows 11 Enterprise_

Steps to Reproduce:

1. Use Shell Integration
2. Run `Get-Variable`
3. See below variables. ( NOTE: I see some with underscores which may be necessary unfortunately. The other more generic ones could prove problematic if someone uses the same name )
```pwsh
$var = @(
                <# VSCode Shell Integration #>
		'__vscode_shell_env_reporting'
                '__LastHistoryId'
                '__psEditorServices_userInput'
                '__VSCodeOriginalPrompt'
                '__VSCodeOriginalPSConsoleHostReadLine'
                'isStable'
                'isWindows10'
                'Nonce'
                'osVersion'
                '__VSCodeIsInExecution'
                'ContinuationPrompt'
                'envVarsToReport'
)
```

Additionally, lines like the below suggest a script scope but the script is dot-sourced in to the global scope making  `$global:` prefixes unecessary.
https://github.com/microsoft/vscode/blob/3087dba2818c69cbc079f1bc7faa4efb09e56896/src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1#L21
Below is the execution from `procexp.exe`.
```pwsh
"C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\MyUserName\scoop\apps\vscode\1.100.2\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
```

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #250000

### CODE REVIEW

File: src/vs/platform/terminal/node/terminalEnvironment.ts [hunk 1]
```diff
@@ -338,10 +338,10 @@ enum ShellIntegrationExecutable {
 
 const shellIntegrationArgs: Map<ShellIntegrationExecutable, string[]> = new Map();
 // The try catch swallows execution policy errors in the case of the archive distributable
-shellIntegrationArgs.set(ShellIntegrationExecutable.WindowsPwsh, ['-noexit', '-command', 'try { . \"{0}\\out\\vs\\workbench\\contrib\\terminal\\common\\scripts\\shellIntegration.ps1\" } catch {}{1}']);
-shellIntegrationArgs.set(ShellIntegrationExecutable.WindowsPwshLogin, ['-l', '-noexit', '-command', 'try { . \"{0}\\out\\vs\\workbench\\contrib\\terminal\\common\\scripts\\shellIntegration.ps1\" } catch {}{1}']);
-shellIntegrationArgs.set(ShellIntegrationExecutable.Pwsh, ['-noexit', '-command', '. "{0}/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1"{1}']);
-shellIntegrationArgs.set(ShellIntegrationExecutable.PwshLogin, ['-l', '-noexit', '-command', '. "{0}/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1"']);
+shellIntegrationArgs.set(ShellIntegrationExecutable.WindowsPwsh, ['-noexit', '-command', 'try { Import-Module \"{0}\\out\\vs\\workbench\\contrib\\terminal\\common\\scripts\\shellIntegration.psm1\" } catch {}{1}']);
```
Comment (anthonykim1) [inline src/vs/platform/terminal/node/terminalEnvironment.ts:341]: Code OSS test failing, I think we just need to update the test from dot sourcing -> import module that we  have now.

Screenshot 2025-06-13 at 9 14 46 AM

File: src/vs/platform/terminal/test/node/terminalEnvironment.test.ts [hunk 2]
```diff
@@ -48,7 +48,7 @@ suite('platform - terminalEnvironment', async () => {
 		// These tests are only expected to work on Windows 10 build 18309 and above
 		(getWindowsBuildNumber() < 18309 ? suite.skip : suite)('pwsh', async () => {
 			const expectedPs1 = process.platform === 'win32'
-				? `try { . "${repoRoot}\\out\\vs\\workbench\\contrib\\terminal\\common\\scripts\\shellIntegration.ps1" } catch {}`
+				? `try { Import-Module "${repoRoot}\\out\\vs\\workbench\\contrib\\terminal\\common\\scripts\\shellIntegration.ps1" } catch {}`
 				: `. "${repoRoot}/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1"`;
```
Comment (anthonykim1) [inline src/vs/platform/terminal/test/node/terminalEnvironment.test.ts]: I've updated the try statement to use import-module instead of dot sourcing: (`try {  Import-Module`) Should we also change 
```
`: `. "${repoRoot}/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1"`;`
```
to be 
```
: `Import-Module "${repoRoot}/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1"`;
```

Comment (Tyriar) [reply src/vs/platform/terminal/test/node/terminalEnvironment.test.ts]: Yes those should change, any test that expects the old syntax should change. Note also the extension changed ps1 -> psm1. @anthonykim1 did you want to finish up this PR?

Comment (anthonykim1) [reply src/vs/platform/terminal/test/node/terminalEnvironment.test.ts]: yeah, I can give this a shot

File: build/gulpfile.reh.js [hunk 3]
```diff
@@ -67,9 +67,7 @@ const serverResourceIncludes = [
 	'out-build/vs/workbench/contrib/externalTerminal/**/*.scpt',
 
 	// Terminal shell integration
-	'out-build/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1',
-	'out-build/vs/workbench/contrib/terminal/common/scripts/CodeTabExpansion.psm1',
```
Comment (anthonykim1) [inline build/gulpfile.reh.js:71]: Do we not need 
```
build/vs/workbench/contrib/terminal/common/scripts/CodeTabExpansion.psm1,
out-build/vs/workbench/contrib/terminal/common/scripts/GitTabExpansion.psm1
```
anymore?

**Comment by anthonykim1** [comment]
Still seem fine (testing on Mac pwsh with starship, and Windows parallels pwsh 7.4.0.)

Screenshot 2025-06-13 at 4 07 19 PM

and 

Screenshot 2025-06-13 at 5 55 46 PM

File: build/gulpfile.reh.js (hunk 3 above)
Comment (Tyriar) [reply build/gulpfile.reh.js:71]: Nope, the tab expansion ones are gone

**Review by aeschli — APPROVED** [review]
