### PR TITLE
Expose data-vscode-theme-id attribute in webviews, fix #149661

### LINKED ISSUE #149661: Webview CSS: data-vscode-theme-name attribute changes when the language changes
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Write webview CSS depending on `data-vscode-theme-name`, e.g. see https://github.com/microsoft/vscode/issues/97663#issuecomment-630558320
2. Change the language by installing a language pack - the CSS will stop working

Would it be possible to use an ID instead of a name string for this attribute (e.g. a new attribute to prevent breaking changes), or perhaps to force this attribute to be English only?

### PR DESCRIPTION
**Pull request by pingren**
This PR fixes #149661

#### Context
- `data-vscode-theme-name` is exposed on webviews for theme extensions to write theme specific CSS.
- theme label will change when change display language change, which unwanted in #149661.
- themes have a **label** not a **name**. The term should be consistent with theme extension.

#### Changes
- deprecate `data-vscode-theme-name`, rename it to `data-vscode-theme-label`
- add `data-vscode-theme-id`

### CODE REVIEW

**Review by mjbvz — CHANGES_REQUESTED** [review]
Instead of adding a new class, how about always using the default english name for `data-vscode-theme-name`. That way existing users don't have to adopt anything

**Comment by pingren** [comment]
@mjbvz I agree it's better not let existing users adopt anything. However, after some diggings around the code, I realized that

theme label is defined in

https://github.com/microsoft/vscode/blob/042e505d3230c3b7dcd7bb0ecdfbff8452fd19fb/extensions/theme-red/package.json#L15

and could be overwritten by i18n extension in

https://github.com/microsoft/vscode-loc/blob/fb987ff21ae002c918fc0e7039642ae345f279b6/i18n/vscode-language-pack-zh-hans/translations/extensions/theme-red.i18n.json#L14

`themeLabel` is localized when `ExtensionsRegistry` loading theme extensions, and `ThemeService` is not aware of that.

Keeping a copy of English `themeLabel` is overkill. Therefore, adding a `data-vscode-theme-id` should be the way to address the issue with minimal efforts.

**Comment by mjbvz** [comment]
Introducing this new attribute both leaves the current broken behavior  and introduces a new thing for users/extension authors to adopt. Not a fan

@aeschli Any ideas on reading the default English value of a theme name?

**Comment by pingren** [comment]
Some themes using `data-vscode-theme-name` from https://github.com/search?q=data-vscode-theme-name&type=code. 
Most of them are used to for theme specific colors or styles. I don't know if there are better way to get exact usage stats.

**Comment by aeschli** [comment]
Searching the top 6000 extensions on the Marketplace so far only `rangav.vscode-thunder-client` uses `data-vscode-theme-name`

**Comment by aeschli** [comment]
After searching 37'800 extensions, I found `data-vscode-theme-name` at the following spaces

blueplanet-ciena.ciena-blueplanet/resource-type-graph/main.91fb18098d9d6cca2a82.js
cweijan.vscode-database-client2/out/webview/js/app.js
cweijan.vscode-database-client2/out/webview/js/query.js
cweijan.vscode-dm-client/out/webview/js/app.js
cweijan.vscode-es-client2/out/webview/js/app.js
cweijan.vscode-es-client2/out/webview/js/query.js
cweijan.vscode-mysql-client2/out/webview/js/app.js
cweijan.vscode-mysql-client2/out/webview/js/query.js
cweijan.vscode-postgresql-client2/out/webview/js/app.js
cweijan.vscode-postgresql-client2/out/webview/js/query.js
cweijan.vscode-redis-client/out/webview/js/app.js
cweijan.vscode-redis-client/out/webview/js/query.js
cweijan.vscode-ssh/out/webview/js/app.js
cweijan.vscode-ssh/out/webview/js/query.js
eliostruyf.vscode-theming-devtools/dist/webview.js
LigaAI.liga/out/web-dist/assets/i18n.js
Lightrun.lightrunplugin-saas/webpack/build/configViewer.js
Lightrun.lightrunplugin-saas/webpack/build/logs.js
rangav.vscode-thunder-client/dist/extension.js
rebornix.vscode-code-renderer/out/client/index.js
YuTengjing.scripting-listener/dist/web/webview.js

My suggestion would be to deprecate `data-vscode-theme-name` (remove it from documentation, but leave it as is for the next half year), add `data-vscode-theme-id` and `data-vscode-theme-label` and inform the extensions above.

**Comment by pingren** [comment]
Thank you for your research! 
I will change the PR to deprecate `data-vscode-theme-name` and add `data-vscode-theme-id` and `data-vscode-theme-label`. 
I could submit another PR to https://github.com/microsoft/vscode-docs about these changes if you want.

And I am just curious. How did you search for source code of extensions on the Marketplace?

**Comment by aeschli** [comment]
@pingren An update to the docs would be fantastic.
We have an internal tool that downloads a set of extensions from the marketplace so we can search them

**Comment by pingren** [comment]
@aeschli PR Updated. Please take a look when you have a moment.

**Comment by aeschli** [comment]
I'd rather not introduce the `id` to `platform/common/IColorTheme`.

Instead you can do the following:
In the [WebviewThemeDataProvider](https://github.com/microsoft/vscode/blob/f58dbc26895b25c5a82cc67eb319a2f4d253c594/src/vs/workbench/contrib/webview/browser/themeing.ts#L30) use `IWorkbenchThemeService` instead of `IThemeService`

Then the theme you get with `this._themeService.getColorTheme()` is of type `IWorkbenchColorTheme` and you can access the property `id`

**Comment by pingren** [comment]
Updated: use `IWorkbenchThemeService` instead of `IThemeService`

**Comment by aeschli** [comment]
Thanks @pingren. Can you also remove the change in src/vs/workbench/contrib/terminal/test/common/terminalColorRegistry.test.ts?

**Comment by pingren** [comment]
Thank you! Sorry for that. 

Updated: Remove change in `src/vs/workbench/contrib/terminal/test/common/terminalColorRegistry.test.ts`

**Review by aeschli — DISMISSED** [review]

File: src/vs/workbench/contrib/webview/browser/themeing.ts [hunk 1]
```diff
@@ -75,7 +76,7 @@ export class WebviewThemeDataProvider extends Disposable {
 			};
 
 			const activeTheme = ApiThemeClassName.fromTheme(theme);
-			this._cachedWebViewThemeData = { styles, activeTheme, themeLabel: theme.label, };
+			this._cachedWebViewThemeData = { styles, activeTheme, themeLabel: theme.label, themeId: theme.settingsId };
```
Comment (mjbvz) [inline src/vs/workbench/contrib/webview/browser/themeing.ts:79]: @aeschli Can you please confirm that `settingsId` is a good value to use here? I switched to use this since `theme.id` is not friendly to consume. Here's some example values for Dark+:

- `theme.id`: `vs-dark vscode-theme-defaults-themes-dark_plus-json`
- `theme.settingsId: `Default Dark+`

Comment (aeschli) [reply src/vs/workbench/contrib/webview/browser/themeing.ts:79]: Yes, sorry for not realizing this. settingsId is what we want (it's unique and it's what can be used in the settings)

**Review by mjbvz — APPROVED** [review]
