### PR TITLE
have a separate progress notification for text save participants and a separate cancellation token so that save participantion can be skipped without cancelling save

### LINKED ISSUE #209789: "Getting code actions" holds up saving for too long
Type: <b>Bug</b>

- Have a few extensions and a big Python workspace.
- Enable PyLance type checking.
- Work, work...
- Maybe have a big file search in progress.
- Try to save a file.

You often get a window saying "Saving 'foo.py': Getting code actions from (a bunch of extensions)". This can take many seconds. Sometimes it just gets stuck and you have to reload the window.

Screenshot 2024-04-07 at 7 06 10 PM

My impression is that this high-priority user action is getting stuck behind lower-priority tasks (e.g. reindexing a file, doing a large search), possibly even in another window. When I'm saving a file, if the save actions need e.g. the PyLance LSP, they should preempt other pending tasks, or at least run in parallel (with higher priority).

Secondly, the only option should not be to cancel saving. At least give me a button to save the file as-is, skipping the on-save actions.

VS Code version: Code - Insiders 1.89.0-insider (Universal) (d6eba9b861e3ab7d1935cff61c3943e319f5c830, 2024-04-05T05:53:04.895Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 7, 6|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 7b87a5b2-68e7-4d42-ad22-32e3bce2e5e7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
ruff|cha|2024.16.0
gitlens|eam|14.9.0
copilot|Git|1.178.0
copilot-chat|Git|0.14.0
vscode-pull-request-github|Git|0.86.0
go|gol|0.41.2
vscode-cython|ktn|1.0.3
marp-vscode|mar|2.8.0
python-path|mge|0.0.14
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.5.10961012
isort|ms-|2023.13.10681007
python|ms-|2024.4.0
vscode-pylance|ms-|2024.4.1
jupyter|ms-|2024.3.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
makefile-tools|ms-|0.9.10
sourcegraph|sou|2.2.16
even-better-toml|tam|0.19.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805:30301674
vsaa593cf:30376535
py29gd2263:30784851
c4g48928:30535728
vscrpc:30624061
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
bf62j303:30968145
cppperfnew:30980852
8082a590:30961435
fegfb526:30952798
bg6jg535:30979844
ccp2r3:30958153
pythonait:30973460
gee8j676:31009450
gd77d436:30999572

```

</details>

### PR DESCRIPTION
**Pull request by jrieken**
fixes https://github.com/microsoft/vscode/issues/209789

Make it like so ⬇️. There is a dedicated progress notification for save participants and skip-action

Screenshot 2024-10-02 at 10 00 00

### CODE REVIEW

File: src/vs/workbench/services/textfile/common/textFileSaveParticipant.ts [hunk 1]
```diff
@@ -32,25 +36,41 @@ export class TextFileSaveParticipant extends Disposable {
...
 
-		for (const saveParticipant of this.saveParticipants) {
-			if (token.isCancellationRequested || !model.textEditorModel /* disposed */) {
-				break;
-			}
+		const cts = new CancellationTokenSource(token);
+
+		await this.progressService.withProgress({
+			priority: NotificationPriority.URGENT,
+			location: ProgressLocation.Notification,
```
Comment (bpasero) [inline src/vs/workbench/services/textfile/common/textFileSaveParticipant.ts:43]: Are you intentionally picking `ProgressLocation.Notification` here to show it to the user? Because the overall save is reported on `ProgressLocation.Window` here: https://github.com/microsoft/vscode/blob/b7a9323c5213f3c1c104304c10645f54bd2ffc0c/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L825

File: src/vs/workbench/services/textfile/common/textFileSaveParticipant.ts [hunk 2]
```diff
@@ -32,25 +36,41 @@ export class TextFileSaveParticipant extends Disposable {
 		// undoStop before participation
 		model.textEditorModel?.pushStackElement();
 
-		for (const saveParticipant of this.saveParticipants) {
-			if (token.isCancellationRequested || !model.textEditorModel /* disposed */) {
-				break;
-			}
+		const cts = new CancellationTokenSource(token);
```
Comment (bpasero) [inline src/vs/workbench/services/textfile/common/textFileSaveParticipant.ts:39]: Should we still be using the `progress` parameter to report that we are in the "running save participants" phase here?

**Review by bpasero — CHANGES_REQUESTED** [review]

File: src/vs/workbench/services/textfile/common/textFileSaveParticipant.ts (hunk 2 above)
Comment (kevinhehehaha) [reply src/vs/workbench/services/textfile/common/textFileSaveParticipant.ts:39]: https://github.com/microsoft/vscode/pull/230291#discussion_r1784289747

File: src/vs/workbench/services/textfile/common/textFileSaveParticipant.ts (hunk 1 above)
Comment (jrieken) [reply src/vs/workbench/services/textfile/common/textFileSaveParticipant.ts:43]: Yeah, I did that on purpose so that it's really clear what's blocking save. Tho, I don't know if calling out the extensions is fair because the whole operation can be blocked 

* because of a slow/bad save participant, 
* or because of unresponsive EH

In the latter case we will "blame" the save participant extension which are equally "stuck in traffic" as anything else.

**Review by bpasero — DISMISSED** [review]

**Review by bpasero — APPROVED** [review]
