### PR TITLE
:lipstick: integration test notebook

### LINKED ISSUE #103003: Failing notebook integration tests in build
They seem to be running fine out of sources but not if I do not give focus to the window. 

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=82545&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&s=d654deb9-056d-50a2-1717-90c08683d50a&t=8e2e103d-8d5d-54da-dc73-3c44bf1dc402&l=947

### PR DESCRIPTION
**Pull request by rebornix**
This PR fixes #103003

### CODE REVIEW

File: extensions/vscode-notebook-tests/src/notebookTestMain.ts [hunk 1]
```diff
@@ -15,7 +15,7 @@ export function activate(context: vscode.ExtensionContext): any {
 	context.subscriptions.push(vscode.notebook.registerNotebookContentProvider('notebookCoreTest', {
 		onDidChangeNotebook: _onDidChangeNotebook.event,
 		openNotebook: async (_resource: vscode.Uri) => {
```
Comment (rebornix) [inline extensions/vscode-notebook-tests/src/notebookTestMain.ts:17]: test
