### PR TITLE
Fixes 115154: Add "overflow: hidden" style to split-view-view

### LINKED ISSUE #115154: Split terminal visually overlaps with neighbor during resize
Issue Type: <b>Bug</b>

**Repro**
1. Split a terminal
1. In both terminals, run some kind of script that outputs text that horizontally fills the terminal
1. Now resize the left terminal to make the right one smaller

**Bug**
For a half second during the resize, the content of two terminals end up overlapping

https://user-images.githubusercontent.com/12821956/105904006-73c69900-5fd5-11eb-9718-18ac400cd725.mp4

VS Code version: Code - Insiders 1.53.0-insider (1a9dd758530782ee4bb09a15bdc484f3dcb9b5a3, 2021-01-26T05:12:23.287Z)
OS version: Darwin x64 20.2.0
Remote OS version: Linux x64 5.4.0-1036-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id cc7f0c9b-aa2b-4a45-8baa-81ffda32679e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1036-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (2 x 2593)|
|Memory (System)|3.84GB (0.93GB free)|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by shskwmt**
This PR fixes https://github.com/microsoft/vscode/issues/115154

https://user-images.githubusercontent.com/17052177/106205162-6261d480-6201-11eb-9d47-b0bac200382f.mp4

### CODE REVIEW

File: src/vs/base/browser/ui/splitview/splitview.ts [hunk 1]
```diff
@@ -675,6 +675,7 @@ export class SplitView<TLayoutContext = undefined> extends Disposable {
 
 		// Add view
 		const container = $('.split-view-view');
+		container.style.overflow = 'hidden';
```
Comment (Tyriar) [inline src/vs/base/browser/ui/splitview/splitview.ts:678]: Let's stick it within the terminal component instead of the general split view widget as I'm worried about regression other parts of the workbench that use it. terminal.css seems like an ideal place for this

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/base/browser/ui/splitview/splitview.ts (hunk 1 above)
Comment (shskwmt) [reply src/vs/base/browser/ui/splitview/splitview.ts]: Thank you, I fixed. https://github.com/microsoft/vscode/pull/115345/commits/a916ce9076cb1f84e4f35728a7e4ed7be388adce


https://user-images.githubusercontent.com/17052177/106344480-69fea780-62ed-11eb-8d50-88e990dab837.mp4

**Review by Tyriar — APPROVED** [review]
Works great, thanks. I also verified the link hover still shows outside correctly:

image
