### PR TITLE
Calling webContents.paste on the floating window

### LINKED ISSUE #246091: Pasting doesn't work in an extracted window
from @ulugbekna :

repro:

1. drag a file to become an extracted vscode window
2. copy text
3. try pasting into an editor within the extracted window

Version: 1.100.0-insider
Commit: 174af221c9ea2ccdb64abe4aab8e1a805e77beae
Date: 2025-04-09T05:05:17.975Z
Electron: 34.4.1
ElectronBuildId: 11317338
Chromium: 132.0.6834.210
Node.js: 20.18.3
V8: 13.2.152.41-electron.0
OS: Darwin arm64 24.4.0

### PR DESCRIPTION
**Pull request by aiday-mar**
fixes https://github.com/microsoft/vscode/issues/246091#event-17187359773

### CODE REVIEW

File: src/vs/editor/contrib/clipboard/browser/clipboard.ts [hunk 1]
```diff
@@ -301,7 +302,8 @@ if (PasteAction) {
 
 	// 2. Paste: (default) handle case when focus is somewhere else.
 	PasteAction.addImplementation(0, 'generic-dom', (accessor: ServicesAccessor, args: any) => {
-		const triggerPaste = accessor.get(IClipboardService).triggerPaste();
+		const targetWindowId = getWindowId(getActiveWindow());
+		const triggerPaste = accessor.get(IClipboardService).triggerPaste(targetWindowId);
```
Comment (bpasero) [inline src/vs/editor/contrib/clipboard/browser/clipboard.ts:306]: You could do `getActiveWindow().vscodeWindowId`

File: src/vs/editor/contrib/clipboard/browser/clipboard.ts [hunk 2]
```diff
@@ -248,7 +248,8 @@ if (PasteAction) {
 			}
 
 			const sw = StopWatch.create(true);
-			const triggerPaste = clipboardService.triggerPaste();
+			const targetWindowId = getWindowId(getActiveWindow());
+			const triggerPaste = clipboardService.triggerPaste(targetWindowId);
```
Comment (bpasero) [inline src/vs/editor/contrib/clipboard/browser/clipboard.ts:252]: Same here

File: src/vs/editor/contrib/clipboard/browser/clipboard.ts (hunk 1 above)
Comment (aiday-mar) [reply src/vs/editor/contrib/clipboard/browser/clipboard.ts:306]: Cool thanks for the review, will do!

**Comment by bpasero** [comment]
@aiday-mar thanks, overall makes sense. `getActiveWindow` is a bit dangerous if there could be any chance that the operation is long running (would it ever be?) and the user moves focus somewhere else. If you have any `HTMLElement` in hand to get the window from, thats usually safer. But I am not sure this would be an issue here after all because typically paste executes where you are focused.

**Comment by aiday-mar** [comment]
Hi @bpasero thank you for the comment. Do you mean we should do the paste on the new active window, if it changes, while the paste operation is in progress?  So to do this, in the file `nativeHostMainService.ts` I could write instead:

	async triggerPaste(windowId: number | undefined, options?: INativeHostOptions): Promise<void> {
		const activeWindowId = await this.getActiveWindowId(undefined);
		if (!activeWindowId) {
			return;
		}
		const window = this.windowById(activeWindowId, windowId);
		return window?.win?.webContents.paste() ?? Promise.resolve();
	}

So that the paste is executed on the active window at the moment when the paste happens. But I wonder if this is expected behavior, as perhaps the user wants the paste operation to happen in the window where the originally triggered the paste.

**Comment by bpasero** [comment]
@aiday-mar no I think its good, lets keep how you have it.

**Review by bpasero — APPROVED** [review]

**Comment by tpucci** [comment]
Hey @aiday-mar 😀
I've just discovered this PR and this makes me think you could help me get some direction to fix https://github.com/microsoft/vscode/issues/129178.

I would be very happy if you could give me a few hints for me to contribute and fix that issue, if you have the time 🙏

Have a good one

**Comment by aiday-mar** [comment]
Hi @tpucci thank you for your comment. I believe I may lack some context on the issue you reference, as it concerns webviews. Perhaps @mjbvz could give you some pointers.
