### PR TITLE
Fix #172989

### LINKED ISSUE #172989: Cannot install extensions
Sanity testing 1.75 on macOS and I found that installing extensions would always fail due to following error

```
2023-01-31 18:21:18.888 [error] Invalid extensions content in vscode-userdata:/Users/penlv/.vscode/extensions/extensions.json: Error: Invalid extensions content in vscode-userdata:/Users/penlv/.vscode/extensions/extensions.json
    at I.p (vscode-file://vscode-app/private/var/folders/j7/py1_06vs0y3bbcdpsn0pd66h0000gn/T/AppTranslocation/2287E3F7-7106-459F-A86E-6AFEAEE53302/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:94382)
    at Object.factory (vscode-file://vscode-app/private/var/folders/j7/py1_06vs0y3bbcdpsn0pd66h0000gn/T/AppTranslocation/2287E3F7-7106-459F-A86E-6AFEAEE53302/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:93857)

```

I was using 1.74.3 before, tried following steps:

* Switch back to 1.74.3, installing extensions work
* Switch back to 1.75, installing extensions continues to fail for the same errors

My `extensions.json` content

```
[{"identifier":{"id":"rebornix.nova","uuid":"258ae097-be50-4084-a73a-c8b1a36a8970"},"version":"0.2.2","location":{"$mid":1,"scheme":"rebornix.nova-0.2.2"},"metadata":{"id":"258ae097-be50-4084-a73a-c8b1a36a8970","publisherId":"d30b9513-547b-4112-9c9c-0fcffa960258","publisherDisplayName":"Peng Lv","isPreReleaseVersion":false,"installedTimestamp":1641933915286}},{"identifier":{"id":"github.codespaces","uuid":"4023d3e5-c840-4cdd-8b54-51c77548aa3f"},"version":"1.13.3","location":{"$mid":1,"scheme":"github.codespaces-1.13.3"},"metadata":{"id":"4023d3e5-c840-4cdd-8b54-51c77548aa3f","publisherDisplayName":"GitHub","publisherId":"7c1c19cd-78eb-4dfb-8999-99caf7679002","isPreReleaseVersion":false,"isApplicationScoped":false,"installedTimestamp":1670275424102,"pinned":true}},{"identifier":{"id":"ms-toolsai.jupyter-keymap","uuid":"9f6dc8db-620c-4844-b8c5-e74914f1be27"},"version":"1.0.0","location":{"$mid":1,"scheme":"ms-toolsai.jupyter-keymap-1.0.0"},"metadata":{"id":"9f6dc8db-620c-4844-b8c5-e74914f1be27","publisherId":"ac8eb7c9-3e59-4b39-8040-f0484d8170ce","publisherDisplayName":"Microsoft","targetPlatform":"undefined","isApplicationScoped":false,"updated":false,"isPreReleaseVersion":false,"installedTimestamp":1670431017420,"preRelease":false}},{"identifier":{"id":"ms-toolsai.vscode-jupyter-cell-tags","uuid":"ab4fb32a-befb-4102-adf9-1652d0cd6a5e"},"version":"0.1.6","location":{"$mid":1,"scheme":"ms-toolsai.vscode-jupyter-cell-tags-0.1.6"},"metadata":{"id":"ab4fb32a-befb-4102-adf9-1652d0cd6a5e","publisherId":"ac8eb7c9-3e59-4b39-8040-f0484d8170ce","publisherDisplayName":"Microsoft","targetPlatform":"undefined","isApplicationScoped":false,"updated":false,"isPreReleaseVersion":false,"installedTimestamp":1670431017429,"preRelease":false}},{"identifier":{"id":"ms-toolsai.vscode-jupyter-slideshow","uuid":"e153ca70-b543-4865-b4c5-b31d34185948"},"version":"0.1.5","location":{"$mid":1,"scheme":"ms-toolsai.vscode-jupyter-slideshow-0.1.5"},"metadata":{"id":"e153ca70-b543-4865-b4c5-b31d34185948","publisherId":"ac8eb7c9-3e59-4b39-8040-f0484d8170ce","publisherDisplayName":"Microsoft","targetPlatform":"undefined","isApplicationScoped":false,"updated":false,"isPreReleaseVersion":false,"installedTimestamp":1670431017433,"preRelease":false}},{"identifier":{"id":"github.vscode-pull-request-github","uuid":"69ddd764-339a-4ecc-97c1-9c4ece58e36d"},"version":"0.56.0","location":{"$mid":1,"scheme":"github.vscode-pull-request-github-0.56.0"},"metadata":{"id":"69ddd764-339a-4ecc-97c1-9c4ece58e36d","publisherId":"7c1c19cd-78eb-4dfb-8999-99caf7679002","publisherDisplayName":"GitHub","targetPlatform":"undefined","isApplicationScoped":false,"updated":true,"isPreReleaseVersion":false,"installedTimestamp":1670474216065,"preRelease":false}},{"identifier":{"id":"ms-toolsai.jupyter","uuid":"6c2f1801-1e7f-45b2-9b5c-7782f1e076e8"},"version":"2022.11.1003412109","location":{"$mid":1,"scheme":"ms-toolsai.jupyter-2022.11.1003412109"},"metadata":{"id":"6c2f1801-1e7f-45b2-9b5c-7782f1e076e8","publisherId":"ac8eb7c9-3e59-4b39-8040-f0484d8170ce","publisherDisplayName":"Microsoft","targetPlatform":"undefined","isApplicationScoped":false,"updated":true,"isPreReleaseVersion":false,"installedTimestamp":1670474216027,"preRelease":false}},{"identifier":{"id":"ms-vscode.vscode-github-issue-notebooks","uuid":"3be1cece-c179-4cd6-b59b-3bae29e1a166"},"version":"0.0.128","location":{"$mid":1,"scheme":"ms-vscode.vscode-github-issue-notebooks-0.0.128"},"metadata":{"id":"3be1cece-c179-4cd6-b59b-3bae29e1a166","publisherId":"5f5636e7-69ed-4afe-b5d6-8d231fb3d3ee","publisherDisplayName":"Microsoft","targetPlatform":"undefined","isApplicationScoped":false,"updated":true,"isPreReleaseVersion":false,"installedTimestamp":1670603827473,"preRelease":false}},{"identifier":{"id":"eamodio.gitlens","uuid":"4de763bd-505d-4978-9575-2b7696ecf94e"},"version":"13.2.0","location":{"$mid":1,"scheme":"eamodio.gitlens-13.2.0"},"metadata":{"id":"4de763bd-505d-4978-9575-2b7696ecf94e","publisherId":"678d198b-9b2e-49d3-96ff-6d801c9575df","publisherDisplayName":"GitKraken","targetPlatform":"undefined","isApplicationScoped":false,"updated":true,"isPreReleaseVersion":false,"installedTimestamp":1671736733466,"preRelease":false}},{"identifier":{"id":"github.github-vscode-theme","uuid":"7328a705-91fc-49e6-8293-da6f112e482d"},"version":"6.3.3","location":{"$mid":1,"scheme":"github.github-vscode-theme-6.3.3"},"metadata":{"id":"7328a705-91fc-49e6-8293-da6f112e482d","publisherId":"7c1c19cd-78eb-4dfb-8999-99caf7679002","publisherDisplayName":"GitHub","targetPlatform":"undefined","isApplicationScoped":false,"updated":true,"isPreReleaseVersion":false,"installedTimestamp":1674599403280,"preRelease":false}},{"identifier":{"id":"ms-toolsai.jupyter-renderers","uuid":"b15c72f8-d5fe-421a-a4f7-27ed9f6addbf"},"version":"1.0.14","location":{"$mid":1,"scheme":"ms-toolsai.jupyter-renderers-1.0.14"},"metadata":{"id":"b15c72f8-d5fe-421a-a4f7-27ed9f6addbf","publisherId":"ac8eb7c9-3e59-4b39-8040-f0484d8170ce","publisherDisplayName":"Microsoft","targetPlatform":"undefined","isApplicationScoped":false,"updated":true,"isPreReleaseVersion":false,"installedTimestamp":1674599403050,"preRelease":false}},{"identifier":{"id":"ms-python.python","uuid":"f1f59ae4-9318-4f3c-a9b5-81b2eaa5f8a5"},"version":"2022.20.2","location":{"$mid":1,"scheme":"ms-python.python-2022.20.2"},"metadata":{"id":"f1f59ae4-9318-4f3c-a9b5-81b2eaa5f8a5","publisherId":"998b010b-e2af-44a5-a6cd-0b5fd3b9b6f8","publisherDisplayName":"Microsoft","targetPlatform":"undefined","isApplicationScoped":false,"updated":true,"isPreReleaseVersion":false,"installedTimestamp":1674599402614,"preRelease":false}},{"identifier":{"id":"ms-python.isort","uuid":"4ad0ce32-ff3f-49f0-83b5-93e5dc00cfff"},"version":"2022.8.0","location":{"$mid":1,"fsPath":"/Users/penlv/.vscode/extensions/ms-python.isort-2022.8.0","path":"/Users/penlv/.vscode/extensions/ms-python.isort-2022.8.0","scheme":"file"},"metadata":{"id":"4ad0ce32-ff3f-49f0-83b5-93e5dc00cfff","publisherId":"998b010b-e2af-44a5-a6cd-0b5fd3b9b6f8","publisherDisplayName":"Microsoft","targetPlatform":"undefined","isApplicationScoped":false,"updated":true,"isPreReleaseVersion":false,"installedTimestamp":1674686475980,"preRelease":false}},{"identifier":{"id":"ms-python.vscode-pylance","uuid":"364d2426-116a-433a-a5d8-a5098dc3afbd"},"version":"2023.1.40","location":{"$mid":1,"fsPath":"/Users/penlv/.vscode/extensions/ms-python.vscode-pylance-2023.1.40","path":"/Users/penlv/.vscode/extensions/ms-python.vscode-pylance-2023.1.40","scheme":"file"},"metadata":{"id":"364d2426-116a-433a-a5d8-a5098dc3afbd","publisherId":"998b010b-e2af-44a5-a6cd-0b5fd3b9b6f8","publisherDisplayName":"Microsoft","targetPlatform":"undefined","isApplicationScoped":false,"updated":true,"isPreReleaseVersion":false,"installedTimestamp":1674686475974,"preRelease":false}}]
```

### PR DESCRIPTION
**Pull request by sandy081**
Fix #172989

### CODE REVIEW

File: src/vs/platform/extensionManagement/common/extensionsProfileScannerService.ts [hunk 1]
```diff
@@ -247,14 +248,23 @@ export abstract class AbstractExtensionsProfileScannerService extends Disposable
...
+						// Extension in new format. No migration needed.
+						location = this.resolveExtensionLocation(e.relativeLocation);
+					} else if (isString(e.location)) {
+						// Extension in intermediate format. Migrate to new format.
 						location = this.resolveExtensionLocation(e.location);
+						migrate = true;
+						e.relativeLocation = e.location;
+						// retain old format so that old clients can read it
+						e.location = location.toJSON();
 					} else {
```
Comment (aeschli) [inline src/vs/platform/extensionManagement/common/extensionsProfileScannerService.ts:261]: I'd add a check `else if (isObject(e.location))` check, in case a user made changes, or the file is corrupted

**Review by aeschli — CHANGES_REQUESTED** [review]

File: src/vs/platform/extensionManagement/common/extensionsProfileScannerService.ts (hunk 1 above)
Comment (aeschli) [reply src/vs/platform/extensionManagement/common/extensionsProfileScannerService.ts:261]: Ok, take it back, better add a check in `isStoredProfileExtension`

Comment (sandy081) [reply src/vs/platform/extensionManagement/common/extensionsProfileScannerService.ts:261]: Added check and also added tests

**Review by aeschli — APPROVED** [review]
