### PR TITLE
Fix text output alignment 

### LINKED ISSUE #143538: New notebook 'text/plain' renderer breaks alignment
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0-insider (Universal) Commit: a0da9978b10ae0b9307c7f545b50a8500efff7eb
- OS Version: Mac OS Monterey 12.2.1

Follow up issue to #143194 as this is a degradation in UX compared to the non-Insider version. Any input on that @rebornix ?

Current:
image

Expected: Different columns should be aligned
image

### PR DESCRIPTION
**Pull request by rebornix**
This PR fixes #143538

The font setting is not respected in the text output we moved into webview, leading to unexpected misalignment for users are using monospace font in editor.

### CODE REVIEW

**Review by roblourens — APPROVED** [review]

File: src/vs/workbench/contrib/notebook/browser/diff/notebookTextDiffEditor.ts [hunk 1]
```diff
@@ -379,20 +379,29 @@ export class NotebookTextDiffEditor extends EditorPane implements INotebookTextD
...
+			...this._notebookOptions.computeDiffWebviewOptions(),
+			fontFamily: this._generateFontFamily()
+		}, undefined) as BackLayerWebView<IDiffCellInfo>;
 		// attach the webview container to the DOM tree first
 		this._list.rowsContainer.insertAdjacentElement('afterbegin', this._modifiedWebview.element);
 		await this._modifiedWebview.createWebview();
 		this._modifiedWebview.element.style.width = `calc(50% - 16px)`;
 		this._modifiedWebview.element.style.left = `calc(50%)`;
 	}
+	_generateFontFamily(): string {
```
Comment (roblourens) [inline src/vs/workbench/contrib/notebook/browser/diff/notebookTextDiffEditor.ts:392]: private?

Comment (rebornix) [reply src/vs/workbench/contrib/notebook/browser/diff/notebookTextDiffEditor.ts:392]: Will tackle this in main.
