### PR TITLE
Fix a potential hang when tsserver exits improperly

### LINKED ISSUE #25807: TSServer Can Hang When Restarting With Ongoing Requests
**Bug**
If the TSServer restarts with ongoing requests queued, the new server instance may not properly startup. in the logs, this looks like a series of cancelled request followed by a restart message, and then more cancelled requests of the same series

### PR DESCRIPTION
**Pull request by mjbvz**
**Bug**
If the TSServer restarts with ongoing requests queued, the new server instance may not properly startup. in the logs, this looks like a series of cancelled request followed by a restart message, and then more cancelled requests of the same series

**fix**
I believe the root cause of this is that the request queue is not properly flushed and the request sequence numbers are not properly reset when starting the new server instance.

Fixes #25807

### CODE REVIEW

File: extensions/typescript/src/typescriptServiceClient.ts [hunk 1]
```diff
@@ -241,6 +239,8 @@ export default class TypeScriptServiceClient implements ITypescriptServiceClient
 			this.trace = this.readTrace();
 			this.tsServerLogLevel = this.readTsServerLogLevel();
 			this.servicePromise = this.startService();
+			this.lastError = null;
```
Comment (mjbvz) [inline extensions/typescript/src/typescriptServiceClient.ts]: I don't think this bit is needed
