### PR TITLE
fix `git similar` quick fix

### LINKED ISSUE #176411: `Git similar` quick fixes no longer work
I noticed that they also don't show up in telemetry

Screenshot 2023-03-07 at 11 12 46 AM

### PR DESCRIPTION
**Pull request by meganrogge**
fix #176411

### CODE REVIEW

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 1]
```diff
@@ -674,7 +674,7 @@ function getOutputMatchForCommand(executedMarker: IMarker | undefined, endMarker
 			i = wrappedLineStart;
 			lines.unshift(getXtermLineContent(buffer, wrappedLineStart, wrappedLineEnd, cols));
 			if (!match) {
-				match = lines[0].match(matcher);
+				match = lines.join('\n').match(matcher);
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:677]: We didn't want to match against all lines joined together, the idea when we last discussed this was to let the quick fix handle multiple lines after the initial match. Doing `lines.join('\n')` will add pretty significant overhead as well.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:677]: You're right, but we mandate at least one match found in the output currently in order to return lines. All of the other quick fixes have output matchers that match a wrapped line

Comment (Tyriar) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:677]: > All of the other quick fixes have output matchers that match a wrapped line

You mean do not right? We want `GitSimilarOutputRegex` to only match `most similar (command|commands) (is|are)` now

Comment (meganrogge) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:677]: Yes, so we should update that and the builtin quick fix. It's just a little weird because then `outputMatch` doesn't mean it's an actual match / what we're looking for anymore.

Comment (Tyriar) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:677]: It's still a match, just a single line match. The experiment trying to have some match multiple lines didn't really work due to perf issues (which is what the regex's are meant to prevent in the first place), too many unique strings being constructed.

Comment (meganrogge) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:677]: I'll update this to make that clear
Screenshot 2023-03-08 at 9 49 13 AM

Comment (meganrogge) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:677]: actually, I guess that doesn't need to be updated 🤔 . I just find it a little confusing still. Will think about if it can be improved

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts [hunk 2]
```diff
@@ -690,7 +690,7 @@ function getOutputMatchForCommand(executedMarker: IMarker | undefined, endMarker
 			i = wrappedLineEnd;
 			lines.push(getXtermLineContent(buffer, wrappedLineStart, wrappedLineEnd, cols));
 			if (!match) {
-				match = lines[lines.length - 1].match(matcher);
+				match = lines.join('\n').match(matcher);
```
Comment (meganrogge) [inline src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts:693]:
```suggestion
				match = lines[lines.length - 1].match(matcher);
```

File: src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts (hunk 1 above)
Comment (Tyriar) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts]: We can clarify it only matches single lines

Comment (meganrogge) [reply src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts]: done

**Comment by meganrogge** [comment]
tests failing

File: src/vs/workbench/contrib/terminal/test/browser/quickFixAddon.test.ts [hunk 3]
```diff
@@ -92,54 +85,6 @@ suite('QuickFixAddon', () => {
 					strictEqual(await (getQuickFixesForCommand([], terminal, createCommand(`gt sttatus`, output, GitSimilarOutputRegex, exitCode), expectedMap, openerService, labelService)), undefined);
 				});
 			});
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/test/browser/quickFixAddon.test.ts:87]: these weren't catching the failure anyway, so fine to remove them

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/test/browser/quickFixAddon.test.ts:87]: we should really have smoke tests for this

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/test/browser/quickFixAddon.test.ts:87]: Aren't they still testing something though?

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/test/browser/quickFixAddon.test.ts:87]: seemingly not since they were passing when this was totally broken

File: src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts [hunk 4]
```diff
@@ -41,8 +41,8 @@ export function gitSimilar(): IInternalOptions {
 				return;
 			}
 			const actions: TerminalQuickFixActionInternal[] = [];
-			const results = matchResult.outputMatch.regexMatch[0].split('\n').map(r => r.trim());
-			for (let i = 1; i < results.length; i++) {
+			const results = matchResult.outputMatch.outputLines.map(r => r.replaceAll('\n', '').trim());
+			for (let i = 3; i < results.length; i++) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts:45]: Instead of hardcoding the line number it starts at, can we scan for the line that the match occurred on (ie. `most similar  ...`) and then add all following lines? I'm concerned about bugs similar to the upstream PR fix where the exact format changes somehow.

File: src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts [hunk 5]
```diff
@@ -11,7 +11,7 @@ import { ITerminalInstance } from 'vs/workbench/contrib/terminal/browser/termina
 export const GitCommandLineRegex = /git/;
 export const GitPushCommandLineRegex = /git\s+push/;
 export const GitTwoDashesRegex = /error: did you mean `--(.+)` \(with two dashes\)\?/;
-export const GitSimilarOutputRegex = /(?:(most similar (command|commands) (is|are)))((\n\s*(?<fixedCommand>[^\s]+))+)/m;
+export const GitSimilarOutputRegex = /(?:(most similar (command|commands) (is|are)))/;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts:14]: Just noticed

```suggestion
export const GitSimilarOutputRegex = /(?:(most similar commands? (is|are)))/;
```

File: src/vs/workbench/contrib/terminal/test/browser/quickFixAddon.test.ts [hunk 6]
```diff
@@ -92,54 +85,6 @@ suite('QuickFixAddon', () => {
...
-			suite('returns actions when', () => {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/test/browser/quickFixAddon.test.ts:95]: I'm still a little confused why we're removing this? We have tests for returning undefined, but not actions like all the other quick fixes? Do we need to tweak the test to something else considering the change we made to this quick fix?

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/test/browser/quickFixAddon.test.ts (hunk 6 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/test/browser/quickFixAddon.test.ts:95]: they fail because the `outputMatch` we provide now does not include any of the actual fixes. Those are handled by the quick fix provider.

File: src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts (hunk 4 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts:45]: I thought about that, but it should always be exact since we're counting wrapped lines here.  Also tested in terminals of varying sizes

File: src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts [hunk 7]
```diff
@@ -37,12 +37,14 @@ export function gitSimilar(): IInternalOptions {
...
-			if (!matchResult?.outputMatch) {
+			const regexMatch = matchResult.outputMatch?.regexMatch[0];
+			if (!regexMatch || !matchResult.outputMatch) {
 				return;
 			}
 			const actions: TerminalQuickFixActionInternal[] = [];
-			const results = matchResult.outputMatch.regexMatch[0].split('\n').map(r => r.trim());
-			for (let i = 1; i < results.length; i++) {
+			const startIndex = matchResult.outputMatch.outputLines.findIndex(l => l.includes(regexMatch)) + 1;
+			const results = matchResult.outputMatch.outputLines.map(r => r.replaceAll('\n', '').trim());
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts:46]: Hasn't `outputLines` already handled wrapped lines at this point?

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts:46]: There shouldn't be any `\n` there if wrapping is already resolved?

**Review by Tyriar — APPROVED** [review]
