### PR TITLE
Fix Integrated Browser Localhost Opener triggering in too many cases

### LINKED ISSUE #293015: Open in external browser opens another tab in vscode when `Open Localhost Links` is enabled
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.109.0
- OS Version: Darwin arm64 25.2.0

Steps to Reproduce:

1. Enable `Open Localhost Links` in settings
2. Open a localhost link in Simple Browser.
3. Select `Open in External Browser` from the three-dot context menu.

https://github.com/user-attachments/assets/52a566a0-e49d-4c64-b2a9-778e9f5e2fcd

### PR DESCRIPTION
**Pull request by jruales**
* Fixes #293015

Turn the Localhost Opener into an external opener, which implicitly is gated by the `allowContributedOpeners` flag

### CODE REVIEW

File: src/vs/workbench/contrib/browserView/electron-browser/browserView.contribution.ts [hunk 1]
```diff
@@ -117,7 +117,11 @@ class LocalhostLinkOpenerContribution extends Disposable implements IWorkbenchCo
 		this._register(openerService.registerOpener(this));
```
Comment (kycutler) [inline src/vs/workbench/contrib/browserView/electron-browser/browserView.contribution.ts]: Looking at how `allowContributedOpeners` is handled already, should we just change this to be `registerExternalOpener(this)` and let the service handle the logic? Then we can audit the places where the flag isn't yet passed but maybe should be

Comment (jruales) [reply src/vs/workbench/contrib/browserView/electron-browser/browserView.contribution.ts]: Done

**Review by kycutler — APPROVED** [review]
