### PR TITLE
Browser: make Playwright per workspace

### LINKED ISSUE #298763: Agent opened browser *in another workspace window*
Type: <b>Bug</b>

I had the agent do a data analysis and create an explainer page for what it found.

After coming back, it had the explainer page open in the browser and the agent was looking at the output but I noticed the same page was also open in another workspace window that is not at all related to the workspace I had opened where the analysis happened.

The other window was also in sharing with agent mode; very odd!

VS Code version: Code - Insiders 1.110.0-insider (Universal) (f5927e727c69039d3037f018f1790ebbbee596bc, 2026-02-28T04:37:38.428Z)
OS version: Darwin arm64 25.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M4 Pro (14 x 2400)|
|GPU Status|2d_canvas: enabled<br>GPU0: VENDOR= 0x106b [Google Inc. (Apple)], DEVICE=0x0000 [ANGLE (Apple, ANGLE Metal Renderer: Apple M4 Pro, Version 26.3 (Build 25D125))], DRIVER_VENDOR=Apple, DRIVER_VERSION=26.3 *ACTIVE*<br>Machine model name: Mac<br>Machine model version: 16.7<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: enabled_on<br>trees_in_viz: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|8, 10, 8|
|Memory (System)|24.00GB (0.20GB free)|
|Process Argv|--log trace --enable-proposed-api digitarald.agent-memory --enable-proposed-api digitarald.agent-handoff --enable-proposed-api digitarald.hello-skill --crash-reporter-id 9b206efe-c338-4f34-baff-2aab1c48a82e|
|Screen Reader|no|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by kycutler**
Fixes #298763

### CODE REVIEW

File: src/vs/platform/browserView/node/playwrightChannel.ts [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+			throw new Error(`Window not initialized for context: ${ctx}`);
+		}
+		const source = (instance as unknown as Record<string, Event<unknown>>)[event];
+		if (typeof source !== 'function') {
+			throw new Error(`Event not found: ${event}`);
+		}
+		return source as Event<T>;
+	}
+
+	call<T>(ctx: string, command: string, arg?: unknown): Promise<T> {
```
Comment (jruales) [inline src/vs/platform/browserView/node/playwrightChannel.ts:52]: Nit: since an __initialize call is kind of like a constructor, maybe put `call` method definition before `listen` method definition in this file

**Review by jruales — APPROVED** [review]
