### PR TITLE
fix microsoft/vscode#117095 de-duplicate reference results

### LINKED ISSUE #117095: vscode-references-view does not de-duplicate results like the built in ReferencesModel
The built-in "go to references" command in vscode uses the `ReferencesModel` to de-duplicate reference results: https://github.com/microsoft/vscode/blob/36dd567011eda09317a76d5dcb820fa9961eb786/src/vs/editor/contrib/gotoSymbol/referencesModel.ts#L171-L182
Equal uri's and ranges constitute duplicate results:
https://github.com/microsoft/vscode/blob/36dd567011eda09317a76d5dcb820fa9961eb786/src/vs/editor/contrib/gotoSymbol/referencesModel.ts#L293-L295
The `ReferencesModel` of the extension does not de-duplicate results at all, but instead always pushes each location to the containing `FileItem`'s references list: https://github.com/microsoft/vscode-references-view/blob/f1b526b39c97981c81d52a98d6e66f8f699dc38a/src/references/model.ts#L73

### PR DESCRIPTION
**Pull request by atscott**
This commit de-duplicates reference and other location results from
API endpoints `executeDefinitionProvider`, `executeDeclarationProvider`,
`executeImplementationProvider`, `executeTypeDefinitionProvider`, and `executeReferenceProvider`
(all commands registered in `goToSymbol.ts` which share the
`getLocationsLinks` helper).

Previously, this work was only done in the `ReferencesModel` which is used by
the `editor.action.findReferences` command. Extensions which called the
`vscode.executeReferenceProvider` would still get the duplicate results.

fix microsoft/vscode#117095

### CODE REVIEW

File: src/vs/editor/contrib/gotoSymbol/goToSymbol.ts [hunk 1]
```diff
@@ -37,7 +39,17 @@ function getLocationLinks<T>(
...
+		const uniqueResults: Set<LocationLink> = new Set();
+		let last: LocationLink | undefined;
+		// Preserve result order by sorting a copy and using that to compare with Set contents.
+		for (const link of [...result].sort(compareLocations)) {
+			if (last === undefined || compareLocations(last, link) !== 0) {
+				uniqueResults.add(link);
+				last = link;
+			}
+		}
+		return result.filter(link => uniqueResults.has(link));
```
Comment (jrieken) [inline src/vs/editor/contrib/gotoSymbol/goToSymbol.ts:52]: You are very, very close the "real" `ReferencesModel`. So, I'd suggest that you create an instance which does all the sorting and de-duping and that you take its result, e.g `ReferencesModel#references`. It might need some tweak but I'd say that's better than the duplication

**Review by jrieken — CHANGES_REQUESTED** [review]

File: src/vs/editor/contrib/gotoSymbol/goToSymbol.ts (hunk 1 above)
Comment (atscott) [reply src/vs/editor/contrib/gotoSymbol/goToSymbol.ts:52]: Let me know if you disagree and think it would still be better to create a `ReferenceModel` instance, but here were my two reasons for not doing that:

I felt that creating a `ReferenceModel` was a bit overkill here since the only two things I needed from it was `compareLocations` and a de-duplicated result array. The duplication of the sorting and comparing code only totals 4 lines and I felt it was much clearer to have that small bit of logic duplicated here rather than to use a whole `ReferenceModel` class just for this simple task.

Secondly (and maybe more importantly), there are tests that require the results from here be returned in the order of the registered providers. That's why I created the `Set` of `uniqueResults` and then filtered the original results rather than simply returning a sorted array of unique locations like the `ReferenceModel` does:
https://github.com/microsoft/vscode/blob/c6d6bda7197d0546d21465dc7f6fa849a146504f/src/vs/workbench/test/browser/api/extHostLanguageFeatures.test.ts#L524-L544

Comment (jrieken) [reply src/vs/editor/contrib/gotoSymbol/goToSymbol.ts:52]: > Secondly (and maybe more importantly), there are tests that require the results from here be returned in the order of the registered providers.

I have no problem with that. We are changing how this command/function works, so it's logical that some tests need to be adjusted.

> I felt that creating a ReferenceModel was a bit overkill here since the only two things I needed from it was compareLocations and a de-duplicated result array.

I don't think it's a big issue. At a minimum you should make `ReferencesModel._compareReferences` accessible and than reuse that

**Review by jrieken — CHANGES_REQUESTED** [review]

File: src/vs/editor/contrib/gotoSymbol/goToSymbol.ts (hunk 1 above)
Comment (atscott) [reply src/vs/editor/contrib/gotoSymbol/goToSymbol.ts]: 👍  Done. Sorting and de-duplication code is now shared between `goToSymbol` and `ReferencesModel` and the tests have been adjusted.

**Review by jrieken — APPROVED** [review]

**Comment by jrieken** [comment]
Thanks

**Comment by coreylight** [comment]
@atscott I'm not sure if I'm in the right place but -
I use these settings:
```
  "editor.gotoLocation.multipleDefinitions": "goto",
  "editor.gotoLocation.multipleTypeDefinitions": "goto",
  "editor.gotoLocation.multipleDeclarations": "goto",
  "editor.gotoLocation.multipleImplementations": "goto",
  "editor.gotoLocation.multipleReferences": "goto",
```
With previous public build when clicking through on a JSX element like:
```
<MyComponent foo />
```
It would go to the spot where `MyComponent` was defined in my source code

With current public build it now goes to the React jsx definition for what a Component is.
In essence, with previous build the goto would go to the last (?) reference that it found, which was always (?) the source code definition. Now it seems to go to the first?

**Comment by atscott** [comment]
@coreylight - this is likely due to the sorting change. 

@jrieken - The change to the result order by sorting the references rather than maintaining results based on the registration order may have some unforeseen consequences like what @coreylight mentioned. What are your thoughts on this?

**Comment by jrieken** [comment]
> With current public build it now goes to the React jsx definition for what a Component is.

That's an issue with TypeScript (likely https://github.com/microsoft/vscode/issues/119086) and unrelated to the work here

**Comment by jrieken** [comment]
wait, maybe it is an issue with the sorting...
