### PR TITLE
References view shows icons even though I have icons disabled (#151420)

### LINKED ISSUE #151406: References view shows icons even though I have icons disabled
Seeing this in the latest released builds, seems to me like a regression that is recent:

image

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #151406

### CODE REVIEW

File: src/vs/workbench/browser/parts/views/treeView.ts [hunk 1]
```diff
@@ -1087,25 +1084,20 @@ class TreeRenderer extends Disposable implements ITreeRenderer<ITreeItem, FuzzyS
 		container.parentElement!.classList.toggle('align-icon-with-twisty', this.aligner.alignIconWithTwisty(treeItem));
 	}
 
+	private shouldHideResourceLabelIcon(iconUrl: URI | undefined, icon: ThemeIcon | undefined): boolean {
+		// We always hide the resource label in favor of the iconUrl when it's provided.
+		// When `ThemeIcon` is provided, we hide the resource label icon in favor of it only if it's a not a file icon.
+		return !!iconUrl || !this.isFileKindThemeIcon(icon);
+	}
+
 	private shouldShowThemeIcon(hasResource: boolean, icon: ThemeIcon | undefined): icon is ThemeIcon {
```
Comment (rzhao271) [inline src/vs/workbench/browser/parts/views/treeView.ts:1093]: I'm wondering whether the return type here should be `boolean` instead?

**Review by rzhao271 — APPROVED** [review]
