### PR TITLE
handle errors in backup tracker while writing backup

### LINKED ISSUE #106388: Error: Unable to resolve non-existing file 'vscode-userdata:/var/folders/t_/43r7j31x64574nx71h4dhpfc0000gn/T/vsctests/backuprestorer
This is not a failure but error output when running the `BackupRestorer` tests:

```
[58332:0910/100057.368278:INFO:CONSOLE(129)] "Uncaught (in promise) Error: Unable to resolve non-existing file 'vscode-userdata:/var/folders/t_/43r7j31x64574nx71h4dhpfc0000gn/T/vsctests/backuprestorer/6ec6abd6-9fb2-41e0-b6b9-0013f0ec8678/Backups/eab0d61a99b6696edb3d2aff87b585e8/file/5a42560bf486d685768dc801359647d5'", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/files/common/fileService.js (129)
[58332:0910/100057.371553:INFO:CONSOLE(129)] "Uncaught (in promise) Error: Unable to resolve non-existing file 'vscode-userdata:/var/folders/t_/43r7j31x64574nx71h4dhpfc0000gn/T/vsctests/backuprestorer/6ec6abd6-9fb2-41e0-b6b9-0013f0ec8678/Backups/eab0d61a99b6696edb3d2aff87b585e8/file/9dd17bb5a8c9ca375b5c48a2a4301db7'", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/files/common/fileService.js (129)
```

I feel this could be a result from the environment service change you did. Bounce back to me if not.

### PR DESCRIPTION
**Pull request by sandy081**
This PR fixes #106388

### CODE REVIEW

File: src/vs/workbench/contrib/backup/common/backupTracker.ts [hunk 1]
```diff
@@ -130,8 +130,10 @@ export abstract class BackupTracker extends Disposable {
 			if (workingCopy.isDirty()) {
 				this.logService.trace(`[backup tracker] running backup`, workingCopy.resource.toString());
 
-				const backup = await workingCopy.backup();
-				this.backupFileService.backup(workingCopy.resource, backup.content, this.getContentVersion(workingCopy), backup.meta);
+				try {
+					const backup = await workingCopy.backup();
+					await this.backupFileService.backup(workingCopy.resource, backup.content, this.getContentVersion(workingCopy), backup.meta);
+				} catch (error) { /* Ignore */ }
```
Comment (bpasero) [inline src/vs/workbench/contrib/backup/common/backupTracker.ts:136]: At least we should log the error, no?

**Review by bpasero — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/backup/common/backupTracker.ts (hunk 1 above)
Comment (sandy081) [reply src/vs/workbench/contrib/backup/common/backupTracker.ts]: 👍 Logged

**Review by bpasero — APPROVED** [review]
LGTM
