### PR TITLE
fix(markdown): avoid considering link references/sources in code sections

### LINKED ISSUE #146714: Link misinterpreted in code blocks in markdown file
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Write any code blocks in any markdown file

image

image

2. It looks like all these properties are interpreted as links in reference style. Indeed, you could `command+click` them, which of course leads to the wrong address.

---

> codes for copy 

\`\`\`js
const double = 'double';
const bb = 'bb';
const x = {
  [double]: [bb],
};
\`\`\`

\`\`\`ts
interface Fruit {
    [key]: number;
}
\`\`\`

\`\`\`python
dict = {
    [a]: "number";
}
\`\`\`

### PR DESCRIPTION
**Pull request by AkatQuas**
This PR fixes #146714

Maybe the code works well, there are still extra modification required on `extensions/markdown-language-features/src/test/documentLinkProvider.test.ts`.

Thanks to @mjbvz .

### CODE REVIEW

File: extensions/markdown-language-features/src/languageFeatures/documentLinkProvider.ts [hunk 1]
```diff
@@ -242,32 +249,32 @@ export class MdLinkProvider implements vscode.DocumentLinkProvider {
...
-			...this.getReferenceLinks(document),
-			...this.getLinkDefinitions(document),
+			...(await this.getInlineLinks(document, codeInDocument)),
+			...this.getReferenceLinks(document, codeInDocument),
+			...this.getLinkDefinitions(document, codeInDocument),
 		]);
 	}
 
-	private async getInlineLinks(document: SkinnyTextDocument): Promise<MdLink[]> {
+	private async getInlineLinks(document: SkinnyTextDocument, codeInDocument: CodeInDocument): Promise<MdLink[]> {
```
Comment (mjbvz) [inline extensions/markdown-language-features/src/languageFeatures/documentLinkProvider.ts:260]: This method no longer needs to be `async` after this change

File: extensions/markdown-language-features/src/languageFeatures/documentLinkProvider.ts [hunk 2]
```diff
@@ -192,9 +192,16 @@ async function findCode(document: SkinnyTextDocument, engine: MarkdownEngine): P
...
-	return code.multiline.some(interval => link.source.hrefRange.start.line >= interval[0] && link.source.hrefRange.start.line < interval[1]) ||
-		code.inline.some(position => position.intersection(link.source.hrefRange));
+/**
+ * Check whether the given {@link linkHrefRange} is inside any code sections.
+ * Ignore those inside code sections.
+ * @param code
+ * @param linkHrefRange
+ * @returns boolean
+ */
+function isLinkInsideCode(code: CodeInDocument, linkHrefRange: MdLink['source']['hrefRange']) {
```
Comment (mjbvz) [inline extensions/markdown-language-features/src/languageFeatures/documentLinkProvider.ts:202]: Just use the actual type here (`vscode.Range`)

**Review by mjbvz — COMMENTED** [review]
Thanks for looking into this. Looks good overall but there seems to be a compile error in `pathCompletions.ts`

**Comment by mjbvz** [comment]
Sorry I introduce a few merge conflicts while working on a56c9f10b717875d9a8fd9b90f179cc23ce7fc0d

Let me know if you have any questions about resolving them or about the comments

**Comment by AkatQuas** [comment]
I have done the rebase chores. 

I'm really concerned about the change in `documentLinkProvider.test.ts`. 

Please let me know if any updates.

File: extensions/markdown-language-features/src/languageFeatures/documentLinkProvider.ts [hunk 3]
```diff
@@ -207,9 +213,16 @@ async function findCode(document: SkinnyTextDocument, engine: MarkdownEngine): P
 	return { multiline, inline };
 }
 
-function isLinkInsideCode(code: CodeInDocument, link: MdLink) {
-	return code.multiline.some(interval => link.source.hrefRange.start.line >= interval[0] && link.source.hrefRange.start.line < interval[1]) ||
-		code.inline.some(position => position.intersection(link.source.hrefRange));
+/**
+ * Check whether the given {@link linkHrefRange} is inside any code sections.
+ * Ignore those inside code sections.
+ * @param code
```
Comment (mjbvz) [inline extensions/markdown-language-features/src/languageFeatures/documentLinkProvider.ts:219]: [nit] Only add doc comments if there's something worth documenting. In this case you should remove all the `@param` and `@returns` because they don't provide any value

File: extensions/markdown-language-features/src/languageFeatures/documentLinkProvider.ts [hunk 4]
```diff
@@ -257,33 +270,33 @@ export class MdLinkProvider implements vscode.DocumentLinkProvider {
...
+				yield matchImageData;
 			}
 			const matchLinkData = extractDocumentLink(document, match[1].length, match[5], match.index);
-			if (matchLinkData && !isLinkInsideCode(codeInDocument, matchLinkData)) {
-				results.push(matchLinkData);
+			if (matchLinkData && !isLinkInsideCode(codeInDocument, matchLinkData.source.hrefRange)) {
+				yield matchLinkData;
 			}
 		}
 		return results;
```
Comment (mjbvz) [inline extensions/markdown-language-features/src/languageFeatures/documentLinkProvider.ts:296]: Since this is now a generator, you should remove the `return` statement (and the `results` variable entirely)

File: extensions/markdown-language-features/src/languageFeatures/documentLinkProvider.ts [hunk 5]
```diff
@@ -327,6 +344,11 @@ export class MdLinkProvider implements vscode.DocumentLinkProvider {
 				continue;
 			}
 
+			const hrefRange = new vscode.Range(linkStart, linkEnd);
```
Comment (mjbvz) [inline extensions/markdown-language-features/src/languageFeatures/documentLinkProvider.ts:347]: Reuse the `hrefRange` you declare here inside the yielded type for `source.hrefRange`

File: extensions/markdown-language-features/src/languageFeatures/pathCompletions.ts [hunk 6]
```diff
@@ -9,7 +9,7 @@ import { MarkdownEngine } from '../markdownEngine';
 import { TableOfContents } from '../tableOfContents';
 import { resolveUriToMarkdownFile } from '../util/openDocumentLink';
 import { SkinnyTextDocument } from '../workspaceContents';
-import { MdLinkProvider } from './documentLinkProvider';
+import { findCode, MdLinkProvider } from './documentLinkProvider';
```
Comment (mjbvz) [inline extensions/markdown-language-features/src/languageFeatures/pathCompletions.ts:12]: `findCode` is an implementation detail of  document links and should not be exported. Instead you can likely just want to have a public api version of `getLinkDefinitions` that computes the code ranges for you

File: extensions/markdown-language-features/src/test/documentLinkProvider.test.ts [hunk 7]
```diff
@@ -213,6 +213,29 @@ suite('markdown.DocumentLinkProvider', () => {
...
 
+	test('Should not consider link references in code fenced with backticks (#146714)', async () => {
+		const text = joinLines(
+			'```',
+			'[a] [bb]',
+			'```',
+			'[bb]: http://example.com'
+		);
+		const links = await getLinksForFile(text);
+		assert.strictEqual(links.length, 1);
```
Comment (mjbvz) [inline extensions/markdown-language-features/src/test/documentLinkProvider.test.ts:224]: Here you should check to makes sure the correct like is detected

**Review by mjbvz — CHANGES_REQUESTED** [review]
Just a few more minor comments  about polish and then we can merge this!

**Comment by mjbvz** [comment]
Thanks! Will be in the next VS Code insiders build
