### PR TITLE
fix #113750

### LINKED ISSUE #113750: vscode does not run npm script names with whitespaces
- VSCode Version: 1.52.1
- OS Version: Windows 10 10.0.19042 build 19042

Steps to Reproduce:

1. Create a new node project
2. Add a script in the package.json with whitespaces in the key name
3. Try to run it from the "scripts" panel

Does this issue occur when all extensions are disabled?: Yes

I have these scripts defined  in the package.json

```js
 "scripts": {
        //...
        "[test] unit": "jest src/.*.unit.test.tsx?",
        "[test] unit --watch": "jest src/.*.unit.test.tsx? --watch",
        "[test] integration": "jest __tests__/.*.int.test.tsx? --silent",
        "[test] integration --watch": "jest __tests__/.*.int.test.tsx? --watch --silent",
        //...
    },
```

If I run `yarn "[test] unit --watch"` or `npm run "[test] unit --watch"` it works  

But if I click on the play button near the script name in the left panel it calls `yarn run [test] unit --watch`, and throws a `Command "[test]" not found.`

[Link to the SO question](https://stackoverflow.com/questions/65478888/vscode-does-not-run-npm-script-names-with-whitespaces)

Is this a vscode bug?

### PR DESCRIPTION
**Pull request by jonamat**
This PR fixes #113750

I've wrapped the script names in quotes in all calls to createTask and inside startDebugging.  
I'm not familiar with vscode oss so I'm not sure about the side effects of this fix but it seems to work

### CODE REVIEW

File: extensions/npm/src/tasks.ts [hunk 1]
```diff
@@ -70,7 +70,7 @@ export class NpmTaskProvider implements TaskProvider {
 			} else {
 				packageJsonUri = _task.scope.uri.with({ path: _task.scope.uri.path + '/package.json' });
 			}
-			return createTask(this.context, kind, `${kind.script === INSTALL_SCRIPT ? '' : 'run '}${kind.script}`, _task.scope, packageJsonUri);
+			return createTask(this.context, kind, `${kind.script === INSTALL_SCRIPT ? '' : 'run '}"${kind.script}"`, _task.scope, packageJsonUri);
```
Comment (alexr00) [inline extensions/npm/src/tasks.ts:73]: Instead of just quoting every script, I would prefer that we only quote scripts that have a space in them. No need to add quotes when they aren't needed.

Comment (alexr00) [reply extensions/npm/src/tasks.ts:73]: To reduce the number of places we need to "remember" to add quotes, we can just add them in one place where we create the command line: 
https://github.com/microsoft/vscode/blob/59ba6494b9eb3e13a7cb558a06e3018a74f30af1/extensions/npm/src/tasks.ts#L318-L318

**Review by alexr00 — CHANGES_REQUESTED** [review]
Thanks for the PR!

File: extensions/npm/src/tasks.ts [hunk 2]
```diff
@@ -316,6 +316,9 @@ export async function createTask(context: ExtensionContext, script: NpmTaskDefin
 
 	const packageManager = await getPackageManager(context, folder.uri, showWarning);
```
Comment (alexr00) [inline extensions/npm/src/tasks.ts:317]: Adding quotes only works if you also use `ShellQuoting.Strong` in this case.

**Review by alexr00 — APPROVED** [review]
I had to use `ShellQuoting` to get this to work. While switching over to that, I also decided to use args, so that only the argument that needed the `ShellQuoting` received it.

**Comment by alexr00** [comment]
@jonamat you just need to take care of https://github.com/microsoft/vscode/pull/113840#issuecomment-757885539 then I'll merge.

**Comment by jonamat** [comment]
@alexr00 Done.
Wow, this fix involves more stuff than I expected!
Shouldn't the script name be processed in the same way in `startDebugging()`? 
I didn't add the quotes but if I understand correctly this could lead to interpretation problems on some shells.
Thank you for your support, I really appreciate it

**Review by alexr00 — APPROVED** [review]
When I try the debugging from the npm scripts view with a script that includes a space it works just fine. Looks like debug's default for how to handle spaces is good.

**Comment by weinand** [comment]
Yes, debug's "StartDebugging" tries to handle escaping and quoting differences of various shells automatically.
