### PR TITLE
fix terminal suggest bug where unexpected completions are returned

### LINKED ISSUE #241909: Path completion sometimes replaces command
Testing #241786

I don't have great repro steps because some combination of creating a new terminal, reloading the window, etc will sometimes make this start working, but I've been seeing this fairly often. 

It seems to happen when I accept the "python" suggestion but if I just type "python" manually then it doesn't happen

https://github.com/user-attachments/assets/6355201e-58ff-45d0-a58e-21bfe17bb2e5

### LINKED ISSUE #241964: Getting executable completions when typing `snap install|`
Testing #241771

image

I don't know why I am getting executable completions when I typed `snap install|`

hitting tab replaces `snap install` with `install`

shell: bash

### PR DESCRIPTION
**Pull request by meganrogge**
- We were adding the spec completion item even when there was no matching available command because of a `startsWith` check - for example,`python3.13` in `availableCommands` would be the reason we add the `python` spec as a command completion. Now, we ensure there's an exact match. for `python`, this means it won't show up unless a user has defined that `alias`. 
- We were checking if `specLabel === command.label` when `command.label` can be an `object`.
- We weren't hiding the widget when there are 0 provided completions _when not manually invoked, IE typing ./_, so it would stick around with the latest model's values.

fixes https://github.com/microsoft/vscode/issues/241909
fixes [#241964](https://github.com/microsoft/vscode/issues/241964)

### CODE REVIEW

File: extensions/terminal-suggest/src/fig/figInterface.ts [hunk 1]
```diff
@@ -52,11 +52,10 @@ export async function getFigSuggestions(
 		if (!specLabels) {
 			continue;
 		}
-
 		for (const specLabel of specLabels) {
 			const availableCommand = (osIsWindows()
 				? availableCommands.find(command => (typeof command.label === 'string' ? command.label : command.label.label).match(new RegExp(`${specLabel}(\\.[^ ]+)?$`)))
-				: availableCommands.find(command => (typeof command.label === 'string' ? command.label : command.label.label).startsWith(specLabel)));
+				: availableCommands.find(command => (typeof command.label === 'string' ? command.label : command.label.label) === (specLabel)));
```
Comment (Tyriar) [inline extensions/terminal-suggest/src/fig/figInterface.ts:58]: Does this still work properly for aliases like `alias lss=ls`?

**Review by Tyriar — DISMISSED** [review]

File: extensions/terminal-suggest/src/fig/figInterface.ts (hunk 1 above)
Comment (meganrogge) [reply extensions/terminal-suggest/src/fig/figInterface.ts:58]: Good point, think we also want to factor in `command.definitionCommand` here to address that

Comment (meganrogge) [reply extensions/terminal-suggest/src/fig/figInterface.ts:58]: tested and that works too with the most recent commit

**Review by amunger — APPROVED** [review]
