### PR TITLE
SCM - fix action button container height

### LINKED ISSUE #239316: SCM - fix action button top/bottom spacing
Image

### PR DESCRIPTION
**Pull request by lszomoru**
Fixes #239316

### CODE REVIEW

File: src/vs/workbench/contrib/scm/browser/scmViewPane.ts [hunk 1]
```diff
@@ -710,9 +710,10 @@ class ListDelegate implements IListVirtualDelegate<TreeElement> {
 
 	getHeight(element: TreeElement) {
 		if (isSCMInput(element)) {
+			console.log(this.inputRenderer.getHeight(element));
```
Comment (aeschli) [inline src/vs/workbench/contrib/scm/browser/scmViewPane.ts:713]: Console.log... Intended?

**Review by aeschli — APPROVED** [review]
