### PR TITLE
dispose of quick fix decoration when the next command is run

### LINKED ISSUE #161629: decoration overlaid on top of lightbulb
1. trigger a contextual action - for example, `git sttatus`
2. run a command `ls` 
3. 🐛 command decoration overlaid on top of lightbulb

Screen Shot 2022-09-23 at 11 04 36 AM (1)

### PR DESCRIPTION
**Pull request by meganrogge**
fix #161629

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/xterm/contextualActionAddon.ts [hunk 1]
```diff
@@ -84,6 +86,7 @@ export class ContextualActionAddon extends Disposable implements ITerminalAddon,
 			return;
 		}
 		this._register(commandDetection.onCommandFinished(async command => {
+			this._decoration?.dispose();
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/contextualActionAddon.ts:89]: I think we actually want to do it on `onCommandFinished` or `onCommandExecuted, whichever comes first`. This doesn't exist right now but we can fire it on the last line of `handleCommandExecuted`.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/xterm/contextualActionAddon.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/contextualActionAddon.ts:89]: since it'll happen with whichever comes first, safe to listen to both imo

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/xterm/contextualActionAddon.ts:89]: Yep, can then do this safely:

```ts
this._decoration?.dispose();
this._decoration = undefined;
```

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/contextualActionAddon.ts:89]: seems sketchy to do that for windows, so will only follow command executed for non-windows

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/xterm/contextualActionAddon.ts:89]: Why is that? The executed sequence should still only fire when you press enter and the command starts executing. We don't care about the positioning, that's the part that's flaky on Windows

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/contextualActionAddon.ts:90]: yes you're right - I was recalling this code which is unrelated to command executed

https://github.com/microsoft/vscode/blob/8624f3a4e39cd23214237a3f6e7046bbb83a0bbb/src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts#L358-L377

**Review by Tyriar — APPROVED** [review]
