### PR TITLE
Change behavior of home/end button

### LINKED ISSUE #19644: Cursor does not go to the end of line when pressing "End" with word wrap enabled
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. Enable the word wrapping: `"editor.wordWrap": true`
2. Write a line long enough so that it covers multiple lines
3. Put the cursor at the beginning of the line
4. Press the End button

The cursor does not go to the EOL character.

[Example here](http://stackoverflow.com/questions/39087693/how-to-jump-to-the-end-of-the-looong-line)

### PR DESCRIPTION
**Pull request by misoguy**
Fixes #19644

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by misoguy** [comment]
@rebornix How does the PR look? Is there room for improvement? or could this be merged as is?

**Comment by misoguy** [comment]
@rebornix It'd be nice to get a feedback on this when you get the time :)

File: src/vs/editor/common/controller/cursor.ts [hunk 1]
```diff
@@ -1234,11 +1234,17 @@ export class Cursor extends EventEmitter {
 	}
 
 	private _moveToBeginningOfLine(inSelectionMode: boolean, ctx: IMultipleCursorOperationContext): boolean {
-		return this._invokeForAll(ctx, (cursorIndex: number, oneCursor: OneCursor, oneCtx: IOneCursorOperationContext) => OneCursorOp.moveToBeginningOfLine(oneCursor, inSelectionMode, oneCtx));
```
Comment (misoguy) [inline src/vs/editor/common/controller/cursor.ts]: After taking a look at the code, the method ```_cursorMove``` which I used instead of ```_invokeForAll``` uses  ```_invokeForAll``` internally so I'm guessing it's not a problem?
However, I think we do need to clarify how ```Home``` and ```End``` command should behave in multi cursor mode. I'll raise this question in the related issue directly.

**Comment by alexandrudima** [comment]
Thank you @misoguy ! :heart:

**Comment by misoguy** [comment]
@alexandrudima Thank you for merging this PR 👍
