### PR TITLE
Fixes webview views fail to load in code web if view id is too long

### LINKED ISSUE #143950: Webview views fail to load in code web if view id is too long
- VS Code Version: stable and from sources

Steps to Reproduce:

1. Run code-server
2. Open webview view extension sample https://github.com/microsoft/vscode-extension-samples/tree/main/webview-view-sample
3. Change [webview view id](https://github.com/microsoft/vscode-extension-samples/blob/2feab6d8f185417e63eaef73b38dae36a6a5dafb/webview-view-sample/package.json#L33) (and references) to something longer than 64 chars e.g. `calicoColors.colorsView.really.really.really.long.name`
4. Run extension
5. :bug: Observe webview view fails to load because we use a custom subdomain (longer than 64 chars) instead of uuid like other webviews (if we run the extension in vscode desktop it uses uuid)

```html
<iframe
  name="webviewview-calicocolors-colorsview-really-really-really-long-name"
  class="webview "
  sandbox="allow-scripts allow-same-origin allow-forms allow-pointer-lock allow-downloads"
  style="border: medium none; width: 100%; height: 100%;"
  src="https://webviewview-calicocolors-colorsview-really-really-really-long-name.vscode-webview.net/insider/93a2a2fa12dd3ae0629eec01c05a28cb60ac1c4b/out/vs/workbench/contrib/webview/browser/pre/index-no-csp.html?id=b368ceb4-9f13-4396-826c-0792e57016b2&amp;swVersion=4&amp;extensionId=vscode-samples.calico-colors&amp;platform=browser&amp;vscode-resource-base-authority=vscode-resource.vscode-webview.net&amp;parentOrigin=http%3A%2F%2Flocalhost%3A9888&amp;remoteAuthority=localhost%3A9888&amp;purpose=webviewView">
</iframe>
```

### PR DESCRIPTION
**Pull request by jeanp413**
This PR fixes #143950

### CODE REVIEW

File: src/vs/workbench/contrib/webviewView/browser/webviewViewPane.ts [hunk 1]
```diff
@@ -160,7 +161,7 @@ export class WebviewViewPane extends ViewPane {
 
 		this._activated = true;
 
-		const webviewId = `webviewView-${this.id.replace(/[^a-z0-9]/gi, '-')}`.toLowerCase();
+		const webviewId = generateUuid();
```
Comment (gjsjohnmurray) [inline src/vs/workbench/contrib/webviewView/browser/webviewViewPane.ts:164]: Is this going to make webview debugging harder because the id is now random? Maybe only resort to a uuid when id is too long to be used as-is.

Comment (jeanp413) [reply src/vs/workbench/contrib/webviewView/browser/webviewViewPane.ts:164]: @gjsjohnmurray you still can debug webviews views with
```
	"debugWebviews": true,
	"rendererDebugOptions": {
		"urlFilter": "*vscode-samples.calico-colors*",
		"webRoot": "${workspaceFolder}/media"
	},
```

**Comment by mjbvz** [comment]
Thanks!
