### PR TITLE
Fixes #7346: Paste native EOL

### LINKED ISSUE #7346: Line breaks in Windows integrated terminal ignored when pasted
- VSCode Version: Windows 1.2.0
- OS Version: Windows 8.1

Steps to Reproduce:

1. Copy several lines of code (open notepad, type mkdir directory1[enter]mkdir directory2)
2. Paste code in integrated terminal, it pastes as a single command 'mkdir directory1mkdirdirectory2' with any line breaks removed.

This happens on both default cmd.exe integrated terminal and powershell integrated terminal.

### PR DESCRIPTION
**Pull request by chrmarti**

### CODE REVIEW

File: src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts [hunk 1]
```diff
@@ -45,7 +49,7 @@ export class TerminalInstance {
 		this.xterm.on('data', (data) => {
 			this.terminalProcess.process.send({
 				event: 'input',
-				data: data
+				data: data && data.replace(TerminalInstance.eolRegex, os.EOL)
```
Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: This should be split out above for clarify, it looks like it's passing in a boolean right now.

Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: Maybe to a `sanitizeInput` function?

**Comment by Tyriar** [comment]
:+1:
