### PR TITLE
Better handle shell env api usage for windows conpty

### LINKED ISSUE #237900: pwsh prompt is clutted with unexpected env output
Type: <b>Bug</b>

I'm using Miniconda to manage my Python Virtual Environments, each time i open a Terminal (powershell), i have junk ansi text written after the virtual environnement selected. It has begun some days ago.
I have reinstalled VSCode insiders, and all the extensions (from bare metal), and same issue each time. Same issue on all of my virtual env
Step to reproduce : 
1. Create an conda vistual environment
2. Open a Python project (folder)
3. Select the virtual environment
4. Open a  powershell Terminal (CTRL+SHIFT+P) from the palette (Create new terminal) 
5. Terminal is opened with the right Virtual Environment selected
6. Hit Enter (or any command)
7. Junk  (it seems it comes from some profile info) is displayed between the (Virtual Env) and the prompt >

Exemple of Junk Data (anonymized) : 

(Sandbox) rs\x5c\x5c[myUSer]\x5c\x5cOneDrive - [myCompany]\x5c\x5cDocuments\x5c\x5cWindowsPowerShell\x5c\x5cModules\x3bC:\x5c\x5cProgram Files\x5c\x5cWindowsPowerShell\x5c\x5cModules\x3bC:\x5c\x5cWINDOWS\x5c\x5csystem32\x5c\x5cWindowsPowerShell\x5c\x5cv1.0\x5c\x5cModules","SSL_CERT_DIR":"C:\x5c\x5cUsers\x5c\x5c[myUSer]\x5c\x5cAppData\x5c\x5cLocal\x5c\x5cminiconda3\x5c\x5cenvs\x5c\x5cSandbox\x5c\x5cLibrary\x5c\x5cssl\x5c\x5ccerts","SNC_LIB_64":"C:\x5c\x5cProgram Files\x5c\x5cSAP\x5c\x5cFrontEnd\x5c\x5cSecureLogin\x5c\x5clib\x5c\x5csapcrypto.dll","CONDA_PREFIX_2":"C:\x5c\x5cUsers\x5c\x5c[myUSer]\x5c\x5cAppData\x5c\x5cLocal\x5c\x5cminiconda3\x5c\x5cenvs\x5c\x5cSandbox","ProgramFiles(x86)":"C:\x5c\x5cProgram Files (x86)","HOMEDRIVE":"C:","OS":"Windows_NT","PUBLIC":"C:\x5c\x5cUsers\x5c\x5cPublic","OneDrive":"C:\x5c\x5cUsers\x5c\x5c[myUSer]\x5c\x5cOneDrive - [myCompany]","VSCODE_GIT_IPC_HANDLE":"\x5c\x5c\x5c\x5c.\x5c\x5cpipe\x5c\x5cvscode-git-ca0238292a-sock","VSCODE_GIT_ASKPASS_EXTRA_ARGS":""};dba6be80-468f-423d-90bf-3bb14c89bd5bPS L:\TFS\PY_FOS\exportPRODEC> 

=> Also i can add that with the same Virtual Env, i don't have any problem with regular VSCode
=> No problem if i open a cmd terminal

Thanks for your help

VS Code version: Code - Insiders 1.97.0-insider (c594d55bae90276d174cea4ddf2901694d4ebb3e, 2025-01-14T05:04:07.371Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1365U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.66GB (14.75GB free)|
|Process Argv|--crash-reporter-id e67fee66-9416-42f3-ab8b-fac7b6887731|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
arepl|alm|3.0.0
pythonsnippets|frh|1.0.2
copilot|Git|1.257.1312
copilot-chat|Git|0.24.2025011401
todo-tree|Gru|0.0.226
flux|inf|1.0.4
vsc-python-indent|Kev|1.19.0
tal|KNo|0.7.11
csvtomarkdown|mar|0.0.1
rainbow-csv|mec|3.14.0
git-graph|mhu|1.30.0
csdevkit|ms-|1.15.34
csharp|ms-|2.61.28
vscode-dotnet-runtime|ms-|2.2.4
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.27.0
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.5
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.14.0
isort|ms-|2023.10.1
python|ms-|2024.22.2
vscode-pylance|ms-|2024.12.1
datawrangler|ms-|1.16.0
jupyter|ms-|2024.11.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-ssh|ms-|0.116.1
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
powershell|ms-|2024.5.2
remote-explorer|ms-|0.4.3
vscode-copilot-vision|ms-|0.2.2024111316
vscode-speech|ms-|0.12.1
indent-rainbow|ode|8.3.1
tmlanguage|ped|1.0.0
csv-to-table|php|1.4.1
vscode-thunder-client|ran|2.33.2
java|red|1.38.0
vscode-xml|red|0.27.2
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
sonarlint-vscode|Son|4.14.1
pdf|tom|1.2.2
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.0
vscode-icons|vsc|12.10.0
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythonnoceb:30776497
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
dvdeprecation:31040973
dwnewjupytercf:31046870
nativerepl1:31134653
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
iacca1:31150324
notype1:31143044
dwcopilot:31158714
h409b430:31177054
c3hdf307:31184662
6074i472:31201624
dwoutputs:31217127

```

</details>

### PR DESCRIPTION
**Pull request by anthonykim1**
Should resolve: https://github.com/microsoft/vscode/issues/237900
and better handle env api usage for windows, conptydll related.

### CODE REVIEW

File: src/vs/platform/terminal/node/terminalEnvironment.ts [hunk 1]
```diff
@@ -87,10 +87,15 @@ export function getShellIntegrationInjection(
...
-		envMixin['VSCODE_SHELL_ENV_REPORTING'] = '1';
+
+	const enableWindowsEnvReporting = options.windowsUseConptyDll || options.windowsEnableConpty && getWindowsBuildNumber() >= 22631;
+
+	if (shellLaunchConfig.shellIntegrationEnvironmentReporting) {
+		if (isWindows && enableWindowsEnvReporting) {
+			envMixin['VSCODE_SHELL_ENV_REPORTING'] = '1';
+		} else {
+			envMixin['VSCODE_SHELL_ENV_REPORTING'] = '1';
+		}
```
Comment (Tyriar) [inline src/vs/platform/terminal/node/terminalEnvironment.ts]: This would set it to `1` when `isWindows && !enableWindowsEnvReporting`. Also pull the variable above so it's only run when it's used. Something like this:

```ts
if (isWindows) {
  const enableWindowsEnvReporting = options.windowsUseConptyDll || options.windowsEnableConpty && getWindowsBuildNumber() >= 22631;
  ...
}
```

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/platform/terminal/node/terminalEnvironment.ts [hunk 2]
```diff
@@ -87,8 +87,17 @@ export function getShellIntegrationInjection(
 	if (options.shellIntegration.nonce) {
 		envMixin['VSCODE_NONCE'] = options.shellIntegration.nonce;
 	}
+
+	const enableWindowsEnvReporting = options.windowsUseConptyDll || options.windowsEnableConpty && getWindowsBuildNumber() >= 22631;
```
Comment (Tyriar) [inline src/vs/platform/terminal/node/terminalEnvironment.ts:91]: Let's stick this inside the isWindows block to avoid unnecessary work

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/platform/terminal/node/terminalEnvironment.ts (hunk 1 above)
Comment (anthonykim1) [reply src/vs/platform/terminal/node/terminalEnvironment.ts]: Ahhh, just saw this, let me make it better also looking at the comment below

File: src/vs/platform/terminal/node/terminalEnvironment.ts (hunk 2 above)
Comment (anthonykim1) [reply src/vs/platform/terminal/node/terminalEnvironment.ts]: Just like [this](https://github.com/microsoft/vscode/pull/240710/commits/39f537068fb3eb66e93d5fd11cd8213d280c2853), right?

**Review by Tyriar — APPROVED** [review]
