### PR TITLE
render terminal chat actions as buttons rather than in the toolbar

### LINKED ISSUE #207368: terminal chat response is `[object Object]`
not sure what the repro steps are yet. 

Image

### LINKED ISSUE #207489: Terminal chat: No accept primary button
image

### LINKED ISSUE #207505: trying to render a codeblock without a model
1. Run a request in the terminal chat
2. 🐛 sometimes, no response will be rendered 

Image

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #207489
fixes [#207505](https://github.com/microsoft/vscode/issues/207505)
fixes #207368

`ChatWidget`s have access to their codeblocks via `_codeBlockModelCollection`. Though the `InlineChatWidget` has a `_codeBlockModelCollection`, it lacks a `ChatViewModel`, which is where events are listened to and code blocks are appended. Thus, for us, the size of that collection was `0`. 

This is a two-fold problem:
- `IChatListRenderer`, uses `_codeBlockModelCollection` to verify and render the code block elements [#207505](https://github.com/microsoft/vscode/issues/207505)
- We need to fetch the code block's content to be able to `Run` or `Insert` it into the terminal

I added a `ChatViewModel` , where the `ChatResponseViewModel` is created when `updateChatMessage` is called so that the collection would get updated. However, events which `ChatViewModel` listens to already happen by the time we create that, so in order to update `_codeBlockModelCollection`, we need to make the update function accessible and call it there. 

Lastly, I added a `getCodeBlockInfo` function in `InlineChatWidget` so we can access that similar to the functions that the `ChatWidget` exposes.

### CODE REVIEW

**Review by lszomoru — DISMISSED** [review]

File: src/vs/workbench/contrib/chat/browser/actions/chatCodeblockActions.ts [hunk 1]
```diff
@@ -88,8 +88,7 @@ export function registerChatCodeBlockActions() {
 				icon: Codicon.copy,
```
Comment (meganrogge) [inline src/vs/workbench/contrib/chat/browser/actions/chatCodeblockActions.ts:88]: this is just reverting changes I had made to get our actions to appear before the ones in the chat toolbar

File: src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts [hunk 2]
```diff
@@ -381,8 +391,11 @@ export class InlineChatWidget {
 		let resultingAppender: IInlineChatMessageAppender | undefined;
 		if (hasMessage) {
 			const sessionModel = this._chatMessageDisposables.add(new ChatModel(message.providerId, undefined, this._logService, this._chatAgentService, this._instantiationService));
+			this._sessionId = sessionModel.sessionId;
 			const responseModel = this._chatMessageDisposables.add(new ChatResponseModel(message.message, sessionModel, undefined, undefined, message.requestId, !isIncomplete, false, undefined));
-			const viewModel = this._chatMessageDisposables.add(new ChatResponseViewModel(responseModel, this._logService));
+			this._responseViewModel = this._chatMessageDisposables.add(new ChatResponseViewModel(responseModel, this._logService));
+			const chatViewModel = this._instantiationService.createInstance(ChatViewModel, sessionModel, this._codeBlockModelCollection);
+			chatViewModel.updateCodeBlockTextModels(this._responseViewModel);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts:398]: Since the `ChatViewModel` is created as progress/events are occurring, the listeners to such events are registered after the events have already happened. Force update here so that `_codeBlockModelCollection` gets populated.

**Comment by Tyriar** [comment]
> Regenerate button

We can do this as part of another PR/issue. Also I'm going to the ux sync today to talk about the buttons

File: src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts [hunk 3]
```diff
@@ -170,6 +170,8 @@ export class InlineChatWidget {
 
 	private _chatMessage: MarkdownString | undefined;
 	private readonly _codeBlockModelCollection: CodeBlockModelCollection;
+	private _responseViewModel: IChatResponseViewModel | undefined;
+	private _sessionId: string | undefined;
```
Comment (jrieken) [inline src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts:174]: Use `_responseViewModel.sessionId` instead of having another property?

File: src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts [hunk 4]
```diff
@@ -300,6 +302,14 @@ export class InlineChatWidget {
 		}
 	}
 
+	getCodeBlockInfo(): Promise<IReference<IResolvedTextEditorModel>> | undefined {
```
Comment (jrieken) [inline src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts:305]: Just hard-coding this to be the first (`0`) is fishy. I understand the terminal use-case but please make the index an argument and then it is up to terminal how to call this. Mid-term this needs to be tackled differently tho

File: src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts [hunk 5]
```diff
@@ -381,8 +391,11 @@ export class InlineChatWidget {
 		let resultingAppender: IInlineChatMessageAppender | undefined;
 		if (hasMessage) {
 			const sessionModel = this._chatMessageDisposables.add(new ChatModel(message.providerId, undefined, this._logService, this._chatAgentService, this._instantiationService));
+			this._sessionId = sessionModel.sessionId;
 			const responseModel = this._chatMessageDisposables.add(new ChatResponseModel(message.message, sessionModel, undefined, undefined, message.requestId, !isIncomplete, false, undefined));
-			const viewModel = this._chatMessageDisposables.add(new ChatResponseViewModel(responseModel, this._logService));
+			this._responseViewModel = this._chatMessageDisposables.add(new ChatResponseViewModel(responseModel, this._logService));
```
Comment (jrieken) [inline src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts:396]: `this._responseViewModel` gets disposed whenever `updateChatMessage` is called. We should account for this and reset (to `undefined`) the property when that happens

File: src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts [hunk 6]
```diff
@@ -504,7 +517,9 @@ export class InlineChatWidget {
 		this.updateInfo('');
 
 		this._elements.accessibleViewer.classList.toggle('hidden', true);
-
+		this._codeBlockModelCollection.clear();
```
Comment (jrieken) [inline src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts:520]: IMO clearing of the code block collection should happen inside `updateChatMessage`

File: src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts [hunk 7]
```diff
@@ -504,7 +517,9 @@ export class InlineChatWidget {
...
+		this._responseViewModel = undefined;
```
Comment (jrieken) [inline src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts:521]: this should be part of the `_chatMessageDisposables`-store

**Review by jrieken — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts (hunk 7 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts:519]: it is so an delete this

**Review by jrieken — APPROVED** [review]

File: src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts [hunk 8]
```diff
@@ -382,7 +393,9 @@ export class InlineChatWidget {
 		if (hasMessage) {
 			const sessionModel = this._chatMessageDisposables.add(new ChatModel(message.providerId, undefined, this._logService, this._chatAgentService, this._instantiationService));
 			const responseModel = this._chatMessageDisposables.add(new ChatResponseModel(message.message, sessionModel, undefined, undefined, message.requestId, !isIncomplete, false, undefined));
-			const viewModel = this._chatMessageDisposables.add(new ChatResponseViewModel(responseModel, this._logService));
+			this._responseViewModel = this._chatMessageDisposables.add(new ChatResponseViewModel(responseModel, this._logService));
```
Comment (roblourens) [inline src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts:396]: This pattern is a bit weird to me, the ChatResponseModel is not actually inside the ChatModel, so then calling `updateCodeBlockTextModels` with a viewModel which is not inside that chatViewModel feels wrong. We should try to make this easier to reuse in a more natural way outside of panel chat

Comment (meganrogge) [reply src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts:396]: I am not sure who owns this, but agree it is not ideal and was tough to figure out. I am out for the rest of the iteration. cc @mjbvz 

I can look in April during debt week

Comment (mjbvz) [reply src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts:396]: Maybe we can move the parsing logic `CodeBlockModelCollection` instead but keep the syncing stuff in `ChatViewModel`?

Comment (jrieken) [reply src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts:396]: just fyi that I working on a change to reuse the whole `ChatWidget` for inline chat. That makes this obsolete

Comment (Tyriar) [reply src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts:396]: Perfect, I think that's exactly what @meganrogge was after
