### PR TITLE
Prevent terminal task system from trying to set a non-existent terminal as active

### LINKED ISSUE #60858: Terminal with ID 2 does not exist (has it already been disposed?)
Version: 1.29.0 insiders
OS: Linux Mint 19
**All extensions disabled**

**Steps to Reproduce:**

1. Run a task, call it **TASK A**, that calls a shell script that infinitely writes lines to the console. My shell script invokes the following java program:  
```
    public static void main (String [] args) throws IOException {
        while (true)
            System.out.println("TEST");
    }
```
2. Hit the "Kill Terminal" button in the panel, to kill terminal and close panel.

3. Run **TASK A** again. Nothing happens, and the following error is output as a notification...

> Terminal with ID 2 does not exist (has it already been disposed?)

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #60858

### CODE REVIEW

File: src/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.ts [hunk 1]
```diff
@@ -375,7 +375,6 @@ export class TerminalTaskSystem implements ITaskSystem {
 					onData.dispose();
 					onExit.dispose();
 					let key = Task.getMapKey(task);
-					delete this.activeTasks[key];
```
Comment (dbaeumer) [inline src/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.ts]: I would still keep this since it is the right place to do this and is necessary if the terminal is reused

File: src/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.ts [hunk 2]
```diff
@@ -693,6 +692,7 @@ export class TerminalTaskSystem implements ITaskSystem {
 				delete this.terminals[terminalKey];
 				delete this.sameTaskTerminals[terminalData.lastTask];
 				this.idleTaskTerminals.delete(terminalData.lastTask);
+				delete this.activeTasks[Task.getMapKey(task)];
```
Comment (dbaeumer) [inline src/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.ts]: Would mark this as a work around for the issue since the task should have already been removed if the onExit fires correctly.

File: src/vs/workbench/parts/terminal/common/terminal.ts [hunk 3]
```diff
@@ -410,10 +410,11 @@ export interface ITerminalInstance {
 	/**
 	 * Dispose the terminal instance, removing it from the panel/service and freeing up resources.
 	 *
-	 * @param isShuttingDown Whether VS Code is shutting down, if so kill any terminal processes
-	 * immediately.
+	 * @param immediate Whether the kill should be immediate or not. Immedeate should only be used
```
Comment (Tyriar) [inline src/vs/workbench/parts/terminal/common/terminal.ts]: nit: typo on immediate

File: src/vs/workbench/parts/terminal/common/terminal.ts [hunk 4]
```diff
@@ -410,10 +410,11 @@ export interface ITerminalInstance {
...
+	 * when VS Code is shutting down or in cases where the terminal dispose was user initiated.
```
Comment (Tyriar) [inline src/vs/workbench/parts/terminal/common/terminal.ts]: Might be good to be more explicit about why `!immediate` exists here (to cover an edge case where final output can get cut off).

**Review by Tyriar — APPROVED** [review]
