### PR TITLE
Watch and remove file attachments that are deleted

### LINKED ISSUE #282900: Context Added unexpectedly
Type: <b>Bug</b>

Context of a file i have delete is being added to my messages without me selecting causing and error from copilot.

Extension version: 0.26.7
VS Code version: Code 1.99.3 (Universal) (17baf841131aa23349f217ca7c570c76ee87b957, 2025-04-15T23:18:46.076Z)
OS version: Darwin arm64 24.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M4 Pro (14 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|24.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 66e80a89-4785-4b61-bd3f-331c989b26ed|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
binariesv615:30325510
2e7ec940:31000449
nativeloc1:31344060
dwcopilot:31170013
6074i472:31201624
dwoutputs:31242946
9064b325:31222308
copilot_t_ci:31333650
e5gg6876:31282496
pythoneinst12:31285622
c7cif404:31314491
pythonpulldiag:31343502
996jf627:31283433
pythonrdcb7:31342333
usemplatestapi:31297334
0aa6g176:31307128
jjjhb125:31275178
aj953862:31281341
generatesymbolt:31295002
convertfstringf:31295003
pylancequickfixt:31350061
usemarketplace:31343026
4f60g487:31327383
nes-diff-11:31337487
6abeh943:31336334
yijiwantestdri0626-c:31336931
0927b901:31350571
4gdec884:31348710

```

</details>

### PR DESCRIPTION
**Pull request by dmitrivMS**
Fixes #282900

### CODE REVIEW

File: src/vs/workbench/contrib/chat/browser/chatAttachmentModel.ts [hunk 1]
```diff
@@ -36,6 +36,23 @@ export class ChatAttachmentModel extends Disposable {
...
+			for (const [id, attachment] of this._attachments) {
+				const uri = IChatRequestVariableEntry.toUri(attachment);
+				if (uri && e.contains(uri, FileChangeType.DELETED)) {
+					idsToDelete.push(id);
+				}
+			}
+			if (idsToDelete.length > 0) {
+				this.updateContext(idsToDelete, Iterable.empty());
+			}
+		}));
```
[the remark this answers is not in the document]
Comment (dmitrivMS) [reply src/vs/workbench/contrib/chat/browser/chatAttachmentModel.ts]: Yeah, I thought about doing this instead. Ok, let me try this approach instead.

File: src/vs/workbench/contrib/chat/browser/chatAttachmentModel.ts [hunk 2]
```diff
@@ -137,6 +144,22 @@ export class ChatAttachmentModel extends Disposable {
 		}
 	}
 
+	private _watchAttachment(attachment: IChatRequestVariableEntry): void {
+		const uri = IChatRequestVariableEntry.toUri(attachment);
+		if (!uri || uri.scheme !== Schemas.file) {
+			return;
+		}
+
+		const watcher = this.fileService.createWatcher(uri, { recursive: false, excludes: [] });
```
Comment (roblourens) [inline src/vs/workbench/contrib/chat/browser/chatAttachmentModel.ts:153]: Is there a cost with creating many watchers? In a dumb case when I have tons of files attached, is it bad to create 20 of these and have them around for a long time?

Comment (dmitrivMS) [reply src/vs/workbench/contrib/chat/browser/chatAttachmentModel.ts:153]: The comment on IFileService says to prefer correlated watchers - otherwise events get fired to every watcher.
Looking through the watchers code it seems that the cost of creating a watcher is a couple of entries in hash tables, so I think it's reasonable.

Perhaps @bpasero can provide more specific guidance.

Comment (bpasero) [reply src/vs/workbench/contrib/chat/browser/chatAttachmentModel.ts:153]: I will review this PR and comment.

Comment (bpasero) [reply src/vs/workbench/contrib/chat/browser/chatAttachmentModel.ts:153]: Yeah so this usage is fine: we have logic in place that will try to re-use the workspace recursive watcher instead of creating a separate new file watcher IF the paths are inside the workspace. Event correlation is good because it makes sure that the event is only ever getting fired back to the requestor.

Btw there is a way to figure out the impact of file watching on VS Code:
* start VS Code and setup your file watchers
* set log level to `trace` using the "Set Log Level" command
* open the "File Watcher" output channel
* it gives you a summary of all recursive and non-recursive file watchers and specifically a I/O handles impact which you should be observing, if that number increases with your file watchers it means there is actual cost involved

image

If you scroll further down into the details of each watcher, you can see that the newly added correlated watchers are reusing the workspace watcher:

image

Comment (dmitrivMS) [reply src/vs/workbench/contrib/chat/browser/chatAttachmentModel.ts:153]: Thank you so much for the details - this is really helpful!

File: src/vs/workbench/contrib/chat/browser/chatAttachmentModel.ts [hunk 3]
```diff
@@ -137,6 +144,22 @@ export class ChatAttachmentModel extends Disposable {
...
+		this._fileWatchers.set(attachment.id, watcher);
+
+		watcher.onDidChange(e => {
```
Comment (roblourens) [inline src/vs/workbench/contrib/chat/browser/chatAttachmentModel.ts]: This listener should be disposed when you dispose the watcher too

Comment (dmitrivMS) [reply src/vs/workbench/contrib/chat/browser/chatAttachmentModel.ts]: Interesting... I thought those things were included. Let me fix that.

Comment (dmitrivMS) [reply src/vs/workbench/contrib/chat/browser/chatAttachmentModel.ts]: Done

**Review by roblourens — APPROVED** [review]
