### PR TITLE
theme: fix unthemable icons in several areas

### LINKED ISSUE #208343: Product icon for debug-stackframe-dot is not overwritten by designated icon in product icon theme
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2
- OS Version: Windows_NT x64 10.0.22621 (Windows 11 Professional)

Steps to Reproduce:

1. Create a product icon theme that replaces the product icon with identifier `debug-stackframe-dot`
2. Load product icon theme
3. Start debug session in a file/language with debugger support (e.g. Python)
4. The icon is not replaced. In developer tools I can see that the CSS property for `content` is incorrect (it uses the default VSCode product icon font and the font glyph content ID) as well as that the `font-family` property is not set.

---

I am in the middle of making a product icon theme and I happened to notice the described behaviour.

Either the documentation at https://code.visualstudio.com/api/references/icons-in-labels is (no longer?) incorrect or the logic to replace this icon is not present. All the other debug and debug-stackframe icons seem to be working just fine.

### PR DESCRIPTION
**Pull request by connor4312**
We manually used icon characters in several areas. These are/were entirely unthemable. Fixing this required people to manually listen to the theme service and apply rules to their elements when icons change. This PRs adds theme variables that people can use instead.

Fixes #208343

### CODE REVIEW

**Review by rzhao271 — DISMISSED** [review]

**Comment by rzhao271** [comment]
Hygiene failed for src/vs/workbench/browser/parts/editor/media/multieditortabscontrol.css(395,1): Bad whitespace indentation

**Comment by connor4312** [comment]
Fixed

**Review by rzhao271 — DISMISSED** [review]

File: src/vs/platform/theme/browser/iconsStyleSheet.ts [hunk 1]
```diff
@@ -31,34 +31,41 @@ export function getIconsStyleSheet(themeService: IThemeService | undefined): IIc
...
-			const rules = [];
-			for (const contribution of iconRegistry.getIcons()) {
-				const rule = formatIconRule(contribution);
-				if (rule) {
-					rules.push(rule);
+					rootAttribs.push(
+						`${fontFamilyVar}: ${asCSSPropertyValue(fontContribution.id)};`,
+						`${contentVar}: '${definition.fontCharacter}';`,
+					);
+					rules.push(`.codicon-${contribution.id}:before { content: '${definition.fontCharacter}'; font-family: ${asCSSPropertyValue(fontContribution.id)}; }`);
```
Comment (DeltaRazero) [inline src/vs/platform/theme/browser/iconsStyleSheet.ts:52]: The font-family property can be overridden by the more specific rule `.monaco-workbench .predefined-file-icon[class*=codicon-]:before`.
I found two icons that have their font-family property overridden by this rule , those being the `search` product icon (rule `.codicon-search-editor-label-icon:before`) when used as tab icon for a search editor tab, and the `settings` product icon (rule `.codicon-settings-editor-label-icon:before`) in a settings editor tab.

**Comment by DeltaRazero** [comment]
I haven't delved too deep in the affecting code and changes, however the `more` product icon as used in the terminal tab (see screenshot to make sure we're not misunderstanding) potentially could not have its icon changed and it might be due to a different issue. Could you please verify this is fixed?
image

File: src/vs/platform/theme/browser/iconsStyleSheet.ts (hunk 1 above)
Comment (connor4312) [reply src/vs/platform/theme/browser/iconsStyleSheet.ts:52]: This PR does not try to change the priority of the existing CSS rules

File: src/vs/platform/theme/browser/iconsStyleSheet.ts [hunk 2]
```diff
@@ -31,34 +31,41 @@ export function getIconsStyleSheet(themeService: IThemeService | undefined): IIc
...
+				} else {
+					rootAttribs.push(`${contentVar}: '${definition.fontCharacter}';`);
```
Comment (aeschli) [inline src/vs/platform/theme/browser/iconsStyleSheet.ts:54]: We should set `${fontFamilyVar}: 'codicon'` and not rely on the undefined variable behavior.

File: src/vs/workbench/contrib/files/browser/views/media/openeditors.css [hunk 3]
```diff
@@ -37,13 +37,15 @@
...
 
 .open-editors .monaco-list .monaco-list-row.dirty:not(:hover) > .monaco-action-bar .codicon-pinned::before {
-	content: "\ebb2"; /* use `pinned-dirty` icon unicode for sticky-dirty indication */
-	font-family: 'codicon';
+	/* use `pinned-dirty` icon unicode for sticky-dirty indication */
+	content: var(--vscode-icon-pinned-dirty-content);
+	font-family: var(--vscode-icon-pinned-dirty-font-family);
 }
 
 .open-editors .monaco-list .monaco-list-row.dirty:not(:hover) > .monaco-action-bar .codicon-close::before {
```
Comment (aeschli) [inline src/vs/workbench/contrib/files/browser/views/media/openeditors.css:45]: `.codicon-close` should be there anymore. It would set the close icon
But we would need a rule so that all oder codicon properties are inherited:
https://github.com/microsoft/vscode/blob/94f7c1d971f71d70cdef7b7ed461f399162d08c3/src/vs/base/browser/ui/codicons/codicon/codicon.css#L12

I think we should set
`.codicon[class*='codicon-']` to `.codicon`

Need to investigat if that has unwanted effects

File: src/vs/workbench/contrib/debug/browser/media/debug.contribution.css [hunk 4]
```diff
@@ -36,7 +36,8 @@
 .codicon-debug-breakpoint-conditional.codicon-debug-stackframe::after,
```
Comment (aeschli) [inline src/vs/workbench/contrib/debug/browser/media/debug.contribution.css:36]: Here the `.codicon-debug-breakpoint-conditional.codicon-debug-stackfram` class names are kind of misused to detect a cerain type of breakpoint.
Would be better if the debug view uses a different class name to mark breakpoint

**Review by aeschli — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/debug/browser/media/debug.contribution.css (hunk 4 above)
Comment (connor4312) [reply src/vs/workbench/contrib/debug/browser/media/debug.contribution.css:36]: This is actually used to detect a case where both a breakpoint exists and is on a current stackframe. Both of these have decorations of their own. Though technically we could handle that in code and make a 3rd type of decoration.

**Review by alexr00 — APPROVED** [review]

**Review by aeschli — APPROVED** [review]
