### PR TITLE
Ensure contributed tasks have a scope

### LINKED ISSUE #67990: Custom task providers no longer work in 1.31.0
Version: 1.31.0-insider (system setup)
Commit: b313db6c58f8c02181a33cd3b5b4b17c64a5b85d
OS: Windows_NT x64 10.0.17134
_____

The task returned by this simple example provider no longer shows up in the `Run Task...` UI for me with current Insider's builds:

Notably, **a breakpoint in `provideTasks` still triggers** when invoking the command, but for some reason the returned task seems to be discarded by VSCode?

It works with the current stable release (1.30.2), which would make this a regression:

______

```ts
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    vscode.workspace.registerTaskProvider("test", {
        provideTasks: () => {
            return [createTask("hello world")];
        },
        resolveTask(task: vscode.Task): vscode.Task | undefined {
            return task;
        }
    });
}

function createTask(message: string): vscode.Task {
    return new vscode.Task({type: "test"}, message, "test", new vscode.ShellExecution("echo " + message));
}
```

Relevant section from `package.json`:

```json
"activationEvents": [
    "*"
],
"contributes": {
    "taskDefinitions": [
        {
            "type": "test"
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by alexr00**
Fixes #67990

### CODE REVIEW

File: src/vs/workbench/api/node/extHostTask.ts [hunk 1]
```diff
@@ -195,6 +195,9 @@ namespace TaskDTO {
 			} else {
 				scope = value.scope.uri;
 			}
+		} else {
+			// To continue to support the deprecated task constructor that doesn't take a scope, we must add a scope here:
+			scope = types.TaskScope.Workspace;
 		}
 		if (!definition || !scope) {
```
Comment (dbaeumer) [inline src/vs/workbench/api/node/extHostTask.ts]: We could remove this || !scope now because it will never be undefined.

**Review by dbaeumer — APPROVED** [review]

File: src/vs/workbench/api/node/extHostTask.ts (hunk 1 above)
Comment (alexr00) [reply src/vs/workbench/api/node/extHostTask.ts]: I'll remove it in an upcoming change in master.
