### PR TITLE
fix async references to global token

### LINKED ISSUE #229437: Quick search showing stale results
1, open the quick search
2. type something out like `treesitter` in the vscode repo
3. notice that some results are only partial matches :bug:

### PR DESCRIPTION
**Pull request by andreamah**
fixes https://github.com/microsoft/vscode/issues/229437

### CODE REVIEW

**Review by connor4312 — DISMISSED** [review]

File: src/vs/workbench/contrib/search/browser/searchModel.ts [hunk 1]
```diff
@@ -2336,7 +2336,7 @@ export class SearchModel extends Disposable {
 			// resolve async parts of search
 			const allClosedEditorResults = await textResult.asyncResults;
 			const resolvedNotebookResults = await notebookResult.completeData;
-			tokenSource.dispose();
+			tokenSource.dispose(true);
```
Comment (connor4312) [inline src/vs/workbench/contrib/search/browser/searchModel.ts:2339]: should this be in a finally block?

Comment (andreamah) [reply src/vs/workbench/contrib/search/browser/searchModel.ts:2339]: yes, good catch

**Review by rzhao271 — APPROVED** [review]
