### PR TITLE
[npm extension] exclude top level npm_modules when detecting npm scripts in workspaces

### LINKED ISSUE #150204: [npm extension] top level npm_modules aren't excluded when detecting npm scripts in workspaces
Does this issue occur when all extensions are disabled?: No

Version: 1.67.2 (user setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.18363

In the course of investigating a Live Share performance issue we noticed an unusual amount of activity when we call: vscode.tasks.fetchTasks() against our Live Share workspace. The issue is that we include `node_modules` in the top level of our workspace file. The NPM extension isn't currently filtering this top level folder out - only node_module subfolders. I'm not sure if this is _by design_  as perhaps it was thought that users would never include this folder in their workspace? But we did - so perhaps others have too.  

Steps to Reproduce:

1. Open a workspace that contains a large _node_modules_ folder:

```
"folders": [
		{
			"path": "."
		},
		{
			"path": "../node_modules"
		}
	],
```
2. Call vscode.tasks.fetchTasks() from the extension.

### PR DESCRIPTION
**Pull request by jramsay**
This PR fixes #150204

### CODE REVIEW

File: extensions/npm/src/tasks.ts [hunk 1]
```diff
@@ -12,10 +12,12 @@ import * as path from 'path';
 import * as fs from 'fs';
 import * as minimatch from 'minimatch';
 import * as nls from 'vscode-nls';
+import { Utils } from 'vscode-uri';
 import { findPreferredPM } from './preferred-pm';
 import { readScripts } from './readScripts';
 
 const localize = nls.loadMessageBundle();
+const excludeRegex = new RegExp('node_modules|.vscode-test', 'i');
```
Comment (jramsay) [inline extensions/npm/src/tasks.ts:20]: will update this to be an exact match

**Review by meganrogge — APPROVED** [review]

**Comment by meganrogge** [comment]
In testing without the changes from this PR, I see that tasks are not provided even when there are some that I'd expect to see. @alexr00 

I'm logging the result of `vscode.tasks.fetchTasks` here and this is the VS Code repo open in OSS.
Screen Shot 2022-06-08 at 10 34 53 AM
