### PR TITLE
dont replace a cell for internal metadata change while the cell is executing

### LINKED ISSUE #230017: Don't reload notebook model if data didn't change
There are a few open issues related to this behavior (https://github.com/microsoft/vscode-jupyter/issues/12863, https://github.com/microsoft/vscode-jupyter/issues/15716) , but I'm trying to get logs to confirm the cause and want to try to figure out a solution separately.
 
Steps to Reproduce:

1. create a notebook cell with the code

```
import time 

for i in range(10):
    time.sleep(3)
    print(i)
```

2. execute the cell, and while it's running, change the `modified time` of the file on disk
e.g. with pwsh

```
$file = get-Item ./notebook.ipynb
$file.LastWriteTime = (Get-Date)
```

You might have to try a few times.

:bug: running cell is cancelled and focus is lost in the notebook

stack for code references:

```
at NotebookFileWorkingCopyModel.update (c:\src\vscode\src\vs\workbench\contrib\notebook\common\notebookEditorModel.ts:349:9)
    at async StoredFileWorkingCopy.doUpdateModel (c:\src\vscode\src\vs\workbench\services\workingCopy\common\storedFileWorkingCopy.ts:711:4)
    at async StoredFileWorkingCopy.resolveFromContent (c:\src\vscode\src\vs\workbench\services\workingCopy\common\storedFileWorkingCopy.ts:674:4)
    at async StoredFileWorkingCopy.resolveFromFile (c:\src\vscode\src\vs\workbench\services\workingCopy\common\storedFileWorkingCopy.ts:615:4)
    at async StoredFileWorkingCopyManager.doResolve (c:\src\vscode\src\vs\workbench\services\workingCopy\common\storedFileWorkingCopyManager.ts:562:4)
    at async StoredFileWorkingCopyManager.reload (c:\src\vscode\src\vs\workbench\services\workingCopy\common\storedFileWorkingCopyManager.ts:453:3)
    at async Object.factory (vscode-file://vscode-app/c:/src/vscode/out/vs/workbench/services/workingCopy/common/storedFileWorkingCopyManager.js:167:21)
```

The etag timestamp is checked when resolving to ensure that we are only loading file content if the file is newer: https://insiders.vscode.dev/github/microsoft/vscode/blob/main/src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts#L599

### PR DESCRIPTION
**Pull request by amunger**
fix https://github.com/microsoft/vscode/issues/230017

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/common/model/notebookCellTextModel.ts [hunk 1]
```diff
@@ -445,24 +446,41 @@ export class NotebookCellTextModel extends Disposable implements ICell {
 			return false;
 		}
 
-		if (this.internalMetadata?.executionOrder !== b.internalMetadata?.executionOrder
-			|| this.internalMetadata?.lastRunSuccess !== b.internalMetadata?.lastRunSuccess
-			|| this.internalMetadata?.runStartTime !== b.internalMetadata?.runStartTime
-			|| this.internalMetadata?.runStartTimeAdjustment !== b.internalMetadata?.runStartTimeAdjustment
-			|| this.internalMetadata?.runEndTime !== b.internalMetadata?.runEndTime) {
-			return false;
+		if (!ignoreMetadata) {
```
Comment (amunger) [inline src/vs/workbench/contrib/notebook/common/model/notebookCellTextModel.ts:449]: alternatively, we could handle internal metadata changes more precisely as we do for outputs and the other metadata changes

**Review by rebornix — APPROVED** [review]
