### PR TITLE
on cursor move, clear and recreate terminal initial hint

### LINKED ISSUE #286080: Fix Overlapping of Suggestion Text with Prompt in VS Code Terminal
Type: <b>Bug</b>

In the VS Code terminal, the suggestion text overlaps with the prompt, obscuring the display and reducing readability. This affects user experience during command input. Adjust the positioning or layering of suggestions to prevent overlap with the prompt.

VS Code version: Code - Insiders 1.108.0-insider (655abb9afbcac8678f4ff6c13d19e23c5cecebe3, 2026-01-06T05:02:34.944Z)
OS version: Windows_NT x64 10.0.26200
Modes:
Remote OS version: Linux x64 6.6.87.2-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1340P (16 x 2189)|
|GPU Status|2d_canvas: enabled<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>trees_in_viz: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.64GB (28.68GB free)|
|Process Argv|--crash-reporter-id 3df60e69-6e36-46e5-9b3d-020ce9a3ab01|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-24.04|
|OS|Linux x64 6.6.87.2-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i5-1340P (16 x 0)|
|Memory (System)|31.17GB (20.90GB free)|
|VM|0%|
</details><details><summary>Extensions (141)</summary>

Extension|Author (truncated)|Version
---|---|---
FreeMarker|dco|0.0.9
codespaces|Git|1.18.4
remotehub|Git|0.65.2025081801
output-colorizer|IBM|0.1.2
icon-fonts|idl|2.5.4
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.436.0
remote-ssh|ms-|0.123.2025121615
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.104.3
vscode-remote-extensionpack|ms-|0.26.0
remote-explorer|ms-|0.6.2025081809
remote-repositories|ms-|0.43.2025081801
remote-server|ms-|1.6.2025102109
vscode-serial-monitor|ms-|0.13.251128001
vscode-speech|ms-|0.16.0
vscode-speech-language-pack-zh-cn|ms-|0.5.1
material-icon-theme|PKi|5.30.0
errorlens|use|3.26.0
material-theme|zhu|3.19.0
codesnap|adp|1.3.4
claude-code|Ant|2.0.75
markdown-mermaid|bie|1.29.0
vscode-tailwindcss|bra|0.14.29
ruff|cha|2025.32.0
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.10.0
vscode-markdownlint|Dav|0.61.1
vscode-eslint|dba|3.0.21
dbcode|dbc|1.22.4
dingtalk-toolkit|Din|0.2.11
docker|doc|0.18.0
vscode-mybatisplus-jrebel|Dws|1.0.1
gitlens|eam|2026.1.304
EditorConfig|Edi|0.17.4
magick-image-reader|ely|0.5.0
prettier-vscode|esb|11.0.2
dependi|fil|0.7.21
shell-format|fox|7.2.8
copilot-chat|Git|0.36.2026010601
vscode-github-actions|git|0.29.1
vscode-pull-request-github|Git|0.125.2026010604
colab|goo|0.1.6
gc-excelviewer|Gra|4.2.64
latex-workshop|Jam|10.12.0
svg|joc|1.5.4
seamless-agent|jra|0.1.18
jrebel|JRe|2025.4.2
vscode-gutter-preview|kis|0.32.2
vscode-leetcode|Lee|0.18.4
loccy|loc|1.8.6
i18n-ally|lok|2.13.1
loghunter|mar|1.2.8
rainbow-csv|mec|3.23.0
pyrefly|met|0.46.3
vscode-azureresourcegroups|ms-|0.11.7
vscode-containers|ms-|2.3.0
vscode-dotnet-runtime|ms-|3.0.0
playwright|ms-|1.1.17
black-formatter|ms-|2025.3.11831009
debugpy|ms-|2025.19.2025121701
mypy-type-checker|ms-|2025.3.13521012
pylint|ms-|2025.3.12271016
python|ms-|2025.21.2026010501
vscode-pylance|ms-|2025.10.100
vscode-python-envs|ms-|1.15.13521014
jupyter|ms-|2025.10.2025121801
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.3.2025062701
python-ds-extension-pack|ms-|0.0.1
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl-recommender|ms-|0.0.20
cmake-tools|ms-|1.22.21
cpptools|ms-|1.30.0
cpptools-extension-pack|ms-|1.3.1
debug-value-editor|ms-|0.2.2
extension-test-runner|ms-|0.0.14
hexeditor|ms-|1.11.1
live-server|ms-|0.5.2025091501
powershell|ms-|2025.5.0
ts-file-path-support|ms-|1.0.0
vscode-github-issue-notebooks|ms-|0.0.134
vscode-serial-monitor|ms-|0.13.251128001
vscode-typescript-next|ms-|6.0.20260105
vscode-websearchforcopilot|ms-|0.2.2026010501
web-editors|ms-|0.3.0
vsliveshare|ms-|1.0.5959
windows-ai-studio|ms-|0.26.5
typescript-explorer|mxs|0.4.2
neo4j-for-vscode|neo|1.13.0
indent-rainbow|ode|8.3.1
vscode-versionlens|pfl|1.22.4
vscode-css-peek|pra|4.4.3
inline-html|pus|0.3.10
geo-data-viewer|Ran|2.6.0
tmlanguage-syntax-highlighter|Red|2.8.0
java|red|1.50.0
vscode-commons|red|0.0.6
vscode-community-server-connector|red|0.26.20
vscode-rsp-ui|red|0.24.12
vscode-xml|red|0.29.2025112508
vscode-yaml|red|1.19.1
redis-for-vscode|Red|1.4.0
omegasheets-vscode|rep|0.2.0
LiveServer|rit|5.7.9
claude-dev|sao|3.46.1
docxreader|Sha|1.3.1
vscode-fileutils|sle|3.10.3
sonarlint-vscode|Son|4.39.0
amp|sou|0.0.1767687087
opencode|sst|0.0.13
code-spell-checker|str|4.4.0
code-spell-checker-cspell-bundled-dictionaries|str|2.0.12
vscode-stylelint|sty|1.6.0
even-better-toml|tam|0.21.2
vscode-ai-foundry|Tea|0.12.5
shellcheck|tim|0.38.5
vscode-decompiler|tin|0.1.0
native-preview|Typ|0.20260106.1
luna-paint|Tyr|0.17.0
context7-mcp|Ups|1.0.1
explorer|vit|1.36.0
vscode-boot-dev-pack|vmw|0.2.2
vscode-spring-boot|vmw|2.0.1
vscode-app-mod-pack|vsc|0.2.4
vscode-gradle|vsc|3.17.2025111402
vscode-java-debug|vsc|0.58.2025121609
vscode-java-dependency|vsc|0.27.0
vscode-java-pack|vsc|0.30.2025111702
vscode-java-test|vsc|0.43.2025120408
vscode-maven|vsc|0.45.2025120808
vscode-spring-boot-dashboard|vsc|0.14.2025041702
vscode-spring-initializr|vsc|0.12.0
volar|Vue|3.2.2
vscode-wakatime|Wak|25.5.1
file-stats|Wan|1.1.1
markdown-notes|Wan|0.1.2
vscode-import-cost|wix|3.3.0
pretty-ts-errors|Yoa|0.7.0
markdown-all-in-one|yzh|3.6.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
pythonvspyt551:31249597
nativeloc1:31118317
dwcopilot:31158714
dwoutputs:31242946
copilot_t_ci:31333650
g012b348:31231168
pythonrdcb7:31268811
pythonpcpt1cf:31399617
6518g693:31302842
6abeh943:31336334
envsactivate1:31349248
editstats-enabled:31346256
cloudbuttont:31366566
todos-1:31405333
3efgi100_wstrepl:31403338
use-responses-api:31390341
2a0ce269:31419921
terminalsuggestenabled:31421703
none:31438490
cp_cls_t_966_ss:31442352
chatvisible:31417128
inlinechat_v2_hd992725:31426642
c0683394:31426860
find_all_ref_in_bg_t:31442083
478ah919:31426749
a5gib710:31434435
no_request_with_suggest:31438039
7ig2g208:31429686
anthropic_thinking_t:31427198
406hc587_ask_agent:31428392
cp_cls_c_1081:31433293
copilot-nes-oct-trt:31432609
ia-no-proxy-models-svc:31436618
nes-slash-models-on:31441832

```

</details>

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #286080

Before:
Screenshot 2026-01-07 at 10 52 07 AM

After:
Screenshot 2026-01-07 at 10 51 09 AM

### CODE REVIEW

File: src/vs/workbench/contrib/terminalContrib/inlineHint/browser/terminal.initialHint.contribution.ts [hunk 1]
```diff
@@ -108,6 +109,13 @@ export class TerminalInitialHintContribution extends Disposable implements ITerm
 		this._register(this._addon.onDidRequestCreateHint(() => this._createHint()));
 	}
 
+	private _disposeHint(): void {
+		this._hintWidget?.remove();
+		this._hintWidget = undefined;
+		this._decoration?.dispose();
+		this._decoration = undefined;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/inlineHint/browser/terminal.initialHint.contribution.ts]: `MutableDisposable` let's us avoid this

File: src/vs/workbench/contrib/terminalContrib/inlineHint/browser/terminal.initialHint.contribution.ts [hunk 2]
```diff
@@ -138,7 +146,10 @@ export class TerminalInitialHintContribution extends Disposable implements ITerm
 			}
 		}
 
-		this._register(this._xterm.raw.onKey(() => this.dispose()));
+		this._register(this._xterm.raw.onKey(() => {
+			this._cursorMoveListener.clear();
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/inlineHint/browser/terminal.initialHint.contribution.ts]: Should `_cursorMoveListener` just be a regular disposable and only be disposed when the class is disposed?

**Review by Tyriar — DISMISSED** [review]

File: src/vs/workbench/contrib/chat/browser/widget/chatContentParts/media/chatTerminalToolProgressPart.css [hunk 3]
```diff
@@ -59,6 +59,11 @@
 
 .chat-terminal-content-part .chat-terminal-content-title .chat-terminal-command-block > .rendered-markdown .monaco-tokenized-source {
 	background: transparent !important;
+	border: none !important;
+}
+
+.chat-terminal-content-part .chat-terminal-content-title .rendered-markdown .monaco-tokenized-source {
+	padding: 1px 0px !important;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/chat/browser/widget/chatContentParts/media/chatTerminalToolProgressPart.css:66]: Unrelated changes?

**Review by Tyriar — APPROVED** [review]

File: src/vs/workbench/contrib/chat/browser/widget/chatContentParts/media/chatTerminalToolProgressPart.css (hunk 3 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/chat/browser/widget/chatContentParts/media/chatTerminalToolProgressPart.css:66]: ooh, thanks for catching !
