### PR TITLE
only show output button when a command's markers haven't been disposed of

### LINKED ISSUE #154215: open output button doesn't work sometimes
https://user-images.githubusercontent.com/29464607/177442739-653bc7f0-3442-4bd0-bc0f-bf029dcfc81c.mov

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #154215

### CODE REVIEW

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts [hunk 1]
```diff
@@ -67,7 +67,7 @@ export class TerminalProfileService implements ITerminalProfileService {
 		// Wait up to 5 seconds for profiles to be ready so it's assured that we know the actual
 		// default terminal before launching the first terminal. This isn't expected to ever take
 		// this long.
-		this._profilesReadyBarrier = new AutoOpenBarrier(5000);
+		this._profilesReadyBarrier = new AutoOpenBarrier(20000);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts:70]: Accidentally slipped in?

**Review by Tyriar — DISMISSED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts:70]: yes nice catch

Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts:70]:
```suggestion
		this._profilesReadyBarrier = new AutoOpenBarrier(5000);
```

**Review by Tyriar — DISMISSED** [review]

**Review by Tyriar — APPROVED** [review]
