### PR TITLE
fix: update debug logic in process explorer

### LINKED ISSUE #168343: Extension host debug just shows loading indicator
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: Ubuntu 22.10

Steps to Reproduce:

1.  Open a folder with VSCode
2.  Open VSCode's Process Explorer
3.  Right click on `extensionHost`, then click debug
4.  Debug Panel opens and shows a loading indicator
5.  After some time, the loading indicator stops

debug-loading

### PR DESCRIPTION
**Pull request by connor4312**
- Remove support for the `legacy` debug protocol, which js-debug does
  not support (and was removed in Node 8)
- Don't try to connect to port 0 (fixes #168343)
- Add extra logic to ps.ts to classify `extension-host` consistently

### CODE REVIEW

File: src/vs/code/electron-sandbox/processExplorer/processExplorerMain.ts [hunk 1]
```diff
@@ -26,8 +26,8 @@ import { applyZoom, zoomIn, zoomOut } from 'vs/platform/window/electron-sandbox/
 import { StandardKeyboardEvent } from 'vs/base/browser/keyboardEvent';
 import { KeyCode } from 'vs/base/common/keyCodes';
 
-const DEBUG_FLAGS_PATTERN = /\s--(inspect|debug)(-brk|port)?=(\d+)?/;
-const DEBUG_PORT_PATTERN = /\s--(inspect|debug)-port=(\d+)/;
+const DEBUG_FLAGS_PATTERN = /\s--inspect(?:-brk|port)?=(\d+)?/;
+const DEBUG_PORT_PATTERN = /\s--inspect-port=(\d+)/;
```
Comment (Tyriar) [inline src/vs/code/electron-sandbox/processExplorer/processExplorerMain.ts:30]: I'm all in on capture groups now for readability, they made terminal links so much easier to deal with. You could make this `(?<port>\d+)` and then access via `matches?.groups?.port`

File: src/vs/code/electron-sandbox/processExplorer/processExplorerMain.ts [hunk 2]
```diff
@@ -374,22 +374,18 @@ class ProcessExplorer {
...
 			config.processId = String(item.pid);
 		}
 
 		// a debug-port=n or inspect-port=n overrides the port
 		matches = DEBUG_PORT_PATTERN.exec(item.cmd);
-		if (matches && matches.length === 3) {
+		if (matches) {
 			// override port
-			config.port = parseInt(matches[2]);
+			config.port = Number(matches[1]);
```
Comment (Tyriar) [inline src/vs/code/electron-sandbox/processExplorer/processExplorerMain.ts:388]: Why not `parseInt`?

File: src/vs/code/electron-sandbox/processExplorer/processExplorerMain.ts (hunk 1 above)
Comment (Tyriar) [inline src/vs/code/electron-sandbox/processExplorer/processExplorerMain.ts:30]: Should `-port` be removed from the first one?

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/code/electron-sandbox/processExplorer/processExplorerMain.ts (hunk 2 above)
Comment (connor4312) [reply src/vs/code/electron-sandbox/processExplorer/processExplorerMain.ts:388]: `parseInt` can 'parse' a lot of stuff that isn't [just a number](https://stackoverflow.com/a/4090577/1125956). I prefer using `Number` if I know a string should only be numeric since it'll fail fast with a NaN.

Also I recall some benchmarks where Number is faster than parseInt, but that's a microoptimization 🤷‍♂️

File: src/vs/code/electron-sandbox/processExplorer/processExplorerMain.ts (hunk 1 above)
Comment (connor4312) [reply src/vs/code/electron-sandbox/processExplorer/processExplorerMain.ts:30]: no, `--inspect-port` is still allowed. I had to check on that 😛

Comment (Tyriar) [reply src/vs/code/electron-sandbox/processExplorer/processExplorerMain.ts]: Oh I misread the first one, it's `--inspectport` and `--inspect-port`.

**Review by Tyriar — APPROVED** [review]
