### PR TITLE
Fix typo in marked.js sanitizer

### LINKED ISSUE #111257: Typo in marked.js sanitization regex
- VSCode Version: N/A
- OS Version: N/A

**pending PR**

Diff:

```
-		const match = markdown.isTrusted ? html.match(/^(<span[^<]+>)|(<\/\s*span>)$/) : undefined;
+		const match = markdown.isTrusted ? html.match(/^(<span[^>]+>)|(<\/\s*span>)$/) : undefined;
```

There was / is a typo in `markdownRenderer.js` that allowed any *trusted* document to pass arbitrary HTML through the marked.js sanitizer provided it is wrapped in `<span></span>` tags, or similar.

What could you have done with this? Not much that was not already possible in trusted mode, which, as far as I can tell is used just for Jypiter Notebooks that pretty much definitionally can execute Python anyway.

Insane strips everything worthwhile except `<a data-href=''/>` which you can use to send `command:` URIs on click (`javascript:` URIs are disabled at a higher level of abstraction), but the ability to do this is already allowlisted (L141) for trusted documents.

### PR DESCRIPTION
**Pull request by Zemnmez**
There was / is a typo in `markdownRenderer.js` that allowed any *trusted* document to pass arbitrary HTML through the marked.js sanitizer provided it is wrapped in `<span></span>` tags, or similar.

What could you have done with this? Not much that was not already possible in trusted mode, which, as far as I can tell is used just for Jypiter Notebooks that pretty much definitionally can execute Python anyway.

Insane strips everything worthwhile except `<a data-href=''/>` which you can use to send `command:` URIs on click (`javascript:` URIs are disabled at a higher level of abstraction), but the ability to do this is already allowlisted (L141) for trusted documents.

This PR fixes #111257

### CODE REVIEW

**Review by mjbvz — APPROVED** [review]

File: src/vs/base/browser/markdownRenderer.ts [hunk 1]
```diff
@@ -218,7 +218,7 @@ export function renderMarkdown(markdown: IMarkdownString, options: MarkdownRende
 	// We always pass the output through insane after this so that we don't rely on
 	// marked for sanitization.
 	markedOptions.sanitizer = (html: string): string => {
-		const match = markdown.isTrusted ? html.match(/^(<span[^<]+>)|(<\/\s*span>)$/) : undefined;
+		const match = markdown.isTrusted ? html.match(/^(<span[^>]+>)|(<\/\s*span>)$/) : undefined;
```
Comment (alexr00) [inline src/vs/base/browser/markdownRenderer.ts:221]: I'm not sure that `[^>]` is correct. We still want to prevent html tags from beginning.  `[^<>]` would probably be the best.

**Review by alexr00 — CHANGES_REQUESTED** [review]

**Comment by Zemnmez** [comment]
An HTML tag can’t begin inside the attributes of another HTML tag.

**Review by alexr00 — APPROVED** [review]

File: src/vs/base/browser/markdownRenderer.ts (hunk 1 above)
Comment (Zemnmez) [reply src/vs/base/browser/markdownRenderer.ts:221]: > An HTML tag can’t begin inside the attributes of another HTML tag.

I wrote this kind of hurriedly. I think you're right in that this regex is not a *perfect* way to do what's being attempted here, which is to allow `<span class="codicon codicon-something" style="color:#ffff">` defined later in the file:
https://github.com/microsoft/vscode/pull/111258/files#diff-a4165063d59c45ee5b74f5e37e26420a00e6832c8c40233fc5c77dac98c6fa48R307

It's a bigger fix than just a typo, but we might want to be safe by going so far as to allowlist this specific set of inputs, since the regexes are already there in part:

```javascript
/^(?:<span (?:(?:class="codicon codicon-[a-z\-]+(?:codicon-animation-[a-z\-]+)?")?|(?:style="(?:color\:#[0-9a-fA-F]+;|background-color\:#[0-9a-fA-F]+;)"))>|^<\/\s*span>)$/g
```

refiddle: http://refiddle.com/refiddles/5fbe763e75622d16b3130000
rail diagram: [rail diagram](https://regexper.com/#%2F%5E%28%3F%3A%3Cspan%20%28%3F%3A%28%3F%3Aclass%3D%22codicon%20codicon-%5Ba-z%5C-%5D%2B%28%3F%3Acodicon-animation-%5Ba-z%5C-%5D%2B%29%3F%22%29%3F%7C%28%3F%3A%28%3F%3Acolor%5C%3A%23%5B0-9a-fA-F%5D%2B%3B%29%3F%28%3F%3Abackground-color%5C%3A%23%5B0-9a-fA-F%5D%2B%3B%29%3F%22%29%29%3E%7C%5E%3C%5C%2F%5Cs*span%3E%29%24%2F)

Comment (mjbvz) [reply src/vs/base/browser/markdownRenderer.ts:221]: Instead of blocking a specific character, can we only allow specific characters? Something like:

```
<span( [a-z\-'"#0-9]*)?>
```

Comment (Zemnmez) [reply src/vs/base/browser/markdownRenderer.ts:221]: It *might* be possible to confuse that regex into showing something it's not meant to by ending each pass with a trailing quote:

```HTML
<span "> "this text may not be interpreted as HTML, but is parsed as HTML now"
```

Comment (mjbvz) [reply src/vs/base/browser/markdownRenderer.ts:221]: It should be safe if you require it to match the entire string

**Comment by mjbvz** [comment]
Thanks! Will be in the VS Code insiders build
