### PR TITLE
Fix #188804

### LINKED ISSUE #188804: `workbench.editorAssociations` does not respect full filenames
Type: <b>Bug</b>

Extension installed: `stateful.runme`

Goal: Open all `*.md`-Files with the default editor, except for `Container.md` which should be opened with `runme`.

Configuration:

```json
				"workbench.editorAssociations": {
					"*.md": "default",
					"Container.md": "runme"
				},
```

The setting for `*.md` is respected, the second one isn't. No matter how I change the config, it's always the same result. I can assign all markdown files to runme, or all to default. Specifying full filenames doesn't have any noticable effect. 

VS Code version: Code - Insiders 1.81.0-insider (fda972663af87b4d1dab87845e36c357738b44f9, 2023-07-25T08:12:53.439Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.0-1041-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3493)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (24.33GB free)|
|Process Argv|--crash-reporter-id ecbd11e2-224f-4385-94f0-5b494aa6300d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js & TypeScript @ ssh://gec|
|OS|Linux x64 5.15.0-1041-azure|
|CPUs|AMD Ryzen 7 5700X 8-Core Processor (16 x 3393)|
|Memory (System)|12.09GB (9.83GB free)|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by lramos15**
Fixes #188804

### CODE REVIEW

File: src/vs/workbench/services/editor/browser/editorResolverService.ts [hunk 1]
```diff
@@ -255,7 +255,9 @@ export class EditorResolverService extends Disposable implements IEditorResolver
 
 	getAssociationsForResource(resource: URI): EditorAssociations {
 		const associations = this.getAllUserAssociations();
-		const matchingAssociations = associations.filter(association => association.filenamePattern && globMatchesResource(association.filenamePattern, resource));
+		let matchingAssociations = associations.filter(association => association.filenamePattern && globMatchesResource(association.filenamePattern, resource));
+		// Sort matching associations based on glob length as a longer glob will be more specific
+		matchingAssociations = matchingAssociations.sort((a, b) => (b.filenamePattern?.length ?? 0) - (a.filenamePattern?.length ?? 0));
 		const allEditors: RegisteredEditors = this._registeredEditors;
 		// Ensure that the settings are valid editors
 		return matchingAssociations.filter(association => allEditors.find(c => c.editorInfo.id === association.viewType));
```
Comment (Tyriar) [inline src/vs/workbench/services/editor/browser/editorResolverService.ts:263]: Not sure if this is run frequently, but if it is you would be better off with a for const loop to avoid creating a new array per filter/sort call

**Review by Tyriar — APPROVED** [review]

File: src/vs/workbench/services/editor/browser/editorResolverService.ts (hunk 1 above)
Comment (lramos15) [reply src/vs/workbench/services/editor/browser/editorResolverService.ts:263]: I'm not sure what you mean by this? How would you use a fore const loop? I could write this as one changed thing but under the hood I think it's the same

```
const matchingAssociations = associations
  .filter(association => association.filenamePattern && globMatchesResource(association.filenamePattern, resource))
  .sort((a, b) => (b.filenamePattern?.length ?? 0) - (a.filenamePattern?.length ?? 0))
  .filter(association => allEditors.find(c => c.editorInfo.id === association.viewType));
```
