### PR TITLE
serve-web: fix `SECRET_KEY_MINT_PATH` does not honour `server-base-path`

### LINKED ISSUE #212369: serve-web: `SECRET_KEY_MINT_PATH` does not honour `server-base-path`
The `code serve-web` command was augmented with the `server-base-path` argument here in https://github.com/microsoft/vscode/pull/207932.

Because the  `SECRET_KEY_MINT_PATH` does not include the `server-base-path`, any attempts to mint a key will result in a 404 if the server-base-path is set.

I think this is the reason why I am experiencing an issue that any sign-in attempt in the browser (e.g., Github Copilot, Settings Sync) do not persist between page refreshes.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.1
- OS Version: x64

Steps to Reproduce:

1. Launch `code serve-web --server-base-path=<something>`
2. Open the browser, observe 404s to `/_vscode-cli/mint-key`

### PR DESCRIPTION
**Pull request by connor4312**
Fixes #212369

### CODE REVIEW

File: cli/src/commands/serve_web.rs [hunk 1]
```diff
@@ -208,11 +205,20 @@ fn handle_secret_mint(ctx: HandleContext, req: Request<Body>) -> Response<Body>
...
+) {
 	let headers = res.headers_mut();
 	headers.append(
 		hyper::header::SET_COOKIE,
-		PATH_COOKIE_VALUE.parse().unwrap(),
+		format!(
+			"{}={}{}; SameSite=Strict; Path=/",
+			PATH_COOKIE_NAME, base_path, SECRET_KEY_MINT_PATH,
+		)
+		.parse()
```
Comment (amunger) [inline cli/src/commands/serve_web.rs:220]: nit: is parse still needed?

File: cli/src/commands/serve_web.rs [hunk 2]
```diff
@@ -510,11 +518,24 @@ fn key_for_release(release: &Release) -> (Quality, String) {
...
 }
 
+fn normalize_base_path(p: &str) -> String {
+	let p = p.trim_matches('/');
+
+	if p.is_empty() {
+		return "/".to_string();
+	}
+
+	format!("/{}/", p.trim_matches('/'))
```
Comment (amunger) [inline cli/src/commands/serve_web.rs:528]: no need to trim_matches again

**Review by amunger — APPROVED** [review]
