### PR TITLE
Fix: release note don't use editor style

### LINKED ISSUE #83701: [Web] In product release notes are ugly compared to desktop
**Repo**
1. Using web
1. Open in product release notes

**Bug**
Left is web, right is electron

Screen Shot 2019-10-30 at 3 35 32 PM

* Different font
* Cramped line spacing 
* No block quote styling

### LINKED ISSUE #114667: [Markdown preview] Code tag font size
```js
"editor.fontSize": 25,
```

Markdown preview seems to be using different font-size for `<code>`  depending on editor font size. It doesn't look good if the editor font is big:

Screenshot (426)

I think it would be better if `<code>` was using the same font size as all the other text in the webview.

### PR DESCRIPTION
**Pull request by susiwen8**
This PR fixes #114667

### CODE REVIEW

File: src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts [hunk 1]
```diff
@@ -288,9 +288,8 @@ export class ReleaseNotesManager {
 					}
 
 					code {
-						font-family: var(--vscode-editor-font-family);
-						font-weight: var(--vscode-editor-font-weight);
-						font-size: var(--vscode-editor-font-size);
+						font-family: Menlo, Monaco, Consolas, "Droid Sans Mono", "Courier New", monospace, "Droid Sans Fallback";
+						font-size: 14px;
```
Comment (mjbvz) [inline src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts:292]: Makes sense for inline code. For codeblocks though, I believe we still should try to use the user's settings. We try to use their theme for codeblocks as well.

Can you confirm this will not effect codeblocks

**Review by mjbvz — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts (hunk 1 above)
Comment (susiwen8) [reply src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts:292]: Yes, this will affect code block

**Comment by susiwen8** [comment]
57fbf4ba39928d7c0d02eab6b40e597e

@mjbvz Hi, I have added a new css rule for code block, please check it. Thanks.

**Comment by mjbvz** [comment]
Thanks!
