### PR TITLE
fix terminal hang for `basic` and `none` SI strategies

### LINKED ISSUE #264013: Chat hangs if command is run in foreground terminal and then another is attempted
With `basic` or `none` shell integration strategy: 
1. Run `run ls in the terminal` in chat and accept the prompt
2. Manually run `top` in the Copilot terminal
3. Run `run cat README.md` in chat and accept the prompt
4. 🐛 hangs

cc @tyriar

https://github.com/user-attachments/assets/672b5e68-5c0a-4eea-9f4b-ab8deaf968da

### PR DESCRIPTION
**Pull request by meganrogge**
fix #264013

Before:

https://github.com/user-attachments/assets/a14fe82e-7463-4f5b-a435-b9dd89e94e74

After:

https://github.com/user-attachments/assets/7716de42-4ff5-4e86-8e17-09e03c949f4a

### CODE REVIEW

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/executeStrategy/basicExecuteStrategy.ts [hunk 1]
```diff
@@ -95,6 +96,15 @@ export class BasicExecuteStrategy implements ITerminalExecuteStrategy {
 				this._onDidCreateStartMarker.fire(this._startMarker = store.add(xterm.raw.registerMarker()));
 			}));
 
+			// Fixes #264013
+			const dataActive = await isDataActive(this._instance);
+			if (dataActive) {
+				this._log('Command timed out, sending SIGINT and retrying');
+				// Send SIGINT (Ctrl+C)
+				await this._instance.sendText('\x03', false);
+				await waitForIdle(this._instance.onData, 1000);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/executeStrategy/basicExecuteStrategy.ts]: going to see if this `waitForIdle` is needed

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/executeStrategy/basicExecuteStrategy.ts]: if not, can move the rest of this into the helper function

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/executeStrategy/basicExecuteStrategy.ts]: yes, it's needed.

Comment (meganrogge) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/executeStrategy/basicExecuteStrategy.ts]: going to try reducing this time

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/executeStrategy/basicExecuteStrategy.ts [hunk 2]
```diff
@@ -95,6 +96,15 @@ export class BasicExecuteStrategy implements ITerminalExecuteStrategy {
...
 			}));
 
+			// Fixes #264013
+			const dataActive = await isDataActive(this._instance);
+			if (dataActive) {
+				this._log('Command timed out, sending SIGINT and retrying');
+				// Send SIGINT (Ctrl+C)
+				await this._instance.sendText('\x03', false);
+				await waitForIdle(this._instance.onData, 100);
+			}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/executeStrategy/basicExecuteStrategy.ts]: As discussed I don't think we should do this generally, even 100ms adds up. Instead only doing this workaround when we detect the user interacted with the terminal:

* Listen to data events on all copilot-owned terminals and flag them as receiving input if they get one of these events, this could go on `toolTerminal`
* Clear that state for the terminal at the end of an execution
* Check for basic/none SI whether it's been touched, if so, send ^C and wait briefly for something that resembles a prompt `waitForIdleWithPromptHeuristics` (this would avoid that p10k problem)

**Review by Tyriar — DISMISSED** [review]

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/executeStrategy/basicExecuteStrategy.ts [hunk 3]
```diff
@@ -43,11 +44,14 @@ export class BasicExecuteStrategy implements ITerminalExecuteStrategy {
 	private readonly _onDidCreateStartMarker = new Emitter<IXtermMarker | undefined>;
 	public onDidCreateStartMarker: Event<IXtermMarker | undefined> = this._onDidCreateStartMarker.event;
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/executeStrategy/basicExecuteStrategy.ts:45]: added this to keep the diff simple

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts [hunk 4]
```diff
@@ -521,7 +521,6 @@ export class RunInTerminalTool extends Disposable implements IToolImpl {
 					outputMonitor = store.add(this._instantiationService.createInstance(OutputMonitor, { instance: toolTerminal.instance, sessionId: invocation.context!.sessionId, getOutput: (marker?: IXtermMarker) => getOutput(toolTerminal.instance, marker ?? startMarker) }, undefined, invocation.context!, token, command));
 				}));
 				const executeResult = await strategy.execute(command, token);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts:523]:
```suggestion
				const executeResult = await strategy.execute(command, token);

```

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/executeStrategy/basicExecuteStrategy.ts [hunk 5]
```diff
@@ -107,6 +118,9 @@ export class BasicExecuteStrategy implements ITerminalExecuteStrategy {
 			// execution requested
 			const finishedCommand = await onDone;
 
+			// Reset user input state after command execution completes
+			this._toolTerminal.receivedUserInput = false;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/executeStrategy/basicExecuteStrategy.ts]: This could live in `runInTerminalTool` after we `await execute()`, then the resetting is the same for all strategies

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts [hunk 6]
```diff
@@ -641,6 +643,14 @@ export class RunInTerminalTool extends Disposable implements IToolImpl {
 		return toolTerminal;
 	}
 
+	private _registerInputListener(toolTerminal: IToolTerminal): void {
+		const disposable = toolTerminal.instance.onData(data => {
+			toolTerminal.receivedUserInput = data.length > 0;
+		});
+		this._register(toolTerminal.instance.onDisposed(() => disposable.dispose()));
+	}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts]: You should filter out `telemetryIgnoredSequences`

https://github.com/microsoft/vscode/blob/e2fb54b517a2180f3710a9853c43e5f9ad0848bc/src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts#L129-L132

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/executeStrategy/noneExecuteStrategy.ts [hunk 7]
```diff
@@ -22,13 +23,16 @@ export class NoneExecuteStrategy implements ITerminalExecuteStrategy {
...
 	private _startMarker: IXtermMarker | undefined;
 
+	private readonly _instance: ITerminalInstance;
+
 	private readonly _onDidCreateStartMarker = new Emitter<IXtermMarker | undefined>;
 	public onDidCreateStartMarker: Event<IXtermMarker | undefined> = this._onDidCreateStartMarker.event;
 
 	constructor(
-		private readonly _instance: ITerminalInstance,
+		private readonly _toolTerminal: IToolTerminal,
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/executeStrategy/noneExecuteStrategy.ts]: It's probably nicer actually to keep it how it was and still pass in `_instance` but also `_hasReceivedUserInput: () => boolean`. That way the properties on the `IToolTerminal` object can't be messed with here at all (combined with my other comment).

**Review by Tyriar — DISMISSED** [review]

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/executeStrategy/basicExecuteStrategy.ts (hunk 5 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/executeStrategy/basicExecuteStrategy.ts]: Thought about that but we don't do this for the rich strategy.

**Review by TylerLeonhardt — APPROVED** [review]
