### PR TITLE
Fix race condition in showing and hiding suggestWidget

### LINKED ISSUE #2437: Race condition in showing and hiding the suggestions widget
We are using Monaco to provide syntax highlighting and autocomplete for a search bar. This issue popped up when upgrading from Monaco from 0.18.1 to 0.23.0. When typing very quickly, the Monaco suggestions widget will sometimes get stuck in an empty state when it should be hidden.

Here is a normal screenshot of our autocomplete:

image

Here is a screenshot of when this bug happens:

image

I have narrowed down the issue to a race condition in `suggestionWidget.ts`. When showing the widget, [there is a 100ms timeout](https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/suggest/suggestWidget.ts#L493). However, [hiding is immediate](https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/suggest/suggestWidget.ts#L443). Therefore, typing very fast could cause the hiding to happen before the showing.

I was able to fix this by modifing `suggestionWidget.ts` to not add the `visible` class if the widget is in a hidden state. 

```diff
private _show(): void {
	this._status.show();
	this._contentWidget.show();
	this._layout(this._persistedSize.restore());
	this._ctxSuggestWidgetVisible.set(true);

	this._showTimeout.cancelAndSet(() => {
+		if (this._state !== State.Hidden)
			this.element.domNode.classList.add('visible');
			this._onDidShow.fire(this);
+		}
	}, 100);
}
```

**monaco-editor version:** 0.23.0
**Browser:** Latest Chrome/Edge
**OS:** masOS 11
**Playground code that reproduces the issue:** I am still working on a minimal repro for this in the playground.

### PR DESCRIPTION
**Pull request by limitedmage**
This PR fixes https://github.com/microsoft/monaco-editor/issues/2437

If suggestions are triggered by typing, typing causes the suggest widget be shown and then hidden as the typing initially matches some suggestions but then no suggestions. However, a race condition might happen because [there is a 100ms timeout for showing the widget](https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/suggest/suggestWidget.ts#L493), but [hiding is immediate](https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/suggest/suggestWidget.ts#L443). This change fixes the issue by cancelling the show timeout when hiding the widget.

### CODE REVIEW

File: src/vs/editor/contrib/suggest/suggestWidget.ts [hunk 1]
```diff
@@ -490,8 +490,10 @@ export class SuggestWidget implements IDisposable {
 		this._ctxSuggestWidgetVisible.set(true);
 
 		this._showTimeout.cancelAndSet(() => {
-			this.element.domNode.classList.add('visible');
-			this._onDidShow.fire(this);
+			if (this._state !== State.Hidden) {
+				this.element.domNode.classList.add('visible');
+				this._onDidShow.fire(this);
+			}
```
Comment (jrieken) [inline src/vs/editor/contrib/suggest/suggestWidget.ts:496]: I'd say a better fix is to call `this._showTimeout.cancel()` when hiding. That avoids the check all together

**Review by jrieken — CHANGES_REQUESTED** [review]

**Comment by limitedmage** [comment]
@jrieken I made the suggested change and now integration tests are failing in CI (they are passing locally for me). Any idea what may be happening? I synced my branch to latest main.l

**Review by jrieken — APPROVED** [review]
lgtm
