### PR TITLE
Restarting task should read the updated content

### LINKED ISSUE #169267: "The task is already active" button "Restart Task" doesn't re-read tasks.json
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Create a task in tasks.json and run it from "Run Task" in Command Palette
2. Use "Run Task" in Command Palette, open the Terminal panel and go to the task.
3. While the task is running, edit the task in tasks.json and save.
4. Warning message appears, The task '..' is already active.
5. Click "Restart Task". The task restarts with the old task definition instead of the new one.

### PR DESCRIPTION
**Pull request by anthonykim1**
Resolves: https://github.com/microsoft/vscode/issues/169267

Fixing two things in this PR:
* Issue where re-run last task did not check for task update, did not re-read the tasks.json content
* Issue where re-starting running task did not check for task update, or deletion

### CODE REVIEW

File: src/vs/workbench/contrib/tasks/common/taskSystem.ts [hunk 1]
```diff
@@ -23,6 +25,38 @@ export const enum TaskErrors {
 	UnknownError
 }
 
+export class VerifiedTask {
```
Comment (anthonykim1) [inline src/vs/workbench/contrib/tasks/common/taskSystem.ts:28]: Had to move this here for code layer!

**Comment by anthonykim1** [comment]
Proof of testing both restarting on going task and re-running last task:

restarting:
https://github.com/user-attachments/assets/c256624f-17ed-4997-96d4-62e1da4f1c86


rerunning last task:


https://github.com/user-attachments/assets/78046d07-efd3-4c97-9f10-2d2c18100275

**Comment by meganrogge** [comment]
@anthonykim1 thanks for working on this! Can you test this on a longrunning task for which you get the notification "the task is already active" vs a single run task like the one in your gif?

**Comment by anthonykim1** [comment]
@meganrogge Thanks for reviewing! 

Yeah, actually I'm not sure why that notification didn't show up in the first gif (the one that prints for 30 second). 
I'm wondering if it needs to be continuous like compile task. Let me see if I get better luck with those.

Edit: Oh, wait I'm finally able to get the notification, but this only shows up sometimes when I re-run, not when I restart from command palette:

Screenshot 2025-06-18 at 1 54 56 PM

Just found a bug where re-starting non-changed compile task leads to error, will investigate and fix!

**Comment by anthonykim1** [comment]
Just tried with compile task for vscode-python here:
Seems like working in the sense that it knows tasks has changed but I'm still not getting the "task is already active" notification.
https://github.com/user-attachments/assets/2424544a-4c90-4b0f-885c-f22e0838949a

**Comment by anthonykim1** [comment]
Got the bug resolved! 

Here are some testing GIFs @meganrogge:


https://github.com/user-attachments/assets/0d1ce09d-7c41-4ca4-a691-b5a384b533cd


https://github.com/user-attachments/assets/fdafdb9f-1a7b-4acb-8bcf-07b14aa44d5a


https://github.com/user-attachments/assets/353a7aea-22e3-47c8-b41b-9aaf226bd5ca

**Review by meganrogge — APPROVED** [review]
LGTM, thanks so much Anthony!
