### PR TITLE
debug: fix toolbar X value goes off screen causing odd DND behavior

### LINKED ISSUE #239654: Debug Toolbar X value goes off screen causing odd DND behavior
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

2. making window left half the screen
2. try dragging the toolbar to the far right of screen, stop dragging
2. now try dragging the toolbar to the left

:bug: you cursor has to move to the left a lot before the toolbar actually starts moving.

### PR DESCRIPTION
**Pull request by connor4312**
And respects the controls container better. I hate it but this seems to be the way. Could be generalized.

Fixes #239654

### CODE REVIEW

File: src/vs/workbench/contrib/debug/browser/debugToolBar.ts [hunk 1]
```diff
@@ -217,13 +209,49 @@ export class DebugToolBar extends Themable implements IWorkbenchContribution {
...
+	/**
+	 * Computes the x percent position at which the toolbar is currently displayed.
+	 */
+	private computeCurrentXPercent(): number {
+		const { left, width } = this.$el.getBoundingClientRect();
+		return (left + width / 2) / dom.getWindow(this.$el).innerWidth;
+	}
+
+	/**
+	 * Gets the y position set in the style of the toolbar. This may not be its
```
Comment (TylerLeonhardt) [inline src/vs/workbench/contrib/debug/browser/debugToolBar.ts:247]:
```suggestion
	 * Gets the x position set in the style of the toolbar. This may not be its
```

**Review by roblourens — APPROVED** [review]

**Review by TylerLeonhardt — APPROVED** [review]

**Comment by bpasero** [comment]
@TylerLeonhardt @connor4312 with https://github.com/microsoft/vscode/pull/239666, WCO is enabled on macOS, making CSS variables work. Maybe this helps reduce the workarounds here? Let me know how it goes.
