### PR TITLE
Fix #59635

### LINKED ISSUE #59635: Terminal.processId property is not updated once terminal's process is changed
- VSCode Version: 1.27.2
- OS Version: Ubuntu 16.04 64-bit

Steps to Reproduce:

1. [Clone this repo](https://github.com/g-arjones/vscode-task-provider-bug)
2. Run the extension
3. Run the "Terminal Test Task" provided by the extension
4. You should see something like `1111 == 1111` 
5. Run the same task again, you should see that Terminal.processId doesn't get updated

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by g-arjones**
@Tyriar AFAICT, the process Id promise resolver [is invalidated once the process id is set](https://github.com/Microsoft/vscode/blob/1358e903716cf77711493770d63dde1ea178a73e/src/vs/workbench/api/node/extHostTerminalService.ts#L145). 

Please let me know if there is a problem with this...

Fix #59635

### CODE REVIEW

File: src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts [hunk 1]
```diff
@@ -772,6 +774,8 @@ export class TerminalInstance implements ITerminalInstance {
 		this._processManager.onProcessExit(exitCode => this._onProcessExit(exitCode));
 		this._processManager.onProcessData(data => this._onData.fire(data));
 
+		this._onProcessLaunching.fire(this);
```
Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: I think the ID may not be ready at this time (race condition), `this._processManager.onProcessReady` should instead be used as the new ID will definitely be set:

https://github.com/Microsoft/vscode/blob/cbd629998bdcc07bd4f98ecc3721b27a20317ec9/src/vs/workbench/parts/terminal/electron-browser/terminalProcessManager.ts#L130-L131

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts (hunk 1 above)
Comment (g-arjones) [reply src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: Sorry, I don't get your point. I am not setting nor using the process id here. This onProcessLaunching event is fired just so that the terminal instance can create the promise and store the resolver which can be done as soon as a new process request is received. Or am I missing something?

Comment (g-arjones) [reply src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: /cc @Tyriar

Comment (alexr00) [reply src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: +1 to using onProcessReady to ensure that the ID is already set.

**Review by alexr00 — DISMISSED** [review]
+1 to using `onProcessReady` to ensure that the ID is already set.

File: src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts (hunk 1 above)
Comment (g-arjones) [reply src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: I'm obviously missing the point here. I mean, onProcessLaunching signals that a new process will be launched whereas onProcessIdReady signals that the process DID launch. They serve different purposes in my opinion.

Besides, why have these events nested? If onProcessLaunching is going to be fired by onProcessIdReady isn't it more sensible to just create the process Id promise in onProcessIdReady anyway?

Could you please elaborate on that just for the sake of clarity?

Comment (Tyriar) [reply src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: You're using the event and then passing in `instance`

https://github.com/Microsoft/vscode/pull/60111/files#diff-738f70b1596a3687ce11b464cd29bfc2R283

That event listener then uses instance.id:

https://github.com/Microsoft/vscode/pull/60111/files#diff-fef4270273da47cf116c1d80fe3da649R38

This is what we're concerned about, `instance.id` may still be out of date but it wouldn't be if `this._processManager.onProcessReady` was used instead to fire the original event.

Comment (g-arjones) [reply src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts]: @Tyriar Hmmm.. But isn't that the terminal instance id (rather than the process id) ? The terminal instance id is set in its constructor here:

https://github.com/Microsoft/vscode/blob/0ce96012870c5364eb143c62b9fcce56fcdfecf8/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L142

And should not depend on the process id being set. Is that correct?

**Review by Tyriar — APPROVED** [review]
@g-arjones thanks for the investigation and the great repro, they were very useful to get to the bottom of this. I ended up coming with a simpler fix to just recreate the promiseId using the existing mechanism. And sorry about the delay, I was out all November. 😃
