### PR TITLE
First kernel change not re-rendering markdown cells

### LINKED ISSUE #159101: Changing kernels causes markdown cells to disappear
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.71.0-insider (Universal)
Commit: 7ed02a69658fc07f08740b98fa0d8d96c1a61ed4
Date: 2022-08-24T05:18:46.886Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

Steps to Reproduce:

1. Open a notebook
2. Create a markdown cell and ensure you are out of edit mode for the md cell
3. Create a code cell
4. Verify the markdown cell is rendered as expected
5. Change the kernel to something else
6. Markdown cell now dissappears

Only way to get it back is to reload vscode

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #159101

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts [hunk 1]
```diff
@@ -942,6 +944,15 @@ var requirejs = (function() {
 			this._sendMessageToWebview({ ...inset.cachedCreation, initiallyHidden: this.hiddenInsetMapping.has(output) });
 		}
 
+		if (this.firstInit) {
+			// On first run the contents have already been initialized so we don't need to init them again
+			this.firstInit = false;
```
Comment (roblourens) [inline src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts:949]: This is fine but seems like it would be better if something in `initializeMarkup` could tell whether the initialization had definitely already happened. Otherwise seems like we might make a change somewhere else and hit this block. Not super familiar with this code though.

**Review by roblourens — APPROVED** [review]
