### PR TITLE
Fix package.json Auto complete

### LINKED ISSUE #17342: Broken autocomplete for package.json dependencies
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z) + Code 1.9.0-insiders
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-icontheme-nomo-dark|be5invis|1.2.1|
|vscode-svgviewer|cssho|1.3.0|
|typewriter|dansilver|1.0.0|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.5.40|
|docthis|joelday|0.3.5|
|vscode-csscomb|mrmlnc|4.0.0|
|vscode-duplicate|mrmlnc|1.0.2|
|vscode-jade-snippets|mrmlnc|1.0.1|
|vscode-less|mrmlnc|0.6.0|
|vscode-puglint|mrmlnc|2.3.0|
|vscode-scss|mrmlnc|0.6.0|
|debugger-for-chrome|msjsdiag|2.4.0|
|indent-rainbow|oderwat|0.4.1|
|promise-snippets|progre|0.2.3|
|nunjucks|ronnidc|0.2.3|
|linter-xo|samverschueren|2.1.0|
|standard|shinnn|0.2.3|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1. Create `package.json` file
  ```json
  {
    "name": "teamcity-test",
    "version": "0.0.1",
    "devDependencies": {
      |cursor
    }
  }
  ```

2. Start writing name of dependency
3. Press <kbd>Enter</kbd> for any suggestion

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #17342

**Bug**
I believe that 739d8ca77f6215a5a385587e6e6c7d66fdbe15c6 introduced a regression for package.json auto complete where we end up inserting the text `*` when completing dependency versions

**Fix**
Insert `""` instead of star to match previous behavior better

### CODE REVIEW

**Comment by jrieken** [comment]
Not so sure. The afore mentioned commit replaced `insertText += ': "{{*}}"';` with `insertText.appendText(': ').appendPlaceholder('*');`. Both should describe a placeholder containing `*`

File: extensions/javascript/src/features/packageJSONContribution.ts [hunk 1]
```diff
@@ -67,7 +67,7 @@ export class PackageJSONContribution implements IJSONContribution {
 										let name = keys[0];
 										let insertText = new SnippetString().appendText(JSON.stringify(name));
 										if (addValue) {
-											insertText.appendText(': ').appendPlaceholder('*');
+											insertText.appendText(': "').appendPlaceholder('').appendText('"');
 											if (!isLast) {
```
Comment (jrieken) [inline extensions/javascript/src/features/packageJSONContribution.ts]: should be `"*"`, not just `""`

**Review by jrieken — CHANGES_REQUESTED** [review]

**Comment by mjbvz** [comment]
@jrieken The reason using an empty string was that I was trying to get the version intellisense to trigger properly after you complete the package name. Here's what I originally tried:

```js
insertText.appendText(': "').appendPlaceholder('*').appendText('"');
```

dec-20-2016 15-47-34

The makes the `package.json` valid, but you have to type a character in order to get any intellisense for the version names. Is this what you recommend using instead, or was it something else?

**Comment by jrieken** [comment]
> Is this what you recommend using instead, or was it something else?

Unsure. I didn't originally write the code but just migrated it. Naturally, I try to get its original behaviour back. What you say makes sense, we should check with @aeschli why it was `"*"` in the beginning

**Review by jrieken — APPROVED** [review]
