### PR TITLE
get placeholder to be read by screen reader for chat inputs

### LINKED ISSUE #269070: NVDA is not announcing placeholder text in the Copilot chat input field: A11y_Visual Studio Code Copilot Extensions_Inline Chat_Screen Reader
### GitHub Tags:
#A11yTCS; #A11ySev2; #DesktopApp; #Win11; #Win32; #A11yMAS; #SH-Visual Studio Code Copilot Extensions-Win32-Sept25;#Visual Studio Code Client;#WCAG1.3.1;#AILimited; #Screen Reader; #NVDA; #Info and Relationships; #Element:Placeholder; 

### Environment Details:
Application Name: Visual Studio Code Copilot Extensions
Visual studio code Version: 1.104.2 (user setup)
Microsoft Windows 11 Enterprise 24H2 Build 26100.6584

### Repro Steps:

1. Open Visual studio Code.
2. Login to GitHub copilot chat.
3. Tab till editor section and press "Ctrl + i" inline chat will get open.
4. Tab till copilot chat input field.
5. Observe that NVDA is announcing placeholder text in the Copilot chat input field or not.

### Actual Result:
NVDA is not announcing "Add Context (#), extensions (@), commands (/)" placeholder text in the Copilot chat input field

### Expected Result:
NVDA should announce the placeholder text "Add Context (#), extensions (@), commands (/)" when the chat input field receives focus.

### User Impact:
Users relying on Screen reader may face difficulty understanding the purpose of the input field when placeholder text is not announced. 

### Attachment:

https://github.com/user-attachments/assets/f51cdf88-b029-4c81-821d-4f171509189a

### PR DESCRIPTION
**Pull request by meganrogge**
fix #269070

The active element is this and that lacks aria info. Applies to all chat inputs.

Screenshot 2025-11-07 at 3 55 45 PM

Before:

Screenshot 2025-11-07 at 3 44 57 PM

After:

Screenshot 2025-11-07 at 3 44 25 PM

### CODE REVIEW

File: src/vs/workbench/contrib/chat/browser/contrib/chatInputEditorContrib.ts [hunk 1]
```diff
@@ -295,6 +300,19 @@ class InputEditorDecorations extends Disposable {
 
 		this.widget.inputEditor.setDecorationsByType(decorationDescription, variableTextDecorationType, varDecorations);
 	}
+
+	private updateAriaPlaceholder(value: string | undefined): void {
+		// eslint-disable-next-line no-restricted-syntax
+		const nativeEditContext = this.widget.inputEditor.getDomNode()?.querySelector<HTMLElement>('.native-edit-context');
```
Comment (roblourens) [inline src/vs/workbench/contrib/chat/browser/contrib/chatInputEditorContrib.ts]: Please don't hack DOM elements inside another component like this. If the monaco editor doesn't have a proper API to set this, then it should. Aiday might know about the 'edit context' thing, if not, then Henning.

Comment (roblourens) [reply src/vs/workbench/contrib/chat/browser/contrib/chatInputEditorContrib.ts]: We just added the eslint rule for a reason, see the discussion at https://vscodeteam.slack.com/archives/C03ERNTC03X/p1761809515111899

Comment (meganrogge) [reply src/vs/workbench/contrib/chat/browser/contrib/chatInputEditorContrib.ts]: @aiday-mar or @hediet do you know how we can access this element in a less hacky way?

Comment (aiday-mar) [reply src/vs/workbench/contrib/chat/browser/contrib/chatInputEditorContrib.ts]: Yes, you can use the NativeEditContextRegistry to fetch the NativeEditContext and the dom node from there. It is in the file _nativeEditContextRegistry.ts_.

**Review by dmitrivMS — APPROVED** [review]
