### PR TITLE
fix layer break

### LINKED ISSUE #211739: Layer breaking: notebook contrib imported into notebook core
https://github.com/microsoft/vscode/blob/001929db91b434532f9307ea7643e71aeba4104b/src/vs/workbench/contrib/notebook/browser/viewModel/codeCellViewModel.ts#L25

We should probably do the other way around, creating a notebook contribution like https://github.com/microsoft/vscode/blob/001929db91b434532f9307ea7643e71aeba4104b/src/vs/workbench/contrib/notebook/browser/contrib/cellStatusBar/contributedStatusBarItemController.ts#L15

### PR DESCRIPTION
**Pull request by amunger**
fix https://github.com/microsoft/vscode/issues/211739

also, one diagnostic editor contribution will manage the entire notebook, rather than one per cell which contributed to https://github.com/microsoft/vscode/issues/211112

### CODE REVIEW

File: src/vs/workbench/contrib/notebook/browser/contrib/cellStatusBar/executionStatusBarItemController.ts [hunk 1]
```diff
@@ -361,17 +362,18 @@ class DiagnosticCellStatusBarItem extends Disposable {
...
 		this._update();
-		this._register(this.cell.cellDiagnostics.onDidDiagnosticsChange(() => this._update()));
+		this._register(this.cellDiagnostics.onDidDiagnosticsChange(() => this._update()));
 	}
 
 	private async _update() {
 		let item: INotebookCellStatusBarItem | undefined;
 
-		if (!!this.cell.cellDiagnostics.ErrorDetails) {
+		if (!!this.cellDiagnostics.getCellExecutionError(this.cell.uri)) {
```
Comment (rebornix) [inline src/vs/workbench/contrib/notebook/browser/contrib/cellStatusBar/executionStatusBarItemController.ts:376]: we can archive this by `notebookEditor.getContribution(CellDiagnostics.ID)#getCellDiagnostics(uri: cellUri)`

File: src/vs/workbench/contrib/notebook/browser/view/cellParts/cellContextKeys.ts [hunk 2]
```diff
@@ -101,7 +103,7 @@ export class CellContextKeyManager extends Disposable {
 
 		if (element instanceof CodeCellViewModel) {
 			this.elementDisposables.add(element.onDidChangeOutputs(() => this.updateForOutputs()));
-			this.elementDisposables.add(element.cellDiagnostics.onDidDiagnosticsChange(() => this.updateForDiagnostics()));
+			this.elementDisposables.add(this._notebookCellDiagnosticsService.onDidDiagnosticsChange(() => this.updateForDiagnostics()));
```
Comment (rebornix) [inline src/vs/workbench/contrib/notebook/browser/view/cellParts/cellContextKeys.ts:106]: I'm wondering if we can introduce the concept of `NotebookEditorWidget.getCellContextKeyManager()`. Once we have a cell context key manager, it can expose `ContextKeyManager.createContextKey(): IDisposable`

File: src/vs/workbench/contrib/notebook/browser/contrib/cellDiagnostics/cellDiagnosticEditorContrib.ts [hunk 3]
```diff
@@ -0,0 +1,144 @@
...
+			this.enabled = true;
+			if (!this.listening) {
+				this.listening = true;
+				this._register(this.notebookExecutionStateService.onDidChangeExecution((e) => this.handleChangeExecutionState(e)));
+			}
+		}
+	}
+
+	private handleChangeExecutionState(e: ICellExecutionStateChangedEvent | IExecutionStateChangedEvent) {
+		const notebookUri = this.notebookEditor.textModel?.uri;
```
Comment (rebornix) [inline src/vs/workbench/contrib/notebook/browser/contrib/cellDiagnostics/cellDiagnosticEditorContrib.ts:67]: do we want to debounce the listener a bit?

File: src/vs/workbench/contrib/notebook/browser/contrib/cellDiagnostics/DiagnosticCellStatusBarContrib.ts [hunk 4]
```diff
@@ -0,0 +1,74 @@
+/*---------------------------------------------------------------------------------------------
```
Comment (rebornix) [inline src/vs/workbench/contrib/notebook/browser/contrib/cellDiagnostics/DiagnosticCellStatusBarContrib.ts:1]: The file name is capitilized.

**Review by rebornix — COMMENTED** [review]
Looks good in overall!

**Review by roblourens — APPROVED** [review]
