### PR TITLE
fix terminal disposable leaks, get dropdown menu to show for terminal editors

### LINKED ISSUE #239741: terminal disposable leaks
Image

### LINKED ISSUE #239810: dropdown action menu missing for terminal editors
In insider's - noticed when debugging action view item disposables. cc @Tyriar 

Image

### PR DESCRIPTION
**Pull request by meganrogge**
fix #239741 
fix https://github.com/microsoft/vscode/issues/239810

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 1]
```diff
@@ -846,7 +846,7 @@ export class TerminalService extends Disposable implements ITerminalService {
 			instance.onDidFocus(this._onDidChangeActiveInstance.fire, this._onDidChangeActiveInstance),
 			instance.onRequestAddInstanceToGroup(async e => await this._addInstanceToGroup(instance, e))
 		];
-		instance.onDisposed(() => dispose(instanceDisposables));
+		this._register(instance.onDisposed(() => dispose(instanceDisposables)));
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:849]: We can't register an instance event against the terminal service as it'll keep stacking up stale references and leaking memory. This probably needs to be tracked in something like `_instanceDisposeListeners: DisposableMap<ITerminalInstance, DisposableStore>` and removed after dispose. Then we can then just register that `DisposableMap` when it's created to clean it up.

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 2]
```diff
@@ -1002,7 +1002,7 @@ export class TerminalService extends Disposable implements ITerminalService {
 			const instance = this._terminalInstanceService.createInstance(shellLaunchConfig, TerminalLocation.Panel);
 			this._backgroundedTerminalInstances.push(instance);
 			this._backgroundedTerminalDisposables.set(instance.instanceId, [
-				instance.onDisposed(this._onDidDisposeInstance.fire, this._onDidDisposeInstance)
+				this._register(instance.onDisposed(this._onDidDisposeInstance.fire, this._onDidDisposeInstance))
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:1005]: Similar here, we can't register instance events against the service

File: src/vs/workbench/contrib/terminal/browser/terminalView.ts [hunk 3]
```diff
@@ -127,11 +127,11 @@ export class TerminalViewPane extends ViewPane {
 			}
 		}));
 		this._register(this._terminalService.onDidCreateInstance((i) => {
-			i.capabilities.onDidAddCapabilityType(c => {
+			this._register(i.capabilities.onDidAddCapabilityType(c => {
 				if (c === TerminalCapability.CommandDetection && this._gutterDecorationsEnabled()) {
 					this._parentDomElement?.classList.add('shell-integration');
 				}
-			});
+			}));
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalView.ts:134]: This one looks like we could clean it up nicer. Right now I think those inner capability type events will keep stacking up even if we don't need them. This is only a one time thing, so we could register a `MutableDisposable` and clear it once it's done. 

Maybe using a new helper like this in terminal service?

```ts
@memoize get onAnyInstanceAddedCapabilityType() { return this._register(this.createOnInstanceEvent(e => e.capabilities.onDidAddCapabilityType)).event; }
```

Then:

```ts
const shellIntegrationDisposable = this._register(new MutableDisposable());
shellIntegrationDisposable.value = this._terminalServiceonAnyInstanceAddedCapabilityType(e => {
  if (c === TerminalCapability.CommandDetection && this._gutterDecorationsEnabled()) {
    this._parentDomElement?.classList.add('shell-integration');
    shellIntegrationDisposable.clear();
  }
});
```

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 4]
```diff
@@ -80,6 +80,7 @@ export class TerminalService extends Disposable implements ITerminalService {
 	private _shutdownWindowCount?: number;
 
 	private _editable: { instance: ITerminalInstance; data: IEditableData } | undefined;
+	private _instanceDisposeListeners: Map<ITerminalInstance, DisposableStore> = new Map();
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:83]: We want `this._register(new DisposableMap())` here so its entries get disposed when the service does.

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 5]
```diff
@@ -836,17 +838,20 @@ export class TerminalService extends Disposable implements ITerminalService {
...
+				this._saveState();
+			}
+		}));
+		instanceDisposables.add(instance.onDidFocus(this._onDidChangeActiveInstance.fire, this._onDidChangeActiveInstance));
+		instanceDisposables.add(instance.onRequestAddInstanceToGroup(async e => await this._addInstanceToGroup(instance, e)));
+		this._instanceDisposeListeners.set(instance, instanceDisposables);
+		this._register(instance.onDisposed(() => {
+			this._instanceDisposeListeners.delete(instance);
+			instanceDisposables.dispose();
+		}));
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:854]: There's still one more problem here where we need to get rid of `instance.onDisposed` when the instance goes down. `DisposableMap` was the suggestion for this, but looking at it again, I think we can do it simpler than that. We could remove `this._instanceDisposeListeners` and instead clean up the `instance.onDisposed` listener by doing something like this:

```ts
const disposeListener = this._register(instance.onDisposed(() => {
  instanceDisposables.dispose();
  this._store.delete(disposeListener);
});
```

That will delete the dispose listener for the no longer existing instance from the terminal service's `DisposableStore`.

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts [hunk 6]
```diff
@@ -166,6 +167,7 @@ export class TerminalService extends Disposable implements ITerminalService {
 	@memoize get onAnyInstanceSelectionChange() { return this._register(this.createOnInstanceEvent(e => e.onDidChangeSelection)).event; }
 	@memoize get onAnyInstanceTitleChange() { return this._register(this.createOnInstanceEvent(e => e.onTitleChanged)).event; }
 	@memoize get onAnyInstanceShellTypeChanged() { return this._register(this.createOnInstanceEvent(e => Event.map(e.onDidChangeShellType, () => e))).event; }
+	@memoize get onAnyInstanceAddedCapabilityType() { return this._register(this.createOnInstanceEvent(e => e.capabilities.onDidAddCapabilityType)).event; }
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalService.ts:170]: Did we not end up needing this one?

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts (hunk 4 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalService.ts:83]: that takes just a disposable, not an array of them

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalService.ts:83]: maybe I could create one disposable to store the array in though?

File: src/vs/workbench/contrib/terminal/browser/terminalService.ts (hunk 6 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalService.ts:170]: weird, not sure how it got removed, we definitely need it.

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalService.ts:170]: we do need that and use it here https://github.com/microsoft/vscode/pull/239742/commits/5051f7689b6061835500f7fede09a04391a68447#diff-9ad94bfccb2c181ffea0b1abb3b85b7a630784ddc3de16f47560a374da26c7ccR130

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalService.ts:169]: Oh I think I was looking at a partial diff somehow

**Review by Tyriar — APPROVED** [review]
