### PR TITLE
[fix] #27649 pin intellisense documentation widget to top

### LINKED ISSUE #27649: Suggestion list jumps between below and above position
- VSCode Version: Code - Insiders 1.13.0-insider (afe47dc84467b487ce0079ff72f55e7ef4f7ebca, 2017-05-30T10:34:18.253Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Testing #27315

It seems to be triggered by an entry with a long doc:
may-30-2017 14-39-47

### PR DESCRIPTION
**Pull request by riltsken**
Fixes: #27649

Long docs when cursor is near the bottom will jump to the top to allow for more space, but if the next suggestion docs are smaller it will jump back down creating a jarring experience when flipping through suggestions quickly. Pin the widget to the top if it flips to the top once so that the experience is more fluid.

This is just one way we might handle it. Open to suggestions as this is my first PR to VSCode.

### CODE REVIEW

File: src/vs/editor/contrib/suggest/suggestWidget.ts [hunk 1]
```diff
@@ -1024,6 +1034,16 @@ export class SuggestWidget implements IContentWidget, IListVirtualDelegate<IComp
 		const widgetX = widgetCoords.left;
 		const widgetY = widgetCoords.top;
 
+		// Fixes #27649
+		// Check if the Y changed to the top of the cursor and keep the widget flagged to prefer top
+		if (this.docsPositionPreviousWidgetY &&
+			this.docsPositionPreviousWidgetY < widgetY &&
+			!this.preferDocPositionTop) {
+			this.preferDocPositionTop = true;
+			this.adjustDocsPosition();
```
Comment (ramya-rao-a) [inline src/vs/editor/contrib/suggest/suggestWidget.ts]: Why do we need to call `this.adjustDocsPosition` again here? None of the constants declared above this `if` condition gets changed by `this.preferDocPositionTop = true`

Comment (riltsken) [reply src/vs/editor/contrib/suggest/suggestWidget.ts]: I will double check tomorrow when I have a moment, but if I remember correctly I believe it's because at this point it has now flipped back to the bottom so I am forcing it to rerender back to the top. I will verify though.

Comment (ramya-rao-a) [reply src/vs/editor/contrib/suggest/suggestWidget.ts]: In that case, why not exit after calling `adjustDocsPosition`?

ie. Replace the `this.adjustDocsPosition()` here with
```
this.docsPositionPreviousWidgetY = widgetY;
this.adjustDocsPosition();
return;
```

File: src/vs/editor/contrib/suggest/suggestWidget.ts [hunk 2]
```diff
@@ -706,6 +709,8 @@ export class SuggestWidget implements IContentWidget, IListVirtualDelegate<IComp
 	}
 
 	showSuggestions(completionModel: CompletionModel, selectionIndex: number, isFrozen: boolean, isAuto: boolean): void {
+		this.preferDocPositionTop = false;
+
```
Comment (ramya-rao-a) [inline src/vs/editor/contrib/suggest/suggestWidget.ts]: Shouldnt we reset `this.docsPositionPreviousWidgetY` here as well?

Comment (riltsken) [reply src/vs/editor/contrib/suggest/suggestWidget.ts]: Updated :)

**Review by ramya-rao-a — APPROVED** [review]
