### PR TITLE
Fix initial terminal dimensions are reload are incorrect

### LINKED ISSUE #221580: Initial terminal dimensions are reload are incorrect
Repro:

1. Open a terminal
2. Reload window
3. Select some rows in terminal, 🐛 the selection should show columns reaching to near the scroll bar

image

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes #221580

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts [hunk 1]
```diff
@@ -143,12 +143,6 @@ export class XtermTerminal extends Disposable implements IXtermTerminal, IDetach
 
 	private readonly _onDidRequestRunCommand = this._register(new Emitter<{ command: ITerminalCommand; copyAsHtml?: boolean; noNewLine?: boolean }>());
 	readonly onDidRequestRunCommand = this._onDidRequestRunCommand.event;
-	private readonly _onDidRequestFocus = this._register(new Emitter<void>());
-	readonly onDidRequestFocus = this._onDidRequestFocus.event;
-	private readonly _onDidRequestSendText = this._register(new Emitter<string>());
-	readonly onDidRequestSendText = this._onDidRequestSendText.event;
-	private readonly _onDidRequestFreePort = this._register(new Emitter<string>());
-	readonly onDidRequestFreePort = this._onDidRequestFreePort.event;
```
Comment (jeanp413) [inline src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts:151]: cleanup 🧹

Comment (pasquale95) [reply src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts:151]: Hi, is this PR going to be released in the next VSCode release?

**Review by Tyriar — APPROVED** [review]
Thanks a bunch!

**Review by lszomoru — APPROVED** [review]
