### PR TITLE
debug: auto recover from shifted tmpdirs in auto lauch

### LINKED ISSUE #1660: Debugger starts in non JavaScript Debug Terminal and crashes
image

### PR DESCRIPTION
**Pull request by connor4312**
I think this should fix https://github.com/microsoft/vscode-js-debug/issues/1660

### CODE REVIEW

File: extensions/debug-auto-launch/src/extension.ts [hunk 1]
```diff
@@ -353,7 +372,7 @@ async function getIpcAddress(context: vscode.ExtensionContext) {
 
 	const settingsValue = getJsDebugSettingKey();
 	if (cachedIpc?.jsDebugPath === jsDebugPath && cachedIpc?.settingsValue === settingsValue) {
-		return cachedIpc.ipcAddress;
+		return '/someinvalid/path.sock';
```
Comment (rzhao271) [inline extensions/debug-auto-launch/src/extension.ts:375]: Intentionally part of this change?

Comment (connor4312) [reply extensions/debug-auto-launch/src/extension.ts:375]: Oops, nope 🤦

**Review by rzhao271 — APPROVED** [review]
