### PR TITLE
Don't treat regular string SignatureInformation documentation as markdown

### LINKED ISSUE #35937: SignatureHelp documentation always being treated as markdown
Steps to Reproduce:

1. For the JavaScript:

```js
/**
 * @param {number} x ![](https://media.giphy.com/media/vFKqnCdLPNOKc/giphy.gif)
 */
function foo(x) {}

foo(
```

2. Trigger signature help on `foo` for param `x`

**Expected**
No cat. TypeScript extension passes a string as the documentation for the parameter.

**Actual**
screen shot 2017-10-09 at 3 30 29 pm

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #35937, documentation in signature information always being treated as markdown

### CODE REVIEW

File: src/vs/workbench/api/node/extHostTypeConverters.ts [hunk 1]
```diff
@@ -405,11 +405,19 @@ export namespace Suggest {
...
 };
 
+
+function convertSignatureDocumentation(documentation: string | types.MarkdownString): undefined | string | htmlContent.IMarkdownString {
+	if (!documentation) {
+		return undefined;
+	}
+	return typeof documentation === 'string' ? documentation : MarkdownString.from(documentation);
+}
+
```
Comment (jrieken) [inline src/vs/workbench/api/node/extHostTypeConverters.ts]: lgtm but should be moved into the `MarkdownString` namespace with a better name, like `fromStrict` signaling that is just strings or the MarkdownString, not the MarkedString. Or rename the `from` function to something like `fromOldOrNew`

**Review by jrieken — CHANGES_REQUESTED** [review]

**Comment by mjbvz** [comment]
@jrieken  Can you please take another look at this pr

**Comment by jrieken** [comment]
lgtm

**Review by jrieken — APPROVED** [review]
