### PR TITLE
Changing the maximum width of hover

### LINKED ISSUE #186334: Color picker stuck with wrong max size
* open a file with color values (testing https://github.com/microsoft/vscode/issues/182697, https://github.com/microsoft/vscode/issues/181597)
* split the editor pane, have the setting UI on the RHS
* resize a color picker hover
* :bug: it gets stuck to a wrong max width
* this seems not to happen having a text editor to its side

https://github.com/microsoft/vscode/assets/1794099/0a8dd1c1-e393-4a53-af2a-01300ef8cb40

### PR DESCRIPTION
**Pull request by aiday-mar**
Fixes: https://github.com/microsoft/vscode/issues/186334

Make the maximum rendering width larger, not limited to the editor but to the whole window in order not to run into the problem

https://github.com/microsoft/vscode/assets/61460952/9d996986-9e33-4d6d-a760-3c594c8e89db

### CODE REVIEW

File: src/vs/editor/contrib/hover/browser/contentHover.ts [hunk 1]
```diff
@@ -618,10 +618,11 @@ export class ContentHoverWidget extends ResizableContentWidget {
...
 		}
-		const editorBox = dom.getDomNodePagePosition(this._editor.getDomNode());
-		const glyphMarginWidth = this._editor.getLayoutInfo().glyphMarginWidth;
-		const leftOfContainer = this._hover.containerDomNode.offsetLeft;
-		return editorBox.width + editorBox.left - leftOfContainer - glyphMarginWidth;
+		const editorLayoutInfo = this._editor.getLayoutInfo();
+		const glyphMarginRight = editorLayoutInfo.glyphMarginLeft + editorLayoutInfo.glyphMarginWidth;
+		const cursorPosition = this._editor._getViewModel().getPrimaryCursorState().viewState.position;
+		const bodyBoxWidth = dom.getClientArea(document.body).width;
+		return bodyBoxWidth - glyphMarginRight - this._editor.getOffsetForColumn(cursorPosition.lineNumber, cursorPosition.column);
```
Comment (jrieken) [inline src/vs/editor/contrib/hover/browser/contentHover.ts:625]: Works much better and is much less code 👏 Tho, now that I see and against my advise I wonder if we should ignore the cursor position all together. Because you are now penalised for being a split editor on the RHS or being far indented. Maybe we allow the width to be the whole body-width minus the usual paddings. The suggest widget (contrary to its details widget) is that here: 

https://github.com/microsoft/vscode/blob/0a6b7a310347de787da1034038442802f3ac0194/src/vs/editor/contrib/suggest/browser/suggestWidget.ts#L785

Comment (aiday-mar) [reply src/vs/editor/contrib/hover/browser/contentHover.ts:625]: I'll change it to the width you specified

**Review by jrieken — APPROVED** [review]
