### PR TITLE
fix task reconnection issues

### LINKED ISSUE #155163: Default build task gets wrongly launched again, after reconnecting
1. Hit `Ctrl Shift B` to start the default build

🐛

image

---

This happened right after something strange, which might be the underlying cause. I had the build running already, the one with two terminals open. But I still pressed `Ctrl Shift B` and noticed another two terminals showed up with the same build tasks! I closed them all. Then I pressed `Ctrl Shift B` and ended up where the screenshot above shows.

cc @alexr00 @Tyriar

### LINKED ISSUE #155246: task statuses don't update after reload
https://github.com/microsoft/vscode/pull/155120#issue-1304051562

### LINKED ISSUE #156284: Restored tasks do not show in status bar
I do not see the build task decoration in status bar after restart or reload:

image

### LINKED ISSUE #156292: Task's don't reconnect when `task.quickOpen.history` is 0
Testing #155349

1. Set `"task.quickOpen.history": 0`.
2. Run a watch task, like the VS Code build task.
3. Reload.
4. The tasks show in the terminal, but they don't have problem matchers.

### LINKED ISSUE #156294: Problem matcher is not added to reconnected VS Code build task
Testing #155349

1. Open selfhost setup
2. Run the VS Code - Build task
3. Also run the Web Ext - Build task
4. Reload
5. A problem matcher is used for Web Ext Build, but no the Core - Build and Ext - Build tasks, which you can see because the Web Ext - Build task has a spinner and the other 2 do not. In fact, since there's only a "1" next to the tools icon in the status bar, it looks like the Core - Build and Ext - Build tasks are not reconnected at all.

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #155163 
fixes #156294
fixes #155246
fixes #156292
fixes #156284

### CODE REVIEW

**Review by mjbvz — APPROVED** [review]

**Comment by meganrogge** [comment]
It was working for me on macOS but isn't working for me on Windows 🤔

**Comment by meganrogge** [comment]
works on Mac but not windows for me atm 🤔 
https://user-images.githubusercontent.com/29464607/182229352-61ac35cf-6eef-4061-8877-4bb4369d24bc.mov

**Review by alexr00 — APPROVED** [review]
Windows issues aside, this looks like a good approach!

File: src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts [hunk 1]
```diff
@@ -54,7 +54,20 @@ let SerializeAddon: typeof SerializeAddonType;
...
+			return this._bufferLines;
+		}
+		for (let i = this._bufferLines.length; i < this.raw.buffer.active.length; i++) {
+			const line = this.raw.buffer.active.getLine(i)?.translateToString();
+			if (line) {
+				this._bufferLines.push(line);
+			}
+		}
+		return this._bufferLines;
+	}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts:70]: This is quite expensive, could a reverse iterator be used instead that searches for the begins pattern?

File: src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts [hunk 2]
```diff
@@ -54,7 +54,20 @@ let SerializeAddon: typeof SerializeAddonType;
 export class XtermTerminal extends DisposableStore implements IXtermTerminal, IInternalXtermTerminal {
 	/** The raw xterm.js instance */
 	readonly raw: RawXtermTerminal;
+	private _bufferLines: string[] = [];
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts:57]: I don't think we want to cache this, otherwise the memory will be held. If we do want to cache line strings, I remember thinking we could do it within xterm.js so that the search addon could benefit as well.

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts:57]: created an issue and now since we'll be checking in reverse order I don't think caching is necessary
