### PR TITLE
fix: Remove extra whitespace in the untitled editor label

### LINKED ISSUE #107979: Remove extra whitespace from labels for unsaved tabs
# Feature suggestion
When VS Code generates a faux "filename" to appear in the tab of a new, unsaved file, I suggest that it would save screen space and eliminate some visual noise if all repeating whitespace characters were collapsed to single spaces.

# Example
A new tab is opened and a chunk of logged text with this first line is pasted in:
`error      13:47:38.285446-0500      cfprefsd      rejecting write of key(s) kFMFDStoredDataKey`

Currently, since the tab doesn't yet have a file name, VS Code labels it like this:
**error      13:47:38.285446-0500      cfprefsd      reje**

I'm suggesting that runs of whitespace _(tabs and spaces, at least)_ be collapsed to single spaces, making it instead like this:
**error 13:47:38.285446-0500 cfprefsd reje**

It's easier on the eye and takes less screen real estate without losing _(what I see as)_ actionable information. Thanks for considering!

### PR DESCRIPTION
**Pull request by mixj93**
This PR fixes #107979

Normalize multiple whitespaces to a single whitespace for the untitled editor label:

Before:
107979-before

After:
107979-after

### CODE REVIEW

**Comment by mixj93** [comment]
Some Updates:

- Add logic in case `cachedModelFirstLineWords` is undefined
- Change regex `/\s{2,}/` to `/\s+/` because it's reasonable to replace tab or form feed to one whitespace.

**Comment by mixj93** [comment]
Is there any issue happened in pipline of test? It seems like it cannot process normally. @bpasero

image

File: src/vs/workbench/services/untitled/common/untitledTextEditorModel.ts [hunk 1]
```diff
@@ -93,7 +93,9 @@ export class UntitledTextEditorModel extends BaseTextEditorModel implements IUnt
 		// we have no associated file path. In that case we
 		// prefer the file name as title.
 		if (this.configuredLabelFormat === 'content' && !this.hasAssociatedFilePath && this.cachedModelFirstLineWords) {
-			return this.cachedModelFirstLineWords;
+			// Normalize multiple whitespaces to a single whitespace for the untitled editor label
+			const normalizedFirstLineWords = this.cachedModelFirstLineWords ? this.cachedModelFirstLineWords.replace(/\s+/g, ' ') : '';
```
Comment (bpasero) [inline src/vs/workbench/services/untitled/common/untitledTextEditorModel.ts:97]: Why is this not done at the point where we cache the name?

https://github.com/microsoft/vscode/blob/50d9f05334aee7bbc416f675cceccd9a174de8c7/src/vs/workbench/services/untitled/common/untitledTextEditorModel.ts#L369-L372

**Review by bpasero — CHANGES_REQUESTED** [review]

File: src/vs/workbench/services/untitled/common/untitledTextEditorModel.ts (hunk 1 above)
Comment (mixj93) [reply src/vs/workbench/services/untitled/common/untitledTextEditorModel.ts]: Update: Normalized when cached the first line words.

File: src/vs/workbench/services/untitled/common/untitledTextEditorModel.ts [hunk 2]
```diff
@@ -365,7 +365,8 @@ export class UntitledTextEditorModel extends BaseTextEditorModel implements IUnt
 		}
 
 		if (modelFirstWordsCandidate !== this.cachedModelFirstLineWords) {
-			this.cachedModelFirstLineWords = modelFirstWordsCandidate;
+			// Normalize multiple whitespaces to a single whitespace for the untitled editor label
+			this.cachedModelFirstLineWords = modelFirstWordsCandidate ? modelFirstWordsCandidate.replace(/\s+/g, ' ') : '';
```
Comment (bpasero) [inline src/vs/workbench/services/untitled/common/untitledTextEditorModel.ts:369]: I would put this after the `.trim()` call here:

https://github.com/microsoft/vscode/blob/50d9f05334aee7bbc416f675cceccd9a174de8c7/src/vs/workbench/services/untitled/common/untitledTextEditorModel.ts#L362-L362

Because then we do a good check `modelFirstWordsCandidate !== this.cachedModelFirstLineWords`

Thanks!

**Review by bpasero — CHANGES_REQUESTED** [review]

File: src/vs/workbench/services/untitled/common/untitledTextEditorModel.ts (hunk 2 above)
Comment (mixj93) [reply src/vs/workbench/services/untitled/common/untitledTextEditorModel.ts]: Update: remove extra spaces after trim first line text.

**Comment by bpasero** [comment]
Thanks!
