### PR TITLE
fix: set dns result order to ipv4first for cli connections

### LINKED ISSUE #264136: CLI hangs indefinitely when updating extensions on IPv6 Network
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.103.2
- OS Version: Windows 10 22H2

Steps to Reproduce:

1. have a working IPv6 connection
2. run `code --update-extensions` with at least one extension out of date

From what I can tell, on the CDN side this is the same issue as in winget (https://github.com/microsoft/winget-cli/issues/5693). Both `cdn.winget.microsoft.com` and `main.vscode-cdn.net` use the same CDN (`star-azurefd-prod.trafficmanager.net`).

In the VS Code UI, there seems to be a timeout and automatic fallback to IPv4, but the same is not happening with the CLI. It just hangs when trying to get `https://main.vscode-cdn.net/extensions/marketplace.json`.

On the CDN side, an incident should already be opened. But it would probably be good to have the same fallback logic in the CLI as exists in the UI.

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes https://github.com/microsoft/vscode/issues/264136

### CODE REVIEW

File: src/vs/code/node/cliProcessMain.ts [hunk 1]
```diff
@@ -109,6 +110,10 @@ class CliMain extends Disposable {
 			// Error handler
 			this.registerErrorHandler(logService);
 
+			// DNS result order
+			// Refs https://github.com/microsoft/vscode/issues/264136
+			setDefaultResultOrder('ipv4first');
```
Comment (bpasero) [inline src/vs/code/node/cliProcessMain.ts:115]: Why are we setting this only in the CLI and not for all startups of VS Code?

**Review by bpasero — CHANGES_REQUESTED** [review]

**Review by bpasero — APPROVED** [review]
