### PR TITLE
Use Inline Completions To Preselect Item In Autocomplete

### LINKED ISSUE #131940: If Intellicode Whole Line Completions are displayed, the suggestions widget does not open
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.19043
- List of extensions that you have installed: Visual Studio IntelliCode Completions

Steps to Reproduce:

1. Open the attached .txt file, convert it to a typescript .ts file 
[main.txt](https://github.com/microsoft/vscode/files/7079987/main.txt)

2. In line 5, type `s=` and you should see a gray text IntelliCode completion. 
3. When you type what the completion shows, and get to typing a dot, ".".
4. When you type a ".", it is expected you see the suggestions widget. But the suggestions widget does not show up in the presence of gray text completion. 
5. GIF - completionsDrivenBug2

### PR DESCRIPTION
**Pull request by hediet**
The suggest widget is not being stopped from automatically opening anymore if suggest preview is enabled. Instead, the first inline suggestion is used to preselect an item in the suggest widget.

This PR fixes #131940.

### CODE REVIEW

File: src/vs/editor/contrib/inlineCompletions/inlineCompletionsModel.ts [hunk 1]
```diff
@@ -581,3 +581,40 @@ export async function provideInlineCompletions(
...
+	return i;
+}
+
+function lengthOfLongestCommonSuffix(str1: string, str2: string): number {
+	let i = 0;
+	while (i < str1.length && i < str2.length && str1[str1.length - i - 1] === str2[str2.length - i - 1]) {
+		i++;
+	}
+	return i;
+}
```
Comment (jrieken) [inline src/vs/editor/contrib/inlineCompletions/inlineCompletionsModel.ts:599]: Duplicates `commonPrefixLength` and `commonSuffixLength` of `strings.ts`?

File: src/vs/editor/contrib/suggest/suggestController.ts [hunk 2]
```diff
@@ -223,7 +224,18 @@ export class SuggestController implements IEditorContribution {
 		}));
 		this._toDispose.add(this.model.onDidSuggest(e => {
 			if (!e.shy) {
-				let index = this._memoryService.select(this.editor.getModel()!, this.editor.getPosition()!, e.completionModel.items);
+				let index = -1;
+				// Highest priority first
+				const selectors = [...this._selectors].sort((s1, s2) => s2.priority - s1.priority);
```
Comment (jrieken) [inline src/vs/editor/contrib/suggest/suggestController.ts:229]: Maybe keep `_selector` always sorted so that you don't need to create and sort a new array each time suggest happens. I'd say it is favorable to pay the price in `registerSelector`

File: src/vs/editor/contrib/suggest/suggestModel.ts [hunk 3]
```diff
@@ -97,17 +97,25 @@ export const enum State {
 	Auto = 2
 }
 
-function shouldPreventQuickSuggest(contextKeyService: IContextKeyService, configurationService: IConfigurationService): boolean {
+function getDefault<T>(value: T | undefined, defaultValue: T): T {
+	return value === undefined ? defaultValue : value;
+}
```
Comment (jrieken) [inline src/vs/editor/contrib/suggest/suggestModel.ts:102]: There is the new `??` operator for these kind of util functions...

**Review by jrieken — COMMENTED** [review]
some nit

File: src/vs/editor/contrib/suggest/suggestModel.ts (hunk 3 above)
Comment (hediet) [reply src/vs/editor/contrib/suggest/suggestModel.ts:102]: Ah, good to know. Usually, I try to avoid such operators, as I'm always unsure how it handles `0` and `false`. I guess that's exactly the difference between `??` and `||` though.

Comment (jrieken) [reply src/vs/editor/contrib/suggest/suggestModel.ts:102]: Yeah, that's why `??` was added: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

**Review by jrieken — APPROVED** [review]
