### PR TITLE
Link detection for the exception widget and debug console

### LINKED ISSUE #15760: DEbug console link detection
- VSCode Version: Version 1.7.1 (1.7.1)
- OS Version: Mac os X 10,11,4

Steps to Reproduce:

1. Run mocha tests with configuration like that :
```
        {
            "name": "MesTests",
            "type": "node",
            "sourceMaps": true,
            "request": "launch",
            "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
            "stopOnEntry": false,
            "env": {
                "NODE_ENV": "unit_test",
                "MONGO_URI":"cedric:cedric01@localhost:27017/unitTests?authSource=add_gen",
                "DEBUG":"tests,renderer"
            },
            "cwd": "${workspaceRoot}/",
            "runtimeExecutable": null,
            "args": ["test/register.js"],
            "outDir": null
        },
```
2.  Debug output on error is like this :

```
     Uncaught TypeError: postInstance.setValue is not a function
      at model.newPostInstance (schemas/**customerSchema.ts:1870:22**)
      at schemas**/customerSchema.ts:1915:26**
      at tryCatcher (node_modules/**bluebird/js/release/util.js:16:23**)
```

I have put between **  the underlined lines, the first part is not. Result is it is not possible to click on the links. Maybe a bad setting on my side, but i was unable to find how to change that issue, all the first subdirectories of my project are not underlined, means not integrated in the link.

### PR DESCRIPTION
**Pull request by michelkaporin**
1. Extracted link detection to a separate common class, shared and reused between REPL viewer and exception widget. 
2. Updated link detection to handle multiple links in a provided string.
3. Added link validation to resolve only files which are part of file system.

Partially reused regex of the reverted PR by @felixfbecker, credits to you!

image
image

Fixes #15760, #17085 (and all its ancestors).
Partially implements #21349.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Awesome! Did you test this with stack traces printed by mocha?

**Comment by michelkaporin** [comment]
@felixfbecker Thank you :) I did not explicitly test mocha but those mocha stack traces described in #15760 should be picked up now (see the the sample image above which is a super set of what was outputted there).

The things that won't work currently:
1. If file is coming from <node internals> or does not exist on file system, it won't be anchored.
2. http:// links still not supported.
3. If the path to the file defined without the column, it won't be recognised.

I plan to tackle those things in a separate issues.

**Comment by felixfbecker** [comment]
I don't see this explicitely in the image above, will it work for relative paths that do not take up a whole line? Eg
```
  at myfunc (src/myfunc.ts:1:0)
```
right now that only highlights `/myfunc.ts:1:0` like it was an absolute path

**Comment by michelkaporin** [comment]
@felixfbecker yes, it will work for relative paths that do not take up a whole line. `src/myfunc.ts:1:0` would be highlighted in your example. 

image

**Comment by isidorn** [comment]
@michelkaporin I appologize for the slow response was busy around the release.

Just checked the PR, looks great!
I really like that you are reusing the logic between the repl and the `exceptionWidget`.

After discussing with @bpasero we agreed that doing a FS stat to figure out if something is a relative link is too heavy for a simple operation like this.

How precise would the relative path mathching be if you can not verify it against the real file system? If not very precise then we should not support relative file matching.
But all in all we need to drop the dependency to `'fs'` in the `linkDetector`

**Comment by felixfbecker** [comment]
I think it should be doable to detect relative links without a stat. If spaces in paths are not to be supported, it's trivial. Otherwise you would need to have to look at common seperators like parenthesis. But please please keep relative link detection, I need to click on these >100 times a day in stack traces.

**Comment by michelkaporin** [comment]
@isidorn Ok, I can drop link validation and try to match it with regex then. 
However, current terminal implementation is also doing `fs.stat` to validate the links in the terminal. If we plan to reuse link detection code between terminal, debug console and exception widget, then we will have to drop `fs.stat` for terminal as well.

**Comment by isidorn** [comment]
Thanks for letting me know, we should also not use `fs.stat` for link detection in the terminal.
fyi @Tyriar

**Comment by Tyriar** [comment]
@michelkaporin @isidorn @bpasero I disagree that we shouldn't stat the files. Without `fs.stat` there are a heap of false positives. A lot of stuff in the terminal is formed like a path, especially if we want to linkify files in the output of `ls`. Note that the terminal does not linkify all output, it happens 200ms after the viewport has not changed, so it will stat as many links that are matched in the viewport (typically 10-20 lines) at most every 200ms.

Related:

- "Link validation" introduced in 1.11 (ie. stat the paths) https://code.visualstudio.com/updates/v1_11#_link-improvements, it was pretty bad before this was added imo.
- I brought up the concern when linkifying `ls` output and suggested we opt for `readdir` there instead. https://github.com/Microsoft/vscode/issues/22772#issuecomment-293625442
- xterm.js link impl https://github.com/sourcelair/xterm.js/blob/master/src/Linkifier.ts

**Comment by bpasero** [comment]
Stating things we "think" are links is crazy to put it in simple words. Since output is unbounded this could easily cause millions of disk access for no helpful reason. A link should be detected without going to disk and it is totally fine to have false positives (e.g. it is OK to not be 100% correct). Once the user clicks on a link, it is fine to show an error if the file does not exist.

**Comment by Tyriar** [comment]
@bpasero to be more specific the terminal stuff [is using `pfs`](https://github.com/Microsoft/vscode/blob/44e6c6dcfcd72f291be00f42d20a8f4fd7c69121/src/vs/workbench/parts/terminal/electron-browser/terminalLinkHandler.ts#L192) so it's not a blocking call or anything. Also for the terminal it *is* bounded as only the current viewport is checked for links.

Is it so bad to check the existence of a handful of paths after a terminal command is run (or when the user scrolls the terminal)?

**Comment by bpasero** [comment]
I would not do it, the output panel has never done it. There are tons of regexes that try to detect links and render them optimistically. What is wrong with that approach?

**Comment by Tyriar** [comment]
Tracking stat in terminal links in https://github.com/Microsoft/vscode/issues/25024

**Comment by michelkaporin** [comment]
@isidorn I have updated regex to be more precise without `fs.stat` validation. We get higher false positive rate now without it, although it is more efficient. 

Exception widget is an example of high false positive rate with file names coming from debug adapter, that are detected by regex as workspace' relative links, whereas they are not, in reality. On the good side the user will get an 'Unable to open' message, when clicking on such links.

File: src/vs/workbench/parts/debug/browser/linkDetector.ts [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+
+export class LinkDetector {
+	private static FILE_LOCATION_PATTERNS: RegExp[] = [
+		// group 0: the full thing :)
+		// group 1: absolute path
+		// group 2: drive letter on windows with trailing backslash or leading slash on mac/linux
+		// group 3: line number
+		// group 4: column number
+		// eg: at Context.<anonymous> (c:\Users\someone\Desktop\mocha-runner\test\test.js:26:11)
+		/(?![\(])(?:file:\/\/)?((?:([a-zA-Z]+:)|[^\(\)<>\'\"\[\]:\s]+)(?:[\\/][^\(\)<>\'\"\[\]:]*)?\.[a-zA-Z]+[0-9]*):(\d+)(?::(\d+))?/g
```
Comment (isidorn) [inline src/vs/workbench/parts/debug/browser/linkDetector.ts]: I notice that the comments are the same but the regex is now more complicated.
Could you please add some comments in code to clarify this regex beast

File: src/vs/workbench/parts/debug/browser/linkDetector.ts [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+	];
+
+	constructor(
+		@IWorkbenchEditorService private editorService: IWorkbenchEditorService,
+		@IWorkspaceContextService private contextService: IWorkspaceContextService
+	) {
+		// noop
+	}
+
+	public handleLinks(text: string): HTMLElement | string {
```
Comment (isidorn) [inline src/vs/workbench/parts/debug/browser/linkDetector.ts]: As far as I understand there have been no changes till the end of this file, it has just been moved over.
If that is the case it looks good to me

File: src/vs/workbench/parts/debug/browser/linkDetector.ts [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+		/(?![\(])(?:file:\/\/)?((?:([a-zA-Z]+:)|[^\(\)<>\'\"\[\]:\s]+)(?:[\\/][^\(\)<>\'\"\[\]:]*)?\.[a-zA-Z]+[0-9]*):(\d+)(?::(\d+))?/g
+	];
+
+	constructor(
+		@IWorkbenchEditorService private editorService: IWorkbenchEditorService,
+		@IWorkspaceContextService private contextService: IWorkspaceContextService
+	) {
+		// noop
+	}
+
```
Comment (isidorn) [inline src/vs/workbench/parts/debug/browser/linkDetector.ts]: Since this handleLinks is now a public method we could try to make the API a bit nicer, a personally find it ugly that it returns an HTMLElement or a string. What does that mean?
At least provide some comments to clarify each case, or try to always return an object with the corresponding fields.

File: src/vs/workbench/parts/debug/browser/media/exceptionWidget.css [hunk 4]
```diff
@@ -27,6 +27,11 @@
 	margin-top: 0.5em;
 }
```
Comment (isidorn) [inline src/vs/workbench/parts/debug/browser/media/exceptionWidget.css]: Makes sense

File: src/vs/workbench/parts/debug/electron-browser/replViewer.ts [hunk 5]
```diff
@@ -7,13 +7,10 @@ import * as nls from 'vs/nls';
 import { TPromise } from 'vs/base/common/winjs.base';
```
Comment (isidorn) [inline src/vs/workbench/parts/debug/electron-browser/replViewer.ts]: Looks good overall and I like we removed code from this class.

I only have the issue that you are creating a `linkDetector` at every iteration in a loop. Would it not make sense just to create one global one for the replViewer and always to reuse it?

File: src/vs/workbench/parts/debug/browser/exceptionWidget.ts [hunk 6]
```diff
@@ -11,9 +11,11 @@ import { ICodeEditor } from 'vs/editor/browser/editorBrowser';
 import { IContextViewService } from 'vs/platform/contextview/browser/contextView';
```
Comment (isidorn) [inline src/vs/workbench/parts/debug/browser/exceptionWidget.ts]: looks good

**Comment by isidorn** [comment]
@michelkaporin great work. I have added some comments directly in the code. Once you adrress them we can merge it in.
I see that the builds are failing, is everything ok when you build it localy?

File: src/vs/workbench/parts/debug/browser/linkDetector.ts (hunk 2 above)
Comment (michelkaporin) [inline src/vs/workbench/parts/debug/browser/linkDetector.ts]: It was changed to handle multiple links in the provided string. Previously it used to detect only first link match and then stopped.

File: src/vs/workbench/parts/debug/browser/linkDetector.ts (hunk 3 above)
Comment (michelkaporin) [inline src/vs/workbench/parts/debug/browser/linkDetector.ts]: I've added the comment to it. I hope this explains it well. 

If you have any suggestions on what should be a return result instead, I am happy to hear. Currently it perfectly suits exception widget and debug console needs.

File: src/vs/workbench/parts/debug/electron-browser/replViewer.ts (hunk 5 above)
Comment (michelkaporin) [inline src/vs/workbench/parts/debug/electron-browser/replViewer.ts]: @isidorn You're right, did not see that for-loop when refactored. I've moved LinkDetector instantiation  to the constructor.

File: src/vs/workbench/parts/debug/browser/linkDetector.ts (hunk 1 above)
Comment (michelkaporin) [inline src/vs/workbench/parts/debug/browser/linkDetector.ts]: @isidorn I've added more comments, hope it makes things more clear. It is quite big just because it tries **not** to match lots of special characters. In the end we still plan to move away from it to the common regex between terminal, debug console and exception widget.

**Comment by michelkaporin** [comment]
@isidorn thank you! I've addressed all your comments, please see my replies. The build is passing locally, AppVeyour succeeds also on the latest codebase. Cannot find any build issues in the Travis log that are to do with my changes.

**Comment by isidorn** [comment]
@michelkaporin looks good, let's merge it in to see how it behaves :)
