### PR TITLE
Change img hrefs in markdown from file to vscode-file

### LINKED ISSUE #136027: With `md.supportHtml = true`, an img tag on the markdown document cannot load the URI of a local resource
Version: 1.62.0-insider (Universal)
Commit: f961b92f0faec5c68124ab4d89922d38cf6f513d
Date: 2021-10-28T05:14:00.367Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

Setting `md.supportHtml = true`, on the markdown document of a completion item, an `img` tag cannot load a PNG file if the path given as a URI with `vscode.Uri.file`. If the path given as the path of a local filesystem, it can load the file.

Steps to Reproduce:

1. Execute https://github.com/tamuratak/vscode-extension-samples/tree/supporthtml_img_local/completions-sample
2. Execute `Trigger Suggest`
3. Only one of images cannot be loaded.

スクリーンショット 2021-10-28 20 51 23

```ts
import * as vscode from 'vscode';
import * as path from 'path';

export function activate(context: vscode.ExtensionContext) {

	const provider1 = vscode.languages.registerCompletionItemProvider('plaintext', {

		provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext) {

			const pngPath = path.join(__dirname, '..', 'a.png')
			const pngPathUriString = vscode.Uri.file(pngPath).toString()

			const snippetCompletion = new vscode.CompletionItem('Good part of the day');
			snippetCompletion.insertText = new vscode.SnippetString('Good ${1|morning,afternoon,evening|}. It is ${1}, right?');
			const md = new vscode.MarkdownString(`1 <img src="${pngPathUriString}"> 2 <img src="${pngPath}"> 3 ![a](${pngPathUriString}) 4 ![a](${pngPath})`);
			md.supportHtml = true
			snippetCompletion.documentation = md

			// return all completion items as array
			return [
				snippetCompletion
			];
		}
	});
	context.subscriptions.push(provider1);
}
```

### PR DESCRIPTION
**Pull request by RyanAfrish7**
In markdown renderer, hrefs of images in html are transformed from `file:` to `vscode-file:` protocol.

This PR fixes #136027

### CODE REVIEW

File: src/vs/base/browser/markdownRenderer.ts [hunk 1]
```diff
@@ -100,6 +100,22 @@ export function renderMarkdown(markdown: IMarkdownString, options: MarkdownRende
 	const withInnerHTML = new Promise<void>(c => signalInnerHTML = c);
 
 	const renderer = new marked.Renderer();
+
+	const htmlParser = new DOMParser();
+	renderer.html = (rawHtml: string) => {
```
Comment (mjbvz) [inline src/vs/base/browser/markdownRenderer.ts:105]: This seems to break markdown text such as: `text <b>bold</b>` as it gets rendered as:

```html
<p>text <b></b>bold</p>
```

Instead, I think you should move this logic after the full md has been rendered but before sanitization:

https://github.com/microsoft/vscode/blob/d209aa2b02f6cc99f3c985b23c99eb2346f9dbdb/src/vs/base/browser/markdownRenderer.ts#L260-L261

**Review by mjbvz — CHANGES_REQUESTED** [review]
Besides the comment:

1. Let's see if we can remove the other call to `_href` so that all images are handled in a consistent way
2. Make sure to add some test cases for this new logic.  Here's the test file: https://github.com/microsoft/vscode/blob/1eaf52cfd50c05b93e73eb6e96046c23257018ad/src/vs/base/test/browser/markdownRenderer.test.ts#L23

**Comment by mjbvz** [comment]
Thanks! Should be in the next insiders build and is scheduled to go out with VS Code 1.63
