### PR TITLE
Fixes output filter field icon cannot be tabbed to, only shift-tabbed

### LINKED ISSUE #117354: Output filter field icon cannot be tabbed to, only shift-tabbed
Testing #116559

recording (1)

### PR DESCRIPTION
**Pull request by jeanp413**
This PR fixes #117354

### CODE REVIEW

File: src/vs/base/browser/ui/actionbar/actionbar.ts [hunk 1]
```diff
@@ -428,6 +428,8 @@ export class ActionBar extends Disposable implements IActionRunner {
 	protected focusNext(): boolean {
 		if (typeof this.focusedItem === 'undefined') {
 			this.focusedItem = this.viewItems.length - 1;
+		} else if (this.viewItems.length <= 1) {
```
Comment (isidorn) [inline src/vs/base/browser/ui/actionbar/actionbar.ts:431]: I do not like this line, since `ActionBar` has a `preventLoopNavigation` flag. So by default we allow loop navigation. When you are on the last one and press next -> first one is focused

File: src/vs/base/browser/ui/actionbar/actionbar.ts [hunk 2]
```diff
@@ -450,6 +452,8 @@ export class ActionBar extends Disposable implements IActionRunner {
 	protected focusPrevious(): boolean {
 		if (typeof this.focusedItem === 'undefined') {
 			this.focusedItem = 0;
+		} else if (this.viewItems.length <= 1) {
```
Comment (isidorn) [inline src/vs/base/browser/ui/actionbar/actionbar.ts:455]: Same as my comment in `focusNext()`

**Review by isidorn — CHANGES_REQUESTED** [review]

**Comment by isidorn** [comment]
@jeanp413 thanks for the PR. Good changes. I have comment in the PR with some things that potentially need to be changed. Let me know what you think.

File: src/vs/base/browser/ui/actionbar/actionbar.ts (hunk 1 above)
Comment (jeanp413) [reply src/vs/base/browser/ui/actionbar/actionbar.ts:431]: Yeah but this is for the case when actionbar has only one action and is already focused, so pressing next won't change the focused action.
This also prevents an infinite loop in the while loop below `while (this.focusedItem !== startIndex ...`

**Review by isidorn — APPROVED** [review]

**Comment by isidorn** [comment]
Thanks, looks good, merging in.
