### PR TITLE
don't add telemetry for feature terminals etc

### LINKED ISSUE #150194: Shell integration failed warning when tasks are run
We should make sure not telemetry gets sent in this case as task (and debug) terminals are special in that they never inject shell integration.

image

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #150194

### CODE REVIEW

File: src/vs/platform/terminal/node/ptyService.ts [hunk 1]
```diff
@@ -502,6 +502,7 @@ export class PersistentTerminalProcess extends Disposable {
 			reconnectConstants.scrollback,
 			unicodeVersion,
 			reviveBuffer,
+			this._terminalProcess.shellLaunchConfig.isFeatureTerminal || this._terminalProcess.shellLaunchConfig.hideFromUser || !this._terminalProcess.shellLaunchConfig.executable,
```
Comment (Tyriar) [inline src/vs/platform/terminal/node/ptyService.ts:505]: Instead of duplicating this can we remember whether an injection happened and use that?

https://github.com/microsoft/vscode/blob/331fa9017a7d7d2370d7fc628f66bdfb61363da8/src/vs/platform/terminal/node/terminalProcess.ts#L203

There might be a nicer way but that could be a property like `TerminalProcess.shellIntegrationInjectionAttempted`. Communicating that back to the renderer to reduce this further would be ideal.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/platform/terminal/node/ptyService.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/platform/terminal/node/ptyService.ts:505]: but yes could add an event that fires just the info above

Comment (meganrogge) [reply src/vs/platform/terminal/node/ptyService.ts:505]: we already have this essentially, but will also want to do this when it's disabled https://github.com/microsoft/vscode/blob/331fa9017a7d7d2370d7fc628f66bdfb61363da8/src/vs/platform/terminal/node/terminalProcess.ts#L218

File: src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts [hunk 2]
```diff
@@ -128,6 +128,7 @@ export class ShellIntegrationAddon extends Disposable implements IShellIntegrati
 	private _activationTimeout: any;
 
 	constructor(
+		_disableTelemetry: boolean | undefined,
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts:131]: No longer used

File: src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts [hunk 3]
```diff
@@ -138,7 +139,6 @@ export class ShellIntegrationAddon extends Disposable implements IShellIntegrati
 		this._terminal = xterm;
 		this.capabilities.add(TerminalCapability.PartialCommandDetection, new PartialCommandDetectionCapability(this._terminal));
 		this._register(xterm.parser.registerOscHandler(ShellIntegrationOscPs.VSCode, data => this._handleVSCodeSequence(data)));
-		this._ensureCapabilitiesOrAddFailureTelemetry();
```
Comment (Tyriar) [inline src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts:141]: We still want this when _telemetryService is set?

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts (hunk 2 above)
Comment (meganrogge) [reply src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts:131]: doesn't work when I remove it

File: src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts (hunk 3 above)
Comment (meganrogge) [reply src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts:141]: this is the addon used by the pty service, so it'll never be set here

File: src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts (hunk 2 above)
Comment (meganrogge) [reply src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts:131]: bc is needed for the renderer

File: src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts (hunk 3 above)
Comment (meganrogge) [reply src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts:141]: was confused - thought there were two

File: src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts (hunk 2 above)
Comment (Tyriar) [reply src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts:131]: The variable is never used though, we use `!this._telemetryService` to disable now

File: src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts [hunk 4]
```diff
@@ -99,6 +99,7 @@ export class XtermTerminal extends DisposableStore implements IXtermTerminal {
 		rows: number,
 		location: TerminalLocation,
 		private readonly _capabilities: ITerminalCapabilityStore,
+		disableShellIntegrationTelemetry: boolean | undefined,
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts:102]: This and the terminalInstance/ptyService changes can be removed as well I believe.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts (hunk 4 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts:102]: we only want to do this for the renderer side under certain conditions, so that's still needed

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts:102]: so we'll only do this when there's a telemetry service (renderer) and it's a feature terminal, has no executable or is hide from user

File: src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts (hunk 2 above)
Comment (meganrogge) [reply src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts]: yeah it should've been used. pushed

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 5]
```diff
@@ -657,7 +657,7 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 			throw new ErrorNoTelemetry('Terminal disposed of during xterm.js creation');
 		}
 
-		const xterm = this._instantiationService.createInstance(XtermTerminal, Terminal, this._configHelper, this._cols, this._rows, this.target || TerminalLocation.Panel, this.capabilities);
+		const xterm = this._instantiationService.createInstance(XtermTerminal, Terminal, this._configHelper, this._cols, this._rows, this.target || TerminalLocation.Panel, this.capabilities, this.shellLaunchConfig.isFeatureTerminal || this.shellLaunchConfig.hideFromUser || this.shellLaunchConfig.executable === undefined);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:660]:
```suggestion
		const disableShellIntegrationTelemetry = this.shellLaunchConfig.isFeatureTerminal || this.shellLaunchConfig.hideFromUser || this.shellLaunchConfig.executable === undefined;
		const xterm = this._instantiationService.createInstance(XtermTerminal, Terminal, this._configHelper, this._cols, this._rows, this.target || TerminalLocation.Panel, this.capabilities, disableShellIntegrationTelemetry);
```

File: src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts (hunk 4 above)
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts:102]: Could this be just `: boolean`?

**Review by Tyriar — DISMISSED** [review]
Oh sorry, I got confused and understand now 👍

**Review by Tyriar — DISMISSED** [review]

**Review by Tyriar — APPROVED** [review]
