### PR TITLE
Fix getting initial configs from debug adapter

### LINKED ISSUE #156943: "Create a launch.json file" does not get initial configs from debug adapter
- Open workspace with no launch.json
- In the debug viewlet click "Create a launch.json"
- Pick "Node"
- Empty launch config is created, when it should have asked the debug adapter for the initial launch configs and added those to the created launch.json

From https://github.com/microsoft/vscode/issues/153388

### PR DESCRIPTION
**Pull request by roblourens**
Fixes #156943

Added this flag, then didn't use it properly. Will look into tests.

### CODE REVIEW

File: src/vs/workbench/contrib/debug/browser/debugQuickAccess.ts [hunk 1]
```diff
@@ -63,7 +63,7 @@ export class StartDebugQuickAccessProvider extends PickerQuickAccessProvider<IPi
 						tooltip: localize('customizeLaunchConfig', "Configure Launch Configuration")
 					}],
 					trigger: () => {
-						config.launch.openConfigFile({ preserveFocus: false, useInitialConfigs: false });
+						config.launch.openConfigFile({ preserveFocus: false });
```
Comment (roblourens) [inline src/vs/workbench/contrib/debug/browser/debugQuickAccess.ts:66]: I don't know why I added `useInitialConfigs: false` here, this should only happen for configs that already exist in a launch.json, so the file should already exist

**Review by bpasero — APPROVED** [review]
