### PR TITLE
fix hovers, make sure content is read before accessible view hint

### LINKED ISSUE #190261: hover content is overwritten by accessible view hint
1. with a screen reader on, and hover verbosity enabled, focus a hover via ctrl/cmd k + i
2. 🐛 the hover content isn't read at all

### PR DESCRIPTION
**Pull request by meganrogge**
fix #190261

the two types of hovers handle this differently. this was involved and works well now for each.

### CODE REVIEW

File: src/vs/editor/contrib/hover/browser/contentHover.ts [hunk 1]
```diff
@@ -758,6 +756,13 @@ export class ContentHoverWidget extends ResizableContentWidget {
 			this._hover.containerDomNode.focus();
 		}
 		hoverData.colorPicker?.layout();
+
+		// The aria label overrides the label, so if we add to it, add the contents of the hover
+		let accessibleViewHint = getHoverAccessibleViewHint(this._configurationService.getValue('accessibility.verbosity.hover') === true && this._accessibilityService.isScreenReaderOptimized(), this._keybindingService.lookupKeybinding('editor.action.accessibleView')?.getAriaLabel() ?? '');
+		if (accessibleViewHint) {
+			accessibleViewHint = ', ' + accessibleViewHint;
+		}
+		this._hover.contentsDomNode.ariaLabel = accessibleViewHint ? this._hover.contentsDomNode.textContent + accessibleViewHint : '';
```
Comment (Tyriar) [inline src/vs/editor/contrib/hover/browser/contentHover.ts:765]: Preferably we wouldn't touch it if accessible View Hint is not set, I think setting it to '' will clear the actual label and then not be available for other assistive tech

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/editor/contrib/hover/browser/contentHover.ts (hunk 1 above)
Comment (rzhao271) [inline src/vs/editor/contrib/hover/browser/contentHover.ts:765]:
```suggestion
		this._hover.contentsDomNode.ariaLabel = accessibleViewHint ? this._hover.contentsDomNode.textContent + ', ' + accessibleViewHint : '';
```

I believe this could help avoid the if statement above.

Comment (meganrogge) [reply src/vs/editor/contrib/hover/browser/contentHover.ts:765]: the `, ` is important because causes the screen reader to pause between statements.

Comment (meganrogge) [reply src/vs/editor/contrib/hover/browser/contentHover.ts:765]: it doesn't do anything wrong (I tested it), but also fine to go with what you suggested.

File: src/vs/workbench/services/hover/browser/hoverWidget.ts [hunk 2]
```diff
@@ -294,8 +295,7 @@ export class HoverWidget extends Widget {
 
 	public render(container: HTMLElement): void {
 		container.appendChild(this._hoverContainer);
-		this._hover.containerDomNode.ariaLabel = getHoverAriaLabel(this._configurationService.getValue('accessibility.verbosity.hover') === true && this._accessibilityService.isScreenReaderOptimized(), this._keybindingService.lookupKeybinding('editor.action.accessibleView')?.getAriaLabel()) ?? '';
-		console.log('aria label', this._hover.containerDomNode.ariaLabel);
+		status(getHoverAccessibleViewHint(this._configurationService.getValue('accessibility.verbosity.hover') === true && this._accessibilityService.isScreenReaderOptimized(), this._keybindingService.lookupKeybinding('editor.action.accessibleView')?.getAriaLabel()) ?? '');
```
Comment (Tyriar) [inline src/vs/workbench/services/hover/browser/hoverWidget.ts:298]: I think you only want to call `status` if the message is not `''`

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Review by Tyriar — APPROVED** [review]
