### PR TITLE
Handle file uri in CommentAuthorInformation.iconPath (fix #174690)

### LINKED ISSUE #174690: Comments API - How can `author.iconPath` reference a file bundled with the extension?
At https://github.com/gjsjohnmurray/vscode-extension-samples/tree/show-iconpath I have created a branch in which the comment-sample example has been amended to set the `author` property of the comments it adds.

Here are the lines that create the `author` object:

https://github.com/gjsjohnmurray/vscode-extension-samples/blob/e0da92cfdf830988616b7f5f2a905ae0054fa4f4/comment-sample/src/extension.ts#L23-L27

image

The commented-out one was my original, but when running on Desktop the console of devtools reported that the `file:` resource wasn't allowed. After digging through sources I found how to make it work on that platform by using the `vscode-file` scheme.

But this doesn't work when running on Codespaces.

What must I set `iconPath` to so the icon appears when running on that platform too?

Version: 1.76.0-insider
Commit: dc619de8d9efdabd781fc5658d0051813c347055
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
Embedder: codespaces

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #174690 and supersedes #174751

It handles the case where the `CommentAuthorInformation.iconPath` uri uses the `file` scheme (for example, to specify an avatar that is bundled with the extension).

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
/assign @alexr00 

Have I got the right idea here?

File: src/vs/workbench/contrib/comments/browser/commentNode.ts [hunk 1]
```diff
@@ -116,7 +117,7 @@ export class CommentNode<T extends IRange | ICellRange> extends Disposable {
 		const avatar = dom.append(this._domNode, dom.$('div.avatar-container'));
 		if (comment.userIconPath) {
 			const img = <HTMLImageElement>dom.append(avatar, dom.$('img.avatar'));
-			img.src = comment.userIconPath.toString();
+			img.src = FileAccess.uriToBrowserUri(URI.from(comment.userIconPath)).toString(true);
```
Comment (alexr00) [inline src/vs/workbench/contrib/comments/browser/commentNode.ts:120]: I'm not sure you need the `FileAccess.uriToBrowserUri`. I'll need to look into it.

**Review by alexr00 — COMMENTED** [review]
Yes, this is the right idea.

File: src/vs/workbench/contrib/comments/browser/commentNode.ts (hunk 1 above)
Comment (gjsjohnmurray) [reply src/vs/workbench/contrib/comments/browser/commentNode.ts:120]: Definitely need that, because file:// URIs in the DOM are blocked. The line after that one sets an error handler which simply removes the img element when that happens, but if you comment that out you'll see the broken image.

**Review by bpasero — APPROVED** [review]

**Review by aiday-mar — APPROVED** [review]

**Review by alexr00 — APPROVED** [review]
Thank you for the PR!
