### PR TITLE
When there are several definitions in the peek view, arrow should point to the correct word 

### LINKED ISSUE #158871: When several definitions revealed, the arrow in the peek view should point to the correct element
The issue can be seen in the gif below. Notice how despite the fact that right definitions are shown the arrow points to the wrong definition in the sticky scroll line.

sticky-scroll-incorrect-arrow

### PR DESCRIPTION
**Pull request by aiday-mar**
Fixes #158871. The new behavior after merging the new changes from yesterday is as follows. The peek view is not hidden behind the target line. 

sticky-scroll-peekview

### CODE REVIEW

File: src/vs/editor/contrib/inlayHints/browser/inlayHintsLocations.ts [hunk 1]
```diff
@@ -106,7 +106,8 @@ export async function goToDefinitionWithLocation(accessor: ServicesAccessor, eve
 		const canPeek = !openToSide && editor.getOption(EditorOption.definitionLinkOpensInPeek) && !isInPeek;
 
 		const action = new DefinitionAction({ openToSide, openInPeek: canPeek, muteMessage: true }, { alias: '', label: '', id: '', precondition: undefined });
-		return action.run(accessor, editor, { model: ref.object.textEditorModel, position: Range.getStartPosition(location.range) });
+		const locationRange = location.range;
+		return action.run(accessor, editor, { model: ref.object.textEditorModel, position: Range.getStartPosition(locationRange) }, new Range(locationRange.startLineNumber, locationRange.startColumn, locationRange.endLineNumber, locationRange.endColumn));
```
Comment (jrieken) [inline src/vs/editor/contrib/inlayHints/browser/inlayHintsLocations.ts:110]: fyi - the is `Range.lift` which is the sugar-variant for creating a `Range` from an `IRange`, e.g all in one `Range.lift(location.range)`

File: src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts [hunk 2]
```diff
@@ -229,10 +229,14 @@ export abstract class SymbolNavigationAction extends EditorAction {
...
-	private _openInPeek(target: ICodeEditor, model: ReferencesModel) {
+	private _openInPeek(target: ICodeEditor, model: ReferencesModel, range?: Range) {
 		const controller = ReferencesController.get(target);
 		if (controller && target.hasModel()) {
-			controller.toggleWidget(target.getSelection(), createCancelablePromise(_ => Promise.resolve(model)), this.configuration.openInPeek);
+			if (range) {
+				controller.toggleWidget(range, createCancelablePromise(_ => Promise.resolve(model)), this.configuration.openInPeek);
+			} else {
+				controller.toggleWidget(target.getSelection(), createCancelablePromise(_ => Promise.resolve(model)), this.configuration.openInPeek);
+			}
```
Comment (jrieken) [inline src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts:239]: Nicer, shorter would be `range = range ?? target.getSelection()` and later always use the range. That would be less similar/duplicated code

**Review by jrieken — CHANGES_REQUESTED** [review]
Some nit but I also think the behaviour can be improved. The recording shows that peek reveals behind sticky scroll, e.g it slightly overlap and IMO we should have a solution where the target line and the arrow are visible

Screenshot 2022-08-24 at 09 15 14

**Review by jrieken — APPROVED** [review]
