### PR TITLE
Fix #182014: ISO Date format

### LINKED ISSUE #182014: Show ISO format dates always
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.78.1
- OS Version: macOS 12.6.3 (21G419)

Steps to Reproduce:

1. Set your OS date format to `dd/mm/yyyy`.
2. Open the Extensions pane.
3. Click on an extension.

## Expected behaviour

The dates in "More Info" are shown in dd/mm/yyyy format. VSCode should have a setting where the locale can be set, but should use the system locale if it has not been set. (I assume there is no setting; a search for "locale" doesn't find anything, and "date" or "language" produces far too many results to be useful!)

Alternatively, if implementing locale support here is tricky, yyyy-mm-dd could be used — or just text like "July 11, 2016" rather than short dates.

## Actual behaviour

The dates are shown in mm/dd/yyyy format, despite the fact that most locales do not use this format.

Here's an example, grabbed today (May 10, 2023). The "last release" and "last updated" dates give a clue in this case, as it's not yet September or October, but the "published" date looks valid. However, it's July 11, 2016 and not November 7, 2016.

image

### PR DESCRIPTION
**Pull request by rielAsh24**
Fixes #182014 

This change addresses the date formatting on the Extensions page to align with `ISO-8601` `(yyyy/mm/dd)`.

Sample Output:

ISO_format

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/182014#issuecomment-1597355077

**Comment by sandy081** [comment]
@rielAsh24 As per @gjsjohnmurray's comment, can you please change the separator

> Based on https://en.wikipedia.org/wiki/ISO_8601 the separators should be - rather than /

**Comment by rielAsh24** [comment]
> @rielAsh24 As per @gjsjohnmurray's comment, can you please change the separator
> 
> > Based on https://en.wikipedia.org/wiki/ISO_8601 the separators should be - rather than /

Sure! Will implement the changes as you suggested

**Comment by rielAsh24** [comment]
@sandy081 Added the `-` :
ISO_format

File: src/vs/workbench/contrib/extensions/browser/extensionEditor.ts [hunk 1]
```diff
@@ -945,22 +945,25 @@ export class ExtensionEditor extends EditorPane {
 		append(moreInfoContainer, $('.additional-details-title', undefined, localize('Marketplace Info', "More Info")));
 		const moreInfo = append(moreInfoContainer, $('.more-info'));
 		if (gallery) {
+			const pub = new Date(gallery.releaseDate);
+			const last_rel = new Date(gallery.lastUpdated);
 			append(moreInfo,
 				$('.more-info-entry', undefined,
 					$('div', undefined, localize('published', "Published")),
-					$('div', undefined, new Date(gallery.releaseDate).toLocaleString(language, { hourCycle: 'h23' }))
+					$('div', undefined, pub.toISOString().slice(0, 10).concat(', ' + pub.toLocaleTimeString(language, { hourCycle: 'h23' })))
```
Comment (sandy081) [inline src/vs/workbench/contrib/extensions/browser/extensionEditor.ts:953]: `toISOString()` is returning the UTC Time. I would recommend to construct the string by getting each value (day, month, year...)

Comment (rielAsh24) [reply src/vs/workbench/contrib/extensions/browser/extensionEditor.ts:953]: Got you! Would implement that and commit when done

Comment (rielAsh24) [reply src/vs/workbench/contrib/extensions/browser/extensionEditor.ts]: > `toISOString()` is returning the UTC Time. I would recommend to construct the string by getting each value (day, month, year...)

Hey! I tried working something. Do let me know if it works!

Comment (rielAsh24) [reply src/vs/workbench/contrib/extensions/browser/extensionEditor.ts]: @sandy081 Worked on another one as well. Do let me know whichever solution suits!

**Comment by rielAsh24** [comment]
Hey @sandy081, are there any other changes required to complete this PR?

**Review by sandy081 — APPROVED** [review]

**Review by jrieken — APPROVED** [review]
