### PR TITLE
Force new terminal editor action to open in same locked group

### LINKED ISSUE #135022: “New terminal” button in locked editor group causes new terminal to open in different editor group
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.0
- OS Version: macOS 11.6

## Steps to Reproduce

1. Create a locked editor group containing a terminal:
    
Screen Shot 2021-10-13 at 1 48 32 PM

2. Click the “New terminal” (+) button in the editor group header.
    
## Result

The terminal opens in a different editor group and locks the group:

Screen Shot 2021-10-13 at 1 48 43 PM

## Expected result

The terminal should open in the same editor group, like so:

Screen Shot 2021-10-13 at 1 52 30 PM

(This may be the same issue as #131156 but because it’s been closed I can’t comment in it.)

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #135022

### CODE REVIEW

**Review by bpasero — DISMISSED** [review]
At first I was wondering why you use `index`. But then I see you have a concept of `viewColumn`, so I think you are doing the right thing for your model.

File: src/vs/workbench/contrib/terminal/browser/terminalActions.ts [hunk 1]
```diff
@@ -227,6 +228,21 @@ export function registerTerminalActions() {
 		}
 	});
 
+	registerTerminalAction({
+		id: TerminalCommandId.CreateTerminalEditorSameGroup,
+		title: { value: localize('workbench.action.terminal.createTerminalEditor', "Create New Terminal in Editor Area"), original: 'Create New Terminal in Editor Area' },
+		f1: false,
+		run: async (c, accessor, args) => {
+			// Force the editor into the same editor group is it's locked. This command is only ever
```
Comment (gjsjohnmurray) [inline src/vs/workbench/contrib/terminal/browser/terminalActions.ts:236]:
```suggestion
			// Force the editor into the same editor group if it's locked. This command is only ever
```

**Review by bpasero — APPROVED** [review]
