### PR TITLE
Git - Another attempt to fix an edge case for adding a safe directory

### LINKED ISSUE #170422: GIT: Unsafe repository 'Mark as Safe' for UNC paths for SMB shares are not working
Does this issue occur when all extensions are disabled?: Yes

Basically, it's a duplicate of #168344 and #169354 because Insiders build doesn't fix it.

VSCode Insiders About Information:
Version: 1.75.0-insider (user setup)
Commit: 6ed4d436a9b6ae131732f4e2a723868231f4473a
Date: 2022-12-23T05:21:57.802Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

Steps to Reproduce:

1. Open VSCode - Insiders
2. Open a git repo that is on a remote computer shared over SMB
3. Get the following prompt and press "Manage Unsafe Repositories"
`The git repository in the current folder is potentially unsafe as the folder is owned by someone other than the current user.`
4. In the popup, select the UNC path for that SMB share. Get the following error: `Git: spawn C:\Program Files\Git\cmd\git.exe ENOENT`.
5. Pressing "Open Git Log" gives the following information (some parts were removed for obvious reasons).
```
2023-01-02 19:23:58.919 [info] > git rev-parse --show-toplevel [240ms]
2023-01-02 19:23:58.920 [info] warning: encountered old-style '//DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/reponame' that should be '%(prefix)///DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/reponame'
warning: encountered old-style '//DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/reponame' that should be '% (prefix)///DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/reponame'  
... (same thing repeated 5x)
fatal: detected dubious ownership in repository at '//DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/reponame'
'//DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/reponame' is owned by:
	'some windows user ID'
but the current user is:
	'some different windows user ID'
To add an exception for this directory, call:

	git config --global --add safe.directory '%(prefix)///DESKTOP-BFO0M0/C Drive/Users/jason/Documents/GitHub/reponame'
```

### PR DESCRIPTION
**Pull request by lszomoru**
Fixes #170422

### CODE REVIEW

File: extensions/git/src/git.ts [hunk 1]
```diff
@@ -686,7 +686,7 @@ export class Git {
 	}
 
 	async addSafeDirectory(repositoryPath: string): Promise<void> {
-		await this.exec(repositoryPath, ['config', '--global', '--add', 'safe.directory', repositoryPath]);
+		await this.exec('', ['config', '--global', '--add', 'safe.directory', repositoryPath]);
```
Comment (joaomoreno) [inline extensions/git/src/git.ts:689]: Would it make more sense to use `os.homedir()` here, instead of `''`? I noticed the same pattern here: https://github.com/microsoft/vscode/blob/6d40104789d03d41b8866a1e57847dae14c5cf0d/extensions/git/src/git.ts#L676

**Review by joaomoreno — APPROVED** [review]
