### PR TITLE
fix: missing translations of remote built-in extensions

### LINKED ISSUE #250579: Translations for built-in extensions are missing in remote mode
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.100.3
- OS Version: Darwin arm64 24.5.0

Steps to Reproduce:

1. Switch the UI language to non-English, e.g. Chinese
2. Connect to a remote server.
3. Notice almost all UI elements are translated, except for those contributed by built-in extensions, e.g. The source control view.

https://github.com/user-attachments/assets/fd0343ee-d24f-429f-9f43-6c02787bccdf

(This reproduction video is captured by @BlackHole1.)

We have submitted a fix https://github.com/microsoft/vscode/pull/249430.

### PR DESCRIPTION
**Pull request by hyrious**
@BlackHole1 noticed that some translations are missing when develop in remote mode. After digging a bit, we found that only built-in extensions' NLS messages are missing. For example, the Source Control view (contributed by the built-in 'Git' extension) and built-in extensions' configurations are in English.

Despite that the remote server will download and install the corresponding language pack extension, it does not pick the language pack up because of 2 problems:

1. There's no `nls.keys.json` in the server build, causing `clp/{hash}.{lang}/*` failed to generate.
2. When scanning built-in extensions, the UI language was not passed correctly to the backend.

This PR fixes the 2 problems.

Note about problem 1: The original code `Promise.all([mkdir, read keys, read messages])` will fail when the keys file is missing, but the mkdir task would succeed and leave an empty folder which prevents it regenerate in the next calling. So I changed the testing logic from the folder to the file in it.

Fixes #250579

### CODE REVIEW

**Comment by hyrious** [comment]
@microsoft-github-policy-service agree

**Comment by sandy081** [comment]
Can you please share more information here - what is the bug? Are there steps to reproduce? Any screenshots would be helpful. Before that please file an issue first with all this information. Thanks

**Comment by hyrious** [comment]
@sandy081 Hi thanks for showing up. I have created an issue linked to this PR: https://github.com/microsoft/vscode/issues/250579

**Comment by TylerLeonhardt** [comment]
@hyrious how did you test this change, because I just tested it (by building a local build of VS Code) and it sadly does not work (I'm using a pseudolanguage pack since I know only English)

image

**Comment by TylerLeonhardt** [comment]
@sandy081 your guidance would be nice here. The steps are easy to reproduce:
* Install a language pack
* Do any Remote connection (like Dev Containers)
* Check the source control view for localization

These strings are localized in the manifest so I'm not sure why, when there's a remote, the manifest strings would stick to English.

**Comment by hyrious** [comment]
@TylerLeonhardt A little tricky to test because the remote host should also be built by yourself. If you're using the official reh build in the remote host it wouldn't work.

I actually tested it by manually port changes to the code-server. You may have a try:

1. Find the code server's source code in the remote OS, it should be inside ~/.vscode-server.
2. Copy the nls.keys.json from your local vscode to the same folder as nls.messages.json in the remote OS.
3. Delete the `clp` folder from the remote OS if it was generated before.
4. Port changes to the server's source code. If you're just lazy, you can hard code a language option in the scan extensions method (see this pr's diff).
5. Reconnect to it, this means a full restart of the code-server process. The client should have been modified to send correct IPC messages. Note that in this step, you have to make sure the local commit does not change otherwise the server may refuse to connect.

**Comment by BlackHole1** [comment]
> Delete the clp folder from the remote OS if it was generated before.

`clp` location: `~/.vscode-server-insiders/data/clp`

**Comment by TylerLeonhardt** [comment]
I built an Insiders build off of this branch and can confirm that this fixes the problem :)

File: src/vs/base/node/nls.ts [hunk 1]
```diff
@@ -108,27 +108,27 @@ export async function resolveNLSConfiguration({ userLocale, osLocale, userDataPa
 			_corruptedFile: languagePackCorruptMarkerFile
 		};
 
-		if (await Promises.exists(commitLanguagePackCachePath)) {
+		if (await Promises.exists(languagePackMessagesFile)) {
```
Comment (TylerLeonhardt) [inline src/vs/base/node/nls.ts:111]: @bpasero does this seem sane to you?

File: src/vs/platform/extensionManagement/common/extensionManagement.ts [hunk 2]
```diff
@@ -616,7 +616,7 @@ export interface IExtensionManagementService {
 	uninstall(extension: ILocalExtension, options?: UninstallOptions): Promise<void>;
 	uninstallExtensions(extensions: UninstallExtensionInfo[]): Promise<void>;
 	toggleApplicationScope(extension: ILocalExtension, fromProfileLocation: URI): Promise<ILocalExtension>;
-	getInstalled(type?: ExtensionType, profileLocation?: URI, productVersion?: IProductVersion): Promise<ILocalExtension[]>;
+	getInstalled(type?: ExtensionType, profileLocation?: URI, productVersion?: IProductVersion, language?: string): Promise<ILocalExtension[]>;
```
Comment (TylerLeonhardt) [inline src/vs/platform/extensionManagement/common/extensionManagement.ts:619]: @sandy081 does this seem ok to you?

**Review by TylerLeonhardt — DISMISSED** [review]

File: src/vs/base/node/nls.ts (hunk 1 above)
Comment (TylerLeonhardt) [reply src/vs/base/node/nls.ts:111]: @hyrious I don't quite understand this change... can you elaborate on it?

Comment (hyrious) [reply src/vs/base/node/nls.ts:111]: See my comment on the pr body:

> Note about problem 1: The original code Promise.all([mkdir, read keys, read messages]) will fail when the keys file is missing, but the mkdir task would succeed and leave an empty folder which prevents it regenerate in the next calling. So I changed the testing logic from the folder to the file in it.

Comment (bpasero) [reply src/vs/base/node/nls.ts:111]: This predates my change, I just moved code around. See: https://github.com/microsoft/vscode/blob/2ccd690cbff1569e4a83d7c43d45101f817401dc/src/vs/base/node/languagePacks.js#L190-L191

@dbaeumer can maybe chime in why we are checking and touching the parent folder of language packs and not the language file (`nls.messages.js`) itself that is inside that folder.

This originates from a 8y old commit: https://github.com/microsoft/vscode/commit/04594c864be35281ff7eca15a6db2a5a735bb320

File: src/vs/base/node/nls.ts [hunk 3]
```diff
@@ -108,27 +108,27 @@ export async function resolveNLSConfiguration({ userLocale, osLocale, userDataPa
...
+			[Array<[string, string[]]>, string[], { contents: Record<string, Record<string, string>> }]
+			//      ^moduleId ^nlsKeys                               ^moduleId      ^nlsKey ^nlsValue
 			= await Promise.all([
-				promises.mkdir(commitLanguagePackCachePath, { recursive: true }),
 				promises.readFile(join(nlsMetadataPath, 'nls.keys.json'), 'utf-8').then(content => JSON.parse(content)),
 				promises.readFile(join(nlsMetadataPath, 'nls.messages.json'), 'utf-8').then(content => JSON.parse(content)),
 				promises.readFile(mainLanguagePackPath, 'utf-8').then(content => JSON.parse(content)),
 			]);
 
+		await promises.mkdir(commitLanguagePackCachePath, { recursive: true });
```
Comment (bpasero) [inline src/vs/base/node/nls.ts]: Is the intent here to not create this folder if the previous read fails? I think that makes sense to me. But then should that code be moved closer to where we do the `promises.writeFile` further below to make this really clear?

Comment (hyrious) [reply src/vs/base/node/nls.ts]: > Is the intent here to not create this folder if the previous read fails?

Yes. I can move the mkdir code to below a few lines later.

File: src/vs/base/node/nls.ts (hunk 1 above)
Comment (dbaeumer) [reply src/vs/base/node/nls.ts:111]: @bpasero if I remember correctly the touch is used to mark the language pack as used. There is some code that deletes old language packs examining the timestamp of these folders.

Comment (dbaeumer) [reply src/vs/base/node/nls.ts:111]: The code that stats this is here: https://github.com/microsoft/vscode/blob/main/src/vs/code/electron-utility/sharedProcess/contrib/languagePackCachedDataCleaner.ts#L90

Comment (dbaeumer) [reply src/vs/base/node/nls.ts:111]: So if we want to touch a file insider we need to stat the inside file to decide whether we want to remove the LP data.

**Review by dbaeumer — DISMISSED** [review]

File: src/vs/base/node/nls.ts (hunk 1 above)
Comment (bpasero) [reply src/vs/base/node/nls.ts:111]: Thanks a lot! Then I think we need to be careful here.

Comment (TylerLeonhardt) [reply src/vs/base/node/nls.ts:111]: Thanks, @dbaeumer! Based on that I think we can keep the proposed change of checking if an inside file exists but still touching the outer folder.

**Review by TylerLeonhardt — DISMISSED** [review]

File: src/vs/base/node/nls.ts (hunk 1 above)
Comment (hyrious) [reply src/vs/base/node/nls.ts:111]: Thanks @dbaeumer! So I assume it is fine to keep existing logic here.

File: src/vs/platform/extensionManagement/node/extensionManagementService.ts [hunk 4]
```diff
@@ -562,14 +562,14 @@ export class ExtensionsScanner extends Disposable {
...
-	async scanExtensions(type: ExtensionType | null, profileLocation: URI, productVersion: IProductVersion): Promise<ILocalExtension[]> {
+	async scanExtensions(type: ExtensionType | null, profileLocation: URI, productVersion: IProductVersion, language?: string): Promise<ILocalExtension[]> {
 		try {
 			const userScanOptions: UserExtensionsScanOptions = { includeInvalid: true, profileLocation, productVersion };
 			let scannedExtensions: IScannedExtension[] = [];
 			if (type === null || type === ExtensionType.System) {
 				let scanAllExtensionsPromise = this.scanAllExtensionPromise.get(profileLocation);
 				if (!scanAllExtensionsPromise) {
-					scanAllExtensionsPromise = this.extensionsScannerService.scanAllExtensions({}, userScanOptions)
+					scanAllExtensionsPromise = this.extensionsScannerService.scanAllExtensions({ language }, userScanOptions)
```
Comment (sandy081) [inline src/vs/platform/extensionManagement/node/extensionManagementService.ts:573]: Is not this promise should be cached by language?

Comment (hyrious) [reply src/vs/platform/extensionManagement/node/extensionManagementService.ts:573]: Oh.. yes. Maybe I will just use `${profileLocation}?${language}` for key of the `scanAllExtensionPromise` map?

**Review by roblourens — DISMISSED** [review]

**Review by TylerLeonhardt — DISMISSED** [review]

**Comment by TylerLeonhardt** [comment]
@sandy081 I defer to you for final approval

File: src/vs/platform/extensionManagement/node/extensionManagementService.ts (hunk 4 above)
Comment (sandy081) [reply src/vs/platform/extensionManagement/node/extensionManagementService.ts:573]: Yes, you need to change both scanned extensions promises map

Comment (hyrious) [reply src/vs/platform/extensionManagement/node/extensionManagementService.ts:573]: @sandy081 Sorry, just noticed the comment. Code updated.

**Review by sandy081 — APPROVED** [review]

**Comment by sandy081** [comment]
@TylerLeonhardt Approved from my side. Should we merge?

**Review by alexr00 — APPROVED** [review]

**Review by TylerLeonhardt — APPROVED** [review]
🎉

**Comment by TylerLeonhardt** [comment]
@hyrious this fix is going to make a lot of devs happy. Thank you for contributing!
