### PR TITLE
fix #233235

### LINKED ISSUE #233235: In profile creation, when switching templates, the snippets view doesn't reset
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.0 through 1.95.1, did not test insiders
- OS Version: Windows 10 Enterprise and Linux (RHEL8) tested, did not test Mac

Steps to Reproduce:

1. Use the profile manager to start creating a new profile.
2. In the 'Copy from' menu, choose Python, expand the Snippets view, then go back and switch the menu to Java Spring.  The reverse order also works. You can also replace Python with Data Science for the same bug.
3. Observe that the Snippets view now contains both sets:  
   Image

After clicking to create the profile, only the correct set of snippets is included. So this is just a UI bug.

### PR DESCRIPTION
**Pull request by sandy081**
fix #233235

### CODE REVIEW

File: src/vs/workbench/contrib/userDataProfile/browser/userDataProfilesEditorModel.ts [hunk 1]
```diff
@@ -786,7 +786,9 @@ export class NewProfileElement extends AbstractUserDataProfileElement {
 	}
 
 	private async getChildrenFromProfileTemplate(profileTemplate: IUserDataProfileTemplate, resourceType: ProfileResourceType): Promise<IProfileResourceTypeChildElement[]> {
-		const profile = toUserDataProfile(generateUuid(), this.name, URI.file('/root').with({ scheme: USER_DATA_PROFILE_TEMPLATE_PREVIEW_SCHEME }), URI.file('/cache').with({ scheme: USER_DATA_PROFILE_TEMPLATE_PREVIEW_SCHEME }));
+		const location = URI.file(`/root/profiles/${profileTemplate.name}`).with({ scheme: USER_DATA_PROFILE_TEMPLATE_PREVIEW_SCHEME });
```
Comment (jrieken) [inline src/vs/workbench/contrib/userDataProfile/browser/userDataProfilesEditorModel.ts:789]: fyi - you don't need to do `URI.file(...).with(..)` and that you can use `URI.from({scheme, path})`

Comment (sandy081) [reply src/vs/workbench/contrib/userDataProfile/browser/userDataProfilesEditorModel.ts]: Thanks. ✅

**Review by aeschli — APPROVED** [review]
