### PR TITLE
Fix bugs with chat paste widget

### LINKED ISSUE #234902: Paste options is behind attach btn
* use edits
* paste a function (see below) into the input
* :bug: the paste options are rendered behind the attach btn

Image

```
export function fib(nth) {
	if (nth <= 0) return 0;
	if (nth === 1) return 0;
	if (nth === 2) return 1;

	return fib(nth - 1) + fib(nth - 2);
}
```

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #234902

- Fix z-index #234902
- Use `yieldTo` for edit ordering  instead of hardcoding chat workaround. This makes sure the list of edits shows up in the correct order
- Clear widget on editor focus loss

### CODE REVIEW

File: src/vs/editor/contrib/dropOrPasteInto/browser/copyPasteController.ts [hunk 1]
```diff
@@ -685,11 +685,6 @@ export class CopyPasteController extends Disposable implements IEditorContributi
 			}
 		}
 
-		// Specific case for pasting code blocks.
```
Comment (mjbvz) [inline src/vs/editor/contrib/dropOrPasteInto/browser/copyPasteController.ts:688]: cc @justschen You can use `yieldTo` to suggest how an edit should be ordered. In this case we can yield to `text.plain` to push the attachment edit after normal text pasting

**Review by justschen — APPROVED** [review]
