### PR TITLE
fix(mcp): resolve env vars in agent plugin MCP server definitions

### LINKED ISSUE #302579: Agent Plugin's MCP does not expand env variables
How are we supposed to ship a local MCP server that requires env variables to work? The plugin loads fine in copilot CLI.

- Copilot Chat Extension Version: 0.39.2
- VS Code Version: 1.111.0
- OS Version: macOS 26.3
- Feature (e.g. agent/edit/ask mode): Does not matter
- Selected model (e.g. GPT 4.1, Claude 3.7 Sonnet): Does not matter
- Logs: No

Steps to Reproduce:

Create an agent plugin, and set the `.mcp.json` to something like this;

```
{
  "mcpServers": {
    "enterprise-github": {
      "command": "docker",
      "args": [
        "run",
        "-i",
        "--rm",
        "-e",
        "GITHUB_PERSONAL_ACCESS_TOKEN",
        "-e",
        "GITHUB_HOST",
        "ghcr.io/github/github-mcp-server"
      ],
      "env": {
        "GITHUB_PERSONAL_ACCESS_TOKEN": "${ENTERPRISE_GITHUB_TOKEN}",
        "GITHUB_HOST": "https://enterprise.github.example.com"
      },
      "tools": ["*"]
    }
  }
}

```

The MCP server does load but throws 401. Works fine in copilot CLI.

### PR DESCRIPTION
**Pull request by ConsoleTVs**
Agent plugin MCP servers did not resolve environment variable references because the resolution pipeline was skipped entirely (no variableReplacement was set) and the MCP-standard bare ${VAR} syntax is not recognized by VS Code's configuration resolver.

- Add variableReplacement to plugin server definitions so the resolution pipeline runs
- Convert bare ${VAR} references to ${env:VAR} at the plugin boundary so the resolver can look them up in process.env

Fixes #302579

### CODE REVIEW

File: src/vs/workbench/contrib/chat/common/plugins/agentPluginServiceImpl.ts [hunk 1]
```diff
@@ -204,6 +204,74 @@ function interpolateMcpPluginRoot(
...
+ */
+export function convertBareEnvVarsToVsCodeSyntax(
+	def: IAgentPluginMcpServerDefinition,
+): IAgentPluginMcpServerDefinition {
+	const convert = (s: string) => s.replace(BARE_ENV_VAR_RE, '${env:$1}');
+
+	const config = def.configuration;
+	let converted: IMcpServerConfiguration;
+
+	if (config.type === McpServerType.LOCAL) {
```
Comment (connor4312) [inline src/vs/workbench/contrib/chat/common/plugins/agentPluginServiceImpl.ts]: We have an helper `cloneAndChange` you can use to simplify this function

Comment (ConsoleTVs) [reply src/vs/workbench/contrib/chat/common/plugins/agentPluginServiceImpl.ts]: @connor4312 addressed here: a9b9bb45c462503eebddf5fbbc3a738d1b58aae3

**Review by connor4312 — DISMISSED** [review]
thanks!

**Review by vijayupadya — APPROVED** [review]

**Review by connor4312 — APPROVED** [review]
