### PR TITLE
use stripped down version of PSReadline for screen reader support on windows to enable pwsh shell integration 

### LINKED ISSUE #233921: terminal shell integration doesn't work for screen reader users sometimes
From @jooyoungseo

waiting for the logs

Image

### PR DESCRIPTION
**Pull request by meganrogge**
fix #233921

### CODE REVIEW

File: src/vs/platform/terminal/node/terminalEnvironment.ts [hunk 1]
```diff
@@ -63,7 +63,7 @@ export async function getShellIntegrationInjection(
 	env: ITerminalEnvironment | undefined,
 	logService: ILogService,
 	productService: IProductService,
-	skipStickyBit: boolean = false
+	skipStickyBit: boolean = false,
```
Comment (meganrogge) [inline src/vs/platform/terminal/node/terminalEnvironment.ts]:
```suggestion
	skipStickyBit: boolean = false
```

File: src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1 [hunk 2]
```diff
@@ -169,6 +169,34 @@ elseif ((Test-Path variable:global:GitPromptSettings) -and $Global:GitPromptSett
 	[Console]::Write("$([char]0x1b)]633;P;PromptType=posh-git`a")
 }
 
+function Global:__VSCode-TestScreenReader {
+	# Detect VS Code screen reader mode from common env vars (treat: 1/true/enabled as on)
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]:
```suggestion
```

File: src/vs/workbench/contrib/terminal/common/psreadline/PSReadLine.psd1
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/psreadline/PSReadLine.psd1:1]: Let's stick these inside the `scripts/` folder

File: src/vs/workbench/contrib/terminal/common/psreadline/License.txt [hunk 3]
```diff
@@ -0,0 +1,23 @@
+Copyright (c) 2013, Jason Shirk
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/psreadline/License.txt]: This would need to integrate into a cgmanifest. Example here:
 https://github.com/microsoft/vscode/blob/b70d0fc99f58928e12d07c78013916cdd5046485/src/vs/base/browser/dompurify/cgmanifest.json#L1-L18

File: src/vs/workbench/contrib/terminal/common/psreadline/Changes.txt [hunk 4]
```diff
@@ -0,0 +1,861 @@
+### [2.4.3-beta3] - 2025-07-23
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/psreadline/Changes.txt]: We should verify this one isn't getting published into our product build

File: src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1 [hunk 5]
```diff
@@ -169,6 +169,32 @@ elseif ((Test-Path variable:global:GitPromptSettings) -and $Global:GitPromptSett
 	[Console]::Write("$([char]0x1b)]633;P;PromptType=posh-git`a")
 }
 
+function Global:__VSCode-TestScreenReader {
+	return ($env:VSCODE_ACCESSIBILITY_SUPPORT -match 'true')
+}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]: Inline this? We want to avoid globals from SI as much as possible as it contaminates the shell session

File: src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1 [hunk 6]
```diff
@@ -169,6 +169,32 @@ elseif ((Test-Path variable:global:GitPromptSettings) -and $Global:GitPromptSett
...
+
+try {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]: Just above this block is a good place to explain what this version of PSReadLine is here for

Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]: I think the try could be more localized? I think the main thing it needs to wrap is `Import-Module`, including other things could hide unexpected bugs that break this support. We may also want to not have a try here at all, especially if we can attempt to import and continue then errors printing would be very useful to stabilize

File: src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1 [hunk 7]
```diff
@@ -169,6 +169,32 @@ elseif ((Test-Path variable:global:GitPromptSettings) -and $Global:GitPromptSett
...
+	if (-not (Get-Module -Name PSReadLine)) {
+		if ($PSVersionTable.PSVersion.Major -ge 7 -and (Global:__VSCode-TestScreenReader)) {
+			# Resolve the path relative to this script
+			$scriptRoot = $PSScriptRoot
+			if (-not $scriptRoot) { $scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path }
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]: Not sure when `-not $scriptRoot` could happen?

File: src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1 [hunk 8]
```diff
@@ -169,6 +169,32 @@ elseif ((Test-Path variable:global:GitPromptSettings) -and $Global:GitPromptSett
...
+
+			$specialPsrlPath = Join-Path $scriptRoot '..\psreadline\'
+
+			Import-Module $specialPsrlPath -ErrorAction Stop
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]: Does `-ErrorAction Stop` means it'll brick the pwsh session? I don't think we want it to continue

File: src/vs/platform/terminal/node/terminalEnvironment.ts [hunk 9]
```diff
@@ -112,6 +112,7 @@ export async function getShellIntegrationInjection(
 	}
 	// Windows
 	if (isWindows) {
+		envMixin['VSCODE_ACCESSIBILITY_SUPPORT'] = options.isScreenReaderOptimized.toString();
```
Comment (Tyriar) [inline src/vs/platform/terminal/node/terminalEnvironment.ts]: We should use `'1'` instead, see `VSCODE_STABLE`, `VSCODE_SUGGEST` (which needs to be removed and I missed https://github.com/microsoft/vscode/issues/263800)

File: build/filters.js [hunk 10]
```diff
@@ -203,6 +206,7 @@ module.exports.tsFormattingFilter = [
 	'!extensions/html-language-features/server/lib/jquery.d.ts',
 	'!extensions/terminal-suggest/src/shell/zshBuiltinsCache.ts',
 	'!extensions/terminal-suggest/src/shell/fishBuiltinsCache.ts',
+	'!src/vs/workbench/contrib/terminal/common/psreadline/**'
```
Comment (Tyriar) [inline build/filters.js]: Shouldn't be needed as there's no ts?

File: .eslint-ignore [hunk 11]
```diff
@@ -38,4 +38,5 @@
 **/test/automation/out/**
 **/typings/**
 **/.build/**
+**/src/vs/workbench/contrib/terminal/common/psreadline/**
```
Comment (Tyriar) [inline .eslint-ignore]: Shouldn't be needed as no js/ts?

File: extensions/package-lock.json [hunk 12]
```diff
@@ -14,7 +14,7 @@
       },
       "devDependencies": {
         "@parcel/watcher": "2.5.1",
-        "esbuild": "0.25.0",
+        "esbuild": "^0.25.0",
```
Comment (Tyriar) [inline extensions/package-lock.json]: Unrelated change?

File: extensions/package.json [hunk 13]
```diff
@@ -11,7 +11,7 @@
   },
   "devDependencies": {
     "@parcel/watcher": "2.5.1",
-    "esbuild": "0.25.0",
+    "esbuild": "^0.25.0",
```
Comment (Tyriar) [inline extensions/package.json]: Unrelated change?

File: src/vs/platform/terminal/node/terminalEnvironment.ts (hunk 9 above)
Comment (Tyriar) [inline src/vs/platform/terminal/node/terminalEnvironment.ts]: Usually env vars aren't this long, how about `VSCODE_A11Y_MODE`?

File: src/vs/workbench/contrib/terminal/common/psreadline/Microsoft.PowerShell.PSReadLine.dll
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/psreadline/Microsoft.PowerShell.PSReadLine.dll:1]: @andyleejordan any help here on what files we should be keep and which we should not?

@meganrogge some of these files will probably get removed without special rules in our `build/` product build packaging code

**Review by Tyriar — DISMISSED** [review]

File: src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1 (hunk 8 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]: This means it will jump to the catch I believe, where we suppress errors.

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]: Sounds like from the above comment, we want the errors to be propagated. So I'll remove this.

File: src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1 (hunk 6 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]: removed it

File: src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1 (hunk 7 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]: looks like only for lower versions of pwsh, removed

File: src/vs/workbench/contrib/terminal/common/psreadline/License.txt (hunk 3 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/common/psreadline/License.txt]: done, just waiting on the commit to use from @andyleejordan

File: src/vs/workbench/contrib/terminal/common/psreadline/Changes.txt (hunk 4 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/common/psreadline/Changes.txt]: I removed it

File: src/vs/workbench/contrib/terminal/common/psreadline/Microsoft.PowerShell.PSReadLine.dll
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/common/psreadline/Microsoft.PowerShell.PSReadLine.dll:1]: According to AI:

net6plus/…Polyfill.dll is used when PSReadLine runs on .NET 6+ (i.e., pwsh 7+ on macOS/Linux/Windows), **so we should keep it.**

netstd/…Polyfill.dll is for the legacy .NET Framework / Windows PowerShell 5.1 path. **(so I think we can remove it since we mandate pwsh 7?)**

We can remove `changes.txt` and `license.txt` as well.

File: src/vs/platform/terminal/node/terminalProcess.ts [hunk 14]
```diff
@@ -147,7 +147,7 @@ export class TerminalProcess extends Disposable implements ITerminalChildProcess
 		private readonly _executableEnv: IProcessEnvironment,
 		private readonly _options: ITerminalProcessOptions,
 		@ILogService private readonly _logService: ILogService,
-		@IProductService private readonly _productService: IProductService
+		@IProductService private readonly _productService: IProductService,
```
Comment (meganrogge) [inline src/vs/platform/terminal/node/terminalProcess.ts]:
```suggestion
		@IProductService private readonly _productService: IProductService
```

File: src/vs/workbench/contrib/terminal/common/scripts/psreadline/cgmanifest.json [hunk 15]
```diff
@@ -0,0 +1,38 @@
+{
+  "registrations": [
+    {
+      "component": {
+        "type": "git",
+        "git": {
+          "name": "PSReadLine",
+          "repositoryUrl": "https://github.com/PowerShell/PSReadLine",
+          "commitHash": "abc123"
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/common/scripts/psreadline/cgmanifest.json]: TODO: real commit hash

File: src/vs/workbench/contrib/terminal/common/scripts/psreadline/PSReadLine.psd1 [hunk 16]
```diff
@@ -0,0 +1,19 @@
+@{
+RootModule = 'PSReadLine.psm1'
+NestedModules = @("Microsoft.PowerShell.PSReadLine.dll")
+ModuleVersion = '2.4.3'
+GUID = '5714753b-2afd-4492-a5fd-01d9e2cff8b5'
+Author = 'Microsoft Corporation'
+CompanyName = 'Microsoft Corporation'
+Copyright = '(c) Microsoft Corporation. All rights reserved.'
+Description = 'Great command line editing in the PowerShell console host'
+PowerShellVersion = '5.1'
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/common/scripts/psreadline/PSReadLine.psd1:10]: I'm surprised this is 5.1 🤔

Comment (andyleejordan) [reply src/vs/workbench/contrib/terminal/common/scripts/psreadline/PSReadLine.psd1:10]: Don't look too closely...I found net6.0 references still existing in the codebase...for building its unit tests on macOS/Linux...which I then found hadn't been done in _years_.

File: src/vs/workbench/contrib/terminal/common/scripts/psreadline/cgmanifest.json [hunk 17]
```diff
@@ -0,0 +1,38 @@
...
+        }
+      },
+      "licenseDetail": [
+        "Copyright (c) 2013, Jason Shirk",
```
Comment (andyleejordan) [inline src/vs/workbench/contrib/terminal/common/scripts/psreadline/cgmanifest.json:15]: It concerns me that we never updated this to be assigned to Microsoft Corporation 😬

File: src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1 [hunk 18]
```diff
@@ -169,6 +169,18 @@ elseif ((Test-Path variable:global:GitPromptSettings) -and $Global:GitPromptSett
 	[Console]::Write("$([char]0x1b)]633;P;PromptType=posh-git`a")
 }
 
+
+if (-not (Get-Module -Name PSReadLine)) {
+	# pwsh version 7+ is required for accessibility support in PSReadLine
```
Comment (andyleejordan) [inline src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]: I just want to clarify where this requirement is coming from? I don't know of a technical reason beyond 5.1 being a lot less reliable than 7 and feature-frozen.

**Comment by Tyriar** [comment]
Red CI

File: src/vs/platform/terminal/node/terminalEnvironment.ts [hunk 19]
```diff
@@ -112,6 +112,7 @@ export async function getShellIntegrationInjection(
 	}
 	// Windows
 	if (isWindows) {
+		envMixin['VSCODE_A11Y_MODE'] = options.isScreenReaderOptimized ? '1' : '0';
```
Comment (Tyriar) [inline src/vs/platform/terminal/node/terminalEnvironment.ts]: We want to do this near the `VSCODE_STABLE` one and for pwsh only.

File: src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1 [hunk 20]
```diff
@@ -169,6 +169,14 @@ elseif ((Test-Path variable:global:GitPromptSettings) -and $Global:GitPromptSett
 	[Console]::Write("$([char]0x1b)]633;P;PromptType=posh-git`a")
 }
 
+
+if (-not (Get-Module -Name PSReadLine) -and $env:VSCODE_A11Y_MODE) {
+	$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
+	$specialPsrlPath = Join-Path $scriptRoot '\psreadline\'
+	Import-Module $specialPsrlPath
+}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]: We should be unsetting `VSCODE_A11Y_MODE` like we do here:

https://github.com/microsoft/vscode/blob/e921a2ee51491b6b2b3825a7eded370760acc624/src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1#L29-L33

File: src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1 [hunk 21]
```diff
@@ -169,6 +169,14 @@ elseif ((Test-Path variable:global:GitPromptSettings) -and $Global:GitPromptSett
 	[Console]::Write("$([char]0x1b)]633;P;PromptType=posh-git`a")
 }
 
+
+if (-not (Get-Module -Name PSReadLine) -and $env:VSCODE_A11Y_MODE) {
+	$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
+	$specialPsrlPath = Join-Path $scriptRoot '\psreadline\'
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]: Guessing you don't need the `\`? Looks wrong seeing that since this is meant to work across platforms.

File: src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1 [hunk 22]
```diff
@@ -169,6 +169,14 @@ elseif ((Test-Path variable:global:GitPromptSettings) -and $Global:GitPromptSett
...
+	Import-Module $specialPsrlPath
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]: We don't need to set that flag anymore?

**Review by Tyriar — DISMISSED** [review]

**Comment by Tyriar** [comment]
Windows pwsh: 
image

File: src/vs/platform/terminal/node/terminalEnvironment.ts [hunk 23]
```diff
@@ -124,6 +124,7 @@ export async function getShellIntegrationInjection(
 			newArgs = [...newArgs]; // Shallow clone the array to avoid setting the default array
 			newArgs[newArgs.length - 1] = format(newArgs[newArgs.length - 1], appRoot, '');
 			envMixin['VSCODE_STABLE'] = productService.quality === 'stable' ? '1' : '0';
+			envMixin['VSCODE_A11Y_MODE'] = options.isScreenReaderOptimized ? '1' : '0';
```
Comment (Tyriar) [inline src/vs/platform/terminal/node/terminalEnvironment.ts]: Don't we need to do this when not Windows as well?

File: src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1 (hunk 22 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]: meaning remove the accessibility flag and just do this whenever the psreadline module is not installed? 

I think we still need the flag if we're going to try to load our special one for macOS because we'll first have to unimport the current version?

File: src/vs/workbench/contrib/chat/browser/chatContentParts/test.ps1
Comment (Tyriar) [inline src/vs/workbench/contrib/chat/browser/chatContentParts/test.ps1:1]: This shouldn't be included

File: src/vs/workbench/contrib/terminal/common/scripts/psreadline/Microsoft.PowerShell.PSReadLine.dll
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/scripts/psreadline/Microsoft.PowerShell.PSReadLine.dll:1]: You should do a product build to make sure all the relevant files are included in the packaged distributables and work when installed.

File: src/vs/workbench/contrib/terminal/common/scripts/psreadline/cgmanifest.json [hunk 24]
```diff
@@ -0,0 +1,40 @@
...
+      "component": {
+        "type": "git",
+        "git": {
+          "name": "PSReadLine",
+          "repositoryUrl": "https://github.com/PowerShell/PSReadLine",
+          "commitHash": "b5aac30d26ce777497e85203dc59989296b73f8e"
+        }
+      },
+			"version": "2.4.4-beta4",
+      "licenseDetail": [
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/scripts/psreadline/cgmanifest.json]:
```suggestion
      },
      "version": "2.4.4-beta4",
      "licenseDetail": [
```

File: src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1 [hunk 25]
```diff
@@ -169,6 +173,16 @@ elseif ((Test-Path variable:global:GitPromptSettings) -and $Global:GitPromptSett
 	[Console]::Write("$([char]0x1b)]633;P;PromptType=posh-git`a")
 }
 
+if ($Global:__VSCodeState.IsA11yMode -eq "1") {
+	if (Get-Module -Name PSReadLine) {
+		return
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]: ⚠️ I think this will exit the entire script

File: src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1 [hunk 26]
```diff
@@ -169,6 +173,16 @@ elseif ((Test-Path variable:global:GitPromptSettings) -and $Global:GitPromptSett
...
+	}
+	$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
+	$specialPsrlPath = Join-Path $scriptRoot 'psreadline'
+	Import-Module $specialPsrlPath
+	Set-PSReadLineOption -EnableScreenReaderMode
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1]: If `Import-Module` fails and the script continues, `Set-PSReadLineOption` would probably fail as well:

```suggestion
	Import-Module $specialPsrlPath
	if (Get-Module -Name PSReadLine) {
		Set-PSReadLineOption -EnableScreenReaderMode
	}
```

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Review by Tyriar — APPROVED** [review]
Test failures. LGTM provided the product build worked out

**Comment by andyleejordan** [comment]
🥳
