### PR TITLE
provide way to adjust table column size via keyboard

### LINKED ISSUE #221554: No single pointer is provided to drag the "columns headers" to the required position in the "Keyboard shortcuts" Table: A11y_Visual Studio Code Client_Customizations and settings_Keyboard Shortcuts_Dragging movements.
### GIT Hub Tags:
#A11yWCAG2.2; #A11yTCS; #A11ySev2; #Visual Studio Code Client; #BM_Visual Studio Code Client_MAC_JULY2024; #DesktopApp; #WCAG2.5.7; #FTP; #A11yMAS; #Dragging Movements; #MAC; #Device;

### Environment and OS details:
MAC Book Pro 
MAC OS Sonoma Version 14.5
Visual Studio code Insider version 1.92.0

### Reproduction Steps:

1. Open Visual Studio Code Insiders editor
2. Tab Navigate to setting icon.
3. Select "Keyboard shortcuts options" and press enter or Press keyboard shortcut as command K, Command S 
4. Keyboard shortcut table gets opened.
5. Observe that No single pointer is provided to drag the "columns headers" to the required position in the "Keyboard shortcuts" Table.

### Actual behavior:
No single pointer is provided to drag the "columns headers" to the required position in the "Keyboard shortcuts" Table.

### Expected behavior:
There should be single pointer provided to drag the "columns headers" to the required position in the "Keyboard shortcuts" Table.

### User Impact:
People with motor impairments who cannot operate content because the only way to actuate a function is by dragging a target element from its initial position to some other position will face difficulty in accessing the application.

### Attachments:

https://github.com/user-attachments/assets/ae697a5e-89ea-4831-8c96-beff3756824f

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #221554

https://github.com/user-attachments/assets/ac648a2c-73d4-4666-8dfd-09ac5b3cff18

### CODE REVIEW

File: src/vs/workbench/contrib/list/browser/tableColumnResizeQuickPick.ts [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+		this.add(quickPick.onDidAccept(() => {
+			const percentage = Number.parseInt(quickPick.value);
+			if (!isNaN(percentage)) {
+				this._table.resizeColumn(index, percentage);
+				quickPick.hide();
+				return;
+			}
+		}));
+		this.add(quickPick.onDidChangeValue(() => this._validateColumnResizeValue(quickPick)));
+	}
```
Comment (TylerLeonhardt) [inline src/vs/workbench/contrib/list/browser/tableColumnResizeQuickPick.ts:62]: Do you think it would be a little easier if you just used the `pick` and `input` APIs?:

```ts
const items: IColumnResizeQuickPickItem[] = [];
this._table.getColumnLabels().forEach((label, index) => {
	if (label) {
		items.push({ label, index });
	}
 });
const column = await quickInputService.pick<IColumnResizeQuickPickItem>(
	items,
	{
		placeHolder: localize('table.column.selection', "Select the column to resize, type to filter."),
	}
);
if (!column) {
	return;
}
const percentage = await quickInputService.input({
	placeHolder: localize('table.column.resizeValue.placeHolder', "i.e. 20, 60, 100..."),
	prompt: localize('table.column.resizeValue.prompt', "Please enter a width in percentage for the '{0}' column.", column.label),
	validateInput: (input: string) => this._newValidateColumnResizeValue(input),
});
if (!percentage) {
	return;
}
this._table.resizeColumn(column.index, percentage);
```

where `_newValidateColumnResizeValue` is:
```ts
const percentage = Number.parseInt(input);
if (!Number.isInteger(percentage)) {
	return {
		content: localize('table.column.resizeValue.invalidType', "Please enter an integer."),
		severity: Severity.Error
	};
} else if (percentage < 0 || percentage > 100) {
	return {
		content: localize('table.column.resizeValue.invalidRange', "Please enter a number greater than 0 and less than or equal to 100."),
		severity: Severity.Error
	};
} else {
	return undefined;
}
```

Comment (TylerLeonhardt) [reply src/vs/workbench/contrib/list/browser/tableColumnResizeQuickPick.ts]: btw, I have not tested this code. I used the TS compiler in my brain (not very accurate)

File: src/vs/workbench/contrib/list/browser/listResizeColumnAction.ts [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+		});
+	}
+
+	async run(accessor: ServicesAccessor): Promise<void> {
+		const listService = accessor.get(IListService);
+		const instantiationService = accessor.get(IInstantiationService);
+
+		const list = listService.lastFocusedList;
+		if (list instanceof Table) {
+			await instantiationService.createInstance(TableColumnResizeQuickPick, list).show();
```
Comment (TylerLeonhardt) [inline src/vs/workbench/contrib/list/browser/listResizeColumnAction.ts:37]: Your call but `TableColumnResizeQuickPick` feels pretty small at this point. You could probably just in-line it here.

File: src/vs/workbench/contrib/list/browser/tableColumnResizeQuickPick.ts [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+		if (!column) {
+			return;
+		}
+		const value = await this._quickInputService.input({
+			placeHolder: localize('table.column.resizeValue.placeHolder', "i.e. 20, 60, 100..."),
+			prompt: localize('table.column.resizeValue.prompt', "Please enter a width in percentage for the '{0}' column.", column.label),
+			validateInput: (input: string) => this._validateColumnResizeValue(input)
+		});
+		const percentageValue = value ? Number.parseInt(value) : undefined;
+		if (!percentageValue || Number.isNaN(percentageValue)) {
```
Comment (TylerLeonhardt) [inline src/vs/workbench/contrib/list/browser/tableColumnResizeQuickPick.ts:41]: The NaN check is redundant, right? Because your validation function handles that case? `value` will only ever be a result that satisfies your `validateInput` function

File: src/vs/workbench/contrib/list/browser/tableColumnResizeQuickPick.ts [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+			return {
+				content: localize('table.column.resizeValue.invalidType', "Please enter an integer."),
+				severity: Severity.Error
+			};
+		} else if (percentage < 0 || percentage > 100) {
+			return {
+				content: localize('table.column.resizeValue.invalidRange', "Please enter a number greater than 0 and less than or equal to 100."),
+				severity: Severity.Error
+			};
+		}
```
Comment (TylerLeonhardt) [inline src/vs/workbench/contrib/list/browser/tableColumnResizeQuickPick.ts:59]: I forgot that you can just return `string` here and it'll use `Severity.Error` by default making this even simpler!:

```suggestion
		if (input && !Number.isInteger(percentage)) {
			return localize('table.column.resizeValue.invalidType', "Please enter an integer.");
		} else if (percentage < 0 || percentage > 100) {
			return localize('table.column.resizeValue.invalidRange', "Please enter a number greater than 0 and less than or equal to 100.");
		}
```

File: src/vs/workbench/contrib/list/browser/listResizeColumnAction.ts (hunk 2 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/list/browser/listResizeColumnAction.ts:37]: I'd like to encapsulate it

**Review by TylerLeonhardt — DISMISSED** [review]

File: src/vs/base/browser/ui/table/tableWidget.ts [hunk 5]
```diff
@@ -198,6 +199,7 @@ export class Table<TRow> implements ISpliceable<TRow>, IDisposable {
 		_options?: ITableOptions<TRow>
 	) {
 		this.domNode = append(container, $(`.monaco-table.${this.domId}`));
+		this.columns = columns;
```
Comment (Tyriar) [inline src/vs/base/browser/ui/table/tableWidget.ts:202]: Could save this and the private line by adding `private columns` to the ctor, similar to `virtualDelegate`?

File: src/vs/workbench/contrib/list/browser/listResizeColumnAction.ts [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+import { localize } from 'vs/nls';
+
+export class ListResizeColumnAction extends Action2 {
+	constructor() {
+		super({
+			id: 'list.resizeColumn',
+			title: { value: localize('list.resizeColumn', "Resize Column"), original: 'Resize Column' },
+			category: { value: localize('list', "List"), original: 'List' },
+			keybinding: {
+				primary: KeyCode.F8,
```
Comment (Tyriar) [inline src/vs/workbench/contrib/list/browser/listResizeColumnAction.ts:22]: F8 is one of my very commonly used keybindings, always annoys me when extensions override this.

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/list/browser/listResizeColumnAction.ts (hunk 6 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/list/browser/listResizeColumnAction.ts:22]: Oh yes, I had forgotten to remove this keybinding, thanks

**Review by Tyriar — APPROVED** [review]
