### PR TITLE
Correct handling of ZDOTDIR variable to avoid crashing terminal

### LINKED ISSUE #160889: Terminal disappears immediately on new VSCode window that was opened by other vscode window
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.72.0-insider (Universal) 17c77dd9bc6af406be11e45e11627b72fba507e7
- OS Version: macOS 12.6

Steps to Reproduce:

1. open terminal tab on vscode
2. type `code-insiders ${other_directory}` in terminal on vscode
3. try to open terminal on opened vscode window

https://user-images.githubusercontent.com/1955233/190109466-4e237b3f-28ed-4563-9220-41862b9a241b.mov

### PR DESCRIPTION
**Pull request by yamachu**
fix: https://github.com/microsoft/vscode/issues/160889
ref: https://github.com/microsoft/vscode/issues/160920

When vscode is started from the integrated terminal, the environment variables are taken over.
Therefore, the `ZDOTDIR` of the starting vscode is oriented to the tmp directory(`os.tmpdir()`).
This causes a problem that the user's `ZDOTDIR` cannot be reflected.
It also causes an infinite loop of calling .zshenv in tmpdir from .zshenv in tmpdir( This seems to be causing the zsh crashes I have reported ).
Therefore, I have changed the allocation method of `USER_ZDOTDIR`.

This behavior was discovered by inserting the following code into the code below (between line 4 and 5)
https://github.com/microsoft/vscode/blob/17bb582b8580e77ec7eaf59f980a3f7b3dfde541/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-env.zsh#L4-L5

```sh
env > ~/vscode-debug/$(gdate +%s)
```

## How to verfify

```
$ yarn; yarn watch
$ ./scripts/code.sh
# on opened vscode integrated terminal
$ cd ${PATH_TO_VSCODE_REPO_DIRECTORY}
$ ./scripts/code-cli.sh .
# on opened new vscode instance
# try to open terminal tab
```

## Additional

from iTerm2 env dump

```
SHLVL=2
HOME=/Users/yk-yamada
GIT_ASKPASS=/Users/yk-yamada/Projects/github.com/yamachu/vscode/extensions/git/out/askpass.sh
VSCODE_GIT_ASKPASS_NODE=/Users/yk-yamada/Projects/github.com/yamachu/vscode/.build/electron/Code - OSS.app/Contents/Frameworks/Code - OSS Helper.app/Contents/MacOS/Code - OSS Helper
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
VSCODE_GIT_ASKPASS_MAIN=/Users/yk-yamada/Projects/github.com/yamachu/vscode/extensions/git/out/askpass-main.js
VSCODE_GIT_IPC_HANDLE=/var/folders/s6/yfw89gs13k78dfw2pdpj3w6h0000gp/T/vscode-git-2152275826.sock
VSCODE_INJECTION=1
ZDOTDIR=/var/folders/s6/yfw89gs13k78dfw2pdpj3w6h0000gp/T/yk-yamada-vscode-zsh
USER_ZDOTDIR=/Users/yk-yamada
_=/usr/bin/env
```

vscode that was run from integrated vscode zsh
```
SHLVL=4
HOME=/Users/yk-yamada
ZDOTDIR=/var/folders/s6/yfw89gs13k78dfw2pdpj3w6h0000gp/T/yk-yamada-vscode-zsh
USER_ZDOTDIR=/var/folders/s6/yfw89gs13k78dfw2pdpj3w6h0000gp/T/yk-yamada-vscode-zsh
GIT_ASKPASS=/Users/yk-yamada/Projects/github.com/yamachu/vscode/extensions/git/out/askpass.sh
VSCODE_GIT_ASKPASS_NODE=/Users/yk-yamada/Projects/github.com/yamachu/vscode/.build/electron/Code - OSS.app/Contents/Frameworks/Code - OSS Helper.app/Contents/MacOS/Code - OSS Helper
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
VSCODE_GIT_ASKPASS_MAIN=/Users/yk-yamada/Projects/github.com/yamachu/vscode/extensions/git/out/askpass-main.js
VSCODE_GIT_IPC_HANDLE=/var/folders/s6/yfw89gs13k78dfw2pdpj3w6h0000gp/T/vscode-git-8ecc674759.sock
VSCODE_INJECTION=1
_=/usr/bin/env
```

with this fix
```
SHLVL=4
HOME=/Users/yk-yamada
ZDOTDIR=/var/folders/s6/yfw89gs13k78dfw2pdpj3w6h0000gp/T/yk-yamada-vscode-zsh
USER_ZDOTDIR=/Users/yk-yamada
GIT_ASKPASS=/Users/yk-yamada/Projects/github.com/yamachu/vscode/extensions/git/out/askpass.sh
VSCODE_GIT_ASKPASS_NODE=/Users/yk-yamada/Projects/github.com/yamachu/vscode/.build/electron/Code - OSS.app/Contents/Frameworks/Code - OSS Helper.app/Contents/MacOS/Code - OSS Helper
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
VSCODE_GIT_ASKPASS_MAIN=/Users/yk-yamada/Projects/github.com/yamachu/vscode/extensions/git/out/askpass-main.js
VSCODE_GIT_IPC_HANDLE=/var/folders/s6/yfw89gs13k78dfw2pdpj3w6h0000gp/T/vscode-git-8ecc674759.sock
VSCODE_INJECTION=1
_=/usr/bin/env
```

### CODE REVIEW

File: src/vs/platform/terminal/node/terminalEnvironment.ts [hunk 1]
```diff
@@ -188,7 +188,10 @@ export function getShellIntegrationInjection(
 			const zdotdir = path.join(os.tmpdir(), `${os.userInfo().username}-vscode-zsh`);
 			envMixin['ZDOTDIR'] = zdotdir;
 			const userZdotdir = env?.ZDOTDIR ?? os.homedir() ?? `~`;
-			envMixin['USER_ZDOTDIR'] = userZdotdir;
+			// NOTE: When vscode is started from the integrated terminal, the environment variables are taken over.
+			// The ZDOTDIR variable is oriented to os.tmpdir(), so we cannot reuse.
+			// Therefore, we use USER_ZDOTDIR variable that is inherited.
+			envMixin['USER_ZDOTDIR'] = env?.USER_ZDOTDIR ?? userZdotdir;
```
Comment (meganrogge) [inline src/vs/platform/terminal/node/terminalEnvironment.ts:194]: thanks for this explanation - it makes a lot of sense. 

While this change would fix it, I think perhaps better would be to remove this line

https://github.com/microsoft/vscode/blob/3161548771dc0e01556e7116bbcd57e0aaa32a26/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-env.zsh#L12

Comment (yamachu) [reply src/vs/platform/terminal/node/terminalEnvironment.ts:194]: By deleting that one line, it is no longer necessary to modify `src/vs/platform/terminal/node/terminalEnvironment.ts` !
It makes more sense that way.

Comment (yamachu) [reply src/vs/platform/terminal/node/terminalEnvironment.ts]: Oops, but if I incorporate that change, command actions, etc. won't work...

Comment (yamachu) [reply src/vs/platform/terminal/node/terminalEnvironment.ts]: Then I think it would be better to revert these two commits, what do you think?
https://github.com/microsoft/vscode/pull/161433/commits/4c6670df6fb68e10267406a66c171b4d99cde190
https://github.com/microsoft/vscode/pull/161433/commits/bcfad3268a11e807f4a611e6f4e64fbb929d3abe

In short, it is the state of the code at the phase you have reviewed.

Comment (Tyriar) [reply src/vs/platform/terminal/node/terminalEnvironment.ts]: > While this change would fix it, I think perhaps better would be to remove this line, which sets the `ZDOTDIR` back to the vscode one unnecessarily
> 
> https://github.com/microsoft/vscode/blob/3161548771dc0e01556e7116bbcd57e0aaa32a26/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-env.zsh#L12

@meganrogge I think the model was when we enter and exit any zsh init script we want our zdotdir to be set to `$VSCODE_ZDOTDIR`, such that our login, rc, etc. correctly get run. With the exception of rc where we do not which is what this was about:

https://github.com/microsoft/vscode/blob/430f212a16b1575e10a562b709f52399869401d7/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh#L131-L133

Should we be doing that in login shells as well? It appears `$ZDOTDIR` remains the vscode path for login shells:

https://github.com/microsoft/vscode/blob/430f212a16b1575e10a562b709f52399869401d7/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh#L19-L24

Could that instead be this?

```ts
if [[ $options[norcs] = off  && -f $USER_ZDOTDIR/.zshrc ]]; then 
 	VSCODE_ZDOTDIR=$ZDOTDIR 
 	ZDOTDIR=$USER_ZDOTDIR 
 	. $USER_ZDOTDIR/.zshrc
 fi 
```

And then remove this:

https://github.com/microsoft/vscode/blob/430f212a16b1575e10a562b709f52399869401d7/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh#L131-L133

Since `$USER_ZDOTDIR` is not actually set when `$VSCODE_INJECTION !== 1`

Comment (meganrogge) [reply src/vs/platform/terminal/node/terminalEnvironment.ts]: Yes I had reversed the order of the startup files and was thinking `env` runs last, but you're correct

Comment (meganrogge) [reply src/vs/platform/terminal/node/terminalEnvironment.ts]: and we might also want to add a `shellIntegration-logout.zsh` file ?

Comment (meganrogge) [reply src/vs/platform/terminal/node/terminalEnvironment.ts]: Screen Shot 2022-09-23 at 1 02 08 PM

Comment (Tyriar) [reply src/vs/platform/terminal/node/terminalEnvironment.ts]: On logout I think we don't need to run anything special so if it was the regular `$ZDOTDIR` at that point it would work fine

Comment (meganrogge) [reply src/vs/platform/terminal/node/terminalEnvironment.ts]: yeah but if we fix it in the `zshrc`, then `.zlogin` won't get run

Comment (meganrogge) [reply src/vs/platform/terminal/node/terminalEnvironment.ts]: so I believe we need to set it back in `shellIntegration-login.zsh`

Comment (Tyriar) [reply src/vs/platform/terminal/node/terminalEnvironment.ts]: Yes you're right, whatever the last thing is we want to set it to the user's ZDOTDIR there (H for login, D for non-login)

Comment (meganrogge) [reply src/vs/platform/terminal/node/terminalEnvironment.ts]: so confusing 😅 thus my bad suggestion at the start of this thread

Comment (meganrogge) [reply src/vs/platform/terminal/node/terminalEnvironment.ts]: @yamachu sorry for the confusion. pls let us know if you'd like us to take it from here

**Comment by meganrogge** [comment]
@yamachu after investigating this, your initial fix was correct

**Review by meganrogge — APPROVED** [review]

**Review by rzhao271 — APPROVED** [review]

**Comment by yamachu** [comment]
@meganrogge Thanks for sharing your summary of the discussion.
I hope this Issue will be resolved in a better way 👍

**Comment by meganrogge** [comment]
Just realized that the fix I reference in the PR which mentions this one should fix this issue such that this workaround won't be necessary. 

I hadn't thought so until now because was testing using code oss and launching from a zsh login shell in insiders where zdotdir is incorrectly set to our temp directory (so appeared to not work).
