### PR TITLE
don't show python completions when subshell is exited

### LINKED ISSUE #282518: Getting python completions after exiting python subshell
> Steps to reproduce this:
> 1. New terminal
> 2. enter `python3` to enter interactive python shell 
> 3. `<CTRL-D>` OR `quit()` OR `exit()` to leave interactive shell, back to normal terminal.
> 4. All commands will now show python completions  

 _Originally posted by @Wim-De-Clercq in [#282474](https://github.com/microsoft/vscode/issues/282474#issuecomment-3637040191)_

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #282518

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 1]
```diff
@@ -1983,10 +1989,22 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 		await this._processManager.setDimensions(rawXterm.cols, rawXterm.rows);
 	}
 
+	private _restorePrimaryShellTypeAfterNestedProcessExit(): void {
+		if (this._shellType === GeneralShellType.Python && this._primaryShellType && this._primaryShellType !== GeneralShellType.Python) {
+			this.setShellType(this._primaryShellType);
+		}
+	}
```
[the remark this answers is not in the document]
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts]: Yeah we should probably do this

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/lspCompletionProviderAddon.ts [hunk 2]
```diff
@@ -26,12 +28,14 @@ export class LspCompletionProviderAddon extends Disposable implements ITerminalA
...
 		textVirtualModel: IReference<IResolvedTextEditorModel>,
 		lspTerminalModelContentProvider: LspTerminalModelContentProvider,
+		shellType: TerminalShellType,
 	) {
 		super();
 		this._provider = provider;
 		this._textVirtualModel = textVirtualModel;
 		this._lspTerminalModelContentProvider = lspTerminalModelContentProvider;
 		this.triggerCharacters = provider.triggerCharacters ? [...provider.triggerCharacters, ' ', '('] : [' ', '('];
+		this.shellTypes = [shellType];
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/lspCompletionProviderAddon.ts]: As we discussed, I think we should hardcode `shellType` to `GeneralShellType.Python` here so that this only gets invoked for that `shellType`. It also simplifies things.

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/suggest/browser/lspCompletionProviderAddon.ts]: Anthony found he does this here https://github.com/microsoft/vscode/blob/71f35296d274d709681d3b7084ad0e42afe84240/src/vs/workbench/contrib/terminalContrib/suggest/browser/lspTerminalUtil.ts#L8-L17

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/suggest/browser/lspCompletionProviderAddon.ts]: So we can revert these changes

**Comment by anthonykim1** [comment]
Just verified this, I think we are good just with the shell type defined in lspCompletionAddonProvider:

https://github.com/user-attachments/assets/122c1d34-d4ac-4c1f-af5a-761e5c35621e

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/lspCompletionProviderAddon.ts [hunk 3]
```diff
@@ -21,6 +22,7 @@ export class LspCompletionProviderAddon extends Disposable implements ITerminalA
 	private _provider: CompletionItemProvider;
 	private _textVirtualModel: IReference<IResolvedTextEditorModel>;
 	private _lspTerminalModelContentProvider: LspTerminalModelContentProvider;
+	shellTypes: TerminalShellType[] = [GeneralShellType.Python];
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/lspCompletionProviderAddon.ts]:
```suggestion
	readonly shellTypes: TerminalShellType[] = [GeneralShellType.Python];
```

**Review by Tyriar — DISMISSED** [review]

**Review by anthonykim1 — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]
