### PR TITLE
migrate run task, get task output to core, fix bugs

### LINKED ISSUE #256555: `get_task_output` tool has multiple issues with task identification and output retrieval
- Copilot Chat Extension Version: 0.30.2025071701
- VS Code Version:
- Version: 1.103.0-insider (user setup)
Commit: 344abe8f7ce560f4883e1542669dd96e5118c767
Date: 2025-07-17T05:03:44.028Z
Electron: 35.6.0
ElectronBuildId: 11847422
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Windows_NT x64 10.0.19045
- OS Version:
- Feature (e.g. agent/edit/ask mode): agent
- Selected model (e.g. GPT 4.1, Claude 3.7 Sonnet): Claude Sonnet 4
- Logs: sorry don't know how to get those?  wait... I can see the 'cancelled' error at least in dev tools console I'll include that after.

**Summary:**
The `get_task_output` tool has two critical issues: 1) Using incorrect task IDs returns output from wrong tasks, and 2) Using correct task IDs causes the tool to fail silently despite appearing successful.

Steps to Reproduce:

**Issue 1: Wrong task output returned**
1. Set up workspace with multiple npm tasks running via VS Code tasks.json
2. Have tasks with labels like "Start Generic Import App", "Start Studio", etc.
3. Use AI assistant with `get_task_output` tool
4. Call `get_task_output` with incorrect task ID format: `"npm: Start Generic Import App"`
5. Observe tool returns output from different task

**Issue 2: Silent failure with correct task ID**
1. Same setup as above
2. Call `get_task_output` with correct task ID: `"Start Generic Import App"`
3. Tool shows successful execution but returns no content

**Actual response received:**

```
<function_results>The user cancelled the tool call.</function_results>
```

*(Note: User did not actually cancel - this appears to be a false message)*

**Expected Behavior:**
- Incorrect task IDs should return an error or "task not found" message
- Correct task IDs should return the actual terminal output from the specified task

**Actual Behavior:**
- **Issue 1:** When requesting "npm: Start Generic Import App", receives "Output for task Start Studio" with Studio output
- **Issue 2:** When requesting "Start Generic Import App" (correct), tool appears to execute successfully but returns "The user cancelled the tool call" message without any actual output

**Additional Context:**
- All tasks are running successfully (confirmed by build output and running processes)
- Pattern is consistent across multiple attempts
- The incorrect ID format seems to fall back to returning a different task's output rather than erroring
- This significantly limits AI assistant's ability to help with development tasks and debugging

Screenshot of error the agent gets when trying to call the tool

Image

### LINKED ISSUE #257100: move run in task tool to core
This will likely fix issues like https://github.com/microsoft/vscode-copilot-issues/issues/98 and https://github.com/microsoft/vscode/issues/256555

### PR DESCRIPTION
**Pull request by meganrogge**
To defer:
- move out of `terminalContrib` into `task contrib` if it won't cause layering issues
- move over `CreateAndRunTask` tool
- remove temporary setting
- remove all 3 tools from copilot

fixes https://github.com/microsoft/vscode/issues/256555
fixes #257100

### CODE REVIEW

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 1]
```diff
@@ -2438,6 +2438,10 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
 		return folder;
 	}
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:2440]: @tyriar this is to avoid import violation. very unfortunate that due to layering warning, cannot just return `ITerminalInstance` here

**Comment by meganrogge** [comment]
@Tyriar eager to merge this as I think it'll fix the issues people have been seeing. Can do any refactoring or cleanup tomorrow.

**Review by DonJayamanne — APPROVED** [review]

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/task.chatAgentTools.contribution.ts [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+		const runTaskTool = instantiationService.createInstance(RunTaskTool);
+		this._register(toolsService.registerToolData(RunTaskToolData));
+		this._register(toolsService.registerToolImplementation(RunTaskToolData.id, runTaskTool));
+
+		const getTaskOutputTool = instantiationService.createInstance(GetTaskOutputTool);
+		this._register(toolsService.registerToolData(GetTaskOutputToolData));
+		this._register(toolsService.registerToolImplementation(GetTaskOutputToolData.id, getTaskOutputTool));
+	}
+}
+registerWorkbenchContribution2(ChatAgentToolsContribution.ID, ChatAgentToolsContribution, WorkbenchPhase.AfterRestored);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/task.chatAgentTools.contribution.ts:36]: I think moving this to task land is just a matter of putting this workbench contribution into the tasks folder.

Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/task.chatAgentTools.contribution.ts:36]: @tyriar as expected, sharing the buffer output tools is the issue across the layers

Screenshot 2025-07-22 at 2 52 42 PM
