### PR TITLE
Fix bug causing recommendations to sometimes appear in two places

### LINKED ISSUE #53646: Recommended Extensions shows already installed extensions.
- VSCode Version: 1.25.0
- OS Version: Windows 10, version 1709, OS Build 16299.492

Steps to Reproduce:

1. Open extensions
2. Look at recommended extensions

extensions

I hope i post this at the correct place.
I find that showing already installed extensions in recommended extensions is not how it is intended to work.

### PR DESCRIPTION
**Pull request by JacksonKearl**
Closes #53646

### CODE REVIEW

File: src/vs/workbench/parts/extensions/electron-browser/extensionTipsService.ts [hunk 1]
```diff
@@ -120,17 +120,15 @@ export class ExtensionTipsService extends Disposable implements IExtensionTipsSe
...
-				this.fetchFileBasedRecommendations();
-				this.fetchExperimentalRecommendations();
-				return this.promptWorkspaceRecommendations();
-			}).then(() => {
-				this._modelService.onModelAdded(this.promptFiletypeBasedRecommendations, this, this._disposables);
-				this._modelService.getModels().forEach(model => this.promptFiletypeBasedRecommendations(model));
-			});
+		this.fetchCachedDynamicWorkspaceRecommendations();
+		this.fetchFileBasedRecommendations();
+		this.fetchExperimentalRecommendations();
```
Comment (ramya-rao-a) [inline src/vs/workbench/parts/extensions/electron-browser/extensionTipsService.ts]: While moving the above out of the wait for workspace recommendations promise does seem to fix the issue, it isnt clear why it does so.

`queryLocal` adds recommendation sources only after `getAllReccomendations` promise is resolved. So why is the bug occuring in the first place?

Comment (ramya-rao-a) [reply src/vs/workbench/parts/extensions/electron-browser/extensionTipsService.ts]: As discussed, `getAllRecommendations` only returns the value of the `this._fileBasedRecommendations` variable which will be empty unless we make this change.

So this fix is good

**Review by ramya-rao-a — APPROVED** [review]
