### PR TITLE
Terminal chat: Hide by default, don't create on focus check

### LINKED ISSUE #207751: Unable to hide the chat widget in terminal
Does this issue occur when all extensions are disabled?: Yes/No

- Version: 1.88.0-insider
- Commit: 7107b38665e428a974c06b2c6e8f67a9a078aefd
- Date: 2024-03-13T06:02:12.129Z (1 day ago)
- Electron: 28.2.6
- ElectronBuildId: 27476517
- Chromium: 120.0.6099.291
- Node.js: 18.18.2
- V8: 12.0.267.19-electron.0
- OS: Darwin arm64 23.3.0

Steps to Reproduce:

Absolutely no idea how i ended up in this state, , howver I can no longer close this chat widget

Screenshot 2024-03-15 at 05 55 43

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #207751

I couldn't find a repro, but hopefully this fixes it

### CODE REVIEW

**Review by jrieken — APPROVED** [review]

File: src/vs/workbench/contrib/terminalContrib/chat/browser/terminalChatController.ts [hunk 1]
```diff
@@ -342,7 +342,7 @@ export class TerminalChatController extends Disposable implements ITerminalContr
 	}
 
 	hasFocus(): boolean {
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminalContrib/chat/browser/terminalChatController.ts:344]: how was this creating on focus check before?

Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/chat/browser/terminalChatController.ts:344]: If `_chatWidget`'s `Lazy` object is initialized, calling `.value` will instantiate it on first access
