### PR TITLE
Fix external terminal when the user has no terminal user settings

### LINKED ISSUE #125985: "Open New External Terminal" doesn't work if no terminal settings are present
Issue Type: <b>Bug</b>

To reproduce the error just run `"Open New External Terminal"` from the command palette.

I tried to trace the error and it seems to be here: [src/vs/platform/externalTerminal/node/externalTerminalService.ts:318](https://github.com/microsoft/vscode/blob/1.57.0/src/vs/platform/externalTerminal/node/externalTerminalService.ts#L318) (v1.57.0)

This is the Output from `Log (Window)`:
```
[2021-06-11 00:13:12.312] [renderer1] [error] Cannot read property 'external' of undefined: TypeError: Cannot read property 'external' of undefined
    at Ze.spawnTerminal (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:32:630)
    at Ze.openTerminal (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:31:613)
    at Object.call (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:21:8293)
    at h.onPromise (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:20:7775)
    at h.onRawMessage (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:20:7134)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:20:6387
    at k.fire (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:16:1835)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:14:46850
    at k.fire (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:16:1835)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:14:47016
    at k.fire (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:16:1835)
    at IpcMainImpl.z (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:14:48719)
    at IpcMainImpl.emit (events.js:327:22)
    at Object.<anonymous> (electron/js2c/browser_init.js:165:9692)
    at Object.emit (events.js:315:20)
```

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.895Z)
OS version: Linux x64 5.8.0-55-generic (Ubuntu 20.04.2 LTS)
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.59GB (5.78GB free)|
|Process Argv|--unity-launch --crash-reporter-id bd0b1a29-4ec2-492b-aa2e-e79c19fc6675|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

### PR DESCRIPTION
**Pull request by Tyriar**
The config service on the main process isn't complete which results in the terminal config being undefined if there are no user terminals settings set.

Fixes #125985

### CODE REVIEW

File: src/vs/platform/externalTerminal/node/externalTerminalService.ts [hunk 1]
```diff
@@ -31,20 +29,12 @@ export class WindowsExternalTerminalService extends ExternalTerminalService impl
...
-	}
-
-	public openTerminal(cwd?: string): Promise<void> {
-		const configuration = this._configurationService.getValue<IExternalTerminalConfiguration>();
+	public openTerminal(configuration: IExternalTerminalSettings, cwd?: string): Promise<void> {
 		return this.spawnTerminal(cp, configuration, processes.getWindowsShell(), cwd);
 	}
 
-	public spawnTerminal(spawner: typeof cp, configuration: IExternalTerminalConfiguration, command: string, cwd?: string): Promise<void> {
-		const terminalConfig = configuration.terminal.external;
```
Comment (meganrogge) [inline src/vs/platform/externalTerminal/node/externalTerminalService.ts:46]: so the other way to fix this would've been `configuration?.terminal?.external`, correct?

Comment (Tyriar) [reply src/vs/platform/externalTerminal/node/externalTerminalService.ts:46]: That would have fixed it but other problems could potentially still happen. The reason it's undefined is because the schema doesn't get registered in the main process, plus workspace settings will never work in the main process if we wanted to add that. So the safest option is to pull it in from the renderer that definitely gets the right settings values.

File: src/vs/workbench/contrib/externalTerminal/browser/externalTerminal.contribution.ts [hunk 2]
```diff
@@ -71,7 +72,7 @@ CommandsRegistry.registerCommand({
 				});
 			} else {
 				distinct(targets.map(({ stat }) => stat!.isDirectory ? stat!.resource.fsPath : dirname(stat!.resource.fsPath))).forEach(cwd => {
-					terminalService!.openTerminal(cwd);
+					terminalService!.openTerminal(config.terminal.external, cwd);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/externalTerminal/browser/externalTerminal.contribution.ts:75]: don't you need to check `config?.terminal?.external` here ?

Comment (Tyriar) [reply src/vs/workbench/contrib/externalTerminal/browser/externalTerminal.contribution.ts:75]: No because it's in the renderer where the schema is registered correctly

**Review by meganrogge — APPROVED** [review]
tested it - works well
