### PR TITLE
define our custom `prepareStackTrace` as getter/setter so that it survises subsequent reassignments

### LINKED ISSUE #175288: 'catch-all' error handler is easily confused by source-map-support library
Many extensions, including Github's, [use the source-map-support library](https://github.com/github/codespaces/issues/12468#issuecomment-1442426516), which overwrites `Error.prepareStackTrace` and breaks error telemetry collection for the _entire_ extension host.

This obviously is not a nice way for the library to behave, but we should try to find a less-fragile way to correlate errors than overriding `prepareStackTrace`. For example, we could parse the stacktrace once the error is caught instead/as a fallback, or `Object.defineProperty(Error, 'prepareStackTrace', ...)` to make it a getter/setter that ensures the tracking function is called.

https://github.com/microsoft/vscode/blob/89781185b9b78834f2e032cf611397b87bcae836/src/vs/workbench/api/common/extensionHostMain.ts#L72

### PR DESCRIPTION
**Pull request by jrieken**
fixes https://github.com/microsoft/vscode/issues/175288

### CODE REVIEW

File: src/vs/workbench/api/common/extensionHostMain.ts [hunk 1]
```diff
@@ -67,9 +67,10 @@ abstract class ErrorHandler {
 		const map = await extensionService.getExtensionPathIndex();
 		const extensionErrors = new WeakMap<Error, ExtensionIdentifier | undefined>();
 
+		// PART 1
 		// set the prepareStackTrace-handle and use it as a side-effect to associate errors
 		// with extensions - this works by looking up callsites in the extension path index
-		(<any>Error).prepareStackTrace = (error: Error, stackTrace: errors.V8CallSite[]) => {
+		function prepareStackTraceAndFindExtension(error: Error, stackTrace: errors.V8CallSite[]) {
 			let stackTraceMessage = '';
```
Comment (connor4312) [inline src/vs/workbench/api/common/extensionHostMain.ts:74]: Small optimization: we should bail if `extensionErrors.has(error)`, since if prepareStackTrace is wrapped more than once (which seems to happen with some library code that Liveshare and Github extensions use) this will be called multiple times.

Comment (jrieken) [reply src/vs/workbench/api/common/extensionHostMain.ts:74]: Do you mean code invoking the function directly instead relying on `Error.stack`? In that case, I could save the `findSubstr` calls but still need to return something, right?

Comment (connor4312) [reply src/vs/workbench/api/common/extensionHostMain.ts:74]: Oh, true. This is probably fine, very small optimization anyway

**Review by connor4312 — APPROVED** [review]
