### PR TITLE
Code Folding won't be remembered after latest update. (fixes #26157)

### LINKED ISSUE #26157: Code Folding won't be remembered after latest update.
Code Folding won't be remembered after latest update.

- VSCode Version: 1.12.1
- OS Version: Windows 10

Steps to Reproduce:

1. Fold some Code in any file.
2. Close that file.
3. Re-open the file and the code folding is gone.

That was by far the nicest feature in VSCode, now it's gone after I updated the app today.

### PR DESCRIPTION
**Pull request by bpasero**
This is a fix for #26157 intended to be pushed to the recovery release. 

Issue (original):
* open an editor
* keep some view state (folding, cursors, scroll position)
* close the editor
* reopen the editor
=> view state is lost

Issue (variant):
* make sure tab preview is enabled (it is by default)
* open an editor
* keep some view state (folding, cursors, scroll position)
* open another editor
* go back to the previous editor
=> view state is lost

We always store the view state of files when you switch between editors or when you close and come back to editors (persisted in local storage). The bug happened during last milestone because the way we dispose resources changed.

Previously:
* close an editor
* persist view state from the editor model
* dispose editor model

Now:
* close an editor
* dispose editor model
* persist view state from editor model
=> since the model is disposed, the view state is undefined

My fix introduces a new event `onWillCloseEditor` directly on the stacks model which the text file editor can use to persist the view state right before the model goes away. On top of that we also only persist the view state when the input is not disposed, because otherwise we still hit the current issue that we try to persist the view state of a disposed model.

@Tyriar can you check the code and let me know what you think? If you guys want to move ahead and release recovery today, feel free to merge. Otherwise I can do it tomorrow.

### CODE REVIEW

**Comment by bpasero** [comment]
Moving to @isidorn since it seems we are not publishing recovery until Monday, so this can wait until tomorrow.

**Comment by bpasero** [comment]
Merging into insiders to get some coverage, will create another PR for stable.

File: src/vs/workbench/common/editor/editorStacksModel.ts [hunk 1]
```diff
@@ -703,6 +703,7 @@ export class EditorStacksModel implements IEditorStacksModel {
 	private _onEditorDirty: Emitter<EditorIdentifier>;
 	private _onEditorLabelChange: Emitter<EditorIdentifier>;
 	private _onEditorOpened: Emitter<EditorIdentifier>;
+	private _onWillCloseEditor: Emitter<EditorIdentifier>;
 	private _onEditorClosed: Emitter<GroupEvent>;
 	private _onModelChanged: Emitter<IStacksModelChangeEvent>;
```
Comment (isidorn) [inline src/vs/workbench/common/editor/editorStacksModel.ts]: Why does `onWillCloseEditor` emit a different event than `onEditorClosed`?
Intuitivly they should emit the same and it makes sense to me that is the `EditorIdentififer`

File: src/vs/workbench/common/editor/editorStacksModel.ts [hunk 2]
```diff
@@ -1155,6 +1161,7 @@ export class EditorStacksModel implements IEditorStacksModel {
 		unbind.push(group.onEditorStateChanged(editor => this._onModelChanged.fire({ group, editor })));
 		unbind.push(group.onEditorOpened(editor => this._onEditorOpened.fire({ editor, group })));
 		unbind.push(group.onEditorClosed(event => {
+			this._onWillCloseEditor.fire({ editor: event.editor, group });
 			this.handleOnEditorClosed(event);
```
Comment (isidorn) [inline src/vs/workbench/common/editor/editorStacksModel.ts]: I checked and you are emiting and handling the `onWillCloseEditor` similar to `onEditorClosed` -> looks good.

File: src/vs/workbench/common/editor/editorStacksModel.ts (hunk 1 above)
Comment (bpasero) [inline src/vs/workbench/common/editor/editorStacksModel.ts]: @isidorn I wanted to keep the change small but you are right, it would make sense to align the events. I wanted to tackle that as a debt item on master.

File: src/vs/workbench/parts/files/browser/editors/textFileEditor.ts [hunk 3]
```diff
@@ -67,6 +70,12 @@ export class TextFileEditor extends BaseTextEditor {
 		}
 	}
 
+	private onWillCloseEditor(e: IEditorIdentifier): void {
+		if (e.editor === this.input && this.position === this.editorGroupService.getStacksModel().positionOfGroup(e.group)) {
```
Comment (isidorn) [inline src/vs/workbench/parts/files/browser/editors/textFileEditor.ts]: It is fine to do the equality check here between editors here? They are actually the same reference?
I understand you do not have an `id` for the editors here.

**Comment by isidorn** [comment]
I added some minor comments, they change looks great in general.
I will just verify it now on insiders if it trully fixes the issue for me.

**Comment by bpasero** [comment]
@isidorn thanks, note that we did not get an insiders update today, but we do have a build to play with.

File: src/vs/workbench/parts/files/browser/editors/textFileEditor.ts (hunk 3 above)
Comment (bpasero) [inline src/vs/workbench/parts/files/browser/editors/textFileEditor.ts]: @isidorn since last milestone, file editor inputs are actually shared when they have the same URI, you can see that here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/editor/browser/editorService.ts#L264

Comment (isidorn) [inline src/vs/workbench/parts/files/browser/editors/textFileEditor.ts]: @bpasero thanks for the clarification

**Comment by isidorn** [comment]
@bpasero I verified this works fine on my mac with unpublished insider build from 2 hours ago.
All in all the PR looks good.

**Comment by bpasero** [comment]
@isidorn thanks
