### PR TITLE
Compress streams in notebook outputs

### LINKED ISSUE #161023: Changes to how stream outputs are handled in Notebooks
Related issues  https://github.com/microsoft/vscode/issues/146768, https://github.com/microsoft/vscode-jupyter/issues/11031

# Multiple Output Items per Output
* Today we can have multiple output items per output
* However all output items in an output must have a unique mime type.
* Thus its not possible to have two stderr output items in the same output.
  This is check is done in `extHostTypes.ensureUniqueMimeTypes`
  I.e. if you were to call `appendOutputItem` with `stdout` multiple times, only the first `stdout` is stored in the model.
  E.g. if you were to call `appendOutputItem` with `stdout` twice with the values `1` and `2` respectively, then you'd end up with a single output item with the value `1` in the model. The second `stdout` output item is ignored.

# Changes to the API
* We will support calling `appendOutputItem` multiple times for the same stream mime types per output.
  However we'd merge the stream output items into one and we'd still end up with a single output item per mime type.
  E.g. if you were to call `appendOutputItem` with `stdout` twice with the values `1` and `2` respectively, then you'd end up with a single output item with the value `12` in the model.

  This change applies only to the stream mime types which include:
    - 'application/vnd.code.notebook.stdout', 
    - 'application/x.notebook.stdout', 
    - 'application/x.notebook.stream', 
    - 'application/vnd.code.notebook.stderr', 
    - 'application/x.notebook.stderr'

# Current approach
Summary: Jupyter extension gets new output for each cell and compresses/merges the outpu items, and replaces the existing output with new output. E.g. if you get a new stream output, we replace the previous output items with a new one.

**Draw backs:**
* Jupyter extension is always replacing existing output with new output
* As Jupyter gets new output, the output grows and this large output is sent to Renderer process and form Renderer process back to Ext Host.
    * I.e. we send large strings back and forth (data sent back and forth grows over time)
    * Sending this ever growing large output back and forth has the potential to crash vs code.
```mermaid
sequenceDiagram
  participant Jupyter
  participant Extension Host
  participant VSCode Renderer Proc
  Jupyter->>Extension Host: Append Kernel Output `Line1` using `Task.appendOutput` 
  Extension Host->>VSCode Renderer Proc: `NotebookTextModel._spliceNotebookCellOutputs2` 
  Note right of VSCode Renderer Proc: Model updated to contain <br/>Output with OutputItem `Line1`
  VSCode Renderer Proc-->>Extension Host: Trigger change event for new Output `Line1`
  Note right of Extension Host: Model updated to contain <br/>Output with OutputItem `Line1`
  Jupyter->>Extension Host: Kernel output is `Line2`<br/>Merge previous outputs with new to get `Line1Line2`<br/>Replace output with new value `Line1Line2`<br/>Using `Task.replaceOutputItems`
  Extension Host->>VSCode Renderer Proc: `NotebookTextModel._replaceNotebookCellOutputItems`
  Note right of VSCode Renderer Proc: Model updated to replace output <br/>with new value `Line1Line2`.
  VSCode Renderer Proc-->>Extension Host: Trigger change event for replace with new output item `Line1Line2`
  Note right of Extension Host: Model updated to replace output <br/>with new value `Line1Line2`.
  Jupyter->>Extension Host: Kernel output is `Line3`<br/>Merge previous outputs with new to get `Line1Line2Line3`<br/>Replace output with new value `Line1Line2Line3`<br/>Using `Task.replaceOutputItems`
  Extension Host->>VSCode Renderer Proc: `NotebookTextModel._replaceNotebookCellOutputItems`
  Note right of VSCode Renderer Proc: Model updated to replace output <br/>with new value `Line1Line2Line3`.
  VSCode Renderer Proc-->>Extension Host: Trigger change event for replace with new output item `Line1Line2Line3`
  Note right of Extension Host: Model updated to replace output <br/>with new value `Line1Line2Line3`.
```

# Why do we need to merge/compress outputs
**Assume we get output from the kernel as follows:**
* First kernel output is `Line1`.
* Second kernel output is `ESC[ALine2`
* Third kernel output is `ESC[ALine3`

Note: Assume `ESC[A` is a special terminal escape sequence that tells the terminal to remove the previous line.

Thus when we get the output `ESC[ALine3`, what needs to be displayed is `Line3` and same `Line3` saved in `*.ipynb` file (the prevous lines need to be dropped).
This compression/merging of outputs needs to happen in realtime, so users can see  updates from terminal progress bars & the like (very common in Jupyter, installing packages and running experiments).

# Proposed Solution
Summary: We send the incremental updates to Renderer process. And instead of appending the new items we compress the new output items with the existing items and replace the existing items with a single output item. I.e. we always have one output item in the cell output.

**Draw backs:**
* Changes to behaviour of existing API or need a new API.  
Current API method is `appendOutputItems`. Today this only supports having multiple output items with distinct mime types.  If one were to call the API with the same mime type, the the new items get dropped.  
The change here allows us to call `appendOutputItems` for the same mime type again without losing this data and this applies to streams mime types.

Optionally we could have a new method `appendStreamOutputItems` to be more explicit about the fact that we have special handling for stream output items.

**Benefits:**
* We only send the new output items (incremental updates) to Renderer process and Extension host. 
* No additional processing required when rendering output in notebook renderer (output items are already merged/compressed)
* No additional processing required when serializing the output in Notebook Serializer (output items are already merged/compressed)
```mermaid
sequenceDiagram
  participant Jupyter
  participant Extension Host
  participant VSCode Renderer Proc
  Jupyter->>Extension Host: Append Kernel Output `Line1` using `Task.appendOutput` 
  Extension Host->>VSCode Renderer Proc: `NotebookTextModel._spliceNotebookCellOutputs2` 
  Note right of VSCode Renderer Proc: Model updated to contain <br/>Output with OutputItem `Line1`
  VSCode Renderer Proc-->>Extension Host: Trigger change event for new Output `Line1`
  Note right of Extension Host: Model updated to contain <br/>Output with OutputItem `Line1`
  Jupyter->>Extension Host: Kernel output is `Line2`<br/>Append new output item with value `Line2` using `Task.appendOutputItem`
  Extension Host->>VSCode Renderer Proc: `NotebookTextModel._appendNotebookCellOutputItems`
  Note right of VSCode Renderer Proc: We now have 2 output items in the output model. `Line`, and `Line2`
  Note right of VSCode Renderer Proc: When sending data to `Notebook Renderer` we need to loop through 2 output items to merge into one.
  VSCode Renderer Proc-->>Extension Host: Trigger change event for append new output item `Line2`
  Note right of Extension Host: Model contains two output items, `Line` and `Line2`.
  Note right of Extension Host: Notebook Serializer needs to loop through 2 output items to merge into one.
  Jupyter->>Extension Host: Kernel output is `Line3`<br/>Append new output item with value `Line3` using `Task.appendOutputItem`
  Extension Host->>VSCode Renderer Proc: `NotebookTextModel._appendNotebookCellOutputItems`
  Note right of VSCode Renderer Proc: We now have 3 output items in the output model. `Line`, `Line2`, and `Line3`
  Note right of VSCode Renderer Proc: When sending data to `Notebook Renderer` we need to loop through 3 output items to merge into one.
  VSCode Renderer Proc-->>Extension Host: Trigger change event for append new output item `Line3`
  Note right of Extension Host: Model contains two output items, `Line1`,`Line2` and `Line3`.
  Note right of Extension Host: Notebook Serializer needs to loop through 3 output items to merge into one.
```

# Solution that we tried and found to not work well
Summary: We send the incremental updates to Renderer process. I.e. we always append output items. As we get new items this list of output items will grow. 

**Draw backs:**
* VS Code renderer process needs to merge/compress all output items into one for Notebook Output Renderer
* IPynb Serializers Extension (in extension host) needs to merge/compress all output items to save to `*.ipynb` file.
* Thus as the output items grow form 1 to n, we end up spending more and more time processing the same output items over & over in both places:
	* I.e. renderer process is processing a large list for Notebook Renderer and as the list grows, this process is busy
	* I.e. extension host is processing a large list for Serialization and as the list grows, this process is busy

Note: We have tried this approach and the results are not good. Basically VS Code is busy processing a large list of output items and this slows other parts of notebook.

**Benefits:**
* We only send the new output items to Renderer process and Extension host. 
    * i.e. only send incremental updates

```mermaid
sequenceDiagram
  participant Jupyter
  participant Extension Host
  participant VSCode Renderer Proc
  Jupyter->>Extension Host: Append Kernel Output `Line1` using `Task.appendOutput` 
  Extension Host->>VSCode Renderer Proc: `NotebookTextModel._spliceNotebookCellOutputs2` 
  Note right of VSCode Renderer Proc: Model updated to contain <br/>Output with OutputItem `Line1`
  VSCode Renderer Proc-->>Extension Host: Trigger change event for new Output `Line1`
  Note right of Extension Host: Model updated to contain <br/>Output with OutputItem `Line1`
  Jupyter->>Extension Host: Kernel output is `Line2`<br/>Append new output item with value `Line2`<br/>using `Task.appendOutputItem`
  Extension Host->>VSCode Renderer Proc: `NotebookTextModel._appendNotebookCellOutputItems`
  Note right of VSCode Renderer Proc: Merge previous output item with new item, <br/>and replace previous Output Item with `Line1Line2`.<br/>Now we have one output item `Line1Line2`
  VSCode Renderer Proc-->>Extension Host: Trigger change event for append new output item `Line2`
  Note right of Extension Host: Merge previous output item with new item, <br/>and replace previous Output Item with `Line1Line2`.<br/>Now we have one output item `Line1Line2`
  Jupyter->>Extension Host: Kernel output is `Line3`<br/>Append new output item with value `Line3`<br/>using `Task.appendOutputItem`
  Extension Host->>VSCode Renderer Proc: `NotebookTextModel._appendNotebookCellOutputItems`
  Note right of VSCode Renderer Proc: Merge previous output item with new item, <br/>and replace previous Output Item with `Line1Line2Line3`.<br/>Now we have one output item `Line1Line2Line3`
  VSCode Renderer Proc-->>Extension Host: Trigger change event for append new output item `Line3`
  Note right of Extension Host: Merge previous output item with new item, <br/>and replace previous Output Item with `Line1Line2Line3`.<br/>Now we have one output item `Line1Line2Line3`
```

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes https://github.com/microsoft/vscode/issues/161023

### CODE REVIEW

File: extensions/ipynb/src/serializers.ts [hunk 1]
```diff
@@ -271,17 +270,21 @@ type JupyterOutput =
 
 function convertStreamOutput(output: NotebookCellOutput): JupyterOutput {
 	const outputs: string[] = [];
-	const compressedStream = output.items.length ? new TextDecoder().decode(compressOutputItemStreams(output.items[0].mime, output.items)) : '';
-	// Ensure each line is a separate entry in an array (ending with \n).
```
Comment (DonJayamanne) [inline extensions/ipynb/src/serializers.ts:275]: Reverted code from previous PR

File: extensions/ipynb/src/streamCompressor.ts [hunk 2]
```diff
@@ -1,63 +0,0 @@
...
- *--------------------------------------------------------------------------------------------*/
-
-import type { NotebookCellOutputItem } from 'vscode';
-
-
-/**
- * Given a stream of individual stdout outputs, this function will return the compressed lines, escaping some of the common terminal escape codes.
- * E.g. some terminal escape codes would result in the previous line getting cleared, such if we had 3 lines and
- * last line contained such a code, then the result string would be just the first two lines.
- */
```
Comment (DonJayamanne) [inline extensions/ipynb/src/streamCompressor.ts:13]: Moved into a common area

File: src/vs/workbench/api/common/extHostNotebookDocument.ts [hunk 3]
```diff
@@ -110,6 +110,14 @@ export class ExtHostCell {
 				output.items.length = 0;
 			}
 			output.items.push(...newItems);
+			if (output.items.every(item => notebookCommon.isTextStreamMime(item.mime))) {
```
Comment (DonJayamanne) [inline src/vs/workbench/api/common/extHostNotebookDocument.ts:113]: TODO: This needs to be via a proposed API, have a specific method such as `appendStreamOutputItem` or the like

File: src/vs/workbench/contrib/notebook/browser/view/renderers/stdOutErrorPreProcessor.ts [hunk 4]
```diff
@@ -1,56 +0,0 @@
...
-import { VSBuffer } from 'vs/base/common/buffer';
-import type { IOutputItemDto } from 'vs/workbench/contrib/notebook/common/notebookCommon';
-
-
-/**
- * Given a stream of individual stdout outputs, this function will return the compressed lines, escaping some of the common terminal escape codes.
- * E.g. some terminal escape codes would result in the previous line getting cleared, such if we had 3 lines and
- * last line contained such a code, then the result string would be just the first two lines.
- */
-export function compressOutputItemStreams(mimeType: string, outputs: IOutputItemDto[]) {
```
Comment (DonJayamanne) [inline src/vs/workbench/contrib/notebook/browser/view/renderers/stdOutErrorPreProcessor.ts:15]: Moved to a common area so the code can be shared

File: src/vs/workbench/contrib/notebook/common/model/notebookCellTextModel.ts [hunk 5]
```diff
@@ -297,6 +297,15 @@ export class NotebookCellTextModel extends Disposable implements ICell {
 		} else {
 			output.replaceData(items);
 		}
+		if (output.outputs.every(item => isTextStreamMime(item.mime))) {
+			const mime = output.outputs[0].mime;
+			const compressed = compressOutputItemStreams(output.outputs[0].mime, output.outputs.map(item => item.data));
```
Comment (DonJayamanne) [inline src/vs/workbench/contrib/notebook/common/model/notebookCellTextModel.ts:302]: TODO: This would be done based on a flag based on the original call via a proposed API

File: src/vs/workbench/api/common/extHostNotebookDocument.ts [hunk 6]
```diff
@@ -110,6 +110,14 @@ export class ExtHostCell {
...
+				const compressed = notebookCommon.compressOutputItemStreams(newOutputItems[0].mime, newOutputItems.map(item => item.valueBytes));
```
Comment (roblourens) [inline src/vs/workbench/api/common/extHostNotebookDocument.ts:114]: I thought this was going to be done in the renderer process

Comment (DonJayamanne) [reply src/vs/workbench/api/common/extHostNotebookDocument.ts:114]: I thought this is what we discussed.

Yes we do this in the renderer process, but when we get the event back from renderer process in extnesion host we need to compress the output on the round trip. this way the serializers have the compressed outputs. 
Else serializers also have to perform the compression.
If we compress in renderer process and send the compressed output, then if there are no `\r` characters or the like, then the output keeps growing and we end up always sending a very large string from renderer back to the exension host via the change events.

Hope that makes sense.

File: src/vs/workbench/contrib/notebook/common/notebookCommon.ts [hunk 7]
```diff
@@ -951,9 +951,95 @@ export interface NotebookExtensionDescription {
...
 }
 
+
+
+/**
+ * Given a stream of individual stdout outputs, this function will return the compressed lines, escaping some of the common terminal escape codes.
+ * E.g. some terminal escape codes would result in the previous line getting cleared, such if we had 3 lines and
+ * last line contained such a code, then the result string would be just the first two lines.
+ */
+const textDecoder = new TextDecoder();
```
Comment (roblourens) [inline src/vs/workbench/contrib/notebook/common/notebookCommon.ts:967]: jsdoc constant can go on the function, not the const

File: src/vs/workbench/contrib/notebook/common/notebookCommon.ts [hunk 8]
```diff
@@ -951,9 +951,95 @@ export interface NotebookExtensionDescription {
...
+		}
+	});
+}
+
+
+
+// Took this from jupyter/notebook
+// https://github.com/jupyter/notebook/blob/b8b66332e2023e83d2ee04f83d8814f567e01a4e/notebook/static/base/js/utils.js
+// Remove characters that are overridden by backspace characters
+function fixBackspace(txt: string) {
```
Comment (roblourens) [inline src/vs/workbench/contrib/notebook/common/notebookCommon.ts:1011]: Please use /** jsdoc comments on functions so it shows up in intellisense

File: src/vs/workbench/api/common/extHostNotebookDocument.ts [hunk 9]
```diff
@@ -110,12 +110,30 @@ export class ExtHostCell {
 				output.items.length = 0;
 			}
 			output.items.push(...newItems);
-			if (output.items.every(item => notebookCommon.isTextStreamMime(item.mime))) {
-				const compressed = notebookCommon.compressOutputItemStreams(newOutputItems[0].mime, output.items.map(item => item.data));
+
+			if (output.items.length > 1 && output.items.every(item => notebookCommon.isTextStreamMime(item.mime))) {
+				// Look for the mimes in the items, and keep track of their order.
+				// Merge the streams into one output item, per mime type.
+				const mimeOutputs = new Map<string, Uint8Array[]>();
```
Comment (roblourens) [inline src/vs/workbench/api/common/extHostNotebookDocument.ts:117]: Might be useful to share code between here and notebookCellTextModel?

**Review by roblourens — DISMISSED** [review]

File: src/vs/workbench/contrib/notebook/common/notebookCommon.ts (hunk 8 above)
Comment (DonJayamanne) [reply src/vs/workbench/contrib/notebook/common/notebookCommon.ts:1011]: Oops, copy paste isue,

File: src/vs/workbench/api/common/extHostNotebookDocument.ts (hunk 9 above)
Comment (DonJayamanne) [reply src/vs/workbench/api/common/extHostNotebookDocument.ts:117]: @roblourens where would i place such a common (shared) block of code.
I need to share code between the two files
* src/vs/workbench/api/common/extHostNotebookDocument.ts
* src/vs/workbench/contrib/notebook/common/model/notebookCellTextModel.ts

I couldn't find a way to share a file that ends up importing `NotebookCellOutputItem`.
Tried to add such a function in the following locations and got eslint errors about imports not being allowed
* src/vs/workbench/common/notebookCommon.ts
* src/vs/workbench/contrib/notebook/common/notebookCommon.ts

Hgere's the error I get
Screen Shot 2022-10-12 at 07 12 50

**Review by rebornix — APPROVED** [review]

File: src/vs/workbench/api/common/extHostNotebookDocument.ts (hunk 9 above)
Comment (roblourens) [reply src/vs/workbench/api/common/extHostNotebookDocument.ts:117]: Yeah, you're already calling into notebookCommon and that makes sense as a place to keep it, but you would have to do it in a way that doesn't directly import 'vscode', eg work with a different interface. Whatever you wanna do though.

Comment (DonJayamanne) [reply src/vs/workbench/api/common/extHostNotebookDocument.ts:117]: Oops, missed this, will work on that in debt.
