### PR TITLE
Fix language-specific tab expansion and polish

### LINKED ISSUE #156075: [Emmet] per-language "Trigger expansion on tab"
Using tab to complete an element is useful in HTML, but ends up causing a lot of false triggers in JS and TS. I do want emmet in JS in general, but only in the suggestions list and not just when I press tab anywhere. I tried to enable the setting for only HTML files but the setting was not available on a per-language basis.

### PR DESCRIPTION
**Pull request by rzhao271**
Fixes #156075

### CODE REVIEW

File: extensions/emmet/src/abbreviationActions.ts [hunk 1]
```diff
@@ -264,47 +264,47 @@ export async function wrapWithAbbreviation(args: any): Promise<boolean> {
 }
 
 export function expandEmmetAbbreviation(args: any): Thenable<boolean | undefined> {
-	if (!validate() || !vscode.window.activeTextEditor) {
-		return fallbackTab();
+	if (!validate()) {
+		return Promise.resolve(undefined);
 	}
 
+	const editor = vscode.window.activeTextEditor!;
```
Comment (joyceerhl) [inline extensions/emmet/src/abbreviationActions.ts:271]: Are we guaranteed an active text editor here?

**Review by joyceerhl — APPROVED** [review]

File: extensions/emmet/src/abbreviationActions.ts (hunk 1 above)
Comment (rzhao271) [reply extensions/emmet/src/abbreviationActions.ts:271]: Yep, otherwise `validate()` above returns `false` and we exit out of the function early.
