### PR TITLE
Windows: piping from another process fails to update editor contents (fix #148952)

### LINKED ISSUE #148952: Windows: piping from another process fails to update editor contents
Issue Type: <b>Bug</b>
1. From any command line run `ping -t github.com | code -` or pipe another process that runs indefinitely to `code -`
2. Observe that a window does not open and the command does not return.

The file should open and update as new data is piped to the code cli command.

This works on the Mac when you run `ping github.com | code -` but does not work on Windows.

This is not a 1.67.0 regression 

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

### PR DESCRIPTION
**Pull request by bpasero**
This PR fixes #148952

### CODE REVIEW

File: src/vs/platform/environment/node/stdin.ts [hunk 1]
```diff
@@ -51,15 +48,21 @@ export async function readFromStdin(targetPath: string, verbose: boolean): Promi
...
+	// which helps file watchers to be aware of the
+	// changes because each append closes the underlying
+	// file descriptor.
+	// (https://github.com/microsoft/vscode/issues/148952)
 	const decoder = iconv.getDecoder(encoding);
-	process.stdin.on('data', chunk => stdinFileStream.write(decoder.write(chunk)));
+	const appendFileQueue = new Queue();
+	process.stdin.on('data', chunk => {
+		const chunkStr = decoder.write(chunk);
+		appendFileQueue.queue(() => Promises.appendFile(targetPath, chunkStr));
```
Comment (joaomoreno) [inline src/vs/platform/environment/node/stdin.ts:60]: At some point we should start removing all the promisify stubs in here and just use `fs.promises`.

**Review by joaomoreno — APPROVED** [review]

File: src/vs/platform/environment/node/stdin.ts (hunk 1 above)
Comment (bpasero) [reply src/vs/platform/environment/node/stdin.ts:60]: @joaomoreno we cannot, `graceful-fs` does not support patching `fs.promises`.

Comment (bpasero) [reply src/vs/platform/environment/node/stdin.ts:60]: https://github.com/microsoft/vscode/blob/32d40cf44e893e87ac33ac4f08de1e5f7fe077fc/src/vs/base/node/pfs.ts#L616-L631

Also, there are subtle differences it seems in how the methods are actually implemented for some...
