### PR TITLE
Spawn .bat/.cmd DebugAdapterExecutables with shell=true

### LINKED ISSUE #224184: DebugAdapterExecutable does not support passing `shell: true` so `.bat`-based debug adapters are broken in current Insiders
In current Insiders (and presumably the upcoming release), spawning a `.bat` file on Windows without `shell: true` fails due to a breaking change in NodeJS:

https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2

> It is important to note that there has been a breaking change for Windows users who utilize `child_process.spawn` and `child_process.spawnSync`. Node.js will now error with `EINVAL` if a `.bat` or `.cmd` file is passed to `child_process.spawn` and `child_process.spawnSync` without the `shell` option set.

It appears that there's no way to signal this to [DebugAdapterExecutable](https://code.visualstudio.com/api/references/vscode-api#DebugAdapterExecutable) and therefore any `.bat`-based debug adapters launched this way fail in current Insiders (and will presumably fail in stable soon).

Could `shell: bool?` be added to `DebugAdapterExecutableOptions`? I don't know enough to contribute this, but this seems quite important.

### PR DESCRIPTION
**Pull request by roblourens**
Fix #224184

- Spawn can use powershell if the user has set COMSPEC to point at powershell, but I don't think this is that common?
- ~~I'm unsure about escaping the args, because I think that in the previous node version, they would have had to be escaped already, but I'll check~~
- In any case, the DAs that pass the if check would be broken anyway in this release.

### CODE REVIEW

File: src/vs/workbench/contrib/debug/node/debugAdapter.ts [hunk 1]
```diff
@@ -222,13 +222,22 @@ export class ExecutableDebugAdapter extends StreamDebugAdapter {
...
 				};
 				if (options.cwd) {
 					spawnOptions.cwd = options.cwd;
 				}
-				this.serverProcess = cp.spawn(command, args, spawnOptions);
+				if (platform.isWindows && command.endsWith('.bat')) {
+					// https://github.com/microsoft/vscode/issues/224184
+					spawnOptions.shell = true;
+					spawnCommand = `"${command}"`;
+					spawnArgs = args.map(a => `"${a}"`);
```
Comment (DanTup) [inline src/vs/workbench/contrib/debug/node/debugAdapter.ts:237]: If any args contain `"` do those need escaping?

(mine don't, and hopefully others don't, but who knows?)

File: src/vs/workbench/contrib/debug/node/debugAdapter.ts [hunk 2]
```diff
@@ -222,13 +222,22 @@ export class ExecutableDebugAdapter extends StreamDebugAdapter {
...
+				let spawnCommand = command;
+				let spawnArgs = args;
 				const spawnOptions: cp.SpawnOptions = {
 					env: env
 				};
 				if (options.cwd) {
 					spawnOptions.cwd = options.cwd;
 				}
-				this.serverProcess = cp.spawn(command, args, spawnOptions);
+				if (platform.isWindows && (command.endsWith('.bat') || command.endsWith('.cmd'))) {
```
Comment (DanTup) [inline src/vs/workbench/contrib/debug/node/debugAdapter.ts:233]: ~~Should this also include `.cmd?`~~

Edit, nm :)

**Review by DanTup — APPROVED** [review]

**Comment by DanTup** [comment]
(btw, typo in title/commit - "with spawn=true" should be "with shell=true")

File: src/vs/workbench/contrib/debug/node/debugAdapter.ts (hunk 1 above)
Comment (connor4312) [reply src/vs/workbench/contrib/debug/node/debugAdapter.ts:237]: Looks like they do 😞

Comment (DanTup) [reply src/vs/workbench/contrib/debug/node/debugAdapter.ts:237]: IIRC things like "<" can cause issues too (see https://ss64.com/nt/syntax-esc.html). In Dart-Code I have this escape function:

https://github.com/Dart-Code/Dart-Code/blob/d1894e79c99360438d509922e5b8ff391ecdbcf0/src/shared/processes.ts#L29

I don't know if it's reliable (particularly if you changed `COMSPEC` to PoSh, but hopefully nobody is doing that 😄) or how likely it is in the debug adapter executable (it came up for me because [test names can be passed as args](https://github.com/Dart-Code/Dart-Code/issues/4042) to some processes and that's a shared escape function).

Comment (roblourens) [reply src/vs/workbench/contrib/debug/node/debugAdapter.ts:237]: Are you already escaping any args that go to the DebugAdapterExecutable? Or is it a fixed set of args?

Comment (DanTup) [reply src/vs/workbench/contrib/debug/node/debugAdapter.ts:237]: No, not escaping anything for `DebugAdapterExecutable` because it's not usually required (the function above is used in the places where we are using `shell:true` to spawn our own processes).

> Or is it a fixed set of args?

Yep, for the place that will come through `DebugAdapterExecutable` our args are fixed (well, they're dynamic, but from a small set which is basically `["debug_adapter", "--test", "--no-dds"]`). There are a few small exceptions (where you might pass a full path), but they're generally just for me (or other contributors to the debug adapter) that are running from source.

(TL;DR; simple escaping such as only putting quotes around them is definitely good enough for me, and the comments above were just general comments about being strict in case others are doing weirder things)

**Review by connor4312 — APPROVED** [review]

File: src/vs/workbench/contrib/debug/node/debugAdapter.ts (hunk 1 above)
Comment (roblourens) [reply src/vs/workbench/contrib/debug/node/debugAdapter.ts]: This level of escaping seems to be fine, including for characters like `>`, although cmd.exe escaping is obviously extremely weird.

Did you test that this works for your scenarios @DanTup?

**Comment by DanTup** [comment]
I just checked out 3bb157866cd (branch `release/1.92`) and tested with my workaround reverted, and the debug adapter is correctly spawned from the `.bat` and works as expected (both with and without the common args we use).

```
Dart Code extension: 3.93.0-dev.reverted
App: Code - OSS Dev
Version: win 1.92.0

[10:13:39 AM] [General] [Info] Running SDK DAP Dart VM in undefined: C:\Dev\Google\Flutter\Flutter main\bin\flutter.bat debug_adapter and options {"env":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code","FLUTTER_ROOT":"C:\\Dev\\Google\\Flutter\\Flutter main"}}
[10:13:39 AM] [DAP] [Info] Starting debug session 79f96753-a0c4-44f5-9e6c-bdb6025359a9
[10:13:39 AM] [DAP] [Info] ==> {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Code - OSS Dev","adapterID":"dart","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true,"supportsArgsCanBeInterpretedByShell":true,"supportsMemoryEvent":true,"supportsStartDebuggingRequest":true,"supportsDartUris":true},"type":"request","seq":1}
[10:13:39 AM] [DAP] [Info] <== {"seq":1,"type":"response","body":{"exceptionBreakpointFilters":[{"default":false,"filter":"All","label":"All Exceptions"},{"default":true,"filter":"Unhandled","label":"Uncaught Exceptions"}],"supportsClipboardContext":true,"supportsConditionalBreakpoints":true,"supportsConfigurationDoneRequest":true,"supportsDelayedStackTraceLoading":true,"supportsEvaluateForHovers":true,"supportsLogPoints":true,"supportsRestartFrame":true,"supportsRestartRequest":false,"supportsTerminateRequest":true,"supportsValueFormattingOptions":true},"command":"initialize","request_seq":1,"success":true}
[10:13:39 AM] [DAP] [Info] <== {"seq":2,"type":"event","body":{},"event":"initialized"}
```

Thank you for this, I really appreciate it - it will have saved us a lot of pain and duplicate GH issues 😄

Does the release branch automatically get merged back to `main` periodically, or is there something more to do for the subsequent release?

**Comment by roblourens** [comment]
Thanks!
