### PR TITLE
prompt for permission in trusted work space once per folder for auto run tasks

### LINKED ISSUE #159370: VSCode not asking whether I want tasks configured with "runOn": "folderOpen" to be executed with "task.allowAutomaticTasks": "auto".
Type: <b>Bug</b>

1. Without VSCode, create a folder named, for instance, "XXXX".
2. In that folder create another called .vscode
3. In .vscode create a file named tasks.json with this content:
```json
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "echo",
      "type": "shell",
      "command": "echo Hello",
      "runOptions": {
        "runOn": "folderOpen"
      }
    }
  ]
}
```
4. Open VSCode
4. Make sure the setting "task.allowAutomaticTasks" is not set or is set to its defautl value "auto".
4. Open "XXXX" with VSCode.

VSCode will run "echo Hello" without asking you whether you want to run tasks configured with "runOn": "folderOpen" or not.

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19043
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.43GB (2.23GB free)|
|Process Argv|--crash-reporter-id 78bf48ec-3ac2-4ab2-9796-20d8802d00af|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

### PR DESCRIPTION
**Pull request by meganrogge**
fix #159370

this function name was confusing and misleading
https://github.com/microsoft/vscode/blob/14b3a74130059492bade6fd738c41bd7f542db72/src/vs/workbench/contrib/tasks/browser/runAutomaticTasks.ts#L122

### CODE REVIEW

File: src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts [hunk 1]
```diff
@@ -1228,7 +1228,7 @@ export abstract class AbstractTaskService extends Disposable implements ITaskSer
 			}
 			if (runSource === TaskRunSource.User) {
 				const workspaceTasks = await this.getWorkspaceTasks();
-				RunAutomaticTasks.promptForPermission(this, this._storageService, this._notificationService, this._workspaceTrustManagementService, this._openerService, this._configurationService, workspaceTasks);
```
Comment (meganrogge) [inline src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts:1231]: this name was misleading

**Review by Tyriar — APPROVED** [review]
