### PR TITLE
fix terminal suggest folder/file completions bugs

### LINKED ISSUE #235033: Terminal suggest: Tweak resource resolving with a focus on consistency
I've noticed a few bugs in the class of completions not showing up depending on where the completion request was made. This is the function that handles inflating resource requests into completion items: 

https://github.com/microsoft/vscode/blob/f408139c28c2c653d673e9a85ba250d6c6a588be/src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts#L192-L246

For example:

---

Type `cd s`:

Image

✅ This is good.

---

Type `cd .`:

Image

❌ This should show all files and folders since `.` is the prefix of `./`

---

Type `cd ./`:

Image

❌ While this does allow navigating between folders when the completion is accepted, the folders starting with `/` make it seem that they are root folders, not relative folders.

---

Type `cd ./s` and request completions:

Image

❌ Tracked in https://github.com/microsoft/vscode/issues/235027

---

Type `cd ./sr` and request completions:

Image

❌ This one was particularly weird.

---

I'm not sure how much of the above problems are related to the resource resolving vs actual filtering, but the first place to start imo is to write a nice testable function with a lot of unit tests and make sure these rules are followed:

- Normalize the path by finding the folder that we're providing completions for, the same code path should be followed when requesting resources for `<empty string>`, `./`, `./sr`, etc. since they are all within the cwd.
- The file portion of . The request should return _all_ files/folders within the cwd.
- Standardize on a `./` (or `.\`) prefix for the first file or folder completion, and no prefix for others. It may seem more ideal to omit the `./` completely in cases where it's not typed, but including it is functionality equivalent so let's focus on getting that right now before trying to support both formats.
- Regardless of where completions are requested (between trigger characters), the results should be the same; `./sr` and `sr` should provide the same completion items. The replacement index should be the beginning on the word and then invalidated when the cursor goes left beyond it (https://github.com/microsoft/vscode/issues/235026)

### LINKED ISSUE #235084: No completions on `/`
Testing #235021

* trigger completions with ctrl+space
* dismiss them
* press `/` cos trigger character
* :bug: nothing

https://github.com/user-attachments/assets/7bac8b2f-97e1-47cf-95cb-ec05ca03c31d

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #235033 
fixes #235084
and adds some tests/ refines their expected values

### CODE REVIEW

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts [hunk 1]
```diff
@@ -224,25 +219,41 @@ export class TerminalCompletionService extends Disposable implements ITerminalCo
 			}
 			const isDirectory = kind === TerminalCompletionItemKind.Folder;
 			const pathToResource = stat.resource.fsPath.replace(cwd.fsPath, '');
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts:221]: Using `cwd.fsPath` to replace here feels a little risky. I think `basename` from `path` is what you want?

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts [hunk 2]
```diff
@@ -224,25 +219,41 @@ export class TerminalCompletionService extends Disposable implements ITerminalCo
...
-			let label = pathToResource;
+
+			let label;
+			if (!prefix.startsWith('.')) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts:224]: Many files and folders start with `.` so this will fall over there (`.git/`, `.bashrc`, etc.)

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts [hunk 3]
```diff
@@ -224,25 +219,41 @@ export class TerminalCompletionService extends Disposable implements ITerminalCo
...
+				// add a dot to the beginning of the label if it doesn't already have one
+				label = '.' + pathToResource;
+			} else {
+				if (prefix.endsWith(resourceRequestConfig.pathSeparator)) {
+					// prevent a double path separator
+					label = prefix + pathToResource.substring(1);
+				} else {
+					label = prefix + pathToResource;
+				}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts:233]: Can we avoid this all together if we use `basename`?

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts [hunk 4]
```diff
@@ -224,25 +219,41 @@ export class TerminalCompletionService extends Disposable implements ITerminalCo
...
+				if (prefix.length && prefix.at(-1) !== resourceRequestConfig.pathSeparator && prefix.at(-1) !== '.') {
+					// prefix has text, so get closest path prefix
+					label = getPathPrefix(prefix, resourceRequestConfig.pathSeparator) + pathToResource;
+				}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts:237]: Having trouble understanding this, "prefix" is getting a little overloaded I think

**Review by Tyriar — DISMISSED** [review]

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts (hunk 3 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts:234]: We cannot

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts [hunk 5]
```diff
@@ -204,12 +205,7 @@ export class TerminalCompletionService extends Disposable implements ITerminalCo
 
 		const resourceCompletions: ITerminalCompletion[] = [];
 		const endsWithSpace = promptValue.substring(0, cursorPosition).endsWith(' ');
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts:207]: `promptValue.substring(0, cursorPosition)` could be pulled into a `cursorPrefix` var?

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts [hunk 6]
```diff
@@ -204,12 +205,7 @@ export class TerminalCompletionService extends Disposable implements ITerminalCo
...
-		let lastWord;
-		if (endsWithSpace) {
-			lastWord = '';
-		} else {
-			lastWord = promptValue.substring(0, cursorPosition).trim().split(' ').at(-1) ?? '';
-		}
+		const lastWord = endsWithSpace ? '' : promptValue.substring(0, cursorPosition + 1).trim().split(' ').at(-1) ?? '';
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts:208]: What is the purpose of the `+ 1` here? Also the trim might cause bugs, I don't think it does anything atm due to the `endsWithSpace` check

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts [hunk 7]
```diff
@@ -223,26 +219,42 @@ export class TerminalCompletionService extends Disposable implements ITerminalCo
...
+			if (!lastWord.startsWith('.' + resourceRequestConfig.pathSeparator) && !lastWord.startsWith('..' + resourceRequestConfig.pathSeparator)) {
+				// add a dot to the beginning of the label if it doesn't already have one
+				label = '.' + pathToResource;
+			} else {
+				if (lastWord.endsWith(resourceRequestConfig.pathSeparator)) {
+					// prevent a double path separator
+					label = lastWord + pathToResource.substring(1);
+				} else {
+					label = lastWord + pathToResource;
+				}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts:234]: `resourceRequestConfig.pathSeparator` is added above at line 222, this code would be easier to follow without the undoing of that. So something like this instead:

```ts
const fileName = basename(stat.resource.fsPath);
...
if (lastWord.endsWith(resourceRequestConfig.pathSeparator)) {
  label = `${lastWord}${fileName}`;
} else {
  label = `${lastWord}${resourceRequestConfig.pathSeparator}${fileName}`;
}
```

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts [hunk 8]
```diff
@@ -223,26 +219,42 @@ export class TerminalCompletionService extends Disposable implements ITerminalCo
...
+				replacementLength: lastWord.length > 0 ? lastWord.length : label.length
 			});
 		}
 
 		return resourceCompletions.length ? resourceCompletions : undefined;
 	}
 }
 
+function findBasePath(word: string, pathSeparator: string): string {
+	const lastSlashIndex = Math.max(word.lastIndexOf(pathSeparator));
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts:258]:
```suggestion
	const lastSlashIndex = word.lastIndexOf(pathSeparator);
```

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts (hunk 6 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts:208]: substring end value is not inclusive, thus the plus one

Comment (Tyriar) [reply src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalCompletionService.ts:208]: But cursorPosition from promptInputState is the position of the cursor, so substring should get the text from 0 to where the cursor is (after the last char). Shouldn't it be the same as `endsWithSpace`?

**Review by Tyriar — DISMISSED** [review]

**Comment by meganrogge** [comment]
that test allows fails in cI, always passes locally, so removed

File: src/vs/workbench/contrib/terminalContrib/suggest/test/browser/terminalCompletionService.test.ts [hunk 9]
```diff
@@ -157,27 +157,5 @@ suite('TerminalCompletionService', () => {
 				replacementLength: 3 // replacing ./f
 			});
 		});
-		test('cd ../', async () => {
-			const resourceRequestConfig: TerminalResourceRequestConfig = {
-				cwd: URI.parse('file:///folder1'),
-				foldersRequested: true,
-				pathSeparator
-			};
-			await fileService.createFolder(URI.parse('file:///test/'));
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/suggest/test/browser/terminalCompletionService.test.ts]: I think you'll want to mock fileService here instead as in don't interact with the OS at all and instead have it return true for a fixed set of resources. That's probably why it's failing in CI as it depends upon the file system.

Something closer to this:

https://github.com/microsoft/vscode/blob/ae4fcd92ba98d58b936c58ac6a36e4a05af14980/src/vs/workbench/contrib/terminalContrib/links/test/browser/terminalLocalLinkDetector.test.ts#L203-L210

Don't want to introduce another flaky test 😅

**Review by Tyriar — DISMISSED** [review]

File: src/vs/workbench/contrib/terminalContrib/suggest/test/browser/terminalCompletionService.test.ts (hunk 9 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/suggest/test/browser/terminalCompletionService.test.ts]: done

**Review by Tyriar — APPROVED** [review]
