### PR TITLE
Git - Remove icons from branch picker to address regression

### LINKED ISSUE #153368: Git: Checkout To...Create Branch From... fails with "fatal: '$(git-branch) main' is not a commit and a branch 'main2' cannot be created from it" (Insiders regression)
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.69.0-insider (user setup)
Commit: e71b6105ebb4fbcfbf38a1b62bcbafdb048d3468
Date: 2022-06-27T07:59:47.622Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Open Folder (or workspace) with some Git repo project, such as from https://github.com/microsoft/vscode-cpptools.git . I've reproed this with multiple git repos.
2. Do command "Git: Checkout To...".
3. Select "Create Branch From...".
4. Type a new branch name, such as "main2".
5. Select an existing branch such "main".

Bug: It fails. Logging shows:
git checkout -q -b main2 --no-track $(git-branch) main
fatal: '$(git-branch) main' is not a commit and a branch 'main2' cannot be created from it.

The bug doesn't repro when I switch to the non-Insiders VS Code and it wasn't reproing last week, so I believe this is a recent Insiders regression.

### PR DESCRIPTION
**Pull request by lszomoru**
Fix #153368

### CODE REVIEW

**Review by joaomoreno — CHANGES_REQUESTED** [review]
I suggest we look into the problem and fix it, instead of reverting changes. Let me know if you need another pair of eyes.

File: extensions/git/src/commands.ts [hunk 1]
```diff
@@ -1998,7 +1999,9 @@ export class CommandCenter {
 				return;
 			}
 
-			target = choice.label;
+			if (choice instanceof CheckoutItem && choice.refName) {
+				target = choice.refName;
+			}
```
Comment (joaomoreno) [inline extensions/git/src/commands.ts:2004]: Let's add `refName` to all types which are supported in this code path, so we don't have to check for `instanceof`. It's the better general change, ie separate the label from the model.

**Review by joaomoreno — CHANGES_REQUESTED** [review]

File: extensions/git/src/commands.ts (hunk 1 above)
Comment (lszomoru) [reply extensions/git/src/commands.ts]: Fixed.

**Review by joaomoreno — APPROVED** [review]
