### PR TITLE
fix min width view in terminal tabs

### LINKED ISSUE #123116: Terminal narrow layout is broken
image

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #123116

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalTabbedView.ts [hunk 1]
```diff
@@ -262,10 +262,10 @@ export class TerminalTabbedView extends Disposable {
 	}
 
 	private _rerenderTabs() {
-		const hasText = this._tabTreeContainer.clientWidth > MIDPOINT_WIDGET_WIDTH;
+		const hasText = this._terminalTabTree.clientWidth > MIDPOINT_WIDGET_WIDTH;
 		this._tabTreeContainer.classList.toggle('has-text', hasText);
 		this._terminalIsTabsNarrowContextKey.set(!hasText);
-		this._tabList.rerender();
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalTabbedView.ts:268]: calling `rerender `on the tabs list doesn't end up calling `renderElement`. @joaomoreno thoughts?

**Review by Tyriar — APPROVED** [review]
