### PR TITLE
Fixes: stuck status bar, problems setting wording

### LINKED ISSUE #199389: Setting name is mentioned twice, once linked and once not
Testing #199247

Why is the setting name linked once and once it just shows the ID? Both should be linked, or maybe you can rephrase it to just use the setting name once like `Overwritten by Problems: Visibility when that setting is off`
image

### PR DESCRIPTION
**Pull request by justschen**
fixes https://github.com/microsoft/vscode/issues/199389, https://github.com/microsoft/vscode/issues/199307, https://github.com/microsoft/vscode/issues/199387, https://github.com/microsoft/vscode/issues/199430

### CODE REVIEW

File: src/vs/workbench/contrib/markers/browser/markers.contribution.ts [hunk 1]
```diff
@@ -595,15 +595,13 @@ class MarkersStatusBarContributions extends Disposable implements IWorkbenchCont
 
 	private getMarkersItemTurnedOff(): IStatusbarEntry {
 		const config = this.configurationService.getValue('problems.visibility');
-		if (config) {
-			return { name: '', text: '', ariaLabel: '', tooltip: '', command: '' };
-		}
+		this.statusbarService.updateEntryVisibility('status.problemsVisibility', config ? false : true);
```
Comment (rzhao271) [inline src/vs/workbench/contrib/markers/browser/markers.contribution.ts:598]:
```suggestion
		this.statusbarService.updateEntryVisibility('status.problemsVisibility', !config);
```

**Review by rzhao271 — APPROVED** [review]
