### PR TITLE
Transform `text/uri-list` mime values in data transfers

### LINKED ISSUE #165636: Dragging an image into markdown adds the wrong path
Type: <b>Bug</b>

Dragging an image from my downloads folder into a dev container notebook, I get

`Alt text`

Dragging it from the VS Code Explorer into markdown I get

`Alt text`

Not trusting the pasted results and editing it down to `Stackoverflow Banner` works.

VS Code version: Code - Insiders 1.74.0-insider (e764c5b816a99eb8673b2fc4fc028827f202872f, 2022-11-04T05:19:54.097Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.49-linuxkit

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #165636

This passes any `text/uri-list` mime values in a datatransfer through our uri transformers. Because these uri values are stored as a list of strings, they are not automatically transformed

### CODE REVIEW

**Review by jrieken — CHANGES_REQUESTED** [review]
I'd suggest to not use the uri transformer but to extract uri'ish data as URI-instances so that the conversion happens. You can use [`Markdown#from`](https://github.com/microsoft/vscode/blob/84a929b8b7ea25af7f2c5fb4e76b6a65028a7a6c/src/vs/workbench/api/common/extHostTypeConverters.ts#L324) as inspiration for this.

**Comment by mjbvz** [comment]
Thanks @jrieken. I switched to a different approach. Please re-review when you have a chance!

File: src/vs/workbench/api/common/extHostTypeConverters.ts [hunk 1]
```diff
@@ -1966,7 +1967,7 @@ export namespace ViewBadge {
 }
 
 export namespace DataTransferItem {
-	export function toDataTransferItem(item: extHostProtocol.DataTransferItemDTO, resolveFileData: () => Promise<Uint8Array>): types.DataTransferItem {
+	export function to(mime: string, item: extHostProtocol.DataTransferItemDTO, resolveFileData: () => Promise<Uint8Array>, uriTransformer?: IURITransformer): types.DataTransferItem {
```
Comment (jrieken) [inline src/vs/workbench/api/common/extHostTypeConverters.ts:1970]: there is a lone `uriTransformer` argument

**Review by jrieken — DISMISSED** [review]

**Review by joyceerhl — APPROVED** [review]
