### PR TITLE
fix: adding escape command in order to focus out of the sticky scroll

### LINKED ISSUE #177871: Can't easily get out of Sticky Scroll focus
Testing #177642

1. Scroll around an open file in the editor with Stick Scroll enabled.
2. Focus Sticky Scroll

Try to move focus out of Sticky Scroll. 
Tried pressing `Escape`.
Tried running "Focus Sticky Scroll" command a second time.

Only way to get focus back to the editor is to select a level and press `Enter`.

I think `Escape` should put you back into the editor

### PR DESCRIPTION
**Pull request by aiday-mar**
Fixes https://github.com/microsoft/vscode/issues/177871

Simple fix to add escape command to focus out of the sticky scroll

### CODE REVIEW

File: src/vs/editor/contrib/stickyScroll/browser/stickyScrollActions.ts [hunk 1]
```diff
@@ -144,3 +144,27 @@ export class GoToStickyScrollLine extends EditorAction2 {
...
+	constructor() {
+		super({
+			id: 'editor.action.escapeStickyScroll',
+			title: {
+				value: localize('escapeStickyScroll.title', "Escape Sticky Scroll"),
+				original: 'Escape Sticky Scroll'
+			},
+			precondition: ContextKeyExpr.has('config.editor.stickyScroll.enabled'),
+			keybinding: {
+				weight,
```
Comment (Tyriar) [inline src/vs/editor/contrib/stickyScroll/browser/stickyScrollActions.ts:158]: Just noticed this:

```
const weight = KeybindingWeight.EditorContrib + 10000;
```

Why isn't it editorcontrib weight? This may cause confusion as workbench/extensions are meant to have a higher weight?

File: src/vs/editor/contrib/stickyScroll/browser/stickyScrollActions.ts [hunk 2]
```diff
@@ -144,3 +144,27 @@ export class GoToStickyScrollLine extends EditorAction2 {
...
+				primary: KeyCode.Escape
+			}
+		});
+	}
+
+	runEditorCommand(_accessor: ServicesAccessor, editor: ICodeEditor) {
+		const stickyScrollController = StickyScrollController.get(editor);
+		if (stickyScrollController) {
+			stickyScrollController.escape();
+		}
```
Comment (Tyriar) [inline src/vs/editor/contrib/stickyScroll/browser/stickyScrollActions.ts:168]:
```suggestion
		StickyScrollController.get(editor)?.escape();
```

Comment (Tyriar) [reply src/vs/editor/contrib/stickyScroll/browser/stickyScrollActions.ts:168]: Even better though would be to use the editor service to focus the active editor, that saves you from exposing an escape function on the controller

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/editor/contrib/stickyScroll/browser/stickyScrollActions.ts (hunk 1 above)
Comment (aiday-mar) [reply src/vs/editor/contrib/stickyScroll/browser/stickyScrollActions.ts:158]: Thanks for pointing it out!

File: src/vs/editor/contrib/stickyScroll/browser/stickyScrollActions.ts (hunk 2 above)
Comment (aiday-mar) [reply src/vs/editor/contrib/stickyScroll/browser/stickyScrollActions.ts:168]: Just tried to access the editor service, it would appear importing it into the stickyScrollAction.ts causes an import violation error:

Screenshot 2023-03-22 at 16 30 39

Comment (Tyriar) [reply src/vs/editor/contrib/stickyScroll/browser/stickyScrollActions.ts]: Ah ok, .selectEditor works then

File: src/vs/editor/contrib/stickyScroll/browser/stickyScrollActions.ts [hunk 3]
```diff
@@ -138,9 +129,28 @@ export class GoToStickyScrollLine extends EditorAction2 {
...
-		}
+		StickyScrollController.get(editor)?.goToFocused();
+	}
+}
+
+export class SelectEditor extends EditorAction2 {
+
+	constructor() {
+		super({
+			id: 'editor.action.selectEditor',
```
Comment (Tyriar) [inline src/vs/editor/contrib/stickyScroll/browser/stickyScrollActions.ts:140]: I'm not the best person to ask but not sure the ideal name for this, should a contrib be registering unprefixed `editor.action.*` commands?

**Review by Tyriar — APPROVED** [review]
Thanks for the changes 🙂
