### PR TITLE
expose altClickMovesCursor as setting

### LINKED ISSUE #101136: Terminal filled with ^[[D^[[D^[[D^[[D when alt-clicking a link
- VSCode Version: 1.46.1
- OS Version: Ubuntu 20.04 LTS x86_64
- shell: bash

When alt-clicking in terminal (e. g. to open a file or URL), it gets filled up with lots of `^[[D^[[D^[[D^[[D` or `^[[C^[[C^[[C^[[C`:

image

Steps to Reproduce:

1. Open integrated terminal
2. Run `read` (or, for a more practical example, `yarn create react-app . && yarn start` in a temp dir)
3. Alt-click anywhere 

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #101136

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts [hunk 1]
```diff
@@ -90,6 +90,11 @@ export const terminalConfiguration: IConfigurationNode = {
 			type: 'boolean',
 			default: false
 		},
+		'terminal.integrated.altClickMovesCursor': {
+			description: localize('terminal.integrated.altClickMovesCursor', "If enabled, alt/option + click will move the prompt cursor to position underneath the mouse."),
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts:94]:
```suggestion
			description: localize('terminal.integrated.altClickMovesCursor', "If enabled, alt/option + click will move the prompt cursor to position underneath the mouse. This may not work reliably depending on your shell."),
```

**Review by Tyriar — APPROVED** [review]
One suggestion but other then that it looks good if it works 🙂
