### PR TITLE
log more info when tasks to terminate is not found

### LINKED ISSUE #160571: Task to terminate not found
```javascript
Error: Task to terminate not found
at <anonymous> in src/vs/workbench/api/browser/mainThreadTask.ts:652:12
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=784b0177c56c607789f9638da7b6bf3230d47a8c&bH=e52c6511-62f7-b23c-c396-f4fa9212e595)

### PR DESCRIPTION
**Pull request by meganrogge**
not sure what's going on here, so need to log more info
fix #160571

@alexr00 should this just be a warning instead of an error or is this condition unexpected?

### CODE REVIEW

File: src/vs/workbench/api/browser/mainThreadTask.ts [hunk 1]
```diff
@@ -649,7 +649,7 @@ export class MainThreadTask implements MainThreadTaskShape {
 						return;
 					}
 				}
-				reject(new Error('Task to terminate not found'));
+				reject(new Error(`Task to terminate not found for ID: ${id}, tasks: ${tasks.map(t => `ID: ${t._id} Label: ${t._label}`)}`));
```
Comment (Tyriar) [inline src/vs/workbench/api/browser/mainThreadTask.ts:652]: I've learned we typically don't want to add customizable text like this as then a lot of distinct errors will end up showing in telemetry.

Comment (Tyriar) [reply src/vs/workbench/api/browser/mainThreadTask.ts:652]: > should this just be a warning instead of an error or is this condition unexpected?

This feels like a warning that should either silently fail (as the request is done already), or show a notification. If we just want a notification and that's happening because of this `Error` bubbling up, changing it to `ErrorNoTelemetry` will keep that.

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Review by Tyriar — APPROVED** [review]

**Comment by alexr00** [comment]
It looks like this error occurs when an extension tries to terminate a task that wasn't running. This should have an error and the error should make it back to the extension ideally.

**Comment by Tyriar** [comment]
@alexr00 an `ErrorNoTelemetry` is meant towork the same as a regular `Error`, just without reporting telemetry. So I think that's covered?

**Comment by alexr00** [comment]
I agree, I think `ErrorNoTelemetry` is the right approach.
