### PR TITLE
Notebook: separate selections and text model

### LINKED ISSUE #99130: Splitting Notebook editor doesn't render new cells in both
Testing #98985

Steps to reproduce
1. Split editor
2. Create new cells.
3. They don't show up in both editors

Changes to existing cells show up in both editors, but not new cells.

### LINKED ISSUE #99995: Markdown cell doesn't always update when editing in split notebook editor
- Open a notebook with a markdown cell
- Split it
- Edit a markdown cell on one side, see that it's not updated on the other side in preview mode
- If it works, repeat a couple times

Seems that the right events are being fired, but `getText` in the viewmodel returns the old text. If I put the preview cell into edit mode, the editor has the right contents. 

Any idea what's going on @rebornix? I touched this area recently but I can still repro after reverting my changes.

Pushed a1feacf5c445f040d42419ddbe07b29bbe5bc165 because I removed that and I think I shouldn't have.

### PR DESCRIPTION
**Pull request by rebornix**
This PR fixes #99130.

To support opening the same document in multiple editor panes, the cell selections need to be detached from the model, otherwise all editor panes for the same resource will scroll/revealCell at the same time. This PR moves the content change all into `NotebookTextModel` but leave the selections in `NotebookViewModel`. 

This also fixes #99130 as previously Notebook Editor only listens to `NotebookViewModel` change events so even though the text model is shared, the view models are not updated properly.

- [x] Separate content change and selection change
- [x] Undo/Redo should still restore selection properly
- [x] If the notebook editor is not focused and undo/redo, it should not update the selections of that editor (follow Monaco Editor's behavior)

### CODE REVIEW

File: src/vs/workbench/contrib/webview/browser/webviewElement.ts [hunk 1]
```diff
@@ -91,7 +92,7 @@ export class IFrameWebview extends BaseWebview<HTMLIFrameElement> implements Web
 	}
 
 	private get useExternalEndpoint(): boolean {
```
Comment (rebornix) [inline src/vs/workbench/contrib/webview/browser/webviewElement.ts:94]: @mjbvz here I added flag for using iframe on desktop for webview.

**Review by mjbvz — APPROVED** [review]
Webview changes look good to me. I'll keep looking into enabling offline iframe based webviews on desktop

**Comment by rebornix** [comment]
I reverted the change for forcing to use iframe for notebook as @deepak1556 's electron is coming in. Once that's in, I'll start testing iframe for notebook locally.
