### PR TITLE
Validate that semantic tokens edits reference valid offsets

### LINKED ISSUE #149412: VS Code hangs when bad semantic token data is received
- Make sure you have Pylance `v2022.5.1` and Jupyter installed
- Set `"jupyter.pylanceHandlesNotebooks": true`
- Create a new jupyter notebook
- Follow these steps: https://github.com/microsoft/pylance-release/issues/2783#issuecomment-1125496102
- vscode stops responding

Fixed on Pylance's side, but it shouldn't be possible for an extension to crash vscode like this. I don't understand the explanation for what they changed to fix it, but maybe you do: https://github.com/microsoft/pyrx/pull/2415

And I didn't debug that much but it seems like it hangs in here https://github.com/microsoft/vscode/blob/6e1e0b1d899b2d262265e8faeadee98c562cfe7b/src/vs/editor/common/services/modelService.ts#L978

### PR DESCRIPTION
**Pull request by alexdima**
The actual hang was caused by a loop that was running for a very long time in `ModelSemanticColoring._copy`. The passed in `length` was 4 billion and it wouldn't do anything, so now we protect against that.

But the root problem was that we received an edit which referenced an offset outside the array. So now we also validate edits and in case they don't make sense simply drop all semantic tokens.

Fixes #149412

### CODE REVIEW

File: src/vs/editor/common/services/modelService.ts [hunk 1]
```diff
@@ -710,6 +710,14 @@ class SemanticColoringFeature extends Disposable {
 		}));
 		this._register(themeService.onDidColorThemeChange(handleSettingOrThemeChange));
 	}
+
+	override dispose(): void {
+		// Dispose all watchers
+		for (const watcher of Object.values(this._watchers)) {
+			watcher.dispose();
+		}
```
Comment (jrieken) [inline src/vs/editor/common/services/modelService.ts:718]: just fyi that the `dispose`-utility support iterables, eg `dispose(Object.values(this._watchers))` would work

**Review by jrieken — APPROVED** [review]

File: src/vs/editor/common/services/modelService.ts (hunk 1 above)
Comment (alexdima) [reply src/vs/editor/common/services/modelService.ts:718]: :+1: Good point. This regex finds around 50 usages that might be replaced `for.*\{\n\s*.*\.dispose\(\);\n\s*\}`

**Comment by gjsjohnmurray** [comment]
@alexdima is it too late to make this a candidate for 1.67.2? I have already seen several Python users open issues here which likely originate from the Pylance extension triggering this.

**Comment by alexdima** [comment]
This is not a VS Code regression. The root cause is that we receive invalid semantic tokens data (e.g. we receive an edit which says “insert a new token at offset 4 billion in this array”). We didn’t validate that specific wrong kind of value and ended up doing a loop up to 4 billion to copy the first 4 billion elements before the insertion. I think the code on our side is there in that shape since more than 1 year, so I can only explain that this is now such a big problem because Pylance maybe changed something recently. We plan to tackle this by releasing a new Pylance extension with the fix.
