### PR TITLE
ctrl+c on ipad

### LINKED ISSUE #114009: iPadOS: Ctrl + C in terminal doesn’t kill running process
## Description 

Hitting `ctrl` + `c` with the terminal focused and a process running (i.e. `yarn start` in a React app) does not kill the process. 

If someone is able to provide a good starting point, I would be willing to take a stab at this.

- VSCode Version: 1.53.0-insider
- OS Version: iPadOS 14.1 (18A8395)
- Commit: 01089c0a5052432594a177f90ad9f3148ec2a6a2
- Date: 2021-01-07T05:25:51.740Z (16 hrs ago)
- Browser: Mozilla/5.0 (iPad; CPU OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.77 Mobile/15E148 Safari/604.1

## Steps to Reproduce:

1. On iPad, open Codespaces environment in Chrome
2. Open integrated Terminal
3. Start application (i.e. like a create-react-app - `yarn start`)
4. Focus terminal and hit `ctrl` + `c`

## Expected

Process (`yarn start`) should stop running

## Actual
Terminal receives new line

https://user-images.githubusercontent.com/3806031/103948200-a11ad800-50f6-11eb-8cb4-87e951735911.MP4

Does this issue occur when all extensions are disabled?: Yes

Related:
- https://github.com/cdr/code-server/issues/1343

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #114009

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/common/terminal.ts [hunk 1]
```diff
@@ -24,6 +24,9 @@ export const KEYBINDING_CONTEXT_TERMINAL_SHELL_TYPE_KEY = 'terminalShellType';
 /** A context key that is set to the detected shell for the most recently active terminal, this is set to the last known value when no terminals exist. */
 export const KEYBINDING_CONTEXT_TERMINAL_SHELL_TYPE = new RawContextKey<string>(KEYBINDING_CONTEXT_TERMINAL_SHELL_TYPE_KEY, undefined, { type: 'string', description: nls.localize('terminalShellTypeContextKey', "The shell type of the active terminal") });
 
+export const KEYBINDING_CONTEXT_IPAD_KEY = 'isIPad';
+export const KEYBINDING_CONTEXT_IPAD = new RawContextKey(KEYBINDING_CONTEXT_IPAD_KEY, false, nls.localize(KEYBINDING_CONTEXT_IPAD_KEY, 'Whether the device is an ipad'));
+
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/common/terminal.ts:29]: This won't work without actually hooking up setting the context key's value, I don't think we need it though since `if (isIPad)` handles it. If we wanted to make it easier to target iPad specifically we could add this to where the isWindows/isMac/etc. context keys live but it's probably not worth the effort right now.

File: src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts [hunk 2]
```diff
@@ -119,6 +120,14 @@ if (platform.isWindows) {
 	});
 }
 
+// send ctrl+c to the iPad when the terminal is focused and ctrl+c is pressed to kill the process
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts:123]: Let's include the link to the issue here

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/common/terminal.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/common/terminal.ts:29]: Yes I considered adding it to platform where those are. I do think it will work as a result of the isIpad check, right?

I considered setting it within terminalService or something, but thought that was unnecessary.

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/common/terminal.ts:29]: I see what you mean actually
