### PR TITLE
SCM - fix an issue with window title variables

### LINKED ISSUE #205643: Multi Folder Workspace title only changes on file change
Testing #205539

1. Open a multi folder workspace with 1 repository each
2. switch the branch
3. branch name updates in the statusbar, but not in the title bar until the user switches to a new tab/file

### PR DESCRIPTION
**Pull request by lszomoru**
Fixes #205643

### CODE REVIEW

File: src/vs/workbench/contrib/scm/browser/activity.ts [hunk 1]
```diff
@@ -224,8 +224,9 @@ export class SCMActiveRepositoryContextKeyController implements IWorkbenchContri
 	private activeRepositoryNameContextKey: IContextKey<string>;
 	private activeRepositoryBranchNameContextKey: IContextKey<string>;
 
+	private focusedRepository: ISCMRepository | undefined = undefined;
+	private focusDisposable: IDisposable = Disposable.None;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/scm/browser/activity.ts:228]: My preferred pattern here is `MutableDisposable` which allows you to register possible disposables at the time of object creation, so you wouldn't need to implement/override a `dispose` function.

**Review by Tyriar — APPROVED** [review]
