### PR TITLE
Provide feedback on malformed JSON of argv.json

### LINKED ISSUE #151200: Show an error when changing display language results in broken `argv.json`
I was trying to test @TylerLeonhardt's display language picker changes but no matter what I tried the language pack I picked wouldn't get applied after restart.

This was in Log (Main):
```
[2022-06-02 16:11:03.860] [main] [error] SyntaxError: Unexpected token } in JSON at position 185
    at JSON.parse (<anonymous>)
    at yt.afterWindowOpen (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:75:75972)
```

Which lead me to 

https://github.com/microsoft/vscode/blob/d9373893583a1b78df346f4671bc24221d5e5aba/src/vs/code/electron-main/app.ts#L1164-L1166

My args file:
```
// This configuration file allows to pass permanent command line arguments to VSCode.
// Only a subset of arguments is currently supported to reduce the likelyhood of breaking
// the installation.
//
// PLEASE DO NOT CHANGE WITHOUT UNDERSTANDING THE IMPACT
//
// If the command line argument does not have any values, simply assign
// it in the JSON below with a value of 'true'. Otherwise, put the value
// directly.
//
// If you see rendering issues in VSCode and have a better experience
// with software rendering, you can configure this by adding:
//
// 'disable-hardware-acceleration': true
//
// NOTE: Changing this file requires a restart of VSCode.
{
	// Enabled by default by VSCode to resolve color issues in the renderer
	// See https://github.com/Microsoft/vscode/issues/51791 for details
	"disable-color-correct-rendering": true,
	// Display language of VSCode
	"locale": "de",
	// Allows to disable crash reporting.
	// Should restart the app if the value is changed.
	"enable-crash-reporter": true,
	// Unique id used for correlating crash reports sent from this instance.
	// Do not edit this value.
	"crash-reporter-id": "9ca60cf1-0992-49ea-b103-33244d6da605",
}
```

After staring at this for a few minutes I noticed and removed the extra comma, which of course fixed everything.

I don't think I've ever edited this file by hand so I don't know how that comma ended up in there.

It also would have been very helpful to know that my args file was malformed.

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
This PR fixes #151200

image

### CODE REVIEW

File: src/vs/workbench/services/configuration/common/jsonEditingService.ts [hunk 1]
```diff
@@ -38,6 +39,18 @@ export class JSONEditingService implements IJSONEditingService {
...
+	// Throws if the content is not valid JSON
+	async read(resource: URI): Promise<any> {
+		const exists = await this.fileService.exists(resource);
+		if (!exists) {
+			throw new Error('Resource does not exist');
+		}
+		const reference = await this.textModelResolverService.createModelReference(resource);
+
+		const value = reference.object.textEditorModel.getValue();
+		return JSON.parse(stripComments(value));
```
Comment (TylerLeonhardt) [inline src/vs/workbench/services/configuration/common/jsonEditingService.ts:51]: @bpasero if the argv.json file supports trailing `,` I can update this to use `parse` from `base/common/json`

**Review by joyceerhl — DISMISSED** [review]

File: src/vs/workbench/services/configuration/common/jsonEditingService.ts (hunk 1 above)
Comment (bpasero) [reply src/vs/workbench/services/configuration/common/jsonEditingService.ts:51]: We read it very early in main.js where we dont have access to our modules:

https://github.com/microsoft/vscode/blob/32d40cf44e893e87ac33ac4f08de1e5f7fe077fc/src/main.js#L238-L246

File: src/vs/workbench/services/configuration/common/jsonEditing.ts [hunk 2]
```diff
@@ -38,4 +38,5 @@ export interface IJSONEditingService {
 	readonly _serviceBrand: undefined;
 
 	write(resource: URI, values: IJSONValue[], save: boolean): Promise<void>;
+	read(resource: URI): Promise<any>;
```
Comment (bpasero) [inline src/vs/workbench/services/configuration/common/jsonEditing.ts:41]: I am not sure this is needed when ITextFileService already exists.

File: src/vs/workbench/contrib/localization/electron-sandbox/localeService.ts [hunk 3]
```diff
@@ -26,11 +28,27 @@ export class NativeLocaleService implements ILocaleService {
...
+	private async writeLocaleValue(locale: string | undefined): Promise<boolean> {
+		try {
+			await this.jsonEditingService.read(this.environmentService.argvResource);
+		} catch (error) {
+			this.notificationService.notify({
+				severity: Severity.Error,
+				message: localize('argvInvalid', 'Your argv.json file is not valid. Please open it and fix any parse errors so that your display language can be set properly.'),
+				actions: {
+					primary: [
+						new Action('openArgv', localize('openArgv', "Open argv.json"), undefined, true, () => this.commandService.executeCommand('workbench.action.configureRuntimeArguments')),
```
Comment (bpasero) [inline src/vs/workbench/contrib/localization/electron-sandbox/localeService.ts:44]: I suggest to use editor service directly here and open the file.

**Review by bpasero — CHANGES_REQUESTED** [review]

File: src/vs/workbench/services/configuration/common/jsonEditingService.ts (hunk 1 above)
Comment (TylerLeonhardt) [reply src/vs/workbench/services/configuration/common/jsonEditingService.ts:51]: I think a big help would be to strip that trailing comma on the last line of `argv.json` if one is there. Logic for that shouldn't be too bad right? What do you think?

File: src/vs/workbench/contrib/localization/electron-sandbox/localeService.ts (hunk 3 above)
Comment (TylerLeonhardt) [reply src/vs/workbench/contrib/localization/electron-sandbox/localeService.ts:52]: done

File: src/vs/workbench/contrib/localization/electron-sandbox/localeService.ts [hunk 4]
```diff
@@ -26,11 +30,33 @@ export class NativeLocaleService implements ILocaleService {
...
+
+			const content = await this.textFileService.read(this.environmentService.argvResource, { encoding: 'utf8' });
+
+			// This is the same logic that we do where argv.json is parsed so mirror that:
+			// https://github.com/microsoft/vscode/blob/32d40cf44e893e87ac33ac4f08de1e5f7fe077fc/src/main.js#L238-L246
+			JSON.parse(stripComments(content.value));
+		} catch (error) {
+			this.notificationService.notify({
+				severity: Severity.Error,
+				message: localize('argvInvalid', 'Your argv.json file is not valid. Please open it and fix any parse errors so that your display language can be set properly.'),
```
Comment (bpasero) [inline src/vs/workbench/contrib/localization/electron-sandbox/localeService.ts:49]: Maybe we can make this more user friendly: the fact that we store the locale in a file `argv.json` is not so important imho. In the end I would just indicate that the settings file where we store the locale is malformed and needs manual fixing.

I think settings editor has a similar error notification, maybe we can borrow the wording.

**Review by bpasero — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/localization/electron-sandbox/localeService.ts (hunk 3 above)
Comment (TylerLeonhardt) [reply src/vs/workbench/contrib/localization/electron-sandbox/localeService.ts:52]: I'm now using the TextFileService. Is that not what you meant by this?

**Review by ubaisa — DISMISSED** [review]

File: src/vs/workbench/contrib/localization/electron-sandbox/localeService.ts (hunk 3 above)
Comment (bpasero) [reply src/vs/workbench/contrib/localization/electron-sandbox/localeService.ts:52]: I meant opening the argv.json file via editor service instead of relying on an internal command.

Comment (TylerLeonhardt) [reply src/vs/workbench/contrib/localization/electron-sandbox/localeService.ts]: ah! Done now.

File: src/vs/workbench/services/configuration/common/jsonEditingService.ts [hunk 5]
```diff
@@ -38,6 +39,18 @@ export class JSONEditingService implements IJSONEditingService {
 		return Promise.resolve(this.queue.queue(() => this.doWriteConfiguration(resource, values, save))); // queue up writes to prevent race conditions
 	}
 
+	// Throws if the content is not valid JSON
+	async read(resource: URI): Promise<any> {
+		const exists = await this.fileService.exists(resource);
+		if (!exists) {
+			throw new Error('Resource does not exist');
+		}
+		const reference = await this.textModelResolverService.createModelReference(resource);
```
[the remark this answers is not in the document]
Comment (TylerLeonhardt) [reply src/vs/workbench/services/configuration/common/jsonEditingService.ts]: gone.

File: src/vs/workbench/services/configuration/common/jsonEditingService.ts [hunk 6]
```diff
@@ -29,7 +30,7 @@ export class JSONEditingService implements IJSONEditingService {
 	constructor(
 		@IFileService private readonly fileService: IFileService,
 		@ITextModelService private readonly textModelResolverService: ITextModelService,
-		@ITextFileService private readonly textFileService: ITextFileService
+		@ITextFileService private readonly textFileService: ITextFileService,
```
[the remark this answers is not in the document]
Comment (TylerLeonhardt) [reply src/vs/workbench/services/configuration/common/jsonEditingService.ts]: gone.

File: src/vs/workbench/services/configuration/common/jsonEditingService.ts (hunk 1 above)
Comment (TylerLeonhardt) [reply src/vs/workbench/services/configuration/common/jsonEditingService.ts]: Martin did this already.

File: src/vs/workbench/contrib/localization/electron-sandbox/localeService.ts [hunk 7]
```diff
@@ -26,11 +30,33 @@ export class NativeLocaleService implements ILocaleService {
...
+		@IProgressService private readonly progressService: IProgressService,
+		@ICommandService private readonly commandService: ICommandService,
+		@ITextFileService private readonly textFileService: ITextFileService
 	) { }
 
-	private async writeLocaleValue(locale: string | undefined): Promise<void> {
+	private async writeLocaleValue(locale: string | undefined): Promise<boolean> {
+		try {
+
+			const content = await this.textFileService.read(this.environmentService.argvResource, { encoding: 'utf8' });
```
[the remark this answers is not in the document]
Comment (TylerLeonhardt) [reply src/vs/workbench/contrib/localization/electron-sandbox/localeService.ts:40]: addressed this.

**Review by bpasero — APPROVED** [review]
