### PR TITLE
Normalize tsconfig path

### LINKED ISSUE #68812: TypeScript task detection is not cross-platform
Issue Type: <b>Bug</b>

If your `tsconfig.json` is in a subfolder, the folder path has to match the system file separator (\\ on Windows, / on Mac/Linux) in order for it to work.

Steps to Reproduce:

1. Create a project with a folder in it.
2. Put tsconfig.json in the subfolder along with a test TypeScript file.
3. Create a build task for that tsconfig.json. On Windows it will get a backslash, on Mac/Linux a forward slash.
4. Switch the slash to that of the opposite platform.
5. Note that now you can't build that task, and that instead you get an error similar to the following:

```
Error: The typescript task detection didn't contribute a task for the following configuration:
{
    "label": "tsc-api",
    "type": "typescript",
    "tsconfig": "api/tsconfig.json",
    "option": "watch",
    "options": {
        "cwd": "${workspaceFolder}/api"
    },
    "promptOnClose": true,
    "problemMatcher": [
        "$tsc-watch"
    ],
    "group": "build"
}
The task will be ignored.
```

The only workaround I've found is to create TWO tasks for each desired task, where one has forward slashes and the other backslashes. But a recent VS Code update made a warning box appear for those configurations _every time I build or debug_, which is annoying. Please address the underlying issue.

Honestly, this would be _yet another situation_ where simply using forward slashes _all the time_ would fix everything. This would also fix, for instance:

https://github.com/Microsoft/vscode/issues/35593

...a bug that's been around for a year and a half now. :(

VS Code version: Code - Insiders 1.32.0-insider (003521e715f2dbcf4f98be99a923097505859954, 2019-02-15T06:16:29.903Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (2.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

### PR DESCRIPTION
**Pull request by NizamLZ**
Normalize tsconfig path before task identifier generation to resolve #68812

Cause:
The task identifier is generated using the required fields of a given task type. For typescript, the value of the `tsconfig` is included in the task identifier. Typescript extension is generating the value of tsconfig using the platform specific path separator(irrespective of the value in tasks.json) but the `createTaskIdentifier()` in [common/tasks.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/tasks/common/tasks.ts#L994) is using the value present in tasks.json.
Hence `configuringTask` in [task.contribution.ts#L1467](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts#L1467) is evaluated as `null` (the task identifiers don't match), making the task invalid.
This PR normalizes the value of tsconfig before the task identifier is generated.

### CODE REVIEW

File: src/vs/workbench/contrib/tasks/common/taskConfiguration.ts [hunk 1]
```diff
@@ -1339,6 +1340,9 @@ namespace ConfiguringTask {
 			));
 			return undefined;
 		}
+		if (identifier.type === 'typescript' && identifier.tsconfig) {
```
Comment (alexr00) [inline src/vs/workbench/contrib/tasks/common/taskConfiguration.ts]: Having a check for an extension contributed task type in VS Code core breaks our layering philosophy: VS Code core shouldn't know about anything extension specific. Instead, the typescript extension should do this. It should be somewhere around here: https://github.com/Microsoft/vscode/blob/master/extensions/typescript-language-features/src/features/task.ts#L174

**Review by alexr00 — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/tasks/common/taskConfiguration.ts (hunk 1 above)
Comment (NizamLZ) [reply src/vs/workbench/contrib/tasks/common/taskConfiguration.ts]: Yes I was very hesitant of this if condition as well. But in this case, ts extension code is correct and VS Code core has the bug! tsconfig file path normalization is a very special case, non of the other supported task types have a path string in them.
The if condition a few lines above `if (customize.indexOf(typescript) === 0)` inspired me to do this. 

The only alternative I can think of is that, inside ts extention, when tasks are generated, the task label should be read from tasks.json file instead of the auto generated Task. Which means, ts extension should find and read .vscode/tasks.json. I don't think that is also a suggested change!

Comment (alexr00) [reply src/vs/workbench/contrib/tasks/common/taskConfiguration.ts]: In the typescript extension, can't you just use the OS specific path for the tsconfig?

Comment (alexr00) [reply src/vs/workbench/contrib/tasks/common/taskConfiguration.ts]: Thinking about it some more, it seems like the typescript extension should just not use the OS specific path for the tsconfig property.

Comment (NizamLZ) [reply src/vs/workbench/contrib/tasks/common/taskConfiguration.ts]: For typescript extension to use what's written in the tasks.json instead of OS specific path, we will have to read .vscode/tasks.json from the extension, if that is advisable, I am willing to do that. What do you say?

Comment (alexr00) [reply src/vs/workbench/contrib/tasks/common/taskConfiguration.ts]: I don't think that the typescript should use what's written in tasks.json, I just think that it should use the non-OS specific path.

Comment (NizamLZ) [reply src/vs/workbench/contrib/tasks/common/taskConfiguration.ts]: Means it should always use '/' irrespective of the OS?

Comment (alexr00) [reply src/vs/workbench/contrib/tasks/common/taskConfiguration.ts]: That is what I meant, but actually we shouldn't change this. I don't want to break existing users who have it configured using the OS specific path. Because of this, there shouldn't be a code fix for this issue.

Comment (alexr00) [reply src/vs/workbench/contrib/tasks/common/taskConfiguration.ts]: We do have precendent for breaking things like this though. It would be a better experience to use the non-OS specific path in the typescript extension. That is still the change we should make!

Comment (NizamLZ) [reply src/vs/workbench/contrib/tasks/common/taskConfiguration.ts]: Alright @alexr00, will make the change accordingly but I think, its a big one. Unless 'tsconfig' is the only property in typescript task which has path as a value. Will update this PR.

File: extensions/typescript-language-features/src/features/task.ts [hunk 2]
```diff
@@ -231,10 +232,13 @@ class TscTaskProvider implements vscode.TaskProvider {
...
 	private getLabelForTasks(project: TSConfig): string {
+		let projectPath: string | undefined = undefined;
 		if (project.workspaceFolder) {
-			return path.relative(project.workspaceFolder.uri.fsPath, project.path);
+			projectPath = path.relative(project.workspaceFolder.uri.fsPath, project.path);
+		} else {
+			projectPath = project.path;
 		}
-		return project.path;
+		return normalizePath(projectPath);
```
Comment (NizamLZ) [inline extensions/typescript-language-features/src/features/task.ts]: @alexr00, done as suggested. Had to use a custom normalizePath() since path.posix.normalize() does not convert win32 paths to unix.

Comment (NizamLZ) [reply extensions/typescript-language-features/src/features/task.ts]: One thing to note as you mentioned earlier, all the tasks.json files around the world which have windows path separators will show 'There are task errors' dialog with the below output:
image

Comment (alexr00) [reply extensions/typescript-language-features/src/features/task.ts]: That is correct. We did something similar with ${relativeFile} [here](https://github.com/Microsoft/vscode/issues/70050)

Comment (NizamLZ) [reply extensions/typescript-language-features/src/features/task.ts]: @alexr00, If all is good, can you please approve this PR.

Comment (alexr00) [reply extensions/typescript-language-features/src/features/task.ts]: @NizamLZ we are in our [endgame](https://github.com/Microsoft/vscode/issues/73175) now, which means that we are trying to only make critical changes. We were slowing down our changes last week too. Because of this, I'll need to wait until next week to merge this PR.

Comment (NizamLZ) [reply extensions/typescript-language-features/src/features/task.ts]: Got it. I was just hoping for an approval of the PR, not merge. Non the less, I now understand that the PR is accepted. 

PS: This **'we are in the endgame now'** gives me chills! @Avengers

**Review by alexr00 — APPROVED** [review]

**Comment by erinha** [comment]
I was just auto-updated to the latest version of VS code and noticed that my custom tasks now always caused an error: `"Error: The typescript task detection didn't contribute a task for the following configuration ... The task will be ignored."` I was surprised since the tasks seemed to be working before the upgrade.

 

After quite a bit of time spelunking the VS Code update list and following many issue links, I discovered that this change appears to have broken all existing and working tasks.json of this form. This is particularly notable because, from what I can tell, the newly required form (forward slashes instead of backslashes) does not work on older versions. It seems like the ramifications of this are that literally all VS Code users who has custom tasks of the old form will immediately break on upgrade (which they may not even realize happened, since it frequently happens automatically). Moreover, it will not be obvious to them what broke or how to fix it: there's no obvious error message or indication of exactly the new requirement.

 

When I did come across this thread, I was surprised to find that this exact issue was called out above: we're going to break all Windows users and seemingly dismissed.  While I don't want to suggest that breaking changes can never be introduced, it seems like this particular change is going to cause untold developer hours trying to understand why their tasks broke suddenly, how to fix the problem, etc.  Is it possible to elaborate on the threshold for when breaking changes like this can be introduced without any warning or obvious remediation alerts?  Are there times when backwards compatibility should be considered?  Or maybe I'm misunderstanding the impact (i.e. will there be fewer devs broken by this than I think and somehow I got lucky?)

 

Thanks!

**Comment by alexr00** [comment]
@erinha you are right that there should have been some sort of announcement for this. I should have included it in the release notes. In this case, the breaking change fixed a bug (typescript tasks could not be customized in a cross platform way). We have a precedence for this kind of change (https://github.com/Microsoft/vscode/issues/70050). This change will impact Windows users who have customized typescript tasks.
