### PR TITLE
Restore default paste fallback

### LINKED ISSUE #192196: Pasting is not selecting the newly pasted text
This happens after a regular ctrl+v:

Image

It's very easy to reproduce.

버전: 1.82.0-insider (user setup)
커밋: f1302be1e67e3af5fbeb8bbb2ea784de7bc96150
날짜: 2023-09-01T11:08:40.414Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #192196

### CODE REVIEW

File: src/vs/editor/contrib/dropOrPasteInto/browser/copyPasteController.ts [hunk 1]
```diff
@@ -283,6 +283,12 @@ export class CopyPasteController extends Disposable implements IEditorContributi
 					return;
 				}
 
+				// If the only edit returned is a text edit, use the default paste handler
```
Comment (hamirmahal) [inline src/vs/editor/contrib/dropOrPasteInto/browser/copyPasteController.ts:286]:
```suggestion
				// If the only edit returned is a text edit, use the default paste handler.
```

Comment (hamirmahal) [inline src/vs/editor/contrib/dropOrPasteInto/browser/copyPasteController.ts:286]:
```suggestion
				// If the only edit returned is a text edit, use the default paste handler.
```
This is just for consistency, like on [line 272](https://github.com/microsoft/vscode/pull/192220/files#diff-3558a9a40fa1a73d2dc9f1b6c00c184581eaa73ff926625b390ab3bf6e116ea6R272). Feel free to ignore this if you don't think it's helpful.

**Review by Tyriar — APPROVED** [review]

**Review by rzhao271 — APPROVED** [review]
