### PR TITLE
load webgl add-on for new terminals

### LINKED ISSUE #140128: New integrated terminals are never GPU-accelerated
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: macOS 11.6.1

Even if `terminal.integrated.gpuAcceleration` is set to `on` or `auto`, newly opened integrated terminals will never be GPU-accelerated. Whenever the `terminal.integrated.gpuAcceleration` setting is changed while an integrated terminal is open, the behavior is corrected.

To be a little clearer, for newly opened integrated terminals, when the `terminal.integrated.gpuAcceleration` setting is:

- `off` or `canvas`, terminal behaves as expected.
- `on` or `canvas`, terminal scrolls slowly as if it's not being GPU-accelerated (seems to behave like `canvas`).

After changing from one setting to another, unexpected behavior in open integrated terminals is corrected. Terminals opened after the change will exhibit the unexpected behavior again.

Here's a video to demonstrate the issue:

https://user-images.githubusercontent.com/6618434/148135080-c905eb32-b6f8-4b6c-af71-49fe48143f00.mov

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #140128

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalInstance.ts [hunk 1]
```diff
@@ -626,6 +626,9 @@ export class TerminalInstance extends Disposable implements ITerminalInstance {
 			this._linkManager = this._instantiationService.createInstance(TerminalLinkManager, xterm.raw, this._processManager!);
 			this._areLinksReady = true;
 			this._onLinksReady.fire(this);
+			if ((!isSafari && this._configHelper.config.gpuAcceleration === 'auto') || this._configHelper.config.gpuAcceleration === 'on') {
```
Comment (meganrogge) [inline src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:629]: waiting for on process ready allows `xterm.raw.element` to become defined, which is necessary to load the webgl add-on

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:629]: can't just call from the constructor (after `xterm.raw` is defined because it's async

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:629]: Immediately after `this.raw.open` is called is ideal

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:629]: that's in a synch method. could create an event, but that seems like overkill

Comment (meganrogge) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:629]: https://github.com/microsoft/vscode/blob/bdb513f5451a2045b7dc5daef7bd75dd1ac24135/src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts#L151

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalInstance.ts:629]: Calling `xterm.enableWebglRenderer();` without the await should be alright, that's similar to how it's done in the event anyhow as nothing happens after the event resolves.
