### PR TITLE
fix shell integration issues after clearing

### LINKED ISSUE #145148: first command run after clear does not have a decoration
1. run some commands
2. run `Terminal: Clear`
3. placeholder shows up ✅ 
4. run a command 🐛 the placeholder is gone, but the decoration to replace it isn't there

### LINKED ISSUE #151217: after clearing, next command run is not correct
Screen Shot 2022-06-03 at 7 40 12 AM

### PR DESCRIPTION
**Pull request by meganrogge**
This PR fixes #145148 fixes #151217

### CODE REVIEW

**Comment by meganrogge** [comment]
oh I think what happens is the top line is just retained of the prompt and not cleared

**Comment by meganrogge** [comment]
which explains why xterm.js doesn't parse anything even though the prompt appears to show up after the `clear`

**Review by roblourens — APPROVED** [review]

File: src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts [hunk 1]
```diff
@@ -396,8 +396,10 @@ export class XtermTerminal extends DisposableStore implements IXtermTerminal {
 
 	clearBuffer(): void {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts:397]: I notice now this is used by tasks and something wrong likely happens with and without this change:

https://github.com/microsoft/vscode/blob/9ade6a663662c5e4805038a6e3b3b4ba2f648472/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1297-L1299

**Review by Tyriar — APPROVED** [review]
Similar thing to what was there before, 👍 if it works on bash, zsh and pwsh. pwsh works fine currently probably because it gets the command line set explicitly so prompt start/command start aren't as important.

File: src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts (hunk 1 above)
Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts:397]: In tasks it may end up adding a decoration when presentation options say clear.
