### PR TITLE
Fix SessionViewPane leaks

### LINKED ISSUE #274236: SessionViewPane leaks dropdown, menu items
Open VSCode and bring up chat sessions pane and create a new chat editor.

Dropdown action and menu are leaked.

```
"[LEAKED DISPOSABLE] Error: CREATED via:
at GCBasedDisposableTracker.trackDisposable (vscode-file://vscode-app/c:/Repos/vscode/out/vs/base/common/lifecycle.js:28:23)
at trackDisposable (vscode-file://vscode-app/c:/Repos/vscode/out/vs/base/common/lifecycle.js:204:24)
at new Disposable (vscode-file://vscode-app/c:/Repos/vscode/out/vs/base/common/lifecycle.js:417:9)
at new Action (vscode-file://vscode-app/c:/Repos/vscode/out/vs/base/common/actions.js:16:9)
at SessionsViewPane.getChatSessionDropdown (vscode-file://vscode-app/c:/Repos/vscode/out/vs/workbench/contrib/chat/browser/chatSessions/view/sessionsViewPane.js:135:32)
at SessionsViewPane.createActionViewItem (vscode-file://vscode-app/c:/Repos/vscode/out/vs/workbench/contrib/chat/browser/chatSessions/view/sessionsViewPane.js:109:25)
at Object.actionViewItemProvider (vscode-file://vscode-app/c:/Repos/vscode/out/vs/workbench/browser/parts/views/viewPane.js:332:35)
at Object.actionViewItemProvider (vscode-file://vscode-app/c:/Repos/vscode/out/vs/base/browser/ui/toolbar/toolbar.js:61:44)
at vscode-file://vscode-app/c:/Repos/vscode/out/vs/base/browser/ui/actionbar/actionbar.js:256:37
at Array.forEach (<anonymous>)", source: vscode-file://vscode-app/c:/Repos/vscode/out/vs/base/common/lifecycle.js (24)
[19752:1030/154115.078:INFO:CONSOLE:24]
```

### PR DESCRIPTION
**Pull request by vijayupadya**
Fixes #274236

The getChatSessionDropdown method created disposable objects (dropdownAction Action and menu IMenu) that were never registered with a parent or explicitly disposed. These orphaned disposables were passed to DropdownWithPrimaryActionViewItem but the view item doesn't take ownership, causing them to leak.

### CODE REVIEW

File: src/vs/workbench/contrib/chat/browser/chatSessions/view/sessionsViewPane.ts [hunk 1]
```diff
@@ -137,13 +139,17 @@ export class SessionsViewPane extends ViewPane {
...
 
 	private getChatSessionDropdown(defaultAction: IAction, options: IBaseActionViewItemOptions) {
+		// Clear previous disposables to avoid leaks when action view items are recreated
+		this._dropdownDisposables.clear();
+
 		const primaryAction = this.instantiationService.createInstance(MenuItemAction, {
 			id: defaultAction.id,
 			title: defaultAction.label,
 			icon: Codicon.plus,
 		}, undefined, undefined, undefined, undefined);
```
[the remark this answers is not in the document]
Comment (vijayupadya) [reply src/vs/workbench/contrib/chat/browser/chatSessions/view/sessionsViewPane.ts:144]: not valid

File: src/vs/workbench/contrib/chat/browser/chatSessions/view/sessionsViewPane.ts [hunk 2]
```diff
@@ -171,6 +177,7 @@ export class SessionsViewPane extends ViewPane {
 			'codicon-chevron-down',
 			true
 		);
+		this._dropdownDisposables.add(dropdownAction);
```
Comment (mjbvz) [inline src/vs/workbench/contrib/chat/browser/chatSessions/view/sessionsViewPane.ts]: Can `dropdownAction` be converted to use `toAction` instead? That version of `IAction` isn't disposable

File: src/vs/workbench/contrib/chat/browser/chatSessions/view/sessionsViewPane.ts [hunk 3]
```diff
@@ -137,13 +139,17 @@ export class SessionsViewPane extends ViewPane {
...
+		// Clear previous disposables to avoid leaks when action view items are recreated
+		this._dropdownDisposables.clear();
+
 		const primaryAction = this.instantiationService.createInstance(MenuItemAction, {
 			id: defaultAction.id,
 			title: defaultAction.label,
 			icon: Codicon.plus,
 		}, undefined, undefined, undefined, undefined);
 
 		const menu = this.menuService.createMenu(MenuId.ChatSessionsMenu, this.scopedContextKeyService);
```
Comment (mjbvz) [inline src/vs/workbench/contrib/chat/browser/chatSessions/view/sessionsViewPane.ts]: Maybe this could be switched to use `getMenuActions` instead?

File: src/vs/workbench/contrib/chat/browser/chatSessions/view/sessionsViewPane.ts (hunk 2 above)
Comment (vijayupadya) [reply src/vs/workbench/contrib/chat/browser/chatSessions/view/sessionsViewPane.ts]: updated

File: src/vs/workbench/contrib/chat/browser/chatSessions/view/sessionsViewPane.ts (hunk 3 above)
Comment (vijayupadya) [reply src/vs/workbench/contrib/chat/browser/chatSessions/view/sessionsViewPane.ts]: updated

**Review by mjbvz — APPROVED** [review]
