### PR TITLE
Fix continuation for configured default shell not used when reconnecting to Codespace

### LINKED ISSUE #175107: Configured default shell not used when reconnecting to Codespace
Does this issue occur when all extensions are disabled?: Yes

Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

When reconnecting to an existing Codespace, my `"terminal.integrated.defaultProfile.linux"` configuration is ignored. Instead of `zsh`, the terminal always starts `bash`.

The same/a similar issue used to exist in early 2022 but was presumably fixed with https://github.com/microsoft/vscode/pull/154290, however this appears to have regressed over the last weeks/months.

Steps to Reproduce:

1. Configure `"terminal.integrated.defaultProfile.linux": "zsh"`
2. Create a Codespace & stop it
3. Reconnect to the Codespace
4. See that the terminal opens using `bash`

### LINKED ISSUE #181515: First terminal does not follow default.
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.78.0 
- OS Version: Mac OS 13.3.1

Steps to Reproduce:

1. Open a new VSCode window using Codespaces. 
2. The initial terminal window opens a `bash` terminal. If I kill that terminal and open a new terminal, I get `zsh` as expected. 

I have in my settings.json:
```
  "terminal.integrated.defaultProfile.linux": "zsh",
```

I believe this is a duplicate of these closed issues: 
- https://github.com/microsoft/vscode/issues/142425
- https://github.com/microsoft/vscode/issues/142649

### PR DESCRIPTION
**Pull request by jeanp413**
Fix continuation when the remote takes more than 20s to resolve, e.g. codespaces

Fixes #175107
Fixes #181515

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts [hunk 1]
```diff
@@ -67,10 +68,14 @@ export class TerminalProfileService implements ITerminalProfileService {
...
-		// this long.
-		this._profilesReadyBarrier = new AutoOpenBarrier(20000);
+		this._profilesReadyPromise = this._remoteAgentService.getEnvironment()
+			.then(() => {
+				// Wait up to 20 seconds for profiles to be ready so it's assured that we know the actual
+				// default terminal before launching the first terminal. This isn't expected to ever take
+				// this long.
+				this._profilesReadyBarrier = new AutoOpenBarrier(20000);
+				return this._profilesReadyBarrier.wait().then(() => { });
+			});
```
Comment (jeanp413) [inline src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts:78]: I lack the context why this barrier was needed before, maybe is not needed anymore and we can remove it? With this change we start the barrier after the remote have been completely resolved, before that vscode is in `Opening remote...` state waiting for the extension RemoteAuthorityResolver to finish

Comment (Tyriar) [reply src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts:78]: We could maybe remove it, but I'm a little scared to tbh 🙂

Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/terminalProfileService.ts:78]: @roblourens I don't think we end up resolving profiles for the ssh extension's special terminal but please ping me if ssh connecting with local servers has problems when this is merged.

**Review by Tyriar — APPROVED** [review]

**Review by alexdima — APPROVED** [review]
