### PR TITLE
Use safer pasted input chunking algorithm

### LINKED ISSUE #180257: Built-in linux terminal crashes when pasting 39-character string into nano
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.3
- OS Version: Ubuntu 20.04.6

Steps to Reproduce:

1. Launch VSCode on an Ubuntu computer (or on Windows using WSL)
2. Enter the built-in terminal
3. Run the command `nano`
4. Copy and paste the following 39-character string into nano: `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`
5. Result: nano shows the error message "Unknown Sequence". Can no longer interact with the terminal, need to kill it and open a new one

More details:
- nano version 4.8
- This does not happen in nano using an external terminal. Only in VSCode's built-in terminal
- This does not happen for any other length of string, even other multiples of 39
- This does not happen in other CLI text editors, such as vim

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #180257

### CODE REVIEW

File: src/vs/platform/terminal/node/terminalProcess.ts [hunk 1]
```diff
@@ -649,3 +645,30 @@ class DelayedResizer extends Disposable {
...
+		if (
+			// If the max chunk size is reached
+			i - nextChunkStartIndex + 1 >= Constants.WriteMaxChunkSize ||
+			// If the next character is ESC, send the pending data to avoid splitting the escape
+			// sequence.
+			data[i + 1] === '\x1b'
+		) {
+			chunks.push(data.substring(nextChunkStartIndex, i + 1));
+			nextChunkStartIndex = i + 1;
+			i++;
```
Comment (rzhao271) [inline src/vs/platform/terminal/node/terminalProcess.ts:666]: Potentially confusing with i++ both here and in the for loop itself. Maybe it can be a while loop?

**Review by joyceerhl — DISMISSED** [review]

File: src/vs/platform/terminal/node/terminalProcess.ts (hunk 1 above)
Comment (Tyriar) [reply src/vs/platform/terminal/node/terminalProcess.ts:666]: I'll leave a comment, that just skips the next character as it'd be 1 in length to save a little time

**Review by lramos15 — APPROVED** [review]
