### PR TITLE
Fix for automatic folderOpen tasks with Remote SSH extension

### LINKED ISSUE #203639: Automatic folderOpen tasks not always run on remote SSH
- VS Code Version: 1.85.2
- OS Version: Linux (OpenSUSE Tumbleweed) as well as Windows 10

If I create an automatic folderOpen task in a folder that I access through VS Code's Remote SSH extension, this task is sometimes run when I open my folder, but it often isn't. It's simple for me to reproduce this on both Windows and Linux, and also with the latest (as of today) Insiders build on Windows. It seems timing related. It also seems like it's less likely to happen if I keep a file open in the workspace when I close it, so that the same file is automatically opened when I open it the next time. I've trusted the workspace.

I have put together a minimal containerized SSH server with a tiny workspace to reproduce this, see https://gist.github.com/emilan/0279df17534785b2b1535239578f679a. I start the container and then connect to it with VS Code over SSH. Please note that the main issue isn't with this container setup. I'm seeing this when connecting to normal remote SSH servers as well. The container is just an attempt to build a minimal reproducible setup, as well as to avoid publishing private details in this report.

I have also added some extra logs to VS Code's source code to try to debug this, see this commit: https://github.com/emilan/vscode/commit/f973ae0103e0ca462a7bdb0bdb0a5601ff2f4c78. I unfortunately wasn't able to get the remote ssh extension working properly with my custom VS Code OSS build. From what I can tell, it seems that Microsoft actually doesn't want me to do that. But I was able to find the corresponding places in the minified `workbench.desktop.main.js` file for my proper VS Code installation, and put my extra logs there instead.

With those changes, the logs from a typical bad run (on Windows) look like this:
```log
2024-01-26 19:56:27.896 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][1273ms] returned WebSocket(127.0.0.1:51548)
2024-01-26 19:56:27.898 [info] resolveAuthority(ssh-remote) returned 'WebSocket(127.0.0.1:51548)' after 1276 ms
2024-01-26 19:56:27.915 [info] Creating a socket (renderer-Management-0ea08084-13b8-48b9-b819-9db8ca2803a7)...
2024-01-26 19:56:27.922 [info] Creating a socket (renderer-ExtensionHost-2c6d915b-5bdd-4fbf-921c-fd4a596921fb)...
2024-01-26 19:56:27.969 [info] Creating a socket (renderer-Management-0ea08084-13b8-48b9-b819-9db8ca2803a7) was successful after 54 ms.
2024-01-26 19:56:27.989 [info] Creating a socket (renderer-ExtensionHost-2c6d915b-5bdd-4fbf-921c-fd4a596921fb) was successful after 68 ms.
2024-01-26 19:56:29.949 [info] RunAutomaticTasks: Trying to run tasks.
2024-01-26 19:56:29.950 [info] RunAutomaticTasks: Awaiting task system info.
2024-01-26 19:56:30.034 [info] getWorkspaceTasks runSource=2
2024-01-26 19:56:30.037 [info] _updateWorkspaceTasks runSource=2
2024-01-26 19:56:30.038 [info] _computeWorkspaceFolderTasks runSource=2
2024-01-26 19:56:30.039 [info] _computeWorkspaceFolderTasks::workspaceFolderConfiguration: {
  "workspaceFolder": {
    "uri": {
      "$mid": 1,
      "fsPath": "\\workspace",
      "_sep": 1,
      "external": "vscode-remote://ssh-remote%2Bvscode-auto-task-test/workspace",
      "path": "/workspace",
      "scheme": "vscode-remote",
      "authority": "ssh-remote+vscode-auto-task-test"
    },
    "name": "workspace",
    "index": 0
  },
  "hasErrors": false
}
2024-01-26 19:56:30.046 [info] RunAutomaticTasks: Found 2 automatic tasks
2024-01-26 19:56:30.047 [info] _runWithPermission::taskNames=[]
2024-01-26 19:56:31.034 [info] [perf] Render performance baseline is 131ms
2024-01-26 19:56:31.217 [info] _updateWorkspaceTasks runSource=3
2024-01-26 19:56:31.218 [info] _computeWorkspaceFolderTasks runSource=3
2024-01-26 19:56:31.229 [info] _computeWorkspaceFolderTasks::workspaceFolderConfiguration: {
  "workspaceFolder": {
    "uri": {
      "$mid": 1,
      "fsPath": "\\workspace",
      "_sep": 1,
      "external": "vscode-remote://ssh-remote%2Bvscode-auto-task-test/workspace",
      "path": "/workspace",
      "scheme": "vscode-remote",
      "authority": "ssh-remote+vscode-auto-task-test"
    },
    "name": "workspace",
    "index": 0
  },
  "config": {
    "version": "2.0.0",
    "tasks": [
      {
        "label": "bg svc",
        "type": "shell",
        "runOptions": {
          "runOn": "folderOpen"
        },
        "presentation": {
          "reveal": "never"
        },
        "command": "sleep 30m",
        "problemMatcher": []
      }
    ]
  },
  "hasErrors": false
}
```

The logs from a typical good run (on Windows) look like this:
```log
2024-01-26 20:00:37.709 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][1008ms] returned WebSocket(127.0.0.1:51577)
2024-01-26 20:00:37.710 [info] resolveAuthority(ssh-remote) returned 'WebSocket(127.0.0.1:51577)' after 1008 ms
2024-01-26 20:00:37.712 [info] Creating a socket (renderer-Management-bdeaebc8-9e86-475a-a71f-36069c9f66ca)...
2024-01-26 20:00:37.715 [info] Creating a socket (renderer-ExtensionHost-08ed65ef-e6ed-4bdf-88da-f07f44b0218c)...
2024-01-26 20:00:37.770 [info] Creating a socket (renderer-Management-bdeaebc8-9e86-475a-a71f-36069c9f66ca) was successful after 57 ms.
2024-01-26 20:00:37.794 [info] Creating a socket (renderer-ExtensionHost-08ed65ef-e6ed-4bdf-88da-f07f44b0218c) was successful after 79 ms.
2024-01-26 20:00:43.345 [info] RunAutomaticTasks: Trying to run tasks.
2024-01-26 20:00:43.346 [info] getWorkspaceTasks runSource=2
2024-01-26 20:00:43.395 [info] _updateWorkspaceTasks runSource=2
2024-01-26 20:00:43.396 [info] _computeWorkspaceFolderTasks runSource=2
2024-01-26 20:00:43.399 [info] _computeWorkspaceFolderTasks::workspaceFolderConfiguration: {
  "workspaceFolder": {
    "uri": {
      "$mid": 1,
      "fsPath": "\\workspace",
      "_sep": 1,
      "external": "vscode-remote://ssh-remote%2Bvscode-auto-task-test/workspace",
      "path": "/workspace",
      "scheme": "vscode-remote",
      "authority": "ssh-remote+vscode-auto-task-test"
    },
    "name": "workspace",
    "index": 0
  },
  "config": {
    "version": "2.0.0",
    "tasks": [
      {
        "label": "bg svc",
        "type": "shell",
        "runOptions": {
          "runOn": "folderOpen"
        },
        "presentation": {
          "reveal": "never"
        },
        "command": "sleep 30m",
        "problemMatcher": []
      }
    ]
  },
  "hasErrors": false
}
2024-01-26 20:00:43.404 [info] RunAutomaticTasks: Found 2 automatic tasks
2024-01-26 20:00:43.405 [info] _runWithPermission::taskNames=["bg svc"]
2024-01-26 20:00:43.773 [info] _updateWorkspaceTasks runSource=1
2024-01-26 20:00:43.774 [info] _computeWorkspaceFolderTasks runSource=1
2024-01-26 20:00:43.775 [info] _computeWorkspaceFolderTasks::workspaceFolderConfiguration: {
  "workspaceFolder": {
    "uri": {
      "$mid": 1,
      "fsPath": "\\workspace",
      "_sep": 1,
      "external": "vscode-remote://ssh-remote%2Bvscode-auto-task-test/workspace",
      "path": "/workspace",
      "scheme": "vscode-remote",
      "authority": "ssh-remote+vscode-auto-task-test"
    },
    "name": "workspace",
    "index": 0
  },
  "config": {
    "version": "2.0.0",
    "tasks": [
      {
        "label": "bg svc",
        "type": "shell",
        "runOptions": {
          "runOn": "folderOpen"
        },
        "presentation": {
          "reveal": "never"
        },
        "command": "sleep 30m",
        "problemMatcher": []
      }
    ]
  },
  "hasErrors": false
}
```

The main difference between these two runs is in what's assigned to `workspaceFolderConfiguration` in `_computeWorkspaceFolderTasks` (`abstractTaskService.ts`), when `_tryRunTasks` (`runAutomaticTasks.ts`) tries to fetch the folderOpen tasks (`TaskRunSource.FolderOpen = 2`). In the good case, I get a config object containing my task. In the bad case, there is no such config object. This is also reflected in the log I added to `_runWithPermission` (`runAutomaticTasks.ts`), where the `taskNames` array is empty in the bad case. 

Please note that in the bad case, there is an update of the tasks fetched in the task service happening soon after VS Code tried to run the automatic tasks. You can see that `_updateWorkspaceTasks` is called with runSource=3 (i.e. `TaskRunSource.ConfigurationChange`), and that the subsequent `workspaceFolderConfiguration` variable assignment actually contains my task. Unfortunately, the code to run the automatic tasks has already been triggered by this time, and isn't retriggered.

In the good case, there is no such update of the fetched tasks based on reconfiguration. But the fetched tasks are also updated when the automatic task is run, which is why you can see similar traces but with `TaskRunSource.User = 1`.

Steps to Reproduce:

1. Start a container like the one in [this](https://gist.github.com/emilan/0279df17534785b2b1535239578f679a) gist
2. Update your .ssh/config file to access the containerized SSH server
3. (optional) Patch your VS Code build (the minified `workbench.desktop.main.js` if you can't use remote SSH with a custom build) to get more logs, like [this](https://github.com/emilan/vscode/commit/f973ae0103e0ca462a7bdb0bdb0a5601ff2f4c78)
4. Connect to the remote SSH workspace and trust it
5. Reconnect a couple of times and note that the automatic task isn't always started

### PR DESCRIPTION
**Pull request by emilan**
In some cases (very often for me), the task configuration is loaded after the RunAutomaticTasks class has searched through the configured tasks to see if there are any automatic tasks to run. Since this search is a one time action, it means that the automatic tasks aren't always run.

This fix works around this race condition by exposing an event (onDidChangeTaskConfig) on the ITaskService interface and letting the AbstractTaskService implementation fire this event when it reloads the task configuration. If the RunAutomaticTasks class encounters zero automatic tasks, it waits for up to 10 seconds for this new event to fire before giving up. If the task configuration is updated during this time, RunAutomaticTasks looks for automatic tasks once more in the updated task configuration.

Fixes #203639

### CODE REVIEW

**Comment by emilan** [comment]
@microsoft-github-policy-service agree

**Review by meganrogge — APPROVED** [review]
Thank you!

File: src/vs/workbench/contrib/tasks/browser/runAutomaticTasks.ts [hunk 1]
```diff
@@ -50,9 +50,34 @@ export class RunAutomaticTasks extends Disposable implements IWorkbenchContribut
...
+
+		// As seen in some cases with the Remote SSH extension, the tasks configuration is loaded after we have come
+		// to this point. Let's give it some extra time.
+		if (autoTasks.taskNames.length === 0) {
+			const updatedWithinTimeout = await Promise.race([
+				new Promise<boolean>((resolve) => {
+					Event.toPromise(Event.once(this._taskService.onDidChangeTaskConfig)).then(() => resolve(true));
+				}),
+				new Promise<boolean>((resolve) => {
+					const timer = setTimeout(() => { clearTimeout(timer); resolve(false); }, 10000);
```
Comment (roblourens) [inline src/vs/workbench/contrib/tasks/browser/runAutomaticTasks.ts:67]: Waiting on some timeout is suspicious to me. Seems like you should just be able to know for sure when the task configuration is loaded. But I reloaded the window a few times and it worked when I tried it.

**Review by roblourens — APPROVED** [review]

File: src/vs/workbench/contrib/tasks/browser/runAutomaticTasks.ts (hunk 1 above)
Comment (emilan) [reply src/vs/workbench/contrib/tasks/browser/runAutomaticTasks.ts:67]: Many thanks for your review!

I fully agree that this isn't the prettiest solution. In my opinion, it would have been better if TaskService waited with firing the existing onDidChangeTaskSystemInfo event until it had tried to fetch the task configuration, if any. I suspect this is where the hidden timing issue really is. But I know too little about the interactions involved in this code base, also together with the remote SSH extension, to look into that right now. And debugging all this was really quite complex when I couldn't use the remote SSH extension with my custom Code OSS build.

The timer is just there to not wait forever if there is no task configuration at all. Removing the timer (and not waiting just once for the new event) could be a way to support running automatic tasks that are configured manually after having opened the folder. But that's new functionality and not something I'd put in a bug fix. 

Anyway, I just tested the latest Insiders build on Windows, which includes this commit. I can no longer reproduce the issues I had.
