### PR TITLE
Initial support for a timeline (file history) view

### LINKED ISSUE #84297: Explore adding support for a file history (or file timeline) view
# Goals

Add support for a unified file-based timeline view to be added to the Explorer sidebar which will track the active document (similar to the Outline view). This new view can be contributed by multiple sources, e.g. save/undo points, source control commits, test runs/failures, etc. Events from all sources will be aggregated into a single chronologically-ordered view. 

# Proposal

```ts
	export class TimelineItem {
		/**
		 * A date for when the timeline item occurred
		 */
		date: Date;

		/**
		 * A human-readable string describing the source of the timeline item. This can be used for filtering by sources so keep it consistent across timeline item types.
		 */
		source: string;

		/**
		 * Optional method to get the children of the timeline item (if any).
		 *
		 * @return Children of the timeline item (if any).
		 */
		getChildren?(): ProviderResult<TreeItem[]>;

		/**
		 * A human-readable string describing the timeline item. When `falsy`, it is derived from [resourceUri](#TreeItem.resourceUri).
		 */
		label: string;

		/**
		 * Optional id for the timeline item. See [TreeItem.id](#TreeItem.id) for more details.
		 */
		id?: string;

		/**
		 * The icon path or [ThemeIcon](#ThemeIcon) for the timeline item. See [TreeItem.iconPath](#TreeItem.iconPath) for more details.
		 */
		iconPath?: string | Uri | { light: string | Uri; dark: string | Uri } | ThemeIcon;

		/**
		 * A human readable string describing less prominent details of the timeline item. See [TreeItem.description](#TreeItem.description) for more details.
		 */
		description?: string | boolean;

		/**
		 * The [uri](#Uri) of the resource representing the timeline item (if any). See [TreeItem.resourceUri](#TreeItem.resourceUri) for more details.
		 */
		resourceUri?: Uri;

		/**
		 * The tooltip text when you hover over the timeline item.
		 */
		tooltip?: string | undefined;

		/**
		 * The [command](#Command) that should be executed when the timeline item is selected.
		 */
		command?: Command;

		/**
		 * [TreeItemCollapsibleState](#TreeItemCollapsibleState) of the timeline item.
		 */
		collapsibleState?: TreeItemCollapsibleState;

		/**
		 * Context value of the timeline item.  See [TreeItem.contextValue](#TreeItem.contextValue) for more details.
		 */
		contextValue?: string;

		/**
		 * @param label A human-readable string describing the timeline item
		 * @param date A date for when the timeline item occurred
		 * @param source A human-readable string describing the source of the timeline item
		 * @param collapsibleState [TreeItemCollapsibleState](#TreeItemCollapsibleState) of the timeline item. Default is [TreeItemCollapsibleState.None](#TreeItemCollapsibleState.None)
		 */
		constructor(label: string, date: Date, source: string, collapsibleState?: TreeItemCollapsibleState);
	}

	export interface TimelimeAddEvent {

		/**
		 * An array of timeline items which have been added.
		 */
		readonly items: readonly TimelineItem[];

		/**
		 * The uri of the file to which the timeline items belong.
		 */
		readonly uri: Uri;
	}

	export interface TimelimeChangeEvent {

		/**
		 * The date after which the timeline has changed. If `undefined` the entire timeline will be reset.
		 */
		readonly since?: Date;

		/**
		 * The uri of the file to which the timeline changed.
		 */
		readonly uri: Uri;
	}

	export interface TimelineProvider {
		onDidAdd?: Event<TimelimeAddEvent>;
		onDidChange?: Event<TimelimeChangeEvent>;

		/**
		 * Provide [timeline items](#TimelineItem) for a [Uri](#Uri) after a particular date.
		 *
		 * @param uri The uri of the file to provide the timeline for.
		 * @param since A date after which timeline items should be provided.
		 * @param token A cancellation token.
		 * @return An array of timeline items or a thenable that resolves to such. The lack of a result
		 * can be signaled by returning `undefined`, `null`, or an empty array.
		 */
		provideTimeline(uri: Uri, since: Date, token: CancellationToken): ProviderResult<TimelineItem[]>;
	}

	export namespace workspace {
		/**
		 * Register a timeline provider.
		 *
		 * Multiple providers can be registered. In that case, providers are asked in
		 * parallel and the results are merged. A failing provider (rejected promise or exception) will
		 * not cause a failure of the whole operation.
		 *
		 * @param selector A selector that defines the documents this provider is applicable to.
		 * @param provider A timeline provider.
		 * @return A [disposable](#Disposable) that unregisters this provider when being disposed.
		 */
		export function registerTimelineProvider(selector: DocumentSelector, provider: TimelineProvider): Disposable;
	}
```

A timeline source (e.g. an extension) registers a `TimelineProvider` for a set of documents. VS Code will then call the all the registered `TimelineProvider.provideTimeline` callbacks (in parallel) when the active editor changes and matches those registrations. The results will be merged into a unified set ordered by the `TimelineItem.date` and displayed in a new _File Timeline_ view in the Explorer sidebar.

A timeline provider can signal that new events have occurred via the `onDidAdd` event, providing the set of additional timeline items. A provider can also signal a refresh of its timeline items via the `onDidChange` event.

# Questions & Challenges

### API
- Should we provides a model/signal that a timeline provider should not be cached or more accurately flushed when the file is no longer the active editor? Basically an alternative to sending events, just call `provideTimeline` again
- Caching will be a bit challenging
  - How much do we keep around? And for how long?
- Should the `TimelimeChangeEvent` event provide a way to signal that an individual item(s) should be updated?
- Do we need a throttle on `onDidAdd`?
- Need to be careful with `id`s for the tree items, since they can come from multiple extensions. Probably should ensure a prefix or something per provider for any provided `id`s (or not give control over the `id`s at all) 

### Behavior
- Should tracking the active document be a toggle (like in GitLens where you can turn on/off tracking in the file history view on demand).
- Should there be a way to trigger a specific file/folder/uri timelime to be shown (which would also turn off active file tracking) -- again similar to GitLens
- Should the view support a refresh action that will drop timeline caches and re-request the timeline from all providers? (Hopefully we don't really need this)
- Should we support filtering based on the `source` of the timeline items?
/cc @jrieken 

Refs: https://github.com/microsoft/vscode/issues/83995

### PR DESCRIPTION
**Pull request by eamodio**
This PR fixes #84297

This is just the initial pass at a Timeline view with a registered `TimelineProvider` in the Git extension to provide Git history for the active file.

To enable this view, set `"timeline.showView": true`

### CODE REVIEW

File: src/vs/workbench/contrib/timeline/common/timelineService.ts [hunk 1]
```diff
@@ -0,0 +1,207 @@
...
+	}
+
+	private onProviderTimelineChanged(source: string, uri: URI | undefined) {
+		// console.log(`TimelineService.onProviderTimelineChanged: source=${source} uri=${uri?.toString(true)}`);
+
+		this._onDidChangeTimeline.fire(uri);
+	}
+}
+
+function* map<T, TMapped>(source: Iterable<T> | IterableIterator<T>, mapper: (item: T) => TMapped): Iterable<TMapped> {
```
Comment (jrieken) [inline src/vs/workbench/contrib/timeline/common/timelineService.ts]: Even tho this is workbench-only we don't use "modern" JS because the editor still supports IE11. This should be flagged as TS compile error, no clue why not 🤷‍♂

File: src/vs/workbench/contrib/timeline/common/timelineService.ts [hunk 2]
```diff
@@ -0,0 +1,207 @@
...
+	for (const item of source) {
+		yield mapper(item);
+	}
+}
+
+class CancellationError<TPromise = any> extends Error {
+	constructor(public readonly promise: TPromise, message: string) {
```
Comment (jrieken) [inline src/vs/workbench/contrib/timeline/common/timelineService.ts]: We usually use `errors.ts#cancled`

File: src/vs/workbench/contrib/timeline/common/timelineService.ts (hunk 1 above)
Comment (jrieken) [reply src/vs/workbench/contrib/timeline/common/timelineService.ts]: This also mean to `Iterable` and such, basically no globals that IE11 doesn't support (and that cannot be poly-filled)

**Review by jrieken — CHANGES_REQUESTED** [review]

File: extensions/git/package.json [hunk 3]
```diff
@@ -442,6 +442,11 @@
         "command": "git.stashDrop",
         "title": "%command.stashDrop%",
         "category": "Git"
+      },
+      {
+        "command": "git.openDiff",
```
Comment (joaomoreno) [inline extensions/git/package.json]: Careful because this will make the command appear in the command palette. It seems it's not meant for that since it requires a `hash` parameter. This isn't really necessary for the command to exist in the system.

File: extensions/git/src/git.ts [hunk 4]
```diff
@@ -503,7 +512,9 @@ export interface Commit {
 	hash: string;
 	message: string;
 	parents: string[];
-	authorEmail?: string | undefined;
+	authorDate?: Date;
+	authorName?: string;
+	authorEmail?: string;
```
Comment (joaomoreno) [inline extensions/git/src/git.ts]: Cool, I'll wait for this to come in before merging https://github.com/microsoft/vscode/pull/89005.

File: extensions/git/src/git.ts [hunk 5]
```diff
@@ -634,14 +645,43 @@ export function parseGitmodules(raw: string): Submodule[] {
...
+
+	do {
+		match = commitRegex.exec(data);
+		if (match === null) {
+			break;
+		}
 
-	const parents = match[3] ? match[3].split(' ') : [];
-	return { hash: match[1], message: match[5], parents, authorEmail: match[2] };
+		[, ref, name, email, date, parents, message] = match;
```
Comment (joaomoreno) [inline extensions/git/src/git.ts]: Why not just a `const` here? Perf really shouldn't be a big issue here.

File: src/vs/workbench/api/browser/mainThreadTimeline.ts [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+
+	$registerTimelineProvider(provider: TimelineProviderDescriptor): void {
+		this.logService.trace(`MainThreadTimeline#registerTimelineProvider: source=${provider.source}`);
+
+		const proxy = this._proxy;
+
+		const emitters = this._providerEmitters;
+		let onDidChange = emitters.get(provider.source);
+		// eslint-disable-next-line eqeqeq
+		if (onDidChange == null) {
```
[the remark this answers is not in the document]
Comment (joaomoreno) [reply src/vs/workbench/api/browser/mainThreadTimeline.ts]: Also, `===`?

File: src/vs/workbench/contrib/timeline/common/timelineService.ts (hunk 2 above)
Comment (joaomoreno) [reply src/vs/workbench/contrib/timeline/common/timelineService.ts]: Yeah, and we usually treat cancellation as a rejection, not a resolution. The current code is a bit hard to understand, since it seems that promises are resolving with errors instead of rejecting with them. I see how here there's a use case for N promises to resolve and some might reject but not block the overall race... but instead of resolving using a generic `CancellationErrorWithId` why not resolving with a specific `NoResults` result type instead?

**Review by joaomoreno — COMMENTED** [review]
Is dayjs localized across all languages we support? We probably should be rolling our own library here, just for the localization support.

File: src/vs/workbench/api/browser/mainThreadTimeline.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (eamodio) [reply src/vs/workbench/api/browser/mainThreadTimeline.ts]: It should. I just always prefer `== null` (since I've been bitten many times where apis/etc say that they return `undefined` but sometimes it is `null`). So I use `== null` as a special case since in the vast majority of cases, I want to handle `null` in the same way as `undefined`

[the remark this answers is not in the document]
Comment (jrieken) [reply src/vs/workbench/api/browser/mainThreadTimeline.ts]: trust the *type*script

File: src/vs/workbench/contrib/timeline/common/timelineService.ts (hunk 2 above)
Comment (eamodio) [reply src/vs/workbench/contrib/timeline/common/timelineService.ts]: Basically I am racing each promise with a timeout so that any one provider can't take too long to return results (although currently I have that turned off as there is no timeout specified). I'm not 100% sure if we do want to do this (imo we probably should have some limit), and if we do, I probably need to think more about what to do with the requests that take too long. Do we cancel them? Do we render everything that is ready and then continue to wait longer for them to finish and then update the UI with those additional results?

I lifted this code from GitLens (so it has some extra needs baked into it), e.g. the `CancellationErrorWithId` contains both a correlation id (to map up with requests) and the promise that we stopped waiting for (its still running).

File: extensions/git/package.json (hunk 3 above)
Comment (eamodio) [reply extensions/git/package.json]: Yeah, I'll remove it for now. I was planning on eventually having a context menu command attached to the timeline items -- and I can just remove it from the palette once that is there.

File: extensions/git/src/git.ts (hunk 4 above)
Comment (eamodio) [reply extensions/git/src/git.ts]: The merge probably wouldn't go very well, since I changed the parsing from how it was. But I can easily add `commitDate` in if we want.

File: extensions/git/src/git.ts (hunk 5 above)
Comment (eamodio) [reply extensions/git/src/git.ts]: It was mainly for perf -- I stole this parsing from GitLens where I saw perf improvements (and memory reductions)

File: src/vs/workbench/api/browser/mainThreadTimeline.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (eamodio) [reply src/vs/workbench/api/browser/mainThreadTimeline.ts]: lol -- won't save from runtime variations 😉

File: src/vs/workbench/contrib/timeline/common/timelineService.ts (hunk 2 above)
Comment (jrieken) [reply src/vs/workbench/contrib/timeline/common/timelineService.ts]: For format on save and code actions on save I went away from timeouts because machines vary too much and also expectation vary too much. Instead, it now shows progress after a short time and that allows to cancel the operation. I came to believe that's more user friendly then timeouts and settings for those timeouts

**Comment by eamodio** [comment]
@joaomoreno RE: day.js -- I don't know if they have all the languages we support. I started implementing this myself using the `Intl.RelativeTimeFormat` but I gave up because I wanted to make sure this landed and didn't want that to be the hold up. I can revisit going down that path, but even using `Intl.RelativeTimeFormat` we'd be beholden to the localized strings supported there.
