### PR TITLE
fix accessiblity signal bug

### LINKED ISSUE #285702: "Terminal is awaiting input" always triggers audio cue
Every time this dialog is rendered, it triggers the audio cue. I don't have screenreader mode or any audio cues enabled.

Image

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #285702

### CODE REVIEW

File: src/vs/platform/accessibilitySignal/browser/accessibilitySignalService.ts [hunk 1]
```diff
@@ -695,7 +695,6 @@ export class AccessibilitySignal {
 		name: localize('accessibilitySignals.chatUserActionRequired', 'Chat User Action Required'),
 		sound: Sound.chatUserActionRequired,
 		announcementMessage: localize('accessibility.signals.chatUserActionRequired', 'Chat User Action Required'),
-		settingsKey: 'accessibility.signals.chatUserActionRequired',
-		managesOwnEnablement: true
```
Comment (roblourens) [inline src/vs/platform/accessibilitySignal/browser/accessibilitySignalService.ts:699]: I'm curious why this exists, it means I can't disable an audio cue?

**Review by roblourens — APPROVED** [review]
I'm very excited for this to be fixed, no more dinging 😅 thanks!
