### PR TITLE
Don't force kill ptys on Windows on window exit

### LINKED ISSUE #117956: Terminal pty host unresponsive after closing a VS Code window
I've seen this happen a few times now, and this last time it seemed to happen right after I closed a VS Code window. After that, I got the following notification in all my other open VS Code windows.

image

Here is the Shared Process output
```
[2021-03-02 03:11:02.588] [sharedprocess] [warning] No ptyHost heartbeat after 6 seconds
[2021-03-02 03:11:07.592] [sharedprocess] [error] No ptyHost heartbeat after 12 seconds
[2021-03-02 03:11:40.245] [sharedprocess] [error] [uncaught exception in sharedProcess]: Could not find pty with id "4": Error: Could not find pty with id "4"
    at P._throwIfNoPty (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:12:36591)
    at P.shutdown (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:12:35103)
    at Object.call (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:11:8178)
    at C.onPromise (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:27579)
    at C.onRawMessage (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:26938)
    at c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:26191
    at A.fire (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:8:1836)
    at process.Z (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:6:30611)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
[2021-03-02 03:11:40.303] [sharedprocess] [error] [uncaught exception in sharedProcess]: Could not find pty with id "2": Error: Could not find pty with id "2"
    at P._throwIfNoPty (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:12:36591)
    at P.resize (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:12:35219)
    at Object.call (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:11:8178)
    at C.onPromise (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:27579)
    at C.onRawMessage (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:26938)
    at c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:26191
    at A.fire (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:8:1836)
    at process.Z (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:6:30611)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
[2021-03-02 03:11:40.838] [sharedprocess] [error] [uncaught exception in sharedProcess]: Could not find pty with id "2": Error: Could not find pty with id "2"
    at P._throwIfNoPty (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:12:36591)
    at P.shutdown (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:12:35103)
    at Object.call (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:11:8178)
    at C.onPromise (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:27579)
    at C.onRawMessage (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:26938)
    at c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:10:26191
    at A.fire (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:8:1836)
    at process.Z (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\platform\terminal\node\ptyHostMain.js:6:30611)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #117956

### CODE REVIEW

File: src/vs/platform/terminal/node/terminalProcess.ts [hunk 1]
```diff
@@ -24,6 +24,25 @@ import { localize } from 'vs/nls';
...
+	 * kill call is triggered. This data flush mechanism works around an [issue in node-pty][1]
+	 * where not all data is flushed which causes problems for task problem matchers. Additionally
+	 * on Windows under conpty, killing a process while data is being output will cause the [conhost
+	 * flush to hang the pty host][2] because [conhost should be hosted on another thread][3].
+	 *
+	 * [1]: https://github.com/Tyriar/node-pty/issues/72
+	 * [2]: https://github.com/microsoft/vscode/issues/71966
+	 * [3]: https://github.com/microsoft/node-pty/pull/415
+	 */
+	DataFlushTimeout = 250,
```
Comment (meganrogge) [inline src/vs/platform/terminal/node/terminalProcess.ts:39]: is this in ms?

**Review by meganrogge — APPROVED** [review]

File: src/vs/platform/terminal/node/terminalProcess.ts (hunk 1 above)
Comment (Tyriar) [reply src/vs/platform/terminal/node/terminalProcess.ts:39]: Yep, I can include that in the comment on main
