### PR TITLE
Use platform agnostic URI comparison for task resolution

### LINKED ISSUE #258720: Task not found error when the task exists
Testing #258358

tool call
```
id   : call_sJufapG6WYDJHmUG6otndWCz__vscode-1753824250347
tool : run_task
args : {
  "id": "Run Bingo API",
  "workspaceFolder": "/home/kanadig/GIT/TPI/2025-07/bingo2"
}
```

task.json:
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Run Bingo API",
      "type": "shell",
      "command": "python -m uvicorn main:app --reload",
      "problemMatcher": []
    }
  ]
}

```

### LINKED ISSUE #258723: All `get_terminal_output` failed, when using the pid passed in context
Testing #258358

Image

It does not find the task terminal:
```
id   : call_8a4YKZbe6SQS9lNi3Ok0UeAW__vscode-1753824250351
tool : get_terminal_output
args : {
  "id": "18556"
}

id   : call_Dre3OXsHoJUcbquuea7oGchU__vscode-1753824250354
tool : get_terminal_output
args : {
  "id": "14944"
}

id   : call_6f9ziWZQpr2klIpspEPEe25e__vscode-1753824250353
tool : get_terminal_output
args : {
  "id": "18556"
}
```

same result in all three calls:
```
ERROR while calling tool: Invalid terminal ID
Please check your input and try again.
```

It seems to not be able to find the running task:
```
id   : call_Z573lugQhwlyuhhUnfknvUZu__vscode-1753824250349
tool : get_task_output
args : {
  "id": "Run Bingo API",
  "workspaceFolder": "/home/kanadig/GIT/TPI/2025-07/bingo2"
}

Task not found: Run Bingo API
```

task.json:
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Run Bingo API",
      "type": "shell",
      "command": ".venv/bin/uvicorn main:app --reload",
      "problemMatcher": []
    }
  ]
}
```

Image

this is the context it has:
```
<context>
The current date is July 29, 2025.
Tasks:
Task: Run Bingo API (, is running, type: shell, command: .venv/bin/uvicorn main:app --reload)
Terminals:
Terminal: bash
Output: {Use get_terminal_output for terminal with ID: 14944.}
Terminal: Run Bingo API
Output: {Use get_terminal_output for terminal with ID: 18556.}
User created Terminals:
Terminal: bash
Output: {Use get_terminal_output for terminal with pid: 14944.}
Terminal: Run Bingo API
Output: {Use get_terminal_output for terminal with pid: 18556.}

</context>
```

### PR DESCRIPTION
**Pull request by meganrogge**
fixes https://github.com/microsoft/vscode/issues/259213
fixes #258720
fixes #258723

### CODE REVIEW

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/task/taskHelpers.ts [hunk 1]
```diff
@@ -66,9 +65,13 @@ export async function getTaskForTool(id: string | undefined, taskDefinition: { t
 	}
 
 	let tasksForWorkspace;
+	const workspaceFolderPath = URI.file(workspaceFolder).path;
 	for (const [folder, tasks] of workspaceFolderToTaskMap) {
-		// Use isEqual to compare URIs for cross-platform compatibility
-		if (isEqual(URI.parse(folder), URI.file(workspaceFolder))) {
+		const parsed = URI.parse(folder);
+		if (parsed.scheme === 'vscode-remote' && parsed.path === workspaceFolderPath) {
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/task/taskHelpers.ts]: `Schemas.vscodeRemote`

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/task/taskHelpers.ts (hunk 1 above)
Comment (meganrogge) [reply src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/task/taskHelpers.ts]: always using parse now

**Review by Tyriar — APPROVED** [review]
