### PR TITLE
fix disposable leak

### LINKED ISSUE #275388: `chatTerminalToolProgressPart.ts` —  Trying to add a disposable to a DisposableStore
Seeing this after running some terminal commands in chat 

```
lifecycle.ts:477 Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at r2i.add (lifecycle.ts:477:18)
    at _rt.D (lifecycle.ts:555:22)
    at _rt.P (chatTerminalToolProgressPart.ts:260:41)
    at s (chatTerminalToolProgressPart.ts:180:9)
    at _rt.L (chatTerminalToolProgressPart.ts:183:9)
    at async chatTerminalToolProgressPart.ts:124:4
```

Maybe the instance gets disposed of around these async calls: https://github.com/microsoft/vscode/blob/ebb5f678cb79d86b18de20cb8c4a2442a160a98f/src/vs/workbench/contrib/chat/browser/chatContentParts/toolInvocationParts/chatTerminalToolProgressPart.ts#L183

### PR DESCRIPTION
**Pull request by meganrogge**
fix #275388

### CODE REVIEW

File: src/vs/workbench/contrib/chat/browser/chatContentParts/toolInvocationParts/chatTerminalToolProgressPart.ts [hunk 1]
```diff
@@ -190,7 +190,9 @@ export class ChatTerminalToolProgressPart extends BaseChatToolInvocationSubPart
 			attachInstance(instance);
 			listener.dispose();
 		});
-		this._register(listener);
+		if (!(this._store.isDisposed)) {
+			this._register(listener);
+		}
```
Comment (Tyriar) [inline src/vs/workbench/contrib/chat/browser/chatContentParts/toolInvocationParts/chatTerminalToolProgressPart.ts]: The handle to `listener` would leak here when `this._store.isDisposed`? Also we shouldn't register against `this` as listener is short lived. I think this is what we need to do:

- Check `isDisposed` before `const listener`, that way it won't be created if it's disposed already
- Change `listener.dispose()` to `this._store.delete(listener)` to free the handle on `this._store` in addition to disposing `listener`
- nit: Pull await call out as it's harder to think about when it's in a condition

**Review by Tyriar — DISMISSED** [review]

File: src/vs/workbench/contrib/chat/browser/chatContentParts/toolInvocationParts/chatTerminalToolProgressPart.ts [hunk 2]
```diff
@@ -181,16 +181,28 @@ export class ChatTerminalToolProgressPart extends BaseChatToolInvocationSubPart
...
-			attachInstance(instance);
-			listener.dispose();
+			await attachInstance(instance);
+			this._store.delete(listener);
 		});
-		this._register(listener);
+
+		if (this._store.isDisposed) {
+			listener.dispose();
+			return;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/chat/browser/chatContentParts/toolInvocationParts/chatTerminalToolProgressPart.ts]: This case shouldn't be possible as you checked just before setting up the listener, and listening to an event is sync and couldn't cause it to be disposed

File: src/vs/workbench/contrib/chat/browser/chatContentParts/toolInvocationParts/chatTerminalToolProgressPart.ts [hunk 3]
```diff
@@ -181,16 +181,28 @@ export class ChatTerminalToolProgressPart extends BaseChatToolInvocationSubPart
...
 		const listener = this._terminalChatService.onDidRegisterTerminalInstanceWithToolSession(async instance => {
-			if (instance !== await this._terminalChatService.getTerminalInstanceByToolSessionId(terminalToolSessionId)) {
+			const registeredInstance = await this._terminalChatService.getTerminalInstanceByToolSessionId(terminalToolSessionId);
+			if (instance !== registeredInstance) {
 				return;
 			}
-			attachInstance(instance);
-			listener.dispose();
+			await attachInstance(instance);
+			this._store.delete(listener);
```
Comment (Tyriar) [inline src/vs/workbench/contrib/chat/browser/chatContentParts/toolInvocationParts/chatTerminalToolProgressPart.ts]: Safer:

```suggestion
			this._store.delete(listener);
			await attachInstance(instance);
```

**Review by Tyriar — DISMISSED** [review]

**Review by Tyriar — APPROVED** [review]
