### PR TITLE
fixes #43687

### LINKED ISSUE #43687: Renaming a file in explorer creates a one second glitch in input box
- VSCode Version: 1.21.0-insider
- OS Version: MacOS Sierra 10.12.6

Steps to Reproduce:

1. Click a file in explorer
2. Press enter to rename the file
3. After renamed the file, press enter again and observe the glitch

Does this issue occur when all extensions are disabled?: Yes

rename-bug

I think, this issue may be related with [this commit](https://github.com/Microsoft/vscode/commit/7f403516c8f5e058670f0c6bd5223ee66a6fb61a)

Have a nice day and happy valentine's day 🎉

### PR DESCRIPTION
**Pull request by tsalinger**

### CODE REVIEW

File: src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts [hunk 1]
```diff
@@ -300,6 +300,7 @@ export class FileRenderer implements IRenderer {
 
 		const done = once((commit: boolean, blur: boolean) => {
 			tree.clearHighlight();
+			label.element.style.display = 'none';
```
Comment (tsalinger) [inline src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts]: line 249: templateData.label.element.style.display = 'flex';
leads to two visible labels.
By setting the old label to display = 'none' this can be avoided.

**Comment by isidorn** [comment]
@tsalinger thanks for this PR. I tried it out and works nicely!
