### PR TITLE
shellEnv: disable powershell discovery on Windows

### LINKED ISSUE #251446: 1.101.0 breaks with powershell 7.5 installed on computer
I'm having an issue with a system after the 1.101.0 update.  I use VSC for powershell with one terminal session and powershell extension in another.  Both are running Windows PS 5.1 and I have Powershell 7.5 installed also.  After the upgrade, none of my modules will load in VSC.  When I run get-module I only see powershell 7 compatible modules. $env:psmodulepath shows all of the correct paths but if I run a get-module -listavailable, I only see the powershell 7 and windows system paths.  If I drill down to where I have my other modules and try to load them, I get the error that there's no maifest file.  This is happening on the windows powershell terminal session while on my powershell extension session never finishes loading.  On that session, it's asking me in the lower right corner to pick a language which powershell is the default.  If I downgrade to 1.100.3, the system is fine.  If I leave 1.101.0 installed and remove powershel 7.5, the system runs normal.  Reinstalling 7.5 breaks VSC again.

With VSC 1.101.0 after update:
Sessions come up with PS 5.1 showing manifest 7.0.0.0 Microsoft.Powershell.management and no modules will load.
With 1.100.3 or 1.101.0 with powershell 7.5 later removed:
Sessions come up with PS 5.1 showing manifest 3.1.0.0 Microsoft.Powershell.management everything runs fine.

It leads me to believe that VSC is attempting to load powershell 7.5 and the system can't process it.  However I've been able to use PS 7.5 sessions in VSC 1.100.3 and older and it's always run fine.  I also did try using information from #251311 to use code to remove the powershell 7 paths from starting up and loading and it did show the manifest ver 3 on my powershell session however none of the modules would load.  Same error that it can't find the manifest files.

I also have another system that took the upgrade fine and everything is working the way it always has.  I have setting sync enabled and have the workspace set up the same on both system.  I downgraded the one system to 1.100.3 and kept powershell 7.5 installed as I have jobs that run that require 7.  The system that is working is a windows 11 laptop and the one having issues after the update is server 2022, 21h2.  I did also try disabling extensions and it was to no avail as well as removing my powershell startup profiles.

### LINKED ISSUE #251901: Unable to resolve your shell environment: Unexpected end of JSON input (vscode launch)
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.101.0 (system setup)
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Launch vscode with menu shortcut
2. get the error notification

Additional informations : 

I added "--verbose" to the vscode shortcut :

Image

With this, I get the underlying problem in the "main" logs : 

```
2025-06-19 14:24:55.255 [trace] doResolveShellEnv#spawn ["-Command"] Write-Output 'a6ad6f0ec1bb'; [System.Environment]::GetEnvironmentVariables() | ConvertTo-Json -Compress; Write-Output 'a6ad6f0ec1bb'
2025-06-19 14:24:55.551 [trace] NativePolicyService#_updatePolicyDefinitions - Found 9 policy definitions
2025-06-19 14:24:55.552 [trace] NativePolicyService#_onDidPolicyChange - Updated policy values: {}
2025-06-19 14:24:55.552 [trace] PolicyConfiguration#onDidChangePolicies []
2025-06-19 14:24:55.553 [trace] PolicyConfiguration#update []
2025-06-19 14:24:55.554 [trace] NativePolicyService#_updatePolicyDefinitions - Found 11 policy definitions
2025-06-19 14:24:55.555 [trace] NativePolicyService#_onDidPolicyChange - Updated policy values: {}
2025-06-19 14:24:55.555 [trace] PolicyConfiguration#onDidChangePolicies []
2025-06-19 14:24:55.555 [trace] PolicyConfiguration#update []
2025-06-19 14:24:55.751 [trace] window#load: window reported ready (id: 1)
2025-06-19 14:24:55.751 [trace] ElectronURLListener#flush(): flushing URLs
2025-06-19 14:24:55.840 [trace] doResolveShellEnv#raw a6ad6f0ec1bb
a6ad6f0ec1bb
2025-06-19 14:24:55.840 [trace] doResolveShellEnv#stderr Impossible d'appeler la m�thode. L'appel aux m�thodes n'est pris en charge que sur les types principaux dans ce mode 
de langage.
Au caract�re Ligne:1 : 30
+ ... d6f0ec1bb'; [System.Environment]::GetEnvironmentVariables() | Convert ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage
 ```

If :
1) I launch `code` from cmd (in windows terminal), I DO NOT get that issue
2) I launch the command `C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command "Write-Output 'a6ad6f0ec1bb'; [System.Environment]::GetEnvironmentVariables() | ConvertTo-Json -Compress; Write-Output 'a6ad6f0ec1bb'"` from command line, I DO get the issue.

edit : I would say it started throwing this error c.a. 1 week ago, and I saw a vscode (automatic) update in my applications on June 13, when I tried uninstalling reinstalling, so maybe (re)introduced in version 1.101

### LINKED ISSUE #251957: Unable to resolve your shell environment: Bad escaped character in JSON at position 376 (line 2 column 375)
<details>
  <summary>Insiders Main log</summary>

<br/>

> Why do I still get error notifications after updating?
> 
> ---
> 
> Error Notification
> ```log
> Unable to resolve your shell environment: Bad escaped character in JSON at position 376 (line 2 column 375)
> ```
> 
> Version
> ```
> Version: 1.101.1 (user setup)
> Commit: 18e3a1ec544e6907be1e944a94c496e302073435
> Date: 2025-06-18T13:35:12.605Z
> Electron: 35.5.1
> ElectronBuildId: 11727614
> Chromium: 134.0.6998.205
> Node.js: 22.15.1
> V8: 13.4.114.21-electron.0
> OS: Windows_NT x64 10.0.19044
> ```
> 
> mian.log
> ```log
> 2025-06-20 08:05:27.082 [trace] PolicyConfiguration#initialize
> 2025-06-20 08:05:27.082 [trace] PolicyConfiguration#updatePolicyDefinitions ["update.mode","update.channel","update.enableWindowsBackgroundUpdates","update.showReleaseNotes","http.useLocalProxyConfiguration","http.electronFetch","http.proxy","http.proxyStrictSSL","http.proxyKerberosServicePrincipal","http.noProxy","http.proxyAuthorization","http.proxySupport","http.systemCertificates","http.experimental.systemCertificatesV2","http.fetchAdditionalSupport","telemetry.telemetryLevel","telemetry.feedback.enabled","telemetry.enableTelemetry","extensions.allowed"]
> 2025-06-20 08:05:27.082 [trace] NativePolicyService#_updatePolicyDefinitions - Found 4 policy definitions
> 2025-06-20 08:05:27.082 [trace] [File Watcher (node.js)] Request to start watching: c:\Users\WindowsOS\AppData\Roaming\Code\User (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>),c:\Users\WindowsOS\AppData\Roaming\Code\User\settings.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
> 2025-06-20 08:05:27.082 [trace] NativePolicyService#_onDidPolicyChange - Updated policy values: {}
> 2025-06-20 08:05:27.082 [trace] PolicyConfiguration#update ["update.mode","telemetry.telemetryLevel","telemetry.feedback.enabled","extensions.allowed"]
> 2025-06-20 08:05:27.082 [trace] PolicyConfiguration#updatePolicyDefinitions []
> 2025-06-20 08:05:27.082 [trace] PolicyConfiguration#update []
> 2025-06-20 08:05:27.082 [debug] Starting VS Code
> 2025-06-20 08:05:27.082 [debug] from: d:\Microsoft VS Code\resources\app
> 2025-06-20 08:05:27.082 [debug] args: {"_":[],"diff":false,"merge":false,"add":false,"remove":false,"goto":false,"new-window":false,"reuse-window":false,"wait":false,"help":false,"list-extensions":false,"show-versions":false,"pre-release":false,"update-extensions":false,"version":false,"verbose":false,"log":["trace"],"status":false,"prof-startup":false,"no-cached-data":false,"prof-v8-extensions":false,"disable-extensions":false,"disable-lcd-text":false,"disable-gpu":false,"disable-chromium-sandbox":false,"sandbox":false,"telemetry":false,"debugRenderer":false,"enable-smoke-test-driver":false,"logExtensionHostCommunication":false,"skip-release-notes":false,"skip-welcome":false,"disable-telemetry":false,"disable-updates":false,"use-inmemory-secretstorage":false,"disable-workspace-trust":false,"disable-crash-reporter":false,"crash-reporter-id":"0eab1816-0a28-4321-a12b-289637751246","skip-add-to-recently-opened":false,"open-url":false,"file-write":false,"file-chmod":false,"force":false,"do-not-sync":false,"do-not-include-pack-dependencies":false,"trace":false,"trace-memory-infra":false,"preserve-env":false,"force-user-env":false,"force-disable-user-env":false,"open-devtools":false,"disable-gpu-sandbox":false,"__enable-file-policy":false,"enable-coi":false,"enable-rdp-display-tracking":false,"no-proxy-server":false,"no-sandbox":false,"nolazy":false,"force-renderer-accessibility":false,"ignore-certificate-errors":false,"allow-insecure-localhost":false,"disable-dev-shm-usage":false,"profile-temp":false,"logsPath":"C:\\Users\\WindowsOS\\AppData\\Roaming\\Code\\logs\\20250620T080526"}
> 2025-06-20 08:05:27.082 [trace] Resolving machine identifier...
> 2025-06-20 08:05:27.082 [trace] Resolved machine identifier: f2b5cafc295488c2ec7e57911f7d51fe8b445c6557f4fd310ee6526bbdd71441
> 2025-06-20 08:05:27.082 [trace] Main->SharedProcess#connect
> 2025-06-20 08:05:27.082 [trace] PolicyConfiguration#updatePolicyDefinitions ["terminal.integrated.automationProfile.linux","terminal.integrated.automationProfile.osx","terminal.integrated.automationProfile.windows","terminal.integrated.profiles.windows","terminal.integrated.profiles.osx","terminal.integrated.profiles.linux","terminal.integrated.useWslProfiles","terminal.integrated.inheritEnv","terminal.integrated.persistentSessionScrollback","terminal.integrated.showLinkHover","terminal.integrated.ignoreProcessNames"]
> 2025-06-20 08:05:27.082 [trace] PolicyConfiguration#updatePolicyDefinitions ["terminal.integrated.defaultProfile.linux","terminal.integrated.defaultProfile.osx","terminal.integrated.defaultProfile.windows"]
> 2025-06-20 08:05:27.082 [trace] PolicyConfiguration#update []
> 2025-06-20 08:05:27.082 [trace] PolicyConfiguration#update []
> 2025-06-20 08:05:27.082 [trace] StorageMainService: creating application storage
> 2025-06-20 08:05:27.082 [trace] ElectronURLListener: waiting for window to be ready to handle URLs...
> 2025-06-20 08:05:27.082 [trace] lifecycle (main): phase changed (value: 2)
> 2025-06-20 08:05:27.082 [trace] windowsManager#open
> 2025-06-20 08:05:27.082 [trace] windowsManager#open pathsToOpen [{"backupPath":"C:\\Users\\WindowsOS\\AppData\\Roaming\\Code\\Backups\\1750376752856"}]
> 2025-06-20 08:05:27.082 [trace] windowsManager#doOpenEmpty {"restore":true,"forceNewWindow":true}
> 2025-06-20 08:05:27.082 [trace] IPC Object URL: Registered new channel vscode:60a1045e-7cd3-4a7c-a2fe-65bd3569dedd.
> 2025-06-20 08:05:27.082 [trace] window#validateWindowState: validating window state on 1 display(s) {"mode":0,"x":254,"y":134,"width":1202,"height":802}
> 2025-06-20 08:05:27.082 [trace] window#validateWindowState: single monitor working area {"x":0,"y":0,"width":1707,"height":1027}
> 2025-06-20 08:05:27.082 [trace] window#ctor: using window state {"mode":0,"x":254,"y":134,"width":1202,"height":802}
> 2025-06-20 08:05:27.082 [trace] window#load: attempt to load window (id: 1)
> 2025-06-20 08:05:27.082 [trace] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, maybeOpenEmptyWindow: false)
> 2025-06-20 08:05:27.082 [trace] lifecycle (main): phase changed (value: 3)
> 2025-06-20 08:05:27.082 [trace] resolveShellEnv(): running
> 2025-06-20 08:05:27.082 [trace] doResolveShellEnv#runAsNode undefined
> 2025-06-20 08:05:27.082 [trace] doResolveShellEnv#noAttach undefined
> 2025-06-20 08:05:27.082 [trace] doResolveShellEnv#env {"ALLUSERSPROFILE":"C:\\ProgramData","APPDATA":"C:\\Users\\WindowsOS\\AppData\\Roaming","CHROME_CRASHPAD_PIPE_NAME":"\\\\.\\pipe\\crashpad_11268_PKVWBVROANCWANRA","CommonProgramFiles":"C:\\Program Files\\Common Files","CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files","CommonProgramW6432":"C:\\Program Files\\Common Files","COMPUTERNAME":"DESKTOP-DMCUEUP","ComSpec":"C:\\Windows\\system32\\cmd.exe","DriverData":"C:\\Windows\\System32\\Drivers\\DriverData","FPS_BROWSER_APP_PROFILE_STRING":"Internet Explorer","FPS_BROWSER_USER_PROFILE_STRING":"Default","HOMEDRIVE":"C:","HOMEPATH":"\\Users\\WindowsOS","LOCALAPPDATA":"C:\\Users\\WindowsOS\\AppData\\Local","LOGONSERVER":"\\\\DESKTOP-DMCUEUP","NUMBER_OF_PROCESSORS":"16","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","OS":"Windows_NT","Path":"C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;D:\\Git\\cmd;D:\\ffmpeg\\bin;D:\\aria2;D:\\Python\\Python313;D:\\微信web开发者工具\\dll;D:\\Python\\Python313\\Scripts\\;D:\\Python\\Python313\\;C:\\Users\\WindowsOS\\AppData\\Local\\Microsoft\\WindowsApps;D:\\Microsoft VS Code\\bin;D:\\fnm-windows;D:\\Python\\Python313;D:\\mingw64\\bin;D:\\cursor\\resources\\app\\bin;","PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC","PROCESSOR_ARCHITECTURE":"AMD64","PROCESSOR_IDENTIFIER":"AMD64 Family 25 Model 116 Stepping 1, AuthenticAMD","PROCESSOR_LEVEL":"25","PROCESSOR_REVISION":"7401","ProgramData":"C:\\ProgramData","ProgramFiles":"C:\\Program Files","ProgramFiles(x86)":"C:\\Program Files (x86)","ProgramW6432":"C:\\Program Files","PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules","PUBLIC":"C:\\Users\\Public","SESSIONNAME":"Console","SystemDrive":"C:","SystemRoot":"C:\\Windows","TEMP":"C:\\Users\\WINDOW~1\\AppData\\Local\\Temp","TMP":"C:\\Users\\WINDOW~1\\AppData\\Local\\Temp","USERDOMAIN":"DESKTOP-DMCUEUP","USERDOMAIN_ROAMINGPROFILE":"DESKTOP-DMCUEUP","USERNAME":"WindowsOS","USERPROFILE":"C:\\Users\\WindowsOS","VSCODE_CODE_CACHE_PATH":"C:\\Users\\WindowsOS\\AppData\\Roaming\\Code\\CachedData\\18e3a1ec544e6907be1e944a94c496e302073435","VSCODE_CWD":"D:\\Microsoft VS Code","VSCODE_IPC_HOOK":"\\\\.\\pipe\\d809d467-1.101.1-main-sock","VSCODE_NLS_CONFIG":"{\"userLocale\":\"en\",\"osLocale\":\"zh-cn\",\"resolvedLanguage\":\"en\",\"defaultMessagesFile\":\"D:\\\\Microsoft VS Code\\\\resources\\\\app\\\\out\\\\nls.messages.json\",\"locale\":\"en\",\"availableLanguages\":{}}","VSCODE_PID":"11268","windir":"C:\\Windows","ELECTRON_RUN_AS_NODE":"1","ELECTRON_NO_ATTACH_CONSOLE":"1","VSCODE_RESOLVING_ENVIRONMENT":"1"}
> 2025-06-20 08:05:27.082 [info] update#setState idle
> 2025-06-20 08:05:27.082 [trace] [File Watcher (node.js)] Started watching: 'c:\Users\WindowsOS\AppData\Roaming\Code\User'
> 2025-06-20 08:05:27.082 [trace] [File Watcher (node.js)] Started watching: 'c:\Users\WindowsOS\AppData\Roaming\Code\User\settings.json'
> 2025-06-20 08:05:27.097 [trace] doResolveShellEnv#shell C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
> 2025-06-20 08:05:27.098 [trace] doResolveShellEnv#powershellProfile found in C:\Users\WindowsOS\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
> 2025-06-20 08:05:27.098 [trace] doResolveShellEnv#spawn ["-Command"] Write-Output 'cce1bcafdaaf'; [System.Environment]::GetEnvironmentVariables() | ConvertTo-Json -Compress; Write-Output 'cce1bcafdaaf'
> 2025-06-20 08:05:27.110 [trace] resolveShellEnv(): running
> 2025-06-20 08:05:27.204 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:27.204 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:27.204 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:27.205 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:27.284 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:27.285 [debug] User data changed
> 2025-06-20 08:05:27.309 [trace] StorageMainService: creating workspace storage (1750376752856)
> 2025-06-20 08:05:27.309 [trace] NativePolicyService#_updatePolicyDefinitions - Found 9 policy definitions
> 2025-06-20 08:05:27.311 [trace] NativePolicyService#_onDidPolicyChange - Updated policy values: {}
> 2025-06-20 08:05:27.311 [trace] PolicyConfiguration#onDidChangePolicies []
> 2025-06-20 08:05:27.311 [trace] PolicyConfiguration#update []
> 2025-06-20 08:05:27.313 [trace] NativePolicyService#_updatePolicyDefinitions - Found 11 policy definitions
> 2025-06-20 08:05:27.314 [trace] NativePolicyService#_onDidPolicyChange - Updated policy values: {}
> 2025-06-20 08:05:27.314 [trace] PolicyConfiguration#onDidChangePolicies []
> 2025-06-20 08:05:27.314 [trace] PolicyConfiguration#update []
> 2025-06-20 08:05:27.435 [trace] doResolveShellEnv#raw cce1bcafdaaf
> {"SESSIONNAME":"Console","ProgramFiles(x86)":"C:\\Program Files (x86)","Path":"C:\\Users\\WindowsOS\\AppData\\Local\\fnm_multishells\\7472_1750377927332;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;D:\\Git\\cmd;D:\\ffmpeg\\bin;D:\\aria2;D:\\Python\\Python313;D:\\微信web开发者工具\dll;D:\\Python\\Python313\\Scripts\\;D:\\Python\\Python313\\;C:\\Users\\WindowsOS\\AppData\\Local\\Microsoft\\WindowsApps;D:\\Microsoft VS Code\\bin;D:\\fnm-windows;D:\\Python\\Python313;D:\\mingw64\\bin;D:\\cursor\\resources\\app\\bin;","ProgramW6432":"C:\\Program Files","PROCESSOR_IDENTIFIER":"AMD64 Family 25 Model 116 Stepping 1, AuthenticAMD","TMP":"C:\\Users\\WINDOW~1\\AppData\\Local\\Temp","PROCESSOR_ARCHITECTURE":"AMD64","PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL","VSCODE_CWD":"D:\\Microsoft VS Code","USERPROFILE":"C:\\Users\\WindowsOS","VSCODE_RESOLVING_ENVIRONMENT":"1","PROCESSOR_REVISION":"7401","TEMP":"C:\\Users\\WINDOW~1\\AppData\\Local\\Temp","FPS_BROWSER_APP_PROFILE_STRING":"Internet Explorer","FPS_BROWSER_USER_PROFILE_STRING":"Default","LOGONSERVER":"\\\\DESKTOP-DMCUEUP","USERNAME":"WindowsOS","SystemRoot":"C:\\Windows","CHROME_CRASHPAD_PIPE_NAME":"\\\\.\\pipe\\crashpad_11268_PKVWBVROANCWANRA","FNM_DIR":"C:\\Users\\WindowsOS\\AppData\\Roaming\\fnm","FNM_LOGLEVEL":"info","USERDOMAIN_ROAMINGPROFILE":"DESKTOP-DMCUEUP","FNM_COREPACK_ENABLED":"false","CommonProgramFiles":"C:\\Program Files\\Common Files","FNM_ARCH":"x64","ProgramData":"C:\\ProgramData","FNM_VERSION_FILE_STRATEGY":"local","HOMEPATH":"\\Users\\WindowsOS","COMPUTERNAME":"DESKTOP-DMCUEUP","ALLUSERSPROFILE":"C:\\ProgramData","CommonProgramW6432":"C:\\Program Files\\Common Files","FNM_MULTISHELL_PATH":"C:\\Users\\WindowsOS\\AppData\\Local\\fnm_multishells\\7472_1750377927332","ELECTRON_NO_ATTACH_CONSOLE":"1","FNM_NODE_DIST_MIRROR":"https://nodejs.org/dist","DriverData":"C:\\Windows\\System32\\Drivers\\DriverData","HOMEDRIVE":"C:","VSCODE_PID":"11268","windir":"C:\\Windows","SystemDrive":"C:","NUMBER_OF_PROCESSORS":"16","OS":"Windows_NT","ProgramFiles":"C:\\Program Files","ComSpec":"C:\\Windows\\system32\\cmd.exe","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","VSCODE_IPC_HOOK":"\\\\.\\pipe\\d809d467-1.101.1-main-sock","ELECTRON_RUN_AS_NODE":"1","PSModulePath":"C:\\Users\\WindowsOS\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules","APPDATA":"C:\\Users\\WindowsOS\\AppData\\Roaming","USERDOMAIN":"DESKTOP-DMCUEUP","PROCESSOR_LEVEL":"25","FNM_RESOLVE_ENGINES":"true","LOCALAPPDATA":"C:\\Users\\WindowsOS\\AppData\\Local","VSCODE_NLS_CONFIG":"{\"userLocale\":\"en\",\"osLocale\":\"zh-cn\",\"resolvedLanguage\":\"en\",\"defaultMessagesFile\":\"D:\\\\Microsoft VS Code\\\\resources\\\\app\\\\out\\\\nls.messages.json\",\"locale\":\"en\",\"availableLanguages\":{}}","CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files","VSCODE_CODE_CACHE_PATH":"C:\\Users\\WindowsOS\\AppData\\Roaming\\Code\\CachedData\\18e3a1ec544e6907be1e944a94c496e302073435","PUBLIC":"C:\\Users\\Public"}
> cce1bcafdaaf
> 
> 2025-06-20 08:05:27.436 [error] doResolveShellEnv#errorCaught Bad escaped character in JSON at position 375 (line 2 column 374)
> 2025-06-20 08:05:27.436 [error] Unable to resolve your shell environment: Bad escaped character in JSON at position 375 (line 2 column 374)
> 2025-06-20 08:05:27.458 [trace] window#load: window reported ready (id: 1)
> 2025-06-20 08:05:27.458 [trace] ElectronURLListener#flush(): flushing URLs
> 2025-06-20 08:05:27.464 [trace] [SharedProcess] onWindowConnection for: vscode:createSharedProcessChannelConnectionResult
> 2025-06-20 08:05:27.464 [trace] [UtilityProcess type: shared-process, pid: <none>]: creating new...
> 2025-06-20 08:05:27.465 [trace] [UtilityProcess type: shared-process, pid: <none>]: payload sent via postMessage()
> 2025-06-20 08:05:27.465 [trace] [UtilityProcessWorker]: createWorker(window: 1, moduleId: vs/platform/files/node/watcher/watcherMain)
> 2025-06-20 08:05:27.466 [trace] [UtilityProcess id: 1, type: fileWatcher, pid: <none>]: creating new...
> 2025-06-20 08:05:27.472 [trace] [UtilityProcess type: shared-process, pid: 12304]: successfully created
> 2025-06-20 08:05:27.480 [trace] [UtilityProcess id: 1, type: fileWatcher, pid: 2852]: successfully created
> 2025-06-20 08:05:27.532 [trace] [UtilityProcess id: 1, type: extensionHost, pid: <none>]: creating new...
> 2025-06-20 08:05:27.541 [trace] [UtilityProcess id: 1, type: extensionHost, pid: 4800]: successfully created
> 2025-06-20 08:05:27.639 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:27.639 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:27.641 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:27.641 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:27.683 [trace] [SharedProcess] IPC ready
> 2025-06-20 08:05:27.683 [trace] Main->SharedProcess#connect: connection established
> 2025-06-20 08:05:27.695 [trace] [File Watcher (node.js)] Request to start watching: c:\Users\WindowsOS\AppData\Roaming\Code\User (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>),c:\Users\WindowsOS\AppData\Roaming\Code\User\settings.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
> 2025-06-20 08:05:27.698 [trace] [File Watcher (node.js)] Started watching: 'c:\Users\WindowsOS\AppData\Roaming\Code\User'
> 2025-06-20 08:05:27.699 [trace] [File Watcher (node.js)] Started watching: 'c:\Users\WindowsOS\AppData\Roaming\Code\User\settings.json'
> 2025-06-20 08:05:27.714 [trace] [SharedProcess] Overall ready
> 2025-06-20 08:05:27.715 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:27.715 [debug] User data changed
> 2025-06-20 08:05:27.734 [trace] [File Watcher (node.js)] Request to start watching: c:\Users\WindowsOS\.vscode\extensions (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>),c:\Users\WindowsOS\.vscode\extensions\extensions.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
> 2025-06-20 08:05:27.737 [trace] [File Watcher (node.js)] Started watching: 'c:\Users\WindowsOS\.vscode\extensions'
> 2025-06-20 08:05:27.738 [trace] [File Watcher (node.js)] Started watching: 'c:\Users\WindowsOS\.vscode\extensions\extensions.json'
> 2025-06-20 08:05:27.986 [debug] Terminal profile not validated bash (MSYS2) [{"path":"C:\\msys64\\usr\\bin\\bash.exe","isUnsafe":true}]
> 2025-06-20 08:05:27.987 [trace] resolveShellEnv(): running
> 2025-06-20 08:05:27.987 [error] resolving shell environment failed Unable to resolve your shell environment: Bad escaped character in JSON at position 375 (line 2 column 374)
> 2025-06-20 08:05:27.988 [trace] #1: https://update.code.visualstudio.com/api/update/win32-x64-user/stable/18e3a1ec544e6907be1e944a94c496e302073435 - begin undefined {}
> 2025-06-20 08:05:27.990 [debug] Terminal profile not validated Cygwin [{"path":"C:\\cygwin64\\bin\\bash.exe","isUnsafe":true},{"path":"C:\\cygwin\\bin\\bash.exe","isUnsafe":true}]
> 2025-06-20 08:05:28.043 [trace] WSL is not installed, so could not detect WSL profiles
> 2025-06-20 08:05:28.044 [trace] [EncryptionMainService] Checking if encryption is available...
> 2025-06-20 08:05:28.044 [trace] [EncryptionMainService] Encryption is available:  true
> 2025-06-20 08:05:28.050 [trace] [EncryptionMainService] Decrypting value...
> 2025-06-20 08:05:28.050 [trace] [EncryptionMainService] Decrypted value.
> 2025-06-20 08:05:28.056 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:28.056 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.056 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:28.056 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.057 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:28.057 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.057 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:28.057 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.131 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.133 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.133 [debug] User data changed
> 2025-06-20 08:05:28.195 [trace] #1: https://update.code.visualstudio.com/api/update/win32-x64-user/stable/18e3a1ec544e6907be1e944a94c496e302073435 - end undefined 204 {"access-control-allow-origin":"*","date":"Fri, 20 Jun 2025 00:05:28 GMT","request-context":"appId=cid-v1:8109e553-6232-492a-afca-b78cea9b431c","strict-transport-security":"max-age=31536000; includeSubDomains","x-azure-ref":"20250620T000527Z-17444d4b9f9mdmxmhC1HKGyu5w00000002fg000000001htt","x-cache":"CONFIG_NOCACHE","x-content-type-options":"nosniff","x-powered-by":"Express","x-source-commit":"52c757d6039fc7b9fc4b210aec30978ae2805866"}
> 2025-06-20 08:05:28.560 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:28.560 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.560 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:28.561 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.562 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:28.562 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.562 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:28.562 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.636 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.637 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.637 [debug] User data changed
> 2025-06-20 08:05:28.697 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:28.697 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.697 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:28.697 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.699 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:28.699 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.699 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:28.699 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.781 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:28.782 [debug] User data changed
> 2025-06-20 08:05:28.782 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:29.046 [debug] ProxyResolver#loadSystemCertificates count 39
> 2025-06-20 08:05:29.048 [debug] ProxyResolver#loadSystemCertificates count filtered 32
> 2025-06-20 08:05:29.076 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:29.076 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:29.076 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:29.076 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:29.158 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:29.158 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:29.158 [debug] User data changed
> 2025-06-20 08:05:29.208 [debug] ProfileStorageChangesListenerChannel#registerStorageChangeListeners
> 2025-06-20 08:05:29.213 [trace] [File Watcher (node.js)] Request to start watching: c:\Users\WindowsOS\AppData\Roaming\Code\User\snippets (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>),c:\Users\WindowsOS\AppData\Roaming\Code\User\prompts (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
> 2025-06-20 08:05:29.214 [trace] [File Watcher (node.js)] ignoring a path for watching who's stat info failed to resolve: c:\Users\WindowsOS\AppData\Roaming\Code\User\prompts (error: Error: ENOENT: no such file or directory, stat 'c:\Users\WindowsOS\AppData\Roaming\Code\User\prompts')
> 2025-06-20 08:05:29.214 [trace] [File Watcher (node.js)] starting fs.watchFile() on c:\Users\WindowsOS\AppData\Roaming\Code\User\prompts (correlationId: undefined)
> 2025-06-20 08:05:29.216 [trace] [File Watcher (node.js)] Started watching: 'c:\Users\WindowsOS\AppData\Roaming\Code\User\snippets'
> 2025-06-20 08:05:29.552 [trace] lifecycle (main): phase changed (value: 4)
> 2025-06-20 08:05:30.022 [trace] [File Watcher (node.js)] Request to stop watching: c:\Users\WindowsOS\AppData\Roaming\Code\User\prompts (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
> 2025-06-20 08:05:30.022 [trace] [File Watcher (node.js)] stopping file watcher (c:\Users\WindowsOS\AppData\Roaming\Code\User\prompts (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>))
> 2025-06-20 08:05:30.132 [trace] [EncryptionMainService] Decrypting value...
> 2025-06-20 08:05:30.132 [trace] [EncryptionMainService] Decrypted value.
> 2025-06-20 08:05:30.133 [trace] [EncryptionMainService] Decrypting value...
> 2025-06-20 08:05:30.133 [trace] [EncryptionMainService] Decrypted value.
> 2025-06-20 08:05:30.134 [trace] [EncryptionMainService] Decrypting value...
> 2025-06-20 08:05:30.134 [trace] [EncryptionMainService] Decrypted value.
> 2025-06-20 08:05:30.135 [trace] [EncryptionMainService] Decrypting value...
> 2025-06-20 08:05:30.135 [trace] [EncryptionMainService] Decrypted value.
> 2025-06-20 08:05:30.839 [trace] [EncryptionMainService] Decrypting value...
> 2025-06-20 08:05:30.839 [trace] [EncryptionMainService] Decrypted value.
> 2025-06-20 08:05:31.057 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:31.057 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:31.057 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:31.057 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:31.058 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:31.058 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:31.059 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:31.059 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:31.139 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:31.139 [debug] User data changed
> 2025-06-20 08:05:31.140 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:33.936 [trace] [EncryptionMainService] Decrypting value...
> 2025-06-20 08:05:33.936 [trace] [EncryptionMainService] Decrypted value.
> 2025-06-20 08:05:34.147 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:34.147 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:34.148 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:34.148 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:34.148 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:34.148 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:34.149 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:05:34.149 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:34.236 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:34.236 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:05:34.236 [debug] User data changed
> 2025-06-20 08:05:57.081 [trace] update#checkForUpdates, state =  idle
> 2025-06-20 08:05:57.081 [info] update#setState checking for updates
> 2025-06-20 08:05:57.081 [trace] resolveShellEnv(): running
> 2025-06-20 08:05:57.081 [trace] #2: https://update.code.visualstudio.com/api/update/win32-x64-user/stable/18e3a1ec544e6907be1e944a94c496e302073435?bg=true - begin undefined {}
> 2025-06-20 08:05:57.175 [trace] #2: https://update.code.visualstudio.com/api/update/win32-x64-user/stable/18e3a1ec544e6907be1e944a94c496e302073435?bg=true - end undefined 204 {"access-control-allow-origin":"*","date":"Fri, 20 Jun 2025 00:05:56 GMT","request-context":"appId=cid-v1:8109e553-6232-492a-afca-b78cea9b431c","strict-transport-security":"max-age=31536000; includeSubDomains","x-azure-ref":"20250620T000556Z-17444d4b9f9mdmxmhC1HKGyu5w00000002fg000000001m8r","x-cache":"CONFIG_NOCACHE","x-content-type-options":"nosniff","x-powered-by":"Express","x-source-commit":"52c757d6039fc7b9fc4b210aec30978ae2805866"}
> 2025-06-20 08:05:57.175 [info] update#setState idle
> 2025-06-20 08:06:11.649 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:11.649 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:11.649 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:11.649 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:11.650 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:11.650 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:11.650 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:11.650 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:11.657 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:11.657 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:11.658 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:11.658 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:11.731 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:11.733 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:11.734 [debug] User data changed
> 2025-06-20 08:06:48.006 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:48.006 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:48.007 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:48.007 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:48.008 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:48.008 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:48.008 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:48.008 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:48.016 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:48.017 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:48.017 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:48.017 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:48.091 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:48.092 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:48.092 [debug] User data changed
> 2025-06-20 08:06:50.046 [trace] [UtilityProcess id: 2, type: extensionHost, pid: <none>]: creating new...
> 2025-06-20 08:06:50.055 [trace] [UtilityProcess id: 2, type: extensionHost, pid: 10816]: successfully created
> 2025-06-20 08:06:50.653 [trace] [EncryptionMainService] Decrypting value...
> 2025-06-20 08:06:50.653 [trace] [EncryptionMainService] Decrypted value.
> 2025-06-20 08:06:51.674 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:51.674 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:51.674 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:51.674 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:51.754 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:51.754 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:51.754 [debug] User data changed
> 2025-06-20 08:06:52.031 [trace] [UtilityProcess id: 1, type: extensionHost, pid: 4800]: received exit event with code 0
> 2025-06-20 08:06:52.031 [info] Extension host with pid 4800 exited with code: 0, signal: unknown.
> 2025-06-20 08:06:52.710 [trace] [EncryptionMainService] Decrypting value...
> 2025-06-20 08:06:52.710 [trace] [EncryptionMainService] Decrypted value.
> 2025-06-20 08:06:52.711 [trace] [EncryptionMainService] Decrypting value...
> 2025-06-20 08:06:52.711 [trace] [EncryptionMainService] Decrypted value.
> 2025-06-20 08:06:52.712 [trace] [EncryptionMainService] Decrypting value...
> 2025-06-20 08:06:52.712 [trace] [EncryptionMainService] Decrypted value.
> 2025-06-20 08:06:52.712 [trace] [EncryptionMainService] Decrypting value...
> 2025-06-20 08:06:52.712 [trace] [EncryptionMainService] Decrypted value.
> 2025-06-20 08:06:53.410 [trace] [EncryptionMainService] Decrypting value...
> 2025-06-20 08:06:53.410 [trace] [EncryptionMainService] Decrypted value.
> 2025-06-20 08:06:53.626 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:53.626 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:53.627 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:53.627 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:53.628 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:53.628 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:53.628 [trace] [File Watcher (node.js)] [raw] ["change"] globalStorage
> 2025-06-20 08:06:53.628 [trace] [File Watcher (node.js)] [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:53.707 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:53.708 [trace] [File Watcher (node.js)]  >> normalized [CHANGED] c:\Users\WindowsOS\AppData\Roaming\Code\User\globalStorage
> 2025-06-20 08:06:53.708 [debug] User data changed
> ``` 

</details>

 _Originally posted by @blackawn in [#251328](https://github.com/microsoft/vscode/issues/251328#issuecomment-2989447853)_

### PR DESCRIPTION
**Pull request by connor4312**
Closes #251957
Closes #251901
Closes #251446

### CODE REVIEW

File: src/vs/platform/shell/node/shellEnv.ts [hunk 1]
```diff
@@ -36,6 +34,10 @@ let shellEnvPromise: Promise<typeof process.env> | undefined = undefined;
  */
 export async function getResolvedShellEnv(configurationService: IConfigurationService, logService: ILogService, args: NativeParsedArgs, env: IProcessEnvironment): Promise<typeof process.env> {
 
+	if (isWindows) {
+		return {};
+	}
```
Comment (Tyriar) [inline src/vs/platform/shell/node/shellEnv.ts]:
```suggestion
	// Skip on windows
	if (isWindows) {
		logService.trace('resolveShellEnv(): skipped (Windows)');

		return {};
	}
```

File: src/vs/platform/shell/node/shellEnv.ts [hunk 2]
```diff
@@ -116,18 +118,11 @@ async function doResolveShellEnv(logService: ILogService, token: CancellationTok
...
 
-	let name = basename(systemShell);
-	if (isWindows) {
-		const nameExt = extname(name);
-		if (getWindowPathExtensions().some(e => equalsIgnoreCase(e, nameExt))) {
-			name = name.substring(0, name.length - nameExt.length); // remove any .exe/.cmd/... from the name for matching logic on Windows
-		}
-	}
-
+	const name = basename(systemShell);
```
Comment (Tyriar) [inline src/vs/platform/shell/node/shellEnv.ts:124]:
```suggestion
	// handle popular non-POSIX shells
	const name = basename(systemShell);
```

File: src/vs/platform/shell/node/shellEnv.ts [hunk 3]
```diff
@@ -116,18 +118,11 @@ async function doResolveShellEnv(logService: ILogService, token: CancellationTok
 	const systemShell = await getSystemShell(OS, env); // note: windows always resolves a powershell instance
```
Comment (Tyriar) [inline src/vs/platform/shell/node/shellEnv.ts]: Comment no longer valid

File: src/vs/platform/shell/node/shellEnv.ts [hunk 4]
```diff
@@ -116,18 +118,11 @@ async function doResolveShellEnv(logService: ILogService, token: CancellationTok
...
-		}
-	}
-
+	const name = basename(systemShell);
 	let command: string, shellArgs: Array<string>;
 	const extraArgs = '';
 	if (/^(?:pwsh|powershell)(?:-preview)?$/.test(name)) {
-		const profilePaths = await getPowershellProfilePaths(systemShell);
+		const profilePaths = await getPowershellProfilePaths();
 		const profilePathThatExists = await first(profilePaths.map(profilePath => async () => (await FSPromises.exists(profilePath)) ? profilePath : undefined));
```
Comment (Tyriar) [inline src/vs/platform/shell/node/shellEnv.ts]: I don't think we need to be doing this anymore? The less awaits in this code the better.

Previously it looked like this:

```
			// Older versions of PowerShell removes double quotes sometimes so we use "double single quotes" which is how
			// you escape single quotes inside of a single quoted string.
			command = `& '${process.execPath}' ${extraArgs} -p '''${mark}'' + JSON.stringify(process.env) + ''${mark}'''`;
			shellArgs = ['-Login', '-Command'];
```

**Review by Tyriar — DISMISSED** [review]
Is it not possible to do straight reverts of the related PRs anymore? We should bring back all the comments so it looks closer to before

**Comment by connor4312** [comment]
> Is it not possible to do straight reverts of the related PRs anymore? We should bring back all the comments so it looks closer to before

No, we made other improvements in the Windows support work that we will keep for other platforms

File: src/vs/platform/shell/node/shellEnv.ts (hunk 4 above)
Comment (connor4312) [reply src/vs/platform/shell/node/shellEnv.ts]: This still avoids doing shell resolution if no profile file is configured, which saves boot time. File existence checks are super cheap compared to launching the shell, so avoiding it is good.

**Review by Yoyokrazy — APPROVED** [review]

**Comment by Tyriar** [comment]
Thanks! 👍

**Comment by bpasero** [comment]
@connor4312 I see build errors with your revert so I am going to revert how it actually used to be in https://github.com/microsoft/vscode/pull/252755

Specifically, in my full build run in https://monacotools.visualstudio.com/Monaco/_build/results?buildId=346732&view=results:

image

That already includes your revert.

I am not sure what improvements you made that macOS and Linux would benefit from, but if you want to bring those back I suggest you try from a branch with a full build.

**Comment by pacoil0** [comment]
gracias solo observe no hice cambios
