### PR TITLE
Goto definition for built-in symbols in HTML script

### LINKED ISSUE #236603: [html] support `goto definition` on built-in symbols inside of `script`
Does this issue occur when all extensions are disabled?: Yes

Version: 1.96.1 (user setup)
Commit: 42b266171e51a016313f47d0c48aca9295b9cbb2
OS: Windows_NT x64 10

Steps to Reproduce:

1. Create new file with `html` type
2. Put code
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        const b = new Blob([]);
    </script>
</body>

</html>
```
3. Press `ctrl` and hover cursor over `Blob` to see underline to go to definition
4. No underline below `Blob` and click on it doesnt do anything

### PR DESCRIPTION
**Pull request by nknguyenhc**
Fixes #236603 

I handle the filename `lib.dom.d.ts` and resolves it to the correct file to view definition of built-in DOM classes.

### CODE REVIEW

File: extensions/html-language-features/server/src/modes/javascriptMode.ts [hunk 1]
```diff
@@ -601,3 +611,11 @@ function generateIndent(level: number, options: FormattingOptions) {
 		return repeat('\t', level);
 	}
 }
+
+function getLibDomUriAndDocument(): [string, TextDocument] {
```
Comment (aeschli) [inline extensions/html-language-features/server/src/modes/javascriptMode.ts:615]: To compute the library location, add a new function to https://github.com/microsoft/vscode/blob/91e6ae971de19ccfb32e90f064cf194d81a29a39/extensions/html-language-features/server/src/modes/javascriptLibs.ts#L11 and reuse the logic there.

As for the document URI, this is trickier as this also needs to run on the web (vscode.dev), and there's no 'file' there.
You probably need to start from the [extensionUri](https://github.com/microsoft/vscode/blob/91e6ae971de19ccfb32e90f064cf194d81a29a39/src/vscode-dts/vscode.d.ts#L8269) that you get on the HTML client, and pass it on the server.

**Review by aeschli — CHANGES_REQUESTED** [review]

File: extensions/html-language-features/server/src/modes/javascriptMode.ts [hunk 2]
```diff
@@ -302,12 +304,29 @@ export function getJavaScriptMode(documentRegions: LanguageModelCache<HTMLDocume
...
+						if (!extensionUri) {
+							return undefined;
+						}
+						const filePath = path.posix.join(extensionUri.path, '../node_modules/typescript/lib', d.fileName);
+						const libUri = `${extensionUri.scheme}://${filePath}`;
+						const content = loadLibrary(d.fileName);
+						if (!content) {
+							return undefined;
+						}
+						const libDocument = TextDocument.create(libUri, 'typescript', 1, content);
```
Comment (nknguyenhc) [inline extensions/html-language-features/server/src/modes/javascriptMode.ts:323]: @aeschli Currently I put the logic here instead of in `javascriptLibs.ts` because webpack (for vscode.dev) uses a different version for it, as specified in `html-language-features/server/extension-browser.webpack.config.js`. Should I declare this logic in `javascriptLibs.ts` and edit the file `html-language-features/server/build/javaScriptLibraryLoader.js` as well, or should I just keep the logic here?

Comment (aeschli) [reply extensions/html-language-features/server/src/modes/javascriptMode.ts:323]: Oh, now I remember, for vscode.dev we just bundle the library files.

**Comment by aeschli** [comment]
Sorry, it's been a while since I did LSP stuff, but I start to remember again.

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#workspace_textDocumentContent

This allows the server to provide documents with virtual URIs that then can be opened by the client (VS Code).

- Your `Definition.uri` will be something like `html-server://typescript-libs/lib.d.ts`.
- In the client you declare that the server can provide document contents for schema `html-server`
- In the server you have a provider that serves these documents using the `libs.loadLibrary(`lib.d.ts') call.

What do you think? I think that's the right approach, which will also work on vscode.dev.

**Comment by aeschli** [comment]
Ah nice it works. What I don't like is that it's not reflecting what we really do (using a bundled file, as we found out). So we could change that, and go away from bunding, but that's another challenge as reading URIs from the server is also not possible (needs to go to the client and the vscode filesystem API)

I think you need to set this to the server capabilities: https://github.com/microsoft/vscode/blob/14cda18c60c650f663e143e02ddf5acdf901ca54/extensions/html-language-features/server/src/htmlServer.ts#L195
```
			workspace: {
				textDocumentContent: {
					schemes: ['foo']
				}
			}
			`

**Comment by aeschli** [comment]
You mean the breadcrumbs. Don't know why they don't show, you have to debug in the breadcrumb code.
For the second issue, Maybe it helps if the json extension has a `"onFileSystem:html-server" activation event?

**Comment by nknguyenhc** [comment]
@aeschli Here's what I found:

For breadcrumb to be displayed with files from `html-server` scheme, a file system provider needs to be declared in the extension, eg:

```ts
vscode.workspace.registerFileSystemProvider('html-server', /* some file system provider */);
```

However, for a client-server extension like `html-language-features`, the language server protocol is not yet able to handle virtual resources. It is still an open issue in [microsoft/language-server-protocol#1264](https://github.com/microsoft/language-server-protocol/issues/1264). Which means, the client needs to declare the file system provider as above.

For now, I believe the solution is to declare the file system provider as above in the client, and then within the provider, make a call to the server to fetch the file content via `workspace/textDocumentContent`.

What do you think? Lmk how I should proceed.

**Comment by aeschli** [comment]
Thanks for the analysis!

I see, the LSP client uses the 'TextDocumentContentProvider' to serve the document, not a file system provider. https://github.com/microsoft/vscode-languageserver-node/blob/df05883f34b39255d40d68cef55caf2e93cff35f/client/src/common/textDocumentContent.ts#L86

I guess we could file an issue against the LSP client to use a file system provider instead. @dbaeumer FYI. That would help other languages as well that use TextDocumentContents (I believe Java)
https://github.com/microsoft/language-server-protocol/issues/1264 is a different topic, not related to TextDocumentContents

I don't know what happens if there's both a vscode.TextDocumentContentProvider as well as a FileSystemProvider.
I would not try to work around the LSP client. IMO not having the breadcrumbs is a minor issue.

**Comment by nknguyenhc** [comment]
@aeschli As for persisting the document through restart, I found out that there must be an editor serializer (`src\vs\workbench\common\editor.ts`, class `IEditorSerializer`) that handles the editor type. For the library files opened by the HTML server, it is of type `TextResourceEditorInput`, and there is no corresponding editor serializer.

I have tried looking through VSCode API, the closest ones that I can find are [`registerCustomEditorProvider`](https://code.visualstudio.com/api/references/vscode-api#window.registerCustomEditorProvider) or [`registerWebviewPanelSerializer`](https://code.visualstudio.com/api/references/vscode-api#window.registerWebviewPanelSerializer), but I believe they are not the same thing as registering an editor serializer? Also, I did not manage to find any similar APIs in language server.

As for now, the only solution I can think of is to add a serializer for `TextResourceEditorInput`, but I'm not too sure if this will affect the behaviour of other files that are under the same editor type. Lmk how I should proceed.

**Comment by nknguyenhc** [comment]
@aeschli Other than these 2 issues, the PR is ready to be reviewed.

**Comment by aeschli** [comment]
@nknguyenhc Very nice and slick! Thanks a lot!

I allowed myself to do a change on the signature of `getTextDocumentContent`. Hope you like it.

**Review by aeschli — APPROVED** [review]

**Comment by nknguyenhc** [comment]
> @nknguyenhc Very nice and slick! Thanks a lot!
> 
> I allowed myself to do a change on the signature of `getTextDocumentContent`. Hope you like it.

Yep, looks great!

**Review by chrmarti — APPROVED** [review]
