### PR TITLE
Browser: allow temporary certificate trust

### LINKED ISSUE #298982: ERR_CERT_AUTHORITY_INVALID for localhost HTTPS in Simple Browser Tab despite working fine in MS Edge
Type: <b>Bug</b>

Opening a Simple Browser tab and trying to access a local dev server over https using a self signed certificate is blocked with an error page saying:

Failed to Load Page
ERR_CERT_AUTHORITY_INVALID (-202)
URL: `https://my-custom-domain.dev.localhost:portNumber/path`

If I open the same url in MS Edge, I get a warning but I can click through to continue anyway because I trust my local dev server. But in the VS Code Simple Browser tab there's no way to continue - I'm just stuck here.

I've tried using mkcert, overriding VS Code arg variables in system user settings as well as workspace settings, clicking in the page and typing `thisisunsafe` - nothing works. There's no way to bypass this page and continue to my local dev server over https.

VS Code version: Code 1.109.5 (072586267e68ece9a47aa43f8c108e0dcbf44622, 2026-02-19T19:43:32.382Z)
OS version: Windows_NT x64 10.0.26200
Modes:

### PR DESCRIPTION
**Pull request by kycutler**
Closes #298982

Same as Chromium, trust is based on hostname+fingerprint and valid for 1 week.

Trust is per-session, persisted in storage, and gets cleared with session data.

image

image

### CODE REVIEW

File: src/vs/platform/browserView/electron-main/browserView.ts [hunk 1]
```diff
@@ -250,20 +250,25 @@ export class BrowserView extends Disposable implements ICDPTarget {
 				this._lastError = {
 					url: validatedURL,
 					errorCode,
-					errorDescription
+					errorDescription,
+					// -200 - -220 are the range of certificate errors in Chromium.
```
Comment (jruales) [inline src/vs/platform/browserView/electron-main/browserView.ts]: Is this documented somewhere? I guess these aren't the standsrd error codes

**Review by lramos15 — APPROVED** [review]
