### PR TITLE
bring back `TerminalChatExecute` menu so voice input is possible, fire `acceptInput` so recording stops appropriately

### LINKED ISSUE #229025: Terminal: voice recording no longer stops when submitted
Steps to Reproduce:

1. start inline chat in terminal with voice
2. speak something so that input gets filled
3. wait until it gets auto submitted

=> 🐛 the recording does not stop

This relies on `terminalChat.onDidAcceptInput` to fire which no longer seems to be the case:

https://github.com/microsoft/vscode/blob/c2d40bee71a1cd38146754402fa1c08d4ef0b03a/src/vs/workbench/contrib/chat/electron-sandbox/actions/voiceChatActions.ts#L224

### LINKED ISSUE #230330: terminal chat voice recording button is missing
It last existed here https://github.com/microsoft/vscode/pull/229402 AFAIK and is missing in Insider's.

Image

### PR DESCRIPTION
**Pull request by meganrogge**
addresses #230330 in main
fixes [#229025](https://github.com/microsoft/vscode/issues/229025)

### CODE REVIEW

File: src/vs/workbench/contrib/chat/electron-sandbox/actions/voiceChatActions.ts [hunk 1]
```diff
@@ -1328,6 +1352,11 @@ export class InstallSpeechProviderForVoiceChatAction extends BaseInstallSpeechPr
 				when: HasSpeechProvider.negate(),
 				group: 'navigation',
 				order: 3
+			}, {
+				id: TerminalChatExecute,
```
Comment (meganrogge) [inline src/vs/workbench/contrib/chat/electron-sandbox/actions/voiceChatActions.ts:1356]: i'm seeing that when this is present, the duplicate mics show up. it seems `HasSpeechProvider` is always `false` for the terminal

Comment (meganrogge) [reply src/vs/workbench/contrib/chat/electron-sandbox/actions/voiceChatActions.ts:1356]: unclear if that's just what i'm seeing because the ext host is crashing in oss

Comment (meganrogge) [reply src/vs/workbench/contrib/chat/electron-sandbox/actions/voiceChatActions.ts:1356]: I hadn't installed the speech extension. Apparently in OSS, the notification to install doesn't show up, so this is expected.

**Review by roblourens — APPROVED** [review]
