### PR TITLE
Fixes #7301: Set LANG for terminal process

### LINKED ISSUE #7301: Set locale variables automatically for the integrated terminal
- VSCode Version: 1.2.0
- OS Version: OSX 10.11.5

Steps to Reproduce:
1. I use ZSH for shell.
2. Open Integrated Terminal and run `locale`.
3. Locale is not set properly. Here is my result:

```
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

Expected:

An optional similar to the default Terminal app in OSX. It makes sense to have it ON by default.
Option from Terminal settings:
screen shot 2016-06-07 at 10 11 48 am

Workaround:

Add the following to your profile (`~/.zhrc` for ZSH):

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

### PR DESCRIPTION
**Pull request by chrmarti**
Setting LANG for the terminal process fixes it. This is also useful when running Cygwin under Windows, so I'm not checking for the platform.

Computing the LANG value could be improved by getting all available values from 'locale -a', but would also make the fix much more involved.

### CODE REVIEW

File: src/vs/workbench/parts/terminal/electron-browser/terminalService.ts [hunk 1]
```diff
@@ -230,6 +230,9 @@ export class TerminalService implements ITerminalService {
 			env[`PTYSHELLARG${i}`] = arg;
 		});
 		env['PTYCWD'] = this.contextService.getWorkspace() ? this.contextService.getWorkspace().resource.fsPath : os.homedir();
+		if (!env['LANG'] && platform.locale) {
+			env['LANG'] = this.getLang(platform.locale);
```
Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalService.ts]: Do the `LC_` variables get fixed with this? Do you need to set `LC_ALL` too?

File: src/vs/workbench/parts/terminal/electron-browser/terminalService.ts [hunk 2]
```diff
@@ -230,6 +230,9 @@ export class TerminalService implements ITerminalService {
 			env[`PTYSHELLARG${i}`] = arg;
 		});
 		env['PTYCWD'] = this.contextService.getWorkspace() ? this.contextService.getWorkspace().resource.fsPath : os.homedir();
+		if (!env['LANG'] && platform.locale) {
```
Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalService.ts]: This function's a bit busy at this point, can you factor out the `env` stuff into a `createTerminalEnv` function?

Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalService.ts]: Some tests for this function would be good too, I can help with this on Monday if you need.

File: src/vs/workbench/parts/terminal/electron-browser/terminalService.ts (hunk 1 above)
Comment (chrmarti) [inline src/vs/workbench/parts/terminal/electron-browser/terminalService.ts]: 'locale' will show the LC_ variables set the same, except for LC_ALL which will be empty. That's the same as you're screenshot shows and the same as the terminal shows me under OS X. I assume that should be fine.

File: src/vs/workbench/parts/terminal/electron-browser/terminalService.ts [hunk 3]
```diff
@@ -222,14 +222,7 @@ export class TerminalService implements ITerminalService {
...
 	private createTerminalProcess(): ITerminalProcess {
-		let env = this.cloneEnv();
-		let shell = this.configHelper.getShell();
-		env['PTYPID'] = process.pid.toString();
-		env['PTYSHELL'] = shell.executable;
-		shell.args.forEach((arg, i) => {
-			env[`PTYSHELLARG${i}`] = arg;
-		});
-		env['PTYCWD'] = this.contextService.getWorkspace() ? this.contextService.getWorkspace().resource.fsPath : os.homedir();
+		let env = this.createTerminalEnv();
```
Comment (Tyriar) [inline src/vs/workbench/parts/terminal/electron-browser/terminalService.ts]: May as well do the call inside `cp.fork` now. Other than that good to go though I'd like to see some tests for it since it see,s fairly testable.

**Comment by Tyriar** [comment]
Thanks for the test :smile: 

I'm thinking this should probably be Mac specific though since I'd rather it didn't change my LANG config on Linux, we also only want it to apply on Unix-like systems.  This can be easily achieved/testable by just adding an `setLang` parameter to `createTerminalEnv`:

```ts
public static createTerminalEnv(parentEnv: IStringDictionary<string>, shell: IShell, workspace: IWorkspace, locale: string, setLang: boolean): IStringDictionary<string>
```

```ts
let env = TerminalService.createTerminalEnv(process.env, this.configHelper.getShell(), this.contextService.getWorkspace(), platform.locale, platform.isMacintosh);
```

**Comment by chrmarti** [comment]
It also makes sense for Windows when using Cygwin's bash. Currently the locale isn't set properly with that:
```
$ locale
LANG=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_ALL=
```

**Comment by Tyriar** [comment]
@chrmarti so there's 2 options then:

1. `LANG` is only set when it's not empty
2. A `terminal.integrated.setLocaleVariables` setting that's on by default on OS X

I'm leaning towards 2 as I'd rather the terminal didn't have `LANG` on Linux if I explicitly did not set it.

**Comment by Tyriar** [comment]
Looks like I just caused some conflicts with my copy/paste change. After they're fixed you can merge this in :+1:
