### PR TITLE
disable shell integration for complex debug trap

### LINKED ISSUE #157851: Terminal Shell Integration Error -- command not found
Type: <b>Bug</b>

After upgrading to 1.70.1 the integrated terminal (with shell integration enabled) is generating the following error whenever a terminal is launched and also after every command.

```
bash: [[ "$BASH_COMMAND" != "$PROMPT_COMMAND" ]] && chruby_auto: command not found...
```

This appears to be related to #157189 as the 1.70.1 version was the first to include the fix for that issue.

The error is the same as what `trap -p DEBUG` is set to. This seems like the command trying to be run is a string and is not being parsed like there are arguments.

```
$ trap -p DEBUG
trap -- '[[ "$BASH_COMMAND" != "$PROMPT_COMMAND" ]] && chruby_auto' DEBUG
```

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:09:15.055Z)
OS version: Linux x64 5.18.15-200.fc36.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|62.56GB (3.04GB free)|
|Process Argv|--unity-launch --crash-reporter-id 57fdd0a5-4103-4bed-9134-70c1dcd69cc9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|2.9.8
scratchpads|bue|0.0.7
solargraph|cas|0.23.0
vscode-markdownlint|Dav|0.47.0
ansible-vault|dho|0.1.3
docs-markdown|doc|0.2.113
githistory|don|0.6.19
gitlens|eam|12.1.2
json-tools|eri|1.0.2
opensslutils|ffa|1.1.1
shell-format|fox|7.2.2
gc-excelviewer|Gra|4.2.55
todo-tree|Gru|0.0.215
rest-client|hum|0.25.0
vscode-jmespath|jos|0.0.6
bash-ide-vscode|mad|1.14.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.22.1
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.20
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
cpptools|ms-|1.11.5
ruby|reb|0.28.1
ansible|red|0.11.29
vscode-commons|red|0.0.6
vscode-yaml|red|1.9.1
bash-debug|rog|0.3.9
rufo-vscode|sil|0.0.3
code-spell-checker|str|2.5.4
shellcheck|tim|0.19.6
pdf|tom|1.2.0
vscode-icons|vsc|11.15.0
vim|vsc|1.23.2
jinja|who|0.0.8
vscode-ruby|win|0.28.0
markdown-all-in-one|yzh|3.4.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
vscaat:30438848
pylanb8912cf:30529770
vsclangdf:30486550
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253

```

</details>

### PR DESCRIPTION
**Pull request by meganrogge**
fix #157851

### CODE REVIEW

File: src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh [hunk 1]
```diff
@@ -131,9 +131,8 @@ if [[ -n "${bash_preexec_imported:-}" ]]; then
 else
 	__vsc_dbg_trap="$(trap -p DEBUG)"
 	if [[ "$__vsc_dbg_trap" =~ .*\[\[.* ]]; then
-		#HACK - is there a better way to do this?
-		__vsc_dbg_trap=${__vsc_dbg_trap#'trap -- '*}
-		__vsc_dbg_trap=${__vsc_dbg_trap%'DEBUG'}
+		#https://github.com/microsoft/vscode/issues/157851
+		builtin return;
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh:135]: Can we do this check earlier, before we setup all the variables/functions?

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh [hunk 2]
```diff
@@ -8,6 +8,12 @@ if [[ -n "$VSCODE_SHELL_INTEGRATION" ]]; then
 	builtin return
 fi
 
+__vsc_dbg_trap="$(trap -p DEBUG)"
+if [[ "$__vsc_dbg_trap" =~ .*\[\[.* ]]; then
+	#https://github.com/microsoft/vscode/issues/157851
+	builtin return;
+fi
```
Comment (Tyriar) [inline src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh:15]: This needs to happen next to the `if [ -z "$VSCODE_SHELL_INTEGRATION" ]; then` statement so regular init scripts run when injected. A comment above the if and I think we should inline the trap command so `__vsc_debug_trap` doesn't get set: `if [[ "$(trap -p DEBUG)" =~ .*\[\[.* ]]; then`

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Review by Tyriar — APPROVED** [review]
