### PR TITLE
Pass display language as a locale to Electron

### LINKED ISSUE #163458: Spanish language pack recommender doesn't work on macOS
1. Ensure that `argv.json` doesn't have a `locale` key-value pair.
2. Ensure the VS Code Spanish language pack isn't already installed.
3. Set macOS to use the `Español (Latinoamérica)` language.
4. Open VS Code.
5. :bug: VS Code isn't in Spanish.

If one repeats the steps with `Français (Canada)` or `Português (Brasil)`, VS Code starts up in French and Portuguese, respectively. With `Español (Latinoamérica)`, `app.getLocale()` returns `es-419`, and the extra country code confuses the recommender.

I plan on fixing this issue as part of the `getSystemLocale` PR.

CC @TylerLeonhardt

### PR DESCRIPTION
**Pull request by rzhao271**
Ref #159813
Passing the locale to Electron fixes how the WCO is rendered, otherwise, Electron decides the locale based on the system language. The WCO should be rendered based on the display language, not the system language.

Ref https://github.com/microsoft/vscode/issues/161218
Fixes https://github.com/microsoft/vscode/issues/163458

TODO:
- [x] Determine what other regressions this change could cause.
- [x] Do we want to limit this change to just Windows?

The screenshot below shows that the WCO has been moved out of the way with the fix.
Screenshot

### CODE REVIEW

**Review by deepak1556 — COMMENTED** [review]
I like this change but I have small concern for this fix being shipped as candidate.

The change impacts ICU's default locale for both chromium and node, also affects `Accept-language` header. Although I agree that these values should match the display language set in VSCode, is there a history for why we haven't done this since the beginning ? Did we have any bugs when we configured the locale of Electron ? @bpasero do you know anything on this ?

**Comment by bpasero** [comment]
I am not aware of the reasoning why we never did this, maybe @dbaeumer, @joaomoreno or @TylerLeonhardt know of a reason. However, we do set the `lang` attribute in the DOM quite early for a long time here and I would have expected that to have an impact, but. maybe @deepak1556 should compare how the `--locale` does things different from the `lang` attribute`:

https://github.com/microsoft/vscode/blob/4f69cdf95a12cef48d405b38bf7812a7f297c310/src/bootstrap-window.js#L96-L103

One thing to keep in mind is that `locale` will only be in `argv.json` if the user explicitly picked a language in VSCode. We do not automatically write to `argv.json` otherwise.

**Review by bpasero — CHANGES_REQUESTED** [review]
I feel this is a bit too heavy for a candidate and would rather suggest to do this on insiders and disable WCO on stable as the candidate fix.

**Comment by deepak1556** [comment]
> However, we do set the lang attribute in the DOM quite early for a long time here and I would have expected that to have an impact

This would only impact the render process in which it was changed, main process would remain unaffected. WCO rendering depends on the locale of the main process. Ideally, to change the application locale of chromium, application has to configure the `--lang` switch so that main process first picks up the change and it will also take care of propagating the changes to all of the child processes automatically.

> should compare how the --locale does things different from the lang attribute`:

`--locale` is a switch implemented for VSCode, the plan is to not alter the behavior of this switch but additionally make sure this switch value also gets reflected for `--lang` which is a switch dedicated to Electron/Chromium.

> One thing to keep in mind is that locale will only be in argv.json if the user explicitly picked a language in VSCode. We do not automatically write to argv.json otherwise.

Thanks for the pointer, we want to reflect the values of both `locale` and language packs via `--lang` moving forward. Given both require a restart for changes, I think we can accommodate them in terms of API contract.

**Comment by bpasero** [comment]
I am not sure I understand the difference between `--locale` and `--lang` and suggest to connect with devs owning our language support (Tyler, Dirk).

Yes we use `app.getLocale` to know which language pack to resolve unless this was explicitly defined by the user. I think in the 99% case, the locale will not be in the `argv.json`:

https://github.com/microsoft/vscode/blob/4f69cdf95a12cef48d405b38bf7812a7f297c310/src/main.js#L552-L568

**Comment by deepak1556** [comment]
@rzhao271 we can continue this PR to address the locale of the runtime after connecting with @TylerLeonhardt and @dbaeumer . 

But for resolving https://github.com/microsoft/vscode/issues/159813 as a candidate, can you open a separate PR that disables WCO. Thanks!

**Comment by dbaeumer** [comment]
Here is what I can remember:

- `app.commandLine.appendSwitch('lang', argvValue ?? 'en')`: I simply wasn't aware of this
- locale versus language in VS Code: `locale` is either the OS local or the locale configured for VS Code. `language` is the language in UI is rendered in. This doesn't necessarily need to be the `locale`. Usually, case is that the `locale` points to a language for which we don't have a language pack.

**Comment by deepak1556** [comment]
> locale is either the OS local or the locale configured for VS Code.

@dbaeumer which components of the UI or core does this value affect ? Especially in cases where language pack and locale value are different.

**Comment by dbaeumer** [comment]
The `locale` value does only affect the picking of the language pack. The UI should always be rendered using the `language` value.

**Comment by rzhao271** [comment]
For https://github.com/microsoft/vscode/pull/159958#issuecomment-1236626210, the reason that `locale` often points to a language for which there is no language pack installed is because `locale` often takes the OS locale if not explicitly passed in. This PR changes it so that it takes whatever is in `argv.json` for the `locale` field. If that value happens to be where the language used by the language pack is stored, then we have `locale = Electron locale = VS Code language` and I think that's what we want.

One issue with this approach is I'm unsure what happens when the language pack doesn't represent a valid locale, such as with the pseudo-language extension pack. In that case, I'd hope that the locale would default back to English, but I still have to check.

**Comment by deepak1556** [comment]
Based on the `locale` and `language` distinctive usage in VSCode I have heard from @dbaeumer and @rzhao271, using `--lang` flag to change Electron's locale will be a disruptive change because `app.getLocale` reflects the value passed to `--lang`.

Given we want `locale` to reflect either a user defined locale or default to OS locale, I suggest exposing another api in Electron `app.getOSLocale` so that we have the following contracts,

1) `--lang` will reflect the value of `language` if a language pack was installed and `app.getLocale` will reflect the same.
2) When language pack is not available `--lang` and `app.getLocale` will point to `en` as default.
3) VSCode `locale` can point to user defined locale or can get OS locale value from `app.getOSLocale`

**Comment by TylerLeonhardt** [comment]
Sounds great! I was just saying to @rzhao271 that we needed an API for "give me whatever the OS says, not anything else"

**Comment by dbaeumer** [comment]
Makes perfect sense to me. It is basically locale and lang in out model.

**Comment by deepak1556** [comment]
Great, thanks for the feedback. @rzhao271 lets start with adding the Electron API as next step.

**Review by TylerLeonhardt — DISMISSED** [review]

File: src/main.js [hunk 1]
```diff
@@ -551,7 +569,13 @@ async function resolveNlsConfiguration() {
...
 		// valid after we have received the app ready event. This is why the
 		// code is here.
-		let appLocale = app.getLocale();
+
+		// The ternary and ts-ignore can both be removed once Electron
+		// officially adopts the getSystemLocale API.
+		// Ref https://github.com/electron/electron/pull/35697
+		let appLocale = 'getSystemLocale' in app ?
+			// @ts-ignore API not yet available in the official Electron
+			app.getSystemLocale() : app.getLocale();
```
Comment (deepak1556) [inline src/main.js:578]: Why not remove the country code from `app.getSystemLocale()` before passing to `localization.contribution.ts` ?

**Review by bpasero — CHANGES_REQUESTED** [review]
I thought we wanted to exclude this in stable? If so, please use `product.quality !== stable` around the new code.

File: src/main.js (hunk 1 above)
Comment (rzhao271) [reply src/main.js:578]: It is needed in some cases. Some language packs have country codes, and others don't.

File: src/main.js [hunk 2]
```diff
@@ -190,6 +193,21 @@ function configureCommandlineSwitchesSync(cliArgs) {
...
+			// Locale
+			else if (argvKey === 'locale') {
+				if ('getSystemLocale' in app) {
+					// Pass in the locale to Electron so that the Windows Control Overlay
+					// is rendered correctly.
+					// The if statement can be removed when Electron officially
+					// adopts the getSystemLocale API.
+					// Ref https://github.com/microsoft/vscode/issues/159813
+					// and https://github.com/electron/electron/pull/35697
+					const localeToUse = (!argvValue || argvValue === 'qps-ploc') ?
```
Comment (deepak1556) [inline src/main.js:205]: Can you add comment on why we need `qps-ploc` check ?

Comment (rzhao271) [reply src/main.js:205]: When changing to another language pack, the locale gets saved in argv.json. If we read the pseudolanguage pack value (qps-ploc) and pass it to Chromium, it isn't a recognized locale. qps-ploc is based on English anyway, so I'd rather pass the en locale to Chromium in that case.

Comment (deepak1556) [reply src/main.js:205]: Can you provide an example when `locale: "qps-ploc"` gets set in argv.json ?

Comment (TylerLeonhardt) [reply src/main.js:205]: @deepak1556 when you install the [Pseudo Language Pack](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-qps-ploc) and set it as the language using `Configure Display Language`.

Comment (deepak1556) [reply src/main.js:205]: TIL about `Pseudo Language Pack` extension. Thanks @TylerLeonhardt

File: src/main.js [hunk 3]
```diff
@@ -190,6 +193,21 @@ function configureCommandlineSwitchesSync(cliArgs) {
 				}
 			}
 
+			// Locale
+			else if (argvKey === 'locale') {
+				if (product.quality === 'code-insiders') {
```
Comment (deepak1556) [inline src/main.js:198]:
```suggestion
				if (product.quality === 'insider') {
```

Refs https://github.com/microsoft/vscode-distro/blob/164595434a0f944feb5cfa6202186b68dade393c/quality/insider/product.json#L43

Comment (bpasero) [reply src/main.js:198]: Alternatively `product.quality !== 'stable'` to support our exploration builds too.

File: src/main.js [hunk 4]
```diff
@@ -551,7 +569,13 @@ async function resolveNlsConfiguration() {
 		// Try to use the app locale. Please note that the app locale is only
 		// valid after we have received the app ready event. This is why the
 		// code is here.
-		let appLocale = app.getLocale();
+
+		// The ternary and ts-ignore can both be removed once Electron
+		// officially adopts the getSystemLocale API.
+		// Ref https://github.com/electron/electron/pull/35697
+		let appLocale = product.quality === 'code-insiders' ?
```
Comment (bpasero) [inline src/main.js:576]: Same as above.

File: src/main.js (hunk 3 above)
Comment (deepak1556) [reply src/main.js:198]: @bpasero can we instead have `product.quality === 'insider' || product.quality === 'exploration'` since we also don't want to enable this change in OSS till we update to Electron v21

**Comment by rzhao271** [comment]
I'd like to move this PR out to October. I think it needs some custom builds and sanity checking first, considering it affects the main startup file.

File: src/main.js (hunk 1 above)
Comment (bpasero) [reply src/main.js:578]: Maybe the call could be surrounded with `perf.mark('code/willGetSystemLocale');` and `perf.mark('code/didGetSystemLocale');` to ensure we track the time this needs.

**Review by bpasero — CHANGES_REQUESTED** [review]
I just realised that by using `getSystemLocale` we can possibly improve startup performance because we no longer have to wait for `app.on(ready)` to resolve NLS, as opposed to `app.getLocale()`. Will follow up on this in November when this landed.

**Comment by deepak1556** [comment]
@bpasero `getSystemLocale` also expects to be called after `app#ready`

**Comment by bpasero** [comment]
Ah ok, I would have not assumed that. Is there anything in Chrome that has an impact on the result of that method?

**Comment by deepak1556** [comment]
Actually, now that I revisit the code we setup both the system locale and application locale values during single thread stage of the main process https://github.com/electron/electron/blob/f82a863f654b12846bab783677f20d0842add13f/shell/browser/electron_browser_main_parts.cc#L287-L364 , the applications main script actually runs later than this step in https://github.com/electron/electron/blob/f82a863f654b12846bab783677f20d0842add13f/shell/browser/electron_browser_main_parts.cc#L431-L434 , so technically both `app.getSystemLocale`, `app.getLocale` values are available by the time main script runs and are fine to be called before `app#ready` event. I will get the restrictions removed on these methods.

**Comment by bpasero** [comment]
Ah nice 👍 . I can look into shuffling the code around when I am back to see how we can speed things up knowing that we can use the methods earlier, but maybe would be good to document in Electron for the JSDoc.

**Comment by rzhao271** [comment]
Windows sanity check seems to have failed:
- The perf mark doesn't show up when viewing startup performance
- The French language pack isn't recommended when it is not yet installed and the user is using VS Code in English while the system language is in French.

File: src/main.js (hunk 1 above)
Comment (deepak1556) [reply src/main.js:579]: Both the API are just getters, they don't calculate the values on demand rather fetch the values that were calculated by Electron on startup before user script starts executing, so these marks wouldn't add any value to the actual time spent on those. We could instead have a mark on the native side if we are interested in the actual cost.

Comment (rzhao271) [reply src/main.js:581]: I have removed the language code in some cases to improve the language pack recommender. See below for the if statement

File: src/vs/workbench/contrib/localization/electron-sandbox/localization.contribution.ts [hunk 5]
```diff
@@ -164,7 +164,7 @@ export class LocalizationWorkbenchContribution extends Disposable implements IWo
 								label: translations['installAndRestart'],
 								run: () => {
 									logUserReaction('installAndRestart');
-									this.installExtension(extensionToInstall).then(() => this.hostService.restart());
+									this.installExtension(extensionToInstall!).then(() => this.hostService.restart());
```
Comment (rzhao271) [inline src/vs/workbench/contrib/localization/electron-sandbox/localization.contribution.ts:167]: extensionToInstall in this context is null-checked at line 176

**Comment by rzhao271** [comment]
I have fixed the issue with the language pack recommender, and this PR should also fix https://github.com/microsoft/vscode/issues/163458

**Review by TylerLeonhardt — DISMISSED** [review]

**Review by deepak1556 — DISMISSED** [review]
LGTM on the Electron side of changes.

**Comment by rzhao271** [comment]
I did some sanity checking on Windows and noticed that when I had no `locale` key in `argv.json`, and had the Windows language set to Farsi, that the WCO would once again render to the left even when the application was in English. It turned out I wasn't handling the case where the `locale` key wasn't in `argv.json` at all.

File: src/main.js [hunk 6]
```diff
@@ -177,6 +180,8 @@ function configureCommandlineSwitchesSync(cliArgs) {
 	// Read argv config
 	const argvConfig = readArgvConfigSync();
 
+	let hasLocaleSwitch = false;
```
Comment (bpasero) [inline src/main.js:183]: Rather than storing `hasLocaleSwitch`, I would suggest to store the locale from the `argv.json` if any and then have a single place where we call `app.commandLine.appendSwitch('lang', localeToUse);` in the end. I also think we can do the check for insiders/exploration there as well as for the pseudo language.

**Review by bpasero — CHANGES_REQUESTED** [review]
What does this change actually mean for our support to run `code --locale`? I just now found out that we advertise for it when you run `code --help`. This probably should then override whatever is in `argv.json`?

**Review by bpasero — COMMENTED** [review]
I am a bit confused by your last change, I was not suggesting to remove the `locale` check, just consolidate it in one place. Why is it removed now? Do we no longer have to check for `argv.json` and `locale`?

**Comment by rzhao271** [comment]
I consolidated the checks&mdash;the check for the locale arg already happens at https://github.com/microsoft/vscode/blob/0f9b263fce25d22b7004a7e69dfbf80f316747f4/src/main.js#L584

**Review by bpasero — APPROVED** [review]
Your last change makes good sense 👍 

Can we also test what happens when you pass a bogus value to the `lang` switch, will the startup continue normally or do we have to validate the input?

**Review by deepak1556 — APPROVED** [review]
LGTM on the Electron changes.

**Review by TylerLeonhardt — APPROVED** [review]
