### PR TITLE
Handle backup data with custom editor input factory

### LINKED ISSUE #99056: Notebook: weird restore from dirty
Steps to Reproduce:

1. create a github issue notebook and leave it dirty
2. reload window
3. create a second github issue notebook and leave it dirty
4. reload window

=> 🐛  3 notebooks open?

image

### PR DESCRIPTION
**Pull request by rebornix**
This PR fixes #99056.

"Custom" editors might be using working copies with different scheme (which means `EditorInput.resource !== WorkingCopy.resource`), then when we restore backups and hook them with editor tabs during workbench restore, we have to ask custom editor contributions if a backup resource is identical to an editor input resource.

### CODE REVIEW

File: src/vs/workbench/contrib/customEditor/browser/customEditorInputFactory.ts [hunk 1]
```diff
@@ -124,4 +124,8 @@ export class CustomEditorInputFactory extends WebviewEditorInputFactory {
 			return editor;
 		});
 	}
+
+	public static canResolveBackup(editorInput: IEditorInput, backupResource: URI): boolean {
+		return false;
```
Comment (mjbvz) [inline src/vs/workbench/contrib/customEditor/browser/customEditorInputFactory.ts:129]: Should this use the same implementation that you added for notebooks?

**Review by mjbvz — APPROVED** [review]

File: src/vs/workbench/contrib/customEditor/browser/customEditorInputFactory.ts (hunk 1 above)
Comment (rebornix) [reply src/vs/workbench/contrib/customEditor/browser/customEditorInputFactory.ts:129]: Yes, I'll make the change for custom editor.

**Comment by rebornix** [comment]
@mjbvz as Custom Editor working copy resource has more information (scheme, viewtype, path), instead of comparing resource URI, I check `editorInput.resource.path === backupResource.path && backupResource.authority === editorInput.viewType)` to decide if the backup can be restored.
