### PR TITLE
Detect md image link

### LINKED ISSUE #49238: Markdown link provider misses link for image
Steps to Reproduce:

1. For the markdown:

```md
[![a](b)](c)

```

**Bug**
Only `b` is detected as a clickable link.

### PR DESCRIPTION
**Pull request by flurmbo**
Fixes #49238. I added an option to the regex to have an image instead of text for the link description. Then when iterating over regex matches `providerInlineLinks` will now check to see if an image resource was also matched, and if so add it to results. All the tests pass, as well as a new one I've added. 

Feedback on the regex would be appreciated, also I think perhaps the code I copied [starting here](https://github.com/Microsoft/vscode/blob/2d79ffe0cd84515a4c771fcbd7294c2448d97826/extensions/markdown-language-features/src/features/documentLinkProvider.ts#L76) could be refactored into a separate function.

### CODE REVIEW

File: extensions/markdown-language-features/src/features/documentLinkProvider.ts [hunk 1]
```diff
@@ -85,6 +85,20 @@ export default class LinkProvider implements vscode.DocumentLinkProvider {
 			} catch (e) {
 				// noop
 			}
+			if (match[5]) {
+				const imagePre = match[3];
+				const imageLink = match[5];
+				const imageOffset = (match.index || 0) + imagePre.length + 1;
```
Comment (mjbvz) [inline extensions/markdown-language-features/src/features/documentLinkProvider.ts]: I agree that you can refactor out this logic. I'd create a function that either returns a `DocumentLink` or `undefined` (if an exception was thrown)

**Review by mjbvz — CHANGES_REQUESTED** [review]
Thanks for taking a look! Changes look good, just a few tweaks.

Let me know if you have any questions about my comments or the code

**Comment by mjbvz** [comment]
Thanks! This change will be in the next VS Code insiders build and is scheduled to be included in VS Code 1.31

**Comment by flurmbo** [comment]
Awesome, thanks for the fast response
