### PR TITLE
Make link text regexp non-greedy

### LINKED ISSUE #163081: Notification command links parsing broken when multiple links are present
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.0
- OS Version: Windows 10 Pro, 21H2, build: 19044.2075

<br>

Command links inside notifications were implemented as described here, [v1.34](https://code.visualstudio.com/updates/v1_34#_command-links-in-notifications) or here #46571, i.e.

>This is now possible using the following syntax: `[link name](command:<command id> "Title")`

_Originally posted by @bpasero in https://github.com/microsoft/vscode/issues/46571#issuecomment-482485207_

The feature works great when a single command link is added to a notification but fails when two (or more) are present, see the sample code below (2).

<br>

Steps to Reproduce:

1. Create a new blank extension (JS/TS)
2. Add the following code to your extension's main entrypoint/command:

```js
vscode.window.showInformationMessage(
  'Lorem ipsum [Test A](command:ext.doSomething "First title") or [Test B](command:ext.doSomethingElse "Second title").'
)
```

Expected behavior is to see the notification with 2 command links and their titles but the following is rendered instead:

<p align="center">
 notification-command
</p>

Note: the provided commands `ext.doSomething` and `ext.doSomethingElse` should be valid and registered for the commands links to work when actually being clicked but that is irrelevant and out of scope for the issue.

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #163081

### CODE REVIEW

File: src/vs/base/common/linkedText.ts [hunk 1]
```diff
@@ -23,7 +23,7 @@ export class LinkedText {
 	}
 }
 
-const LINK_REGEX = /\[([^\]]+)\]\(((?:https?:\/\/|command:|file:)[^\)\s]+)(?: ("|')([^\3]+)(\3))?\)/gi;
+const LINK_REGEX = /\[([^\]]+)\]\(((?:https?:\/\/|command:|file:)[^\)\s]+)(?: (["'])(.+?)(\3))?\)/gi;
```
Comment (mjbvz) [inline src/vs/base/common/linkedText.ts:26]: I don't think references such as `\3` work inside of character groups. It is also not required here anyways

**Review by aeschli — APPROVED** [review]
