### PR TITLE
Action lgtm.io alerts in terminal

### LINKED ISSUE #159616: Profile quick pick quote formatting is not working
Found this via lgtm.io

Repro:

Create a profile with quotes in `args`:

```json
  "terminal.integrated.profiles.windows": {
    "Command Prompt": {
      "path": [
        "${env:windir}\\Sysnative\\cmd.exe",
        "${env:windir}\\System32\\cmd.exe"
      ],
      "args": ["abc \" def \""],
      "icon": "terminal-cmd"
    }
```

It should show `\"` around `def`:

image

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #159616

### CODE REVIEW

File: src/vs/platform/terminal/common/terminalProfiles.ts [hunk 1]
```diff
@@ -93,8 +93,8 @@ export function terminalIconsEqual(iconOne?: TerminalIcon, iconTwo?: TerminalIco
 	if (ThemeIcon.isThemeIcon(iconOne) && ThemeIcon.isThemeIcon(iconTwo)) {
 		return iconOne.id === iconTwo.id && iconOne.color === iconTwo.color;
 	}
```
Comment (meganrogge) [inline src/vs/platform/terminal/common/terminalProfiles.ts:95]: I think this monstrosity was my doing, but we could go with `a` and `b` instead of `iconOne` and `iconTwo` all over the place since the context IE `terminalIconsEqual` makes it clear what we're comparing already.

**Review by meganrogge — APPROVED** [review]

File: src/vs/platform/terminal/common/terminalProfiles.ts (hunk 1 above)
Comment (Tyriar) [reply src/vs/platform/terminal/common/terminalProfiles.ts:95]: https://github.com/microsoft/vscode/pull/159667
